/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.DivisionSplitting
import InverseGalois.CFT.Brauer.DivisionTeichmuller

/-!
# The unramified splitting field of a division algebra over a local field is Galois

The subfield of a division algebra over a nonarchimedean local field generated by a lift of a
generator of the residue ring is generated by a root of unity whose order is the number of nonzero
residues.  A field generated over its base field by a primitive root of unity is a cyclotomic
extension of it, and a cyclotomic extension is Galois.  So the splitting field produced by the
residue argument is a Galois extension of the base field, of degree the square root of the
dimension, carrying only the absolute values of the base field.

## Main results

* `InverseGalois.CFT.adjoin_adjoin_singleton_eq_top`: the subalgebra generated by an element of an
  algebra is generated, over the base field, by that element viewed inside it.
* `InverseGalois.CFT.isGalois_adjoin_rootOfUnity`: **the subfield generated by a primitive root of
  unity is a Galois extension of the base field.**
* `InverseGalois.CFT.exists_galois_unramified_splitting`: **a division algebra over a
  nonarchimedean local field is split by a Galois subfield of degree the square root of the
  dimension which carries only the absolute values of the base field.**

## Tags

division algebra, local field, splitting field, cyclotomic extension, Galois extension, unramified
-/

set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 1000000

universe u

open Module

open scoped TensorProduct

namespace InverseGalois.CFT

/-! ### A subalgebra generated by one element is generated by it -/

section Adjoin

variable {K D : Type u} [Field K] [Ring D] [Algebra K D]

variable (K) in
/-- **The subalgebra generated by an element is generated, over the base field, by that element
viewed inside it.**  Every element of the subalgebra is built from the generator and the scalars by
sums and products, and that construction takes place inside the subalgebra. -/
theorem adjoin_adjoin_singleton_eq_top (x : D) :
    Algebra.adjoin K ({⟨x, Algebra.self_mem_adjoin_singleton K x⟩} :
        Set ↥(Algebra.adjoin K ({x} : Set D))) = ⊤ := by
  refine Algebra.eq_top_iff.2 ?_
  rintro ⟨y, hy⟩
  refine Algebra.adjoin_induction (hx := hy) (fun b hb => ?_) (fun a => ?_)
    (fun b₁ b₂ _ _ hb₁ hb₂ => ?_) (fun b₁ b₂ _ _ hb₁ hb₂ => ?_)
  · rw [Set.mem_singleton_iff] at hb
    subst hb
    exact Algebra.subset_adjoin rfl
  · exact Subalgebra.algebraMap_mem _ a
  · exact Subalgebra.add_mem _ hb₁ hb₂
  · exact Subalgebra.mul_mem _ hb₁ hb₂

end Adjoin

/-! ### The field generated by a root of unity -/

section RootOfUnity

variable {K D : Type u} [Field K] [DivisionRing D] [Algebra K D]

/-- **A subfield generated by a primitive root of unity is a Galois extension of the base
field.**  It is generated by the roots of `X ^ m - 1`, so it is a cyclotomic extension, and a
cyclotomic extension is Galois. -/
theorem isGalois_adjoin_rootOfUnity {ζ : D} {m : ℕ} (hm : m ≠ 0) (hpow : ζ ^ m = 1)
    (hord : ∀ k : ℕ, ζ ^ k = 1 → m ∣ k)
    (hfield : IsField ↥(Algebra.adjoin K ({ζ} : Set D))) :
    letI : Field ↥(Algebra.adjoin K ({ζ} : Set D)) := hfield.toField
    IsGalois K ↥(Algebra.adjoin K ({ζ} : Set D)) := by
  letI : Field ↥(Algebra.adjoin K ({ζ} : Set D)) := hfield.toField
  haveI : NeZero m := ⟨hm⟩
  set ζ' : ↥(Algebra.adjoin K ({ζ} : Set D)) :=
    ⟨ζ, Algebra.self_mem_adjoin_singleton K ζ⟩ with hζ'
  have hpowcoe : ∀ k : ℕ, ((ζ' ^ k : ↥(Algebra.adjoin K ({ζ} : Set D))) : D) = ζ ^ k := by
    intro k
    rw [hζ']
    exact map_pow (Algebra.adjoin K ({ζ} : Set D)).val _ k
  have hprim : IsPrimitiveRoot ζ' m := by
    refine ⟨Subtype.ext ?_, fun k hk => hord k ?_⟩
    · rw [hpowcoe m, hpow, OneMemClass.coe_one]
    · rw [← hpowcoe k, hk, OneMemClass.coe_one]
  have htop : Algebra.adjoin K ({ζ'} : Set ↥(Algebra.adjoin K ({ζ} : Set D))) = ⊤ := by
    rw [hζ']
    exact adjoin_adjoin_singleton_eq_top K ζ
  haveI : IsCyclotomicExtension {m} K ↥(Algebra.adjoin K ({ζ} : Set D)) := by
    refine (IsCyclotomicExtension.iff_adjoin_eq_top {m} K
      ↥(Algebra.adjoin K ({ζ} : Set D))).2 ⟨fun n hn _ => ?_, ?_⟩
    · rw [Set.mem_singleton_iff] at hn
      subst hn
      exact ⟨ζ', hprim⟩
    · refine top_le_iff.1 ?_
      rw [← htop]
      refine Algebra.adjoin_mono ?_
      rintro b hb
      rw [Set.mem_singleton_iff] at hb
      subst hb
      exact ⟨m, rfl, hm, hprim.pow_eq_one⟩
  exact IsCyclotomicExtension.isGalois {m} K ↥(Algebra.adjoin K ({ζ} : Set D))

end RootOfUnity

/-! ### The Galois splitting field of a division algebra over a local field -/

section Local

variable (K D : Type u) [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D] [Algebra.IsCentral K D]

/-- **A division algebra over a nonarchimedean local field is split by a Galois subfield of degree
the square root of the dimension which carries only the absolute values of the base field.**  The
subfield generated by a lift of a generator of the residue ring is generated by a root of unity of
order the number of nonzero residues, so it is a cyclotomic, hence Galois, extension. -/
theorem exists_galois_unramified_splitting {n : ℕ} (hn : n * n = finrank K D) :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (f : L →ₐ[K] D),
      finrank K L = n ∧ IsGalois K L ∧
        (∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K D (f z) = ‖c‖) ∧
        ∃ m : ℕ, Nonempty ((L ⊗[K] D) ≃ₐ[L] Matrix (Fin m) (Fin m) L) := by
  obtain ⟨ζ, hζpow, hζord, hfield, hdim, hval⟩ := exists_rootOfUnity_unramified_generator K D hn
  have hcard : 1 < Nat.card (DivisionResidue K D) := Finite.one_lt_card
  have hm : Nat.card (DivisionResidue K D) - 1 ≠ 0 := by omega
  have hle : Algebra.adjoin K ({ζ} : Set D) ≤
      Subalgebra.centralizer K ((Algebra.adjoin K ({ζ} : Set D) : Subalgebra K D) : Set D) :=
    adjoin_singleton_le_centralizer ζ
  have hsplit := exists_splitting_of_finrank_eq hfield hn hdim hle
  have hgal := isGalois_adjoin_rootOfUnity hm hζpow hζord hfield
  letI : Field ↥(Algebra.adjoin K ({ζ} : Set D)) := hfield.toField
  refine ⟨↥(Algebra.adjoin K ({ζ} : Set D)), inferInstance, inferInstance,
    (Algebra.adjoin K ({ζ} : Set D)).val, hdim, hgal, fun z hz => ?_, hsplit⟩
  exact hval (z : D) z.2 fun h => hz (Subtype.ext h)

end Local

end InverseGalois.CFT
