/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.DivisionGalois

/-!
# The splitting field of a division algebra over a local field is cyclic

A `K`-automorphism of a finite extension `L` of a nonarchimedean local field preserves the spectral
norm, so it preserves the integers of `L` and descends to the residue field.  The descended map is a
ring automorphism of a finite field, and the group of those is cyclic.  If `L` is generated over `K`
by a root of unity whose order is invertible in the residue field, then an automorphism acting
trivially on the residues fixes that root of unity, because a root of unity congruent to one is one;
so the descent is injective and the Galois group of `L` over `K` is cyclic.

Applied to the subfield generated by the Teichmüller lift of a generator of the residue ring of a
division algebra, this says that a division algebra over a nonarchimedean local field is split by a
cyclic extension of degree the square root of its dimension.

## Main definitions

* `InverseGalois.CFT.divisionResidueAut`: the action of the `K`-automorphisms of `L` on the residue
  field of `L`.

## Main results

* `InverseGalois.CFT.eq_one_of_pow_eq_one_of_divisionNorm_sub_lt_one`: **a root of unity congruent
  to one is one**, when its order is invertible.
* `InverseGalois.CFT.isCyclic_ringAut_of_finite`: the ring automorphisms of a finite ring without
  zero divisors form a cyclic group.
* `InverseGalois.CFT.isCyclic_algEquiv_of_rootOfUnity`: **the Galois group of a local field
  generated by a root of unity of invertible order is cyclic.**
* `InverseGalois.CFT.exists_cyclic_unramified_splitting`: **a division algebra over a
  nonarchimedean local field is split by a cyclic extension of degree the square root of the
  dimension which carries only the absolute values of the base field.**

## Tags

division algebra, local field, unramified, cyclic extension, residue field, root of unity
-/

set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 1000000

universe u

open Module

open scoped TensorProduct

namespace InverseGalois.CFT

/-! ### Roots of unity are rigid -/

section Rigid

variable {K D : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D]

/-- The geometric sum `1 + a + ⋯ + a ^ (m-1)` of an integer `a` differs from `m` by a multiple of
`a - 1`. -/
theorem divisionNorm_geomSum_sub_natCast_le {a : D} (ha : divisionNorm K D a ≤ 1) (m : ℕ) :
    divisionNorm K D ((∑ i ∈ Finset.range m, a ^ i) - (m : D)) ≤ divisionNorm K D (a - 1) := by
  classical
  have hai : ∀ i : ℕ, divisionNorm K D (a ^ i) ≤ 1 := fun i => by
    rw [divisionNorm_pow]
    exact pow_le_one₀ (divisionNorm_nonneg _) ha
  have hTeq : (∑ i ∈ Finset.range m, ∑ k ∈ Finset.range i, a ^ k) * (a - 1)
      = (∑ i ∈ Finset.range m, a ^ i) - (m : D) := by
    rw [Finset.sum_mul, Finset.sum_congr rfl fun i _ => geom_sum_mul a i,
      Finset.sum_sub_distrib]
    simp
  have hTle : divisionNorm K D (∑ i ∈ Finset.range m, ∑ k ∈ Finset.range i, a ^ k) ≤ 1 :=
    divisionNorm_sum_le_one _ _ fun i _ => divisionNorm_sum_le_one _ _ fun k _ => hai k
  rw [← hTeq, divisionNorm_mul]
  exact mul_le_of_le_one_left (divisionNorm_nonneg _) hTle

/-- **A root of unity congruent to one is one**, provided its order has absolute value one.  The
geometric sum `1 + a + ⋯ + a ^ (m-1)` is annihilated by `a - 1`, hence vanishes if `a ≠ 1`; but it
differs from `m` by a multiple of `a - 1`, so it has absolute value one. -/
theorem eq_one_of_pow_eq_one_of_divisionNorm_sub_lt_one {a : D} {m : ℕ} (hpow : a ^ m = 1)
    (hm : divisionNorm K D (m : D) = 1) (ha : divisionNorm K D (a - 1) < 1) : a = 1 := by
  classical
  by_contra hne
  have hsub : a - 1 ≠ 0 := sub_ne_zero.2 hne
  have hm0 : m ≠ 0 := by
    rintro rfl
    rw [Nat.cast_zero, divisionNorm_zero] at hm
    exact zero_ne_one hm
  have hanorm : divisionNorm K D a = 1 := by
    have hp : divisionNorm K D a ^ m = 1 := by rw [← divisionNorm_pow, hpow, divisionNorm_one]
    have hnn := divisionNorm_nonneg (K := K) (D := D) a
    rcases lt_trichotomy (divisionNorm K D a) 1 with h | h | h
    · exact absurd hp (ne_of_lt (pow_lt_one₀ hnn h hm0))
    · exact h
    · exact absurd hp (ne_of_gt (one_lt_pow₀ h hm0))
  have hgeom : (∑ i ∈ Finset.range m, a ^ i) * (a - 1) = a ^ m - 1 := geom_sum_mul a m
  have hS0 : (∑ i ∈ Finset.range m, a ^ i) = 0 := by
    have h0 : (∑ i ∈ Finset.range m, a ^ i) * (a - 1) = 0 := by rw [hgeom, hpow, sub_self]
    rcases mul_eq_zero.1 h0 with h | h
    · exact h
    · exact absurd h hsub
  have hSm := divisionNorm_geomSum_sub_natCast_le (K := K) hanorm.le m
  rw [hS0, zero_sub, divisionNorm_neg, hm] at hSm
  exact absurd ha (not_lt.2 hSm)

end Rigid

/-! ### The action on the residue field -/

section Residue

variable {K L : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-- On a finite extension of a nonarchimedean local field the absolute value of the algebra is the
spectral norm. -/
theorem divisionNorm_eq_spectralNorm (y : L) : divisionNorm K L y = spectralNorm K L y := by
  have h := divisionNorm_algHom (K := K) (D := L) (AlgHom.id K L) Nat.one_pos
    (by rw [mul_one]) (fun y => by rw [AlgHom.id_apply, pow_one]) y
  rwa [AlgHom.id_apply] at h

/-- **A `K`-automorphism of a finite extension of a nonarchimedean local field is an isometry.** -/
theorem divisionNorm_algEquiv (σ : L ≃ₐ[K] L) (y : L) :
    divisionNorm K L (σ y) = divisionNorm K L y := by
  rw [divisionNorm_eq_spectralNorm, divisionNorm_eq_spectralNorm, ← spectralNorm_eq_of_equiv σ y]

/-- A `K`-automorphism of `L` restricted to the integers of `L`. -/
noncomputable def divisionIntegersAlgEquiv (σ : L ≃ₐ[K] L) :
    divisionIntegers K L →+* divisionIntegers K L :=
  RingHom.codRestrict (σ.toAlgHom.toRingHom.comp (divisionIntegers K L).subtype)
    (divisionIntegers K L) fun x => by
      have hx : (σ.toAlgHom.toRingHom.comp (divisionIntegers K L).subtype) x = σ (x : L) := rfl
      rw [hx, mem_divisionIntegers, divisionNorm_algEquiv]
      exact mem_divisionIntegers.1 x.2

@[simp]
theorem coe_divisionIntegersAlgEquiv (σ : L ≃ₐ[K] L) (x : divisionIntegers K L) :
    ((divisionIntegersAlgEquiv σ x : divisionIntegers K L) : L) = σ (x : L) := rfl

/-- The map induced on the residue field by a `K`-automorphism of `L`. -/
noncomputable def divisionResidueHom (σ : L ≃ₐ[K] L) :
    DivisionResidue K L →+* DivisionResidue K L :=
  (divisionResidueCon K L).lift
    (((divisionResidueCon K L).mk').comp (divisionIntegersAlgEquiv σ))
    (by
      intro x y h
      rw [RingCon.ker_apply]
      simp only [RingHom.comp_apply, RingCon.coe_mk']
      refine divisionResidue_eq_iff.2 ?_
      rw [coe_divisionIntegersAlgEquiv, coe_divisionIntegersAlgEquiv, ← map_sub,
        divisionNorm_algEquiv]
      exact h)

@[simp]
theorem divisionResidueHom_coe (σ : L ≃ₐ[K] L) (x : divisionIntegers K L) :
    divisionResidueHom σ ((x : divisionIntegers K L) : DivisionResidue K L)
      = ((divisionIntegersAlgEquiv σ x : divisionIntegers K L) : DivisionResidue K L) := rfl

theorem divisionResidueHom_comp (σ τ : L ≃ₐ[K] L) :
    (divisionResidueHom σ).comp (divisionResidueHom τ) = divisionResidueHom (σ * τ) := by
  refine RingHom.ext fun r => ?_
  obtain ⟨x, rfl⟩ := (divisionResidueCon K L).mk'_surjective r
  rw [RingCon.coe_mk']
  simp only [RingHom.comp_apply, divisionResidueHom_coe]
  refine congrArg _ (Subtype.ext ?_)
  rw [coe_divisionIntegersAlgEquiv, coe_divisionIntegersAlgEquiv, coe_divisionIntegersAlgEquiv]
  rfl

theorem divisionResidueHom_one :
    divisionResidueHom (1 : L ≃ₐ[K] L) = RingHom.id (DivisionResidue K L) := by
  refine RingHom.ext fun r => ?_
  obtain ⟨x, rfl⟩ := (divisionResidueCon K L).mk'_surjective r
  rw [RingCon.coe_mk']
  simp only [divisionResidueHom_coe, RingHom.id_apply]
  refine congrArg _ (Subtype.ext ?_)
  rw [coe_divisionIntegersAlgEquiv]
  rfl

variable (K L) in
/-- **The `K`-automorphisms of a finite extension of a nonarchimedean local field act on its
residue field.** -/
noncomputable def divisionResidueAut : (L ≃ₐ[K] L) →* RingAut (DivisionResidue K L) where
  toFun σ := RingEquiv.ofRingHom (divisionResidueHom σ) (divisionResidueHom σ⁻¹)
    (by rw [divisionResidueHom_comp, mul_inv_cancel, divisionResidueHom_one])
    (by rw [divisionResidueHom_comp, inv_mul_cancel, divisionResidueHom_one])
  map_one' := by
    refine RingEquiv.ext fun r => ?_
    exact RingHom.congr_fun (divisionResidueHom_one (K := K) (L := L)) r
  map_mul' σ τ := by
    refine RingEquiv.ext fun r => ?_
    exact (RingHom.congr_fun (divisionResidueHom_comp σ τ) r).symm

theorem divisionResidueAut_coe (σ : L ≃ₐ[K] L) (x : divisionIntegers K L) :
    divisionResidueAut K L σ ((x : divisionIntegers K L) : DivisionResidue K L)
      = ((divisionIntegersAlgEquiv σ x : divisionIntegers K L) : DivisionResidue K L) := rfl

end Residue

/-! ### The automorphisms of a finite field -/

/-- **The ring automorphisms of a finite ring without zero divisors form a cyclic group.**  Such a
ring is a finite field by the theorem of Wedderburn, every ring homomorphism is linear over the
prime field, and the Galois group of a finite field is cyclic. -/
theorem isCyclic_ringAut_of_finite (F : Type*) [Ring F] [IsDomain F] [Finite F] :
    IsCyclic (RingAut F) := by
  classical
  letI : Field F := (Finite.isDomain_to_isField F).toField
  obtain ⟨p, hp⟩ := CharP.exists F
  haveI : CharP F p := hp
  haveI : Fact p.Prime := ⟨CharP.char_is_prime F p⟩
  letI : Algebra (ZMod p) F := ZMod.algebra F p
  refine isCyclic_of_surjective
    (MonoidHom.mk' (fun σ : F ≃ₐ[ZMod p] F => σ.toRingEquiv) fun _ _ => rfl) ?_
  intro g
  refine ⟨AlgEquiv.ofRingEquiv (f := g) fun x => ?_, rfl⟩
  exact congrArg (fun f : ZMod p →+* F => f x)
    (Subsingleton.elim (g.toRingHom.comp (algebraMap (ZMod p) F)) (algebraMap (ZMod p) F))

/-! ### The Galois group of an unramified extension -/

section Cyclic

variable {K L : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **A `K`-automorphism of `L` acting trivially on the residue field is trivial**, when `L` is
generated over `K` by a root of unity of order invertible in the residue field. -/
theorem divisionResidueAut_injective {ζ : L} {m : ℕ} (hpow : ζ ^ m = 1)
    (hm : ‖((m : ℕ) : K)‖ = 1) (htop : Algebra.adjoin K ({ζ} : Set L) = ⊤) :
    Function.Injective (divisionResidueAut K L) := by
  have hmL : divisionNorm K L ((m : ℕ) : L) = 1 := by
    rw [show (((m : ℕ)) : L) = algebraMap K L ((m : ℕ) : K) by rw [map_natCast],
      divisionNorm_algebraMap]
    exact hm
  have hm0 : m ≠ 0 := by
    rintro rfl
    rw [Nat.cast_zero, norm_zero] at hm
    exact zero_ne_one hm
  have h1 : divisionNorm K L ζ = 1 := by
    have hp : divisionNorm K L ζ ^ m = 1 := by rw [← divisionNorm_pow, hpow, divisionNorm_one]
    have hnn := divisionNorm_nonneg (K := K) (D := L) ζ
    rcases lt_trichotomy (divisionNorm K L ζ) 1 with h | h | h
    · exact absurd hp (ne_of_lt (pow_lt_one₀ hnn h hm0))
    · exact h
    · exact absurd hp (ne_of_gt (one_lt_pow₀ h hm0))
  have hζ0 : ζ ≠ 0 := by
    rintro rfl
    rw [divisionNorm_zero] at h1
    exact zero_ne_one h1
  have hζO : ζ ∈ divisionIntegers K L := mem_divisionIntegers.2 h1.le
  refine (injective_iff_map_eq_one _).2 fun σ hσ => ?_
  have hres : ((divisionIntegersAlgEquiv σ ⟨ζ, hζO⟩ : divisionIntegers K L) :
      DivisionResidue K L) = ((⟨ζ, hζO⟩ : divisionIntegers K L) : DivisionResidue K L) :=
    congrArg (fun e : RingAut (DivisionResidue K L) =>
      e ((⟨ζ, hζO⟩ : divisionIntegers K L) : DivisionResidue K L)) hσ
  have hlt : divisionNorm K L (σ ζ - ζ) < 1 := divisionResidue_eq_iff.1 hres
  have hapow : (σ ζ * ζ⁻¹) ^ m = 1 := by
    have hp1 : (σ ζ) ^ m = 1 := by rw [← map_pow, hpow, map_one]
    have hp2 : (ζ⁻¹) ^ m = 1 := by rw [inv_pow, hpow, inv_one]
    rw [mul_pow, hp1, hp2, one_mul]
  have hasub : σ ζ * ζ⁻¹ - 1 = (σ ζ - ζ) * ζ⁻¹ := by
    rw [sub_mul, mul_inv_cancel₀ hζ0]
  have halt : divisionNorm K L (σ ζ * ζ⁻¹ - 1) < 1 := by
    rw [hasub, divisionNorm_mul, divisionNorm_inv, h1, inv_one, mul_one]
    exact hlt
  have hone := eq_one_of_pow_eq_one_of_divisionNorm_sub_lt_one hapow hmL halt
  have hσζ : σ ζ = ζ := by
    have h : σ ζ * ζ⁻¹ * ζ = 1 * ζ := by rw [hone]
    rwa [mul_assoc, inv_mul_cancel₀ hζ0, mul_one, one_mul] at h
  have hid : σ.toAlgHom = AlgHom.id K L :=
    AlgHom.ext_of_adjoin_eq_top htop fun x hx => by
      rw [Set.mem_singleton_iff] at hx
      subst hx
      simpa using hσζ
  refine AlgEquiv.ext fun x => ?_
  simpa using AlgHom.congr_fun hid x

/-- **The Galois group of a finite extension of a nonarchimedean local field generated by a root of
unity of invertible order is cyclic.**  Such an extension acts faithfully on its residue field,
which is a finite field. -/
theorem isCyclic_algEquiv_of_rootOfUnity {ζ : L} {m : ℕ} (hpow : ζ ^ m = 1)
    (hm : ‖((m : ℕ) : K)‖ = 1) (htop : Algebra.adjoin K ({ζ} : Set L) = ⊤) :
    IsCyclic (L ≃ₐ[K] L) := by
  haveI := isCyclic_ringAut_of_finite (DivisionResidue K L)
  exact isCyclic_of_surjective _
    (MonoidHom.ofInjective (divisionResidueAut_injective hpow hm htop)).symm.surjective

end Cyclic

/-! ### The cyclic splitting field of a division algebra over a local field -/

section Local

variable (K D : Type u) [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D] [Algebra.IsCentral K D]

omit [Algebra.IsCentral K D] in
/-- The number of residues of a division algebra over a nonarchimedean local field is one more than
a natural number of absolute value one in the base field. -/
theorem norm_natCast_card_divisionResidue_sub_one :
    ‖((Nat.card (DivisionResidue K D) - 1 : ℕ) : K)‖ = 1 := by
  have hcard : 1 < Nat.card (DivisionResidue K D) := Finite.one_lt_card
  have hQ : divisionNorm K D ((Nat.card (DivisionResidue K D) : ℕ) : D) < 1 :=
    divisionNorm_natCard_divisionResidue_lt_one K D
  rw [show (((Nat.card (DivisionResidue K D) : ℕ)) : D)
      = algebraMap K D ((Nat.card (DivisionResidue K D) : ℕ) : K) by rw [map_natCast],
    divisionNorm_algebraMap] at hQ
  have hcast : ((Nat.card (DivisionResidue K D) - 1 : ℕ) : K)
      = ((Nat.card (DivisionResidue K D) : ℕ) : K) + (-1 : K) := by
    rw [Nat.cast_sub (by omega)]
    push_cast
    ring
  rw [hcast, IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm (by simp [hQ.ne])]
  simp [hQ.le]

/-- **A division algebra over a nonarchimedean local field is split by a cyclic extension of degree
the square root of the dimension which carries only the absolute values of the base field.**  The
subfield generated by a root of unity lifting a generator of the residues has that degree and is a
cyclotomic, hence Galois, extension; and it acts faithfully on the residues, so its Galois group is
cyclic. -/
theorem exists_cyclic_unramified_splitting {n : ℕ} (hn : n * n = finrank K D) :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (f : L →ₐ[K] D),
      finrank K L = n ∧ IsGalois K L ∧ IsCyclic (L ≃ₐ[K] L) ∧
        (∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K D (f z) = ‖c‖) ∧
        ∃ m : ℕ, Nonempty ((L ⊗[K] D) ≃ₐ[L] Matrix (Fin m) (Fin m) L) := by
  obtain ⟨ζ, hζpow, hζord, hfield, hdim, hval⟩ := exists_rootOfUnity_unramified_generator K D hn
  have hcard : 1 < Nat.card (DivisionResidue K D) := Finite.one_lt_card
  have hm : Nat.card (DivisionResidue K D) - 1 ≠ 0 := by omega
  have hle : Algebra.adjoin K ({ζ} : Set D) ≤
      Subalgebra.centralizer K ((Algebra.adjoin K ({ζ} : Set D) : Subalgebra K D) : Set D) :=
    adjoin_singleton_le_centralizer ζ
  have hsplit := exists_splitting_of_finrank_eq hfield hn hdim hle
  have hgal := isGalois_adjoin_rootOfUnity hm hζpow hζord hfield
  letI : Field ↥(Algebra.adjoin K ({ζ} : Set D)) := hfield.toField
  have hζ' : (⟨ζ, Algebra.self_mem_adjoin_singleton K ζ⟩ :
      ↥(Algebra.adjoin K ({ζ} : Set D))) ^ (Nat.card (DivisionResidue K D) - 1) = 1 := by
    refine Subtype.ext ?_
    rw [show (((⟨ζ, Algebra.self_mem_adjoin_singleton K ζ⟩ :
        ↥(Algebra.adjoin K ({ζ} : Set D))) ^ (Nat.card (DivisionResidue K D) - 1) :
          ↥(Algebra.adjoin K ({ζ} : Set D))) : D)
        = ζ ^ (Nat.card (DivisionResidue K D) - 1) from
      map_pow (Algebra.adjoin K ({ζ} : Set D)).val _ _, hζpow, OneMemClass.coe_one]
  have hcyc := isCyclic_algEquiv_of_rootOfUnity hζ'
    (norm_natCast_card_divisionResidue_sub_one K D)
    (adjoin_adjoin_singleton_eq_top K ζ)
  refine ⟨↥(Algebra.adjoin K ({ζ} : Set D)), inferInstance, inferInstance,
    (Algebra.adjoin K ({ζ} : Set D)).val, hdim, hgal, hcyc, fun z hz => ?_, hsplit⟩
  exact hval (z : D) z.2 fun h => hz (Subtype.ext h)

end Local

end InverseGalois.CFT
