/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.DivisionValueGroup

/-!
# An unramified maximal subfield of a division algebra over a local field

Let `D` be a division algebra of dimension `n ^ 2` over a nonarchimedean local field `K`, let `ϖ` be
a uniformizer of `D` and write `ρ` for its absolute value, so that the absolute values of the
nonzero elements of `D` are the integer powers of `ρ`.  Let `L` be a subfield of `D` and suppose
that every integer of `D` is congruent modulo the elements of absolute value less than one to an
element of `L`.  If `L` contains an element of absolute value `ρ ^ m` with `m` positive, then

  `D = L + L ϖ + ⋯ + L ϖ ^ (m - 1)`.

Indeed one clears the coefficients of an integer of `D` one power of `ϖ` at a time, reaching an
error of absolute value `ρ ^ m`, and then repeats after dividing by the chosen element of `L`,
which is legitimate because the right-hand side is a left `L`-module.  The errors tend to zero and a
subspace of `D` is closed, so the two sides agree on the integers, and every element of `D` is an
integer after multiplication by a scalar.  Comparing dimensions gives `n ^ 2 ≤ m ⬝ [L : K]`.

Applied to the subfield generated by an element whose powers exhaust the residues, and to the
element `π` of `K`, this forces `[L : K] = n` and shows that `π` already has the smallest positive
exponent occurring in `L`.  So `L` is a maximal subfield of `D` whose absolute values are exactly
the absolute values of the scalars: it is unramified over `K`.

## Main definitions

* `InverseGalois.CFT.uniformizerCombination`: the map `(z_t) ↦ ∑ z_t ϖ ^ t`.

## Main results

* `InverseGalois.CFT.finrank_le_mul_of_divisionNorm_eq_pow`: the dimension bound
  `n ^ 2 ≤ m ⬝ [L : K]`.
* `InverseGalois.CFT.exists_unramified_generator`: **a division algebra over a nonarchimedean local
  field has an unramified maximal subfield generated by one element.**

## Tags

division algebra, local field, maximal subfield, unramified, ramification
-/

set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 1000000

universe u

open Module

namespace InverseGalois.CFT

/-! ### Combinations of powers of a uniformizer -/

section Combination

variable {K D : Type u} [Field K] [DivisionRing D] [Algebra K D]

variable (K) in
/-- The `K`-linear map sending a family `(z t)` of elements of a subalgebra `L` to the combination
`∑ z t ⬝ ϖ ^ t`, with the coefficients on the left and the powers of `ϖ` on the right. -/
noncomputable def uniformizerCombination (L : Subalgebra K D) (ϖ : D) (m : ℕ) :
    (Fin m → L) →ₗ[K] D where
  toFun c := ∑ t : Fin m, (c t : D) * ϖ ^ (t : ℕ)
  map_add' a b := by simp [add_mul, Finset.sum_add_distrib]
  map_smul' r a := by simp [Finset.smul_sum]

theorem uniformizerCombination_apply (L : Subalgebra K D) (ϖ : D) (m : ℕ) (c : Fin m → L) :
    uniformizerCombination K L ϖ m c = ∑ t : Fin m, (c t : D) * ϖ ^ (t : ℕ) := rfl

/-- Each single term `z ⬝ ϖ ^ k` with `k < m` is a combination of powers of `ϖ`. -/
theorem mul_pow_mem_range (L : Subalgebra K D) (ϖ : D) {m : ℕ} (z : L) {k : ℕ} (hk : k < m) :
    (z : D) * ϖ ^ k ∈ LinearMap.range (uniformizerCombination K L ϖ m) := by
  classical
  refine ⟨fun t => if t = (⟨k, hk⟩ : Fin m) then z else 0, ?_⟩
  rw [uniformizerCombination_apply]
  rw [Finset.sum_eq_single (⟨k, hk⟩ : Fin m)]
  · simp
  · intro b _ hb
    simp [hb]
  · intro h
    exact absurd (Finset.mem_univ (⟨k, hk⟩ : Fin m)) h

/-- The combinations of powers of `ϖ` form a left module over the subalgebra. -/
theorem mul_mem_range {L : Subalgebra K D} {ϖ : D} {m : ℕ} (w : L) {v : D}
    (hv : v ∈ LinearMap.range (uniformizerCombination K L ϖ m)) :
    (w : D) * v ∈ LinearMap.range (uniformizerCombination K L ϖ m) := by
  obtain ⟨c, rfl⟩ := hv
  refine ⟨fun t => w * c t, ?_⟩
  rw [uniformizerCombination_apply, uniformizerCombination_apply, Finset.mul_sum]
  refine Finset.sum_congr rfl fun t _ => ?_
  push_cast
  rw [mul_assoc]

variable [FiniteDimensional K D]

/-- The combinations of powers of `ϖ` span a space of dimension at most `m ⬝ [L : K]`. -/
theorem finrank_range_uniformizerCombination_le (L : Subalgebra K D) (ϖ : D) (m : ℕ) :
    finrank K ↥(LinearMap.range (uniformizerCombination K L ϖ m)) ≤ m * finrank K ↥L := by
  have h := LinearMap.finrank_range_le (uniformizerCombination K L ϖ m)
  have hpi : finrank K (Fin m → ↥L) = m * finrank K ↥L := by
    rw [Module.finrank_pi_fintype K]
    simp
  rwa [hpi] at h

end Combination

/-! ### Successive approximation -/

section Approximation

variable {K D : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D]

omit [IsUltrametricDist K] [ProperSpace K] in
/-- **Clearing the coefficients one power of a uniformizer at a time.**  An integer of `D` is
approximated to within `ρ ^ k` by a combination of the first `m` powers of `ϖ`, for every `k` at
most `m`: at each stage the error is divided by `ϖ ^ k`, replaced by a representative from `L`, and
multiplied back. -/
theorem exists_mem_range_divisionNorm_sub_le {ϖ : D} (hϖ : IsDivisionUniformizer K D ϖ)
    {L : Subalgebra K D}
    (hcov : ∀ x : D, divisionNorm K D x ≤ 1 → ∃ z : L, divisionNorm K D (x - (z : D)) < 1)
    (m : ℕ) : ∀ k : ℕ, k ≤ m → ∀ x : D, divisionNorm K D x ≤ 1 →
      ∃ v ∈ LinearMap.range (uniformizerCombination K L ϖ m),
        divisionNorm K D (x - v) ≤ divisionNorm K D ϖ ^ k := by
  intro k
  induction k with
  | zero =>
    intro _ x hx
    exact ⟨0, Submodule.zero_mem _, by simpa using hx⟩
  | succ k ih =>
    intro hkm x hx
    obtain ⟨v, hv, hvle⟩ := ih (by omega) x hx
    have hρpos : 0 < divisionNorm K D ϖ := hϖ.norm_pos
    have hρ1 : divisionNorm K D ϖ < 1 := hϖ.norm_lt_one
    have hϖ0 : ϖ ≠ 0 := hϖ.ne_zero
    have hwn : divisionNorm K D ((x - v) * ϖ ^ (-(k : ℤ)))
        = divisionNorm K D (x - v) / divisionNorm K D ϖ ^ k := by
      rw [divisionNorm_mul, divisionNorm_zpow, zpow_neg, zpow_natCast, div_eq_mul_inv]
    have hwle : divisionNorm K D ((x - v) * ϖ ^ (-(k : ℤ))) ≤ 1 := by
      rw [hwn, div_le_one (by positivity)]
      exact hvle
    obtain ⟨z, hz⟩ := hcov _ hwle
    refine ⟨v + (z : D) * ϖ ^ k, Submodule.add_mem _ hv (mul_pow_mem_range L ϖ z (by omega)), ?_⟩
    have hwmul : (x - v) * ϖ ^ (-(k : ℤ)) * ϖ ^ k = x - v := by
      rw [mul_assoc, ← zpow_natCast ϖ k, ← zpow_add₀ hϖ0]
      simp
    have hkey : x - (v + (z : D) * ϖ ^ k)
        = ((x - v) * ϖ ^ (-(k : ℤ)) - (z : D)) * ϖ ^ k := by
      rw [sub_mul, hwmul]
      abel
    have hnormkey : divisionNorm K D (x - (v + (z : D) * ϖ ^ k))
        = divisionNorm K D ((x - v) * ϖ ^ (-(k : ℤ)) - (z : D)) * divisionNorm K D ϖ ^ k := by
      rw [hkey, divisionNorm_mul, divisionNorm_pow]
    have hlt : divisionNorm K D (x - (v + (z : D) * ϖ ^ k)) < divisionNorm K D ϖ ^ k := by
      rw [hnormkey]
      have hpk : (0 : ℝ) < divisionNorm K D ϖ ^ k := by positivity
      calc divisionNorm K D ((x - v) * ϖ ^ (-(k : ℤ)) - (z : D)) * divisionNorm K D ϖ ^ k
          < 1 * divisionNorm K D ϖ ^ k := mul_lt_mul_of_pos_right hz hpk
        _ = divisionNorm K D ϖ ^ k := one_mul _
    rcases eq_or_ne (x - (v + (z : D) * ϖ ^ k)) 0 with hzero | hnz
    · rw [hzero, divisionNorm_zero]
      positivity
    · obtain ⟨j, hj⟩ := hϖ.exists_zpow hnz
      rw [hj] at hlt ⊢
      rw [← zpow_natCast (divisionNorm K D ϖ) k] at hlt
      rw [← zpow_natCast (divisionNorm K D ϖ) (k + 1)]
      have hkj : ((k : ℤ)) < j := by
        by_contra hcon
        push_neg at hcon
        have h6 : divisionNorm K D ϖ ^ (k : ℤ) ≤ divisionNorm K D ϖ ^ j :=
          zpow_le_zpow_right_of_le_one₀ hρpos hρ1.le hcon
        linarith
      refine zpow_le_zpow_right_of_le_one₀ hρpos hρ1.le ?_
      push_cast
      omega

omit [IsUltrametricDist K] [ProperSpace K] in
/-- **Iterating the approximation.**  Once every integer of `D` is approximated to within the
absolute value of an element `ϖL` of `L` by a combination of powers of `ϖ`, the error can be divided
by `ϖL` and the process repeated, because the combinations form a left `L`-module. -/
theorem exists_mem_range_divisionNorm_sub_le_pow {ϖ : D} {L : Subalgebra K D} {m : ℕ} {ϖL : L}
    (hbase : ∀ x : D, divisionNorm K D x ≤ 1 →
      ∃ v ∈ LinearMap.range (uniformizerCombination K L ϖ m),
        divisionNorm K D (x - v) ≤ divisionNorm K D (ϖL : D))
    (hne : (ϖL : D) ≠ 0) : ∀ N : ℕ, ∀ x : D, divisionNorm K D x ≤ 1 →
      ∃ v ∈ LinearMap.range (uniformizerCombination K L ϖ m),
        divisionNorm K D (x - v) ≤ divisionNorm K D (ϖL : D) ^ N := by
  intro N
  induction N with
  | zero =>
    intro x hx
    exact ⟨0, Submodule.zero_mem _, by simpa using hx⟩
  | succ N ih =>
    intro x hx
    obtain ⟨v₀, hv₀, hle₀⟩ := hbase x hx
    have hσpos : 0 < divisionNorm K D (ϖL : D) := divisionNorm_pos hne
    have hun : divisionNorm K D ((ϖL : D)⁻¹ * (x - v₀))
        = divisionNorm K D (x - v₀) / divisionNorm K D (ϖL : D) := by
      rw [divisionNorm_mul, divisionNorm_inv, div_eq_inv_mul]
    have hule : divisionNorm K D ((ϖL : D)⁻¹ * (x - v₀)) ≤ 1 := by
      rw [hun, div_le_one hσpos]
      exact hle₀
    obtain ⟨v₁, hv₁, hle₁⟩ := ih _ hule
    refine ⟨v₀ + (ϖL : D) * v₁, Submodule.add_mem _ hv₀ (mul_mem_range ϖL hv₁), ?_⟩
    have hkey : x - (v₀ + (ϖL : D) * v₁)
        = (ϖL : D) * ((ϖL : D)⁻¹ * (x - v₀) - v₁) := by
      rw [mul_sub, ← mul_assoc, mul_inv_cancel₀ hne, one_mul]
      abel
    rw [hkey, divisionNorm_mul, pow_succ]
    calc divisionNorm K D (ϖL : D) * divisionNorm K D ((ϖL : D)⁻¹ * (x - v₀) - v₁)
        ≤ divisionNorm K D (ϖL : D) * divisionNorm K D (ϖL : D) ^ N :=
          mul_le_mul_of_nonneg_left hle₁ hσpos.le
      _ = divisionNorm K D (ϖL : D) ^ N * divisionNorm K D (ϖL : D) := by ring

end Approximation

/-! ### The dimension bound -/

section Bound

variable {K D : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D]

/-- **A subfield whose residues exhaust those of `D` and which contains an element of absolute
value `ρ ^ m` spans `D` together with the first `m` powers of a uniformizer.**  Hence the dimension
of `D` is at most `m` times the degree of the subfield. -/
theorem finrank_le_mul_of_divisionNorm_eq_pow {ϖ : D} (hϖ : IsDivisionUniformizer K D ϖ) {π : K}
    (hπ : IsNormUniformizer π) {L : Subalgebra K D}
    (hcov : ∀ x : D, divisionNorm K D x ≤ 1 → ∃ z : L, divisionNorm K D (x - (z : D)) < 1)
    {m : ℕ} (hm : 0 < m) {ϖL : L} (hne : (ϖL : D) ≠ 0)
    (hnorm : divisionNorm K D (ϖL : D) = divisionNorm K D ϖ ^ m) :
    finrank K D ≤ m * finrank K ↥L := by
  classical
  have hbase : ∀ x : D, divisionNorm K D x ≤ 1 →
      ∃ v ∈ LinearMap.range (uniformizerCombination K L ϖ m),
        divisionNorm K D (x - v) ≤ divisionNorm K D (ϖL : D) := by
    intro x hx
    obtain ⟨v, hv, hle⟩ := exists_mem_range_divisionNorm_sub_le hϖ hcov m m le_rfl x hx
    exact ⟨v, hv, by rw [hnorm]; exact hle⟩
  have hiter := exists_mem_range_divisionNorm_sub_le_pow hbase hne
  have hσ1 : divisionNorm K D (ϖL : D) < 1 := by
    rw [hnorm]
    exact pow_lt_one₀ hϖ.norm_pos.le hϖ.norm_lt_one hm.ne'
  have hint : ∀ x : D, divisionNorm K D x ≤ 1 →
      x ∈ LinearMap.range (uniformizerCombination K L ϖ m) := by
    intro x hx
    refine mem_of_forall_exists_divisionNorm_sub_lt K D _ fun ε hε => ?_
    obtain ⟨N, hN⟩ := exists_pow_lt_of_lt_one hε hσ1
    obtain ⟨v, hv, hle⟩ := hiter N x hx
    exact ⟨v, hv, lt_of_le_of_lt hle hN⟩
  have htop : LinearMap.range (uniformizerCombination K L ϖ m) = ⊤ := by
    refine eq_top_iff.2 fun x _ => ?_
    rcases eq_or_ne x 0 with rfl | hx0
    · exact Submodule.zero_mem _
    · have hxpos : 0 < divisionNorm K D x := divisionNorm_pos hx0
      obtain ⟨N, hN⟩ := exists_pow_lt_of_lt_one (inv_pos.2 hxpos) hπ.norm_lt_one
      have hscale : divisionNorm K D ((π ^ N) • x) ≤ 1 := by
        rw [Algebra.smul_def, divisionNorm_mul, divisionNorm_algebraMap, norm_pow]
        have hinv : (divisionNorm K D x)⁻¹ * divisionNorm K D x = 1 :=
          inv_mul_cancel₀ hxpos.ne'
        have h5 := mul_lt_mul_of_pos_right hN hxpos
        rw [hinv] at h5
        linarith
      have hmem := hint _ hscale
      have hx : x = ((π ^ N)⁻¹) • ((π ^ N) • x) := by
        rw [smul_smul, inv_mul_cancel₀ (pow_ne_zero N hπ.ne_zero), one_smul]
      rw [hx]
      exact Submodule.smul_mem _ _ hmem
  rw [← finrank_top K D, ← htop]
  exact finrank_range_uniformizerCombination_le L ϖ m

end Bound

/-! ### The unramified maximal subfield -/

section Maximal

variable {K D : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [DivisionRing D] [Algebra K D] [FiniteDimensional K D]

/-- **A subfield of `D` whose residues exhaust those of `D` has degree `n` and is unramified.**  The
dimension bound applied to a uniformizer of the base field already forces the degree to be `n`, and
applied to an element realizing a smaller exponent it would force that exponent to be at least `n`,
which is impossible.  So the absolute values of the nonzero elements of the subfield are exactly
those of the nonzero scalars. -/
theorem finrank_eq_and_exists_norm_eq_of_cover [Algebra.IsCentral K D] {n : ℕ}
    (hn : n * n = finrank K D) {L : Subalgebra K D} (hdn : finrank K ↥L ≤ n)
    (hcov : ∀ x : D, divisionNorm K D x ≤ 1 → ∃ z : L, divisionNorm K D (x - (z : D)) < 1) :
    finrank K ↥L = n ∧
      ∀ z : D, z ∈ L → z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K D z = ‖c‖ := by
  classical
  obtain ⟨π, hπ⟩ := exists_isNormUniformizer K
  obtain ⟨ϖ, hϖ⟩ := exists_isDivisionUniformizer K D hπ hn
  obtain ⟨e, he0, hee⟩ := IsDivisionUniformizer.exists_pow_eq_norm K D hϖ hπ
  have hen : e ≤ n := IsDivisionUniformizer.ramification_le K D hϖ hπ hn he0 hee
  have hρpos : 0 < divisionNorm K D ϖ := hϖ.norm_pos
  have hnpos : 0 < n := by
    have hpos : 0 < finrank K D := Module.finrank_pos
    rw [← hn] at hpos
    rcases Nat.eq_zero_or_pos n with rfl | h
    · simp at hpos
    · exact h
  -- every positive exponent realized inside `L` is at least `n`
  have hkey : ∀ (m : ℕ) (z : L), 0 < m → (z : D) ≠ 0 →
      divisionNorm K D (z : D) = divisionNorm K D ϖ ^ m → n ≤ m := by
    intro m z hm hz hzn
    have hb := finrank_le_mul_of_divisionNorm_eq_pow hϖ hπ hcov hm hz hzn
    rw [← hn] at hb
    have h1 : m * finrank K ↥L ≤ m * n := Nat.mul_le_mul_left m hdn
    exact Nat.le_of_mul_le_mul_right (le_trans hb h1) hnpos
  -- the scalar `π` realizes the exponent `e`
  have hπne : ((⟨algebraMap K D π, L.algebraMap_mem π⟩ : L) : D) ≠ 0 := by
    show algebraMap K D π ≠ 0
    exact fun h => hπ.ne_zero ((algebraMap K D).injective (h.trans (map_zero _).symm))
  have hπnorm : divisionNorm K D ((⟨algebraMap K D π, L.algebraMap_mem π⟩ : L) : D)
      = divisionNorm K D ϖ ^ e := by
    show divisionNorm K D (algebraMap K D π) = divisionNorm K D ϖ ^ e
    rw [divisionNorm_algebraMap, hee]
  have heqn : e = n := le_antisymm hen (hkey e _ he0 hπne hπnorm)
  have hdim : finrank K ↥L = n := by
    have hb := finrank_le_mul_of_divisionNorm_eq_pow hϖ hπ hcov he0 hπne hπnorm
    rw [← hn, heqn] at hb
    exact le_antisymm hdn (Nat.le_of_mul_le_mul_left hb hnpos)
  refine ⟨hdim, ?_⟩
  intro z hzmem hz0
  obtain ⟨j, hj⟩ := hϖ.exists_zpow hz0
  have hnZ : (0 : ℤ) < (n : ℤ) := by exact_mod_cast hnpos
  have hjs : j = (n : ℤ) * (j / (n : ℤ)) + j % (n : ℤ) := (Int.mul_ediv_add_emod j (n : ℤ)).symm
  set q : ℤ := j / (n : ℤ) with hqdef
  set s : ℤ := j % (n : ℤ) with hsdef
  have hs0 : 0 ≤ s := Int.emod_nonneg j (by omega)
  have hsn : s < (n : ℤ) := Int.emod_lt_of_pos j hnZ
  -- the element `z ⬝ π ^ (-q)` of `L` has absolute value `ρ ^ s`
  have hπzpow : ‖π ^ (-q)‖ = divisionNorm K D ϖ ^ ((n : ℤ) * (-q)) := by
    rw [norm_zpow, ← hee, heqn, ← zpow_natCast (divisionNorm K D ϖ) n, ← zpow_mul]
  have huMem : z * algebraMap K D (π ^ (-q)) ∈ L := mul_mem hzmem (L.algebraMap_mem _)
  have hune : z * algebraMap K D (π ^ (-q)) ≠ 0 := by
    refine mul_ne_zero hz0 ?_
    have hzn : π ^ (-q) ≠ 0 := zpow_ne_zero _ hπ.ne_zero
    exact fun h => hzn ((algebraMap K D).injective (h.trans (map_zero _).symm))
  have hunorm : divisionNorm K D (z * algebraMap K D (π ^ (-q)))
      = divisionNorm K D ϖ ^ s := by
    rw [divisionNorm_mul, hj, divisionNorm_algebraMap, hπzpow, ← zpow_add₀ hρpos.ne']
    congr 1
    linear_combination hjs
  have hs : s = 0 := by
    by_contra hcon
    have hspos : 0 < s := lt_of_le_of_ne hs0 (Ne.symm hcon)
    have hle := hkey s.toNat ⟨_, huMem⟩ (by omega) hune (by
      show divisionNorm K D (z * algebraMap K D (π ^ (-q))) = divisionNorm K D ϖ ^ s.toNat
      rw [hunorm, ← zpow_natCast (divisionNorm K D ϖ) s.toNat]
      congr 1
      omega)
    omega
  have hjq : j = (n : ℤ) * q := by rw [hjs, hs, add_zero]
  refine ⟨π ^ q, zpow_ne_zero _ hπ.ne_zero, ?_⟩
  rw [hj, norm_zpow, ← hee, heqn, ← zpow_natCast (divisionNorm K D ϖ) n, ← zpow_mul, hjq]

variable (K D) in
/-- **A division algebra over a nonarchimedean local field is generated by one element over an
unramified maximal subfield.**  The subfield generated by an element whose powers exhaust the
residues has degree `n` over `K`, and the absolute values of its nonzero elements are exactly the
absolute values of the nonzero scalars. -/
theorem exists_unramified_generator [Algebra.IsCentral K D] {n : ℕ} (hn : n * n = finrank K D) :
    ∃ y : D, IsField ↥(Algebra.adjoin K ({y} : Set D)) ∧
      finrank K ↥(Algebra.adjoin K ({y} : Set D)) = n ∧
      ∀ z : D, z ∈ Algebra.adjoin K ({y} : Set D) → z ≠ 0 →
        ∃ c : K, c ≠ 0 ∧ divisionNorm K D z = ‖c‖ := by
  obtain ⟨y, hy1, hy2⟩ := exists_pow_divisionNorm_sub_lt_one K D
  have hymem : y ∈ Algebra.adjoin K ({y} : Set D) := Algebra.subset_adjoin (Set.mem_singleton y)
  have hdn : finrank K ↥(Algebra.adjoin K ({y} : Set D)) ≤ n := by
    have hsq := finrank_adjoin_singleton_mul_self_le K y
    rw [← hn] at hsq
    by_contra hcon
    push_neg at hcon
    nlinarith
  have hcov : ∀ x : D, divisionNorm K D x ≤ 1 →
      ∃ z : ↥(Algebra.adjoin K ({y} : Set D)), divisionNorm K D (x - (z : D)) < 1 := by
    intro x hx
    rcases lt_or_eq_of_le hx with hlt | heq
    · exact ⟨0, by simpa using hlt⟩
    · obtain ⟨i, hi⟩ := hy2 x heq
      exact ⟨⟨y ^ i, pow_mem hymem i⟩, hi⟩
  obtain ⟨h1, h2⟩ := finrank_eq_and_exists_norm_eq_of_cover hn hdn hcov
  exact ⟨y, isField_adjoin_singleton (K := K) y, h1, h2⟩

end Maximal

end InverseGalois.CFT

