/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.ResidueGalois

/-!
# The Frobenius automorphism of an unramified extension of a local field

An unramified extension of a nonarchimedean local field has an automorphism which raises every
residue to the power given by the number of residues of the base field, and that automorphism
generates the Galois group.  It is moreover the *only* automorphism with that effect on residues:
the extension is generated by a root of unity whose order is invertible in the residue field, and
such an extension acts faithfully on its residue field.

The Frobenius automorphism is therefore a canonical generator of the Galois group, which is what
turns the invariant of a cyclic algebra into a canonically normalised invariant.

## Main definitions

* `InverseGalois.CFT.IsDivisionFrobenius`: the property of raising every residue to the power given
  by the number of residues of the base field.
* `InverseGalois.CFT.divisionFrobenius`: the Frobenius automorphism of an unramified extension.

## Main results

* `InverseGalois.CFT.eq_of_isDivisionFrobenius`: **the Frobenius automorphism is unique.**
* `InverseGalois.CFT.divisionFrobenius_zpowers`: **the Frobenius automorphism generates the Galois
  group.**

## Tags

local field, unramified extension, Frobenius
-/

set_option synthInstance.maxHeartbeats 800000

universe u

namespace InverseGalois.CFT

open Module

variable {K L : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-! ### The Frobenius condition -/

/-- An automorphism of an extension of a nonarchimedean local field is a *Frobenius* automorphism
when it raises every residue to the power given by the number of residues of the base field. -/
def IsDivisionFrobenius (σ : L ≃ₐ[K] L) : Prop :=
  ∀ x : divisionIntegers K L,
    ((divisionIntegersAlgEquiv σ x : divisionIntegers K L) : DivisionResidue K L)
      = ((x : divisionIntegers K L) : DivisionResidue K L) ^ Nat.card (DivisionResidue K K)

variable (K L) in
/-- **An unramified extension of a local field has a Frobenius automorphism, and it generates the
Galois group.** -/
theorem exists_isDivisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    ∃ σ : L ≃ₐ[K] L, Subgroup.zpowers σ = ⊤ ∧ IsDivisionFrobenius σ :=
  exists_frobenius_of_unramified K L hur

/-- **The Frobenius automorphism of an unramified extension of a local field is unique**, because
such an extension acts faithfully on its residue field. -/
theorem eq_of_isDivisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖)
    {σ τ : L ≃ₐ[K] L} (hσ : IsDivisionFrobenius σ) (hτ : IsDivisionFrobenius τ) : σ = τ := by
  obtain ⟨ζ, h1, -, htop⟩ := exists_adjoin_rootOfUnity_eq_top_of_unramified K L hur
  refine divisionResidueAut_injective h1 (norm_natCast_card_divisionResidue_sub_one K L) htop ?_
  refine RingEquiv.ext fun z => ?_
  obtain ⟨x, rfl⟩ := (divisionResidueCon K L).mk'_surjective z
  rw [RingCon.coe_mk', divisionResidueAut_coe, divisionResidueAut_coe, hσ x, hτ x]

/-! ### The Frobenius automorphism -/

variable (K L) in
/-- **The Frobenius automorphism of an unramified extension of a local field**: the unique
automorphism raising every residue to the power given by the number of residues of the base
field. -/
noncomputable def divisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) : L ≃ₐ[K] L :=
  (exists_isDivisionFrobenius K L hur).choose

variable (K L) in
/-- **The Frobenius automorphism generates the Galois group.** -/
theorem divisionFrobenius_zpowers
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    Subgroup.zpowers (divisionFrobenius K L hur) = ⊤ :=
  (exists_isDivisionFrobenius K L hur).choose_spec.1

variable (K L) in
/-- Every automorphism of an unramified extension of a local field is a power of the Frobenius
automorphism. -/
theorem forall_mem_zpowers_divisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) (x : L ≃ₐ[K] L) :
    x ∈ Subgroup.zpowers (divisionFrobenius K L hur) := by
  rw [divisionFrobenius_zpowers K L hur]
  exact Subgroup.mem_top x

variable (K L) in
/-- The Frobenius automorphism raises every residue to the power given by the number of residues of
the base field. -/
theorem isDivisionFrobenius_divisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    IsDivisionFrobenius (divisionFrobenius K L hur) :=
  (exists_isDivisionFrobenius K L hur).choose_spec.2

variable (K L) in
/-- **An automorphism raising every residue to the power given by the number of residues of the base
field is the Frobenius automorphism.** -/
theorem eq_divisionFrobenius
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖)
    {σ : L ≃ₐ[K] L} (hσ : IsDivisionFrobenius σ) : σ = divisionFrobenius K L hur :=
  eq_of_isDivisionFrobenius hur hσ (isDivisionFrobenius_divisionFrobenius K L hur)

end InverseGalois.CFT
