/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.ResidueBaseChange
import InverseGalois.CFT.Brauer.UnramifiedDegree
import InverseGalois.CFT.Local.SubfieldValued

/-!
# The maximal unramified subextension of a finite extension of local fields

A finite extension `M / K` of nonarchimedean local fields whose absolute value extends that of `K`
factors through the subextension generated by the roots of unity: an unramified extension `S / K`
whose degree is the residue degree, followed by an extension `M / S` which does not enlarge the
residue field at all.  This file produces that factorisation together with all the structure that
makes `S` a local field in its own right.

The valuation of `S` is the restriction of the valuation of `M`, taken without renormalisation, so
that the absolute value of `S` extends the absolute value of `K` on the nose and the absolute value
of `M` extends the absolute value of `S` on the nose.  Completeness and local compactness of `S`
then come from the finite dimensionality of `S` over the complete, locally compact field `K`.

## Main results

* `InverseGalois.CFT.exists_valued_of_unramified_tower`: an intermediate field of a finite extension
  of local fields is a local field for the restricted valuation.
* `InverseGalois.CFT.natCard_divisionResidue_top`: the residues of the top intermediate field are
  the residues of the extension.
* `InverseGalois.CFT.exists_maximalUnramified_subextension`: **a finite extension of local fields
  factors through an unramified subextension across which the residue field does not grow.**

## Tags

local field, unramified extension, ramification, residue field, inertia
-/

set_option synthInstance.maxHeartbeats 1600000
set_option maxHeartbeats 1000000

universe u

namespace InverseGalois.CFT

open Module

open scoped Valued WithZero

/-! ### The residues of the top intermediate field -/

section Top

variable {K M : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field M] [Algebra K M] [FiniteDimensional K M]

variable (K M) in
/-- **An extension has as many residues as its top intermediate field**, the two being the same
field with the same absolute value. -/
theorem natCard_divisionResidue_top :
    Nat.card (DivisionResidue K ↥(⊤ : IntermediateField K M))
      = Nat.card (DivisionResidue K M) := by
  haveI : FiniteDimensional K ↥(⊤ : IntermediateField K M) :=
    (IntermediateField.topEquiv (F := K) (E := M)).symm.toLinearEquiv.finiteDimensional
  refine Nat.card_eq_of_bijective _ ⟨divisionResidueTower_injective, ?_⟩
  intro r
  obtain ⟨x, rfl⟩ := (divisionResidueCon K M).mk'_surjective r
  have hx : (⟨(x : M), IntermediateField.mem_top⟩ : ↥(⊤ : IntermediateField K M))
      ∈ divisionIntegers K ↥(⊤ : IntermediateField K M) := by
    have hmem := mem_divisionIntegers.1 x.2
    rw [show ((x : M)) = algebraMap ↥(⊤ : IntermediateField K M) M
      ⟨(x : M), IntermediateField.mem_top⟩ from rfl, divisionNorm_algebraMap_tower] at hmem
    exact mem_divisionIntegers.2 hmem
  refine ⟨((⟨_, hx⟩ : divisionIntegers K ↥(⊤ : IntermediateField K M)) :
    DivisionResidue K ↥(⊤ : IntermediateField K M)), ?_⟩
  rw [divisionResidueTower_coe, RingCon.coe_mk']
  exact congrArg _ (Subtype.ext rfl)

end Top

/-! ### An intermediate field is a local field -/

section Tower

variable {K M S : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
variable [Field M] [Valued M ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation M ℤᵐ⁰)] [CompleteSpace M] [ProperSpace M]
variable [Algebra K M] [FiniteDimensional K M]
variable [Field S] [Algebra K S] [Algebra S M] [IsScalarTower K S M]
variable [FiniteDimensional K S] [FiniteDimensional S M]

omit [CompleteSpace M] [ProperSpace M] in
/-- **An intermediate field of a finite extension of local fields is itself a local field**, for
the valuation restricted from the top field.  The restriction is taken without renormalisation, so
the absolute values of the three fields extend one another literally; completeness and local
compactness then come from finite dimensionality over the base.  When the intermediate field is
unramified of the full residue degree, the residue field does not grow above it. -/
theorem exists_valued_of_unramified_tower (hnorm : ∀ x : K, ‖algebraMap K M x‖ = ‖x‖)
    (hur : ∀ z : S, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K S z = ‖c‖)
    (hf : Nat.card (DivisionResidue K M) = Nat.card (DivisionResidue K K) ^ finrank K S) :
    ∃ (_ : Valued S ℤᵐ⁰) (_ : Valuation.RankOne (Valued.v : Valuation S ℤᵐ⁰))
      (_ : CompleteSpace S) (_ : ProperSpace S),
      (∀ x : K, ‖algebraMap K S x‖ = ‖x‖) ∧ (∀ y : S, ‖algebraMap S M y‖ = ‖y‖) ∧
        (∀ y : S, (Valued.v (algebraMap S M y) : ℤᵐ⁰) = Valued.v y) ∧
        Nat.card (DivisionResidue S M) = Nat.card (DivisionResidue S S) := by
  letI vS : Valued S ℤᵐ⁰ := subValued S M
  have hval : ∀ y : S, (Valued.v y : ℤᵐ⁰) = Valued.v (algebraMap S M y) := fun _ => rfl
  have hnt : ∃ y : S, (Valued.v y : ℤᵐ⁰) ≠ 0 ∧ (Valued.v y : ℤᵐ⁰) ≠ 1 := by
    obtain ⟨c, hc0, hc1⟩ := Valuation.RankOne.nontrivial (Valued.v : Valuation K ℤᵐ⁰)
    have hc : c ≠ 0 := fun h => hc0 (by rw [h, map_zero])
    have hcM : (Valued.v (algebraMap K S c) : ℤᵐ⁰) = Valued.v (algebraMap K M c) := by
      rw [hval, ← IsScalarTower.algebraMap_apply]
    refine ⟨algebraMap K S c, ?_, ?_⟩
    · rw [hcM, Valuation.ne_zero_iff]
      exact (map_ne_zero_iff _ (algebraMap K M).injective).2 hc
    · rw [hcM]
      intro heq
      refine hc1 (le_antisymm ?_ ?_)
      · refine Valued.toNormedField.norm_le_one_iff.1 ?_
        rw [← hnorm c]
        exact Valued.toNormedField.norm_le_one_iff.2 heq.le
      · refine Valued.toNormedField.one_le_norm_iff.1 ?_
        rw [← hnorm c]
        exact Valued.toNormedField.one_le_norm_iff.2 heq.ge
  letI rS : Valuation.RankOne (Valued.v : Valuation S ℤᵐ⁰) :=
    { hom := Valuation.RankOne.hom (Valued.v : Valuation M ℤᵐ⁰)
      strictMono' := Valuation.RankOne.strictMono (Valued.v : Valuation M ℤᵐ⁰)
      exists_val_nontrivial := hnt }
  have hnormSM : ∀ y : S, ‖algebraMap S M y‖ = ‖y‖ := fun _ => rfl
  have hnormKS : ∀ x : K, ‖algebraMap K S x‖ = ‖x‖ := by
    intro x
    rw [← hnormSM (algebraMap K S x), ← IsScalarTower.algebraMap_apply, hnorm]
  letI : NormedSpace K S :=
    { (inferInstance : Module K S) with
      norm_smul_le := fun c y =>
        le_of_eq (by rw [Algebra.smul_def, norm_mul, hnormKS]) }
  haveI : CompleteSpace S := FiniteDimensional.complete K S
  haveI : ProperSpace S := FiniteDimensional.proper K S
  refine ⟨vS, rS, inferInstance, inferInstance, hnormKS, hnormSM, fun y => (hval y).symm, ?_⟩
  rw [natCard_divisionResidue_base (M := S) (L := M) hnormKS,
    natCard_divisionResidue_self (M := S) hnormKS,
    card_divisionResidue_of_unramified K S hur, hf]

end Tower

/-! ### The factorisation -/

section Factor

variable (K M : Type) [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
variable [Field M] [Valued M ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation M ℤᵐ⁰)] [CompleteSpace M] [ProperSpace M]
variable [Algebra K M] [FiniteDimensional K M]

omit [CompleteSpace M] [ProperSpace M] in
/-- **A finite extension of local fields factors through an unramified subextension across which
the residue field does not grow.**  The subextension is the one generated by the roots of unity of
order one less than the number of residues upstairs; it is unramified of the full residue degree,
so nothing is left for the residue field to gain above it. -/
theorem exists_maximalUnramified_subextension (hnorm : ∀ x : K, ‖algebraMap K M x‖ = ‖x‖) :
    ∃ (S : Type) (_ : Field S) (_ : Algebra K S) (_ : Algebra S M) (_ : IsScalarTower K S M)
      (_ : FiniteDimensional K S) (_ : FiniteDimensional S M) (_ : Valued S ℤᵐ⁰)
      (_ : Valuation.RankOne (Valued.v : Valuation S ℤᵐ⁰)) (_ : CompleteSpace S)
      (_ : ProperSpace S),
      (∀ x : K, ‖algebraMap K S x‖ = ‖x‖) ∧ (∀ y : S, ‖algebraMap S M y‖ = ‖y‖) ∧
        (∀ y : S, (Valued.v (algebraMap S M y) : ℤᵐ⁰) = Valued.v y) ∧
        (∀ z : S, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K S z = ‖c‖) ∧
        Nat.card (DivisionResidue S M) = Nat.card (DivisionResidue S S) := by
  obtain ⟨f, -, hfM⟩ := exists_card_divisionResidue_eq_pow K M
  haveI : FiniteDimensional K ↥(⊤ : IntermediateField K M) :=
    (IntermediateField.topEquiv (F := K) (E := M)).symm.toLinearEquiv.finiteDimensional
  have hftop : Nat.card (DivisionResidue K ↥(⊤ : IntermediateField K M))
      = Nat.card (DivisionResidue K K) ^ f := by
    rw [natCard_divisionResidue_top K M, hfM]
  obtain ⟨L, hLfin, -, hurL, hrank⟩ :=
    exists_unramified_le_finrank_eq K (⊤ : IntermediateField K M) hftop
  haveI := hLfin
  haveI : FiniteDimensional ↥L M := FiniteDimensional.right K ↥L M
  obtain ⟨vS, rS, hcS, hpS, hnormKS, hnormSM, hvalSM, hcard⟩ :=
    exists_valued_of_unramified_tower (K := K) (M := M) (S := ↥L) hnorm hurL (by rw [hrank, hfM])
  exact ⟨↥L, inferInstance, inferInstance, inferInstance, inferInstance, hLfin, inferInstance,
    vS, rS, hcS, hpS, hnormKS, hnormSM, hvalSM, hurL, hcard⟩

end Factor

end InverseGalois.CFT
