/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.RatResidueDegree

/-!
# The residue degree of a place over the integers and over the rationals

The residue degree of a place of a number field can be measured against two different bases: the
ideal generated by the rational prime below it in the integers, or the place of the rationals below
it in the integers of the rationals.  The local computation of an invariant produces the first,
because the number of residues of a completion is a power of the rational prime; the norm formula
for values at places produces the second, because the norm is taken relative to the integers of the
rationals.

The two agree.  The absolute norm of an ideal is the absolute norm of the ideal below it raised to
the residue degree, and it is also the rational prime raised to the residue degree over the
integers; since every finite place of the rationals has residue degree one, the absolute norm of
the place of the rationals below is the rational prime itself, and comparing the two expressions of
the same power of a prime identifies the exponents.

## Main results

* `InverseGalois.CFT.inertiaDeg_span_eq_inertiaDeg_rat`: **the residue degree of a place of a
  number field over the ideal generated by the rational prime below it is its residue degree over
  the place of the rationals below it.**

## Tags

number field, place, residue degree, inertia degree, absolute norm, rational prime
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

section InertiaDegRat

variable {k : Type} [Field k] [NumberField k]

/-- **The residue degree of a place of a number field over the ideal generated by the rational
prime below it is its residue degree over the place of the rationals below it.**  Both make the
absolute norm of the place the rational prime raised to that degree, the absolute norm of a place
of the rationals being the prime itself. -/
theorem inertiaDeg_span_eq_inertiaDeg_rat (P : HeightOneSpectrum (𝓞 ℚ))
    (v : HeightOneSpectrum (𝓞 k)) [v.asIdeal.LiesOver P.asIdeal] {q : ℕ} (hq : q.Prime)
    [v.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] [P.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] :
    (Ideal.span {(q : ℤ)}).inertiaDeg v.asIdeal = P.asIdeal.inertiaDeg v.asIdeal := by
  have h1 : Ideal.absNorm v.asIdeal = q ^ ((Ideal.span {(q : ℤ)}).inertiaDeg v.asIdeal) :=
    Ideal.absNorm_eq_pow_inertiaDeg' _ hq
  have h2 : Ideal.absNorm P.asIdeal = q ^ ((Ideal.span {(q : ℤ)}).inertiaDeg P.asIdeal) :=
    Ideal.absNorm_eq_pow_inertiaDeg' _ hq
  have h3 : Ideal.absNorm v.asIdeal
      = Ideal.absNorm P.asIdeal ^ (P.asIdeal.inertiaDeg v.asIdeal) :=
    Ideal.absNorm_eq_pow_inertiaDeg_of_liesOver _ _ P.isPrime P.ne_bot
  rw [inertiaDeg_rat_eq_one hq P, pow_one] at h2
  rw [h2, h1] at h3
  exact Nat.pow_right_injective hq.two_le h3

end InertiaDegRat

end InverseGalois.CFT
