/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.FrobeniusRamified
import InverseGalois.CFT.Brauer.InvariantCompositum
import InverseGalois.CFT.Brauer.InvariantMap
import InverseGalois.CFT.Brauer.ResidueBaseChange
import InverseGalois.CFT.Brauer.UnramifiedDegree

/-!
# The invariant map under base change to an extension with the same residues

Let `M / K` be a finite extension of local fields whose absolute value extends the absolute value
of `K` and which has no more residues than `K`, and let `r` be the factor by which the normalised
valuation of `K` is multiplied inside `M`.  The invariant of a Brauer class over `K` computed over
`M` is then `r` times the invariant computed over `K`:

`inv_M (res_M x) = r · inv_K x`.

A class over `K` is split by an unramified extension `F` of `K`, which is generated by a root of
unity `η` whose order is one less than the number of residues of `F`.  Adjoining the same root of
unity to `M` produces an unramified extension of `M` of the same degree: the two residue rings of
`M⟮η⟯` agree because the two absolute values do, and `M` has no more residues than `K`, so counting
residues bounds the degree from below, while the minimal polynomial of `η` bounds it from above.
The Frobenius automorphism of `M⟮η⟯` restricts to the Frobenius automorphism of `K⟮η⟯`, so the
degree count upgrades to an isomorphism of Galois groups carrying one generator to the other, and
the invariant of a cyclic algebra transports along it.

## Main results

* `InverseGalois.CFT.localInvariantHom_baseChange_of_residue_eq`: **the invariant of a Brauer class
  is multiplied by the ratio of the two normalised valuations under base change to an extension
  with the same residues.**

## Tags

Brauer group, local field, totally ramified extension, invariant map, base change,
class field theory
-/

set_option synthInstance.maxHeartbeats 1600000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open Module

open scoped IntermediateField Valued WithZero

variable {K M : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
variable [Field M] [Valued M ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation M ℤᵐ⁰)] [CompleteSpace M] [ProperSpace M]
variable [Algebra K M] [FiniteDimensional K M] {mK mM : ℤ}

/-- **The invariant of a Brauer class is multiplied by the ratio of the two normalised valuations
under base change to an extension with the same residues.**  The class is split by an unramified
extension generated by a root of unity; adjoining that root of unity to the larger base field gives
an unramified extension of the same degree, and its Frobenius automorphism restricts to the
Frobenius automorphism downstairs, so the two cyclic algebras have the same coefficient and the
same degree and only the change of valuation is left. -/
theorem localInvariantHom_baseChange_of_residue_eq
    (hnorm : ∀ x : K, ‖algebraMap K M x‖ = ‖x‖)
    (hres : Nat.card (DivisionResidue M M) = Nat.card (DivisionResidue K K))
    (hmK : IsUnitValGen K mK) (hmM : IsUnitValGen M mM) {r : ℕ}
    (hval : ∀ a : Kˣ,
      unitValDiv hmM (Additive.ofMul (Units.map (algebraMap K M).toMonoidHom a))
        = (r : ℤ) * unitValDiv hmK (Additive.ofMul a))
    (x : BrauerGroup.{0, 0} K) :
    localInvariantHom M hmM (BrauerGroup.baseChangeHom M x)
      = localInvariantHom K hmK x ^ r := by
  classical
  obtain ⟨F₀, hF₀⟩ := exists_unramifiedSubfield_mem_relative K x
  have hn0 : finrank K ↥F₀.carrier ≠ 0 := Module.finrank_pos.ne'
  have hcard : Nat.card (DivisionResidue K ↥F₀.carrier)
      = Nat.card (DivisionResidue K K) ^ finrank K ↥F₀.carrier :=
    card_divisionResidue_of_unramified K ↥F₀.carrier F₀.unramified
  have h1lt : 1 < Nat.card (DivisionResidue K ↥F₀.carrier) := Finite.one_lt_card
  haveI : NeZero (Nat.card (DivisionResidue K ↥F₀.carrier) - 1) := ⟨by omega⟩
  have hmnormK : ‖((Nat.card (DivisionResidue K ↥F₀.carrier) - 1 : ℕ) : K)‖ = 1 := by
    rw [hcard]
    exact norm_natCast_pow_card_divisionResidue_sub_one K hn0
  have hmnormM : ‖((Nat.card (DivisionResidue K ↥F₀.carrier) - 1 : ℕ) : M)‖ = 1 := by
    rw [← map_natCast (algebraMap K M), hnorm]
    exact hmnormK
  obtain ⟨ζ, hζ, htop⟩ :=
    exists_isPrimitiveRoot_adjoin_eq_top_of_unramified K ↥F₀.carrier F₀.unramified
  set q := Nat.card (DivisionResidue K ↥F₀.carrier) - 1 with hqdef
  clear_value q
  -- A copy of the splitting field inside an algebraic closure of the larger base field.
  haveI : Algebra.IsAlgebraic K ↥F₀.carrier := Algebra.IsAlgebraic.of_finite K ↥F₀.carrier
  obtain ⟨ψ⟩ : Nonempty (↥F₀.carrier →ₐ[K] AlgebraicClosure M) := ⟨IsAlgClosed.lift⟩
  obtain ⟨η, hηprim, hηrange⟩ :
      ∃ η : AlgebraicClosure M, IsPrimitiveRoot η q ∧ ψ.fieldRange = K⟮η⟯ := by
    refine ⟨ψ ζ, hζ.map_of_injective (f := ψ) ψ.toRingHom.injective, ?_⟩
    refine le_antisymm ?_ (IntermediateField.adjoin_simple_le_iff.2 ⟨ζ, rfl⟩)
    rintro - ⟨y, rfl⟩
    have hy : y ∈ Algebra.adjoin K ({ζ} : Set ↥F₀.carrier) := htop ▸ Algebra.mem_top
    rw [Algebra.adjoin_singleton_eq_range_aeval] at hy
    obtain ⟨p, rfl⟩ := hy
    have hsub : Algebra.adjoin K ({ψ ζ} : Set (AlgebraicClosure M)) ≤ K⟮ψ ζ⟯.toSubalgebra :=
      Algebra.adjoin_le
        (Set.singleton_subset_iff.2 (IntermediateField.mem_adjoin_simple_self K (ψ ζ)))
    show ψ (Polynomial.aeval ζ p) ∈ K⟮ψ ζ⟯
    rw [← IntermediateField.mem_toSubalgebra, ← Polynomial.aeval_algHom_apply]
    refine hsub ?_
    rw [Algebra.adjoin_singleton_eq_range_aeval]
    exact ⟨p, rfl⟩
  -- The unramified splitting field, transported.
  let χ : ↥F₀.carrier ≃ₐ[K] ↥K⟮η⟯ :=
    (AlgEquiv.ofInjectiveField ψ).trans (IntermediateField.equivOfEq hηrange)
  haveI : FiniteDimensional K ↥K⟮η⟯ := χ.toLinearEquiv.finiteDimensional
  have hurE : ∀ z : ↥K⟮η⟯, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥K⟮η⟯ z = ‖c‖ :=
    unramified_of_algEquiv χ F₀.unramified
  haveI : IsGalois K ↥K⟮η⟯ := isGalois_of_unramified K ↥K⟮η⟯ hurE
  have hdeg : finrank K ↥K⟮η⟯ = finrank K ↥F₀.carrier := χ.toLinearEquiv.finrank_eq.symm
  have hmemE : x ∈ BrauerGroup.relative K ↥K⟮η⟯ := by
    letI : Algebra ↥F₀.carrier ↥K⟮η⟯ := (χ : ↥F₀.carrier →ₐ[K] ↥K⟮η⟯).toRingHom.toAlgebra
    haveI : IsScalarTower K ↥F₀.carrier ↥K⟮η⟯ :=
      IsScalarTower.of_algebraMap_eq fun y => (χ.commutes y).symm
    exact BrauerGroup.relative_le_relative K ↥F₀.carrier ↥K⟮η⟯ hF₀
  -- The same root of unity over the larger base field.
  haveI : FiniteDimensional M ↥M⟮η⟯ := finiteDimensional_adjoin_isPrimitiveRoot M hηprim
  have hurN : ∀ z : ↥M⟮η⟯, z ≠ 0 → ∃ c : M, c ≠ 0 ∧ divisionNorm M ↥M⟮η⟯ z = ‖c‖ :=
    unramified_adjoin_isPrimitiveRoot M hηprim hmnormM
  haveI : IsGalois M ↥M⟮η⟯ := isGalois_of_unramified M ↥M⟮η⟯ hurN
  haveI : FiniteDimensional K ↥M⟮η⟯ := FiniteDimensional.trans K M ↥M⟮η⟯
  -- The smaller extension sits inside the larger one.
  have hsubfield : K⟮η⟯ ≤ (M⟮η⟯ : IntermediateField M (AlgebraicClosure M)).restrictScalars K := by
    rw [IntermediateField.adjoin_le_iff]
    intro w hw
    rw [Set.mem_singleton_iff] at hw
    subst hw
    simpa using IntermediateField.mem_adjoin_simple_self M w
  have hmemN : ∀ y : ↥K⟮η⟯, (y : AlgebraicClosure M) ∈ M⟮η⟯ := fun y =>
    (IntermediateField.mem_restrictScalars K).1 (hsubfield y.2)
  let ι : ↥K⟮η⟯ →ₐ[K] ↥M⟮η⟯ :=
    { toFun := fun y => ⟨(y : AlgebraicClosure M), hmemN y⟩
      map_one' := rfl
      map_mul' := fun _ _ => rfl
      map_zero' := rfl
      map_add' := fun _ _ => rfl
      commutes' := fun c => Subtype.ext (by
        rw [IsScalarTower.algebraMap_apply K M ↥M⟮η⟯]
        exact IsScalarTower.algebraMap_apply K M (AlgebraicClosure M) c) }
  letI : Algebra ↥K⟮η⟯ ↥M⟮η⟯ := ι.toRingHom.toAlgebra
  haveI : IsScalarTower K ↥K⟮η⟯ ↥M⟮η⟯ :=
    IsScalarTower.of_algebraMap_eq fun c => (ι.commutes c).symm
  -- The two extensions have the same degree.
  have hintK : IsIntegral K η :=
    ⟨Polynomial.X ^ q - Polynomial.C 1, Polynomial.monic_X_pow_sub_C 1 (NeZero.ne q), by
      simp [hηprim.pow_eq_one]⟩
  have hintM : IsIntegral M η :=
    ⟨Polynomial.X ^ q - Polynomial.C 1, Polynomial.monic_X_pow_sub_C 1 (NeZero.ne q), by
      simp [hηprim.pow_eq_one]⟩
  have hup : finrank M ↥M⟮η⟯ ≤ finrank K ↥K⟮η⟯ := by
    rw [IntermediateField.adjoin.finrank hintM, IntermediateField.adjoin.finrank hintK]
    refine le_trans (Polynomial.natDegree_le_of_dvd (minpoly.dvd_map_of_isScalarTower K M η)
      (((minpoly.monic hintK).map (algebraMap K M)).ne_zero) ) ?_
    exact le_of_eq ((minpoly.monic hintK).natDegree_map (algebraMap K M))
  have hlow : finrank K ↥K⟮η⟯ ≤ finrank M ↥M⟮η⟯ := by
    have hbase : Nat.card (DivisionResidue M ↥M⟮η⟯) = Nat.card (DivisionResidue K ↥M⟮η⟯) :=
      natCard_divisionResidue_base (K := K) (M := M) (L := ↥M⟮η⟯) hnorm
    have hinj : Nat.card (DivisionResidue K ↥K⟮η⟯) ≤ Nat.card (DivisionResidue K ↥M⟮η⟯) :=
      Nat.card_le_card_of_injective _ (divisionResidueTower_injective (L' := ↥M⟮η⟯))
    refine (Nat.pow_le_pow_iff_right (Finite.one_lt_card (α := DivisionResidue K K))).1 ?_
    calc Nat.card (DivisionResidue K K) ^ finrank K ↥K⟮η⟯
        = Nat.card (DivisionResidue K ↥K⟮η⟯) :=
          (card_divisionResidue_of_unramified K ↥K⟮η⟯ hurE).symm
      _ ≤ Nat.card (DivisionResidue K ↥M⟮η⟯) := hinj
      _ = Nat.card (DivisionResidue M ↥M⟮η⟯) := hbase.symm
      _ = Nat.card (DivisionResidue M M) ^ finrank M ↥M⟮η⟯ :=
          card_divisionResidue_of_unramified M ↥M⟮η⟯ hurN
      _ = Nat.card (DivisionResidue K K) ^ finrank M ↥M⟮η⟯ := by rw [hres]
  have hfin : finrank M ↥M⟮η⟯ = finrank K ↥K⟮η⟯ := le_antisymm hup hlow
  -- The two Galois groups are isomorphic.
  let Φ : Gal(↥M⟮η⟯/M) →* Gal(↥K⟮η⟯/K) :=
    (AlgEquiv.restrictNormalHom (F := K) (K₁ := ↥M⟮η⟯) ↥K⟮η⟯).comp
      (MonoidHom.mk' (fun σ : Gal(↥M⟮η⟯/M) => AlgEquiv.restrictScalars K σ) fun _ _ => rfl)
  have hΦinj : Function.Injective Φ := by
    rw [injective_iff_map_eq_one]
    intro σ hσ
    have hfix : ∀ y : ↥K⟮η⟯, σ (algebraMap ↥K⟮η⟯ ↥M⟮η⟯ y) = algebraMap ↥K⟮η⟯ ↥M⟮η⟯ y := by
      intro y
      have h := ((σ.restrictScalars K).restrictNormal_commutes ↥K⟮η⟯ y).symm
      rw [show (σ.restrictScalars K).restrictNormal ↥K⟮η⟯ = Φ σ from rfl, hσ] at h
      simpa using h
    have hid : (σ : ↥M⟮η⟯ →ₐ[M] ↥M⟮η⟯) = AlgHom.id M ↥M⟮η⟯ := by
      refine IntermediateField.adjoin_algHom_ext M ?_
      intro w hw
      obtain rfl : w = η := hw
      exact hfix ⟨w, IntermediateField.mem_adjoin_simple_self K w⟩
    refine AlgEquiv.ext fun y => ?_
    simpa using AlgHom.congr_fun hid y
  have hcards : Nat.card Gal(↥M⟮η⟯/M) = Nat.card Gal(↥K⟮η⟯/K) := by
    rw [IsGalois.card_aut_eq_finrank M ↥M⟮η⟯, IsGalois.card_aut_eq_finrank K ↥K⟮η⟯, hfin]
  let e : Gal(↥M⟮η⟯/M) ≃* Gal(↥K⟮η⟯/K) :=
    MulEquiv.ofBijective Φ ((Nat.bijective_iff_injective_and_card Φ).2 ⟨hΦinj, hcards⟩)
  have he : ∀ (σ : Gal(↥M⟮η⟯/M)) (y : ↥K⟮η⟯),
      σ (algebraMap ↥K⟮η⟯ ↥M⟮η⟯ y) = algebraMap ↥K⟮η⟯ ↥M⟮η⟯ (e σ y) := fun σ y =>
    ((σ.restrictScalars K).restrictNormal_commutes ↥K⟮η⟯ y).symm
  have hgen : e (divisionFrobenius M ↥M⟮η⟯ hurN) = divisionFrobenius K ↥K⟮η⟯ hurE :=
    restrictNormal_restrictScalars_divisionFrobenius hnorm hres hurN hurE
  -- Both invariants are computed in the two extensions.
  have hmemNrel : BrauerGroup.baseChangeHom M x ∈ BrauerGroup.relative M ↥M⟮η⟯ :=
    baseChangeHom_mem_relative_compositum M ↥M⟮η⟯ hmemE
  have h1 : localInvariantHom K hmK x = localInvariant K ↥K⟮η⟯ hurE hmK ⟨x, hmemE⟩ :=
    localInvariantHom_apply_of_unramified hmK hurE ⟨x, hmemE⟩
  have h2 : localInvariantHom M hmM (BrauerGroup.baseChangeHom M x)
      = localInvariant M ↥M⟮η⟯ hurN hmM ⟨BrauerGroup.baseChangeHom M x, hmemNrel⟩ :=
    localInvariantHom_apply_of_unramified hmM hurN
      ⟨BrauerGroup.baseChangeHom M x, hmemNrel⟩
  rw [h1, h2]
  exact brauerInvariant_baseChange_compositum
    (forall_mem_zpowers_divisionFrobenius K ↥K⟮η⟯ hurE)
    (forall_mem_zpowers_divisionFrobenius M ↥M⟮η⟯ hurN) hgen he
    (hasUnramifiedNormValues_of_divisionNorm hurE)
    (hasUnramifiedNormValues_of_divisionNorm hurN) hmK hmM hval ⟨x, hmemE⟩

end InverseGalois.CFT
