/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.LocalSymbol
import InverseGalois.CFT.Brauer.SymbolSteinberg
import InverseGalois.CFT.Local.RadicalUnramified

/-!
# The norm residue symbol of two units of a local field

The norm residue symbol is the invariant of the power symbol, and the invariant map is an
isomorphism, so every relation between power symbols is a relation between norm residue symbols.
Skew symmetry, the Steinberg relation and the triviality of the symbol of a unit against its
negative therefore all descend from the power symbol to the local field.

The relation that is proper to a local field is the triviality of the symbol of two units of the
valuation ring, for a prime exponent that the residue characteristic does not divide.  The level of
such a unit is generated by a root of prime order of a unit, so it has degree one or the exponent;
in the first case the base element is its own norm, and in the second the minimal polynomial of the
generator is the difference of the power of the variable and the unit, whose reduction stays
irreducible, so the extension is unramified and every unit of the valuation ring of the base is a
norm from it.

Together with bilinearity these are all the relations the tame symbol satisfies: a symbol of two
units is trivial, so a symbol is determined by the values of its arguments and by the symbol of a
uniformiser against a unit.

## Main results

* `InverseGalois.CFT.localKummerSymbol_eq_one_of_kummerSymbolUnits`: a trivial power symbol has a
  trivial norm residue symbol.
* `InverseGalois.CFT.kummerSymbolUnits_eq_one_of_valued_eq_one`: **the power symbol of two units of
  the valuation ring of a local field is trivial**, for a prime exponent prime to the residue
  characteristic.
* `InverseGalois.CFT.localSymbol_eq_one_of_valued_eq_one`: **the norm residue symbol of two units
  of the valuation ring of a local field is trivial.**
* `InverseGalois.CFT.localSymbol_mul_swap`: **the norm residue symbol is skew symmetric.**
* `InverseGalois.CFT.localSymbol_one_sub`, `InverseGalois.CFT.localSymbol_self_one_sub`: **the
  Steinberg relation for the norm residue symbol.**
* `InverseGalois.CFT.localSymbol_neg_self`: **the norm residue symbol of a unit against its
  negative is trivial.**

## Tags

norm residue symbol, Hilbert symbol, tame symbol, local field, unramified extension,
Steinberg relation, Kummer theory, class field theory
-/

namespace InverseGalois.CFT

open Module Polynomial

open scoped Valued WithZero

/-! ### Units of the valuation ring pair trivially -/

section KummerUnits

variable {K Ω : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
  [Field Ω] [Algebra K Ω] [IsGalois K Ω] {n : ℕ} [NeZero n] {ζ : K}
  {hζ : IsPrimitiveRoot ζ n} {p e : ℕ}

attribute [local instance] zmodTrivialAction isSmoothAction_zmod

variable (h : IsKummerData K Ω (Multiplicative (ZMod n)) (zmodRootHom hζ) n)

attribute [local instance] finiteDimensional_kummerLevel isGalois_kummerLevel

/-- **The power symbol of two units of the valuation ring of a local field is trivial**, for a
prime exponent that the residue characteristic does not divide.  The level of the second unit has
degree one or the exponent; in the first case the first unit is its own norm, and in the second the
level is the radical extension by a unit generated by a root of prime order, which is unramified,
so every unit of the valuation ring of the base is a norm from it. -/
theorem kummerSymbolUnits_eq_one_of_valued_eq_one (hn : n.Prime) (hpn : ¬ p ∣ n)
    (hres : HasResidueChar K p e) {a b : Kˣ} (ha : Valued.v (a : K) = 1)
    (hb : Valued.v (b : K) = 1) : kummerSymbolUnits h (mulZMod n) a b = 1 := by
  obtain ⟨σ₀, t, hgen, -, -, -⟩ := exists_generator_kummerLevel_index h b
  haveI : IsCyclic Gal(↥(kummerLevel h b)/K) :=
    isCyclic_iff_exists_zpowers_eq_top.mpr ⟨σ₀, eq_top_iff.mpr fun x _ => hgen x⟩
  refine (kummerSymbolUnits_eq_one_iff_norm_kummerLevel h a b).mpr ?_
  rcases hn.eq_one_or_self_of_dvd _ (card_gal_kummerLevel_dvd h b) with hd1 | hdn
  · refine ⟨unitsAlgebraMap K ↥(kummerLevel h b) a, ?_⟩
    rw [coe_unitsAlgebraMap, Algebra.norm_algebraMap,
      ← IsGalois.card_aut_eq_finrank K ↥(kummerLevel h b), hd1, pow_one]
  · obtain ⟨c, hc⟩ := exists_algebraMap_eq_pow_card h b
    have hbn : algebraMap K ↥(kummerLevel h b) (b : K) = kummerLevelGen h b ^ n := by
      refine (algebraMap ↥(kummerLevel h b) Ω).injective ?_
      rw [map_pow, ← IsScalarTower.algebraMap_apply]
      exact (congrArg Units.val (h.root_pow b)).symm
    have hcb : c = (b : K) := by
      refine (algebraMap K ↥(kummerLevel h b)).injective ?_
      rw [hc, hbn, hdn]
    have hmin : minpoly K (kummerLevelPowerBasis h b).gen = X ^ n - C (b : K) := by
      rw [kummerLevelPowerBasis_gen, minpoly_kummerLevelGen h b hc, hcb, hdn]
    exact (mem_normSubgroup_iff _).mp
      (mem_normSubgroup_of_radical_unit (kummerLevelPowerBasis h b) hn hpn hb hmin hres ha)

end KummerUnits

/-! ### Relations descend to the norm residue symbol -/

section Bridge

variable {K : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
  [PerfectField K] {m : ℤ} {p e : ℕ}
variable {M : Type} [CommGroup M] [MulDistribMulAction Gal(AlgebraicClosure K/K) M]
  {ι : M →* Kˣ} {n : ℕ} [NeZero n] [IsSmoothAction Gal(AlgebraicClosure K/K) M]

/-- A trivial power symbol has a trivial norm residue symbol, the latter being the invariant of the
former. -/
theorem localKummerSymbol_eq_one_of_kummerSymbolUnits (hres : HasResidueChar K p e)
    (hm : IsUnitValGen K m) (h : IsKummerData K (AlgebraicClosure K) M ι n) (Φ : M →* M →* M)
    {a b : Kˣ} (hs : kummerSymbolUnits h Φ a b = 1) : localKummerSymbol hres hm h Φ a b = 1 := by
  rw [localKummerSymbol_apply, hs, map_one]

/-- A product of two power symbols which is trivial has a trivial product of norm residue
symbols. -/
theorem localKummerSymbol_mul_swap (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (h : IsKummerData K (AlgebraicClosure K) M ι n) (Φ : M →* M →* M) (a b : Kˣ)
    (hs : kummerSymbolUnits h Φ a b * kummerSymbolUnits h Φ b a = 1) :
    localKummerSymbol hres hm h Φ a b * localKummerSymbol hres hm h Φ b a = 1 := by
  rw [localKummerSymbol_apply, localKummerSymbol_apply, ← map_mul, hs, map_one]

end Bridge

/-! ### The relations of the norm residue symbol -/

section Root

variable {K : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
  [PerfectField K] {m : ℤ} {p e : ℕ} {n : ℕ} [NeZero n] {ζ : K}

/-- **The norm residue symbol of two units of the valuation ring of a local field is trivial**, for
a prime exponent that the residue characteristic does not divide.  Adjoining a root of prime order
of a unit gives an unramified extension, and every unit of the valuation ring of the base is a norm
from an unramified extension. -/
theorem localSymbol_eq_one_of_valued_eq_one (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hζ : IsPrimitiveRoot ζ n) (hn : n.Prime) (hpn : ¬ p ∣ n) {a b : Kˣ}
    (ha : Valued.v (a : K) = 1) (hb : Valued.v (b : K) = 1) : localSymbol hres hm hζ a b = 1 :=
  letI := zmodTrivialAction K (AlgebraicClosure K) n
  haveI : IsSmoothAction Gal(AlgebraicClosure K/K) (Multiplicative (ZMod n)) :=
    isSmoothAction_of_trivial fun _ _ => rfl
  localKummerSymbol_eq_one_of_kummerSymbolUnits hres hm
    (isKummerData_zmod hζ exists_units_pow_eq) (mulZMod n)
    (kummerSymbolUnits_eq_one_of_valued_eq_one (isKummerData_zmod hζ exists_units_pow_eq) hn hpn
      hres ha hb)

/-- **The norm residue symbol is skew symmetric**: the symbol of two units times the symbol of the
same two units in the other order is trivial. -/
theorem localSymbol_mul_swap (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hζ : IsPrimitiveRoot ζ n) (a b : Kˣ) :
    localSymbol hres hm hζ a b * localSymbol hres hm hζ b a = 1 :=
  letI := zmodTrivialAction K (AlgebraicClosure K) n
  haveI : IsSmoothAction Gal(AlgebraicClosure K/K) (Multiplicative (ZMod n)) :=
    isSmoothAction_of_trivial fun _ _ => rfl
  localKummerSymbol_mul_swap hres hm (isKummerData_zmod hζ exists_units_pow_eq) (mulZMod n) a b
    (kummerSymbolUnits_mul_swap (isKummerData_zmod hζ exists_units_pow_eq) a b)

/-- **The Steinberg relation**: the norm residue symbol of one minus a unit against that unit is
trivial. -/
theorem localSymbol_one_sub (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hζ : IsPrimitiveRoot ζ n) (a u : Kˣ) (hu : (u : K) = 1 - (a : K)) :
    localSymbol hres hm hζ u a = 1 :=
  letI := zmodTrivialAction K (AlgebraicClosure K) n
  haveI : IsSmoothAction Gal(AlgebraicClosure K/K) (Multiplicative (ZMod n)) :=
    isSmoothAction_of_trivial fun _ _ => rfl
  localKummerSymbol_eq_one_of_kummerSymbolUnits hres hm
    (isKummerData_zmod hζ exists_units_pow_eq) (mulZMod n)
    (kummerSymbolUnits_one_sub (isKummerData_zmod hζ exists_units_pow_eq) a u hu)

/-- **The Steinberg relation**: the norm residue symbol of a unit against one minus that unit is
trivial. -/
theorem localSymbol_self_one_sub (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hζ : IsPrimitiveRoot ζ n) (a u : Kˣ) (hu : (u : K) = 1 - (a : K)) :
    localSymbol hres hm hζ a u = 1 :=
  letI := zmodTrivialAction K (AlgebraicClosure K) n
  haveI : IsSmoothAction Gal(AlgebraicClosure K/K) (Multiplicative (ZMod n)) :=
    isSmoothAction_of_trivial fun _ _ => rfl
  localKummerSymbol_eq_one_of_kummerSymbolUnits hres hm
    (isKummerData_zmod hζ exists_units_pow_eq) (mulZMod n)
    (kummerSymbolUnits_self_one_sub (isKummerData_zmod hζ exists_units_pow_eq) a u hu)

/-- **The norm residue symbol of a unit against its negative is trivial.** -/
theorem localSymbol_neg_self (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hζ : IsPrimitiveRoot ζ n) (a : Kˣ) : localSymbol hres hm hζ a (-a) = 1 :=
  letI := zmodTrivialAction K (AlgebraicClosure K) n
  haveI : IsSmoothAction Gal(AlgebraicClosure K/K) (Multiplicative (ZMod n)) :=
    isSmoothAction_of_trivial fun _ _ => rfl
  localKummerSymbol_eq_one_of_kummerSymbolUnits hres hm
    (isKummerData_zmod hζ exists_units_pow_eq) (mulZMod n)
    (kummerSymbolUnits_neg_self (isKummerData_zmod hζ exists_units_pow_eq) a)

end Root

end InverseGalois.CFT
