/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.FrobeniusBaseChange
import InverseGalois.CFT.Brauer.InvariantRestrict
import InverseGalois.CFT.Brauer.LocalInvariant

/-!
# The normalised invariant under base change to an intermediate local field

Let `K ⊆ M ⊆ L` be a tower of nonarchimedean local fields with `L / K` unramified and Galois, and
suppose the absolute value and the normalised valuation of `M` extend those of `K`.  The invariant
of a Brauer class of `Br(L / K)` computed over `M` is then `[M : K]` times the invariant computed
over `K`.

Both normalisations are taken with respect to the Frobenius automorphism, and the two Frobenius
automorphisms are compatible: the Galois group of `L / M` is the subgroup of index `[M : K]` in the
cyclic group `Gal(L / K)`, so its generator induces the `[M : K]`-th power of a generator
downstairs, and an automorphism inducing that power of the Frobenius automorphism *is* the
Frobenius automorphism of `L / M`.  So the change of generator that the base-change formula for
cyclic algebras asks for is exactly the change of normalisation, and the invariant multiplies by
the degree.

## Main results

* `InverseGalois.CFT.restrictScalars_divisionFrobenius`: **the Frobenius automorphism of the top
  field over the intermediate field induces the power of the Frobenius automorphism over the base
  field given by the degree of the intermediate field.**
* `InverseGalois.CFT.localInvariant_baseChange`: **the normalised invariant of a Brauer class is
  multiplied by the degree of the intermediate field under base change.**

## Tags

Brauer group, local field, unramified extension, Frobenius, invariant map, restriction,
class field theory
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open Module

open scoped Valued WithZero

variable {K M L : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
variable [Field M] [Valued M ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation M ℤᵐ⁰)] [CompleteSpace M] [ProperSpace M]
variable [Algebra K M] [FiniteDimensional K M]
variable [Field L] [Algebra K L] [Algebra M L] [IsScalarTower K M L]
variable [FiniteDimensional K L] [IsGalois K L] [FiniteDimensional M L] [IsGalois M L]
variable {mK mM : ℤ}

/-! ### The two Frobenius automorphisms -/

omit [CompleteSpace K] [CompleteSpace M] in
/-- **The Frobenius automorphism of the top field over a compatibly normed intermediate field
induces the power of the Frobenius automorphism over the base field given by the degree of the
intermediate field.**  The Galois group of the top field over the intermediate field is the subgroup
of that index in a cyclic group, so it is generated by an automorphism inducing that power of the
Frobenius automorphism downstairs, and such an automorphism is the Frobenius automorphism upstairs.
-/
theorem restrictScalars_divisionFrobenius (hnorm : ∀ x : K, ‖algebraMap K M x‖ = ‖x‖)
    (hurK : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    (divisionFrobenius M L (unramified_base hnorm hurK)).restrictScalars K
      = divisionFrobenius K L hurK ^ finrank K M := by
  obtain ⟨σ₁, hσ₁, -⟩ :=
    exists_restrictScalars_eq_pow (M := M) (forall_mem_zpowers_divisionFrobenius K L hurK)
  rw [← eq_divisionFrobenius_of_restrictScalars hnorm
    (natCard_divisionResidue_self_eq_pow hnorm
      (unramified_of_unramified_tower (K := K) (L := M) (L' := L) hurK)) hσ₁]
  exact hσ₁

/-! ### The invariant under base change -/

/-- **The normalised invariant of a Brauer class is multiplied by the degree of the intermediate
field under base change.**  Base change replaces the coefficient of a cyclic algebra by its image
and the generator by one inducing its power, and the Frobenius automorphism of the top field over
the intermediate field is exactly such a generator. -/
theorem localInvariant_baseChange (hnorm : ∀ x : K, ‖algebraMap K M x‖ = ‖x‖)
    (hurK : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖)
    (hmK : IsUnitValGen K mK) (hmM : IsUnitValGen M mM)
    (hval : ∀ a : Kˣ,
      unitValDiv hmM (Additive.ofMul (Units.map (algebraMap K M).toMonoidHom a))
        = unitValDiv hmK (Additive.ofMul a))
    (x : ↥(BrauerGroup.relative K L)) :
    localInvariant M L (unramified_base hnorm hurK) hmM
        ⟨BrauerGroup.baseChangeHom M (x : BrauerGroup.{0, 0} K),
          baseChangeHom_mem_relative M x.2⟩
      = localInvariant K L hurK hmK x ^ finrank K M :=
  brauerInvariant_baseChange (forall_mem_zpowers_divisionFrobenius K L hurK)
    (forall_mem_zpowers_divisionFrobenius M L (unramified_base hnorm hurK))
    (restrictScalars_divisionFrobenius hnorm hurK)
    (hasUnramifiedNormValues_of_divisionNorm hurK)
    (hasUnramifiedNormValues_of_divisionNorm (unramified_base hnorm hurK)) hmK hmM hval x

end InverseGalois.CFT
