/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.NormPlaceValue

/-!
# Elements with prescribed orders at finitely many places

Finitely many prescribed orders at finitely many places of a number field are realised by a single
element of the field.  The construction is by prime avoidance: a prime of a Dedekind domain is
contained neither in its own square nor in any other prime, so it is not contained in the union of
its square with finitely many other primes, and an element of the prime avoiding that union has
multiplicity exactly one at the prime and zero at each of the others.  Multiplying powers of such
elements realises any prescribed system of multiplicities, and a quotient of two of them realises
any prescribed system of orders.

The consequence that is actually used is that an element of a number field can always be corrected,
by a factor chosen at will, to have order zero at each of finitely many places.  The correcting
factor can then be produced as a norm from an extension, whose class in the Brauer group is
therefore unchanged, so nothing is lost by assuming that the coefficient of a cyclic algebra is a
unit at the finitely many places under consideration.

## Main results

* `InverseGalois.CFT.exists_primeCount_eq_one`: **a prime of a Dedekind domain contains an element
  of multiplicity one there and multiplicity zero at each of finitely many other primes.**
* `InverseGalois.CFT.exists_primeCount_eq`: **prescribed multiplicities at finitely many primes of
  a Dedekind domain are realised by a single nonzero element.**
* `InverseGalois.CFT.exists_placeOrd_eq`: **prescribed orders at finitely many finite places of a
  number field are realised by a single element of the field.**
* `InverseGalois.CFT.exists_placeOrd_mul_eq_zero`: **any element of a number field can be corrected
  to have order zero at each of finitely many finite places.**

## Tags

Dedekind domain, prime avoidance, valuation, uniformizer, place, order, number field
-/

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

/-! ### Prescribed multiplicities in a Dedekind domain -/

section Dedekind

variable {R : Type*} [CommRing R] [IsDedekindDomain R]

/-- **A prime power divides the ideal generated by a nonzero element exactly when its exponent is
at most the multiplicity of the prime there.** -/
theorem le_primeCount_iff_dvd (v : HeightOneSpectrum R) {x : R} (hx : x ≠ 0) (n : ℕ) :
    n ≤ primeCount v (Ideal.span {x}) ↔ v.asIdeal ^ n ∣ Ideal.span {x} := by
  classical
  have hne : Ideal.span {x} ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hx
  rw [primeCount, ← Associates.prime_pow_dvd_iff_le (Associates.mk_ne_zero.mpr hne)
    v.associates_irreducible, ← Associates.mk_pow, Associates.mk_le_mk_iff_dvd]

/-- **A prime of a Dedekind domain contains an element of multiplicity one there and multiplicity
zero at each of finitely many other primes.**  The prime is contained neither in its square nor in
any of the others, so prime avoidance produces an element of it outside their union. -/
theorem exists_primeCount_eq_one (v : HeightOneSpectrum R) (s : Finset (HeightOneSpectrum R)) :
    ∃ x : R, x ≠ 0 ∧ primeCount v (Ideal.span {x}) = 1 ∧
      ∀ w ∈ s, w ≠ v → primeCount w (Ideal.span {x}) = 0 := by
  classical
  set t : Finset (Option (HeightOneSpectrum R)) := insert none ((s.erase v).image some) with ht
  set f : Option (HeightOneSpectrum R) → Ideal R :=
    fun o => o.elim (v.asIdeal ^ 2) (fun w => w.asIdeal) with hf
  have hp : ∀ i ∈ t, i ≠ none → i ≠ none → (f i).IsPrime := by
    rintro (_ | w) _ h _
    · exact absurd rfl h
    · exact w.isPrime
  have hnot : ¬ ((v.asIdeal : Set R) ⊆ ⋃ i ∈ (↑t : Set (Option (HeightOneSpectrum R))), f i) := by
    rw [Ideal.subset_union_prime none none hp]
    rintro ⟨i, hi, hle⟩
    match i with
    | none =>
        have hlt : v.asIdeal ^ 2 < v.asIdeal :=
          Ideal.pow_lt_self v.asIdeal v.ne_bot v.isMaximal.ne_top 2 le_rfl
        exact absurd (show v.asIdeal ≤ v.asIdeal ^ 2 from hle) hlt.not_ge
    | some w =>
        simp only [ht, Finset.mem_insert, Finset.mem_image, reduceCtorEq, false_or,
          Option.some.injEq, exists_eq_right] at hi
        exact (Finset.mem_erase.mp hi).1 (HeightOneSpectrum.ext
          (v.isMaximal.eq_of_le w.isMaximal.ne_top (show v.asIdeal ≤ w.asIdeal from hle)).symm)
  simp only [Set.not_subset] at hnot
  obtain ⟨x, hxv, hxn⟩ := hnot
  simp only [Set.mem_iUnion, not_exists] at hxn
  have hx2 : x ∉ v.asIdeal ^ 2 := fun hc => hxn none (by simp [ht]) hc
  have hx0 : x ≠ 0 := fun hc => hx2 (hc ▸ Submodule.zero_mem _)
  refine ⟨x, hx0, ?_, ?_⟩
  · have h1 : 1 ≤ primeCount v (Ideal.span {x}) :=
      (le_primeCount_iff_dvd v hx0 1).mpr (by
        simpa [Ideal.dvd_span_singleton] using hxv)
    have h2 : ¬ 2 ≤ primeCount v (Ideal.span {x}) := fun hc =>
      hx2 (Ideal.dvd_span_singleton.mp ((le_primeCount_iff_dvd v hx0 2).mp hc))
    omega
  · intro w hw hwv
    by_contra hc
    have h1 : 1 ≤ primeCount w (Ideal.span {x}) := Nat.one_le_iff_ne_zero.mpr hc
    have hmem : x ∈ w.asIdeal :=
      Ideal.dvd_span_singleton.mp (by simpa using (le_primeCount_iff_dvd w hx0 1).mp h1)
    exact hxn (some w) (by simp [ht, hw, hwv]) hmem

/-- **The multiplicity of a prime in a product of nonzero elements** is the sum of the
multiplicities. -/
theorem primeCount_span_prod {ι : Type*} (w : HeightOneSpectrum R) (s : Finset ι) (g : ι → R)
    (hg : ∀ i ∈ s, g i ≠ 0) :
    primeCount w (Ideal.span {∏ i ∈ s, g i}) = ∑ i ∈ s, primeCount w (Ideal.span {g i}) := by
  classical
  induction s using Finset.induction with
  | empty => simp [primeCount_top]
  | insert a s ha ih =>
      have h0 : ∀ i ∈ s, g i ≠ 0 := fun i hi => hg i (Finset.mem_insert_of_mem hi)
      have hga : g a ≠ 0 := hg a (Finset.mem_insert_self a s)
      have hprod : ∏ i ∈ s, g i ≠ 0 := Finset.prod_ne_zero_iff.mpr h0
      rw [Finset.prod_insert ha, Finset.sum_insert ha, ← ih h0,
        ← Ideal.span_singleton_mul_span_singleton,
        primeCount_mul w (by simpa [Ideal.span_singleton_eq_bot] using hga)
          (by simpa [Ideal.span_singleton_eq_bot] using hprod)]

/-- **Prescribed multiplicities at finitely many primes of a Dedekind domain are realised by a
single nonzero element**, a product of powers of the elements of multiplicity one. -/
theorem exists_primeCount_eq (s : Finset (HeightOneSpectrum R))
    (m : HeightOneSpectrum R → ℕ) :
    ∃ x : R, x ≠ 0 ∧ ∀ w ∈ s, primeCount w (Ideal.span {x}) = m w := by
  classical
  choose π hπ0 hπ1 hπ2 using fun v : HeightOneSpectrum R => exists_primeCount_eq_one v s
  refine ⟨∏ v ∈ s, π v ^ m v, Finset.prod_ne_zero_iff.mpr fun v _ => pow_ne_zero _ (hπ0 v), ?_⟩
  intro w hw
  rw [primeCount_span_prod w s _ fun v _ => pow_ne_zero _ (hπ0 v), Finset.sum_eq_single w]
  · rw [← Ideal.span_singleton_pow, primeCount_pow w
      (by simpa [Ideal.span_singleton_eq_bot] using hπ0 w), hπ1 w, mul_one]
  · intro v hv hvw
    rw [← Ideal.span_singleton_pow, primeCount_pow w
      (by simpa [Ideal.span_singleton_eq_bot] using hπ0 v), hπ2 v w hw (Ne.symm hvw), mul_zero]
  · intro h
    exact absurd hw h

end Dedekind

/-! ### Prescribed orders at finitely many places of a number field -/

section NumberField

variable {k : Type} [Field k] [NumberField k]

/-- **Prescribed orders at finitely many finite places of a number field are realised by a single
element of the field**, a quotient of two algebraic integers realising the two signs. -/
theorem exists_placeOrd_eq (s : Finset (HeightOneSpectrum (𝓞 k)))
    (n : HeightOneSpectrum (𝓞 k) → ℤ) :
    ∃ x : kˣ, ∀ w ∈ s, placeOrd w (x : k) = n w := by
  obtain ⟨y, hy0, hy⟩ := exists_primeCount_eq s fun w => (-n w).toNat
  obtain ⟨z, hz0, hz⟩ := exists_primeCount_eq s fun w => (n w).toNat
  have hyK : algebraMap (𝓞 k) k y ≠ 0 :=
    (map_ne_zero_iff _ (FaithfulSMul.algebraMap_injective (𝓞 k) k)).mpr hy0
  have hzK : algebraMap (𝓞 k) k z ≠ 0 :=
    (map_ne_zero_iff _ (FaithfulSMul.algebraMap_injective (𝓞 k) k)).mpr hz0
  refine ⟨Units.mk0 (algebraMap (𝓞 k) k y / algebraMap (𝓞 k) k z) (div_ne_zero hyK hzK), ?_⟩
  intro w hw
  rw [Units.val_mk0, placeOrd_div w hyK hzK, placeOrd_algebraMap w hy0,
    placeOrd_algebraMap w hz0, hy w hw, hz w hw]
  omega

/-- **Any element of a number field can be corrected to have order zero at each of finitely many
finite places.** -/
theorem exists_placeOrd_mul_eq_zero (s : Finset (HeightOneSpectrum (𝓞 k))) (a : kˣ) :
    ∃ x : kˣ, ∀ w ∈ s, placeOrd w ((a * x : kˣ) : k) = 0 := by
  obtain ⟨x, hx⟩ := exists_placeOrd_eq s fun w => -placeOrd w (a : k)
  refine ⟨x, fun w hw => ?_⟩
  rw [Units.val_mul, placeOrd_mul w a.ne_zero x.ne_zero, hx w hw, add_neg_cancel]

end NumberField

end InverseGalois.CFT
