/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.CyclicProduct
import InverseGalois.CFT.Brauer.PlaceRadical

/-!
# The local invariant of a radical cyclic algebra is the power residue symbol

Let `K / k` be a cyclic extension of number fields of prime degree `n`, cut out by a radical: an
element `β` of `K` whose `n`-th power is a unit `b` of the base, and which a chosen generator of
the Galois group multiplies by a primitive `n`-th root of unity of the base.  Then at **every**
finite place of the base the invariant of the cyclic algebra with coefficient `a` is the inverse of
the power residue symbol of `a` against `b`, computed in the completion there.

The degree being prime is what makes the statement uniform.  A decomposition group is a subgroup of
a group of prime order, so it is everything or it is trivial.  When it is everything the completion
of the extension is again generated by the radical, and the invariant is the symbol against the
power of that radical.  When it is trivial the completion of the extension is the completion of the
base, so on the one hand the coefficient is trivially a local norm and the invariant vanishes, and
on the other hand the radicand is a local `n`-th power and the symbol is trivial as well.

## Main results

* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_eq_one_of_card_gal_eq_one`: a cyclic algebra
  has trivial invariant at a place where the extension splits completely.
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_of_globalRadical`: **at a place where the
  extension does not split at all, the invariant of a cyclic algebra presented by a global radical
  is the inverse of the power residue symbol of its coefficient against the radicand.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_eq_inv_localSymbol`: **for a cyclic extension
  of prime degree presented by a radical, the invariant of a cyclic algebra at any finite place is
  the inverse of the power residue symbol of its coefficient against the radicand.**

## Tags

Brauer group, cyclic algebra, local invariant, power residue symbol, Hilbert symbol, radical
extension, decomposition group, class field theory
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open IsDedekindDomain Module MulAction NumberField

/-! ### A place at which the extension splits completely -/

section PlaceSymbol

attribute [local instance] isGalois_adicCompletion

variable {k K : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K] (w : HeightOneSpectrum (𝓞 K)) {p e n : ℕ} [NeZero n]

variable (k) in
/-- The completion of an extension at a place whose Galois group is trivial is the completion of
the base. -/
theorem finrank_adicCompletion_eq_one_of_card_gal_eq_one
    (hcard : Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) = 1) :
    finrank ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) = 1 := by
  rw [← IsGalois.card_aut_eq_finrank]
  exact hcard

variable (k) in
/-- Every element of the completion of an extension at a place where it splits completely comes
from the completion of the base. -/
theorem exists_algebraMap_adicCompletion_eq_of_card_gal_eq_one
    (hcard : Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) = 1)
    (x : w.adicCompletion K) :
    ∃ c : (primeUnder (𝓞 k) w).adicCompletion k,
      algebraMap ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) c = x := by
  obtain ⟨c, hc⟩ := (finrank_eq_one_iff_of_nonzero' (K := (primeUnder (𝓞 k) w).adicCompletion k)
    (1 : w.adicCompletion K) one_ne_zero).1
      (finrank_adicCompletion_eq_one_of_card_gal_eq_one k w hcard) x
  exact ⟨c, by rw [← hc, Algebra.smul_def, mul_one]⟩

variable (k) in
/-- A cyclic algebra has trivial invariant at a finite place where its splitting field splits
completely: the coefficient is its own norm from a trivial extension. -/
theorem placeInvariant_cyclicBrauerHom_eq_one_of_card_gal_eq_one {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    (hcard : Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) = 1)
    (a : kˣ) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a) = 1 := by
  rw [placeInvariant_cyclicBrauerHom_eq_one_iff k w hσ₀ a]
  refine ⟨Units.map (algebraMap ((primeUnder (𝓞 k) w).adicCompletion k)
      (w.adicCompletion K)).toMonoidHom
      (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a), ?_⟩
  show Algebra.norm ((primeUnder (𝓞 k) w).adicCompletion k)
      (algebraMap ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K)
        (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) (a : k))) = _
  rw [Algebra.norm_algebraMap, finrank_adicCompletion_eq_one_of_card_gal_eq_one k w hcard, pow_one]

/-! ### A place at which the extension does not split -/

variable (k) in
/-- **At a place where the extension does not split, the invariant of a cyclic algebra presented by
a global radical is the inverse of the power residue symbol of its coefficient against the
radicand.**  The decomposition group is the whole Galois group, so the completion of the extension
is generated by the image of the radical, which is a radical for the image of the radicand. -/
theorem placeInvariant_cyclicBrauerHom_of_globalRadical
    (hres : HasResidueChar ((primeUnder (𝓞 k) w).adicCompletion k) p e)
    {ζ : k} (hζ : IsPrimitiveRoot ζ n) {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    (hdeg : Nat.card Gal(K/k) = n)
    (hcard : Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) = n)
    {b : kˣ} {β : K} (hpow : β ^ n = algebraMap k K (b : k))
    (hact : σ₀ β = algebraMap k K ζ * β) (a : kˣ) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a)
      = (localSymbol hres
          (isUnitValGen_one (valued_adicCompletion_surjective (primeUnder (𝓞 k) w)))
          (hζ.map_of_injective
            (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).injective)
          (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a)
          (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom b))⁻¹ := by
  obtain ⟨σ, hσ, hrestr⟩ := exists_forall_mem_zpowers_restrictScalars_eq k w hσ₀
  have hstab : Nat.card ↥(stabilizer Gal(K/k) w) = n := by
    rw [← hcard]
    exact Nat.card_congr
      ((decompositionFieldEquiv k w).trans (localDecompositionEquiv k w).symm).toEquiv
  have hindex : (stabilizer Gal(K/k) w).index = 1 := by
    have h := Subgroup.index_mul_card (stabilizer Gal(K/k) w)
    rw [hstab, hdeg] at h
    exact Nat.eq_of_mul_eq_mul_right (Nat.pos_of_ne_zero (NeZero.ne n)) (h.trans (one_mul n).symm)
  rw [hindex, pow_one] at hrestr
  have hβ : (localDecompositionEquiv k w σ) β = σ₀ β := congrArg (fun f => f β) hrestr
  have hpow' : (algebraMap K (w.adicCompletion K) β) ^ n
      = algebraMap ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K)
        ((Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom b :
          (primeUnder (𝓞 k) w).adicCompletion k)) := by
    rw [← map_pow, hpow]
    show algebraMap K (w.adicCompletion K) (algebraMap k K (b : k))
      = algebraMap ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K)
        (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) (b : k))
    rw [← IsScalarTower.algebraMap_apply k K (w.adicCompletion K),
      ← IsScalarTower.algebraMap_apply k ((primeUnder (𝓞 k) w).adicCompletion k)
        (w.adicCompletion K)]
  have hact' : σ (algebraMap K (w.adicCompletion K) β)
      = algebraMap ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K)
          (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) ζ)
        * algebraMap K (w.adicCompletion K) β := by
    rw [algebraMap_localDecompositionEquiv k w σ β, hβ, hact, map_mul]
    congr 1
    rw [← IsScalarTower.algebraMap_apply k K (w.adicCompletion K),
      ← IsScalarTower.algebraMap_apply k ((primeUnder (𝓞 k) w).adicCompletion k)
        (w.adicCompletion K)]
  refine placeInvariant_cyclicBrauerHom_of_radical k w hres _ hσ₀ hσ ?_ hcard hpow' hact' a
  rw [hrestr, hindex, pow_one]

/-! ### Every finite place -/

variable (k) in
/-- **For a cyclic extension of prime degree presented by a radical, the invariant of a cyclic
algebra at any finite place is the inverse of the power residue symbol of its coefficient against
the radicand.**  A decomposition group of a group of prime order is everything or is trivial; in
the first case the completion of the extension is presented by the radical, and in the second both
sides are trivial, the radicand being a local power. -/
theorem placeInvariant_cyclicBrauerHom_eq_inv_localSymbol (hn : n.Prime)
    (hres : HasResidueChar ((primeUnder (𝓞 k) w).adicCompletion k) p e)
    {ζ : k} (hζ : IsPrimitiveRoot ζ n) {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    (hdeg : Nat.card Gal(K/k) = n)
    {b : kˣ} {β : K} (hpow : β ^ n = algebraMap k K (b : k))
    (hact : σ₀ β = algebraMap k K ζ * β) (a : kˣ) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a)
      = (localSymbol hres
          (isUnitValGen_one (valued_adicCompletion_surjective (primeUnder (𝓞 k) w)))
          (hζ.map_of_injective
            (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).injective)
          (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a)
          (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom b))⁻¹ := by
  have hstab : Nat.card ↥(stabilizer Gal(K/k) w)
      = Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) :=
    Nat.card_congr ((decompositionFieldEquiv k w).trans (localDecompositionEquiv k w).symm).toEquiv
  have hdvd : Nat.card Gal(w.adicCompletion K/(primeUnder (𝓞 k) w).adicCompletion k) ∣ n := by
    rw [← hstab, ← hdeg]
    exact Subgroup.card_subgroup_dvd_card _
  rcases hn.eq_one_or_self_of_dvd _ hdvd with hone | hall
  · rw [placeInvariant_cyclicBrauerHom_eq_one_of_card_gal_eq_one k w hσ₀ hone a]
    refine (inv_eq_one.2 ?_).symm
    obtain ⟨c, hc⟩ := exists_algebraMap_adicCompletion_eq_of_card_gal_eq_one k w hone
      (algebraMap K (w.adicCompletion K) β)
    have hcpow : c ^ n = algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) (b : k) := by
      refine (algebraMap ((primeUnder (𝓞 k) w).adicCompletion k)
        (w.adicCompletion K)).injective ?_
      rw [map_pow, hc, ← map_pow, hpow,
        ← IsScalarTower.algebraMap_apply k K (w.adicCompletion K),
        ← IsScalarTower.algebraMap_apply k ((primeUnder (𝓞 k) w).adicCompletion k)
          (w.adicCompletion K)]
    have hcne : c ≠ 0 := by
      intro h
      rw [h, zero_pow (NeZero.ne n)] at hcpow
      exact (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom b).ne_zero
        hcpow.symm
    exact localSymbol_eq_one_of_isPow_right hres _ _ _ ⟨Units.mk0 c hcne, Units.ext hcpow⟩
  · exact placeInvariant_cyclicBrauerHom_of_globalRadical k w hres hζ hσ₀ hdeg hall hpow hact a

end PlaceSymbol

end InverseGalois.CFT
