/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.PlaceExponent
import InverseGalois.CFT.Brauer.PlaceUnramified
import InverseGalois.CFT.Units.RatRamIdx

/-!
# The invariant of a cyclic algebra at a place away from the conductor

The local invariant of a cyclic algebra at an unramified finite place is the exponent expressing
the Frobenius as a power of the chosen generator of the Galois group, times the value of the
coefficient there, divided by the degree.  The two auxiliary objects that formula is stated with,
the generator of the Galois group of the completions and the exponent expressing the Frobenius as
one of its powers, are both produced by the extension itself, so neither has to be supplied by a
caller: what is left is the ramification index and the exponent of the Frobenius *in the global
Galois group*.

Over the rationals, and for an extension generated by a root of unity, the second of those is the
cyclotomic description of the Frobenius, and for a subfield of a cyclotomic field the first is the
unramifiedness away from the conductor.  Both are available, so the invariant at such a place is
computed by a purely global datum: the exponent of the automorphism raising the root of unity to
the power of the rational prime below the place.

## Main results

* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_eq_intQModZ_of_ramIdx_eq_one`: **at an
  unramified finite place the invariant of a cyclic algebra is the exponent of the Frobenius times
  the value of the coefficient, divided by the degree.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_eq_one_of_valued_eq_one`: **the invariant is
  trivial at an unramified finite place at which the coefficient is a unit.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_rat_of_adjoin`: over the rationals, with the
  Frobenius identified by its action on a root of unity generating the extension.
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_rat_of_adjoin_not_dvd`: the same for a place of
  a subfield of a cyclotomic field lying over a rational prime that divides neither the conductor
  nor the order of the root of unity.

## Tags

Brauer group, local invariant, cyclic algebra, Frobenius, cyclotomic field, reciprocity
-/

namespace InverseGalois.CFT

open IsDedekindDomain Module MulAction NumberField

/-! ### The invariant at an unramified place -/

section Unramified

attribute [local instance] isGalois_adicCompletion

variable {k K : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K] (w : HeightOneSpectrum (𝓞 K))

variable (k) in
/-- **At an unramified finite place the invariant of a cyclic algebra is the exponent of the
Frobenius times the value of the coefficient, divided by the degree.**  The exponent is the one
expressing the restriction of the Frobenius of the completion as a power of the chosen generator of
the Galois group of the extension. -/
theorem placeInvariant_cyclicBrauerHom_eq_intQModZ_of_ramIdx_eq_one {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀) (hram : ramIdx (𝓞 k) w = 1) {c : ℕ}
    (hc : restrictToBase k w (divisionFrobenius ((primeUnder (𝓞 k) w).adicCompletion k)
      (w.adicCompletion K)
      (fun z hz => exists_divisionNorm_eq_norm_adicCompletion k w hram z hz)) = σ₀ ^ c)
    (a : kˣ) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a)
      = Multiplicative.ofAdd (intQModZ (Nat.card Gal(K/k))
        ((c : ℤ) * placeValue (primeUnder (𝓞 k) w) a)) := by
  obtain ⟨σ, hσ, hres⟩ := exists_forall_mem_zpowers_restrictScalars_eq k w hσ₀
  obtain ⟨s, hs⟩ := exists_divisionFrobenius_eq_pow_adicCompletion k w hram hσ
  exact placeInvariant_cyclicBrauerHom_eq_intQModZ k w hσ₀ hσ hres _ hs hc a

variable (k) in
/-- **A cyclic algebra whose coefficient is a unit at an unramified finite place has trivial
invariant there.**  Only the places dividing the coefficient and the places ramified in the
extension can contribute, and neither the generator of the Galois group of the completions nor the
exponent of the local Frobenius has to be named. -/
theorem placeInvariant_cyclicBrauerHom_eq_one_of_valued_eq_one {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀) (hram : ramIdx (𝓞 k) w = 1) {a : kˣ}
    (ha : Valued.v (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) (a : k)) = 1) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a) = 1 := by
  obtain ⟨σ, hσ, hres⟩ := exists_forall_mem_zpowers_restrictScalars_eq k w hσ₀
  exact placeInvariant_cyclicBrauerHom_eq_one_of_ramIdx_eq_one k w hσ₀ hσ hres hram ha

end Unramified

/-! ### The rational prime below a place -/

section Below

variable {K : Type} [Field K] [NumberField K] (w : HeightOneSpectrum (𝓞 K))

/-- The rational prime below a place lies in the prime of the rationals below it. -/
theorem natCast_mem_primeUnder_rat {q : ℕ} [w.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] :
    ((q : ℕ) : 𝓞 ℚ) ∈ (primeUnder (𝓞 ℚ) w).asIdeal := by
  have hz : (q : ℤ) ∈ Ideal.under ℤ w.asIdeal := by
    rw [← Ideal.LiesOver.over (p := Ideal.span {(q : ℤ)}) (P := w.asIdeal)]
    exact Ideal.mem_span_singleton_self _
  rw [Ideal.under_def, Ideal.mem_comap] at hz
  rw [primeUnder_asIdeal, Ideal.under_def, Ideal.mem_comap]
  rw [map_natCast] at hz ⊢
  exact hz

end Below

/-! ### The invariant over the rationals -/

section RatCyclotomic

attribute [local instance] isGalois_adicCompletion

variable {K : Type} [Field K] [NumberField K] [IsGalois ℚ K] (w : HeightOneSpectrum (𝓞 K))

/-- **The invariant at an unramified place of a cyclic algebra over the rationals whose splitting
field is generated by a root of unity.**  The Frobenius raises the root of unity to the power of
the rational prime below the place, so the exponent in the formula is the one of that
automorphism. -/
theorem placeInvariant_cyclicBrauerHom_rat_of_adjoin {σ₀ : Gal(K/ℚ)}
    (hσ₀ : ∀ x : Gal(K/ℚ), x ∈ Subgroup.zpowers σ₀) {q : ℕ} (hq : q.Prime)
    (hqmem : ((q : ℕ) : 𝓞 ℚ) ∈ (primeUnder (𝓞 ℚ) w).asIdeal) (hram : ramIdx (𝓞 ℚ) w = 1)
    {m : ℕ} (hm : m ≠ 0) (hmv : w.valuation K ((m : ℕ) : K) = 1) {ζ : K} (hζ : ζ ^ m = 1)
    (hgen : Algebra.adjoin ℚ ({ζ} : Set K) = ⊤) {τ : Gal(K/ℚ)} (hτ : τ ζ = ζ ^ q) {c : ℕ}
    (hc : τ = σ₀ ^ c) (a : ℚˣ) :
    placeInvariant ℚ (primeUnder (𝓞 ℚ) w) (cyclicBrauerHom hσ₀ a)
      = Multiplicative.ofAdd (intQModZ (Nat.card Gal(K/ℚ))
        ((c : ℤ) * placeValue (primeUnder (𝓞 ℚ) w) a)) := by
  refine placeInvariant_cyclicBrauerHom_eq_intQModZ_of_ramIdx_eq_one ℚ w hσ₀ hram ?_ a
  rw [restrictToBase_divisionFrobenius_eq_of_adjoin_rat w hq hqmem hram hm hmv hζ hgen hτ, hc]

/-- **The invariant at a place of a subfield of a cyclotomic field away from the conductor.**  The
place is unramified over the rationals and the order of the root of unity is a unit there, so both
side conditions of the cyclotomic description of the Frobenius are automatic. -/
theorem placeInvariant_cyclicBrauerHom_rat_of_adjoin_not_dvd {σ₀ : Gal(K/ℚ)}
    (hσ₀ : ∀ x : Gal(K/ℚ), x ∈ Subgroup.zpowers σ₀) (N : ℕ) [NeZero N] (E : Type) [Field E]
    [NumberField E] [IsCyclotomicExtension {N} ℚ E] [Algebra K E] {q : ℕ} [Fact q.Prime]
    [w.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] (hqN : ¬ q ∣ N) {m : ℕ} (hm : m ≠ 0)
    (hqm : ¬ q ∣ m) {ζ : K} (hζ : ζ ^ m = 1) (hgen : Algebra.adjoin ℚ ({ζ} : Set K) = ⊤)
    {τ : Gal(K/ℚ)} (hτ : τ ζ = ζ ^ q) {c : ℕ} (hc : τ = σ₀ ^ c) (a : ℚˣ) :
    placeInvariant ℚ (primeUnder (𝓞 ℚ) w) (cyclicBrauerHom hσ₀ a)
      = Multiplicative.ofAdd (intQModZ (Nat.card Gal(K/ℚ))
        ((c : ℤ) * placeValue (primeUnder (𝓞 ℚ) w) a)) :=
  placeInvariant_cyclicBrauerHom_rat_of_adjoin w hσ₀ (Fact.out : q.Prime)
    (natCast_mem_primeUnder_rat w) (ramIdx_rat_eq_one_of_not_dvd N E q w hqN) hm
    (valuation_natCast_eq_one_of_not_dvd w hqm) hζ hgen hτ hc a

end RatCyclotomic

end InverseGalois.CFT
