/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.CyclicBaseChange
import InverseGalois.CFT.Brauer.CyclicCompositum
import InverseGalois.CFT.Brauer.CyclicGenerator
import InverseGalois.CFT.Brauer.PlaceCrossedProduct
import InverseGalois.CFT.Brauer.PlaceInvariant
import InverseGalois.CFT.Brauer.TameSymbol

/-!
# Localising a cyclic algebra at a finite place

Let `K / k` be a cyclic Galois extension of number fields with generator `σ₀`, and let `w` be a
prime of `K` lying over the prime `v` of `k`.  Completing at `v` turns the cyclic algebra
`(K / k, σ₀, a)` into a central simple algebra over the local field `k_v` split by `K_w`, and that
algebra is again cyclic, for the decomposition group at `w`, **with the same coefficient `a`**.

The passage goes through the decomposition field `F`, exactly as for a general crossed product.
Over `F` the extension `K / F` is cyclic with a generator inducing a power of `σ₀`, and the cyclic
cocycle restricts to the cyclic cocycle with the same coefficient; the degree ratio disappears into
the change of generator.  From `F` to `k_v` the fields `K` and `k_v` are linearly disjoint and
generate `K_w`, and the identification of `Gal(K_w/k_v)` with `Gal(K/F)` transports the cyclic
cocycle again without touching the coefficient.

The two steps compose to base change from `k` to `k_v`, so the whole change of invariant between
the global and the local algebra is carried by the local degree, which is where it belongs.  The
single hypothesis tying the local generator to the global one is that it induces on `K` the power
of `σ₀` by the number of primes above `v`, which is the index of the decomposition group; such a
generator always exists, because the subgroups of a finite cyclic group are the groups generated by
the divisors of the order.

## Main results

* `InverseGalois.CFT.exists_forall_mem_zpowers_restrictScalars_eq`: **the completion of a cyclic
  extension at a finite place has a generator inducing the power of the global generator by the
  index of the decomposition group.**
* `InverseGalois.CFT.baseChangeHom_cyclicBrauerHom_adicCompletion`: **extending scalars to the
  completion at a finite place sends a cyclic algebra to the cyclic algebra of the decomposition
  group with the same coefficient.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom`: **the invariant at a finite place of a cyclic
  algebra is the invariant of its coefficient, raised to the discrete logarithm of the Frobenius.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_eq_one`: **a cyclic algebra whose coefficient is
  a unit at an unramified place has trivial invariant there.**

## Tags

Brauer group, cyclic algebra, completion, decomposition group, local invariant, class field theory
-/

set_option synthInstance.maxHeartbeats 1000000

namespace InverseGalois.CFT

open IsDedekindDomain Module MulAction NumberField

/-! ### Transporting a generator along an isomorphism -/

/-- An isomorphism of groups carries a generator to a generator. -/
theorem forall_mem_zpowers_mulEquiv {A B : Type*} [Group A] [Group B] (e : A ≃* B) {g : A}
    (hg : ∀ y : A, y ∈ Subgroup.zpowers g) (y : B) : y ∈ Subgroup.zpowers (e g) := by
  obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (hg (e.symm y))
  exact Subgroup.mem_zpowers_iff.mpr ⟨j, by rw [← map_zpow e, hj, e.apply_symm_apply]⟩

/-! ### The cyclic algebra of a completion -/

section PlaceCyclic

attribute [local instance] isGalois_adicCompletion

variable {k K : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K] (w : HeightOneSpectrum (𝓞 K))

variable (k) in
/-- **The completion of a cyclic extension at a finite place has a generator inducing the power of
the global generator by the index of the decomposition group.**  The decomposition group is a
subgroup of a finite cyclic group, hence is generated by that power, and the Galois group of the
completions is the decomposition group. -/
theorem exists_forall_mem_zpowers_restrictScalars_eq {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀) :
    ∃ σ : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K,
      (∀ x : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K,
          x ∈ Subgroup.zpowers σ) ∧
        (localDecompositionEquiv k w σ).restrictScalars k
          = σ₀ ^ (stabilizer Gal(K/k) w).index := by
  have hcard : Nat.card Gal(K/k)
      = (stabilizer Gal(K/k) w).index * Nat.card ↥(stabilizer Gal(K/k) w) :=
    (Subgroup.index_mul_card _).symm
  have hstab : stabilizer Gal(K/k) w = Subgroup.zpowers (σ₀ ^ (stabilizer Gal(K/k) w).index) :=
    subgroup_eq_zpowers_pow hσ₀ _ hcard
  have hmem : σ₀ ^ (stabilizer Gal(K/k) w).index ∈ stabilizer Gal(K/k) w :=
    hstab.ge (Subgroup.mem_zpowers _)
  have hgH : ∀ y : ↥(stabilizer Gal(K/k) w),
      y ∈ Subgroup.zpowers (⟨σ₀ ^ (stabilizer Gal(K/k) w).index, hmem⟩ :
        ↥(stabilizer Gal(K/k) w)) := by
    intro y
    obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (hstab.le y.2)
    exact Subgroup.mem_zpowers_iff.mpr
      ⟨j, Subtype.ext (by rw [SubgroupClass.coe_zpow]; exact hj)⟩
  refine ⟨(localDecompositionEquiv k w).symm (decompositionFieldEquiv k w
    ⟨σ₀ ^ (stabilizer Gal(K/k) w).index, hmem⟩), ?_, ?_⟩
  · exact forall_mem_zpowers_mulEquiv (localDecompositionEquiv k w).symm
      (forall_mem_zpowers_mulEquiv (decompositionFieldEquiv k w) hgH)
  · rw [MulEquiv.apply_symm_apply]
    exact AlgEquiv.ext fun x => decompositionFieldEquiv_apply k w _ x

variable (k) in
/-- **Extending scalars to the completion at a finite place sends a cyclic algebra to the cyclic
algebra of the decomposition group with the same coefficient.**  The base change factors through
the decomposition field, over which the extension is cyclic with a generator inducing a power of
the given one, and neither step changes the coefficient. -/
theorem baseChangeHom_cyclicBrauerHom_adicCompletion {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    {σ : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K}
    (hσ : ∀ x : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K,
      x ∈ Subgroup.zpowers σ)
    (hres : (localDecompositionEquiv k w σ).restrictScalars k
      = σ₀ ^ (stabilizer Gal(K/k) w).index) (a : kˣ) :
    BrauerGroup.baseChangeHom ((primeUnder (𝓞 k) w).adicCompletion k) (cyclicBrauerHom hσ₀ a)
      = cyclicBrauerHom hσ
        (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a) := by
  have hσ₁ : ∀ x : Gal(K/↥(decompositionField k w)),
      x ∈ Subgroup.zpowers (localDecompositionEquiv k w σ) :=
    forall_mem_zpowers_mulEquiv (localDecompositionEquiv k w) hσ
  have hcard : Nat.card Gal(K/k)
      = (stabilizer Gal(K/k) w).index * Nat.card Gal(K/↥(decompositionField k w)) := by
    rw [← Nat.card_congr (decompositionFieldEquiv k w).toEquiv]
    exact (Subgroup.index_mul_card _).symm
  have hmap : Units.map
        (algebraMap ↥(decompositionField k w)
          ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom
        (Units.map (algebraMap k ↥(decompositionField k w)).toMonoidHom a)
      = Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a := by
    ext
    exact (IsScalarTower.algebraMap_apply k ↥(decompositionField k w)
      ((primeUnder (𝓞 k) w).adicCompletion k) (a : k)).symm
  rw [← BrauerGroup.baseChangeHom_comp k ↥(decompositionField k w)
      ((primeUnder (𝓞 k) w).adicCompletion k), MonoidHom.coe_comp, Function.comp_apply,
    baseChangeHom_cyclicBrauerHom ↥(decompositionField k w) hσ₀ hσ₁ hres hcard a,
    baseChangeHom_cyclicBrauerHom_compositum hσ₁ hσ rfl
      (algebraMap_localDecompositionEquiv k w), hmap]

variable (k) in
/-- **The invariant at a finite place of a cyclic algebra is the invariant of its coefficient,
raised to the discrete logarithm of the Frobenius automorphism of the completed extension.**  This
is the local formula `inv_v (K/k, σ₀, a) = s · v(a) / n_v`, with `s` the exponent expressing the
Frobenius as a power of the chosen generator of the decomposition group. -/
theorem placeInvariant_cyclicBrauerHom {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    {σ : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K}
    (hσ : ∀ x : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K,
      x ∈ Subgroup.zpowers σ)
    (hres : (localDecompositionEquiv k w σ).restrictScalars k
      = σ₀ ^ (stabilizer Gal(K/k) w).index)
    (hur : ∀ z : w.adicCompletion K, z ≠ 0 → ∃ c : (primeUnder (𝓞 k) w).adicCompletion k,
      c ≠ 0 ∧ divisionNorm ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) z = ‖c‖)
    {s : ℕ}
    (hs : divisionFrobenius ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) hur
      = σ ^ s) (a : kˣ) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a)
      = baseInvariant
          (isUnitValGen_one (valued_adicCompletion_surjective (primeUnder (𝓞 k) w)))
          (finrank ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K))
          (Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a) ^ s := by
  set hm := isUnitValGen_one (valued_adicCompletion_surjective (primeUnder (𝓞 k) w)) with hmdef
  set b := Units.map (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k)).toMonoidHom a with hbdef
  rw [placeInvariant_apply,
    baseChangeHom_cyclicBrauerHom_adicCompletion k w hσ₀ hσ hres a,
    localInvariantHom_apply_of_unramified hm hur
      ⟨cyclicBrauerHom hσ b, cyclicBrauerHom_mem_relative hσ b⟩]
  exact localInvariant_cyclicBrauerHom_pow hur hm hσ hs b

variable (k) in
/-- **A cyclic algebra whose coefficient is a unit at an unramified place has trivial invariant
there.**  Only the places dividing the coefficient and the ramified places can contribute to the
sum of the invariants. -/
theorem placeInvariant_cyclicBrauerHom_eq_one {σ₀ : Gal(K/k)}
    (hσ₀ : ∀ x : Gal(K/k), x ∈ Subgroup.zpowers σ₀)
    {σ : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K}
    (hσ : ∀ x : w.adicCompletion K ≃ₐ[(primeUnder (𝓞 k) w).adicCompletion k] w.adicCompletion K,
      x ∈ Subgroup.zpowers σ)
    (hres : (localDecompositionEquiv k w σ).restrictScalars k
      = σ₀ ^ (stabilizer Gal(K/k) w).index)
    (hur : ∀ z : w.adicCompletion K, z ≠ 0 → ∃ c : (primeUnder (𝓞 k) w).adicCompletion k,
      c ≠ 0 ∧ divisionNorm ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) z = ‖c‖)
    {s : ℕ}
    (hs : divisionFrobenius ((primeUnder (𝓞 k) w).adicCompletion k) (w.adicCompletion K) hur
      = σ ^ s) {a : kˣ}
    (ha : Valued.v (algebraMap k ((primeUnder (𝓞 k) w).adicCompletion k) (a : k)) = 1) :
    placeInvariant k (primeUnder (𝓞 k) w) (cyclicBrauerHom hσ₀ a) = 1 := by
  rw [placeInvariant_cyclicBrauerHom k w hσ₀ hσ hres hur hs a, baseInvariant_apply,
    unitInvariant_apply, unitValDiv_eq_zero_of_valued_eq_one _ ha, Int.cast_zero, zero_div]
  exact one_pow s

end PlaceCyclic

end InverseGalois.CFT
