/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.CyclicTower
import InverseGalois.CFT.Brauer.CyclotomicFrobenius
import InverseGalois.CFT.Brauer.PlaceTotallyRamified
import InverseGalois.CFT.Local.RatUniformiser

/-!
# The invariant at a place of a subfield of a cyclotomic field

The invariant of a cyclic algebra over the rationals at a place away from the conductor is known
when the splitting field is the cyclotomic field itself, because the Frobenius is then the
automorphism raising the roots of unity to the power of the rational prime below the place.  A
subfield of a cyclotomic field inherits the computation through the compatibility of cyclic
algebras along a tower: the cyclic algebra of the subfield for the restricted generator is the
cyclic algebra of the cyclotomic field for the coefficient raised to the relative degree.

Raising the coefficient to the relative degree multiplies its value at the place by that degree,
and the degree of the cyclotomic field is the degree of the subfield times the same relative
degree, so the two factors cancel in the rationals modulo the integers and the answer is the one
the subfield alone would predict.  This is what makes the totally real subfield of the cyclotomic
field of a prime conductor usable in the reciprocity computation, even though no root of unity
generates it.

The coefficient of interest is a rational prime, and the place of interest is the one attached to
it.  A rational prime is a uniformiser of the completion at that place, and the value group of the
completion is generated by one step, so its value there is minus one and the formula collapses to
the exponent alone, with a sign.  That sign is what cancels against the ramified place.

## Main results

* `InverseGalois.CFT.placeValue_pow`: the value at a place of a power of a unit.
* `InverseGalois.CFT.intQModZ_mul_natCast`: cancelling a common factor from a fraction taken
  modulo the integers.
* `InverseGalois.CFT.placeValue_ratPlace`: **a rational prime has value minus one at the place
  attached to it.**
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_subcyclotomic`: **the invariant of a cyclic
  algebra over the rationals, split by a subfield of a cyclotomic field, at a place away from the
  conductor**, in terms of the exponent expressing the automorphism raising the roots of unity to
  the power of the rational prime below the place as a power of the chosen generator.
* `InverseGalois.CFT.placeInvariant_cyclicBrauerHom_subcyclotomic_ratPlace`: the same invariant for
  a coefficient equal to the rational prime below the place, where only the exponent survives.

## Tags

cyclotomic field, subfield, Brauer group, local invariant, cyclic algebra, tower, reciprocity
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

/-! ### Two arithmetic reductions -/

section Arith

variable {k : Type} [Field k] [NumberField k]

/-- **The value at a place of a power of a unit** is the multiple of its value. -/
theorem placeValue_pow (v : HeightOneSpectrum (𝓞 k)) (a : kˣ) (d : ℕ) :
    placeValue v (a ^ d) = d * placeValue v a := by
  rw [placeValue_def, placeValue_def, map_pow, ofMul_pow, map_nsmul, nsmul_eq_mul]

/-- **A common factor cancels from a fraction taken modulo the integers.** -/
theorem intQModZ_mul_natCast (n : ℕ) {d : ℕ} (hd : d ≠ 0) (j : ℤ) :
    intQModZ (n * d) (j * (d : ℤ)) = intQModZ n j := by
  have hd' : ((d : ℚ)) ≠ 0 := Nat.cast_ne_zero.mpr hd
  rw [intQModZ_apply, intQModZ_apply]
  congr 1
  push_cast
  rcases eq_or_ne ((n : ℚ)) 0 with hn | hn
  · rw [hn, zero_mul, div_zero, div_zero]
  · field_simp

/-- **A unit whose image in the completion is a uniformiser has value minus one at the place.** -/
theorem placeValue_eq_neg_one_of_valued (v : HeightOneSpectrum (𝓞 k)) {a : kˣ}
    (ha : Valued.v (algebraMap k (v.adicCompletion k) (a : k)) = WithZero.exp (-1 : ℤ)) :
    placeValue v a = -1 := by
  rw [placeValue_def]
  exact unitValDiv_eq_neg_one_of_valued_eq_exp_neg_one (valued_adicCompletion_surjective v)
    (by simpa using ha)

end Arith

/-! ### The value of a rational prime at the place it determines -/

section RatValue

variable {p : ℕ}

/-- **A rational prime has value minus one at a place of the rationals above it**, because it is a
uniformiser of the completion there. -/
theorem placeValue_eq_neg_one_of_liesOver (hp : p.Prime) (v : HeightOneSpectrum (𝓞 ℚ))
    [v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] {a : ℚˣ} (hap : (a : ℚ) = ((p : ℕ) : ℚ)) :
    placeValue v a = -1 := by
  refine placeValue_eq_neg_one_of_valued v ?_
  rw [hap, map_natCast]
  exact valued_natCast_adicCompletion_rat hp v

/-- **A rational prime has value minus one at the place attached to it.** -/
theorem placeValue_ratPlace (hp : p.Prime) {a : ℚˣ} (hap : (a : ℚ) = ((p : ℕ) : ℚ)) :
    placeValue (ratPlace p hp) a = -1 :=
  haveI := liesOver_span_of_natCast_mem hp (ratPlace p hp) (natCast_mem_ratPlace p hp)
  placeValue_eq_neg_one_of_liesOver hp _ hap

end RatValue

/-! ### The invariant at a place of a subfield of a cyclotomic field -/

section Subcyclotomic

attribute [local instance] isGalois_adicCompletion

variable (n : ℕ) [NeZero n] (L F : Type) [Field L] [NumberField L]
  [IsCyclotomicExtension {n} ℚ L] [IsGalois ℚ L] [Field F] [NumberField F] [Algebra F L]
  [IsScalarTower ℚ F L] [IsGalois ℚ F]

/-- **The invariant of a cyclic algebra over the rationals, split by a subfield of a cyclotomic
field, at a place of the cyclotomic field away from the conductor.**  The cyclic algebra of the
subfield for the restricted generator is the cyclic algebra of the cyclotomic field for the
coefficient raised to the relative degree, and the relative degree cancels between the value of
that power and the degree of the cyclotomic field. -/
theorem placeInvariant_cyclicBrauerHom_subcyclotomic {σ : Gal(L/ℚ)}
    (hσ : ∀ x : Gal(L/ℚ), x ∈ Subgroup.zpowers σ) (W : HeightOneSpectrum (𝓞 L)) {q : ℕ}
    [hq : Fact q.Prime] [W.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] (hqn : Nat.Coprime q n) {c : ℕ}
    (hc : cyclotomicPowerAut n L hqn = σ ^ c) (a : ℚˣ) :
    placeInvariant ℚ (primeUnder (𝓞 ℚ) W)
        (cyclicBrauerHom (forall_mem_zpowers_restrictNormal (L := F) hσ) a)
      = Multiplicative.ofAdd (intQModZ (Nat.card Gal(F/ℚ))
        ((c : ℤ) * placeValue (primeUnder (𝓞 ℚ) W) a)) := by
  haveI : Module.Finite F L := FiniteDimensional.right ℚ F L
  have hd : Module.finrank F L ≠ 0 := Module.finrank_pos.ne'
  have hfin : Module.finrank ℚ F * Module.finrank F L = Module.finrank ℚ L :=
    Module.finrank_mul_finrank ℚ F L
  have key : (c : ℤ) * placeValue (primeUnder (𝓞 ℚ) W) (a ^ Module.finrank F L)
      = ((c : ℤ) * placeValue (primeUnder (𝓞 ℚ) W) a) * (Module.finrank F L : ℤ) := by
    rw [placeValue_pow]
    ring
  rw [cyclicBrauerHom_restrictNormal hσ a,
    placeInvariant_cyclicBrauerHom_cyclotomic n L hσ W hqn hc (a ^ Module.finrank F L), key,
    IsGalois.card_aut_eq_finrank ℚ L, ← hfin, IsGalois.card_aut_eq_finrank ℚ F,
    intQModZ_mul_natCast _ hd]

/-- **The invariant of a cyclic algebra over the rationals, split by a subfield of a cyclotomic
field, at the place attached to its coefficient**, when that coefficient is the rational prime
below a place of the cyclotomic field away from the conductor.  The coefficient is a uniformiser
there, so its value is minus one and the exponent of the Frobenius is all that is left. -/
theorem placeInvariant_cyclicBrauerHom_subcyclotomic_ratPlace {σ : Gal(L/ℚ)}
    (hσ : ∀ x : Gal(L/ℚ), x ∈ Subgroup.zpowers σ) (W : HeightOneSpectrum (𝓞 L)) {q : ℕ}
    [hq : Fact q.Prime] [W.asIdeal.LiesOver (Ideal.span {(q : ℤ)})] (hqn : Nat.Coprime q n) {c : ℕ}
    (hc : cyclotomicPowerAut n L hqn = σ ^ c) {a : ℚˣ} (haq : (a : ℚ) = ((q : ℕ) : ℚ)) :
    placeInvariant ℚ (ratPlace q hq.out)
        (cyclicBrauerHom (forall_mem_zpowers_restrictNormal (L := F) hσ) a)
      = Multiplicative.ofAdd (intQModZ (Nat.card Gal(F/ℚ)) (-(c : ℤ))) := by
  have hpv : placeValue (primeUnder (𝓞 ℚ) W) a = -1 := by
    rw [primeUnder_eq_ratPlace hq.out W]
    exact placeValue_ratPlace hq.out haq
  rw [← primeUnder_eq_ratPlace hq.out W,
    placeInvariant_cyclicBrauerHom_subcyclotomic n L F hσ W hqn hc a, hpv, mul_neg_one]

end Subcyclotomic

end InverseGalois.CFT
