import Mathlib
import InverseGalois.CFT.Brauer.GaloisSplitting
import InverseGalois.CFT.Brauer.H2Surjective
import InverseGalois.CFT.Brauer.RealBrauer

/-!
# Primary decomposition of the Brauer group

Every element of a torsion abelian group is a product of elements of prime power order: writing
the order `n` of an element `g` as `p ^ k * m` with `p` prime and `p ∤ m`, a Bézout relation
`a * p ^ k + b * m = 1` expresses `g` as `(g ^ p ^ k) ^ a * (g ^ m) ^ b`, where the second factor
is `p`-primary and the first has order dividing `m < n`.  Iterating, the `p`-primary components
of a torsion abelian group generate it.  Mathlib provides `CommGroup.primaryComponent` but no
such generation statement, so it is proved here.

Over a perfect field the Brauer group is torsion, so this applies verbatim: `Br(K)` is generated
by its `p`-primary components.  Two complements make the decomposition useful.  First, a finite
Galois extension `L / K` kills the relative Brauer group `Br(L / K)` in degree `[L : K]`, so a
class split by `L` whose order is a power of a prime `p` not dividing `[L : K]` is trivial:
splitting by an extension of degree prime to `p` sees nothing `p`-primary.  Second, the Brauer
group of the reals has order two, hence is entirely `2`-primary and has vanishing `p`-primary
component for every odd prime `p`.

## Main results

* `InverseGalois.CFT.eq_one_of_pow_eq_one_of_coprime`: an element of an abelian group killed by
  two coprime exponents is trivial.
* `InverseGalois.CFT.mem_primaryComponent_of_orderOf_dvd_pow`: an element whose order divides a
  power of `p` lies in the `p`-primary component.
* `InverseGalois.CFT.iSup_primaryComponent_eq_top`: **the primary components of a torsion abelian
  group generate it**.
* `InverseGalois.CFT.iSup_primaryComponent_brauerGroup_eq_top`: **the Brauer group of a perfect
  field is generated by its primary components**.
* `InverseGalois.CFT.eq_one_of_mem_relative_of_coprime`: **a `p`-primary class split by a finite
  Galois extension of degree prime to `p` is trivial**.
* `InverseGalois.CFT.primaryComponent_brauerGroup_real_two` and
  `InverseGalois.CFT.primaryComponent_brauerGroup_real_eq_bot`: **the Brauer group of the reals
  is `2`-primary**.

## Tags

Brauer group, primary component, torsion abelian group, prime power order
-/

namespace InverseGalois.CFT

variable {G : Type*} [CommGroup G]

/-! ### Coprime exponents -/

/-- **Coprime exponents force triviality.**  If an element of an abelian group is killed by two
coprime natural numbers, its order divides their greatest common divisor, which is `1`. -/
theorem eq_one_of_pow_eq_one_of_coprime {G : Type*} [CommGroup G] {g : G} {m n : ℕ}
    (hmn : Nat.Coprime m n) (hm : g ^ m = 1) (hn : g ^ n = 1) : g = 1 := by
  have h1 : orderOf g ∣ Nat.gcd m n :=
    Nat.dvd_gcd (orderOf_dvd_of_pow_eq_one hm) (orderOf_dvd_of_pow_eq_one hn)
  rw [hmn] at h1
  exact orderOf_eq_one_iff.mp (Nat.dvd_one.mp h1)

/-- **A divisor of a prime power is a prime power.**  Hence an element whose order divides
`p ^ k` belongs to the `p`-primary component. -/
theorem mem_primaryComponent_of_orderOf_dvd_pow {p k : ℕ} [Fact p.Prime] {g : G}
    (h : orderOf g ∣ p ^ k) : g ∈ CommGroup.primaryComponent G p := by
  obtain ⟨j, _, hj⟩ := (Nat.dvd_prime_pow (Fact.out : p.Prime)).mp h
  exact ⟨j, hj⟩

/-! ### Primary decomposition of a torsion abelian group -/

/-- **The primary components of a torsion abelian group generate it.**  Strong induction on the
exponent killing an element: splitting that exponent as `p ^ k * m` at its least prime factor,
a Bézout relation writes the element as a product of a `p`-primary power and a power killed by
the strictly smaller exponent `m`. -/
theorem iSup_primaryComponent_eq_top (h : Monoid.IsTorsion G) :
    (⨆ p : Nat.Primes, @CommGroup.primaryComponent G _ p.1 (Fact.mk p.2)) = ⊤ := by
  set S : Subgroup G := ⨆ p : Nat.Primes, @CommGroup.primaryComponent G _ p.1 (Fact.mk p.2)
  have key : ∀ n : ℕ, ∀ g : G, n ≠ 0 → g ^ n = 1 → g ∈ S := by
    intro n
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      intro g hn hgn
      rcases eq_or_lt_of_le (Nat.one_le_iff_ne_zero.mpr hn) with h1 | h1
      · rw [← h1, pow_one] at hgn
        exact hgn ▸ one_mem S
      · set p := n.minFac
        have hpp : p.Prime := Nat.minFac_prime (by omega)
        haveI : Fact p.Prime := Fact.mk hpp
        set k := n.factorization p with hk
        set q := p ^ k
        set m := n / q
        have hqm : q * m = n := Nat.ordProj_mul_ordCompl_eq_self n p
        have hcop : Nat.Coprime q m := Nat.Coprime.pow_left k (Nat.coprime_ordCompl hpp hn)
        have hm0 : m ≠ 0 := by
          intro hcon
          rw [hcon, mul_zero] at hqm
          exact hn hqm.symm
        have hk1 : 1 ≤ k := by
          rw [hk]
          exact Nat.Prime.factorization_pos_of_dvd hpp hn (Nat.minFac_dvd n)
        have hq2 : 2 ≤ q := by
          calc 2 ≤ p := hpp.two_le
          _ = p ^ 1 := (pow_one p).symm
          _ ≤ p ^ k := Nat.pow_le_pow_right hpp.pos hk1
        have hmn : m < n := by
          rw [← hqm]
          nlinarith [Nat.pos_of_ne_zero hm0]
        have hA : g ^ m ∈ S := by
          refine Subgroup.mem_iSup_of_mem ⟨p, hpp⟩ ?_
          refine mem_primaryComponent_of_orderOf_dvd_pow (k := k) (orderOf_dvd_of_pow_eq_one ?_)
          rw [← pow_mul, mul_comm m q, hqm, hgn]
        have hB : g ^ q ∈ S := by
          refine ih m hmn (g ^ q) hm0 ?_
          rw [← pow_mul, hqm, hgn]
        have hbez : (1 : ℤ) = (q : ℤ) * Nat.gcdA q m + (m : ℤ) * Nat.gcdB q m := by
          have hg := Nat.gcd_eq_gcd_ab q m
          rwa [hcop, Nat.cast_one] at hg
        have hsplit : g = (g ^ q) ^ (Nat.gcdA q m) * (g ^ m) ^ (Nat.gcdB q m) := by
          rw [← zpow_natCast g q, ← zpow_natCast g m, ← zpow_mul, ← zpow_mul, ← zpow_add,
            ← hbez, zpow_one]
        rw [hsplit]
        exact mul_mem (Subgroup.zpow_mem S hB _) (Subgroup.zpow_mem S hA _)
  rw [eq_top_iff]
  intro g _
  obtain ⟨n, hn, hgn⟩ := isOfFinOrder_iff_pow_eq_one.mp (h g)
  exact key n g (by omega) hgn

/-! ### The Brauer group of a perfect field -/

/-- **The Brauer group of a perfect field is generated by its primary components.**  The Brauer
group of a perfect field is torsion, so the primary decomposition of a torsion abelian group
applies. -/
theorem iSup_primaryComponent_brauerGroup_eq_top {K : Type} [Field K] [PerfectField K] :
    (⨆ p : Nat.Primes,
      @CommGroup.primaryComponent (BrauerGroup K) _ p.1 (Fact.mk p.2)) = ⊤ :=
  iSup_primaryComponent_eq_top isTorsion_brauerGroup

/-- **Splitting by an extension of degree prime to `p` kills the `p`-primary part.**  A class in
the relative Brauer group of a finite Galois extension `L / K` is killed by `[L : K]`, while a
`p`-primary class is killed by a power of `p`; if `p` does not divide `[L : K]` these two
exponents are coprime. -/
theorem eq_one_of_mem_relative_of_coprime {K L : Type} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [IsGalois K L] {p : ℕ} [Fact p.Prime]
    (hp : ¬ p ∣ Module.finrank K L) (x : BrauerGroup K)
    (hx : x ∈ BrauerGroup.relative K L)
    (hxp : x ∈ CommGroup.primaryComponent (BrauerGroup K) p) : x = 1 := by
  obtain ⟨k, hk⟩ := hxp
  have h1 : x ^ p ^ k = 1 := by rw [← hk]; exact pow_orderOf_eq_one x
  have h2 : x ^ Module.finrank K L = 1 := pow_finrank_eq_one_of_mem_relative x hx
  have hcop : Nat.Coprime (p ^ k) (Module.finrank K L) :=
    Nat.Coprime.pow_left k ((Nat.Prime.coprime_iff_not_dvd Fact.out).mpr hp)
  exact eq_one_of_pow_eq_one_of_coprime hcop h1 h2

/-! ### The real place is `2`-primary -/

/-- **The Brauer group of the reals is its own `2`-primary component.**  Every real Brauer class
squares to one, so its order divides `2`. -/
theorem primaryComponent_brauerGroup_real_two :
    CommGroup.primaryComponent (BrauerGroup.{0, 0} ℝ) 2 = ⊤ := by
  rw [eq_top_iff]
  intro x _
  exact mem_primaryComponent_of_orderOf_dvd_pow (k := 1)
    (by simpa using orderOf_dvd_of_pow_eq_one (sq_eq_one_brauerGroup_real x))

/-- **The odd primary components of the real Brauer group vanish.**  A `p`-primary real Brauer
class is killed both by a power of an odd prime `p` and by `2`, two coprime exponents. -/
theorem primaryComponent_brauerGroup_real_eq_bot {p : ℕ} [Fact p.Prime] (hp : p ≠ 2) :
    CommGroup.primaryComponent (BrauerGroup.{0, 0} ℝ) p = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  obtain ⟨k, hk⟩ := hx
  have h1 : x ^ p ^ k = 1 := by rw [← hk]; exact pow_orderOf_eq_one x
  have hcop : Nat.Coprime (p ^ k) 2 :=
    Nat.Coprime.pow_left k ((Nat.coprime_primes Fact.out Nat.prime_two).mpr hp)
  exact Subgroup.mem_bot.mpr
    (eq_one_of_pow_eq_one_of_coprime hcop h1 (sq_eq_one_brauerGroup_real x))

end InverseGalois.CFT
