/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.SymbolCyclicAlgebra
import InverseGalois.CFT.Profinite.KummerLevel

/-!
# A level presented by a radical

A cyclic extension of degree `n` of a base containing a primitive `n`-th root of unity is often
handed over in radical form: an element of the extension whose `n`-th power lies in the base, and a
generator of the Galois group which multiplies that element by the root of unity.  The Kummer
theory of the separable closure instead presents the same extension through a chosen `n`-th root of
the unit, and through the character recording by which root of unity an automorphism moves it.

The two presentations agree.  The radical and the chosen root have the same `n`-th power, so their
ratio is a root of unity of the base; an automorphism therefore moves them by the same root of
unity.  On the radical that root of unity is named by the discrete logarithm of the restriction to
the level, and on the chosen root by the Kummer character, so the two natural numbers coincide.

That equality is exactly the hypothesis under which the power residue symbol of a pair of units is
the class of a cyclic algebra, so a level offered in radical form can be fed to the symbol without
first being identified with the level generated by the chosen root.

## Main results

* `InverseGalois.CFT.aut_pow_apply_eq_algebraMap_pow_mul`: an iterate of an automorphism which
  scales an element by a root of unity of the base scales it by the matching power.
* `InverseGalois.CFT.dlog_eq_kummerChar_of_radical`: **the discrete logarithm of a level presented
  by a radical computes the Kummer character of the `n`-th power of the radical.**

## Tags

Kummer theory, radical extension, cyclic extension, discrete logarithm, power residue symbol,
cyclic algebra, class field theory
-/

namespace InverseGalois.CFT

open groupCohomology

/-! ### The unit attached to a root of unity -/

section RootUnit

variable {k : Type*} [Field k] {n : ℕ} [NeZero n] {ζ : k}

/-- The unit attached to a primitive root of unity of a field has that root of unity as its
value. -/
theorem coe_primitiveRootUnit (hζ : IsPrimitiveRoot ζ n) :
    ((primitiveRootUnit hζ : kˣ) : k) = ζ := rfl

end RootUnit

/-! ### A level presented by a radical -/

section RadicalLevel

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω] {n : ℕ} [NeZero n]
  {ζ : k} {hζ : IsPrimitiveRoot ζ n}

attribute [local instance] zmodTrivialAction isSmoothAction_zmod

omit [IsGalois k Ω] in
/-- The chosen root of unity of the extension is the image of the root of unity of the base. -/
theorem coe_kummerRootUnit : ((kummerRootUnit Ω hζ : Ωˣ) : Ω) = algebraMap k Ω ζ := by
  show ((Units.map (algebraMap k Ω : k →* Ω) (primitiveRootUnit hζ) : Ωˣ) : Ω) = algebraMap k Ω ζ
  rw [Units.coe_map, MonoidHom.coe_coe, coe_primitiveRootUnit]

variable (h : IsKummerData k Ω (Multiplicative (ZMod n)) (zmodRootHom hζ) n)
  (E : IntermediateField k Ω) [FiniteDimensional k ↥E] [IsGalois k ↥E] {σ₀ : Gal(↥E/k)}

omit [IsGalois k Ω] [NeZero n] [FiniteDimensional k ↥E] [IsGalois k ↥E] in
/-- **An iterate of an automorphism which scales an element by a root of unity of the base scales
it by the matching power of that root of unity.** -/
theorem aut_pow_apply_eq_algebraMap_pow_mul {ν : ↥E} (hact : σ₀ ν = algebraMap k ↥E ζ * ν)
    (j : ℕ) : (σ₀ ^ j) ν = algebraMap k ↥E ζ ^ j * ν := by
  induction j with
  | zero => rw [pow_zero, pow_zero, one_mul, AlgEquiv.one_apply]
  | succ j ih =>
    rw [pow_succ, AlgEquiv.mul_apply, hact, map_mul, AlgEquiv.commutes, ih, pow_succ]
    ring

/-- **A level presented by a radical computes the Kummer character of the `n`-th power of the
radical.**  The radical and the chosen root of its `n`-th power differ by a root of unity of the
base, so an automorphism multiplies the two by the same root of unity: on the radical that root of
unity is named by the discrete logarithm of the restriction to the level, on the chosen root by the
Kummer character. -/
theorem dlog_eq_kummerChar_of_radical {b : kˣ} {ν : ↥E}
    (hσ₀ : ∀ x : Gal(↥E/k), x ∈ Subgroup.zpowers σ₀) (hcard : Nat.card Gal(↥E/k) = n)
    (hpow : algebraMap ↥E Ω ν ^ n = algebraMap k Ω (b : k))
    (hact : σ₀ ν = algebraMap k ↥E ζ * ν) (g : Gal(Ω/k)) :
    (dlog σ₀ (AlgEquiv.restrictNormalHom ↥E g)).val = (kummerChar h b g).val := by
  haveI : Fintype Gal(↥E/k) := AlgEquiv.fintype k ↥E
  have hzΩ : IsPrimitiveRoot (algebraMap k Ω ζ) n :=
    hζ.map_of_injective (f := (algebraMap k Ω : k →+* Ω)) (algebraMap k Ω).injective
  have hb0 : algebraMap k Ω (b : k) ≠ 0 := by
    rw [Ne, map_eq_zero_iff _ (algebraMap k Ω).injective]
    exact b.ne_zero
  have hx0 : algebraMap ↥E Ω ν ≠ 0 := by
    intro hx
    rw [hx, zero_pow (NeZero.ne n)] at hpow
    exact hb0 hpow.symm
  have hrpow : ((h.root b : Ωˣ) : Ω) ^ n = algebraMap k Ω (b : k) :=
    congrArg Units.val (h.root_pow b)
  have hquot : (((h.root b : Ωˣ) : Ω) * (algebraMap ↥E Ω ν)⁻¹) ^ n = 1 := by
    rw [mul_pow, inv_pow, hrpow, hpow, mul_inv_cancel₀ hb0]
  obtain ⟨j, -, hj⟩ := hzΩ.eq_pow_of_pow_eq_one hquot
  have hrj : ((h.root b : Ωˣ) : Ω) = algebraMap k Ω ζ ^ j * algebraMap ↥E Ω ν := by
    rw [hj, inv_mul_cancel_right₀ hx0]
  have hgr : g ((h.root b : Ωˣ) : Ω)
      = algebraMap k Ω ζ ^ (kummerChar h b g).val * ((h.root b : Ωˣ) : Ω) := by
    have hs := congrArg Units.val (smul_root_eq_kummerRootUnit_pow h b g)
    rw [show g ((h.root b : Ωˣ) : Ω) = ((g • h.root b : Ωˣ) : Ω) from rfl, hs, Units.val_mul,
      Units.val_pow_eq_pow_val, coe_kummerRootUnit]
  have hcomm : algebraMap ↥E Ω (AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥E g ν)
      = g (algebraMap ↥E Ω ν) := AlgEquiv.restrictNormal_commutes g ↥E ν
  have hgx : ∀ i : ℕ, AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥E g = σ₀ ^ i →
      g (algebraMap ↥E Ω ν) = algebraMap k Ω ζ ^ i * algebraMap ↥E Ω ν := by
    intro i hi
    rw [← hcomm, hi, aut_pow_apply_eq_algebraMap_pow_mul E hact, map_mul, map_pow,
      ← IsScalarTower.algebraMap_apply k ↥E Ω]
  have hres : AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥E g
      = σ₀ ^ (dlog σ₀ (AlgEquiv.restrictNormalHom ↥E g)).val := (pow_val_dlog hσ₀ _).symm
  have h1 : g ((h.root b : Ωˣ) : Ω)
      = algebraMap k Ω ζ ^ (dlog σ₀ (AlgEquiv.restrictNormalHom ↥E g)).val
        * (algebraMap k Ω ζ ^ j * algebraMap ↥E Ω ν) := by
    rw [hrj, map_mul, map_pow, AlgEquiv.commutes, hgx _ hres]
    ring
  have h2 : g ((h.root b : Ωˣ) : Ω)
      = algebraMap k Ω ζ ^ (kummerChar h b g).val
        * (algebraMap k Ω ζ ^ j * algebraMap ↥E Ω ν) := by
    rw [hgr, hrj]
  have hne : algebraMap k Ω ζ ^ j * algebraMap ↥E Ω ν ≠ 0 := by
    rw [← hrj]
    exact (h.root b).ne_zero
  exact hzΩ.pow_inj (by rw [← hcard]; exact val_dlog_lt σ₀ _) (ZMod.val_lt _)
    (mul_right_cancel₀ hne (h1.symm.trans h2))

end RadicalLevel

end InverseGalois.CFT
