/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.CyclicTransport
import InverseGalois.CFT.Brauer.LocalSymbolRamified
import InverseGalois.CFT.Brauer.RadicalLevel

/-!
# The invariant of a cyclic algebra over a radical level

The norm residue symbol of two units of a local field is the inverse of the invariant of the cyclic
algebra of the first unit over any cyclic level carrying the Kummer character of the second.  When
the level is handed over in radical form — an element whose power is the second unit, and a
generator of the Galois group multiplying that element by a root of unity of the base — the
character is carried automatically, because the radical and the chosen root of the unit differ by a
root of unity.

The radical form is what the arithmetic actually produces.  A totally ramified cyclic extension of
a local field is generated by a radical, and the generator of its Galois group is pinned down by
the root of unity through which it moves that radical, so the invariant of a cyclic algebra over
such an extension is computed by the power residue symbol with no further identification of the
level.

The level is also allowed to be an abstract extension rather than a subfield of the algebraic
closure: any finite extension embeds into the algebraic closure, the Brauer class of a cyclic
algebra is unchanged by such an embedding, and the radical travels with it.

## Main results

* `InverseGalois.CFT.localInvariantHom_cyclicBrauerHom_eq_inv_localKummerSymbol_of_radical`: the
  invariant of a cyclic algebra over a level of the algebraic closure presented by a radical is the
  inverse of the norm residue symbol of its coefficient against the power of the radical.
* `InverseGalois.CFT.localInvariantHom_cyclicBrauerHom_eq_inv_localSymbol_of_radical`: **the
  invariant of a cyclic algebra over a cyclic extension presented by a radical is the inverse of
  the power residue symbol of its coefficient against the power of the radical.**

## Tags

norm residue symbol, power residue symbol, cyclic algebra, Brauer group, radical extension,
ramified extension, Kummer theory, class field theory
-/

namespace InverseGalois.CFT

open scoped Valued WithZero

/-! ### A radical level inside the algebraic closure -/

section Level

variable {K : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
  [PerfectField K] {m : ℤ} {p e : ℕ} {n : ℕ} [NeZero n] {ζ : K} {hζ : IsPrimitiveRoot ζ n}

attribute [local instance] zmodTrivialAction isSmoothAction_zmod

/-- **The invariant of a cyclic algebra over a level presented by a radical is the inverse of the
norm residue symbol of its coefficient against the power of the radical.**  The discrete logarithm
of such a level computes the Kummer character of that power, so the carry condition holds. -/
theorem localInvariantHom_cyclicBrauerHom_eq_inv_localKummerSymbol_of_radical
    (h : IsKummerData K (AlgebraicClosure K) (Multiplicative (ZMod n)) (zmodRootHom hζ) n)
    (E : IntermediateField K (AlgebraicClosure K)) [FiniteDimensional K ↥E] [IsGalois K ↥E]
    {σ₀ : Gal(↥E/K)} (hres : HasResidueChar K p e) (hm : IsUnitValGen K m)
    (hσ₀ : ∀ x : Gal(↥E/K), x ∈ Subgroup.zpowers σ₀) (hcard : Nat.card Gal(↥E/K) = n) {b : Kˣ}
    {ν : ↥E} (hpow : algebraMap ↥E (AlgebraicClosure K) ν ^ n
      = algebraMap K (AlgebraicClosure K) (b : K))
    (hact : σ₀ ν = algebraMap K ↥E ζ * ν) (a : Kˣ) :
    localInvariantHom K hm (cyclicBrauerHom hσ₀ a)
      = (localKummerSymbol hres hm h (mulZMod n) a b)⁻¹ :=
  localInvariantHom_cyclicBrauerHom_eq_inv_localKummerSymbol h E hres hm hσ₀ a b
    (carry_iff_of_dlog_eq h E hcard (dlog_eq_kummerChar_of_radical h E hσ₀ hcard hpow hact))

end Level

/-! ### An abstract radical extension -/

section Abstract

variable {K : Type} [Field K] [Valued K ℤᵐ⁰]
  [Valuation.RankOne (Valued.v : Valuation K ℤᵐ⁰)] [CompleteSpace K] [ProperSpace K]
  [PerfectField K] {m : ℤ} {p e : ℕ} {n : ℕ} [NeZero n] {ζ : K}

attribute [local instance] zmodTrivialAction isSmoothAction_zmod

/-- **The invariant of a cyclic algebra over a cyclic extension presented by a radical is the
inverse of the power residue symbol of its coefficient against the power of the radical.**  The
extension is embedded into the algebraic closure, which changes neither the Brauer class of the
cyclic algebra nor the radical presentation of the level. -/
theorem localInvariantHom_cyclicBrauerHom_eq_inv_localSymbol_of_radical
    (hres : HasResidueChar K p e) (hm : IsUnitValGen K m) (hζ : IsPrimitiveRoot ζ n) {L : Type}
    [Field L] [Algebra K L] [FiniteDimensional K L] [IsGalois K L] {σ : Gal(L/K)}
    (hσ : ∀ x : Gal(L/K), x ∈ Subgroup.zpowers σ) (hcard : Nat.card Gal(L/K) = n) {b : Kˣ} {ν : L}
    (hpow : ν ^ n = algebraMap K L (b : K)) (hact : σ ν = algebraMap K L ζ * ν) (a : Kˣ) :
    localInvariantHom K hm (cyclicBrauerHom hσ a) = (localSymbol hres hm hζ a b)⁻¹ := by
  obtain ⟨ψ⟩ : Nonempty (L →ₐ[K] AlgebraicClosure K) := ⟨IsAlgClosed.lift⟩
  let φ : L ≃ₐ[K] ↥ψ.fieldRange := AlgEquiv.ofInjectiveField ψ
  have hcomm : ∀ x : L, algebraMap ↥ψ.fieldRange (AlgebraicClosure K) (φ x) = ψ x := fun _ => rfl
  haveI : FiniteDimensional K ↥ψ.fieldRange :=
    FiniteDimensional.of_injective φ.symm.toLinearMap φ.symm.injective
  haveI : IsGalois K ↥ψ.fieldRange := IsGalois.of_algEquiv φ
  have hφ : ∀ x : L, φ (σ x) = AlgEquiv.autCongr φ σ (φ x) := by
    intro x
    show φ (σ x) = φ (σ (φ.symm (φ x)))
    rw [φ.symm_apply_apply]
  have hσ₀ : ∀ x : Gal(↥ψ.fieldRange/K), x ∈ Subgroup.zpowers (AlgEquiv.autCongr φ σ) := by
    intro x
    obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (hσ ((AlgEquiv.autCongr φ).symm x))
    refine Subgroup.mem_zpowers_iff.mpr ⟨j, ?_⟩
    rw [← map_zpow, hj, MulEquiv.apply_symm_apply]
  have hcard' : Nat.card Gal(↥ψ.fieldRange/K) = n := by
    rw [← hcard]
    exact Nat.card_congr (AlgEquiv.autCongr φ).symm.toEquiv
  have hpow' : algebraMap ↥ψ.fieldRange (AlgebraicClosure K) (φ ν) ^ n
      = algebraMap K (AlgebraicClosure K) (b : K) := by
    rw [hcomm, ← map_pow, hpow, AlgHom.commutes]
  have hact' : AlgEquiv.autCongr φ σ (φ ν) = algebraMap K ↥ψ.fieldRange ζ * φ ν := by
    rw [← hφ, hact, map_mul, AlgEquiv.commutes]
  rw [← cyclicBrauerHom_congr hσ hσ₀ φ hφ a,
    localInvariantHom_cyclicBrauerHom_eq_inv_localKummerSymbol_of_radical
      (isKummerData_zmod hζ exists_units_pow_eq) ψ.fieldRange hres hm hσ₀ hcard' hpow' hact' a]
  rfl

end Abstract

end InverseGalois.CFT
