/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.ResidueDegree
import InverseGalois.CFT.Brauer.UnramifiedAut

/-!
# The residue degree of an unramified extension of a local field

An unramified extension of a nonarchimedean local field is generated by a root of unity of order
prime to the residue characteristic, hence is a cyclotomic extension and in particular Galois.  Its
automorphisms act faithfully on the residue field and fix the residues of the base field, so the
number of automorphisms is at most the residue degree; the residue degree is at most the degree of
the extension because independent residues lift to independent integers.  The two bounds meet:
**for an unramified extension the residue degree is the degree of the extension.**

## Main results

* `InverseGalois.CFT.isGalois_of_unramified`: **an unramified extension of a local field is
  Galois.**
* `InverseGalois.CFT.card_divisionResidue_of_unramified`: **the residue field of an unramified
  extension of a local field has exactly as many elements as the degree of the extension allows.**

## Tags

local field, unramified extension, residue degree, Galois
-/

set_option synthInstance.maxHeartbeats 800000

universe u

namespace InverseGalois.CFT

open Module

variable {K L : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-! ### The residue fields -/

/-- The residue ring of an extension of a nonarchimedean local field is a field. -/
noncomputable local instance galResidueField : Field (DivisionResidue K L) :=
  (Finite.isField_of_domain (DivisionResidue K L)).toField

/-- The residue ring of a nonarchimedean local field is a field. -/
noncomputable local instance galResidueBaseField : Field (DivisionResidue K K) :=
  (Finite.isField_of_domain (DivisionResidue K K)).toField

/-- The residue ring of an extension is an algebra over the residue field of the base field. -/
noncomputable local instance galResidueAlgebra :
    Algebra (DivisionResidue K K) (DivisionResidue K L) :=
  (divisionResidueBase L).toAlgebra

/-! ### The action on the residue field -/

/-- **An automorphism of an extension of a local field fixes the residues of the base field.** -/
theorem divisionResidueHom_divisionResidueBase (σ : L ≃ₐ[K] L) (c : DivisionResidue K K) :
    divisionResidueHom σ (divisionResidueBase L c) = divisionResidueBase L c := by
  obtain ⟨x, rfl⟩ := (divisionResidueCon K K).mk'_surjective c
  rw [RingCon.coe_mk', divisionResidueBase_coe, divisionResidueHom_coe]
  refine congrArg _ (Subtype.ext ?_)
  simp only [coe_divisionIntegersAlgEquiv, coe_divisionIntegersBase]
  exact σ.commutes _

/-- The action of an automorphism of an extension of a local field on the residue field, as an
automorphism over the residue field of the base field. -/
noncomputable def residueAlgAut (σ : L ≃ₐ[K] L) :
    DivisionResidue K L ≃ₐ[DivisionResidue K K] DivisionResidue K L :=
  AlgEquiv.ofRingEquiv (f := divisionResidueAut K L σ)
    fun c => divisionResidueHom_divisionResidueBase σ c

theorem residueAlgAut_apply (σ : L ≃ₐ[K] L) (z : DivisionResidue K L) :
    residueAlgAut σ z = divisionResidueAut K L σ z := rfl

/-- **An automorphism of an extension of a local field generated by a root of unity of invertible
order is determined by its action on the residue field.** -/
theorem residueAlgAut_injective {ζ : L} {m : ℕ} (hpow : ζ ^ m = 1) (hm : ‖((m : ℕ) : K)‖ = 1)
    (htop : Algebra.adjoin K ({ζ} : Set L) = ⊤) :
    Function.Injective (residueAlgAut : (L ≃ₐ[K] L) → _) := by
  intro σ τ h
  refine divisionResidueAut_injective hpow hm htop (RingEquiv.ext fun z => ?_)
  rw [← residueAlgAut_apply, ← residueAlgAut_apply, h]

/-! ### An unramified extension is Galois -/

variable (K L) in
/-- **An unramified extension of a local field is a cyclotomic extension.** -/
theorem isCyclotomicExtension_of_unramified
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    IsCyclotomicExtension {Nat.card (DivisionResidue K L) - 1} K L := by
  obtain ⟨ζ, hζ, htop⟩ := exists_isPrimitiveRoot_adjoin_eq_top_of_unramified K L hur
  haveI := neZero_card_divisionResidue_sub_one K L
  rw [IsCyclotomicExtension.iff_adjoin_eq_top]
  refine ⟨fun n hn _ => ?_, le_antisymm le_top ?_⟩
  · rw [Set.mem_singleton_iff] at hn
    exact ⟨ζ, hn ▸ hζ⟩
  · rw [← htop]
    refine Algebra.adjoin_mono ?_
    rintro x hx
    rw [Set.mem_singleton_iff] at hx
    subst hx
    exact ⟨Nat.card (DivisionResidue K L) - 1, Set.mem_singleton _, NeZero.ne _, hζ.pow_eq_one⟩

variable (K L) in
/-- **An unramified extension of a local field is Galois.** -/
theorem isGalois_of_unramified
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) : IsGalois K L := by
  haveI := isCyclotomicExtension_of_unramified K L hur
  exact IsCyclotomicExtension.isGalois {Nat.card (DivisionResidue K L) - 1} K L

/-! ### The two bounds on the residue degree -/

variable (K L) in
/-- The number of automorphisms of an unramified extension of a local field is at most the residue
degree, because the automorphisms act faithfully on the residue field over the residue field of the
base field. -/
theorem card_algEquiv_le_finrank_divisionResidue
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    Nat.card (L ≃ₐ[K] L) ≤ finrank (DivisionResidue K K) (DivisionResidue K L) := by
  obtain ⟨ζ, h1, -, htop⟩ := exists_adjoin_rootOfUnity_eq_top_of_unramified K L hur
  have hinj : Function.Injective (residueAlgAut : (L ≃ₐ[K] L) → _) :=
    residueAlgAut_injective h1 (norm_natCast_card_divisionResidue_sub_one K L) htop
  calc Nat.card (L ≃ₐ[K] L)
      ≤ Nat.card (DivisionResidue K L ≃ₐ[DivisionResidue K K] DivisionResidue K L) :=
        Nat.card_le_card_of_injective _ hinj
    _ = finrank (DivisionResidue K K) (DivisionResidue K L) := by
        rw [← IsGalois.card_aut_eq_finrank (DivisionResidue K K) (DivisionResidue K L)]

variable (K L) in
/-- **The residue field of an unramified extension of a local field has exactly as many elements as
the degree of the extension allows.** -/
theorem card_divisionResidue_of_unramified
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    Nat.card (DivisionResidue K L) = Nat.card (DivisionResidue K K) ^ finrank K L := by
  haveI := isGalois_of_unramified K L hur
  have hbase : 1 < Nat.card (DivisionResidue K K) := Finite.one_lt_card
  have hpow : Nat.card (DivisionResidue K L)
      = Nat.card (DivisionResidue K K) ^ finrank (DivisionResidue K K) (DivisionResidue K L) :=
    Module.natCard_eq_pow_finrank
  have hlow : finrank K L ≤ finrank (DivisionResidue K K) (DivisionResidue K L) := by
    have hcard : Nat.card (L ≃ₐ[K] L) = finrank K L := by
      rw [← IsGalois.card_aut_eq_finrank K L]
    exact hcard ▸ card_algEquiv_le_finrank_divisionResidue K L hur
  have hhigh : finrank (DivisionResidue K K) (DivisionResidue K L) ≤ finrank K L := by
    refine (Nat.pow_le_pow_iff_right hbase).1 ?_
    rw [← hpow]
    exact card_divisionResidue_le_pow_finrank K L
  rw [hpow, le_antisymm hhigh hlow]

/-! ### The Frobenius automorphism -/

variable (K L) in
/-- The residue degree of an unramified extension of a local field is its degree. -/
theorem finrank_divisionResidue_of_unramified
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    finrank (DivisionResidue K K) (DivisionResidue K L) = finrank K L := by
  have hbase : 2 ≤ Nat.card (DivisionResidue K K) := Finite.one_lt_card
  have hpow : Nat.card (DivisionResidue K L)
      = Nat.card (DivisionResidue K K) ^ finrank (DivisionResidue K K) (DivisionResidue K L) :=
    Module.natCard_eq_pow_finrank
  have hcard := card_divisionResidue_of_unramified K L hur
  rw [hpow] at hcard
  exact Nat.pow_right_injective hbase hcard

/-- The action of the automorphisms of an extension of a local field on its residue field, as a
homomorphism of groups. -/
noncomputable def residueAlgAutHom :
    (L ≃ₐ[K] L) →* DivisionResidue K L ≃ₐ[DivisionResidue K K] DivisionResidue K L where
  toFun := residueAlgAut
  map_one' := by
    refine AlgEquiv.ext fun z => ?_
    rw [residueAlgAut_apply, map_one]
    rfl
  map_mul' σ τ := by
    refine AlgEquiv.ext fun z => ?_
    rw [residueAlgAut_apply, map_mul]
    rfl

@[simp]
theorem residueAlgAutHom_apply (σ : L ≃ₐ[K] L) : residueAlgAutHom σ = residueAlgAut σ := rfl

variable (K L) in
/-- **An unramified extension of a local field has a Frobenius automorphism**: an automorphism which
generates the Galois group and raises every residue to the number of residues of the base field. -/
theorem exists_frobenius_of_unramified
    (hur : ∀ z : L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K L z = ‖c‖) :
    ∃ σ : L ≃ₐ[K] L, Subgroup.zpowers σ = ⊤ ∧
      ∀ x : divisionIntegers K L,
        ((divisionIntegersAlgEquiv σ x : divisionIntegers K L) : DivisionResidue K L)
          = ((x : divisionIntegers K L) : DivisionResidue K L)
              ^ Nat.card (DivisionResidue K K) := by
  classical
  haveI := isGalois_of_unramified K L hur
  haveI : Fintype (DivisionResidue K K) := Fintype.ofFinite _
  obtain ⟨ζ, h1, -, htop⟩ := exists_adjoin_rootOfUnity_eq_top_of_unramified K L hur
  have hinj : Function.Injective (residueAlgAutHom : (L ≃ₐ[K] L) →* _) :=
    residueAlgAut_injective h1 (norm_natCast_card_divisionResidue_sub_one K L) htop
  have hff : finrank (DivisionResidue K K) (DivisionResidue K L) = finrank K L :=
    finrank_divisionResidue_of_unramified K L hur
  have hcardL : Nat.card (L ≃ₐ[K] L) = finrank K L := by
    rw [← IsGalois.card_aut_eq_finrank K L]
  have hcardres : Nat.card (DivisionResidue K L ≃ₐ[DivisionResidue K K] DivisionResidue K L)
      = finrank K L := by
    rw [← hff, ← IsGalois.card_aut_eq_finrank (DivisionResidue K K) (DivisionResidue K L)]
  have hbij : Function.Bijective (residueAlgAutHom : (L ≃ₐ[K] L) →* _) :=
    (Nat.bijective_iff_injective_and_card _).2 ⟨hinj, by rw [hcardL, hcardres]⟩
  set Φ : DivisionResidue K L ≃ₐ[DivisionResidue K K] DivisionResidue K L :=
    FiniteField.frobeniusAlgEquivOfAlgebraic (DivisionResidue K K) (DivisionResidue K L) with hΦ
  obtain ⟨σ, hσ⟩ := hbij.2 Φ
  refine ⟨σ, ?_, ?_⟩
  · refine Subgroup.eq_top_of_card_eq _ ?_
    rw [Nat.card_zpowers, hcardL, ← orderOf_injective _ hinj σ, hσ, hΦ,
      FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic, hff]
  · intro x
    have hx : residueAlgAut σ ((x : divisionIntegers K L) : DivisionResidue K L)
        = Φ ((x : divisionIntegers K L) : DivisionResidue K L) := by
      rw [← residueAlgAutHom_apply, hσ]
    rw [hΦ, FiniteField.coe_frobeniusAlgEquivOfAlgebraic] at hx
    have hx2 : residueAlgAut σ ((x : divisionIntegers K L) : DivisionResidue K L)
        = ((x : divisionIntegers K L) : DivisionResidue K L)
            ^ Fintype.card (DivisionResidue K K) := hx
    rw [Nat.card_eq_fintype_card (α := DivisionResidue K K), ← hx2, residueAlgAut_apply]
    exact (divisionResidueAut_coe σ x).symm

end InverseGalois.CFT
