/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.TotallyRealInvariant

/-!
# The archimedean invariants over an arbitrary base

An infinite place of a number field is real or complex.  At a complex place the completion is
algebraically closed and splits everything, so the invariant there is trivial for any class at all.
At a real place the completion is the reals along the associated embedding, and a class split by
some extension is split there as soon as that extension admits a compatible embedding into the
reals.

An extension generated by a totally real subfield always admits one.  Extend the composite of the
real embedding of the base with the inclusion of the reals into the complex numbers along the
algebraically closed target; the extended embedding and its conjugate are two algebra maps of the
extension which agree on the totally real subfield, hence everywhere, so the extended embedding is
fixed by conjugation and factors through the reals.  The factorisation agrees with the given
embedding on the base because the reals inject into the complex numbers.

The generating subfield is needed because an extension of a base with a complex place can never be
totally real, while the extensions that arise in the reciprocity computation over an arbitrary base
are compositums of the base with a totally real field of the rationals, and are generated by that
field.  Consequently a Brauer class of an arbitrary number field split by such an extension has
trivial invariant at every infinite place, and its total invariant is the product of the invariants
at the finite places alone.  This is the archimedean half of the reciprocity computation over an
arbitrary base, replacing the argument over the rationals which used that the rationals have a
single infinite place.

## Main results

* `InverseGalois.CFT.nonempty_algHom_real_of_adjoin_isTotallyReal`: **an extension of a number
  field generated by a totally real subfield embeds into the reals over any real embedding of the
  base.**
* `InverseGalois.CFT.infinitePlaceInvariant_eq_one_of_adjoin_isTotallyReal`: **a Brauer class of a
  number field split by an extension generated by a totally real subfield has trivial invariant at
  every infinite place.**
* `InverseGalois.CFT.totalInvariant_eq_finprod_of_adjoin_isTotallyReal`: **the total invariant of
  such a class is the product of its invariants at the finite places.**
* `InverseGalois.CFT.totalInvariant_cyclicBrauerHom_of_adjoin_isTotallyReal`: the same for a cyclic
  algebra over an arbitrary number field whose splitting field is generated by a totally real
  subfield.

## Tags

Brauer group, invariant, infinite place, totally real, number field, cyclic algebra, reciprocity,
class field theory
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

/-! ### A real embedding of an extension generated by a totally real subfield -/

section RealEmbedding

variable {k F₀ F : Type} [Field k] [NumberField k] [Field F₀] [IsTotallyReal F₀]
  [Field F] [NumberField F] [Algebra k F] [Algebra F₀ F]

/-- **An extension of a number field generated by a totally real subfield embeds into the reals
over any real embedding of the base.**  Extend the composite of the real embedding with the
inclusion of the reals into the complex numbers along the algebraically closed target; the extended
embedding and its conjugate are two algebra maps agreeing on the totally real subfield, hence
everywhere, so the extended embedding is fixed by conjugation and factors through the reals, and
the factorisation agrees with the given embedding on the base because the reals inject into the
complex numbers. -/
theorem nonempty_algHom_real_of_adjoin_isTotallyReal [Algebra k ℝ]
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ F)) = ⊤) : Nonempty (F →ₐ[k] ℝ) := by
  letI : Algebra k ℂ := (Complex.ofRealHom.comp (algebraMap k ℝ)).toAlgebra
  let φ : F →ₐ[k] ℂ := IsAlgClosed.lift
  have hconj : ∀ r : k, (starRingEnd ℂ) (algebraMap k ℂ r) = algebraMap k ℂ r := by
    intro r
    show (starRingEnd ℂ) (Complex.ofRealHom (algebraMap k ℝ r)) = _
    exact Complex.conj_ofReal _
  let ψ : F →ₐ[k] ℂ :=
    { ComplexEmbedding.conjugate (φ : F →+* ℂ) with
      commutes' := fun r => by
        show (starRingEnd ℂ) (φ (algebraMap k F r)) = _
        rw [φ.commutes]
        exact hconj r }
  have hψφ : ψ = φ := by
    refine AlgHom.ext_of_adjoin_eq_top hgen ?_
    rintro _ ⟨y, rfl⟩
    show (starRingEnd ℂ) (φ (algebraMap F₀ F y)) = φ (algebraMap F₀ F y)
    exact RingHom.congr_fun
      (IsTotallyReal.complexEmbedding_isReal ((φ : F →+* ℂ).comp (algebraMap F₀ F))) y
  have hφreal : ComplexEmbedding.IsReal (φ : F →+* ℂ) :=
    ComplexEmbedding.isReal_iff.mpr (congrArg (fun f : F →ₐ[k] ℂ => (f : F →+* ℂ)) hψφ)
  have hcomm : ∀ r : k, hφreal.embedding (algebraMap k F r) = algebraMap k ℝ r := by
    intro r
    apply Complex.ofReal_injective
    rw [ComplexEmbedding.IsReal.coe_embedding_apply]
    show φ (algebraMap k F r) = _
    rw [φ.commutes]
    rfl
  exact ⟨{ hφreal.embedding with commutes' := hcomm }⟩

end RealEmbedding

section RealEmbeddingTotallyReal

variable {k F : Type} [Field k] [NumberField k] [Field F] [NumberField F] [Algebra k F]
  [IsTotallyReal F]

/-- **A totally real extension of a number field embeds into the reals over any real embedding of
the base**, the case of an extension generated by itself. -/
theorem nonempty_algHom_real_of_isTotallyReal [Algebra k ℝ] : Nonempty (F →ₐ[k] ℝ) :=
  nonempty_algHom_real_of_adjoin_isTotallyReal (F₀ := F) (by simp)

end RealEmbeddingTotallyReal

/-! ### Triviality of the archimedean invariants -/

section Archimedean

variable {k F₀ F : Type} [Field k] [NumberField k] [Field F₀] [IsTotallyReal F₀]
  [Field F] [NumberField F] [Algebra k F] [Algebra F₀ F]

/-- **A Brauer class of a number field split by an extension generated by a totally real subfield
has trivial invariant at every infinite place.**  At a complex place every class is split, and at a
real place the extension embeds into the reals over the associated embedding of the base. -/
theorem infinitePlaceInvariant_eq_one_of_adjoin_isTotallyReal
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ F)) = ⊤) (u : InfinitePlace k)
    {x : BrauerGroup.{0, 0} k} (hx : x ∈ BrauerGroup.relative k F) :
    infinitePlaceInvariant k u x = 1 := by
  rcases u.isReal_or_isComplex with hu | hu
  · letI : Algebra k ℝ := (InfinitePlace.embedding_of_isReal hu).toAlgebra
    rw [infinitePlaceInvariant_eq_one_iff, relative_completion_eq_relative_real k hu rfl]
    obtain ⟨ψ⟩ : Nonempty (F →ₐ[k] ℝ) := nonempty_algHom_real_of_adjoin_isTotallyReal hgen
    exact relative_le_relative_of_algHom ψ hx
  · rw [infinitePlaceInvariant_of_isComplex k hu, MonoidHom.one_apply]

/-- **The total invariant of a Brauer class split by an extension generated by a totally real
subfield is the product of its invariants at the finite places.** -/
theorem totalInvariant_eq_finprod_of_adjoin_isTotallyReal
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ F)) = ⊤) {x : BrauerGroup.{0, 0} k}
    (hx : x ∈ BrauerGroup.relative k F) :
    totalInvariant k x = ∏ᶠ v : HeightOneSpectrum (𝓞 k), placeInvariant k v x :=
  totalInvariant_eq_finprod k x fun u =>
    infinitePlaceInvariant_eq_one_of_adjoin_isTotallyReal hgen u hx

end Archimedean

section ArchimedeanTotallyReal

variable {k F : Type} [Field k] [NumberField k] [Field F] [NumberField F] [Algebra k F]
  [IsTotallyReal F]

/-- **A Brauer class of a number field split by a totally real extension has trivial invariant at
every infinite place.** -/
theorem infinitePlaceInvariant_eq_one_of_isTotallyReal (u : InfinitePlace k)
    {x : BrauerGroup.{0, 0} k} (hx : x ∈ BrauerGroup.relative k F) :
    infinitePlaceInvariant k u x = 1 :=
  infinitePlaceInvariant_eq_one_of_adjoin_isTotallyReal (F₀ := F) (by simp) u hx

/-- **The total invariant of a Brauer class split by a totally real extension is the product of its
invariants at the finite places.** -/
theorem totalInvariant_eq_finprod_of_isTotallyReal {x : BrauerGroup.{0, 0} k}
    (hx : x ∈ BrauerGroup.relative k F) :
    totalInvariant k x = ∏ᶠ v : HeightOneSpectrum (𝓞 k), placeInvariant k v x :=
  totalInvariant_eq_finprod k x fun u => infinitePlaceInvariant_eq_one_of_isTotallyReal u hx

end ArchimedeanTotallyReal

/-! ### Cyclic algebras with a splitting field generated by a totally real subfield -/

section Cyclic

variable {k F₀ F : Type} [Field k] [NumberField k] [Field F₀] [IsTotallyReal F₀]
  [Field F] [NumberField F] [Algebra k F] [Algebra F₀ F] [IsGalois k F] {σ₀ : Gal(F/k)}
  (hσ₀ : ∀ x : Gal(F/k), x ∈ Subgroup.zpowers σ₀)

/-- **A cyclic algebra over a number field whose splitting field is generated by a totally real
subfield has trivial invariant at every infinite place.** -/
theorem infinitePlaceInvariant_cyclicBrauerHom_of_adjoin_isTotallyReal
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ F)) = ⊤) (a : kˣ) (u : InfinitePlace k) :
    infinitePlaceInvariant k u (cyclicBrauerHom hσ₀ a) = 1 :=
  infinitePlaceInvariant_eq_one_of_adjoin_isTotallyReal hgen u (cyclicBrauerHom_mem_relative hσ₀ a)

/-- **The total invariant of a cyclic algebra over a number field whose splitting field is
generated by a totally real subfield is the product of its invariants at the finite places.**  This
is the archimedean half of the reciprocity computation for such an algebra over an arbitrary
base. -/
theorem totalInvariant_cyclicBrauerHom_of_adjoin_isTotallyReal
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ F)) = ⊤) (a : kˣ) :
    totalInvariant k (cyclicBrauerHom hσ₀ a)
      = ∏ᶠ v : HeightOneSpectrum (𝓞 k), placeInvariant k v (cyclicBrauerHom hσ₀ a) :=
  totalInvariant_eq_finprod_of_adjoin_isTotallyReal hgen (cyclicBrauerHom_mem_relative hσ₀ a)

end Cyclic

section CyclicTotallyReal

variable {k F : Type} [Field k] [NumberField k] [Field F] [NumberField F] [Algebra k F]
  [IsGalois k F] [IsTotallyReal F] {σ₀ : Gal(F/k)}
  (hσ₀ : ∀ x : Gal(F/k), x ∈ Subgroup.zpowers σ₀)

/-- **A cyclic algebra over a number field with a totally real splitting field has trivial invariant
at every infinite place.** -/
theorem infinitePlaceInvariant_cyclicBrauerHom_of_isTotallyReal (a : kˣ) (u : InfinitePlace k) :
    infinitePlaceInvariant k u (cyclicBrauerHom hσ₀ a) = 1 :=
  infinitePlaceInvariant_eq_one_of_isTotallyReal u (cyclicBrauerHom_mem_relative hσ₀ a)

/-- **The total invariant of a cyclic algebra over a number field with a totally real splitting
field is the product of its invariants at the finite places.** -/
theorem totalInvariant_cyclicBrauerHom_of_isTotallyReal (a : kˣ) :
    totalInvariant k (cyclicBrauerHom hσ₀ a)
      = ∏ᶠ v : HeightOneSpectrum (𝓞 k), placeInvariant k v (cyclicBrauerHom hσ₀ a) :=
  totalInvariant_eq_finprod_of_isTotallyReal (cyclicBrauerHom_mem_relative hσ₀ a)

end CyclicTotallyReal

end InverseGalois.CFT
