/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.InvariantSurjective

/-!
# Unramified subextensions are classified by their degree

An unramified extension of a nonarchimedean local field is generated by a root of unity whose order
is one less than the number of its residues, and that number is the power of the number of residues
of the base field given by the degree.  The roots of unity of a fixed order in a field are the
powers of any one of them, so inside a fixed extension of the base field an unramified extension
contains every root of unity of the order attached to its degree, hence every unramified extension
whose degree divides its own; in particular two unramified extensions of the same degree coincide.

The same root of unity produces the largest unramified subextension of an arbitrary finite
extension.  Adjoining the root of unity of order one less than the number of residues of the top
field gives a cyclotomic, hence unramified, subextension, and comparing the two divisibilities
shows that its degree is exactly the residue degree.

## Main results

* `InverseGalois.CFT.exists_card_divisionResidue_eq_pow`: the number of residues of an extension
  of a local field is a power of the number of residues of the base field.
* `InverseGalois.CFT.mem_of_pow_card_divisionResidue_sub_one_eq_one`: **a root of unity whose order
  is one less than the number of residues allowed by the degree of an unramified extension lies in
  that extension.**
* `InverseGalois.CFT.le_of_finrank_dvd_of_unramified`: **an unramified extension contains every
  unramified extension whose degree divides its own.**
* `InverseGalois.CFT.eq_of_finrank_eq_of_unramified`: **two unramified extensions of the same
  degree coincide.**
* `InverseGalois.CFT.finrank_dvd_of_unramified_le`: **the degree of an unramified subextension
  divides the residue degree.**
* `InverseGalois.CFT.exists_unramified_le_finrank_eq`: **every finite extension of a local field
  has an unramified subextension whose degree is the residue degree.**

## Tags

local field, unramified extension, residue degree, root of unity, cyclotomic extension
-/

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1000000

universe u

namespace InverseGalois.CFT

open Module

open scoped IntermediateField

/-! ### The number of residues is a power -/

section ResidueDegree

variable {K L : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-- The residue ring of an extension of a nonarchimedean local field is a field. -/
noncomputable local instance degResidueField : Field (DivisionResidue K L) :=
  (Finite.isField_of_domain (DivisionResidue K L)).toField

/-- The residue ring of a nonarchimedean local field is a field. -/
noncomputable local instance degResidueBaseField : Field (DivisionResidue K K) :=
  (Finite.isField_of_domain (DivisionResidue K K)).toField

/-- The residue ring of an extension is an algebra over the residue field of the base field. -/
noncomputable local instance degResidueAlgebra :
    Algebra (DivisionResidue K K) (DivisionResidue K L) :=
  (divisionResidueBase L).toAlgebra

variable (K L) in
/-- The number of residues of an extension of a local field is a nonzero power of the number of
residues of the base field, because the residue field of the extension is a vector space over the
residue field of the base field. -/
theorem exists_card_divisionResidue_eq_pow :
    ∃ f : ℕ, f ≠ 0 ∧ Nat.card (DivisionResidue K L) = Nat.card (DivisionResidue K K) ^ f := by
  refine ⟨finrank (DivisionResidue K K) (DivisionResidue K L), ?_, Module.natCard_eq_pow_finrank⟩
  intro h
  have hcard : Nat.card (DivisionResidue K L)
      = Nat.card (DivisionResidue K K) ^
        finrank (DivisionResidue K K) (DivisionResidue K L) := Module.natCard_eq_pow_finrank
  rw [h, pow_zero] at hcard
  have h1 : 1 < Nat.card (DivisionResidue K L) := Finite.one_lt_card
  omega

end ResidueDegree

/-! ### Unramified subextensions of a fixed extension -/

section Ambient

variable {K Ω : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [ProperSpace K]
variable [Field Ω] [Algebra K Ω]

/-- **A root of unity whose order is one less than the number of residues allowed by the degree of
an unramified extension already lies in that extension.**  The extension contains a root of unity
of exactly that order, and the roots of unity of a given order in a field are its powers. -/
theorem mem_of_pow_card_divisionResidue_sub_one_eq_one (L : IntermediateField K Ω)
    [FiniteDimensional K ↥L]
    (hur : ∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖) {ζ : Ω}
    (hζ : ζ ^ (Nat.card (DivisionResidue K K) ^ finrank K ↥L - 1) = 1) : ζ ∈ L := by
  have h2 : 2 ≤ Nat.card (DivisionResidue K K) := Finite.one_lt_card
  have hn : finrank K ↥L ≠ 0 := Module.finrank_pos.ne'
  have hpow : 2 ≤ Nat.card (DivisionResidue K K) ^ finrank K ↥L :=
    le_trans h2 (Nat.le_self_pow hn _)
  haveI : NeZero (Nat.card (DivisionResidue K K) ^ finrank K ↥L - 1) := ⟨by omega⟩
  obtain ⟨ξ, hξ, -⟩ := exists_isPrimitiveRoot_adjoin_eq_top_of_unramified K ↥L hur
  rw [card_divisionResidue_of_unramified K ↥L hur] at hξ
  have hξΩ : IsPrimitiveRoot ((ξ : Ω)) (Nat.card (DivisionResidue K K) ^ finrank K ↥L - 1) :=
    hξ.map_of_injective (f := L.val) L.val.toRingHom.injective
  obtain ⟨i, -, hi⟩ := hξΩ.eq_pow_of_pow_eq_one hζ
  rw [← hi]
  exact pow_mem ξ.2 i

/-- **An unramified extension contains every unramified extension whose degree divides its own.**
The smaller one is generated by a root of unity whose order divides the order of the root of unity
generating the larger one, so that root of unity, and with it every polynomial in it, lies in the
larger extension. -/
theorem le_of_finrank_dvd_of_unramified (L M : IntermediateField K Ω) [FiniteDimensional K ↥L]
    [FiniteDimensional K ↥M]
    (hurL : ∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖)
    (hurM : ∀ z : ↥M, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥M z = ‖c‖)
    (hdvd : finrank K ↥M ∣ finrank K ↥L) : M ≤ L := by
  obtain ⟨ζ, hζ, htop⟩ := exists_isPrimitiveRoot_adjoin_eq_top_of_unramified K ↥M hurM
  rw [card_divisionResidue_of_unramified K ↥M hurM] at hζ
  have hone : ((ζ : Ω)) ^ (Nat.card (DivisionResidue K K) ^ finrank K ↥M - 1) = 1 := by
    simpa using congrArg (fun y : ↥M => (y : Ω)) hζ.pow_eq_one
  have hmem : (ζ : Ω) ∈ L := by
    refine mem_of_pow_card_divisionResidue_sub_one_eq_one L hurL ?_
    obtain ⟨c, hc⟩ := Nat.pow_sub_one_dvd_pow_sub_one (Nat.card (DivisionResidue K K)) hdvd
    rw [hc, pow_mul, hone, one_pow]
  intro x hx
  have hxM : (⟨x, hx⟩ : ↥M) ∈ Algebra.adjoin K ({ζ} : Set ↥M) := by
    rw [htop]
    exact Algebra.mem_top
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hxM
  obtain ⟨p, hp⟩ := hxM
  have hxp : Polynomial.aeval ((ζ : Ω)) p = x := by
    have h : M.val (Polynomial.aeval ζ p) = M.val ⟨x, hx⟩ := congrArg M.val hp
    rw [← Polynomial.aeval_algHom_apply] at h
    simpa using h
  have hsub : Algebra.adjoin K ({(ζ : Ω)} : Set Ω) ≤ L.toSubalgebra :=
    Algebra.adjoin_le (Set.singleton_subset_iff.2 hmem)
  rw [← hxp, ← IntermediateField.mem_toSubalgebra]
  refine hsub ?_
  rw [Algebra.adjoin_singleton_eq_range_aeval]
  exact ⟨p, rfl⟩

/-- **Two unramified extensions of a local field of the same degree inside a common extension
coincide.** -/
theorem eq_of_finrank_eq_of_unramified (L M : IntermediateField K Ω) [FiniteDimensional K ↥L]
    [FiniteDimensional K ↥M]
    (hurL : ∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖)
    (hurM : ∀ z : ↥M, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥M z = ‖c‖)
    (h : finrank K ↥M = finrank K ↥L) : M = L :=
  le_antisymm (le_of_finrank_dvd_of_unramified L M hurL hurM (dvd_of_eq h))
    (le_of_finrank_dvd_of_unramified M L hurM hurL (dvd_of_eq h.symm))

/-! ### The degree of an unramified subextension -/

/-- The roots of unity of an unramified subextension survive in the residue field of the ambient
extension, so one less than the number of residues allowed by its degree divides one less than the
number of residues upstairs. -/
theorem pow_finrank_sub_one_dvd_card_divisionResidue_sub_one (L M : IntermediateField K Ω)
    [FiniteDimensional K ↥L] [FiniteDimensional K ↥M]
    (hurL : ∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖) (hLM : L ≤ M) :
    Nat.card (DivisionResidue K K) ^ finrank K ↥L - 1 ∣ Nat.card (DivisionResidue K ↥M) - 1 := by
  have hn : finrank K ↥L ≠ 0 := Module.finrank_pos.ne'
  obtain ⟨ζ, hζ, -⟩ := exists_isPrimitiveRoot_adjoin_eq_top_of_unramified K ↥L hurL
  rw [card_divisionResidue_of_unramified K ↥L hurL] at hζ
  exact dvd_card_divisionResidue_sub_one_of_isPrimitiveRoot
    (hζ.map_of_injective (IntermediateField.inclusion_injective hLM))
    (norm_natCast_pow_card_divisionResidue_sub_one K hn)

/-- **The degree of an unramified subextension divides the residue degree of the ambient
extension.** -/
theorem finrank_dvd_of_unramified_le (L M : IntermediateField K Ω) [FiniteDimensional K ↥L]
    [FiniteDimensional K ↥M]
    (hurL : ∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖) (hLM : L ≤ M) {f : ℕ}
    (hf : Nat.card (DivisionResidue K ↥M) = Nat.card (DivisionResidue K K) ^ f) :
    finrank K ↥L ∣ f := by
  have h2 : 2 ≤ Nat.card (DivisionResidue K K) := Finite.one_lt_card
  refine dvd_of_pow_sub_one_dvd_pow_sub_one h2 ?_
  rw [← hf]
  exact pow_finrank_sub_one_dvd_card_divisionResidue_sub_one L M hurL hLM

/-! ### Adjoining a root of unity -/

omit [IsUltrametricDist K] [ProperSpace K] in
variable (K) in
/-- Adjoining a root of unity to a field gives a cyclotomic extension of the corresponding order,
because every root of unity of that order in the ambient field is one of its powers. -/
theorem isCyclotomicExtension_adjoin_isPrimitiveRoot {ζ : Ω} {m : ℕ} [NeZero m]
    (hζ : IsPrimitiveRoot ζ m) : IsCyclotomicExtension {m} K ↥K⟮ζ⟯ := by
  have hset : IntermediateField.adjoin K {b : Ω | ∃ n ∈ ({m} : Set ℕ), n ≠ 0 ∧ b ^ n = 1}
      = K⟮ζ⟯ := by
    refine le_antisymm (IntermediateField.adjoin_le_iff.2 ?_)
      (IntermediateField.adjoin_le_iff.2 ?_)
    · rintro b ⟨n, hn, -, hb⟩
      rw [Set.mem_singleton_iff] at hn
      subst hn
      obtain ⟨i, -, rfl⟩ := hζ.eq_pow_of_pow_eq_one hb
      exact pow_mem (IntermediateField.mem_adjoin_simple_self K ζ) i
    · rintro b hb
      rw [Set.mem_singleton_iff] at hb
      subst hb
      exact IntermediateField.subset_adjoin K _ ⟨m, rfl, NeZero.ne m, hζ.pow_eq_one⟩
  rw [← hset]
  exact IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot _ _ _
    fun n hn _ => ⟨ζ, (Set.mem_singleton_iff.1 hn) ▸ hζ⟩

omit [IsUltrametricDist K] [ProperSpace K] in
variable (K) in
/-- Adjoining a root of unity to a field gives a finite extension. -/
theorem finiteDimensional_adjoin_isPrimitiveRoot {ζ : Ω} {m : ℕ} [NeZero m]
    (hζ : IsPrimitiveRoot ζ m) : FiniteDimensional K ↥K⟮ζ⟯ := by
  haveI := isCyclotomicExtension_adjoin_isPrimitiveRoot K hζ
  exact IsCyclotomicExtension.finiteDimensional (S := ({m} : Set ℕ)) (K := K) ↥K⟮ζ⟯

variable (K) in
/-- **Adjoining a root of unity whose order is invertible in a local field gives an unramified
extension.**  It is a cyclotomic extension of that order, and cyclotomic extensions of invertible
order never ramify. -/
theorem unramified_adjoin_isPrimitiveRoot {ζ : Ω} {m : ℕ} [NeZero m] (hζ : IsPrimitiveRoot ζ m)
    (hmnorm : ‖((m : ℕ) : K)‖ = 1) :
    ∀ z : ↥K⟮ζ⟯, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥K⟮ζ⟯ z = ‖c‖ := by
  haveI := isCyclotomicExtension_adjoin_isPrimitiveRoot K hζ
  haveI := finiteDimensional_adjoin_isPrimitiveRoot K hζ
  exact unramified_of_isCyclotomicExtension K ↥K⟮ζ⟯ hmnorm

/-! ### The maximal unramified subextension -/

variable (K) in
/-- **Every finite extension of a local field has an unramified subextension whose degree is the
residue degree.**  Adjoining the root of unity of order one less than the number of residues of the
top field gives a cyclotomic, hence unramified, subextension; that root of unity still has the same
order in the residue field, which forces the residue degree to divide the degree of the
subextension, and no unramified subextension has degree exceeding the residue degree. -/
theorem exists_unramified_le_finrank_eq (M : IntermediateField K Ω) [FiniteDimensional K ↥M]
    {f : ℕ} (hf : Nat.card (DivisionResidue K ↥M) = Nat.card (DivisionResidue K K) ^ f) :
    ∃ (L : IntermediateField K Ω) (_ : FiniteDimensional K ↥L), L ≤ M ∧
      (∀ z : ↥L, z ≠ 0 → ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥L z = ‖c‖) ∧ finrank K ↥L = f := by
  classical
  have h2 : 2 ≤ Nat.card (DivisionResidue K K) := Finite.one_lt_card
  have hM1 : 1 < Nat.card (DivisionResidue K ↥M) := Finite.one_lt_card
  have hf0 : f ≠ 0 := by
    rintro rfl
    rw [pow_zero] at hf
    omega
  have hQf : 2 ≤ Nat.card (DivisionResidue K K) ^ f := le_trans h2 (Nat.le_self_pow hf0 _)
  have hmnorm : ‖((Nat.card (DivisionResidue K K) ^ f - 1 : ℕ) : K)‖ = 1 :=
    norm_natCast_pow_card_divisionResidue_sub_one K hf0
  haveI : NeZero (Nat.card (DivisionResidue K K) ^ f - 1) := ⟨by omega⟩
  obtain ⟨ζ, hζpow, hζord, -⟩ := exists_rootOfUnity_pow_divisionNorm_sub_lt_one K ↥M
  rw [hf] at hζpow hζord
  have hζprim : IsPrimitiveRoot ζ (Nat.card (DivisionResidue K K) ^ f - 1) := ⟨hζpow, hζord⟩
  have hζΩ : IsPrimitiveRoot ((ζ : Ω)) (Nat.card (DivisionResidue K K) ^ f - 1) :=
    hζprim.map_of_injective (f := M.val) M.val.toRingHom.injective
  haveI hLfin : FiniteDimensional K ↥K⟮(ζ : Ω)⟯ :=
    finiteDimensional_adjoin_isPrimitiveRoot K hζΩ
  have hurL : ∀ z : ↥K⟮(ζ : Ω)⟯, z ≠ 0 →
      ∃ c : K, c ≠ 0 ∧ divisionNorm K ↥K⟮(ζ : Ω)⟯ z = ‖c‖ :=
    unramified_adjoin_isPrimitiveRoot K hζΩ hmnorm
  have hle : K⟮(ζ : Ω)⟯ ≤ M := IntermediateField.adjoin_simple_le_iff.2 ζ.2
  have hmemζ : (ζ : Ω) ∈ K⟮(ζ : Ω)⟯ := IntermediateField.mem_adjoin_simple_self K _
  have hζL : IsPrimitiveRoot (⟨(ζ : Ω), hmemζ⟩ : ↥K⟮(ζ : Ω)⟯)
      (Nat.card (DivisionResidue K K) ^ f - 1) :=
    IsPrimitiveRoot.of_map_of_injective (f := K⟮(ζ : Ω)⟯.val) hζΩ
      K⟮(ζ : Ω)⟯.val.toRingHom.injective
  have hdvd1 : f ∣ finrank K ↥K⟮(ζ : Ω)⟯ := by
    have hres := dvd_card_divisionResidue_sub_one_of_isPrimitiveRoot hζL hmnorm
    rw [card_divisionResidue_of_unramified K ↥K⟮(ζ : Ω)⟯ hurL] at hres
    exact dvd_of_pow_sub_one_dvd_pow_sub_one h2 hres
  have hdvd2 : finrank K ↥K⟮(ζ : Ω)⟯ ∣ f :=
    finrank_dvd_of_unramified_le K⟮(ζ : Ω)⟯ M hurL hle hf
  exact ⟨K⟮(ζ : Ω)⟯, hLfin, hle, hurL, Nat.dvd_antisymm hdvd2 hdvd1⟩

end Ambient

end InverseGalois.CFT
