/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Analytic.GaloisLocalCycles
import InverseGalois.Rigidity.RET.Pi1.Topological.PlaneSpider

/-!
# Branch cycles of an extension of `ℂ(T)`, attached to the branch points and multiplying to one

`RET/Analytic/GaloisLocalCycles.lean` presents the Galois group of a finite Galois extension of
`ℂ(T)` as a quotient of the fundamental group of a punctured plane, generated by the images of
loops around the individual punctures.  What that statement does not record is the relation among
those loops.

Combining the same presentation with the generating product-one system of
`RET/Pi1/Topological/PlaneSpider.lean` supplies the relation as well: the loops can be chosen so
that their images, in a prescribed order and followed by a single further element, multiply to the
identity.  The extra element is the inverse of a large boundary loop, that is, a loop around the
point at infinity, so the system is the branch-cycle system of the extension over the punctures
together with infinity.

## Main results

* `Rigidity.RET.Analytic.exists_prodOneBranchCycles_of_isGalois` — the branch cycles of a finite
  Galois extension of `ℂ(T)`, one attached to each branch point, multiplying to the identity and
  generating the Galois group.
-/

open Polynomial Rigidity.RET

noncomputable section

namespace Rigidity.RET.Analytic

/-- **The Galois group of a finite Galois extension of `ℂ(T)` is generated by branch cycles which
multiply to the identity, one attached to each puncture.**

The extension is presented by a monic family of equations, whose degenerate parameters are the
punctures.  Its Galois group is a quotient of the fundamental group of the punctured plane, and the
system of loops is the one of `Rigidity.RET.exists_punctureLoops_prodOne_compl`: the entry indexed
by `i.castSucc` winds around the puncture `pt i` alone, and the whole ordered list, whose last
entry accounts for the point at infinity, has product the identity. -/
theorem exists_prodOneBranchCycles_of_isGalois (M : Type) [Field M] [Algebra (RatFunc ℂ) M]
    [FiniteDimensional (RatFunc ℂ) M] [IsGalois (RatFunc ℂ) M] :
    ∃ (P : Polynomial (Polynomial ℂ)) (S : Finset ℂ) (z₀ : ℂ) (hz₀ : z₀ ∉ (S : Set ℂ)),
      P.Monic ∧ (∀ z ∉ (S : Set ℂ), (spec P z).Separable) ∧
        ∃ (Φ : FundamentalGroup ↥((S : Set ℂ)ᶜ) ⟨z₀, hz₀⟩ →* (M ≃ₐ[RatFunc ℂ] M)) (r : ℕ)
          (pt : Fin r → ℂ) (γ : Fin (r + 1) → FundamentalGroup ↥((S : Set ℂ)ᶜ) ⟨z₀, hz₀⟩),
          Function.Surjective Φ ∧ Function.Injective pt ∧ Set.range pt = (S : Set ℂ) ∧
            (∀ i : Fin r, IsPunctureLoop ((S : Set ℂ)ᶜ) (pt i) hz₀ (γ i.castSucc)) ∧
              (List.ofFn fun i => Φ (γ i)).prod = 1 ∧
                Subgroup.closure (Set.range fun i => Φ (γ i)) = ⊤ := by
  obtain ⟨P, S, z₀, hz₀, hP, hS, Φ, -, hsurj, -, -⟩ :=
    exists_localizedBranchCycles_of_isGalois M
  obtain ⟨r, pt, γ, hinj, hrange, hloop, hprod, hgen⟩ :=
    exists_punctureLoops_prodOne_of_surjective S.finite_toSet hz₀ hsurj
  exact ⟨P, S, z₀, hz₀, hP, hS, Φ, r, pt, γ, hsurj, hinj, hrange, hloop, hprod, hgen⟩

end Rigidity.RET.Analytic

end
