/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.RET.Analytic.GermInertia
import InverseGalois.Rigidity.RET.Descent.AKLBGen

/-!
# The ramification index of a branch place is the Kummer exponent

An analytic branch of a finite Galois extension `Ω` of `ℂ(T)` at a point `s`, read in the Kummer
coordinate `T = s + u ^ d`, cuts out a place of the integral model of the cover.  Two independent
bounds pin down the ramification index there.

From below: the rotation `u ↦ c u` of the Kummer coordinate, `c` a primitive `d`-th root of unity,
is realized by an automorphism `σ` of the extension of order `d`; it fixes the branch place, hence
lies in its inertia group, because the residues at a place of a cover over an algebraically closed
constant field are all constants.  So the inertia group has at least `d` elements.

From above: the uniformizer `X - s` becomes `u ^ d`, which vanishes to order exactly `d`, so the
place is ramified to order at most `d`; and the inertia group of a place of an AKLB extension has
order the ramification index.

The two meet, and the inertia group is cyclic of order exactly `d`, generated by the rotation.  This
is the comparison of the analytic and the algebraic normalizations at a branch point: the local
monodromy in its analytic guise, a rotation of a Kummer coordinate, is a distinguished generator of
an algebraic inertia group.  The hypothesis that makes it work is primitivity of the branch — that
no nontrivial rotation of the coordinate fixes the branch — which says the Kummer exponent used to
read the branch is the right one and not a multiple of it.

## Main definitions

* `Rigidity.RET.Analytic.germInModel` — a branch, restricted to the integral model.
* `Rigidity.RET.Analytic.branchPlace` — the place of the cover cut out by a branch.

## Main results

* `Rigidity.RET.Analytic.mem_inertia_branchPlace` — a rotation of the Kummer coordinate lies in the
  inertia group of the branch place.
* `Rigidity.RET.Analytic.inertia_branchPlace_eq_zpowers` — the inertia group is generated by it.
* `Rigidity.RET.Analytic.card_inertia_branchPlace` — the inertia group has order the Kummer
  exponent.
* `Rigidity.RET.Analytic.exists_inertia_generator_of_branch` — a primitive branch of Kummer exponent
  `d` produces a place whose inertia group is cyclic of order `d`.
-/

open Filter Topology Polynomial
open scoped Pointwise

noncomputable section

namespace Rigidity.RET.Analytic

open MeroGerm Rigidity.RET.AKLBGen

attribute [local instance] Ideal.Quotient.field Rigidity.RET.AKLBGen.instMSA
  Rigidity.RET.AKLBGen.instIsFrac Rigidity.RET.AKLBGen.instIGG Rigidity.RET.AKLBGen.instFinite
  Rigidity.RET.AKLBGen.instIntegral Rigidity.RET.AKLBGen.instFaithful
  Rigidity.RET.AKLBGen.instDedekindB

variable {Ω : Type*} [Field Ω] [Algebra (RatFunc ℂ) Ω] [FiniteDimensional (RatFunc ℂ) Ω]
  [IsGalois (RatFunc ℂ) Ω] [Algebra (Polynomial ℂ) Ω]
  [IsScalarTower (Polynomial ℂ) (RatFunc ℂ) Ω]

variable {s : ℂ} {d : ℕ}

/-- A branch, restricted to the integral model. -/
def germInModel (Ψ : Ω →+* MeroGerm (0 : ℂ)) : Bring ℂ Ω →+* MeroGerm (0 : ℂ) :=
  Ψ.comp (Subalgebra.val (integralClosure (Polynomial ℂ) Ω)).toRingHom

omit [Algebra (RatFunc ℂ) Ω] [FiniteDimensional (RatFunc ℂ) Ω] [IsGalois (RatFunc ℂ) Ω]
  [IsScalarTower (Polynomial ℂ) (RatFunc ℂ) Ω] in
@[simp] theorem germInModel_apply (Ψ : Ω →+* MeroGerm (0 : ℂ)) (b : Bring ℂ Ω) :
    germInModel Ψ b = Ψ (b : Ω) := rfl

omit [FiniteDimensional (RatFunc ℂ) Ω] [IsGalois (RatFunc ℂ) Ω] in
/-- A branch restricted to the integral model extends the Kummer substitution. -/
theorem germInModel_algebraMap (hd : d ≠ 0) {Ψ : Ω →+* MeroGerm (0 : ℂ)}
    (hΨ : ∀ x : RatFunc ℂ, Ψ (algebraMap (RatFunc ℂ) Ω x) = kummerRatHom s hd x)
    (p : Polynomial ℂ) :
    germInModel Ψ (algebraMap (Polynomial ℂ) (Bring ℂ Ω) p) = kummerHom s d p := by
  have hcoe : ((algebraMap (Polynomial ℂ) (Bring ℂ Ω) p : Bring ℂ Ω) : Ω)
      = algebraMap (Polynomial ℂ) Ω p := rfl
  rw [germInModel_apply, hcoe, IsScalarTower.algebraMap_apply (Polynomial ℂ) (RatFunc ℂ) Ω, hΨ,
    kummerRatHom_algebraMap]

omit [Algebra (RatFunc ℂ) Ω] [FiniteDimensional (RatFunc ℂ) Ω] [IsGalois (RatFunc ℂ) Ω]
  [IsScalarTower (Polynomial ℂ) (RatFunc ℂ) Ω] in
/-- Every element of the integral model is integral over `ℂ[X]`. -/
theorem isIntegral_model (b : Bring ℂ Ω) : IsIntegral (Polynomial ℂ) b :=
  Algebra.IsIntegral.isIntegral b

variable (hd : d ≠ 0) {Ψ : Ω →+* MeroGerm (0 : ℂ)}
  (hΨ : ∀ x : RatFunc ℂ, Ψ (algebraMap (RatFunc ℂ) Ω x) = kummerRatHom s hd x)

include hd hΨ

/-- **The place of the cover cut out by an analytic branch** at the point `s`. -/
def branchPlace : Ideal (Bring ℂ Ω) :=
  germPlace (germInModel_algebraMap hd hΨ) isIntegral_model

instance branchPlace_isPrime : (branchPlace hd hΨ).IsPrime := germPlace_isPrime _ _

instance branchPlace_liesOver : (branchPlace hd hΨ).LiesOver (placeP ℂ s) :=
  ⟨(comap_germPlace hd (germInModel_algebraMap hd hΨ) isIntegral_model).symm⟩

set_option synthInstance.maxHeartbeats 400000 in
instance branchPlace_isMaximal : (branchPlace hd hΨ).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance (ne_bot_of_liesOver ℂ Ω s _)

set_option synthInstance.maxHeartbeats 400000 in
/-- **The ramification index at the branch place is at most the Kummer exponent.** -/
theorem ramificationIdxIn_branchPlace_le :
    Ideal.ramificationIdxIn (placeP ℂ s) (Bring ℂ Ω) ≤ d := by
  rw [Ideal.ramificationIdxIn_eq_ramificationIdx (placeP ℂ s) (branchPlace hd hΨ)
    (Ω ≃ₐ[RatFunc ℂ] Ω)]
  exact ramificationIdx_germPlace_le (germInModel_algebraMap hd hΨ) isIntegral_model

omit [FiniteDimensional (RatFunc ℂ) Ω] in
/-- An automorphism which rotates the Kummer coordinate of the branch stabilizes the branch
place. -/
theorem smul_branchPlace {c : ℂ} (hc : c ≠ 0) {σ : Ω ≃ₐ[RatFunc ℂ] Ω}
    (h : ∀ x : Ω, Ψ (σ x) = scaleGerm hc (Ψ x)) : σ • branchPlace hd hΨ = branchPlace hd hΨ := by
  set σB : Bring ℂ Ω →+* Bring ℂ Ω :=
    MulSemiringAction.toRingHom (Ω ≃ₐ[RatFunc ℂ] Ω) (Bring ℂ Ω) σ with hσB
  have hcomp : (germInModel Ψ).comp σB = (scaleGerm hc).comp (germInModel Ψ) := by
    refine RingHom.ext fun b => ?_
    show Ψ ((σ • b : Bring ℂ Ω) : Ω) = scaleGerm hc (Ψ (b : Ω))
    rw [coe_smul ℂ Ω σ b, h]
  have hQ := germPlace_comap_eq_self_of_scale hc (germInModel_algebraMap hd hΨ)
    isIntegral_model σB hcomp
  have hmem : ∀ b : Bring ℂ Ω, σ • b ∈ branchPlace hd hΨ ↔ b ∈ branchPlace hd hΨ :=
    fun b => Ideal.ext_iff.1 hQ b
  ext x
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, ← hmem (σ⁻¹ • x), smul_inv_smul]

set_option synthInstance.maxHeartbeats 400000 in
/-- An automorphism which rotates the Kummer coordinate of the branch lies in the inertia group of
the branch place. -/
theorem mem_inertia_branchPlace {c : ℂ} (hc : c ≠ 0) {σ : Ω ≃ₐ[RatFunc ℂ] Ω}
    (h : ∀ x : Ω, Ψ (σ x) = scaleGerm hc (Ψ x)) :
    σ ∈ (branchPlace hd hΨ).inertia (Ω ≃ₐ[RatFunc ℂ] Ω) := by
  rw [inertia_eq_stabilizer ℂ Ω s (branchPlace hd hΨ)]
  exact smul_branchPlace hd hΨ hc h

set_option synthInstance.maxHeartbeats 400000 in
/-- **The inertia group at the branch place is generated by the rotation of the Kummer
coordinate.** -/
theorem inertia_branchPlace_eq_zpowers {c : ℂ} (hc : c ≠ 0) (hcd : orderOf c = d)
    (hprim : ∀ (a : ℂ) (ha : a ≠ 0), a ^ d = 1 → (∀ x : Ω, scaleGerm ha (Ψ x) = Ψ x) → a = 1)
    {σ : Ω ≃ₐ[RatFunc ℂ] Ω} (h : ∀ x : Ω, Ψ (σ x) = scaleGerm hc (Ψ x)) :
    (branchPlace hd hΨ).inertia (Ω ≃ₐ[RatFunc ℂ] Ω) = Subgroup.zpowers σ := by
  have hσ : orderOf σ = d := orderOf_eq_of_scaleGerm hc hcd hprim h
  have hle : Subgroup.zpowers σ ≤ (branchPlace hd hΨ).inertia (Ω ≃ₐ[RatFunc ℂ] Ω) :=
    Subgroup.zpowers_le.2 (mem_inertia_branchPlace hd hΨ hc h)
  have hzp : Nat.card (Subgroup.zpowers σ) = d := by rw [Nat.card_zpowers, hσ]
  have hcard : Nat.card ((branchPlace hd hΨ).inertia (Ω ≃ₐ[RatFunc ℂ] Ω)) ≤ d := by
    rw [card_inertia ℂ Ω s (branchPlace hd hΨ)]
    exact ramificationIdxIn_branchPlace_le hd hΨ
  exact (Subgroup.eq_of_le_of_card_ge hle (hzp ▸ hcard)).symm

set_option synthInstance.maxHeartbeats 400000 in
/-- **The inertia group at the branch place has order exactly the Kummer exponent.** -/
theorem card_inertia_branchPlace {c : ℂ} (hc : c ≠ 0) (hcd : orderOf c = d)
    (hprim : ∀ (a : ℂ) (ha : a ≠ 0), a ^ d = 1 → (∀ x : Ω, scaleGerm ha (Ψ x) = Ψ x) → a = 1)
    {σ : Ω ≃ₐ[RatFunc ℂ] Ω} (h : ∀ x : Ω, Ψ (σ x) = scaleGerm hc (Ψ x)) :
    Nat.card ((branchPlace hd hΨ).inertia (Ω ≃ₐ[RatFunc ℂ] Ω)) = d := by
  rw [inertia_branchPlace_eq_zpowers hd hΨ hc hcd hprim h, Nat.card_zpowers,
    orderOf_eq_of_scaleGerm hc hcd hprim h]

set_option synthInstance.maxHeartbeats 400000 in
/-- **A primitive analytic branch of Kummer exponent `d` at a point `s` produces a place of the
cover whose inertia group is cyclic of order exactly `d`.** -/
theorem exists_inertia_generator_of_branch {c : ℂ} (hc : c ≠ 0) (hcd : orderOf c = d)
    (hprim : ∀ (a : ℂ) (ha : a ≠ 0), a ^ d = 1 → (∀ x : Ω, scaleGerm ha (Ψ x) = Ψ x) → a = 1) :
    ∃ (Q : Ideal (Bring ℂ Ω)) (σ : Ω ≃ₐ[RatFunc ℂ] Ω), Q.IsMaximal ∧ Q.LiesOver (placeP ℂ s) ∧
      orderOf σ = d ∧ Q.inertia (Ω ≃ₐ[RatFunc ℂ] Ω) = Subgroup.zpowers σ ∧
      Nat.card (Q.inertia (Ω ≃ₐ[RatFunc ℂ] Ω)) = d := by
  have hcd' : c ^ d = 1 := by rw [← hcd]; exact pow_orderOf_eq_one c
  obtain ⟨σ, hσ⟩ := exists_algEquiv_of_scaleGerm hd hc hcd' hΨ
  exact ⟨branchPlace hd hΨ, σ, inferInstance, inferInstance,
    orderOf_eq_of_scaleGerm hc hcd hprim hσ,
    inertia_branchPlace_eq_zpowers hd hΨ hc hcd hprim hσ,
    card_inertia_branchPlace hd hΨ hc hcd hprim hσ⟩

end Rigidity.RET.Analytic

end
