/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Wreath.GeomBase
import InverseGalois.Rigidity.RET.Wreath.CompositumDegree

/-!
# Extension of constants: degrees over `ℚ̄(T)` rather than over the geometric base

The compositum theorems of `CompositumDegree` compare a finite Galois extension `V / ℚ(T)` inside
`QTbar` with the compositum `V · ℚ̄(T)`, and they measure that compositum over the *intermediate
field* `geomBase` — the copy of `ℚ̄(T)` sitting inside `QTbar`.  Everything downstream, however,
happens in `IntermediateField (RatFunc k) QTbar`: Kummer theory, radicands and inertia are all
phrased over the honest field `ℚ̄(T) = RatFunc k`, not over its image.  This file performs the
translation.

The bridge is purely formal.  An intermediate field `W` of `QTbar / ℚ(T)` that contains `geomBase`
is, as a subset of `QTbar`, already closed under the arithmetic of `ℚ̄(T)`, so it can be reread as
an intermediate field of `QTbar / ℚ̄(T)` with *the same underlying set*: that is `geomRestrict`.
Applying it to the compositum `V ⊔ geomBase` produces the **geometric closure** `geomClosure V`,
the field generated by `V` over `ℚ̄(T)`.  Because the membership predicate is unchanged, the
coercions `↥(geomClosure V)` and `↥(V ⊔ geomBase)` are definitionally equal, and the two degrees
in play differ only by the factor `[geomBase : ℚ̄(T)] = 1`; the tower law turns that observation
into the identity `finrank_geomClosure_eq_finrank_sup`.

Transporting the natural-irrationalities theorems across that identity yields the arithmetic
payload: extension of constants can only lower the degree, it lowers nothing exactly when the
extension is regular over `ℚ(T)`, and conversely a preserved degree detects regularity.

## Main results

* `Rigidity.RET.Wreath.geomRestrict` — an intermediate field of `QTbar / ℚ(T)` containing the
  geometric base, reread as an intermediate field of `QTbar / ℚ̄(T)`.
* `Rigidity.RET.Wreath.geomClosure` — the geometric closure of an intermediate field of
  `QTbar / ℚ(T)`, namely the field it generates over `ℚ̄(T)`.
* `Rigidity.RET.Wreath.geomClosure_eq_adjoin` — the geometric closure is the field obtained by
  adjoining the given field to `ℚ̄(T)`.
* `Rigidity.RET.Wreath.instFiniteDimensionalGeomClosure` — the geometric closure of a finite
  extension of `ℚ(T)` is finite over `ℚ̄(T)`.
* `Rigidity.RET.Wreath.finrank_geomClosure_eq_finrank_sup` — the degree of the geometric closure
  over `ℚ̄(T)` is the degree of the compositum over the geometric base.
* `Rigidity.RET.Wreath.finrank_geomClosure_le` — extension of constants does not raise the degree.
* `Rigidity.RET.Wreath.finrank_geomClosure` — a regular extension keeps its degree after extension
  of constants.
* `Rigidity.RET.Wreath.regular_of_finrank_geomClosure` — conversely, an extension keeping its
  degree after extension of constants is regular.
* `Rigidity.RET.Wreath.finrank_le_finrank_of_le` — degrees over `ℚ̄(T)` are monotone in the field.
* `Rigidity.RET.Wreath.finrank_le_of_le` — geometric closures of nested fields have nested degrees.
-/

noncomputable section

namespace Rigidity.RET.Wreath

open GeomAKLB (k)

open Module

/-! ## Rereading a field over `ℚ(T)` as a field over `ℚ̄(T)` -/

/-- **An intermediate field of `QTbar / ℚ(T)` containing the geometric base is an intermediate
field of `QTbar / ℚ̄(T)`.**  As a subset of `QTbar` it is a subfield, and it contains the image of
`ℚ̄(T)` because it contains the geometric base; nothing about the underlying set changes. -/
def geomRestrict (W : IntermediateField QT QTbar) (h : geomBase ≤ W) :
    IntermediateField (RatFunc k) QTbar :=
  W.toSubfield.toIntermediateField fun x => h (mem_geomBase_iff.2 ⟨x, rfl⟩)

/-- Rereading a field over `ℚ̄(T)` leaves its elements unchanged. -/
@[simp] theorem mem_geomRestrict {W : IntermediateField QT QTbar} {h : geomBase ≤ W} {x : QTbar} :
    x ∈ geomRestrict W h ↔ x ∈ W := Iff.rfl

/-- Restricting the scalars of the reread field back to `ℚ(T)` recovers the original field. -/
theorem restrictScalars_geomRestrict (W : IntermediateField QT QTbar) (h : geomBase ≤ W) :
    (geomRestrict W h).restrictScalars QT = W := rfl

/-! ## The geometric closure -/

/-- **The geometric closure of an intermediate field of `QTbar / ℚ(T)`**: the field it generates
together with the geometric base, read as an extension of `ℚ̄(T)`. -/
def geomClosure (V : IntermediateField QT QTbar) : IntermediateField (RatFunc k) QTbar :=
  geomRestrict (V ⊔ geomBase) le_sup_right

/-- The geometric closure consists of the elements of the compositum with the geometric base. -/
@[simp] theorem mem_geomClosure {V : IntermediateField QT QTbar} {x : QTbar} :
    x ∈ geomClosure V ↔ x ∈ V ⊔ geomBase := Iff.rfl

/-- Restricting the scalars of the geometric closure to `ℚ(T)` gives the compositum with the
geometric base. -/
theorem restrictScalars_geomClosure (V : IntermediateField QT QTbar) :
    (geomClosure V).restrictScalars QT = V ⊔ geomBase := rfl

/-- **A field is contained in its geometric closure.** -/
theorem le_geomClosure (V : IntermediateField QT QTbar) : ∀ x ∈ V, x ∈ geomClosure V :=
  fun _ hx => mem_geomClosure.2 ((le_sup_left : V ≤ V ⊔ geomBase) hx)

/-- **The geometric closure is monotone.** -/
theorem geomClosure_mono {V W : IntermediateField QT QTbar} (h : V ≤ W) :
    geomClosure V ≤ geomClosure W :=
  fun _ hx => mem_geomClosure.2 (sup_le_sup_right h geomBase (mem_geomClosure.1 hx))

/-- **The geometric closure contains the base field `ℚ(T)`**, since the geometric base does. -/
theorem algebraMap_QT_mem_geomClosure (V : IntermediateField QT QTbar) (r : QT) :
    algebraMap QT QTbar r ∈ geomClosure V :=
  mem_geomClosure.2 ((le_sup_right : geomBase ≤ V ⊔ geomBase) (algebraMap_mem_geomBase r))

/-- **The geometric closure is generated over `ℚ̄(T)` by the given field.**  The adjunction is
contained in the geometric closure because the latter is a field over `ℚ̄(T)` containing `V`;
conversely the adjunction, read back as an extension of `ℚ(T)`, contains both `V` and the image
of `ℚ̄(T)`, hence the field they generate. -/
theorem geomClosure_eq_adjoin (V : IntermediateField QT QTbar) :
    geomClosure V = IntermediateField.adjoin (RatFunc k) (V : Set QTbar) := by
  refine le_antisymm ?_ (IntermediateField.adjoin_le_iff.2 (le_geomClosure V))
  intro x hx
  have hle : V ⊔ geomBase ≤
      (IntermediateField.adjoin (RatFunc k) (V : Set QTbar)).restrictScalars QT := by
    refine sup_le (fun y hy => ?_) (fun y hy => ?_)
    · exact IntermediateField.subset_adjoin (RatFunc k) (V : Set QTbar) hy
    · obtain ⟨u, rfl⟩ := mem_geomBase_iff.1 hy
      exact (IntermediateField.adjoin (RatFunc k) (V : Set QTbar)).algebraMap_mem u
  exact hle (mem_geomClosure.1 hx)

/-! ## The geometric base as an extension of `ℚ̄(T)` -/

/-- **The geometric base is an algebra over `ℚ̄(T)`.**  It is by construction the bottom
intermediate field of `QTbar / ℚ̄(T)`, with its scalars restricted to `ℚ(T)`. -/
noncomputable instance instAlgebraGeomBase : Algebra (RatFunc k) ↥geomBase :=
  inferInstanceAs (Algebra (RatFunc k) ↥(⊥ : IntermediateField (RatFunc k) QTbar))

/-- **`ℚ̄(T)` acts on the geometric base**, by multiplication inside `QTbar`.  The action is
recorded separately from the algebra structure because the generic search from `Algebra` to `SMul`
is expensive at these subtypes. -/
noncomputable instance instSMulGeomBase : SMul (RatFunc k) ↥geomBase := Algebra.toSMul

/-- **The geometric base is a `ℚ̄(T)`-module**, recorded separately from its algebra structure for
the same reason. -/
noncomputable instance instModuleGeomBase : Module (RatFunc k) ↥geomBase :=
  inferInstanceAs (Module (RatFunc k) ↥(⊥ : IntermediateField (RatFunc k) QTbar))

/-- **The geometric base is finite over `ℚ̄(T)`.** -/
instance instFiniteDimensionalGeomBase : FiniteDimensional (RatFunc k) ↥geomBase :=
  inferInstanceAs (FiniteDimensional (RatFunc k) ↥(⊥ : IntermediateField (RatFunc k) QTbar))

/-- **The geometric base has degree one over `ℚ̄(T)`**: it is the image of `ℚ̄(T)` in `QTbar`, and
the embedding is injective. -/
theorem finrank_geomBase : finrank (RatFunc k) ↥geomBase = 1 :=
  IntermediateField.finrank_bot

/-! ## The geometric closure as an extension of the geometric base -/

/-- **The geometric closure is an algebra over the geometric base.**  It has the same elements as
the compositum `V ⊔ geomBase`, which carries the compositum algebra structure of
`Rigidity.RET.Wreath.instAlgebraSupRight`. -/
noncomputable instance instAlgebraGeomBaseClosure (V : IntermediateField QT QTbar) :
    Algebra ↥geomBase ↥(geomClosure V) :=
  inferInstanceAs (Algebra ↥geomBase ↥(V ⊔ geomBase))

/-- **The geometric base acts on the geometric closure**, by multiplication inside `QTbar`. -/
noncomputable instance instSMulGeomBaseClosure (V : IntermediateField QT QTbar) :
    SMul ↥geomBase ↥(geomClosure V) := Algebra.toSMul

/-- **The geometric closure is a module over the geometric base.** -/
noncomputable instance instModuleGeomBaseClosure (V : IntermediateField QT QTbar) :
    Module ↥geomBase ↥(geomClosure V) :=
  inferInstanceAs (Module ↥geomBase ↥(V ⊔ geomBase))

/-- **The tower `ℚ̄(T) ⊆ geomBase ⊆ geomClosure V`.**  All three structure maps are inclusions of
subsets of `QTbar`. -/
instance instTowerGeomBaseClosure (V : IntermediateField QT QTbar) :
    IsScalarTower (RatFunc k) ↥geomBase ↥(geomClosure V) :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-- **The geometric closure of a finite extension of `ℚ(T)` is finite over the geometric base.**
This is the compositum finiteness of `Rigidity.RET.Wreath.instFiniteDimensionalSup`. -/
instance instFiniteDimensionalGeomBaseClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] : FiniteDimensional ↥geomBase ↥(geomClosure V) :=
  inferInstanceAs (FiniteDimensional ↥geomBase ↥(V ⊔ geomBase))

/-- **The geometric closure of a finite extension of `ℚ(T)` is finite over `ℚ̄(T)`**, by
transitivity along the tower through the geometric base. -/
instance instFiniteDimensionalGeomClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] : FiniteDimensional (RatFunc k) ↥(geomClosure V) :=
  Module.Finite.trans (R := RatFunc k) ↥geomBase ↥(geomClosure V)

/-! ## The degree of the geometric closure -/

/-- **The degree of the geometric closure over `ℚ̄(T)` is the degree of the compositum over the
geometric base.**  The geometric base has degree one over `ℚ̄(T)`, so the tower law through it
leaves the degree of the compositum untouched. -/
theorem finrank_geomClosure_eq_finrank_sup (V : IntermediateField QT QTbar) :
    finrank (RatFunc k) ↥(geomClosure V) = finrank ↥geomBase ↥(V ⊔ geomBase) := by
  have h := Module.finrank_mul_finrank (RatFunc k) ↥geomBase ↥(geomClosure V)
  rw [finrank_geomBase, one_mul] at h
  exact h.symm

/-- **The geometric closure of a finite Galois extension of `ℚ(T)` has at most its degree.**
Extension of constants can only shrink the minimal polynomial of a primitive element. -/
theorem finrank_geomClosure_le (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] [IsGalois QT ↥V] :
    finrank (RatFunc k) ↥(geomClosure V) ≤ finrank QT ↥V := by
  rw [finrank_geomClosure_eq_finrank_sup]
  exact finrank_sup_le_finrank geomBase V

/-- **A regular extension keeps its degree after extension of constants.**  Having no constants
beyond `ℚ` means meeting the geometric base trivially, and natural irrationalities then gives the
compositum the full degree. -/
theorem finrank_geomClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] [IsGalois QT ↥V] (hreg : algebraicClosure ℚ ↥V = ⊥) :
    finrank (RatFunc k) ↥(geomClosure V) = finrank QT ↥V := by
  rw [finrank_geomClosure_eq_finrank_sup]
  exact finrank_sup_eq_of_inf_eq_bot geomBase V ((inf_geomBase_eq_bot_iff V).2 hreg)

/-- **An extension that keeps its degree after extension of constants is regular.**  The converse
half of natural irrationalities forces the intersection with the geometric base to be trivial,
which is exactly the absence of constants beyond `ℚ`. -/
theorem regular_of_finrank_geomClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] [IsGalois QT ↥V]
    (h : finrank (RatFunc k) ↥(geomClosure V) = finrank QT ↥V) :
    algebraicClosure ℚ ↥V = ⊥ := by
  rw [finrank_geomClosure_eq_finrank_sup] at h
  exact (inf_geomBase_eq_bot_iff V).1 (inf_eq_bot_of_finrank_sup_eq geomBase V h)

/-- **Degrees over `ℚ̄(T)` are monotone.**  The degree of the smaller field divides the degree of
the larger one, by the tower law for the relative degree, and the larger degree is positive. -/
theorem finrank_le_finrank_of_le {U W : IntermediateField (RatFunc k) QTbar} (h : U ≤ W)
    [FiniteDimensional (RatFunc k) ↥W] :
    finrank (RatFunc k) ↥U ≤ finrank (RatFunc k) ↥W :=
  Nat.le_of_dvd Module.finrank_pos
    (Dvd.intro _ (IntermediateField.finrank_bot_mul_relfinrank h))

/-- **Nested fields have nested geometric closures, hence nested degrees over `ℚ̄(T)`.** -/
theorem finrank_le_of_le {V W : IntermediateField QT QTbar} (h : V ≤ W)
    [FiniteDimensional QT ↥W] :
    finrank (RatFunc k) ↥(geomClosure V) ≤ finrank (RatFunc k) ↥(geomClosure W) :=
  finrank_le_finrank_of_le (geomClosure_mono h)

end Rigidity.RET.Wreath
