/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Wreath.GeomDegree
import InverseGalois.Rigidity.RET.Wreath.KummerLayer

/-!
# Extension of constants preserves normality, Galois-ness and cyclicity

The geometric closure `geomClosure V` of an intermediate field `V` of `QTbar / ℚ(T)` is the field
`V · ℚ̄(T)` generated by `V` over the geometric base.  This file records that the three properties
that matter for the wreath-product construction survive the passage from `V / ℚ(T)` to
`geomClosure V / ℚ̄(T)`.

Everything rests on the observation that a `ℚ̄(T)`-automorphism of `QTbar` is in particular a
`ℚ(T)`-automorphism of `QTbar`.  Indeed the geometric base contains the image of `ℚ(T)`, so an
automorphism fixing `ℚ̄(T)` pointwise fixes `ℚ(T)` pointwise as well; `toQTAlgEquiv` performs that
reinterpretation.  Since `QTbar` is normal over `ℚ̄(T)` — it is algebraically closed, and it is
algebraic over `ℚ̄(T)` because it is already algebraic over `ℚ(T)` — normality of an intermediate
field is tested by stability under such automorphisms.  Now `geomClosure V` is generated over
`ℚ̄(T)` by `V`, and `V` is stable under every `ℚ(T)`-automorphism of `QTbar` when it is normal over
`ℚ(T)`, so `geomClosure V` is stable too.  Separability is automatic in characteristic zero and
finiteness is inherited, so a finite Galois `V` has a finite Galois geometric closure.

Cyclicity is the one statement that is not a formality about `QTbar`: it uses the injectivity of
restriction `restrictAut` from the geometric Galois group of `geomClosure V` to the Galois group of
`V`, which holds because `V` together with `ℚ̄(T)` generates `geomClosure V`.  A group admitting an
injective homomorphism into a cyclic group is cyclic.

## Main results

* `Rigidity.RET.Wreath.isAlgebraic_geom_QTbar` — `QTbar` is algebraic over the geometric base
  `ℚ̄(T)`.
* `Rigidity.RET.Wreath.algEquiv_fixes_QT` — a `ℚ̄(T)`-automorphism of `QTbar` fixes `ℚ(T)`
  pointwise.
* `Rigidity.RET.Wreath.toQTAlgEquiv` — a `ℚ̄(T)`-automorphism of `QTbar`, reread as a
  `ℚ(T)`-automorphism.
* `Rigidity.RET.Wreath.normal_geomClosure` — the geometric closure of a normal extension of `ℚ(T)`
  is normal over `ℚ̄(T)`.
* `Rigidity.RET.Wreath.isGalois_geomClosure` — the geometric closure of a finite Galois extension
  of `ℚ(T)` is Galois over `ℚ̄(T)`.
* `Rigidity.RET.Wreath.isCyclic_geomClosure` — the geometric closure of a finite cyclic extension
  of `ℚ(T)` has cyclic Galois group over `ℚ̄(T)`.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET.Wreath

open GeomAKLB

/-! ## `QTbar` over the geometric base -/

/-- **`QTbar` is algebraic over the geometric function field `ℚ̄(T)`.**  An element of `QTbar` is
already algebraic over `ℚ(T)`, and extending the coefficients of a vanishing polynomial along
`ℚ(T) → ℚ̄(T)` keeps it nonzero, since that structure map is injective, and keeps it vanishing,
because the two structure maps compose to the structure map of `QTbar` over `ℚ(T)`. -/
instance isAlgebraic_geom_QTbar : Algebra.IsAlgebraic (RatFunc k) QTbar := by
  have hcomp : (algebraMap (RatFunc k) QTbar).comp (algebraMap QT (RatFunc k))
      = algebraMap QT QTbar := RingHom.ext fun q => geomEmbed.commutes q
  refine ⟨fun x => ?_⟩
  obtain ⟨p, hp0, hpx⟩ := Algebra.IsAlgebraic.isAlgebraic (R := QT) x
  refine ⟨p.map (algebraMap QT (RatFunc k)),
    (Polynomial.map_ne_zero_iff (algebraMap QT (RatFunc k)).injective).2 hp0, ?_⟩
  rw [Polynomial.aeval_def, Polynomial.eval₂_map, hcomp, ← Polynomial.aeval_def]
  exact hpx

/-- **A `ℚ̄(T)`-automorphism of `QTbar` fixes the rational base `ℚ(T)` pointwise.**  The image of
`ℚ(T)` in `QTbar` is contained in the geometric base, so every element of that image is the image of
an element of `ℚ̄(T)`, which the automorphism fixes. -/
theorem algEquiv_fixes_QT (σ : QTbar ≃ₐ[RatFunc k] QTbar) (q : QT) :
    σ (algebraMap QT QTbar q) = algebraMap QT QTbar q := by
  obtain ⟨u, hu⟩ := mem_geomBase_iff.1 (algebraMap_mem_geomBase q)
  rw [← hu, σ.commutes]

/-- **A `ℚ̄(T)`-automorphism of `QTbar`, reread as a `ℚ(T)`-automorphism.**  The underlying ring
equivalence is unchanged; it commutes with the structure map of `ℚ(T)` by
`algEquiv_fixes_QT`. -/
def toQTAlgEquiv (σ : QTbar ≃ₐ[RatFunc k] QTbar) : QTbar ≃ₐ[QT] QTbar :=
  AlgEquiv.ofRingEquiv (f := σ.toRingEquiv) (algEquiv_fixes_QT σ)

@[simp] theorem toQTAlgEquiv_apply (σ : QTbar ≃ₐ[RatFunc k] QTbar) (x : QTbar) :
    toQTAlgEquiv σ x = σ x := rfl

/-! ## Normality and Galois-ness of the geometric closure -/

/-- **`QTbar` is normal over the geometric function field `ℚ̄(T)`.**  It is algebraic over `ℚ̄(T)`,
and being algebraically closed every polynomial splits in it. -/
instance normal_geom_QTbar : Normal (RatFunc k) QTbar where
  toIsAlgebraic := isAlgebraic_geom_QTbar
  splits' _ := IsAlgClosed.splits _

/-- **The geometric closure of a normal extension of `ℚ(T)` is normal over `ℚ̄(T)`.**  Normality
inside the normal extension `QTbar / ℚ̄(T)` means stability under every `ℚ̄(T)`-automorphism of
`QTbar`.  The geometric closure is generated over `ℚ̄(T)` by the given field, so it suffices to move
the generators, and each such automorphism is also a `ℚ(T)`-automorphism, under which the given
field is stable by its own normality. -/
instance normal_geomClosure (V : IntermediateField QT QTbar) [Normal QT ↥V] :
    Normal (RatFunc k) ↥(geomClosure V) := by
  refine IntermediateField.normal_iff_forall_map_le'.mpr fun σ => ?_
  have hmem : ∀ x ∈ (V : Set QTbar), σ x ∈ geomClosure V := by
    intro x hx
    have hV : (toQTAlgEquiv σ : QTbar →ₐ[QT] QTbar) x ∈ V :=
      IntermediateField.normal_iff_forall_map_le'.mp inferInstance (toQTAlgEquiv σ) ⟨x, hx, rfl⟩
    exact le_geomClosure V _ hV
  refine IntermediateField.map_le_iff_le_comap.mpr ?_
  rw [geomClosure_eq_adjoin V]
  refine IntermediateField.adjoin_le_iff.mpr fun x hx => ?_
  have hx' := hmem x hx
  rw [geomClosure_eq_adjoin V] at hx'
  exact hx'

/-- **The geometric closure of a finite Galois extension of `ℚ(T)` is Galois over `ℚ̄(T)`.**  It is
normal by `normal_geomClosure`, and separable because the characteristic is zero. -/
instance isGalois_geomClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] [IsGalois QT ↥V] : IsGalois (RatFunc k) ↥(geomClosure V) := ⟨⟩

/-- **The geometric closure of a finite cyclic extension of `ℚ(T)` is cyclic over `ℚ̄(T)`.**
Restriction to the rational model is an injective homomorphism from the geometric Galois group into
the arithmetic one, because the model generates the closure over `ℚ̄(T)`; a group mapping
injectively into a cyclic group is itself cyclic. -/
theorem isCyclic_geomClosure (V : IntermediateField QT QTbar)
    [FiniteDimensional QT ↥V] [IsGalois QT ↥V] [IsCyclic (↥V ≃ₐ[QT] ↥V)] :
    IsCyclic (↥(geomClosure V) ≃ₐ[RatFunc k] ↥(geomClosure V)) :=
  isCyclic_of_injective (restrictAut V (geomClosure V) (geomClosure_eq_adjoin V).symm)
    (restrictAut_injective V (geomClosure V) (geomClosure_eq_adjoin V).symm)

end Rigidity.RET.Wreath
