/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Wreath.GeomDegree
import InverseGalois.Rigidity.RET.Wreath.KummerLayer
import InverseGalois.Rigidity.RET.KummerIndep

/-!
# Pinning down the degree of a multi-radical extension inside `QTbar`

Let `Eb` be a finite extension of `ℚ̄(T)` realised as an intermediate field of the fixed algebraic
closure `QTbar`, containing a primitive `n`-th root of unity `ζ`, and let `g : ι → Eb` be a finite
family of nonzero elements which is independent modulo `n`-th powers.  Choosing inside `QTbar` an
`n`-th root `w i` of each `g i` and adjoining them all to `Eb` produces an extension whose degree
over `Eb` is as large as it can possibly be, namely `n ^ #ι`: this is the multiplicativity statement
of Kummer theory, packaged in `Rigidity.RET.Kummer.Setup`.

The point of this file is to say that in the coordinates actually used downstream.  All the fields
of the wreath-product construction are intermediate fields of `QTbar / ℚ̄(T)`, so the extension
generated by the radicals has to be produced as such an intermediate field, and its degree has to be
measured over `ℚ̄(T)` rather than over `Eb`.  The first step is performed by
`IntermediateField.adjoin` over the field `Eb` itself and `IntermediateField.restrictScalars`, which
rereads the result over `ℚ̄(T)` without changing its underlying set; the second is the tower law,
which turns the Kummer degree `n ^ #ι` into the factor by which the degree of `Eb` is multiplied.

## Main results

* `Rigidity.RET.Wreath.coe_image_range_mk` — the image in the ambient field of a family of elements
  of an intermediate field, read inside that field, is the original family.
* `Rigidity.RET.Wreath.exists_intermediateField_finrank_radicals` — adjoining to a finite extension
  `Eb` of `ℚ̄(T)` a system of `n`-th roots of elements independent modulo `n`-th powers yields the
  smallest intermediate field of `QTbar / ℚ̄(T)` containing `Eb` and all the radicals, of degree
  exactly `n ^ #ι` times the degree of `Eb`.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET.Wreath

open GeomAKLB (k)

/-- **A family of elements of an intermediate field, read inside that field, has the original family
as its image in the ambient field.**  Both sides consist of the elements `w i`; the left-hand side
merely takes a detour through the subtype. -/
theorem coe_image_range_mk {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω] {ι : Type*}
    (W : IntermediateField F Ω) (w : ι → Ω) (hw : ∀ i, w i ∈ W) :
    ((↑) '' (Set.range fun i => (⟨w i, hw i⟩ : ↥W)) : Set Ω) = Set.range w := by
  ext x
  constructor
  · rintro ⟨-, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨⟨w i, hw i⟩, ⟨i, rfl⟩, rfl⟩

/-- **Adjoining independent radicals to a finite extension of `ℚ̄(T)` multiplies its degree by
`n ^ #ι`.**  The radicals `w i` generate over `Eb` an intermediate field `L₀` of `QTbar / Eb`;
because `Eb` contains a primitive `n`-th root of unity and the radicands are independent modulo
`n`-th powers, Kummer theory identifies the Galois group of `L₀ / Eb` with `(μₙ)^ι`, so
`[L₀ : Eb] = n ^ #ι`.  Restricting the scalars of `L₀` back to `ℚ̄(T)` changes neither its elements
nor its ring structure, and the tower law `ℚ̄(T) ⊆ Eb ⊆ L₀` computes its degree over `ℚ̄(T)`. -/
theorem exists_intermediateField_finrank_radicals
    {ι : Type} [Fintype ι] [DecidableEq ι] {n : ℕ} [NeZero n]
    (Eb : IntermediateField (RatFunc k) QTbar) [FiniteDimensional (RatFunc k) ↥Eb]
    (zeta : ↥Eb) (hz : IsPrimitiveRoot zeta n)
    (g : ι → ↥Eb) (hg : ∀ i, g i ≠ 0)
    (hind : ∀ (m : ι → ℤ) (y : ↥Eb), y ≠ 0 → y ^ n = ∏ i, g i ^ m i → ∀ i, (n : ℤ) ∣ m i)
    (w : ι → QTbar) (hw : ∀ i, w i ^ n = ((g i : QTbar))) :
    ∃ L : IntermediateField (RatFunc k) QTbar,
      (∀ i, w i ∈ L) ∧ (∀ x ∈ Eb, x ∈ L) ∧
      (∀ W : IntermediateField (RatFunc k) QTbar, Eb ≤ W → (∀ i, w i ∈ W) → L ≤ W) ∧
      Module.finrank (RatFunc k) ↥L
        = n ^ Fintype.card ι * Module.finrank (RatFunc k) ↥Eb := by
  obtain ⟨L₀, hL₀⟩ : ∃ L₀ : IntermediateField ↥Eb QTbar,
      L₀ = IntermediateField.adjoin ↥Eb (Set.range w) := ⟨_, rfl⟩
  have hwmem : ∀ i, w i ∈ L₀ := fun i => by
    rw [hL₀]
    exact IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩
  let S : Kummer.Setup ↥Eb ↥L₀ ι n :=
    { zeta := zeta
      g := g
      w := fun i => ⟨w i, hwmem i⟩
      isPrimitiveRoot := hz
      g_ne_zero := hg
      w_pow := fun i => Subtype.ext (hw i)
      adjoin_eq_top := by
        refine adjoin_eq_top_of_adjoin_coe_eq L₀ ?_
        rw [coe_image_range_mk L₀ w hwmem, ← hL₀]
      indep := hind }
  haveI : FiniteDimensional ↥Eb ↥L₀ := S.finiteDimensional
  have hfr : Module.finrank ↥Eb ↥L₀ = n ^ Fintype.card ι := S.finrank_eq
  have htower := Module.finrank_mul_finrank (RatFunc k) ↥Eb ↥L₀
  rw [hfr] at htower
  refine ⟨L₀.restrictScalars (RatFunc k), hwmem, fun x hx => L₀.algebraMap_mem ⟨x, hx⟩,
    fun W hEbW hwW => ?_, ?_⟩
  · show L₀ ≤ IntermediateField.extendScalars hEbW
    rw [hL₀]
    refine IntermediateField.adjoin_le_iff.mpr ?_
    rintro - ⟨i, rfl⟩
    exact hwW i
  calc Module.finrank (RatFunc k) ↥(L₀.restrictScalars (RatFunc k))
      = Module.finrank (RatFunc k) ↥L₀ := rfl
    _ = n ^ Fintype.card ι * Module.finrank (RatFunc k) ↥Eb := by
        rw [← htower]
        exact Nat.mul_comm _ _

end Rigidity.RET.Wreath
