/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Wreath.Conjugates
import InverseGalois.Rigidity.RET.Wreath.GeomBase
import InverseGalois.Rigidity.RET.LineParam

/-!
# Substituting a conjugate for the variable

The construction of a wreath product as a Galois group pulls one and the same cyclic cover back
along every conjugate of a primitive element.  Each pullback is a substitution `T ↦ ϑ`, that is, a
ring homomorphism out of the field of rational functions determined by where it sends the variable.

Two facts about such substitutions are collected here.  The first is that the variable generates
the field of rational functions, so a substitution is controlled by the single value it takes
there: whenever a subfield of the target contains the constants and the substituted element, it
contains the whole image.  The second is that a substitution can be arranged to take its values
inside a prescribed regular extension of the rationals: a translate of a conjugate of a
transcendental primitive element is again transcendental, so it presents a copy of the rational
function field inside that extension.

## Main results

* `Rigidity.RET.Wreath.adjoin_ratFunc_X_eq_top` — the variable generates the field of rational
  functions over the constants.
* `Rigidity.RET.Wreath.paramHom_mem_of_mem` — a substitution lands in any subfield containing the
  constants and the substituted element.
* `Rigidity.RET.Wreath.exists_baseHom` — a substitution of a translated conjugate, with values in
  the given regular extension.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET.Wreath

open GeomAKLB

/-! ## The variable generates -/

/-- **The variable generates the field of rational functions over the constants.**  Every
polynomial is a value of the evaluation map at the variable, and every rational function is a
quotient of two polynomials. -/
theorem adjoin_ratFunc_X_eq_top (K : Type*) [Field K] :
    IntermediateField.adjoin K {(RatFunc.X : RatFunc K)} = ⊤ := by
  have hpoly : ∀ p : K[X], algebraMap K[X] (RatFunc K) p ∈
      IntermediateField.adjoin K {(RatFunc.X : RatFunc K)} := by
    intro p
    have h := Polynomial.aeval_mem_adjoin_singleton (R := K) (x := (RatFunc.X : RatFunc K)) (p := p)
    have hle : Algebra.adjoin K {(RatFunc.X : RatFunc K)} ≤
        (IntermediateField.adjoin K {(RatFunc.X : RatFunc K)}).toSubalgebra :=
      IntermediateField.algebra_adjoin_le_adjoin K _
    have := hle h
    rwa [RatFunc.aeval_X_left_eq_algebraMap] at this
  refine eq_top_iff.2 fun x _ => ?_
  induction x using RatFunc.induction_on with
  | f p q hq => exact div_mem (hpoly p) (hpoly q)

/-! ## Substitutions land where their value does -/

variable {M : Type} [Field M] [Algebra (RatFunc k) M] [Algebra k M]
  [IsScalarTower k (RatFunc k) M]

omit [Algebra (RatFunc k) M] [IsScalarTower k (RatFunc k) M] in
/-- **A substitution takes its values in any subfield holding the constants and the substituted
element.**  The variable generates, so the image of the whole field of rational functions is
generated by the image of the constants together with the image of the variable. -/
theorem paramHom_mem_of_mem {u : M} (hu : Transcendental k u) (Z : Subfield M)
    (hk : ∀ a : k, algebraMap k M a ∈ Z) (hu' : u ∈ Z) (r : RatFunc k) :
    paramHom u hu r ∈ Z :=
  range_subset_of_adjoin_eq_top (adjoin_ratFunc_X_eq_top k) (paramHom u hu) Z
    (fun a => by rw [paramHom_const]; exact hk a)
    (by rw [paramHom_X]; exact hu') r

/-! ## Substituting a translated conjugate -/

/-- **A translated conjugate of a transcendental primitive element presents the rational function
field inside the extension it generates.**  The translate is again transcendental over the
rationals, so evaluation at it is injective on polynomials and extends to the fraction field. -/
theorem exists_baseHom {H : Type*} [Group H] (E : IntermediateField QT QTbar)
    (galH : (↥E ≃ₐ[QT] ↥E) ≃* H) {θ : ↥E} (hθ : Transcendental ℚ θ) (c : ℚ) (h : H) :
    ∃ f : QT →+* QTbar, (∀ r : QT, f r ∈ E) ∧
      f RatFunc.X = ((galH.symm h θ : ↥E) : QTbar) + (c : QTbar) := by
  set y : ↥E := galH.symm h θ + (c : ↥E) with hyd
  have hyt : Transcendental ℚ y := by
    have h1 : ((1 : ℚ) : ↥E) * (galH.symm h θ : ↥E) + (c : ↥E) = y := by
      rw [hyd, Rat.cast_one, one_mul]
    rw [← h1]
    exact transcendental_linear one_ne_zero
      (transcendental_ringHom (galH.symm h).toAlgHom.toRingHom hθ)
  have hginj : Function.Injective ⇑((Polynomial.aeval y : ℚ[X] →ₐ[ℚ] ↥E).toRingHom) :=
    transcendental_iff_injective.mp hyt
  set tw : QT →+* ↥E := IsFractionRing.lift hginj with htw
  have htwX : tw RatFunc.X = y := by
    rw [htw, ← RatFunc.algebraMap_X, IsFractionRing.lift_algebraMap]
    simp
  refine ⟨(IntermediateField.val E).toRingHom.comp tw, fun r => SetLike.coe_mem (tw r), ?_⟩
  rw [RingHom.comp_apply, htwX, hyd, map_add, map_ratCast]
  rfl

end Rigidity.RET.Wreath
