/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Wreath.Layers
import InverseGalois.Rigidity.RET.Wreath.RadicandIndep
import InverseGalois.Rigidity.RET.Descent.ConstantNormal

/-!
# Extending a substitution to a finite extension of the line

A substitution `T ↦ u` is a ring homomorphism out of `ℚ̄(T)`.  To pull a cover of the line back
along it one has to extend it to the covering field, and that is possible because the covering
field is algebraic over the line while the target `ℚ̄(T)‾` is algebraically closed: reading the
target as an algebra over the line *through the substitution* turns the extension problem into the
universal property of an algebraic closure.

Two further tools are collected here.  The image of a field generated over a base by a set is
controlled by the images of the base and of that set, which is how one certifies that a pulled-back
cover lands inside a prescribed compositum; and the value of a conjugate radicand commutes with any
morphism of algebras over the constants, which is how one passes between the radicands read in a
finite extension and the radicands read in the algebraic closure.

## Main results

* `Rigidity.RET.Wreath.range_subset_of_adjoin_set_eq_top` — the image of a field generated by a set
  lies in any subfield containing the images of the base and of the set.
* `Rigidity.RET.Wreath.algebraMap_QT_X` — the variable of `ℚ(T)` and the variable of `ℚ̄(T)` have
  the same image in `ℚ̄(T)‾`.
* `Rigidity.RET.Wreath.exists_substHom` — a substitution extends to any finite extension of the
  line.
* `Rigidity.RET.Wreath.map_conjRadicand` — conjugate radicands are natural in the ambient field.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET.Wreath

open GeomAKLB

/-! ## Images of generated fields -/

/-- **The image of a field generated over a base by a set is controlled by the images of the base
and of the set.**  The underlying subfield of the generated field is the subfield generated by the
image of the base together with the set, and the preimage of a subfield is a subfield. -/
theorem range_subset_of_adjoin_set_eq_top {F N Ω : Type*} [Field F] [Field N] [Field Ω]
    [Algebra F N] {S : Set N} (hS : IntermediateField.adjoin F S = ⊤)
    (f : N →+* Ω) (Z : Subfield Ω)
    (hF : ∀ r : F, f (algebraMap F N r) ∈ Z) (hS' : ∀ s ∈ S, f s ∈ Z) (x : N) : f x ∈ Z := by
  have hmem : x ∈ (IntermediateField.adjoin F S).toSubfield := by
    rw [hS]
    trivial
  rw [IntermediateField.adjoin_toSubfield] at hmem
  have hle : Subfield.closure (Set.range (algebraMap F N) ∪ S) ≤ Subfield.comap f Z := by
    rw [Subfield.closure_le]
    rintro y (⟨r, rfl⟩ | hy)
    · exact hF r
    · exact hS' y hy
  exact hle hmem

/-! ## The two variables -/

/-- **The variable of `ℚ(T)` and the variable of `ℚ̄(T)` have the same image in the algebraic
closure.**  Extending the coefficients along `ℚ → ℚ̄` fixes the variable, and the embedding of
`ℚ̄(T)` is a morphism of `ℚ(T)`-algebras. -/
theorem algebraMap_QT_X :
    algebraMap QT QTbar (RatFunc.X : QT) = algebraMap (RatFunc k) QTbar (RatFunc.X : RatFunc k) := by
  rw [algebraMap_geom_eq, ← Descent.algebraMap_ratFunc_closure_X]
  exact (geomEmbed.commutes _).symm

/-! ## Extending a substitution -/

/-- **A substitution extends to any finite extension of the line.**  Reading the algebraic closure
as an algebra over the line through the substitution makes the extension an algebraic algebra over
the line, and an algebraically closed field receives every such algebra. -/
theorem exists_substHom (W : Type) [Field W] [Algebra (RatFunc k) W]
    [FiniteDimensional (RatFunc k) W] {u : QTbar} (hu : Transcendental k u) :
    ∃ f : W →+* QTbar, ∀ r : RatFunc k, f (algebraMap (RatFunc k) W r) = paramHom u hu r := by
  letI : Algebra (RatFunc k) QTbar := (paramHom u hu).toAlgebra
  haveI : Algebra.IsAlgebraic (RatFunc k) W := Algebra.IsAlgebraic.of_finite _ _
  exact ⟨(IsAlgClosed.lift : W →ₐ[RatFunc k] QTbar).toRingHom, fun r => AlgHom.commutes _ r⟩

/-! ## Naturality of the radicands -/

variable {F : Type*} [Field F] [Algebra k F] {ι : Type*} {r : ℕ}

/-- **A conjugate radicand is natural in the ambient field**: it is a product of translates of the
member of the family by constants, and a morphism of algebras over the constants preserves both. -/
theorem map_conjRadicand (Θ : ι → F) (t : Fin r → k) (e : Fin r → ℕ) (c : k)
    (f : F →ₐ[k] QTbar) (j : ι) :
    f (conjRadicand Θ t e c j) = conjRadicand (fun j => f (Θ j)) t e c j := by
  rw [conjRadicand_eq, conjRadicand_eq, map_prod]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [map_pow, map_sub, map_add, AlgHom.commutes, AlgHom.commutes]

end Rigidity.RET.Wreath
