import Mathlib
import Mathieu.CardSL

/-!
# `SL(2, 𝔽₂₃)` is generated by `T` and `S`

This file proves that the special linear group `SL(2, ZMod 23)` is generated by the two
matrices

* `Tmat = !![1,1;0,1]`  (the unipotent translation `z ↦ z+1`), and
* `Smat = !![0,-1;1,0]` (the inversion `z ↦ -1/z`),

i.e. `Subgroup.closure {Tmat, Smat} = ⊤`.

This is the classical fact that `S` and `T` generate `SL₂`.  It is proved here **structurally**
by Gaussian elimination / row reduction (elementary transvections generate `SLₙ` over a field),
in the same `native_decide`-free style as `SL211Gen.lean`.  No enumeration is used.

The result feeds `PSL223.lean`, where the Möbius action of `SL(2,𝔽₂₃)` on the projective
line `ℙ¹(𝔽₂₃) ≃ Fin 24` is shown to land inside `M₂₄`.
-/

namespace Mathieu

open Matrix
open scoped MatrixGroups

instance instFact23Prime : Fact (Nat.Prime 23) := ⟨by norm_num⟩

namespace EnumSL223

set_option maxRecDepth 10000
set_option maxHeartbeats 2000000

/-- The translation generator `T = !![1,1;0,1] ∈ SL(2, 𝔽₂₃)`. -/
def Tmat : SL(2, ZMod 23) := ⟨!![1,1;0,1], by decide⟩

/-- The inversion generator `S = !![0,-1;1,0] ∈ SL(2, 𝔽₂₃)`. -/
def Smat : SL(2, ZMod 23) := ⟨!![0,22;1,0], by decide⟩

/-- The upper transvection `!![1,m;0,1] ∈ SL(2, 𝔽₂₃)`. -/
def upper (m : ZMod 23) : SL(2, ZMod 23) := ⟨!![1,m;0,1], by simp [Matrix.det_fin_two_of]⟩

/-- The lower transvection `!![1,0;m,1] ∈ SL(2, 𝔽₂₃)`. -/
def lower (m : ZMod 23) : SL(2, ZMod 23) := ⟨!![1,0;m,1], by simp [Matrix.det_fin_two_of]⟩

/-- `|SL(2, 𝔽₂₃)| = 12144`, obtained (pen-and-paper) from `|GL(2, 𝔽₂₃)| = 267168` via the order
formula `CardSL.card_GL_eq_card_SL_mul` and `|𝔽₂₃ˣ| = 22`, rather than by enumeration. -/
theorem slCard : Fintype.card SL(2, ZMod 23) = 12144 := by
  haveI : Fact (Nat.Prime 23) := ⟨by norm_num⟩
  have hGL : Nat.card (GL (Fin 2) (ZMod 23)) = 267168 := by
    rw [Matrix.card_GL_field]; norm_num [Fin.prod_univ_two, ZMod.card]
  have hmul := CardSL.card_GL_eq_card_SL_mul (𝔽 := ZMod 23) (n := 2)
  rw [hGL, show Fintype.card (ZMod 23) = 23 from by simp [ZMod.card]] at hmul
  rw [← Nat.card_eq_fintype_card]
  omega

/-- Every upper transvection is a power of `Tmat`, hence lies in the closure. -/
theorem upper_mem (m : ZMod 23) : upper m ∈ Subgroup.closure {Tmat, Smat} := by
  have hTmat_pow_eq : ∀ k : ℕ,
      (Tmat ^ k : Matrix.SpecialLinearGroup (Fin 2) (ZMod 23)).val
        = !![1, (k : ZMod 23); 0, 1] := by
    intro k
    induction k with
    | zero => ext i j; fin_cases i <;> fin_cases j <;> simp
    | succ k hk =>
        rw [pow_succ, Matrix.SpecialLinearGroup.coe_mul, hk]
        show _ * (Tmat : Matrix (Fin 2) (Fin 2) (ZMod 23)) = _
        rw [show (Tmat : Matrix (Fin 2) (Fin 2) (ZMod 23)) = !![1,1;0,1] from rfl]
        ext i j; fin_cases i <;> fin_cases j <;>
          simp [Matrix.mul_apply, Fin.sum_univ_two]; ring
  have hpow : Tmat ^ m.val ∈ Subgroup.closure {Tmat, Smat} :=
    Subgroup.pow_mem _ (Subgroup.subset_closure (by left; rfl)) _
  have : upper m = Tmat ^ m.val := by
    apply Subtype.ext
    rw [hTmat_pow_eq m.val]
    simp [upper, ZMod.natCast_val, ZMod.cast_id]
  rw [this]; exact hpow

/-- Every lower transvection lies in the closure: `lower m = Smat * upper (-m) * Smat⁻¹`. -/
theorem lower_mem (m : ZMod 23) : lower m ∈ Subgroup.closure {Tmat, Smat} := by
  have hSmat_mem : Smat ∈ Subgroup.closure {Tmat, Smat} :=
    Subgroup.subset_closure (by right; rfl)
  have hSinv : (Smat⁻¹ : SL(2, ZMod 23)) = ⟨!![0,1;22,0], by decide⟩ :=
    inv_eq_of_mul_eq_one_right (by apply Subtype.ext; rw [Matrix.SpecialLinearGroup.coe_mul]; decide)
  have hconj : lower m = Smat * upper (-m) * Smat⁻¹ := by
    apply Subtype.ext
    rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul, hSinv]
    have hA : (Smat : Matrix (Fin 2) (Fin 2) (ZMod 23)) = !![0,-1;1,0] := by decide
    have hC : ((⟨!![0,1;22,0], by decide⟩ : SL(2, ZMod 23)) : Matrix (Fin 2) (Fin 2) (ZMod 23))
        = !![0,1;-1,0] := by decide
    rw [hA, hC, show (upper (-m) : Matrix (Fin 2) (Fin 2) (ZMod 23)) = !![1,-m;0,1] from rfl,
      show (lower m : Matrix (Fin 2) (Fin 2) (ZMod 23)) = !![1,0;m,1] from rfl]
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]
  rw [hconj]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hSmat_mem (upper_mem _)) (Subgroup.inv_mem _ hSmat_mem)

/-- **`S` and `T` generate `SL(2, 𝔽₂₃)`.**  Proved structurally by row reduction, without any
enumeration / `native_decide`. -/
theorem closure_eq_top : Subgroup.closure {Tmat, Smat} = ⊤ := by
  ext g
  have h_prod : ∀ g : SL(2, ZMod 23), (g.val 1 0 ≠ 0) → g ∈ Subgroup.closure {Tmat, Smat} := by
    intro g hg_nonzero
    obtain ⟨x, hx⟩ : ∃ x : ZMod 23, g.val 0 0 + x * g.val 1 0 = 1 := by
      have h_inv : ∃ x : ZMod 23, x * g.val 1 0 = 1 :=
        ⟨_, inv_mul_cancel₀ hg_nonzero⟩
      exact ⟨h_inv.choose * (1 - g.val 0 0),
        by linear_combination' h_inv.choose_spec * (1 - g.val 0 0)⟩
    obtain ⟨b', hb'⟩ : ∃ b' : ZMod 23, (upper x * g).val = !![1, b'; g.val 1 0, g.val 1 1] := by
      refine ⟨g.val 0 1 + x * g.val 1 1, ?_⟩
      rw [Matrix.SpecialLinearGroup.coe_mul,
        show (upper x : Matrix (Fin 2) (Fin 2) (ZMod 23)) = !![1,x;0,1] from rfl]
      ext i j; fin_cases i <;> fin_cases j <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two];
        linear_combination hx
    have hdet : (1 : ZMod 23) = 1 * g.val 1 1 - b' * g.val 1 0 := by
      have h := congr_arg Matrix.det hb'
      rw [Matrix.SpecialLinearGroup.det_coe, Matrix.det_fin_two_of] at h
      exact h
    have h_lower : (lower (-g.val 1 0) * (upper x * g)).val = !![1, b'; 0, 1] := by
      rw [Matrix.SpecialLinearGroup.coe_mul, hb',
        show (lower (-g.val 1 0) : Matrix (Fin 2) (Fin 2) (ZMod 23))
            = !![1,0;-g.val 1 0,1] from rfl]
      ext i j; fin_cases i <;> fin_cases j <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two];
        first | linear_combination hdet | linear_combination -hdet
    have h_g : g = (upper x)⁻¹ * (lower (-g.val 1 0))⁻¹ * upper b' := by
      have h_g' : lower (-g.val 1 0) * (upper x * g) = upper b' := by
        apply Subtype.ext; rw [h_lower]; rfl
      rw [show upper b' = lower (-g.val 1 0) * (upper x * g) from h_g'.symm]
      group
    rw [h_g]
    exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (Subgroup.inv_mem _ (upper_mem _))
      (Subgroup.inv_mem _ (lower_mem _))) (upper_mem _)
  refine ⟨fun _ => Subgroup.mem_top _, fun _ => ?_⟩
  by_cases h : (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0 = 0
  · have hdet : (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 0 0 * (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 1
        - (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 0 1 * (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0 = 1 := by
      have := g.2; rwa [Matrix.det_fin_two] at this
    have h00 : (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 0 0 ≠ 0 := by
      intro hc; rw [hc, h] at hdet
      simp only [zero_mul, mul_zero, sub_zero] at hdet
      exact absurd hdet (by decide)
    have hentry : ((lower 1 * g : SL(2, ZMod 23)) : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0
        = (g : Matrix (Fin 2) (Fin 2) (ZMod 23)) 0 0 := by
      rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, Fin.sum_univ_two]
      show (lower 1 : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0 * _
          + (lower 1 : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 1 * _ = _
      have e0 : (lower 1 : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0 = 1 := by decide
      have e1 : (lower 1 : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 1 = 1 := by decide
      rw [e0, e1, h]; ring
    have h10 : ((lower 1 * g : SL(2, ZMod 23)) : Matrix (Fin 2) (Fin 2) (ZMod 23)) 1 0 ≠ 0 := by
      rw [hentry]; exact h00
    have hg : g = (lower 1)⁻¹ * (lower 1 * g) := (inv_mul_cancel_left (lower 1) g).symm
    rw [hg]; exact mul_mem (inv_mem (lower_mem 1)) (h_prod _ h10)
  · exact h_prod g h

end EnumSL223

end Mathieu
