import Mathlib
import Mathieu.DefM11
import Mathieu.DefM12
import Mathieu.DefM23
import Mathieu.DefM24
import Mathieu.EnumM12Clean

/-!
# Perfectness of `M₁₁`, `M₁₂`, `M₂₃` and `M₂₄`

(`M₂₂` perfectness is in `PerfectM22.lean`.)

A group `G` is *perfect* when `commutator G = ⊤`, i.e. it equals its own commutator
subgroup.  Perfectness is one of the hypotheses of the Iwasawa criterion for simplicity
(`MulAction.IwasawaStructure.isSimpleGroup`), see `PLAN.md` §3.5.

Here we prove that `M₁₁` and `M₁₂` are perfect.  The strategy is concrete and uniform:
to show `commutator G = ⊤` for a group `G = ⟨s₁, …, sₖ⟩` generated by an explicit set, it
suffices (after `M⋆_top_eq`, which lifts the generating set to `⊤` of the subgroup) to show
each generator `sᵢ` lies in `commutator G`.  By Ore's theorem each element of a finite simple
group is a single commutator, and indeed each Mathieu generator can be written explicitly as
a commutator `⁅x, y⁆` of two words `x, y` in the generators; the identity `sᵢ = ⁅x, y⁆` is a
closed statement about permutations checked by `decide`, and membership then follows
from `Subgroup.commutator_mem_commutator`.

The commutator words were found by a breadth-first search over short words in the generators.
The search was run *externally* (a small permutation BFS); only the resulting closed identity
`sᵢ = ⁅x, y⁆` (or a product of two such commutators, for `M₂₃` and two of the `M₂₄`
generators) is verified here by `decide`.  Each commutator word is first reduced to a concrete
permutation (each reduction is a shallow `decide`), which keeps the final `decide` cheap even for
long words.  For `M₂₃`/`M₂₄` a *single* short commutator was not found for every generator, so a
product of two commutators is used; membership in `commutator` then follows from `mul_mem`.
-/

namespace Mathieu

set_option maxRecDepth 20000

open Equiv

/-! ## A reusable step for the perfectness chain

The perfectness of the larger groups is intended to be obtained along the subgroup chain
`M₂₁ < M₂₂ < M₂₃ < M₂₄` (and `M₁₁ < M₁₂`): each group is the *normal closure* of the previous
one (a non-normal maximal subgroup), and the normal closure of a perfect subgroup is perfect.
The following lemma is that reusable step.  -/

/-- **The normal closure of a perfect subgroup is perfect.**  If `H ≤ G` satisfies
`⁅H, H⁆ = H` (i.e. `H` is perfect as a subgroup) and the normal closure of `H` is all of `G`,
then `G` is perfect (`commutator G = ⊤`).

Intended use: given `Mₙ₋₁` perfect and realised as a non-normal *maximal* subgroup of `Mₙ`
(so its normal closure is `⊤`), this yields `Mₙ` perfect. -/
theorem perfect_of_perfect_normalClosure_eq_top {G : Type*} [Group G] (H : Subgroup G)
    (hHperf : ⁅H, H⁆ = H) (hcl : Subgroup.normalClosure (H : Set G) = ⊤) :
    commutator G = ⊤ := by
  have hHle : H ≤ commutator G := by
    calc H = ⁅H, H⁆ := hHperf.symm
    _ ≤ ⁅(⊤ : Subgroup G), ⊤⁆ := Subgroup.commutator_mono le_top le_top
    _ = commutator G := rfl
  have hle : Subgroup.normalClosure (H : Set G) ≤ commutator G :=
    Subgroup.normalClosure_le_normal hHle
  rw [hcl] at hle
  exact top_le_iff.mp hle

/-! ## `M₁₁` -/

/-- The top subgroup of `↥M₁₁` is generated by the (lifted) two standard generators. -/
theorem M11_top_eq : (⊤ : Subgroup (↥M11)) =
    Subgroup.closure {(⟨m11a, m11a_mem⟩ : ↥M11), ⟨m11b, m11b_mem⟩} := by
  have hinj : Function.Injective (M11.subtype) := Subgroup.subtype_injective M11
  apply Subgroup.map_injective hinj
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [Set.image_insert_eq, Set.image_singleton]
  rfl

set_option maxHeartbeats 1000000 in
/-- **`M₁₁` is perfect**: it equals its own commutator subgroup. -/
theorem M11_perfect : commutator (↥M11) = ⊤ := by
  rw [eq_top_iff, M11_top_eq]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  set ga : ↥M11 := ⟨m11a, m11a_mem⟩ with hga
  set gb : ↥M11 := ⟨m11b, m11b_mem⟩ with hgb
  have cga : ((ga : ↥M11) : Perm (Fin 11)) = m11a := by rw [hga]
  have cgb : ((gb : ↥M11) : Perm (Fin 11)) = m11b := by rw [hgb]
  rcases hg with rfl | rfl
  · have h : ga = ⁅gb⁻¹*ga⁻¹*gb⁻¹*ga*gb⁻¹*ga, gb⁻¹*gb⁻¹*ga⁻¹*ga⁻¹*ga⁻¹*ga⁻¹⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  · have h : gb = ⁅ga*ga*gb*ga, ga⁻¹*ga⁻¹*gb⁻¹*ga⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-! ## `M₁₂` -/

/-- The top subgroup of `↥M₁₂` is generated by the (lifted) three standard generators. -/
theorem M12_top_eq : (⊤ : Subgroup (↥M12)) =
    Subgroup.closure
      {(⟨m12a, m12a_mem⟩ : ↥M12), ⟨m12b, EnumM12Clean.m12b_mem⟩, ⟨m12c, m12c_mem⟩} := by
  have hinj : Function.Injective (M12.subtype) := Subgroup.subtype_injective M12
  apply Subgroup.map_injective hinj
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [Set.image_insert_eq, Set.image_insert_eq, Set.image_singleton]
  rfl

set_option maxHeartbeats 2000000 in
/-- **`M₁₂` is perfect**: it equals its own commutator subgroup. -/
theorem M12_perfect : commutator (↥M12) = ⊤ := by
  rw [eq_top_iff, M12_top_eq]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  set ga : ↥M12 := ⟨m12a, m12a_mem⟩ with hga
  set gb : ↥M12 := ⟨m12b, EnumM12Clean.m12b_mem⟩ with hgb
  set gc : ↥M12 := ⟨m12c, m12c_mem⟩ with hgc
  have cga : ((ga : ↥M12) : Perm (Fin 12)) = m12a := by rw [hga]
  have cgb : ((gb : ↥M12) : Perm (Fin 12)) = m12b := by rw [hgb]
  have cgc : ((gc : ↥M12) : Perm (Fin 12)) = m12c := by rw [hgc]
  rcases hg with rfl | rfl | rfl
  · have h : ga = ⁅gb*ga⁻¹*ga⁻¹*ga⁻¹*gc, gb⁻¹*ga*ga*gb*gc⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  · have h : gb = ⁅gc*ga⁻¹*gb⁻¹*ga*gc, ga⁻¹*ga⁻¹*gb⁻¹*ga⁻¹*gc⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  · have h : gc = ⁅ga*gc*gb*ga*gc, gb⁻¹*gb⁻¹*ga⁻¹*gc*ga⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-! ## `M₂₃`

Unlike `M₁₁`/`M₁₂`, each generator of `M₂₃` is exhibited as a *product of two* commutators of
words in the generators (a single commutator with short words was not found by the search; by
Ore's theorem a single one exists, but its words are longer).  Each commutator is reduced to a
concrete permutation (verified by `decide`), and membership in `commutator` follows since
`commutator` is a subgroup (closed under multiplication). -/

/-- The top subgroup of `↥M₂₃` is generated by the (lifted) two standard generators. -/
theorem M23_top_eq : (⊤ : Subgroup (↥M23)) =
    Subgroup.closure {(⟨m23a, m23a_mem⟩ : ↥M23), ⟨m23b, m23b_mem⟩} := by
  have hinj : Function.Injective (M23.subtype) := Subgroup.subtype_injective M23
  apply Subgroup.map_injective hinj
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [Set.image_insert_eq, Set.image_singleton]
  rfl

set_option maxHeartbeats 2000000 in
/-- **`M₂₃` is perfect**: it equals its own commutator subgroup. -/
theorem M23_perfect : commutator (↥M23) = ⊤ := by
  rw [eq_top_iff, M23_top_eq]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  set ga : ↥M23 := ⟨m23a, m23a_mem⟩ with hga
  set gb : ↥M23 := ⟨m23b, m23b_mem⟩ with hgb
  have cga : ((ga : ↥M23) : Perm (Fin 23)) = m23a := by rw [hga]
  have cgb : ((gb : ↥M23) : Perm (Fin 23)) = m23b := by rw [hgb]
  rcases hg with rfl | rfl
  · have e1 : ((⁅ga, ga*gb⁻¹*ga⁻¹*gb⁆ : ↥M23) : Perm (Fin 23)) =
        c[0, 20, 19, 10, 16] * c[1, 13, 15, 17, 8, 5, 18, 7, 14, 9, 12, 11, 22, 6, 3] * c[2, 4, 21] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    have e2 : ((⁅gb⁻¹*ga⁻¹*ga⁻¹*gb⁻¹*gb⁻¹*ga⁻¹, ga⁻¹*ga⁻¹*gb*ga⁻¹*gb⁆ : ↥M23) : Perm (Fin 23)) =
        c[0, 3, 2, 6, 18, 20, 4, 8, 14, 13, 7, 17, 5, 22, 16, 15, 10, 12, 1, 21, 11, 9, 19] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    have h : ga = ⁅ga, ga*gb⁻¹*ga⁻¹*gb⁆ * ⁅gb⁻¹*ga⁻¹*ga⁻¹*gb⁻¹*gb⁻¹*ga⁻¹, ga⁻¹*ga⁻¹*gb*ga⁻¹*gb⁆ := by
      apply Subtype.ext
      rw [Subgroup.coe_mul, e1, e2, cga]
      decide
    rw [h]
    exact mul_mem
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
  · have e1 : ((⁅ga, gb⁻¹*ga⁻¹*gb⁆ : ↥M23) : Perm (Fin 23)) =
        c[0, 12, 14, 16, 7, 4, 17, 6, 13, 8, 11, 10, 21, 5, 2] * c[1, 3, 20] * c[9, 15, 22, 19, 18] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    have e2 : ((⁅gb*ga⁻¹*gb⁻¹*gb⁻¹*ga⁻¹*gb⁻¹, ga⁻¹*gb*ga⁻¹*gb⁻¹*gb⁻¹*ga⁆ : ↥M23) : Perm (Fin 23)) =
        c[0, 2, 14, 22, 16, 18, 7, 4, 1, 20, 9, 17, 11, 15, 12, 6, 13, 19, 10, 8, 5, 21, 3] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb]
      decide
    have h : gb = ⁅ga, gb⁻¹*ga⁻¹*gb⁆ * ⁅gb*ga⁻¹*gb⁻¹*gb⁻¹*ga⁻¹*gb⁻¹, ga⁻¹*gb*ga⁻¹*gb⁻¹*gb⁻¹*ga⁆ := by
      apply Subtype.ext
      rw [Subgroup.coe_mul, e1, e2, cgb]
      decide
    rw [h]
    exact mul_mem
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))

/-! ## `M₂₄` -/

/-- `m24b` is a member of `M₂₄`. -/
theorem m24b_mem' : m24b ∈ M24 := Subgroup.subset_closure (by right; left; rfl)

/-- The top subgroup of `↥M₂₄` is generated by the (lifted) three standard generators. -/
theorem M24_top_eq : (⊤ : Subgroup (↥M24)) =
    Subgroup.closure
      {(⟨m24a, m24a_mem⟩ : ↥M24), ⟨m24b, m24b_mem'⟩, ⟨m24c, m24c_mem⟩} := by
  have hinj : Function.Injective (M24.subtype) := Subgroup.subtype_injective M24
  apply Subgroup.map_injective hinj
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [Set.image_insert_eq, Set.image_insert_eq, Set.image_singleton]
  rfl

set_option maxHeartbeats 4000000 in
/-- **`M₂₄` is perfect**: it equals its own commutator subgroup. -/
theorem M24_perfect : commutator (↥M24) = ⊤ := by
  rw [eq_top_iff, M24_top_eq]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  set ga : ↥M24 := ⟨m24a, m24a_mem⟩ with hga
  set gb : ↥M24 := ⟨m24b, m24b_mem'⟩ with hgb
  set gc : ↥M24 := ⟨m24c, m24c_mem⟩ with hgc
  have cga : ((ga : ↥M24) : Perm (Fin 24)) = m24a := by rw [hga]
  have cgb : ((gb : ↥M24) : Perm (Fin 24)) = m24b := by rw [hgb]
  have cgc : ((gc : ↥M24) : Perm (Fin 24)) = m24c := by rw [hgc]
  rcases hg with rfl | rfl | rfl
  · have h : ga = ⁅ga⁻¹, gc*gb⁻¹*gc*gb⁆ := by
      apply Subtype.ext
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    rw [h]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  · have e1 : ((⁅gb, gb*gb*ga*gc⁆ : ↥M24) : Perm (Fin 24)) =
        c[2, 17, 8, 3, 21, 6, 12] * c[4, 11, 5, 20, 13, 22, 7] * c[9, 18, 14, 16, 10, 15, 19] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    have e2 : ((⁅ga⁻¹*gc*gb⁻¹*gc, ga*gb*gc*ga⁻¹⁆ : ↥M24) : Perm (Fin 24)) =
        c[2, 14, 15, 18, 7] * c[3, 6, 17, 16, 19] * c[4, 8, 12, 20, 10] * c[5, 11, 13, 9, 21] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    have h : gb = ⁅gb, gb*gb*ga*gc⁆ * ⁅ga⁻¹*gc*gb⁻¹*gc, ga*gb*gc*ga⁻¹⁆ := by
      apply Subtype.ext
      rw [Subgroup.coe_mul, e1, e2, cgb]
      decide
    rw [h]
    exact mul_mem
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
  · have e1 : ((⁅ga, ga⁻¹*ga⁻¹*gc⁆ : ↥M24) : Perm (Fin 24)) =
        c[0, 15, 14, 4, 13, 10, 7, 16, 6, 5, 20, 23] * c[1, 17, 8, 2, 9, 21, 22, 11, 18, 12, 3, 19] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgc]
      decide
    have e2 : ((⁅ga*ga*ga, gc*gb⁻¹*gc*gb⁆ : ↥M24) : Perm (Fin 24)) =
        c[0, 20, 17, 14, 11, 8, 5, 2, 22, 19, 16, 13, 10, 7, 4, 1, 21, 18, 15, 12, 9, 6, 3] := by
      simp only [commutatorElement_def, Subgroup.coe_mul, InvMemClass.coe_inv, cga, cgb, cgc]
      decide
    have h : gc = ⁅ga, ga⁻¹*ga⁻¹*gc⁆ * ⁅ga*ga*ga, gc*gb⁻¹*gc*gb⁆ := by
      apply Subtype.ext
      rw [Subgroup.coe_mul, e1, e2, cgc]
      decide
    rw [h]
    exact mul_mem
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))

end Mathieu
