/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Hilbert.Analytic.Luroth

/-!
# Ritt-type polynomial decomposition and primitivity of `k(f)/k(X)`

This file provides the *field-theoretic core* of the primitivity half of the Morse
monodromy input.  Given a polynomial `f ∈ k[X]` of degree `≥ 2` that is **indecomposable**
(no factorisation `f = h ∘ g` with `deg h, deg g ≥ 2`), we prove that the subfield
`k(f) ⊆ k(X) = RatFunc k` is a **coatom** in the lattice of intermediate fields, i.e. there
is no intermediate field strictly between `k(f)` and `k(X)`.

The Ritt bridge is proved elementarily (`RatFunc.exists_poly_gen`) via a homogenisation /
coprimality argument: after a fractional-linear normalisation `w = p/q` with `deg p > deg q`,
the presence of a polynomial in `k(w)` forces `q` to be constant.  Everything is assembled from
Lüroth; no function-field pole/valuation theory is needed. -/

open Polynomial IntermediateField

namespace RatFunc

variable {k : Type*} [Field k]

/-
The image of a polynomial `f` in `RatFunc k` has height `f.natDegree`.
-/
theorem height_algebraMap (f : k[X]) :
    (algebraMap k[X] (RatFunc k) f).height = f.natDegree := by
  by_cases h : f = 0 <;> simp_all [RatFunc.height]

/-
The image of a non-constant polynomial `f` in `RatFunc k` is not in the base field `k`.
-/
theorem algebraMap_not_mem_bot (f : k[X]) (hf : 1 ≤ f.natDegree) :
    (algebraMap k[X] (RatFunc k) f) ∉ (⊥ : IntermediateField k (RatFunc k)) := by
  have := RatFunc.mem_bot_iff (algebraMap k[X] (RatFunc k) f)
  convert this.mpr
  obtain ⟨c, hc⟩ := ‹_›
  have := congr_arg RatFunc.num hc
  norm_num at this
  subst this
  simp_all only [natDegree_C, nonpos_iff_eq_zero, one_ne_zero]

/-- A polynomial `f` lying in the subfield `k(g)` generated by a nonconstant polynomial `g`
is a polynomial composition `f = h ∘ g`.

*Proof.* `X` is integral over the subring `k[g] = Algebra.adjoin k {g}` (it is a root of the
monic-in-`Y` polynomial `g(Y) - g` after scaling by the leading coefficient), so `k[X]` — and
in particular `f` — is integral over `k[g]`.  Since `k[g] ≅ k[Y]` is integrally closed with
fraction field `k(g)`, and `f ∈ k(g)` is integral over `k[g]`, we get `f ∈ k[g]`, i.e.
`f = h ∘ g` for some `h ∈ k[Y]`. -/
theorem poly_mem_adjoin_poly (f g : k[X]) (hg : 1 ≤ g.natDegree)
    (hf : algebraMap k[X] (RatFunc k) f ∈ k⟮algebraMap k[X] (RatFunc k) g⟯) :
    ∃ h : k[X], f = h.comp g := by
  classical
  have haeval : ∀ p : k[X],
      aeval (algebraMap k[X] (RatFunc k) g) p = algebraMap k[X] (RatFunc k) (p.comp g) := by
    intro p
    rw [aeval_algebraMap_apply]
    congr 1
  have hgc : ∀ p : k[X], p ≠ 0 → p.comp g ≠ 0 := by
    intro p hp hcontra
    rw [Polynomial.comp_eq_zero_iff] at hcontra
    rcases hcontra with h | ⟨_, hgeq⟩
    · exact hp h
    · rw [hgeq] at hg
      simp at hg
  have hinj := IsFractionRing.injective k[X] (RatFunc k)
  obtain ⟨r, s, hs0, hrs⟩ :
      ∃ r s : k[X], s ≠ 0 ∧
        (algebraMap k[X] (RatFunc k)) f
          = aeval (algebraMap k[X] (RatFunc k) g) r / aeval (algebraMap k[X] (RatFunc k) g) s := by
    rw [IntermediateField.mem_adjoin_simple_iff] at hf
    by_cases h : (algebraMap k[X] (RatFunc k)) f = 0
    · exact ⟨0, 1, one_ne_zero, by simp [h]⟩
    · obtain ⟨r, s, hrs⟩ := hf
      refine ⟨r, s, ?_, hrs⟩
      rintro rfl
      rw [map_zero, div_zero] at hrs
      exact h hrs
  obtain ⟨r, s, hs0, hcop, hrs⟩ :
      ∃ r s : k[X], s ≠ 0 ∧ IsCoprime r s ∧
        (algebraMap k[X] (RatFunc k)) f
          = aeval (algebraMap k[X] (RatFunc k) g) r / aeval (algebraMap k[X] (RatFunc k) g) s := by
    set d := EuclideanDomain.gcd r s with hd
    have hd0 : d ≠ 0 := by
      rw [hd, Ne, EuclideanDomain.gcd_eq_zero_iff]
      rintro ⟨_, h⟩
      exact hs0 h
    obtain ⟨r', hr'⟩ := EuclideanDomain.gcd_dvd_left r s
    obtain ⟨s', hs'⟩ := EuclideanDomain.gcd_dvd_right r s
    rw [← hd] at hr' hs'
    have hcop : IsCoprime r' s' := by
      apply isCoprime_of_dvd
      · rintro ⟨rfl, rfl⟩
        apply hs0
        rw [hs', mul_zero]
      · intro z hz hz0 hzr hzs
        apply hz
        have hzd1 : z * d ∣ r := by
          rw [hr', mul_comm z d]
          exact mul_dvd_mul_left d hzr
        have hzd2 : z * d ∣ s := by
          rw [hs', mul_comm z d]
          exact mul_dvd_mul_left d hzs
        obtain ⟨q, hq⟩ := EuclideanDomain.dvd_gcd hzd1 hzd2
        have h1 : d * (z * q) = d * 1 := by linear_combination -hq
        exact IsUnit.of_mul_eq_one q (mul_left_cancel₀ hd0 h1)
    refine ⟨r', s', ?_, hcop, ?_⟩
    · rintro rfl
      rw [mul_zero] at hs'
      exact hs0 hs'
    · have hdne : algebraMap k[X] (RatFunc k) (d.comp g) ≠ 0 := by
        rw [Ne, map_eq_zero_iff _ hinj]
        exact hgc d hd0
      rw [hrs, hr', hs', haeval, haeval, haeval, haeval, mul_comp, mul_comp, map_mul, map_mul,
        mul_div_mul_left _ _ hdne]
  have hden : algebraMap k[X] (RatFunc k) (s.comp g) ≠ 0 := by
    rw [Ne, map_eq_zero_iff _ hinj]
    exact hgc s hs0
  have h_eq : f * s.comp g = r.comp g := by
    rw [haeval, haeval, eq_div_iff hden] at hrs
    apply hinj
    rw [map_mul]
    exact hrs
  have h_unit : IsUnit (s.comp g) := by
    obtain ⟨a, b, h⟩ := hcop
    have h_coprime : IsCoprime (r.comp g) (s.comp g) := by
      refine ⟨a.comp g, b.comp g, ?_⟩
      have := congr_arg (Polynomial.comp · g) h
      simpa [add_comp, mul_comp, one_comp] using this
    exact h_coprime.isUnit_of_dvd' ⟨f, by rw [← h_eq, mul_comm]⟩ dvd_rfl
  have h_deg_zero : s.natDegree = 0 := by
    have := Polynomial.natDegree_eq_zero_of_isUnit h_unit
    rw [Polynomial.natDegree_comp] at this
    rcases Nat.mul_eq_zero.mp this with h | h
    · exact h
    · omega
  have hsc : s = Polynomial.C (s.coeff 0) := Polynomial.eq_C_of_natDegree_eq_zero h_deg_zero
  have hc0 : s.coeff 0 ≠ 0 := by
    intro h
    apply hs0
    rw [hsc, h, map_zero]
  refine ⟨Polynomial.C (s.coeff 0)⁻¹ * r, ?_⟩
  have hkey : f * Polynomial.C (s.coeff 0) = r.comp g := by
    rw [hsc] at h_eq
    simpa [Polynomial.C_comp] using h_eq
  rw [mul_comp, Polynomial.C_comp, ← hkey, ← mul_assoc, mul_comm (Polynomial.C (s.coeff 0)⁻¹) f,
    mul_assoc, ← Polynomial.C_mul, inv_mul_cancel₀ hc0, Polynomial.C_1, mul_one]

/-- `RatFunc.X` is integral over the polynomial ring `k[X]` (it is the image of `X`). -/
theorem ratfuncX_isIntegral : IsIntegral k[X] (RatFunc.X : RatFunc k) := by
  have : (RatFunc.X : RatFunc k) = algebraMap k[X] (RatFunc k) Polynomial.X := by
    simp [RatFunc.algebraMap_X]
  rw [this]
  exact isIntegral_algebraMap

/-- Two intermediate fields of `k(X)/k` with the same (finite) degree of `k(X)` over them and
one contained in the other are equal. -/
theorem finrank_eq_of_le {E1 E2 : IntermediateField k (RatFunc k)}
    (hle : E1 ≤ E2) [FiniteDimensional (E1) (RatFunc k)]
    (h : Module.finrank (E1) (RatFunc k) = Module.finrank (E2) (RatFunc k)) : E1 = E2 :=
  eq_of_le_of_finrank_eq' hle h

/-!
### Elementary proof of Ritt normalisation

We prove `exists_poly_gen` — a proper intermediate field `E ⊊ k(X)` containing a nonconstant
polynomial `f` is `k(g)` for a *polynomial* `g` — by a completely elementary argument, avoiding
norms and valuations.  By Lüroth `E = k(w)`; after a fractional-linear normalisation we may
assume `w = p/q` (coprime) with `deg p > deg q`, and then the presence of the polynomial `f`
forces `q` to be constant, so `w` itself is a polynomial.

The heart is the *homogenisation* `homog A p q = ∑ᵢ A.coeffᵢ · pⁱ · q^(deg A − i)`, which equals
`q^(deg A) · A(p/q)`; comparing degrees at the "top" term and using coprimality of `p, q` gives
the contradiction unless `q` is constant.
-/

/-- Homogenisation of `A` with respect to `p/q`: the polynomial `∑ᵢ Aᵢ · pⁱ · q^(deg A − i)`.
It satisfies `algebraMap (homog A p q) = q ^ (deg A) · A(p/q)` (see `algebraMap_homog`). -/
noncomputable def homog (A p q : k[X]) : k[X] :=
  ∑ i ∈ Finset.range (A.natDegree + 1),
    Polynomial.C (A.coeff i) * p ^ i * q ^ (A.natDegree - i)

/-
The defining property of `homog`: `q ^ (deg A) · A(p/q) = homog A p q` inside `k(X)`.
-/
theorem algebraMap_homog (A p q : k[X]) (hq : q ≠ 0) :
    algebraMap k[X] (RatFunc k) (homog A p q)
      = (algebraMap k[X] (RatFunc k) q) ^ A.natDegree
        * aeval (algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q) A := by
  simp [homog]
  rw [Polynomial.aeval_eq_sum_range]
  simp [div_pow, mul_assoc, mul_comm, Finset.mul_sum, Algebra.smul_def]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  field_simp
  rw [eq_div_iff (pow_ne_zero _
    (IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors <| by simp_all))]
  rw [show (algebraMap k[X] (RatFunc k) q) ^ A.natDegree
      = (algebraMap k[X] (RatFunc k) q) ^ (A.natDegree - i)
        * (algebraMap k[X] (RatFunc k) q) ^ i by
    rw [← pow_add, Nat.sub_add_cancel (Finset.mem_range_succ_iff.mp hi)]]
  ring

/-
Modulo `q`, `homog A p q` is `A.leadingCoeff · p ^ (deg A)`; since `p, q` are coprime and
`A ≠ 0`, this makes `homog A p q` coprime to `q`.
-/
theorem isCoprime_homog (A p q : k[X]) (hcop : IsCoprime p q) (hA : A ≠ 0) :
    IsCoprime (homog A p q) q := by
  simp_all [IsCoprime]
  -- `homog A p q = C A.leadingCoeff * p ^ (deg A) + q * t` for some polynomial `t`.
  obtain ⟨t, ht⟩ : ∃ t : k[X], homog A p q = Polynomial.C (A.leadingCoeff) * p ^ (A.natDegree) + q * t := by
    unfold homog
    simp [Finset.sum_range_succ]
    refine ⟨∑ i ∈ Finset.range A.natDegree,
      Polynomial.C (A.coeff i) * p ^ i * q ^ (A.natDegree - i - 1), ?_⟩
    rw [add_comm, Finset.mul_sum]
    exact congr_arg _
      (Finset.sum_congr rfl fun i hi ↦ by
        rw [mul_left_comm, ← pow_succ',
          tsub_add_cancel_of_le (Nat.succ_le_of_lt (Nat.sub_pos_of_lt (Finset.mem_range.mp hi)))])
  -- Since `p` and `q` are coprime, `p ^ n` and `q` are also coprime.
  have h_coprime_pow : IsCoprime (p ^ A.natDegree) q := IsCoprime.pow_left hcop
  -- Since `A.leadingCoeff ≠ 0`, `C A.leadingCoeff` is a unit.
  have h_unit : IsUnit (Polynomial.C (A.leadingCoeff)) :=
    Polynomial.isUnit_C.mpr (isUnit_iff_ne_zero.mpr (Polynomial.leadingCoeff_ne_zero.mpr hA))
  obtain ⟨u, hu⟩ := h_unit.exists_left_inv
  obtain ⟨a, b, h⟩ := h_coprime_pow
  refine ⟨u * a, b - u * a * t, ?_⟩
  linear_combination' h + hu * a * p ^ A.natDegree + ht * u * a

/-
When `deg q < deg p`, the top term `A.leadingCoeff · p ^ (deg A)` strictly dominates, so
`homog A p q` has degree exactly `deg A · deg p`.
-/
theorem natDegree_homog (A p q : k[X]) (hA : A ≠ 0) (hp : p ≠ 0)
    (hdeg : q.natDegree < p.natDegree) :
    (homog A p q).natDegree = A.natDegree * p.natDegree := by
  apply Polynomial.natDegree_eq_of_le_of_coeff_ne_zero
  · refine le_trans (Polynomial.natDegree_sum_le _ _) (Finset.sup_le ?_)
    intro i hi
    by_cases hi' : A.coeff i = 0 <;> by_cases hi'' : q = 0 <;> simp_all [Polynomial.natDegree_mul']
    · by_cases hi''' : A.natDegree - i = 0 <;> simp_all [Polynomial.natDegree_mul']
    · nlinarith [Nat.sub_add_cancel hi]
  ·
    -- The coefficient of the highest degree term in the homogenized polynomial is the product of the leading coefficients of A and p.
    have h_coeff : (homog A p q).coeff (A.natDegree * p.natDegree)
        = A.leadingCoeff * p.leadingCoeff ^ A.natDegree := by
      have h_coeff_zero : ∀ i ∈ Finset.range (A.natDegree + 1), i ≠ A.natDegree →
          (Polynomial.C (A.coeff i) * p ^ i * q ^ (A.natDegree - i)).coeff
            (A.natDegree * p.natDegree) = 0 := by
        intro i hi hne
        have h_deg : (Polynomial.C (A.coeff i) * p ^ i * q ^ (A.natDegree - i)).natDegree
            < A.natDegree * p.natDegree := by
          apply lt_of_le_of_lt (Polynomial.natDegree_mul_le ..)
          apply lt_of_le_of_lt
            (add_le_add (Polynomial.natDegree_C_mul_le _ _) (Polynomial.natDegree_pow_le))
          rw [Polynomial.natDegree_pow]
          have := Finset.mem_range.mp hi
          have := Nat.sub_add_cancel (show i ≤ A.natDegree from Finset.mem_range_succ_iff.mp hi)
          have := Nat.lt_of_le_of_ne (Finset.mem_range_succ_iff.mp hi) hne
          nlinarith
        exact Polynomial.coeff_eq_zero_of_natDegree_lt h_deg
      rw [homog, Polynomial.finset_sum_coeff, Finset.sum_eq_single (A.natDegree)] <;>
        simp_all [Polynomial.coeff_natDegree]
    simp_all

theorem homog_ne_zero (A p q : k[X]) (hA : A ≠ 0) (hp : p ≠ 0)
    (hdeg : q.natDegree < p.natDegree) : homog A p q ≠ 0 := by
  intro h
  convert natDegree_homog A p q hA hp hdeg using 1
  simp_all
  constructor <;> intro h' <;> simp_all [Polynomial.natDegree_eq_zero_iff_degree_le_zero]
  rw [Polynomial.eq_C_of_degree_le_zero h'] at hA h
  simp_all [homog]

/-
**Key normalised step.**  If `w = p/q` is a coprime fraction with `deg p > deg q` and the
field `k(w)` contains a nonconstant polynomial `f`, then `q` is constant (so `w` is itself a
polynomial).
-/
theorem denom_natDegree_eq_zero_of_poly_mem
    (p q : k[X]) (hq : q ≠ 0) (hcop : IsCoprime p q)
    (hdeg : q.natDegree < p.natDegree)
    (f : k[X]) (hf : 1 ≤ f.natDegree)
    (hfw : algebraMap k[X] (RatFunc k) f
        ∈ k⟮algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q⟯) :
    q.natDegree = 0 := by
  obtain ⟨A, B, hAB⟩ :
      ∃ A B : k[X], B ≠ 0 ∧ (algebraMap k[X] (RatFunc k)) f
        = aeval (algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q) A
          / aeval (algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q) B := by
    have := @IntermediateField.mem_adjoin_simple_iff
    obtain ⟨A, B, h⟩ := this k (algebraMap k[X] (RatFunc k) f) |>.1 hfw
    grind only [isCoprime_iff_aeval_ne_zero, = map_zero]
  obtain ⟨A, B, hA, hB, h_eq⟩ :
      ∃ A B : k[X], A ≠ 0 ∧ B ≠ 0 ∧ (algebraMap k[X] (RatFunc k)) f
        * aeval (algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q) B
          = aeval (algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q) A := by
    by_cases hA : A = 0
    · have h_contra : f = 0 := by
        grind only [= map_zero, algebraMap_ne_zero]
      simp_all
    · grind +splitImp
  -- Show the key identity `f * q ^ A.natDegree * homog B p q = homog A p q * q ^ B.natDegree`.
  have h_poly_eq : f * q ^ A.natDegree * homog B p q = homog A p q * q ^ B.natDegree := by
    apply_fun (algebraMap k[X] (RatFunc k)) using IsFractionRing.injective _ _
    simp_all [algebraMap_homog]
    grind
  -- From this equation together with Q < P and 1 ≤ f.natDegree, deduce β < α.
  have h_beta_lt_alpha : B.natDegree < A.natDegree := by
    replace h_poly_eq := congr_arg Polynomial.natDegree h_poly_eq
    rw [Polynomial.natDegree_mul', Polynomial.natDegree_mul'] at h_poly_eq <;>
      simp_all [Polynomial.natDegree_pow]
    · rw [Polynomial.natDegree_mul'] at h_poly_eq <;> simp_all [Polynomial.natDegree_pow]
      · rw [natDegree_homog, natDegree_homog] at h_poly_eq <;> try assumption
        · nlinarith
        · simp_all only [ne_eq]; obtain ⟨left, right⟩ := hAB; apply Aesop.BuiltinRules.not_intro; intro a; subst a; simp_all only [natDegree_zero, not_lt_zero]
        · simp_all only [ne_eq]; obtain ⟨left, right⟩ := hAB; apply Aesop.BuiltinRules.not_intro; intro a; subst a; simp_all only [natDegree_zero, not_lt_zero]
      · refine RatFunc.homog_ne_zero A p q hA ?_ hdeg
        simp_all only [ne_eq]
        obtain ⟨left, right⟩ := hAB
        apply Aesop.BuiltinRules.not_intro
        intro a
        subst a
        simp_all only [natDegree_zero, not_lt_zero]
    · obtain ⟨left, right⟩ := hAB; apply Aesop.BuiltinRules.not_intro; intro a; subst a; simp_all only [natDegree_zero, nonpos_iff_eq_zero, one_ne_zero]
    · refine ⟨?_, RatFunc.homog_ne_zero _ _ _ hB ?_ hdeg⟩
      · obtain ⟨left, right⟩ := hAB; apply Aesop.BuiltinRules.not_intro; intro a; subst a; simp_all only [natDegree_zero, nonpos_iff_eq_zero, one_ne_zero]
      · simp_all only [ne_eq]; obtain ⟨left, right⟩ := hAB; apply Aesop.BuiltinRules.not_intro; intro a; subst a; simp_all only [natDegree_zero, not_lt_zero]
  -- From `q ^ A.natDegree ∣ homog A p q * q ^ B.natDegree`, we get `q ^ A.natDegree ∣ q ^ B.natDegree`.
  have h_div : q ^ A.natDegree ∣ q ^ B.natDegree := by
    refine IsCoprime.dvd_of_dvd_mul_left ?_
      (h_poly_eq ▸ dvd_mul_of_dvd_left (dvd_mul_left _ _) _)
    exact IsCoprime.pow_left (IsCoprime.symm (isCoprime_homog A p q hcop hA))
  contrapose! h_div
  intro h
  refine absurd (Polynomial.natDegree_le_of_dvd h (pow_ne_zero _ hq)) ?_
  rw [Polynomial.natDegree_pow, Polynomial.natDegree_pow]
  nlinarith [Nat.pos_of_ne_zero h_div]

/-
**Fractional-linear normalisation.**  Any `w ∉ k` can be replaced by a coprime fraction
`p/q` generating the same subfield `k(w)` and with `deg p > deg q`.
-/
theorem exists_coprime_repr_deg (w : RatFunc k)
    (hw : w ∉ (⊥ : IntermediateField k (RatFunc k))) :
    ∃ p q : k[X], q ≠ 0 ∧ IsCoprime p q ∧ q.natDegree < p.natDegree ∧
      k⟮algebraMap k[X] (RatFunc k) p / algebraMap k[X] (RatFunc k) q⟯ = k⟮w⟯ := by
  by_cases h_deg : w.num.natDegree = w.denom.natDegree
  · -- Let `c = w.num.leadingCoeff / w.denom.leadingCoeff`.
    obtain ⟨c, hc⟩ : ∃ c : k, w.num.leadingCoeff = c * w.denom.leadingCoeff :=
      ⟨w.num.leadingCoeff / w.denom.leadingCoeff,
        by rw [div_mul_cancel₀ _ (by simpa using w.denom_ne_zero)]⟩
    refine ⟨w.denom, w.num - Polynomial.C c * w.denom, ?_, ?_, ?_, ?_⟩
    · contrapose! hw
      rw [sub_eq_zero] at hw
      rw [← RatFunc.num_div_denom w, hw]
      rw [map_mul, mul_div_cancel_right₀]
      · exact ⟨c, rfl⟩
      · exact RatFunc.algebraMap_ne_zero (RatFunc.denom_ne_zero _)
    · have := RatFunc.isCoprime_num_denom w
      convert this.symm.add_mul_right_right (-Polynomial.C c) using 1
      ring
    · rw [Polynomial.natDegree_lt_iff_degree_lt, Polynomial.degree_lt_iff_coeff_zero]
      · intro m hm
        rcases eq_or_lt_of_le hm with rfl | hm' <;> simp_all [Polynomial.coeff_eq_zero_of_natDegree_lt]
        rw [← hc, ← h_deg, Polynomial.coeff_natDegree, sub_self]
      · intro h
        rw [sub_eq_zero] at h
        have := RatFunc.num_div_denom w
        rw [h, map_mul, mul_div_cancel_right₀] at this
        · exact hw (this ▸ IntermediateField.mem_bot.mpr ⟨c, by simp⟩)
        · exact RatFunc.algebraMap_ne_zero (RatFunc.denom_ne_zero _)
    · apply le_antisymm
      · have h_inv : (algebraMap k[X] (RatFunc k) w.denom)
            / ((algebraMap k[X] (RatFunc k) w.num) - (algebraMap k[X] (RatFunc k) (Polynomial.C c * w.denom)))
            = (w - (algebraMap k (RatFunc k) c))⁻¹ := by
          rw [inv_eq_one_div, div_eq_div_iff] <;> simp
          · grind only [num_eq_mul_denom]
          · intro h
            have h_contra : w = algebraMap k (RatFunc k) c := by
              rw [← RatFunc.num_div_denom w]
              rw [sub_eq_zero.mp h, mul_div_cancel_right₀]
              · trivial
              · exact RatFunc.algebraMap_ne_zero (RatFunc.denom_ne_zero _)
            exact hw (h_contra ▸ IntermediateField.algebraMap_mem _ _)
          · rw [sub_eq_zero]
            intro h
            simp_all [IntermediateField.mem_bot]
        simp_all
        exact Subalgebra.sub_mem _ (IntermediateField.mem_adjoin_simple_self k w) (Subalgebra.algebraMap_mem _ _)
      · have h_inv_mem : (w - algebraMap k (RatFunc k) c)⁻¹
            ∈ k⟮(algebraMap k[X] (RatFunc k)) w.denom
              / (algebraMap k[X] (RatFunc k)) (w.num - Polynomial.C c * w.denom)⟯ := by
          have h_eq : (w - algebraMap k (RatFunc k) c)⁻¹
              = (algebraMap k[X] (RatFunc k)) w.denom
                / (algebraMap k[X] (RatFunc k)) (w.num - Polynomial.C c * w.denom) := by
            rw [inv_eq_iff_eq_inv, inv_div]
            simp
            grind only [num_div_denom, denom_ne_zero, algebraMap_apply, algebraMap_ne_zero]
          rw [h_eq]
          exact IntermediateField.mem_adjoin_simple_self k _
        have h_mem : w - algebraMap k (RatFunc k) c
            ∈ k⟮(algebraMap k[X] (RatFunc k)) w.denom
              / (algebraMap k[X] (RatFunc k)) (w.num - Polynomial.C c * w.denom)⟯ := by
          convert inv_mem h_inv_mem using 1
          rw [inv_inv]
        convert Subalgebra.add_mem _ h_mem (Subalgebra.algebraMap_mem _ c) using 1
        simp [sub_add_cancel]
  · cases lt_or_gt_of_ne h_deg
    · refine ⟨w.denom, w.num, ?_, ?_, ?_, ?_⟩
      · intro h
        simp_all
      · exact w.isCoprime_num_denom.symm
      · assumption
      · apply le_antisymm
        · simp [IntermediateField.adjoin_le_iff]
          rw [← inv_div]
          apply inv_mem
          rw [RatFunc.num_div_denom]
          exact IntermediateField.mem_adjoin_simple_self k w
        · simp
          convert Subfield.inv_mem _
            (IntermediateField.mem_adjoin_simple_self k
              ((algebraMap k[X] (RatFunc k)) w.denom / (algebraMap k[X] (RatFunc k)) w.num))
            using 1
          rw [inv_div, RatFunc.num_div_denom]
    · refine ⟨w.num, w.denom, ?_, ?_, ?_, ?_⟩
      · exact RatFunc.denom_ne_zero _
      · exact RatFunc.isCoprime_num_denom w
      · assumption
      · rw [RatFunc.num_div_denom]

/-
**Ritt normalisation.**  A *proper* intermediate field `E ⊊ k(X)` that contains a
nonconstant polynomial `f` is generated by a single polynomial `g`, i.e. `E = k(g)`.

Proof: `E ≠ ⊥` (it contains the nonconstant `f`), so by Lüroth `E = k(w)`; normalise `w` to a
coprime fraction `p/q` with `deg p > deg q` (`exists_coprime_repr_deg`); then
`denom_natDegree_eq_zero_of_poly_mem` forces `q` constant, so `p/q` is the image of a
polynomial `g`.
-/
theorem exists_poly_gen (f : k[X]) (hf : 2 ≤ f.natDegree)
    (E : IntermediateField k (RatFunc k))
    (hfE : algebraMap k[X] (RatFunc k) f ∈ E) (hEtop : E ≠ ⊤) :
    ∃ g : k[X], k⟮algebraMap k[X] (RatFunc k) g⟯ = E := by
  obtain ⟨g, hg⟩ : ∃ g : RatFunc k, E = IntermediateField.adjoin k {g} := by
    apply RatFunc.luroth
    intro h
    have := RatFunc.algebraMap_not_mem_bot f (by linarith)
    simp_all
  -- By `exists_coprime_repr_deg`, obtain `p` and `q` with `q ≠ 0`, `IsCoprime p q`, `q.natDegree < p.natDegree`, and `k⟮φ p / φ q⟯ = k⟮g⟯ = E`.
  obtain ⟨p, q, hq, hcop, hdeg, hEq⟩ :
      ∃ p q : k[X], q ≠ 0 ∧ IsCoprime p q ∧ q.natDegree < p.natDegree
        ∧ k⟮(algebraMap k[X] (RatFunc k) p) / (algebraMap k[X] (RatFunc k) q)⟯ = k⟮g⟯ := by
    apply exists_coprime_repr_deg
    intro hg_bot
    have h_contra : (algebraMap k[X] (RatFunc k) f) ∈ (⊥ : IntermediateField k (RatFunc k)) := by
      rw [hg] at hfE
      exact IntermediateField.adjoin_le_iff.mpr (Set.singleton_subset_iff.mpr hg_bot) hfE
    refine absurd h_contra (RatFunc.algebraMap_not_mem_bot f ?_)
    linarith
  -- By `denom_natDegree_eq_zero_of_poly_mem`, `q.natDegree = 0`.
  have hq0 : q.natDegree = 0 := by
    apply denom_natDegree_eq_zero_of_poly_mem p q hq hcop hdeg f (by omega)
    subst hg
    simp_all only [ne_eq]
  obtain ⟨c, hc⟩ : ∃ c : k, q = Polynomial.C c :=
    ⟨q.coeff 0, Polynomial.eq_C_of_natDegree_eq_zero hq0⟩
  refine ⟨Polynomial.C c⁻¹ * p, ?_⟩
  by_cases hc : c = 0 <;> simp_all [div_eq_mul_inv, mul_comm]

/-
**Ritt polynomial-decomposition bridge**.

If `f` is a polynomial of degree `≥ 2` and `k(f) ⊊ k(w) ⊊ k(X)` is a rational intermediate
field strictly between `k(f)` and `k(X)`, then `f` factors as an honest polynomial composition
`f = h ∘ g` with `deg h, deg g ≥ 2`.

Assembled from `exists_poly_gen` (normalising `k(w)` to a polynomial generator `g`) and
`poly_mem_adjoin_poly` (`f ∈ k(g)` polynomial ⟹ `f = h ∘ g`).  The degree bounds
`deg g ≥ 2` and `deg h ≥ 2` come from `k(w) ≠ k(X)` and `k(f) ≠ k(w)`.
-/
theorem exists_poly_comp_of_strict_intermediate (f : k[X]) (hf : 2 ≤ f.natDegree)
    (w : RatFunc k)
    (hle : k⟮algebraMap k[X] (RatFunc k) f⟯ ≤ k⟮w⟯)
    (hne1 : k⟮algebraMap k[X] (RatFunc k) f⟯ ≠ k⟮w⟯)
    (hne2 : k⟮w⟯ ≠ ⊤) :
    ∃ h g : k[X], 2 ≤ h.natDegree ∧ 2 ≤ g.natDegree ∧ f = h.comp g := by
  obtain ⟨g, hg⟩ := exists_poly_gen f hf (IntermediateField.adjoin k {w})
    (hle <| IntermediateField.subset_adjoin k _ <| Set.mem_singleton _) hne2
  have hg_nonconst : 2 ≤ g.natDegree := by
    have hg_finrank :
        2 ≤ Module.finrank (IntermediateField.adjoin k {algebraMap (Polynomial k) (RatFunc k) g}) (RatFunc k) := by
      contrapose! hne1
      interval_cases _ : Module.finrank (IntermediateField.adjoin k {algebraMap k[X] (RatFunc k) g}) (RatFunc k) <;>
        simp_all
      · have h_finite :
            FiniteDimensional (IntermediateField.adjoin k {algebraMap (Polynomial k) (RatFunc k) g}) (RatFunc k) := by
          apply RatFunc.finiteDimensional_of_ne_bot
          intro h
          simp_all
          refine absurd (RatFunc.algebraMap_not_mem_bot f ?_) ?_
          · linarith
          · simpa [← hg] using hle
        exact absurd ‹Module.finrank _ _ = 0› (Nat.ne_of_gt (Module.finrank_pos))
      · have := finrank_eq_one_iff_eq_top.mp ‹_›
        simp_all
    convert hg_finrank using 1
    have := @RatFunc.finrank_adjoin_eq_height k _ (algebraMap k[X] (RatFunc k) g) ?_
    · rw [this, RatFunc.height_algebraMap]
    · grind only [adjoin_eq_bot_iff, adjoin_le_iff, adjoin_simple_eq_bot_iff]
  obtain ⟨h, hh⟩ : ∃ h : k[X], f = h.comp g := by
    refine poly_mem_adjoin_poly f g ?_ ?_
    · linarith
    · rw [hg]
      exact hle (IntermediateField.mem_adjoin_simple_self k _)
  have hh_nonconst : 2 ≤ h.natDegree := by
    contrapose! hne1
    interval_cases _ : h.natDegree <;> simp_all [Polynomial.natDegree_comp]
    -- Since `h` has degree 1, write it as `h = C a * X + C b` for some `a, b : k`.
    obtain ⟨a, b, ha⟩ : ∃ a b : k, h = Polynomial.C a * Polynomial.X + Polynomial.C b :=
      ⟨h.coeff 1, h.coeff 0, Polynomial.eq_X_add_C_of_natDegree_le_one <| le_of_eq ‹_›⟩
    by_cases ha : a = 0 <;> simp_all [Polynomial.natDegree_add_eq_left_of_natDegree_lt]
    convert hg using 1
    apply le_antisymm <;> simp [IntermediateField.adjoin_le_iff]
    · exact Subalgebra.add_mem _
        (Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _) (IntermediateField.mem_adjoin_simple_self k _))
        (Subalgebra.algebraMap_mem _ _)
    · have h_mem : (algebraMap k (RatFunc k)) a⁻¹ ∈ k⟮C a * (algebraMap k[X] (RatFunc k)) g + C b⟯ :=
        Subalgebra.algebraMap_mem _ _
      have h_mem_mul : (algebraMap k (RatFunc k)) a⁻¹ * (C a * (algebraMap k[X] (RatFunc k)) g + C b - C b)
          ∈ k⟮C a * (algebraMap k[X] (RatFunc k)) g + C b⟯ :=
        Subalgebra.mul_mem _ h_mem
          (Subalgebra.sub_mem _ (IntermediateField.mem_adjoin_simple_self k _) (Subalgebra.algebraMap_mem _ _))
      convert h_mem_mul using 1
      simp [ha]
  use h, g

/-
**Primitivity of `k(f)/k(X)` for an indecomposable polynomial.**

If `f ∈ k[X]` has degree `≥ 2` and admits no polynomial decomposition `f = h ∘ g` with
`deg h, deg g ≥ 2`, then `k(f)` is a coatom in the lattice of intermediate fields of
`k(X) / k`: there is no intermediate field strictly between `k(f)` and `k(X)`.
-/
theorem isCoatom_adjoin_of_indecomposable (f : k[X]) (hf : 2 ≤ f.natDegree)
    (hind : ∀ (h g : k[X]), 2 ≤ h.natDegree → 2 ≤ g.natDegree → f ≠ h.comp g) :
    IsCoatom (k⟮algebraMap k[X] (RatFunc k) f⟯ : IntermediateField k (RatFunc k)) := by
  refine ⟨?_, fun M hM ↦ ?_⟩
  · intro h_top
    have h_finrank : Module.finrank k⟮(algebraMap k[X] (RatFunc k)) f⟯ (RatFunc k) = 1 :=
      finrank_eq_one_iff_eq_top.mpr h_top
    rw [RatFunc.finrank_adjoin_eq_height] at h_finrank
    · rw [RatFunc.height_algebraMap] at h_finrank
      linarith
    · refine RatFunc.algebraMap_not_mem_bot f ?_
      linarith
  · obtain ⟨w, hw⟩ := RatFunc.luroth M (ne_of_gt (lt_of_le_of_lt bot_le hM))
    contrapose! hind
    apply exists_poly_comp_of_strict_intermediate f hf w
    · exact hw ▸ hM.le
    · subst hw; simp_all only [ne_eq]; apply Aesop.BuiltinRules.not_intro; intro a; simp_all only [lt_self_iff_false]
    · grind +extAll

end RatFunc
