/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Hilbert.Analytic.SerreBaseSwap

/-!
# The intermediate ring `ℚ̄[T][x]` and the ramified branch point of the Serre base cover

The reduction set up in `InverseGalois.Hilbert.Analytic.SerreBaseSwap` is completed here by the
local computation at the branch point `T = serreBaseP 1`: two sheets of the cover collide there
and no others, so the inertia is generated by a transposition.  As in the Morse case the
computation is carried out not on the full integral closure `B` but on the concrete monogenic
ring `A[x] = ℚ̄[T][x]`, where Kummer–Dedekind reads the factorisation at the branch point off
the reduction of the defining polynomial.

## Main results

* `SerreBaseSwap.branch_ramified` — the branch point is ramified with index at least two.
* `SerreBaseSwap.exists_nontrivial_inertia` — a place above it with nontrivial inertia.
* `serreBaseGeomPoly_hasSwap` — the transposition in the geometric monodromy group.
* `serreBaseGeomPoly_galActionHom_surjective` — full symmetric geometric monodromy, via Jordan.
-/

open Polynomial
open scoped Classical
noncomputable section

set_option linter.unusedSectionVars false

namespace SerreBaseSwap

open SerreBaseCover

local instance splitsFactBranch (F : Type*) [Field F] (p : F[X]) :
    Fact ((p.map (algebraMap F p.SplittingField)).Splits) := ⟨SplittingField.splits p⟩

variable (n : ℕ) [hn3 : Fact (3 ≤ n)]

/-! ### The concrete intermediate ring `A[x] = ℚ̄[x] ⊆ B` -/

lemma exists_rootB : ∃ x : Bring n, (aeval x) (serreBaseC n) = 0 := by
  have h2 : 2 ≤ n := by
    have := hn3.out
    omega
  have hcard := serreBaseGeomPoly_card_rootSet n h2
  have hne : Nonempty ((serreBaseGeomPoly n).rootSet (Lfield n)) :=
    Fintype.card_pos_iff.mp (by
      rw [hcard]
      omega)
  obtain ⟨r⟩ := hne
  obtain ⟨s, _⟩ := (rootMap_bijective n).2 r
  exact ⟨s, aeval_eq_zero_of_mem_rootSet s.2⟩

/-- A chosen root of `serreBaseC n` in `B`. -/
def rootB : Bring n := (exists_rootB n).choose

lemma rootB_spec : (aeval (rootB n)) (serreBaseC n) = 0 := (exists_rootB n).choose_spec

/-- The intermediate ring `A[x] = ℚ̄[x] ⊆ B`. -/
abbrev Smid : Type := ↑(Algebra.adjoin Abase ({rootB n} : Set (Bring n)))

/-- The generator `x` viewed inside the intermediate ring. -/
def xS : Smid n := ⟨rootB n, Algebra.subset_adjoin (Set.mem_singleton _)⟩

set_option synthInstance.maxHeartbeats 200000 in
instance : Module.IsTorsionFree Abase (Bring n) := by
  constructor
  intro r hr x hx h
  replace h := congr_arg Subtype.val h
  simp_all [Algebra.smul_def]
  refine h.resolve_right ?_
  simpa [IsScalarTower.algebraMap_apply Abase GeomBase (Lfield n)] using hr.left.ne_zero

set_option synthInstance.maxHeartbeats 200000 in
instance : Module.IsTorsionFree Abase (Smid n) := by
  constructor
  intro r hr x y hxy
  replace hxy := congr_arg Subtype.val hxy
  simp_all [Algebra.smul_def]
  refine hxy.resolve_right ?_
  simpa using hr.left.ne_zero

/-! ### Shortcut instances

`Bring n` is an integral closure and `Smid n` is the carrier of an adjoined subalgebra, so the
generic search for their algebraic structure unfolds `Algebra.adjoin` down to `Subsemiring.closure`
and tries the graded-piece instances on the way.  Each shortcut below is `inferInstance`, hence
definitionally the term that search returns; naming them at a high priority only shortens the
route. -/

instance (priority := high) : CommRing (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : AddCommGroup (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : AddCommMonoid (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : SubtractionMonoid (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : NonAssocSemiring (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : Mul (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : Zero (Smid n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : One (Smid n) := inferInstance

instance (priority := high) : Algebra Abase (Smid n) := inferInstance

instance (priority := high) : Algebra (Smid n) (Bring n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : Module (Smid n) (Bring n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance (priority := high) : FaithfulSMul Abase (Bring n) := inferInstance

set_option synthInstance.maxHeartbeats 200000 in
instance : Module.IsTorsionFree (Smid n) (Bring n) := by
  refine ⟨fun x hx ↦ ?_⟩
  intro y z h_eq
  simp_all

set_option synthInstance.maxHeartbeats 200000 in
instance : Module.Finite (Smid n) (Bring n) :=
  (inferInstance : Module.Finite Abase (Bring n)).of_restrictScalars_finite Abase (Smid n) (Bring n)

set_option synthInstance.maxHeartbeats 200000 in
instance : Algebra.IsIntegral (Smid n) (Bring n) := by infer_instance

set_option synthInstance.maxHeartbeats 200000 in
lemma algebraMap_Abase_Bring_injective : Function.Injective (algebraMap Abase (Bring n)) := by
  intro x y hxy
  simpa using hxy

lemma xS_conductor_top : conductor Abase (xS n) = ⊤ := by
  convert (conductor_eq_top_iff_adjoin_eq_top (R := Abase) (x := xS n)).mpr _ using 1
  rw [Algebra.eq_top_iff]
  intro y
  simp [xS]
  rcases y with ⟨y, hy⟩
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ hy
  · exact fun x hx ↦ Algebra.subset_adjoin <| by simp_all only [Set.mem_singleton_iff, Subtype.mk.injEq]; simp_all only [Set.mem_singleton_iff]
  · exact Subalgebra.algebraMap_mem _
  · exact fun x y hx hy hx' hy' ↦ Subalgebra.add_mem _ hx' hy'
  · exact fun x y hx hy hx' hy' ↦ Subalgebra.mul_mem _ hx' hy'

lemma xS_minpoly : minpoly Abase (xS n) = serreBaseC n := by
  have h2 : 2 ≤ n := by
    have := hn3.out
    omega
  have h_minpoly_div : minpoly Abase (xS n) ∣ serreBaseC n := by
    refine minpoly.isIntegrallyClosed_dvd ?_ ?_
    · refine ⟨serreBaseC n, serreBaseC_monic n h2, ?_⟩
      convert rootB_spec n using 1
      simp [aeval_def, Polynomial.eval₂_eq_sum_range]
      rw [← Subtype.coe_inj]
      simp_all only [AddSubmonoidClass.coe_finset_sum, MulMemClass.coe_mul, SubalgebraClass.coe_algebraMap,
        SubmonoidClass.coe_pow, AlgHom.toRingHom_eq_coe, ZeroMemClass.coe_zero]
      rfl
    · convert rootB_spec n using 1
      rw [← Subtype.coe_inj]
      simp [xS]
  have h_irreducible : Irreducible (serreBaseC n) := serreBaseC_irreducible n
  refine eq_of_monic_of_associated ?_ ?_ ?_
  · apply minpoly.monic
    refine ⟨serreBaseC n, serreBaseC_monic n h2, ?_⟩
    convert rootB_spec n using 1
    simp [xS, aeval_def, Polynomial.eval₂_eq_sum_range, ← Subtype.coe_inj]
  · exact serreBaseC_monic n h2
  · obtain ⟨q, hq⟩ := h_minpoly_div
    have := h_irreducible.2 hq
    exact this.elim (fun h ↦ False.elim <| minpoly.not_isUnit Abase (xS n) h)
      fun h ↦ associated_of_dvd_dvd (by simp_all) (by simp_all)

set_option maxHeartbeats 400000 in
set_option synthInstance.maxHeartbeats 200000 in
/-- The image of the base variable `T` in `A[x] = ℚ̄[x]`:
`T ↦ xⁿ − (n/(n−1))·x^{n−1}` (i.e. `serreBaseP` evaluated at `x`). -/
lemma algebraMap_Abase_Smid_X :
    algebraMap Abase (Smid n) (Polynomial.X)
      = (xS n) ^ n
        - (algebraMap Abase (Smid n)
            (C ((n : AlgebraicClosure ℚ) / ((n : AlgebraicClosure ℚ) - 1)))) * (xS n) ^ (n - 1) := by
  have hφ := aeval_algHom_apply
    (Subalgebra.val (Algebra.adjoin Abase ({rootB n} : Set (Bring n)))) (xS n) (serreBaseC n)
  have hval : (Subalgebra.val (Algebra.adjoin Abase ({rootB n} : Set (Bring n)))) (xS n)
      = rootB n := rfl
  rw [hval] at hφ
  have hz : (Subalgebra.val (Algebra.adjoin Abase ({rootB n} : Set (Bring n))))
      ((aeval (xS n)) (serreBaseC n)) = 0 := by
    rw [← hφ]
    exact rootB_spec n
  have hxS0 : (aeval (xS n)) (serreBaseC n) = 0 := Subtype.val_injective hz
  have hexpand : (aeval (xS n)) (serreBaseC n)
      = (xS n) ^ n
        - (algebraMap Abase (Smid n)
            (C ((n : AlgebraicClosure ℚ) / ((n : AlgebraicClosure ℚ) - 1)))) * (xS n) ^ (n - 1)
        - algebraMap Abase (Smid n) X := by
    rw [serreBaseC, linearCoverC, map_sub, aeval_C]
    rw [Polynomial.aeval_def, Polynomial.eval₂_map]
    simp only [serreBaseP, eval₂_sub, eval₂_mul, eval₂_C, eval₂_pow, eval₂_X, RingHom.comp_apply]
  rw [hexpand] at hxS0
  linear_combination -hxS0

set_option synthInstance.maxHeartbeats 200000 in
lemma Smid_eval_surjective :
    Function.Surjective
      (Polynomial.eval₂RingHom ((algebraMap Abase (Smid n)).comp Polynomial.C) (xS n)) := by
  intro y
  have h_span : ∀ y : Smid n, y ∈ Subalgebra.toSubmodule (Algebra.adjoin (Abase) {xS n}) := by
    intro y
    apply Algebra.eq_top_iff.mp (by
    convert (conductor_eq_top_iff_adjoin_eq_top (R := Abase) (x := xS n)).mp
      (xS_conductor_top n) using 1) y
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ (h_span y)
  · exact fun x hx ↦ ⟨X, by simp_all⟩
  · intro r
    use Polynomial.comp r (serreBaseP n)
    have hkey : Polynomial.eval₂ ((algebraMap Abase (Smid n)).comp C) (xS n)
        (serreBaseP n) = algebraMap Abase (Smid n) X := by
      rw [algebraMap_Abase_Smid_X]
      simp only [serreBaseP, eval₂_sub, eval₂_mul, eval₂_C, eval₂_pow, eval₂_X, RingHom.comp_apply]
    simp only [Polynomial.coe_eval₂RingHom, Polynomial.eval₂_comp, hkey]
    rw [Polynomial.eval₂_eq_sum_range]
    conv_rhs => rw [as_sum_range_C_mul_X_pow r]
    simp [map_sum, map_mul, map_pow]
  · rintro x y hx hy ⟨a, rfl⟩ ⟨b, rfl⟩
    exact ⟨a + b, by simp⟩
  · rintro x y hx hy ⟨a, rfl⟩ ⟨b, rfl⟩
    exact ⟨a * b, by simp⟩

instance : IsDedekindDomain (Smid n) := by
  have : IsPrincipalIdealRing (Smid n) :=
    IsPrincipalIdealRing.of_surjective _ (Smid_eval_surjective n)
  infer_instance

/-! ### The branch-point ideal and its ramification -/

theorem sq_dvd_fiber_serre (hn : 3 ≤ n) :
    (X - C (1 : AlgebraicClosure ℚ)) ^ 2 ∣ (serreBaseP n - C (critT n)) := by
  have h2 : 2 ≤ n := by omega
  obtain ⟨q, hq⟩ : ∃ q : (AlgebraicClosure ℚ)[X],
      (X - C (1 : AlgebraicClosure ℚ)) * q = serreBaseP n - C (critT n) := by
    refine ⟨(serreBaseP n - C (critT n)) /ₘ (X - C 1), ?_⟩
    have hroot : (serreBaseP n - C (critT n)).IsRoot 1 := by
      rw [IsRoot.def, eval_sub, eval_C]
      unfold critT
      ring
    rw [mul_divByMonic_eq_iff_isRoot.mpr hroot]
  convert mul_dvd_mul_left (X - C (1 : AlgebraicClosure ℚ))
    (dvd_iff_isRoot.mpr (show q.eval 1 = 0 from ?_)) using 1
  · ring
  · exact hq.symm
  · replace hq := congr_arg derivative hq
    rw [derivative_mul, derivative_sub, derivative_X, derivative_C, sub_zero] at hq
    replace hq := congr_arg (eval 1) hq
    simp only [eval_add, eval_mul, eval_sub, eval_X, eval_C, one_mul, sub_self, zero_mul,
      add_zero] at hq
    rw [hq, derivative_sub, derivative_C, sub_zero, serreBaseP_derivative_eval n h2]
    ring

attribute [local instance] Ideal.Quotient.field

lemma branch_reduced_sq_dvd (hn : 3 ≤ n) :
    (X - C (Ideal.Quotient.mk (branchIdeal n) (Polynomial.C (1 : AlgebraicClosure ℚ)))) ^ 2 ∣
      (serreBaseC n).map (Ideal.Quotient.mk (branchIdeal n)) := by
  set ρ : (AlgebraicClosure ℚ) →+* (Abase ⧸ branchIdeal n) :=
    (Ideal.Quotient.mk (branchIdeal n)).comp C with hρ
  have hXeq : (Ideal.Quotient.mk (branchIdeal n)) X =
      (Ideal.Quotient.mk (branchIdeal n)) (C (critT n)) := by
    rw [← sub_eq_zero, ← map_sub, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.mem_span_singleton_self _
  have hmapeq : (serreBaseC n).map (Ideal.Quotient.mk (branchIdeal n))
      = (serreBaseP n - C (critT n)).map ρ := by
    simp only [serreBaseC, linearCoverC, Polynomial.map_sub, Polynomial.map_map, Polynomial.map_C,
      hXeq, hρ, RingHom.comp_apply]
  rw [hmapeq]
  have hdvd := sq_dvd_fiber_serre n hn
  have := Polynomial.map_dvd ρ hdvd
  simpa [Polynomial.map_pow, Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C, hρ,
    RingHom.comp_apply] using this

set_option maxHeartbeats 400000 in
lemma branch_ramified (hn : 3 ≤ n) :
    ∃ PS : Ideal (Smid n), PS.IsPrime ∧ PS.LiesOver (branchIdeal n) ∧
      2 ≤ Ideal.ramificationIdx (algebraMap Abase (Smid n)) (branchIdeal n) PS ∧
      Ideal.map (algebraMap (Smid n) (Bring n)) PS ≠ ⊥ := by
  classical
  have h2 : 2 ≤ n := by omega
  have hsq := branch_reduced_sq_dvd n hn
  have hI' : branchIdeal n ≠ ⊥ := branchIdeal_ne_bot n
  have hxint : IsIntegral Abase (xS n) := ⟨serreBaseC n, serreBaseC_monic n h2, by
    rw [← xS_minpoly n]
    exact minpoly.aeval Abase (xS n)⟩
  have hx : (conductor Abase (xS n)).comap (algebraMap Abase (Smid n)) ⊔ (branchIdeal n) = ⊤ := by
    rw [xS_conductor_top]
    simp
  set d : (Abase ⧸ branchIdeal n)[X] :=
    X - C (Ideal.Quotient.mk (branchIdeal n) (C (1 : AlgebraicClosure ℚ))) with hd
  have hPne : (minpoly Abase (xS n)).map (Ideal.Quotient.mk (branchIdeal n)) ≠ 0 := by
    rw [xS_minpoly]
    exact (Monic.map _ (serreBaseC_monic n h2)).ne_zero
  have hd_irr : Irreducible d := irreducible_X_sub_C _
  have hd_norm : normalize d = d := (monic_X_sub_C _).normalize_eq_self
  have hcount2 : 2 ≤ Multiset.count d (UniqueFactorizationMonoid.normalizedFactors
      ((minpoly Abase (xS n)).map (Ideal.Quotient.mk (branchIdeal n)))) := by
    have hemult : (2 : ℕ∞) ≤ emultiplicity d
        ((minpoly Abase (xS n)).map (Ideal.Quotient.mk (branchIdeal n))) := by
      rw [xS_minpoly]
      exact pow_dvd_iff_le_emultiplicity.mp hsq
    rw [UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hd_irr hPne, hd_norm]
      at hemult
    exact_mod_cast hemult
  have hd_mem : d ∈ UniqueFactorizationMonoid.normalizedFactors
      ((minpoly Abase (xS n)).map (Ideal.Quotient.mk (branchIdeal n))) :=
    Multiset.count_pos.mp (by omega)
  set equiv := KummerDedekind.normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
    (inferInstance : (branchIdeal n).IsMaximal) hI' hx hxint with heq
  set PS := (equiv.symm ⟨d, hd_mem⟩ :
    {J // J ∈ UniqueFactorizationMonoid.normalizedFactors
      (Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n))}) with hPS
  have hmem : PS.1 ∈ UniqueFactorizationMonoid.normalizedFactors
      (Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n)) := PS.2
  have hmapI_ne : Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n) ≠ ⊥ :=
    Ideal.map_ne_bot_of_ne_bot hI'
  have hPS_ne : PS.1 ≠ ⊥ := UniqueFactorizationMonoid.ne_zero_of_mem_normalizedFactors hmem
  have hPS_prime : Prime PS.1 := UniqueFactorizationMonoid.prime_of_normalized_factor _ hmem
  have hPS_isPrime : PS.1.IsPrime := Ideal.isPrime_of_prime hPS_prime
  have hle : Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n) ≤ PS.1 :=
    (Ideal.dvd_iff_le).mp (UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hmem)
  have hcomap : Ideal.comap (algebraMap Abase (Smid n)) PS.1 = branchIdeal n := by
    have hIle : branchIdeal n ≤ Ideal.comap (algebraMap Abase (Smid n)) PS.1 :=
      Ideal.map_le_iff_le_comap.mp hle
    rcases (inferInstance : (branchIdeal n).IsMaximal).eq_of_le (by
      intro h
      exact hPS_isPrime.ne_top (Ideal.comap_eq_top_iff.mp h)) hIle with h
    exact h.symm
  have hLiesOver : PS.1.LiesOver (branchIdeal n) := ⟨hcomap.symm⟩
  refine ⟨PS.1, hPS_isPrime, hLiesOver, ?_, Ideal.map_ne_bot_of_ne_bot hPS_ne⟩
  rw [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count hmapI_ne hPS_isPrime hPS_ne]
  have hkd := KummerDedekind.emultiplicity_factors_map_eq_emultiplicity
    (inferInstance : (branchIdeal n).IsMaximal) hI' hx hxint hmem
  have hequiv_eq : (↑(equiv ⟨PS.1, hmem⟩) : (Abase ⧸ branchIdeal n)[X]) = d := by
    have h1 : (⟨PS.1, hmem⟩ :
        {J // J ∈ UniqueFactorizationMonoid.normalizedFactors
          (Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n))}) = PS := Subtype.ext rfl
    rw [h1, hPS, Equiv.apply_symm_apply]
  rw [hequiv_eq] at hkd
  have hPS_irr : Irreducible PS.1 :=
    UniqueFactorizationMonoid.irreducible_of_normalized_factor _ hmem
  have hPS_normeq : normalize PS.1 = PS.1 :=
    UniqueFactorizationMonoid.normalize_normalized_factor _ hmem
  have hcount_eq : emultiplicity PS.1 (Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n))
      = ((Multiset.count PS.1 (UniqueFactorizationMonoid.normalizedFactors
          (Ideal.map (algebraMap Abase (Smid n)) (branchIdeal n)))) : ℕ∞) := by
    rw [UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hPS_irr hmapI_ne,
      hPS_normeq]
  have hd_emult : (2 : ℕ∞) ≤ emultiplicity d
      ((minpoly Abase (xS n)).map (Ideal.Quotient.mk (branchIdeal n))) := by
    rw [UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hd_irr hPne, hd_norm]
    exact_mod_cast hcount2
  rw [← hkd, hcount_eq] at hd_emult
  exact_mod_cast hd_emult

lemma branch_residue_separable (Q : Ideal (Bring n)) [Q.LiesOver (branchIdeal n)] [Q.IsMaximal] :
    Algebra.IsSeparable (Abase ⧸ branchIdeal n) ((Bring n) ⧸ Q) := by
  have : CharZero (Abase ⧸ branchIdeal n) := algebraRat.charZero _
  have : Algebra.IsIntegral (Abase ⧸ branchIdeal n) ((Bring n) ⧸ Q) :=
    Ideal.Quotient.algebra_isIntegral_of_liesOver Q (branchIdeal n)
  have : Algebra.IsAlgebraic (Abase ⧸ branchIdeal n) ((Bring n) ⧸ Q) :=
    Algebra.IsIntegral.isAlgebraic
  exact Algebra.IsAlgebraic.isSeparable_of_perfectField

set_option synthInstance.maxHeartbeats 200000 in
lemma exists_nontrivial_inertia (hn : 3 ≤ n) :
    ∃ (P : Ideal (Bring n)), P.IsMaximal ∧ P.LiesOver (branchIdeal n) ∧
      ∃ g : (serreBaseGeomPoly n).Gal, g ∈ P.inertia (serreBaseGeomPoly n).Gal ∧ g ≠ 1 := by
  obtain ⟨PS, hPSprime, hPSover, hPSe, hPSmap⟩ := branch_ramified n hn
  exact inertia_of_ramified n (Smid n) (branchIdeal n) (branchIdeal_ne_bot n)
    (algebraMap_Abase_Bring_injective n) PS hPSe hPSmap
    (Ideal.map_ne_bot_of_ne_bot (branchIdeal_ne_bot n))
    (fun Q _ _ ↦ branch_residue_separable n Q)

/-! ## Assembling the transposition -/

theorem swap_input_final (hn : 3 ≤ n) :
    ∃ g : (serreBaseGeomPoly n).Gal,
      ((Gal.galActionHom (serreBaseGeomPoly n) (Lfield n)) g).IsSwap := by
  classical
  obtain ⟨P, hPmax, hPlo, g, hg_in, hg_ne⟩ := exists_nontrivial_inertia n hn
  have hmorse := Polynomial.Splits.toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia
    (R := Abase) (S := Bring n) (G := (serreBaseGeomPoly n).Gal) (f := serreBaseC n)
    (serreBaseC_splits_B n) P (serre_ncard_bound n hn P) g hg_in
  have hne1 : MulAction.toPermHom (serreBaseGeomPoly n).Gal
      ((serreBaseC n).rootSet (Bring n)) g ≠ 1 := by
    intro h
    refine hg_ne (toPermHom_B_injective n ?_)
    simpa using h
  have hswapB : (MulAction.toPermHom (serreBaseGeomPoly n).Gal
      ((serreBaseC n).rootSet (Bring n)) g).IsSwap := hmorse.resolve_left hne1
  refine ⟨g, ?_⟩
  rw [galActionHom_eq_permCongr n g]
  exact MorseSwap.isSwap_permCongr
    ((rootEquiv n).trans (Gal.rootsEquivRoots (serreBaseGeomPoly n) (Lfield n))) hswapB

end SerreBaseSwap

open SerreBaseCover

/-- The polynomial always splits in its own splitting field (top-level `local Fact` instance). -/
local instance splitsInSplittingFieldSerre'' (F : Type*) [Field F] (p : F[X]) :
    Fact ((p.map (algebraMap F p.SplittingField)).Splits) := ⟨SplittingField.splits p⟩

open scoped Classical in
/-- **A transposition in the geometric monodromy group** of the Serre base cover: the group
contains an element acting on the roots as a transposition. -/
theorem serreBaseGeomPoly_hasSwap (n : ℕ) (hn : 3 ≤ n) :
    ∃ g : (serreBaseGeomPoly n).Gal, Equiv.Perm.IsSwap
      ((Gal.galActionHom (serreBaseGeomPoly n) (serreBaseGeomPoly n).SplittingField) g) := by
  have : Fact (3 ≤ n) := ⟨hn⟩
  exact SerreBaseSwap.swap_input_final n hn

open scoped Classical in
/-- **The geometric-monodromy surjectivity for the Serre base cover**, via Jordan's theorem.
The permutation representation of the geometric Galois group of `serreBaseP n − T` over `ℚ̄(T)`
on the roots is surjective onto the full symmetric group. -/
theorem serreBaseGeomPoly_galActionHom_surjective (n : ℕ) (hn : 3 ≤ n) :
    Function.Surjective
      (Gal.galActionHom (serreBaseGeomPoly n) (serreBaseGeomPoly n).SplittingField) := by
  classical
  rw [← MonoidHom.range_eq_top]
  obtain ⟨g, hg⟩ := serreBaseGeomPoly_hasSwap n hn
  exact Equiv.Perm.subgroup_eq_top_of_isPreprimitive_of_isSwap_mem
    (SerreBaseCover.serreBaseGeomPoly_isPreprimitive n hn)
    (Gal.galActionHom (serreBaseGeomPoly n) (serreBaseGeomPoly n).SplittingField g) hg ⟨g, rfl⟩

end
