/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Core.Basic
import InverseGalois.Solvable.Shafarevich.PrimePower

/-!
# Generic operator groups

Shafarevich's construction replaces an arbitrary finite `p`-group carrying an action of a group `U`
by a *generic* one.  Let `F` be the free group on `n` copies of the regular `U`-set, so that `U`
permutes a basis of `F` freely, and let `S` be a finite group.  Killing every homomorphism from `F`
to `S` at once leaves a finite quotient, the relatively free group on that basis in the variety
generated by `S`, and the action of `U` descends to it.  Taking for `S` a given finite group `P`
carrying a `U`-action, and for `n` the order of `P`, the group `P` is an equivariant quotient of the
generic group, so `P ⋊ U` is a quotient of the generic semidirect product.  A Galois group over `ℚ`
stays one after passing to a quotient, so a split embedding problem over `ℚ` with a `p`-group kernel
is settled once the generic ones are.

The construction is functorial in the basis: any homomorphism between two of these free groups
carries the one kernel into the other, because the kernel is cut out by *all* homomorphisms to `S`
at once.  That is what makes the generic groups usable as a single system rather than one at a time.

## Main definitions

* `InverseGalois.Shafarevich.OperatorFree` — the free group on `n` copies of the regular `U`-set.
* `InverseGalois.Shafarevich.freeAut` — the action of `U` on it by translating the basis.
* `InverseGalois.Shafarevich.Generic` — the relatively free operator group, the quotient of
  `OperatorFree` by the elements killed by every homomorphism to the test group `S`.
* `InverseGalois.Shafarevich.genericAut` — the induced action of `U` on the generic group.
* `Shafarevich.GenericSplitEP` — the split embedding problem over `ℚ` for the generic kernels.

## Main results

* `InverseGalois.Shafarevich.isPGroup_generic` — the generic group over a `p`-group test group is a
  finite `p`-group.
* `InverseGalois.Shafarevich.genericProj_surjective` — **a finite group with a `U`-action is an
  equivariant quotient of a generic operator group.**
* `Shafarevich.splitPrimePowerEP_of_genericSplitEP` — **the split embedding problem over `ℚ` with a
  `p`-group kernel follows from its generic instances**, and
  `Shafarevich.genericSplitEP_of_splitPrimePowerEP` for the converse.

## Tags

inverse Galois problem, Shafarevich's theorem, embedding problem, relatively free group
-/

namespace InverseGalois.Shafarevich

variable (U : Type) [Group U] (n : ℕ) (S : Type) [Group S]

/-! ### The free group on a free operator set -/

/-- The free group on `n` copies of the regular `U`-set. -/
abbrev OperatorFree : Type := FreeGroup (Fin n × U)

/-- Left translation of the second coordinate of the basis of `OperatorFree`. -/
def indexEquiv (u : U) : Fin n × U ≃ Fin n × U :=
  (Equiv.refl (Fin n)).prodCongr (Equiv.mulLeft u)

@[simp]
theorem indexEquiv_apply (u : U) (x : Fin n × U) : indexEquiv U n u x = (x.1, u * x.2) := rfl

/-- **The action of `U` on the free group on `n` copies of its regular representation**, by
translating the second coordinate of the basis.  The basis is a free `U`-set. -/
def freeAut : U →* MulAut (OperatorFree U n) :=
  MonoidHom.mk' (fun u => FreeGroup.freeGroupCongr (indexEquiv U n u)) <| by
    intro u v
    refine MulEquiv.ext fun x => ?_
    have he : indexEquiv U n (u * v) = (indexEquiv U n v).trans (indexEquiv U n u) :=
      Equiv.ext fun y => by simp [mul_assoc]
    show FreeGroup.freeGroupCongr (indexEquiv U n (u * v)) x = _
    rw [he, ← FreeGroup.freeGroupCongr_trans]
    rfl

@[simp]
theorem freeAut_of (u : U) (x : Fin n × U) :
    freeAut U n u (FreeGroup.of x) = FreeGroup.of (x.1, u * x.2) := by
  simp [freeAut, FreeGroup.map.of]

/-! ### The generic quotient -/

/-- The product of all homomorphisms from the free operator group to the test group `S`. -/
def testPi : OperatorFree U n →* ((OperatorFree U n →* S) → S) where
  toFun x := fun f => f x
  map_one' := by ext f; simp
  map_mul' x y := by ext f; simp

omit [Group U] in
@[simp]
theorem testPi_apply (x : OperatorFree U n) (f : OperatorFree U n →* S) :
    testPi U n S x f = f x := rfl

omit [Group U] in
theorem mem_testPi_ker {x : OperatorFree U n} :
    x ∈ (testPi U n S).ker ↔ ∀ f : OperatorFree U n →* S, f x = 1 := by
  refine ⟨fun hx f => ?_, fun h => MonoidHom.mem_ker.mpr (funext fun f => by simpa using h f)⟩
  simpa using congrFun (MonoidHom.mem_ker.mp hx) f

/-- **The generic `U`-operator group**: the relatively free group on `n` copies of the regular
`U`-set in the variety generated by the test group `S`. -/
abbrev Generic : Type := OperatorFree U n ⧸ (testPi U n S).ker

instance instFiniteOperatorHom [Finite U] [Finite S] : Finite (OperatorFree U n →* S) :=
  Finite.of_equiv (Fin n × U → S) FreeGroup.lift

instance instFiniteGeneric [Finite U] [Finite S] : Finite (Generic U n S) :=
  Finite.of_equiv _ (QuotientGroup.quotientKerEquivRange (testPi U n S)).symm.toEquiv

/-- A power of a `p`-group indexed by a finite type is a `p`-group. -/
theorem isPGroup_pi {ι : Type*} [Finite ι] {ℓ : ℕ} {T : Type*} [Group T] (hT : IsPGroup ℓ T) :
    IsPGroup ℓ (ι → T) := by
  classical
  letI := Fintype.ofFinite ι
  intro z
  choose k hk using fun i => hT (z i)
  refine ⟨Finset.univ.sup k, funext fun i => ?_⟩
  obtain ⟨m, hm⟩ : ℓ ^ k i ∣ ℓ ^ Finset.univ.sup k :=
    pow_dvd_pow ℓ (Finset.le_sup (Finset.mem_univ i))
  have : z i ^ ℓ ^ Finset.univ.sup k = 1 := by rw [hm, pow_mul, hk i, one_pow]
  simpa using this

omit [Group U] in
/-- **The generic group over a `p`-group test group is a `p`-group.** -/
theorem isPGroup_generic {ℓ : ℕ} [Finite U] [Finite S] (hS : IsPGroup ℓ S) :
    IsPGroup ℓ (Generic U n S) :=
  ((isPGroup_pi (ι := OperatorFree U n →* S) hS).to_subgroup (testPi U n S).range).of_equiv
    (QuotientGroup.quotientKerEquivRange (testPi U n S)).symm

/-! ### The action on the generic group -/

theorem map_testPi_ker (u : U) :
    Subgroup.map (freeAut U n u : OperatorFree U n →* OperatorFree U n) (testPi U n S).ker
      = (testPi U n S).ker := by
  have hle : ∀ v : U, Subgroup.map (freeAut U n v : OperatorFree U n →* OperatorFree U n)
      (testPi U n S).ker ≤ (testPi U n S).ker := by
    intro v y hy
    obtain ⟨x, hx, rfl⟩ := Subgroup.mem_map.mp hy
    rw [mem_testPi_ker] at hx ⊢
    intro f
    exact hx (f.comp (freeAut U n v : OperatorFree U n →* OperatorFree U n))
  refine le_antisymm (hle u) fun x hx => ?_
  refine ⟨freeAut U n u⁻¹ x, hle u⁻¹ ⟨x, hx, rfl⟩, ?_⟩
  have hinv : freeAut U n u * freeAut U n u⁻¹ = 1 := by
    rw [← map_mul, mul_inv_cancel, map_one]
  calc freeAut U n u (freeAut U n u⁻¹ x) = (freeAut U n u * freeAut U n u⁻¹) x := rfl
    _ = x := by rw [hinv]; rfl

/-- **The action of `U` on the generic operator group.** -/
def genericAut : U →* MulAut (Generic U n S) :=
  MonoidHom.mk' (fun u => QuotientGroup.congr _ _ (freeAut U n u) (map_testPi_ker U n S u)) <| by
    intro u v
    refine MulEquiv.ext fun x => ?_
    induction x using QuotientGroup.induction_on with
    | _ y =>
      show QuotientGroup.mk (freeAut U n (u * v) y) = _
      rw [map_mul]
      rfl

@[simp]
theorem genericAut_mk (u : U) (y : OperatorFree U n) :
    genericAut U n S u (QuotientGroup.mk y) = QuotientGroup.mk (freeAut U n u y) := rfl

/-! ### Every operator group is a generic one -/

variable {U n}

/-- The equivariant homomorphism out of the free operator group determined by a family of
elements. -/
def orbitLift {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P) :
    OperatorFree U n →* P :=
  FreeGroup.lift fun x => φ x.2 (a x.1)

@[simp]
theorem orbitLift_of {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P) (x : Fin n × U) :
    orbitLift φ a (FreeGroup.of x) = φ x.2 (a x.1) :=
  FreeGroup.lift_apply_of

theorem orbitLift_equivariant {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P) (u : U) :
    (orbitLift φ a).comp (freeAut U n u : OperatorFree U n →* OperatorFree U n)
      = (φ u).toMonoidHom.comp (orbitLift φ a) :=
  FreeGroup.ext_hom _ _ fun x => by simp [map_mul]

/-- The projection of the generic operator group onto a group carrying a `U`-action. -/
def genericProj {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P) :
    Generic U n P →* P :=
  QuotientGroup.lift _ (orbitLift φ a) fun _ hx => (mem_testPi_ker U n P).mp hx _

@[simp]
theorem genericProj_mk {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P)
    (y : OperatorFree U n) :
    genericProj φ a (QuotientGroup.mk y) = orbitLift φ a y := rfl

theorem genericProj_equivariant {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P) (u : U) :
    (genericProj φ a).comp (genericAut U n P u).toMonoidHom
      = (φ u).toMonoidHom.comp (genericProj φ a) := by
  refine MonoidHom.ext fun x => ?_
  induction x using QuotientGroup.induction_on with
  | _ y => exact congrFun (congrArg (fun g : OperatorFree U n →* P => (g : _ → _))
      (orbitLift_equivariant φ a u)) y

/-- **A group generated by the `U`-orbits of `n` elements is a quotient of the generic operator
group on `n` letters.** -/
theorem genericProj_surjective {P : Type} [Group P] (φ : U →* MulAut P) (a : Fin n → P)
    (hgen : Subgroup.closure {x : P | ∃ (i : Fin n) (u : U), x = φ u (a i)} = ⊤) :
    Function.Surjective (genericProj φ a) := by
  rw [← MonoidHom.range_eq_top]
  refine top_le_iff.mp ?_
  rw [← hgen]
  refine Subgroup.closure_le _ |>.mpr ?_
  rintro x ⟨i, u, rfl⟩
  exact ⟨QuotientGroup.mk (FreeGroup.of (i, u)), by simp⟩

/-- Enumerating a finite group by its own elements gives a generating family of orbits. -/
theorem closure_orbits_eq_top {P : Type} [Group P] [Finite P] (φ : U →* MulAut P) :
    Subgroup.closure
        {x : P | ∃ (i : Fin (Nat.card P)) (u : U), x = φ u ((Finite.equivFin P).symm i)} = ⊤ := by
  refine top_le_iff.mp fun x _ => ?_
  refine Subgroup.subset_closure ⟨Finite.equivFin P x, 1, ?_⟩
  simp

/-! ### The reduction -/

/-- **A split embedding problem with a finite kernel is a quotient of a generic one.** -/
theorem isInverseGalois_semidirectProduct_of_generic {P : Type} [Group P] [Finite P]
    (φ : U →* MulAut P)
    (h : IsInverseGalois
      (Generic U (Nat.card P) P ⋊[genericAut U (Nat.card P) P] U)) :
    IsInverseGalois (P ⋊[φ] U) := by
  set a : Fin (Nat.card P) → P := fun i => (Finite.equivFin P).symm i with ha
  have hsurj : Function.Surjective (genericProj φ a) :=
    genericProj_surjective φ a (closure_orbits_eq_top φ)
  refine h.of_surjective (SemidirectProduct.map (genericProj φ a) (MonoidHom.id U)
    (fun u => genericProj_equivariant φ a u)) ?_
  rintro ⟨p, u⟩
  obtain ⟨z, hz⟩ := hsurj p
  exact ⟨⟨z, u⟩, by ext <;> simp [hz]⟩

end InverseGalois.Shafarevich

namespace Shafarevich

open InverseGalois.Shafarevich

/-- **The split embedding problem over `ℚ` for the generic kernels.**  Whenever `U` is a Galois
group over `ℚ` and `S` is a finite `ℓ`-group, the semidirect product of `U` with the relatively
free operator group on `n` letters over `S` is again a Galois group over `ℚ`. -/
def GenericSplitEP (ℓ : ℕ) : Prop :=
  ∀ (S U : Type) [Group S] [Finite S] [Group U] [Finite U] (n : ℕ), IsPGroup ℓ S →
    IsInverseGalois U → IsInverseGalois (Generic U n S ⋊[genericAut U n S] U)

/-- **The split embedding problem over `ℚ` with a `p`-group kernel follows from its generic
instances.** -/
theorem splitPrimePowerEP_of_genericSplitEP (h : ∀ ℓ : ℕ, GenericSplitEP ℓ) :
    SplitPrimePowerEP := by
  intro H U _ _ _ _ p _ hH φ hU
  exact isInverseGalois_semidirectProduct_of_generic φ (h p H U (Nat.card H) hH hU)

/-- The generic instances are themselves instances of the split embedding problem with a `p`-group
kernel. -/
theorem genericSplitEP_of_splitPrimePowerEP {ℓ : ℕ} (hℓ : ℓ.Prime) (h : SplitPrimePowerEP) :
    GenericSplitEP ℓ := by
  intro S U _ _ _ _ n hS hU
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  exact h _ _ ℓ (isPGroup_generic U n S hS) _ hU

end Shafarevich
