/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.InertiaTameLevel
import InverseGalois.Solvable.Shafarevich.KernelPrimeClass

/-!
# A smooth homomorphism of inertia at a prime away from the exponent has cyclic image

At a prime away from an exponent `n`, the inertia subgroup of an infinite extension is generated by
one element modulo an open subgroup and modulo raising to a power prime to `n`.  A homomorphism of
inertia into a group of exponent `n` which is trivial on an open subgroup therefore has cyclic
image, and one of its own values generates: raising to the prime-to-`n` power costs nothing, since
the two orders which then divide the order of a value are coprime.

The prescriptions of the repair name the part of inertia the base realization kills, at a prime
away from the prime of the layer.  Read over the level that realization cuts out, that subgroup is
the whole inertia subgroup, so the same statement applies to it: a prescribed homomorphism there is
a power of a single value, and the arithmetic which answers it need only produce one radicand.

## Main results

* `InverseGalois.Shafarevich.exists_forall_mem_zpowers_of_inertia` — a homomorphism of the inertia
  subgroup at a prime away from an exponent, into a group of that exponent and trivial on an open
  subgroup, has one of its values generating all of them.
* `InverseGalois.Shafarevich.exists_forall_mem_zpowers_of_inertia_inf_ker` — **the same for the
  part of inertia the base realization kills**, at a prime away from the prime of the layer.

## Tags

Shafarevich's theorem, embedding problem, inertia subgroup, tame character, cyclic group
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1600000

/-! ### Inertia over the level -/

section Base

variable {K Ω : Type*} [Field K] [NumberField K] [Field Ω] [Algebra K Ω] [IsGalois K Ω]
  [IsAlgClosed Ω]

/-- **A homomorphism of the inertia subgroup at a prime away from an exponent, into a group of that
exponent and trivial on an open subgroup, has one of its values generating all of them.**

Inertia is carried by a single element `g` modulo the open subgroup and modulo raising to a power
`m` prime to the exponent.  The value at `x` divided by the corresponding power of the value at `g`
is therefore killed by `m` and by the exponent at once, so it is trivial. -/
theorem exists_forall_mem_zpowers_of_inertia {n : ℕ} {P : Ideal (𝓞 Ω)} [P.IsPrime] (hP : P ≠ ⊥)
    (hn : (n : 𝓞 Ω) ∉ P) {B : Subgroup Gal(Ω/K)} (hB : B = Ideal.inertia Gal(Ω/K) P)
    {M : Type*} [CommGroup M] (hMn : ∀ v : M, v ^ n = 1) (a : ↥B →* M)
    (hsm : ∃ N : Subgroup Gal(Ω/K), IsOpen (N : Set Gal(Ω/K)) ∧
      ∀ x : ↥B, (x : Gal(Ω/K)) ∈ N → a x = 1) :
    ∃ g : ↥B, ∀ x : ↥B, a x ∈ Subgroup.zpowers (a g) := by
  subst hB
  obtain ⟨N, hN, hNa⟩ := hsm
  obtain ⟨g, m, hmn, hg⟩ := exists_mem_inertia_forall_pow_mem P hP hn hN
  refine ⟨g, fun x => ?_⟩
  obtain ⟨j, hj⟩ := hg x
  have hone : (a x * (a g ^ j)⁻¹) ^ m = 1 := by
    have h1 : a ((x * (g ^ j)⁻¹) ^ m) = 1 := hNa _ hj
    rwa [_root_.map_pow, _root_.map_mul, _root_.map_inv, _root_.map_pow] at h1
  have hgcd : Nat.gcd m n = 1 := hmn
  have hdvd : orderOf (a x * (a g ^ j)⁻¹) ∣ 1 := by
    have hd := Nat.dvd_gcd (orderOf_dvd_of_pow_eq_one hone) (orderOf_dvd_of_pow_eq_one (hMn _))
    rwa [hgcd] at hd
  have hx1 : a x * (a g ^ j)⁻¹ = 1 := orderOf_eq_one_iff.1 (Nat.dvd_one.1 hdvd)
  rw [mul_inv_eq_one] at hx1
  refine ⟨(j : ℤ), ?_⟩
  show a g ^ (j : ℤ) = a x
  rw [zpow_natCast, ← hx1]

end Base

/-! ### The part of inertia the base realization kills -/

section Level

variable {ℓ : ℕ} {k Ω U : Type*} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω] [IsAlgClosed Ω]
  [Group U] {φ : Gal(Ω/k) →* U} {K : IntermediateField k Ω} [NumberField ↥K]

/-- **A smooth homomorphism of the part of inertia the base realization kills has one of its values
generating all of them**, at a prime away from the prime of the layer.

Read over the level the base realization cuts out, that subgroup is the whole inertia subgroup
there, and every element of it comes from an automorphism over the level, the base realization
being trivial on it to begin with. -/
theorem exists_forall_mem_zpowers_of_inertia_inf_ker (hKker : K.fixingSubgroup = φ.ker)
    {P : Ideal (𝓞 Ω)} [P.IsPrime] (hP : P ≠ ⊥) (hℓP : (ℓ : 𝓞 Ω) ∉ P)
    {A : Subgroup Gal(Ω/k)} (hA : A = Ideal.inertia Gal(Ω/k) P ⊓ φ.ker)
    {M : Type*} [CommGroup M] (hMℓ : ∀ v : M, v ^ ℓ = 1)
    (a : ↥A →* M) (hasm : IsSmooth₁ ((a : ↥A →* M) : ↥A → M)) :
    ∃ x₀ : ↥A, ∀ x : ↥A, a x ∈ Subgroup.zpowers (a x₀) := by
  set r : ↥(A.comap (galSubHom K)) →* ↥A := (galSubHom K).subgroupComap A with hr
  have hrc : ∀ x : ↥(A.comap (galSubHom K)),
      (r x : Gal(Ω/k)) = galSubHom K (x : Gal(Ω/↥K)) := fun _ => rfl
  have hB : A.comap (galSubHom K) = Ideal.inertia Gal(Ω/↥K) P :=
    comap_galSubHom_eq_inertia hKker hA
  have hsm : ∃ N : Subgroup Gal(Ω/↥K), IsOpen (N : Set Gal(Ω/↥K)) ∧
      ∀ x : ↥(A.comap (galSubHom K)), (x : Gal(Ω/↥K)) ∈ N → (a.comp r) x = 1 := by
    obtain ⟨N₀, hN₀, hcon⟩ := hasm
    obtain ⟨E, hEfin, hEN⟩ := exists_fixingSubgroup_forall_mem hN₀.isOpen
    haveI := hEfin
    refine ⟨E.fixingSubgroup.comap (galSubHom K), ?_, fun x hx => ?_⟩
    · rw [Subgroup.coe_comap]
      exact E.fixingSubgroup_isOpen.preimage (continuous_galSubHom K)
    · have h1 := hcon 1 (r x) (hEN (r x) (by rw [hrc]; exact Subgroup.mem_comap.1 hx))
      rwa [one_mul, _root_.map_one] at h1
  obtain ⟨g, hg⟩ := exists_forall_mem_zpowers_of_inertia hP hℓP hB hMℓ (a.comp r) hsm
  refine ⟨r g, fun x => ?_⟩
  have hxA : (x : Gal(Ω/k)) ∈ Ideal.inertia Gal(Ω/k) P ⊓ φ.ker := by rw [← hA]; exact x.2
  have hyA : (kerGalEquiv hKker ⟨(x : Gal(Ω/k)), (Subgroup.mem_inf.1 hxA).2⟩ : Gal(Ω/↥K))
      ∈ A.comap (galSubHom K) := by
    refine Subgroup.mem_comap.2 ?_
    rw [galSubHom_kerGalEquiv]
    exact x.2
  have hrx : r ⟨_, hyA⟩ = x := by
    refine Subtype.ext ?_
    rw [hrc]
    exact galSubHom_kerGalEquiv hKker _
  have hval := hg ⟨_, hyA⟩
  simp only [MonoidHom.comp_apply] at hval
  rwa [hrx] at hval

end Level

end InverseGalois.Shafarevich
