/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.CharPlace
import InverseGalois.CFT.Profinite.Trivial
import InverseGalois.Solvable.Shafarevich.CharacterProduct
import InverseGalois.Solvable.Shafarevich.ElementaryQuotientDecomposition

/-!
# A homomorphism of the kernel assembled out of units of a level

The prescription of the repair is a homomorphism of the kernel of the base realization into a layer,
and the kernel of the base realization is the group of automorphisms over the level the base
realization cuts out.  Over that level Kummer theory is available: a unit of the level has an `ℓ`-th
root in the algebraic closure, and the way the automorphisms move that root is a character of the
kernel with values in the residues modulo `ℓ`.  A finite family of units, read against a finite
family of elements of the layer, therefore assembles into a homomorphism of the kernel into the
layer.

Everything the prescription asks of that homomorphism is a statement about one unit at a time.  It
is trivial at an automorphism fixing all the roots, in particular on the subgroup cutting out the
level generated by them, which is what makes it smooth; it is trivial on the decomposition subgroup
at a prime where every unit of the family is a local power; it is trivial on the inertia subgroup
at a prime away from the exponent where every unit of the family has order divisible by the
exponent; and it takes a prescribed value wherever the characters of the units take the coordinates
of that value.

## Main definitions

* `InverseGalois.Shafarevich.kerGalEquiv` — the kernel of the base realization, read as the
  automorphisms over the level it cuts out.
* `InverseGalois.Shafarevich.kummerKernelHom` — the homomorphism of the kernel assembled out of a
  family of units of the level and a family of elements of the target.

## Main results

* `InverseGalois.Shafarevich.kummerKernelHom_eq_of_forall_kummerChar_eq` — **the assembled
  homomorphism takes the value whose coordinates the characters of the units take.**
* `InverseGalois.Shafarevich.kummerKernelHom_eq_one_of_mem_stabilizer` — the assembled homomorphism
  is trivial on the decomposition subgroup at a prime where every unit is a local power.
* `InverseGalois.Shafarevich.kummerKernelHom_eq_one_of_mem_inertia` — the assembled homomorphism is
  trivial on the inertia subgroup at a prime away from the exponent where every unit has order
  divisible by the exponent.
* `InverseGalois.Shafarevich.isSmooth₁_kummerKernelHom` — **the assembled homomorphism is smooth.**

## Tags

Shafarevich's theorem, embedding problem, Kummer theory, character, level, smooth cochain
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1600000

/-! ### The kernel of the base realization as the automorphisms over the level -/

section Equiv

variable {k Ω U : Type*} [Field k] [Field Ω] [Algebra k Ω] [Group U] {φ : Gal(Ω/k) →* U}
  {K : IntermediateField k Ω}

/-- **The kernel of the base realization, read as the automorphisms over the level it cuts out.** -/
def kerGalEquiv (hKker : K.fixingSubgroup = φ.ker) : ↥φ.ker ≃* Gal(Ω/↥K) :=
  (MulEquiv.subgroupCongr hKker).symm.trans (IntermediateField.fixingSubgroupEquiv K)

/-- Reading an element of the kernel of the base realization as an automorphism over the level and
back gives the element one started from. -/
theorem galSubHom_kerGalEquiv (hKker : K.fixingSubgroup = φ.ker) (y : ↥φ.ker) :
    galSubHom K (kerGalEquiv hKker y) = (y : Gal(Ω/k)) := by
  rw [kerGalEquiv, show ((MulEquiv.subgroupCongr hKker).symm.trans
      (IntermediateField.fixingSubgroupEquiv K)) y
      = IntermediateField.fixingSubgroupEquiv K ((MulEquiv.subgroupCongr hKker).symm y) from rfl,
    ← coe_fixingSubgroupEquiv_symm, (IntermediateField.fixingSubgroupEquiv K).symm_apply_apply]
  rfl

end Equiv

/-! ### The homomorphism assembled out of a family of units -/

section Hom

variable {ℓ : ℕ} [NeZero ℓ] {k Ω U : Type} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  [Group U] {φ : Gal(Ω/k) →* U} {K : IntermediateField k Ω} [NumberField ↥K]
  {ζ : ↥K} {hζ : IsPrimitiveRoot ζ ℓ}

attribute [local instance] zmodTrivialAction

variable (hKker : K.fixingSubgroup = φ.ker)
  (h : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)
  {M : Type*} [CommGroup M] {d : ℕ} (b : Fin d → M) (hb : ∀ t, b t ^ ℓ = 1) (z : Fin d → (↥K)ˣ)

/-- **The homomorphism of the kernel of the base realization assembled out of a family of units of
the level and a family of elements of the target**: the product of the powers of the elements by
the Kummer characters of the units. -/
noncomputable def kummerKernelHom : ↥φ.ker →* M :=
  charProd b hb (fun t y => kummerChar h (z t) (kerGalEquiv hKker y))
    (fun t x y => by
      show kummerChar h (z t) (kerGalEquiv hKker (x * y))
        = kummerChar h (z t) (kerGalEquiv hKker x) + kummerChar h (z t) (kerGalEquiv hKker y)
      rw [_root_.map_mul, kummerChar_mul])

omit [NumberField ↥K] in
/-- The assembled homomorphism is the product of the powers of the elements of the family by the
Kummer characters of the units. -/
theorem kummerKernelHom_apply (y : ↥φ.ker) :
    kummerKernelHom hKker h b hb z y
      = ∏ t, b t ^ (kummerChar h (z t) (kerGalEquiv hKker y)).val :=
  charProd_apply y

omit [NumberField ↥K] in
/-- The assembled homomorphism is trivial wherever every Kummer character vanishes. -/
theorem kummerKernelHom_eq_one {y : ↥φ.ker}
    (hy : ∀ t, kummerChar h (z t) (kerGalEquiv hKker y) = 0) :
    kummerKernelHom hKker h b hb z y = 1 :=
  charProd_eq_one hy

omit [NumberField ↥K] in
/-- **The assembled homomorphism takes the value whose coordinates the Kummer characters of the
units take.** -/
theorem kummerKernelHom_eq_of_forall_kummerChar_eq {χ : Fin d → M → ZMod ℓ}
    (hχ : ∀ m : M, ∏ t, b t ^ (χ t m).val = m) {y : ↥φ.ker} {m : M}
    (hy : ∀ t, kummerChar h (z t) (kerGalEquiv hKker y) = χ t m) :
    kummerKernelHom hKker h b hb z y = m := by
  rw [kummerKernelHom_apply]
  simp only [hy]
  exact hχ m

omit [NumberField ↥K] in
/-- The assembled homomorphism is trivial at an automorphism fixing an `ℓ`-th root of every unit of
the family. -/
theorem kummerKernelHom_eq_one_of_forall_smul_root_eq {y : ↥φ.ker}
    (hy : ∀ t, ∀ β : Ωˣ, β ^ ℓ = Units.map (algebraMap ↥K Ω : ↥K →* Ω) (z t) →
      (y : Gal(Ω/k)) • β = β) :
    kummerKernelHom hKker h b hb z y = 1 := by
  refine kummerKernelHom_eq_one hKker h b hb z fun t => ?_
  refine (kummerChar_eq_zero_iff_smul_root_eq h (z t) _).2 ?_
  rw [← smul_units_galSubHom K, galSubHom_kerGalEquiv]
  exact hy t _ (h.root_pow (z t))

/-- The assembled homomorphism is trivial on the decomposition subgroup at a prime where every unit
of the family is a local power. -/
theorem kummerKernelHom_eq_one_of_mem_stabilizer {P : Ideal (𝓞 Ω)} [P.IsPrime]
    {w : HeightOneSpectrum (𝓞 ↥K)} (hw : w.asIdeal = Ideal.under (𝓞 ↥K) P)
    (hloc : ∀ t, localClassHom w ℓ (z t) = 1) {y : ↥φ.ker}
    (hy : (y : Gal(Ω/k)) ∈ stabilizer Gal(Ω/k) P) :
    kummerKernelHom hKker h b hb z y = 1 := by
  refine kummerKernelHom_eq_one hKker h b hb z fun t => ?_
  refine kummerChar_eq_zero_of_mem_stabilizer h hw (hloc t) ?_
  rw [← mem_stabilizer_galSubHom_iff K, galSubHom_kerGalEquiv]
  exact hy

/-- The assembled homomorphism is trivial on the inertia subgroup at a prime away from the exponent
where every unit of the family has order at the place below divisible by the exponent. -/
theorem kummerKernelHom_eq_one_of_mem_inertia (hℓ : ℓ.Prime) {P : Ideal (𝓞 Ω)} [P.IsPrime]
    (hℓP : (ℓ : 𝓞 Ω) ∉ P) {w : HeightOneSpectrum (𝓞 ↥K)}
    (hw : w.asIdeal = Ideal.under (𝓞 ↥K) P) (hord : ∀ t, (ℓ : ℤ) ∣ placeValue w (z t))
    {y : ↥φ.ker} (hy : (y : Gal(Ω/k)) ∈ Ideal.inertia Gal(Ω/k) P) :
    kummerKernelHom hKker h b hb z y = 1 := by
  refine kummerKernelHom_eq_one hKker h b hb z fun t => ?_
  refine kummerChar_eq_zero_of_mem_inertia h hℓ hℓP hw (hord t) ?_
  rw [← mem_inertia_galSubHom_iff K, galSubHom_kerGalEquiv]
  exact hy

end Hom

/-! ### Smoothness -/

section Smooth

variable {ℓ : ℕ} [NeZero ℓ] {k Ω U : Type} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  [Group U] {φ : Gal(Ω/k) →* U} {K : IntermediateField k Ω}
  [FiniteDimensional k ↥K] {ζ : ↥K} {hζ : IsPrimitiveRoot ζ ℓ}

attribute [local instance] zmodTrivialAction

variable (hKker : K.fixingSubgroup = φ.ker)
  (h : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)
  {M : Type*} [CommGroup M] {d : ℕ} (b : Fin d → M) (hb : ∀ t, b t ^ ℓ = 1) (z : Fin d → (↥K)ˣ)

/-- **The assembled homomorphism is smooth**: it is trivial on the subgroup cutting out the finite
level generated by the level itself and the chosen roots of the units of the family. -/
theorem isSmooth₁_kummerKernelHom :
    IsSmooth₁ (kummerKernelHom hKker h b hb z : ↥φ.ker → M) := by
  classical
  set rts : Set Ω := Set.range fun t : Fin d => ((h.root (z t) : Ωˣ) : Ω) with hrts
  haveI : Finite ↥rts := by rw [hrts]; exact (Set.finite_range _).to_subtype
  haveI : FiniteDimensional k ↥(IntermediateField.adjoin k rts) :=
    IntermediateField.finiteDimensional_adjoin fun x _ => Algebra.IsIntegral.isIntegral x
  set W : IntermediateField k Ω := normalClosure k ↥(K ⊔ IntermediateField.adjoin k rts) Ω with hW
  haveI : FiniteDimensional k ↥W := by rw [hW]; infer_instance
  haveI : Normal k ↥W := by rw [hW]; infer_instance
  have hWle : W.fixingSubgroup ≤ φ.ker := by
    rw [← hKker]
    exact IntermediateField.fixingSubgroup_le
      (le_trans le_sup_left (IntermediateField.le_normalClosure _))
  have hrle : rts ⊆ (W : Set Ω) := fun x hx =>
    le_trans le_sup_right (IntermediateField.le_normalClosure _)
      (IntermediateField.subset_adjoin k rts hx)
  have hWon : IsOpenNormal W.fixingSubgroup := isOpenNormal_fixingSubgroup W
  refine isSmooth₁_of_ker_le (N := W.fixingSubgroup.subgroupOf φ.ker)
    ⟨hWon.normal.subgroupOf φ.ker, isOpen_subgroupOf hWon.isOpen⟩ fun y hy => ?_
  refine MonoidHom.mem_ker.2 (kummerKernelHom_eq_one hKker h b hb z fun t => ?_)
  refine (kummerChar_eq_zero_iff_smul_root_eq h (z t) _).2 (Units.ext ?_)
  show galSubHom K (kerGalEquiv hKker y) ((h.root (z t) : Ωˣ) : Ω) = ((h.root (z t) : Ωˣ) : Ω)
  rw [galSubHom_kerGalEquiv]
  exact (IntermediateField.mem_fixingSubgroup_iff _ _).1 (Subgroup.mem_subgroupOf.1 hy) _
    (hrle (by rw [hrts]; exact ⟨t, rfl⟩))

end Smooth

end InverseGalois.Shafarevich
