/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Profinite.Symbol
import InverseGalois.Solvable.Shafarevich.KernelClauses

/-!
# Where only one coordinate survives, the values are cyclic

The confinement clause of the prescription asks, at a prime the prescribed homomorphism itself
brings in, that its values along the decomposition subgroup there all be powers of a single one.
For a homomorphism assembled out of a family of units that is a statement about the family: at a
place where every unit but one is a local power, only one coordinate of the product survives, so
every value is a power of the one element of the target that coordinate reads against, and the
residues modulo a prime are generated by any nonzero one of them.

Nothing but that is used, so the statement is made for an arbitrary product of powers of a fixed
family by the values of arbitrary functions into the residues, and then read off for the
homomorphism assembled out of units by way of the vanishing of the Kummer characters of the units
which are local powers.

## Main results

* `InverseGalois.Shafarevich.exists_forall_mem_zpowers_of_prod_pow` — a product of powers of a
  fixed family takes, on a subgroup all but one of whose coordinates vanish, values which are all
  powers of one of them.
* `InverseGalois.Shafarevich.exists_forall_mem_zpowers_kummerKernelHom` — **the homomorphism
  assembled out of a family of units takes, on the decomposition subgroup at a prime where all but
  one unit of the family is a local power, values which are all powers of one of them.**

## Tags

Shafarevich's theorem, embedding problem, decomposition group, cyclic, Kummer theory
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

set_option maxHeartbeats 1600000

/-! ### A single surviving coordinate -/

section Prod

variable {G : Type*} [Group G] {V : Type*} [CommGroup V] {ℓ : ℕ} [NeZero ℓ] {ι : Type*}
  [Fintype ι]

omit [NeZero ℓ] in
/-- **A product of powers of a fixed family takes, on a subgroup all but one of whose coordinates
vanish, values which are all powers of one of them.**  Only the surviving coordinate contributes,
and a nonzero residue modulo a prime generates all of them; if the surviving coordinate vanishes
too then every value is trivial. -/
theorem exists_forall_mem_zpowers_of_prod_pow (hℓ : ℓ.Prime) {v : ι → V} {i₀ : ι}
    (hv : v i₀ ^ ℓ = 1) {f : ι → G → ZMod ℓ} {u : G → V}
    (hu : ∀ x, u x = ∏ i, v i ^ (f i x).val) {H : Subgroup G}
    (h : ∀ x ∈ H, ∀ i, i ≠ i₀ → f i x = 0) :
    ∃ x₀ ∈ H, ∀ x ∈ H, u x ∈ Subgroup.zpowers (u x₀) := by
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  have hsingle : ∀ x ∈ H, u x = v i₀ ^ (f i₀ x).val := by
    intro x hx
    rw [hu]
    refine Finset.prod_eq_single i₀ (fun i _ hi => ?_) (fun hi => absurd (Finset.mem_univ i₀) hi)
    rw [h x hx i hi, ZMod.val_zero, pow_zero]
  by_cases hex : ∃ x₀ ∈ H, f i₀ x₀ ≠ 0
  · obtain ⟨x₀, hx₀H, hx₀⟩ := hex
    refine ⟨x₀, hx₀H, fun x hx => ?_⟩
    obtain ⟨m, hm⟩ : ∃ m : ZMod ℓ, f i₀ x = m * f i₀ x₀ :=
      ⟨f i₀ x * (f i₀ x₀)⁻¹, by field_simp⟩
    have hval : (f i₀ x).val = m.val * (f i₀ x₀).val % ℓ := by rw [hm, ZMod.val_mul]
    refine ⟨(m.val : ℤ), ?_⟩
    show u x₀ ^ (m.val : ℤ) = u x
    rw [zpow_natCast, hsingle x₀ hx₀H, hsingle x hx, ← pow_mul, hval,
      pow_mod_of_pow_eq_one hv, Nat.mul_comm (f i₀ x₀).val m.val]
  · push_neg at hex
    refine ⟨1, H.one_mem, fun x hx => ?_⟩
    rw [hsingle x hx, hex x hx, ZMod.val_zero, pow_zero]
    exact Subgroup.one_mem _

end Prod

/-! ### The homomorphism assembled out of units -/

section Kummer

variable {ℓ : ℕ} [NeZero ℓ] {k Ω U : Type} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  [Group U] {φ : Gal(Ω/k) →* U} {K : IntermediateField k Ω} [NumberField ↥K]
  {ζ : ↥K} {hζ : IsPrimitiveRoot ζ ℓ}

attribute [local instance] zmodTrivialAction

variable (hKker : K.fixingSubgroup = φ.ker)
  (hkd : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)
  {M : Type*} [CommGroup M] {d : ℕ} (b : Fin d → M) (hb : ∀ t, b t ^ ℓ = 1) (z : Fin d → (↥K)ˣ)

/-- **The homomorphism assembled out of a family of units takes, on the decomposition subgroup at a
prime where all but one unit of the family is a local power, values which are all powers of one of
them.**  The Kummer characters of the units which are local powers vanish on the decomposition
subgroup, so only one coordinate of the product survives there. -/
theorem exists_forall_mem_zpowers_kummerKernelHom (hℓ : ℓ.Prime) {P : Ideal (𝓞 Ω)} [P.IsPrime]
    {w : HeightOneSpectrum (𝓞 ↥K)} (hw : w.asIdeal = Ideal.under (𝓞 ↥K) P) {i₀ : Fin d}
    (hloc : ∀ t, t ≠ i₀ → localClassHom w ℓ (z t) = 1) :
    ∃ y₀ : ↥φ.ker, (y₀ : Gal(Ω/k)) ∈ stabilizer Gal(Ω/k) P ∧
      ∀ y : ↥φ.ker, (y : Gal(Ω/k)) ∈ stabilizer Gal(Ω/k) P →
        kummerKernelHom hKker hkd b hb z y ∈
          Subgroup.zpowers (kummerKernelHom hKker hkd b hb z y₀) := by
  have hvan : ∀ y ∈ (stabilizer Gal(Ω/k) P).subgroupOf φ.ker, ∀ t, t ≠ i₀ →
      kummerChar hkd (z t) (kerGalEquiv hKker y) = 0 := by
    intro y hy t ht
    refine kummerChar_eq_zero_of_mem_stabilizer hkd hw (hloc t ht) ?_
    rw [← mem_stabilizer_galSubHom_iff, galSubHom_kerGalEquiv]
    exact Subgroup.mem_subgroupOf.1 hy
  obtain ⟨y₀, hy₀, hgen⟩ := exists_forall_mem_zpowers_of_prod_pow (v := b) (i₀ := i₀) hℓ (hb i₀)
    (u := kummerKernelHom hKker hkd b hb z) (kummerKernelHom_apply hKker hkd b hb z) hvan
  exact ⟨y₀, Subgroup.mem_subgroupOf.1 hy₀,
    fun y hy => hgen y (Subgroup.mem_subgroupOf.2 hy)⟩

end Kummer

end InverseGalois.Shafarevich
