/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.PCentralFrattini
import InverseGalois.Solvable.Shafarevich.LayerExtension

/-!
# Above the first layer a lift is onto for nothing

A solution of an embedding problem is asked to be onto, and carrying one up the filtration one
layer at a time raises the question at every rung.  Past the first rung it costs nothing.  The
layer sits inside the subgroup generated by the `p`-th powers and the commutators, which for a
finite `p`-group lies in the Frattini subgroup, and the Frattini subgroup is by definition
non-generating: a subgroup which together with it generates the whole group is already the whole
group.  A lift over a surjection therefore generates the group one layer up together with the
layer, hence generates it outright.

The operator group carried alongside does not disturb this.  What has to be supplemented is only
the normal factor, the layer being a subgroup of it, so the Frattini subgroup used is that of the
normal factor, and the operator group is never asked to be a `p`-group.

## Main results

* `InverseGalois.Shafarevich.pCentral_eq_lowerPCentralSeries` — the descending `p`-central series
  used here is the lower `p`-central series.
* `InverseGalois.Shafarevich.layerSub_le_frattini` — **past the first, a layer lies in the Frattini
  subgroup of the quotient it sits in.**
* `InverseGalois.Shafarevich.eq_top_of_sup_le_map_frattini` — a subgroup supplemented by the image
  of a non-generating subgroup is everything.
* `InverseGalois.Shafarevich.sup_range_inl_eq_top` — a homomorphism onto the quotient of an
  extension generates the extension together with its kernel.
* `InverseGalois.Shafarevich.surjective_of_rightHom_comp_surjective` — **past the first layer, a
  lift over a surjection is itself a surjection.**

## Tags

Shafarevich's theorem, embedding problem, Frattini subgroup, p-central series, group extension
-/

namespace InverseGalois.Shafarevich

open InverseGalois

open scoped Pointwise

/-! ### The two descending `p`-central series agree -/

/-- **The descending `p`-central series is the lower `p`-central series.**  Both are built from the
`p`-th powers and the commutators of the previous term, in the other order. -/
theorem pCentral_eq_lowerPCentralSeries (p : ℕ) (P : Type*) [Group P] (n : ℕ) :
    pCentral p P n = lowerPCentralSeries p P n := by
  induction n with
  | zero => rfl
  | succ n ih => rw [pCentral_succ, lowerPCentralSeries_succ, ih, powSubgroup, sup_comm]

/-! ### A layer lies in the Frattini subgroup -/

/-- **The first term of the descending `p`-central series of a finite `p`-group lies in its
Frattini subgroup.** -/
theorem pCentral_one_le_frattini {p : ℕ} [Fact p.Prime] {P : Type*} [Group P] [Finite P]
    (hP : IsPGroup p P) : pCentral p P 1 ≤ frattini P := by
  rw [pCentral_eq_lowerPCentralSeries]
  exact lowerPCentralSeries_one_le_frattini hP

/-- **Every term of the descending `p`-central series of a finite `p`-group past the zeroth lies in
its Frattini subgroup.** -/
theorem pCentral_le_frattini {p : ℕ} [Fact p.Prime] {P : Type*} [Group P] [Finite P]
    (hP : IsPGroup p P) {n : ℕ} (hn : 1 ≤ n) : pCentral p P n ≤ frattini P :=
  (pCentral_le_pCentral p hn).trans (pCentral_one_le_frattini hP)

/-- **Past the first, a layer of the descending `p`-central series lies in the Frattini subgroup of
the quotient it sits in.**  The layer is the image of a term of the series past the zeroth, and a
surjection carries the series onto the series. -/
theorem layerSub_le_frattini {p : ℕ} [Fact p.Prime] {P : Type*} [Group P] [Finite P]
    (hP : IsPGroup p P) {n : ℕ} (hn : 1 ≤ n) :
    layerSub p P n ≤ frattini (P ⧸ pCentral p P (n + 1)) := by
  rw [layerSub, map_pCentral p (QuotientGroup.mk' (pCentral p P (n + 1)))
    (QuotientGroup.mk'_surjective _) n]
  exact pCentral_le_frattini (hP.to_quotient _) hn

/-! ### Supplementing by a non-generating subgroup -/

/-- **A subgroup supplemented by the image of a non-generating subgroup is everything.**  Pulling
the supplement back along the homomorphism supplements the non-generating subgroup upstairs, so the
pullback is everything, the image of the homomorphism lies in the subgroup, and with it the
supplement itself. -/
theorem eq_top_of_sup_le_map_frattini {Q G : Type*} [Group Q] [Finite Q] [Group G] (ι : Q →* G)
    {N : Subgroup Q} (hN : N ≤ frattini Q) {K : Subgroup G} (hnorm : K.Normal)
    (hK : K ≤ N.map ι) {H : Subgroup G} (hsup : H ⊔ K = ⊤) : H = ⊤ := by
  haveI := hnorm
  -- the pullback of `H` supplements `N` upstairs
  have hcomap : H.comap ι ⊔ N = ⊤ := by
    refine eq_top_iff.2 fun q _ => ?_
    have hmem : ι q ∈ (H : Set G) * (K : Set G) := by
      rw [← Subgroup.mul_normal, hsup, Subgroup.coe_top]
      exact Set.mem_univ _
    obtain ⟨a, ha, b, hb, hab⟩ := hmem
    obtain ⟨m, hm, rfl⟩ := Subgroup.mem_map.1 (hK hb)
    have hqm : q * m⁻¹ ∈ H.comap ι := by
      refine Subgroup.mem_comap.2 ?_
      rw [_root_.map_mul, _root_.map_inv, ← hab]
      simpa using ha
    have hq := Subgroup.mul_mem_sup hqm hm
    rwa [inv_mul_cancel_right] at hq
  -- so the pullback is everything, the non-generating subgroup being non-generating
  have htop : H.comap ι = ⊤ :=
    frattini_nongenerating (eq_top_iff.2 (hcomap.ge.trans (sup_le_sup_left hN _)))
  refine eq_top_iff.2 ?_
  rw [← hsup]
  exact sup_le le_rfl (hK.trans (Subgroup.map_le_iff_le_comap.2 (by rw [htop]; exact le_top)))

/-! ### A lift generates the extension together with its kernel -/

/-- **A homomorphism onto the quotient of an extension generates the extension together with its
kernel.**  Any element of the extension differs from a value of the homomorphism by an element
which the projection kills. -/
theorem sup_range_inl_eq_top {N E G : Type*} [Group N] [Group E] [Group G]
    (S : GroupExtension N E G) {Γ : Type*} [Group Γ] (f : Γ →* E)
    (hsurj : Function.Surjective (S.rightHom.comp f)) : f.range ⊔ S.inl.range = ⊤ := by
  refine eq_top_iff.2 fun e _ => ?_
  obtain ⟨γ, hγ⟩ := hsurj (S.rightHom e)
  have hker : (f γ)⁻¹ * e ∈ S.inl.range := by
    rw [S.range_inl_eq_ker_rightHom, MonoidHom.mem_ker, _root_.map_mul, _root_.map_inv,
      show S.rightHom (f γ) = S.rightHom e from hγ, inv_mul_cancel]
  have he := Subgroup.mul_mem_sup (f.mem_range.2 ⟨γ, rfl⟩) hker
  rwa [mul_inv_cancel_left] at he

/-! ### Properness of a lift past the first layer -/

/-- **Past the first layer, a lift over a surjection is itself a surjection.**  The lift generates
the group one layer up together with the layer, the layer lies in the Frattini subgroup of the
normal factor, and a subgroup supplemented by a non-generating subgroup is everything. -/
theorem surjective_of_rightHom_comp_surjective (p : ℕ) [Fact p.Prime] {P U : Type*} [Group P]
    [Finite P] [Group U] (hP : IsPGroup p P) (χ : U →* MulAut P) {j : ℕ} (hj : 1 ≤ j) {Γ : Type*}
    [Group Γ] (f : Γ →* (P ⧸ pCentral p P (j + 1)) ⋊[pCentralAut p χ (j + 1)] U)
    (hsurj : Function.Surjective ((layerExtension p χ j).rightHom.comp f)) :
    Function.Surjective f := by
  rw [← MonoidHom.range_eq_top]
  refine eq_top_of_sup_le_map_frattini (SemidirectProduct.inl) (layerSub_le_frattini hP hj)
    (K := (layerExtension p χ j).inl.range) ?_ ?_ (sup_range_inl_eq_top _ f hsurj)
  · rw [(layerExtension p χ j).range_inl_eq_ker_rightHom]
    exact MonoidHom.normal_ker _
  · rintro _ ⟨v, rfl⟩
    exact ⟨(v : P ⧸ pCentral p P (j + 1)), v.2, rfl⟩

end InverseGalois.Shafarevich
