/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Profinite.LiftTwist
import InverseGalois.Solvable.Shafarevich.LevelTwist

/-!
# The lift made trivial along the family, by a third shrinking

A solution at one level of the descending `ℓ`-central series lifts to the next once the everywhere
locally trivial classes of the layer are killed by a shrinking, and the lift produced is smooth,
onto and over the base realization.  What it is not yet is trivial along the family of
subgroups the local conditions name.  Along a member of the family where the base realization is
trivial the lift takes its values in the layer, where it is a homomorphism; so the whole of the
discrepancy is a finite family of homomorphisms from those subgroups into the layer, and killing
them is all that separates the lift from a solution at the next level.

They can be killed by the count, and that is what the arithmetic is spared.  A homomorphism from one
of the subgroups into a commutative group killed by `ℓ` factors through the largest quotient of that
shape, and for a decomposition subgroup that quotient is finite, of an order settled by the local
field alone.  So the number of values the discrepancies take is fixed before any solution is chosen,
the count asks for a number of letters depending on that number alone, and a shrinking down to the
intended number of letters carries every one of those values to one.  The pushed down lift is then
trivial along the family, and nothing else about it has changed.

## Main definitions

* `InverseGalois.Shafarevich.HasFiniteElementaryQuotient` — **a subgroup whose smooth homomorphisms
  into commutative groups killed by `ℓ` all factor through one finite quotient.**

## Main results

* `InverseGalois.Shafarevich.pow_eq_one_layerSub` — a layer is killed by `ℓ`.
* `InverseGalois.Shafarevich.hasFiniteElementaryQuotient_of_le` — a normal subgroup of finite index
  lying inside the subgroup generated by the commutators and the `ℓ`-th powers gives such a
  quotient.
* `InverseGalois.Shafarevich.exists_lift_eq_one_of_levelSolution` — **a solution at one level gives
  a lift at the next which is trivial along the family**, granted that every everywhere locally
  trivial class of the layer is killed by a shrinking and that the members of the family have
  finite elementary quotients.
* `InverseGalois.Shafarevich.levelSolution_succ_of_hasFiniteElementaryQuotient` — **and hence one
  whole rung of the ladder, with nothing asked of the first cohomology.**

## Tags

Shafarevich's theorem, embedding problem, p-central series, local conditions, decomposition group
-/

universe u

namespace InverseGalois.Shafarevich

open InverseGalois.CFT

attribute [local instance] genericQuotAction

/-! ### A layer is killed by the prime -/

/-- **A layer of the descending `ℓ`-central series is killed by `ℓ`.** -/
theorem pow_eq_one_layerSub {ℓ : ℕ} {P : Type*} [Group P] {j : ℕ} (v : ↥(layerSub ℓ P j)) :
    v ^ ℓ = 1 :=
  Subtype.ext (by simpa using pow_eq_one_of_mem_layerSub v.2)

/-! ### Subgroups with a finite elementary quotient -/

/-- **A subgroup whose smooth homomorphisms into commutative groups killed by `ℓ` all factor
through one finite quotient.**

The quotient is asked for once and for all, before any coefficients are named, and that is the
whole point of the condition: it bounds, in advance, how many values such a homomorphism can take.
For the decomposition subgroup at a place of a number field the quotient is the largest elementary
abelian `ℓ`-quotient of the Galois group of the local field, which local class field theory makes
finite. -/
def HasFiniteElementaryQuotient (ℓ : ℕ) {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    (D : Subgroup Γ) : Prop :=
  ∃ (Q : Type u) (_ : Group Q) (_ : Finite Q) (q : ↥D →* Q),
    ∀ (M : Type) [CommGroup M], (∀ y : M, y ^ ℓ = 1) → ∀ a : ↥D →* M,
      IsSmooth₁ (a : ↥D → M) → ∃ b : Q →* M, ∀ x : ↥D, b (q x) = a x

/-- **A normal subgroup of finite index lying inside the subgroup generated by the commutators and
the `ℓ`-th powers gives a finite elementary quotient.**  A homomorphism into a commutative group
killed by `ℓ` kills every commutator and every `ℓ`-th power, hence kills the subgroup, hence
factors through the quotient by it. -/
theorem hasFiniteElementaryQuotient_of_le (ℓ : ℕ) {Γ : Type u} [Group Γ] [TopologicalSpace Γ]
    {D : Subgroup Γ} (N : Subgroup ↥D) [N.Normal] [Finite (↥D ⧸ N)]
    (hN : N ≤ commutator ↥D ⊔ Subgroup.closure (Set.range fun x : ↥D => x ^ ℓ)) :
    HasFiniteElementaryQuotient ℓ D := by
  refine ⟨↥D ⧸ N, inferInstance, inferInstance, QuotientGroup.mk' N, ?_⟩
  intro M _ hM a _
  have hker : N ≤ a.ker := by
    refine hN.trans (sup_le ?_ ?_)
    · rw [commutator_def]
      refine Subgroup.commutator_le.2 fun x _ y _ => ?_
      rw [MonoidHom.mem_ker, _root_.map_commutatorElement, commutatorElement_eq_one_iff_mul_comm]
      exact mul_comm _ _
    · refine Subgroup.closure_le _ |>.2 ?_
      rintro _ ⟨x, rfl⟩
      rw [SetLike.mem_coe, MonoidHom.mem_ker, _root_.map_pow, hM]
  exact ⟨QuotientGroup.lift N a hker, fun x => rfl⟩

/-! ### The lift, made trivial along the family -/

/-- **A solution at one level of the filtration gives a lift at the next which is trivial along the
family.**

The lift itself is produced by the second shrinking, which kills the everywhere locally trivial
class the obstruction is.  Along a member of the family where the base realization is trivial the
solution is trivial too, so the lift lands in the layer and is a homomorphism there; the finite
elementary quotient of the member bounds the number of values it takes, and that bound is known
before the solution is chosen.  A third shrinking onto the intended number of letters therefore
carries all of those values to one at once, and the lift pushed down is trivial along the whole
family. -/
theorem exists_lift_eq_one_of_levelSolution (ℓ : ℕ) [Fact ℓ.Prime] (U : Type) [Group U]
    [Finite U] [TopologicalSpace U] [DiscreteTopology U] (n : ℕ) (S : Type) [Group S] [Finite S]
    (hS : IsPGroup ℓ S) (j : ℕ) {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]
    (φ : Gal(Ω/k) →* U) {t : ℕ} (D : Fin t → Subgroup Gal(Ω/k))
    (T : Set (Subgroup Gal(Ω/k))) (hvan : ∀ m : ℕ, HasLocalLift ℓ U m S j φ D T)
    (hsh : ∀ m : ℕ, HasShrinkableSha ℓ U m S j φ T)
    (hfin : ∀ ν : Fin t, HasFiniteElementaryQuotient ℓ (D ν ⊓ φ.ker))
    (h : ∀ m : ℕ, LevelSolution ℓ U S φ (Set.range D) m j) :
    ∃ (Φ : Gal(Ω/k) →* GenericQuot ℓ U n S j) (f : Gal(Ω/k) →* GenericQuot ℓ U n S (j + 1)),
      Function.Surjective Φ ∧ IsSmoothHom Φ ∧ (∀ x, SemidirectProduct.rightHom (Φ x) = φ x) ∧
        (∀ A ∈ Set.range D, ∀ x ∈ A, φ x = 1 → Φ x = 1) ∧ IsSmoothHom f ∧
          (∀ x, (layerExtension ℓ (genericAut U n S) j).rightHom (f x) = Φ x) ∧
            ∀ (ν : Fin t), ∀ x ∈ D ν, φ x = 1 → f x = 1 := by
  classical
  -- the finite quotients through which the discrepancies must factor, chosen in advance
  choose Q hQgroup hQfinite q hq using hfin
  letI : ∀ ν, Group (Q ν) := hQgroup
  letI : ∀ ν, Finite (Q ν) := hQfinite
  -- and hence the number of letters the third shrinking asks for, also fixed in advance
  obtain ⟨m, hm⟩ := exists_operatorHom_forall_layerSubMap_eq_one U n S hS (j := j)
    ((ν : Fin t) × Q ν)
  -- a lift at that number of letters
  obtain ⟨Φ₁, f₁, hsurj₁, hsm₁, hright₁, hloc₁, hfsm₁, hf₁⟩ :=
    exists_lift_of_levelSolution_of_hasShrinkableSha ℓ U m S hS j φ D T hvan (hsh m) h
  have hf₁s : IsSmooth₁ (f₁ : Gal(Ω/k) → GenericQuot ℓ U m S (j + 1)) :=
    isSmooth₁_of_isOpenNormal_ker (isOpenNormal_ker_of_isSmoothHom hfsm₁)
  have hDloc : ∀ ν : Fin t, ∀ x ∈ D ν ⊓ φ.ker, Φ₁ x = 1 := fun ν x hx =>
    hloc₁ (D ν) ⟨ν, rfl⟩ x (Subgroup.mem_inf.1 hx).1
      (MonoidHom.mem_ker.1 (Subgroup.mem_inf.1 hx).2)
  -- the discrepancy along each member of the family, and the values it takes
  choose a ha using fun ν : Fin t =>
    exists_hom_inl_eq (layerExtension ℓ (genericAut U m S) j) hf₁ (D ν ⊓ φ.ker) (hDloc ν)
  have hasm : ∀ ν : Fin t, IsSmooth₁ ((a ν : ↥(D ν ⊓ φ.ker) →* _) : ↥(D ν ⊓ φ.ker) → _) :=
    fun ν => isSmooth₁_of_inl_comp (layerExtension ℓ (genericAut U m S) j) (ha ν) hf₁s
  choose b hb using fun ν : Fin t => hq ν (↥(layerSub ℓ (Generic U m S) j))
    (fun y => pow_eq_one_layerSub y) (a ν) (hasm ν)
  -- the third shrinking kills every one of those values
  obtain ⟨α, hα, hαsurj, hkill⟩ := hm fun c : (ν : Fin t) × Q ν => b c.1 c.2
  refine ⟨(layerSemidirectMap ℓ hα j).comp Φ₁, (layerSemidirectMap ℓ hα (j + 1)).comp f₁,
    (layerSemidirectMap_surjective ℓ hα j hαsurj).comp hsurj₁,
    isSmoothHom_comp hsm₁ (isSmoothHom_of_continuous continuous_of_discreteTopology),
    fun x => hright₁ x, ?_,
    isSmoothHom_comp hfsm₁ (isSmoothHom_of_continuous continuous_of_discreteTopology), ?_, ?_⟩
  · rintro _ ⟨ν, rfl⟩ x hx hx1
    show layerSemidirectMap ℓ hα j (Φ₁ x) = 1
    rw [hloc₁ (D ν) ⟨ν, rfl⟩ x hx hx1, _root_.map_one]
  · intro x
    show (layerExtension ℓ (genericAut U n S) j).rightHom
      (layerSemidirectMap ℓ hα (j + 1) (f₁ x)) = layerSemidirectMap ℓ hα j (Φ₁ x)
    rw [rightHom_layerSemidirectMap ℓ j hα, hf₁ x]
  · intro ν x hx hx1
    have hxm : x ∈ D ν ⊓ φ.ker := Subgroup.mem_inf.2 ⟨hx, MonoidHom.mem_ker.2 hx1⟩
    show layerSemidirectMap ℓ hα (j + 1) (f₁ x) = 1
    rw [← ha ν ⟨x, hxm⟩, inl_layerSemidirectMap ℓ j hα, ← hb ν ⟨x, hxm⟩,
      hkill ⟨ν, q ν ⟨x, hxm⟩⟩, _root_.map_one]

/-! ### One rung -/

/-- **One whole rung of the ladder, with nothing asked of the first cohomology.**  The lift produced
is already trivial along the family, so it is itself a solution at the next level: past the first
layer a lift over a surjection is again a surjection, the layer generating nothing. -/
theorem levelSolution_succ_of_hasFiniteElementaryQuotient (ℓ : ℕ) [Fact ℓ.Prime] (U : Type)
    [Group U] [Finite U] [TopologicalSpace U] [DiscreteTopology U] (n : ℕ) (S : Type) [Group S]
    [Finite S] (hS : IsPGroup ℓ S) {j : ℕ} (hj : 1 ≤ j) {k Ω : Type*} [Field k] [Field Ω]
    [Algebra k Ω] (φ : Gal(Ω/k) →* U) {t : ℕ}
    (D : Fin t → Subgroup Gal(Ω/k)) (T : Set (Subgroup Gal(Ω/k)))
    (hvan : ∀ m : ℕ, HasLocalLift ℓ U m S j φ D T)
    (hsh : ∀ m : ℕ, HasShrinkableSha ℓ U m S j φ T)
    (hfin : ∀ ν : Fin t, HasFiniteElementaryQuotient ℓ (D ν ⊓ φ.ker))
    (h : ∀ m : ℕ, LevelSolution ℓ U S φ (Set.range D) m j) :
    LevelSolution ℓ U S φ (Set.range D) n (j + 1) := by
  obtain ⟨Φ, f, hsurj, -, hright, -, hfsm, hf, hloc⟩ :=
    exists_lift_eq_one_of_levelSolution ℓ U n S hS j φ D T hvan hsh hfin h
  have hcomp :
      Function.Surjective ((layerExtension ℓ (genericAut U n S) j).rightHom.comp f) := by
    intro y
    obtain ⟨x, hx⟩ := hsurj y
    exact ⟨x, (hf x).trans hx⟩
  refine ⟨f, surjective_of_rightHom_comp_surjective ℓ (isPGroup_generic U n S hS)
    (genericAut U n S) hj f hcomp, hfsm, fun x => ?_, ?_⟩
  · have hproj : SemidirectProduct.rightHom (f x)
        = SemidirectProduct.rightHom
            ((layerExtension ℓ (genericAut U n S) j).rightHom (f x)) := rfl
    rw [hproj, hf x, hright x]
  · rintro _ ⟨ν, rfl⟩ x hx hx1
    exact hloc ν x hx hx1

end InverseGalois.Shafarevich
