/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Shafarevich.LevelObstruction

/-!
# The ramification a solution of the ladder is asked to carry

A solution at one level of the descending `ℓ`-central series is asked, beyond being a smooth
surjection over the base realization and trivial along the finite family, to carry a property; and
the property the arithmetic needs is a restriction on where the field it cuts out ramifies.  Without
it the step to the next level is not locally solvable: at a prime where the field ramifies over the
field the base realization cuts out, the local group of the base is whatever it happens to be, and
an extension of it by the layer has no reason to exist, the local field having a bounded supply of
roots of unity.

The restriction asked is the one a root of a uniformizer supplies.  A prime at which the field
ramifies over the base field must be a prime which splits completely in the base field, and over
which the local extension is cyclic and totally ramified.  There the local group is generated by
one element which is inertia, the local field contains the roots of unity the layer needs because
the base field does, and adjoining a further root of a uniformizer produces the local lift.

The property is stated over the primes of the ring of integers of the whole extension, not over the
places of a finite level, so that no level has to be named: a prime of the big ring has a
decomposition subgroup and an inertia subgroup inside the whole Galois group, and the two subgroups
are all the property mentions.

## Main definitions

* `InverseGalois.Shafarevich.IsSplitTotallyRamified` — **at a prime where the solution ramifies
  over the base realization, the base realization splits completely and the solution is cyclic and
  totally ramified.**

## Main results

* `InverseGalois.Shafarevich.IsSplitTotallyRamified.comp` — the restriction is inherited by the
  image of a solution under any homomorphism.
* `InverseGalois.Shafarevich.isSplitTotallyRamified_of_ker_le` — a solution which is trivial
  wherever the base realization is carries the restriction, there being nothing to check.
* `InverseGalois.Shafarevich.isShrinkStable_isSplitTotallyRamified` — **a shrinking does not
  destroy the restriction**, so it can be carried up the whole ladder.
* `InverseGalois.Shafarevich.levelSolution_zero_isSplitTotallyRamified` — **the bottom of the ladder
  carries the restriction**, the base realization being a solution there.

## Tags

Shafarevich's theorem, embedding problem, ramification, inertia subgroup, decomposition group
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT MulAction NumberField

open scoped Pointwise

section Property

variable (ℓ : ℕ) (U : Type) [Group U] (S : Type) [Group S] {k Ω : Type*} [Field k] [Field Ω]
  [Algebra k Ω]

/-- **At a prime where the solution ramifies over the base realization, the base realization
splits completely there and the solution is cyclic and totally ramified.**

The three clauses are read off the two subgroups a prime of the ring of integers of the whole
extension carries: its stabiliser, which is the decomposition subgroup, and its inertia subgroup,
the automorphisms acting trivially on the residue ring.  Ramifying over the base realization is
having an element of inertia which the base realization kills and the solution does not; splitting
completely is the base realization killing the whole decomposition subgroup; being totally ramified
is the solution taking no value on the decomposition subgroup which it does not already take on
inertia; and being cyclic is asked in the form that bounds it, the values on the decomposition
subgroup lying in the powers of a single element. -/
def IsSplitTotallyRamified (φ : Gal(Ω/k) →* U) : LevelProperty ℓ U S k Ω := fun _ _ Φ =>
  ∀ P : Ideal (𝓞 Ω), P.IsPrime → P ≠ ⊥ →
    (∃ x ∈ Ideal.inertia Gal(Ω/k) P, φ x = 1 ∧ Φ x ≠ 1) →
      (∀ x ∈ stabilizer Gal(Ω/k) P, φ x = 1) ∧
        (∀ x ∈ stabilizer Gal(Ω/k) P, ∃ y ∈ Ideal.inertia Gal(Ω/k) P, Φ x = Φ y) ∧
          ∃ c, ∀ x ∈ stabilizer Gal(Ω/k) P, Φ x ∈ Subgroup.zpowers c

variable {ℓ U S}

/-- **The restriction is inherited by the image of a solution under any homomorphism.**  Every
clause is a statement about the values the solution takes, and following a homomorphism can only
identify values: a prime where the image ramifies is a prime where the solution already ramified,
and there the three clauses transport one by one. -/
theorem IsSplitTotallyRamified.comp {φ : Gal(Ω/k) →* U} {m n j : ℕ}
    {Φ : Gal(Ω/k) →* GenericQuot ℓ U m S j} (h : IsSplitTotallyRamified ℓ U S φ m j Φ)
    (g : GenericQuot ℓ U m S j →* GenericQuot ℓ U n S j) :
    IsSplitTotallyRamified ℓ U S φ n j (g.comp Φ) := by
  rintro P hPp hPbot ⟨x, hxI, hxφ, hxg⟩
  obtain ⟨hsplit, htot, c, hc⟩ := h P hPp hPbot
    ⟨x, hxI, hxφ, fun hx => hxg (by rw [MonoidHom.comp_apply, hx, _root_.map_one])⟩
  refine ⟨hsplit, fun y hy => ?_, g c, fun y hy => ?_⟩
  · obtain ⟨z, hzI, hz⟩ := htot y hy
    exact ⟨z, hzI, by rw [MonoidHom.comp_apply, MonoidHom.comp_apply, hz]⟩
  · obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.1 (hc y hy)
    exact Subgroup.mem_zpowers_iff.2 ⟨i, by rw [← _root_.map_zpow, hi, MonoidHom.comp_apply]⟩

/-- **A solution which is trivial wherever the base realization is carries the restriction**, there
being nothing to check: no prime ramifies over the base realization at all. -/
theorem isSplitTotallyRamified_of_ker_le {φ : Gal(Ω/k) →* U} {m j : ℕ}
    {Φ : Gal(Ω/k) →* GenericQuot ℓ U m S j} (h : ∀ x, φ x = 1 → Φ x = 1) :
    IsSplitTotallyRamified ℓ U S φ m j Φ := by
  rintro P - - ⟨x, -, hxφ, hxΦ⟩
  exact absurd (h x hxφ) hxΦ

variable (ℓ U S)

/-- **A shrinking does not destroy the restriction**, so it can be carried up the whole ladder.  A
shrinking pushes a solution forward along a homomorphism of the groups the solutions take values
in, and the restriction is inherited by any such image. -/
theorem isShrinkStable_isSplitTotallyRamified (φ : Gal(Ω/k) →* U) :
    IsShrinkStable ℓ U S (IsSplitTotallyRamified ℓ U S φ) :=
  fun _ _ _ _ hα _ hΨ => hΨ.comp (layerSemidirectMap ℓ hα _)

end Property

section Bottom

variable (ℓ : ℕ) (U : Type) [Group U] [TopologicalSpace U] [DiscreteTopology U] (S : Type)
  [Group S] {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- **At the bottom of the ladder the restriction is carried for nothing.**  The solution at the
zeroth level is the base realization read in the group at that level, so it is trivial wherever the
base realization is and no prime ramifies over the base realization at all. -/
theorem levelSolution_zero_isSplitTotallyRamified (φ : Gal(Ω/k) →* U)
    (hsurj : Function.Surjective φ) (hsm : IsSmoothHom φ) (T : Set (Subgroup Gal(Ω/k))) (m : ℕ) :
    LevelSolution ℓ U S φ T (IsSplitTotallyRamified ℓ U S φ) m 0 :=
  levelSolution_zero ℓ U S φ hsurj hsm T _ m
    (isSplitTotallyRamified_of_ker_le fun x hx => by
      show (pCentralZeroEquiv ℓ (genericAut U m S)).symm (φ x) = 1
      rw [hx, _root_.map_one])

end Bottom

end InverseGalois.Shafarevich
