/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Residue.Decomposition
import InverseGalois.Solvable.Shafarevich.LevelRamification

/-!
# The step is locally solvable wherever the solution is unramified

Of the three things the ladder asks of the arithmetic at every rung, the first is that the step to
the next level have a local solution along every decomposition subgroup the finite family does not
name.  The docstring of that condition already divides the primes it ranges over into two kinds:
those at which the field the solution cuts out is unramified, and those at which it ramifies, which
by the property the solutions carry are primes where the base field splits completely and the
solution is cyclic and totally ramified.

The first kind is settled here, and settled outright.  A prime of the ring of integers of an
algebraic closure of a number field has a decomposition subgroup whose quotient by inertia is
generated by one element, the Frobenius, in the strong sense that every finite quotient of the
decomposition subgroup which kills inertia is generated by the image of that one element; and a
homomorphism of the decomposition subgroup into a finite group which kills inertia therefore lifts
along any surjection onto that group from a finite group, one sending the Frobenius wherever a
preimage of its image goes.  That is exactly the local solution asked for, so at a prime where the
solution kills inertia there is nothing more to do.

The second kind is left as a named condition, stated in the shape the property supplies: the base
realization kills the whole decomposition subgroup, the solution takes no value there which it does
not already take on inertia, and its values lie in the powers of a single element.  With the first
kind proved, the local solvability of the step is exactly that condition.

## Main definitions

* `InverseGalois.Shafarevich.HasSplitRamifiedLift` — the local solution at a prime where the
  solution ramifies and the base field splits completely.

## Main results

* `InverseGalois.Shafarevich.exists_smoothHom_lift_of_unramified` — **at a prime where the solution
  kills inertia the step has a local solution.**
* `InverseGalois.Shafarevich.hasLocalLift_of_hasSplitRamifiedLift` — **local solvability of the step
  is the ramified case alone**, once the family names every prime where the base realization
  ramifies and the wider family holds nothing but decomposition subgroups.

## Tags

Shafarevich's theorem, embedding problem, decomposition group, inertia subgroup, Frobenius
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT MulAction NumberField

open scoped Pointwise

section LocalLift

variable (ℓ : ℕ) [Fact ℓ.Prime] (U : Type) [Group U] [Finite U] (n : ℕ) (S : Type) [Group S]
  [Finite S] (j : ℕ) {k Ω : Type*} [Field k] [NumberField k] [Field Ω] [Algebra k Ω]
  [IsGalois k Ω] [IsAlgClosed Ω]

omit [Fact ℓ.Prime] in
/-- **At a prime where the solution kills inertia the step has a local solution.**

The decomposition subgroup of a prime of the ring of integers of an algebraic closure is generated,
modulo inertia and modulo any open subgroup, by the Frobenius, so a homomorphism of it into a finite
group which kills inertia is determined by where the Frobenius goes and can be lifted by choosing a
preimage of that value. -/
theorem exists_smoothHom_lift_of_unramified (Φ : Gal(Ω/k) →* GenericQuot ℓ U n S j)
    (hsm : IsSmoothHom Φ) (P : Ideal (𝓞 Ω)) [P.IsPrime] (hP : P ≠ ⊥)
    (hunr : ∀ x ∈ Ideal.inertia Gal(Ω/k) P, Φ x = 1) :
    ∃ g : ↥(stabilizer Gal(Ω/k) P) →* GenericQuot ℓ U n S (j + 1),
      IsSmooth₁ (g : ↥(stabilizer Gal(Ω/k) P) → GenericQuot ℓ U n S (j + 1)) ∧
        ∀ x : ↥(stabilizer Gal(Ω/k) P),
          (layerExtension ℓ (genericAut U n S) j).rightHom (g x) = Φ (x : Gal(Ω/k)) := by
  haveI : Finite (GenericQuot ℓ U n S (j + 1)) :=
    Finite.of_equiv _ SemidirectProduct.equivProd.symm
  refine exists_smoothHom_lift_of_inertia_le_ker P hP _
    (layerExtension ℓ (genericAut U n S) j).rightHom_surjective (Φ.comp (stabilizer _ P).subtype)
    (isSmooth₁_comp (continuous_subtype _)
      (isSmooth₁_of_isOpenNormal_ker (isOpenNormal_ker_of_isSmoothHom hsm))) (fun x hx => ?_)
  exact hunr (x : Gal(Ω/k)) (Subgroup.mem_subgroupOf.1 hx)

/-- **The local solution at a prime where the solution ramifies and the base field splits
completely.**

The three hypotheses on the prime are the three clauses the property carried by the solutions
supplies at a prime where it ramifies over the base realization: the base realization kills the
whole decomposition subgroup, the solution takes no value on the decomposition subgroup which it
does not already take on inertia, and its values there lie in the powers of a single element.  What
is asked is the same local solution the unramified case supplies, a homomorphism of the
decomposition subgroup into the group at the next level over the solution. -/
def HasSplitRamifiedLift (φ : Gal(Ω/k) →* U) : Prop :=
  ∀ Φ : Gal(Ω/k) →* GenericQuot ℓ U n S j, IsSmoothHom Φ →
    (∀ x, SemidirectProduct.rightHom (Φ x) = φ x) →
    ∀ P : Ideal (𝓞 Ω), P.IsPrime → P ≠ ⊥ →
      (∀ x ∈ stabilizer Gal(Ω/k) P, φ x = 1) →
      (∀ x ∈ stabilizer Gal(Ω/k) P, ∃ y ∈ Ideal.inertia Gal(Ω/k) P, Φ x = Φ y) →
      (∃ c, ∀ x ∈ stabilizer Gal(Ω/k) P, Φ x ∈ Subgroup.zpowers c) →
        ∃ g : ↥(stabilizer Gal(Ω/k) P) →* GenericQuot ℓ U n S (j + 1),
          IsSmooth₁ (g : ↥(stabilizer Gal(Ω/k) P) → GenericQuot ℓ U n S (j + 1)) ∧
            ∀ x : ↥(stabilizer Gal(Ω/k) P),
              (layerExtension ℓ (genericAut U n S) j).rightHom (g x) = Φ (x : Gal(Ω/k))

/-- **Local solvability of the step is the ramified case alone.**

The wider family is asked to hold nothing but decomposition subgroups of primes of the ring of
integers of the algebraic closure, and the finite family to name every prime at which the base
realization ramifies, in the form that a prime whose decomposition subgroup is not a conjugate of a
member has the base realization trivial on its inertia.  At such a prime the solution either kills
inertia, and the unramified case applies, or it does not, and then the property it carries supplies
the three clauses of the ramified case. -/
theorem hasLocalLift_of_hasSplitRamifiedLift (φ : Gal(Ω/k) →* U) {t : ℕ}
    (D : Fin t → Subgroup Gal(Ω/k)) (T : Set (Subgroup Gal(Ω/k)))
    (hT : ∀ A ∈ T, ∃ P : Ideal (𝓞 Ω), P.IsPrime ∧ P ≠ ⊥ ∧ A = stabilizer Gal(Ω/k) P)
    (hD : ∀ P : Ideal (𝓞 Ω), P.IsPrime → P ≠ ⊥ →
      stabilizer Gal(Ω/k) P ∉ conjFamily D → ∀ x ∈ Ideal.inertia Gal(Ω/k) P, φ x = 1)
    (hram : HasSplitRamifiedLift ℓ U n S j φ) :
    HasLocalLift ℓ U n S j φ D T (IsSplitTotallyRamified ℓ U S φ) := by
  intro Φ hsm hover _ hprop A hA hAD
  obtain ⟨P, hPp, hPbot, rfl⟩ := hT A hA
  haveI := hPp
  by_cases hunr : ∀ x ∈ Ideal.inertia Gal(Ω/k) P, Φ x = 1
  · exact exists_smoothHom_lift_of_unramified ℓ U n S j Φ hsm P hPbot hunr
  · push_neg at hunr
    obtain ⟨x, hxI, hx1⟩ := hunr
    obtain ⟨hsplit, htot, hcyc⟩ :=
      hprop P hPp hPbot ⟨x, hxI, hD P hPp hPbot hAD x hxI, hx1⟩
    exact hram Φ hsm hover P hPp hPbot hsplit htot hcyc

end LocalLift

end InverseGalois.Shafarevich
