/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Shafarevich.Frattini
import InverseGalois.Solvable.Shafarevich.Reduction
import InverseGalois.Solvable.Shafarevich.PrimePower
import InverseGalois.Rigidity.RET.RegularQuotient
import InverseGalois.Rigidity.RET.RegularCriterion

/-!
# Shafarevich's theorem, reduced to its arithmetic core

Shafarevich's theorem asserts that every finite solvable group is a Galois group over `ℚ`.  The
group-theoretic half of the proof is carried out here in full: the theorem follows from the single
statement `Shafarevich.SplitNilpotentEP`, that every split embedding problem over `ℚ` with nilpotent
kernel is solvable.

The two ingredients are Ore's supplement theorem and an induction on the order.  A nontrivial finite
solvable group `G` has a nilpotent normal subgroup `N` that is not contained in the Frattini
subgroup (`exists_nilpotent_normal_supplement`), hence a proper subgroup `U` with `N ⊔ U = G`, and
multiplication `N ⋊ U → G` is then surjective.  Because `U` is proper it is smaller than `G`, so it
is realizable by induction, and `SplitNilpotentEP` upgrades that to a realization of `N ⋊ U`, of
which `G` is a quotient.

Nothing in the reduction is specific to realizability over `ℚ`: it uses only that the property is
inherited by quotients and holds for the trivial group.  So the same argument reduces the *regular*
form of Shafarevich's theorem — every finite solvable group as a Galois group of a regular extension
of `ℚ(T)` — to the regular form of the same embedding problem.

## Main results

* `Shafarevich.hasNilpotentSupplement` — the group-theoretic input, discharged.
* `Shafarevich.isSolvable_isInverseGalois_of_splitNilpotentEP` — every finite solvable group is a
  Galois group over `ℚ`, given `SplitNilpotentEP`.
* `Shafarevich.isSolvable_isInverseGalois_of_splitPrimePowerEP` — the same, given only the case of
  a kernel of prime power order.
* `Shafarevich.isSolvable_isRegularInverseGalois_of_splitNilpotentEP` and
  `Shafarevich.isSolvable_isRegularInverseGalois_of_splitPrimePowerEP` — the regular analogues over
  `ℚ(T)`.
-/

namespace Shafarevich

open SemidirectProduct

/-- **Ore's supplement theorem.**

Every nontrivial finite solvable group is generated by a nilpotent normal subgroup together with a
proper subgroup. -/
theorem hasNilpotentSupplement : HasNilpotentSupplement :=
  fun G => exists_nilpotent_normal_supplement G

/-- **Shafarevich's theorem, reduced to split embedding problems with nilpotent kernel.**

If every split embedding problem over `ℚ` whose kernel is a finite nilpotent group is solvable, then
every finite solvable group is a Galois group over `ℚ`. -/
theorem isSolvable_isInverseGalois_of_splitNilpotentEP (hEP : SplitNilpotentEP)
    (G : Type) [Group G] [Finite G] [IsSolvable G] : IsInverseGalois G :=
  isInverseGalois_of_isSolvable_of_splitNilpotentEP hasNilpotentSupplement hEP G

/-- **Shafarevich's theorem, reduced to split embedding problems with kernel of prime power
order.**

The Sylow decomposition of a nilpotent group splits such a kernel one prime at a time, so the
hypothesis of `isSolvable_isInverseGalois_of_splitNilpotentEP` already follows from its special
case for kernels of prime power order.  This is the sharpest form of the reduction: everything
that remains of Shafarevich's theorem is the realization of `H ⋊[φ] U` for `H` a finite `p`-group
over a group `U` already realized. -/
theorem isSolvable_isInverseGalois_of_splitPrimePowerEP (hEP : SplitPrimePowerEP)
    (G : Type) [Group G] [Finite G] [IsSolvable G] : IsInverseGalois G :=
  isSolvable_isInverseGalois_of_splitNilpotentEP (splitNilpotentEP_of_splitPrimePowerEP hEP) G

/-- **Regular realizability over `ℚ(T)` passes to quotients.** -/
theorem isQuotientClosed_isRegularInverseGalois :
    IsQuotientClosed (fun G _ => IsRegularInverseGalois G) :=
  fun _ _ _ _ f hf hG => hG.of_surjective f hf

/-- **Every split embedding problem with nilpotent kernel is solvable regularly over `ℚ(T)`.**

The regular analogue of `SplitNilpotentEP`. -/
def SplitNilpotentEPRegular : Prop :=
  ∀ (H U : Type) [Group H] [Finite H] [Group.IsNilpotent H] [Group U] [Finite U]
    (φ : U →* MulAut H), IsRegularInverseGalois U → IsRegularInverseGalois (H ⋊[φ] U)

/-- **The regular form of Shafarevich's theorem, reduced to split embedding problems with nilpotent
kernel.**

If every split embedding problem with finite nilpotent kernel is solvable regularly over `ℚ(T)`,
then every finite solvable group is the Galois group of a regular extension of `ℚ(T)`. -/
theorem isSolvable_isRegularInverseGalois_of_splitNilpotentEP (hEP : SplitNilpotentEPRegular)
    (G : Type) [Group G] [Finite G] [IsSolvable G] : IsRegularInverseGalois G :=
  oreInduction isQuotientClosed_isRegularInverseGalois
    (fun _ _ _ => IsRegularInverseGalois.of_subsingleton) hasNilpotentSupplement hEP G

/-- **Every split embedding problem with kernel of prime power order is solvable regularly over
`ℚ(T)`.**

The regular analogue of `SplitPrimePowerEP`. -/
def SplitPrimePowerEPRegular : Prop :=
  ∀ (H U : Type) [Group H] [Finite H] [Group U] [Finite U] (p : ℕ) [Fact p.Prime],
    IsPGroup p H → ∀ φ : U →* MulAut H, IsRegularInverseGalois U →
      IsRegularInverseGalois (H ⋊[φ] U)

/-- **The regular form of Shafarevich's theorem, reduced to split embedding problems with kernel of
prime power order.** -/
theorem isSolvable_isRegularInverseGalois_of_splitPrimePowerEP (hEP : SplitPrimePowerEPRegular)
    (G : Type) [Group G] [Finite G] [IsSolvable G] : IsRegularInverseGalois G :=
  isSolvable_isRegularInverseGalois_of_splitNilpotentEP
    (fun H U _ _ _ _ _ φ hU =>
      splitNilpotent_of_splitPrimePower isQuotientClosed_isRegularInverseGalois
        (fun H U _ _ _ _ p _ hp φ hU => hEP H U p hp φ hU) H U φ hU)
    G

end Shafarevich
