/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Solvable.Shafarevich.PCentral
import InverseGalois.Solvable.Shafarevich.ClassTwo

/-!
# Generators for the layers of the descending `p`-central series

A generating set `S` of a group generates each layer of the descending `p`-central series in an
explicit way: the layer `P^i / P^{i+1}` is generated by the classes of the words obtained from `S`
by applying, `i` times over, one of the two operations that define the series — raise to the `p`-th
power, or take the commutator with a member of `S`.

This is the group-theoretic input to Shafarevich's induction.  What it buys is a *bounded* supply
of generators for each layer, each of them a word in which the members of `S` occur a bounded
number of times; an endomorphism substituting a product of new generators for each member of `S`
therefore acts on the layer by a polynomial of bounded degree in the exponents, which is what makes
the Chevalley–Warning count of `InverseGalois.Solvable.Shafarevich.Shrink` applicable.

The proof is a double induction.  Modulo the next term of the series the layer is central, so the
commutator is bilinear there and the `p`-th power map is additive up to a commutator; the two
statements "every commutator of a word with a group element is a product of generators" and "every
`p`-th power of a word is a product of generators" then follow by induction on the word, the second
one calling on the first through the class two power formula.

## Main definitions

* `InverseGalois.Shafarevich.layerGen` — the generators of the `n`-th layer built from `S`.

## Main results

* `InverseGalois.Shafarevich.pCentral_eq_closure_layerGen_sup` — **the layers of the descending
  `p`-central series are generated by those words.**

## Tags

p-central series, generators, Shafarevich's theorem, embedding problem
-/

namespace InverseGalois.Shafarevich

variable {P : Type*} [Group P]

/-- The **generators of the `n`-th layer** of the descending `p`-central series associated with a
set `S`: start from `S`, and at each step either raise a previous generator to the `p`-th power or
take its commutator with a member of `S`. -/
def layerGen (p : ℕ) (S : Set P) : ℕ → Set P
  | 0 => S
  | n + 1 =>
      (fun g => g ^ p) '' layerGen p S n ∪ {g | ∃ x ∈ layerGen p S n, ∃ s ∈ S, ⁅x, s⁆ = g}

@[simp]
theorem layerGen_zero (p : ℕ) (S : Set P) : layerGen p S 0 = S := rfl

theorem layerGen_succ (p : ℕ) (S : Set P) (n : ℕ) :
    layerGen p S (n + 1) = (fun g => g ^ p) '' layerGen p S n ∪
      {g | ∃ x ∈ layerGen p S n, ∃ s ∈ S, ⁅x, s⁆ = g} := rfl

theorem pow_mem_layerGen_succ {p : ℕ} {S : Set P} {n : ℕ} {x : P} (hx : x ∈ layerGen p S n) :
    x ^ p ∈ layerGen p S (n + 1) := Or.inl ⟨x, hx, rfl⟩

theorem commutatorElement_mem_layerGen_succ {p : ℕ} {S : Set P} {n : ℕ} {x : P}
    (hx : x ∈ layerGen p S n) {s : P} (hs : s ∈ S) : ⁅x, s⁆ ∈ layerGen p S (n + 1) :=
  Or.inr ⟨x, hx, s, hs, rfl⟩

/-- The generators of the `n`-th layer do lie in the `n`-th term of the series. -/
theorem layerGen_subset_pCentral (p : ℕ) (S : Set P) (n : ℕ) :
    layerGen p S n ⊆ (pCentral p P n : Set P) := by
  induction n with
  | zero => intro x _; simp
  | succ n ih =>
    rintro g (⟨x, hx, rfl⟩ | ⟨x, hx, s, -, rfl⟩)
    · exact pow_mem_pCentral_succ p (ih hx)
    · exact commutatorElement_mem_pCentral_succ p (ih hx) s

theorem closure_layerGen_le (p : ℕ) (S : Set P) (n : ℕ) :
    Subgroup.closure (layerGen p S n) ≤ pCentral p P n :=
  (Subgroup.closure_le _).mpr (layerGen_subset_pCentral p S n)

/-- The inductive step: given that the `n`-th term is generated by the `n`-th layer's words
together with the next term, the same holds one level up. -/
private theorem pCentral_succ_le_closure_layerGen_sup (p : ℕ) {S : Set P}
    (hS : Subgroup.closure S = ⊤) (n : ℕ)
    (ih : pCentral p P n ≤ Subgroup.closure (layerGen p S n) ⊔ pCentral p P (n + 1)) :
    pCentral p P (n + 1) ≤
      Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1) := by
  classical
  have hMle : Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1) ≤
      pCentral p P (n + 1) :=
    sup_le (closure_layerGen_le p S (n + 1)) (pCentral_succ_le p (n + 1))
  set π : P →* P ⧸ pCentral p P (n + 1 + 1) :=
    QuotientGroup.mk' (pCentral p P (n + 1 + 1)) with hπ
  set A : Subgroup (P ⧸ pCentral p P (n + 1 + 1)) :=
    Subgroup.map π (Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1)) with hA
  -- everything in `A` is central, because the whole layer is
  have hcomm : ∀ a ∈ A, ∀ q : P ⧸ pCentral p P (n + 1 + 1), Commute q a := by
    intro a ha q
    exact Subgroup.mem_center_iff.mp
      (map_pCentral_le_center p (n + 1) (Subgroup.map_mono hMle ha)) q
  have hsubL : Subgroup.closure (layerGen p S (n + 1)) ≤
      Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1) := le_sup_left
  have hsubR : pCentral p P (n + 1 + 1) ≤
      Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1) := le_sup_right
  -- the generators of the next layer lie in `A`
  have hLA : ∀ g ∈ layerGen p S (n + 1), π g ∈ A :=
    fun g hg => ⟨g, hsubL (Subgroup.subset_closure hg), rfl⟩
  -- membership in `A` is membership in the subgroup we are aiming at
  have hback : ∀ g : P,
      π g ∈ A → g ∈ Subgroup.closure (layerGen p S (n + 1)) ⊔ pCentral p P (n + 1 + 1) := by
    rintro g ⟨m, hm, hgm⟩
    have hker : g * m⁻¹ ∈ pCentral p P (n + 1 + 1) := by
      rw [← QuotientGroup.ker_mk' (pCentral p P (n + 1 + 1)), ← hπ, MonoidHom.mem_ker, map_mul,
        map_inv, hgm, mul_inv_cancel]
    have hgg : g = g * m⁻¹ * m := by group
    rw [hgg]
    exact mul_mem (hsubR hker) hm
  -- an element of the previous layer vanishes in the quotient after a `p`-th power
  have hone : ∀ g : P, g ∈ pCentral p P (n + 1 + 1) → π g = 1 := by
    intro g hg
    rw [hπ, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
    exact hg
  -- **first claim**: commutators of words with arbitrary group elements
  have hB1 : ∀ g ∈ layerGen p S n, ∀ z : P, ⁅π g, π z⁆ ∈ A := by
    intro g hg z
    have hz : z ∈ Subgroup.closure S := by rw [hS]; exact Subgroup.mem_top z
    induction hz using Subgroup.closure_induction with
    | mem s hs =>
      rw [← map_commutatorElement]
      exact hLA _ (commutatorElement_mem_layerGen_succ hg hs)
    | one => simp
    | mul z₁ z₂ _ _ ih₁ ih₂ =>
      rw [map_mul, commutatorElement_mul_right_of_commute (hcomm _ ih₂ (π z₁))]
      exact mul_mem ih₁ ih₂
    | inv z₁ _ ih₁ =>
      rw [map_inv, commutatorElement_inv_right_of_commute (hcomm _ ih₁ (π z₁))]
      exact inv_mem ih₁
  have hB : ∀ z : P, ∀ w ∈ Subgroup.closure (layerGen p S n), ⁅π w, π z⁆ ∈ A := by
    intro z w hw
    induction hw using Subgroup.closure_induction with
    | mem g hg => exact hB1 g hg z
    | one => simp
    | mul w₁ w₂ _ _ ih₁ ih₂ =>
      rw [map_mul, commutatorElement_mul_left_of_commute (hcomm _ ih₂ (π w₁))]
      exact mul_mem ih₂ ih₁
    | inv w₁ _ ih₁ =>
      rw [map_inv, commutatorElement_inv_left_of_commute (hcomm _ ih₁ (π w₁))]
      exact inv_mem ih₁
  -- **second claim**: `p`-th powers of words
  have hPow : ∀ w ∈ Subgroup.closure (layerGen p S n), π w ^ p ∈ A := by
    intro w hw
    induction hw using Subgroup.closure_induction with
    | mem g hg =>
      rw [← map_pow]
      exact hLA _ (pow_mem_layerGen_succ hg)
    | one => simp
    | mul w₁ w₂ _ hw₂ ih₁ ih₂ =>
      have hc : ⁅π w₂, π w₁⁆ ∈ A := hB w₁ w₂ hw₂
      rw [map_mul, mul_pow_of_commute_commutator (hcomm _ hc (π w₁)).symm
        (hcomm _ hc (π w₂)).symm]
      exact mul_mem (mul_mem ih₁ ih₂) (pow_mem hc _)
    | inv w₁ _ ih₁ =>
      rw [map_inv, inv_pow]
      exact inv_mem ih₁
  -- decompose an element of the previous term along the inductive hypothesis
  have hdec : ∀ x ∈ pCentral p P n, ∃ w ∈ Subgroup.closure (layerGen p S n),
      ∃ u ∈ pCentral p P (n + 1), w * u = x := by
    intro x hx
    have hx' : x ∈ (↑(Subgroup.closure (layerGen p S n) ⊔ pCentral p P (n + 1)) : Set P) := ih hx
    rw [Subgroup.mul_normal, Set.mem_mul] at hx'
    exact hx'
  rw [pCentral_succ]
  refine sup_le ((Subgroup.closure_le _).mpr ?_) (Subgroup.commutator_le.mpr ?_)
  · rintro _ ⟨x, hx, rfl⟩
    obtain ⟨w, hw, u, hu, rfl⟩ := hdec x hx
    have hucen : Commute (π w) (π u) := by
      have hcen : π u ∈ Subgroup.center (P ⧸ pCentral p P (n + 1 + 1)) :=
        map_pCentral_le_center p (n + 1) ⟨u, hu, rfl⟩
      exact Subgroup.mem_center_iff.mp hcen (π w)
    have hup : π u ^ p = 1 := by
      rw [← map_pow]
      exact hone _ (pow_mem_pCentral_succ p hu)
    refine hback _ ?_
    rw [map_pow, map_mul, hucen.mul_pow, hup, mul_one]
    exact hPow w hw
  · intro x hx z _
    obtain ⟨w, hw, u, hu, rfl⟩ := hdec x hx
    have huz : ⁅π u, π z⁆ = 1 := by
      rw [← map_commutatorElement]
      exact hone _ (commutatorElement_mem_pCentral_succ p hu z)
    have hcomm1 : Commute (π w) ⁅π u, π z⁆ := by
      rw [huz]
      exact Commute.one_right _
    refine hback _ ?_
    rw [map_commutatorElement, map_mul, commutatorElement_mul_left_of_commute hcomm1, huz, one_mul]
    exact hB z w hw

/-- **The layers of the descending `p`-central series are generated by the words built from a
generating set**: the `n`-th term is generated by the `n`-th layer's words together with the next
term. -/
theorem pCentral_le_closure_layerGen_sup (p : ℕ) {S : Set P} (hS : Subgroup.closure S = ⊤)
    (n : ℕ) : pCentral p P n ≤ Subgroup.closure (layerGen p S n) ⊔ pCentral p P (n + 1) := by
  induction n with
  | zero =>
    rw [layerGen_zero, hS, top_sup_eq]
    exact le_top
  | succ n ih => exact pCentral_succ_le_closure_layerGen_sup p hS n ih

/-- **The layers of the descending `p`-central series are generated by the words built from a
generating set.** -/
theorem pCentral_eq_closure_layerGen_sup (p : ℕ) {S : Set P} (hS : Subgroup.closure S = ⊤)
    (n : ℕ) : pCentral p P n = Subgroup.closure (layerGen p S n) ⊔ pCentral p P (n + 1) :=
  le_antisymm (pCentral_le_closure_layerGen_sup p hS n)
    (sup_le (closure_layerGen_le p S n) (pCentral_succ_le p n))

end InverseGalois.Shafarevich
