/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Shafarevich.GenericHomology
import InverseGalois.Solvable.Shafarevich.ShrinkHom

/-!
# Reading the letters of a generic operator group one block at a time

Among the shrinking homomorphisms attached to a vector of exponents there is, for each block, the
one whose vector is the indicator of that block: it keeps the letters of that block and kills every
other letter.  Because the surviving exponent is one and not merely prime to the residue
characteristic, this particular shrinking is surjective with no hypothesis whatever on the groups
involved — the letters downstairs are hit on the nose.

The blocks also cut the source into pieces.  The classes of the letters of one block generate a
subgroup; the block subgroups jointly generate everything; and the shrinking belonging to a block
kills the subgroup of every other block.  That is the combinatorial input to a counting argument
which, given enough blocks, finds one whose shrinking separates a prescribed field from a field of
radicals.

## Main definitions

* `InverseGalois.Shafarevich.blockExp` — the indicator vector of a block.
* `InverseGalois.Shafarevich.blockShrink` — the shrinking homomorphism it determines.
* `InverseGalois.Shafarevich.blockGen` — the classes of the letters of a block.

## Main results

* `InverseGalois.Shafarevich.blockShrink_surjective`: **the shrinking belonging to a block is
  surjective**, with no finiteness and no `p`-group hypothesis.
* `InverseGalois.Shafarevich.iSup_closure_blockGen`: **the block subgroups generate the whole
  generic operator group.**
* `InverseGalois.Shafarevich.closure_blockGen_le_ker`: the shrinking belonging to a block kills the
  subgroup generated by any other block.

## Tags

Shafarevich's theorem, embedding problem, relatively free group, shrinking, block
-/

namespace InverseGalois.Shafarevich

section Blocks

variable (U : Type) [Group U] (r n : ℕ) (S : Type) [Group S]

/-- The indicator vector of a block: the exponent one there and zero on every other block. -/
def blockExp (k : Fin r) : Fin r → ℕ := fun j => if j = k then 1 else 0

@[simp]
theorem blockExp_self (k : Fin r) : blockExp r k k = 1 := if_pos rfl

theorem blockExp_of_ne {j k : Fin r} (h : j ≠ k) : blockExp r k j = 0 := if_neg h

/-- **The shrinking homomorphism belonging to a block**: it keeps the letters of that block and
kills the letters of every other block. -/
def blockShrink (k : Fin r) : Generic U (r * n) S →* Generic U n S :=
  genericShrink U r n S (blockExp r k)

/-- The shrinking belonging to a block is equivariant for the operator action. -/
theorem isOperatorHom_blockShrink (k : Fin r) : IsOperatorHom (blockShrink U r n S k) :=
  isOperatorHom_genericShrink U r n S (blockExp r k)

omit [Group U] in
@[simp]
theorem blockShrink_mk_of (k j : Fin r) (i : Fin n) (g : U) :
    blockShrink U r n S k (QuotientGroup.mk (FreeGroup.of (finProdFinEquiv (j, i), g)))
      = QuotientGroup.mk (FreeGroup.of (i, g) ^ blockExp r k j) := by
  rw [blockShrink, genericShrink_mk, shrinkHom_of_block]

/-- The classes of the letters of one block. -/
def blockGen (k : Fin r) : Set (Generic U (r * n) S) :=
  Set.range fun z : Fin n × U =>
    (QuotientGroup.mk (FreeGroup.of (finProdFinEquiv (k, z.1), z.2)) : Generic U (r * n) S)

omit [Group U] in
/-- The letters of the blocks are exactly all the letters. -/
theorem iUnion_blockGen :
    (⋃ k : Fin r, blockGen U r n S k)
      = Set.range fun z : Fin (r * n) × U =>
          (QuotientGroup.mk (FreeGroup.of z) : Generic U (r * n) S) := by
  ext x
  constructor
  · intro hx
    rw [Set.mem_iUnion] at hx
    obtain ⟨k, z, rfl⟩ := hx
    exact ⟨(finProdFinEquiv (k, z.1), z.2), rfl⟩
  · rintro ⟨z, rfl⟩
    refine Set.mem_iUnion.2 ⟨(finProdFinEquiv.symm z.1).1,
      ⟨((finProdFinEquiv.symm z.1).2, z.2), ?_⟩⟩
    exact congrArg (fun w => (QuotientGroup.mk (FreeGroup.of (w, z.2)) : Generic U (r * n) S))
      (finProdFinEquiv.apply_symm_apply z.1)

omit [Group U] in
/-- **The block subgroups generate the whole generic operator group.** -/
theorem iSup_closure_blockGen :
    ⨆ k : Fin r, Subgroup.closure (blockGen U r n S k) = ⊤ := by
  rw [← Subgroup.closure_iUnion, iUnion_blockGen, closure_range_mk_of]

omit [Group U] in
/-- The shrinking belonging to a block kills the letters of every other block. -/
theorem blockShrink_eq_one_of_ne {j k : Fin r} (hjk : j ≠ k) {x : Generic U (r * n) S}
    (hx : x ∈ blockGen U r n S j) : blockShrink U r n S k x = 1 := by
  obtain ⟨z, rfl⟩ := hx
  rw [blockShrink_mk_of, blockExp_of_ne r hjk, pow_zero]
  rfl

omit [Group U] in
/-- The shrinking belonging to a block kills the subgroup generated by any other block. -/
theorem closure_blockGen_le_ker {j k : Fin r} (hjk : j ≠ k) :
    Subgroup.closure (blockGen U r n S j) ≤ (blockShrink U r n S k).ker :=
  (Subgroup.closure_le _).2 fun _ hx =>
    MonoidHom.mem_ker.2 (blockShrink_eq_one_of_ne U r n S hjk hx)

omit [Group U] in
/-- **The shrinking belonging to a block is surjective**, with no finiteness and no `p`-group
hypothesis: the surviving exponent is one, so the letters downstairs are hit on the nose. -/
theorem blockShrink_surjective (k : Fin r) : Function.Surjective (blockShrink U r n S k) := by
  rw [← MonoidHom.range_eq_top]
  refine top_le_iff.mp ?_
  rw [← closure_range_mk_of U n S, Subgroup.closure_le]
  rintro _ ⟨z, rfl⟩
  refine ⟨QuotientGroup.mk (FreeGroup.of (finProdFinEquiv (k, z.1), z.2)), ?_⟩
  rw [blockShrink_mk_of, blockExp_self, pow_one]

end Blocks

end InverseGalois.Shafarevich
