/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Core.Basic

/-!
# Reducing solvable groups to split embedding problems

Shafarevich's theorem asserts that every finite solvable group is a Galois group over `ℚ`.  Its
group-theoretic half is a reduction, due to Ore, of the general case to *split* extensions with
nilpotent kernel: a finite solvable group `G ≠ 1` has a normal nilpotent subgroup `N` that is not
contained in the Frattini subgroup, hence has a proper supplement `U`, and then multiplication
`N ⋊ U → G` is onto.  Since `U` is a proper subgroup it is smaller than `G`, so an induction on the
order reduces the realizability of `G` to the realizability of semidirect products `N ⋊ U` in which
`U` is already known to be realizable and `N` is nilpotent.

This is a genuine gain over the naive induction along a chief series, which leaves one facing an
arbitrary — not necessarily split — embedding problem at each step.  The arithmetic input is thereby
concentrated in the single statement `SplitNilpotentEP`.
-/

namespace Shafarevich

open SemidirectProduct

/-- **Every split embedding problem over `ℚ` with nilpotent kernel is solvable.**

This is the arithmetic content of Shafarevich's theorem: if a finite group `U` is a Galois group
over `ℚ`, then so is any semidirect product `H ⋊[φ] U` with `H` finite nilpotent. -/
def SplitNilpotentEP : Prop :=
  ∀ (H U : Type) [Group H] [Finite H] [Group.IsNilpotent H] [Group U] [Finite U]
    (φ : U →* MulAut H), IsInverseGalois U → IsInverseGalois (H ⋊[φ] U)

/-- **A nontrivial finite solvable group is generated by a nilpotent normal subgroup together with
a proper subgroup.**

Stated as a hypothesis here so that the reduction below can be read off from it alone. -/
def HasNilpotentSupplement : Prop :=
  ∀ (G : Type) [Group G] [Finite G] [IsSolvable G] [Nontrivial G],
    ∃ N : Subgroup G, ∃ _ : N.Normal, ∃ U : Subgroup G,
      Group.IsNilpotent N ∧ U ≠ ⊤ ∧ N ⊔ U = ⊤

/-- **A proper subgroup of a finite group is smaller than the group.** -/
theorem card_lt_card_of_ne_top {G : Type*} [Group G] [Finite G] {U : Subgroup G} (hU : U ≠ ⊤) :
    Nat.card U < Nat.card G := by
  have hindex : 1 < U.index := by
    have h0 : U.index ≠ 0 := Subgroup.index_ne_zero_of_finite
    have h1 : U.index ≠ 1 := fun h => hU (Subgroup.index_eq_one.mp h)
    omega
  have hcard : Nat.card G = U.index * Nat.card U := by
    rw [Subgroup.index, Subgroup.card_eq_card_quotient_mul_card_subgroup U]
  have hpos : 0 < Nat.card U := Nat.card_pos
  nlinarith [hcard, hindex, hpos]

/-- **Ore's reduction of solvable groups to split embedding problems with nilpotent kernel.**

Granted that a nontrivial finite solvable group always admits a nilpotent normal subgroup with a
proper supplement, and that split embedding problems over `ℚ` with nilpotent kernel are solvable,
every finite solvable group is a Galois group over `ℚ`. -/
theorem isInverseGalois_of_isSolvable_of_splitNilpotentEP
    (hSupp : HasNilpotentSupplement) (hEP : SplitNilpotentEP)
    (G : Type) [Group G] [Finite G] [IsSolvable G] : IsInverseGalois G := by
  suffices H : ∀ (n : ℕ) (G : Type) [Group G] [Finite G] [IsSolvable G],
      Nat.card G ≤ n → IsInverseGalois G from H (Nat.card G) G le_rfl
  intro n
  induction n with
  | zero => exact fun G _ _ _ h => absurd h (not_le.mpr Nat.card_pos)
  | succ n ih =>
    intro G _ _ _ hcard
    rcases subsingleton_or_nontrivial G with hs | hs
    · haveI := hs
      haveI : Unique G := uniqueOfSubsingleton 1
      exact IsInverseGalois.unit.of_mulEquiv MulEquiv.ofUnique
    · obtain ⟨N, hN, U, hnil, hUne, hsup⟩ := hSupp G
      haveI := hN
      haveI := hnil
      have hUcard : Nat.card U ≤ n := by
        have := card_lt_card_of_ne_top hUne
        omega
      have hle : U ≤ N.normalizer := by
        rw [N.normalizer_eq_top]
        exact le_top
      have hsurj : Function.Surjective (monoidHomSubgroup hle) := by
        intro g
        have hg : g ∈ (↑(N ⊔ U) : Set G) := by
          rw [hsup]
          trivial
        rw [Subgroup.normal_mul] at hg
        obtain ⟨a, ha, b, hb, rfl⟩ := hg
        exact ⟨⟨⟨a, ha⟩, ⟨b, hb⟩⟩, rfl⟩
      exact (hEP N U _ (ih U hUcard)).of_surjective _ hsurj

end Shafarevich
