/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Shafarevich.RamifiedHom
import InverseGalois.Solvable.Shafarevich.ScholzCyclic

/-!
# The alternative at the primes a solution ramifies at

The demand the prescription makes at a named place is the classical alternative: either the
auxiliary field turns no class of the level there into an exponent-th power beyond the trivial one
and the place carries a uniformiser fixed by its decomposition group, or the classes it does turn
into powers are generated by a single ramified class.  A place whose decomposition group acts on the
auxiliary field through the powers of a single automorphism lying in inertia satisfies it, so what
is left is to say where such places come from.

They come from the restriction the climb already carries.  A solution over a level is asked, at
every prime where it ramifies over the base realization, to have the base realization split
completely there and to take no value on the decomposition subgroup which it does not already take
on inertia, all those values lying in the powers of a single element.  Those three clauses are
exactly what is wanted.  The values on the decomposition subgroup form a subgroup of a group of
powers, hence a cyclic one; a generator of it is a value on the decomposition subgroup, so by total
ramification it is already a value on inertia; and the complete splitting puts the whole
decomposition subgroup inside the automorphisms over the level, so the witness in inertia may be
read there.  The auxiliary field being the one the solution cuts out, two automorphisms agreeing in
value agree on the field.

So a prime where a solution ramifies over the base realization lies over a Scholz place of the field
the solution cuts out, and no arithmetic input is spent on it: the alternative there is a
consequence of the ramification restriction the ladder carries from rung to rung.

The other source is complete decomposition.  A prime whose decomposition group over the base already
fixes the auxiliary field pointwise is acted on by the identity alone, which lies in inertia, so the
alternative holds there too; a place lying only below such primes and carrying a uniformiser fixed
by its decomposition group is a Scholz place of the field.

## Main results

* `InverseGalois.Shafarevich.IsSplitTotallyRamifiedHom.exists_inertia_generator`: **the values a
  split totally ramified homomorphism takes on a decomposition subgroup are the powers of its value
  at a single automorphism lying in inertia.**
* `InverseGalois.Shafarevich.isCyclicInertiaAt_of_isSplitTotallyRamifiedHom`: **the decomposition
  group over the level acts on the field a split totally ramified homomorphism cuts out through the
  powers of a single automorphism lying in inertia.**
* `InverseGalois.Shafarevich.isScholzPlace_of_isSplitTotallyRamifiedHom`: **a prime where a solution
  ramifies over the base realization lies over a Scholz place** of the level, for the field the
  solution cuts out.
* `InverseGalois.Shafarevich.isCyclicInertiaAt_of_stabilizer_le_fixingSubgroup`: a prime whose
  decomposition group over the base fixes the auxiliary field pointwise is acted on through the
  powers of a single automorphism lying in inertia.
* `InverseGalois.Shafarevich.isScholzPlace_of_stabilizer_le_fixingSubgroup`: **a place lying only
  below primes completely decomposed in the auxiliary field is a Scholz place** there, as soon as it
  carries a uniformiser fixed by its decomposition group.

## Tags

Shafarevich's theorem, embedding problem, Scholz condition, ramification, decomposition group
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

set_option maxHeartbeats 1600000

/-! ### A generator of the local image lying in inertia -/

section Generator

variable {n : ℕ} {U W : Type*} [Group U] [Group W] {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- **The values a split totally ramified homomorphism takes on a decomposition subgroup are the
powers of its value at a single automorphism lying in inertia.**

The restriction bounds those values by the powers of one element, so they form a subgroup of a
cyclic group and are therefore the powers of one of themselves; and total ramification turns the
element of the decomposition subgroup realising that generator into one of inertia. -/
theorem IsSplitTotallyRamifiedHom.exists_inertia_generator {φ : Gal(Ω/k) →* U} {Φ : Gal(Ω/k) →* W}
    (h : IsSplitTotallyRamifiedHom n φ Φ) {P : Ideal (𝓞 Ω)} (hPp : P.IsPrime) (hPbot : P ≠ ⊥)
    (hram : ∃ x ∈ Ideal.inertia Gal(Ω/k) P, φ x = 1 ∧ Φ x ≠ 1) :
    (∀ x ∈ stabilizer Gal(Ω/k) P, φ x = 1) ∧
      ∃ τ ∈ Ideal.inertia Gal(Ω/k) P,
        ∀ x ∈ stabilizer Gal(Ω/k) P, Φ x ∈ Subgroup.zpowers (Φ τ) := by
  obtain ⟨hsplit, htot, c, hc, -⟩ := h P hPp hPbot hram
  refine ⟨hsplit, ?_⟩
  have hle : (stabilizer Gal(Ω/k) P).map Φ ≤ Subgroup.zpowers c := by
    rintro y hy
    obtain ⟨x, hx, rfl⟩ := Subgroup.mem_map.1 hy
    exact hc x hx
  haveI : IsCyclic ↥((stabilizer Gal(Ω/k) P).map Φ) := Subgroup.isCyclic_of_le hle
  obtain ⟨g, hg⟩ :=
    ((stabilizer Gal(Ω/k) P).map Φ).isCyclic_iff_exists_zpowers_eq_top.1 inferInstance
  obtain ⟨x₀, hx₀, hx₀g⟩ : ∃ x ∈ stabilizer Gal(Ω/k) P, Φ x = g :=
    Subgroup.mem_map.1 (hg ▸ Subgroup.mem_zpowers g)
  obtain ⟨τ, hτI, hτ⟩ := htot x₀ hx₀
  refine ⟨τ, hτI, fun x hx => ?_⟩
  rw [← hτ, hx₀g, hg]
  exact Subgroup.mem_map_of_mem Φ hx

end Generator

/-! ### The decomposition group acting through a single automorphism of inertia -/

section Tower

variable {n : ℕ} {U W : Type*} [Group U] [Group W] {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]
  {K E : IntermediateField k Ω} {φ : Gal(Ω/k) →* U} {Φ : Gal(Ω/k) →* W} {P : Ideal (𝓞 Ω)}
  [P.IsPrime]

/-- **The decomposition group over the level acts on the field a split totally ramified homomorphism
cuts out through the powers of a single automorphism lying in inertia**, at every prime where the
homomorphism ramifies over the base realization.

The base realization splitting completely at the prime puts its whole decomposition subgroup inside
the automorphisms over the level, so both the generator of the local image and the elements it
generates may be read over the level; and two automorphisms on which the homomorphism agrees differ
by one in its kernel, and its kernel fixes the field it cuts out. -/
theorem isCyclicInertiaAt_of_isSplitTotallyRamifiedHom (hKker : φ.ker ≤ K.fixingSubgroup)
    (hEker : Φ.ker ≤ E.fixingSubgroup) (h : IsSplitTotallyRamifiedHom n φ Φ) (hPbot : P ≠ ⊥)
    (hram : ∃ x ∈ Ideal.inertia Gal(Ω/k) P, φ x = 1 ∧ Φ x ≠ 1) :
    IsCyclicInertiaAt K E P := by
  obtain ⟨hsplit, τ, hτI, hτz⟩ := h.exists_inertia_generator ‹P.IsPrime› hPbot hram
  have hτK : τ ∈ K.fixingSubgroup :=
    hKker (MonoidHom.mem_ker.2 (hsplit τ (Ideal.inertia_le_stabilizer P hτI)))
  obtain ⟨τ', hτ'⟩ := exists_galSubHom_eq K hτK
  refine ⟨τ', (mem_inertia_galSubHom_iff K τ' P).1 (by rw [hτ']; exact hτI), fun σ hσ => ?_⟩
  obtain ⟨i, hi⟩ :=
    Subgroup.mem_zpowers_iff.1 (hτz _ ((mem_stabilizer_galSubHom_iff K σ P).2 hσ))
  refine ⟨i, fun y hy => ?_⟩
  have hmem : (galSubHom K τ' ^ i)⁻¹ * galSubHom K σ ∈ E.fixingSubgroup := by
    refine hEker (MonoidHom.mem_ker.2 ?_)
    rw [_root_.map_mul, _root_.map_inv, _root_.map_zpow, hτ', hi, inv_mul_cancel]
  have hgy : ((galSubHom K τ' ^ i)⁻¹ * galSubHom K σ) y = y := by
    rw [IntermediateField.mem_fixingSubgroup_iff] at hmem
    exact hmem y hy
  have hfac : galSubHom K σ
      = (galSubHom K τ' ^ i) * ((galSubHom K τ' ^ i)⁻¹ * galSubHom K σ) :=
    (mul_inv_cancel_left (galSubHom K τ' ^ i) (galSubHom K σ)).symm
  calc σ y = galSubHom K σ y := (galSubHom_apply K σ y).symm
    _ = ((galSubHom K τ' ^ i) * ((galSubHom K τ' ^ i)⁻¹ * galSubHom K σ)) y := by rw [← hfac]
    _ = (galSubHom K τ' ^ i) (((galSubHom K τ' ^ i)⁻¹ * galSubHom K σ) y) := rfl
    _ = (galSubHom K τ' ^ i) y := by rw [hgy]
    _ = (τ' ^ i) y := by rw [← _root_.map_zpow (galSubHom K) τ' i, galSubHom_apply]

omit [P.IsPrime] in
/-- **A prime whose decomposition group over the base fixes an auxiliary field pointwise makes the
decomposition group over the level act on that field through the powers of a single automorphism
lying in inertia**, the identity serving as that automorphism.

So a prime completely decomposed in the auxiliary field costs nothing at all: every automorphism
fixing it already fixes the field, and the trivial power of the trivial automorphism records
that. -/
theorem isCyclicInertiaAt_of_stabilizer_le_fixingSubgroup
    (hdec : stabilizer Gal(Ω/k) P ≤ E.fixingSubgroup) : IsCyclicInertiaAt K E P := by
  refine ⟨1, one_mem _, fun σ hσ => ⟨0, fun y hy => ?_⟩⟩
  have hmem : galSubHom K σ ∈ E.fixingSubgroup :=
    hdec ((mem_stabilizer_galSubHom_iff K σ P).2 hσ)
  rw [IntermediateField.mem_fixingSubgroup_iff] at hmem
  calc σ y = galSubHom K σ y := (galSubHom_apply K σ y).symm
    _ = y := hmem y hy
    _ = ((1 : Gal(Ω/↥K)) ^ (0 : ℤ)) y := by rw [zpow_zero]; rfl

end Tower

/-! ### The Scholz alternative at a prime the solution ramifies at -/

section Place

variable {ℓ n : ℕ} [NeZero ℓ] {U W : Type*} [Group U] [Group W] {k Ω : Type} [Field k] [Field Ω]
  [Algebra k Ω] {K : IntermediateField k Ω} [NumberField ↥K] [IsGalois ↥K Ω] {ζ : ↥K}
  {hζ : IsPrimitiveRoot ζ ℓ} {E : IntermediateField k Ω} {P : Ideal (𝓞 Ω)} [P.IsPrime]
  {w : HeightOneSpectrum (𝓞 ↥K)} {φ : Gal(Ω/k) →* U} {Φ : Gal(Ω/k) →* W}

attribute [local instance] zmodTrivialAction

variable (h : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)

include h in
/-- **A prime where a solution ramifies over the base realization lies over a Scholz place of the
level**, for the field the solution cuts out.

Nothing arithmetic is spent: the ramification restriction the climb carries makes the decomposition
group act on that field through the powers of a single automorphism of inertia, and at such a place
the classes the field turns into exponent-th powers are either trivial or generated by a single
ramified one. -/
theorem isScholzPlace_of_isSplitTotallyRamifiedHom (hℓ : ℓ.Prime) (hℓP : (ℓ : 𝓞 Ω) ∉ P)
    (hv : w.asIdeal = Ideal.under (𝓞 ↥K) P) (hfix : w ∈ fixedUniformizerPlaces k ↥K)
    (hKker : φ.ker ≤ K.fixingSubgroup) (hEker : Φ.ker ≤ E.fixingSubgroup)
    (hst : IsSplitTotallyRamifiedHom n φ Φ) (hPbot : P ≠ ⊥)
    (hram : ∃ x ∈ Ideal.inertia Gal(Ω/k) P, φ x = 1 ∧ Φ x ≠ 1) :
    IsScholzPlace ℓ K E w :=
  isScholzPlace_of_isCyclicInertiaAt h hℓ hℓP hv hfix
    (isCyclicInertiaAt_of_isSplitTotallyRamifiedHom hKker hEker hst hPbot hram)

include h in
/-- **A place lying only below primes completely decomposed in the auxiliary field is a Scholz place
there**, as soon as it carries a uniformiser fixed by its decomposition group.

The field is fixed pointwise by the whole decomposition group, so it turns no class of the level at
the place into an exponent-th power beyond the trivial one. -/
theorem isScholzPlace_of_stabilizer_le_fixingSubgroup (hℓ : ℓ.Prime) (hℓP : (ℓ : 𝓞 Ω) ∉ P)
    (hv : w.asIdeal = Ideal.under (𝓞 ↥K) P) (hfix : w ∈ fixedUniformizerPlaces k ↥K)
    (hdec : stabilizer Gal(Ω/k) P ≤ E.fixingSubgroup) :
    IsScholzPlace ℓ K E w :=
  isScholzPlace_of_isCyclicInertiaAt h hℓ hℓP hv hfix
    (isCyclicInertiaAt_of_stabilizer_le_fixingSubgroup hdec)

end Place

end InverseGalois.Shafarevich
