/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.AdicHerbrand
import InverseGalois.Solvable.Shafarevich.FlatDiagonalUnits
import InverseGalois.Solvable.Shafarevich.ScholzLine

/-!
# The diagonal of units is free at Scholz places

The arithmetic input of the prescription over a level asks, at finitely many places lying in
distinct orbits, for one unit of the level per place: ramified at its own place, a local power at a
prescribed finite set of places and at every conjugate of every named place but its own, and
confined elsewhere to the orbits of the named places and to the places completely decomposed in a
given auxiliary field.  Producing such a unit costs a reciprocity residue, and that residue is a
purely local demand at each named place taken on its own: the classes there of the units of the
level which the auxiliary field turns into exponent-th powers must lie on the line the naming is
made on.

A line is at hand at every place with no hypothesis whatever, and what it leaves to be asked of a
named place is the classical alternative — either the auxiliary field turns no class of the level
there into an exponent-th power beyond the trivial one and the place carries a uniformiser fixed by
its decomposition group, or the classes it does turn into powers there are generated by a single
ramified class.  Asking that of the named places makes the arithmetic input a theorem, with no
further hypothesis at all beyond a primitive root of unity of the exponent in the level and the
exponent being an odd prime.

The alternative is a demand on the pair of a place and an auxiliary field, not on the place alone:
the classes an auxiliary field turns into exponent-th powers at a place of the level are the local
image of the radicands of the elementary abelian part of the field over the level, and a field with
two independent radicands has a place where that image fills the whole group of classes.  So what
this file supplies is the arithmetic, read against the alternative; which places the naming may be
made at is the business of the tower the naming is made in.

## Main definitions

* `InverseGalois.Shafarevich.HasScholzDiagonalUnits`: the arithmetic input of the prescription, made
  only at named places satisfying the alternative.
* `InverseGalois.Shafarevich.HasScholzPlaces`: every place of a level which is prime to the exponent
  and reachable in an auxiliary field satisfies the alternative there.

## Main results

* `InverseGalois.Shafarevich.hasScholzDiagonalUnits`: **the units the prescription asks for exist at
  named places satisfying the alternative**, for every level carrying a primitive root of unity of
  an odd prime exponent, with no further hypothesis.
* `InverseGalois.Shafarevich.hasFlatDiagonalUnits_of_hasScholzPlaces`: a level all of whose places
  satisfy the alternative carries the units at every choice of named places.

## Tags

Shafarevich's theorem, embedding problem, Scholz condition, Kummer theory, local class, reciprocity
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

set_option maxHeartbeats 1600000

/-! ### The arithmetic input, read at Scholz places -/

section Demand

variable {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]

/-- **A unit of a level can be found for each of finitely many Scholz places lying in distinct
orbits, of order there prime to the exponent, a local power at a prescribed finite set of places
those avoid and at every proper conjugate of its own place and at every conjugate of the others, and
confined elsewhere to places sitting over the named ones or completely decomposed in a given finite
level.**

This is the arithmetic input of the prescription with the equivariance clause dropped and with one
clause added: each named place is asked to satisfy the alternative the reciprocity residue leaves
behind, which is what the naming of the line the unit is produced on costs. -/
def HasScholzDiagonalUnits (ℓ : ℕ) [NeZero ℓ] (K : IntermediateField k Ω) [NumberField ↥K] :
    Prop :=
  ∀ E : IntermediateField k Ω, FiniteDimensional k ↥E → IsGalois k ↥E → K ≤ E →
    ∀ (ι : Type) [Fintype ι] (w : ι → HeightOneSpectrum (𝓞 ↥K)),
      (∀ μ ν : ι, μ ≠ ν → ∀ σ : Gal(↥K/k), σ • w μ ≠ w ν) →
      ∀ Tz : Finset (HeightOneSpectrum (𝓞 ↥K)), (∀ μ : ι, w μ ∉ Tz) →
        (∀ μ : ι, (ℓ : 𝓞 ↥K) ∉ (w μ).asIdeal) →
        (∀ μ : ι, IsReachablePlace ℓ K E (w μ)) →
        (∀ μ : ι, IsScholzPlace ℓ K E (w μ)) →
        ∃ Z : ι → (↥K)ˣ,
          (∀ μ : ι, ¬ (ℓ : ℤ) ∣ placeValue (w μ) (Z μ)) ∧
          (∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), v ∈ Tz → localClassHom v ℓ (Z μ) = 1) ∧
          (∀ (μ : ι) (σ : Gal(↥K/k)), σ • w μ ≠ w μ → localClassHom (σ • w μ) ℓ (Z μ) = 1) ∧
          (∀ μ ν : ι, ν ≠ μ → ∀ σ : Gal(↥K/k), localClassHom (σ • w ν) ℓ (Z μ) = 1) ∧
          ∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), ¬ (ℓ : ℤ) ∣ placeValue v (Z μ) →
            (∃ (ν : ι) (σ : Gal(↥K/k)), v = σ • w ν) ∨
              ∀ P : Ideal (𝓞 Ω), P.IsPrime → P ≠ ⊥ → Ideal.under (𝓞 ↥K) P = v.asIdeal →
                stabilizer Gal(Ω/k) P ≤ E.fixingSubgroup

/-- **Every place of a level prime to the exponent and reachable in an auxiliary field is a Scholz
place there**: either the auxiliary field turns no class of the level at the place into an
exponent-th power beyond the trivial one and the place carries a uniformiser fixed by its
decomposition group, or the classes it does turn into powers there are generated by a single
ramified class.

This is the local half of the demand the prescription makes at a named place, the half a reciprocity
residue leaves behind, and it is Schmidt–Wingberg's alternative for the primes of a tower.  The two
clauses a named place comes with are granted to the condition, so nothing is asked at a place above
the exponent or at a place the auxiliary field does not reach. -/
def HasScholzPlaces (ℓ : ℕ) (K : IntermediateField k Ω) [NumberField ↥K] : Prop :=
  ∀ E : IntermediateField k Ω, FiniteDimensional k ↥E → IsGalois k ↥E → K ≤ E →
    ∀ w : HeightOneSpectrum (𝓞 ↥K), (ℓ : 𝓞 ↥K) ∉ w.asIdeal → IsReachablePlace ℓ K E w →
      IsScholzPlace ℓ K E w

end Demand

/-! ### The units the prescription asks for -/

section Units

variable {k Ω : Type} [Field k] [NumberField k] [Field Ω] [Algebra k Ω] [IsAlgClosed Ω]
  [IsGalois k Ω]

/-- **The units the prescription asks for exist at named places satisfying the alternative.**

Nothing is assumed beyond the alternative itself, a primitive root of unity of the exponent in the
level and the exponent being an odd prime: the line the units are named on is the one the auxiliary
field names of itself, the reciprocity residue on it collapses to the alternative at each named
place, and the two-place construction supplies the rest. -/
theorem hasScholzDiagonalUnits {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) (hodd : 2 < ℓ)
    (K : IntermediateField k Ω) [FiniteDimensional k ↥K] [IsGalois k ↥K] [NumberField ↥K]
    {Pc Ec : HeightOneSpectrum (𝓞 ↥K) → ℕ}
    (hres : ∀ v : HeightOneSpectrum (𝓞 ↥K), HasResidueChar (v.adicCompletion ↥K) (Pc v) (Ec v))
    {ζ : ↥K} (hζ : IsPrimitiveRoot ζ ℓ) : HasScholzDiagonalUnits ℓ K := by
  intro E hEfin hEgal hKE ι _ w hdist Tz hwTz hℓw _ hscholz
  exact exists_units_scholz_diagonal hℓ hodd K hres hζ E hEfin hEgal hKE w hdist Tz hwTz hℓw
    hscholz

/-- A level all of whose places satisfy the alternative carries the units at every choice of named
places, the alternative being all the arithmetic input asks for beyond the clauses a named place
arrives with. -/
theorem hasFlatDiagonalUnits_of_hasScholzPlaces {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) (hodd : 2 < ℓ)
    (K : IntermediateField k Ω) [FiniteDimensional k ↥K] [IsGalois k ↥K] [NumberField ↥K]
    {Pc Ec : HeightOneSpectrum (𝓞 ↥K) → ℕ}
    (hres : ∀ v : HeightOneSpectrum (𝓞 ↥K), HasResidueChar (v.adicCompletion ↥K) (Pc v) (Ec v))
    {ζ : ↥K} (hζ : IsPrimitiveRoot ζ ℓ) (h : HasScholzPlaces ℓ K) : HasFlatDiagonalUnits ℓ K := by
  intro E hEfin hEgal hKE ι _ w hdist Tz hwTz hℓw hreach
  exact hasScholzDiagonalUnits hℓ hodd K hres hζ E hEfin hEgal hKE ι w hdist Tz hwTz hℓw hreach
    fun μ => h E hEfin hEgal hKE (w μ) (hℓw μ) (hreach μ)

end Units

end InverseGalois.Shafarevich
