/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.CharLocalClass
import InverseGalois.Solvable.Shafarevich.ScholzLine

/-!
# The alternative at a place whose decomposition group acts cyclically

The naming of a line of local classes at a place of a level asks, of the pair made of a place and an
auxiliary field, the classical alternative: either the field turns no class of the level there into
an exponent-th power beyond the trivial one, or the classes it does turn into powers are generated
by a single ramified one.  The alternative is not automatic — a field with two independent radicands
has places where the classes it turns into powers fill the whole group — so it has to be read off
something, and what it is read off here is the way the decomposition group at the place acts on the
auxiliary field.

A unit of the level which the field turns into a power carries with it a root in the field, and an
automorphism of the closure over the level moves the chosen root of the unit exactly as it moves
that one, the two differing by a root of unity of the level.  So the Kummer character of such a unit
depends on an automorphism only through its action on the field.  If the decomposition group at a
prime above the place acts on the field through the powers of a single automorphism, the characters
of all those units on that group are determined by their values at the generator; and since the
values live in a field of residues, one unit whose value there is not zero determines every other up
to a power.  The classes at the place of the units the field turns into powers are read off the
characters on the decomposition group, so they are generated by the class of that one unit — the
second branch of the alternative — and if the generator of the action lies in the inertia group that
class is ramified, because the character of a unit whose order at the place is a multiple of the
exponent vanishes on inertia.

The first branch appears when no unit of the level the field turns into a power has a nonzero
character at the generator: every such unit then has trivial class at the place.

## Main definitions

* `InverseGalois.Shafarevich.IsCyclicInertiaAt`: the decomposition group at a prime acts on an
  auxiliary field through the powers of a single automorphism lying in the inertia group.

## Main results

* `InverseGalois.Shafarevich.kummerChar_eq_zero_iff_apply_eq_self`: the Kummer character of a unit
  the auxiliary field turns into a power vanishes at an automorphism exactly when that automorphism
  fixes the root the field supplies.
* `InverseGalois.Shafarevich.levelPowerClasses_eq_bot_or_exists_zpowers`: **the classes at a place
  of the units an auxiliary field turns into powers are trivial or generated by the class of one of
  them**, as soon as the decomposition group at a prime above the place acts on the field through
  the powers of a single automorphism.
* `InverseGalois.Shafarevich.isScholzPlace_of_isCyclicInertiaAt`: **a place whose decomposition
  group acts on the auxiliary field through the powers of one inertia element, and which carries a
  uniformiser fixed by its decomposition group, satisfies the alternative.**

## Tags

Shafarevich's theorem, Scholz condition, Kummer theory, decomposition group, inertia, local class
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

set_option maxHeartbeats 1600000

/-! ### The powers of an automorphism fixing an element -/

section Zpow

/-- **Every power of an automorphism fixing an element fixes it**, the automorphisms fixing an
element forming a subgroup. -/
theorem zpow_apply_eq_self_of_apply_eq_self {R A : Type*} [CommSemiring R] [Semiring A]
    [Algebra R A] {τ : A ≃ₐ[R] A} {y : A} (hτ : τ y = y) (i : ℤ) : (τ ^ i) y = y := by
  have hst : τ ∈ stabilizer (A ≃ₐ[R] A) y := hτ
  exact Subgroup.zpow_mem _ hst i

end Zpow

/-! ### The character of a unit the auxiliary field turns into a power -/

section Character

variable {ℓ : ℕ} [NeZero ℓ] {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]
  {K : IntermediateField k Ω} [IsGalois ↥K Ω] {ζ : ↥K} {hζ : IsPrimitiveRoot ζ ℓ}

attribute [local instance] zmodTrivialAction

variable (h : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)

omit [IsGalois ↥K Ω] in
/-- A root of a unit of the level is not zero. -/
theorem ne_zero_of_pow_eq_algebraMap {u : (↥K)ˣ} {y : Ω}
    (hy : y ^ ℓ = algebraMap ↥K Ω (u : ↥K)) : y ≠ 0 := by
  intro h0
  rw [h0, zero_pow (NeZero.ne ℓ)] at hy
  exact (map_ne_zero_iff _ (algebraMap ↥K Ω).injective).2 u.ne_zero hy.symm

/-- **The Kummer character of a unit of the level which an auxiliary field turns into an
exponent-th power vanishes at an automorphism exactly when that automorphism fixes the root the
field supplies.**

The chosen root of the unit and the root the field supplies differ by a root of unity of the level,
which every automorphism over the level fixes, so the two are moved alike; and the character
vanishes exactly at the automorphisms fixing the chosen root. -/
theorem kummerChar_eq_zero_iff_apply_eq_self {u : (↥K)ˣ} {y : Ω} (hy0 : y ≠ 0)
    (hy : y ^ ℓ = algebraMap ↥K Ω (u : ↥K)) (σ : Gal(Ω/↥K)) :
    kummerChar h u σ = 0 ↔ σ y = y := by
  have hpow : h.root u ^ ℓ = Units.mk0 y hy0 ^ ℓ := by
    refine Units.ext ?_
    rw [Units.val_pow_eq_pow_val, Units.val_pow_eq_pow_val, coe_root_pow h u, Units.val_mk0, hy]
  have hdiv := smul_div_eq_of_pow_eq hζ h.exists_ι_eq hpow σ
  rw [kummerChar_eq_zero_iff_smul_root_eq h u σ]
  constructor
  · intro hfix
    have h1 : σ • Units.mk0 y hy0 / Units.mk0 y hy0 = 1 := by rw [← hdiv, hfix, div_self']
    exact congrArg Units.val (div_eq_one.1 h1)
  · intro hσy
    have h2 : σ • Units.mk0 y hy0 = Units.mk0 y hy0 := Units.ext hσy
    have h1 : σ • h.root u / h.root u = 1 := by rw [hdiv, h2, div_self']
    exact div_eq_one.1 h1

/-- **The Kummer character is multiplied by the exponent at a power of a unit.** -/
theorem kummerChar_pow_units (a : (↥K)ˣ) (g : Gal(Ω/↥K)) (m : ℕ) :
    kummerChar h (a ^ m) g = m • kummerChar h a g := by
  induction m with
  | zero => rw [pow_zero, zero_smul, kummerChar_one_units]
  | succ m ih => rw [pow_succ, kummerChar_mul_units, ih, succ_nsmul]

end Character

/-! ### The classes at a place with a cyclic decomposition group -/

section Cyclic

variable {ℓ : ℕ} [NeZero ℓ] {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]
  {K : IntermediateField k Ω} [NumberField ↥K] [IsGalois ↥K Ω] {ζ : ↥K}
  {hζ : IsPrimitiveRoot ζ ℓ} {E : IntermediateField k Ω} {P : Ideal (𝓞 Ω)} [P.IsPrime]
  {w : HeightOneSpectrum (𝓞 ↥K)} {τ : Gal(Ω/↥K)}

attribute [local instance] zmodTrivialAction

variable (h : IsKummerData ↥K Ω (Multiplicative (ZMod ℓ)) (zmodRootHom hζ) ℓ)

omit [NumberField ↥K] [IsGalois ↥K Ω] in
variable (K E P) in
/-- **The decomposition group at a prime acts on an auxiliary field through the powers of a single
automorphism lying in the inertia group**: every automorphism of the closure over the level fixing
the prime agrees on the field with a power of that one. -/
def IsCyclicInertiaAt : Prop :=
  ∃ τ ∈ Ideal.inertia Gal(Ω/↥K) P,
    ∀ σ ∈ stabilizer Gal(Ω/↥K) P, ∃ i : ℤ, ∀ y ∈ E, σ y = (τ ^ i) y

omit [NumberField ↥K] [P.IsPrime] in
/-- **The Kummer character of a unit the auxiliary field turns into a power vanishes on the whole
decomposition group as soon as it vanishes at a generator of the action on the field**, the
character of such a unit depending on an automorphism only through its action on the field. -/
theorem kummerChar_eq_zero_of_mem_stabilizer_of_cyclic
    (hcyc : ∀ σ ∈ stabilizer Gal(Ω/↥K) P, ∃ i : ℤ, ∀ y ∈ E, σ y = (τ ^ i) y) {u : (↥K)ˣ}
    (hu : u ∈ levelPowerUnits ℓ K E) (h0 : kummerChar h u τ = 0) {σ : Gal(Ω/↥K)}
    (hσ : σ ∈ stabilizer Gal(Ω/↥K) P) : kummerChar h u σ = 0 := by
  obtain ⟨y, hyE, hy⟩ := hu
  have hy0 : y ≠ 0 := ne_zero_of_pow_eq_algebraMap hy
  obtain ⟨i, hi⟩ := hcyc σ hσ
  refine (kummerChar_eq_zero_iff_apply_eq_self h hy0 hy σ).2 ?_
  rw [hi y hyE]
  exact zpow_apply_eq_self_of_apply_eq_self
    ((kummerChar_eq_zero_iff_apply_eq_self h hy0 hy τ).1 h0) i

/-- **Two units the auxiliary field turns into powers whose Kummer characters agree at a generator
of the action on the field have the same class at the place**, their quotient being a unit the field
turns into a power whose character vanishes on the whole decomposition group. -/
theorem localClassHom_eq_of_kummerChar_eq (hv : w.asIdeal = Ideal.under (𝓞 ↥K) P)
    (hcyc : ∀ σ ∈ stabilizer Gal(Ω/↥K) P, ∃ i : ℤ, ∀ y ∈ E, σ y = (τ ^ i) y) {u u' : (↥K)ˣ}
    (hu : u ∈ levelPowerUnits ℓ K E) (hu' : u' ∈ levelPowerUnits ℓ K E)
    (hchar : kummerChar h u τ = kummerChar h u' τ) :
    localClassHom w ℓ u = localClassHom w ℓ u' := by
  refine localClassHom_eq_of_forall_kummerChar_eq h hv fun σ hσ => ?_
  refine (kummerChar_eq_iff_kummerChar_div_eq_zero h u u' σ).2 ?_
  refine kummerChar_eq_zero_of_mem_stabilizer_of_cyclic h hcyc
    (Subgroup.mul_mem _ hu (Subgroup.inv_mem _ hu')) ?_ hσ
  exact (kummerChar_eq_iff_kummerChar_div_eq_zero h u u' τ).1 hchar

/-- **The classes at a place of the units an auxiliary field turns into exponent-th powers are
trivial or generated by the class of one of them**, as soon as the decomposition group at a prime
above the place acts on the field through the powers of a single automorphism.

Either every such unit has vanishing character at the generator, and then trivial class at the
place; or one of them has a nonzero character there, and since the characters live in a field of
residues every other unit has the character of a power of that one, hence its class. -/
theorem levelPowerClasses_eq_bot_or_exists_zpowers (hℓ : ℓ.Prime)
    (hv : w.asIdeal = Ideal.under (𝓞 ↥K) P)
    (hcyc : ∀ σ ∈ stabilizer Gal(Ω/↥K) P, ∃ i : ℤ, ∀ y ∈ E, σ y = (τ ^ i) y) :
    levelPowerClasses ℓ K E w = ⊥ ∨
      ∃ u₀ ∈ levelPowerUnits ℓ K E, kummerChar h u₀ τ ≠ 0 ∧
        levelPowerClasses ℓ K E w = Subgroup.zpowers (localClassHom w ℓ u₀) := by
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  by_cases hall : ∀ u ∈ levelPowerUnits ℓ K E, kummerChar h u τ = 0
  · refine Or.inl ((Subgroup.map_eq_bot_iff _).2 fun u hu => MonoidHom.mem_ker.2 ?_)
    exact localClassHom_eq_one_of_forall_mem_stabilizer h hv fun σ hσ =>
      kummerChar_eq_zero_of_mem_stabilizer_of_cyclic h hcyc hu (hall u hu) hσ
  · push_neg at hall
    obtain ⟨u₀, hu₀, hne⟩ := hall
    refine Or.inr ⟨u₀, hu₀, hne, le_antisymm ?_ ?_⟩
    · refine (Subgroup.map_le_iff_le_comap (f := localClassHom w ℓ)).2 fun u hu => ?_
      obtain ⟨m, hm⟩ : ∃ m : ℕ, kummerChar h (u₀ ^ m) τ = kummerChar h u τ := by
        refine ⟨(kummerChar h u τ * (kummerChar h u₀ τ)⁻¹).val, ?_⟩
        rw [kummerChar_pow_units, nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id,
          inv_mul_cancel_right₀ hne]
      refine Subgroup.mem_comap.2 ?_
      rw [localClassHom_eq_of_kummerChar_eq h hv hcyc hu (Subgroup.pow_mem _ hu₀ m) hm.symm,
        _root_.map_pow]
      exact Subgroup.pow_mem _ (Subgroup.mem_zpowers _) m
    · rw [Subgroup.zpowers_le]
      exact localClassHom_mem_levelPowerClasses w hu₀

include h in
/-- **A place whose decomposition group acts on the auxiliary field through the powers of one
inertia element, and which carries a uniformiser fixed by its decomposition group, satisfies the
alternative.**

The classes the field turns into powers there are trivial or generated by the class of a single
unit, and in the second case the generator is ramified: the character of a unit whose order at the
place is a multiple of the exponent vanishes on inertia, and the generating unit was chosen with a
nonzero character at an element of inertia. -/
theorem isScholzPlace_of_isCyclicInertiaAt (hℓ : ℓ.Prime) (hℓP : (ℓ : 𝓞 Ω) ∉ P)
    (hv : w.asIdeal = Ideal.under (𝓞 ↥K) P) (hfix : w ∈ fixedUniformizerPlaces k ↥K)
    (hcyc : IsCyclicInertiaAt K E P) : IsScholzPlace ℓ K E w := by
  obtain ⟨τ, hτ, hgen⟩ := hcyc
  rcases levelPowerClasses_eq_bot_or_exists_zpowers h hℓ hv hgen with hbot | ⟨u₀, _, hne, heq⟩
  · exact Or.inl ⟨hbot, hfix⟩
  · refine Or.inr ⟨localClassHom w ℓ u₀, heq, fun hmem => hne ?_⟩
    exact kummerChar_eq_zero_of_mem_inertia h hℓ hℓP hv
      ((localClassHom_mem_localUnramified_iff w u₀).1 hmem) hτ

end Cyclic

end InverseGalois.Shafarevich
