/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.PoitouTate.OrbitLine
import InverseGalois.CFT.PoitouTate.UniformizerLine
import InverseGalois.CFT.Profinite.Krull
import InverseGalois.Solvable.Shafarevich.FlatLineUnits

/-!
# The classes the auxiliary field turns into powers, and the line they are asked to lie on

The construction of a family of units named on an equivariant line of local classes costs a
reciprocity residue, and on a line that residue is the demand that, at each named place, the
classes of the units of the level which become exponent-th powers in the auxiliary field lie on the
line there.  Those units form a subgroup of the units of the level, carried into itself by the
automorphisms of the level because an automorphism of the level extends to one of the ambient
closure and the auxiliary field is carried into itself by that extension.  Their classes at a place
therefore form a subgroup of the local classes, and the subgroup at the image of a place is the
image of the subgroup at the place.

That makes the demand a comparison of two Galois stable families of subgroups, which is how the
construction is restated here: the line is given as a family of subgroups rather than as a family
of elements, the family is asked to be cyclic at every place, and the classes the auxiliary field
turns into powers are asked to lie in it at the named places.  A family of subgroups needs no
generator transported along the action, so the equivariance of the family is the whole of what the
two-place construction reads, and the generators it does read are produced from the cyclicity by
choice, independently at each place.

One such family is at hand with no hypothesis at all: at a place where the classes the auxiliary
field turns into powers are a nontrivial cyclic group, take that group; everywhere else take the
line cut out by the invariant family of uniformisers.  Both branches are equivariant and the
condition telling them apart is too, so the family is.  What it then asks of a named place is the
classical alternative: either the auxiliary field turns no class there into a power beyond the
trivial one and the place carries a uniformiser fixed by its decomposition group, or the classes it
does turn into powers are generated by a single ramified class.

## Main definitions

* `InverseGalois.Shafarevich.levelPowerUnits`: the units of the level which the auxiliary field
  turns into an exponent-`n` power.
* `InverseGalois.Shafarevich.levelPowerClasses`: their classes at a place.
* `InverseGalois.Shafarevich.scholzSubgroup`: **the line of local classes named by the auxiliary
  field.**
* `InverseGalois.Shafarevich.IsScholzPlace`: **the alternative asked of a named place.**

## Main results

* `InverseGalois.Shafarevich.levelPowerClasses_smul`: the classes the auxiliary field turns into
  powers at the image of a place are the image of those at the place.
* `InverseGalois.Shafarevich.scholzSubgroup_smul`: **the line named by the auxiliary field is
  equivariant.**
* `InverseGalois.Shafarevich.exists_units_levelPower_diagonal`: **one unit per named place,
  ramified at its own place and trivial at the others**, in exchange for an equivariant family of
  cyclic subgroups of local classes which is ramified at the named places and contains the classes
  the auxiliary field turns into powers there.
* `InverseGalois.Shafarevich.exists_units_scholz_diagonal`: **the same, in exchange for the
  classical alternative at each named place and nothing else.**

## Tags

Shafarevich's theorem, embedding problem, Kummer theory, local class, line, reciprocity
-/

namespace InverseGalois.Shafarevich

open InverseGalois.CFT IsDedekindDomain IntermediateField MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

set_option maxHeartbeats 1600000

/-! ### The units the auxiliary field turns into powers -/

section LevelPower

variable {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]

/-- **The units of the level which the auxiliary field turns into an exponent-`n` power.** -/
def levelPowerUnits (n : ℕ) (K E : IntermediateField k Ω) : Subgroup (↥K)ˣ where
  carrier := {u | ∃ y : Ω, y ∈ E ∧ y ^ n = algebraMap ↥K Ω (u : ↥K)}
  mul_mem' := by
    rintro a b ⟨x, hxE, hx⟩ ⟨y, hyE, hy⟩
    refine ⟨x * y, E.mul_mem hxE hyE, ?_⟩
    rw [mul_pow, hx, hy, ← _root_.map_mul, ← Units.val_mul]
  one_mem' := ⟨1, E.one_mem, by simp⟩
  inv_mem' := by
    rintro a ⟨x, hxE, hx⟩
    refine ⟨x⁻¹, E.inv_mem hxE, ?_⟩
    rw [inv_pow, hx, ← map_inv₀, Units.val_inv_eq_inv_val]

theorem mem_levelPowerUnits {n : ℕ} {K E : IntermediateField k Ω} {u : (↥K)ˣ} :
    u ∈ levelPowerUnits n K E ↔ ∃ y : Ω, y ∈ E ∧ y ^ n = algebraMap ↥K Ω (u : ↥K) :=
  Iff.rfl

/-- **The classes at a place of the units of the level which the auxiliary field turns into an
exponent-`n` power.** -/
noncomputable def levelPowerClasses (n : ℕ) (K E : IntermediateField k Ω) [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) : Subgroup (localClasses v n) :=
  (levelPowerUnits n K E).map (localClassHom v n)

/-- The class of a unit the auxiliary field turns into a power lies in the subgroup those units cut
out at a place. -/
theorem localClassHom_mem_levelPowerClasses {n : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) {u : (↥K)ˣ} (hu : u ∈ levelPowerUnits n K E) :
    localClassHom v n u ∈ levelPowerClasses n K E v :=
  Subgroup.mem_map_of_mem _ hu

variable [IsGalois k Ω]

/-- **The units the auxiliary field turns into powers are carried into themselves by the
automorphisms of the level**, an automorphism of the level extending to one of the ambient closure
and the auxiliary field being carried into itself by that extension. -/
theorem galUnits_mem_levelPowerUnits {n : ℕ} {K E : IntermediateField k Ω} [Normal k ↥K]
    [Normal k ↥E] (σ : Gal(↥K/k)) {u : (↥K)ˣ} (hu : u ∈ levelPowerUnits n K E) :
    galUnits σ u ∈ levelPowerUnits n K E := by
  obtain ⟨y, hyE, hy⟩ := hu
  obtain ⟨ρ, hρ⟩ := restrictNormalHom_surjective_level (k := k) (K := Ω) K σ
  refine ⟨ρ y, ?_, ?_⟩
  · rw [← AlgEquiv.restrictNormalHom_apply (F := k) (K₁ := Ω) E ρ ⟨y, hyE⟩]
    exact (AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) E ρ ⟨y, hyE⟩).2
  · rw [← _root_.map_pow, hy, coe_galUnits_apply, ← hρ]
    exact (AlgEquiv.restrictNormalHom_apply (F := k) (K₁ := Ω) K ρ (u : ↥K)).symm

/-- **The classes the auxiliary field turns into powers at the image of a place are the image of
those at the place.** -/
theorem levelPowerClasses_smul {n : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    [Normal k ↥K] [Normal k ↥E] (σ : Gal(↥K/k)) (v : HeightOneSpectrum (𝓞 ↥K)) :
    levelPowerClasses n K E (σ • v)
      = (levelPowerClasses n K E v).map (localClassesGalEquiv σ v n).toMonoidHom := by
  refine le_antisymm (fun x hx => ?_) (fun x hx => ?_)
  · obtain ⟨u, hu, rfl⟩ := Subgroup.mem_map.1 hx
    refine Subgroup.mem_map.2 ⟨localClassHom v n (galUnits σ⁻¹ u),
      Subgroup.mem_map_of_mem _ (galUnits_mem_levelPowerUnits σ⁻¹ hu), ?_⟩
    show localClassesGalEquiv σ v n (localClassHom v n (galUnits σ⁻¹ u))
      = localClassHom (σ • v) n u
    rw [localClassesGalEquiv_localClassHom, galUnits_mul_apply, mul_inv_cancel, galUnits_one_eq]
  · obtain ⟨y, hy, rfl⟩ := Subgroup.mem_map.1 hx
    obtain ⟨u, hu, rfl⟩ := Subgroup.mem_map.1 hy
    exact Subgroup.mem_map.2 ⟨galUnits σ u, galUnits_mem_levelPowerUnits σ hu,
      (localClassesGalEquiv_localClassHom σ v n u).symm⟩

end LevelPower

/-! ### The line named by the auxiliary field -/

section Scholz

variable {k Ω : Type} [Field k] [Field Ω] [Algebra k Ω]

/-- A subgroup generated by an element lying outside another subgroup is not trivial. -/
theorem zpowers_ne_bot_of_notMem {G : Type*} [Group G] {H : Subgroup G} {d : G} (hd : d ∉ H) :
    Subgroup.zpowers d ≠ ⊥ := fun h0 => hd (by
  rw [Subgroup.zpowers_eq_bot.1 h0]
  exact one_mem H)

/-- An isomorphism of groups carries the subgroups generated by a single element onto the subgroups
generated by a single element. -/
theorem exists_zpowers_map_iff {G H : Type*} [Group G] [Group H] (e : G ≃* H) (S : Subgroup G) :
    (∃ d : H, S.map e.toMonoidHom = Subgroup.zpowers d) ↔ ∃ d : G, S = Subgroup.zpowers d := by
  have hcomp : e.symm.toMonoidHom.comp e.toMonoidHom = MonoidHom.id G :=
    MonoidHom.ext fun x => e.symm_apply_apply x
  have hround : (S.map e.toMonoidHom).map e.symm.toMonoidHom = S := by
    rw [Subgroup.map_map, hcomp, Subgroup.map_id]
  constructor
  · rintro ⟨d, hd⟩
    refine ⟨e.symm d, ?_⟩
    rw [← hround, hd, MonoidHom.map_zpowers]
    rfl
  · rintro ⟨d, hd⟩
    refine ⟨e d, ?_⟩
    rw [hd, MonoidHom.map_zpowers]
    rfl

/-- **The classes the auxiliary field turns into powers form a nontrivial cyclic group at a
place.** -/
def IsLevelPowerLine (ℓ : ℕ) (K E : IntermediateField k Ω) [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) : Prop :=
  levelPowerClasses ℓ K E v ≠ ⊥ ∧
    ∃ d : localClasses v ℓ, levelPowerClasses ℓ K E v = Subgroup.zpowers d

open scoped Classical in
/-- **The line of local classes named by the auxiliary field**: the classes it turns into powers at
a place where those form a nontrivial cyclic group, and the line cut out by the invariant family of
uniformisers at every other place. -/
noncomputable def scholzSubgroup (ℓ : ℕ) (K E : IntermediateField k Ω) [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) : Subgroup (localClasses v ℓ) :=
  if IsLevelPowerLine ℓ K E v then levelPowerClasses ℓ K E v
  else Subgroup.zpowers (uniformizerLine k ℓ v)

theorem scholzSubgroup_of_isLevelPowerLine {ℓ : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    {v : HeightOneSpectrum (𝓞 ↥K)} (h : IsLevelPowerLine ℓ K E v) :
    scholzSubgroup ℓ K E v = levelPowerClasses ℓ K E v :=
  if_pos h

theorem scholzSubgroup_of_not_isLevelPowerLine {ℓ : ℕ} {K E : IntermediateField k Ω}
    [NumberField ↥K] {v : HeightOneSpectrum (𝓞 ↥K)} (h : ¬ IsLevelPowerLine ℓ K E v) :
    scholzSubgroup ℓ K E v = Subgroup.zpowers (uniformizerLine k ℓ v) :=
  if_neg h

/-- **The line named by the auxiliary field is generated by a single class at every place.** -/
theorem exists_zpowers_scholzSubgroup {ℓ : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) :
    ∃ d : localClasses v ℓ, scholzSubgroup ℓ K E v = Subgroup.zpowers d := by
  by_cases h : IsLevelPowerLine ℓ K E v
  · obtain ⟨d, hd⟩ := h.2
    exact ⟨d, (scholzSubgroup_of_isLevelPowerLine h).trans hd⟩
  · exact ⟨uniformizerLine k ℓ v, scholzSubgroup_of_not_isLevelPowerLine h⟩

/-- **The classes the auxiliary field turns into powers lie on the line it names**, at a place
where they are a nontrivial cyclic group because the line is that group, and at a place where they
are trivial because they are then trivial. -/
theorem levelPowerClasses_le_scholzSubgroup {ℓ : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    {v : HeightOneSpectrum (𝓞 ↥K)} (h : IsLevelPowerLine ℓ K E v ∨ levelPowerClasses ℓ K E v = ⊥) :
    levelPowerClasses ℓ K E v ≤ scholzSubgroup ℓ K E v := by
  rcases h with h | h
  · exact (scholzSubgroup_of_isLevelPowerLine h).ge
  · rw [h]
    exact bot_le

variable [IsGalois k Ω]

/-- **A place is named by the auxiliary field exactly when its image under an automorphism of the
level is.** -/
theorem isLevelPowerLine_smul {ℓ : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    [Normal k ↥K] [Normal k ↥E] (σ : Gal(↥K/k)) (v : HeightOneSpectrum (𝓞 ↥K)) :
    IsLevelPowerLine ℓ K E (σ • v) ↔ IsLevelPowerLine ℓ K E v := by
  have hmap := levelPowerClasses_smul (n := ℓ) (K := K) (E := E) σ v
  have hinj : Function.Injective ⇑(localClassesGalEquiv σ v ℓ).toMonoidHom :=
    (localClassesGalEquiv σ v ℓ).injective
  constructor
  · rintro ⟨hne, hcyc⟩
    rw [hmap] at hne hcyc
    exact ⟨fun h0 => hne (by rw [h0, Subgroup.map_bot]),
      (exists_zpowers_map_iff (localClassesGalEquiv σ v ℓ) _).1 hcyc⟩
  · rintro ⟨hne, hcyc⟩
    refine ⟨fun h0 => hne ?_, ?_⟩
    · rw [hmap] at h0
      exact (Subgroup.map_eq_bot_iff_of_injective _ hinj).1 h0
    · rw [hmap]
      exact (exists_zpowers_map_iff (localClassesGalEquiv σ v ℓ) _).2 hcyc

/-- **The line named by the auxiliary field is equivariant**: the line at the image of a place is
the image of the line at the place.  Both branches of the naming are, and so is the condition
telling them apart. -/
theorem scholzSubgroup_smul {ℓ : ℕ} {K E : IntermediateField k Ω} [NumberField ↥K]
    [Normal k ↥K] [Normal k ↥E] (σ : Gal(↥K/k)) (v : HeightOneSpectrum (𝓞 ↥K)) :
    scholzSubgroup ℓ K E (σ • v)
      = (scholzSubgroup ℓ K E v).map (localClassesGalEquiv σ v ℓ).toMonoidHom := by
  by_cases h : IsLevelPowerLine ℓ K E v
  · rw [scholzSubgroup_of_isLevelPowerLine ((isLevelPowerLine_smul σ v).2 h),
      scholzSubgroup_of_isLevelPowerLine h, levelPowerClasses_smul σ v]
  · rw [scholzSubgroup_of_not_isLevelPowerLine (fun hc => h ((isLevelPowerLine_smul σ v).1 hc)),
      scholzSubgroup_of_not_isLevelPowerLine h, MonoidHom.map_zpowers]
    exact congrArg Subgroup.zpowers (localClassesGalEquiv_uniformizerLine ℓ σ v).symm

/-- **The alternative asked of a place named by a prescription**: either the auxiliary field turns
no class of the level there into an exponent-th power beyond the trivial one and the place carries
a uniformiser fixed by its decomposition group, or the classes it does turn into powers there are
generated by a single ramified class. -/
def IsScholzPlace (ℓ : ℕ) (K E : IntermediateField k Ω) [NumberField ↥K]
    (v : HeightOneSpectrum (𝓞 ↥K)) : Prop :=
  (levelPowerClasses ℓ K E v = ⊥ ∧ v ∈ fixedUniformizerPlaces k ↥K) ∨
    ∃ d : localClasses v ℓ,
      levelPowerClasses ℓ K E v = Subgroup.zpowers d ∧ d ∉ localUnramified v ℓ

end Scholz

/-! ### The diagonal over a family of cyclic subgroups -/

section Diagonal

variable {k Ω : Type} [Field k] [NumberField k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  [IsAlgClosed Ω]

/-- **One unit per named place, ramified at its own place and trivial at the others, in exchange
for an equivariant family of cyclic subgroups of local classes.**

The line is given as a family of subgroups, one at every place, carried to the family at the image
of a place by the identification of the classes there; no generator has to be transported, so the
generators the two-place construction reads off are produced from the cyclicity independently at
each place, and whichever generator is at hand answers.  What is asked at a named place is that the
subgroup there be generated by a ramified class, and that the classes of the units of the level
which the auxiliary field turns into exponent-th powers lie in it; nothing at all is asked anywhere
else. -/
theorem exists_units_levelPower_diagonal {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) (hodd : 2 < ℓ)
    (K : IntermediateField k Ω) [FiniteDimensional k ↥K] [IsGalois k ↥K] [NumberField ↥K]
    {Pc Ec : HeightOneSpectrum (𝓞 ↥K) → ℕ}
    (hres : ∀ v : HeightOneSpectrum (𝓞 ↥K), HasResidueChar (v.adicCompletion ↥K) (Pc v) (Ec v))
    {ζ : ↥K} (hζ : IsPrimitiveRoot ζ ℓ) (E : IntermediateField k Ω)
    (hEfin : FiniteDimensional k ↥E) (hEgal : IsGalois k ↥E) (hKE : K ≤ E)
    {P : (v : HeightOneSpectrum (𝓞 ↥K)) → Subgroup (localClasses v ℓ)}
    (hPgal : ∀ (σ : Gal(↥K/k)) (v : HeightOneSpectrum (𝓞 ↥K)),
      P (σ • v) = (P v).map (localClassesGalEquiv σ v ℓ).toMonoidHom)
    (hPcyc : ∀ v : HeightOneSpectrum (𝓞 ↥K), ∃ d : localClasses v ℓ, P v = Subgroup.zpowers d)
    {ι : Type} [Fintype ι] (w : ι → HeightOneSpectrum (𝓞 ↥K))
    (hdist : ∀ μ ν : ι, μ ≠ ν → ∀ σ : Gal(↥K/k), σ • w μ ≠ w ν)
    (Tz : Finset (HeightOneSpectrum (𝓞 ↥K))) (hTz : ∀ μ : ι, w μ ∉ Tz)
    (hℓw : ∀ μ : ι, (ℓ : 𝓞 ↥K) ∉ (w μ).asIdeal)
    (hPram : ∀ μ : ι, ∃ d : localClasses (w μ) ℓ,
      P (w μ) = Subgroup.zpowers d ∧ d ∉ localUnramified (w μ) ℓ)
    (hPscholz : ∀ μ : ι, levelPowerClasses ℓ K E (w μ) ≤ P (w μ)) :
    ∃ Z : ι → (↥K)ˣ,
      (∀ μ : ι, ¬ (ℓ : ℤ) ∣ placeValue (w μ) (Z μ)) ∧
      (∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), v ∈ Tz → localClassHom v ℓ (Z μ) = 1) ∧
      (∀ (μ : ι) (σ : Gal(↥K/k)), σ • w μ ≠ w μ → localClassHom (σ • w μ) ℓ (Z μ) = 1) ∧
      (∀ μ ν : ι, ν ≠ μ → ∀ σ : Gal(↥K/k), localClassHom (σ • w ν) ℓ (Z μ) = 1) ∧
      ∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), ¬ (ℓ : ℤ) ∣ placeValue v (Z μ) →
        (∃ (ν : ι) (σ : Gal(↥K/k)), v = σ • w ν) ∨
          ∀ Q : Ideal (𝓞 Ω), Q.IsPrime → Q ≠ ⊥ → Ideal.under (𝓞 ↥K) Q = v.asIdeal →
            stabilizer Gal(Ω/k) Q ≤ E.fixingSubgroup := by
  classical
  choose D hD using hPcyc
  refine exists_units_line_diagonal_of_scholz hℓ hodd K hres hζ E hEfin hEgal hKE (D := D) ?_ w
    hdist Tz hTz hℓw ?_ ?_
  · intro σ v
    rw [← hD (σ • v), hPgal σ v, hD v, MonoidHom.map_zpowers]
    rfl
  · intro μ a ha
    obtain ⟨d, hdP, hdram⟩ := hPram μ
    rw [← localClassHom_mem_localUnramified_iff, ha]
    intro hmem
    refine hdram ?_
    have hle : Subgroup.zpowers (D (w μ)) ≤ localUnramified (w μ) ℓ := Subgroup.zpowers_le.2 hmem
    rw [← hD (w μ), hdP] at hle
    exact hle (Subgroup.mem_zpowers d)
  · intro μ u hu
    rw [← hD (w μ)]
    exact hPscholz μ (localClassHom_mem_levelPowerClasses (w μ) hu)

/-- **One unit per named place, ramified at its own place and trivial at the others, in exchange
for the classical alternative at each named place and nothing else.**

The line the units are named on is the one the auxiliary field names of itself, and the alternative
asked of a named place is exactly what makes that line cyclic, ramified and large enough there: the
auxiliary field either turns no class of the level at the place into an exponent-th power beyond
the trivial one, the place then carrying a uniformiser fixed by its decomposition group, or the
classes it does turn into powers there are generated by a single ramified class. -/
theorem exists_units_scholz_diagonal {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) (hodd : 2 < ℓ)
    (K : IntermediateField k Ω) [FiniteDimensional k ↥K] [IsGalois k ↥K] [NumberField ↥K]
    {Pc Ec : HeightOneSpectrum (𝓞 ↥K) → ℕ}
    (hres : ∀ v : HeightOneSpectrum (𝓞 ↥K), HasResidueChar (v.adicCompletion ↥K) (Pc v) (Ec v))
    {ζ : ↥K} (hζ : IsPrimitiveRoot ζ ℓ) (E : IntermediateField k Ω)
    (hEfin : FiniteDimensional k ↥E) (hEgal : IsGalois k ↥E) (hKE : K ≤ E)
    {ι : Type} [Fintype ι] (w : ι → HeightOneSpectrum (𝓞 ↥K))
    (hdist : ∀ μ ν : ι, μ ≠ ν → ∀ σ : Gal(↥K/k), σ • w μ ≠ w ν)
    (Tz : Finset (HeightOneSpectrum (𝓞 ↥K))) (hTz : ∀ μ : ι, w μ ∉ Tz)
    (hℓw : ∀ μ : ι, (ℓ : 𝓞 ↥K) ∉ (w μ).asIdeal)
    (hscholz : ∀ μ : ι, IsScholzPlace ℓ K E (w μ)) :
    ∃ Z : ι → (↥K)ˣ,
      (∀ μ : ι, ¬ (ℓ : ℤ) ∣ placeValue (w μ) (Z μ)) ∧
      (∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), v ∈ Tz → localClassHom v ℓ (Z μ) = 1) ∧
      (∀ (μ : ι) (σ : Gal(↥K/k)), σ • w μ ≠ w μ → localClassHom (σ • w μ) ℓ (Z μ) = 1) ∧
      (∀ μ ν : ι, ν ≠ μ → ∀ σ : Gal(↥K/k), localClassHom (σ • w ν) ℓ (Z μ) = 1) ∧
      ∀ (μ : ι) (v : HeightOneSpectrum (𝓞 ↥K)), ¬ (ℓ : ℤ) ∣ placeValue v (Z μ) →
        (∃ (ν : ι) (σ : Gal(↥K/k)), v = σ • w ν) ∨
          ∀ Q : Ideal (𝓞 Ω), Q.IsPrime → Q ≠ ⊥ → Ideal.under (𝓞 ↥K) Q = v.asIdeal →
            stabilizer Gal(Ω/k) Q ≤ E.fixingSubgroup := by
  haveI : Normal k ↥E := hEgal.to_normal
  refine exists_units_levelPower_diagonal hℓ hodd K hres hζ E hEfin hEgal hKE
    (P := scholzSubgroup ℓ K E) scholzSubgroup_smul exists_zpowers_scholzSubgroup w hdist Tz hTz
    hℓw (fun μ => ?_) fun μ => ?_
  · rcases hscholz μ with ⟨hbot, hfix⟩ | ⟨d, hd, hdram⟩
    · exact ⟨uniformizerLine k ℓ (w μ), scholzSubgroup_of_not_isLevelPowerLine
        (fun hc => hc.1 hbot), uniformizerLine_notMem_localUnramified hℓ.one_lt hfix⟩
    · have hline : IsLevelPowerLine ℓ K E (w μ) :=
        ⟨by rw [hd]; exact zpowers_ne_bot_of_notMem hdram, d, hd⟩
      exact ⟨d, (scholzSubgroup_of_isLevelPowerLine hline).trans hd, hdram⟩
  · refine levelPowerClasses_le_scholzSubgroup ?_
    rcases hscholz μ with ⟨hbot, -⟩ | ⟨d, hd, hdram⟩
    · exact Or.inr hbot
    · exact Or.inl ⟨by rw [hd]; exact zpowers_ne_bot_of_notMem hdram, d, hd⟩

end Diagonal

end InverseGalois.Shafarevich
