/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Shafarevich.FlatDiagonalUnits
import InverseGalois.Solvable.Shafarevich.Main

/-!
# Shafarevich's theorem

Every finite solvable group is a Galois group over `ℚ`.

Everything the theorem rests on has been built: the group-theoretic reduction carries it to split
embedding problems with a kernel of prime power order, the roots of unity may be assumed to lie in
the base realization, the climb up the `p`-central series turns such a problem into a ladder of
one-step problems over a group of letters, and the step of the ladder is bought by the arithmetic
of a level — a diagonal of units subject to local conditions at places chosen to confine the
obstruction, and the sharp prescription one field up which the orthogonality of the naming makes.
This file is the assembly: the step holds at every prime, so the ladder climbs, so the split
problems with prime power kernel are solvable, so every finite solvable group is realized.

## Main results

* `Shafarevich.splitPrimePowerEP` — **every split embedding problem over `ℚ` whose kernel has prime
  power order is solvable.**
* `Shafarevich.isInverseGalois_of_isSolvable` — **Shafarevich's theorem**: every finite solvable
  group is a Galois group over `ℚ`.

## Tags

Shafarevich's theorem, inverse Galois problem, solvable group, embedding problem
-/

namespace Shafarevich

open InverseGalois.Shafarevich

/-- **Every split embedding problem over `ℚ` whose kernel has prime power order is solvable.**

The step of the ladder is a theorem at every prime, and a base realization may be enlarged until it
contains the roots of unity the step wants, so the ladder climbs the `p`-central series of the
kernel from the trivial group all the way up. -/
theorem splitPrimePowerEP : SplitPrimePowerEP :=
  splitPrimePowerEP_of_genericLevelStepEPRoots fun ℓ hℓ =>
    haveI : Fact ℓ.Prime := ⟨hℓ⟩
    haveI : NeZero ℓ := ⟨hℓ.ne_zero⟩
    genericLevelStepEPRoots ℓ

/-- **Shafarevich's theorem: every finite solvable group is a Galois group over `ℚ`.**

A nontrivial finite solvable group is generated by a nilpotent normal subgroup together with a
proper subgroup, and the proper subgroup is realized by induction on the order; the split embedding
problem that supplements it has nilpotent kernel, which the Sylow decomposition breaks into kernels
of prime power order. -/
theorem isInverseGalois_of_isSolvable (G : Type) [Group G] [Finite G] [IsSolvable G] :
    IsInverseGalois G :=
  isSolvable_isInverseGalois_of_splitPrimePowerEP splitPrimePowerEP G

end Shafarevich
