/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.KummerIndep
import InverseGalois.Solvable.WreathExtension
import InverseGalois.Solvable.Shafarevich.RadicalTower

/-!
# The Galois group of an orbit of radicals is a wreath product

Let `N / F` be a finite Galois extension containing a primitive `p`-th root of unity, and adjoin a
`p`-th root of every conjugate of an element `b` of `N` whose orbit is independent modulo `p`-th
powers.  The resulting field `L` is Galois over `F`, and its Galois group is the regular wreath
product of the group of `p`-th roots of unity by `Gal(N/F)`.

The kernel of the restriction `Gal(L/F) → Gal(N/F)` is `Gal(L/N)`, which Kummer theory identifies
with the functions from the orbit to the `p`-th roots of unity.  Since the orbit is a principal
homogeneous space for `Gal(N/F)`, this is a group of functions on the quotient, and the general
recognition theorem for such extensions applies.  Its hypothesis is that the coordinate family of
an element of the kernel — the value of the Kummer character at the first radical, evaluated after
conjugating by each element of the quotient — runs bijectively over all of the functions.  That is
checked by counting: the coordinate map is injective because an element of the kernel with trivial
coordinates fixes every conjugate of the first radical, hence, up to roots of unity that it also
fixes, every radical; and both sides have `p ^ |Gal(N/F)|` elements.

## Main results

* `InverseGalois.Shafarevich.kerEquivAut` — the automorphisms restricting to the identity on a
  normal intermediate field are the automorphisms over it.
* `InverseGalois.Shafarevich.nonempty_mulEquiv_wreath_of_setup` — the Galois group of an orbit of
  radicals is a regular wreath product.
* `InverseGalois.Shafarevich.nonempty_mulEquiv_wreath_conjRadExt` — the same statement for the
  concrete multi-radical extension attached to an element with independent conjugates.

## Tags

wreath product, Kummer theory, Galois group, radical extension
-/

noncomputable section

open Polynomial IntermediateField Rigidity.RET.Kummer

namespace InverseGalois.Shafarevich

/-! ### Automorphisms trivial on a normal intermediate field -/

section Kernel

variable (F : Type*) [Field F] (N : Type*) [Field N] [Algebra F N] [Normal F N]
  (L : Type*) [Field L] [Algebra F L] [Algebra N L] [IsScalarTower F N L]

/-- Lying in the kernel of the restriction to a normal intermediate field means fixing that field
pointwise. -/
theorem mem_ker_restrictNormalHom_iff {k : L ≃ₐ[F] L} :
    k ∈ (AlgEquiv.restrictNormalHom (F := F) (K₁ := L) N).ker ↔
      ∀ y : N, k (algebraMap N L y) = algebraMap N L y := by
  rw [MonoidHom.mem_ker]
  refine ⟨fun h y => ?_, fun h => ?_⟩
  · have h1 := AlgEquiv.restrictNormal_commutes k N y
    rw [show k.restrictNormal N = AlgEquiv.restrictNormalHom N k from rfl, h] at h1
    simpa using h1.symm
  · refine AlgEquiv.ext fun y => (algebraMap N L).injective ?_
    show algebraMap N L (k.restrictNormal N y) = algebraMap N L ((1 : N ≃ₐ[F] N) y)
    rw [AlgEquiv.restrictNormal_commutes, h]
    rfl

/-- **The automorphisms restricting to the identity on a normal intermediate field are exactly the
automorphisms over that field.** -/
def kerEquivAut :
    ↥(AlgEquiv.restrictNormalHom (F := F) (K₁ := L) N).ker ≃* (L ≃ₐ[N] L) where
  toFun k := { (k : L ≃ₐ[F] L).toRingEquiv with
    commutes' := (mem_ker_restrictNormalHom_iff F N L).mp k.2 }
  invFun σ := ⟨σ.restrictScalars F, (mem_ker_restrictNormalHom_iff F N L).mpr σ.commutes⟩
  left_inv _ := by ext; rfl
  right_inv _ := by ext; rfl
  map_mul' _ _ := by ext; rfl

@[simp] theorem kerEquivAut_apply
    (k : ↥(AlgEquiv.restrictNormalHom (F := F) (K₁ := L) N).ker) (y : L) :
    kerEquivAut F N L k y = (k : L ≃ₐ[F] L) y := rfl

end Kernel

/-! ### The Galois group of a Galois orbit of radicals -/

section Wreath

variable {F N L : Type*} [Field F] [Field N] [Field L] [Algebra F N] [Algebra F L] [Algebra N L]
  [IsScalarTower F N L] [FiniteDimensional F N] [IsGalois F N] [IsGalois F L] [CharZero N]
  {p : ℕ} [NeZero p]

/-- **The Galois group of an extension generated by `p`-th roots of a Galois orbit is the regular
wreath product of the `p`-th roots of unity by the Galois group of the base.** -/
theorem nonempty_mulEquiv_wreath_of_setup (S : Setup N L (N ≃ₐ[F] N) p)
    (hg : ∀ σ : N ≃ₐ[F] N, S.g σ = σ (S.g 1)) :
    Nonempty ((L ≃ₐ[F] L) ≃* rootsOfUnity p L ≀ᵣ (N ≃ₐ[F] N)) := by
  classical
  haveI : IsGalois N L := S.isGalois
  haveI : FiniteDimensional N L := S.finiteDimensional
  haveI : FiniteDimensional F L := Module.Finite.trans (R := F) N L
  set f : (L ≃ₐ[F] L) →* (N ≃ₐ[F] N) := AlgEquiv.restrictNormalHom N with hfdef
  have hf : Function.Surjective f := AlgEquiv.restrictNormalHom_surjective L
  set e : ↥f.ker ≃* (L ≃ₐ[N] L) := kerEquivAut F N L with hedef
  haveI : IsMulCommutative ↥f.ker := ⟨⟨fun a c => (e.trans S.galEquiv).injective (by
    rw [map_mul, map_mul, mul_comm])⟩⟩
  set ρ : (N ≃ₐ[F] N) →* MulAut ↥f.ker := RegularWreathProduct.quotientConj f hf with hρdef
  have hρapp : ∀ (x : L ≃ₐ[F] L) (m : ↥f.ker),
      ((ρ (f x) m : ↥f.ker) : L ≃ₐ[F] L) = x * (m : L ≃ₐ[F] L) * x⁻¹ :=
    RegularWreathProduct.quotientConj_apply f hf
  set ev : ↥f.ker →* rootsOfUnity p L :=
    (Pi.evalMonoidHom (fun _ : N ≃ₐ[F] N => rootsOfUnity p L) 1).comp
      (S.psi.comp e.toMonoidHom) with hevdef
  have hev : ∀ m : ↥f.ker, ev m = S.psi (e m) 1 := fun _ => rfl
  refine RegularWreathProduct.nonempty_mulEquiv_of_bijective_coord f hf ρ hρapp ev ?_
  -- the coordinate map, as a homomorphism
  set coord : ↥f.ker →* ((N ≃ₐ[F] N) → rootsOfUnity p L) :=
    { toFun := fun k u => ev (ρ u⁻¹ k)
      map_one' := by ext u; simp
      map_mul' := fun k l => by ext u; simp } with hcoorddef
  show Function.Bijective ⇑coord
  -- an element of the kernel with trivial first coordinate fixes the first radical
  have hev1 : ∀ m : ↥f.ker, ev m = 1 → (m : L ≃ₐ[F] L) (S.w 1) = S.w 1 := by
    intro m hm
    have h3 : ((S.psi (e m) 1 : Lˣ) : L) = 1 := by rw [← hev m, hm]; simp
    rw [S.psi_coe, div_eq_one_iff_eq (S.w_ne_zero 1)] at h3
    exact h3
  have hinjc : Function.Injective ⇑coord := by
    rw [injective_iff_map_eq_one]
    intro k hk
    -- every conjugate of the first radical is fixed
    have hfixinv : ∀ y : L ≃ₐ[F] L, (k : L ≃ₐ[F] L) (y⁻¹ (S.w 1)) = y⁻¹ (S.w 1) := by
      intro y
      have h0 : ev (ρ ((f y)⁻¹)⁻¹ k) = 1 := congrFun hk ((f y)⁻¹)
      rw [inv_inv] at h0
      have h1 := hev1 _ h0
      rw [hρapp y k, AlgEquiv.mul_apply, AlgEquiv.mul_apply] at h1
      refine y.injective ?_
      rw [h1, ← AlgEquiv.mul_apply, mul_inv_cancel, AlgEquiv.one_apply]
    have hfixw : ∀ x : L ≃ₐ[F] L, (k : L ≃ₐ[F] L) (x (S.w 1)) = x (S.w 1) := by
      intro x
      have h := hfixinv x⁻¹
      rwa [inv_inv] at h
    -- hence every radical is fixed
    have hfixall : ∀ u : N ≃ₐ[F] N, (k : L ≃ₐ[F] L) (S.w u) = S.w u := by
      intro u
      obtain ⟨x, hx⟩ := hf u
      have hxr : x.restrictNormal N = u := hx
      have hxpow : x (S.w 1) ^ p = algebraMap N L (S.g u) := by
        rw [← map_pow, S.w_pow 1, ← AlgEquiv.restrictNormal_commutes x N (S.g 1), hxr, hg u]
      have hgne : algebraMap N L (S.g u) ≠ 0 := by
        simpa using S.g_ne_zero u
      have hc : (x (S.w 1) / S.w u) ^ p = 1 := by
        rw [div_pow, hxpow, S.w_pow u]
        exact div_self hgne
      have hkc : (k : L ≃ₐ[F] L) (x (S.w 1) / S.w u) = x (S.w 1) / S.w u :=
        S.map_eq_of_pow_eq_one (e k) hc
      have hx1 : x (S.w 1) ≠ 0 := by simpa using S.w_ne_zero 1
      have hkw : (k : L ≃ₐ[F] L) (S.w u) ≠ 0 := by simpa using S.w_ne_zero u
      rw [map_div₀, hfixw x, div_eq_div_iff hkw (S.w_ne_zero u)] at hkc
      exact (mul_left_cancel₀ hx1 hkc).symm
    -- so the Kummer character is trivial
    have hpsi : S.psi (e k) = 1 := by
      funext u
      refine Subtype.ext (Units.ext ?_)
      have hfu : (e k) (S.w u) = S.w u := hfixall u
      rw [S.psi_coe, hfu, div_self (S.w_ne_zero u)]
      simp
    have hek : e k = 1 := S.psi_injective (by rw [hpsi, map_one])
    exact e.injective (hek.trans (map_one e).symm)
  -- both sides have `p ^ |Gal(N/F)|` elements
  have hcard : Nat.card ↥f.ker = Nat.card ((N ≃ₐ[F] N) → rootsOfUnity p L) := by
    haveI := S.hasEnoughRootsOfUnity
    rw [Nat.card_congr e.toEquiv, S.card_aut, Nat.card_pi, Finset.prod_const,
      HasEnoughRootsOfUnity.natCard_rootsOfUnity L p, Finset.card_univ]
  exact (Nat.bijective_iff_injective_and_card ⇑coord).mpr ⟨hinjc, hcard⟩

end Wreath

/-! ### The concrete multi-radical extension -/

section ConjRad

variable {F : Type*} [Field F] [CharZero F] {N : Type*} [Field N] [Algebra F N]
  [FiniteDimensional F N] [IsGalois F N] {p : ℕ} [NeZero p] {zeta b : N}

/-- The Kummer data attached to the Galois orbit of a radicand. -/
def orbitSetup (hz : IsPrimitiveRoot zeta p) (hne : ∀ σ : N ≃ₐ[F] N, σ b ≠ 0)
    (hindep : ∀ (m : (N ≃ₐ[F] N) → ℤ) (y : N), y ≠ 0 → y ^ p = ∏ σ, (σ b) ^ m σ →
      ∀ σ, (p : ℤ) ∣ m σ) :
    Setup N (ConjRadExt F p b) (N ≃ₐ[F] N) p :=
  setupOfIndep zeta hz (fun σ : N ≃ₐ[F] N => σ b) hne hindep

/-- **The Galois group of the multi-radical extension attached to an element with independent
conjugates is the regular wreath product of the `p`-th roots of unity by the Galois group of the
base.** -/
theorem nonempty_mulEquiv_wreath_conjRadExt (hz : IsPrimitiveRoot zeta p)
    (hne : ∀ σ : N ≃ₐ[F] N, σ b ≠ 0)
    (hinj : Function.Injective fun σ : N ≃ₐ[F] N => σ b)
    (hindep : ∀ (m : (N ≃ₐ[F] N) → ℤ) (y : N), y ≠ 0 → y ^ p = ∏ σ, (σ b) ^ m σ →
      ∀ σ, (p : ℤ) ∣ m σ) :
    Nonempty ((ConjRadExt F p b ≃ₐ[F] ConjRadExt F p b) ≃*
      rootsOfUnity p (ConjRadExt F p b) ≀ᵣ (N ≃ₐ[F] N)) := by
  haveI : CharZero N := charZero_of_injective_algebraMap (algebraMap F N).injective
  haveI : IsGalois F (ConjRadExt F p b) := isGalois_conjRadExt hinj
  refine nonempty_mulEquiv_wreath_of_setup (orbitSetup hz hne hindep) fun σ => ?_
  show σ b = σ ((1 : N ≃ₐ[F] N) b)
  rw [AlgEquiv.one_apply]

end ConjRad

end InverseGalois.Shafarevich

end
