/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.InertiaFixedField
import InverseGalois.CFT.Scholz.CompositumTransport
import InverseGalois.CFT.Scholz.DyadicShrink
import InverseGalois.CFT.Scholz.PGroupInertia
import InverseGalois.CFT.SqrtRamification
import InverseGalois.CFT.SqrtUnramified
import InverseGalois.Solvable.PCentralPow

/-!
# The inertia subgroup at a prime of a block

A strong Scholz realization carries a square root of the product of each of its blocks of primes,
and the sign by which an automorphism moves the `i`-th square root is the `i`-th coordinate of the
automorphism read in the free object.  This file computes the inertia subgroup at a prime `q` of
the `i`-th block in those coordinates: it is generated by an element whose coordinate vector is the
`i`-th standard basis vector.

Two independent inputs meet.  On the one hand `q` must move the `i`-th square root, because a
square root of a squarefree number divisible by `q` cannot live in a field where `q` is unramified;
applied to the fixed field of the kernel of the `i`-th sign character this says that the inertia
subgroup at `q` is not killed by that character.  On the other hand `q` cannot move the `j`-th
square root for `j ≠ i`, because that square root generates a field ramified only at `2` and at the
primes of the `j`-th block, none of which is `q`.  Since the inertia subgroup at an odd prime of a
`2`-extension is cyclic, its generator has coordinate vector the `i`-th standard basis vector.

Reading that through the power map along the lower `2`-central series identifies the part of the
inertia subgroup lying in the kernel of the projection to the previous class: it is generated by
the distinguished central element attached to the `i`-th generator.

## Main results

* `InverseGalois.CFT.exists_mem_inertia_sqrtSign_eq_one`: **a prime of a block moves the square
  root of that block.**
* `InverseGalois.CFT.sqrtSign_eq_zero_of_notMem`: **an odd prime outside a block fixes the square
  root of that block.**
* `InverseGalois.CFT.StrongScholzRealization.coordClass_inertia_generator`: **a generator of the
  inertia subgroup at an odd prime of the `i`-th block has the coordinates of the `i`-th
  distinguished generator.**
* `InverseGalois.CFT.StrongScholzRealization.map_inertia_inf_ker_proj`: **the part of the inertia
  subgroup at an odd prime of the `i`-th block lying over the previous class is generated by the
  distinguished central element attached to the `i`-th generator.**

## Tags

Scholz–Reichardt, inertia subgroup, block, square root, free `2`-group, Shafarevich
-/

open IntermediateField NumberField InverseGalois.NumberTheory

namespace InverseGalois.CFT

/-! ### Divisibility inside a set of primes -/

/-- A prime of a finite set of primes divides the product of the set exactly once. -/
theorem sq_not_dvd_prod_of_mem {s : Finset ℕ} (hs : ∀ p ∈ s, p.Prime) {q : ℕ} (hq : q ∈ s) :
    ¬ q ^ 2 ∣ ∏ p ∈ s, p := by
  have hqp : q.Prime := hs q hq
  have hsplit : q * ∏ p ∈ s.erase q, p = ∏ p ∈ s, p :=
    Finset.mul_prod_erase s (fun p => p) hq
  intro hdvd
  rw [← hsplit, sq] at hdvd
  have h2 : q ∣ ∏ p ∈ s.erase q, p := (mul_dvd_mul_iff_left hqp.ne_zero).mp hdvd
  obtain ⟨r, hr, hrd⟩ := (hqp.prime.dvd_finset_prod_iff (fun p => p)).mp h2
  exact (Finset.ne_of_mem_erase hr).symm
    ((Nat.prime_dvd_prime_iff_eq hqp (hs r (Finset.mem_of_mem_erase hr))).mp hrd)

/-- A prime outside a finite set of primes does not divide the product of the set. -/
theorem not_dvd_prod_of_notMem {s : Finset ℕ} (hs : ∀ p ∈ s, p.Prime) {q : ℕ} (hqp : q.Prime)
    (hq : q ∉ s) : ¬ q ∣ ∏ p ∈ s, p := by
  intro hdvd
  obtain ⟨r, hr, hrd⟩ := (hqp.prime.dvd_finset_prod_iff (fun p => p)).mp hdvd
  exact hq ((Nat.prime_dvd_prime_iff_eq hqp (hs r hr)).mp hrd ▸ hr)

/-! ### The sign character of a single square root -/

variable {F M : Type*} [Field F] [Field M] [Algebra F M] [CharZero M] {m : F} {u : M}

/-- The **sign character** of a single square root of a base element. -/
noncomputable def sqrtSignChar (hu : u ≠ 0) (hm : u ^ 2 = algebraMap F M m) :
    Gal(M/F) →* Multiplicative (ZMod 2) :=
  MonoidHom.mk' (fun σ => Multiplicative.ofAdd (sqrtSign u σ)) fun σ τ =>
    congrArg Multiplicative.ofAdd (sqrtSign_apply_mul hu hm σ τ)

theorem sqrtSignChar_apply (hu : u ≠ 0) (hm : u ^ 2 = algebraMap F M m) (σ : Gal(M/F)) :
    sqrtSignChar hu hm σ = Multiplicative.ofAdd (sqrtSign u σ) := rfl

theorem mem_ker_sqrtSignChar_iff (hu : u ≠ 0) (hm : u ^ 2 = algebraMap F M m) (σ : Gal(M/F)) :
    σ ∈ (sqrtSignChar hu hm).ker ↔ σ u = u := by
  rw [MonoidHom.mem_ker, sqrtSignChar_apply, ofAdd_eq_one, sqrtSign_eq_zero_iff]

/-! ### A prime of a block moves the square root of that block -/

variable {A : IntermediateField ℚ (AlgebraicClosure ℚ)} [NumberField ↥A] [IsGalois ℚ ↥A]
  {s : Finset ℕ} {v : ↥A} {q : ℕ}

/-- **A prime of a block moves the square root of that block.**  If every element of the inertia
subgroup at `q` fixed the square root, then `q` would be unramified in the fixed field of the
kernel of the sign character; but that fixed field contains a square root of a product of distinct
primes one of which is `q`. -/
theorem exists_mem_inertia_sqrtSign_eq_one (hs : ∀ p ∈ s, p.Prime) (hv : v ≠ 0)
    (hvsq : v ^ 2 = algebraMap ℚ ↥A ((∏ p ∈ s, p : ℕ) : ℚ)) (hq : q ∈ s)
    (P : Ideal (𝓞 ↥A)) [P.IsPrime] [P.LiesOver (Ideal.span {(q : ℤ)})] :
    ∃ σ ∈ Ideal.inertia Gal(↥A/ℚ) P, sqrtSign v σ = 1 := by
  by_contra hc
  push_neg at hc
  set ψ : Gal(↥A/ℚ) →* Multiplicative (ZMod 2) := sqrtSignChar hv hvsq with hψ
  have hker : ∀ σ ∈ Ideal.inertia Gal(↥A/ℚ) P, ψ σ = 1 := by
    intro σ hσ
    rw [hψ, ← MonoidHom.mem_ker, mem_ker_sqrtSignChar_iff]
    exact (sqrtSign_eq_zero_iff v σ).mp ((eq_zero_or_one_zmod_two _).resolve_right (hc σ hσ))
  have hunr : q ∉ ramifiedSet ↥(IntermediateField.fixedField ψ.ker) :=
    notMem_ramifiedSet_fixedField_ker_of_inertia ψ (hs q hq) P hker
  set E : IntermediateField ℚ ↥A := IntermediateField.fixedField ψ.ker with hE
  have hvmem : v ∈ E := by
    rw [hE, IntermediateField.mem_fixedField_iff]
    exact fun σ hσ => (mem_ker_sqrtSignChar_iff hv hvsq σ).mp hσ
  have hy : (⟨v, hvmem⟩ : ↥E) ^ 2 = (((∏ p ∈ s, p : ℕ) : ℤ) : ↥E) := by
    refine (IntermediateField.val E).injective ?_
    rw [map_pow, map_intCast]
    show v ^ 2 = _
    rw [hvsq]
    push_cast
    ring
  refine hunr (mem_ramifiedSet_of_sq_eq_intCast hy (hs q hq) ?_ ?_)
  · exact_mod_cast Finset.dvd_prod_of_mem id hq
  · intro hdvd
    refine sq_not_dvd_prod_of_mem hs hq ?_
    exact_mod_cast hdvd

/-! ### A prime outside a block fixes the square root of that block -/

/-- **An odd prime outside a block fixes the square root of that block.**  The square root
generates a field in which only `2` and the primes of the block ramify, so the inertia subgroup at
the prime fixes that field pointwise. -/
theorem sqrtSign_eq_zero_of_notMem (hs : ∀ p ∈ s, p.Prime)
    (hvsq : v ^ 2 = algebraMap ℚ ↥A ((∏ p ∈ s, p : ℕ) : ℚ)) (hqp : q.Prime) (hq2 : q ≠ 2)
    (hqs : q ∉ s) (P : Ideal (𝓞 ↥A)) [P.IsPrime] [P.LiesOver (Ideal.span {(q : ℤ)})]
    {σ : Gal(↥A/ℚ)} (hσ : σ ∈ Ideal.inertia Gal(↥A/ℚ) P) : sqrtSign v σ = 0 := by
  set b : ℕ := ∏ p ∈ s, p with hb
  set Y : AlgebraicClosure ℚ := (v : AlgebraicClosure ℚ) with hY
  have hYsq : Y ^ 2 = algebraMap ℚ (AlgebraicClosure ℚ) ((b : ℕ) : ℚ) := by
    have h := congrArg (IntermediateField.val A) hvsq
    rw [map_pow, AlgHom.commutes] at h
    exact h
  have hYnat : Y ^ 2 = ((b : ℕ) : AlgebraicClosure ℚ) := by rw [hYsq]; push_cast; ring
  set G : IntermediateField ℚ (AlgebraicClosure ℚ) := ℚ⟮Y⟯ with hG
  have hGA : G ≤ A := IntermediateField.adjoin_simple_le_iff.mpr v.2
  haveI : Normal ℚ ↥G := normal_adjoin_simple_of_sq_eq hYsq
  haveI : FiniteDimensional ℚ ↥G :=
    IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral Y)
  haveI : NumberField ↥G := ⟨⟩
  have hram : q ∉ ramifiedSet ↥(IntermediateField.restrict hGA) := by
    rw [ramifiedSet_restrict hGA]
    intro hmem
    rcases ramifiedSet_adjoin_sqrt_subset (prod_prime_ne_zero hs) hYnat hmem with h | h
    · exact hq2 h
    · exact not_dvd_prod_of_notMem hs hqp hqs (Nat.mem_primeFactors.mp h).2.1
  have hfix := inertia_le_fixingSubgroup (IntermediateField.restrict hGA) hqp P hram hσ
  have hvmem : v ∈ IntermediateField.restrict hGA :=
    (IntermediateField.mem_restrict hGA v).mpr (IntermediateField.mem_adjoin_simple_self ℚ Y)
  rw [IntermediateField.mem_fixingSubgroup_iff] at hfix
  rw [sqrtSign_eq_zero_iff]
  exact hfix v hvmem

/-! ### A cyclic inertia subgroup has a generator -/

/-- **The inertia subgroup at an odd prime of a `2`-extension is generated by one element.** -/
theorem exists_inertia_eq_zpowers (hqp : q.Prime) (hq2 : q ≠ 2)
    (hG : IsPGroup 2 Gal(↥A/ℚ)) (P : Ideal (𝓞 ↥A)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] :
    ∃ x : Gal(↥A/ℚ), Ideal.inertia Gal(↥A/ℚ) P = Subgroup.zpowers x := by
  haveI := isCyclic_inertia_of_isPGroup Nat.prime_two hqp hq2 hG P
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := ↥(Ideal.inertia Gal(↥A/ℚ) P))
  refine ⟨(g : Gal(↥A/ℚ)), le_antisymm (fun y hy => ?_) (Subgroup.zpowers_le.mpr g.2)⟩
  obtain ⟨n, hn⟩ := hg ⟨y, hy⟩
  exact ⟨n, by simpa using congrArg Subtype.val hn⟩

/-! ### The coordinates of a generator of the inertia subgroup -/

/-- **A generator of the inertia subgroup at an odd prime of the `i`-th block has the coordinates
of the `i`-th distinguished generator.**  Only the square roots of the blocks and the way the
distinguished generators move them enter, so the statement is made for a bare family of blocks and
square roots rather than for a strong Scholz realization. -/
theorem coordClass_inertia_generator_of_sqrt {d c : ℕ} (hc : 1 ≤ c)
    (e : Gal(↥A/ℚ) ≃* FreePClass 2 d c) {B : Fin d → Finset ℕ}
    (hBprime : ∀ j, ∀ p ∈ B j, p.Prime) (hBdisjoint : ∀ j k, j ≠ k → Disjoint (B j) (B k))
    {w : Fin d → ↥A} (hw : ∀ j, w j ≠ 0)
    (hwsq : ∀ j, w j ^ 2 = algebraMap ℚ ↥A ((∏ p ∈ B j, p : ℕ) : ℚ))
    (hgen : ∀ k j, sqrtSign (w j) (e.symm (FreePClass.gen 2 d c k)) = if j = k then 1 else 0)
    {i : Fin d} (hq : q ∈ B i) (hq2 : q ≠ 2) (P : Ideal (𝓞 ↥A)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] {x : Gal(↥A/ℚ)}
    (hx : Ideal.inertia Gal(↥A/ℚ) P = Subgroup.zpowers x) :
    FreePClass.coordClass 2 d hc (e x) = Multiplicative.ofAdd (Pi.single i 1) := by
  have hqp : q.Prime := hBprime i q hq
  have hcoord : ∀ j : Fin d, sqrtSign (w j) x
      = Multiplicative.toAdd (FreePClass.coordClass 2 d hc (e x)) j :=
    fun j => sqrtSign_eq_coordClass hc e hw hwsq hgen x j
  have hxmem : x ∈ Ideal.inertia Gal(↥A/ℚ) P := by
    rw [hx]; exact Subgroup.mem_zpowers x
  -- off the `i`-th coordinate the generator is trivial
  have hoff : ∀ j : Fin d, j ≠ i → sqrtSign (w j) x = 0 := by
    intro j hj
    refine sqrtSign_eq_zero_of_notMem (hBprime j) (hwsq j) hqp hq2 ?_ P hxmem
    exact fun hmem => (Finset.disjoint_left.mp (hBdisjoint j i hj)) hmem hq
  -- on the `i`-th coordinate it is not
  have hon : sqrtSign (w i) x = 1 := by
    obtain ⟨σ, hσ, hσ1⟩ := exists_mem_inertia_sqrtSign_eq_one (hBprime i) (hw i) (hwsq i) hq P
    rw [hx, Subgroup.mem_zpowers_iff] at hσ
    obtain ⟨n, rfl⟩ := hσ
    refine (eq_zero_or_one_zmod_two _).resolve_left fun hzero => ?_
    have hker : x ∈ (sqrtSignChar (hw i) (hwsq i)).ker :=
      (mem_ker_sqrtSignChar_iff _ _ x).mpr ((sqrtSign_eq_zero_iff _ x).mp hzero)
    have hker' := (mem_ker_sqrtSignChar_iff (hw i) (hwsq i) (x ^ n)).mp
      (Subgroup.zpow_mem _ hker n)
    rw [← sqrtSign_eq_zero_iff] at hker'
    rw [hker'] at hσ1
    exact zero_ne_one hσ1
  have hkey : Multiplicative.toAdd (FreePClass.coordClass 2 d hc (e x)) = Pi.single i 1 := by
    funext j
    rw [← hcoord j, Pi.single_apply]
    rcases eq_or_ne j i with rfl | hj
    · simpa using hon
    · simpa [hj] using hoff j hj
  rw [← hkey, ofAdd_toAdd]

namespace StrongScholzRealization

variable {d c N : ℕ}

/-- **A generator of the inertia subgroup at an odd prime of the `i`-th block has the coordinates
of the `i`-th distinguished generator.** -/
theorem coordClass_inertia_generator (R : StrongScholzRealization d c N) (hc : 1 ≤ c) {i : Fin d}
    (hq : q ∈ R.block i) (hq2 : q ≠ 2) (P : Ideal (𝓞 ↥R.carrier)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] {x : Gal(↥R.carrier/ℚ)}
    (hx : Ideal.inertia Gal(↥R.carrier/ℚ) P = Subgroup.zpowers x) :
    FreePClass.coordClass 2 d hc (R.galEquiv x) = Multiplicative.ofAdd (Pi.single i 1) :=
  coordClass_inertia_generator_of_sqrt hc R.galEquiv R.blockPrime R.blockDisjoint R.sqrt_ne_zero
    R.sqrt_sq R.sqrtSign_gen hq hq2 P hx

/-- **The part of the inertia subgroup at an odd prime of the `i`-th block lying over the previous
class is generated by the distinguished central element attached to the `i`-th generator.** -/
theorem map_inertia_inf_ker_proj {n : ℕ} (R : StrongScholzRealization d (n + 1) N) {i : Fin d}
    (hq : q ∈ R.block i) (hq2 : q ≠ 2) (P : Ideal (𝓞 ↥R.carrier)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] :
    (Ideal.inertia Gal(↥R.carrier/ℚ) P).map R.galEquiv.toMonoidHom ⊓
        (FreePClass.proj 2 d n).ker
      = Subgroup.zpowers (FreePClass.zGen 2 d n i) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨x, hx⟩ := exists_inertia_eq_zpowers (R.blockPrime i q hq) hq2
    ((FreePClass.isPGroup 2 d (n + 1)).of_equiv R.galEquiv.symm) P
  have hcoord := R.coordClass_inertia_generator (Nat.succ_pos n) hq hq2 P hx
  rw [hx, MonoidHom.map_zpowers]
  exact FreePClass.zpowers_inf_ker_proj hcoord

/-! ### Odd primes -/

/-- **Every prime of a block ramifies in the field.** -/
theorem mem_ramifiedSet_of_mem_block (R : StrongScholzRealization d c N) {i : Fin d}
    (hq : q ∈ R.block i) : q ∈ ramifiedSet ↥R.carrier := by
  refine mem_ramifiedSet_of_sq_eq_intCast (y := R.sqrt i)
    (n := ((∏ p ∈ R.block i, p : ℕ) : ℤ)) ?_ (R.blockPrime i q hq) ?_ ?_
  · rw [R.sqrt_sq i]; push_cast; ring
  · exact_mod_cast Finset.dvd_prod_of_mem id hq
  · intro hdvd
    exact sq_not_dvd_prod_of_mem (R.blockPrime i) hq (by exact_mod_cast hdvd)

/-- **Every prime of a block of a realization of positive level is odd.** -/
theorem ne_two_of_mem_block (R : StrongScholzRealization d c N) (hN : 1 ≤ N) {i : Fin d}
    (hq : q ∈ R.block i) : q ≠ 2 := by
  have hlevel := R.isScholz.1 q (R.mem_ramifiedSet_of_mem_block hq)
  have h2 : q ≡ 1 [MOD 2] := hlevel.of_dvd (dvd_pow_self 2 (by omega))
  rintro rfl
  simp [Nat.ModEq] at h2

end StrongScholzRealization

end InverseGalois.CFT
