/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.RestrictLE
import InverseGalois.CFT.Scholz.BlockInertia

/-!
# The inertia subgroup at a prime of a block, read on a cover

The dyadic climb carries a strong Scholz realization together with a field above it realising the
free object of the next `2`-class.  The residue correction has to know the inertia subgroup at a
prime of a block *on that cover*, not just on the realization below, because the correcting
character is chosen upstairs.

Nothing new is needed to compute it.  The square roots of the blocks live in the realization, hence
in the cover, and an automorphism of the cover moves such a square root exactly when its restriction
does.  So the sign characters of the cover are the sign characters of the realization inflated along
restriction, the distinguished generators of the free object of the next class project to the
distinguished generators of the previous one, and the computation of the coordinates of a generator
of the inertia subgroup goes through verbatim one class higher.

Reading that through the power map along the lower `2`-central series identifies the part of the
inertia subgroup lying in the kernel of the projection to the previous class: it is generated by the
distinguished central element attached to the `i`-th generator.

## Main results

* `InverseGalois.CFT.sqrtSign_galRestrictLE`: **an automorphism moves an element of a subextension
  exactly when its restriction does.**
* `InverseGalois.CFT.StrongScholzRealization.coordClass_inertia_generator_cover`: **a generator of
  the inertia subgroup of the cover at an odd prime of the `i`-th block has the coordinates of the
  `i`-th distinguished generator.**
* `InverseGalois.CFT.StrongScholzRealization.map_inertia_inf_ker_proj_cover`: **the part of the
  inertia subgroup of the cover at an odd prime of the `i`-th block lying over the previous class is
  generated by the distinguished central element attached to the `i`-th generator.**

## Tags

Scholz–Reichardt, inertia subgroup, block, square root, free `2`-group, cover, Shafarevich
-/

open NumberField InverseGalois.NumberTheory

namespace InverseGalois.CFT

/-! ### Sign characters of a subextension read upstairs -/

section SqrtSign

variable {F L : Type*} [Field F] [Field L] [Algebra F L] {E E' : IntermediateField F L}

/-- **An automorphism moves an element of a subextension exactly when its restriction does.** -/
theorem sqrtSign_galRestrictLE (h : E ≤ E') [Normal F ↥E] (v : ↥E) (σ : Gal(↥E'/F)) :
    sqrtSign (IntermediateField.inclusion h v) σ = sqrtSign v (galRestrictLE h σ) := by
  have hco : ((σ (IntermediateField.inclusion h v) : ↥E') : L)
      = ((galRestrictLE h σ v : ↥E) : L) := (coe_galRestrictLE h σ v).symm
  have key : σ (IntermediateField.inclusion h v) = IntermediateField.inclusion h v
      ↔ galRestrictLE h σ v = v := by
    constructor
    · refine fun hs => Subtype.ext ?_
      rw [← hco, hs, IntermediateField.coe_inclusion]
    · refine fun hs => Subtype.ext ?_
      rw [hco, hs, IntermediateField.coe_inclusion]
  by_cases hs : galRestrictLE h σ v = v
  · rw [(sqrtSign_eq_zero_iff _ _).mpr (key.mpr hs), (sqrtSign_eq_zero_iff _ _).mpr hs]
  · have h1 : sqrtSign (IntermediateField.inclusion h v) σ ≠ 0 := fun hz =>
      hs (key.mp ((sqrtSign_eq_zero_iff _ _).mp hz))
    have h2 : sqrtSign v (galRestrictLE h σ) ≠ 0 := fun hz =>
      hs ((sqrtSign_eq_zero_iff _ _).mp hz)
    rw [(eq_zero_or_one_zmod_two _).resolve_left h1, (eq_zero_or_one_zmod_two _).resolve_left h2]

end SqrtSign

/-! ### The square roots of the blocks read on a cover -/

namespace StrongScholzRealization

variable {d c N : ℕ} {T : IntermediateField ℚ (AlgebraicClosure ℚ)}

/-- **The square root of the product of the `i`-th block, read in a larger field.** -/
def sqrtIn (R : StrongScholzRealization d c N) (hAT : R.carrier ≤ T) (i : Fin d) : ↥T :=
  IntermediateField.inclusion hAT (R.sqrt i)

theorem sqrtIn_ne_zero (R : StrongScholzRealization d c N) (hAT : R.carrier ≤ T) (i : Fin d) :
    R.sqrtIn hAT i ≠ 0 := by
  rw [sqrtIn, ne_eq, map_eq_zero_iff _ (IntermediateField.inclusion_injective hAT)]
  exact R.sqrt_ne_zero i

theorem sqrtIn_sq (R : StrongScholzRealization d c N) (hAT : R.carrier ≤ T) (i : Fin d) :
    R.sqrtIn hAT i ^ 2 = algebraMap ℚ ↥T ((∏ p ∈ R.block i, p : ℕ) : ℚ) := by
  rw [sqrtIn, ← map_pow, R.sqrt_sq i, AlgHom.commutes]

/-- **On a cover realising the next `2`-class, the `k`-th distinguished generator still changes the
sign of the `k`-th square root alone.** -/
theorem sqrtSign_gen_cover {n : ℕ} (R : StrongScholzRealization d (n + 1) N)
    [NumberField ↥T] [IsGalois ℚ ↥T] (hAT : R.carrier ≤ T)
    (Ψ : Gal(↥T/ℚ) ≃* FreePClass 2 d (n + 2))
    (hcomp : ∀ τ, FreePClass.proj 2 d (n + 1) (Ψ τ) = R.galEquiv (galRestrictLE hAT τ))
    (k i : Fin d) :
    sqrtSign (R.sqrtIn hAT i) (Ψ.symm (FreePClass.gen 2 d (n + 2) k)) = if i = k then 1 else 0 := by
  have hres : galRestrictLE hAT (Ψ.symm (FreePClass.gen 2 d (n + 2) k))
      = R.galEquiv.symm (FreePClass.gen 2 d (n + 1) k) := by
    refine R.galEquiv.injective ?_
    rw [MulEquiv.apply_symm_apply, ← hcomp, MulEquiv.apply_symm_apply, FreePClass.proj_gen]
  rw [sqrtIn, sqrtSign_galRestrictLE, hres, R.sqrtSign_gen]

/-! ### The inertia subgroup of the cover at a prime of a block -/

variable {q : ℕ}

/-- **A generator of the inertia subgroup of the cover at an odd prime of the `i`-th block has the
coordinates of the `i`-th distinguished generator.** -/
theorem coordClass_inertia_generator_cover {n : ℕ} (R : StrongScholzRealization d (n + 1) N)
    [NumberField ↥T] [IsGalois ℚ ↥T] (hAT : R.carrier ≤ T)
    (Ψ : Gal(↥T/ℚ) ≃* FreePClass 2 d (n + 2))
    (hcomp : ∀ τ, FreePClass.proj 2 d (n + 1) (Ψ τ) = R.galEquiv (galRestrictLE hAT τ))
    (hc : 1 ≤ n + 2) {i : Fin d} (hq : q ∈ R.block i) (hq2 : q ≠ 2) (P : Ideal (𝓞 ↥T)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] {x : Gal(↥T/ℚ)}
    (hx : Ideal.inertia Gal(↥T/ℚ) P = Subgroup.zpowers x) :
    FreePClass.coordClass 2 d hc (Ψ x) = Multiplicative.ofAdd (Pi.single i 1) :=
  coordClass_inertia_generator_of_sqrt hc Ψ R.blockPrime R.blockDisjoint (R.sqrtIn_ne_zero hAT)
    (R.sqrtIn_sq hAT) (R.sqrtSign_gen_cover hAT Ψ hcomp) hq hq2 P hx

/-- **The part of the inertia subgroup of the cover at an odd prime of the `i`-th block lying over
the previous class is generated by the distinguished central element attached to the `i`-th
generator.** -/
theorem map_inertia_inf_ker_proj_cover {n : ℕ} (R : StrongScholzRealization d (n + 1) N)
    [NumberField ↥T] [IsGalois ℚ ↥T] (hAT : R.carrier ≤ T)
    (Ψ : Gal(↥T/ℚ) ≃* FreePClass 2 d (n + 2))
    (hcomp : ∀ τ, FreePClass.proj 2 d (n + 1) (Ψ τ) = R.galEquiv (galRestrictLE hAT τ))
    {i : Fin d} (hq : q ∈ R.block i) (hq2 : q ≠ 2) (P : Ideal (𝓞 ↥T)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(q : ℤ)})] :
    (Ideal.inertia Gal(↥T/ℚ) P).map Ψ.toMonoidHom ⊓ (FreePClass.proj 2 d (n + 1)).ker
      = Subgroup.zpowers (FreePClass.zGen 2 d (n + 1) i) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨x, hx⟩ := exists_inertia_eq_zpowers (R.blockPrime i q hq) hq2
    ((FreePClass.isPGroup 2 d (n + 2)).of_equiv Ψ.symm) P
  have hcoord := R.coordClass_inertia_generator_cover hAT Ψ hcomp (Nat.succ_pos (n + 1)) hq hq2 P hx
  rw [hx, MonoidHom.map_zpowers]
  exact FreePClass.zpowers_inf_ker_proj hcoord

end StrongScholzRealization

end InverseGalois.CFT
