import Mathlib
import InverseGalois.CFT.Scholz.SplitReduction
import InverseGalois.Solvable.Shafarevich.Frattini

/-!
# The central step is only needed for kernels inside the Frattini subgroup

The Scholz–Reichardt induction is driven by one embedding step: a finite group `G` surjecting onto
`H` with central kernel of order `ℓ` must be realised as soon as `H` is.  The previous reduction
confined that step to the surjections without a homomorphic section; here the scope is narrowed
once more, to the surjections whose kernel sits inside the Frattini subgroup `Φ = frattini G`, the
intersection of the maximal subgroups.

The mechanism is a counting argument that owes nothing to arithmetic and nothing to centrality.  A
kernel `Z` of prime order which escapes `Φ` misses some maximal subgroup `M`, so `Z ⊔ M` is
strictly larger than `M` and therefore everything, while `Z ⊓ M` is a proper subgroup of a group of
prime order and therefore trivial.  Thus `M` is a complement to `Z`, the surjection restricts to an
isomorphism of `M` onto `H`, and its inverse is a homomorphic section.  Contrapositively, an
extension that does not split has its kernel inside `Φ`.

## Main definitions

* `InverseGalois.CFT.IsFrattiniCentralStepSolvable`: the central embedding step, restricted to
  surjections whose kernel lies in the Frattini subgroup of the source.

## Main results

* `InverseGalois.CFT.exists_section_of_not_le_frattini`: a surjection whose kernel has prime order
  and escapes the Frattini subgroup admits a homomorphic section.
* `InverseGalois.CFT.le_frattini_of_not_exists_section`: a surjection whose kernel has prime order
  and admits no homomorphic section has its kernel inside the Frattini subgroup.
* `InverseGalois.CFT.IsNonsplitCentralStepSolvable.of_frattini`: the non-split central step follows
  from its restriction to Frattini kernels.
* `InverseGalois.CFT.IsCentralStepSolvable.of_frattini`: **the central step follows from its
  restriction to Frattini kernels.**
-/

namespace InverseGalois.CFT

open _root_.Subgroup

/-! ### Splitting off a kernel of prime order outside the Frattini subgroup -/

/-- **A surjection whose kernel has prime order and escapes the Frattini subgroup splits.**  Some
maximal subgroup `M` of the source fails to contain the kernel `Z`, so `Z ⊔ M` is strictly larger
than `M` and hence the whole group, while `Z ⊓ M` is a proper subgroup of `Z`; as `Z` has prime
order it is generated by any of its nontrivial elements, so `Z ⊓ M` is trivial.  The surjection
therefore restricts to a bijection of `M` onto the target, and the inverse bijection, followed by
the inclusion of `M`, is the required section. -/
theorem exists_section_of_not_le_frattini {G H : Type*} [Group G] [Group H] [Finite G]
    (f : G →* H) (hf : Function.Surjective f) {p : ℕ} (hp : p.Prime) (hcard : Nat.card f.ker = p)
    (h : ¬ f.ker ≤ frattini G) : ∃ s : H →* G, ∀ x, f (s x) = x := by
  obtain ⟨U, hUtop, hsup⟩ := Shafarevich.exists_proper_supplement_of_not_le_frattini h
  have hinter : f.ker ⊓ U = ⊥ := by
    rcases (f.ker ⊓ U).bot_or_exists_ne_one with hb | ⟨x, hx, hx1⟩
    · exact hb
    · exfalso
      obtain ⟨hxK, hxU⟩ := hx
      have hle : (zpowers x : Set G) ⊆ (f.ker : Set G) := by
        exact_mod_cast zpowers_le.2 hxK
      have hord : orderOf x = p := by
        have hdvd : orderOf x ∣ p := by
          rw [← hcard, ← orderOf_mk x hxK]
          exact orderOf_dvd_natCard _
        rcases hp.eq_one_or_self_of_dvd _ hdvd with h1 | h1
        · exact absurd (orderOf_eq_one_iff.1 h1) hx1
        · exact h1
      have hcards : (f.ker : Set G).ncard ≤ (zpowers x : Set G).ncard := by
        simp only [← Nat.card_coe_set_eq, SetLike.coe_sort_coe, hcard, Nat.card_zpowers, hord,
          le_refl]
      have heq : (zpowers x : Set G) = (f.ker : Set G) :=
        Set.eq_of_subset_of_ncard_le hle hcards (Set.toFinite _)
      have hkerU : f.ker ≤ U := by
        rw [← SetLike.coe_subset_coe, ← heq]
        exact_mod_cast zpowers_le.2 hxU
      exact hUtop (top_le_iff.1 (hsup ▸ sup_le hkerU le_rfl))
  set φ : ↥U →* H := f.comp U.subtype with hφ
  have hinj : Function.Injective φ := by
    rw [injective_iff_map_eq_one]
    intro u hu
    have hmem : (u : G) ∈ f.ker ⊓ U := ⟨hu, u.2⟩
    rw [hinter] at hmem
    exact Subtype.ext hmem
  have hsurj : Function.Surjective φ := by
    intro y
    obtain ⟨g, hg⟩ := hf y
    have hmem : g ∈ (U ⊔ f.ker : Subgroup G) := by
      rw [sup_comm, hsup]
      trivial
    rw [← SetLike.mem_coe, mul_normal U f.ker] at hmem
    obtain ⟨u, hu, k, hk, rfl⟩ := hmem
    exact ⟨⟨u, hu⟩, by simpa [hφ, MonoidHom.mem_ker.1 hk] using hg⟩
  refine ⟨U.subtype.comp (MulEquiv.ofBijective φ ⟨hinj, hsurj⟩).symm.toMonoidHom, fun x => ?_⟩
  exact (MulEquiv.ofBijective φ ⟨hinj, hsurj⟩).apply_symm_apply x

/-- **A surjection with a kernel of prime order and no homomorphic section has its kernel inside
the Frattini subgroup.**  A kernel of prime order escaping the intersection of the maximal
subgroups would be complemented by one of them, and the complement would provide a section. -/
theorem le_frattini_of_not_exists_section {G H : Type*} [Group G] [Group H] [Finite G]
    (f : G →* H) (hf : Function.Surjective f) {p : ℕ} (hp : p.Prime) (hcard : Nat.card f.ker = p)
    (h : ¬ ∃ s : H →* G, ∀ x, f (s x) = x) : f.ker ≤ frattini G :=
  not_not.1 fun hc => h (exists_section_of_not_le_frattini f hf hp hcard hc)

/-! ### The reduction -/

variable {ℓ : ℕ}

/-- **The central embedding step for kernels inside the Frattini subgroup.**  This is the property
`InverseGalois.CFT.IsCentralStepSolvable` with its scope cut down to the surjections whose kernel
is contained in the Frattini subgroup of the source. -/
def IsFrattiniCentralStepSolvable (ℓ : ℕ) : Prop :=
  ∀ (N : ℕ) {G H : Type} [Group G] [Group H] [Finite G] (f : G →* H), IsPGroup ℓ G →
    Function.Surjective f → f.ker ≤ Subgroup.center G → Nat.card f.ker = ℓ →
    Nat.card H ∣ ℓ ^ N →
    f.ker ≤ frattini G →
    IsScholzRealizable H ℓ (N + 1) → IsScholzRealizable G ℓ N

/-- **The non-split central step follows from its restriction to Frattini kernels.**  A kernel of
prime order that is not contained in the Frattini subgroup is complemented by a maximal subgroup,
and the complement splits the extension; so an extension outside the reach of the restricted step
splits, and the non-split step never has to face it. -/
theorem IsNonsplitCentralStepSolvable.of_frattini (hℓ : ℓ.Prime)
    (h : IsFrattiniCentralStepSolvable ℓ) : IsNonsplitCentralStepSolvable ℓ := by
  intro N G H _ _ _ f hpg hsurj hker hcard hdvd hsplit hH
  exact h N f hpg hsurj hker hcard hdvd
    (le_frattini_of_not_exists_section f hsurj hℓ hcard hsplit) hH

/-- **The central step follows from its restriction to Frattini kernels.**  The split extensions
are handled by the compositum construction and the remaining ones have their kernel inside the
Frattini subgroup. -/
theorem IsCentralStepSolvable.of_frattini (hℓ : ℓ.Prime) (h : IsFrattiniCentralStepSolvable ℓ) :
    IsCentralStepSolvable ℓ :=
  IsCentralStepSolvable.of_nonsplit hℓ (IsNonsplitCentralStepSolvable.of_frattini hℓ h)

end InverseGalois.CFT
