/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Cyclotomic.Chebotarev
import InverseGalois.CFT.Cyclotomic.DivisorSubfield
import InverseGalois.CFT.Cyclotomic.Splitting
import InverseGalois.CFT.CyclotomicCompositum
import InverseGalois.CFT.Decomposition
import InverseGalois.CFT.InertiaSurjective
import InverseGalois.CFT.InertiaTransport
import InverseGalois.CFT.Scholz.AuxPrimeChoice
import InverseGalois.CFT.Scholz.PrimeIndependence

/-!
# A cyclic extension of `ℓ`-power degree in which `ℓ` is inert

The subfield of degree `ℓ ^ n` of the cyclotomic field of prime conductor `q` is unramified at
every prime other than `q`, and the decomposition group at a prime above `ℓ` is generated by the
Frobenius, whose order is the order of the class of `ℓ` in the quotient of `(ℤ/qℤ)ˣ` of order
`ℓ ^ n`.  That order is `ℓ ^ n` exactly when `ℓ` is not an `ℓ`-th power residue modulo `q`, so a
prime `q` with `ℓ ^ ((q - 1) / ℓ) ≢ 1` produces a cyclic extension of degree `ℓ ^ n` in which `ℓ`
is inert.

Both conclusions — trivial inertia and full decomposition group — are read off the ramification
index and the residue degree, so they survive the transport of the field along an isomorphism, and
in particular the transport into a fixed algebraic closure of the rationals.

## Main results

* `InverseGalois.CFT.stabilizer_eq_top_of_algEquiv`: an inert prime stays inert along an
  isomorphism of number fields.
* `InverseGalois.CFT.exists_intermediateField_finrank_eq_pow_inert`: **the cyclotomic field of
  prime conductor `q` contains a cyclic extension of degree `ℓ ^ n` in which `ℓ` is inert**, as
  soon as `ℓ ^ n` divides `q - 1` and `ℓ` is not an `ℓ`-th power residue modulo `q`.
* `InverseGalois.CFT.exists_intermediateField_cyclic_pow_inert`: **for an odd prime `ℓ` a fixed
  algebraic closure of the rationals contains a cyclic extension of degree `ℓ ^ n` in which `ℓ` is
  inert**, the conductor being supplied by the Chebotarev input of the Scholz–Reichardt
  construction.

## Tags

inert prime, decomposition group, Frobenius, cyclotomic field, cyclic extension
-/

open Module NumberField IsCyclotomicExtension InverseGalois.NumberTheory

open scoped Pointwise

namespace InverseGalois.CFT

set_option synthInstance.maxHeartbeats 400000

attribute [local instance] Int.ideal_span_isMaximal_of_prime

/-! ### The order of the decomposition group -/

section Card

variable {K : Type*} [Field K] [NumberField K] [IsGalois ℚ K]

/-- **The order of the decomposition group is the ramification index times the residue degree.** -/
theorem card_stabilizer_eq_ramificationIdx_mul_inertiaDeg (P : Ideal (𝓞 K)) [P.IsPrime]
    (hP : P ≠ ⊥) :
    Nat.card (MulAction.stabilizer Gal(K/ℚ) P) =
      Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (P.under ℤ) P * (P.under ℤ).inertiaDeg P := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  rw [Ideal.card_stabilizer_eq (G := Gal(K/ℚ)) (P.under ℤ) (under_ne_bot P hP) P,
    Ideal.ramificationIdxIn_eq_ramificationIdx (P.under ℤ) P Gal(K/ℚ),
    Ideal.inertiaDegIn_eq_inertiaDeg (P.under ℤ) P Gal(K/ℚ)]

end Card

/-! ### Transport along an isomorphism -/

section Transport

variable {E F : Type*} [Field E] [NumberField E] [IsGalois ℚ E] [Field F] [NumberField F]
  [IsGalois ℚ F] {p : ℕ}

omit [IsGalois ℚ E] [IsGalois ℚ F] in
/-- A prime of the target of an isomorphism of number fields contracts to a prime of the source
lying over the same rational prime. -/
theorem liesOver_comap_mapAlgEquivInt (e : E ≃ₐ[ℚ] F) (Q : Ideal (𝓞 F))
    [hQo : Q.LiesOver (Ideal.span {(p : ℤ)})] :
    (Ideal.comap (mapAlgEquivInt (e : E ≃+* F) : 𝓞 E →+* 𝓞 F) Q).LiesOver
      (Ideal.span {(p : ℤ)}) := by
  refine ⟨?_⟩
  have hunder : (Ideal.comap (mapAlgEquivInt (e : E ≃+* F) : 𝓞 E →+* 𝓞 F) Q).under ℤ
      = Q.under ℤ := by
    rw [Ideal.under, Ideal.under, Ideal.comap_comap]
    congr 1
    exact Subsingleton.elim _ _
  rw [hunder]
  exact hQo.over

/-- **An unramified prime stays unramified along an isomorphism of number fields**, because the
ramification index is unchanged by contracting along the isomorphism. -/
theorem inertia_eq_bot_of_algEquiv (e : E ≃ₐ[ℚ] F) (hp : p.Prime)
    (h : ∀ (P : Ideal (𝓞 E)) (_ : P.IsPrime) (_ : P.LiesOver (Ideal.span {(p : ℤ)})),
      Ideal.inertia Gal(E/ℚ) P = ⊥)
    (Q : Ideal (𝓞 F)) [Q.IsPrime] [Q.LiesOver (Ideal.span {(p : ℤ)})] :
    Ideal.inertia Gal(F/ℚ) Q = ⊥ := by
  haveI hPp : (Ideal.comap (mapAlgEquivInt (e : E ≃+* F) : 𝓞 E →+* 𝓞 F) Q).IsPrime :=
    Ideal.comap_isPrime _ _
  haveI hPo := liesOver_comap_mapAlgEquivInt (p := p) e Q
  set f := mapAlgEquivInt (e : E ≃+* F) with hf
  set P : Ideal (𝓞 E) := Ideal.comap (f : 𝓞 E →+* 𝓞 F) Q with hP
  have hidx : Ideal.ramificationIdx (algebraMap ℤ (𝓞 E)) (Ideal.span {(p : ℤ)}) P =
      Ideal.ramificationIdx (algebraMap ℤ (𝓞 F)) (Ideal.span {(p : ℤ)}) Q :=
    Ideal.ramificationIdx_comap_eq (Ideal.span {(p : ℤ)}) f Q
  rw [← Subgroup.card_eq_one, card_inertia_eq_ramificationIdx_span hp Q, ← hidx,
    ← card_inertia_eq_ramificationIdx_span hp P, h P hPp hPo, Subgroup.card_bot]

/-- **An inert prime stays inert along an isomorphism of number fields.**  The decomposition group
has the order of the Galois group exactly when the ramification index times the residue degree is
the degree of the field, and all three numbers are unchanged by the isomorphism. -/
theorem stabilizer_eq_top_of_algEquiv (e : E ≃ₐ[ℚ] F) (hp : p.Prime)
    (h : ∀ (P : Ideal (𝓞 E)) (_ : P.IsPrime) (_ : P.LiesOver (Ideal.span {(p : ℤ)})),
      MulAction.stabilizer Gal(E/ℚ) P = ⊤)
    (Q : Ideal (𝓞 F)) [Q.IsPrime] [Q.LiesOver (Ideal.span {(p : ℤ)})] :
    MulAction.stabilizer Gal(F/ℚ) Q = ⊤ := by
  haveI := Fact.mk hp
  haveI hPp : (Ideal.comap (mapAlgEquivInt (e : E ≃+* F) : 𝓞 E →+* 𝓞 F) Q).IsPrime :=
    Ideal.comap_isPrime _ _
  haveI hPo := liesOver_comap_mapAlgEquivInt (p := p) e Q
  set f := mapAlgEquivInt (e : E ≃+* F) with hf
  set P : Ideal (𝓞 E) := Ideal.comap (f : 𝓞 E →+* 𝓞 F) Q with hP
  have hPne : P ≠ ⊥ := ne_bot_of_liesOver p P
  have hQne : Q ≠ ⊥ := ne_bot_of_liesOver p Q
  have hPu : P.under ℤ = Ideal.span {(p : ℤ)} := under_eq_span_of_liesOver (p := p) P
  have hQu : Q.under ℤ = Ideal.span {(p : ℤ)} := under_eq_span_of_liesOver (p := p) Q
  have hidx : Ideal.ramificationIdx (algebraMap ℤ (𝓞 E)) (Ideal.span {(p : ℤ)}) P =
      Ideal.ramificationIdx (algebraMap ℤ (𝓞 F)) (Ideal.span {(p : ℤ)}) Q :=
    Ideal.ramificationIdx_comap_eq (Ideal.span {(p : ℤ)}) f Q
  have hdeg : (Ideal.span {(p : ℤ)}).inertiaDeg P = (Ideal.span {(p : ℤ)}).inertiaDeg Q :=
    Ideal.inertiaDeg_comap_eq (Ideal.span {(p : ℤ)}) f Q
  refine Subgroup.eq_top_of_card_eq _ ?_
  rw [card_stabilizer_eq_ramificationIdx_mul_inertiaDeg Q hQne, hQu, ← hidx, ← hdeg, ← hPu,
    ← card_stabilizer_eq_ramificationIdx_mul_inertiaDeg P hPne, h P hPp hPo,
    Subgroup.card_top, IsGalois.card_aut_eq_finrank, IsGalois.card_aut_eq_finrank]
  exact e.toLinearEquiv.finrank_eq

end Transport

/-! ### Reading inertness off the Frobenius -/

section Frobenius

variable {E : Type*} [Field E] [NumberField E] [IsGalois ℚ E]

/-- Restriction to the fixed field of a normal subgroup kills exactly that subgroup. -/
theorem restrictNormalHom_fixedField_eq_one_iff (H : Subgroup Gal(E/ℚ)) [H.Normal]
    (x : Gal(E/ℚ)) :
    AlgEquiv.restrictNormalHom ↥(IntermediateField.fixedField H) x = 1 ↔ x ∈ H := by
  rw [← MonoidHom.mem_ker, IntermediateField.restrictNormalHom_ker,
    IntermediateField.fixingSubgroup_fixedField]

/-- **A prime is inert in a subextension as soon as the restriction of a Frobenius above it
generates the Galois group of the subextension.**  Unramifiedness upstairs gives unramifiedness
downstairs because restriction maps inertia onto inertia, and then the decomposition group
downstairs is generated by the Frobenius, which is the restriction of the Frobenius upstairs. -/
theorem inertia_eq_bot_and_stabilizer_eq_top_of_orderOf (F : IntermediateField ℚ E)
    [IsGalois ℚ ↥F] {p : ℕ} (hp : p.Prime) (Q : Ideal (𝓞 ↥F)) [Q.IsPrime]
    [Q.LiesOver (Ideal.span {(p : ℤ)})]
    (hunr : ∀ (P : Ideal (𝓞 E)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})],
      Algebra.IsUnramifiedAt ℤ P)
    (horder : ∀ (P : Ideal (𝓞 E)) [P.IsPrime] [Finite (𝓞 E ⧸ P)]
      [P.LiesOver (Ideal.span {(p : ℤ)})],
      P.under (𝓞 ↥F) = Q →
        orderOf (AlgEquiv.restrictNormalHom ↥F (arithFrobAt ℤ Gal(E/ℚ) P)) =
          Nat.card Gal(↥F/ℚ)) :
    Ideal.inertia Gal(↥F/ℚ) Q = ⊥ ∧ MulAction.stabilizer Gal(↥F/ℚ) Q = ⊤ := by
  haveI := Fact.mk hp
  have hQne : Q ≠ ⊥ := ne_bot_of_liesOver p Q
  haveI : Q.IsMaximal := isMaximal_of_ne_bot Q hQne
  haveI : Finite (𝓞 ↥F ⧸ Q) := finite_quotient_of_ne_bot Q hQne
  obtain ⟨P, hPmax, hPover⟩ := Ideal.exists_maximal_ideal_liesOver_of_isIntegral (S := 𝓞 E) Q
  haveI := hPmax
  haveI := hPover
  haveI : P.IsPrime := hPmax.isPrime
  haveI : P.LiesOver (Ideal.span {(p : ℤ)}) := Ideal.LiesOver.trans P Q (Ideal.span {(p : ℤ)})
  have hunder : P.under (𝓞 ↥F) = Q := (Ideal.LiesOver.over (p := Q)).symm
  have hPne : P ≠ ⊥ := ne_bot_of_liesOver p P
  haveI : Finite (𝓞 E ⧸ P) := finite_quotient_of_ne_bot P hPne
  have hinertP : Ideal.inertia Gal(E/ℚ) P = ⊥ :=
    (inertia_eq_bot_iff_isUnramifiedAt P hPne).mpr (hunr P)
  have hinertQ : Ideal.inertia Gal(↥F/ℚ) Q = ⊥ := by
    rw [← hunder, ← map_inertia_eq_inertia F hp P, hinertP, Subgroup.map_bot]
  refine ⟨hinertQ, ?_⟩
  have hunrQ : Algebra.IsUnramifiedAt ℤ Q := (inertia_eq_bot_iff_isUnramifiedAt Q hQne).mp hinertQ
  have hfrobQ : arithFrobAt ℤ Gal(↥F/ℚ) Q
      = AlgEquiv.restrictNormalHom ↥F (arithFrobAt ℤ Gal(E/ℚ) P) := by
    have h1 : IsArithFrobAt ℤ (AlgEquiv.restrictNormalHom ↥F (arithFrobAt ℤ Gal(E/ℚ) P)) Q := by
      rw [← hunder]
      exact isArithFrobAt_restrictNormal F (arithFrobAt ℤ Gal(E/ℚ) P) P
        (IsArithFrobAt.arithFrobAt ℤ Gal(E/ℚ) P)
    have h2 := (IsArithFrobAt.arithFrobAt ℤ Gal(↥F/ℚ) Q).mul_inv_mem_inertia h1
    rw [hinertQ, Subgroup.mem_bot, mul_inv_eq_one] at h2
    exact h2
  rw [stabilizer_eq_zpowers_arithFrobAt Q hQne hunrQ]
  refine Subgroup.eq_top_of_card_eq _ ?_
  rw [Nat.card_zpowers, hfrobQ, horder P hunder]

end Frobenius

/-! ### The inert subfield of a cyclotomic field of prime conductor -/

variable {ℓ n : ℕ}

/-- **The cyclotomic field of prime conductor `q` contains a cyclic extension of degree `ℓ ^ n` in
which `ℓ` is inert**, as soon as `ℓ ^ n` divides `q - 1` and `ℓ` is not an `ℓ`-th power residue
modulo `q`.  The subfield is the fixed field of the kernel of the `((q - 1) / ℓ ^ n)`-th power map
on `(ℤ/qℤ)ˣ ≃ Gal(ℚ(ζ_q)/ℚ)`; the prime `ℓ` is unramified there because it is unramified in the
cyclotomic field, and the decomposition group is generated by the Frobenius, which is the class of
`ℓ` and generates the quotient of order `ℓ ^ n` precisely under the power residue hypothesis. -/
theorem exists_intermediateField_finrank_eq_pow_inert (q : ℕ) [hq : Fact q.Prime] (hℓ : ℓ.Prime)
    (hn : n ≠ 0) (hℓq : ℓ ≠ q) (hdvd : ℓ ^ n ∣ q - 1) (hres : (ℓ : ZMod q) ^ ((q - 1) / ℓ) ≠ 1)
    (E : Type*) [Field E] [NumberField E] [IsCyclotomicExtension {q} ℚ E] :
    ∃ F : IntermediateField ℚ E, IsGalois ℚ ↥F ∧ IsCyclic Gal(↥F/ℚ) ∧ finrank ℚ ↥F = ℓ ^ n ∧
      ∀ (Q : Ideal (𝓞 ↥F)) (_ : Q.IsPrime) (_ : Q.LiesOver (Ideal.span {(ℓ : ℤ)})),
        Ideal.inertia Gal(↥F/ℚ) Q = ⊥ ∧ MulAction.stabilizer Gal(↥F/ℚ) Q = ⊤ := by
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  haveI : NeZero q := ⟨hq.out.ne_zero⟩
  haveI : IsGalois ℚ E := IsCyclotomicExtension.isGalois {q} ℚ E
  haveI : IsCyclic (ZMod q)ˣ := ZMod.isCyclic_units_prime hq.out
  haveI : IsCyclic Gal(E/ℚ) :=
    isCyclic_of_surjective (Rat.galEquivZMod q E).symm (Rat.galEquivZMod q E).symm.surjective
  have hcard : Nat.card (ZMod q)ˣ = q - 1 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient, Nat.totient_prime hq.out]
  have hq1 : q - 1 ≠ 0 := by
    have := hq.out.two_le
    omega
  have hd : ℓ ^ n ≠ 0 := pow_ne_zero n hℓ.ne_zero
  have hmne : (q - 1) / ℓ ^ n ≠ 0 := Nat.div_ne_zero_iff_of_dvd hdvd |>.mpr ⟨hq1, hd⟩
  have hmdvd : (q - 1) / ℓ ^ n ∣ q - 1 := Nat.div_dvd_of_dvd hdvd
  set H := Subgroup.comap (Rat.galEquivZMod q E).toMonoidHom
    (MonoidHom.ker (powMonoidHom ((q - 1) / ℓ ^ n) : (ZMod q)ˣ →* (ZMod q)ˣ)) with hH
  haveI : H.Normal := Subgroup.Normal.comap (MonoidHom.normal_ker _) _
  have hindex : H.index = ℓ ^ n := by
    rw [hH, Subgroup.index_comap_of_surjective (f := (Rat.galEquivZMod q E).toMonoidHom) _
        (Rat.galEquivZMod q E).surjective,
      Subgroup.index_ker, card_range_powMonoidHom hmne (hcard ▸ hmdvd), hcard,
      Nat.div_div_self hdvd hq1]
  have hrank : finrank ℚ ↥(IntermediateField.fixedField H) = ℓ ^ n := by
    rw [finrank_fixedField_eq_index, hindex]
  have hcyc : IsCyclic Gal(↥(IntermediateField.fixedField H)/ℚ) :=
    isCyclic_of_surjective
      (AlgEquiv.restrictNormalHom (F := ℚ) (K₁ := E) ↥(IntermediateField.fixedField H))
      (AlgEquiv.restrictNormalHom_surjective _)
  have hcardF : Nat.card Gal(↥(IntermediateField.fixedField H)/ℚ) = ℓ ^ n := by
    rw [IsGalois.card_aut_eq_finrank, hrank]
  have hℓq' : ¬ ℓ ∣ q := fun h => hℓq ((Nat.prime_dvd_prime_iff_eq hℓ hq.out).mp h)
  have hunr : ∀ (P : Ideal (𝓞 E)) [P.IsPrime] [P.LiesOver (Ideal.span {(ℓ : ℤ)})],
      Algebra.IsUnramifiedAt ℤ P := by
    intro P _ _
    have hPne : P ≠ ⊥ := ne_bot_of_liesOver ℓ P
    rw [Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hPne,
      ← Ideal.over_def P (Ideal.span {(ℓ : ℤ)})]
    exact IsCyclotomicExtension.Rat.ramificationIdx_eq_of_not_dvd ℓ E P hℓq'
  refine ⟨IntermediateField.fixedField H, inferInstance, hcyc, hrank, ?_⟩
  intro Q hQp hQo
  haveI := hQp
  haveI := hQo
  refine inertia_eq_bot_and_stabilizer_eq_top_of_orderOf _ hℓ Q hunr ?_
  intro P _ _ _ _
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  have harith : ℓ ^ m * ((q - 1) / ℓ ^ (m + 1)) = (q - 1) / ℓ := by
    obtain ⟨k, hk⟩ := hdvd
    rw [hk, Nat.mul_div_cancel_left _ (Nat.pos_of_ne_zero hd), pow_succ,
      mul_comm (ℓ ^ m) ℓ, mul_assoc, Nat.mul_div_cancel_left _ hℓ.pos]
  rw [hcardF]
  refine orderOf_eq_prime_pow ?_ ?_
  · rw [← map_pow, restrictNormalHom_fixedField_eq_one_iff, hH, Subgroup.mem_comap,
      MonoidHom.mem_ker, MulEquiv.coe_toMonoidHom, map_pow,
      galEquivZMod_arithFrobAt q E hℓ hℓq' P (Ideal.over_def P (Ideal.span {(ℓ : ℤ)})).symm,
      powMonoidHom_apply, ← pow_mul, ← Units.val_eq_one, Units.val_pow_eq_pow_val,
      ZMod.coe_unitOfCoprime, harith]
    exact hres
  · rw [← hcardF]
    exact pow_card_eq_one'

/-! ### Inside a fixed algebraic closure -/

set_option maxHeartbeats 1000000 in
/-- **For an odd prime `ℓ` a fixed algebraic closure of the rationals contains a cyclic extension
of degree `ℓ ^ n` in which `ℓ` is inert.**  The conductor `q` is supplied by the Chebotarev input
of the Scholz–Reichardt construction applied to the radicand `ℓ`, which is not an `ℓ`-th power in
the rationals: splitting completely in the cyclotomic field of conductor `ℓ ^ n` forces `ℓ ^ n` to
divide `q - 1`, and failing to split completely in the radical field says that `ℓ` is not an
`ℓ`-th power residue modulo `q`.  The subfield of degree `ℓ ^ n` of the cyclotomic field of
conductor `q` is then transported into the algebraic closure along the canonical isomorphism. -/
theorem exists_intermediateField_cyclic_pow_inert [Fact ℓ.Prime] (hodd : Odd ℓ) (hn : n ≠ 0) :
    ∃ U : IntermediateField ℚ (AlgebraicClosure ℚ), ∃ _ : NumberField ↥U,
      IsGalois ℚ ↥U ∧ IsCyclic Gal(↥U/ℚ) ∧ finrank ℚ ↥U = ℓ ^ n ∧
      ∀ (Q : Ideal (𝓞 ↥U)) (_ : Q.IsPrime) (_ : Q.LiesOver (Ideal.span {(ℓ : ℤ)})),
        Ideal.inertia Gal(↥U/ℚ) Q = ⊥ ∧ MulAction.stabilizer Gal(↥U/ℚ) Q = ⊤ := by
  have hℓ : ℓ.Prime := Fact.out
  haveI : NeZero (ℓ ^ n) := ⟨pow_ne_zero n hℓ.ne_zero⟩
  have hnil : Group.IsNilpotent Gal(↥(cycSubfield (ℓ ^ n))/ℚ) :=
    nilpotent_of_mulEquiv
      (IsCyclotomicExtension.Rat.galEquivZMod (ℓ ^ n) ↥(cycSubfield (ℓ ^ n))).symm
  obtain ⟨ζ, hζ, hζA⟩ :
      ∃ ζ : AlgebraicClosure ℚ, IsPrimitiveRoot ζ ℓ ∧ ζ ∈ cycSubfield (ℓ ^ n) := by
    obtain ⟨j, rfl⟩ : ∃ j, n = j + 1 := ⟨n - 1, by omega⟩
    refine ⟨cycRoot (ℓ ^ (j + 1)) ^ ℓ ^ j, ?_, ?_⟩
    · exact IsPrimitiveRoot.pow (NeZero.pos (ℓ ^ (j + 1))) (cycRoot_spec (ℓ ^ (j + 1)))
        (pow_succ ℓ j)
    · refine pow_mem ?_ _
      exact IntermediateField.subset_adjoin ℚ _ rfl
  have hv : ∀ y : ℚ, y ^ ℓ ≠ ((ℓ : ℤ) : ℚ) := by
    have h := pow_ne_prod_pow (ℓ := ℓ) (S := ({ℓ} : Finset ℕ)) (a := fun _ => 1) (p₀ := ℓ)
      (fun p hp => by rwa [Finset.mem_singleton.mp hp]) (Finset.mem_singleton_self ℓ)
      (fun hd => hℓ.one_lt.ne' (Nat.dvd_one.mp hd))
    intro y
    simpa using h y
  have hpow : ∀ q : ℕ, q.Prime → q ≠ ℓ → SplitsCompletely ↥(cycSubfield (ℓ ^ n)) q →
      ℓ ^ n ∣ q - 1 := by
    intro q hq hqℓ hs
    haveI : Fact q.Prime := ⟨hq⟩
    have hnd : ¬ q ∣ ℓ ^ n := fun h =>
      hqℓ ((Nat.prime_dvd_prime_iff_eq hq hℓ).mp (hq.dvd_of_dvd_pow h))
    exact (Nat.modEq_iff_dvd' hq.one_le).mp
      (modEq_of_splitsCompletely (ℓ ^ n) ↥(cycSubfield (ℓ ^ n)) q hnd hs).symm
  obtain ⟨q, hqp, -, hqℓ, hqs, hqres⟩ :=
    exists_prime_splitsCompletely_pow_ne_one (A := cycSubfield (ℓ ^ n)) hodd hnil hζ hζA hv ∅
      (fun q hq hqne hs => dvd_trans (dvd_pow_self ℓ hn) (hpow q hq hqne hs))
  haveI : Fact q.Prime := ⟨hqp⟩
  haveI : NeZero q := ⟨hqp.ne_zero⟩
  obtain ⟨F, hgal, hcyc, hrank, hinert⟩ :=
    exists_intermediateField_finrank_eq_pow_inert q hℓ hn (Ne.symm hqℓ) (hpow q hqp hqℓ hqs)
      (by exact_mod_cast hqres) ↥(cycSubfield q)
  haveI := hgal
  haveI := hcyc
  set e := IntermediateField.liftAlgEquiv F with he
  haveI : FiniteDimensional ℚ ↥(IntermediateField.lift F) :=
    LinearEquiv.finiteDimensional e.toLinearEquiv
  haveI : NumberField ↥(IntermediateField.lift F) := ⟨⟩
  haveI : IsGalois ℚ ↥(IntermediateField.lift F) := IsGalois.of_algEquiv e
  refine ⟨IntermediateField.lift F, inferInstance, inferInstance, ?_, ?_, ?_⟩
  · exact isCyclic_of_surjective (AlgEquiv.autCongr e) (AlgEquiv.autCongr e).surjective
  · rw [← e.toLinearEquiv.finrank_eq]
    exact hrank
  · intro Q hQp hQo
    haveI := hQp
    haveI := hQo
    exact ⟨inertia_eq_bot_of_algEquiv e hℓ (fun P hP hPo => (hinert P hP hPo).1) Q,
      stabilizer_eq_top_of_algEquiv e hℓ (fun P hP hPo => (hinert P hP hPo).2) Q⟩

end InverseGalois.CFT
