/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Scholz.DyadicSocle
import InverseGalois.CFT.Scholz.Realization
import InverseGalois.CFT.Scholz.StepRamification
import InverseGalois.CFT.Scholz.StepSqrt
import InverseGalois.Solvable.ElementaryAbelian

/-!
# The multiquadratic base of the dyadic Scholz–Reichardt induction

Iterating the split step of `InverseGalois.CFT.Scholz.SplitStep` at the prime two, starting from
`ℚ` and adjoining one quadratic layer at a time, produces a field of degree `2 ^ d` over `ℚ`
satisfying Serre's condition and ramified at exactly `d` primes, one contributed by each layer.
The branching prime of a layer is unramified in the field built so far, and every prime already
used is genuinely ramified there, so the `d` primes are distinct.

The Galois group is abelian of exponent two and order `2 ^ d`, hence the free object of rank `d`
and `2`-class one.  From level two on the branching prime of each layer is congruent to one modulo
four, so the layer is generated by a square root of that prime, and the field comes equipped with a
square root of each of its ramified primes.  That is the base of the induction on the `2`-class.

## Main results

* `InverseGalois.CFT.exists_scholz_ramifiedSet_eq_range`: **a field satisfying Serre's condition
  whose ramified primes are exactly a prescribed number of distinct primes, with Galois group
  abelian of exponent two, and carrying a square root of each of those primes.**

## Tags

Scholz–Reichardt, multiquadratic field, elementary abelian, block, square root
-/

open Module NumberField InverseGalois.NumberTheory

namespace InverseGalois.CFT

set_option maxHeartbeats 1000000 in
/-- **A Scholz field ramified at exactly `d` distinct primes, with elementary abelian Galois group
of order `2 ^ d`, and carrying a square root of each of those primes.**  Each quadratic layer of the
tower contributes one ramified prime, which is unramified below it and stays ramified above it; from
level two on the branching prime is congruent to one modulo four, so the layer is generated by a
square root of it, and the square roots of the earlier layers survive in the compositum. -/
theorem exists_scholz_ramifiedSet_eq_range {N : ℕ} (hN : 2 ≤ N) : ∀ d : ℕ,
    ∃ (K : IntermediateField ℚ (AlgebraicClosure ℚ)) (_ : NumberField ↥K) (_ : IsGalois ℚ ↥K)
      (q : Fin d → ℕ) (v : Fin d → ↥K), Function.Injective q ∧ (∀ i, (q i).Prime) ∧
        IsScholz 2 N ↥K ∧ ramifiedSet ↥K = Set.range q ∧ Nat.card Gal(↥K/ℚ) = 2 ^ d ∧
        (∀ σ : Gal(↥K/ℚ), σ ^ 2 = 1) ∧
        ∀ i, v i ^ 2 = algebraMap ℚ ↥K ((q i : ℕ) : ℚ) := by
  intro d
  induction d with
  | zero =>
    set E : IntermediateField ℚ (AlgebraicClosure ℚ) := ⊥ with hE
    haveI : FiniteDimensional ℚ ↥E :=
      FiniteDimensional.of_finrank_eq_succ (n := 0) IntermediateField.finrank_bot
    haveI : NumberField ↥E := ⟨⟩
    haveI : IsGalois ℚ ↥E :=
      IsGalois.of_algEquiv (IntermediateField.botEquiv ℚ (AlgebraicClosure ℚ)).symm
    have hrank : finrank ℚ ↥E = 1 := IntermediateField.finrank_bot
    have hcard : Nat.card Gal(↥E/ℚ) = 2 ^ 0 := by
      rw [IsGalois.card_aut_eq_finrank ℚ ↥E, hrank, pow_zero]
    haveI : Subsingleton Gal(↥E/ℚ) := (Nat.card_eq_one_iff_unique.mp (by rw [hcard, pow_zero])).1
    have hram : ramifiedSet ↥E = Set.range (Fin.elim0 : Fin 0 → ℕ) :=
      (ramifiedSet_eq_empty_of_finrank_eq_one ↥E hrank).trans (Set.range_eq_empty _).symm
    exact ⟨E, inferInstance, inferInstance, Fin.elim0, Fin.elim0,
      fun a _ _ => Subsingleton.elim a _, fun i => i.elim0,
      isScholz_of_finrank_eq_one ↥E hrank 2 N, hram, hcard,
      (fun σ => by rw [Subsingleton.elim σ 1, one_pow]), fun i => i.elim0⟩
  | succ d ih =>
    obtain ⟨K, hNF, hGal, q, v, hqinj, hqp, hsch, hram, hcard, hexp, hvsq⟩ := ih
    haveI := hNF
    haveI := hGal
    have hqnp : (stepPrime ↥K Nat.prime_two N 1).Prime := prime_stepPrime ↥K Nat.prime_two N 1
    have hqnnot : stepPrime ↥K Nat.prime_two N 1 ∉ Set.range q := by
      rw [← hram]
      exact stepPrime_notMem_ramifiedSet ↥K Nat.prime_two N 1
    obtain ⟨w, hw⟩ := exists_sq_eq_stepPrime ↥K hN
    refine ⟨stepField ↥K Nat.prime_two N 1, inferInstance, inferInstance,
      Fin.cons (stepPrime ↥K Nat.prime_two N 1) q,
      Fin.cons (innerNewAlgHom ↥K Nat.prime_two N 1 w)
        (fun i => innerOldAlgHom ↥K Nat.prime_two N 1 (v i)),
      Fin.cons_injective_iff.mpr ⟨hqnnot, hqinj⟩,
      ?_, isScholz_stepField ↥K Nat.prime_two N 1 hsch, ?_, ?_, ?_, ?_⟩
    · refine Fin.cases ?_ ?_
      · rw [Fin.cons_zero]
        exact hqnp
      · intro j
        rw [Fin.cons_succ]
        exact hqp j
    · rw [ramifiedSet_stepField_eq ↥K Nat.prime_two N 1 one_ne_zero, hram, Fin.range_cons,
        Set.union_singleton]
    · rw [Nat.card_congr (galEquivStepField ↥K Nat.prime_two N 1).toEquiv, Nat.card_prod, hcard,
        card_gal_stepAux ↥K Nat.prime_two N 1, pow_one, pow_succ]
    · intro σ
      have hsnd := pow_card_eq_one' (G := Gal(↥(stepAux ↥K Nat.prime_two N 1)/ℚ))
        (x := (galEquivStepField ↥K Nat.prime_two N 1 σ).2)
      rw [card_gal_stepAux ↥K Nat.prime_two N 1, pow_one] at hsnd
      refine (galEquivStepField ↥K Nat.prime_two N 1).injective ?_
      rw [map_pow, map_one]
      refine Prod.ext ?_ ?_
      · show (galEquivStepField ↥K Nat.prime_two N 1 σ).1 ^ 2 = 1
        exact hexp _
      · show (galEquivStepField ↥K Nat.prime_two N 1 σ).2 ^ 2 = 1
        exact hsnd
    · refine Fin.cases ?_ ?_
      · rw [Fin.cons_zero, Fin.cons_zero]
        exact sq_eq_algebraMap_map _ hw
      · intro j
        rw [Fin.cons_succ, Fin.cons_succ]
        exact sq_eq_algebraMap_map _ (hvsq j)

end InverseGalois.CFT
