/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Scholz.RadicalTower

/-!
# The degree of a radical field over a field of roots of unity

Adjoining the `ℓ`-th roots of a single rational number to a field already containing the `ℓ`-th
roots of unity adjoins nothing more than one of those roots: the others differ from it by a root of
unity.  So the compositum of such a field with the radical field of one rational number is a simple
extension, generated by a root of `X ^ ℓ` minus that number.

For `ℓ` prime that polynomial is irreducible as soon as the number has no `ℓ`-th root in the field,
with no hypothesis on roots of unity, so it is the minimal polynomial of the generator and the
compositum has degree exactly `ℓ` over the field.  This exact degree is what a density argument
needs when two enlargements have to be avoided at once: knowing only that each enlargement is
strictly larger leaves room for degree two, where the union bound gives nothing.

## Main results

* `InverseGalois.CFT.sup_radicalField_singleton_eq_sup_adjoin`: the compositum of a field of `ℓ`-th
  roots of unity with the radical field of one rational number is generated by a single `ℓ`-th root
  of that number.
* `InverseGalois.CFT.finrank_sup_radicalField_singleton`: **that compositum has degree exactly `ℓ`
  times the degree of the field**, when the number has no `ℓ`-th root in it.

## Tags

radical extension, Kummer theory, minimal polynomial, degree, root of unity
-/

open Module Polynomial IntermediateField

namespace InverseGalois.CFT

variable {ℓ : ℕ} {S : Finset ℚ}

/-! ### Roots of the radical polynomial, remembering which factor -/

section RootSet

/-- An element whose `ℓ`-th power is one of the constants indexing the radical polynomial is a root
of that polynomial. -/
theorem mem_rootSet_radicalPoly (hℓ : ℓ ≠ 0) {c : ℚ} (hc : c ∈ insert 1 S)
    {β : AlgebraicClosure ℚ} (hβ : β ^ ℓ = algebraMap ℚ (AlgebraicClosure ℚ) c) :
    β ∈ (radicalPoly ℓ S).rootSet (AlgebraicClosure ℚ) := by
  rw [mem_rootSet]
  refine ⟨radicalPoly_ne_zero ℓ S hℓ, ?_⟩
  rw [radicalPoly, map_prod]
  refine Finset.prod_eq_zero hc ?_
  simp [hβ]

/-- Every root of the radical polynomial has one of the indexing constants as its `ℓ`-th power. -/
theorem exists_mem_insert_pow_eq_of_mem_rootSet {β : AlgebraicClosure ℚ}
    (hβ : β ∈ (radicalPoly ℓ S).rootSet (AlgebraicClosure ℚ)) :
    ∃ c ∈ insert 1 S, β ^ ℓ = algebraMap ℚ (AlgebraicClosure ℚ) c := by
  rw [mem_rootSet] at hβ
  obtain ⟨-, h⟩ := hβ
  rw [radicalPoly, map_prod] at h
  obtain ⟨c, hcmem, hc⟩ := Finset.prod_eq_zero_iff.mp h
  refine ⟨c, hcmem, ?_⟩
  simp only [map_sub, map_pow, aeval_X, aeval_C, sub_eq_zero] at hc
  exact hc

end RootSet

/-! ### A radical field over a field of roots of unity is simple -/

section Simple

variable {A : IntermediateField ℚ (AlgebraicClosure ℚ)} {m : ℚ} {α ζ : AlgebraicClosure ℚ}

/-- **The compositum of a field of `ℓ`-th roots of unity with the radical field of one rational
number is generated by a single `ℓ`-th root of that number.**  Any two `ℓ`-th roots of the number
differ by an `ℓ`-th root of unity, and the roots of unity themselves are powers of the primitive
one already present. -/
theorem sup_radicalField_singleton_eq_sup_adjoin (hℓ : ℓ ≠ 0) (hζ : IsPrimitiveRoot ζ ℓ)
    (hζA : ζ ∈ A) (hm0 : m ≠ 0) (hα : α ^ ℓ = algebraMap ℚ (AlgebraicClosure ℚ) m) :
    A ⊔ radicalField ℓ ({m} : Finset ℚ)
      = A ⊔ IntermediateField.adjoin ℚ ({α} : Set (AlgebraicClosure ℚ)) := by
  haveI : NeZero ℓ := ⟨hℓ⟩
  have hα0 : α ≠ 0 := by
    rintro rfl
    rw [zero_pow hℓ] at hα
    exact hm0 (FaithfulSMul.algebraMap_injective ℚ (AlgebraicClosure ℚ) (by rw [← hα, map_zero]))
  have hαmem : α ∈ A ⊔ IntermediateField.adjoin ℚ ({α} : Set (AlgebraicClosure ℚ)) :=
    (le_sup_right : IntermediateField.adjoin ℚ ({α} : Set (AlgebraicClosure ℚ)) ≤ _)
      (IntermediateField.subset_adjoin ℚ _ rfl)
  refine le_antisymm (sup_le le_sup_left ?_) (sup_le le_sup_left ?_)
  · rw [radicalField, IntermediateField.adjoin_le_iff]
    intro γ hγ
    obtain ⟨c, hc, hcγ⟩ := exists_mem_insert_pow_eq_of_mem_rootSet hγ
    rcases Finset.mem_insert.mp hc with rfl | hc1
    · obtain ⟨i, -, hi⟩ := hζ.eq_pow_of_pow_eq_one (by rw [hcγ, map_one])
      rw [← hi]
      exact (le_sup_left : A ≤ _) (pow_mem hζA i)
    · rw [Finset.mem_singleton] at hc1
      subst hc1
      obtain ⟨i, -, hi⟩ := hζ.eq_pow_of_pow_eq_one (ξ := γ / α)
        (by rw [div_pow, hcγ, hα, div_self (by rw [← hα]; exact pow_ne_zero _ hα0)])
      have hγeq : γ = ζ ^ i * α := by
        rw [hi, div_mul_cancel₀ _ hα0]
      rw [hγeq]
      exact mul_mem ((le_sup_left : A ≤ _) (pow_mem hζA i)) hαmem
  · rw [IntermediateField.adjoin_le_iff]
    rintro γ rfl
    exact (le_sup_right : radicalField ℓ ({m} : Finset ℚ) ≤ _)
      (IntermediateField.subset_adjoin ℚ _
        (mem_rootSet_radicalPoly hℓ (Finset.mem_insert_of_mem (Finset.mem_singleton_self m)) hα))

end Simple

/-! ### The exact degree -/

section Degree

variable {A : IntermediateField ℚ (AlgebraicClosure ℚ)} {m : ℚ} {α ζ : AlgebraicClosure ℚ}

/-- The degree over a field of an `ℓ`-th root of a rational number without an `ℓ`-th root there is
the prime `ℓ`: the polynomial `X ^ ℓ` minus the number is then irreducible, hence is the minimal
polynomial of the root. -/
theorem finrank_adjoin_of_forall_pow_ne (hℓ : ℓ.Prime)
    (hm : ∀ u ∈ A, u ^ ℓ ≠ algebraMap ℚ (AlgebraicClosure ℚ) m)
    (hα : α ^ ℓ = algebraMap ℚ (AlgebraicClosure ℚ) m) :
    finrank ↥A ↥(IntermediateField.adjoin ↥A ({α} : Set (AlgebraicClosure ℚ))) = ℓ := by
  have hmap : algebraMap ↥A (AlgebraicClosure ℚ) (algebraMap ℚ ↥A m)
      = algebraMap ℚ (AlgebraicClosure ℚ) m :=
    (IsScalarTower.algebraMap_apply ℚ ↥A (AlgebraicClosure ℚ) m).symm
  have haeval : Polynomial.aeval α (X ^ ℓ - C (algebraMap ℚ ↥A m)) = 0 := by
    rw [map_sub, map_pow, aeval_X, aeval_C, hmap, hα, sub_self]
  have hmonic : (X ^ ℓ - C (algebraMap ℚ ↥A m)).Monic :=
    Polynomial.monic_X_pow_sub_C _ hℓ.ne_zero
  have hirr : Irreducible (X ^ ℓ - C (algebraMap ℚ ↥A m)) := by
    refine X_pow_sub_C_irreducible_of_prime hℓ fun b hb => hm (b : AlgebraicClosure ℚ) b.2 ?_
    rw [← hmap, ← hb, map_pow]
    rfl
  rw [IntermediateField.adjoin.finrank ⟨_, hmonic, haeval⟩,
    ← minpoly.eq_of_irreducible_of_monic hirr haeval hmonic, natDegree_X_pow_sub_C]

/-- **The compositum of a field of `ℓ`-th roots of unity with the radical field of a rational
number having no `ℓ`-th root there has degree exactly `ℓ` times the degree of the field.**  The
compositum is generated over the field by a single `ℓ`-th root of the number, whose minimal
polynomial is `X ^ ℓ` minus the number. -/
theorem finrank_sup_radicalField_singleton (hℓ : ℓ.Prime) (hζ : IsPrimitiveRoot ζ ℓ) (hζA : ζ ∈ A)
    (hm : ∀ u ∈ A, u ^ ℓ ≠ algebraMap ℚ (AlgebraicClosure ℚ) m) :
    finrank ℚ ↥(A ⊔ radicalField ℓ ({m} : Finset ℚ)) = ℓ * finrank ℚ ↥A := by
  have hm0 : m ≠ 0 := by
    rintro rfl
    exact hm 0 (zero_mem A) (by rw [zero_pow hℓ.ne_zero, map_zero])
  obtain ⟨α, hα⟩ := IsAlgClosed.exists_pow_nat_eq
    (algebraMap ℚ (AlgebraicClosure ℚ) m) hℓ.pos
  have key := Module.finrank_mul_finrank ℚ ↥A
    ↥(IntermediateField.adjoin ↥A ({α} : Set (AlgebraicClosure ℚ)))
  rw [finrank_adjoin_of_forall_pow_ne hℓ hm hα, mul_comm] at key
  rw [sup_radicalField_singleton_eq_sup_adjoin hℓ.ne_zero hζ hζA hm0 hα,
    ← IntermediateField.restrictScalars_adjoin_eq_sup]
  exact key.symm

end Degree

end InverseGalois.CFT
