/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# The completion of a number field at a finite place is locally compact

The completion of the field of fractions of a Dedekind domain at a height one prime carries a
discrete valuation whose ring of integers is a complete discrete valuation ring.  Its residue field
is the residue field of the prime: every element of the completion of absolute value at most one is
approximated by an element of the field, and every element of the field of absolute value at most
one is approximated by an element of the Dedekind domain, because the ideal generated by a
denominator differs from a power of the prime by an ideal coprime to it.

When the Dedekind domain has finite residue fields — as the ring of integers of a number field does
— the residue field of the completion is therefore finite, and the completion is a proper metric
space.  This is what identifies the completion of a number field at a finite place as a
nonarchimedean local field, and so puts the theory of division algebras over local fields at its
disposal.

## Main results

* `InverseGalois.CFT.Local.exists_sub_valuation_lt_one`: **an element of the fraction field of
  absolute value at most one differs from an element of the Dedekind domain by an element of
  absolute value less than one.**
* `InverseGalois.CFT.Local.exists_sub_valued_lt_one`: the same statement for the completion.
* `InverseGalois.CFT.Local.residue_adicIntegersHom_surjective`: **the Dedekind domain surjects onto
  the residue field of the completion.**
* `InverseGalois.CFT.Local.properSpace_adicCompletion`: **the completion of a number field at a
  finite place is a proper metric space.**

## Tags

Dedekind domain, adic completion, local field, residue field, discrete valuation ring
-/

set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 400000

open IsDedekindDomain WithZero

namespace InverseGalois.CFT.Local

section Dedekind

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
variable (v : HeightOneSpectrum R)

/-- The ring of integers of the completion, described as the elements of absolute value at most
one, is a discrete valuation ring. -/
instance isDiscreteValuationRing_valuedInteger :
    IsDiscreteValuationRing (Valued.integer (v.adicCompletion K)) :=
  inferInstanceAs (IsDiscreteValuationRing (v.adicCompletionIntegers K))

variable {K}

/-- **An element of the fraction field of absolute value at most one differs from an element of the
Dedekind domain by an element of absolute value less than one.**  Writing the element as a quotient,
the ideal generated by the denominator is a power of the prime times an ideal coprime to it, so
adding one more factor of the prime to that power recovers the power itself; the numerator lies in
it, and the resulting decomposition is the required approximation. -/
theorem exists_sub_valuation_lt_one (y : K) (hy : v.valuation K y ≤ 1) :
    ∃ z : R, v.valuation K (y - algebraMap R K z) < 1 := by
  classical
  obtain ⟨⟨a, s⟩, rfl⟩ := IsLocalization.mk'_surjective (nonZeroDivisors R) y
  have hs0 : (s : R) ≠ 0 := nonZeroDivisors.coe_ne_zero s
  have hvs : v.intValuation (s : R) ≠ 0 := v.intValuation_ne_zero' s
  rw [HeightOneSpectrum.valuation_of_mk'] at hy
  have hle : v.intValuation a ≤ v.intValuation (s : R) := by
    rwa [div_le_one₀ (v.intValuation_zero_lt s)] at hy
  haveI : v.asIdeal.IsMaximal := v.isPrime.isMaximal v.ne_bot
  have hspan : (Ideal.span {(s : R)} : Ideal R) ≠ ⊥ := by
    simp [Ideal.span_singleton_eq_bot, hs0]
  obtain ⟨Q, hQ, hQeq⟩ := Ideal.eq_prime_pow_mul_coprime hspan v.asIdeal
  set c := Multiset.count v.asIdeal (UniqueFactorizationMonoid.normalizedFactors
    (Ideal.span {(s : R)} : Ideal R)) with hcdef
  have hsc : (s : R) ∈ v.asIdeal ^ c := by
    have hsub : (Ideal.span {(s : R)} : Ideal R) ≤ v.asIdeal ^ c := by
      rw [hQeq]; exact Ideal.mul_le_right
    exact hsub (Ideal.mem_span_singleton_self _)
  have hsc1 : (s : R) ∉ v.asIdeal ^ (c + 1) := by
    intro hmem
    rw [← Ideal.span_singleton_le_iff_mem, ← Ideal.dvd_iff_le, hQeq, pow_succ] at hmem
    have hne : (v.asIdeal ^ c : Ideal R) ≠ 0 :=
      pow_ne_zero _ (by simpa [Ideal.zero_eq_bot] using v.ne_bot)
    have hdvd : v.asIdeal ∣ Q := (mul_dvd_mul_iff_left hne).1 hmem
    have hQle : Q ≤ v.asIdeal := Ideal.le_of_dvd hdvd
    exact v.isPrime.ne_top (by rw [← hQ, sup_eq_left.2 hQle])
  have hvsle : v.intValuation (s : R) ≤ exp (-(c : ℤ)) :=
    (v.intValuation_le_pow_iff_mem _ c).2 hsc
  have hvsgt : exp (-((c : ℤ) + 1)) < v.intValuation (s : R) := by
    by_contra h
    push_neg at h
    exact hsc1 ((v.intValuation_le_pow_iff_mem _ (c + 1)).1 (by push_cast; exact h))
  have hac : a ∈ v.asIdeal ^ c := (v.intValuation_le_pow_iff_mem _ c).1 (hle.trans hvsle)
  have hsup : Ideal.span {(s : R)} ⊔ v.asIdeal ^ (c + 1) = v.asIdeal ^ c := by
    rw [hQeq, pow_succ, ← Ideal.mul_sup, sup_comm, hQ, Ideal.mul_top]
  obtain ⟨t, ht, w, hw, htw⟩ := Submodule.mem_sup.1 (hsup ▸ hac)
  obtain ⟨z, rfl⟩ := Ideal.mem_span_singleton'.1 ht
  refine ⟨z, ?_⟩
  have hsplit : IsLocalization.mk' K a s - algebraMap R K z = IsLocalization.mk' K w s := by
    rw [eq_comm, IsLocalization.mk'_eq_iff_eq_mul, sub_mul, IsLocalization.mk'_spec,
      ← map_mul, ← map_sub]
    exact congrArg _ (by linear_combination htw)
  rw [hsplit, HeightOneSpectrum.valuation_of_mk']
  refine (div_lt_one₀ (v.intValuation_zero_lt s)).2 (lt_of_le_of_lt ?_ hvsgt)
  have hwle := (v.intValuation_le_pow_iff_mem w (c + 1)).2 hw
  push_cast at hwle
  exact hwle

/-- An element of the completion of absolute value at most one differs from an element of the
Dedekind domain by an element of absolute value less than one: the field is dense in its
completion, and the field is approximated by the Dedekind domain. -/
theorem exists_sub_valued_lt_one (x : v.adicCompletion K) (hx : Valued.v x ≤ 1) :
    ∃ z : R, Valued.v (x - algebraMap R (v.adicCompletion K) z) < 1 := by
  have hball : {y : v.adicCompletion K | Valued.v (y - x) < 1} ∈ nhds x :=
    Valued.mem_nhds.2 ⟨1, by simp⟩
  have hdense : DenseRange (fun k : K => (k : v.adicCompletion K)) :=
    UniformSpace.Completion.denseRange_coe (α := WithVal (v.valuation K))
  obtain ⟨y, hy⟩ := hdense.mem_nhds hball
  simp only [Set.mem_setOf_eq] at hy
  have hyle : v.valuation K y ≤ 1 := by
    rw [← HeightOneSpectrum.valuedAdicCompletion_eq_valuation' v y]
    calc Valued.v ((y : v.adicCompletion K)) = Valued.v (((y : v.adicCompletion K) - x) + x) := by
          rw [sub_add_cancel]
      _ ≤ max (Valued.v ((y : v.adicCompletion K) - x)) (Valued.v x) := Valuation.map_add _ _ _
      _ ≤ 1 := max_le hy.le hx
  obtain ⟨z, hz⟩ := exists_sub_valuation_lt_one v y hyle
  refine ⟨z, ?_⟩
  have hcoe : algebraMap R (v.adicCompletion K) z
      = ((algebraMap R K z : K) : v.adicCompletion K) := rfl
  have hz' : Valued.v ((y : v.adicCompletion K)
      - algebraMap R (v.adicCompletion K) z) < 1 := by
    rw [hcoe, ← UniformSpace.Completion.coe_sub,
      HeightOneSpectrum.valuedAdicCompletion_eq_valuation' v (y - algebraMap R K z)]
    exact hz
  calc Valued.v (x - algebraMap R (v.adicCompletion K) z)
      = Valued.v ((x - (y : v.adicCompletion K))
        + ((y : v.adicCompletion K) - algebraMap R (v.adicCompletion K) z)) := by ring_nf
    _ ≤ max (Valued.v (x - (y : v.adicCompletion K)))
        (Valued.v ((y : v.adicCompletion K) - algebraMap R (v.adicCompletion K) z)) :=
      Valuation.map_add _ _ _
    _ < 1 := max_lt (by rwa [← Valuation.map_neg, neg_sub]) hz'

variable (K)

/-- The Dedekind domain maps into the ring of integers of the completion. -/
noncomputable def adicIntegersHom : R →+* Valued.integer (v.adicCompletion K) :=
  RingHom.codRestrict (algebraMap R (v.adicCompletion K)) _ fun r =>
    HeightOneSpectrum.coe_mem_adicCompletionIntegers (K := K) v r

@[simp]
theorem coe_adicIntegersHom (r : R) :
    ((adicIntegersHom K v r : Valued.integer (v.adicCompletion K)) : v.adicCompletion K)
      = algebraMap R (v.adicCompletion K) r := rfl

/-- The maximal ideal of the ring of integers of the completion consists of the elements of
absolute value less than one. -/
theorem mem_maximalIdeal_valuedInteger_iff (x : Valued.integer (v.adicCompletion K)) :
    x ∈ IsLocalRing.maximalIdeal (Valued.integer (v.adicCompletion K))
      ↔ Valued.v (x : v.adicCompletion K) < 1 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff,
    Valuation.Integer.not_isUnit_iff_valuation_lt_one]

/-- The prime is carried into the maximal ideal of the ring of integers of the completion. -/
theorem residue_adicIntegersHom_eq_zero {r : R} (hr : r ∈ v.asIdeal) :
    IsLocalRing.residue (Valued.integer (v.adicCompletion K)) (adicIntegersHom K v r) = 0 := by
  rw [IsLocalRing.residue_eq_zero_iff, mem_maximalIdeal_valuedInteger_iff, coe_adicIntegersHom,
    HeightOneSpectrum.algebraMap_adicCompletion, Function.comp_apply,
    HeightOneSpectrum.valuedAdicCompletion_eq_valuation' v (algebraMap R K r)]
  exact (HeightOneSpectrum.valuation_lt_one_iff_mem v r).2 hr

/-- **The Dedekind domain surjects onto the residue field of the completion.** -/
theorem residue_adicIntegersHom_surjective :
    Function.Surjective fun r : R =>
      IsLocalRing.residue (Valued.integer (v.adicCompletion K)) (adicIntegersHom K v r) := by
  intro t
  obtain ⟨x, rfl⟩ := IsLocalRing.residue_surjective t
  obtain ⟨z, hz⟩ := exists_sub_valued_lt_one v (x : v.adicCompletion K) x.2
  refine ⟨z, ?_⟩
  rw [eq_comm, ← sub_eq_zero, ← map_sub, IsLocalRing.residue_eq_zero_iff,
    mem_maximalIdeal_valuedInteger_iff]
  exact hz

/-- The residue field of the completion is finite as soon as the residue field of the prime is:
it is a quotient of the latter. -/
instance finite_residueField_adicCompletion [Finite (R ⧸ v.asIdeal)] :
    Finite (IsLocalRing.ResidueField (Valued.integer (v.adicCompletion K))) := by
  refine Finite.of_surjective (Ideal.Quotient.lift v.asIdeal
    ((IsLocalRing.residue (Valued.integer (v.adicCompletion K))).comp (adicIntegersHom K v))
    (fun r hr => residue_adicIntegersHom_eq_zero K v hr)) ?_
  intro t
  obtain ⟨r, hr⟩ := residue_adicIntegersHom_surjective K v t
  exact ⟨Ideal.Quotient.mk _ r, hr⟩

end Dedekind

section NumberField

open NumberField

variable (F : Type*) [Field F] [NumberField F] (w : HeightOneSpectrum (𝓞 F))

/-- A height one prime of the ring of integers of a number field has finite residue field. -/
instance finite_quotient_asIdeal : Finite (𝓞 F ⧸ w.asIdeal) :=
  w.asIdeal.finiteQuotientOfFreeOfNeBot w.ne_bot

open Valued.integer in
/-- **The completion of a number field at a finite place is a proper metric space.**  It is
complete, its ring of integers is a discrete valuation ring, and its residue field is finite. -/
instance properSpace_adicCompletion : ProperSpace (w.adicCompletion F) :=
  properSpace_iff_completeSpace_and_isDiscreteValuationRing_integer_and_finite_residueField.2
    ⟨inferInstance, inferInstance, inferInstance⟩

end NumberField

end InverseGalois.CFT.Local
