/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.UnitFiltration

/-!
# The residue field of an adic completion

Let `R` be a Dedekind domain with fraction field `K` and let `v` be a height one prime of `R`.
The completion `v.adicCompletion K` is a valued field whose value group is the integers, so it
falls under the theory of the unit filtration developed for an arbitrary such field.  This file
supplies the two arithmetic inputs that the theory asks for: a uniformizer, and the finiteness of
the residue field, that is, of the graded piece `gradedAdd (v.adicCompletion K) 0`.

The uniformizer is inherited from `K` itself, because the valuation of the completion restricts to
the `v`-adic valuation of `K`.  Finiteness rests on two approximation steps.  First, `K` is dense
in its completion, so every element of the valuation ring of the completion is congruent, modulo
elements of valuation at most that of a uniformizer, to an element of `K` of valuation at most
one.  Second, an element of `K` of valuation at most one is congruent, again modulo elements of
small valuation, to an element of `R`: writing the element as a fraction `n / d`, factoring the
ideal generated by `d` as a power of `v` times an ideal prime to `v`, and using that the latter is
comaximal with `v`, one finds that the ideal generated by `d` together with the next power of `v`
already contains `n`.  Composing the two steps exhibits the residue field of the completion as a
quotient of `R ⧸ v`, which for the ring of integers of a number field is finite.

## Main results

* `InverseGalois.CFT.exists_algebraMap_sub_le_exp_neg_one`: **an element of the valuation ring of
  the completion is congruent to an element of `R` modulo the maximal ideal.**
* `InverseGalois.CFT.exists_uniformizer_adicCompletion`: **the adic completion carries a
  uniformizer.**
* `InverseGalois.CFT.finite_gradedAdd_adicCompletion_zero`: **the residue field of the adic
  completion is finite** whenever the residue field of `R` at `v` is.
* `InverseGalois.CFT.instFiniteGradedAddAdicCompletionNumberField`: the residue field of the adic
  completion of a number field at a finite place is finite.

## Tags

Dedekind domain, adic completion, residue field, uniformizer, local field
-/

namespace InverseGalois.CFT

open scoped WithZero

open IsDedekindDomain NumberField

/-! ### An arithmetic remark on the value group -/

/-- A value of the integers which is smaller than one is at most the value of a uniformizer. -/
theorem le_exp_neg_one_of_lt_one {g : ℤᵐ⁰} (hg : g < 1) : g ≤ WithZero.exp (-1 : ℤ) := by
  rcases eq_or_ne g 0 with rfl | hg0
  · exact zero_le'
  · refine WithZero.le_exp_of_log_le ?_
    have hlt : WithZero.log g < 0 := by
      refine (WithZero.log_lt_iff_lt_exp hg0).mpr ?_
      simpa using hg
    omega

/-! ### Approximating an element of the field by an element of the ring -/

variable {R : Type*} [CommRing R] [IsDedekindDomain R] {K : Type*} [Field K] [Algebra R K]
  [IsFractionRing R K] (v : HeightOneSpectrum R)

/-- **An element of `K` whose `v`-adic valuation is at most one is congruent to an element of `R`
modulo the elements of valuation at most that of a uniformizer.**  Writing the element as `n / d`
and letting `m` be the exponent of `v` in the ideal generated by `d`, the ideal generated by `d`
together with the `(m + 1)`-st power of `v` is the `m`-th power of `v`, which contains `n`. -/
theorem exists_valuation_sub_algebraMap_le {a : K} (ha : v.valuation K a ≤ 1) :
    ∃ b : R, v.valuation K (a - algebraMap R K b) ≤ WithZero.exp (-1 : ℤ) := by
  classical
  obtain ⟨⟨n, ⟨d, hd⟩⟩, hx⟩ := IsLocalization.surj (nonZeroDivisors R) a
  simp only at hx
  have hd0 : d ≠ 0 := nonZeroDivisors.ne_zero hd
  have hdK : algebraMap R K d ≠ 0 :=
    fun h => hd0 (IsFractionRing.to_map_eq_zero_iff.mp h)
  have hvd0 : v.intValuation d ≠ 0 := v.intValuation_ne_zero d hd0
  have hlogle : WithZero.log (v.intValuation d) ≤ 0 := by
    refine (WithZero.log_le_iff_le_exp hvd0).mpr ?_
    simpa using v.intValuation_le_one d
  set m : ℕ := (-WithZero.log (v.intValuation d)).toNat with hmdef
  have hmcast : (m : ℤ) = -WithZero.log (v.intValuation d) := Int.toNat_of_nonneg (by omega)
  have hmv : v.intValuation d = WithZero.exp (-(m : ℤ)) := by
    rw [hmcast, neg_neg, WithZero.exp_log hvd0]
  -- The numerator lies in the `m`-th power of `v`.
  have hnval : v.intValuation n = v.valuation K a * v.intValuation d := by
    have h1 : v.valuation K (algebraMap R K n) = v.valuation K (a * algebraMap R K d) := by
      rw [hx]
    rwa [map_mul, v.valuation_of_algebraMap, v.valuation_of_algebraMap] at h1
  have hnmem : n ∈ v.asIdeal ^ m := by
    rw [← v.intValuation_le_pow_iff_mem, hnval, ← hmv]
    calc v.valuation K a * v.intValuation d ≤ 1 * v.intValuation d := mul_le_mul_left ha _
      _ = v.intValuation d := one_mul _
  -- The denominator lies in the `m`-th power of `v` but not in the next one.
  have hdmem : d ∈ v.asIdeal ^ m := (v.intValuation_le_pow_iff_mem d m).mp (le_of_eq hmv)
  have hdnot : d ∉ v.asIdeal ^ (m + 1) := by
    intro hcon
    have hle := (v.intValuation_le_pow_iff_mem d (m + 1)).mpr hcon
    rw [hmv] at hle
    push_cast at hle
    rw [WithZero.exp_le_exp] at hle
    omega
  -- Factor the ideal generated by the denominator.
  obtain ⟨J, hJ⟩ : v.asIdeal ^ m ∣ Ideal.span {d} :=
    Ideal.dvd_iff_le.mpr (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hdmem))
  have hmax : v.asIdeal.IsMaximal := v.isMaximal
  have hJsup : J ⊔ v.asIdeal = ⊤ := by
    by_contra hcon
    have heq : v.asIdeal = J ⊔ v.asIdeal := hmax.eq_of_le hcon le_sup_right
    have hle : J ≤ v.asIdeal := heq ▸ le_sup_left
    refine hdnot ?_
    have hsub : Ideal.span {d} ≤ v.asIdeal ^ (m + 1) := by
      rw [hJ, pow_succ]
      exact Ideal.mul_mono le_rfl hle
    exact hsub (Ideal.mem_span_singleton_self d)
  have hsup : Ideal.span {d} ⊔ v.asIdeal ^ (m + 1) = v.asIdeal ^ m := by
    rw [hJ, pow_succ, ← Ideal.mul_sup, hJsup, Ideal.mul_top]
  obtain ⟨x, hxmem, z, hzmem, hxz⟩ := Submodule.mem_sup.mp (hsup ▸ hnmem)
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hxmem
  refine ⟨b, ?_⟩
  -- The difference is `z / d`, whose valuation is at most that of a uniformizer.
  have hn : n = b * d + z := by rw [← hxz, ← hb]
  have hzeq : (a - algebraMap R K b) * algebraMap R K d = algebraMap R K z := by
    rw [sub_mul, hx, hn, map_add, map_mul]
    ring
  have hkey : a - algebraMap R K b = algebraMap R K z / algebraMap R K d :=
    (eq_div_iff hdK).mpr hzeq
  have hzle : v.intValuation z ≤ WithZero.exp (-((m : ℤ) + 1)) := by
    have hmem := (v.intValuation_le_pow_iff_mem z (m + 1)).mpr hzmem
    push_cast at hmem
    exact hmem
  rw [hkey, map_div₀, v.valuation_of_algebraMap, v.valuation_of_algebraMap, hmv, div_eq_mul_inv]
  calc v.intValuation z * (WithZero.exp (-(m : ℤ)))⁻¹
      ≤ WithZero.exp (-((m : ℤ) + 1)) * (WithZero.exp (-(m : ℤ)))⁻¹ := mul_le_mul_left hzle _
    _ = WithZero.exp (-1 : ℤ) := by
        rw [← WithZero.exp_neg, ← WithZero.exp_add]
        congr 1
        ring

/-! ### Approximating an element of the completion by an element of the field -/

variable (K)

/-- **The field is dense in its adic completion**, in the quantitative form that every element of
the completion is within the value of a uniformizer of an element of the field. -/
theorem exists_valued_sub_coe_le (x : v.adicCompletion K) :
    ∃ a : K, Valued.v (x - (a : v.adicCompletion K)) ≤ WithZero.exp (-1 : ℤ) := by
  have hdense : DenseRange ((↑) : WithVal (v.valuation K) → v.adicCompletion K) :=
    UniformSpace.Completion.denseRange_coe
  have hnhds : {y : v.adicCompletion K | Valued.v (y - x) < 1} ∈ nhds x := by
    rw [Valued.mem_nhds]
    exact ⟨1, by simp⟩
  obtain ⟨y, hymem, hyrange⟩ := mem_closure_iff_nhds.mp (hdense x) _ hnhds
  obtain ⟨a, rfl⟩ := hyrange
  refine ⟨a, le_exp_neg_one_of_lt_one ?_⟩
  have hswap : Valued.v (x - (a : v.adicCompletion K))
      = Valued.v ((a : v.adicCompletion K) - x) := Valuation.map_sub_swap _ _ _
  rw [hswap]
  exact hymem

/-- **An element of the valuation ring of the adic completion is congruent to an element of `R`**
modulo the elements of valuation at most that of a uniformizer.  This combines the density of `K`
in its completion with the approximation of an element of `K` by an element of `R`. -/
theorem exists_algebraMap_sub_le_exp_neg_one {x : v.adicCompletion K} (hx : Valued.v x ≤ 1) :
    ∃ b : R, Valued.v (x - algebraMap R (v.adicCompletion K) b) ≤ WithZero.exp (-1 : ℤ) := by
  obtain ⟨a, ha⟩ := exists_valued_sub_coe_le K v x
  have hexp : WithZero.exp (-1 : ℤ) ≤ (1 : ℤᵐ⁰) := by
    simpa using WithZero.exp_le_exp.mpr (by omega : (-1 : ℤ) ≤ 0)
  have hva : v.valuation K a ≤ 1 := by
    rw [← HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := v) a]
    have hrw : ((a : v.adicCompletion K)) = x - (x - (a : v.adicCompletion K)) := by ring
    rw [hrw]
    refine le_trans (Valuation.map_sub _ _ _) (max_le hx (ha.trans hexp))
  obtain ⟨b, hb⟩ := exists_valuation_sub_algebraMap_le v hva
  refine ⟨b, ?_⟩
  have hsplit : x - algebraMap R (v.adicCompletion K) b
      = (x - (a : v.adicCompletion K))
        + ((a : v.adicCompletion K) - ((algebraMap R K b : K) : v.adicCompletion K)) := by
    have hmap : algebraMap R (v.adicCompletion K) b
        = ((algebraMap R K b : K) : v.adicCompletion K) := rfl
    rw [hmap]
    ring
  have hcoe : (a : v.adicCompletion K) - ((algebraMap R K b : K) : v.adicCompletion K)
      = ((a - algebraMap R K b : K) : v.adicCompletion K) := by
    push_cast
    ring
  rw [hsplit, hcoe]
  refine le_trans (Valuation.map_add _ _ _) (max_le ha ?_)
  rw [HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := v)]
  exact hb

/-! ### A uniformizer and a finite residue field -/

/-- **The adic completion of a Dedekind domain at a height one prime carries a uniformizer**, that
is, an element whose value generates the value group. -/
theorem exists_uniformizer_adicCompletion :
    ∃ π : v.adicCompletion K, Valued.v π = WithZero.exp (-1 : ℤ) := by
  obtain ⟨π, hπ⟩ := v.valuation_exists_uniformizer K
  refine ⟨(π : v.adicCompletion K), ?_⟩
  rw [HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := v)]
  exact hπ

/-- The image in the adic completion of an element of `R` lies in the valuation ring, that is, in
the zeroth step of the additive filtration. -/
theorem algebraMap_mem_valAddSubgroup_zero (b : R) :
    algebraMap R (v.adicCompletion K) b ∈ valAddSubgroup (v.adicCompletion K) 0 := by
  rw [mem_valAddSubgroup, neg_zero, WithZero.exp_zero]
  have hmap : algebraMap R (v.adicCompletion K) b
      = ((algebraMap R K b : K) : v.adicCompletion K) := rfl
  rw [hmap, HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := v)]
  exact v.valuation_le_one b

/-- The image in the residue field of the adic completion of an element of `R`. -/
noncomputable def adicResidueRep (b : R) : ↥(valAddSubgroup (v.adicCompletion K) 0) :=
  ⟨algebraMap R (v.adicCompletion K) b, algebraMap_mem_valAddSubgroup_zero K v b⟩

/-- Two elements of `R` congruent modulo `v` have the same image in the residue field of the adic
completion. -/
theorem adicResidueRep_eq_of_sub_mem {b c : R} (h : b - c ∈ v.asIdeal) :
    (QuotientAddGroup.mk (adicResidueRep K v b) : gradedAdd (v.adicCompletion K) 0)
      = QuotientAddGroup.mk (adicResidueRep K v c) := by
  refine gradedAdd_mk_eq ?_
  have hsub : ((adicResidueRep K v b : v.adicCompletion K)
      - (adicResidueRep K v c : v.adicCompletion K))
      = ((algebraMap R K (b - c) : K) : v.adicCompletion K) := by
    have hb : (adicResidueRep K v b : v.adicCompletion K)
        = ((algebraMap R K b : K) : v.adicCompletion K) := rfl
    have hc : (adicResidueRep K v c : v.adicCompletion K)
        = ((algebraMap R K c : K) : v.adicCompletion K) := rfl
    rw [hb, hc, map_sub]
    push_cast
    ring
  rw [hsub, HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := v),
    v.valuation_of_algebraMap]
  refine le_exp_neg_one_of_lt_one ?_
  · simpa using (v.intValuation_lt_one_iff_mem (b - c)).mpr h

/-- **The residue field of the adic completion is finite** as soon as the residue field of `R` at
`v` is: reducing an element of `R` modulo `v` gives a surjection of the latter onto the former. -/
theorem finite_gradedAdd_adicCompletion_zero [Finite (R ⧸ v.asIdeal)] :
    Finite (gradedAdd (v.adicCompletion K) 0) := by
  classical
  refine Finite.of_surjective
    (fun y : R ⧸ v.asIdeal =>
      (QuotientAddGroup.mk
        (adicResidueRep K v (Function.surjInv Ideal.Quotient.mk_surjective y)) :
          gradedAdd (v.adicCompletion K) 0)) ?_
  intro g
  induction g using QuotientAddGroup.induction_on with
  | H w =>
    obtain ⟨b, hb⟩ := exists_algebraMap_sub_le_exp_neg_one K v
      (by simpa using mem_valAddSubgroup.mp w.2)
    refine ⟨Ideal.Quotient.mk v.asIdeal b, ?_⟩
    show (QuotientAddGroup.mk (adicResidueRep K v
        (Function.surjInv Ideal.Quotient.mk_surjective (Ideal.Quotient.mk v.asIdeal b))) :
          gradedAdd (v.adicCompletion K) 0) = QuotientAddGroup.mk w
    have hsurj : Ideal.Quotient.mk v.asIdeal
        (Function.surjInv (f := Ideal.Quotient.mk v.asIdeal) Ideal.Quotient.mk_surjective
          (Ideal.Quotient.mk v.asIdeal b)) = Ideal.Quotient.mk v.asIdeal b :=
      Function.surjInv_eq Ideal.Quotient.mk_surjective _
    rw [adicResidueRep_eq_of_sub_mem K v (Ideal.Quotient.eq.mp hsurj)]
    refine gradedAdd_mk_eq ?_
    have hrep : (adicResidueRep K v b : v.adicCompletion K)
        = algebraMap R (v.adicCompletion K) b := rfl
    have hswap : Valued.v ((adicResidueRep K v b : v.adicCompletion K) - (w : v.adicCompletion K))
        = Valued.v ((w : v.adicCompletion K) - (adicResidueRep K v b : v.adicCompletion K)) :=
      Valuation.map_sub_swap _ _ _
    rw [hswap, hrep]
    simpa using hb

/-- The residue field of the adic completion of a number field at a finite place is finite. -/
instance instFiniteGradedAddAdicCompletionNumberField {F : Type*} [Field F] [NumberField F]
    (w : HeightOneSpectrum (𝓞 F)) : Finite (gradedAdd (w.adicCompletion F) 0) :=
  have : Finite (𝓞 F ⧸ w.asIdeal) := w.asIdeal.finiteQuotientOfFreeOfNeBot w.ne_bot
  finite_gradedAdd_adicCompletion_zero F w

end InverseGalois.CFT
