/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.RealPlace
import InverseGalois.CFT.Tate.GaloisH0

/-!
# The Herbrand quotient of the complex units

Complex conjugation generates the Galois group of `ℂ / ℝ`, a cyclic group of order two, and the
norms from `ℂˣ` are exactly the positive real units.  The Herbrand quotient of the unit group of a
cyclic extension is the index of the norms in the units of the base field, so the Herbrand quotient
of `ℂˣ` for complex conjugation is two.

This is the local factor of the group of ideles at a ramified real place: the completion there is
the complex numbers and the decomposition group is generated by complex conjugation, so its
Herbrand quotient is the order of the decomposition group, exactly as at a finite place.

## Main results

* `InverseGalois.CFT.index_normSubgroup_real_complex`: the norms from `ℂˣ` have index two in `ℝˣ`.
* `InverseGalois.CFT.card_gal_complex_real`: the Galois group of `ℂ / ℝ` has order two.
* `InverseGalois.CFT.herbrand_complexUnits`: **the Herbrand quotient of `ℂˣ` for complex
  conjugation is two.**

## Tags

Herbrand quotient, complex conjugation, real place, norm index
-/

namespace InverseGalois.CFT

/-- **The norms from `ℂˣ` have index two in `ℝˣ`.**  The quotient is the sign group. -/
theorem index_normSubgroup_real_complex : (normSubgroup ℝ ℂ).index = 2 := by
  rw [Subgroup.index_eq_card, Nat.card_congr realUnitsQuotientEquiv.toEquiv]
  simp [Nat.card_eq_fintype_card]

/-- **The Galois group of `ℂ / ℝ` has order two.** -/
theorem card_gal_complex_real : Nat.card Gal(ℂ/ℝ) = 2 := by
  rw [IsGalois.card_aut_eq_finrank, Complex.finrank_real_complex]

/-- **The Herbrand quotient of `ℂˣ` for complex conjugation is two.**  The lower Tate group
vanishes by Hilbert's theorem 90 and the upper one is the sign group. -/
theorem herbrand_complexUnits : herbrand (addAut (unitsAut Complex.conjAe)) 2 = 2 := by
  have h := herbrand_units Complex.conjAe forall_mem_zpowers_conjAe
  rw [card_gal_complex_real, index_normSubgroup_real_complex] at h
  rw [h]
  norm_num

end InverseGalois.CFT
