/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.ComplexHerbrand
import InverseGalois.CFT.Local.InfiniteAction
import InverseGalois.CFT.Local.UnitValuation
import InverseGalois.CFT.Tate.Congr
import InverseGalois.CFT.Tate.InducedLattice

/-!
# The Herbrand quotient of the units at an infinite place

The decomposition group of an infinite place of a Galois extension of number fields has order one
or two, and it has order two exactly when the place is complex and lies above a real place.  In the
first case the group is trivial and the Herbrand quotient of any module over it is one; in the
second case the completion is the complex numbers and the nontrivial element of the decomposition
group acts by complex conjugation, so the Herbrand quotient of the units is two.

Either way the Herbrand quotient of the units of the completion is the order of the decomposition
group, which is the same statement as at a finite place.  This is what makes the archimedean places
contribute to the Herbrand quotient of the ideles by exactly the same formula as the finite ones.

## Main results

* `InverseGalois.CFT.embedding_smul_of_ne_one`: a nontrivial automorphism fixing an infinite place
  conjugates the embedding attached to that place.
* `InverseGalois.CFT.extensionEmbedding_stabilizer_smul_of_ne_one`: the same statement on the
  completion.
* `InverseGalois.CFT.herbrand_infiniteUnits_eq_card`: **the units of the completion at an infinite
  place have Herbrand quotient the order of the decomposition group.**

## Tags

number field, infinite place, decomposition group, Herbrand quotient, complex conjugation
-/

namespace InverseGalois.CFT

open MulAction NumberField NumberField.InfinitePlace

variable {k K : Type*} [Field k] [Field K] [Algebra k K] (w : InfinitePlace K)

/-! ### The nontrivial element of a decomposition group -/

/-- **A nontrivial automorphism fixing an infinite place conjugates the embedding attached to that
place.** -/
theorem embedding_smul_of_ne_one {σ : Gal(K/k)} (hσ : σ ∈ stabilizer Gal(K/k) w)
    (hσ1 : σ ≠ 1) (x : K) : w.embedding (σ x) = starRingEnd ℂ (w.embedding x) := by
  rw [← mk_embedding w, mem_stabilizer_mk_iff] at hσ
  exact (hσ.resolve_left hσ1).eq x

/-- **A nontrivial element of the decomposition group at an infinite place acts on the completion
by complex conjugation**, read through the embedding of the completion into the complex numbers. -/
theorem extensionEmbedding_stabilizer_smul_of_ne_one {σ : ↥(stabilizer Gal(K/k) w)}
    (hσ1 : (σ : Gal(K/k)) ≠ 1) (z : w.Completion) :
    Completion.extensionEmbedding w (σ • z)
      = starRingEnd ℂ (Completion.extensionEmbedding w z) := by
  refine UniformSpace.Completion.induction_on z ?_ ?_
  · exact isClosed_eq
      ((Completion.isometry_extensionEmbedding w).continuous.comp
        (continuous_infiniteCompletionAut w σ.1 (mem_stabilizer_iff.mp σ.2)))
      (Complex.continuous_conj.comp (Completion.isometry_extensionEmbedding w).continuous)
  · intro x
    rw [smul_infiniteCompletion_coe, Completion.extensionEmbedding_coe,
      Completion.extensionEmbedding_coe]
    exact embedding_smul_of_ne_one w σ.2 hσ1 _

/-! ### The Herbrand quotient -/

/-- **The units of the completion at an infinite place have Herbrand quotient the order of the
decomposition group.**  An unramified place has a trivial decomposition group, and a ramified one
has completion the complex numbers with the decomposition group generated by complex
conjugation. -/
theorem herbrand_infiniteUnits_eq_card [IsGalois k K] {σ : ↥(stabilizer Gal(K/k) w)}
    (hgen : ∀ g : ↥(stabilizer Gal(K/k) w), g ∈ Subgroup.zpowers σ) {d : ℕ}
    (hcard : Nat.card ↥(stabilizer Gal(K/k) w) = d) :
    herbrand (smulUnitsAut (R := w.Completion) σ) d = d := by
  rcases InfinitePlace.nat_card_stabilizer_eq_one_or_two k w with h1 | h2
  · rw [← hcard, h1, herbrand_one]
    norm_num
  · have hd : d = 2 := by rw [← hcard, h2]
    subst hd
    -- the place is ramified, hence complex
    have hram : w.IsRamified k := InfinitePlace.isRamified_iff_card_stabilizer_eq_two.mpr h2
    have hcx : w.IsComplex := hram.isComplex
    -- the generator of a group of order two is nontrivial
    have hσ1 : (σ : Gal(K/k)) ≠ 1 := by
      intro h
      have hone : σ = 1 := Subtype.ext h
      have : ∀ g : ↥(stabilizer Gal(K/k) w), g = 1 := by
        intro g
        obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.mp (hgen g)
        rw [← hm, hone, one_zpow]
      have : Subsingleton ↥(stabilizer Gal(K/k) w) := ⟨fun a b => by rw [this a, this b]⟩
      rw [Nat.card_eq_one_iff_unique.mpr ⟨this, ⟨1⟩⟩] at h2
      exact absurd h2 (by norm_num)
    -- the completion is the complex numbers, equivariantly for the conjugation
    set ec : w.Completion ≃+* ℂ := Completion.ringEquivComplexOfIsComplex hcx with hec_def
    have hec : ∀ z : w.Completion, ec (σ • z) = starRingEnd ℂ (ec z) :=
      extensionEmbedding_stabilizer_smul_of_ne_one w hσ1
    set e : Additive (w.Completion)ˣ ≃+ Additive ℂˣ :=
      MulEquiv.toAdditive (Units.mapEquiv ec.toMulEquiv) with he_def
    have he : ∀ a, e (smulUnitsAut (R := w.Completion) σ a)
        = addAut (unitsAut Complex.conjAe) (e a) := by
      intro a
      refine Units.ext ?_
      exact hec _
    rw [herbrand_congr e he 2, herbrand_complexUnits]
    norm_num

end InverseGalois.CFT
