/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.AdicResidue
import InverseGalois.CFT.Local.Exp
import InverseGalois.CFT.SplitCompositum

/-!
# Places of residue degree one have prime residue field

A finite place `v` of a number field `K` lying over the rational prime `p` has residue degree one
exactly when the residue field at `v` is no larger than the prime field, that is, when every
element of `𝓞 K` is congruent modulo `v` to a rational integer.  Passing to the completion costs
nothing: the field `K` is dense in `v.adicCompletion K`, and an element of the valuation ring of
the completion is already congruent to an element of `𝓞 K` modulo the maximal ideal.

The conclusion is the shape in which the local hypotheses of the central embedding criterion ask
for a prime residue field: every element of the completion of valuation at most one differs from a
rational integer by an element of valuation strictly less than one.

## Main results

* `InverseGalois.CFT.surjective_intCast_quotient_of_inertiaDeg_eq_one`: **residue degree one makes
  the rational integers surject onto the residue field.**
* `InverseGalois.CFT.exists_intCast_sub_lt_one_of_inertiaDeg_eq_one`: **at a place of residue
  degree one every integer of the completion is congruent to a rational integer.**
* `InverseGalois.CFT.exists_hasResidueChar_of_liesOver`: **the completion at a place over `p`
  has residue characteristic `p`.**
* `InverseGalois.CFT.exists_hasResidueChar_and_primeResidue`: the three together, in the shape the
  local solvability criterion asks for.

## Tags

residue field, residue degree, adic completion, number field
-/

namespace InverseGalois.CFT

open scoped WithZero

open IsDedekindDomain NumberField Module

variable {K : Type*} [Field K] [NumberField K]

/-- **The rational integers surject onto a residue field of degree one.**  The residue field is an
extension of the prime field of rank one, so it is generated by the image of the prime field, and
that image is the image of `ℤ`. -/
theorem surjective_intCast_quotient_of_inertiaDeg_eq_one {p : ℕ} (hp : p.Prime)
    (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})]
    (hf : (Ideal.span {(p : ℤ)}).inertiaDeg P = 1) :
    Function.Surjective (Int.cast : ℤ → 𝓞 K ⧸ P) := by
  haveI := isMaximal_span_prime hp
  let _ : Field (ℤ ⧸ Ideal.span {(p : ℤ)}) := Ideal.Quotient.field _
  haveI : Nontrivial (𝓞 K ⧸ P) :=
    Ideal.Quotient.nontrivial_of_liesOver_of_isPrime P (Ideal.span {(p : ℤ)})
  have hbot : (⊥ : Subalgebra (ℤ ⧸ Ideal.span {(p : ℤ)}) (𝓞 K ⧸ P)) = ⊤ :=
    Subalgebra.bot_eq_top_of_finrank_eq_one
      (by rwa [← Ideal.inertiaDeg_algebraMap (Ideal.span {(p : ℤ)}) P])
  intro x
  have hx : x ∈ (⊥ : Subalgebra (ℤ ⧸ Ideal.span {(p : ℤ)}) (𝓞 K ⧸ P)) := by
    rw [hbot]; trivial
  obtain ⟨y, hy⟩ := Algebra.mem_bot.mp hx
  obtain ⟨z, rfl⟩ := Ideal.Quotient.mk_surjective y
  exact ⟨z, by rw [← hy, eq_intCast (Ideal.Quotient.mk (Ideal.span {(p : ℤ)})) z, map_intCast]⟩

/-- **At a place of residue degree one every integer of the completion is congruent to a rational
integer.**  Density of the number field in its completion reduces the claim to an element of the
ring of integers, and residue degree one makes that element congruent to a rational integer modulo
the place. -/
theorem exists_intCast_sub_lt_one_of_inertiaDeg_eq_one {p : ℕ} (hp : p.Prime)
    (v : HeightOneSpectrum (𝓞 K)) [v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})]
    (hf : (Ideal.span {(p : ℤ)}).inertiaDeg v.asIdeal = 1) {x : v.adicCompletion K}
    (hx : Valued.v x ≤ 1) : ∃ b : ℤ, Valued.v (x - (b : v.adicCompletion K)) < 1 := by
  obtain ⟨r, hr⟩ := exists_algebraMap_sub_le_exp_neg_one K v hx
  obtain ⟨b, hb⟩ :=
    surjective_intCast_quotient_of_inertiaDeg_eq_one hp v.asIdeal hf (Ideal.Quotient.mk _ r)
  refine ⟨b, ?_⟩
  -- the difference of `r` and `b` lies in the place
  have hmem : r - (b : 𝓞 K) ∈ v.asIdeal := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, sub_eq_zero,
      map_intCast (Ideal.Quotient.mk v.asIdeal) b]
    exact hb.symm
  -- so it has valuation less than one, while the first difference is at most that of a uniformizer
  have hlt : Valued.v (algebraMap (𝓞 K) (v.adicCompletion K) (r - (b : 𝓞 K))) < 1 := by
    rw [HeightOneSpectrum.valuedAdicCompletion_eq_valuation]
    exact (HeightOneSpectrum.valuation_lt_one_iff_mem v _).mpr hmem
  have hsplit : x - (b : v.adicCompletion K)
      = (x - algebraMap (𝓞 K) (v.adicCompletion K) r)
        + algebraMap (𝓞 K) (v.adicCompletion K) (r - (b : 𝓞 K)) := by
    rw [map_sub, map_intCast]
    ring
  have hexp : (WithZero.exp (-1 : ℤ) : ℤᵐ⁰) < 1 := by
    simpa using WithZero.exp_lt_exp.mpr (by omega : (-1 : ℤ) < 0)
  rw [hsplit]
  exact lt_of_le_of_lt (Valuation.map_add _ _ _) (max_lt (lt_of_le_of_lt hr hexp) hlt)

/-! ### The residue characteristic of the completion -/

/-- **The completion at a place over `p` has residue characteristic `p`.**  The rational prime lies
in the place, so it has valuation less than one there, and it is nonzero, so its valuation is the
exponential of a negative integer. -/
theorem exists_hasResidueChar_of_liesOver {p : ℕ} (hp : p.Prime)
    (v : HeightOneSpectrum (𝓞 K)) [v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] :
    ∃ e : ℕ, HasResidueChar (v.adicCompletion K) p e := by
  -- the rational prime lies in the place
  have hmem : ((p : ℕ) : 𝓞 K) ∈ v.asIdeal := by
    have hz : (p : ℤ) ∈ Ideal.span {(p : ℤ)} := Ideal.subset_span rfl
    rw [Ideal.LiesOver.over (p := Ideal.span {(p : ℤ)}) (P := v.asIdeal)] at hz
    simpa using hz
  have hval : Valued.v ((p : ℕ) : v.adicCompletion K)
      = v.valuation K (algebraMap (𝓞 K) K ((p : ℕ) : 𝓞 K)) := by
    rw [← map_natCast (algebraMap (𝓞 K) (v.adicCompletion K)) p,
      HeightOneSpectrum.valuedAdicCompletion_eq_valuation]
  have hlt : Valued.v ((p : ℕ) : v.adicCompletion K) < 1 := by
    rw [hval]
    exact (HeightOneSpectrum.valuation_lt_one_iff_mem v _).mpr hmem
  have hne : Valued.v ((p : ℕ) : v.adicCompletion K) ≠ 0 := by
    rw [hval]
    refine (Valuation.ne_zero_iff _).mpr ?_
    simpa using hp.ne_zero
  -- so its valuation is the exponential of a negative integer
  have hlog : WithZero.log (Valued.v ((p : ℕ) : v.adicCompletion K)) < 0 :=
    (WithZero.log_lt_iff_lt_exp hne).mpr (by simpa using hlt)
  refine ⟨(-WithZero.log (Valued.v ((p : ℕ) : v.adicCompletion K))).toNat, hp, by omega, ?_⟩
  rw [Int.toNat_of_nonneg (by omega), neg_neg, WithZero.exp_log hne]

/-- **The local data at a place of residue degree one.**  This is the exact shape in which the
local solvability criterion for a central embedding problem asks for its arithmetic input at a
ramified place: a residue characteristic, a prime residue field, and a congruence. -/
theorem exists_hasResidueChar_and_primeResidue {p : ℕ} (hp : p.Prime)
    (v : HeightOneSpectrum (𝓞 K)) [v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})]
    (hdeg : (Ideal.span {(p : ℤ)}).inertiaDeg v.asIdeal = 1) {m : ℕ} (hm : m ∣ p - 1) :
    ∃ q e : ℕ, HasResidueChar (v.adicCompletion K) q e ∧
      (∀ x : v.adicCompletion K, Valued.v x ≤ 1 →
        ∃ b : ℤ, Valued.v (x - (b : v.adicCompletion K)) < 1) ∧ m ∣ q - 1 :=
  let ⟨e, he⟩ := exists_hasResidueChar_of_liesOver hp v
  ⟨p, e, he, fun _ hx => exists_intCast_sub_lt_one_of_inertiaDeg_eq_one hp v hdeg hx, hm⟩

end InverseGalois.CFT
