import Mathlib
import InverseGalois.CFT.Local.HilbertSymbol
import InverseGalois.CFT.Local.PadicSquares
import InverseGalois.CFT.Local.PadicHilbert

/-!
# The norm form of the unramified quadratic extension of `ℚ_[p]`

Fix an odd prime `p` and a unit `w` of `ℤ_[p]` whose residue mod `p` is not a square.  Then
`(w : ℚ_[p])` is a nonsquare of `ℚ_[p]` and `ℚ_[p](√w)` is the *unramified* quadratic extension.
This file identifies its group of norms: a nonzero `p`-adic number is of the shape
`u ^ 2 - w * v ^ 2` exactly when its valuation is even.  Equivalently, the Hilbert symbol
`⟨a, w⟩` is `1` for `a` of even valuation and `-1` for `a` of odd valuation, so that `⟨-, w⟩` is
the unramified quadratic character.

The argument is elementary and rests on two observations.  The first is that the norm form is
multiplicative,
`(s ^ 2 - w t ^ 2) (s' ^ 2 - w t' ^ 2) = (s s' + w t t') ^ 2 - w (s t' + t s') ^ 2`,
so that the values it takes on the nonzero elements form a subgroup of `ℚ_[p]ˣ`.  The second is
Hensel's lemma: every unit of `ℤ_[p]` is a norm, because the equation `x ^ 2 - w̄ y ^ 2 = ā` is
solvable in the residue field for `ā ≠ 0` and the resulting discrepancy is a unit congruent to
`1` mod `p`, hence a square.

Together these give one inclusion at once — an element of even valuation is a unit times an even
power of the uniformiser, that is, a norm times a square.  The converse is a purely formal
consequence: if some element of odd valuation were a norm, then dividing by an even power of the
uniformiser and by a unit, both norms, would exhibit the uniformiser itself as a norm, which
`InverseGalois.CFT.Local.isSquare_toZMod_of_eq_sub_sq` forbids for a unit `w` with nonsquare
residue.

Since the valuation is additive, the resulting description of the symbol is visibly multiplicative
in its first argument, which is the one instance of bimultiplicativity of the `p`-adic Hilbert
symbol that comes for free.

## Main results

* `InverseGalois.CFT.Local.exists_sub_sq_mul`, `InverseGalois.CFT.Local.exists_sub_sq_inv`,
  `InverseGalois.CFT.Local.exists_sub_sq_sq`: the values of the norm form `u ^ 2 - w * v ^ 2`
  form a subgroup of the units containing the squares.
* `InverseGalois.CFT.Local.exists_sub_sq_of_isUnit`: for `p` odd, every unit of `ℤ_[p]` is a value
  of the norm form attached to a unit `w`.
* `InverseGalois.CFT.Local.even_valuation_of_eq_sub_sq`: a nonzero value of the norm form attached
  to a unit with nonsquare residue has even valuation.
* `InverseGalois.CFT.Local.exists_sub_sq_of_even_valuation`: conversely every nonzero `p`-adic
  number of even valuation is a value of the norm form.
* `InverseGalois.CFT.Local.hilbertSymbol_unramified`,
  `InverseGalois.CFT.Local.hilbertSymbol_unramified_eq_neg_one_iff`: the Hilbert symbol against an
  unramified nonsquare is the parity of the valuation.
* `InverseGalois.CFT.Local.hilbertSymbol_unramified_mul`: consequently the Hilbert symbol is
  multiplicative in its first argument when the second is an unramified nonsquare.
* `InverseGalois.CFT.Local.exists_unramified_nonsquare`: for `p` odd such a `w` exists.
* `InverseGalois.CFT.Local.zpow_two_mul_eq_sq`,
  `InverseGalois.CFT.Local.valuation_eq_of_eq_zpow_mul`: bookkeeping for powers of the
  uniformiser.
-/

namespace InverseGalois.CFT.Local

variable {p : ℕ} [Fact p.Prime]

/-- **The norm form is multiplicative.**  The composition law
`(s ^ 2 - w t ^ 2) (s' ^ 2 - w t' ^ 2) = (s s' + w t t') ^ 2 - w (s t' + t s') ^ 2` is the
multiplicativity of the norm of the quadratic extension generated by a square root of `w`. -/
theorem exists_sub_sq_mul {K : Type*} [CommRing K] {w a a' : K}
    (h : ∃ u v : K, a = u ^ 2 - w * v ^ 2) (h' : ∃ u v : K, a' = u ^ 2 - w * v ^ 2) :
    ∃ u v : K, a * a' = u ^ 2 - w * v ^ 2 := by
  obtain ⟨s, t, rfl⟩ := h
  obtain ⟨s', t', rfl⟩ := h'
  exact ⟨s * s' + w * t * t', s * t' + t * s', by ring⟩

/-- **The nonzero values of the norm form are closed under inverses**: if `a = s ^ 2 - w t ^ 2`
is nonzero then `a⁻¹ = (s / a) ^ 2 - w (t / a) ^ 2`, since the right-hand side is `a / a ^ 2`. -/
theorem exists_sub_sq_inv {K : Type*} [Field K] {w a : K} (ha : a ≠ 0)
    (h : ∃ u v : K, a = u ^ 2 - w * v ^ 2) : ∃ u v : K, a⁻¹ = u ^ 2 - w * v ^ 2 := by
  obtain ⟨s, t, hst⟩ := h
  refine ⟨s / a, t / a, ?_⟩
  have hrw : (s / a) ^ 2 - w * (t / a) ^ 2 = (s ^ 2 - w * t ^ 2) / a ^ 2 := by
    field_simp
  rw [hrw, ← hst, sq, ← div_div, div_self ha, one_div]

/-- Every square is a value of the norm form, with vanishing second coordinate. -/
theorem exists_sub_sq_sq {K : Type*} [CommRing K] (w c : K) :
    ∃ u v : K, c ^ 2 = u ^ 2 - w * v ^ 2 :=
  ⟨c, 0, by ring⟩

/-- **Every `p`-adic unit is a norm from the quadratic extension attached to a unit `w`**, for `p`
odd.  In the residue field the equation `x ^ 2 - w̄ y ^ 2 = ā` is solvable because every binary
quadratic form with nonzero coefficients represents `1`; lifting a solution arbitrarily makes
`(u₀ ^ 2 - w v₀ ^ 2) a⁻¹` a unit with residue `1`, hence a square `t ^ 2` by Hensel's lemma, and
dividing the lifted solution by `t` produces an exact representation of `a`. -/
theorem exists_sub_sq_of_isUnit (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w) {a : ℤ_[p]}
    (ha : IsUnit a) : ∃ u v : ℤ_[p], a = u ^ 2 - w * v ^ 2 := by
  have haz : PadicInt.toZMod a ≠ 0 := toZMod_ne_zero_iff_isUnit.mpr ha
  have hwz : PadicInt.toZMod w ≠ 0 := toZMod_ne_zero_iff_isUnit.mpr hw
  obtain ⟨x, y, hxy⟩ := exists_add_sq_eq_one hp (a := (PadicInt.toZMod a)⁻¹)
    (b := -PadicInt.toZMod w * (PadicInt.toZMod a)⁻¹) (inv_ne_zero haz)
    (mul_ne_zero (neg_ne_zero.mpr hwz) (inv_ne_zero haz))
  have h1 : PadicInt.toZMod a * (PadicInt.toZMod a)⁻¹ = 1 := mul_inv_cancel₀ haz
  have key : x ^ 2 - PadicInt.toZMod w * y ^ 2 = PadicInt.toZMod a := by
    linear_combination PadicInt.toZMod a * hxy - (x ^ 2 - PadicInt.toZMod w * y ^ 2) * h1
  obtain ⟨u₀, rfl⟩ := ZMod.ringHom_surjective (PadicInt.toZMod (p := p)) x
  obtain ⟨v₀, rfl⟩ := ZMod.ringHom_surjective (PadicInt.toZMod (p := p)) y
  obtain ⟨b, hb⟩ := ha.exists_right_inv
  have hab : PadicInt.toZMod a * PadicInt.toZMod b = 1 := by rw [← map_mul, hb, map_one]
  have hsz : PadicInt.toZMod ((u₀ ^ 2 - w * v₀ ^ 2) * b) = 1 := by
    simp only [map_mul, map_sub, map_pow]
    rw [key, hab]
  have hsu : IsUnit ((u₀ ^ 2 - w * v₀ ^ 2) * b) :=
    toZMod_ne_zero_iff_isUnit.mp (by rw [hsz]; exact one_ne_zero)
  obtain ⟨t, ht⟩ :=
    (isSquare_iff_isSquare_toZMod hp hsu).mpr (by rw [hsz]; exact ⟨1, (one_mul 1).symm⟩)
  have htu : IsUnit t := isUnit_of_mul_isUnit_left (ht ▸ hsu)
  obtain ⟨t', ht'⟩ := htu.exists_right_inv
  have key2 : u₀ ^ 2 - w * v₀ ^ 2 = a * (t * t) := by
    linear_combination a * ht - (u₀ ^ 2 - w * v₀ ^ 2) * hb
  refine ⟨u₀ * t', v₀ * t', ?_⟩
  linear_combination (-(t' ^ 2)) * key2 - a * (1 + t * t') * ht'

/-- An even integral power is a square: `x ^ (2 * m) = (x ^ m) ^ 2`. -/
theorem zpow_two_mul_eq_sq {K : Type*} [DivisionRing K] (x : K) (m : ℤ) :
    x ^ (2 * m) = (x ^ m) ^ (2 : ℕ) := by
  rw [mul_comm, zpow_mul, ← zpow_natCast (x ^ m) 2]
  norm_num

/-- The exponent in a factorisation `a = p ^ n * c` with `c` a unit of `ℤ_[p]` is the valuation
of `a`, a unit contributing valuation zero. -/
theorem valuation_eq_of_eq_zpow_mul {a : ℚ_[p]} {n : ℤ} {c : ℤ_[p]} (hc : IsUnit c)
    (hac : a = (p : ℚ_[p]) ^ n * (c : ℚ_[p])) : a.valuation = n := by
  have hp0 : ((p : ℚ_[p])) ≠ 0 := NeZero.ne _
  have hcne : ((c : ℚ_[p])) ≠ 0 := PadicInt.coe_ne_zero.mpr hc.ne_zero
  rw [hac, Padic.valuation_mul (zpow_ne_zero _ hp0) hcne, Padic.valuation_zpow,
    Padic.valuation_p, valuation_coe_eq_zero hc, mul_one, add_zero]

/-- **Every `p`-adic number of even valuation is a norm from the extension attached to a unit
`w`**, for `p` odd: strip off an even power of the uniformiser, which is a square and hence a
norm, and represent the remaining unit. -/
theorem exists_sub_sq_of_even_valuation (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w) {a : ℚ_[p]}
    (ha : a ≠ 0) (hv : Even a.valuation) : ∃ u v : ℚ_[p], a = u ^ 2 - (w : ℚ_[p]) * v ^ 2 := by
  obtain ⟨n, c, hc, hac⟩ := exists_unit_mul_zpow ha
  have hval : a.valuation = n := valuation_eq_of_eq_zpow_mul hc hac
  rw [hval] at hv
  obtain ⟨m, hm⟩ := hv
  have hn : n = 2 * m := by omega
  rw [hac, hn, zpow_two_mul_eq_sq]
  refine exists_sub_sq_mul (exists_sub_sq_sq _ _) ?_
  obtain ⟨x, y, hxy⟩ := exists_sub_sq_of_isUnit hp hw hc
  exact ⟨(x : ℚ_[p]), (y : ℚ_[p]), by rw [hxy]; push_cast; ring⟩

/-- **A norm from the unramified quadratic extension has even valuation.**  Suppose `a ≠ 0` is of
the shape `u ^ 2 - w v ^ 2` for a unit `w` with nonsquare residue, and write `a = p ^ n * c` with
`c` a unit.  If `n` were odd then, the values of the norm form being a group containing all units
and all squares, the uniformiser `p = a * (p ^ m) ^ (-2) * c⁻¹` would itself be a norm, forcing
the residue of `w` to be a square. -/
theorem even_valuation_of_eq_sub_sq (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w)
    (hws : ¬ IsSquare (PadicInt.toZMod w)) {a u v : ℚ_[p]} (ha : a ≠ 0)
    (h : a = u ^ 2 - (w : ℚ_[p]) * v ^ 2) : Even a.valuation := by
  by_contra hodd
  obtain ⟨n, c, hc, hac⟩ := exists_unit_mul_zpow ha
  have hval : a.valuation = n := valuation_eq_of_eq_zpow_mul hc hac
  rw [hval] at hodd
  obtain ⟨m, hm⟩ := Int.not_even_iff_odd.mp hodd
  have hp0 : ((p : ℚ_[p])) ≠ 0 := NeZero.ne _
  have hcne : ((c : ℚ_[p])) ≠ 0 := PadicInt.coe_ne_zero.mpr hc.ne_zero
  have hq : ((p : ℚ_[p]) ^ m) ≠ 0 := zpow_ne_zero _ hp0
  have hNc : ∃ s t : ℚ_[p], ((c : ℚ_[p])) = s ^ 2 - (w : ℚ_[p]) * t ^ 2 := by
    obtain ⟨x, y, hxy⟩ := exists_sub_sq_of_isUnit hp hw hc
    exact ⟨(x : ℚ_[p]), (y : ℚ_[p]), by rw [hxy]; push_cast; ring⟩
  have hpe : ((p : ℚ_[p])) = a * ((((p : ℚ_[p]) ^ m) ^ (2 : ℕ))⁻¹ * ((c : ℚ_[p]))⁻¹) := by
    rw [hac, hm, zpow_add₀ hp0, zpow_one, zpow_two_mul_eq_sq]
    field_simp
  have hNp : ∃ s t : ℚ_[p], ((p : ℚ_[p])) = s ^ 2 - (w : ℚ_[p]) * t ^ 2 := by
    rw [hpe]
    refine exists_sub_sq_mul ⟨u, v, h⟩ (exists_sub_sq_mul ?_ (exists_sub_sq_inv hcne hNc))
    exact exists_sub_sq_inv (pow_ne_zero 2 hq) (exists_sub_sq_sq _ _)
  obtain ⟨s, t, hst⟩ := hNp
  exact hws (isSquare_toZMod_of_eq_sub_sq hw hst)

/-- **The Hilbert symbol against an unramified nonsquare is the parity of the valuation.**  For
`p` odd and `w` a unit of `ℤ_[p]` whose residue is not a square, a nonzero `a : ℚ_[p]` has
`⟨a, w⟩ = 1` exactly when the valuation of `a` is even. -/
theorem hilbertSymbol_unramified (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w)
    (hws : ¬ IsSquare (PadicInt.toZMod w)) {a : ℚ_[p]} (ha : a ≠ 0) :
    hilbertSymbol a ((w : ℚ_[p])) = 1 ↔ Even a.valuation := by
  have hnsq : ¬ IsSquare ((w : ℚ_[p])) := fun hs =>
    hws (((isSquare_coe_iff hw).mp hs).map PadicInt.toZMod)
  rw [hilbertSymbol_eq_one_iff_exists_sub_sq hnsq]
  exact ⟨fun ⟨_, _, huv⟩ => even_valuation_of_eq_sub_sq hp hw hws ha huv,
    fun hv => exists_sub_sq_of_even_valuation hp hw ha hv⟩

/-- The complementary value: the Hilbert symbol against an unramified nonsquare is `-1` exactly
for an argument of odd valuation. -/
theorem hilbertSymbol_unramified_eq_neg_one_iff (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w)
    (hws : ¬ IsSquare (PadicInt.toZMod w)) {a : ℚ_[p]} (ha : a ≠ 0) :
    hilbertSymbol a ((w : ℚ_[p])) = -1 ↔ ¬ Even a.valuation := by
  constructor
  · intro h hev
    rw [(hilbertSymbol_unramified hp hw hws ha).mpr hev] at h
    norm_num at h
  · intro h
    rcases hilbertSymbol_eq_one_or a ((w : ℚ_[p])) with h1 | h1
    · exact absurd ((hilbertSymbol_unramified hp hw hws ha).mp h1) h
    · exact h1

/-- **The Hilbert symbol against an unramified nonsquare is multiplicative in its first
argument.**  Both sides are signs, and by the previous computation each is determined by the
parity of a valuation; the valuation of a product being the sum of the valuations, the four cases
match up. -/
theorem hilbertSymbol_unramified_mul (hp : p ≠ 2) {w : ℤ_[p]} (hw : IsUnit w)
    (hws : ¬ IsSquare (PadicInt.toZMod w)) {a a' : ℚ_[p]} (ha : a ≠ 0) (ha' : a' ≠ 0) :
    hilbertSymbol (a * a') ((w : ℚ_[p]))
      = hilbertSymbol a ((w : ℚ_[p])) * hilbertSymbol a' ((w : ℚ_[p])) := by
  have hval : (a * a').valuation = a.valuation + a'.valuation := Padic.valuation_mul ha ha'
  have e1 := hilbertSymbol_unramified hp hw hws ha
  have e2 := hilbertSymbol_unramified hp hw hws ha'
  have n1 := hilbertSymbol_unramified_eq_neg_one_iff hp hw hws ha
  have n2 := hilbertSymbol_unramified_eq_neg_one_iff hp hw hws ha'
  have e3 := hilbertSymbol_unramified hp hw hws (mul_ne_zero ha ha')
  have n3 := hilbertSymbol_unramified_eq_neg_one_iff hp hw hws (mul_ne_zero ha ha')
  rcases Int.even_or_odd a.valuation with hA | hA <;>
    rcases Int.even_or_odd a'.valuation with hB | hB
  · rw [e1.mpr hA, e2.mpr hB, e3.mpr (by rw [hval]; exact hA.add hB)]
    norm_num
  · rw [e1.mpr hA, n2.mpr (Int.not_even_iff_odd.mpr hB),
      n3.mpr (Int.not_even_iff_odd.mpr (by rw [hval]; exact hA.add_odd hB))]
    norm_num
  · rw [n1.mpr (Int.not_even_iff_odd.mpr hA), e2.mpr hB,
      n3.mpr (Int.not_even_iff_odd.mpr (by rw [hval]; exact hA.add_even hB))]
    norm_num
  · rw [n1.mpr (Int.not_even_iff_odd.mpr hA), n2.mpr (Int.not_even_iff_odd.mpr hB),
      e3.mpr (by rw [hval]; exact hA.add_odd hB)]
    norm_num

/-- **The unramified quadratic extension exists**: for `p` odd there is a unit of `ℤ_[p]` whose
residue mod `p` is not a square, namely any lift of a nonsquare of the residue field. -/
theorem exists_unramified_nonsquare (hp : p ≠ 2) :
    ∃ w : ℤ_[p], IsUnit w ∧ ¬ IsSquare (PadicInt.toZMod w) := by
  have hchar : ringChar (ZMod p) ≠ 2 := by rw [ZMod.ringChar_zmod_n]; exact hp
  obtain ⟨z, hz⟩ := FiniteField.exists_nonsquare hchar
  obtain ⟨w, hw⟩ := ZMod.ringHom_surjective (PadicInt.toZMod (p := p)) z
  refine ⟨w, toZMod_ne_zero_iff_isUnit.mp ?_, by rw [hw]; exact hz⟩
  rw [hw]
  rintro rfl
  exact hz (⟨0, (mul_zero 0).symm⟩ : IsSquare (0 : ZMod p))

end InverseGalois.CFT.Local
