/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Profinite.QuotientAction
import InverseGalois.CFT.Profinite.TwistTensor

/-!
# The tensor product of two modules over a group is a module over that group

The twisting map goes out of the tensor product of the group the base group provides with the
homomorphisms of the coefficients, and it carries the action of the ambient group factor by factor
to conjugation.  To say that in the language of modules the tensor product itself has to be one,
which it is: **an element of the group acts on a tensor product by acting on each factor**, the
diagonal action.  A tensor product is generated by its pure tensors, so the axioms reduce to the
axioms on each factor.

With the action in place the equivariance of the twisting map becomes an equation between an action
and conjugation rather than an equation between two tensor maps, which is what the descent to the
quotient consumes: an element of the normal subgroup which moves both factors trivially moves the
whole tensor product trivially, and conjugation by it is trivial on the first cohomology, so the two
sides descend together.

## Main definitions

* `InverseGalois.CFT.tensorSMulMap`: the diagonal action of a single element, as a linear map.
* `InverseGalois.CFT.tensorDistribMulAction`: **the diagonal action on the tensor product.**
* `InverseGalois.CFT.actsTrivially_tensor`: a subgroup acting trivially on both factors acts
  trivially on the tensor product, so the quotient by it acts there.

## Main results

* `InverseGalois.CFT.tensorSMul_eq_self_of_forall`: an element moving both factors trivially moves
  the tensor product trivially.
* `InverseGalois.CFT.conjH1_twistMap_smul`: **the twisting map out of the tensor product carries
  the diagonal action to conjugation.**

## Tags

tensor product, diagonal action, twist, Galois cohomology, equivariance
-/

namespace InverseGalois.CFT

open groupCohomology TensorProduct

/-! ### The diagonal action on a tensor product -/

section Action

variable {G : Type*} [Group G] {A B : Type*} [CommGroup A] [CommGroup B]
variable [MulDistribMulAction G A] [MulDistribMulAction G B]

variable (A B) in
/-- The action of a single element of the group on the tensor product of two of its modules,
acting on each factor. -/
def tensorSMulMap (σ : G) :
    Additive A ⊗[ℤ] Additive B →ₗ[ℤ] Additive A ⊗[ℤ] Additive B :=
  TensorProduct.map (MonoidHom.toAdditive (MulDistribMulAction.toMonoidHom A σ)).toIntLinearMap
    (MonoidHom.toAdditive (MulDistribMulAction.toMonoidHom B σ)).toIntLinearMap

@[simp]
theorem tensorSMulMap_tmul (σ : G) (a : A) (b : B) :
    tensorSMulMap A B σ (Additive.ofMul a ⊗ₜ[ℤ] Additive.ofMul b)
      = Additive.ofMul (σ • a) ⊗ₜ[ℤ] Additive.ofMul (σ • b) := rfl

variable (A B) in
theorem tensorSMulMap_one : tensorSMulMap A B (1 : G) = LinearMap.id := by
  refine TensorProduct.ext' fun x y => ?_
  show Additive.ofMul ((1 : G) • x.toMul) ⊗ₜ[ℤ] Additive.ofMul ((1 : G) • y.toMul) = x ⊗ₜ[ℤ] y
  rw [one_smul, one_smul]
  rfl

variable (A B) in
theorem tensorSMulMap_comp (σ τ : G) :
    tensorSMulMap A B σ ∘ₗ tensorSMulMap A B τ = tensorSMulMap A B (σ * τ) := by
  refine TensorProduct.ext' fun x y => ?_
  show Additive.ofMul (σ • τ • x.toMul) ⊗ₜ[ℤ] Additive.ofMul (σ • τ • y.toMul)
    = Additive.ofMul ((σ * τ) • x.toMul) ⊗ₜ[ℤ] Additive.ofMul ((σ * τ) • y.toMul)
  rw [mul_smul, mul_smul]

variable (G A B) in
/-- **The tensor product of two modules over a group is a module over that group**, acted on
factor by factor. -/
instance tensorDistribMulAction : DistribMulAction G (Additive A ⊗[ℤ] Additive B) where
  smul σ := tensorSMulMap A B σ
  one_smul z := LinearMap.congr_fun (tensorSMulMap_one A B) z
  mul_smul σ τ z := (LinearMap.congr_fun (tensorSMulMap_comp A B σ τ) z).symm
  smul_zero σ := map_zero (tensorSMulMap A B σ)
  smul_add σ z z' := map_add (tensorSMulMap A B σ) z z'

@[simp]
theorem tensorSMul_tmul (σ : G) (a : A) (b : B) :
    (σ • (Additive.ofMul a ⊗ₜ[ℤ] Additive.ofMul b) : Additive A ⊗[ℤ] Additive B)
      = Additive.ofMul (σ • a) ⊗ₜ[ℤ] Additive.ofMul (σ • b) := rfl

/-- **An element of the group moving both factors trivially moves the tensor product trivially.**
This is what makes the diagonal action an action of a quotient. -/
theorem tensorSMul_eq_self_of_forall {σ : G} (ha : ∀ a : A, σ • a = a) (hb : ∀ b : B, σ • b = b)
    (z : Additive A ⊗[ℤ] Additive B) : σ • z = z := by
  induction z using TensorProduct.induction_on with
  | zero => exact smul_zero σ
  | add z z' hz hz' => rw [smul_add, hz, hz']
  | tmul x y =>
    show Additive.ofMul (σ • x.toMul) ⊗ₜ[ℤ] Additive.ofMul (σ • y.toMul) = x ⊗ₜ[ℤ] y
    rw [ha, hb]
    rfl

variable (N : Subgroup G) (A B) in
/-- **A subgroup acting trivially on both factors acts trivially on the tensor product**, so the
quotient by it acts there. -/
instance actsTrivially_tensor [ActsTrivially N A] [ActsTrivially N B] :
    AddActsTrivially N (Additive A ⊗[ℤ] Additive B) :=
  ⟨fun n hn => tensorSMul_eq_self_of_forall (ActsTrivially.smul_eq_self n hn)
    (ActsTrivially.smul_eq_self n hn)⟩

end Action

/-! ### The equivariance of the twisting map, as an action -/

section Twist

variable {G : Type*} [Group G] [TopologicalSpace G] [ContinuousMul G] {N : Subgroup G}
variable {M E A : Type*} [CommGroup M] [CommGroup E] [CommGroup A]
variable [MulDistribMulAction G M] [MulDistribMulAction G E] [MulDistribMulAction G A]
variable (hN : N.Normal)
variable (htrivM : ∀ (x : ↥N) (m : M), x • m = m) (htrivE : ∀ (x : ↥N) (e : E), x • e = e)
variable (κ : A →* SmoothH1 ↥N M)

/-- **The twisting map out of the tensor product carries the diagonal action of the ambient group
to conjugation** on the first cohomology of the normal subgroup. -/
theorem conjH1_twistMap_smul (hκ : ∀ (σ : G) (a : A), conjH1 hN σ (κ a) = κ (σ • a)) (σ : G)
    (z : Additive A ⊗[ℤ] Additive (M →* E)) :
    MonoidHom.toAdditive (conjH1 hN σ) (twistMap htrivM htrivE κ z)
      = twistMap htrivM htrivE κ (σ • z) :=
  conjH1_twistMap hN htrivM htrivE κ (fun σ => MulDistribMulAction.toMonoidHom A σ) hκ σ z

omit [TopologicalSpace G] [ContinuousMul G] in
include htrivM htrivE in
/-- **The normal subgroup moves the tensor product trivially**, its elements acting trivially on
the coefficients, provided they act trivially on the group the base group provides. -/
theorem tensorSMul_eq_self_of_mem (hA : ∀ (x : ↥N) (a : A), x • a = a) {g : G} (hg : g ∈ N)
    (z : Additive A ⊗[ℤ] Additive (M →* E)) : g • z = z :=
  tensorSMul_eq_self_of_forall (fun a => hA ⟨g, hg⟩ a)
    (fun w => homSMul_eq_self_of_mem htrivM htrivE hg w) z

end Twist

end InverseGalois.CFT
