/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Hilbert.AlternatingFamilyDisc
import InverseGalois.Hilbert.AlternatingFamilyDescent
import InverseGalois.Hilbert.AlternatingFamilyMonodromy
import InverseGalois.Resolvent.AlternatingResolvent
import InverseGalois.Resolvent.AlternatingResolventDescent

/-!
# The explicit `Aₙ`-family (Serre §4.5) — analytic (monodromy) half

Companion to `Hilbert/AlternatingFamily.lean` / `Hilbert/AlternatingFamilyDisc.lean`.  Where
those files supply the *algebraic* inputs of `exists_alternating_resolvent_family` around the
**concrete** substituted family `serreAnFamily` (degree/monic/separability and the
square-discriminant certificate), this file supplies the *monodromy* inputs: the descended
`Aₙ`-orbit resolvent `G` of `serreAnFamily n`, and its irreducibility and **absolute**
irreducibility.

## The coupling (why this is *not* a decoupled existential)

Following the `Sₙ` blueprint (`ResolventFamily.IsFullResolvent` / `fullResolvent_irreducible`),
the resolvent `G` is tied to the concrete family `F = serreAnFamily n` by the predicate
`IsAltResolvent n F G`: at every specialisation in which `F` splits with roots `x`, the
specialised `G` equals `AlternatingResolvent.altResolventProduct n x`.  The irreducibility
lemmas take that coupling as a hypothesis, so — unlike a bare `∃ F G, … ∧ Irreducible G` — they
cannot be satisfied by an unrelated `G`, and they compose with the algebraic side into the single
bundled `exists_alternating_resolvent_family`.

## Why `Aₙ` (the monodromy argument)

For the base family `f = Xⁿ − X^{n-1} − T` the finite inertia at the single ramified value is a
**transposition** and the whole group is `Sₙ` (Serre §4.4).  After the square-discriminant
substitution the group descends to `Aₙ` by the double-group trick (Lemma 4.5.1); equivalently,
in the substituted family the finite inertia becomes a **3-cycle**, and a transitive subgroup of
`Sₙ` generated by 3-cycles is all of `Aₙ`.  The group-theoretic half is Mathlib's
`Equiv.Perm.closure_three_cycles_eq_alternating` (`alternating_eq_closure_three_cycles` below);
the *analytic* half — that the inertia generators are in fact 3-cycles — is the genuine remaining
content and parallels the `Sₙ` analytic stack (`MorseSwap` / `NewtonPuiseux` / `SelmerMorse`).
-/

open Polynomial

noncomputable section

namespace AlternatingFamily

open AlternatingResolvent ResolventFamily

/-- **[monodromy leaf — group theory, closed]** The alternating group on `Fin n` is generated by
its 3-cycles — the group-theoretic core of "transitive + 3-cycle-inertia ⟹ geometric monodromy
`= Aₙ`", a direct specialisation of Mathlib's `Equiv.Perm.closure_three_cycles_eq_alternating`. -/
theorem alternating_eq_closure_three_cycles (n : ℕ) :
    Subgroup.closure {σ : Equiv.Perm (Fin n) | σ.IsThreeCycle} = alternatingGroup (Fin n) :=
  Equiv.Perm.closure_three_cycles_eq_alternating

/-- **[resolvent core — descent]** For the concrete square-discriminant family
`serreAnFamily n` there is a descended orbit-resolvent `G ∈ ℚ[T][Y]`, monic of `Y`-degree `n!/2`,
coupled to `F` via `IsAltResolvent`, with a root of `G(t)` inside the splitting field of
`F(t)` for every `t`.

This is the `Aₙ`-analogue of `ResolventFamily.exists_fullResolvent`.  The descent of the
`Aₙ`-invariant coefficients to `ℚ(T)` uses that they live in `ℚ[e₁,…,eₙ][δ]` with `δ = √disc F`,
which is *rational* precisely because `disc F` is a square (the certificate
`serreAnFamily_disc_isSquare_of_separable`, valid for `Even n`); the machinery is in
`Resolvent/AlternatingResolventDescent.lean`, and root-containment follows from
`altResolventProduct_isRoot_genForm_one` exactly as in the `Sₙ` `resolvent_root_property`.

`Even n` because `serreAnFamily` is Serre's even-`n` family (odd `n` uses `serreAnFamilyOdd`). -/
theorem exists_altResolvent (n : ℕ) (hn : 2 ≤ n) (heven : Even n) :
    ∃ G : Polynomial (Polynomial ℚ), G.Monic ∧ G.natDegree = n.factorial / 2 ∧
      IsAltResolvent n (serreAnFamily n) G ∧
      (∀ t : ℤ, ∃ α : (specialize (serreAnFamily n) t).SplittingField,
        (aeval α) (specialize G t) = 0) := by
  obtain ⟨G, hm, hd, hres⟩ := exists_descended_altResolvent n hn heven
  exact ⟨G, hm, hd, hres, altResolvent_root_property n hn G hres⟩

/-- **[monodromy core — geometric]** The descended resolvent `G` of `serreAnFamily n` is
**absolutely irreducible**: it stays irreducible after base change to `AlgebraicClosure ℚ`, i.e.
the *geometric* monodromy group over `ℚ̄(T)` is exactly `Aₙ`.

This is the deepest input.  It is now *decomposed* (in `Hilbert/AlternatingFamilyMonodromy.lean`,
mirroring the `Sₙ` chain `ResolventFamily.fullResolvent_abs_irreducible`) into the Gauss reduction
`abs_irreducible_of_geometric_galois_alternating` and the geometric-monodromy input
`an_geometric_galois_alternating` (the image of the geometric Galois action is exactly the
alternating group on the roots).  This theorem is discharged by the `anResolvent_abs_irreducible'`
assembly there; the remaining `sorry`s are the three tractable leaves of that file
(`serreAnOverFrac_separable`, `anResolventFrac_irreducible`, `an_geometric_galois_alternating` — the
last being the genuine 3-cycle-inertia content, the `Aₙ`-analogue of the transposition-inertia
computation in the `Sₙ` `MorseSwap`/`NewtonPuiseux` stack). -/
theorem anResolvent_abs_irreducible (n : ℕ) (hn : 3 ≤ n) (heven : Even n)
    (G : Polynomial (Polynomial ℚ))
    (hGmonic : G.Monic) (hG : IsAltResolvent n (serreAnFamily n) G) :
    Irreducible (G.map (mapRingHom (algebraMap ℚ (AlgebraicClosure ℚ)))) :=
  anResolvent_abs_irreducible' n hn heven G hGmonic hG

/-- **[monodromy core — arithmetic, `sorry`]** The descended resolvent `G` of `serreAnFamily n` is
**irreducible** over `ℚ(T)` — equivalently, the arithmetic monodromy group over `ℚ(T)` is exactly
`Aₙ`.  As in `ResolventFamily.fullResolvent_irreducible`, this descends from the absolute
irreducibility along the base change `ℚ[T] → ℚ̄[T]` (`Monic.irreducible_of_irreducible_map`). -/
theorem anResolvent_irreducible (n : ℕ) (hn : 3 ≤ n) (heven : Even n)
    (G : Polynomial (Polynomial ℚ))
    (hGmonic : G.Monic) (hG : IsAltResolvent n (serreAnFamily n) G) :
    Irreducible G :=
  hGmonic.irreducible_of_irreducible_map (mapRingHom (algebraMap ℚ (AlgebraicClosure ℚ))) G
    (anResolvent_abs_irreducible n hn heven G hGmonic hG)

end AlternatingFamily

end
