/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.BaseChangeCocycle
import InverseGalois.CFT.Units.LocalCoboundaryTwist
import InverseGalois.CFT.Units.LocalSqrtNegOne
import InverseGalois.CFT.Units.RatSumSquares

/-!
# The Albert-Brauer-Hasse-Noether theorem at the prime two

Over the rational numbers the archimedean hypothesis of the Albert-Brauer-Hasse-Noether theorem for
torsion cocycles cannot be met at the prime two, because the real place ramifies in every totally
complex extension.  When the extension contains a square root of minus one the hypothesis can be
dispensed with altogether.

The subgroup fixing the square root of minus one has two cosets and a totally complex fixed field,
so over that fixed field the theorem applies with nothing to check at infinity and trivialises the
restriction of the cocycle.  The inflation-restriction sequence in degree two then reduces the
cocycle, up to a coboundary, to the inflation of a single rational invariant, and the local
conditions say exactly that this invariant is a sum of two squares in every completion.  A rational
number which is everywhere locally a sum of two squares is a sum of two squares, and a sum of two
squares is the norm of an element of the quadratic subextension generated by the square root of
minus one, which is precisely the condition for the inflated cocycle to be a coboundary.

## Main results

* `InverseGalois.CFT.exists_isMulCoboundary_of_sq_eq_neg_one`: **a two-cocycle with values in the
  units of the rational numbers, killed by a nonzero integer and a coboundary at every ramified
  finite place, is a coboundary as soon as the extension contains a square root of minus one.**

## Tags

number field, Albert-Brauer-Hasse-Noether, two-cocycle, coboundary, square root of minus one,
index two, sum of two squares
-/

open IsDedekindDomain MulAction NumberField groupCohomology

namespace InverseGalois.CFT

variable {K : Type} [Field K] [NumberField K] [IsGalois ℚ K]

/-- **A two-cocycle with values in the units of the rational numbers, killed by a nonzero integer
and a coboundary at every ramified finite place, is a coboundary as soon as the extension contains
a square root of minus one.**  The real place is the only obstruction to the
Albert-Brauer-Hasse-Noether theorem for such a cocycle, and the square root of minus one removes it:
the subgroup fixing it has a totally complex fixed field, over which the theorem applies verbatim,
and the resulting inflated invariant is a rational number which is everywhere locally, hence
globally, a sum of two squares. -/
theorem exists_isMulCoboundary_of_sq_eq_neg_one {ι : K} (hι : ι ^ 2 = -1) {n : ℕ} (hn : n ≠ 0)
    {a : Gal(K/ℚ) → Gal(K/ℚ) → ℚˣ} (hpow : ∀ x y, a x y ^ n = 1)
    (ha : ∀ x y z : Gal(K/ℚ), a y z * a x (y * z) = a (x * y) z * a x y)
    (hram : ∀ v : HeightOneSpectrum (𝓞 K), ¬ Algebra.IsUnramifiedAt (𝓞 ℚ) v.asIdeal →
      ∃ c : ↥(stabilizer Gal(K/ℚ) v) → Additive (v.adicCompletion K)ˣ,
      ∀ s t : ↥(stabilizer Gal(K/ℚ) v),
        Additive.ofMul (adicUnitHom v (Units.map (algebraMap ℚ K : ℚ →* K) (a s.1 t.1)))
          = smulUnitsAut s (c t) - c (s * t) + c s) :
    ∃ b : Gal(K/ℚ) → Kˣ, ∀ g h : Gal(K/ℚ),
      g • b h / b (g * h) * b g = Units.map (algebraMap ℚ K : ℚ →* K) (a g h) := by
  classical
  haveI : (stabilizer Gal(K/ℚ) ι).Normal := stabilizer_normal_of_sq_eq_neg_one hι
  set A : Gal(K/ℚ) × Gal(K/ℚ) → Kˣ :=
    fun p => Units.map (algebraMap ℚ K : ℚ →* K) (a p.1 p.2) with hAdef
  set Aadd : Gal(K/ℚ) → Gal(K/ℚ) → Additive Kˣ := fun x y => Additive.ofMul (A (x, y)) with hAadd
  have hAsmul : ∀ (g : Gal(K/ℚ)) (p : Gal(K/ℚ) × Gal(K/ℚ)), g • A p = A p :=
    fun g p => smul_algebraMap_units g (a p.1 p.2)
  have hAcoc : IsMulCocycle₂ A := by
    intro g h j
    rw [hAsmul g (h, j)]
    show Units.map (algebraMap ℚ K : ℚ →* K) (a (g * h) j)
        * Units.map (algebraMap ℚ K : ℚ →* K) (a g h)
      = Units.map (algebraMap ℚ K : ℚ →* K) (a h j)
        * Units.map (algebraMap ℚ K : ℚ →* K) (a g (h * j))
    rw [← map_mul, ← map_mul, ha]
  /- The local conditions, at every finite place: unramified places are free, ramified ones are
  the hypothesis. -/
  have hApow : ∀ x y : Gal(K/ℚ), n • Aadd x y = 0 := by
    intro x y
    show n • Additive.ofMul (Units.map (algebraMap ℚ K : ℚ →* K) (a x y)) = 0
    rw [← ofMul_pow, ← map_pow, hpow, map_one]
    rfl
  have hAcocadd : ∀ x y z : Gal(K/ℚ),
      globalUnitsAut x (Aadd y z) + Aadd x (y * z) = Aadd (x * y) z + Aadd x y := by
    intro x y z
    have hfx : globalUnitsAut x (Aadd y z) = Aadd y z := by
      refine Additive.toMul.injective ?_
      rw [toMul_globalUnitsAut]
      exact hAsmul x (y, z)
    have h := hAcoc x y z
    rw [hAsmul x (y, z)] at h
    rw [hfx]
    show Additive.ofMul (A (y, z)) + Additive.ofMul (A (x, y * z))
      = Additive.ofMul (A (x * y, z)) + Additive.ofMul (A (x, y))
    rw [← ofMul_mul, ← ofMul_mul, h]
  have hfin : ∀ w : HeightOneSpectrum (𝓞 K),
      ∃ b : ↥(stabilizer Gal(K/ℚ) w) → Additive (w.adicCompletion K)ˣ,
        ∀ s t : ↥(stabilizer Gal(K/ℚ) w),
          Additive.ofMul (adicUnitHom w (A (s.1, t.1)))
            = smulUnitsAut s (b t) - b (s * t) + b s := by
    intro w
    by_cases hunr : Algebra.IsUnramifiedAt (𝓞 ℚ) w.asIdeal
    · exact exists_sub_add_eq_adicUnits_of_nsmul_eq_zero w hunr hn hApow hAcocadd
    · exact hram w hunr
  /- The inflation-restriction sequence in degree two. -/
  obtain ⟨σ, hσ⟩ :=
    exists_not_mem_stabilizer_of_sq_eq_neg_one (F := ℚ) hι rat_sq_ne_neg_one
  have hcov := mem_stabilizer_or_mul_inv_mem hι hσ
  have hH1 : ∀ f : Gal(K/ℚ) → Kˣ, (∀ x ∈ stabilizer Gal(K/ℚ) ι, ∀ y ∈ stabilizer Gal(K/ℚ) ι,
      f (x * y) = x • f y * f x) → ∃ t : Kˣ, ∀ x ∈ stabilizer Gal(K/ℚ) ι, x • t / t = f x :=
    fun f hf => exists_smul_div_eq_of_mem_subgroup _ hf
  have hres := exists_isMulCoboundary_on_subgroup (stabilizer Gal(K/ℚ) ι)
    (isTotallyComplex_fixedField_stabilizer hι) hn hpow ha hram
  obtain ⟨cval, u, hfix, heq⟩ :=
    exists_twist_eq_indexTwoInflation hσ hcov hH1 hAcoc hres
  /- The inflated invariant is locally a sum of two squares. -/
  have hcob : ∀ w : HeightOneSpectrum (𝓞 K),
      ∃ b : ↥(stabilizer Gal(K/ℚ) w) → Additive (w.adicCompletion K)ˣ,
        ∀ s t : ↥(stabilizer Gal(K/ℚ) w),
          Additive.ofMul
              (adicUnitHom w (indexTwoInflation (stabilizer Gal(K/ℚ) ι) cval (s.1, t.1)))
            = smulUnitsAut s (b t) - b (s * t) + b s := by
    intro w
    have h := exists_sub_add_eq_adicUnits_twist (k := ℚ) w (a := A) u (hfin w)
    rwa [heq] at h
  have hcvalfix : ∀ g : Gal(K/ℚ), g • (cval : K) = (cval : K) :=
    fun g => congrArg Units.val (hfix g)
  have hsq : ∀ w : HeightOneSpectrum (𝓞 K),
      ∃ x y : (primeUnder (𝓞 ℚ) w).adicCompletion ℚ,
        algebraMap ((primeUnder (𝓞 ℚ) w).adicCompletion ℚ) (w.adicCompletion K) (x ^ 2 + y ^ 2)
          = toAdicCompletion w (cval : K) :=
    fun w => exists_sq_add_sq_adicCompletion ℚ w hι hcvalfix (hcob w)
  /- Hence globally a sum of two squares, hence a norm. -/
  obtain ⟨c₀, hc₀⟩ := (IsGalois.mem_range_algebraMap_iff_fixed (F := ℚ) (cval : K)).mpr hcvalfix
  have hc₀ne : c₀ ≠ 0 := by
    intro h
    rw [h, map_zero] at hc₀
    exact cval.ne_zero hc₀.symm
  obtain ⟨x, y, hxy⟩ := exists_sq_add_sq_of_forall_adicCompletion (K := K) hc₀ne
    fun w => by rw [hc₀]; exact hsq w
  have hrat : ∀ (g : Gal(K/ℚ)) (q : ℚ), g • algebraMap ℚ K q = algebraMap ℚ K q :=
    fun g q => g.commutes q
  have hσι : σ • ι = -ι := smul_eq_neg_of_not_mem_stabilizer hι hσ
  have hc₀K : algebraMap ℚ K c₀ = algebraMap ℚ K x ^ 2 + algebraMap ℚ K y ^ 2 := by
    rw [hxy, map_add, map_pow, map_pow]
  have hnorm : σ • (algebraMap ℚ K x + algebraMap ℚ K y * ι)
      * (algebraMap ℚ K x + algebraMap ℚ K y * ι) = algebraMap ℚ K c₀ := by
    rw [smul_add, smul_mul', hrat σ x, hrat σ y, hσι, hc₀K]
    linear_combination (-(algebraMap ℚ K y ^ 2)) * hι
  have hfne : algebraMap ℚ K x + algebraMap ℚ K y * ι ≠ 0 := by
    intro h
    rw [h, mul_zero] at hnorm
    exact hc₀ne ((algebraMap ℚ K).injective (by rw [map_zero, ← hnorm]))
  have hfN : ∀ m ∈ stabilizer Gal(K/ℚ) ι,
      m • (algebraMap ℚ K x + algebraMap ℚ K y * ι)
        = algebraMap ℚ K x + algebraMap ℚ K y * ι := by
    intro m hm
    rw [smul_add, smul_mul', hrat m x, hrat m y, mem_stabilizer_iff.mp hm]
  have hFN : ∀ m ∈ stabilizer Gal(K/ℚ) ι,
      m • Units.mk0 _ hfne = Units.mk0 (algebraMap ℚ K x + algebraMap ℚ K y * ι) hfne :=
    fun m hm => Units.ext (hfN m hm)
  have hFF : σ • Units.mk0 _ hfne * Units.mk0 (algebraMap ℚ K x + algebraMap ℚ K y * ι) hfne
      = cval := Units.ext (by rw [hc₀] at hnorm; exact hnorm)
  have hcob2 : IsMulCoboundary₂ (indexTwoInflation (stabilizer Gal(K/ℚ) ι) cval) := by
    have h := isMulCoboundary₂_indexTwoInflation hσ hcov hFN
    rwa [hFF] at h
  /- Assembling the two coboundaries. -/
  rw [isMulCoboundary₂_iff] at hcob2
  obtain ⟨vv, hvv⟩ := hcob2
  have hAcobeq : coboundary₂ (vv * u) = A := by
    rw [coboundary₂_mul, hvv, ← heq]
    funext p
    show twist A u p * coboundary₂ u p = A p
    exact (eq_twist_mul_coboundary₂ A u p).symm
  exact ⟨vv * u, fun g h => congrFun hAcobeq (g, h)⟩

end InverseGalois.CFT
