/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.ClassSet

/-!
# How few primes it takes to carry the ideal classes

A finite set of primes of a number field supports the ideal classes when every finitely supported
system of orders is realised, away from that set, by an element of the field.  The sets produced by
choosing one fractional ideal in each class are finite but of no controlled size: they collect every
prime occurring in every chosen representative, and a different choice of representatives gives a
different and possibly much larger set.

The size can be controlled, and by the class number alone.  A prime has an ideal class, and a
fractional ideal supported on a set of primes is the product of those primes raised to their
exponents, so its class is the corresponding product of the classes of the primes.  Replacing each
prime by another of the same class therefore leaves the class of the product alone while moving its
support.  Keeping one prime for each class that actually occurs leaves a set of at most as many
primes as there are classes, and it still carries them all.

This is what makes the size of such a set available before the set is: it is bounded by an invariant
of the field, so a construction that must fix a number of generators in advance can do so without
knowing which primes it will eventually use.

## Main definitions

* `InverseGalois.CFT.placeUnit` — a prime read as an invertible fractional ideal.
* `InverseGalois.CFT.clsPlace` — the ideal class of a prime.
* `InverseGalois.CFT.HasClassReps` — every ideal class is carried by a fractional ideal supported on
  the given set of primes.

## Main results

* `InverseGalois.CFT.hasClassReps_of_ord_repr` and
  `InverseGalois.CFT.exists_ord_repr_of_hasClassReps`: carrying the ideal classes is the same thing
  as realising every finitely supported system of orders away from the set.
* `InverseGalois.CFT.hasClassReps_of_forall_exists_clsPlace`: **a set carrying the ideal classes may
  be replaced by any set meeting the same classes.**
* `InverseGalois.CFT.exists_card_le_ord_repr_of_ord_repr`: **a set away from which every finitely
  supported system of orders is realised contains one of at most the class number many primes with
  the same property.**

## Tags

number field, class group, fractional ideal, order, place, class number
-/

namespace InverseGalois.CFT

open FractionalIdeal IsDedekindDomain NumberField Rigidity.RET

open scoped nonZeroDivisors

/-! ### The ideal class of a prime -/

section Places

variable (K : Type*) [Field K] [NumberField K]

/-- **A prime of the ring of integers, read as an invertible fractional ideal.** -/
noncomputable def placeUnit (v : HeightOneSpectrum (𝓞 K)) : (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  Units.mk0 (v.asIdeal : FractionalIdeal (𝓞 K)⁰ K) (coeIdeal_ne_zero.mpr v.ne_bot)

@[simp]
theorem coe_placeUnit (v : HeightOneSpectrum (𝓞 K)) :
    (placeUnit K v : FractionalIdeal (𝓞 K)⁰ K) = (v.asIdeal : FractionalIdeal (𝓞 K)⁰ K) := rfl

/-- **The ideal class of a prime.** -/
noncomputable def clsPlace (v : HeightOneSpectrum (𝓞 K)) :
    (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range :=
  QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range (placeUnit K v)

theorem clsPlace_def (v : HeightOneSpectrum (𝓞 K)) :
    clsPlace K v = QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range (placeUnit K v) := rfl

/-- **Every ideal class is carried by an invertible fractional ideal whose exponents live on the
given set of primes.** -/
def HasClassReps (X : Set (HeightOneSpectrum (𝓞 K))) : Prop :=
  ∀ q : (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range,
    ∃ J : (FractionalIdeal (𝓞 K)⁰ K)ˣ,
      (∀ v ∉ X, FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) = 0) ∧
      QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range J = q

/-- Carrying the ideal classes only becomes easier on a larger set of primes. -/
theorem HasClassReps.mono {X Y : Set (HeightOneSpectrum (𝓞 K))} (h : HasClassReps K X)
    (hXY : X ⊆ Y) : HasClassReps K Y := by
  intro q
  obtain ⟨J, hJ0, hJq⟩ := h q
  exact ⟨J, fun v hv => hJ0 v fun hvX => hv (hXY hvX), hJq⟩

end Places

/-! ### Carrying the classes and realising the orders -/

section Dictionary

variable (K : Type*) [Field K] [NumberField K]

/-- **A set away from which every finitely supported system of orders is realised carries the ideal
classes.**  A class is the class of some invertible fractional ideal; correcting that ideal by the
principal ideal generated by an element whose orders away from the set are those of the ideal leaves
the class alone and kills the exponents there. -/
theorem hasClassReps_of_ord_repr {X : Set (HeightOneSpectrum (𝓞 K))}
    (hX : ∀ n : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) →
      ∃ a : Kˣ, ∀ v ∉ X, ord K v (a : K) = n v) :
    HasClassReps K X := by
  intro q
  obtain ⟨I, rfl⟩ : ∃ I : (FractionalIdeal (𝓞 K)⁰ K)ˣ,
      QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range I = q :=
    QuotientGroup.induction_on q fun I => ⟨I, rfl⟩
  obtain ⟨a, ha⟩ := hX (fun v => FractionalIdeal.count K v (I : FractionalIdeal (𝓞 K)⁰ K))
    (FractionalIdeal.finite_factors _)
  refine ⟨I * toPrincipalIdeal (𝓞 K) K a⁻¹, fun v hv => ?_, ?_⟩
  · have h1 : FractionalIdeal.count K v
        ((I * toPrincipalIdeal (𝓞 K) K a⁻¹ : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
          FractionalIdeal (𝓞 K)⁰ K)
        = FractionalIdeal.count K v (I : FractionalIdeal (𝓞 K)⁰ K)
          + ord K v ((a⁻¹ : Kˣ) : K) := by
      rw [Units.val_mul, coe_toPrincipalIdeal,
        FractionalIdeal.count_mul K v (Units.ne_zero I)
          (spanSingleton_ne_zero_iff.mpr (Units.ne_zero a⁻¹)), ord_def]
    rw [h1, Units.val_inv_eq_inv_val, ord_inv, ha v hv, add_neg_cancel]
  · have h1 : QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range
        (toPrincipalIdeal (𝓞 K) K a⁻¹) = 1 :=
      (QuotientGroup.eq_one_iff _).2 (MonoidHom.mem_range.2 ⟨a⁻¹, rfl⟩)
    rw [_root_.map_mul, h1, mul_one]

/-- **A set carrying the ideal classes is a set away from which every finitely supported system of
orders is realised.** -/
theorem exists_ord_repr_of_hasClassReps {X : Set (HeightOneSpectrum (𝓞 K))}
    (h : HasClassReps K X) (n : HeightOneSpectrum (𝓞 K) → ℤ)
    (hn : ∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) :
    ∃ a : Kˣ, ∀ v ∉ X, ord K v (a : K) = n v := by
  choose rep hrep0 hrep using h
  obtain ⟨a, ha⟩ := exists_ord_repr_of_forall_count K rep hrep n hn
  exact ⟨a, fun v hv => ha v fun q => hrep0 q v hv⟩

end Dictionary

/-! ### Moving the support onto the same classes -/

section Replace

variable (K : Type*) [Field K] [NumberField K]

/-- **A set carrying the ideal classes may be replaced by any set meeting the same classes.**  A
fractional ideal supported on the first set is the product of the primes there, each raised to its
exponent, so its class is the product of the classes of those primes; replacing each prime by one of
the same class taken from the second set gives a fractional ideal of the same class supported on the
second. -/
theorem hasClassReps_of_forall_exists_clsPlace {X A : Set (HeightOneSpectrum (𝓞 K))}
    (hX : X.Finite) (h : HasClassReps K X)
    (hA : ∀ v ∈ X, ∃ w ∈ A, clsPlace K w = clsPlace K v) :
    HasClassReps K A := by
  classical
  obtain ⟨s, hs⟩ : ∃ s : Finset (HeightOneSpectrum (𝓞 K)), ∀ v, v ∈ s ↔ v ∈ X :=
    ⟨hX.toFinset, fun v => hX.mem_toFinset⟩
  set p : HeightOneSpectrum (𝓞 K) → HeightOneSpectrum (𝓞 K) := fun v =>
    if hv : ∃ w ∈ A, clsPlace K w = clsPlace K v then hv.choose else v with hp
  have hpA : ∀ v ∈ X, p v ∈ A := by
    intro v hv
    have h1 : ∃ w ∈ A, clsPlace K w = clsPlace K v := hA v hv
    rw [hp]
    simp only [dif_pos h1]
    exact h1.choose_spec.1
  have hpc : ∀ v ∈ X, clsPlace K (p v) = clsPlace K v := by
    intro v hv
    have h1 : ∃ w ∈ A, clsPlace K w = clsPlace K v := hA v hv
    rw [hp]
    simp only [dif_pos h1]
    exact h1.choose_spec.2
  intro q
  obtain ⟨J, hJ0, hJq⟩ := h q
  have hJne : ∀ (w : HeightOneSpectrum (𝓞 K)) (m : ℤ),
      ((w.asIdeal : FractionalIdeal (𝓞 K)⁰ K) ^ m) ≠ 0 := fun w m =>
    zpow_ne_zero _ (coeIdeal_ne_zero.mpr w.ne_bot)
  have hJfac : J = ∏ v ∈ s, placeUnit K v ^
      FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) := by
    refine Units.ext ?_
    have hsub : Function.mulSupport (fun v : HeightOneSpectrum (𝓞 K) =>
        (v.asIdeal : FractionalIdeal (𝓞 K)⁰ K) ^
          FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K)) ⊆ ↑s := by
      intro v hv
      by_contra hvs
      apply hv
      show (v.asIdeal : FractionalIdeal (𝓞 K)⁰ K) ^
        FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) = 1
      rw [hJ0 v fun hvX => hvs (Finset.mem_coe.mpr ((hs v).mpr hvX)), zpow_zero]
    rw [Units.coe_prod]
    simp only [Units.val_zpow_eq_zpow_val, coe_placeUnit]
    rw [← finprod_eq_finset_prod_of_mulSupport_subset _ hsub]
    exact (FractionalIdeal.finprod_heightOneSpectrum_factorization' K (Units.ne_zero J)).symm
  refine ⟨∏ v ∈ s, placeUnit K (p v) ^
    FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K), fun u hu => ?_, ?_⟩
  · have hval : ((∏ v ∈ s, placeUnit K (p v) ^
        FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) :
          (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K)
        = ∏ v ∈ s, ((p v).asIdeal : FractionalIdeal (𝓞 K)⁰ K) ^
          FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) := by
      rw [Units.coe_prod]
      simp only [Units.val_zpow_eq_zpow_val, coe_placeUnit]
    rw [hval, FractionalIdeal.count_prod K u s _ fun v _ => hJne (p v) _]
    refine Finset.sum_eq_zero fun v hv => ?_
    have hne : p v ≠ u := fun hvu => hu (hvu ▸ hpA v ((hs v).mp hv))
    rw [FractionalIdeal.count_zpow, FractionalIdeal.count_maximal_coprime K u hne, mul_zero]
  · have h1 : QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range
        (∏ v ∈ s, placeUnit K (p v) ^
          FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K))
        = ∏ v ∈ s, clsPlace K (p v) ^
          FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) := by
      rw [_root_.map_prod]
      exact Finset.prod_congr rfl fun v _ => by rw [clsPlace_def, _root_.map_zpow]
    have h2 : ∏ v ∈ s, clsPlace K (p v) ^
        FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K)
        = ∏ v ∈ s, clsPlace K v ^
          FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K) :=
      Finset.prod_congr rfl fun v hv => by rw [hpc v ((hs v).mp hv)]
    have h3 : ∏ v ∈ s, clsPlace K v ^
        FractionalIdeal.count K v (J : FractionalIdeal (𝓞 K)⁰ K)
        = QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range J := by
      conv_rhs => rw [hJfac]
      rw [_root_.map_prod]
      exact (Finset.prod_congr rfl fun v _ => by rw [clsPlace_def, _root_.map_zpow]).symm
    rw [h1, h2, h3, hJq]

end Replace

/-! ### Bounding the number of primes by the class number -/

section Bounded

variable (K : Type*) [Field K] [NumberField K]

/-- **A finite set carrying the ideal classes contains one of at most the class number many primes
which carries them too.**  Keep one prime for each class actually occurring in the set. -/
theorem exists_subset_card_le_hasClassReps {X : Set (HeightOneSpectrum (𝓞 K))} (hX : X.Finite)
    (h : HasClassReps K X) :
    ∃ A ⊆ X, A.Finite ∧
      Nat.card ↥A ≤
        Nat.card ((FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range) ∧
      HasClassReps K A := by
  classical
  have hchoose : ∀ c : ↥(clsPlace K '' X),
      ∃ v, v ∈ X ∧ clsPlace K v = (c : (FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸
        (toPrincipalIdeal (𝓞 K) K).range) := fun c => c.2
  choose g hgX hgc using hchoose
  refine ⟨Set.range g, ?_, Set.finite_range g, ?_, ?_⟩
  · rintro _ ⟨c, rfl⟩
    exact hgX c
  · have h1 : Nat.card ↥(Set.range g) ≤ Nat.card ↥(clsPlace K '' X) :=
      Nat.card_le_card_of_surjective (fun c => (⟨g c, ⟨c, rfl⟩⟩ : ↥(Set.range g)))
        fun y => by
          obtain ⟨c, hc⟩ := y.2
          exact ⟨c, Subtype.ext hc⟩
    have h2 : Nat.card ↥(clsPlace K '' X) ≤
        Nat.card ((FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range) :=
      Nat.card_le_card_of_injective Subtype.val Subtype.val_injective
    exact h1.trans h2
  · refine hasClassReps_of_forall_exists_clsPlace K hX h fun v hv => ?_
    exact ⟨g ⟨clsPlace K v, ⟨v, hv, rfl⟩⟩, ⟨_, rfl⟩, hgc _⟩

/-- **A set away from which every finitely supported system of orders is realised contains one of at
most the class number many primes with the same property.**  The size of the smaller set is bounded
by an invariant of the field, so it is known before the set is. -/
theorem exists_card_le_ord_repr_of_ord_repr {X : Set (HeightOneSpectrum (𝓞 K))} (hX : X.Finite)
    (hXrepr : ∀ n : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) →
      ∃ a : Kˣ, ∀ v ∉ X, ord K v (a : K) = n v) :
    ∃ A ⊆ X, A.Finite ∧
      Nat.card ↥A ≤
        Nat.card ((FractionalIdeal (𝓞 K)⁰ K)ˣ ⧸ (toPrincipalIdeal (𝓞 K) K).range) ∧
      ∀ n : HeightOneSpectrum (𝓞 K) → ℤ,
        (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) →
        ∃ a : Kˣ, ∀ v ∉ A, ord K v (a : K) = n v := by
  obtain ⟨A, hAX, hAfin, hAcard, hA⟩ :=
    exists_subset_card_le_hasClassReps K hX (hasClassReps_of_ord_repr K hXrepr)
  exact ⟨A, hAX, hAfin, hAcard, fun n hn => exists_ord_repr_of_hasClassReps K hA n hn⟩

end Bounded

end InverseGalois.CFT
