/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Compositum
import InverseGalois.CFT.CompositumLift
import InverseGalois.CFT.Units.CompositumFundamental

/-!
# Two extensions embedded in a common overfield

The transport of a class of the right order across a compositum asks for two extensions sitting
inside one common extension, with complementary groups of automorphisms.  Two abstract extensions
of the rationals do not sit anywhere in particular, but any two of them embed into an algebraically
closed field, and the subfield generated by the two images is a common extension of both.

The two groups of automorphisms are complementary exactly when the two images meet in the rationals
and generate everything.  Both conditions are statements about the lattice of intermediate fields
of the compositum, and the passage between an automorphism restricting to the identity and an
automorphism fixing a subfield pointwise turns them into the two lattice identities relating the
fixing subgroup of a supremum and of an infimum.

## Main results

* `InverseGalois.CFT.ker_restrictNormalHom_eq_fixingSubgroup`: the automorphisms of an extension
  restricting to the identity on a normal intermediate extension are exactly those fixing its
  image pointwise.
* `InverseGalois.CFT.exists_zsmul_eq_zero_imp_dvd_H2_ideleClassRep_of_embed`: **a class of the
  second cohomology of the idele class group of a Galois number field annihilated by exactly the
  multiples of its degree, out of a disjointly embedded auxiliary cyclic field of the same
  degree.**

## Tags

number field, idele class group, fundamental class, compositum, embedding
-/

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1000000

open CategoryTheory groupCohomology IsDedekindDomain NumberField

namespace InverseGalois.CFT

noncomputable section

/-! ### Restriction to an intermediate field and its fixing subgroup -/

section Bridge

variable {k K M : Type*} [Field k] [Field K] [Field M] [Algebra k K] [Algebra k M] [Algebra K M]
  [IsScalarTower k K M] [Normal k K]

variable (k K M) in
/-- **The automorphisms of an extension restricting to the identity on a normal intermediate field
are exactly those fixing its image pointwise.** -/
theorem ker_restrictNormalHom_eq_fixingSubgroup :
    (AlgEquiv.restrictNormalHom K : Gal(M/k) →* Gal(K/k)).ker
      = (IsScalarTower.toAlgHom k K M).fieldRange.fixingSubgroup := by
  ext σ
  rw [MonoidHom.mem_ker, IntermediateField.mem_fixingSubgroup_iff]
  constructor
  · rintro h y ⟨x, rfl⟩
    have hx : σ.restrictNormal K x = x := by
      have hax := congrArg (fun τ : Gal(K/k) => τ x) h
      simpa only [AlgEquiv.one_apply] using hax
    show σ (algebraMap K M x) = algebraMap K M x
    rw [← AlgEquiv.restrictNormal_commutes σ K x, hx]
  · intro h
    ext x
    show σ.restrictNormal K x = x
    apply (algebraMap K M).injective
    rw [AlgEquiv.restrictNormal_commutes σ K x]
    exact h _ ⟨x, rfl⟩

end Bridge

/-! ### The compositum of two embedded extensions -/

section Embed

variable {K L Ω : Type} [Field K] [NumberField K] [IsGalois ℚ K] [Field L] [NumberField L]
  [IsGalois ℚ L] [Field Ω] [CharZero Ω]

variable (K L) in
/-- **A class of the second cohomology of the idele class group of a Galois number field,
annihilated by exactly the multiples of the degree, out of an auxiliary cyclic field embedded
disjointly in a common overfield.** -/
theorem exists_zsmul_eq_zero_imp_dvd_H2_ideleClassRep_of_embed (φ : K →ₐ[ℚ] Ω) (ψ : L →ₐ[ℚ] Ω)
    (hinf : φ.fieldRange ⊓ ψ.fieldRange = ⊥)
    {n : ℕ} (hnK : Nat.card Gal(K/ℚ) = n) (hnL : Nat.card Gal(L/ℚ) = n)
    {σL : Gal(L/ℚ)} (hgenσ : ∀ g : Gal(L/ℚ), g ∈ Subgroup.zpowers σL) (d : ↥(idele ℚ))
    (hgend : ∀ z : ↥(idele ℚ) ⧸ ((ideleDiag ℚ).range ⊔ (ideleNorm ℚ L).range),
      z ∈ AddSubmonoid.multiples (QuotientAddGroup.mk d))
    (hordd : addOrderOf (QuotientAddGroup.mk d :
      ↥(idele ℚ) ⧸ ((ideleDiag ℚ).range ⊔ (ideleNorm ℚ L).range)) = n)
    (hdnorm : d ∈ (ideleNorm ℚ K).range) :
    ∃ α : ↥(H2 (ideleClassRep ℚ K)), ∀ m : ℤ, m • α = 0 → (n : ℤ) ∣ m := by
  haveI : FiniteDimensional ℚ ↥φ.fieldRange :=
    FiniteDimensional.of_injective (AlgEquiv.ofInjectiveField φ).symm.toLinearMap
      (AlgEquiv.ofInjectiveField φ).symm.injective
  haveI : NumberField ↥φ.fieldRange := ⟨⟩
  haveI : IsGalois ℚ ↥φ.fieldRange := IsGalois.of_algEquiv (AlgEquiv.ofInjectiveField φ)
  haveI : FiniteDimensional ℚ ↥ψ.fieldRange :=
    FiniteDimensional.of_injective (AlgEquiv.ofInjectiveField ψ).symm.toLinearMap
      (AlgEquiv.ofInjectiveField ψ).symm.injective
  haveI : NumberField ↥ψ.fieldRange := ⟨⟩
  haveI : IsGalois ℚ ↥ψ.fieldRange := IsGalois.of_algEquiv (AlgEquiv.ofInjectiveField ψ)
  haveI : FiniteDimensional ℚ ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    IntermediateField.finiteDimensional_sup _ _
  haveI : NumberField ↥(φ.fieldRange ⊔ ψ.fieldRange) := ⟨⟩
  haveI : IsGalois ℚ ↥(φ.fieldRange ⊔ ψ.fieldRange) := isGalois_sup _ _
  letI : Algebra K ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    (RingHom.codRestrict φ.toRingHom (φ.fieldRange ⊔ ψ.fieldRange)
      fun x => (le_sup_left : φ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange)
        (AlgHom.mem_fieldRange.mpr ⟨x, rfl⟩)).toAlgebra
  letI : Algebra L ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    (RingHom.codRestrict ψ.toRingHom (φ.fieldRange ⊔ ψ.fieldRange)
      fun x => (le_sup_right : ψ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange)
        (AlgHom.mem_fieldRange.mpr ⟨x, rfl⟩)).toAlgebra
  haveI : IsScalarTower ℚ K ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    IsScalarTower.of_algebraMap_eq fun r => Subtype.ext (φ.commutes r).symm
  haveI : IsScalarTower ℚ L ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    IsScalarTower.of_algebraMap_eq fun r => Subtype.ext (ψ.commutes r).symm
  haveI : IsGalois K ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    IsGalois.tower_top_of_isGalois ℚ K ↥(φ.fieldRange ⊔ ψ.fieldRange)
  haveI : IsGalois L ↥(φ.fieldRange ⊔ ψ.fieldRange) :=
    IsGalois.tower_top_of_isGalois ℚ L ↥(φ.fieldRange ⊔ ψ.fieldRange)
  have hrangeK : (IsScalarTower.toAlgHom ℚ K ↥(φ.fieldRange ⊔ ψ.fieldRange)).fieldRange
      = IntermediateField.restrict
          (le_sup_left : φ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange) := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact (IntermediateField.mem_restrict _ _).mpr ⟨y, rfl⟩
    · intro hx
      obtain ⟨y, hy⟩ := (IntermediateField.mem_restrict _ _).mp hx
      exact ⟨y, Subtype.ext hy⟩
  have hrangeL : (IsScalarTower.toAlgHom ℚ L ↥(φ.fieldRange ⊔ ψ.fieldRange)).fieldRange
      = IntermediateField.restrict
          (le_sup_right : ψ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange) := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact (IntermediateField.mem_restrict _ _).mpr ⟨y, rfl⟩
    · intro hx
      obtain ⟨y, hy⟩ := (IntermediateField.mem_restrict _ _).mp hx
      exact ⟨y, Subtype.ext hy⟩
  have hdisj : (AlgEquiv.restrictNormalHom L :
        Gal(↥(φ.fieldRange ⊔ ψ.fieldRange)/ℚ) →* Gal(L/ℚ)).ker
      ⊓ (AlgEquiv.restrictNormalHom K :
        Gal(↥(φ.fieldRange ⊔ ψ.fieldRange)/ℚ) →* Gal(K/ℚ)).ker = ⊥ := by
    have htop : IntermediateField.restrict
          (le_sup_right : ψ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange)
        ⊔ IntermediateField.restrict
          (le_sup_left : φ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange) = ⊤ :=
      (sup_comm _ _).trans (restrict_sup_restrict φ.fieldRange ψ.fieldRange)
    rw [ker_restrictNormalHom_eq_fixingSubgroup ℚ L ↥(φ.fieldRange ⊔ ψ.fieldRange),
      ker_restrictNormalHom_eq_fixingSubgroup ℚ K ↥(φ.fieldRange ⊔ ψ.fieldRange),
      hrangeK, hrangeL, ← IntermediateField.fixingSubgroup_sup, htop,
      IntermediateField.fixingSubgroup_top]
  have hsup : (AlgEquiv.restrictNormalHom L :
        Gal(↥(φ.fieldRange ⊔ ψ.fieldRange)/ℚ) →* Gal(L/ℚ)).ker
      ⊔ (AlgEquiv.restrictNormalHom K :
        Gal(↥(φ.fieldRange ⊔ ψ.fieldRange)/ℚ) →* Gal(K/ℚ)).ker = ⊤ := by
    have hbot : IntermediateField.restrict
          (le_sup_right : ψ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange)
        ⊓ IntermediateField.restrict
          (le_sup_left : φ.fieldRange ≤ φ.fieldRange ⊔ ψ.fieldRange) = ⊥ := by
      rw [← IntermediateField.lift_inj, IntermediateField.lift_inf,
        IntermediateField.lift_restrict, IntermediateField.lift_restrict,
        IntermediateField.lift_bot]
      exact (inf_comm _ _).trans hinf
    rw [ker_restrictNormalHom_eq_fixingSubgroup ℚ L ↥(φ.fieldRange ⊔ ψ.fieldRange),
      ker_restrictNormalHom_eq_fixingSubgroup ℚ K ↥(φ.fieldRange ⊔ ψ.fieldRange),
      hrangeK, hrangeL, ← fixingSubgroup_inf, hbot, IntermediateField.fixingSubgroup_bot]
  exact exists_zsmul_eq_zero_imp_dvd_H2_ideleClassRep_of_compositum ℚ K L
    ↥(φ.fieldRange ⊔ ψ.fieldRange) hdisj hsup hnK hnL hgenσ d hgend hordd hdnorm

end Embed

end

end InverseGalois.CFT
