/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Profinite.FixingSubgroup
import InverseGalois.CFT.Profinite.KummerFinite
import InverseGalois.CFT.Units.DecompositionRestrict

/-!
# The cyclotomic level of an algebraic closure

An algebraic closure of a field of characteristic zero carries a primitive root of unity of every
order, and adjoining one of them to the base cuts out a finite Galois subextension: the extension it
generates is a cyclotomic extension of the base, hence finite and Galois.  Its degree divides the
number of invertible residues modulo the order, because an automorphism is determined by the power
to which it raises the root and that power is invertible; so for a prime order the degree divides
the prime minus one and is therefore prime to it.

The degree is also the index of the subgroup fixing the level, the quotient by that subgroup being
the Galois group of the level.  That is the form in which the coprimality is used: a class of
cohomology of prime order dying on the subgroup which fixes the level dies outright, so a statement
which needs the roots of unity in the base can be proved over the level and carried back down.

Carrying it back down needs the local structure to travel too, and it does: reading an automorphism
over the level as an automorphism over the base is the restriction of scalars, so a decomposition
subgroup over the level lands in a decomposition subgroup over the base.

## Main definitions

* `InverseGalois.CFT.cycLevel`: the subextension of an algebraic closure generated by a chosen
  primitive root of unity of a given order.

## Main results

* `InverseGalois.CFT.cycLevelRootBase_spec`: the chosen element is a primitive root of unity of the
  level.
* `InverseGalois.CFT.finrank_cycLevel_dvd_totient`: **the degree of the level divides the number of
  invertible residues modulo the order.**
* `InverseGalois.CFT.coprime_index_fixingSubgroup_cycLevel`: **for a prime order the index of the
  subgroup fixing the level is prime to that order.**
* `InverseGalois.CFT.decompositionSubgroups_le_galSubHom`: **a decomposition subgroup over an
  intermediate field maps into a decomposition subgroup over the base.**

## Tags

cyclotomic field, roots of unity, Krull topology, fixing subgroup, decomposition subgroup
-/

namespace InverseGalois.CFT

open Module IntermediateField

/-! ### A root of unity in an algebraic closure -/

section Level

variable (k Ω : Type) [Field k] [CharZero k] [Field Ω] [Algebra k Ω] [IsAlgClosure k Ω] (n : ℕ)
  [NeZero n]

include k in
/-- An algebraic closure of a field of characteristic zero contains a primitive root of unity of
every nonzero order. -/
theorem exists_isPrimitiveRoot_of_isAlgClosure : ∃ ζ : Ω, IsPrimitiveRoot ζ n := by
  haveI : IsAlgClosed Ω := IsAlgClosure.isAlgClosed k
  haveI : CharZero Ω := charZero_of_injective_algebraMap (algebraMap k Ω).injective
  haveI : NeZero ((n : ℕ) : Ω) := ⟨Nat.cast_ne_zero.2 (NeZero.ne n)⟩
  exact HasEnoughRootsOfUnity.exists_primitiveRoot _ n

/-- A chosen primitive root of unity of a given order in an algebraic closure. -/
noncomputable def cycLevelRoot : Ω :=
  (exists_isPrimitiveRoot_of_isAlgClosure k Ω n).choose

/-- The chosen element is a primitive root of unity. -/
theorem cycLevelRoot_spec : IsPrimitiveRoot (cycLevelRoot k Ω n) n :=
  (exists_isPrimitiveRoot_of_isAlgClosure k Ω n).choose_spec

/-- **The cyclotomic level of an algebraic closure**: the subextension generated by a chosen
primitive root of unity of a given order. -/
noncomputable def cycLevel : IntermediateField k Ω :=
  IntermediateField.adjoin k {cycLevelRoot k Ω n}

/-- The cyclotomic level is a cyclotomic extension of the base. -/
instance isCyclotomicExtension_cycLevel : IsCyclotomicExtension {n} k ↥(cycLevel k Ω n) := by
  haveI : Algebra.IsAlgebraic k Ω := IsAlgClosure.isAlgebraic
  haveI : Algebra.IsIntegral k Ω := Algebra.IsAlgebraic.isIntegral
  exact (cycLevelRoot_spec k Ω n).intermediateField_adjoin_isCyclotomicExtension k

/-- The cyclotomic level is a finite extension of the base. -/
instance finiteDimensional_cycLevel : FiniteDimensional k ↥(cycLevel k Ω n) :=
  IsCyclotomicExtension.finiteDimensional {n} k _

/-- The cyclotomic level is Galois over the base. -/
instance isGalois_cycLevel : IsGalois k ↥(cycLevel k Ω n) :=
  IsCyclotomicExtension.isGalois {n} k _

/-- The chosen root of unity lies in the level it generates. -/
theorem cycLevelRoot_mem : cycLevelRoot k Ω n ∈ cycLevel k Ω n :=
  IntermediateField.subset_adjoin k {cycLevelRoot k Ω n} rfl

/-- The chosen root of unity, read as an element of the level it generates. -/
noncomputable def cycLevelRootBase : ↥(cycLevel k Ω n) :=
  ⟨cycLevelRoot k Ω n, cycLevelRoot_mem k Ω n⟩

/-- **The level carries a primitive root of unity of the given order.** -/
theorem cycLevelRootBase_spec : IsPrimitiveRoot (cycLevelRootBase k Ω n) n :=
  IsPrimitiveRoot.of_map_of_injective
    (f := (algebraMap ↥(cycLevel k Ω n) Ω).toMonoidHom)
    (cycLevelRoot_spec k Ω n) (algebraMap ↥(cycLevel k Ω n) Ω).injective

/-! ### The degree of the level -/

/-- **The degree of the cyclotomic level divides the number of invertible residues modulo the
order.**  An automorphism of the level raises the chosen root of unity to an invertible power, the
power determines the automorphism, and the powers form a group of that size. -/
theorem finrank_cycLevel_dvd_totient : finrank k ↥(cycLevel k Ω n) ∣ Nat.totient n := by
  classical
  have hinj := (cycLevelRootBase_spec k Ω n).autToPow_injective (K := k)
  have h1 : Nat.card Gal(↥(cycLevel k Ω n)/k)
      = Nat.card ↥(((cycLevelRootBase_spec k Ω n).autToPow k).range) :=
    Nat.card_congr (Equiv.ofInjective _ hinj)
  rw [← IsGalois.card_aut_eq_finrank (F := k) (E := ↥(cycLevel k Ω n)), h1,
    ← ZMod.card_units_eq_totient n, ← Nat.card_eq_fintype_card]
  exact Subgroup.card_subgroup_dvd_card _

/-- **The index of the subgroup fixing the cyclotomic level is the degree of the level**, the
quotient by that subgroup being the Galois group of the level. -/
theorem index_fixingSubgroup_cycLevel :
    (cycLevel k Ω n).fixingSubgroup.index = finrank k ↥(cycLevel k Ω n) := by
  rw [Subgroup.index_eq_card,
    Nat.card_congr (quotientFixingSubgroupEquiv (cycLevel k Ω n)).toEquiv,
    IsGalois.card_aut_eq_finrank]

/-- **For a prime order the index of the subgroup fixing the cyclotomic level is prime to that
order.**  The index divides the order minus one. -/
theorem coprime_index_fixingSubgroup_cycLevel (hn : n.Prime) :
    Nat.Coprime n (cycLevel k Ω n).fixingSubgroup.index := by
  rw [index_fixingSubgroup_cycLevel]
  refine Nat.Coprime.coprime_dvd_right (finrank_cycLevel_dvd_totient k Ω n) ?_
  rw [Nat.totient_prime hn]
  exact (Nat.coprime_self_sub_right hn.one_le).mpr (Nat.coprime_one_right n)

end Level

/-! ### The level over a number field -/

section NumberFieldLevel

variable (k Ω : Type) [Field k] [NumberField k] [Field Ω] [Algebra k Ω] [IsAlgClosure k Ω] (n : ℕ)
  [NeZero n]

/-- The cyclotomic level of an algebraic closure of a number field is a number field. -/
instance numberField_cycLevel : NumberField ↥(cycLevel k Ω n) :=
  NumberField.of_module_finite k ↥(cycLevel k Ω n)

/-- An algebraic closure of the base is one of the cyclotomic level as well. -/
instance isAlgClosure_cycLevel : IsAlgClosure ↥(cycLevel k Ω n) Ω :=
  ⟨IsAlgClosure.isAlgClosed k, Algebra.IsAlgebraic.tower_top (K := k) _⟩

end NumberFieldLevel

/-! ### The local structure over an intermediate field -/

section GalSub

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω] (F : IntermediateField k Ω)

/-- Reading an automorphism over an intermediate field as an automorphism over the base is the
restriction of scalars. -/
theorem galRestrictScalarsHom_eq_galSubHom : galRestrictScalarsHom k ↥F Ω = galSubHom F :=
  MonoidHom.ext fun _ => AlgEquiv.ext fun _ => rfl

/-- **A decomposition subgroup over an intermediate field maps into a decomposition subgroup over
the base**, an automorphism over the field being one over the base fixing the same prime or the
same archimedean place. -/
theorem decompositionSubgroups_le_galSubHom :
    ∀ D' ∈ decompositionSubgroups ↥F Ω, ∃ D ∈ decompositionSubgroups k Ω,
      ∀ x ∈ D', galSubHom F x ∈ D := by
  simpa only [galRestrictScalarsHom_eq_galSubHom] using
    decompositionSubgroups_le_galRestrictScalarsHom k ↥F Ω

end GalSub

end InverseGalois.CFT
