/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.DecompositionFieldTower
import InverseGalois.CFT.Units.HasseTwoDecomposition

/-!
# The decomposition field of a level over a level

Let `Ω` be a Galois extension of a number field, let `K` be a finite Galois level of it and let `P`
be a nonzero prime of the integers of `Ω`.  The automorphisms of `Ω` fixing `P` and fixing `K`
pointwise form a subgroup, and the elements of `Ω` they fix form a field between `K` and `Ω`.  Each
finite Galois level `M` above `K` sees that field as the decomposition field, over `K`, of the
prime of `M` below `P`: **an element of `M` is fixed by every automorphism fixing the prime and the
level `K` exactly when it lies in the decomposition field of `M` over `K`.**

One direction restricts an automorphism of `Ω` to `M`, where it fixes the prime below and `K`
pointwise, so it is an automorphism of `M` over `K` in the decomposition group there.  The other
lifts an automorphism of `M` over `K` fixing the prime below to an automorphism of `Ω` fixing the
prime; the lift fixes `K` pointwise because its restriction does.

The decomposition field of the level embeds into the completion of `K` at the place below, and that
embedding is equivariant for the automorphisms of `Ω` fixing the prime: restricting such an
automorphism first to `M` and then to `K` is restricting it to `K` directly.

## Main results

* `InverseGalois.CFT.exists_isGalois_level_sup`: **a finite Galois level contains a given finite
  Galois level and a given finite set of elements.**
* `InverseGalois.CFT.mem_decompositionField_level_iff`: **an element of a level lies in the
  decomposition field of the level over a smaller level exactly when every automorphism of the
  whole extension fixing the prime and the smaller level pointwise fixes it.**
* `InverseGalois.CFT.decompositionFieldHom_smul_level`: **the embedding of the decomposition field
  of a level into the completion of the smaller level is equivariant** for the automorphisms of the
  whole extension fixing the prime.
* `InverseGalois.CFT.coe_stabilizerRestrictPlace_stabilizerRestrictPrime`: **restricting to the
  smaller level in two steps is restricting to it directly.**

## Tags

number field, infinite Galois theory, decomposition group, decomposition field, completion, level
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### A finite Galois level above a level and a finite set -/

section Sup

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]

variable (k) in
/-- **A finite Galois level contains a given finite Galois level and a given finite set of
elements**, being the compositum of the level with the normal closure of the subfield generated by
the set. -/
theorem exists_isGalois_level_sup (K : IntermediateField k Ω) [FiniteDimensional k ↥K]
    [IsGalois k ↥K] (s : Set Ω) [Finite s] :
    ∃ M : IntermediateField k Ω, K ≤ M ∧ FiniteDimensional k ↥M ∧ IsGalois k ↥M ∧
      s ⊆ (M : Set Ω) := by
  refine ⟨K ⊔ (FiniteGaloisIntermediateField.adjoin k s).toIntermediateField, le_sup_left,
    inferInstance, inferInstance, fun x hx => ?_⟩
  exact SetLike.le_def.mp le_sup_right (FiniteGaloisIntermediateField.subset_adjoin k s hx)

end Sup

/-! ### The decomposition field of a level over a level -/

section Level

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  {K M : IntermediateField k Ω} [NumberField ↥K] [IsGalois k ↥K] [NumberField ↥M] [IsGalois k ↥M]
  [Algebra ↥K ↥M] [IsScalarTower k ↥K ↥M] [IsScalarTower ↥K ↥M Ω] [IsGalois ↥K ↥M]
  {P : Ideal (𝓞 Ω)} [P.IsPrime] {Q : HeightOneSpectrum (𝓞 ↥M)}
  (hQ : Q.asIdeal = Ideal.under (𝓞 ↥M) P)

omit [IsGalois k Ω] [NumberField ↥K] [IsGalois k ↥K] [NumberField ↥M] [IsGalois k ↥M]
  [IsScalarTower ↥K ↥M Ω] [IsGalois ↥K ↥M] [P.IsPrime] in
/-- The action of an automorphism of the level over the smaller level on the primes of the level is
its action as an automorphism over the base. -/
theorem smul_restrictScalars_heightOneSpectrum (τ : ↥M ≃ₐ[↥K] ↥M)
    (v : HeightOneSpectrum (𝓞 ↥M)) : (τ.restrictScalars k) • v = τ • v := rfl

omit [IsGalois k Ω] [NumberField ↥K] [IsGalois k ↥K] [NumberField ↥M] [IsGalois k ↥M]
  [IsScalarTower k ↥K ↥M] [IsGalois ↥K ↥M] [P.IsPrime] in
/-- An element of the smaller level, read in the level, is the element itself. -/
theorem coe_algebraMap_level (y : ↥K) : ((algebraMap ↥K ↥M y : ↥M) : Ω) = (y : Ω) :=
  (IsScalarTower.algebraMap_apply ↥K ↥M Ω y).symm

omit [IsGalois k Ω] [IsGalois k ↥K] [NumberField ↥M] [IsGalois ↥K ↥M] [P.IsPrime] in
/-- The restriction of an automorphism of the whole extension to a level is compatible with the
inclusion of the level. -/
theorem coe_restrictNormalHom_level (τ : Gal(Ω/k)) (u : ↥M) :
    ((AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M τ u : ↥M) : Ω) = τ (u : Ω) :=
  AlgEquiv.restrictNormal_commutes τ ↥M u

omit [NumberField ↥K] [IsGalois k ↥K] [NumberField ↥M] [IsGalois ↥K ↥M] in
include hQ in
/-- **An element of a level lies in the decomposition field of the level over a smaller level
exactly when every automorphism of the whole extension fixing the prime and the smaller level
pointwise fixes it.**  Restricting such an automorphism to the level gives an automorphism over the
smaller level fixing the prime below, and every such automorphism arises that way. -/
theorem mem_decompositionField_level_iff {x : ↥M} :
    x ∈ decompositionField ↥K Q ↔
      ∀ σ : Gal(Ω/k), σ • P = P → σ ∈ K.fixingSubgroup → σ (x : Ω) = (x : Ω) := by
  constructor
  · intro hx σ hσP hσK
    have hτK : ∀ y : ↥K, AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M σ
        (algebraMap ↥K ↥M y) = algebraMap ↥K ↥M y := by
      intro y
      refine Subtype.ext ?_
      rw [coe_restrictNormalHom_level σ (algebraMap ↥K ↥M y), coe_algebraMap_level y]
      exact (IntermediateField.mem_fixingSubgroup_iff K σ).1 hσK (y : Ω) y.2
    have hτ'Q : (AlgEquiv.ofRingEquiv
        (f := (AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M σ).toRingEquiv) hτK) • Q = Q := by
      rw [← smul_restrictScalars_heightOneSpectrum (k := k)]
      exact restrictNormalHom_smul_place_of_smul_eq M hQ hσP
    have hfix := eq_of_mem_decompositionField ↥K Q hx
      ⟨AlgEquiv.ofRingEquiv (f := (AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M σ).toRingEquiv)
        hτK, mem_stabilizer_iff.mpr hτ'Q⟩
    have h : AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M σ x = x := hfix
    rw [← coe_restrictNormalHom_level σ x, h]
  · intro hfix
    rw [mem_decompositionField_iff]
    intro τ
    have hres : (τ.1.restrictScalars k) • Q = Q := by
      rw [smul_restrictScalars_heightOneSpectrum (k := k)]
      exact mem_stabilizer_iff.mp τ.2
    obtain ⟨σ, hσ⟩ := stabilizerRestrictPrime_surjective M hQ
      ⟨τ.1.restrictScalars k, mem_stabilizer_iff.mpr hres⟩
    have hσres : AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M (σ : Gal(Ω/k))
        = τ.1.restrictScalars k := congrArg Subtype.val hσ
    have hσK : (σ : Gal(Ω/k)) ∈ K.fixingSubgroup := by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro y hy
      have h1 : ((algebraMap ↥K ↥M ⟨y, hy⟩ : ↥M) : Ω) = y := coe_algebraMap_level (M := M) ⟨y, hy⟩
      calc (σ : Gal(Ω/k)) y
          = (σ : Gal(Ω/k)) ((algebraMap ↥K ↥M ⟨y, hy⟩ : ↥M) : Ω) := by rw [h1]
        _ = ((AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M (σ : Gal(Ω/k))
              (algebraMap ↥K ↥M ⟨y, hy⟩) : ↥M) : Ω) :=
            (coe_restrictNormalHom_level (σ : Gal(Ω/k)) _).symm
        _ = ((τ.1 (algebraMap ↥K ↥M ⟨y, hy⟩) : ↥M) : Ω) := by rw [hσres]; rfl
        _ = ((algebraMap ↥K ↥M ⟨y, hy⟩ : ↥M) : Ω) := by rw [τ.1.commutes]
        _ = y := h1
    refine Subtype.ext ?_
    have h : ((AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥M (σ : Gal(Ω/k)) x : ↥M) : Ω)
        = ((τ.1 x : ↥M) : Ω) := by rw [hσres]; rfl
    rw [← h, coe_restrictNormalHom_level]
    exact hfix (σ : Gal(Ω/k)) (mem_stabilizer_iff.mp σ.2) hσK

omit [IsGalois k Ω] [NumberField ↥K] [IsGalois ↥K ↥M] [P.IsPrime] in
include hQ in
/-- **Restricting an automorphism fixing the prime first to a level and then to a smaller one is
restricting it to the smaller level directly.** -/
theorem coe_stabilizerRestrictPlace_stabilizerRestrictPrime (σ : ↥(stabilizer Gal(Ω/k) P)) :
    (stabilizerRestrictPlace ↥K Q (stabilizerRestrictPrime M hQ σ) : Gal(↥K/k))
      = AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥K (σ : Gal(Ω/k)) := by
  have hKM : K ≤ M := fun y hy => by
    have h1 : ((algebraMap ↥K ↥M ⟨y, hy⟩ : ↥M) : Ω) = y := coe_algebraMap_level (M := M) ⟨y, hy⟩
    rw [← h1]
    exact (algebraMap ↥K ↥M ⟨y, hy⟩).2
  have hres : ∀ (g : Gal(↥M/k)) (y : Ω) (hy : y ∈ K) (hy' : y ∈ M),
      ((AlgEquiv.restrictNormalHom (F := k) (K₁ := ↥M) ↥K g ⟨y, hy⟩ : ↥K) : Ω)
        = ((g ⟨y, hy'⟩ : ↥M) : Ω) := by
    intro g y hy hy'
    have hmk : (algebraMap ↥K ↥M ⟨y, hy⟩ : ↥M) = ⟨y, hy'⟩ :=
      Subtype.ext (coe_algebraMap_level (M := M) ⟨y, hy⟩)
    have h : ((algebraMap ↥K ↥M (AlgEquiv.restrictNormal g ↥K ⟨y, hy⟩) : ↥M) : Ω)
        = ((g (algebraMap ↥K ↥M ⟨y, hy⟩) : ↥M) : Ω) :=
      congrArg (fun u : ↥M => (u : Ω)) (AlgEquiv.restrictNormal_commutes g ↥K ⟨y, hy⟩)
    rw [coe_algebraMap_level (M := M), hmk] at h
    exact h
  rw [coe_stabilizerRestrict, coe_stabilizerRestrictPrime]
  exact restrictNormalHom_eq_of_res hKM hres (σ : Gal(Ω/k))

omit [IsGalois k Ω] [IsScalarTower ↥K ↥M Ω] [P.IsPrime] in
include hQ in
/-- **The embedding of the decomposition field of a level into the completion of the smaller level
is equivariant** for the automorphisms of the whole extension fixing the prime, acting on the
completion through their restriction to the smaller level. -/
theorem decompositionFieldHom_smul_level (σ : ↥(stabilizer Gal(Ω/k) P))
    (x : ↥(decompositionField ↥K Q)) :
    decompositionFieldHom ↥K Q ⟨(stabilizerRestrictPrime M hQ σ : Gal(↥M/k)) (x : ↥M),
        smul_mem_decompositionField Q (stabilizerRestrictPrime M hQ σ) x.2⟩
      = stabilizerRestrictPlace ↥K Q (stabilizerRestrictPrime M hQ σ) •
          decompositionFieldHom ↥K Q x :=
  decompositionFieldHom_smul Q (stabilizerRestrictPrime M hQ σ) x

omit [IsGalois k Ω] [NumberField ↥M] [P.IsPrime] in
include hQ in
/-- The value at a point of the restriction to a level of an automorphism fixing the prime is the
value of the automorphism itself. -/
theorem coe_stabilizerRestrictPrime_apply (σ : ↥(stabilizer Gal(Ω/k) P)) (u : ↥M) :
    (((stabilizerRestrictPrime M hQ σ : Gal(↥M/k)) u : ↥M) : Ω) = (σ : Gal(Ω/k)) (u : Ω) := by
  rw [coe_stabilizerRestrictPrime]
  exact coe_restrictNormalHom_level (σ : Gal(Ω/k)) u

end Level

end InverseGalois.CFT
