/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.PlaceRestrict
import InverseGalois.CFT.Units.OrbitPlaces
import InverseGalois.CFT.Units.SplitNorm

/-!
# The decomposition groups generate the Galois group

The subgroup of the Galois group of a Galois extension of number fields generated by all the
decomposition groups, at the finite places and at the infinite places alike, is the whole Galois
group when the Galois group is solvable.  Its fixed field is a Galois subextension in which every
place of the base field splits completely, because an automorphism of a subextension fixing a place
is the restriction of an automorphism of the top field fixing a place above it: lift it arbitrarily,
and correct the lift by an automorphism over the subextension carrying the moved place back, which
is possible because the automorphisms over the subextension permute the places above a place of it
transitively.  A solvable extension in which every place splits completely is trivial, so the fixed
field is the base field.

## Main definitions

* `InverseGalois.CFT.decompositionSet`: the automorphisms fixing some place.
* `InverseGalois.CFT.decompositionSubgroup`: **the subgroup generated by the decomposition
  groups.**

## Main results

* `InverseGalois.CFT.exists_restrictNormalHom_eq_of_prime`,
  `InverseGalois.CFT.exists_restrictNormalHom_eq_of_infinitePlace`: **an automorphism of a
  subextension fixing a place is the restriction of an automorphism fixing a place above it.**
* `InverseGalois.CFT.decompositionSubgroup_eq_top`: **the decomposition groups generate a solvable
  Galois group.**

## Tags

number field, place, decomposition group, splitting, solvable
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

section Lift

variable {k F K : Type*} [Field k] [NumberField k] [Field F] [NumberField F] [Field K]
  [NumberField K] [Algebra k F] [Algebra F K] [Algebra k K] [IsScalarTower k F K]
  [IsGalois k F] [IsGalois k K]

variable (K) in
omit [NumberField k] in
/-- **An automorphism of the middle field fixing a finite place is the restriction of an
automorphism of the top field fixing a finite place above it.**  Any lift moves a chosen place above
to another place above, and the automorphisms over the middle field permute those transitively, so
correcting the lift by one of them gives a lift that fixes the chosen place. -/
theorem exists_restrictNormalHom_eq_of_prime (τ : Gal(F/k)) {u : HeightOneSpectrum (𝓞 F)}
    (hu : τ • u = u) :
    ∃ σ : Gal(K/k), (∃ v : HeightOneSpectrum (𝓞 K), σ • v = v) ∧
      AlgEquiv.restrictNormalHom F σ = τ := by
  haveI : IsGalois F K := IsGalois.tower_top_of_isGalois (F := k) (K := F) (E := K)
  obtain ⟨σ₀, hσ₀⟩ := AlgEquiv.restrictNormalHom_surjective (F := k) (K₁ := F) (E := K) τ
  obtain ⟨v, hv⟩ := exists_primeUnder_eq (𝓞 F) (𝓞 K) u
  have h1 : primeUnder (𝓞 F) (σ₀ • v) = primeUnder (𝓞 F) v := by
    rw [primeUnder_smul F, hv, hσ₀, hu]
  obtain ⟨ρ, hρ⟩ := exists_smul_eq_of_primeUnder_eq (A := 𝓞 F) (G := K ≃ₐ[F] K) h1
  refine ⟨ρ.restrictScalars k * σ₀, ⟨v, ?_⟩, ?_⟩
  · rw [mul_smul]
    exact hρ
  · rw [map_mul, restrictNormalHom_restrictScalars k F ρ, one_mul, hσ₀]

variable (K) in
omit [NumberField k] [NumberField F] [NumberField K] in
/-- **An automorphism of the middle field fixing an infinite place is the restriction of an
automorphism of the top field fixing an infinite place above it.** -/
theorem exists_restrictNormalHom_eq_of_infinitePlace (τ : Gal(F/k)) {u : InfinitePlace F}
    (hu : τ • u = u) :
    ∃ σ : Gal(K/k), (∃ w : InfinitePlace K, σ • w = w) ∧
      AlgEquiv.restrictNormalHom F σ = τ := by
  haveI : IsGalois F K := IsGalois.tower_top_of_isGalois (F := k) (K := F) (E := K)
  obtain ⟨σ₀, hσ₀⟩ := AlgEquiv.restrictNormalHom_surjective (F := k) (K₁ := F) (E := K) τ
  obtain ⟨w, hw⟩ := InfinitePlace.comap_surjective (k := F) (K := K) u
  have h1 : (σ₀ • w).comap (algebraMap F K) = w.comap (algebraMap F K) := by
    rw [comap_smul_algebraMap F, show w.comap (algebraMap F K) = u from hw, hσ₀, hu]
  obtain ⟨ρ, hρ⟩ := InfinitePlace.exists_smul_eq_of_comap_eq (k := F) h1
  refine ⟨ρ.restrictScalars k * σ₀, ⟨w, ?_⟩, ?_⟩
  · rw [mul_smul]
    exact hρ
  · rw [map_mul, restrictNormalHom_restrictScalars k F ρ, one_mul, hσ₀]

end Lift

section Decomposition

variable (k K : Type*) [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K]

/-- **The automorphisms fixing some place**, finite or infinite: the union of the decomposition
groups. -/
def decompositionSet : Set Gal(K/k) :=
  {σ | (∃ v : HeightOneSpectrum (𝓞 K), σ • v = v) ∨ ∃ w : InfinitePlace K, σ • w = w}

/-- **The subgroup generated by the decomposition groups.** -/
def decompositionSubgroup : Subgroup Gal(K/k) := Subgroup.closure (decompositionSet k K)

omit [NumberField k] [NumberField K] [IsGalois k K] in
theorem subset_decompositionSubgroup : decompositionSet k K ⊆ decompositionSubgroup k K :=
  Subgroup.subset_closure

omit [NumberField k] [NumberField K] [IsGalois k K] in
/-- The decomposition group at a finite place lies in the subgroup generated by the decomposition
groups. -/
theorem stabilizer_le_decompositionSubgroup (v : HeightOneSpectrum (𝓞 K)) :
    stabilizer Gal(K/k) v ≤ decompositionSubgroup k K :=
  fun _ hσ => subset_decompositionSubgroup k K (Or.inl ⟨v, hσ⟩)

omit [NumberField k] [NumberField K] [IsGalois k K] in
/-- The decomposition group at an infinite place lies in the subgroup generated by the decomposition
groups. -/
theorem stabilizer_infinitePlace_le_decompositionSubgroup (w : InfinitePlace K) :
    stabilizer Gal(K/k) w ≤ decompositionSubgroup k K :=
  fun _ hσ => subset_decompositionSubgroup k K (Or.inr ⟨w, hσ⟩)

variable {k K} in
omit [NumberField k] [NumberField K] [IsGalois k K] in
/-- **The set of automorphisms fixing some place is stable under conjugation**, because a conjugate
fixes the moved place. -/
theorem conj_mem_decompositionSet (g : Gal(K/k)) {σ : Gal(K/k)} (hσ : σ ∈ decompositionSet k K) :
    g * σ * g⁻¹ ∈ decompositionSet k K := by
  rcases hσ with ⟨v, hv⟩ | ⟨w, hw⟩
  · exact Or.inl ⟨g • v, by rw [mul_smul, inv_smul_smul, mul_smul, hv]⟩
  · exact Or.inr ⟨g • w, by rw [mul_smul, inv_smul_smul, mul_smul, hw]⟩

instance decompositionSubgroup_normal : (decompositionSubgroup k K).Normal := by
  refine ⟨fun n hn g => ?_⟩
  induction hn using Subgroup.closure_induction with
  | mem x hx => exact subset_decompositionSubgroup k K (conj_mem_decompositionSet g hx)
  | one => simp
  | mul x y _ _ hx hy =>
    rw [show g * (x * y) * g⁻¹ = g * x * g⁻¹ * (g * y * g⁻¹) by group]
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [show g * x⁻¹ * g⁻¹ = (g * x * g⁻¹)⁻¹ by group]
    exact inv_mem hx

end Decomposition

section FixedField

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K] (H : Subgroup Gal(K/k)) [H.Normal]

/-- **The automorphisms restricting to the identity on the fixed field of a normal subgroup are
exactly that subgroup.** -/
theorem ker_restrictNormalHom_fixedField :
    (AlgEquiv.restrictNormalHom ↥(IntermediateField.fixedField H) : Gal(K/k) →* _).ker = H :=
  (IntermediateField.restrictNormalHom_ker _).trans (IntermediateField.fixingSubgroup_fixedField H)

/-- **A normal subgroup whose fixed field has trivial Galois group is everything.** -/
theorem eq_top_of_subsingleton_gal_fixedField
    (h : Subsingleton Gal(↥(IntermediateField.fixedField H)/k)) : H = ⊤ :=
  (Subgroup.eq_top_iff' H).mpr fun _ =>
    ker_restrictNormalHom_fixedField H ▸ MonoidHom.mem_ker.mpr (h.elim _ _)

end FixedField

section Generate

variable (k K : Type*) [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K]

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

/-- **The decomposition groups generate a solvable Galois group.**  In the fixed field of the
subgroup they generate every place of the base field splits completely, because an automorphism of
that subextension fixing a place lifts to an automorphism fixing a place above it, which lies in the
subgroup and so restricts to the identity; a solvable extension in which every place splits
completely is trivial. -/
theorem decompositionSubgroup_eq_top [IsSolvable Gal(K/k)] : decompositionSubgroup k K = ⊤ := by
  refine eq_top_of_subsingleton_gal_fixedField _ ?_
  haveI : IsSolvable Gal(↥(IntermediateField.fixedField (decompositionSubgroup k K))/k) :=
    solvable_of_surjective (AlgEquiv.restrictNormalHom_surjective (F := k)
      (K₁ := ↥(IntermediateField.fixedField (decompositionSubgroup k K))) (E := K))
  have key : ∀ σ : Gal(K/k), σ ∈ decompositionSet k K →
      AlgEquiv.restrictNormalHom ↥(IntermediateField.fixedField (decompositionSubgroup k K)) σ
        = 1 := by
    intro σ hσ
    refine MonoidHom.mem_ker.mp ?_
    rw [ker_restrictNormalHom_fixedField]
    exact subset_decompositionSubgroup k K hσ
  refine subsingleton_gal_of_isSolvable_of_free k
    ↥(IntermediateField.fixedField (decompositionSubgroup k K)) (fun τ u hu => ?_)
    (fun τ w hw => ?_)
  · obtain ⟨σ, hσ, hres⟩ := exists_restrictNormalHom_eq_of_prime K τ hu
    rw [← hres]
    exact key σ (Or.inl hσ)
  · obtain ⟨σ, hσ, hres⟩ := exists_restrictNormalHom_eq_of_infinitePlace K τ hw
    rw [← hres]
    exact key σ (Or.inr hσ)

end Generate

end InverseGalois.CFT
