/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Profinite.PiTwo
import InverseGalois.CFT.Profinite.ShaComap
import InverseGalois.CFT.Units.BaseFundamental
import InverseGalois.CFT.Units.HasseTwoDecomposition

/-!
# Everywhere locally trivial classes stay locally trivial over a larger base

An automorphism of a Galois extension over an intermediate field is in particular an automorphism
over the base, and that inclusion of Galois groups is continuous: a finite subextension of the base
is generated by finitely many elements, adjoining them to the intermediate field gives a finite
subextension there, and an automorphism fixing the latter fixes the former.

The inclusion also respects the local structure.  A prime of the ring of integers of the extension
and an archimedean place of it are the same objects whichever base one works over, and an
automorphism over the intermediate field fixing one of them fixes it over the base too, so every
decomposition subgroup over the intermediate field sits inside the corresponding decomposition
subgroup over the base.  A class of the cohomology over the base dying on every decomposition
subgroup therefore restricts to a class over the intermediate field dying on every decomposition
subgroup.

Over a base with enough roots of unity that already forces the restricted class to be trivial, so
an everywhere locally trivial class of the second cohomology with roots of unity coefficients dies
as soon as one passes to the field generated by them.

Any finite module of exponent dividing the order of those roots of unity on which the Galois group
over the intermediate field acts trivially is a product of copies of them, and the second
cohomology of a finite product is the product of the second cohomologies.  So the same conclusion
holds for such a module: **an everywhere locally trivial class of the second cohomology of the
absolute Galois group of the base, with coefficients in a finite module split by the intermediate
field, dies over that field.**

## Main results

* `InverseGalois.CFT.continuous_galRestrictScalarsHom`: **restriction of scalars of an automorphism
  is continuous for the Krull topologies.**
* `InverseGalois.CFT.decompositionSubgroups_le_galRestrictScalarsHom`: **a decomposition subgroup
  over an intermediate field maps into a decomposition subgroup over the base.**
* `InverseGalois.CFT.comapH2_mem_sha2_decompositionSubgroups`: **an everywhere locally trivial
  class over the base restricts to an everywhere locally trivial class over an intermediate
  field.**
* `InverseGalois.CFT.eq_one_of_mem_sha2_of_isPrimitiveRoot_intermediate`: **an everywhere locally
  trivial class of the second cohomology with roots of unity coefficients dies on the Galois group
  over an intermediate field containing a primitive root of unity.**
* `InverseGalois.CFT.eq_one_of_mem_sha2_of_mulEquivPi_intermediate`: **an everywhere locally
  trivial class of the second cohomology with coefficients in a finite module split by an
  intermediate field with enough roots of unity dies on the Galois group over that field.**

## Tags

number field, Galois cohomology, decomposition group, restriction, local-global principle
-/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open groupCohomology MulAction NumberField

open scoped Pointwise

/-! ### Restriction of scalars is continuous -/

section Continuity

variable (F k K : Type*) [Field F] [Field k] [Field K] [Algebra F k] [Algebra k K] [Algebra F K]
  [IsScalarTower F k K] [Algebra.IsIntegral F K]

/-- **Restriction of scalars of an automorphism is continuous for the Krull topologies.**  A finite
subextension of the base is generated by a finite set, and adjoining that set to the intermediate
field gives a finite subextension over which an automorphism fixing it fixes the original one. -/
theorem continuous_galRestrictScalarsHom : Continuous (galRestrictScalarsHom F k K) := by
  refine continuous_of_continuousAt_one _ ?_
  rw [ContinuousAt, map_one, Filter.tendsto_def]
  intro s hs
  rw [krullTopology_mem_nhds_one_iff] at hs
  obtain ⟨E, hEfin, hEs⟩ := hs
  obtain ⟨t, ht⟩ : E.FG := by
    rw [← IntermediateField.essFiniteType_iff]
    infer_instance
  rw [krullTopology_mem_nhds_one_iff]
  refine ⟨IntermediateField.adjoin k (↑t : Set K), ?_, ?_⟩
  · exact IntermediateField.finiteDimensional_adjoin fun x _ =>
      (Algebra.IsIntegral.isIntegral (R := F) x).tower_top
  · intro σ hσ
    refine hEs ?_
    rw [SetLike.mem_coe, IntermediateField.mem_fixingSubgroup_iff] at hσ ⊢
    intro x hx
    have hsub : E ≤ IntermediateField.fixedField
        (Subgroup.zpowers (galRestrictScalarsHom F k K σ)) := by
      rw [← ht, IntermediateField.adjoin_le_iff]
      intro y hy
      rw [SetLike.mem_coe, IntermediateField.mem_fixedField_iff]
      intro f hf
      have hle : Subgroup.zpowers (galRestrictScalarsHom F k K σ) ≤
          stabilizer Gal(K/F) y := by
        rw [Subgroup.zpowers_le]
        exact hσ y (IntermediateField.subset_adjoin k _ hy)
      exact hle hf
    exact (IntermediateField.mem_fixedField_iff _ _).1 (hsub hx)
      (galRestrictScalarsHom F k K σ) (Subgroup.mem_zpowers _)

/-- **Restriction of scalars of an automorphism is a smooth homomorphism.** -/
theorem isSmoothHom_galRestrictScalarsHom : IsSmoothHom (galRestrictScalarsHom F k K) :=
  isSmoothHom_of_continuous (continuous_galRestrictScalarsHom F k K)

end Continuity

/-! ### The decomposition subgroups over an intermediate field -/

section Tower

variable (k K Ω : Type*) [Field k] [Field K] [Field Ω] [Algebra k K] [Algebra K Ω] [Algebra k Ω]
  [IsScalarTower k K Ω]

/-- **A decomposition subgroup over an intermediate field maps into a decomposition subgroup over
the base**, at the same prime of the ring of integers or at the same archimedean place. -/
theorem decompositionSubgroups_le_galRestrictScalarsHom :
    ∀ D' ∈ decompositionSubgroups K Ω, ∃ D ∈ decompositionSubgroups k Ω,
      ∀ x ∈ D', galRestrictScalarsHom k K Ω x ∈ D := by
  rintro D' (⟨P, hPp, hPbot, rfl⟩ | ⟨w, rfl⟩)
  · refine ⟨stabilizer Gal(Ω/k) P, Or.inl ⟨P, hPp, hPbot, rfl⟩, fun x hx => ?_⟩
    rw [mem_stabilizer_iff] at hx ⊢
    exact hx
  · refine ⟨stabilizer Gal(Ω/k) w, Or.inr ⟨w, rfl⟩, fun x hx => ?_⟩
    rw [mem_stabilizer_iff] at hx ⊢
    exact hx

end Tower

/-! ### Local triviality over an intermediate field -/

section Sha

variable {k K Ω : Type*} [Field k] [Field K] [Field Ω] [Algebra k K] [Algebra K Ω] [Algebra k Ω]
  [IsScalarTower k K Ω] [Algebra.IsIntegral k Ω]
variable {M : Type*} [CommGroup M] [MulDistribMulAction Gal(Ω/k) M]
  [MulDistribMulAction Gal(Ω/K) M]
variable (hπ : ∀ (g : Gal(Ω/K)) (m : M), g • m = galRestrictScalarsHom k K Ω g • m)

include hπ

/-- **An everywhere locally trivial class of the first cohomology over the base restricts to an
everywhere locally trivial class over an intermediate field.** -/
theorem comapH1_mem_sha1_decompositionSubgroups (z : SmoothH1 Gal(Ω/k) M)
    (hz : z ∈ sha1 M (decompositionSubgroups k Ω)) :
    comapH1 (galRestrictScalarsHom k K Ω) hπ (isSmoothHom_galRestrictScalarsHom k K Ω) z
      ∈ sha1 M (decompositionSubgroups K Ω) :=
  comapH1_mem_sha1 hπ _ (continuous_galRestrictScalarsHom k K Ω)
    (decompositionSubgroups_le_galRestrictScalarsHom k K Ω) hz

/-- **An everywhere locally trivial class of the second cohomology over the base restricts to an
everywhere locally trivial class over an intermediate field.** -/
theorem comapH2_mem_sha2_decompositionSubgroups (z : SmoothH2 Gal(Ω/k) M)
    (hz : z ∈ sha2 M (decompositionSubgroups k Ω)) :
    comapH2 (galRestrictScalarsHom k K Ω) hπ (isSmoothHom_galRestrictScalarsHom k K Ω) z
      ∈ sha2 M (decompositionSubgroups K Ω) :=
  comapH2_mem_sha2 hπ _ (continuous_galRestrictScalarsHom k K Ω)
    (decompositionSubgroups_le_galRestrictScalarsHom k K Ω) hz

end Sha

/-! ### The restricted class is trivial over a field with the roots of unity -/

section Trivial

variable {k K Ω : Type} [Field k] [Field K] [NumberField K] [Field Ω] [Algebra k K] [Algebra K Ω]
  [Algebra k Ω] [IsScalarTower k K Ω] [IsAlgClosure K Ω] [Algebra.IsIntegral k Ω]
variable {M : Type*} [CommGroup M] [MulDistribMulAction Gal(Ω/k) M]
  [MulDistribMulAction Gal(Ω/K) M]

/-- **An everywhere locally trivial class of the second cohomology with roots of unity coefficients
dies on the Galois group over an intermediate field containing a primitive root of unity.**  The
decomposition subgroups over the intermediate field sit inside those over the base, so the
restricted class is again everywhere locally trivial, and over a number field with the roots of
unity the everywhere locally trivial classes vanish. -/
theorem eq_one_of_mem_sha2_of_isPrimitiveRoot_intermediate
    (hπ : ∀ (g : Gal(Ω/K)) (m : M), g • m = galRestrictScalarsHom k K Ω g • m)
    {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (htriv : ∀ (g : Gal(Ω/K)) (m : M), g • m = m)
    {ι : M →* Kˣ} (hιinj : Function.Injective ι) (hιpow : ∀ m : M, ι m ^ n = 1)
    (hιsurj : ∀ y : Kˣ, y ^ n = 1 → ∃ m : M, ι m = y)
    (z : SmoothH2 Gal(Ω/k) M) (hz : z ∈ sha2 M (decompositionSubgroups k Ω)) :
    comapH2 (galRestrictScalarsHom k K Ω) hπ (isSmoothHom_galRestrictScalarsHom k K Ω) z = 1 :=
  eq_one_of_mem_sha2 hζ htriv hιinj hιpow hιsurj _
    (comapH2_mem_sha2_decompositionSubgroups hπ z hz)

end Trivial

/-! ### The restricted class is trivial for a module split by the intermediate field -/

section Split

variable {k K Ω : Type} [Field k] [Field K] [NumberField K] [Field Ω] [Algebra k K] [Algebra K Ω]
  [Algebra k Ω] [IsScalarTower k K Ω] [IsAlgClosure K Ω] [Algebra.IsIntegral k Ω]
variable {M : Type*} [CommGroup M] [MulDistribMulAction Gal(Ω/K) M]
variable {E : Type*} [CommGroup E] [MulDistribMulAction Gal(Ω/k) E]
  [MulDistribMulAction Gal(Ω/K) E]

/-- **An everywhere locally trivial class of the second cohomology with coefficients in a module
split by an intermediate field with enough roots of unity dies on the Galois group over that
field.**  The coefficients are a finite product of copies of the roots of unity, so the class is a
family of classes with roots of unity coefficients, each of them again everywhere locally trivial
and hence trivial over the intermediate field; and a class of the second cohomology of a finite
product dying in every factor is trivial. -/
theorem eq_one_of_mem_sha2_of_mulEquivPi_intermediate
    (hπ : ∀ (g : Gal(Ω/K)) (e : E), g • e = galRestrictScalarsHom k K Ω g • e)
    {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (htrivE : ∀ (g : Gal(Ω/K)) (e : E), g • e = e)
    (htrivM : ∀ (g : Gal(Ω/K)) (m : M), g • m = m)
    {J : Type*} [Fintype J] (α : E ≃* (J → M))
    {ι : M →* Kˣ} (hιinj : Function.Injective ι) (hιpow : ∀ m : M, ι m ^ n = 1)
    (hιsurj : ∀ y : Kˣ, y ^ n = 1 → ∃ m : M, ι m = y)
    (z : SmoothH2 Gal(Ω/k) E) (hz : z ∈ sha2 E (decompositionSubgroups k Ω)) :
    comapH2 (galRestrictScalarsHom k K Ω) hπ (isSmoothHom_galRestrictScalarsHom k K Ω) z = 1 := by
  set w := comapH2 (galRestrictScalarsHom k K Ω) hπ (isSmoothHom_galRestrictScalarsHom k K Ω) z
  have hw : w ∈ sha2 E (decompositionSubgroups K Ω) :=
    comapH2_mem_sha2_decompositionSubgroups hπ z hz
  have hα : ∀ (g : Gal(Ω/K)) (e : E), α (g • e) = g • α e := fun g e => by
    rw [htrivE]
    exact (funext fun j => htrivM g ((α e) j)).symm
  refine (MulEquiv.map_eq_one_iff (coeffH2Equiv α hα)).1 ?_
  refine (injective_iff_map_eq_one _).1 smoothH2PiHom_injective _ (funext fun j => ?_)
  have hcomp : ∀ (g : Gal(Ω/K)) (e : E),
      ((Pi.evalMonoidHom (fun _ : J => M) j).comp (α : E →* (J → M))) (g • e)
        = g • ((Pi.evalMonoidHom (fun _ : J => M) j).comp (α : E →* (J → M))) e := fun g e => by
    rw [htrivE, htrivM]
  rw [show smoothH2PiHom Gal(Ω/K) (fun _ : J => M) (coeffH2Equiv α hα w) j
        = coeffH2 (Pi.evalMonoidHom (fun _ : J => M) j) (fun _ _ => rfl)
            (coeffH2 (α : E →* (J → M)) hα w) from rfl,
    coeffH2_comp (α : E →* (J → M)) hα (Pi.evalMonoidHom (fun _ : J => M) j)
      (fun _ _ => rfl) hcomp w]
  exact eq_one_of_mem_sha2 hζ htrivM hιinj hιpow hιsurj _ (coeffH2_mem_sha2 _ hcomp hw)

end Split

end InverseGalois.CFT
