/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.FirstInequality
import InverseGalois.CFT.Units.IdeleClassFixed
import InverseGalois.CFT.Units.IdeleNorm

/-!
# The zeroth Tate group of the idele class group as a norm index

For a cyclic extension of number fields the zeroth Tate group of the idele class group is the
quotient of the ideles of the base field by the subgroup generated by the principal ideles and the
norms.  This is the identification that turns the first inequality into its classical form, a lower
bound for the index `(I_K : K^× · Nm I_L)`.

The map is the obvious one: an idele of the base field gives an idele of the extension, whose class
is fixed, and so a class in the Tate group.  It is surjective because a fixed idele class is the
class of a fixed idele and a fixed idele comes from the base field.  Its kernel is computed by
unwinding what it means for the class of an idele of the base field to be a norm in the idele class
group: the difference between the idele and a norm is a principal idele of the extension which is
fixed by the Galois group, hence a principal idele of the base field.

That last step is the remaining half of the identification of the fixed points: a unit of the
extension fixed by the Galois group is a unit of the base field, because the fixed field is the base
field.

## Main definitions

* `InverseGalois.CFT.toTateH0`: the map from the ideles of the base field to the zeroth Tate group
  of the idele class group.

## Main results

* `InverseGalois.CFT.mem_range_globalUnitsComap_iff`: the units of the extension fixed by the
  Galois group are the units of the base field.
* `InverseGalois.CFT.ideleQuotEquivTateH0`: **the zeroth Tate group of the idele class group is the
  quotient of the ideles of the base field by the principal ideles and the norms.**
* `InverseGalois.CFT.first_inequality_index`: **the first inequality**, as a lower bound for the
  index of the principal ideles together with the norms.

## Tags

number field, idele class group, norm index, first inequality, Tate cohomology
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

section IdeleClassIndex

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K]

/-! ### The units fixed by the Galois group -/

/-- **The units of the extension fixed by the Galois group are the units of the base field**, the
fixed field of the whole Galois group being the base field. -/
theorem mem_range_globalUnitsComap_iff (u : Additive Kˣ) :
    u ∈ (globalUnitsComap k K).range ↔ ∀ τ : Gal(K/k), globalUnitsAut τ u = u := by
  refine ⟨?_, fun h => ?_⟩
  · rintro ⟨c, rfl⟩ τ
    refine Additive.toMul.injective (Units.ext ?_)
    rw [coe_globalUnitsAut_apply, coe_globalUnitsComap]
    exact τ.commutes _
  · have hfix : ∀ τ : Gal(K/k), τ ((Additive.toMul u : Kˣ) : K) = ((Additive.toMul u : Kˣ) : K) :=
      fun τ => by rw [← coe_globalUnitsAut_apply, h τ]
    obtain ⟨y, hy⟩ := (IsGalois.mem_range_algebraMap_iff_fixed
      ((Additive.toMul u : Kˣ) : K)).mpr hfix
    have hy0 : y ≠ 0 := by
      rintro rfl
      exact (Additive.toMul u : Kˣ).ne_zero (by rw [← hy, map_zero])
    refine ⟨Additive.ofMul (Units.mk0 y hy0), Additive.toMul.injective (Units.ext ?_)⟩
    rw [coe_globalUnitsComap]
    exact hy

/-- **A principal idele of the extension comes from the base field exactly when its unit does.** -/
theorem mem_range_ideleComap_ideleDiag_iff (u : Additive Kˣ) :
    ideleDiag K u ∈ (ideleComap k K).range ↔ u ∈ (globalUnitsComap k K).range := by
  rw [mem_range_ideleComap_iff, mem_range_globalUnitsComap_iff]
  refine forall_congr' fun τ => ?_
  rw [ideleAut_ideleDiag]
  exact ⟨fun h => ideleDiag_injective K h, fun h => congrArg (ideleDiag K) h⟩

/-! ### The map to the Tate group -/

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 1000000

variable {σ : Gal(K/k)} {n : ℕ}

/-- The class of an idele coming from the base field is fixed by the Galois group. -/
theorem ideleClassAut_mk_ideleComap (τ : Gal(K/k)) (b : ↥(idele k)) :
    ideleClassAut (k := k) τ
        ((ideleComap k K b : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range)
      = ((ideleComap k K b : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range) := by
  rw [ideleClassAut_mk, ideleAut_ideleComap]

variable (σ n) in
/-- **The map from the ideles of the base field to the zeroth Tate group of the idele class
group.** -/
noncomputable def toTateH0 : ↥(idele k) →+ tateH0 (ideleClassAut (k := k) σ) n :=
  (QuotientAddGroup.mk' _).comp
    (AddMonoidHom.codRestrict
      ((QuotientAddGroup.mk' ((ideleDiag K).range)).comp (ideleComap k K))
      (sigmaSubOne (ideleClassAut (k := k) σ)).ker
      fun b => (mem_ker_sigmaSubOne_iff _ _).mpr (ideleClassAut_mk_ideleComap σ b))

variable (σ n) in
@[simp]
theorem toTateH0_apply (b : ↥(idele k)) :
    toTateH0 (k := k) (K := K) σ n b
      = tateH0.mk (ideleClassAut (k := k) σ) n
          ((ideleComap k K b : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range)
          (ideleClassAut_mk_ideleComap σ b) := rfl

omit [NumberField k] [IsGalois k K] in
/-- The class of an idele of the extension is the norm of the class of the norm. -/
theorem mk_normHom_ideleAut (d : ↥(idele K)) :
    ((normHom (ideleAut (k := k) σ) n d : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range)
      = normHom (ideleClassAut (k := k) σ) n
          ((d : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range) :=
  map_normHom (σA := ideleAut (k := k) σ) (σB := ideleClassAut (k := k) σ)
    (QuotientAddGroup.mk' ((ideleDiag K).range)) (fun _ => rfl) n d

/-! ### The kernel and the image -/

variable (hgen : ∀ g : Gal(K/k), g ∈ Subgroup.zpowers σ) (hσ : σ ^ n = 1)

include hgen hσ

/-- **The ideles of the base field killed by the map to the Tate group are exactly the principal
ideles together with the norms.** -/
theorem mem_ker_toTateH0_iff (b : ↥(idele k)) :
    b ∈ (toTateH0 (k := k) (K := K) σ n).ker ↔
      b ∈ (ideleDiag k).range ⊔ (ideleNorm k K hgen hσ).range := by
  rw [AddMonoidHom.mem_ker, toTateH0_apply, tateH0.mk_eq_zero_iff, AddSubgroup.mem_sup]
  refine ⟨?_, ?_⟩
  · rintro ⟨y, hy⟩
    obtain ⟨d, rfl⟩ := QuotientAddGroup.mk_surjective y
    have hd : ((ideleComap k K (ideleNorm k K hgen hσ d) : ↥(idele K)) :
          ↥(idele K) ⧸ (ideleDiag K).range)
        = ((ideleComap k K b : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range) := by
      rw [ideleComap_ideleNorm, mk_normHom_ideleAut, hy]
    obtain ⟨u, hu⟩ := AddMonoidHom.mem_range.mp
      (QuotientAddGroup.eq_iff_sub_mem.mp hd.symm)
    have hcomap : ideleComap k K (b - ideleNorm k K hgen hσ d) = ideleDiag K u := by
      rw [map_sub, hu]
    obtain ⟨c, rfl⟩ := (mem_range_ideleComap_ideleDiag_iff u).mp ⟨_, hcomap⟩
    have hb : b - ideleNorm k K hgen hσ d = ideleDiag k c :=
      ideleComap_injective k K (by rw [hcomap, ideleComap_ideleDiag])
    exact ⟨ideleDiag k c, ⟨c, rfl⟩, ideleNorm k K hgen hσ d, ⟨d, rfl⟩, by rw [← hb]; abel⟩
  · rintro ⟨-, ⟨c, rfl⟩, -, ⟨d, rfl⟩, rfl⟩
    refine ⟨((d : ↥(idele K)) : ↥(idele K) ⧸ (ideleDiag K).range), ?_⟩
    rw [← mk_normHom_ideleAut, map_add, ideleComap_ideleDiag, ideleComap_ideleNorm,
      QuotientAddGroup.mk_add, (QuotientAddGroup.eq_zero_iff _).mpr
        (AddMonoidHom.mem_range.mpr ⟨globalUnitsComap k K c, rfl⟩)]
    exact (zero_add ((normHom (ideleAut (k := k) σ) n d : ↥(idele K)) :
      ↥(idele K) ⧸ (ideleDiag K).range)).symm

variable (hn : Nat.card Gal(K/k) = n)

include hn

/-- **Every class in the zeroth Tate group of the idele class group comes from an idele of the base
field**, a fixed class being the class of a fixed idele. -/
theorem toTateH0_surjective : Function.Surjective (toTateH0 (k := k) (K := K) σ n) := by
  intro c
  obtain ⟨x, hx, rfl⟩ := tateH0.mk_surjective c
  obtain ⟨a, ha, rfl⟩ := exists_fixed_ideleClass hgen hn hσ hx
  obtain ⟨b, rfl⟩ := (mem_range_ideleComap_iff_of_zpowers k K hgen a).mpr ha
  exact ⟨b, rfl⟩

/-- **The zeroth Tate group of the idele class group of a cyclic extension is the quotient of the
ideles of the base field by the principal ideles together with the norms.** -/
noncomputable def ideleQuotEquivTateH0 :
    (↥(idele k) ⧸ ((ideleDiag k).range ⊔ (ideleNorm k K hgen hσ).range))
      ≃+ tateH0 (ideleClassAut (k := k) σ) n :=
  (QuotientAddGroup.quotientAddEquivOfEq
    (AddSubgroup.ext fun b => (mem_ker_toTateH0_iff hgen hσ b).symm)).trans
      (QuotientAddGroup.quotientKerEquivOfSurjective _ (toTateH0_surjective hgen hσ hn))

/-- **The order of the zeroth Tate group of the idele class group is the index of the principal
ideles together with the norms.** -/
theorem card_tateH0_ideleClassAut :
    Nat.card (tateH0 (ideleClassAut (k := k) σ) n)
      = ((ideleDiag k).range ⊔ (ideleNorm k K hgen hσ).range).index :=
  ((AddSubgroup.index_eq_card _).trans
    (Nat.card_congr (ideleQuotEquivTateH0 hgen hσ hn).toEquiv)).symm

variable [NeZero n]

/-- **The first inequality**: the index of the principal ideles together with the norms of a cyclic
extension is at least the degree. -/
theorem first_inequality_index :
    n ≤ ((ideleDiag k).range ⊔ (ideleNorm k K hgen hσ).range).index :=
  (card_tateH0_ideleClassAut hgen hσ hn) ▸ first_inequality σ hn hgen

end IdeleClassIndex

end InverseGalois.CFT
