/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.FrobeniusPlace
import InverseGalois.CFT.Units.PlaceRestrict

/-!
# Only finitely many places ramify

An automorphism of a number field which is not the identity displaces some integer, and the
displacements it produces generate a nonzero ideal; a place at which the automorphism is trivial on
the residues is a place whose prime contains that ideal, so it divides it, and only finitely many
primes divide a nonzero ideal.  The Galois group being finite, only finitely many places have any
nontrivial inertia at all, which is to say that only finitely many places ramify.

The same displacement argument, read over a level of an arbitrary Galois extension, says where the
inertia of the big group goes.  Restriction to the level carries inertia at a prime to inertia at
the prime below it, because restriction commutes with the inclusion of the integers; so at a prime
whose place in the level is unramified over the base field the inertia of the big group already
fixes the level.

## Main definitions

* `InverseGalois.CFT.displacementIdeal`: the ideal generated by the displacements of an
  automorphism on the integers.

## Main results

* `InverseGalois.CFT.finite_setOf_inertia_ne_bot`: only finitely many places of a number field
  carry nontrivial inertia over a base field.
* `InverseGalois.CFT.mem_inertia_restrictNormalHom`: restriction to a level carries inertia to
  inertia.
* `InverseGalois.CFT.inertia_le_fixingSubgroup_of_isUnramifiedAt`: inertia at a prime whose place
  in a level is unramified over the base field fixes that level.

## Tags

class field theory, inertia, ramification, place, number field
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

/-! ### The displacement ideal of an automorphism -/

section Displacement

variable {k K : Type*} [Field k] [Field K] [NumberField K] [Algebra k K]

/-- The ideal generated by the displacements of an automorphism on the integers. -/
def displacementIdeal (σ : Gal(K/k)) : Ideal (𝓞 K) :=
  Ideal.span (Set.range fun y : 𝓞 K => σ • y - y)

/-- **The displacement ideal of a nontrivial automorphism is nonzero.**  An automorphism trivial on
the integers is trivial on the field they are the integers of. -/
theorem displacementIdeal_ne_bot {σ : Gal(K/k)} (hσ : σ ≠ 1) : displacementIdeal σ ≠ ⊥ := by
  intro h
  refine hσ (AlgEquiv.ext fun x => ?_)
  have hy : ∀ y : 𝓞 K, σ (y : K) = (y : K) := by
    intro y
    have hmem : σ • y - y ∈ displacementIdeal (k := k) σ := Ideal.subset_span ⟨y, rfl⟩
    rw [h, Ideal.mem_bot, sub_eq_zero] at hmem
    exact congrArg (fun z : 𝓞 K => (z : K)) hmem
  have hext : (σ.toRingEquiv : K →+* K) = RingHom.id K :=
    IsFractionRing.ringHom_ext (A := 𝓞 K) fun y => by
      simpa [← RingOfIntegers.coe_eq_algebraMap] using hy y
  exact congrArg (fun f : K →+* K => f x) hext

variable [FiniteDimensional k K]

/-- **Only finitely many places of a number field carry nontrivial inertia over a base field.**  A
place with nontrivial inertia is a place whose prime divides the displacement ideal of one of the
finitely many nontrivial automorphisms. -/
theorem finite_setOf_inertia_ne_bot :
    {v : HeightOneSpectrum (𝓞 K) | Ideal.inertia Gal(K/k) v.asIdeal ≠ ⊥}.Finite := by
  classical
  refine Set.Finite.subset (Set.finite_iUnion fun σ : {σ : Gal(K/k) // σ ≠ 1} =>
    Ideal.finite_factors (displacementIdeal_ne_bot σ.2)) ?_
  intro v hv
  haveI := (Subgroup.nontrivial_iff_ne_bot (Ideal.inertia Gal(K/k) v.asIdeal)).2 hv
  obtain ⟨σ, hσ1⟩ := exists_ne (1 : ↥(Ideal.inertia Gal(K/k) v.asIdeal))
  refine Set.mem_iUnion.2 ⟨⟨(σ : Gal(K/k)), fun hc => hσ1 (Subtype.ext hc)⟩, ?_⟩
  refine Ideal.dvd_iff_le.2 (Ideal.span_le.2 ?_)
  rintro _ ⟨y, rfl⟩
  exact AddSubgroup.mem_inertia.1 σ.2 y

end Displacement

/-! ### Inertia over a level -/

section Level

variable {k Ω : Type*} [Field k] [NumberField k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  (K : IntermediateField k Ω) [NumberField ↥K] [IsGalois k ↥K]

omit [NumberField k] [NumberField ↥K] [IsGalois k Ω] in
/-- **Restriction to a level carries inertia to inertia.** -/
theorem mem_inertia_restrictNormalHom {P : Ideal (𝓞 Ω)} {σ : Gal(Ω/k)}
    (hσ : σ ∈ Ideal.inertia Gal(Ω/k) P) :
    AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥K σ
      ∈ Ideal.inertia Gal(↥K/k) (Ideal.under (𝓞 ↥K) P) := by
  refine AddSubgroup.mem_inertia.2 fun y => ?_
  have hmem : algebraMap (𝓞 ↥K) (𝓞 Ω)
      (AlgEquiv.restrictNormalHom (F := k) (K₁ := Ω) ↥K σ • y - y) ∈ P := by
    rw [map_sub, algebraMap_smul_ringOfIntegers ↥K]
    exact AddSubgroup.mem_inertia.1 hσ _
  exact hmem

omit [IsGalois k Ω] in
/-- **Inertia at a prime whose place in a level is unramified over the base field fixes that
level.** -/
theorem inertia_le_fixingSubgroup_of_isUnramifiedAt {P : Ideal (𝓞 Ω)} [P.IsPrime] (hP : P ≠ ⊥)
    (hunr : Algebra.IsUnramifiedAt (𝓞 k) (Ideal.under (𝓞 ↥K) P)) :
    Ideal.inertia Gal(Ω/k) P ≤ K.fixingSubgroup := by
  intro σ hσ
  haveI : (Ideal.under (𝓞 ↥K) P).IsPrime := Ideal.IsPrime.under _ P
  have hbot := (inertia_eq_bot_iff_isUnramifiedAt_base (k := k) (K := ↥K)
    (Ideal.under (𝓞 ↥K) P) (Ideal.under_ne_bot _ hP)).2 hunr
  rw [← IntermediateField.restrictNormalHom_ker, MonoidHom.mem_ker]
  exact (Subgroup.eq_bot_iff_forall _).1 hbot _ (mem_inertia_restrictNormalHom K hσ)

end Level

end InverseGalois.CFT
