/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.InfiniteFamily
import InverseGalois.CFT.Local.UnitValuation
import InverseGalois.CFT.Units.InfiniteComap

/-!
# The completion at an infinite place as a Galois extension of the completion below

Let `K / k` be a Galois extension of number fields and let `w` be an infinite place of `K`, lying
over the place `v` of `k`.  This file shows that the completion of `K` at `w` is a Galois extension
of the completion of `k` at `v`, and that its Galois group is the decomposition group at `w`.  The
elements of the completion of `K` at `w` fixed by the decomposition group are therefore exactly
those coming from the completion of `k` at `v`, and the same holds for the unit groups.

The extension is a splitting field: `K` is the splitting field of a separable polynomial over `k`,
and the same polynomial splits in the completion, whose subalgebra generated by the roots is closed
and contains a dense set, hence is everything.  The decomposition group exhausts the Galois group
because an automorphism of the completion over the completion of the base is an isometry: it is a
bounded linear map of a finite dimensional space, and applying the bound to the powers of an
element forces the constant to disappear.  An isometry of the completion preserves the absolute
value of the place, so it restricts to an automorphism of `K` fixing `w`.

## Main definitions

* `InverseGalois.CFT.restrictToBaseInfinite`: the automorphism of the extension underlying an
  automorphism of the completion.
* `InverseGalois.CFT.infiniteUnitsComap`: **the units of the completion of the base field, viewed
  in the completion at a place above.**

## Main results

* `InverseGalois.CFT.norm_algEquivInfinite`: **an automorphism of the completion over the
  completion of the base is an isometry.**
* `InverseGalois.CFT.isGalois_infiniteCompletion`: **the completion at an infinite place is a
  Galois extension of the completion at the place below.**
* `InverseGalois.CFT.infiniteCompletionAut_restrictToBaseInfinite`: every automorphism of the
  completion comes from the decomposition group.
* `InverseGalois.CFT.mem_range_algebraMap_iff_forall_stabilizer_smul_eq_infinite`: **the elements
  of the completion fixed by the decomposition group are those coming from the completion of the
  base.**
* `InverseGalois.CFT.mem_range_infiniteUnitsComap_iff`: **the units of the completion fixed by the
  decomposition group are those coming from the completion of the base.**

## Tags

number field, infinite place, completion, decomposition group, Galois extension
-/

namespace InverseGalois.CFT

open Module MulAction NumberField NumberField.InfinitePlace Polynomial

/-! ### The completion of the extension is generated by the extension -/

section Adjoin

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  (w : InfinitePlace K)

variable (k) in
/-- **A subalgebra of the completion containing the extension is everything**: it is finite
dimensional over the completion of the base, hence closed, and the extension is dense. -/
theorem subalgebra_eq_top_of_forall_mem_infinite
    (S : Subalgebra (w.comap (algebraMap k K)).Completion w.Completion)
    (h : ∀ x : K, algebraMap K w.Completion x ∈ S) : S = ⊤ := by
  have hclosed : IsClosed (S : Set w.Completion) := by
    have := (Subalgebra.toSubmodule S).closed_of_finiteDimensional
    rwa [Subalgebra.coe_toSubmodule] at this
  have huniv : (S : Set w.Completion) = Set.univ := by
    rw [← hclosed.closure_eq]
    refine (Dense.mono ?_ (denseRange_algebraMap_infiniteCompletion w)).closure_eq
    rintro _ ⟨x, rfl⟩
    exact h x
  refine eq_top_iff.mpr fun x _ => ?_
  have hx : x ∈ (S : Set w.Completion) := huniv ▸ Set.mem_univ x
  exact hx

variable (k) in
/-- **A generating set of the extension generates the completion** over the completion of the
base. -/
theorem adjoin_image_eq_top_infinite {s : Set K} (hs : Algebra.adjoin k s = ⊤) :
    Algebra.adjoin (w.comap (algebraMap k K)).Completion (algebraMap K w.Completion '' s) = ⊤ := by
  refine subalgebra_eq_top_of_forall_mem_infinite k w _ fun x => ?_
  have hx : x ∈ Algebra.adjoin k s := hs ▸ Algebra.mem_top
  induction hx using Algebra.adjoin_induction with
  | mem y hy => exact Algebra.subset_adjoin ⟨y, hy, rfl⟩
  | algebraMap c =>
    have hc : algebraMap K w.Completion (algebraMap k K c)
        = algebraMap (w.comap (algebraMap k K)).Completion w.Completion
          (algebraMap k (w.comap (algebraMap k K)).Completion c) := by
      rw [← IsScalarTower.algebraMap_apply, ← IsScalarTower.algebraMap_apply]
    rw [hc]
    exact Subalgebra.algebraMap_mem _ _
  | add a b _ _ ha hb => simpa only [map_add] using Subalgebra.add_mem _ ha hb
  | mul a b _ _ ha hb => simpa only [map_mul] using Subalgebra.mul_mem _ ha hb

end Adjoin

/-! ### The completion is a Galois extension of the completion below -/

section Galois

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  (w : InfinitePlace K)

variable (k) in
/-- **A polynomial splitting the extension splits the completion** over the completion of the
base. -/
theorem isSplittingField_map_infiniteCompletion {p : k[X]} (hp : p.IsSplittingField k K) :
    (p.map (algebraMap k (w.comap (algebraMap k K)).Completion)).IsSplittingField
      (w.comap (algebraMap k K)).Completion w.Completion := by
  constructor
  · rw [Polynomial.map_map, ← IsScalarTower.algebraMap_eq]
    exact hp.splits'.of_isScalarTower w.Completion
  · refine top_le_iff.mp ?_
    rw [← adjoin_image_eq_top_infinite k w hp.adjoin_rootSet']
    refine Algebra.adjoin_mono ?_
    rintro _ ⟨r, hr, rfl⟩
    rw [Polynomial.mem_rootSet'] at hr ⊢
    have hp0 : p ≠ 0 := fun h => hr.1 (by rw [h, Polynomial.map_zero])
    refine ⟨?_, ?_⟩
    · rw [Polynomial.map_map, ← IsScalarTower.algebraMap_eq]
      exact (Polynomial.map_ne_zero_iff
        (FaithfulSMul.algebraMap_injective k w.Completion)).mpr hp0
    · rw [Polynomial.aeval_map_algebraMap,
        show algebraMap K w.Completion r = IsScalarTower.toAlgHom k K w.Completion r from rfl,
        Polynomial.aeval_algHom_apply, hr.2, map_zero]

variable (k) in
/-- **The completion at an infinite place is a Galois extension of the completion at the place
below.** -/
theorem isGalois_infiniteCompletion [IsGalois k K] :
    IsGalois (w.comap (algebraMap k K)).Completion w.Completion := by
  obtain ⟨p, hsep, hsplit⟩ := IsGalois.is_separable_splitting_field k K
  haveI := isSplittingField_map_infiniteCompletion k w hsplit
  have hsep' : (p.map (algebraMap k (w.comap (algebraMap k K)).Completion)).Separable := hsep.map
  exact IsGalois.of_separable_splitting_field hsep'

end Galois

/-! ### An automorphism of the completion is an isometry -/

section Isometry

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  (w : InfinitePlace K)

variable (k) in
/-- An automorphism of the completion over the completion of the base is continuous, the completion
being a finite extension. -/
theorem continuous_algEquivInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion) : Continuous τ :=
  τ.toLinearMap.continuous_of_finiteDimensional

variable (k) in
/-- **An automorphism of the completion over the completion of the base does not increase the
metric.**  It is a bounded linear map of a finite dimensional space, so the norm of its value at an
element is at most a constant times the norm of the element; applying this to the powers of the
element and using that both norms are multiplicative makes the constant disappear. -/
theorem norm_algEquivInfinite_le
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion)
    (z : w.Completion) : ‖τ z‖ ≤ ‖z‖ := by
  set T := LinearMap.toContinuousLinearMap τ.toLinearMap with hT
  have hbound : ∀ y : w.Completion, ‖τ y‖ ≤ ‖T‖ * ‖y‖ := fun y => T.le_opNorm y
  by_contra hlt
  push_neg at hlt
  have hz : z ≠ 0 := by
    rintro rfl
    simp at hlt
  have hzpos : (0 : ℝ) < ‖z‖ := norm_pos_iff.mpr hz
  have hpow : ∀ n : ℕ, (‖τ z‖ / ‖z‖) ^ n ≤ ‖T‖ := by
    intro n
    have h1 : ‖τ z‖ ^ n ≤ ‖T‖ * ‖z‖ ^ n := by
      have h2 := hbound (z ^ n)
      rwa [map_pow, norm_pow, norm_pow] at h2
    rw [div_pow, div_le_iff₀ (by positivity)]
    exact h1
  obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt (‖T‖) ((one_lt_div hzpos).mpr hlt)
  exact absurd (hpow n) (not_le.mpr hn)

variable (k) in
/-- **An automorphism of the completion over the completion of the base is an isometry**: neither
it nor its inverse increases the metric. -/
theorem norm_algEquivInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion)
    (z : w.Completion) : ‖τ z‖ = ‖z‖ := by
  refine le_antisymm (norm_algEquivInfinite_le k w τ z) ?_
  have h := norm_algEquivInfinite_le k w τ.symm (τ z)
  rwa [τ.symm_apply_apply] at h

end Isometry

/-! ### The Galois group is the decomposition group -/

section Decomposition

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K] (w : InfinitePlace K)

variable (k) in
/-- **The automorphism of the extension underlying an automorphism of the completion**: the
extension is normal, so it is carried into itself. -/
noncomputable def restrictToBaseInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion) : Gal(K/k) :=
  AlgEquiv.restrictNormal (τ.restrictScalars k) K

variable (k) in
omit [NumberField k] [NumberField K] in
@[simp]
theorem algebraMap_restrictToBaseInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion) (x : K) :
    algebraMap K w.Completion (restrictToBaseInfinite k w τ x)
      = τ (algebraMap K w.Completion x) :=
  AlgEquiv.restrictNormal_commutes (τ.restrictScalars k) K x

variable (k) in
/-- The restriction of an automorphism of the completion preserves the absolute value of the
place. -/
theorem apply_restrictToBaseInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion) (x : K) :
    w (restrictToBaseInfinite k w τ x) = w x := by
  rw [← norm_algebraMap_infiniteCompletion w, ← norm_algebraMap_infiniteCompletion w,
    algebraMap_restrictToBaseInfinite k w τ, norm_algEquivInfinite k w τ]

variable (k) in
/-- **An automorphism of the completion fixes the place**, so its restriction lies in the
decomposition group. -/
theorem restrictToBaseInfinite_mem_stabilizer
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion) :
    restrictToBaseInfinite k w τ ∈ stabilizer Gal(K/k) w := by
  refine mem_stabilizer_iff.mpr (InfinitePlace.ext _ _ fun x => ?_)
  have h := apply_restrictToBaseInfinite k w τ ((restrictToBaseInfinite k w τ).symm x)
  rw [AlgEquiv.apply_symm_apply] at h
  rw [InfinitePlace.smul_apply]
  exact h.symm

variable (k) in
/-- **Every automorphism of the completion comes from the decomposition group.** -/
theorem infiniteCompletionAut_restrictToBaseInfinite
    (τ : w.Completion ≃ₐ[(w.comap (algebraMap k K)).Completion] w.Completion)
    (z : w.Completion) :
    infiniteCompletionAut w (restrictToBaseInfinite k w τ)
      (mem_stabilizer_iff.mp (restrictToBaseInfinite_mem_stabilizer k w τ)) z = τ z := by
  refine UniformSpace.Completion.induction_on z ?_ ?_
  · exact isClosed_eq (continuous_infiniteCompletionAut w _ _) (continuous_algEquivInfinite k w τ)
  · intro x
    rw [infiniteCompletionAut_coe]
    exact algebraMap_restrictToBaseInfinite k w τ (WithAbs.equiv w.1 x)

variable (k) in
omit [NumberField k] [NumberField K] [IsGalois k K] in
/-- The decomposition group fixes the image of the completion of the base. -/
theorem stabilizer_smul_algebraMap_infinite (σ : ↥(stabilizer Gal(K/k) w))
    (c : (w.comap (algebraMap k K)).Completion) :
    σ • (algebraMap (w.comap (algebraMap k K)).Completion w.Completion c)
      = algebraMap (w.comap (algebraMap k K)).Completion w.Completion c := by
  rw [algebraMap_infiniteCompletion k w]
  refine UniformSpace.Completion.induction_on c ?_ ?_
  · exact isClosed_eq
      ((continuous_infiniteCompletionAut w σ.1 (mem_stabilizer_iff.mp σ.2)).comp
        (continuous_infiniteCompletionComap k w)) (continuous_infiniteCompletionComap k w)
  · intro x
    rw [infiniteCompletionComap_coe, stabilizer_smul_infiniteCompletion_def,
      infiniteCompletionAut_coe]
    have hx : withAbsAut w σ.1 (mem_stabilizer_iff.mp σ.2) (withAbsComap k w x)
        = withAbsComap k w x :=
      σ.1.commutes (WithAbs.equiv (w.comap (algebraMap k K)).1 x)
    rw [hx]

variable (k) in
/-- **The elements of the completion fixed by the decomposition group are exactly those coming from
the completion of the base.** -/
theorem mem_range_algebraMap_iff_forall_stabilizer_smul_eq_infinite (z : w.Completion) :
    (∀ σ : ↥(stabilizer Gal(K/k) w), σ • z = z) ↔
      z ∈ Set.range (algebraMap (w.comap (algebraMap k K)).Completion w.Completion) := by
  haveI := isGalois_infiniteCompletion k w
  refine ⟨fun h => ?_, ?_⟩
  · rw [← IntermediateField.mem_bot]
    refine (IsGalois.mem_bot_iff_fixed z).mpr fun τ => ?_
    have hτ := infiniteCompletionAut_restrictToBaseInfinite k w τ z
    rw [← hτ]
    simpa using h ⟨restrictToBaseInfinite k w τ, restrictToBaseInfinite_mem_stabilizer k w τ⟩
  · rintro ⟨c, rfl⟩ σ
    exact stabilizer_smul_algebraMap_infinite k w σ c

end Decomposition

/-! ### The units of the completion -/

section Units

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  (w : InfinitePlace K)

variable (k) in
/-- **The units of the completion of the base field, viewed in the completion at a place above**,
written additively. -/
noncomputable def infiniteUnitsComap :
    Additive ((w.comap (algebraMap k K)).Completion)ˣ →+ Additive (w.Completion)ˣ :=
  MonoidHom.toAdditive (Units.map
    (algebraMap (w.comap (algebraMap k K)).Completion w.Completion).toMonoidHom)

variable (k) in
omit [NumberField k] [NumberField K] in
@[simp]
theorem coe_infiniteUnitsComap (u : Additive ((w.comap (algebraMap k K)).Completion)ˣ) :
    ((Additive.toMul (infiniteUnitsComap k w u) : (w.Completion)ˣ) : w.Completion)
      = algebraMap (w.comap (algebraMap k K)).Completion w.Completion
        ((Additive.toMul u : ((w.comap (algebraMap k K)).Completion)ˣ) :
          (w.comap (algebraMap k K)).Completion) := rfl

variable (k) in
/-- **The inclusion of the local units of the base field is injective.** -/
theorem infiniteUnitsComap_injective : Function.Injective (infiniteUnitsComap k w) := by
  intro u u' h
  refine Additive.toMul.injective (Units.ext ?_)
  refine FaithfulSMul.algebraMap_injective (w.comap (algebraMap k K)).Completion w.Completion ?_
  rw [← coe_infiniteUnitsComap k w u, ← coe_infiniteUnitsComap k w u', h]

variable (k) in
omit [NumberField k] [NumberField K] in
/-- The decomposition group fixes the local units of the base field. -/
theorem smulUnitsAut_infiniteUnitsComap (σ : ↥(stabilizer Gal(K/k) w))
    (u : Additive ((w.comap (algebraMap k K)).Completion)ˣ) :
    smulUnitsAut σ (infiniteUnitsComap k w u) = infiniteUnitsComap k w u := by
  refine Additive.toMul.injective (Units.ext ?_)
  rw [coe_smulUnitsAut_apply, coe_infiniteUnitsComap]
  exact stabilizer_smul_algebraMap_infinite k w σ _

variable (k) in
/-- **The units of the completion fixed by the decomposition group are exactly those coming from
the completion of the base.** -/
theorem mem_range_infiniteUnitsComap_iff [IsGalois k K] (u : Additive (w.Completion)ˣ) :
    u ∈ (infiniteUnitsComap k w).range ↔
      ∀ σ : ↥(stabilizer Gal(K/k) w), smulUnitsAut σ u = u := by
  refine ⟨?_, fun h => ?_⟩
  · rintro ⟨c, rfl⟩ σ
    exact smulUnitsAut_infiniteUnitsComap k w σ c
  · set x : (w.Completion)ˣ := Additive.toMul u with hx
    have hfix : ∀ σ : ↥(stabilizer Gal(K/k) w), σ • (x : w.Completion) = x := by
      intro σ
      have hσ := congrArg
        (fun a => ((Additive.toMul a : (w.Completion)ˣ) : w.Completion)) (h σ)
      simpa only [coe_smulUnitsAut_apply] using hσ
    obtain ⟨c, hc⟩ :=
      (mem_range_algebraMap_iff_forall_stabilizer_smul_eq_infinite k w
        (x : w.Completion)).mp hfix
    have hc0 : c ≠ 0 := by
      rintro rfl
      exact x.ne_zero (by rw [← hc, map_zero])
    refine ⟨Additive.ofMul (Units.mk0 c hc0), Additive.toMul.injective (Units.ext ?_)⟩
    rw [coe_infiniteUnitsComap]
    exact hc

end Units

end InverseGalois.CFT
