/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Local.AdicHerbrand
import InverseGalois.CFT.Local.AdicUnramified
import InverseGalois.CFT.Local.UnramifiedCoboundary
import InverseGalois.CFT.TateCohomology.CyclicVanishing
import InverseGalois.CFT.Units.FrobeniusPlace
import InverseGalois.CFT.Units.IdeleRep

/-!
# The units of the valuation ring at an unramified place have no complete cohomology

The two Tate groups of the units of the valuation ring of an unramified extension of complete
discretely valued fields vanish: Hilbert's theorem 90 corrected by a uniformizer of the base kills
the lower one, and the Herbrand quotient being one kills the upper one.  Those two statements are
about a single automorphism, and they are exactly the two middle degrees of the complete cohomology
of the decomposition group.

A decomposition group at an unramified place is generated by one element, so periodicity carries
the two middle degrees to every degree.  Read in the category of representations, this says that the
units of the valuation ring of the completion at an unramified place are a representation of the
decomposition group with **no complete cohomology whatsoever** — which is what removes the places
outside a finite set from the description of the cohomology of the ideles.

## Main results

* `InverseGalois.CFT.isZero_tateModule_kerUnitValAutHom`: **the complete cohomology of the units of
  the valuation ring of an unramified extension vanishes in every degree.**
* `InverseGalois.CFT.isZero_tateModule_adicKerUnitVal`: **the same statement for the decomposition
  group at a finite place of a Galois extension of number fields that is unramified there.**

## Tags

unramified extension, local units, Tate cohomology, decomposition group, cyclic group
-/

namespace InverseGalois.CFT

open CategoryTheory IsDedekindDomain MulAction NumberField Tate

open scoped WithZero

noncomputable section

/-! ### The general statement -/

section General

variable {G A : Type} [Group G] [Fintype G] [Field A] [Valued A ℤᵐ⁰] [MulSemiringAction G A]
  [FaithfulSMul G A] [CompleteSpace A] [∀ j : ℤ, Finite (gradedAdd A j)] {p e : ℕ}
  (hv : ∀ (σ : G) (x : A), Valued.v (σ • x) = Valued.v x)

omit [Fintype G] [FaithfulSMul G A] [CompleteSpace A] [∀ j : ℤ, Finite (gradedAdd A j)] in
/-- The powers of an element act on the units of the valuation ring as the powers of the
automorphism it induces. -/
theorem repOfAddAut_kerUnitValAutHom_pow (σ : G) (i : ℕ) (x : ↥(unitVal (A := A)).ker) :
    (repOfAddAut (kerUnitValAutHom hv)).ρ (σ ^ i) x = ((kerUnitValAut hv σ) ^ i) x := by
  rw [repOfAddAut_ρ_apply, map_pow]
  rfl

omit [Fintype G] [FaithfulSMul G A] [CompleteSpace A] [∀ j : ℤ, Finite (gradedAdd A j)] in
/-- The norm operator of a generator computes the sums appearing in the two middle degrees. -/
theorem sum_repOfAddAut_kerUnitValAutHom (σ : G) (d : ℕ) (x : ↥(unitVal (A := A)).ker) :
    ∑ i ∈ Finset.range d, (repOfAddAut (kerUnitValAutHom hv)).ρ (σ ^ i) x
      = normHom (kerUnitValAut hv σ) d x := by
  rw [normHom_apply]
  exact Finset.sum_congr rfl fun i _ => repOfAddAut_kerUnitValAutHom_pow hv σ i x

/-- **The complete cohomology of the units of the valuation ring of an unramified extension
vanishes in every degree.**  Both middle degrees vanish, and the group is generated by one
element, so periodicity reaches every degree from them. -/
theorem isZero_tateModule_kerUnitValAutHom (h : HasResidueChar A p e) {σ : G}
    (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (π : Aˣ) (hπfix : ∀ g : G, g • (π : A) = (π : A))
    (hπval : unitVal (Additive.ofMul π) = 1) (n : ℤ) :
    Limits.IsZero (tateModule (repOfAddAut (kerUnitValAutHom hv)) n) := by
  haveI : NeZero (Nat.card G) := ⟨Nat.card_pos.ne'⟩
  have hσ : σ ^ Nat.card G = 1 := pow_card_eq_one'
  refine isZero_tateModule_of_forall_mem_zpowers _ hgen (d := Nat.card G) rfl ?_ ?_ n
  · intro x hx
    obtain ⟨y, hy⟩ := exists_normHom_kerUnitVal hv h hgen hσ rfl π hπfix hπval x (hx σ)
    exact ⟨y, (sum_repOfAddAut_kerUnitValAutHom hv σ _ y).trans hy⟩
  · intro x hx
    haveI := subsingleton_tateHm1_kerUnitValAut hv hgen (d := Nat.card G) rfl π hπfix hπval
    have hx' : normHom (kerUnitValAut hv σ) (Nat.card G) x = 0 :=
      (sum_repOfAddAut_kerUnitValAutHom hv σ _ x).symm.trans hx
    exact (tateHm1.mk_eq_zero_iff x hx').1 (Subsingleton.elim _ _)

end General

/-! ### An unramified place of a Galois extension of number fields -/

section Adic

variable {k K : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
  [IsGalois k K]

/-- **The complete cohomology of the units of the valuation ring of the completion at an unramified
finite place vanishes in every degree.**  The decomposition group there is generated by a Frobenius
element and fixes a uniformizer of the base. -/
theorem isZero_tateModule_adicKerUnitVal (v : HeightOneSpectrum (𝓞 K))
    (hunr : Algebra.IsUnramifiedAt (𝓞 k) v.asIdeal) (n : ℤ) :
    Limits.IsZero
      (tateModule (repOfAddAut (kerUnitValAutHom (valued_smul_adicCompletion (k := k) v))) n) := by
  haveI : Fintype ↥(stabilizer Gal(K/k) v) := Fintype.ofFinite _
  haveI := isCyclic_stabilizer_of_isUnramifiedAt (k := k) v hunr
  obtain ⟨σ, hgen⟩ := IsCyclic.exists_generator (α := ↥(stabilizer Gal(K/k) v))
  obtain ⟨π, hπfix, hπval⟩ := exists_fixedUniformizer_of_isUnramifiedAt (k := k) v hunr
  obtain ⟨_, _, h⟩ := exists_hasResidueChar_adicCompletion v
  exact isZero_tateModule_kerUnitValAutHom _ h hgen π hπfix hπval n

end Adic

end

end InverseGalois.CFT
