/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.RET.Pi1.Topological.VanKampen.Group

/-!
# Seifert–van Kampen: generation over a path connected overlap

The free-product form of Seifert–van Kampen needs the overlap `U ∩ V` to be simply connected.  The
weaker *generation* statement — that `π₁(X, x)` is generated by the images of `π₁(U, x)` and
`π₁(V, x)` — needs only that the overlap is path connected, and that is what this file proves.

The generation analysis is already available in the groupoid form used for the uniqueness half of
the pushout property: every morphism of `π(X)` is a composite of morphisms coming from `π(U)` and
from `π(V)`.  Phrased as a closure principle for an arbitrary predicate on morphisms
(`prop_of_mk`), it applies verbatim to the predicate "the vertex-group retraction of this morphism
lies in the subgroup generated by the two images".  The retraction is built from a system of
connecting morphisms chosen inside `U ∩ V` whenever possible — the same recipe as in
`VanKampen/Group.lean`, except that the connecting morphism at the basepoint is *defined* to be
the identity rather than shown to be one by simple connectivity.

## Main declarations

* `Rigidity.RET.VanKampen.prop_of_mk` — a predicate on the morphisms of `π(X)` containing the
  identities, closed under composition, and holding on everything coming from `π(U)` and `π(V)`,
  holds on every morphism.
* `Rigidity.RET.VanKampen.closure_range_pi1_union_of_pathConnected` — `π₁(X, x)` is generated by
  the images of `π₁(U, x)` and `π₁(V, x)`, for an open cover with path connected pieces and path
  connected overlap.
-/

universe u v w

open CategoryTheory Set unitInterval FundamentalGroupoid

namespace Rigidity.RET.VanKampen

/-! ### A closure principle for predicates on the morphisms of `π(X)` -/

section Predicate

variable {X : Type u} [TopologicalSpace X]
  (P : ∀ a b : FundamentalGroupoid X, (a ⟶ b) → Prop)
  (hid : ∀ a : FundamentalGroupoid X, P a a (𝟙 a))
  (hcomp : ∀ (a b c : FundamentalGroupoid X) (f : a ⟶ b) (g : b ⟶ c),
    P a b f → P b c g → P a c (f ≫ g))

/-- A predicate stable under the harmless endpoint recast of a morphism. -/
theorem prop_cast {a b a' b' : X} (q : Path.Homotopic.Quotient a' b') (hx : a = a') (hy : b = b')
    (hq : P ⟨a'⟩ ⟨b'⟩ q) :
    P ⟨a⟩ ⟨b⟩ (Path.Homotopic.Quotient.cast q hx hy) := by
  subst hx; subst hy
  have hc : Path.Homotopic.Quotient.cast q rfl rfl = q := by simp
  rw [hc]; exact hq

include hid hcomp in
/-- A predicate containing the identities and stable under composition propagates through a
concatenation of paths. -/
theorem prop_concat {m : ℕ} (p : Fin (m + 1) → X)
    (F : (k : Fin m) → Path (p k.castSucc) (p k.succ))
    (hF : ∀ k, P ⟨p k.castSucc⟩ ⟨p k.succ⟩ ⟦F k⟧) :
    P ⟨p 0⟩ ⟨p (Fin.last m)⟩ ⟦Path.concat p F⟧ := by
  induction m with
  | zero =>
    have h0 : (⟦Path.concat p F⟧ : (⟨p 0⟩ : FundamentalGroupoid X) ⟶ ⟨p (Fin.last 0)⟩)
        = 𝟙 (⟨p 0⟩ : FundamentalGroupoid X) := by rw [Path.concat_zero]; rfl
    rw [h0]
    exact hid _
  | succ m ih =>
    have hsucc : (⟦Path.concat p F⟧ : (⟨p 0⟩ : FundamentalGroupoid X) ⟶ ⟨p (Fin.last (m + 1))⟩)
        = (((⟦Path.concat (p ∘ Fin.castSucc) (fun k => F k.castSucc)⟧ :
              (⟨p 0⟩ : FundamentalGroupoid X) ⟶ ⟨p (Fin.last m).castSucc⟩)
            ≫ (⟦F (Fin.last m)⟧ :
              (⟨p (Fin.last m).castSucc⟩ : FundamentalGroupoid X) ⟶ ⟨p (Fin.last m).succ⟩)) :
            (⟨p 0⟩ : FundamentalGroupoid X) ⟶ ⟨p (Fin.last (m + 1))⟩) := by
      rw [Path.concat_succ]; rfl
    rw [hsucc]
    exact hcomp _ _ _ _ _
      (ih (p ∘ Fin.castSucc) (fun k => F k.castSucc) (fun k => hF k.castSucc))
      (hF (Fin.last m))

include hid hcomp in
/-- **The closure principle.**  A predicate on the morphisms of `π(X)` which contains the
identities, is stable under composition, and holds on every morphism coming from `π(U)` or from
`π(V)`, holds on every morphism of `π(X)`. -/
theorem prop_of_mk (U V : Set X) (hUopen : IsOpen U) (hVopen : IsOpen V) (hUV : U ∪ V = univ)
    (hPU : ∀ (y z : FundamentalGroupoid (U : Set X)) (δ : y ⟶ z),
      P ((FundamentalGroupoid.map (inclUX U)).obj y) ((FundamentalGroupoid.map (inclUX U)).obj z)
        ((FundamentalGroupoid.map (inclUX U)).map δ))
    (hPV : ∀ (y z : FundamentalGroupoid (V : Set X)) (δ : y ⟶ z),
      P ((FundamentalGroupoid.map (inclVX V)).obj y) ((FundamentalGroupoid.map (inclVX V)).obj z)
        ((FundamentalGroupoid.map (inclVX V)).map δ))
    {a b : X} (γ : Path a b) :
    P ⟨a⟩ ⟨b⟩ (⟦γ⟧ : Path.Homotopic.Quotient a b) := by
  obtain ⟨n, t, h0, h1, _, hcov, hgen⟩ :=
    exists_homotopic_concat_cover U V hUopen hVopen hUV γ
  have hpiece : ∀ k : Fin n,
      P ⟨(γ ∘ t) k.castSucc⟩ ⟨(γ ∘ t) k.succ⟩ ⟦γ.subpath (t k.castSucc) (t k.succ)⟧ := by
    intro k
    rcases hcov k with hk | hk
    · obtain ⟨m0, m1, δ, hδ⟩ := mk_subpath_eq_mapUX U γ (t k.castSucc) (t k.succ) hk
      have h := hPU _ _ δ
      rw [hδ] at h
      exact h
    · obtain ⟨m0, m1, δ, hδ⟩ := mk_subpath_eq_mapVX V γ (t k.castSucc) (t k.succ) hk
      have h := hPV _ _ δ
      rw [hδ] at h
      exact h
  have hcc := prop_concat P hid hcomp (γ ∘ t)
    (fun k => γ.subpath (t k.castSucc) (t k.succ)) hpiece
  rw [hgen]
  exact prop_cast P _ _ _ hcc

end Predicate

/-! ### Connecting morphisms without simple connectivity -/

section Conn

variable {X : Type u} [TopologicalSpace X] (U V : Set X) {x : X} (hxU : x ∈ U) (hxV : x ∈ V)
variable [PathConnectedSpace (U ∩ V : Set X)]

open Classical in
/-- A choice of morphism from the basepoint to every object of `π(U ∩ V)`, normalized to be the
identity at the basepoint itself. -/
noncomputable def connW' (y : FundamentalGroupoid (U ∩ V : Set X)) :
    mk (⟨x, ⟨hxU, hxV⟩⟩ : (U ∩ V : Set X)) ⟶ y :=
  if h : mk (⟨x, ⟨hxU, hxV⟩⟩ : (U ∩ V : Set X)) = y then eqToHom h
  else ⟦PathConnectedSpace.somePath _ y.as⟧

theorem connW'_self : connW' U V hxU hxV (mk ⟨x, ⟨hxU, hxV⟩⟩) = 𝟙 _ := by
  rw [connW', dif_pos rfl, eqToHom_refl]

variable [PathConnectedSpace U] [PathConnectedSpace V]

open Classical in
/-- A choice of morphism from the basepoint to every object of `π(U)`, chosen inside `U ∩ V`
whenever possible. -/
noncomputable def connU' (y : FundamentalGroupoid (U : Set X)) :
    mk (⟨x, hxU⟩ : (U : Set X)) ⟶ y :=
  if h : (y.as : X) ∈ V then
    (FundamentalGroupoid.map (inclUW U V)).map
      (connW' U V hxU hxV (mk ⟨(y.as : X), ⟨y.as.2, h⟩⟩))
  else ⟦PathConnectedSpace.somePath _ y.as⟧

open Classical in
/-- A choice of morphism from the basepoint to every object of `π(V)`, chosen inside `U ∩ V`
whenever possible. -/
noncomputable def connV' (y : FundamentalGroupoid (V : Set X)) :
    mk (⟨x, hxV⟩ : (V : Set X)) ⟶ y :=
  if h : (y.as : X) ∈ U then
    (FundamentalGroupoid.map (inclVW U V)).map
      (connW' U V hxU hxV (mk ⟨(y.as : X), ⟨h, y.as.2⟩⟩))
  else ⟦PathConnectedSpace.somePath _ y.as⟧

omit [PathConnectedSpace (V : Set X)] in
theorem connU'_eq (y : FundamentalGroupoid (U : Set X)) (h : (y.as : X) ∈ V) :
    connU' U V hxU hxV y = (FundamentalGroupoid.map (inclUW U V)).map
      (connW' U V hxU hxV (mk ⟨(y.as : X), ⟨y.as.2, h⟩⟩)) := by
  rw [connU', dif_pos h]

omit [PathConnectedSpace (U : Set X)] in
theorem connV'_eq (y : FundamentalGroupoid (V : Set X)) (h : (y.as : X) ∈ U) :
    connV' U V hxU hxV y = (FundamentalGroupoid.map (inclVW U V)).map
      (connW' U V hxU hxV (mk ⟨(y.as : X), ⟨h, y.as.2⟩⟩)) := by
  rw [connV', dif_pos h]

omit [PathConnectedSpace (V : Set X)] in
theorem connU'_self : connU' U V hxU hxV (mk ⟨x, hxU⟩) = 𝟙 _ := by
  rw [connU'_eq U V hxU hxV _ hxV, connW'_self]
  exact (FundamentalGroupoid.map (inclUW U V)).map_id _

omit [PathConnectedSpace (U : Set X)] in
theorem connV'_self : connV' U V hxU hxV (mk ⟨x, hxV⟩) = 𝟙 _ := by
  rw [connV'_eq U V hxU hxV _ hxU, connW'_self]
  exact (FundamentalGroupoid.map (inclVW U V)).map_id _

variable (hUV : U ∪ V = univ)

open Classical in
/-- A choice of morphism from the basepoint to every object of `π(X)`, restricting to `connU'`
on `U` and to `connV'` on `V`. -/
noncomputable def connX' (y : FundamentalGroupoid X) : mk x ⟶ y :=
  if h : y.as ∈ U then
    (FundamentalGroupoid.map (inclUX U)).map (connU' U V hxU hxV (mk ⟨y.as, h⟩))
  else
    (FundamentalGroupoid.map (inclVX V)).map
      (connV' U V hxU hxV (mk ⟨y.as, ((hUV ▸ Set.mem_univ y.as : y.as ∈ U ∪ V)).resolve_left h⟩))

theorem connX'_eq_U (y : FundamentalGroupoid X) (h : y.as ∈ U) :
    connX' U V hxU hxV hUV y
      = (FundamentalGroupoid.map (inclUX U)).map (connU' U V hxU hxV (mk ⟨y.as, h⟩)) := by
  rw [connX', dif_pos h]

theorem connX'_eq_V (y : FundamentalGroupoid X) (h : y.as ∉ U) (h' : y.as ∈ V) :
    connX' U V hxU hxV hUV y
      = (FundamentalGroupoid.map (inclVX V)).map (connV' U V hxU hxV (mk ⟨y.as, h'⟩)) := by
  rw [connX', dif_neg h]

theorem connX'_of_memU (y : FundamentalGroupoid (U : Set X)) :
    connX' U V hxU hxV hUV ((FundamentalGroupoid.map (inclUX U)).obj y)
      = (FundamentalGroupoid.map (inclUX U)).map (connU' U V hxU hxV y) := by
  rw [connX'_eq_U U V hxU hxV hUV ((FundamentalGroupoid.map (inclUX U)).obj y) y.as.2]
  rfl

theorem connX'_of_memV (y : FundamentalGroupoid (V : Set X)) :
    connX' U V hxU hxV hUV ((FundamentalGroupoid.map (inclVX V)).obj y)
      = (FundamentalGroupoid.map (inclVX V)).map (connV' U V hxU hxV y) := by
  by_cases h : (y.as : X) ∈ U
  · rw [connX'_eq_U U V hxU hxV hUV ((FundamentalGroupoid.map (inclVX V)).obj y) h,
      connU'_eq U V hxU hxV _ y.as.2, connV'_eq U V hxU hxV y h]
    simpa using
      CategoryTheory.Functor.congr_hom (mapW_comp_eq U V)
        (connW' U V hxU hxV (mk ⟨(y.as : X), ⟨h, y.as.2⟩⟩))
  · rw [connX'_eq_V U V hxU hxV hUV ((FundamentalGroupoid.map (inclVX V)).obj y) h y.as.2]
    rfl

theorem connX'_self : connX' U V hxU hxV hUV (mk x) = 𝟙 _ := by
  rw [connX'_eq_U U V hxU hxV hUV (mk x) hxU, connU'_self]
  exact (FundamentalGroupoid.map (inclUX U)).map_id _

/-- The retraction of `π(X)` onto `π₁(X, x)` sends a morphism coming from `π(U)` into the image of
`π₁(U, x)`. -/
theorem vertexFunctorX'_map_inclU (y z : FundamentalGroupoid (U : Set X)) (γ : y ⟶ z) :
    (vertexFunctor (mk x) (connX' U V hxU hxV hUV)).map
        ((FundamentalGroupoid.map (inclUX U)).map γ)
      = pi1U U hxU
          ((vertexFunctor (mk (⟨x, hxU⟩ : (U : Set X))) (connU' U V hxU hxV)).map γ) := by
  rw [vertexFunctor_map, connX'_of_memU, connX'_of_memU, pi1U_apply, vertexFunctor_map]
  simp only [Groupoid.inv_eq_inv, CategoryTheory.Functor.map_comp,
    CategoryTheory.Functor.map_inv]

/-- The retraction of `π(X)` onto `π₁(X, x)` sends a morphism coming from `π(V)` into the image of
`π₁(V, x)`. -/
theorem vertexFunctorX'_map_inclV (y z : FundamentalGroupoid (V : Set X)) (γ : y ⟶ z) :
    (vertexFunctor (mk x) (connX' U V hxU hxV hUV)).map
        ((FundamentalGroupoid.map (inclVX V)).map γ)
      = pi1V V hxV
          ((vertexFunctor (mk (⟨x, hxV⟩ : (V : Set X))) (connV' U V hxU hxV)).map γ) := by
  rw [vertexFunctor_map, connX'_of_memV, connX'_of_memV, pi1V_apply, vertexFunctor_map]
  simp only [Groupoid.inv_eq_inv, CategoryTheory.Functor.map_comp,
    CategoryTheory.Functor.map_inv]

include hUV in
/-- **Seifert–van Kampen, generation form.**  For an open cover `X = U ∪ V` by path connected sets
with path connected overlap containing the basepoint, `π₁(X, x)` is generated by the images of
`π₁(U, x)` and `π₁(V, x)`.  No hypothesis is placed on the fundamental group of the overlap. -/
theorem closure_range_pi1_union_of_pathConnected (hUopen : IsOpen U) (hVopen : IsOpen V) :
    Subgroup.closure (Set.range (pi1U U hxU) ∪ Set.range (pi1V V hxV)) = ⊤ := by
  set N : Subgroup (FundamentalGroup X x) :=
    Subgroup.closure (Set.range (pi1U U hxU) ∪ Set.range (pi1V V hxV)) with hN
  set A := vertexFunctor (mk x) (connX' U V hxU hxV hUV) with hA
  set P : ∀ a b : FundamentalGroupoid X, (a ⟶ b) → Prop :=
    fun a b f => ((A.map f : End (mk x)) : FundamentalGroup X x) ∈ N with hP
  have hid : ∀ a : FundamentalGroupoid X, P a a (𝟙 a) := by
    intro a
    show ((A.map (𝟙 a) : End (mk x)) : FundamentalGroup X x) ∈ N
    rw [A.map_id]
    exact one_mem N
  have hcomp : ∀ (a b c : FundamentalGroupoid X) (f : a ⟶ b) (g : b ⟶ c),
      P a b f → P b c g → P a c (f ≫ g) := by
    intro a b c f g hf hg
    show ((A.map (f ≫ g) : End (mk x)) : FundamentalGroup X x) ∈ N
    rw [A.map_comp]
    exact mul_mem hg hf
  have hPU : ∀ (y z : FundamentalGroupoid (U : Set X)) (δ : y ⟶ z),
      P ((FundamentalGroupoid.map (inclUX U)).obj y) ((FundamentalGroupoid.map (inclUX U)).obj z)
        ((FundamentalGroupoid.map (inclUX U)).map δ) := by
    intro y z δ
    show ((A.map ((FundamentalGroupoid.map (inclUX U)).map δ) : End (mk x)) :
      FundamentalGroup X x) ∈ N
    rw [hA, vertexFunctorX'_map_inclU]
    exact Subgroup.subset_closure (Or.inl ⟨_, rfl⟩)
  have hPV : ∀ (y z : FundamentalGroupoid (V : Set X)) (δ : y ⟶ z),
      P ((FundamentalGroupoid.map (inclVX V)).obj y) ((FundamentalGroupoid.map (inclVX V)).obj z)
        ((FundamentalGroupoid.map (inclVX V)).map δ) := by
    intro y z δ
    show ((A.map ((FundamentalGroupoid.map (inclVX V)).map δ) : End (mk x)) :
      FundamentalGroup X x) ∈ N
    rw [hA, vertexFunctorX'_map_inclV]
    exact Subgroup.subset_closure (Or.inr ⟨_, rfl⟩)
  refine eq_top_iff.2 fun α _ => ?_
  have hα : P (mk x) (mk x) (α : mk x ⟶ mk x) := by
    induction (α : Path.Homotopic.Quotient x x) using Quotient.inductionOn with
    | h γ => exact prop_of_mk P hid hcomp U V hUopen hVopen hUV hPU hPV γ
  have hself : A.map (α : mk x ⟶ mk x) = (α : End (mk x)) :=
    vertexFunctor_map_self _ _ (connX'_self U V hxU hxV hUV) _
  rw [hP] at hα
  rw [hself] at hα
  exact hα

end Conn

end Rigidity.RET.VanKampen
