/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.GeomRET
import InverseGalois.Rigidity.RET.BranchLocus
import InverseGalois.Rigidity.RET.BranchSet
import InverseGalois.Rigidity.RET.ExistenceAbelian
import InverseGalois.Rigidity.RET.AbelianBranchPoints

/-!
# The covers correspondence for abelian deck groups

Both directions of the correspondence between covers of the line and generating product-one tuples
hold, for every number of branch points, once the group is abelian.  Realizing a prescribed tuple
is the multi-point Kummer construction; recovering a tuple from a cover is the abelian branch-cycle
theorem.  Packaged together they are the same statement as `Rigidity.RET.GeomRET`, with the finite
groups replaced by the finite abelian ones.

Two further readings of the same correspondence are available.  Which abelian groups occur over a
given branch locus is determined by the number of points alone — `r + 1` points admit exactly the
groups generated by `r` elements.  And a cover whose deck group is abelian need not have its branch
locus prescribed at all: the branch locus is finite, so a tuple of points carrying the branch
cycles can always be produced.

## Main results

* `Rigidity.RET.GeomRETComm` — the two directions of the correspondence, for abelian deck groups.
* `Rigidity.RET.geomRETComm` — they both hold, unconditionally.
* `Rigidity.RET.GeomRET.toGeomRETComm` — the abelian correspondence is a consequence of the general
  one, so it is exactly the abelian part of the Riemann existence theorem for the line.
* `Rigidity.RET.exists_branchPoints_generating_of_comm` — an abelian cover branched over `r + 1`
  points has deck group generated by `r` elements, with no branch locus prescribed in advance.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-- **Covers of the line with abelian deck group and branch locus in `{t₀,…,t_{r-1}}` are the
finite abelian quotients of the sphere group**, in the two directions in which the correspondence
is used.

* `exists_cover`: a tuple `h` in a finite abelian group `H` which generates `H` and has product `1`
  is the monodromy of a cover of the line with deck group `H`, unramified outside the `tᵢ` and
  infinity, in which `hᵢ` generates an inertia group at `tᵢ`.
* `exists_cycles`: conversely, a cover of the line with abelian deck group, unramified outside the
  `tᵢ` and infinity, carries a system of branch cycles over those points.

This is `Rigidity.RET.GeomRET` with the finite groups replaced by the finite abelian ones. -/
structure GeomRETComm {r : ℕ} (t : Fin r → k) : Prop where
  /-- a generating product-one tuple in a finite abelian group is the monodromy of a cover branched
  over the given points. -/
  exists_cover : ∀ {H : Type} [CommGroup H] [Finite H] (h : Fin r → H),
      (List.ofFn h).prod = 1 → Subgroup.closure (Set.range h) = ⊤ →
      ∃ (L : LineCover) (e : L.deck ≃* H),
        L.IsUnramifiedOutside (Set.range t) ∧ L.IsUnramifiedAtInfinity ∧
        ∀ i, L.IsInertiaGenAt (t i) (e.symm (h i))
  /-- a cover with abelian deck group, branched only over the given points and infinity, has a
  system of branch cycles over those points. -/
  exists_cycles : ∀ L : LineCover, (∀ a b : L.deck, a * b = b * a) →
      L.IsUnramifiedOutside (Set.range t) → L.IsUnramifiedAtInfinity →
      ∃ g : Fin r → L.deck, L.IsBranchCycleGenSystem t g

/-- **The covers correspondence holds for abelian deck groups**, over any number of branch points.

The existence direction is the multi-point Kummer construction: an abelian group with a prescribed
product-one generating tuple is realized by adjoining roots of products of the linear forms cutting
out the branch points, with the exponents read off from the tuple.  The converse direction goes
through the same construction in reverse — a cover with abelian deck group is a compositum of
Kummer extensions — so that its inertia generators can be chosen coherently enough for their
ordered product to be trivial.

Neither direction uses the Riemann existence theorem. -/
theorem geomRETComm {r : ℕ} (t : Fin r → k) (ht : Function.Injective t) : GeomRETComm t := by
  refine ⟨fun {_} _ _ h hprod htop => exists_cover_of_commGroup t ht h hprod htop, ?_⟩
  intro L hab hout hinf
  exact exists_branchCycleGenSystem_of_comm L hab t ht hout hinf

/-- **The abelian correspondence is the abelian part of the covers correspondence.**  Restricting
the general statement to abelian groups gives exactly `GeomRETComm`, which is where the two
statements can be compared. -/
theorem GeomRET.toGeomRETComm {r : ℕ} {t : Fin r → k} (h : GeomRET t) : GeomRETComm t where
  exists_cover h' hprod htop := h.exists_cover h' hprod htop
  exists_cycles L _ hout hinf := h.exists_cycles L hout hinf

/-! ### The correspondence without a prescribed branch locus -/

/-- **A cover of the line is unramified outside the range of a nonempty injective tuple of
points.**  The branch locus is finite, and a point outside it may always be adjoined, since the
line has infinitely many points. -/
theorem LineCover.exists_unramifiedOutside_range_succ (L : LineCover) :
    ∃ (r : ℕ) (t : Fin (r + 1) → k),
      Function.Injective t ∧ L.IsUnramifiedOutside (Set.range t) := by
  classical
  obtain ⟨r, t, ht, hout⟩ := L.exists_unramifiedOutside_range
  cases r with
  | succ s => exact ⟨s, t, ht, hout⟩
  | zero =>
    refine ⟨0, fun _ => 0, fun a b _ => by omega,
      hout.mono (by rw [Set.range_eq_empty t]; exact Set.empty_subset _)⟩

/-- **A cover of the line with abelian deck group, unramified at infinity and branched over
`r + 1` points, has deck group generated by `r` elements** — one fewer than the number of branch
points, because the ordered product of the branch cycles is trivial.  The branch locus does not
have to be prescribed here: it is finite, so a tuple of points carrying it exists. -/
theorem exists_branchPoints_generating_of_comm (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ (r : ℕ) (t : Fin (r + 1) → k) (s : Fin r → L.deck), Function.Injective t ∧
      L.IsUnramifiedOutside (Set.range t) ∧ Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨r, t, ht, hout⟩ := L.exists_unramifiedOutside_range_succ
  obtain ⟨g, hg⟩ := exists_branchCycleGenSystem_of_comm L hab t ht hout hinf
  exact ⟨r, t, fun i => g i.castSucc, ht, hout, hg.closure_castSucc_eq_top⟩

/-! ### Prescribing the branch locus exactly -/

/-- **A product-one generating tuple with no trivial entry is realized by a cover branched over
exactly the prescribed points.**  The multi-point Kummer cover is unramified outside them, and the
inertia generator at each of them is the corresponding entry of the tuple, so it is nontrivial
there too.

Against the lower bound `Rigidity.RET.two_add_le_card_branchLocus_of_comm`, this says that the
number of branch points an abelian group requires is exactly one more than the number of generators
it requires. -/
theorem exists_cover_card_branchLocus_of_commGroup {H : Type} [CommGroup H] [Finite H] {r : ℕ}
    (t : Fin r → k) (ht : Function.Injective t) (h : Fin r → H) (hprod : (List.ofFn h).prod = 1)
    (htop : Subgroup.closure (Set.range h) = ⊤) (hne : ∀ i, h i ≠ 1) :
    ∃ L : LineCover, Nonempty (L.deck ≃* H) ∧ L.IsUnramifiedAtInfinity ∧
      L.branchLocus = Set.range t ∧ L.finite_branchLocus.toFinset.card = r := by
  obtain ⟨L, e, hout, hinf, hgen⟩ := exists_cover_of_commGroup t ht h hprod htop
  have hnontriv : ∀ i, ∃ σ : L.deck, σ ≠ 1 ∧ L.IsInertiaAt (t i) σ := fun i =>
    ⟨e.symm (h i), fun hσ => hne i (by rw [← e.apply_symm_apply (h i), hσ, map_one]),
      (hgen i).isInertiaAt⟩
  exact ⟨L, ⟨e⟩, hinf, L.branchLocus_eq_range hout hnontriv,
    L.card_branchLocus_eq ht hout hnontriv⟩

end Rigidity.RET
