/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.AbelKummer
import InverseGalois.Rigidity.RET.KummerBase

/-!
# The multi-radical layer is regular

The layer `L` of `Rigidity.RET.Abel` is a Galois extension of `ℚ(T)` of degree `n ^ k` whose group
is the Kummer group `(μₙ)ᵏ`.  This file shows that it gains no constants: `ℚ` is relatively
algebraically closed in it, so the extension is *regular* over `ℚ`.

The argument is the one used for a single radical.  Over the geometric base `ℚ̄(T)` the same
radicands remain independent modulo `n`-th powers (`gABar_indep`), so they generate a second
multi-radical extension of the same degree `n ^ k`; comparing it with the base change identifies
`ℚ̄(T) ⊗ M` with a field (`Rigidity.RET.Kummer.isField_tensor`), which forces the constants of `M`
down to the cyclotomic field `K` (`algebraicClosure_KK_MA`).  A constant of the layer is fixed by
the whole cyclotomic character, hence lies in `ℚ`.

## Main results

* `Rigidity.RET.Abel.isField_tensor_MA` — the geometric base change of `M` is a field.
* `Rigidity.RET.Abel.algebraicClosure_KK_MA` — the constants of `M` are exactly `K`.
* `Rigidity.RET.Abel.regular_LA` — the layer is regular over `ℚ`.
* `Rigidity.RET.Abel.isRegularInverseGalois_autA` — its Galois group is a regular inverse Galois
  group over `ℚ`.
-/

open Polynomial

namespace Rigidity.RET.Abel

noncomputable section

attribute [local instance] Polynomial.algebra

open scoped RatFunc IntermediateField TensorProduct

open Rigidity.RET.Cyclic

variable (n : ℕ) [hn : Fact (1 < n)] (k : ℕ)

/-! ### The geometric multi-radical extension -/

/-- A primitive `n`-th root of unity in the geometric base field. -/
def zetaG : GG n := algebraMap (EE n) (GG n) (zetaE n)

theorem zetaG_isPrimitiveRoot : IsPrimitiveRoot (zetaG n) n :=
  (zetaE_isPrimitiveRoot n).map_of_injective (algebraMap (EE n) (GG n)).injective

/-- The extension of `ℚ̄(T)` generated by the same radicals. -/
abbrev NA : Type := Kummer.RadExt n (gABar n k)

/-- A shortcut for a slow instance search. -/
instance (priority := high) algGGNA : Algebra (GG n) (NA n k) :=
  Polynomial.SplittingField.instAlgebra _

/-- A shortcut for a slow instance search. -/
instance (priority := high) algEENA : Algebra (EE n) (NA n k) :=
  Polynomial.SplittingField.instAlgebra _

/-- A shortcut for a slow instance search. -/
instance (priority := high) smulEEGG : SMul (EE n) (GG n) := Algebra.toSMul

set_option synthInstance.maxHeartbeats 400000 in
/-- A shortcut for a slow instance search. -/
instance (priority := high) isScalarTowerEEGGNA : IsScalarTower (EE n) (GG n) (NA n k) :=
  Polynomial.SplittingField.instIsScalarTower _

/-- The Kummer setup over the geometric base field. -/
def setupBar : Kummer.Setup (GG n) (NA n k) (Fin k) n :=
  Kummer.setupOfIndep (zetaG n) (zetaG_isPrimitiveRoot n) (gABar n k) (gABar_ne_zero n k)
    (gABar_indep n k)

/-- **The geometric base change of the multi-radical extension is a field.** -/
theorem isField_tensor_MA : IsField (GG n ⊗[EE n] MA n k) :=
  Kummer.isField_tensor (setupA n k) (setupBar n k) (fun _ => rfl)

/-! ### The constants of the multi-radical extension -/

/-- A shortcut for a slow instance search. -/
instance (priority := high) algKKMA : Algebra (KK n) (MA n k) :=
  Polynomial.SplittingField.instAlgebra _

/-- A shortcut for a slow instance search. -/
instance (priority := high) isScalarTowerKKEEMA : IsScalarTower (KK n) (EE n) (MA n k) :=
  Polynomial.SplittingField.instIsScalarTower _

/-- **The constants of `M` are exactly `K`**: the multi-radical extension is geometric over `K`. -/
theorem algebraicClosure_KK_MA : algebraicClosure (KK n) (MA n k) = ⊥ :=
  Rigidity.RET.algebraicClosure_eq_bot_of_isField_tensor (F := KK n) (K := EE n) (K' := GG n)
    (L := MA n k) (splits_geom n) (Rigidity.RET.algebraicClosure_ratFunc (KK n))
    (isField_tensor_MA n k)

theorem exists_const_of_isIntegral {y : MA n k} (hy : IsIntegral (KK n) y) :
    ∃ a : KK n, algebraMap (KK n) (MA n k) a = y := by
  have hmem : y ∈ algebraicClosure (KK n) (MA n k) := mem_algebraicClosure_iff'.mpr hy
  rw [algebraicClosure_KK_MA, IntermediateField.mem_bot] at hmem
  exact hmem

/-! ### Regularity of the layer -/

/-- Scaling a rational function by a rational number is multiplication by the constant. -/
theorem ratSmulFF (q : ℚ) (x : FF) : q • x = algebraMap ℚ FF q * x := by
  rw [RatFunc.smul_eq_C_mul]
  exact congrArg (fun f : ℚ →+* FF => f q * x) (Subsingleton.elim RatFunc.C (algebraMap ℚ FF))

set_option synthInstance.maxHeartbeats 400000 in
/-- The layer sits over `ℚ` through `ℚ(T)`. -/
instance (priority := high) isScalarTowerQFFLA : IsScalarTower ℚ FF ↥(LA n k) := by
  have hq : ∀ q : ℚ, (algebraMap FF ↥(LA n k)) (algebraMap ℚ FF q) = algebraMap ℚ ↥(LA n k) q :=
    fun q => congrArg (fun f : ℚ →+* ↥(LA n k) => f q)
      (Subsingleton.elim ((algebraMap FF ↥(LA n k)).comp (algebraMap ℚ FF))
        (algebraMap ℚ ↥(LA n k)))
  refine ⟨fun q x y => Subtype.ext ?_⟩
  simp only [Algebra.smul_def, ratSmulFF, ← hq, ← map_mul, ← mul_assoc]

/-- The two routes from `ℚ` into `M`, through the constants and through `ℚ(T)`, agree: `ℚ` is
initial. -/
theorem rationalMapsA_eq :
    (algebraMap (KK n) (MA n k)).comp (algebraMap ℚ (KK n))
      = (algebraMap FF (MA n k)).comp (algebraMap ℚ FF) :=
  Subsingleton.elim _ _

set_option synthInstance.maxHeartbeats 400000 in
/-- The two routes from `ℚ` into `M`, through the layer and through the constants, agree. -/
theorem rationalMapsA_LA :
    (algebraMap ↥(LA n k) (MA n k)).comp (algebraMap ℚ ↥(LA n k))
      = (algebraMap (KK n) (MA n k)).comp (algebraMap ℚ (KK n)) :=
  Subsingleton.elim _ _

theorem sigmaMAe_algebraMap_KK (c : (ZMod n)ˣ) (a : KK n) :
    sigmaMAe n k c (algebraMap (KK n) (MA n k) a)
      = algebraMap (KK n) (MA n k) (sigmaK n c a) := by
  rw [IsScalarTower.algebraMap_apply (KK n) (EE n) (MA n k),
    IsScalarTower.algebraMap_apply (KK n) (EE n) (MA n k), sigmaMAe_algebraMap, sigmaE_algebraMap]

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 400000 in
/-- **The layer is regular**: it gains no constants over `ℚ`. -/
theorem regular_LA : algebraicClosure ℚ (LA n k) = ⊥ := by
  refine bot_unique fun x hx => ?_
  have hxint : IsIntegral ℚ x := mem_algebraicClosure_iff'.mp hx
  have hpm : (minpoly ℚ x).Monic := minpoly.monic hxint
  have hpx : aeval x (minpoly ℚ x) = 0 := minpoly.aeval ℚ x
  -- the image of `x` in `M` is a constant, i.e. an element of `K`
  have hPx : aeval x ((minpoly ℚ x).map (algebraMap ℚ FF)) = 0 := by
    rw [Polynomial.aeval_map_algebraMap]
    exact hpx
  have hPy : aeval (x : MA n k) ((minpoly ℚ x).map (algebraMap ℚ FF)) = 0 := by
    have hval := Polynomial.aeval_algHom_apply (LA n k).val x ((minpoly ℚ x).map (algebraMap ℚ FF))
    rw [hPx, map_zero] at hval
    exact hval
  have hyint : IsIntegral (KK n) (x : MA n k) := by
    refine ⟨(minpoly ℚ x).map (algebraMap ℚ (KK n)), hpm.map _, ?_⟩
    rw [eval₂_map, rationalMapsA_eq, ← eval₂_map]
    exact hPy
  obtain ⟨a, ha⟩ := exists_const_of_isIntegral n k hyint
  -- being in the layer, the constant is fixed by the whole cyclotomic character
  have hfix : ∀ f : KK n ≃ₐ[ℚ] KK n, f a = a := by
    intro f
    obtain ⟨c, rfl⟩ := sigmaK_surjective n f
    refine (algebraMap (KK n) (MA n k)).injective ?_
    rw [← sigmaMAe_algebraMap_KK, ha]
    exact (mem_LA_iff n k).mp x.2 c
  have hmem : a ∈ (⊥ : IntermediateField ℚ (KK n)) := (IsGalois.mem_bot_iff_fixed a).mpr hfix
  obtain ⟨q, hq⟩ := IntermediateField.mem_bot.mp hmem
  refine IntermediateField.mem_bot.mpr ⟨q, Subtype.ext ?_⟩
  have h1 : ((algebraMap ℚ ↥(LA n k) q : ↥(LA n k)) : MA n k)
      = (algebraMap ↥(LA n k) (MA n k)).comp (algebraMap ℚ ↥(LA n k)) q := rfl
  rw [h1, rationalMapsA_LA, RingHom.comp_apply, hq, ha]

/-! ### The regular realization -/

/-- **The Galois group of the multi-radical layer is a regular inverse Galois group over `ℚ`.** -/
theorem isRegularInverseGalois_autA : IsRegularInverseGalois (LA n k ≃ₐ[FF] LA n k) :=
  ⟨LA n k, inferInstance, algFFLA n k, inferInstance, isGalois_FF_LA n k, inferInstance,
    inferInstance, regular_LA n k, ⟨MulEquiv.refl _⟩⟩

end

end Rigidity.RET.Abel
