/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.AbelianEmbed
import InverseGalois.Rigidity.RET.AbelianGeneration

/-!
# Branch cycles of a cover of the line with abelian deck group

A cover of the line with abelian deck group, unramified outside `r` points of the affine line and
at infinity, embeds in the free abelian cover of the line over those points: both are generated by
radicals of multi-point data, and the free cover swallows every admissible one.  The free cover
carries the standard system of distinguished branch cycles — the coordinate vectors, whose ordered
product is cancelled by the inverse diagonal vector at the last point — and a system of
distinguished branch cycles restricts to a Galois subcover and transports along an isomorphism of
covers.  Pushing the standard system forward therefore produces distinguished branch cycles on the
original cover.

This is the converse direction of the covers correspondence — the statement that a cover comes
from a product-one generating tuple — for abelian deck groups and an arbitrary number of branch
points.

## Main results

* `Rigidity.RET.exists_branchCycleGenSystem_of_comm` — a cover of the line with abelian deck group
  unramified outside `r` points and infinity has a system of distinguished branch cycles over
  those points.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-- **A cover of the line with abelian deck group, unramified outside a tuple of points of the
affine line and at infinity, has a system of distinguished branch cycles over that tuple.** -/
theorem exists_branchCycleGenSystem_of_comm (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a)
    {r : ℕ} (t : Fin r → k) (ht : Function.Injective t)
    (hout : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin r → L.deck, L.IsBranchCycleGenSystem t g := by
  classical
  rcases Nat.eq_zero_or_pos r with rfl | hr
  · -- no branch points: the cover is trivial, in particular cyclic
    haveI : Subsingleton L.deck :=
      subsingleton_deck_of_comm_of_unramified L hab (Set.range_eq_empty t ▸ hout) hinf
    haveI : IsCyclic L.deck :=
      ⟨⟨1, fun x => by rw [Subsingleton.elim x 1]; exact Subgroup.mem_zpowers 1⟩⟩
    exact exists_branchCycleGenSystem_of_isCyclic L t ht hout hinf
  obtain ⟨s, rfl⟩ : ∃ s, r = s + 1 := ⟨r - 1, by omega⟩
  set n := Module.finrank (RatFunc k) L.M with hn
  have hnpos : 0 < n := Module.finrank_pos
  haveI : NeZero n := ⟨hnpos.ne'⟩
  -- the free abelian cover of exponent `n` over the same points, and the embedding into it
  obtain ⟨U, gU, -, -, hbcgs, hsplits⟩ := exists_cover_free_universal n t ht
  obtain ⟨ψ⟩ := exists_algHom_of_comm L U hab t ht hout hinf hsplits
  set E : IntermediateField (RatFunc k) U.M := ψ.fieldRange with hE
  let ψ' : L.M →ₐ[RatFunc k] (E : Type) :=
    ψ.codRestrict E.toSubalgebra fun y => AlgHom.mem_fieldRange.mpr ⟨y, rfl⟩
  have hψ' : Function.Bijective ψ' := by
    constructor
    · intro x y hxy
      exact ψ.toRingHom.injective (congrArg Subtype.val hxy)
    · rintro ⟨x, hx⟩
      obtain ⟨y, hy⟩ := AlgHom.mem_fieldRange.mp hx
      exact ⟨y, Subtype.ext hy⟩
  let ee : L.M ≃ₐ[RatFunc k] (E : Type) := AlgEquiv.ofBijective ψ' hψ'
  haveI : Normal (RatFunc k) (E : Type) := Normal.of_algEquiv ee
  exact ⟨_, (hbcgs.restrict (E := E)).transport ee.symm⟩

end Rigidity.RET
