/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.CyclicCycles
import InverseGalois.Rigidity.RET.ExistenceAbelian

/-!
# The inertia elements of a cover of the line generate its deck group

A cover of the line with cyclic deck group is trivial when it is unramified everywhere and at
infinity, and also when it is branched over a single point (`RET/CyclicCycles.lean`).  Both
statements carry over to an abelian deck group, and in fact yield more: the inertia elements of an
abelian cover generate the whole deck group, and above two branch points the deck group is not
merely generated by inertia but *is* a single inertia group, hence cyclic.  In each case a proper
subgroup is enlarged to a maximal one, which in an abelian group is normal with cyclic quotient,
and the Galois subcover it cuts out is a cyclic cover branched over fewer points than are allowed
by the cyclic theorems.

Passing to the Galois subcover cut out by the commutator subgroup, whose deck group is the
abelianization and whose branch locus is no larger, removes the commutativity hypothesis from the
conclusions that only see abelian quotients: the inertia elements generate the deck group modulo
commutators, and above two branch points the abelianization is cyclic.  The full conclusions
return for a solvable deck group, which a trivial abelianization kills outright, and for a
nilpotent one, where a cyclic abelianization forces the group itself to be cyclic.

The inputs are the passage from a surjection of deck groups to a Galois subcover
(`Rigidity.RET.descentEquiv`), the fact that a subcover in which the inertia away from a set `S`
dies is unramified outside `S`, and the transitivity of the deck action on the places above a
point.

## Main results

* `Rigidity.RET.isUnramifiedOutside_sub` — a Galois subcover in which every inertia element away
  from `S` restricts trivially is unramified outside `S`.
* `Rigidity.RET.eq_one_of_cyclic_quotient_singleton` — a cyclic quotient of the deck group killing
  all the inertia away from one point of the line is trivial.
* `Rigidity.RET.closure_isInertiaAt_eq_top_of_comm` — the inertia elements of a cover with abelian
  deck group, unramified at infinity, generate the deck group.
* `Rigidity.RET.subsingleton_deck_of_comm_of_unramified` — a cover with abelian deck group,
  unramified everywhere and at infinity, is trivial.
* `Rigidity.RET.isInertiaAt_iff_mem_of_comm` — for an abelian deck group all the inertia groups
  above a point of the line coincide.
* `Rigidity.RET.isCyclic_deck_of_comm_of_unramified_outside_pair` — a cover with abelian deck
  group, branched over at most two points and unramified at infinity, has cyclic deck group.
* `Rigidity.RET.exists_branchCycleGenSystem_of_comm_of_two` — a cover with abelian deck group,
  unramified outside two points and infinity, has distinguished branch cycles over them.
* `Rigidity.RET.exists_places_iSup_geomInertia_eq_top_of_comm` — the inertia groups above the
  branch points of a cover with abelian deck group generate the deck group.
* `Rigidity.RET.exists_inertiaGens_of_comm` — a cover with abelian deck group has a generating
  tuple of distinguished inertia generators over any tuple of points containing its branch locus.
* `Rigidity.RET.normalClosure_isInertiaAt_sup_commutator_eq_top` — the inertia elements of an
  arbitrary cover generate its deck group modulo commutators.
* `Rigidity.RET.normalClosure_isInertiaAt_eq_top_of_isSolvable` — the inertia elements of a cover
  with solvable deck group generate it as a normal subgroup.
* `Rigidity.RET.exists_places_normalClosure_iSup_geomInertia_sup_commutator_eq_top` — one inertia
  group above each branch point generates the deck group of an arbitrary cover modulo commutators.
* `Rigidity.RET.isCyclic_deck_of_isNilpotent_of_unramified_outside_pair` — a cover with nilpotent
  deck group, branched over at most two points and unramified at infinity, has cyclic deck group.
* `Rigidity.RET.subsingleton_deck_of_isSolvable_of_unramified_outside_singleton` — a cover with
  solvable deck group, branched over at most one point and unramified at infinity, is trivial.
* `Rigidity.RET.isCyclic_abelianization_of_unramified_outside_pair` — the abelianized deck group of
  a cover branched over at most two points is cyclic.
* `Rigidity.RET.subsingleton_abelianization_of_unramified_outside_singleton` — the deck group of a
  cover branched over at most one point is perfect.
* `Rigidity.RET.exists_gens_abelianization_of_unramifiedOutside` — the abelianized deck group of a
  cover unramified outside `r` points and infinity is generated by `r` elements.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

attribute [local instance] LineCover.sub_isGalois

/-! ### A subcover killing all the inertia is unramified -/

/-- **A Galois subcover is unramified outside the points where some inertia element survives in
it.**  Every place of the subcover above a point of the line is a deck translate of the
contraction of a place of the big cover, and inertia at a contracted place is the image of the
inertia above it. -/
theorem isUnramifiedOutside_sub {L : LineCover} (E : IntermediateField (RatFunc k) L.M)
    [Normal (RatFunc k) E] {S : Set k}
    (h : ∀ t : k, t ∉ S → ∀ σ : L.deck, L.IsInertiaAt t σ → L.subHom E σ = 1) :
    (L.sub E).IsUnramifiedOutside S := by
  haveI := isScalarTower_poly_sub (E : Type) L.M
  intro t ht τ hτ
  obtain ⟨Q', hQ'max, hQ'over, hQ'in⟩ := hτ
  obtain ⟨Q, hQmax, hQover⟩ := L.exists_place t
  haveI := hQmax
  haveI : Q.IsPrime := hQmax.isPrime
  haveI := hQover
  -- the whole inertia group upstairs restricts to the identity
  have hbot : (geomInertia L.M Q).map (L.subHom E) = ⊥ := by
    rw [eq_bot_iff]
    rintro σ' hσ'
    obtain ⟨σ, hσ, rfl⟩ := hσ'
    exact Subgroup.mem_bot.mpr (h t ht σ ⟨Q, hQmax, hQover, hσ⟩)
  have hQ'in' : τ ∈ geomInertia (E : Type) Q' := hQ'in
  have hcomap : geomInertia (E : Type)
      (Q.comap (subInclusion (E := (E : Type)) (M := L.M))) = ⊥ := by
    rw [geomInertia_comap_eq_map (E := (E : Type)) (M := L.M) (L.subHom E) (L.subHom_commutes E)
      t Q (L.subHom_surjective E), hbot]
  -- every place of the subcover above `t` is a deck translate of the contracted place
  haveI := hQ'max
  haveI : Q'.IsPrime := hQ'max.isPrime
  haveI := hQ'over
  haveI hcm : (Q.comap (subInclusion (E := (E : Type)) (M := L.M))).IsMaximal :=
    isMaximal_comap_subInclusion (E := (E : Type)) t Q
  haveI : (Q.comap (subInclusion (E := (E : Type)) (M := L.M))).IsPrime := hcm.isPrime
  haveI := liesOver_comap_subInclusion (E := (E : Type)) (M := L.M) t Q
  obtain ⟨g, hg⟩ := exists_smul_eq_of_liesOver (Ω := (E : Type)) t
    (Q.comap (subInclusion (E := (E : Type)) (M := L.M))) Q'
  rw [hg, geomInertia_smul, hcomap, Subgroup.map_bot] at hQ'in'
  exact Subgroup.mem_bot.mp hQ'in'

/-! ### No cyclic quotient survives -/

/-- **A cyclic quotient of the deck group killing all the inertia away from a single point of the
line is trivial.**  The Galois subcover cut out by the kernel is a cyclic cover of the line
branched over at most that one point and unramified at infinity, hence trivial. -/
theorem eq_one_of_cyclic_quotient_singleton {L : LineCover} {H : Type} [Group H] [IsCyclic H]
    (f : L.deck →* H) (hf : Function.Surjective f) (t₀ : k)
    (hker : ∀ t : k, t ≠ t₀ → ∀ σ : L.deck, L.IsInertiaAt t σ → f σ = 1)
    (hinf : L.IsUnramifiedAtInfinity) (x : H) : x = 1 := by
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  -- the subcover is cyclic
  haveI : IsCyclic (L.sub E).deck :=
    isCyclic_of_surjective (descentEquiv f hf).symm (descentEquiv f hf).symm.surjective
  -- and branched over at most `t₀`, since every other inertia element restricts trivially to it
  have hres : ∀ t : k, t ∉ ({t₀} : Set k) → ∀ σ : L.deck, L.IsInertiaAt t σ →
      L.subHom E σ = 1 := by
    intro t ht σ hσ
    refine (MulEquiv.map_eq_one_iff (descentEquiv f hf)).mp ?_
    rw [descentEquiv_apply f hf σ]
    exact hker t (by simpa using ht) σ hσ
  haveI := subsingleton_deck_of_unramified_outside_singleton (L.sub E) t₀
    (isUnramifiedOutside_sub E hres) (hinf.sub E)
  calc x = descentEquiv f hf ((descentEquiv f hf).symm x) :=
        ((descentEquiv f hf).apply_symm_apply x).symm
    _ = descentEquiv f hf 1 := by rw [Subsingleton.elim ((descentEquiv f hf).symm x) 1]
    _ = 1 := map_one _

/-- **A cover unramified everywhere and at infinity has no nontrivial cyclic quotient of its deck
group.** -/
theorem eq_one_of_cyclic_quotient {L : LineCover} {H : Type} [Group H] [IsCyclic H]
    (f : L.deck →* H) (hf : Function.Surjective f)
    (hker : ∀ (t : k) (σ : L.deck), L.IsInertiaAt t σ → f σ = 1)
    (hinf : L.IsUnramifiedAtInfinity) (x : H) : x = 1 :=
  eq_one_of_cyclic_quotient_singleton f hf 0 (fun t _ => hker t) hinf x

/-! ### Two pieces of group theory -/

/-- A proper subgroup of a finite group is contained in a maximal one. -/
theorem exists_isCoatom_ge {G : Type*} [Group G] [Finite G] {I : Subgroup G} (hI : I ≠ ⊤) :
    ∃ B : Subgroup G, IsCoatom B ∧ I ≤ B := by
  haveI : Finite (Subgroup G) := Finite.of_injective _ (SetLike.coe_injective (A := Subgroup G))
  exact (eq_top_or_exists_le_coatom I).resolve_left hI

/-- **The quotient by a maximal normal subgroup is cyclic**, generated by the image of any element
outside it: that image together with the subgroup generates everything. -/
theorem isCyclic_quotient_of_isCoatom {G : Type*} [Group G] (B : Subgroup G) [B.Normal]
    (hB : IsCoatom B) : IsCyclic (G ⧸ B) := by
  obtain ⟨x, hx⟩ : ∃ x : G, x ∉ B := by
    by_contra hall
    exact hB.1 (eq_top_iff.mpr fun y _ => not_not.mp fun hy => hall ⟨y, hy⟩)
  set π : G →* G ⧸ B := QuotientGroup.mk' B with hπ
  have hsup : Subgroup.closure {x} ⊔ B = ⊤ := by
    refine hB.2 _ (lt_of_le_of_ne le_sup_right fun heq => hx ?_)
    have hxm : x ∈ Subgroup.closure {x} ⊔ B :=
      (le_sup_left : Subgroup.closure {x} ≤ _) (Subgroup.subset_closure rfl)
    rwa [← heq] at hxm
  have hkill : Subgroup.map π B = ⊥ := by
    rw [Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk']
  have hmapsup : Subgroup.map π (Subgroup.closure {x} ⊔ B) = Subgroup.zpowers (π x) := by
    rw [Subgroup.map_sup, hkill, sup_bot_eq, MonoidHom.map_closure, Set.image_singleton,
      ← Subgroup.zpowers_eq_closure]
  refine ⟨π x, fun a => ?_⟩
  show a ∈ Subgroup.zpowers (π x)
  rw [← hmapsup, hsup, ← MonoidHom.range_eq_map,
    MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective B)]
  exact Subgroup.mem_top a

/-! ### The abelian case -/

/-- **The inertia elements of a cover with abelian deck group, unramified at infinity, generate the
deck group.**  A proper subgroup of a finite group lies inside a maximal one, which in an abelian
group is normal with cyclic quotient; the subcover it cuts out would then be a nontrivial cyclic
cover of the line unramified everywhere and at infinity. -/
theorem closure_isInertiaAt_eq_top_of_comm (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a)
    (hinf : L.IsUnramifiedAtInfinity) :
    Subgroup.closure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} = ⊤ := by
  set B : Subgroup L.deck := Subgroup.closure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} with hB
  by_contra hne
  obtain ⟨B', hB'co, hBB'⟩ := exists_isCoatom_ge hne
  haveI : B'.Normal :=
    ⟨fun n hn g => by rw [hab g n, mul_assoc, mul_inv_cancel, mul_one]; exact hn⟩
  obtain ⟨x, hx⟩ : ∃ x : L.deck, x ∉ B' := by
    by_contra hall
    exact hB'co.1 (eq_top_iff.mpr fun y _ => not_not.mp fun hy => hall ⟨y, hy⟩)
  set π : L.deck →* L.deck ⧸ B' := QuotientGroup.mk' B' with hπ
  have hπsurj : Function.Surjective π := QuotientGroup.mk'_surjective B'
  haveI : IsCyclic (L.deck ⧸ B') := isCyclic_quotient_of_isCoatom B' hB'co
  -- every inertia element dies in the quotient, so the quotient is trivial — a contradiction
  have hker : ∀ (t : k) (σ : L.deck), L.IsInertiaAt t σ → π σ = 1 := by
    intro t σ hσ
    exact (QuotientGroup.eq_one_iff σ).mpr (hBB' (Subgroup.subset_closure ⟨t, hσ⟩))
  exact hx ((QuotientGroup.eq_one_iff x).mp
    (eq_one_of_cyclic_quotient π hπsurj hker hinf (π x)))

/-- **A cover of the line with abelian deck group, unramified everywhere and at infinity, is
trivial.** -/
theorem subsingleton_deck_of_comm_of_unramified (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (hS : L.IsUnramifiedOutside ∅)
    (hinf : L.IsUnramifiedAtInfinity) : Subsingleton L.deck := by
  have htop := closure_isInertiaAt_eq_top_of_comm L hab hinf
  have hbot : Subgroup.closure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} ≤ ⊥ := by
    refine (Subgroup.closure_le _).mpr ?_
    rintro σ ⟨t, hσ⟩
    exact Subgroup.mem_bot.mpr (hS t (Set.notMem_empty t) σ hσ)
  rw [htop] at hbot
  exact ⟨fun a b => by
    rw [Subgroup.mem_bot.mp (hbot (Subgroup.mem_top a)),
      Subgroup.mem_bot.mp (hbot (Subgroup.mem_top b))]⟩

/-! ### At most two branch points -/

/-- **For an abelian cover all the inertia groups above a point of the line coincide.**  The deck
group permutes the places above a point transitively and moves inertia groups by conjugation,
which is trivial when the deck group is abelian. -/
theorem isInertiaAt_iff_mem_of_comm (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a) (t : k)
    (Q : Ideal (Bring L.M)) [hQmax : Q.IsMaximal] [hQover : Q.LiesOver (placeP t)]
    {σ : L.deck} : L.IsInertiaAt t σ ↔ σ ∈ geomInertia L.M Q := by
  haveI : Q.IsPrime := hQmax.isPrime
  refine ⟨?_, fun h => ⟨Q, hQmax, hQover, h⟩⟩
  rintro ⟨Q', hQ'max, hQ'over, hQ'in⟩
  haveI := hQ'max
  haveI : Q'.IsPrime := hQ'max.isPrime
  haveI := hQ'over
  obtain ⟨g, hg⟩ := exists_smul_eq_of_liesOver (Ω := L.M) t Q Q'
  rw [hg, geomInertia_smul] at hQ'in
  obtain ⟨y, hy, rfl⟩ := hQ'in
  have hfix : (MulAut.conj g).toMonoidHom y = y := by
    show g * y * g⁻¹ = y
    rw [hab g y, mul_assoc, mul_inv_cancel, mul_one]
  rw [hfix]
  exact hy

/-- **A cover of the line with abelian deck group, branched over at most two points and unramified
at infinity, has cyclic deck group.**  Were the inertia group above the first point proper, it
would sit inside a maximal subgroup, and the cyclic quotient by that subgroup would be a cyclic
cover branched over the second point alone — hence trivial.  So the deck group *is* an inertia
group, and a geometric inertia group is cyclic.  This is the algebraic shadow of the abelianized
fundamental group of the twice-punctured line being procyclic. -/
theorem isCyclic_deck_of_comm_of_unramified_outside_pair (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (t₀ t₁ : k) (hS : L.IsUnramifiedOutside {t₀, t₁})
    (hinf : L.IsUnramifiedAtInfinity) : IsCyclic L.deck := by
  obtain ⟨Q, hQmax, hQover⟩ := L.exists_place t₀
  haveI := hQmax
  haveI := hQover
  have htop : geomInertia L.M Q = ⊤ := by
    by_contra hne
    obtain ⟨B', hB'co, hIB'⟩ := exists_isCoatom_ge hne
    haveI : B'.Normal :=
      ⟨fun n hn g => by rw [hab g n, mul_assoc, mul_inv_cancel, mul_one]; exact hn⟩
    obtain ⟨x, hx⟩ : ∃ x : L.deck, x ∉ B' := by
      by_contra hall
      exact hB'co.1 (eq_top_iff.mpr fun y _ => not_not.mp fun hy => hall ⟨y, hy⟩)
    set π : L.deck →* L.deck ⧸ B' := QuotientGroup.mk' B' with hπ
    haveI : IsCyclic (L.deck ⧸ B') := isCyclic_quotient_of_isCoatom B' hB'co
    -- in the quotient the inertia above `t₀` dies, and away from `t₀` and `t₁` there is none
    have hker : ∀ t : k, t ≠ t₁ → ∀ σ : L.deck, L.IsInertiaAt t σ → π σ = 1 := by
      intro t ht σ hσ
      refine (QuotientGroup.eq_one_iff σ).mpr ?_
      by_cases h : t = t₀
      · exact hIB' ((isInertiaAt_iff_mem_of_comm L hab t₀ Q).mp (h ▸ hσ))
      · have hnot : t ∉ ({t₀, t₁} : Set k) := by
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
          push_neg
          exact ⟨h, ht⟩
        rw [hS t hnot σ hσ]
        exact one_mem _
    exact hx ((QuotientGroup.eq_one_iff x).mp (eq_one_of_cyclic_quotient_singleton π
      (QuotientGroup.mk'_surjective B') t₁ hker hinf (π x)))
  haveI := GeomAKLB.isCyclic_geomInertia (Ω := L.M) t₀ Q
  exact isCyclic_of_surjective
    ((MulEquiv.subgroupCongr htop).trans Subgroup.topEquiv : geomInertia L.M Q ≃* L.deck)
    (MulEquiv.surjective _)

/-- **A cover of the line with abelian deck group, branched over at most one point and unramified
at infinity, has cyclic deck group.** -/
theorem isCyclic_deck_of_comm_of_unramified_outside_singleton (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (t₀ : k) (hS : L.IsUnramifiedOutside {t₀})
    (hinf : L.IsUnramifiedAtInfinity) : IsCyclic L.deck :=
  isCyclic_deck_of_comm_of_unramified_outside_pair L hab t₀ t₀
    (by rwa [Set.pair_eq_singleton]) hinf

/-- **A cover of the line with abelian deck group, branched over at most one point and unramified
at infinity, is trivial.** -/
theorem subsingleton_deck_of_comm_of_unramified_outside_singleton (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (t₀ : k) (hS : L.IsUnramifiedOutside {t₀})
    (hinf : L.IsUnramifiedAtInfinity) : Subsingleton L.deck := by
  haveI := isCyclic_deck_of_comm_of_unramified_outside_singleton L hab t₀ hS hinf
  exact subsingleton_deck_of_unramified_outside_singleton L t₀ hS hinf

/-- **A cover of the line with abelian deck group, unramified outside two points and infinity, has
distinguished branch cycles over them.**  Such a cover is cyclic, so the cyclic converse of the
Riemann existence correspondence applies.  This is the full `exists_cycles` clause — branch cycles,
generation and the product-one relation — for abelian deck groups in rank two. -/
theorem exists_branchCycleGenSystem_of_comm_of_two (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (t : Fin 2 → k) (ht : Function.Injective t)
    (hS : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin 2 → L.deck, L.IsBranchCycleGenSystem t g := by
  have hrange : Set.range t = {t 0, t 1} := by
    ext x
    simp [Set.mem_range, Fin.exists_fin_two, eq_comm]
  haveI : IsCyclic L.deck :=
    isCyclic_deck_of_comm_of_unramified_outside_pair L hab (t 0) (t 1) (hrange ▸ hS) hinf
  exact exists_branchCycleGenSystem_of_isCyclic L t ht hS hinf

/-- **The inertia groups above the branch points of an abelian cover generate its deck group.**
This is the generation clause localized at the branch points: one place above each of them
suffices, because for an abelian deck group the choice of place does not matter. -/
theorem exists_places_iSup_geomInertia_eq_top_of_comm (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) {r : ℕ} (t : Fin r → k)
    (hS : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ Q : Fin r → Ideal (Bring L.M),
      (∀ i, (Q i).IsMaximal ∧ (Q i).LiesOver (placeP (t i))) ∧
        ⨆ i, geomInertia L.M (Q i) = ⊤ := by
  choose Q hQmax hQover using fun i : Fin r => L.exists_place (t i)
  refine ⟨Q, fun i => ⟨hQmax i, hQover i⟩, eq_top_iff.mpr ?_⟩
  rw [← closure_isInertiaAt_eq_top_of_comm L hab hinf]
  refine (Subgroup.closure_le _).mpr ?_
  rintro σ ⟨u, hσ⟩
  by_cases h : ∃ i, t i = u
  · obtain ⟨i, rfl⟩ := h
    haveI := hQmax i
    haveI := hQover i
    exact Subgroup.mem_iSup_of_mem i ((isInertiaAt_iff_mem_of_comm L hab (t i) (Q i)).mp hσ)
  · rw [hS u h σ hσ]
    exact one_mem _

/-- **A cover with abelian deck group has a generating tuple of distinguished inertia generators
over any tuple of points containing its branch locus.**  Each inertia group above a branch point
is cyclic, and by the previous theorem those groups generate; this is every clause of a system of
distinguished branch cycles except the product-one relation, which needs the generators to be
chosen coherently. -/
theorem exists_inertiaGens_of_comm (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a) {r : ℕ}
    (t : Fin r → k) (hS : L.IsUnramifiedOutside (Set.range t))
    (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin r → L.deck,
      (∀ i, L.IsInertiaGenAt (t i) (g i)) ∧ Subgroup.closure (Set.range g) = ⊤ := by
  obtain ⟨Q, hQ, hsup⟩ := exists_places_iSup_geomInertia_eq_top_of_comm L hab t hS hinf
  have hcyc : ∀ i, ∃ g : L.deck, Subgroup.zpowers g = geomInertia L.M (Q i) := by
    intro i
    haveI := (hQ i).1
    haveI := (hQ i).2
    exact (Subgroup.isCyclic_iff_exists_zpowers_eq_top _).mp
      (GeomAKLB.isCyclic_geomInertia (Ω := L.M) (t i) (Q i))
  choose g hg using hcyc
  refine ⟨g, fun i => ⟨Q i, (hQ i).1, (hQ i).2, (hg i).symm⟩, eq_top_iff.mpr ?_⟩
  rw [← hsup]
  refine iSup_le fun i => ?_
  rw [← hg i]
  exact Subgroup.zpowers_le.mpr (Subgroup.subset_closure ⟨i, rfl⟩)

/-! ### Dropping the abelian hypothesis: the abelianized deck group -/

/-- Every element of the abelianization comes from the group. -/
theorem surjective_abelianization_of {G : Type*} [Group G] :
    Function.Surjective (Abelianization.of : G →* Abelianization G) := fun x =>
  QuotientGroup.induction_on x fun g => ⟨g, rfl⟩

/-- The abelianization of the deck group is the deck group of a Galois subcover. -/
theorem abelianization_of_surjective (L : LineCover) :
    Function.Surjective (Abelianization.of : L.deck →* Abelianization L.deck) :=
  surjective_abelianization_of

/-- **The abelianized deck group of a cover of the line branched over at most two points is
cyclic**, with no commutativity hypothesis on the cover itself: the Galois subcover cut out by the
commutator subgroup has the abelianization as its deck group and the same branch locus. -/
theorem isCyclic_abelianization_of_unramified_outside_pair (L : LineCover) (t₀ t₁ : k)
    (hS : L.IsUnramifiedOutside {t₀, t₁}) (hinf : L.IsUnramifiedAtInfinity) :
    IsCyclic (Abelianization L.deck) := by
  set f : L.deck →* Abelianization L.deck := Abelianization.of with hfdef
  have hfsurj : Function.Surjective f := abelianization_of_surjective L
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  have hab : ∀ a b : (L.sub E).deck, a * b = b * a := fun a b =>
    (descentEquiv f hfsurj).injective (by rw [map_mul, map_mul, mul_comm])
  haveI := isCyclic_deck_of_comm_of_unramified_outside_pair (L.sub E) hab t₀ t₁
    (hS.sub E) (hinf.sub E)
  exact isCyclic_of_surjective (descentEquiv f hfsurj) (descentEquiv f hfsurj).surjective

/-- **The deck group of a cover of the line branched over at most one point is perfect.**  This is
the shadow of `π₁(𝔸¹) = 1` that survives without a commutativity hypothesis: the cover has no
nontrivial abelian quotient, even though it may well be nontrivial as far as these methods can
tell. -/
theorem subsingleton_abelianization_of_unramified_outside_singleton (L : LineCover) (t₀ : k)
    (hS : L.IsUnramifiedOutside {t₀}) (hinf : L.IsUnramifiedAtInfinity) :
    Subsingleton (Abelianization L.deck) := by
  set f : L.deck →* Abelianization L.deck := Abelianization.of with hfdef
  have hfsurj : Function.Surjective f := abelianization_of_surjective L
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  have hab : ∀ a b : (L.sub E).deck, a * b = b * a := fun a b =>
    (descentEquiv f hfsurj).injective (by rw [map_mul, map_mul, mul_comm])
  haveI := subsingleton_deck_of_comm_of_unramified_outside_singleton (L.sub E) hab t₀
    (hS.sub E) (hinf.sub E)
  exact (descentEquiv f hfsurj).symm.injective.subsingleton

/-- **The abelianized deck group of a cover of the line unramified outside `r` points and infinity
is generated by `r` elements.**  One generator comes from each branch point, through the Galois
subcover cut out by the commutator subgroup. -/
theorem exists_gens_abelianization_of_unramifiedOutside (L : LineCover) {r : ℕ} (t : Fin r → k)
    (hS : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin r → Abelianization L.deck, Subgroup.closure (Set.range g) = ⊤ := by
  set f : L.deck →* Abelianization L.deck := Abelianization.of with hfdef
  have hfsurj : Function.Surjective f := abelianization_of_surjective L
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  have hab : ∀ a b : (L.sub E).deck, a * b = b * a := fun a b =>
    (descentEquiv f hfsurj).injective (by rw [map_mul, map_mul, mul_comm])
  obtain ⟨g, -, htop⟩ := exists_inertiaGens_of_comm (L.sub E) hab t (hS.sub E) (hinf.sub E)
  refine ⟨fun i => descentEquiv f hfsurj (g i), eq_top_iff.mpr fun x _ => ?_⟩
  obtain ⟨y, rfl⟩ := (descentEquiv f hfsurj).surjective x
  have hy : y ∈ Subgroup.closure (Set.range g) := htop ▸ Subgroup.mem_top y
  have hmap : Subgroup.map (descentEquiv f hfsurj).toMonoidHom (Subgroup.closure (Set.range g))
      ≤ Subgroup.closure (Set.range fun i => descentEquiv f hfsurj (g i)) := by
    rw [MonoidHom.map_closure]
    refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    exact Subgroup.subset_closure ⟨i, rfl⟩
  exact hmap ⟨y, hy, rfl⟩

/-! ### Inertia generates the deck group modulo commutators -/

/-- **The inertia elements of an arbitrary cover of the line generate the deck group modulo
commutators.**  No commutativity hypothesis is needed: the quotient of the deck group by the
normal closure of the inertia elements together with the commutator subgroup is the deck group of
an abelian cover of the line unramified everywhere, hence trivial. -/
theorem normalClosure_isInertiaAt_sup_commutator_eq_top (L : LineCover)
    (hinf : L.IsUnramifiedAtInfinity) :
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} ⊔ commutator L.deck = ⊤ := by
  set K : Subgroup L.deck :=
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} ⊔ commutator L.deck with hKdef
  haveI : K.Normal := Subgroup.sup_normal _ _
  set f : L.deck →* L.deck ⧸ K := QuotientGroup.mk' K with hfdef
  have hfs : Function.Surjective f := QuotientGroup.mk'_surjective K
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  -- the quotient is abelian, since it kills the commutator subgroup
  have hquot : ∀ a b : L.deck ⧸ K, a * b = b * a := by
    intro a b
    induction a using QuotientGroup.induction_on with
    | _ x =>
      induction b using QuotientGroup.induction_on with
      | _ y =>
        have hcomm : f ⁅x, y⁆ = 1 := (QuotientGroup.eq_one_iff _).mpr
          (Subgroup.mem_sup_right (Subgroup.commutator_mem_commutator (Subgroup.mem_top x)
            (Subgroup.mem_top y)))
        rw [map_commutatorElement] at hcomm
        exact commutatorElement_eq_one_iff_mul_comm.mp hcomm
  have hab : ∀ a b : (L.sub E).deck, a * b = b * a := fun a b =>
    (descentEquiv f hfs).injective (by rw [map_mul, map_mul, hquot])
  -- and it kills every inertia element, so the subcover is unramified everywhere
  have hres : ∀ t : k, t ∉ (∅ : Set k) → ∀ σ : L.deck, L.IsInertiaAt t σ → L.subHom E σ = 1 := by
    intro t _ σ hσ
    refine (MulEquiv.map_eq_one_iff (descentEquiv f hfs)).mp ?_
    rw [descentEquiv_apply f hfs σ]
    exact (QuotientGroup.eq_one_iff σ).mpr
      (Subgroup.mem_sup_left (Subgroup.subset_normalClosure ⟨t, hσ⟩))
  haveI := subsingleton_deck_of_comm_of_unramified (L.sub E) hab (isUnramifiedOutside_sub E hres)
    (hinf.sub E)
  haveI : Subsingleton (L.deck ⧸ K) := (descentEquiv f hfs).symm.injective.subsingleton
  exact eq_top_iff.mpr fun y _ => (QuotientGroup.eq_one_iff y).mp (Subsingleton.elim _ _)

/-! ### Solvable and nilpotent covers of the affine line -/

/-- A cyclic group is commutative. -/
theorem mul_comm_of_isCyclic {G : Type*} [Group G] [IsCyclic G] (a b : G) : a * b = b * a := by
  obtain ⟨g, hg⟩ := (inferInstance : IsCyclic G)
  obtain ⟨m, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg a)
  obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg b)
  exact zpow_mul_comm g m n

/-- The commutator subgroup lies in any normal subgroup with cyclic quotient. -/
theorem commutator_le_of_isCyclic_quotient {G : Type*} [Group G] (B : Subgroup G) [B.Normal]
    (h : IsCyclic (G ⧸ B)) : commutator G ≤ B := by
  haveI := h
  refine Subgroup.commutator_le.mpr fun g₁ _ g₂ _ => ?_
  refine (QuotientGroup.eq_one_iff _).mp ?_
  show QuotientGroup.mk' B ⁅g₁, g₂⁆ = 1
  rw [map_commutatorElement, commutatorElement_eq_one_iff_mul_comm]
  exact mul_comm_of_isCyclic _ _

/-- A finite nilpotent group with cyclic abelianization is cyclic: an element generating the
abelianization generates the group, since otherwise it would lie in a maximal subgroup, which is
normal with cyclic — hence abelian — quotient, and so would contain the commutator subgroup
too. -/
theorem isCyclic_of_isNilpotent_of_isCyclic_abelianization {G : Type*} [Group G] [Finite G]
    [Group.IsNilpotent G] (h : IsCyclic (Abelianization G)) : IsCyclic G := by
  obtain ⟨a, ha⟩ := h
  obtain ⟨x, rfl⟩ := surjective_abelianization_of a
  have hsup : Subgroup.zpowers x ⊔ commutator G = ⊤ := by
    refine eq_top_iff.mpr fun y _ => ?_
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (ha (Abelianization.of y))
    have hmem : y * (x ^ n)⁻¹ ∈ commutator G := by
      rw [← Abelianization.ker_of, MonoidHom.mem_ker, map_mul, map_inv, map_zpow, hn,
        mul_inv_cancel]
    have : y = y * (x ^ n)⁻¹ * x ^ n := by group
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_right hmem)
      (Subgroup.mem_sup_left (Subgroup.zpow_mem _ (Subgroup.mem_zpowers x) n))
  have hxtop : Subgroup.zpowers x = ⊤ := by
    by_contra hne
    obtain ⟨B, hBco, hxB⟩ := exists_isCoatom_ge hne
    haveI : B.Normal :=
      Subgroup.NormalizerCondition.normal_of_coatom B normalizerCondition_of_isNilpotent hBco
    refine hBco.1 (eq_top_iff.mpr ?_)
    rw [← hsup]
    exact sup_le hxB (commutator_le_of_isCyclic_quotient B (isCyclic_quotient_of_isCoatom B hBco))
  refine ⟨x, fun y => ?_⟩
  show y ∈ Subgroup.zpowers x
  rw [hxtop]
  exact Subgroup.mem_top y

/-- **A cover of the line with nilpotent deck group, branched over at most two points, is
cyclic.**  For nilpotent deck groups this is the whole of `π₁` of the twice-punctured line being
procyclic: cyclicity of the abelianization propagates to the group itself. -/
theorem isCyclic_deck_of_isNilpotent_of_unramified_outside_pair (L : LineCover)
    [Group.IsNilpotent L.deck] (t₀ t₁ : k) (hS : L.IsUnramifiedOutside {t₀, t₁})
    (hinf : L.IsUnramifiedAtInfinity) : IsCyclic L.deck :=
  isCyclic_of_isNilpotent_of_isCyclic_abelianization
    (isCyclic_abelianization_of_unramified_outside_pair L t₀ t₁ hS hinf)

/-- **A cover of the line with nilpotent deck group, unramified outside two points and infinity,
has distinguished branch cycles over them.** -/
theorem exists_branchCycleGenSystem_of_isNilpotent_of_two (L : LineCover)
    [Group.IsNilpotent L.deck] (t : Fin 2 → k) (ht : Function.Injective t)
    (hS : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin 2 → L.deck, L.IsBranchCycleGenSystem t g := by
  have hrange : Set.range t = {t 0, t 1} := by
    ext x
    simp [Set.mem_range, Fin.exists_fin_two, eq_comm]
  haveI : IsCyclic L.deck :=
    isCyclic_deck_of_isNilpotent_of_unramified_outside_pair L (t 0) (t 1) (hrange ▸ hS) hinf
  exact exists_branchCycleGenSystem_of_isCyclic L t ht hS hinf

/-! ### Solvable covers of the affine line -/

/-- A solvable group with trivial abelianization is trivial. -/
theorem subsingleton_of_isSolvable_of_subsingleton_abelianization {G : Type*} [Group G]
    [IsSolvable G] (h : Subsingleton (Abelianization G)) : Subsingleton G := by
  rw [← not_nontrivial_iff_subsingleton]
  intro hnt
  have htop : commutator G = ⊤ := by
    rw [← Abelianization.ker_of]
    ext x
    simp only [MonoidHom.mem_ker, Subgroup.mem_top, iff_true]
    exact Subsingleton.elim _ _
  exact absurd htop (IsSolvable.commutator_lt_top_of_nontrivial (G := G)).ne

/-- **A cover of the line with solvable deck group, branched over at most one point, is trivial.**
This is the full statement `π₁(𝔸¹) = 1` for solvable deck groups: a solvable group is killed by
the successive abelian quotients that the branch locus already forbids. -/
theorem subsingleton_deck_of_isSolvable_of_unramified_outside_singleton (L : LineCover)
    [IsSolvable L.deck] (t₀ : k) (hS : L.IsUnramifiedOutside {t₀})
    (hinf : L.IsUnramifiedAtInfinity) : Subsingleton L.deck :=
  subsingleton_of_isSolvable_of_subsingleton_abelianization
    (subsingleton_abelianization_of_unramified_outside_singleton L t₀ hS hinf)

/-- **A cover of the line with solvable deck group, unramified everywhere and at infinity, is
trivial.** -/
theorem subsingleton_deck_of_isSolvable_of_unramified (L : LineCover) [IsSolvable L.deck]
    (hS : L.IsUnramifiedOutside ∅) (hinf : L.IsUnramifiedAtInfinity) : Subsingleton L.deck :=
  subsingleton_deck_of_isSolvable_of_unramified_outside_singleton L 0
    (hS.mono (Set.empty_subset _)) hinf

/-- **The inertia elements of a cover of the line with solvable deck group generate it as a normal
subgroup.**  The quotient by their normal closure is the deck group of a solvable cover of the line
unramified everywhere, hence trivial. -/
theorem normalClosure_isInertiaAt_eq_top_of_isSolvable (L : LineCover) [IsSolvable L.deck]
    (hinf : L.IsUnramifiedAtInfinity) :
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} = ⊤ := by
  set N : Subgroup L.deck := Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ}
    with hNdef
  set f : L.deck →* L.deck ⧸ N := QuotientGroup.mk' N with hfdef
  have hfs : Function.Surjective f := QuotientGroup.mk'_surjective N
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  haveI : IsSolvable (L.sub E).deck :=
    solvable_of_surjective (f := (descentEquiv f hfs).symm.toMonoidHom)
      (descentEquiv f hfs).symm.surjective
  have hres : ∀ t : k, t ∉ (∅ : Set k) → ∀ σ : L.deck, L.IsInertiaAt t σ → L.subHom E σ = 1 := by
    intro t _ σ hσ
    refine (MulEquiv.map_eq_one_iff (descentEquiv f hfs)).mp ?_
    rw [descentEquiv_apply f hfs σ]
    exact (QuotientGroup.eq_one_iff σ).mpr (Subgroup.subset_normalClosure ⟨t, hσ⟩)
  haveI := subsingleton_deck_of_isSolvable_of_unramified (L.sub E) (isUnramifiedOutside_sub E hres)
    (hinf.sub E)
  haveI : Subsingleton (L.deck ⧸ N) := (descentEquiv f hfs).symm.injective.subsingleton
  exact eq_top_iff.mpr fun y _ => (QuotientGroup.eq_one_iff y).mp (Subsingleton.elim _ _)

/-- **The inertia groups above the branch points of an arbitrary cover generate the deck group
modulo commutators**, one chosen place above each branch point being enough: every place above a
branch point is a deck translate of the chosen one, so every inertia element is a conjugate of an
element of one of the chosen inertia groups. -/
theorem exists_places_normalClosure_iSup_geomInertia_sup_commutator_eq_top (L : LineCover) {r : ℕ}
    (t : Fin r → k) (hS : L.IsUnramifiedOutside (Set.range t)) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ Q : Fin r → Ideal (Bring L.M),
      (∀ i, (Q i).IsMaximal ∧ (Q i).LiesOver (placeP (t i))) ∧
        Subgroup.normalClosure (⋃ i, (geomInertia L.M (Q i) : Set L.deck)) ⊔ commutator L.deck
          = ⊤ := by
  choose Q hQmax hQover using fun i : Fin r => L.exists_place (t i)
  refine ⟨Q, fun i => ⟨hQmax i, hQover i⟩, eq_top_iff.mpr ?_⟩
  rw [← normalClosure_isInertiaAt_sup_commutator_eq_top L hinf]
  refine sup_le_sup_right ((Subgroup.normalClosure_le_normal ?_)) _
  rintro σ ⟨u, Q', hQ'max, hQ'over, hQ'in⟩
  by_cases h : ∃ i, t i = u
  · obtain ⟨i, rfl⟩ := h
    haveI := hQmax i
    haveI : (Q i).IsPrime := (hQmax i).isPrime
    haveI := hQover i
    haveI := hQ'max
    haveI : Q'.IsPrime := hQ'max.isPrime
    haveI := hQ'over
    obtain ⟨g, hg⟩ := exists_smul_eq_of_liesOver (Ω := L.M) (t i) (Q i) Q'
    rw [hg, geomInertia_smul] at hQ'in
    obtain ⟨y, hy, rfl⟩ := hQ'in
    exact (Subgroup.normalClosure_normal (s := ⋃ i, (geomInertia L.M (Q i) : Set L.deck))).conj_mem
      y (Subgroup.subset_normalClosure (Set.mem_iUnion.mpr ⟨i, hy⟩)) g
  · rw [hS u h σ ⟨Q', hQ'max, hQ'over, hQ'in⟩]
    exact one_mem _

/-- **A cover of the line whose deck group is a `p`-group, branched over at most two points, is
cyclic.** -/
theorem isCyclic_deck_of_isPGroup_of_unramified_outside_pair (L : LineCover) {p : ℕ}
    [Fact (Nat.Prime p)] (hp : IsPGroup p L.deck) (t₀ t₁ : k)
    (hS : L.IsUnramifiedOutside {t₀, t₁}) (hinf : L.IsUnramifiedAtInfinity) : IsCyclic L.deck :=
  haveI := hp.isNilpotent
  isCyclic_deck_of_isNilpotent_of_unramified_outside_pair L t₀ t₁ hS hinf

end Rigidity.RET
