/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.AbelianCycles
import InverseGalois.Rigidity.RET.InertiaGenerate
import InverseGalois.Rigidity.RET.InertiaLift

/-!
# Branch cycles modulo commutators, for an arbitrary cover of the line

The Galois subcover cut out by the commutator subgroup of the deck group has the abelianization as
its deck group, and the same branch locus.  That subcover is abelian, so it carries a full system
of distinguished branch cycles over the branch points, and each of those cycles lifts to a
distinguished inertia element of the original cover with the prescribed restriction.  The lifted
tuple generates the deck group modulo commutators and its ordered product is a commutator.

No hypothesis is placed on the deck group: this is the part of the converse direction of the
covers correspondence that is visible to abelian data.

## Main results

* `Rigidity.RET.exists_inertiaGens_mod_commutator` — an arbitrary cover of the line, unramified
  outside a tuple of points of the affine line and at infinity, has distinguished inertia elements
  over those points generating the deck group modulo commutators, with ordered product a
  commutator.
* `Rigidity.RET.isInertiaAt_mem_normalClosure` — every inertia element at a point lies in the
  normal closure of a distinguished inertia element there.
* `Rigidity.RET.normalClosure_range_eq_top_of_isInertiaGenAt` — distinguished inertia elements over
  the branch points generate the deck group as a normal subgroup.
* `Rigidity.RET.exists_branchCycles_mod_commutator` — the two generation statements and the
  product relation together.
* `Rigidity.RET.exists_generating_abelianization` — a cover unramified outside `r + 1` points and
  at infinity has abelianized deck group generated by `r` elements.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-- **An arbitrary cover of the line, unramified outside a tuple of points of the affine line and
at infinity, has distinguished inertia elements over those points which generate the deck group
modulo commutators and whose ordered product is a commutator.** -/
theorem exists_inertiaGens_mod_commutator (L : LineCover) {r : ℕ} (t : Fin r → k)
    (ht : Function.Injective t) (hout : L.IsUnramifiedOutside (Set.range t))
    (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin r → L.deck, (∀ i, L.IsInertiaGenAt (t i) (g i)) ∧
      Subgroup.closure (Set.range g) ⊔ commutator L.deck = ⊤ ∧
      (List.ofFn g).prod ∈ commutator L.deck := by
  classical
  let ab : L.deck →* Abelianization L.deck := Abelianization.of
  have hsurj : Function.Surjective ab := abelianization_of_surjective L
  let E : IntermediateField (RatFunc k) L.M := fixedField ab.ker
  -- the subcover cut out by the commutator subgroup is abelian, with the same branch locus
  have hcomm : ∀ a b : (L.sub E).deck, a * b = b * a := fun a b =>
    (descentEquiv ab hsurj).injective (by rw [map_mul, map_mul, mul_comm])
  obtain ⟨gA, hbcgs⟩ :=
    exists_branchCycleGenSystem_of_comm (L.sub E) hcomm t ht (hout.sub E) (hinf.sub E)
  -- lift its branch cycles to distinguished inertia elements upstairs
  choose g hgin hgres using fun i =>
    LineCover.IsInertiaGenAt.exists_lift L (E := E) (hbcgs.inertia i)
  -- the kernel of the restriction is exactly the commutator subgroup
  have hker : (L.subHom E).ker = commutator L.deck := by
    have hkab : ab.ker = commutator L.deck := QuotientGroup.ker_mk' _
    have h1 : ∀ σ : L.deck, L.subHom E σ = 1 ↔ ab σ = 1 := by
      intro σ
      constructor
      · intro h
        rw [← descentEquiv_apply ab hsurj σ, h, map_one]
      · intro h
        refine (descentEquiv ab hsurj).injective ?_
        rw [descentEquiv_apply, h, map_one]
    ext σ
    rw [MonoidHom.mem_ker, h1 σ, ← MonoidHom.mem_ker, hkab]
  refine ⟨g, hgin, ?_, ?_⟩
  · -- the lifted tuple generates modulo the kernel of the restriction
    have hmap : Subgroup.map (L.subHom E) (Subgroup.closure (Set.range g)) = ⊤ := by
      rw [MonoidHom.map_closure,
        show (L.subHom E) '' Set.range g = Set.range gA by
          rw [← Set.range_comp]; exact congrArg Set.range (funext hgres)]
      exact hbcgs.top
    rw [← hker, ← Subgroup.comap_map_eq, hmap, Subgroup.comap_top]
  · -- the ordered product restricts to the ordered product downstairs, which is trivial
    rw [← hker, MonoidHom.mem_ker, map_list_prod,
      show (List.ofFn g).map (L.subHom E) = List.ofFn gA by
        rw [List.map_ofFn]; exact congrArg List.ofFn (funext hgres)]
    exact hbcgs.prod

/-! ### Normal generation by the distinguished inertia elements -/

/-- The normal closure of a cyclic subgroup is the normal closure of a generator. -/
theorem normalClosure_zpowers_le {G : Type*} [Group G] (g : G) :
    Subgroup.normalClosure ((Subgroup.zpowers g : Subgroup G) : Set G)
      ≤ Subgroup.normalClosure ({g} : Set G) :=
  Subgroup.normalClosure_le_normal
    (SetLike.coe_subset_coe.mpr (Subgroup.zpowers_le.mpr (Subgroup.subset_normalClosure rfl)))

/-- **Every inertia element at a point lies in the normal closure of a distinguished inertia
element there.**  All the inertia groups above the point are conjugate, and the distinguished
element generates one of them. -/
theorem isInertiaAt_mem_normalClosure {L : LineCover} {t : k} {g σ : L.deck}
    (hg : L.IsInertiaGenAt t g) (hσ : L.IsInertiaAt t σ) :
    σ ∈ Subgroup.normalClosure ({g} : Set L.deck) := by
  obtain ⟨Q, hQmax, hQover, hQin⟩ := hg
  haveI := hQmax
  haveI := hQover
  have h1 : σ ∈ Subgroup.normalClosure {x : L.deck | L.IsInertiaAt t x} :=
    Subgroup.subset_normalClosure hσ
  rw [← normalClosure_geomInertia_eq_normalClosure L t Q, hQin] at h1
  exact normalClosure_zpowers_le g h1

/-- **Distinguished inertia elements over the branch points generate the deck group as a normal
subgroup.**  All inertia generates the deck group, and every inertia element is a conjugate of a
power of one of the chosen elements. -/
theorem normalClosure_range_eq_top_of_isInertiaGenAt (L : LineCover) {r : ℕ} {t : Fin r → k}
    (hout : L.IsUnramifiedOutside (Set.range t)) {g : Fin r → L.deck}
    (hg : ∀ i, L.IsInertiaGenAt (t i) (g i)) :
    Subgroup.normalClosure (Set.range g) = ⊤ := by
  refine eq_top_iff.mpr ?_
  rw [← closure_isInertiaAt_eq_top L, Subgroup.closure_le]
  rintro σ ⟨u, hσ⟩
  by_cases hu : u ∈ Set.range t
  · obtain ⟨i, rfl⟩ := hu
    have hsub : ({g i} : Set L.deck) ⊆ Set.range g :=
      Set.singleton_subset_iff.mpr (Set.mem_range_self i)
    exact Subgroup.normalClosure_mono hsub (isInertiaAt_mem_normalClosure (hg i) hσ)
  · rw [hout u hu σ hσ]
    exact one_mem _

/-- **An arbitrary cover of the line, unramified outside a tuple of points of the affine line and
at infinity, has distinguished inertia elements over those points which generate the deck group as
a normal subgroup, generate it modulo commutators, and have commutator ordered product.** -/
theorem exists_branchCycles_mod_commutator (L : LineCover) {r : ℕ} (t : Fin r → k)
    (ht : Function.Injective t) (hout : L.IsUnramifiedOutside (Set.range t))
    (hinf : L.IsUnramifiedAtInfinity) :
    ∃ g : Fin r → L.deck, (∀ i, L.IsInertiaGenAt (t i) (g i)) ∧
      Subgroup.normalClosure (Set.range g) = ⊤ ∧
      Subgroup.closure (Set.range g) ⊔ commutator L.deck = ⊤ ∧
      (List.ofFn g).prod ∈ commutator L.deck := by
  obtain ⟨g, hgin, hgtop, hgprod⟩ := exists_inertiaGens_mod_commutator L t ht hout hinf
  exact ⟨g, hgin, normalClosure_range_eq_top_of_isInertiaGenAt L hout hgin, hgtop, hgprod⟩

/-! ### The abelianized deck group needs one generator fewer than there are branch points -/

/-- **A cover of the line unramified outside `r + 1` points of the affine line and at infinity has
abelianized deck group generated by `r` elements.**  The branch cycles generate it, and the
product relation expresses the last of them through the others. -/
theorem exists_generating_abelianization (L : LineCover) {r : ℕ} (t : Fin (r + 1) → k)
    (ht : Function.Injective t) (hout : L.IsUnramifiedOutside (Set.range t))
    (hinf : L.IsUnramifiedAtInfinity) :
    ∃ h : Fin r → Abelianization L.deck, Subgroup.closure (Set.range h) = ⊤ := by
  classical
  obtain ⟨g, -, hgtop, hgprod⟩ := exists_inertiaGens_mod_commutator L t ht hout hinf
  let ab : L.deck →* Abelianization L.deck := Abelianization.of
  have hker : commutator L.deck ≤ ab.ker := (QuotientGroup.ker_mk' _).ge
  set h : Fin r → Abelianization L.deck := fun i => ab (g i.castSucc) with hh
  -- the images of all the branch cycles generate the abelianization
  have hall : Subgroup.closure (Set.range fun i => ab (g i)) = ⊤ := by
    have := congrArg (Subgroup.map ab) hgtop
    rw [Subgroup.map_sup, Subgroup.map_eq_bot_iff _ |>.mpr hker,
      Subgroup.map_top_of_surjective _ (abelianization_of_surjective L), sup_bot_eq,
      MonoidHom.map_closure, ← Set.range_comp] at this
    exact this
  -- the product relation writes the last one in terms of the others
  have hlast : ab (g (Fin.last r)) ∈ Subgroup.closure (Set.range h) := by
    have hone : ∏ i, ab (g i) = 1 := by
      have hk : ab (List.ofFn g).prod = 1 := MonoidHom.mem_ker.mp (hker hgprod)
      rwa [map_list_prod, List.map_ofFn, List.prod_ofFn] at hk
    rw [Fin.prod_univ_castSucc] at hone
    have hinv : ab (g (Fin.last r)) = (∏ i : Fin r, h i)⁻¹ := eq_inv_of_mul_eq_one_right hone
    rw [hinv]
    exact inv_mem (prod_mem fun i _ => Subgroup.subset_closure ⟨i, rfl⟩)
  refine ⟨h, eq_top_iff.mpr ?_⟩
  rw [← hall, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  induction i using Fin.lastCases with
  | last => exact hlast
  | cast j => exact Subgroup.subset_closure ⟨j, rfl⟩

end Rigidity.RET
