/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.BranchLocus
import InverseGalois.Rigidity.RET.LowRankRET

/-!
# The branch locus of a cover of the line

Unramifiedness has so far been expressed relative to a set of points chosen in advance.  Since the
set of points at which a cover ramifies is finite, that set can be used itself: it is the smallest
set outside which the cover is unramified, and every statement of the form "unramified outside `S`"
is the statement that it is contained in `S`.

With the branch locus available as an object, the low-rank theorems become statements about a
cover alone.  A cover with no branch points is trivial, one branch point (with nothing at infinity)
is still trivial, and two branch points force the deck group to be cyclic.

Counting the branch points bounds the deck group in both directions.  A cover unramified at
infinity with `r + 1` branch points has abelianized deck group generated by `r` elements, and the
deck group itself when it is nilpotent; conversely a deck group needing `r` generators forces
`r + 1` branch points.  For abelian groups the multi-point Kummer construction attains the bound,
so the number of branch points a group requires is exactly one more than the number of generators.

## Main results

* `Rigidity.RET.LineCover.branchLocus` — the set of points of the affine line over which the cover
  ramifies, and `Rigidity.RET.LineCover.finite_branchLocus`, its finiteness.
* `Rigidity.RET.LineCover.isUnramifiedOutside_iff_branchLocus_subset` — unramifiedness outside a
  set is containment of the branch locus in it.
* `Rigidity.RET.LineCover.branchLocus_eq_empty_iff` — a cover of the affine line with no branch
  points is trivial.
* `Rigidity.RET.LineCover.isCyclic_deck_of_branchLocus_card_le_two` — at most two branch points
  force a cyclic deck group.
* `Rigidity.RET.exists_generating_abelianization_of_card` — the abelianized deck group of a cover
  unramified at infinity is generated by one fewer element than the cover has branch points.
* `Rigidity.RET.two_add_le_card_branchLocus_of_comm` — an abelian cover whose deck group needs `r`
  generators has at least `r + 1` branch points.
* `Rigidity.RET.exists_generating_of_comm_of_card_le` — the generation bound in the form of an
  upper bound on the number of branch points, which is the form a coordinate move leaves intact.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-- A finite set of points of the line is contained in the range of an injective tuple of any
length at least its cardinality, because the line has infinitely many points. -/
theorem exists_range_superset_of_card_le {S : Set k} (hS : S.Finite) {m : ℕ}
    (hm : hS.toFinset.card ≤ m) :
    ∃ t : Fin m → k, Function.Injective t ∧ S ⊆ Set.range t := by
  classical
  obtain ⟨F, hsub, hcard⟩ := Infinite.exists_superset_card_eq hS.toFinset m hm
  refine ⟨fun i => (F.equivFin.symm (Fin.cast hcard.symm i) : k), ?_, ?_⟩
  · exact Subtype.coe_injective.comp
      (F.equivFin.symm.injective.comp (Fin.cast_injective hcard.symm))
  · intro u hu
    have huF : u ∈ F := hsub (hS.mem_toFinset.mpr hu)
    exact ⟨Fin.cast hcard (F.equivFin ⟨u, huF⟩), by simp⟩

namespace LineCover

/-- The **branch locus** of a cover of the line: the points of the affine line at which some
nontrivial deck transformation lies in an inertia group. -/
def branchLocus (L : LineCover) : Set k := {t : k | ∃ σ : L.deck, σ ≠ 1 ∧ L.IsInertiaAt t σ}

/-- **A cover is unramified outside a set exactly when its branch locus is contained in it.** -/
theorem isUnramifiedOutside_iff_branchLocus_subset (L : LineCover) (S : Set k) :
    L.IsUnramifiedOutside S ↔ L.branchLocus ⊆ S := by
  constructor
  · rintro h u ⟨σ, hσ1, hσ⟩
    by_contra hu
    exact hσ1 (h u hu σ hσ)
  · intro h u hu σ hσ
    by_contra hσ1
    exact hu (h ⟨σ, hσ1, hσ⟩)

/-- **A cover is unramified outside its branch locus**, which is therefore the least set with that
property. -/
theorem isUnramifiedOutside_branchLocus (L : LineCover) :
    L.IsUnramifiedOutside L.branchLocus :=
  (L.isUnramifiedOutside_iff_branchLocus_subset _).mpr subset_rfl

/-- **The branch locus is finite.** -/
theorem finite_branchLocus (L : LineCover) : L.branchLocus.Finite := by
  obtain ⟨S, hSfin, hS⟩ := L.exists_unramifiedOutside_finite
  exact hSfin.subset ((L.isUnramifiedOutside_iff_branchLocus_subset S).mp hS)

/-- **A cover of the line with no branch points is trivial**, and conversely. -/
theorem branchLocus_eq_empty_iff (L : LineCover) :
    L.branchLocus = ∅ ↔ Subsingleton L.deck := by
  constructor
  · intro h
    refine subsingleton_deck_of_unramifiedOutside_empty L ?_
    rw [← h]
    exact L.isUnramifiedOutside_branchLocus
  · intro h
    refine Set.eq_empty_iff_forall_notMem.mpr fun u hu => ?_
    obtain ⟨σ, hσ1, -⟩ := hu
    exact hσ1 (Subsingleton.elim σ 1)

/-- **A subcover branches only where the cover does.** -/
theorem branchLocus_sub_subset (L : LineCover) (E : IntermediateField (RatFunc k) L.M)
    [Normal (RatFunc k) E] : (L.sub E).branchLocus ⊆ L.branchLocus :=
  ((L.sub E).isUnramifiedOutside_iff_branchLocus_subset _).mp
    (L.isUnramifiedOutside_branchLocus.sub E)

/-! ### Covers with few branch points -/

/-- **A cover of the line with at most one branch point, unramified at infinity, is trivial.** -/
theorem subsingleton_deck_of_branchLocus_card_le_one (L : LineCover)
    (hcard : L.finite_branchLocus.toFinset.card ≤ 1) (hinf : L.IsUnramifiedAtInfinity) :
    Subsingleton L.deck := by
  obtain ⟨t, -, hsub⟩ := exists_range_superset_of_card_le L.finite_branchLocus hcard
  have hrange : Set.range t = {t 0} := by
    ext u
    exact ⟨by rintro ⟨i, rfl⟩; rw [Subsingleton.elim i 0]; rfl, by rintro rfl; exact ⟨0, rfl⟩⟩
  refine subsingleton_deck_of_unramifiedOutside_singleton L (t 0) ?_ hinf
  rw [← hrange]
  exact (L.isUnramifiedOutside_iff_branchLocus_subset _).mpr hsub

/-- **A cover of the line with at most two branch points, unramified at infinity, has cyclic deck
group.** -/
theorem isCyclic_deck_of_branchLocus_card_le_two (L : LineCover)
    (hcard : L.finite_branchLocus.toFinset.card ≤ 2) (hinf : L.IsUnramifiedAtInfinity) :
    IsCyclic L.deck := by
  obtain ⟨t, -, hsub⟩ := exists_range_superset_of_card_le L.finite_branchLocus hcard
  exact isCyclic_deck_of_unramifiedOutside_range_two L t
    ((L.isUnramifiedOutside_iff_branchLocus_subset _).mpr hsub) hinf

/-- **A cover of the line with at most two branch points, unramified at infinity, has a system of
distinguished branch cycles over a pair of points containing its branch locus.** -/
theorem exists_branchCycleGenSystem_of_branchLocus_card_le_two (L : LineCover)
    (hcard : L.finite_branchLocus.toFinset.card ≤ 2) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ (t : Fin 2 → k) (g : Fin 2 → L.deck),
      Function.Injective t ∧ L.IsBranchCycleGenSystem t g := by
  obtain ⟨t, ht, hsub⟩ := exists_range_superset_of_card_le L.finite_branchLocus hcard
  have hout : L.IsUnramifiedOutside (Set.range t) :=
    (L.isUnramifiedOutside_iff_branchLocus_subset _).mpr hsub
  obtain ⟨g, hg⟩ := exists_branchCycleGenSystem_pair L t ht hout hinf
  exact ⟨t, g, ht, hg⟩

end LineCover

/-! ### Counting the branch points -/

/-- A finite set of points of the line is the range of an injective tuple indexed by its own
cardinality. -/
theorem exists_fin_card_range {S : Set k} (hS : S.Finite) :
    ∃ t : Fin hS.toFinset.card → k, Function.Injective t ∧ Set.range t = S := by
  classical
  refine ⟨fun i => (hS.toFinset.equivFin.symm i : k),
    Subtype.coe_injective.comp hS.toFinset.equivFin.symm.injective, ?_⟩
  ext u
  constructor
  · rintro ⟨i, rfl⟩
    exact hS.mem_toFinset.mp (hS.toFinset.equivFin.symm i).2
  · intro hu
    exact ⟨hS.toFinset.equivFin ⟨u, hS.mem_toFinset.mpr hu⟩, by simp⟩

namespace LineCover

/-- A tuple of distinguished branch cycles indexed by the branch points themselves. -/
theorem exists_branchLocus_unramifiedOutside (L : LineCover) :
    ∃ t : Fin L.finite_branchLocus.toFinset.card → k,
      Function.Injective t ∧ L.IsUnramifiedOutside (Set.range t) := by
  obtain ⟨t, ht, hrange⟩ := exists_fin_card_range L.finite_branchLocus
  exact ⟨t, ht, by rw [hrange]; exact L.isUnramifiedOutside_branchLocus⟩

end LineCover

/-- **The abelianized deck group of a cover of the line unramified at infinity is generated by one
fewer element than the cover has branch points.**  This holds for every deck group: the branch
cycles generate the abelianization, and their product is trivial there, so the last of them is
redundant. -/
theorem exists_generating_abelianization_of_card (L : LineCover)
    (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hcard : L.finite_branchLocus.toFinset.card = r + 1) :
    ∃ h : Fin r → Abelianization L.deck, Subgroup.closure (Set.range h) = ⊤ := by
  have h := L.exists_branchLocus_unramifiedOutside
  rw [hcard] at h
  obtain ⟨t, ht, hout⟩ := h
  exact exists_generating_abelianization L t ht hout hinf

/-- **A cover of the line with nilpotent deck group, unramified at infinity, has deck group
generated by one fewer element than it has branch points.**  For a nilpotent group generation
modulo commutators is generation, so the bound on the abelianization is a bound on the group. -/
theorem exists_generating_of_isNilpotent_of_card (L : LineCover) [Group.IsNilpotent L.deck]
    (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hcard : L.finite_branchLocus.toFinset.card = r + 1) :
    ∃ s : Fin r → L.deck, Subgroup.closure (Set.range s) = ⊤ := by
  have h := L.exists_branchLocus_unramifiedOutside
  rw [hcard] at h
  obtain ⟨t, ht, hout⟩ := h
  obtain ⟨g, -, hgtop, -⟩ := exists_branchCycles_generating_of_isNilpotent L t ht hout hinf
  exact ⟨fun i => g i.castSucc, hgtop⟩

/-- **A cover of the line with abelian deck group, unramified at infinity, has deck group generated
by one fewer element than it has branch points.**  Together with the existence direction — an
abelian group generated by `r` elements is the deck group of a cover branched over `r + 1`
prescribed points — this determines exactly which abelian groups occur over how many points. -/
theorem exists_generating_of_comm_of_card (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a)
    (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hcard : L.finite_branchLocus.toFinset.card = r + 1) :
    ∃ s : Fin r → L.deck, Subgroup.closure (Set.range s) = ⊤ := by
  have h := L.exists_branchLocus_unramifiedOutside
  rw [hcard] at h
  obtain ⟨t, ht, hout⟩ := h
  obtain ⟨g, hg⟩ := exists_branchCycleGenSystem_of_comm L hab t ht hout hinf
  exact ⟨fun i => g i.castSucc, hg.closure_castSucc_eq_top⟩

/-! ### Branch cycles of a quotient cover -/

/-- **A system of branch cycles restricts to a system of branch cycles on every Galois subcover.**
Each distinguished inertia element restricts to one at the same point, the ordered product is
carried along by a homomorphism, and generation survives because restriction of automorphisms is
surjective. -/
theorem LineCover.IsBranchCycleGenSystem.sub {L : LineCover} {r : ℕ} {t : Fin r → k}
    {g : Fin r → L.deck} (hg : L.IsBranchCycleGenSystem t g)
    (E : IntermediateField (RatFunc k) L.M) [Normal (RatFunc k) E] :
    (L.sub E).IsBranchCycleGenSystem t fun i => L.subHom E (g i) where
  inertia i := (hg.inertia i).restrict
  top := by
    have : (Set.range fun i => L.subHom E (g i)) = L.subHom E '' Set.range g := by
      rw [← Set.range_comp]; rfl
    rw [this, ← MonoidHom.map_closure, hg.top,
      Subgroup.map_top_of_surjective _ (L.subHom_surjective E)]
  prod := by
    have : (List.ofFn fun i => L.subHom E (g i)) = (List.ofFn g).map (L.subHom E) := by
      rw [List.map_ofFn]; rfl
    rw [this, ← MonoidHom.map_list_prod, hg.prod, map_one]

/-! ### Covers branched over exactly a prescribed set of points -/

/-- **A cover unramified outside a tuple of points, with nontrivial inertia at each of them,
branches over exactly those points.** -/
theorem LineCover.branchLocus_eq_range (L : LineCover) {r : ℕ} {t : Fin r → k}
    (hout : L.IsUnramifiedOutside (Set.range t))
    (hne : ∀ i, ∃ σ : L.deck, σ ≠ 1 ∧ L.IsInertiaAt (t i) σ) :
    L.branchLocus = Set.range t := by
  refine subset_antisymm ((L.isUnramifiedOutside_iff_branchLocus_subset _).mp hout) ?_
  rintro _ ⟨i, rfl⟩
  exact hne i

/-- **Such a cover has exactly as many branch points as the tuple has entries**, the points being
distinct. -/
theorem LineCover.card_branchLocus_eq (L : LineCover) {r : ℕ} {t : Fin r → k}
    (ht : Function.Injective t) (hout : L.IsUnramifiedOutside (Set.range t))
    (hne : ∀ i, ∃ σ : L.deck, σ ≠ 1 ∧ L.IsInertiaAt (t i) σ) :
    L.finite_branchLocus.toFinset.card = r := by
  rw [← Set.ncard_eq_toFinset_card _ L.finite_branchLocus, L.branchLocus_eq_range hout hne,
    Set.ncard_range_of_injective ht]
  simp

/-! ### How many branch points a cover needs -/

/-- Generation transports along an isomorphism of groups. -/
theorem closure_range_mulEquiv_eq_top {G H : Type*} [Group G] [Group H] (e : G ≃* H) {r : ℕ}
    {s : Fin r → G} (hs : Subgroup.closure (Set.range s) = ⊤) :
    Subgroup.closure (Set.range fun i => e (s i)) = ⊤ := by
  have hrange : (Set.range fun i => e (s i)) = (e : G →* H) '' Set.range s := by
    rw [← Set.range_comp]; rfl
  rw [hrange, ← MonoidHom.map_closure, hs,
    Subgroup.map_top_of_surjective _ e.surjective]

/-- A group generated by `m` elements is generated by any larger number of elements. -/
theorem exists_generating_of_le {G : Type*} [Group G] {m r : ℕ} (hmr : m ≤ r) {s : Fin m → G}
    (hs : Subgroup.closure (Set.range s) = ⊤) :
    ∃ s' : Fin r → G, Subgroup.closure (Set.range s') = ⊤ := by
  classical
  refine ⟨fun i => if h : (i : ℕ) < m then s ⟨i, h⟩ else 1, eq_top_iff.mpr ?_⟩
  rw [← hs, Subgroup.closure_le]
  rintro _ ⟨j, rfl⟩
  refine Subgroup.subset_closure ⟨⟨j, lt_of_lt_of_le j.2 hmr⟩, ?_⟩
  simp

/-- **A bound on the number of branch points bounds the number of generators.**  The exact count
`m + 1` is not needed: a cover with at most `r + 1` branch points has deck group generated by `r`
elements, and if it has none at all the deck group is trivial. -/
theorem exists_generating_of_card_le (L : LineCover)
    (hbound : ∀ m : ℕ, L.finite_branchLocus.toFinset.card = m + 1 →
      ∃ s : Fin m → L.deck, Subgroup.closure (Set.range s) = ⊤)
    {r : ℕ} (hcard : L.finite_branchLocus.toFinset.card ≤ r + 1) :
    ∃ s : Fin r → L.deck, Subgroup.closure (Set.range s) = ⊤ := by
  rcases hc : L.finite_branchLocus.toFinset.card with _ | m
  · haveI : Subsingleton L.deck :=
      (L.branchLocus_eq_empty_iff).mp
        (Set.Finite.toFinset_eq_empty.mp (Finset.card_eq_zero.mp hc))
    exact ⟨fun _ => 1, (Subgroup.eq_top_iff' _).mpr fun x => by
      rw [Subsingleton.elim x 1]; exact one_mem _⟩
  · obtain ⟨s, hs⟩ := hbound m hc
    exact exists_generating_of_le (r := r) (by omega) hs

/-- **An abelian deck group is generated by one fewer element than the cover has branch points**,
in the form of an upper bound on the number of branch points. -/
theorem exists_generating_of_comm_of_card_le (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hcard : L.finite_branchLocus.toFinset.card ≤ r + 1) :
    ∃ s : Fin r → L.deck, Subgroup.closure (Set.range s) = ⊤ :=
  exists_generating_of_card_le L
    (fun _ hc => exists_generating_of_comm_of_card L hab hinf hc) hcard

/-- **A nilpotent deck group is generated by one fewer element than the cover has branch points**,
in the form of an upper bound on the number of branch points. -/
theorem exists_generating_of_isNilpotent_of_card_le (L : LineCover) [Group.IsNilpotent L.deck]
    (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hcard : L.finite_branchLocus.toFinset.card ≤ r + 1) :
    ∃ s : Fin r → L.deck, Subgroup.closure (Set.range s) = ⊤ :=
  exists_generating_of_card_le L
    (fun _ hc => exists_generating_of_isNilpotent_of_card L hinf hc) hcard

/-- **A cover needs at least one more branch point than its deck group needs generators.**  The
hypothesis is the counting bound in the other direction — over `m + 1` branch points the deck group
is generated by `m` elements — which holds for abelian and for nilpotent deck groups. -/
theorem two_add_le_card_branchLocus (L : LineCover)
    (hbound : ∀ m : ℕ, L.finite_branchLocus.toFinset.card = m + 1 →
      ∃ s : Fin m → L.deck, Subgroup.closure (Set.range s) = ⊤)
    {r : ℕ} (hgen : ∀ s : Fin r → L.deck, Subgroup.closure (Set.range s) ≠ ⊤) :
    r + 2 ≤ L.finite_branchLocus.toFinset.card := by
  by_contra hlt
  push_neg at hlt
  rcases hcard : L.finite_branchLocus.toFinset.card with _ | m
  · -- no branch points: the cover is trivial, so every tuple generates
    haveI : Subsingleton L.deck :=
      (L.branchLocus_eq_empty_iff).mp
        (Set.Finite.toFinset_eq_empty.mp (Finset.card_eq_zero.mp hcard))
    exact hgen (fun _ => 1) ((Subgroup.eq_top_iff' _).mpr fun x => by
      rw [Subsingleton.elim x 1]; exact one_mem _)
  · obtain ⟨s, hs⟩ := hbound m hcard
    obtain ⟨s', hs'⟩ := exists_generating_of_le (r := r) (by omega) hs
    exact hgen s' hs'

/-- **An abelian cover of the line unramified at infinity has at least one more branch point than
its deck group has generators.**  With the multi-point Kummer construction, which realizes a group
generated by `r` elements over `r + 1` prescribed points, this is sharp. -/
theorem two_add_le_card_branchLocus_of_comm (L : LineCover)
    (hab : ∀ a b : L.deck, a * b = b * a) (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hgen : ∀ s : Fin r → L.deck, Subgroup.closure (Set.range s) ≠ ⊤) :
    r + 2 ≤ L.finite_branchLocus.toFinset.card :=
  two_add_le_card_branchLocus L
    (fun _ hcard => exists_generating_of_comm_of_card L hab hinf hcard) hgen

/-- **A nilpotent cover of the line unramified at infinity has at least one more branch point than
its deck group has generators.** -/
theorem two_add_le_card_branchLocus_of_isNilpotent (L : LineCover) [Group.IsNilpotent L.deck]
    (hinf : L.IsUnramifiedAtInfinity) {r : ℕ}
    (hgen : ∀ s : Fin r → L.deck, Subgroup.closure (Set.range s) ≠ ⊤) :
    r + 2 ≤ L.finite_branchLocus.toFinset.card :=
  two_add_le_card_branchLocus L
    (fun _ hcard => exists_generating_of_isNilpotent_of_card L hinf hcard) hgen

end Rigidity.RET
