/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Unramified
import InverseGalois.Rigidity.RET.Twist
import InverseGalois.Rigidity.RET.Inversion
import InverseGalois.Rigidity.RET.MoveInfinity
import InverseGalois.Rigidity.RET.ExistenceLowRank
import InverseGalois.Rigidity.RET.Transfer.Datum
import InverseGalois.Rigidity.RET.Transfer.DatumDescent
import InverseGalois.Rigidity.RET.Transfer.Complex

/-!
# Realizing a group as the deck group of a cover with a prescribed branch locus

A finite group with a generating product-one `r`-tuple is the deck group of a cover of the line
over `ℚ̄` unramified outside `r` prescribed points and infinity.  This is the existence half of the
Riemann Existence Theorem, stripped of all bookkeeping: no branch cycles, no inertia, only the
group, the cover and the branch locus.

The two hypotheses on the tuple are the two relations that hold among the loops of the punctured
sphere — they generate, because the cover is connected, and their ordered product is contractible —
so a group admitting no such tuple is the deck group of no such cover.  The tuple itself does not
appear in the conclusion: what it certifies is that the group is *small enough* to be generated by
`r` loops subject to one relation, and the branch cycles of the resulting cover need bear no
relation to it.  Recovering a cover whose branch cycles are the prescribed tuple is a separate step
(`Rigidity.RET.geomRETExistence_of_isDeckGroupOver`, `RET/UniversalTuple.lean`).

## How the cover is built

The product-one relation is not used to build anything: it is spent, at the very start, on
*deleting* one of the `r` points.  The remaining `r - 1` points are inverted about the deleted one,
so the deleted point becomes the point at infinity and the truncated tuple — which still generates,
its missing entry being the inverse of the product of the others — no longer has to satisfy any
relation.  A generating tuple with no relation is exactly a surjection from the free fundamental
group of the punctured plane (`RET/Pi1/Topological/PuncturedPlane.lean`), hence a connected
topological covering of the punctured plane (`Rigidity.RET.exists_coverDatum_of_generating`), and
`RET/Analytic/` turns that covering into an equation over `ℂ` — a `Rigidity.RET.CoverDatum`.

A `CoverDatum` is a finite list of polynomial identities and non-vanishing conditions, so it
descends from `ℂ` to `ℚ̄` by specialization once the branch points already lie in `ℚ̄`
(`Rigidity.RET.exists_coverDatum_descend`); over `ℚ̄` it names a cover of the line
(`Rigidity.RET.exists_lineCover_of_coverDatum`).  Inverting the coordinate back leaves infinity
unramified — the origin was not a branch point downstairs — and translating restores the deleted
point.  See Grothendieck, *SGA 1*, Exp. XIII; Völklein, *Groups as Galois Groups*, Thm 2.13 and §4;
Serre, *Topics in Galois Theory*, §6.

## Main results

* `Rigidity.RET.exists_lineCover_of_generating` — a finite group generated by an `m`-tuple is the
  deck group of a cover branched inside `m` prescribed points.
* `Rigidity.RET.exists_lineCover_of_prodOne` — a finite group with a generating product-one
  `r`-tuple is the deck group of a cover branched inside `r` prescribed points and infinity.
-/

noncomputable section

namespace Rigidity.RET

open GeomAKLB

/-- An embedding of the algebraic closure of the rationals into the complex numbers. -/
def kToComplex : k →ₐ[ℚ] ℂ := IsAlgClosed.lift (R := ℚ) (S := k) (M := ℂ)

/-- The complex numbers as an algebra over the algebraic closure of the rationals. -/
def kToComplexAlgebra : Algebra k ℂ := (kToComplex : k →+* ℂ).toAlgebra

attribute [local instance] kToComplexAlgebra

theorem algebraMap_kToComplex_injective : Function.Injective (algebraMap k ℂ) :=
  (algebraMap k ℂ).injective

/-- Re-indexing a family along a bijection leaves its range unchanged. -/
theorem range_comp_equiv {α β γ : Type*} (e : α ≃ β) (f : β → γ) :
    (Set.range fun i => f (e i)) = Set.range f := by
  rw [show (fun i => f (e i)) = f ∘ e from rfl, Set.range_comp, Equiv.range_eq_univ,
    Set.image_univ]

/-- **A finite group generated by an `m`-tuple occurs as the deck group of a cover of the line over
`ℚ̄` unramified outside `m` prescribed points.** -/
theorem exists_lineCover_of_generating {m : ℕ} {u : Fin m → k} (hu : Function.Injective u)
    {G : Type} [Group G] [Finite G] (g : Fin m → G)
    (htop : Subgroup.closure (Set.range g) = ⊤) :
    ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.IsUnramifiedOutside (Set.range u) := by
  classical
  have hinj : Function.Injective (algebraMap k ℂ) := algebraMap_kToComplex_injective
  have hwinj : Function.Injective fun i => algebraMap k ℂ (u i) := hinj.comp hu
  set S : Finset ℂ := Finset.image (fun i => algebraMap k ℂ (u i)) Finset.univ with hS
  have hcard : S.card = m := by
    rw [hS, Finset.card_image_of_injective _ hwinj, Finset.card_univ, Fintype.card_fin]
  -- re-index the points along the equality of cardinalities
  set ι : Fin S.card ≃ Fin m := finCongr hcard with hι
  have hptrange : Set.range (fun i => algebraMap k ℂ (u (ι i))) = (S : Set ℂ) := by
    rw [range_comp_equiv ι fun i => algebraMap k ℂ (u i), hS]
    simp [Finset.coe_image]
  have hgtop : Subgroup.closure (Set.range fun i => g (ι i)) = ⊤ := by
    rw [range_comp_equiv ι g]; exact htop
  obtain ⟨Dt⟩ := exists_coverDatum_of_generating S (fun i => algebraMap k ℂ (u (ι i))) hptrange
    (fun i => g (ι i)) hgtop
  obtain ⟨D⟩ := exists_coverDatum_descend (K := ℂ) (fun i => u (ι i)) Dt
  obtain ⟨L, he, hout⟩ := exists_lineCover_of_coverDatum D
  exact ⟨L, he, by rwa [range_comp_equiv ι u] at hout⟩

/-- **A finite group with a generating product-one `r`-tuple occurs as the deck group of a cover of
the line over `ℚ̄` unramified outside `r` prescribed points and infinity.** -/
theorem exists_lineCover_of_prodOne {r : ℕ} {t : Fin r → k} (ht : Function.Injective t)
    {G : Type} [Group G] [Finite G] (g : Fin r → G) (hprod : (List.ofFn g).prod = 1)
    (htop : Subgroup.closure (Set.range g) = ⊤) :
    ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.IsUnramifiedOutside (Set.range t) ∧
      L.IsUnramifiedAtInfinity := by
  classical
  by_cases hr : r ≤ 2
  · obtain ⟨L, e, hout, hinf, -⟩ := exists_cover_of_le_two hr t ht g hprod htop
    exact ⟨L, ⟨e⟩, hout, hinf⟩
  push_neg at hr
  obtain ⟨m, rfl⟩ : ∃ m, r = m + 1 := ⟨r - 1, by omega⟩
  -- the last branch point is moved to infinity: the remaining ones are inverted about it
  have hne : ∀ i : Fin m, t i.castSucc - t (Fin.last m) ≠ 0 := by
    intro i hi
    exact (Fin.castSucc_lt_last i).ne (ht (sub_eq_zero.1 hi))
  have hune : ∀ i : Fin m, (t i.castSucc - t (Fin.last m))⁻¹ ≠ 0 := fun i => inv_ne_zero (hne i)
  have huinj : Function.Injective fun i : Fin m => (t i.castSucc - t (Fin.last m))⁻¹ := by
    intro i j hij
    exact Fin.castSucc_injective m (ht (sub_left_inj.1 (inv_injective hij)))
  -- the truncated tuple still generates, since the last entry is the inverse of its product
  have hg₀top : Subgroup.closure (Set.range fun i : Fin m => g i.castSucc) = ⊤ := by
    refine le_antisymm le_top ?_
    rw [← htop, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    have hmem : ∀ j : Fin m, g j.castSucc ∈
        Subgroup.closure (Set.range fun i : Fin m => g i.castSucc) :=
      fun j => Subgroup.subset_closure ⟨j, rfl⟩
    rcases Fin.eq_castSucc_or_eq_last i with ⟨j, rfl⟩ | rfl
    · exact hmem j
    · have hlist : (List.ofFn fun i : Fin m => g i.castSucc).prod * g (Fin.last m) = 1 := by
        rw [← hprod, List.ofFn_succ_last]
        simp
      have hgl : g (Fin.last m) = ((List.ofFn fun i : Fin m => g i.castSucc).prod)⁻¹ :=
        (inv_eq_iff_mul_eq_one.2 hlist).symm
      rw [hgl]
      refine Subgroup.inv_mem _ (Subgroup.list_prod_mem _ ?_)
      intro x hx
      obtain ⟨j, rfl⟩ := List.mem_ofFn.1 hx
      exact hmem j
  obtain ⟨P, ⟨e⟩, hPout⟩ := exists_lineCover_of_generating huinj (fun i => g i.castSucc) hg₀top
  -- invert the coordinate: infinity becomes clean and the branch points return to their places
  have hP₁out : (P.twist invSubst.toRingEquiv).IsUnramifiedOutside
      ({(0 : k)} ∪ Set.range fun i : Fin m => t i.castSucc - t (Fin.last m)) := by
    have h := LineCover.isUnramifiedOutside_twist_inv_ne_zero P hPout
    rw [setOf_inv_mem_range hune] at h
    convert h using 3
    exact funext fun i => (inv_inv _).symm
  have hP₁inf : (P.twist invSubst.toRingEquiv).IsUnramifiedAtInfinity :=
    LineCover.isUnramifiedAtInfinity_twist_inv P
      (isUnramifiedOutside_compl_zero_of_range hune hPout)
  -- translate the origin back to the last branch point
  refine ⟨(P.twist invSubst.toRingEquiv).twist (translateSubst (t (Fin.last m))),
    ⟨((P.twist invSubst.toRingEquiv).twistDeckEquiv (translateSubst (t (Fin.last m)))).symm.trans
      ((P.twistDeckEquiv invSubst.toRingEquiv).symm.trans e)⟩, ?_,
    LineCover.IsUnramifiedAtInfinity.twist_translate _ hP₁inf⟩
  have h := LineCover.IsUnramifiedOutside.twist_translate (t (Fin.last m)) hP₁out
  have hset : ((· - t (Fin.last m)) ⁻¹'
      ({(0 : k)} ∪ Set.range fun i : Fin m => t i.castSucc - t (Fin.last m))) = Set.range t := by
    ext z
    simp only [Set.mem_preimage, Set.mem_union, Set.mem_singleton_iff, Set.mem_range,
      sub_eq_zero, sub_left_inj]
    constructor
    · rintro (rfl | ⟨i, rfl⟩)
      · exact ⟨Fin.last m, rfl⟩
      · exact ⟨i.castSucc, rfl⟩
    · rintro ⟨j, rfl⟩
      rcases Fin.eq_castSucc_or_eq_last j with ⟨i, rfl⟩ | rfl
      · exact Or.inr ⟨i, rfl⟩
      · exact Or.inl rfl
  rwa [hset] at h

end Rigidity.RET

end
