/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Unramified
import InverseGalois.Rigidity.RET.Twist

/-!
# Realizing a group as the deck group of a cover with a prescribed branch locus

A finite group with a generating product-one `r`-tuple is the deck group of a cover of the line
over `ℚ̄` unramified outside `r` prescribed points and infinity.  This is the existence half of the
Riemann Existence Theorem, stripped of all bookkeeping: no branch cycles, no inertia, only the
group, the cover and the branch locus.

The two hypotheses on the tuple are the two relations that hold among the loops of the punctured
sphere — they generate, because the cover is connected, and their ordered product is contractible —
so a group admitting no such tuple is the deck group of no such cover.  The tuple itself does not
appear in the conclusion: what it certifies is that the group is *small enough* to be generated by
`r` loops subject to one relation, and the branch cycles of the resulting cover need bear no
relation to it.  Recovering a cover whose branch cycles are the prescribed tuple is a separate step
(`Rigidity.RET.geomRETExistence_of_isDeckGroupOver`, `RET/UniversalTuple.lean`).

Over `ℂ` the statement is covering-space theory together with the theorem of Grauert–Remmert that a
finite topological cover of a punctured Riemann surface, tame at the punctures, is the
analytification of an algebraic one; the constant field `ℚ̄` is reached from `ℂ` by the Lefschetz
principle.  See Grothendieck, *SGA 1*, Exp. XIII; Völklein, *Groups as Galois Groups*, Thm 2.13 and
§4; Serre, *Topics in Galois Theory*, §6.

## Main results

* `Rigidity.RET.exists_lineCover_of_prodOne` — a finite group with a generating product-one
  `r`-tuple is the deck group of a cover branched inside `r` prescribed points and infinity.
-/

noncomputable section

namespace Rigidity.RET

open GeomAKLB

/-- **A finite group with a generating product-one `r`-tuple occurs as the deck group of a cover of
the line over `ℚ̄` unramified outside `r` prescribed points and infinity.** -/
theorem exists_lineCover_of_prodOne {r : ℕ} {t : Fin r → k} (ht : Function.Injective t)
    {G : Type} [Group G] [Finite G] (g : Fin r → G) (hprod : (List.ofFn g).prod = 1)
    (htop : Subgroup.closure (Set.range g) = ⊤) :
    ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.IsUnramifiedOutside (Set.range t) ∧
      L.IsUnramifiedAtInfinity :=
  sorry

end Rigidity.RET

end
