/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.KummerNormalForm

/-!
# Every cyclic cover of the line is a multi-point Kummer cover

A cyclic extension of degree `n` of a field containing the `n`-th roots of unity is generated by an
`n`-th root of one of its elements (Kummer theory).  Over `ℚ̄(T)` that element can be normalized,
modulo `n`-th powers, to a product of linear polynomials with exponents `< n`
(`RET/KummerNormalForm.lean`).  Hence every cover of the line with cyclic deck group *is* a
multi-point Kummer cover `wⁿ = ∏ᵢ (T - tᵢ)^{eᵢ}` — the covers whose local theory is developed in
`RET/MultiKummer.lean` and `RET/MultiKummerInertia.lean`.

## Main results

* `Rigidity.RET.exists_multiKummer_model` — a cover of the line with cyclic deck group is the
  splitting field of the irreducible polynomial `Xⁿ - ∏ᵢ (T - tᵢ)^{eᵢ}` for distinct points `tᵢ`
  and exponents `eᵢ < n`.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB Module

/-- **A cover of the line with cyclic deck group is a multi-point Kummer cover.**  Kummer theory
provides a radical generator, and the radicand is normalized modulo `n`-th powers to a product of
linear polynomials with exponents smaller than the degree.  The radical generator generates the
cover, so the polynomial it satisfies is its minimal polynomial, hence irreducible. -/
theorem exists_multiKummer_model (L : LineCover) [IsCyclic L.deck] :
    ∃ (r : ℕ) (t : Fin r → k) (e : Fin r → ℕ),
      Function.Injective t ∧ (∀ i, e i < finrank (RatFunc k) L.M) ∧
      Irreducible (X ^ finrank (RatFunc k) L.M -
          C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) ∧
      IsSplittingField (RatFunc k) L.M
        (X ^ finrank (RatFunc k) L.M -
          C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) := by
  have hnpos : 0 < finrank (RatFunc k) L.M := finrank_pos
  haveI : NeZero (finrank (RatFunc k) L.M) := ⟨hnpos.ne'⟩
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k (finrank (RatFunc k) L.M)
  have hK : (primitiveRoots (finrank (RatFunc k) L.M) (RatFunc k)).Nonempty :=
    ⟨algebraMap k (RatFunc k) ζ₀, (mem_primitiveRoots hnpos).mpr
      (hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective)⟩
  -- a radical generator with a *nonzero* radicand gives the model
  have key : ∀ (β : L.M) (c : RatFunc k), c ≠ 0 →
      algebraMap (RatFunc k) L.M c = β ^ finrank (RatFunc k) L.M →
      (RatFunc k)⟮β⟯ = ⊤ →
      ∃ (r : ℕ) (t : Fin r → k) (e : Fin r → ℕ),
        Function.Injective t ∧ (∀ i, e i < finrank (RatFunc k) L.M) ∧
        Irreducible (X ^ finrank (RatFunc k) L.M -
            C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) ∧
        IsSplittingField (RatFunc k) L.M
          (X ^ finrank (RatFunc k) L.M -
            C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) := by
    intro β c hc hβ hβtop
    obtain ⟨r, t, e, b, hinj, hlt, hb, hval⟩ := exists_multiA_mul_pow hnpos hc
    have hB : algebraMap (RatFunc k) L.M b ≠ 0 := fun h =>
      hb ((injective_iff_map_eq_zero _).mp (algebraMap (RatFunc k) L.M).injective b h)
    have hroot : (β * (algebraMap (RatFunc k) L.M b)⁻¹) ^ finrank (RatFunc k) L.M
        = algebraMap (RatFunc k) L.M
            (algebraMap (Polynomial k) (RatFunc k) (multiA t e)) := by
      rw [mul_pow, ← hβ, inv_pow, hval, map_mul, map_pow]
      field_simp
    have htop : (RatFunc k)⟮β * (algebraMap (RatFunc k) L.M b)⁻¹⟯ = ⊤ := by
      refine top_le_iff.mp ?_
      rw [← hβtop]
      refine adjoin_le_iff.mpr ?_
      rw [Set.singleton_subset_iff]
      have hsplit : β = β * (algebraMap (RatFunc k) L.M b)⁻¹ * algebraMap (RatFunc k) L.M b := by
        field_simp
      have hmem : β * (algebraMap (RatFunc k) L.M b)⁻¹ * algebraMap (RatFunc k) L.M b
          ∈ (RatFunc k)⟮β * (algebraMap (RatFunc k) L.M b)⁻¹⟯ :=
        mul_mem (mem_adjoin_simple_self _ _) (IntermediateField.algebraMap_mem _ b)
      rwa [← hsplit] at hmem
    exact ⟨r, t, e, hinj, hlt, irreducible_X_pow_sub_C_of_root_adjoin_eq_top hroot htop,
      isSplittingField_X_pow_sub_C_of_root_adjoin_eq_top hK hroot htop⟩
  obtain ⟨α, ⟨a, ha⟩, hαtop⟩ := exists_root_adjoin_eq_top_of_isCyclic (RatFunc k) L.M hK
  by_cases ha0 : a = 0
  · -- a degenerate radicand forces the cover to be trivial, and `1` is a radical generator
    have hα0 : α = 0 := by
      have h := ha
      rw [ha0, map_zero] at h
      exact pow_eq_zero_iff hnpos.ne' |>.mp h.symm
    refine key 1 1 one_ne_zero (by rw [map_one, one_pow]) ?_
    rw [adjoin_simple_eq_bot_iff.mpr (one_mem _), ← hαtop, hα0,
      adjoin_simple_eq_bot_iff.mpr (zero_mem _)]
  · exact key α a ha0 ha hαtop

end Rigidity.RET
