/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.CyclicKummerModel
import InverseGalois.Rigidity.RET.MultiKummerInertia
import InverseGalois.Rigidity.RET.GeomRET

/-!
# The branch locus of a cyclic cover of the line

A cover of the line with cyclic deck group is a multi-point Kummer cover
`wⁿ = ∏ᵢ (T - tᵢ)^{eᵢ}` with exponents `eᵢ < n` (`RET/CyclicKummerModel.lean`), and the inertia
group at `tᵢ` is generated by the deck transformation with parameter `eᵢ ∈ ℤ/n`
(`RET/MultiKummerInertia.lean`).  Two consequences are drawn here.

* A point carrying a nonzero exponent is a branch point.  So a cover unramified outside a
  prescribed finite set of points has a model supported on that set, and the exponents can be
  re-indexed onto the prescribed points.
* The parameters `eᵢ` generate `ℤ/n`.  Otherwise a prime `p` would divide `n` and every `eᵢ`, the
  radicand would be a `p`-th power, and the Kummer polynomial would be reducible.

Together these produce, for a cyclic cover unramified outside `{t₀,…,t_{r-1}}`, a distinguished
inertia generator at each `tᵢ` such that the tuple generates the deck group: everything a system
of branch cycles asks for except the relation that the ordered product is trivial.

## Main results

* `Rigidity.RET.exists_reindex_multiA` — an exponent datum supported on a set of points is an
  exponent datum on any injective tuple enumerating a larger set.
* `Rigidity.RET.exists_multiKummer_model_on` — a cyclic cover unramified outside the range of an
  injective tuple `t` is the splitting field of `Xⁿ - ∏ᵢ (T - tᵢ)^{eᵢ}`.
* `Rigidity.RET.closure_range_ofAdd_eq_top` — parameters with no common prime factor with `n`
  generate `ℤ/n`.
* `Rigidity.RET.exists_inertiaGens_of_isCyclic` — a cyclic cover unramified outside the range of
  `t` carries a generating tuple of distinguished inertia generators over the `tᵢ`.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB Module

/-! ### Re-indexing an exponent datum onto prescribed points -/

open scoped Classical in
/-- **An exponent datum supported inside the range of `t` is an exponent datum on `t`.**  The
exponent attached to a point of `t` is the one the given datum attaches to it, or `0` if the datum
does not mention it. -/
theorem exists_reindex_multiA {r r' : ℕ} {t : Fin r → k} (ht : Function.Injective t)
    {t' : Fin r' → k} (ht' : Function.Injective t') {e' : Fin r' → ℕ} {n : ℕ} (hn : 0 < n)
    (hlt : ∀ j, e' j < n) (hsupp : ∀ j, t' j ∉ Set.range t → e' j = 0) :
    ∃ e : Fin r → ℕ, (∀ i, e i < n) ∧ multiA t e = multiA t' e' := by
  set F : k → ℕ := fun p => if h : ∃ j, t' j = p then e' h.choose else 0 with hF
  have hFt' : ∀ j, F (t' j) = e' j := by
    intro j
    have hex : ∃ j', t' j' = t' j := ⟨j, rfl⟩
    simp only [hF, dif_pos hex]
    exact congrArg e' (ht' hex.choose_spec)
  have hFnot : ∀ p, p ∉ Set.range t' → F p = 0 := by
    intro p hp
    simp only [hF]
    rw [dif_neg]
    rintro ⟨j, rfl⟩
    exact hp ⟨j, rfl⟩
  refine ⟨fun i => F (t i), fun i => ?_, ?_⟩
  · show F (t i) < n
    by_cases h : t i ∈ Set.range t'
    · obtain ⟨j, hj⟩ := h
      rw [← hj, hFt' j]
      exact hlt j
    · rw [hFnot _ h]
      exact hn
  · simp only [multiA]
    have h1 : (∏ i, (X - C (t i)) ^ F (t i))
        = ∏ p ∈ Finset.univ.image t, (X - C p) ^ F p :=
      (Finset.prod_image (f := fun p => (X - C p) ^ F p) (g := t)
        fun x _ y _ h => ht h).symm
    have h2 : (∏ j, (X - C (t' j)) ^ e' j)
        = ∏ p ∈ Finset.univ.image t', (X - C p) ^ F p := by
      rw [Finset.prod_image (f := fun p => (X - C p) ^ F p) (g := t')
        fun x _ y _ h => ht' h]
      exact Finset.prod_congr rfl fun j _ => by rw [hFt' j]
    have h3 : (∏ p ∈ Finset.univ.image t, (X - C p) ^ F p)
        = ∏ p ∈ Finset.univ.image t ∪ Finset.univ.image t', (X - C p) ^ F p := by
      refine Finset.prod_subset Finset.subset_union_left fun p hpu hp => ?_
      obtain ⟨j, -, rfl⟩ := Finset.mem_image.mp ((Finset.mem_union.mp hpu).resolve_left hp)
      have hnr : t' j ∉ Set.range t := by
        rintro ⟨i, hi⟩
        exact hp (Finset.mem_image.mpr ⟨i, Finset.mem_univ i, hi⟩)
      rw [hFt' j, hsupp j hnr, pow_zero]
    have h4 : (∏ p ∈ Finset.univ.image t', (X - C p) ^ F p)
        = ∏ p ∈ Finset.univ.image t ∪ Finset.univ.image t', (X - C p) ^ F p := by
      refine Finset.prod_subset Finset.subset_union_right fun p hpu hp => ?_
      have hnr : p ∉ Set.range t' := by
        rintro ⟨j, rfl⟩
        exact hp (Finset.mem_image.mpr ⟨j, Finset.mem_univ j, rfl⟩)
      rw [hFnot p hnr, pow_zero]
    rw [h1, h3, ← h4, ← h2]

/-! ### The model of a cover unramified outside prescribed points -/

/-- **A cyclic cover unramified outside the range of `t` is a multi-point Kummer cover branched
over `t`.**  A point with a nonzero exponent carries a nontrivial inertia group, so the exponents
of a model vanish outside the prescribed points. -/
theorem exists_multiKummer_model_on (L : LineCover) [IsCyclic L.deck] {r : ℕ} (t : Fin r → k)
    (ht : Function.Injective t) (hS : L.IsUnramifiedOutside (Set.range t)) :
    ∃ e : Fin r → ℕ, (∀ i, e i < finrank (RatFunc k) L.M) ∧
      Irreducible (X ^ finrank (RatFunc k) L.M -
        C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) ∧
      IsSplittingField (RatFunc k) L.M
        (X ^ finrank (RatFunc k) L.M -
          C (algebraMap (Polynomial k) (RatFunc k) (multiA t e))) := by
  set n := finrank (RatFunc k) L.M with hndef
  have hnpos : 0 < n := finrank_pos
  haveI : NeZero n := ⟨hnpos.ne'⟩
  obtain ⟨r', t', e', ht', hlt', hirr', hsf'⟩ := exists_multiKummer_model L
  haveI := hsf'
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k n
  have hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n :=
    hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective
  -- an exponent not divisible by `n` produces a nontrivial inertia element
  have hsupp : ∀ j, t' j ∉ Set.range t → e' j = 0 := by
    intro j hj
    have hgen := isInertiaGenAt_multiCover ht' hirr' L hζ₀ hζ j
    have h1 := hS (t' j) hj _ hgen.isInertiaAt
    have h2 : Multiplicative.ofAdd ((e' j : ℕ) : ZMod n) = 1 := by
      have := congrArg (autEquivZmod hirr' L.M hζ) h1
      rwa [MulEquiv.apply_symm_apply, map_one] at this
    have h3 : ((e' j : ℕ) : ZMod n) = 0 := h2
    have h4 : n ∣ e' j := (ZMod.natCast_eq_zero_iff _ _).mp h3
    exact Nat.eq_zero_of_dvd_of_lt h4 (hlt' j)
  obtain ⟨e, hlt, heq⟩ := exists_reindex_multiA ht ht' hnpos hlt' hsupp
  rw [← heq] at hirr' hsf'
  exact ⟨e, hlt, hirr', hsf'⟩

/-! ### The parameters of the inertia generators generate -/

/-- The exponents of a datum with a common factor `p` are `p` times the exponents of a datum. -/
theorem multiA_pow_of_dvd {r : ℕ} (t : Fin r → k) (e : Fin r → ℕ) {p : ℕ} (hp : ∀ i, p ∣ e i) :
    multiA t e = (multiA t fun i => e i / p) ^ p := by
  rw [multiA, multiA, ← Finset.prod_pow]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [← pow_mul, Nat.div_mul_cancel (hp i)]

/-- **Parameters sharing no prime factor with `n` generate `ℤ/n`.**  The quotient of `ℤ/n` by the
subgroup they generate is cyclic, generated by the image of `1`, whose order divides `n` and every
parameter; a prime factor of that order would be a common factor. -/
theorem closure_range_ofAdd_eq_top {n : ℕ} [NeZero n] {r : ℕ} {c : Fin r → ℕ}
    (hc : ∀ p : ℕ, p.Prime → p ∣ n → ¬ ∀ i, p ∣ c i) :
    Subgroup.closure (Set.range fun i => Multiplicative.ofAdd ((c i : ℕ) : ZMod n)) = ⊤ := by
  set g₀ : Multiplicative (ZMod n) := Multiplicative.ofAdd (1 : ZMod n) with hg₀
  have hpow : ∀ m : ℕ, g₀ ^ m = Multiplicative.ofAdd ((m : ℕ) : ZMod n) := by
    intro m
    rw [hg₀, ← ofAdd_nsmul]
    congr 1
    simp
  set S := Subgroup.closure (Set.range fun i => Multiplicative.ofAdd ((c i : ℕ) : ZMod n))
    with hSdef
  by_contra hne
  -- the generator of `ℤ/n` is not in `S`
  have hg₀S : g₀ ∉ S := by
    intro hmem
    refine hne ?_
    rw [Subgroup.eq_top_iff']
    intro x
    obtain ⟨m, hm⟩ : ∃ m : ℕ, g₀ ^ m = x := by
      refine ⟨(Multiplicative.toAdd x).val, ?_⟩
      rw [hpow]
      exact congrArg Multiplicative.ofAdd (ZMod.natCast_rightInverse _)
    exact hm ▸ pow_mem hmem m
  -- the order of the image of the generator in the quotient
  set q : Multiplicative (ZMod n) ⧸ S := QuotientGroup.mk g₀ with hq
  have hq1 : q ≠ 1 := fun h => hg₀S ((QuotientGroup.eq_one_iff g₀).mp h)
  have hqpow : ∀ m : ℕ, q ^ m = QuotientGroup.mk (Multiplicative.ofAdd ((m : ℕ) : ZMod n)) := by
    intro m
    have hm : (QuotientGroup.mk' S) (g₀ ^ m) = (QuotientGroup.mk' S) g₀ ^ m := map_pow _ _ _
    rw [hpow m] at hm
    exact hm.symm
  have hdn : orderOf q ∣ n := by
    refine orderOf_dvd_of_pow_eq_one ?_
    rw [hqpow n, ZMod.natCast_self, ofAdd_zero]
    exact (QuotientGroup.eq_one_iff _).mpr (one_mem S)
  have hdc : ∀ i, orderOf q ∣ c i := by
    intro i
    refine orderOf_dvd_of_pow_eq_one ?_
    rw [hqpow (c i)]
    exact (QuotientGroup.eq_one_iff _).mpr (Subgroup.subset_closure ⟨i, rfl⟩)
  obtain ⟨p, hp, hpd⟩ := Nat.exists_prime_and_dvd (fun h => hq1 (orderOf_eq_one_iff.mp h))
  exact hc p hp (hpd.trans hdn) fun i => hpd.trans (hdc i)

/-! ### Distinguished inertia generators over prescribed points -/

/-- **A cyclic cover unramified outside the range of `t` has a generating tuple of distinguished
inertia generators over the `tᵢ`.** -/
theorem exists_inertiaGens_of_isCyclic (L : LineCover) [IsCyclic L.deck] {r : ℕ} (t : Fin r → k)
    (ht : Function.Injective t) (hS : L.IsUnramifiedOutside (Set.range t)) :
    ∃ g : Fin r → L.deck,
      (∀ i, L.IsInertiaGenAt (t i) (g i)) ∧ Subgroup.closure (Set.range g) = ⊤ := by
  set n := finrank (RatFunc k) L.M with hndef
  have hnpos : 0 < n := finrank_pos
  haveI : NeZero n := ⟨hnpos.ne'⟩
  obtain ⟨e, hlt, hirr, hsf⟩ := exists_multiKummer_model_on L t ht hS
  haveI := hsf
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k n
  have hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n :=
    hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective
  set E := autEquivZmod hirr L.M hζ with hE
  refine ⟨fun i => E.symm (Multiplicative.ofAdd ((e i : ℕ) : ZMod n)),
    fun i => isInertiaGenAt_multiCover ht hirr L hζ₀ hζ i, ?_⟩
  refine closure_range_symm_eq_top E (closure_range_ofAdd_eq_top fun p hp hpn hpe => ?_)
  -- a common prime factor would make the radicand a `p`-th power
  refine pow_ne_of_irreducible_X_pow_sub_C hirr hpn hp.ne_one
    (algebraMap (Polynomial k) (RatFunc k) (multiA t fun i => e i / p)) ?_
  rw [← map_pow, ← multiA_pow_of_dvd t e hpe]

end Rigidity.RET
