/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.DeckGroups
import InverseGalois.Rigidity.RET.CoverExistence

/-!
# Every finite group occurs over enough points

The class of groups occurring over a prescribed branch locus (`Rigidity.RET.IsDeckGroupOver`) is,
for an arbitrary finite group, entered through the existence half of the Riemann Existence Theorem:
a generating product-one tuple is exactly what is needed, and there is no restriction on the group
beyond being generated by as many elements as there are points, subject to one relation.

## Main results

* `Rigidity.RET.isDeckGroupOver_of_prodOne` — every finite group with a product-one generating
  `r`-tuple occurs over `r` prescribed points.
-/

noncomputable section

namespace Rigidity.RET

open GeomAKLB

/-- **Every finite group with a product-one generating `r`-tuple occurs over `r` prescribed
points.** -/
theorem isDeckGroupOver_of_prodOne {G : Type} [Group G] [Finite G] {r : ℕ} {t : Fin r → k}
    (ht : Function.Injective t) (g : Fin r → G) (hprod : (List.ofFn g).prod = 1)
    (htop : Subgroup.closure (Set.range g) = ⊤) : IsDeckGroupOver (Set.range t) G :=
  exists_lineCover_of_prodOne ht g hprod htop

end Rigidity.RET

end
