/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.RatFuncSubst
import InverseGalois.Rigidity.RET.RatFuncGen
import InverseGalois.Rigidity.RET.ArtinFixedField

/-!
# Dihedral groups as covers of the line

The dihedral group of order `2n` acts on the line by the substitutions `u ↦ ζ^i·u` and
`u ↦ ζ^i·u⁻¹`, where `ζ` is a primitive `n`-th root of unity: the rotations scale the parameter by
the `n`-th roots of unity and the reflections compose a scaling with the inversion `u ↦ u⁻¹`.  The
action is faithful, so Artin's theorem exhibits `ℚ̄(u)` as a Galois extension of its invariants with
group the dihedral group; the invariants are generated by the single function

`w = u^n + u^{-n}`,

because `u` satisfies the degree-`2n` equation `Y^{2n} - w·Y^n + 1 = 0` over `ℚ̄(w)` and `2n` is
exactly the order of the group, leaving no room for a larger field of invariants.

This realizes every dihedral group as a geometric Galois cover of the line, with no appeal to the
Riemann Existence Theorem.  Together with the cyclic and Kummer covers and the covers with group
`Aₙ` or `Sₙ`, it enlarges the stock of groups known to be covering groups by explicit equations.

## Main definitions and results

* `Rigidity.RET.scaleAut`, `Rigidity.RET.inversionAut` — the substitutions `u ↦ c·u` and `u ↦ u⁻¹`
  as automorphisms of `K(u)`, and their multiplication table.
* `Rigidity.RET.dihedralAut` — the dihedral group of order `2n` as a group of automorphisms of
  `K(u)`, and `Rigidity.RET.dihedralAut_injective`, its faithfulness.
* `Rigidity.RET.dihedralInvariant` — the invariant function `w = u^n + u^{-n}`.
* `Rigidity.RET.isGeometricGaloisCover_dihedralGroup` — every dihedral group is a geometric Galois
  cover of the line.
-/

open Polynomial


namespace Rigidity.RET

variable {K : Type*} [Field K]

/-! ## The scaling and inversion automorphisms of the line -/

/-- **Two automorphisms of `K(u)` over `K` agreeing at the parameter are equal.** -/
theorem ratFunc_algEquiv_ext {f g : RatFunc K ≃ₐ[K] RatFunc K}
    (h : f RatFunc.X = g RatFunc.X) : f = g :=
  AlgEquiv.coe_algHom_injective (ratFunc_algHom_ext h)

@[simp] theorem algEquiv_algebraMap (f : RatFunc K ≃ₐ[K] RatFunc K) (a : K) :
    f (algebraMap K (RatFunc K) a) = algebraMap K (RatFunc K) a := f.commutes a

/-- Substituting `c·u` into `d·u` gives `(d·c)·u`. -/
theorem ratFuncSubst_const_mul_X {c : K} (hc : c ≠ 0) (d : K) :
    ratFuncSubst _ (transcendental_const_mul_X hc)
        (algebraMap K (RatFunc K) d * RatFunc.X)
      = algebraMap K (RatFunc K) (d * c) * RatFunc.X := by
  rw [map_mul, AlgHom.commutes, ratFuncSubst_X, map_mul]
  ring

/-- **The scaling `u ↦ c·u` of `K(u)`**, for a nonzero constant `c`. -/
noncomputable def scaleAut {c : K} (hc : c ≠ 0) : RatFunc K ≃ₐ[K] RatFunc K :=
  ratFuncSubstEquiv (transcendental_const_mul_X hc) (transcendental_const_mul_X (inv_ne_zero hc))
    (by rw [ratFuncSubst_const_mul_X hc c⁻¹, inv_mul_cancel₀ hc, map_one, one_mul])
    (by rw [ratFuncSubst_const_mul_X (inv_ne_zero hc) c, mul_inv_cancel₀ hc, map_one, one_mul])

@[simp] theorem scaleAut_X {c : K} (hc : c ≠ 0) :
    scaleAut hc RatFunc.X = algebraMap K (RatFunc K) c * RatFunc.X := by
  rw [scaleAut, ratFuncSubstEquiv_apply, ratFuncSubst_X]

/-- **The inversion `u ↦ u⁻¹` of `K(u)`.** -/
noncomputable def inversionAut : RatFunc K ≃ₐ[K] RatFunc K :=
  ratFuncSubstEquiv transcendental_inv_X transcendental_inv_X
    (by rw [map_inv₀, ratFuncSubst_X, inv_inv]) (by rw [map_inv₀, ratFuncSubst_X, inv_inv])

@[simp] theorem inversionAut_X :
    (inversionAut : RatFunc K ≃ₐ[K] RatFunc K) RatFunc.X = (RatFunc.X)⁻¹ := by
  rw [inversionAut, ratFuncSubstEquiv_apply, ratFuncSubst_X]

/-- Scalings compose. -/
theorem scaleAut_mul {c d : K} (hc : c ≠ 0) (hd : d ≠ 0) :
    scaleAut hc * scaleAut hd = scaleAut (mul_ne_zero hd hc) := by
  refine ratFunc_algEquiv_ext ?_
  simp only [AlgEquiv.mul_apply, scaleAut_X, map_mul, algEquiv_algebraMap]
  ring

/-- Scaling by `1` is the identity. -/
theorem scaleAut_one : scaleAut (one_ne_zero (α := K)) = 1 := by
  refine ratFunc_algEquiv_ext ?_
  simp

/-- The inversion is an involution. -/
theorem inversionAut_inversionAut :
    (inversionAut : RatFunc K ≃ₐ[K] RatFunc K) * inversionAut = 1 := by
  refine ratFunc_algEquiv_ext ?_
  simp [AlgEquiv.mul_apply]

/-- Conjugating a scaling by the inversion inverts the scalar. -/
theorem scaleAut_inversionAut {c : K} (hc : c ≠ 0) :
    scaleAut hc * (inversionAut : RatFunc K ≃ₐ[K] RatFunc K)
      = inversionAut * scaleAut (inv_ne_zero hc) := by
  refine ratFunc_algEquiv_ext ?_
  simp only [AlgEquiv.mul_apply, inversionAut_X, scaleAut_X, map_inv₀, map_mul,
    algEquiv_algebraMap, mul_inv]

/-! ## The dihedral group of automorphisms -/

section Dihedral

variable {n : ℕ} [NeZero n] {ζ : K}

/-- The `i`-th power of a root of unity, indexed by `ZMod n`. -/
noncomputable def rootPow (ζ : K) (i : ZMod n) : K := ζ ^ i.val

theorem rootPow_ne_zero (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) : rootPow ζ i ≠ 0 :=
  pow_ne_zero _ (hζ.ne_zero (NeZero.ne n))

omit [NeZero n] in
theorem pow_mod_eq (hζ : IsPrimitiveRoot ζ n) (a : ℕ) : ζ ^ (a % n) = ζ ^ a := by
  conv_rhs => rw [← Nat.div_add_mod a n]
  rw [pow_add, pow_mul, hζ.pow_eq_one, one_pow, one_mul]

theorem rootPow_add (hζ : IsPrimitiveRoot ζ n) (i j : ZMod n) :
    rootPow ζ (i + j) = rootPow ζ i * rootPow ζ j := by
  rw [rootPow, rootPow, rootPow, ← pow_add, ZMod.val_add, pow_mod_eq hζ]

omit [NeZero n] in
theorem rootPow_zero (ζ : K) : rootPow ζ (0 : ZMod n) = 1 := by
  rw [rootPow, ZMod.val_zero, pow_zero]

theorem rootPow_neg (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) :
    rootPow ζ (-i) = (rootPow ζ i)⁻¹ := by
  have h : rootPow ζ i * rootPow ζ (-i) = 1 := by
    rw [← rootPow_add hζ, add_neg_cancel, rootPow_zero]
  exact eq_inv_of_mul_eq_one_right h

theorem rootPow_sub (hζ : IsPrimitiveRoot ζ n) (i j : ZMod n) :
    rootPow ζ (i - j) = rootPow ζ i * (rootPow ζ j)⁻¹ := by
  rw [sub_eq_add_neg, rootPow_add hζ, rootPow_neg hζ]

omit [NeZero n] in
theorem rootPow_pow (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) : (rootPow ζ i) ^ n = 1 := by
  rw [rootPow, ← pow_mul, mul_comm, pow_mul, hζ.pow_eq_one, one_pow]

theorem rootPow_eq_one_iff (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) :
    rootPow ζ i = 1 ↔ i = 0 := by
  constructor
  · intro h
    have hdvd : n ∣ i.val := hζ.dvd_of_pow_eq_one _ h
    have h0 : i.val = 0 := Nat.eq_zero_of_dvd_of_lt hdvd (ZMod.val_lt i)
    have hcast : ((i.val : ℕ) : ZMod n) = i := by rw [ZMod.natCast_val, ZMod.cast_id]
    rw [← hcast, h0, Nat.cast_zero]
  · rintro rfl
    exact rootPow_zero ζ

theorem scaleAut_congr {c d : K} (hc : c ≠ 0) (hd : d ≠ 0) (h : c = d) :
    scaleAut hc = scaleAut hd := by
  subst h; rfl

/-- The rotation `r i` scales by `ζ^i`, the reflection `sr i` scales by `ζ^i` after inverting. -/
noncomputable def dihedralAutFun (hζ : IsPrimitiveRoot ζ n) :
    DihedralGroup n → (RatFunc K ≃ₐ[K] RatFunc K)
  | .r i => scaleAut (rootPow_ne_zero hζ i)
  | .sr i => inversionAut * scaleAut (rootPow_ne_zero hζ i)

/-- **The dihedral group of order `2n` as a group of automorphisms of `K(u)`.** -/
noncomputable def dihedralAut (hζ : IsPrimitiveRoot ζ n) :
    DihedralGroup n →* (RatFunc K ≃ₐ[K] RatFunc K) where
  toFun := dihedralAutFun hζ
  map_one' := by
    show dihedralAutFun hζ (DihedralGroup.r 0) = 1
    rw [dihedralAutFun, scaleAut_congr _ (one_ne_zero (α := K)) (rootPow_zero ζ), scaleAut_one]
  map_mul' a b := by
    cases a with
    | r i =>
      cases b with
      | r j =>
        show dihedralAutFun hζ (DihedralGroup.r (i + j)) = _
        rw [dihedralAutFun, dihedralAutFun, dihedralAutFun, scaleAut_mul]
        exact scaleAut_congr (rootPow_ne_zero hζ (i + j))
          (mul_ne_zero (rootPow_ne_zero hζ j) (rootPow_ne_zero hζ i))
          (by rw [rootPow_add hζ, mul_comm])
      | sr j =>
        show dihedralAutFun hζ (DihedralGroup.sr (j - i)) = _
        rw [dihedralAutFun, dihedralAutFun, dihedralAutFun, ← mul_assoc, scaleAut_inversionAut,
          mul_assoc, scaleAut_mul,
          scaleAut_congr (mul_ne_zero (rootPow_ne_zero hζ j) (inv_ne_zero (rootPow_ne_zero hζ i)))
            (rootPow_ne_zero hζ (j - i)) (rootPow_sub hζ j i).symm]
    | sr i =>
      cases b with
      | r j =>
        show dihedralAutFun hζ (DihedralGroup.sr (i + j)) = _
        rw [dihedralAutFun, dihedralAutFun, dihedralAutFun, mul_assoc, scaleAut_mul]
        exact congrArg (fun f => inversionAut * f)
          (scaleAut_congr (rootPow_ne_zero hζ (i + j))
            (mul_ne_zero (rootPow_ne_zero hζ j) (rootPow_ne_zero hζ i))
            (by rw [rootPow_add hζ, mul_comm]))
      | sr j =>
        show dihedralAutFun hζ (DihedralGroup.r (j - i)) = _
        rw [dihedralAutFun, dihedralAutFun, dihedralAutFun, mul_assoc, ← mul_assoc (scaleAut _),
          scaleAut_inversionAut, ← mul_assoc, ← mul_assoc, inversionAut_inversionAut, one_mul,
          scaleAut_mul,
          scaleAut_congr (mul_ne_zero (rootPow_ne_zero hζ j) (inv_ne_zero (rootPow_ne_zero hζ i)))
            (rootPow_ne_zero hζ (j - i)) (rootPow_sub hζ j i).symm]

@[simp] theorem dihedralAut_r (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) :
    dihedralAut hζ (DihedralGroup.r i) = scaleAut (rootPow_ne_zero hζ i) := rfl

@[simp] theorem dihedralAut_sr (hζ : IsPrimitiveRoot ζ n) (i : ZMod n) :
    dihedralAut hζ (DihedralGroup.sr i) = inversionAut * scaleAut (rootPow_ne_zero hζ i) := rfl

/-- **The dihedral action on the line is faithful.** -/
theorem dihedralAut_injective (hζ : IsPrimitiveRoot ζ n) :
    Function.Injective (dihedralAut hζ) := by
  rw [injective_iff_map_eq_one]
  intro a ha
  have hX0 : (RatFunc.X : RatFunc K) ≠ 0 := RatFunc.X_ne_zero
  cases a with
  | r i =>
    have hX : scaleAut (rootPow_ne_zero hζ i) RatFunc.X = RatFunc.X := by
      rw [← dihedralAut_r hζ i, ha]; rfl
    rw [scaleAut_X] at hX
    have hc : algebraMap K (RatFunc K) (rootPow ζ i) = 1 := by
      have := mul_right_cancel₀ hX0 (by rw [hX, one_mul] :
        algebraMap K (RatFunc K) (rootPow ζ i) * RatFunc.X = (1 : RatFunc K) * RatFunc.X)
      exact this
    have hc1 : rootPow ζ i = 1 := by
      have hinj : Function.Injective (algebraMap K (RatFunc K)) :=
        (algebraMap K (RatFunc K)).injective
      exact hinj (by rw [hc, map_one])
    rw [(rootPow_eq_one_iff hζ i).mp hc1]
    rfl
  | sr i =>
    exfalso
    have hX : (inversionAut * scaleAut (rootPow_ne_zero hζ i) :
        RatFunc K ≃ₐ[K] RatFunc K) RatFunc.X = (RatFunc.X : RatFunc K) := by
      rw [← dihedralAut_sr hζ i, ha]; rfl
    rw [AlgEquiv.mul_apply, scaleAut_X, map_mul, algEquiv_algebraMap, inversionAut_X] at hX
    have h2 : algebraMap K (RatFunc K) (rootPow ζ i) = RatFunc.X * RatFunc.X := by
      have := congrArg (fun y : RatFunc K => y * RatFunc.X) hX
      simpa [mul_assoc, inv_mul_cancel₀ hX0] using this
    refine RatFunc.transcendental_X (K := K)
      ⟨Polynomial.X ^ 2 - Polynomial.C (rootPow ζ i), ?_, ?_⟩
    · exact Polynomial.X_pow_sub_C_ne_zero (by norm_num) _
    · simp only [map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C, h2]
      ring

end Dihedral

/-! ## The invariant function and its equation -/

/-- The invariant function `w = u^n + u^{-n}` of the dihedral action on the line. -/
noncomputable def dihedralInvariant (K : Type*) [Field K] (n : ℕ) : RatFunc K :=
  RatFunc.X ^ n + (RatFunc.X ^ n)⁻¹

/-- The degree-`2n` equation `Y^{2n} - w·Y^n + 1` satisfied by the parameter over the invariants. -/
noncomputable def dihedralPoly {A : Type*} [CommRing A] (u : A) (n : ℕ) : Polynomial A :=
  Polynomial.X ^ (2 * n) + (-(Polynomial.C u * Polynomial.X ^ n) + 1)

theorem dihedralPoly_monic {A : Type*} [CommRing A] [Nontrivial A] (u : A) {n : ℕ} (hn : 0 < n) :
    (dihedralPoly u n).Monic := by
  unfold dihedralPoly
  monicity!
  have h1 : n ≤ 2 * n := by omega
  have h2 : ¬ (2 * n ≤ n) := by omega
  have h3 : n ≠ 0 := by omega
  simp [h1, h2, h3]

theorem dihedralPoly_natDegree_le {A : Type*} [CommRing A] (u : A) (n : ℕ) :
    (dihedralPoly u n).natDegree ≤ 2 * n := by
  unfold dihedralPoly
  compute_degree
  omega

/-- **The parameter satisfies the degree-`2n` equation over any field containing the invariant.** -/
theorem aeval_dihedralPoly {A : Type*} [Field A] [Algebra A (RatFunc K)] (u : A) {n : ℕ}
    (hu : algebraMap A (RatFunc K) u = dihedralInvariant K n) :
    Polynomial.aeval (RatFunc.X : RatFunc K) (dihedralPoly u n) = 0 := by
  have hXn : (RatFunc.X : RatFunc K) ^ n ≠ 0 := pow_ne_zero _ RatFunc.X_ne_zero
  simp only [dihedralPoly, map_add, map_neg, map_mul, map_pow, map_one, Polynomial.aeval_X,
    Polynomial.aeval_C, hu, dihedralInvariant, two_mul, pow_add]
  field_simp
  ring

/-! ## Invariance of `w` under the dihedral action -/

section Invariance

variable {n : ℕ} [NeZero n] {ζ : K}

omit [NeZero n] in
/-- A scaling by an `n`-th root of unity fixes `w = u^n + u^{-n}`. -/
theorem scaleAut_dihedralInvariant {c : K} (hc : c ≠ 0) (hcn : c ^ n = 1) :
    scaleAut hc (dihedralInvariant K n) = dihedralInvariant K n := by
  have hC : (algebraMap K (RatFunc K) c) ^ n = 1 := by rw [← map_pow, hcn, map_one]
  simp only [dihedralInvariant, map_add, map_inv₀, map_pow, scaleAut_X, mul_pow, hC, one_mul]

omit [NeZero n] in
/-- The inversion fixes `w = u^n + u^{-n}`: it exchanges the two summands. -/
theorem inversionAut_dihedralInvariant :
    (inversionAut : RatFunc K ≃ₐ[K] RatFunc K) (dihedralInvariant K n)
      = dihedralInvariant K n := by
  simp only [dihedralInvariant, map_add, map_inv₀, map_pow, inversionAut_X, inv_pow, inv_inv]
  rw [add_comm]

/-- **`w = u^n + u^{-n}` is a dihedral invariant.** -/
theorem dihedralAut_dihedralInvariant (hζ : IsPrimitiveRoot ζ n) (g : DihedralGroup n) :
    dihedralAut hζ g (dihedralInvariant K n) = dihedralInvariant K n := by
  cases g with
  | r i => rw [dihedralAut_r, scaleAut_dihedralInvariant _ (rootPow_pow hζ i)]
  | sr i =>
      rw [dihedralAut_sr, AlgEquiv.mul_apply, scaleAut_dihedralInvariant _ (rootPow_pow hζ i),
        inversionAut_dihedralInvariant]

end Invariance

/-- **The invariant `w = u^n + u^{-n}` is not a constant.**

The parameter satisfies a degree-`2n` equation over the field generated by `w`, so a constant `w`
would make the parameter algebraic over the constants, which it is not. -/
theorem transcendental_dihedralInvariant (n : ℕ) (hn : 0 < n) :
    Transcendental K (dihedralInvariant K n) := by
  intro halg
  have hint : IsIntegral K (dihedralInvariant K n) := halg.isIntegral
  haveI : Algebra.IsAlgebraic K ↥(IntermediateField.adjoin K {dihedralInvariant K n}) :=
    IntermediateField.isAlgebraic_adjoin_simple hint
  have hwE : dihedralInvariant K n ∈ IntermediateField.adjoin K {dihedralInvariant K n} :=
    IntermediateField.mem_adjoin_simple_self K _
  have hu : algebraMap ↥(IntermediateField.adjoin K {dihedralInvariant K n}) (RatFunc K)
      ⟨dihedralInvariant K n, hwE⟩ = dihedralInvariant K n := rfl
  have hXalg : IsAlgebraic ↥(IntermediateField.adjoin K {dihedralInvariant K n})
      (RatFunc.X : RatFunc K) :=
    ⟨dihedralPoly ⟨dihedralInvariant K n, hwE⟩ n,
      (dihedralPoly_monic _ hn).ne_zero, aeval_dihedralPoly _ hu⟩
  exact RatFunc.transcendental_X (K := K) (hXalg.restrictScalars K)

/-! ## Pinning the field of invariants -/

/-- A subfield of `K(u)` containing the constants has `K(u)` generated over it by the parameter. -/
theorem adjoin_X_eq_top (S : Subfield (RatFunc K))
    (hC : ∀ c : K, algebraMap K (RatFunc K) c ∈ S) :
    IntermediateField.adjoin ↥S {(RatFunc.X : RatFunc K)} = ⊤ :=
  ratFunc_intermediateField_eq_top
    (fun c => (IntermediateField.adjoin ↥S {(RatFunc.X : RatFunc K)}).algebraMap_mem ⟨_, hC c⟩)
    (IntermediateField.mem_adjoin_simple_self _ _)

set_option synthInstance.maxHeartbeats 200000 in
/-- If the parameter is integral over a subfield containing the constants, `K(u)` is finite over
that subfield. -/
theorem finiteDimensional_of_isIntegral_X {S : Subfield (RatFunc K)}
    (hC : ∀ c : K, algebraMap K (RatFunc K) c ∈ S)
    (hint : IsIntegral ↥S (RatFunc.X : RatFunc K)) : FiniteDimensional ↥S (RatFunc K) := by
  have hfd := IntermediateField.adjoin.finiteDimensional hint
  rw [adjoin_X_eq_top S hC] at hfd
  exact (IntermediateField.topEquiv (F := ↥S) (E := RatFunc K)).toLinearEquiv.finiteDimensional

set_option synthInstance.maxHeartbeats 200000 in
/-- **The degree of `K(u)` over a subfield containing the constants is bounded by the degree of any
monic equation satisfied by the parameter.** -/
theorem finrank_le_of_monic_root {S : Subfield (RatFunc K)}
    (hC : ∀ c : K, algebraMap K (RatFunc K) c ∈ S) {p : Polynomial ↥S} (hp : p.Monic)
    (hroot : Polynomial.aeval (RatFunc.X : RatFunc K) p = 0) :
    Module.finrank ↥S (RatFunc K) ≤ p.natDegree := by
  have hint : IsIntegral ↥S (RatFunc.X : RatFunc K) := ⟨p, hp, hroot⟩
  have h1 : Module.finrank ↥S ↥(IntermediateField.adjoin ↥S {(RatFunc.X : RatFunc K)})
      = (minpoly ↥S (RatFunc.X : RatFunc K)).natDegree := IntermediateField.adjoin.finrank hint
  have h2 : (minpoly ↥S (RatFunc.X : RatFunc K)).natDegree ≤ p.natDegree :=
    Polynomial.natDegree_le_natDegree
      (minpoly.degree_le_of_ne_zero (A := ↥S) (x := (RatFunc.X : RatFunc K)) hp.ne_zero hroot)
  have h3 : Module.finrank ↥S (RatFunc K)
      = Module.finrank ↥S ↥(IntermediateField.adjoin ↥S {(RatFunc.X : RatFunc K)}) := by
    rw [adjoin_X_eq_top S hC]
    exact (LinearEquiv.finrank_eq
      (IntermediateField.topEquiv (F := ↥S) (E := RatFunc K)).toLinearEquiv).symm
  rw [h3, h1]
  exact h2

/-! ## Dihedral covers of the line -/

/-- The algebraic closure of `ℚ` contains a primitive `n`-th root of unity. -/
theorem exists_isPrimitiveRoot_algebraicClosure (n : ℕ) (hn : 0 < n) :
    ∃ ζ : AlgebraicClosure ℚ, IsPrimitiveRoot ζ n := by
  have hdeg : (Polynomial.cyclotomic n (AlgebraicClosure ℚ)).degree ≠ 0 := by
    rw [Polynomial.degree_cyclotomic]
    exact_mod_cast (Nat.totient_pos.mpr hn).ne'
  obtain ⟨ζ, hζ⟩ := IsAlgClosed.exists_root _ hdeg
  exact ⟨ζ, (Polynomial.isRoot_cyclotomic_iff_charZero hn).mp hζ⟩

set_option synthInstance.maxHeartbeats 200000 in
/-- **Every dihedral group is a geometric Galois cover of the line.**

The group of order `2n` acts on `ℚ̄(u)` by `u ↦ ζ^i·u` and `u ↦ ζ^i·u⁻¹`; the invariant `w` of the
action generates a subfield over which the parameter satisfies an equation of degree `2n`, so that
subfield is the whole field of invariants and Artin's theorem applies. -/
theorem isGeometricGaloisCover_dihedralGroup (n : ℕ) (hn : 0 < n) :
    IsGeometricGaloisCover (DihedralGroup n) := by
  haveI : NeZero n := ⟨hn.ne'⟩
  obtain ⟨ζ, hζ⟩ := exists_isPrimitiveRoot_algebraicClosure n hn
  letI : MulSemiringAction (DihedralGroup n) (RatFunc (AlgebraicClosure ℚ)) :=
    MulSemiringAction.compHom _ (dihedralAut hζ)
  haveI : FaithfulSMul (DihedralGroup n) (RatFunc (AlgebraicClosure ℚ)) :=
    ⟨fun {_ _} h => dihedralAut_injective hζ (AlgEquiv.ext fun x => h x)⟩
  have hw : Transcendental (AlgebraicClosure ℚ) (dihedralInvariant (AlgebraicClosure ℚ) n) :=
    transcendental_dihedralInvariant n hn
  set φ := ratFuncSubst (dihedralInvariant (AlgebraicClosure ℚ) n) hw with hφ
  set S : Subfield (RatFunc (AlgebraicClosure ℚ)) :=
    (φ : RatFunc (AlgebraicClosure ℚ) →+* RatFunc (AlgebraicClosure ℚ)).fieldRange with hS
  have hCS : ∀ c : AlgebraicClosure ℚ,
      algebraMap (AlgebraicClosure ℚ) (RatFunc (AlgebraicClosure ℚ)) c ∈ S :=
    fun c => ⟨algebraMap _ _ c, φ.commutes c⟩
  have hwS : dihedralInvariant (AlgebraicClosure ℚ) n ∈ S :=
    ⟨RatFunc.X, ratFuncSubst_X _ hw⟩
  have hfix : S ≤ FixedPoints.subfield (DihedralGroup n) (RatFunc (AlgebraicClosure ℚ)) := by
    rintro x ⟨y, rfl⟩ g
    show dihedralAut hζ g (φ y) = φ y
    have hcomp : (dihedralAut hζ g).toAlgHom.comp φ = φ :=
      ratFunc_algHom_ext (by
        rw [AlgHom.comp_apply, hφ, ratFuncSubst_X]
        exact dihedralAut_dihedralInvariant hζ g)
    exact congrArg (fun ψ : RatFunc (AlgebraicClosure ℚ) →ₐ[AlgebraicClosure ℚ]
      RatFunc (AlgebraicClosure ℚ) => ψ y) hcomp
  have hu : algebraMap ↥S (RatFunc (AlgebraicClosure ℚ))
      ⟨dihedralInvariant (AlgebraicClosure ℚ) n, hwS⟩
        = dihedralInvariant (AlgebraicClosure ℚ) n := rfl
  have hroot := aeval_dihedralPoly (K := AlgebraicClosure ℚ)
    (⟨dihedralInvariant (AlgebraicClosure ℚ) n, hwS⟩ : ↥S) (n := n) hu
  haveI : FiniteDimensional ↥S (RatFunc (AlgebraicClosure ℚ)) :=
    finiteDimensional_of_isIntegral_X hCS ⟨_, dihedralPoly_monic _ hn, hroot⟩
  have hfr : Module.finrank ↥S (RatFunc (AlgebraicClosure ℚ)) ≤ Nat.card (DihedralGroup n) := by
    refine le_trans (finrank_le_of_monic_root hCS (dihedralPoly_monic _ hn) hroot) ?_
    rw [DihedralGroup.nat_card]
    exact dihedralPoly_natDegree_le _ n
  exact isGeometricGaloisCover_of_invariant_subfield S hfix hfr
    (RingHom.rangeRestrictFieldEquiv
      (φ : RatFunc (AlgebraicClosure ℚ) →+* RatFunc (AlgebraicClosure ℚ))).symm

end Rigidity.RET
