/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.MonodromyGroup

/-!
# Branch data of a product over disjoint branch loci

Two covers branched over disjoint sets of points are linearly disjoint, and their compositum has
the product of the two deck groups.  This is the construction of `RET/Product.lean`; what is added
here is the branch-cycle datum.  Above a point of the first locus the second cover is unramified,
so its inertia is trivial and the inertia of the compositum is generated by a pair whose second
coordinate is `1` — the coprimality hypothesis of `RET/CoprimeProduct.lean` is satisfied for free,
the order of `1` being `1`.  The branch cycles of the compositum are therefore the two given
systems, each padded by the identity of the other factor.

No hypothesis on the two groups is needed: unlike the coprime-degree construction over a common
locus, moving the branch points apart makes any two groups multiply.

## Main results

* `Rigidity.RET.LineCover.isInertiaGenAt_one_of_unramified` — at an unramified point the identity
  is a distinguished inertia element.
* `Rigidity.RET.IsMonodromyOver.prod_disjoint` — the padded concatenation of two branch data over
  disjoint loci is branch data for the product group.
* `Rigidity.RET.exists_isMonodromyOver_prod` — product-one generating branch data multiply.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-! ## Tuples concatenated across a direct product -/

section GroupTheory

variable {G₁ G₂ : Type*} [Group G₁] [Group G₂] {r s : ℕ}

/-- The concatenation of two tuples, each padded by the identity of the other factor. -/
def padAppend (h₁ : Fin r → G₁) (h₂ : Fin s → G₂) : Fin (r + s) → G₁ × G₂ :=
  Fin.append (fun i => (h₁ i, (1 : G₂))) (fun j => ((1 : G₁), h₂ j))

@[simp]
theorem padAppend_left (h₁ : Fin r → G₁) (h₂ : Fin s → G₂) (i : Fin r) :
    padAppend h₁ h₂ (Fin.castAdd s i) = (h₁ i, 1) :=
  Fin.append_left _ _ i

@[simp]
theorem padAppend_right (h₁ : Fin r → G₁) (h₂ : Fin s → G₂) (j : Fin s) :
    padAppend h₁ h₂ (Fin.natAdd r j) = (1, h₂ j) :=
  Fin.append_right _ _ j

/-- **The padded concatenation of two product-one tuples has product one.** -/
theorem prod_ofFn_padAppend (h₁ : Fin r → G₁) (h₂ : Fin s → G₂)
    (hp₁ : (List.ofFn h₁).prod = 1) (hp₂ : (List.ofFn h₂).prod = 1) :
    (List.ofFn (padAppend h₁ h₂)).prod = 1 := by
  have e1 : (List.ofFn fun i => ((h₁ i, (1 : G₂)) : G₁ × G₂)).prod = 1 := by
    have hm := prod_ofFn_map (MonoidHom.inl G₁ G₂) h₁
    rw [hp₁, map_one] at hm
    exact hm
  have e2 : (List.ofFn fun j => (((1 : G₁), h₂ j) : G₁ × G₂)).prod = 1 := by
    have hm := prod_ofFn_map (MonoidHom.inr G₁ G₂) h₂
    rw [hp₂, map_one] at hm
    exact hm
  rw [padAppend, List.ofFn_fin_append, List.prod_append, e1, e2, one_mul]

/-- **The padded concatenation of two generating tuples generates the product.** -/
theorem closure_range_padAppend_eq_top {h₁ : Fin r → G₁} {h₂ : Fin s → G₂}
    (ht₁ : Subgroup.closure (Set.range h₁) = ⊤) (ht₂ : Subgroup.closure (Set.range h₂) = ⊤) :
    Subgroup.closure (Set.range (padAppend h₁ h₂)) = ⊤ := by
  have hleft : Subgroup.map (MonoidHom.inl G₁ G₂) (Subgroup.closure (Set.range h₁))
      ≤ Subgroup.closure (Set.range (padAppend h₁ h₂)) := by
    rw [MonoidHom.map_closure, Subgroup.closure_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    exact Subgroup.subset_closure ⟨Fin.castAdd s i, padAppend_left h₁ h₂ i⟩
  have hright : Subgroup.map (MonoidHom.inr G₁ G₂) (Subgroup.closure (Set.range h₂))
      ≤ Subgroup.closure (Set.range (padAppend h₁ h₂)) := by
    rw [MonoidHom.map_closure, Subgroup.closure_le]
    rintro _ ⟨_, ⟨j, rfl⟩, rfl⟩
    exact Subgroup.subset_closure ⟨Fin.natAdd r j, padAppend_right h₁ h₂ j⟩
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨a, b⟩ := x
  have hx : ((a, b) : G₁ × G₂) = (a, 1) * (1, b) := by
    show ((a, b) : G₁ × G₂) = ((a * 1, 1 * b) : G₁ × G₂)
    rw [mul_one, one_mul]
  rw [hx]
  refine Subgroup.mul_mem _ (hleft ?_) (hright ?_)
  · rw [ht₁]
    exact ⟨a, Subgroup.mem_top a, rfl⟩
  · rw [ht₂]
    exact ⟨b, Subgroup.mem_top b, rfl⟩

end GroupTheory

/-! ## Points where a cover is unramified -/

namespace LineCover

attribute [local instance] sub_isGalois

/-- **At a point outside the branch locus the identity is a distinguished inertia element.** -/
theorem isInertiaGenAt_one_of_unramified (L : LineCover) {S : Set k}
    (hout : L.IsUnramifiedOutside S) {t : k} (ht : t ∉ S) : L.IsInertiaGenAt t 1 := by
  obtain ⟨σ, hσ⟩ := L.exists_isInertiaGenAt t
  have hone : σ = 1 := hout t ht σ hσ.isInertiaAt
  exact hone ▸ hσ

end LineCover

/-! ## Branch data multiply over disjoint loci -/

/-- The branch locus of a concatenated tuple is the union of the two branch loci. -/
theorem range_fin_append {r s : ℕ} (t : Fin r → k) (u : Fin s → k) :
    Set.range (Fin.append t u) = Set.range t ∪ Set.range u := by
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    induction i using Fin.addCases with
    | left i => exact Or.inl ⟨i, (Fin.append_left t u i).symm⟩
    | right j => exact Or.inr ⟨j, (Fin.append_right t u j).symm⟩
  · rintro (⟨i, rfl⟩ | ⟨j, rfl⟩)
    · exact ⟨Fin.castAdd s i, Fin.append_left t u i⟩
    · exact ⟨Fin.natAdd r j, Fin.append_right t u j⟩

/-- **Two branch data over disjoint loci combine into branch data for the product group.**

The two covers are placed inside their compositum, where disjointness of the branch loci makes them
linearly disjoint, so the deck group of the compositum is the product.  Above a point of one locus
the other cover is unramified, so the branch cycle there is the given one padded by the identity. -/
theorem IsMonodromyOver.prod_disjoint {G₁ G₂ : Type} [Group G₁] [Finite G₁] [Group G₂] [Finite G₂]
    {r s : ℕ} {h₁ : Fin r → G₁} {h₂ : Fin s → G₂} {t : Fin r → k} {u : Fin s → k}
    (hdisj : Disjoint (Set.range t) (Set.range u))
    (H₁ : IsMonodromyOver h₁ t) (H₂ : IsMonodromyOver h₂ u) :
    IsMonodromyOver (padAppend h₁ h₂) (Fin.append t u) := by
  obtain ⟨L₁, e₁, hout₁, hinf₁, hin₁⟩ := H₁
  obtain ⟨L₂, e₂, hout₂, hinf₂, hin₂⟩ := H₂
  set M := L₁.compositum L₂ with hM
  set A := L₁.compositumLeft L₂ with hA
  set B := L₁.compositumRight L₂ with hB
  set φ := L₁.compositumLeftEquiv L₂ with hφ
  set ψ := L₁.compositumRightEquiv L₂ with hψ
  set dA : (M.sub A).deck ≃* G₁ := (AlgEquiv.autCongr φ).trans e₁ with hdA
  set dB : (M.sub B).deck ≃* G₂ := (AlgEquiv.autCongr ψ).trans e₂ with hdB
  have houtA : (M.sub A).IsUnramifiedOutside (Set.range t) :=
    LineCover.IsUnramifiedOutside.transport (L := L₁) (L' := M.sub A) φ.symm hout₁
  have houtB : (M.sub B).IsUnramifiedOutside (Set.range u) :=
    LineCover.IsUnramifiedOutside.transport (L := L₂) (L' := M.sub B) ψ.symm hout₂
  have hinfA : (M.sub A).IsUnramifiedAtInfinity :=
    LineCover.IsUnramifiedAtInfinity.transport (L := L₁) (L' := M.sub A) φ.symm hinf₁
  have hinfB : (M.sub B).IsUnramifiedAtInfinity :=
    LineCover.IsUnramifiedAtInfinity.transport (L := L₂) (L' := M.sub B) ψ.symm hinf₂
  have hsup : A ⊔ B = ⊤ := L₁.compositumLeft_sup_compositumRight L₂
  have hbot : A ⊓ B = ⊥ :=
    LineCover.inf_eq_bot_of_disjoint M A B hdisj houtA hinfA houtB
  refine ⟨M, (LineCover.deckProdEquiv M A B hsup hbot).trans (MulEquiv.prodCongr dA dB), ?_, ?_,
    fun i => ?_⟩
  · rw [range_fin_append]
    exact LineCover.IsUnramifiedOutside.of_sup hsup houtA houtB
  · exact LineCover.IsUnramifiedAtInfinity.of_sup hsup hinfA hinfB
  · induction i using Fin.addCases with
    | left i =>
      have hinA : (M.sub A).IsInertiaGenAt (t i) (dA.symm (h₁ i)) := by
        have := LineCover.IsInertiaGenAt.transport (L := L₁) (L' := M.sub A) φ.symm (hin₁ i)
        rwa [hdA, MulEquiv.symm_trans_apply, AlgEquiv.autCongr_symm]
      have hnot : t i ∉ Set.range u := Set.disjoint_left.mp hdisj ⟨i, rfl⟩
      have hinB : (M.sub B).IsInertiaGenAt (t i) 1 :=
        LineCover.isInertiaGenAt_one_of_unramified _ houtB hnot
      have hkey := LineCover.isInertiaGenAt_deckProdEquiv_symm M A B hsup hbot
        (by rw [orderOf_one]; exact Nat.coprime_one_right _) hinA hinB
      have hsymm : ((LineCover.deckProdEquiv M A B hsup hbot).trans
            (MulEquiv.prodCongr dA dB)).symm ((h₁ i, 1) : G₁ × G₂)
          = (LineCover.deckProdEquiv M A B hsup hbot).symm (dA.symm (h₁ i), 1) := by
        show (LineCover.deckProdEquiv M A B hsup hbot).symm (dA.symm (h₁ i), dB.symm 1) = _
        rw [map_one]
      rw [Fin.append_left, padAppend_left, hsymm]
      exact hkey
    | right j =>
      have hinB : (M.sub B).IsInertiaGenAt (u j) (dB.symm (h₂ j)) := by
        have := LineCover.IsInertiaGenAt.transport (L := L₂) (L' := M.sub B) ψ.symm (hin₂ j)
        rwa [hdB, MulEquiv.symm_trans_apply, AlgEquiv.autCongr_symm]
      have hnot : u j ∉ Set.range t := Set.disjoint_right.mp hdisj ⟨j, rfl⟩
      have hinA : (M.sub A).IsInertiaGenAt (u j) 1 :=
        LineCover.isInertiaGenAt_one_of_unramified _ houtA hnot
      have hkey := LineCover.isInertiaGenAt_deckProdEquiv_symm M A B hsup hbot
        (by rw [orderOf_one]; exact Nat.coprime_one_left _) hinA hinB
      have hsymm : ((LineCover.deckProdEquiv M A B hsup hbot).trans
            (MulEquiv.prodCongr dA dB)).symm ((1, h₂ j) : G₁ × G₂)
          = (LineCover.deckProdEquiv M A B hsup hbot).symm (1, dB.symm (h₂ j)) := by
        show (LineCover.deckProdEquiv M A B hsup hbot).symm (dA.symm 1, dB.symm (h₂ j)) = _
        rw [map_one]
      rw [Fin.append_right, padAppend_right, hsymm]
      exact hkey

/-- **Product-one generating branch data over disjoint loci multiply.**

Any two finite groups realized over disjoint sets of points are realized together over the union,
with no hypothesis relating them: the branch cycles of the product are those of the factors, each
padded by the identity of the other. -/
theorem exists_isMonodromyOver_prod {G₁ G₂ : Type} [Group G₁] [Finite G₁] [Group G₂] [Finite G₂]
    {r s : ℕ} {h₁ : Fin r → G₁} {h₂ : Fin s → G₂} {t : Fin r → k} {u : Fin s → k}
    (hdisj : Disjoint (Set.range t) (Set.range u))
    (hp₁ : (List.ofFn h₁).prod = 1) (hp₂ : (List.ofFn h₂).prod = 1)
    (ht₁ : Subgroup.closure (Set.range h₁) = ⊤) (ht₂ : Subgroup.closure (Set.range h₂) = ⊤)
    (H₁ : IsMonodromyOver h₁ t) (H₂ : IsMonodromyOver h₂ u) :
    ∃ h : Fin (r + s) → G₁ × G₂, (List.ofFn h).prod = 1 ∧
      Subgroup.closure (Set.range h) = ⊤ ∧ IsMonodromyOver h (Fin.append t u) :=
  ⟨padAppend h₁ h₂, prod_ofFn_padAppend h₁ h₂ hp₁ hp₂,
    closure_range_padAppend_eq_top ht₁ ht₂, H₁.prod_disjoint hdisj H₂⟩

end Rigidity.RET
