/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.MultiKummerInertia
import InverseGalois.Rigidity.RET.ExistenceLowRank

/-!
# The existence direction of the covers correspondence, for a cyclic group

`GeomRET.exists_cover` asserts that a product-one generating tuple `h₀, …, h_{r-1}` in a finite
group `H` is the tuple of branch cycles of a cover of the line branched over prescribed points
`t₀, …, t_{r-1}`.  For a **cyclic** `H` that assertion is a theorem, with no geometric input, and
this file proves it for every number of branch points.

The cover is the multi-point Kummer cover `wⁿ = ∏ᵢ (T - tᵢ)^{aᵢ}` of `RET/MultiKummer.lean`, where
`n = |H|` and `aᵢ` is the exponent of `hᵢ` read through an isomorphism `H ≅ ℤ/n`.  The three
hypotheses of the correspondence translate into the three hypotheses of that construction:

* `hᵢ` generate `H` ⟹ the `aᵢ` are jointly coprime to `n`, which is what makes the Kummer
  equation irreducible and its deck group all of `ℤ/n`;
* `∏ᵢ hᵢ = 1` ⟹ `n ∣ ∑ᵢ aᵢ`, which is what makes the cover unramified at infinity;
* the points are distinct ⟹ the inertia group at `tⱼ` is generated by the deck transformation
  `w ↦ ζ^{aⱼ} w`, which is the image of `hⱼ`.

The condition at infinity is the geometric shadow of the product-one relation: the branch cycles of
a cover of the line multiply to the inverse of the branch cycle at infinity, so `∏ᵢ hᵢ = 1` says
exactly that nothing is left over there.

## Main results

* `Rigidity.RET.exists_cover_of_isCyclic` — the existence direction of `GeomRET`, with the branch
  points named and the distinguished-inertia clause, for a finite cyclic group and any number of
  branch points.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

/-- **The existence direction of the covers correspondence for a cyclic group**, with the branch
points named and the distinguished-inertia clause, for any number of branch points. -/
theorem exists_cover_of_isCyclic {r : ℕ} (t : Fin r → k) (ht : Function.Injective t)
    {H : Type} [Group H] [Finite H] [IsCyclic H] (h : Fin r → H)
    (hprod : (List.ofFn h).prod = 1) (htop : Subgroup.closure (Set.range h) = ⊤) :
    ∃ (L : LineCover) (e : L.deck ≃* H),
      L.IsUnramifiedOutside (Set.range t) ∧ L.IsUnramifiedAtInfinity ∧
      ∀ i, L.IsInertiaGenAt (t i) (e.symm (h i)) := by
  haveI : NeZero (Nat.card H) := ⟨Nat.card_pos.ne'⟩
  set n : ℕ := Nat.card H with hn
  set φ : Multiplicative (ZMod n) ≃* H := zmodCyclicMulEquiv (inferInstance : IsCyclic H) with hφ
  -- the exponent of `h i`, read in `ℤ/n`
  set a : Fin r → ℕ := fun i => ((φ.symm (h i)).toAdd).val with hadef
  have hofAdd : ∀ i, Multiplicative.ofAdd ((a i : ℕ) : ZMod n) = φ.symm (h i) := by
    intro i
    show Multiplicative.ofAdd (((((φ.symm (h i)).toAdd).val : ℕ) : ZMod n)) = φ.symm (h i)
    rw [ZMod.natCast_val, ZMod.cast_id]
    rfl
  -- the exponents generate `ℤ/n`, so the Kummer equation is irreducible
  have htop' : Subgroup.closure (Set.range fun i => φ.symm (h i)) = ⊤ := by
    calc Subgroup.closure (Set.range fun i => φ.symm (h i))
        = Subgroup.closure (φ.symm '' Set.range h) := by rw [← Set.range_comp]; rfl
      _ = Subgroup.map φ.symm.toMonoidHom (Subgroup.closure (Set.range h)) :=
          (MonoidHom.map_closure _ _).symm
      _ = Subgroup.map φ.symm.toMonoidHom ⊤ := by rw [htop]
      _ = ⊤ := Subgroup.map_top_of_surjective _ φ.symm.surjective
  have hgen : ∀ ee : ℕ, (∀ i, n ∣ a i * ee) → n ∣ ee := by
    intro ee hee
    have hker : ∀ i, (φ.symm (h i)) ^ ee = 1 := by
      intro i
      rw [← hofAdd i, ← ofAdd_nsmul]
      have hz : ee • ((a i : ℕ) : ZMod n) = ((a i * ee : ℕ) : ZMod n) := by
        push_cast
        rw [nsmul_eq_mul]
        ring
      rw [hz, (ZMod.natCast_eq_zero_iff _ _).mpr (hee i)]
      rfl
    have hle : Subgroup.closure (Set.range fun i => φ.symm (h i)) ≤
        (powMonoidHom ee : Multiplicative (ZMod n) →* Multiplicative (ZMod n)).ker := by
      rw [Subgroup.closure_le]
      rintro x ⟨i, rfl⟩
      exact hker i
    rw [htop'] at hle
    have hmem : Multiplicative.ofAdd (1 : ZMod n) ∈
        (powMonoidHom ee : Multiplicative (ZMod n) →* Multiplicative (ZMod n)).ker :=
      hle (Subgroup.mem_top _)
    rw [MonoidHom.mem_ker, powMonoidHom_apply, ← ofAdd_nsmul] at hmem
    have h0 : ee • (1 : ZMod n) = 0 := by
      simpa using hmem
    rw [nsmul_eq_mul, mul_one] at h0
    exact (ZMod.natCast_eq_zero_iff _ _).mp h0
  -- the exponents sum to a multiple of `n`, so the cover is unramified at infinity
  have hprod' : (∏ i, φ.symm (h i)) = 1 := by
    have h1 : (List.ofFn fun i => φ.symm (h i)).prod = 1 := by
      have h2 : (List.ofFn fun i => φ.symm (h i)) = (List.ofFn h).map φ.symm := by
        rw [List.map_ofFn]; rfl
      rw [h2, ← map_list_prod, hprod, map_one]
    rwa [List.prod_ofFn] at h1
  have hkey : ∀ s : Finset (Fin r),
      Multiplicative.ofAdd (∑ i ∈ s, ((a i : ℕ) : ZMod n)) = ∏ i ∈ s, φ.symm (h i) := by
    intro s
    induction s using Finset.induction with
    | empty => simp
    | insert x s hx ih =>
        rw [Finset.sum_insert hx, Finset.prod_insert hx, ofAdd_add, ih, hofAdd]
  have hsum0 : ((∑ i, a i : ℕ) : ZMod n) = 0 := by
    have h1 := hkey Finset.univ
    rw [hprod'] at h1
    have h2 : (∑ i, ((a i : ℕ) : ZMod n)) = 0 := by
      simpa using congrArg Multiplicative.toAdd h1
    rw [Nat.cast_sum]
    exact h2
  obtain ⟨s, hs⟩ : n ∣ ∑ i, a i := (ZMod.natCast_eq_zero_iff _ _).mp hsum0
  -- the multi-point Kummer cover of these data
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k n
  have hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n :=
    hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective
  have hprim : (primitiveRoots n (RatFunc k)).Nonempty :=
    ⟨_, (mem_primitiveRoots (NeZero.pos n)).mpr hζ⟩
  set b : RatFunc k := algebraMap (Polynomial k) (RatFunc k) (multiA t a) with hb
  let M := ((X : (RatFunc k)[X]) ^ n - C b).SplittingField
  have Hirr : Irreducible ((X : (RatFunc k)[X]) ^ n - C b) := irreducible_multiA ht hgen M
  haveI : IsGalois (RatFunc k) M := isGalois_of_isSplittingField_X_pow_sub_C hprim Hirr M
  haveI : FiniteDimensional (RatFunc k) M :=
    IsSplittingField.finiteDimensional M ((X : (RatFunc k)[X]) ^ n - C b)
  let L : LineCover := LineCover.of M
  haveI : IsSplittingField (RatFunc k) L.M ((X : (RatFunc k)[X]) ^ n - C b) :=
    inferInstanceAs (IsSplittingField (RatFunc k) M ((X : (RatFunc k)[X]) ^ n - C b))
  refine ⟨L, (autEquivZmod Hirr M hζ).trans φ, isUnramifiedOutside_multiCover ht hgen L,
    isUnramifiedAtInfinity_multiCover hs Hirr L, ?_⟩
  intro i
  have hi : ((autEquivZmod Hirr M hζ).trans φ).symm (h i)
      = (autEquivZmod Hirr M hζ).symm (Multiplicative.ofAdd ((a i : ℕ) : ZMod n)) := by
    rw [hofAdd i]
    rfl
  rw [hi]
  exact isInertiaGenAt_multiCover ht Hirr L hζ₀ hζ i

end Rigidity.RET
