/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.FreeAbelianCover
import InverseGalois.Rigidity.RET.CyclicCycles

/-!
# The free abelian cover swallows every admissible Kummer equation

The free abelian cover of the line on `s + 1` points, of exponent `n`, is generated by radicals
`w_l ⁿ = (T - t_l) (T - t_s)^{n-1}`.  A monomial in those radicals is an `n`-th root of the
multi-point datum `∏ᵢ (T - tᵢ)^{cᵢ}` whose exponent at the last point is forced; correcting by a
power of `T - t_s` — which is legitimate exactly when the exponents of the datum sum to `0` modulo
the degree — produces a root of *any* multi-point Kummer equation `X^m - ∏ᵢ (T - tᵢ)^{aᵢ}` with
`m` dividing `n` and `m` dividing `∑ᵢ aᵢ`.  Such an equation therefore splits in the free abelian
cover.

Those two conditions are exactly what a cyclic cover of the line unramified outside the points and
infinity satisfies: `m` is its degree, which divides the exponent of any deck group it is a
quotient of, and `m ∣ ∑ᵢ aᵢ` is unramifiedness at infinity.  So the free abelian cover contains a
copy of every cyclic cover with that branch locus, which is what makes it universal for abelian
covers.

## Main results

* `Rigidity.RET.splits_X_pow_sub_C_multiA_of_free` — an admissible multi-point Kummer equation
  splits in the free abelian cover.
* `Rigidity.RET.exists_cover_free_universal` — the free abelian cover of the line, with its system
  of distinguished branch cycles and the splitting property.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-! ### Splitting an admissible Kummer equation in the free abelian cover -/

section Splits

variable {s n : ℕ} [NeZero n] {t : Fin (s + 1) → k}
  {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] {y : Fin s → Ω}

/-- The last linear factor of a multi-point datum, as an element of the cover. -/
private def lastFactor (t : Fin (s + 1) → k) (Ω : Type) [Field Ω] [Algebra (RatFunc k) Ω] : Ω :=
  algebraMap (RatFunc k) Ω
    (algebraMap (Polynomial k) (RatFunc k) (X - C (t (Fin.last s))))

private theorem lastFactor_ne_zero : lastFactor t Ω ≠ 0 := by
  refine (map_ne_zero_iff _ (algebraMap (RatFunc k) Ω).injective).mpr ?_
  exact (map_ne_zero_iff _ (IsFractionRing.injective (Polynomial k) (RatFunc k))).mpr
    (X_sub_C_ne_zero (t (Fin.last s)))

/-- **Two multi-point data with the same exponents away from the last point differ by a power of
the last linear factor.** -/
private theorem multiA_div_multiA (a b : Fin (s + 1) → ℕ)
    (hab : ∀ j : Fin s, a j.castSucc = b j.castSucc) :
    algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k) (multiA t b))
      = algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k) (multiA t a))
        * lastFactor t Ω ^ ((b (Fin.last s) : ℤ) - (a (Fin.last s) : ℤ)) := by
  have hsplit : ∀ c : Fin (s + 1) → ℕ,
      algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k) (multiA t c))
        = (∏ j : Fin s, algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k)
            ((X - C (t j.castSucc)) ^ c j.castSucc))) * lastFactor t Ω ^ (c (Fin.last s)) := by
    intro c
    rw [multiA, Fin.prod_univ_castSucc, map_mul, map_mul, map_prod, map_prod, lastFactor,
      map_pow, map_pow]
  have hpre : (∏ j : Fin s, algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k)
        ((X - C (t j.castSucc)) ^ b j.castSucc)))
      = ∏ j : Fin s, algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k)
        ((X - C (t j.castSucc)) ^ a j.castSucc)) :=
    Finset.prod_congr rfl fun j _ => by rw [hab j]
  have hexp : ((a (Fin.last s) : ℤ)) + ((b (Fin.last s) : ℤ) - (a (Fin.last s) : ℤ))
      = (b (Fin.last s) : ℤ) := by ring
  rw [hsplit a, hsplit b, hpre, ← zpow_natCast (lastFactor t Ω) (b (Fin.last s)),
    ← zpow_natCast (lastFactor t Ω) (a (Fin.last s)), mul_assoc,
    ← zpow_add₀ lastFactor_ne_zero, hexp]

/-- **Every admissible multi-point Kummer equation has a root in the free abelian cover.**

The exponents `a` are admissible when the degree `m` divides both the exponent `n` of the cover
and the sum `∑ᵢ aᵢ`; the second condition is unramifiedness at infinity. -/
theorem exists_pow_eq_multiA_of_free
    (hy : ∀ l, y l ^ n = algebraMap (RatFunc k) Ω (freeB n t l))
    {m : ℕ} (hmn : m ∣ n) (a : Fin (s + 1) → ℕ) (hsum : m ∣ ∑ i, a i) :
    ∃ w : Ω, w ^ m
      = algebraMap (RatFunc k) Ω (algebraMap (Polynomial k) (RatFunc k) (multiA t a)) := by
  classical
  set c : Fin s → ℕ := fun l => a l.castSucc with hc
  set A : Ω := algebraMap (RatFunc k) Ω
    (algebraMap (Polynomial k) (RatFunc k) (multiA t a)) with hA
  set u : Ω := lastFactor t Ω with hu
  have hune : u ≠ 0 := lastFactor_ne_zero
  set E : ℕ := ∑ l, c l with hE
  set D : ℤ := ((freeExp n c (Fin.last s) : ℤ) - (a (Fin.last s) : ℤ)) with hD
  -- the monomial in the radicals is an `n`-th root of a datum differing from `a` at the last point
  have hz : (∏ l, y l ^ c l) ^ n = A * u ^ D := by
    rw [freeMonomial_pow hy c, hA, hu]
    exact multiA_div_multiA a (freeExp n c) fun j => by rw [freeExp_castSucc]
  -- the discrepancy at the last point is a multiple of the degree
  have hmD : (m : ℤ) ∣ D := by
    have hone : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr (NeZero.ne n)
    have hlast : (freeExp n c (Fin.last s) : ℤ) = (n : ℤ) * (E : ℤ) - (E : ℤ) := by
      rw [freeExp_last, Nat.cast_mul, Nat.cast_sub hone, Nat.cast_one, sub_mul, one_mul]
    have hsum' : (m : ℤ) ∣ ((E : ℤ) + (a (Fin.last s) : ℤ)) := by
      have : ∑ i, a i = E + a (Fin.last s) := by
        rw [hE, hc, Fin.sum_univ_castSucc]
      exact_mod_cast (Int.natCast_dvd_natCast.mpr (this ▸ hsum))
    have hnE : (m : ℤ) ∣ (n : ℤ) * (E : ℤ) :=
      Dvd.dvd.mul_right (Int.natCast_dvd_natCast.mpr hmn) _
    have : D = (n : ℤ) * (E : ℤ) - ((E : ℤ) + (a (Fin.last s) : ℤ)) := by
      rw [hD, hlast]; ring
    rw [this]
    exact dvd_sub hnE hsum'
  -- correct the monomial by the discrepancy
  refine ⟨(∏ l, y l ^ c l) ^ (n / m) * u ^ (-(D / (m : ℤ))), ?_⟩
  rw [mul_pow, ← pow_mul, Nat.div_mul_cancel hmn, hz, ← zpow_natCast (u ^ (-(D / (m : ℤ)))) m,
    ← zpow_mul, neg_mul, Int.ediv_mul_cancel hmD]
  rw [mul_assoc, ← zpow_add₀ hune, add_neg_cancel, zpow_zero, mul_one]

/-- **An admissible multi-point Kummer equation splits in the free abelian cover.** -/
theorem splits_X_pow_sub_C_multiA_of_free
    (hy : ∀ l, y l ^ n = algebraMap (RatFunc k) Ω (freeB n t l))
    {m : ℕ} (hm : 0 < m) (hmn : m ∣ n) (a : Fin (s + 1) → ℕ) (hsum : m ∣ ∑ i, a i) :
    (((X : (RatFunc k)[X]) ^ m - C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))).map
      (algebraMap (RatFunc k) Ω)).Splits := by
  haveI : NeZero m := ⟨hm.ne'⟩
  obtain ⟨w, hw⟩ := exists_pow_eq_multiA_of_free hy hmn a hsum
  obtain ⟨ζ₁, hζ₁⟩ := exists_primitiveRoot_k m
  have hζ : IsPrimitiveRoot
      (algebraMap (RatFunc k) Ω (algebraMap k (RatFunc k) ζ₁)) m :=
    hζ₁.map_of_injective (f := (algebraMap (RatFunc k) Ω).comp (algebraMap k (RatFunc k)))
      ((algebraMap (RatFunc k) Ω).injective.comp (algebraMap k (RatFunc k)).injective)
  simpa only [Polynomial.map_sub, Polynomial.map_pow, map_X, map_C] using
    X_pow_sub_C_splits_of_isPrimitiveRoot hζ hw

end Splits

/-! ### The free abelian cover, packaged -/

section Package

variable {s n : ℕ} [NeZero n] {t : Fin (s + 1) → k}

/-- **Every admissible multi-point Kummer equation splits in a splitting field of the defining
polynomial of the free abelian cover.** -/
theorem splits_multiA_of_isSplittingField (L : LineCover)
    [IsSplittingField (RatFunc k) L.M (freePoly n t)]
    {m : ℕ} (hm : 0 < m) (hmn : m ∣ n) (a : Fin (s + 1) → ℕ) (hsum : m ∣ ∑ i, a i) :
    (((X : (RatFunc k)[X]) ^ m - C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))).map
      (algebraMap (RatFunc k) L.M)).Splits := by
  have hroot : ∀ l, ∃ x : L.M, x ^ n = algebraMap (RatFunc k) L.M (freeB n t l) := by
    intro l
    have hdvdP : ((X : (RatFunc k)[X]) ^ n - C (freeB n t l)) ∣ freePoly n t := by
      rw [freePoly]
      exact Finset.dvd_prod_of_mem _ (Finset.mem_univ l)
    have hsplit : (((X : (RatFunc k)[X]) ^ n - C (freeB n t l)).map
        (algebraMap (RatFunc k) L.M)).Splits :=
      Polynomial.Splits.of_dvd (IsSplittingField.splits L.M (freePoly n t))
        ((Polynomial.map_ne_zero_iff (algebraMap (RatFunc k) L.M).injective).mpr
          (freePoly_ne_zero n t))
        (Polynomial.map_dvd _ hdvdP)
    obtain ⟨x, hx⟩ := hsplit.exists_eval_eq_zero (by
      rw [Polynomial.map_sub, Polynomial.map_pow, map_X, map_C,
        degree_X_pow_sub_C (NeZero.pos n)]
      exact_mod_cast (NeZero.pos n).ne')
    refine ⟨x, ?_⟩
    rw [Polynomial.map_sub, Polynomial.map_pow, map_X, map_C, eval_sub, eval_pow, eval_X, eval_C,
      sub_eq_zero] at hx
    exact hx
  choose y hy using hroot
  exact splits_X_pow_sub_C_multiA_of_free hy hm hmn a hsum

/-- The standard tuple of branch cycles of the free abelian cover: the coordinate vectors at the
first `s` points, and the inverse of their product at the last one. -/
def freeCycles (L : LineCover) (e : L.deck ≃* (Fin s → Multiplicative (ZMod n))) :
    Fin (s + 1) → L.deck :=
  Fin.lastCases (e.symm (fun _ => Multiplicative.ofAdd (1 : ZMod n))⁻¹)
    fun j => e.symm (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)))

/-- **The standard tuple of the free abelian cover is a system of distinguished branch cycles.**

The coordinate vectors generate the deck group, and their ordered product cancels against the
inverse diagonal vector sitting at the last point. -/
theorem isBranchCycleGenSystem_freeCycles (L : LineCover)
    (e : L.deck ≃* (Fin s → Multiplicative (ZMod n)))
    (hgen : ∀ j : Fin s, L.IsInertiaGenAt (t j.castSucc)
      (e.symm (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)))))
    (hlast : 0 < s → L.IsInertiaGenAt (t (Fin.last s))
      (e.symm (fun _ => Multiplicative.ofAdd (1 : ZMod n))⁻¹)) :
    L.IsBranchCycleGenSystem t (freeCycles L e) where
  inertia i := by
    induction i using Fin.lastCases with
    | last =>
        rw [freeCycles, Fin.lastCases_last]
        rcases Nat.eq_zero_or_pos s with rfl | hs
        · -- with no coordinates the deck group is trivial and every inertia group is trivial
          haveI : Subsingleton L.deck := Equiv.subsingleton e.toEquiv
          obtain ⟨Q, hQmax, hQover⟩ := L.exists_place (t (Fin.last 0))
          refine ⟨Q, hQmax, hQover, ?_⟩
          rw [Subgroup.eq_bot_of_subsingleton (geomInertia L.M Q),
            Subgroup.eq_bot_of_subsingleton (Subgroup.zpowers
              (e.symm (fun _ => Multiplicative.ofAdd (1 : ZMod n))⁻¹))]
        · exact hlast hs
    | cast j =>
        rw [freeCycles, Fin.lastCases_castSucc]
        exact hgen j
  top := by
    have hstd : ∀ j : Fin s, e.symm (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)))
        ∈ Subgroup.closure (Set.range (freeCycles L e)) := fun j =>
      Subgroup.subset_closure ⟨j.castSucc, by rw [freeCycles, Fin.lastCases_castSucc]⟩
    have hpow : ∀ (j : Fin s) (v : Multiplicative (ZMod n)),
        (Pi.mulSingle j v : Fin s → Multiplicative (ZMod n))
          = (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)) :
              Fin s → Multiplicative (ZMod n)) ^ (Multiplicative.toAdd v).val := by
      intro j v
      funext l
      rcases eq_or_ne l j with rfl | hl
      · rw [Pi.mulSingle_eq_same, Pi.pow_apply, Pi.mulSingle_eq_same, ← ofAdd_nsmul]
        simp
      · rw [Pi.mulSingle_eq_of_ne hl, Pi.pow_apply, Pi.mulSingle_eq_of_ne hl, one_pow]
    -- the coordinate vectors generate the group of exponents
    have hgentop : Subgroup.closure
        (Set.range (fun j : Fin s => (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)) :
          Fin s → Multiplicative (ZMod n)))) = ⊤ := by
      rw [Subgroup.eq_top_iff']
      intro v
      rw [← Finset.univ_prod_mulSingle v]
      refine prod_mem fun j _ => ?_
      rw [hpow j (v j)]
      have hj : (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)) :
            Fin s → Multiplicative (ZMod n))
          ∈ Subgroup.closure (Set.range (fun j : Fin s =>
            (Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)) :
              Fin s → Multiplicative (ZMod n)))) :=
        Subgroup.subset_closure ⟨j, rfl⟩
      exact pow_mem hj _
    -- so their preimages generate the deck group
    have hle : (⊤ : Subgroup (Fin s → Multiplicative (ZMod n))) ≤
        Subgroup.map e.toMonoidHom (Subgroup.closure (Set.range (freeCycles L e))) := by
      rw [← hgentop, Subgroup.closure_le]
      rintro _ ⟨j, rfl⟩
      have hmem := Subgroup.mem_map_of_mem e.toMonoidHom (hstd j)
      simpa using hmem
    rw [Subgroup.eq_top_iff']
    intro x
    obtain ⟨y, hy, hyx⟩ := hle (Subgroup.mem_top (e x))
    rwa [e.injective hyx] at hy
  prod := by
    refine e.injective ?_
    rw [map_one, map_list_prod, List.map_ofFn, List.prod_ofFn, Fin.prod_univ_castSucc]
    have hc : ∀ j : Fin s, (e ∘ freeCycles L e) j.castSucc
        = Pi.mulSingle j (Multiplicative.ofAdd (1 : ZMod n)) := by
      intro j
      show e (freeCycles L e j.castSucc) = _
      rw [freeCycles, Fin.lastCases_castSucc, e.apply_symm_apply]
    have hl : (e ∘ freeCycles L e) (Fin.last s)
        = (fun _ => Multiplicative.ofAdd (1 : ZMod n))⁻¹ := by
      show e (freeCycles L e (Fin.last s)) = _
      rw [freeCycles, Fin.lastCases_last, e.apply_symm_apply]
    rw [hl, Finset.prod_congr rfl fun j _ => hc j,
      Finset.univ_prod_mulSingle (fun _ : Fin s => Multiplicative.ofAdd (1 : ZMod n)),
      mul_inv_cancel]

/-- **The free abelian cover of the line, with its branch cycles and its universality.**

For `s + 1` points of the line and an exponent `n` there is a cover unramified outside those
points and infinity, carrying a system of distinguished branch cycles over them, in which every
multi-point Kummer equation of degree dividing `n` with exponent sum divisible by the degree
splits. -/
theorem exists_cover_free_universal (n : ℕ) [NeZero n] {s : ℕ} (t : Fin (s + 1) → k)
    (ht : Function.Injective t) :
    ∃ (L : LineCover) (g : Fin (s + 1) → L.deck),
      L.IsUnramifiedOutside (Set.range t) ∧ L.IsUnramifiedAtInfinity ∧
      L.IsBranchCycleGenSystem t g ∧
      ∀ (m : ℕ) (a : Fin (s + 1) → ℕ), 0 < m → m ∣ n → m ∣ ∑ i, a i →
        (((X : (RatFunc k)[X]) ^ m -
            C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))).map
          (algebraMap (RatFunc k) L.M)).Splits := by
  obtain ⟨L, e, hsf, hout, hinf, hgen, hlast⟩ := exists_cover_free n t ht
  haveI := hsf
  exact ⟨L, freeCycles L e, hout, hinf, isBranchCycleGenSystem_freeCycles L e hgen hlast,
    fun m a hm hmn hsum => splits_multiA_of_isSplittingField L hm hmn a hsum⟩

end Package

end Rigidity.RET
