/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.GeomPi1
import InverseGalois.Rigidity.RET.GeomPi1Abelian
import InverseGalois.Rigidity.RET.NilpotentCycles

/-!
# The nilpotent quotients of the geometric fundamental group

For a nilpotent group generation modulo commutators is generation, so the count that bounds the
abelianization of a group occurring over `r + 1` points bounds the group itself: a finite nilpotent
group occurring over `r + 1` points is generated by `r` elements, and a nilpotent group needing
more generators than that does not occur.  Through the dictionary between covers over a set of
points and finite quotients of the geometric fundamental group, the same count describes the
nilpotent quotients of that group.

Only this direction is available beyond the abelian case: producing a cover with a prescribed
nilpotent deck group is the existence half of the Riemann existence theorem.

## Main results

* `Rigidity.RET.exists_generating_of_generating_abelianization` — in a finite nilpotent group,
  lifts of generators of the abelianization generate.
* `Rigidity.RET.exists_generating_of_isDeckGroupOver_of_isNilpotent` — a nilpotent group occurring
  over `r + 1` points is generated by `r` elements.
* `Rigidity.RET.exists_generating_of_surjective_geomPi1_of_isNilpotent` — the same read as a
  statement about the nilpotent quotients of the fundamental group.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-! ### Lifting generators through the abelianization -/

/-- **In a finite nilpotent group, generators of the abelianization lift to generators.**  The
subgroup they generate maps onto the abelianization, hence together with the commutator subgroup is
everything, and in a nilpotent group that already forces it to be everything. -/
theorem exists_generating_of_generating_abelianization {G : Type*} [Group G] [Finite G]
    [Group.IsNilpotent G] {r : ℕ} {s : Fin r → Abelianization G}
    (hs : Subgroup.closure (Set.range s) = ⊤) :
    ∃ s' : Fin r → G, Subgroup.closure (Set.range s') = ⊤ := by
  have hsurj : Function.Surjective (Abelianization.of : G →* Abelianization G) :=
    QuotientGroup.mk'_surjective (commutator G)
  choose s' hs' using fun i => hsurj (s i)
  refine ⟨s', eq_top_of_sup_commutator_eq_top ?_⟩
  have hker : (Abelianization.of : G →* Abelianization G).ker ≤
      Subgroup.closure (Set.range s') ⊔ commutator G := by
    rw [Abelianization.ker_of]
    exact le_sup_right
  have hmap : Subgroup.map (Abelianization.of : G →* Abelianization G)
      (Subgroup.closure (Set.range s') ⊔ commutator G) = ⊤ := by
    refine eq_top_iff.mpr ?_
    rw [← hs]
    refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨i, rfl⟩
    exact ⟨s' i, Subgroup.mem_sup_left (Subgroup.subset_closure ⟨i, rfl⟩), hs' i⟩
  have hcm := Subgroup.comap_map_eq_self hker
  rw [hmap, Subgroup.comap_top] at hcm
  exact hcm.symm

/-! ### Nilpotent groups over a prescribed set of points -/

/-- **A finite nilpotent group occurring over `r + 1` points is generated by `r` elements.**  The
branch cycles generate the abelianization, and for a nilpotent group that is enough. -/
theorem exists_generating_of_isDeckGroupOver_of_isNilpotent {S : Set k} (hS : S.Finite) {r : ℕ}
    (hcard : hS.toFinset.card = r + 1) {G : Type} [Group G] [Finite G] [Group.IsNilpotent G]
    (h : IsDeckGroupOver S G) : ∃ s : Fin r → G, Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨s, hs⟩ := exists_generating_abelianization_of_isDeckGroupOver hS hcard h
  exact exists_generating_of_generating_abelianization hs

/-- **A nilpotent group needing more than `r` generators does not occur over `r + 1` points.** -/
theorem not_isDeckGroupOver_of_isNilpotent {S : Set k} (hS : S.Finite) {r : ℕ}
    (hcard : hS.toFinset.card = r + 1) {G : Type} [Group G] [Finite G] [Group.IsNilpotent G]
    (hgen : ∀ s : Fin r → G, Subgroup.closure (Set.range s) ≠ ⊤) : ¬ IsDeckGroupOver S G := by
  intro h
  obtain ⟨s, hs⟩ := exists_generating_of_isDeckGroupOver_of_isNilpotent hS hcard h
  exact hgen s hs

/-! ### Nilpotent quotients of the fundamental group -/

/-- **A finite nilpotent quotient of the fundamental group of the line with `r + 1` punctures is
generated by `r` elements.** -/
theorem exists_generating_of_surjective_geomPi1_of_isNilpotent {S : Set k} (hS : S.Finite) {r : ℕ}
    (hcard : hS.toFinset.card = r + 1) {G : Type} [Group G] [Finite G] [Group.IsNilpotent G]
    (φ : geomPi1 S →* G) (hφ : Function.Surjective φ)
    (hopen : IsOpen (φ.ker : Set (geomPi1 S))) :
    ∃ s : Fin r → G, Subgroup.closure (Set.range s) = ⊤ :=
  exists_generating_of_isDeckGroupOver_of_isNilpotent hS hcard
    (isDeckGroupOver_of_surjective φ hφ hopen)

/-- **A nilpotent group needing more than `r` generators is not a finite quotient of the
fundamental group of the line with `r + 1` punctures.** -/
theorem not_exists_surjective_geomPi1_of_isNilpotent {S : Set k} (hS : S.Finite) {r : ℕ}
    (hcard : hS.toFinset.card = r + 1) {G : Type} [Group G] [Finite G] [Group.IsNilpotent G]
    (hgen : ∀ s : Fin r → G, Subgroup.closure (Set.range s) ≠ ⊤) :
    ¬ ∃ φ : geomPi1 S →* G, Function.Surjective φ ∧ IsOpen (φ.ker : Set (geomPi1 S)) := by
  rw [← isDeckGroupOver_iff_exists_surjective]
  exact not_isDeckGroupOver_of_isNilpotent hS hcard hgen

end Rigidity.RET
