/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Geometric (absolute) irreducibility from regularity

This file supplies the **regularity teeth** of the model translation
(`InverseGalois.Rigidity.RET.Specialization`): if `L / ℚ(T)` is a finite Galois extension in
which `ℚ` is relatively algebraically closed (`algebraicClosure ℚ L = ⊥`, "regular"), then the
primitive-element polynomial of `L / ℚ(T)` stays **absolutely irreducible** — irreducible after
base change to `ℚ̄(T)`.

## Structure of the argument

The statement factors into two recognizable pieces:

* **Transfer** (`irreducible_map_minpoly_of_isField_baseChange`, axiom-free, present-API):
  for a finite extension `L / K` generated by `β`, if the base change `K' ⊗[K] L` is a *field*,
  then `minpoly K β` stays irreducible over `K'`.  This is the algebra: base-change a power basis
  (`Basis.baseChange`), read off that `1 ⊗ β` generates `K' ⊗[K] L` over `K'` with degree
  `[L : K]`, and match `(minpoly K β).map` (monic, same degree, vanishing at `1 ⊗ β`) with the
  minimal polynomial.

* **Core** (`isField_baseChange_of_regular`): `K' ⊗[K] L` is a field, from regularity.  This is
  the geometric-integrality content — linear disjointness of `L` and `ℚ̄` over `ℚ` (Galois
  averaging), which Mathlib does *not* provide as a lemma.  Isolated here as the honest gap.
-/

open Polynomial TensorProduct

namespace Rigidity.RET

noncomputable section

/-- **Crux: irreducibility descends from a relatively algebraically closed base.**
If `k` is relatively algebraically closed in `L` (`algebraicClosure k L = ⊥`), then every monic
irreducible polynomial over `k` stays irreducible after base change to `L`.

Proof: any monic factor `f` of `p.map` over `L` has, by Vieta on its roots (which are roots of the
monic `p ∈ k[X]`, hence integral over `k`), coefficients integral over `k`
(`Polynomial.isIntegral_coeff_of_dvd`); relative algebraic closedness (`hbot`) puts those
coefficients back in `k`, so `f` descends to a monic factor `f₀ ∣ p` — which, `p` being irreducible,
is trivial. -/
theorem irreducible_map_of_algClosure_eq_bot
    {k L : Type*} [Field k] [Field L] [Algebra k L]
    (hbot : algebraicClosure k L = ⊥)
    {p : k[X]} (hpmonic : p.Monic) (hp : Irreducible p) :
    Irreducible (p.map (algebraMap k L)) := by
  classical
  have hpdeg : 0 < p.natDegree := hp.natDegree_pos
  have hmapdeg : (p.map (algebraMap k L)).natDegree = p.natDegree :=
    Polynomial.natDegree_map_eq_of_injective (algebraMap k L).injective p
  rw [(hpmonic.map (algebraMap k L)).irreducible_iff_natDegree]
  refine ⟨?_, ?_⟩
  · -- `p.map ≠ 1`, since it has positive degree.
    intro h
    rw [h, Polynomial.natDegree_one] at hmapdeg
    omega
  · intro f g hf hg hfg
    -- `f` is a monic factor of `p.map`, so its coefficients are integral over `k`.
    have hfdvd : f ∣ p.map (algebraMap k L) := ⟨g, hfg.symm⟩
    have hcoeff : ∀ i, IsIntegral k (f.coeff i) := fun i =>
      Polynomial.isIntegral_coeff_of_dvd p f hpmonic hf hfdvd i
    -- Relative algebraic closedness pulls those coefficients back into `k`, so `f` lifts.
    have hlift : f ∈ Polynomial.lifts (algebraMap k L) := by
      rw [Polynomial.lifts_iff_coeff_lifts]
      intro i
      have hmem : f.coeff i ∈ algebraicClosure k L := mem_algebraicClosure_iff'.2 (hcoeff i)
      rw [hbot, IntermediateField.mem_bot] at hmem
      exact hmem
    obtain ⟨f₀, hf₀⟩ := (Polynomial.mem_lifts _).1 hlift
    -- The lift `f₀` divides `p`, which is irreducible.
    have hf₀dvd : f₀ ∣ p := by
      rw [← Polynomial.map_dvd_map' (algebraMap k L), hf₀]; exact hfdvd
    obtain ⟨c, hc⟩ := hf₀dvd
    rcases hp.isUnit_or_isUnit hc with hu | hu
    · -- `f₀` is a unit, so `f = f₀.map` is constant.
      left
      rw [← hf₀, Polynomial.natDegree_map_eq_of_injective (algebraMap k L).injective,
        Polynomial.natDegree_eq_zero_of_isUnit hu]
    · -- `c` is a unit, so `f₀` (hence `f`) has full degree, forcing `g` constant.
      right
      have hcdeg : c.natDegree = 0 := Polynomial.natDegree_eq_zero_of_isUnit hu
      have hc0 : c ≠ 0 := hu.ne_zero
      have hf00 : f₀ ≠ 0 := by
        rintro rfl; rw [Polynomial.map_zero] at hf₀; exact hf.ne_zero hf₀.symm
      have hf₀deg : f₀.natDegree = p.natDegree := by
        rw [hc, Polynomial.natDegree_mul hf00 hc0, hcdeg, add_zero]
      have hfdeg : f.natDegree = p.natDegree := by
        rw [← hf₀, Polynomial.natDegree_map_eq_of_injective (algebraMap k L).injective, hf₀deg]
      have : f.natDegree + g.natDegree = (p.map (algebraMap k L)).natDegree := by
        rw [← hfg, Polynomial.natDegree_mul hf.ne_zero hg.ne_zero]
      rw [hfdeg, hmapdeg] at this
      omega

/-- **Base-change irreducibility transfer.**  If `β` generates the finite field extension `L / K`
(so `minpoly K β` is a primitive-element polynomial of degree `[L : K]`) and the base change
`K' ⊗[K] L` is a *field*, then `minpoly K β` stays irreducible after base change to `K'`.

All of this is standard algebra available in Mathlib: `1 ⊗ β` generates `K' ⊗[K] L` over `K'`
(base change of the power basis of `L`), and `(minpoly K β).map (algebraMap K K')` is a monic
polynomial of degree `[L : K] = [K' ⊗ L : K']` vanishing at `1 ⊗ β`, hence equal to its minimal
polynomial. -/
theorem irreducible_map_minpoly_of_isField_baseChange
    {K L K' : Type*} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L]
    [Field K'] [Algebra K K']
    (β : L) (hβgen : IntermediateField.adjoin K {β} = ⊤)
    (hfield : IsField (K' ⊗[K] L)) :
    Irreducible ((minpoly K β).map (algebraMap K K')) := by
  classical
  -- Make the base change a field, so minimal polynomials over `K'` behave.
  letI : Field (K' ⊗[K] L) := hfield.toField
  -- `β` is integral over `K`.
  have hβint : IsIntegral K β := IsIntegral.of_finite K β
  -- Power basis of `L / K` with generator `β` (transport the adjoin power basis through
  -- `K⟮β⟯ = ⊤ ≃ L`).
  let pbL : PowerBasis K L :=
    (IntermediateField.adjoin.powerBasis hβint).map
      ((IntermediateField.equivOfEq hβgen).trans IntermediateField.topEquiv)
  have hpbLgen : pbL.gen = β := by
    simp only [pbL, PowerBasis.map, AlgEquiv.trans_apply, IntermediateField.equivOfEq_apply,
      IntermediateField.topEquiv_apply, IntermediateField.adjoin.powerBasis]
    exact IntermediateField.AdjoinSimple.coe_gen K β
  -- The generator `x = 1 ⊗ β` of the base change.
  let x : K' ⊗[K] L := Algebra.TensorProduct.includeRight β
  have hxdef : x = Algebra.TensorProduct.includeRight β := rfl
  -- Base change the power basis: `x` generates `K' ⊗[K] L` over `K'`, with `dim = pbL.dim`.
  let pbD : PowerBasis K' (K' ⊗[K] L) :=
    { gen := x
      dim := pbL.dim
      basis := pbL.basis.baseChange K'
      basis_eq_pow := fun i => by
        rw [Module.Basis.baseChange_apply, pbL.basis_eq_pow, hpbLgen, hxdef, ← map_pow,
          Algebra.TensorProduct.includeRight_apply] }
  -- Degree bookkeeping: `deg (minpoly K' x) = pbD.dim = pbL.dim = deg (minpoly K β)`.
  have hdimL : pbL.dim = (minpoly K β).natDegree := by
    have := pbL.natDegree_minpoly
    rw [hpbLgen] at this; omega
  have hdegD : (minpoly K' x).natDegree = (minpoly K β).natDegree := by
    have := pbD.natDegree_minpoly
    simpa [pbD, hdimL] using this
  -- `x` is integral over `K'`.
  have hxint : IsIntegral K' x := pbD.isIntegral_gen
  -- `(minpoly K β).map (algebraMap K K')` is monic and vanishes at `x`.
  have hmapmonic : ((minpoly K β).map (algebraMap K K')).Monic :=
    (minpoly.monic hβint).map _
  have hvanish : aeval x ((minpoly K β).map (algebraMap K K')) = 0 := by
    rw [Polynomial.aeval_map_algebraMap, hxdef, Polynomial.aeval_algHom_apply, minpoly.aeval,
      map_zero]
  -- Therefore `minpoly K' x ∣ (minpoly K β).map`, and they are monic of equal degree.
  have hdvd : minpoly K' x ∣ (minpoly K β).map (algebraMap K K') := minpoly.dvd _ _ hvanish
  have hdeg_le : ((minpoly K β).map (algebraMap K K')).natDegree ≤ (minpoly K' x).natDegree := by
    rw [hdegD, Polynomial.natDegree_map_eq_of_injective (algebraMap K K').injective]
  have heq : (minpoly K β).map (algebraMap K K') = minpoly K' x :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hxint) hmapmonic hdvd hdeg_le
  rw [heq]
  exact minpoly.irreducible hxint

end

/-! ## Finite building block: base change of a simple extension

The reusable heart of the regularity argument.  For a **finite** extension `E / F` and any field
`K / F`, if the minimal polynomial of a primitive element of `E` stays irreducible over `K`, then
`K ⊗[F] E` is a field.  Combined with the crux `irreducible_map_of_algClosure_eq_bot` (which
supplies that irreducibility from relative algebraic closedness), this discharges the finite level
of geometric integrality — over any base `F` in which the primitive element is `F`-algebraic. -/

/-- **Base change of `AdjoinRoot`.**  `K ⊗[F] (F[X]/(g)) ≅ K[X]/(g.map)` as `K`-algebras.  A
standard algebra fact: the tensor product base-changes the presentation of the simple extension. -/
noncomputable def baseChangeAdjoinRoot
    {F K : Type*} [Field F] [Field K] [Algebra F K] (g : F[X]) :
    K ⊗[F] AdjoinRoot g ≃ₐ[K] AdjoinRoot (g.map (algebraMap F K)) := by
  -- `gToC : AdjoinRoot g →ₐ[F] AdjoinRoot (g.map)` sending `root ↦ root`.
  have hvanish : eval₂ (algebraMap F (AdjoinRoot (g.map (algebraMap F K))))
      (AdjoinRoot.root (g.map (algebraMap F K))) g = 0 := by
    have h1 : (algebraMap F (AdjoinRoot (g.map (algebraMap F K))))
        = (algebraMap K (AdjoinRoot (g.map (algebraMap F K)))).comp (algebraMap F K) := by
      rw [← IsScalarTower.algebraMap_eq]
    rw [h1, ← Polynomial.eval₂_map]
    exact AdjoinRoot.eval₂_root _
  let gToC : AdjoinRoot g →ₐ[F] AdjoinRoot (g.map (algebraMap F K)) :=
    AdjoinRoot.liftAlgHom g (Algebra.ofId F (AdjoinRoot (g.map (algebraMap F K))))
      (AdjoinRoot.root (g.map (algebraMap F K))) hvanish
  let fwd : K ⊗[F] AdjoinRoot g →ₐ[K] AdjoinRoot (g.map (algebraMap F K)) :=
    Algebra.TensorProduct.lift (Algebra.ofId K (AdjoinRoot (g.map (algebraMap F K)))) gToC
      (fun _ _ => Commute.all _ _)
  -- inverse
  have hvanish2 : aeval ((1 : K) ⊗ₜ[F] AdjoinRoot.root g)
      (g.map (algebraMap F K)) = 0 := by
    rw [Polynomial.aeval_map_algebraMap (A := K),
        show ((1 : K) ⊗ₜ[F] AdjoinRoot.root g)
          = Algebra.TensorProduct.includeRight (AdjoinRoot.root g) from rfl,
        Polynomial.aeval_algHom_apply, AdjoinRoot.aeval_eq]
    simp [AdjoinRoot.mk_self]
  let inv : AdjoinRoot (g.map (algebraMap F K)) →ₐ[K] K ⊗[F] AdjoinRoot g :=
    AdjoinRoot.liftAlgHom (R := K) (S := K) (T := K ⊗[F] AdjoinRoot g)
      (g.map (algebraMap F K))
      (Algebra.ofId K (K ⊗[F] AdjoinRoot g))
      ((1 : K) ⊗ₜ[F] AdjoinRoot.root g) hvanish2
  refine AlgEquiv.ofAlgHom fwd inv ?_ ?_
  · -- `fwd ∘ inv = id` on `AdjoinRoot (g.map)`
    apply AdjoinRoot.algHom_ext
    show fwd (inv (AdjoinRoot.root _)) = AdjoinRoot.root _
    rw [show inv (AdjoinRoot.root (g.map (algebraMap F K)))
          = (1 : K) ⊗ₜ[F] AdjoinRoot.root g from AdjoinRoot.liftAlgHom_root _ _ _ _]
    show fwd ((1 : K) ⊗ₜ[F] AdjoinRoot.root g) = _
    simp only [fwd, Algebra.TensorProduct.lift_tmul, map_one, one_mul, gToC,
      AdjoinRoot.liftAlgHom_root]
  · -- `inv ∘ fwd = id` on `K ⊗ AdjoinRoot g`
    apply Algebra.TensorProduct.ext
    · exact Subsingleton.elim _ _
    · apply AdjoinRoot.algHom_ext
      show inv (fwd ((1 : K) ⊗ₜ[F] AdjoinRoot.root g)) = (1 : K) ⊗ₜ[F] AdjoinRoot.root g
      rw [show fwd ((1 : K) ⊗ₜ[F] AdjoinRoot.root g)
            = AdjoinRoot.root (g.map (algebraMap F K)) by
          simp only [fwd, Algebra.TensorProduct.lift_tmul, map_one, one_mul, gToC,
            AdjoinRoot.liftAlgHom_root]]
      exact AdjoinRoot.liftAlgHom_root (g.map (algebraMap F K)) _ _ _

/-- **Finite building block (domain form).**  If `E / F` is finite with primitive element `γ` whose
`F`-minimal polynomial stays irreducible over `K`, then `K ⊗[F] E` is a domain. -/
theorem isDomain_tensor_of_primitive_irreducible
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (E : Type*) [Field E] [Algebra F E] [FiniteDimensional F E]
    (γ : E) (hγtop : IntermediateField.adjoin F {γ} = ⊤)
    (hirr : Irreducible ((minpoly F γ).map (algebraMap F K))) :
    IsDomain (K ⊗[F] E) := by
  have hγint : IsIntegral F γ := IsIntegral.of_finite F γ
  let eAdj := IntermediateField.adjoinRootEquivAdjoin F hγint
  let eTop := (IntermediateField.equivOfEq hγtop).trans IntermediateField.topEquiv
  let eE : AdjoinRoot (minpoly F γ) ≃ₐ[F] E := eAdj.trans eTop
  let eKtensor : K ⊗[F] AdjoinRoot (minpoly F γ) ≃ₐ[K] K ⊗[F] E :=
    Algebra.TensorProduct.congr AlgEquiv.refl eE
  haveI : Fact (Irreducible ((minpoly F γ).map (algebraMap F K))) := ⟨hirr⟩
  let eFull : K ⊗[F] E ≃ₐ[K] AdjoinRoot ((minpoly F γ).map (algebraMap F K)) :=
    eKtensor.symm.trans (baseChangeAdjoinRoot (minpoly F γ))
  haveI : IsDomain (AdjoinRoot ((minpoly F γ).map (algebraMap F K))) := inferInstance
  exact eFull.toMulEquiv.isDomain _

/-- **Finite building block (field form).**  Under the same hypotheses, `K ⊗[F] E` is a field. -/
theorem isField_tensor_of_primitive_irreducible
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (E : Type*) [Field E] [Algebra F E] [FiniteDimensional F E]
    (γ : E) (hγtop : IntermediateField.adjoin F {γ} = ⊤)
    (hirr : Irreducible ((minpoly F γ).map (algebraMap F K))) :
    IsField (K ⊗[F] E) := by
  haveI : IsDomain (K ⊗[F] E) :=
    isDomain_tensor_of_primitive_irreducible E γ hγtop hirr
  haveI algE : Algebra.IsAlgebraic F E := Algebra.IsAlgebraic.of_finite _ _
  exact Algebra.TensorProduct.isField_of_isAlgebraic F K E (Or.inr algE)

/-! ## The geometric base field `ℚ̄(T)` and the regularity core

We now specialise `K'` to the geometric base field `ℚ̄(T) = FractionRing ℚ̄[T]`, build the algebra
structure `RatFunc ℚ → ℚ̄(T)` (base change on `ℚ[T]` then localise), and reduce the core `IsField`
statement to a single **linear disjointness** fact, which is the geometric-integrality content of
regularity. -/

section GeomBase

open scoped Polynomial

attribute [local instance] Polynomial.algebra

/-- The base-change-then-localise ring hom `ℚ[T] → ℚ̄(T) = FractionRing ℚ̄[T]`: map coefficients
along `ℚ → ℚ̄`, then include `ℚ̄[T]` into its fraction field. -/
noncomputable def toClosureFrac : ℚ[X] →+* FractionRing (Polynomial (AlgebraicClosure ℚ)) :=
  (algebraMap (Polynomial (AlgebraicClosure ℚ))
      (FractionRing (Polynomial (AlgebraicClosure ℚ)))).comp
    (mapRingHom (algebraMap ℚ (AlgebraicClosure ℚ)))

theorem toClosureFrac_injective : Function.Injective toClosureFrac :=
  (IsFractionRing.injective (Polynomial (AlgebraicClosure ℚ))
      (FractionRing (Polynomial (AlgebraicClosure ℚ)))).comp
    (Polynomial.map_injective _ (FaithfulSMul.algebraMap_injective ℚ (AlgebraicClosure ℚ)))

/-- The geometric base field `ℚ̄(T)` is a `ℚ(T)`-algebra, via the fraction-field lift of
`toClosureFrac`. -/
noncomputable instance instAlgRatFuncGeom :
    Algebra (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) :=
  (IsFractionRing.lift (A := ℚ[X]) toClosureFrac_injective).toAlgebra

/-- The structure map `ℚ(T) → ℚ̄(T)` restricted to `ℚ[T]` is exactly `toClosureFrac`. -/
theorem algebraMap_ratFunc_geom_comp (x : ℚ[X]) :
    algebraMap (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))
        (algebraMap ℚ[X] (RatFunc ℚ) x) = toClosureFrac x := by
  show IsFractionRing.lift (A := ℚ[X]) toClosureFrac_injective _ = _
  rw [IsFractionRing.lift_algebraMap]

/-- `ℚ[T] → ℚ(T) → ℚ̄(T)` is a scalar tower. -/
instance instTowerRatFuncGeom :
    IsScalarTower ℚ[X] (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) := by
  apply IsScalarTower.of_algebraMap_eq
  intro x
  rw [algebraMap_ratFunc_geom_comp,
    IsScalarTower.algebraMap_apply ℚ[X] (Polynomial (AlgebraicClosure ℚ))
      (FractionRing (Polynomial (AlgebraicClosure ℚ)))]
  rfl

/-- `ℚ̄(T)` is algebraic over `ℚ(T)`: it is the fraction field of `ℚ̄[T]`, which is integral over
`ℚ[T]` (coefficients algebraic over `ℚ`). -/
theorem isAlgebraic_ratFunc_geom :
    Algebra.IsAlgebraic (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) :=
  isAlgebraic_of_isFractionRing (R := ℚ[X]) (S := Polynomial (AlgebraicClosure ℚ))
    (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))

/-- `ℚ` is relatively algebraically closed in `ℚ(T)`: any element of `RatFunc ℚ` integral over
`ℚ` is a constant.  Proof: integral over `ℚ ⟹` integral over `ℚ[T]`; `ℚ[T]` is integrally closed
in its fraction field `ℚ(T)`, so the element is (the image of) some `p ∈ ℚ[T]`; `p` integral over
`ℚ` forces `natDegree p = 0` (`(minpoly ℚ p).comp p = 0` with `natDegree_comp`), so `p` is a
constant. -/
theorem regular_ratFunc : algebraicClosure ℚ (RatFunc ℚ) = ⊥ := by
  refine bot_unique fun x hx => ?_
  rw [mem_algebraicClosure_iff'] at hx
  have hxT : IsIntegral (Polynomial ℚ) x := hx.tower_top
  obtain ⟨p, hp⟩ := (IsIntegrallyClosed.isIntegral_iff (R := Polynomial ℚ)
    (x := x)).mp hxT
  let φ : Polynomial ℚ →ₐ[ℚ] RatFunc ℚ := IsScalarTower.toAlgHom ℚ (Polynomial ℚ) (RatFunc ℚ)
  have hφinj : Function.Injective φ := by
    show Function.Injective (algebraMap (Polynomial ℚ) (RatFunc ℚ))
    exact IsFractionRing.injective _ _
  have hpint : IsIntegral ℚ p := by
    have hh : IsIntegral ℚ (φ p) := (show φ p = x from hp) ▸ hx
    exact (isIntegral_algHom_iff φ hφinj).mp hh
  have key : Polynomial.aeval p (minpoly ℚ p) = (minpoly ℚ p).comp p := by
    rw [Polynomial.aeval_def]; rfl
  have hcomp : (minpoly ℚ p).comp p = 0 := key.symm.trans (minpoly.aeval ℚ p)
  have hdeg : (minpoly ℚ p).natDegree * p.natDegree = 0 := by
    have h := Polynomial.natDegree_comp (p := minpoly ℚ p) (q := p)
    rw [hcomp, Polynomial.natDegree_zero] at h
    exact h.symm
  have hqpos : 0 < (minpoly ℚ p).natDegree := minpoly.natDegree_pos hpint
  have hp0 : p.natDegree = 0 := by
    rcases Nat.mul_eq_zero.mp hdeg with h | h
    · omega
    · exact h
  obtain ⟨c, hc⟩ := Polynomial.natDegree_eq_zero.mp hp0
  rw [IntermediateField.mem_bot]
  refine ⟨c, ?_⟩
  rw [← hp, ← hc, Polynomial.C_eq_algebraMap, ← IsScalarTower.algebraMap_apply]

/-- The image of the variable `X` under `ℚ̄[T] → ℚ̄(T)` lies in `ℚ(T)` (hence in any adjoin over
`ℚ(T)`), since it is the image of the variable of `ℚ(T)`. -/
theorem geomVar_mem (T : Set (FractionRing (Polynomial (AlgebraicClosure ℚ)))) :
    algebraMap (Polynomial (AlgebraicClosure ℚ))
        (FractionRing (Polynomial (AlgebraicClosure ℚ))) X ∈
      IntermediateField.adjoin (RatFunc ℚ) T := by
  have hτ : algebraMap (Polynomial (AlgebraicClosure ℚ))
        (FractionRing (Polynomial (AlgebraicClosure ℚ))) X
      = algebraMap (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))
          (algebraMap ℚ[X] (RatFunc ℚ) X) := by
    rw [algebraMap_ratFunc_geom_comp]
    show _ = toClosureFrac X
    rw [toClosureFrac, RingHom.comp_apply]
    simp [Polynomial.coe_mapRingHom]
  rw [hτ]
  exact IntermediateField.algebraMap_mem _ _

/-- The image in `ℚ̄(T)` of any `q ∈ ℚ̄[T]` lies in `ℚ(T)` adjoined with (the images of) a finite
set of constants: namely the coefficients of `q`. -/
theorem geomPoly_mem (q : Polynomial (AlgebraicClosure ℚ)) :
    ∃ S : Finset (AlgebraicClosure ℚ),
      algebraMap (Polynomial (AlgebraicClosure ℚ))
          (FractionRing (Polynomial (AlgebraicClosure ℚ))) q ∈
        IntermediateField.adjoin (RatFunc ℚ)
          ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
            '' (↑S : Set (AlgebraicClosure ℚ))) := by
  classical
  induction q using Polynomial.induction_on' with
  | add p r hp hr =>
    obtain ⟨S1, hS1⟩ := hp
    obtain ⟨S2, hS2⟩ := hr
    refine ⟨S1 ∪ S2, ?_⟩
    rw [map_add]
    have hmono : ∀ (S' : Finset (AlgebraicClosure ℚ)), S' ⊆ S1 ∪ S2 →
        IntermediateField.adjoin (RatFunc ℚ)
            ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
              '' (↑S' : Set (AlgebraicClosure ℚ)))
          ≤ IntermediateField.adjoin (RatFunc ℚ)
            ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
              '' (↑(S1 ∪ S2) : Set (AlgebraicClosure ℚ))) :=
      fun S' hsub => IntermediateField.adjoin.mono _ _ _
        (Set.image_mono (by exact_mod_cast hsub))
    exact add_mem (hmono S1 Finset.subset_union_left hS1)
      (hmono S2 Finset.subset_union_right hS2)
  | monomial n a =>
    refine ⟨{a}, ?_⟩
    rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, map_pow]
    have hCa : algebraMap (Polynomial (AlgebraicClosure ℚ))
          (FractionRing (Polynomial (AlgebraicClosure ℚ))) (C a)
        = algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) a := by
      rw [Polynomial.C_eq_algebraMap, ← IsScalarTower.algebraMap_apply]
    rw [hCa]
    apply mul_mem
    · apply IntermediateField.subset_adjoin
      exact ⟨a, by simp, rfl⟩
    · exact pow_mem (geomVar_mem _) n

/-- Every element of `ℚ̄(T)` lies in `ℚ(T)` adjoined with a finite set of constants. -/
theorem geomElt_mem (k : FractionRing (Polynomial (AlgebraicClosure ℚ))) :
    ∃ S : Finset (AlgebraicClosure ℚ),
      k ∈ IntermediateField.adjoin (RatFunc ℚ)
        ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
          '' (↑S : Set (AlgebraicClosure ℚ))) := by
  classical
  obtain ⟨num, den, hden, hk⟩ :=
    IsFractionRing.div_surjective (A := Polynomial (AlgebraicClosure ℚ)) k
  obtain ⟨S1, hS1⟩ := geomPoly_mem num
  obtain ⟨S2, hS2⟩ := geomPoly_mem den
  refine ⟨S1 ∪ S2, ?_⟩
  have hmono : ∀ (S' : Finset (AlgebraicClosure ℚ)), S' ⊆ S1 ∪ S2 →
      IntermediateField.adjoin (RatFunc ℚ)
          ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
            '' (↑S' : Set (AlgebraicClosure ℚ)))
        ≤ IntermediateField.adjoin (RatFunc ℚ)
          ((algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))))
            '' (↑(S1 ∪ S2) : Set (AlgebraicClosure ℚ))) :=
    fun S' hsub => IntermediateField.adjoin.mono _ _ _
      (Set.image_mono (by exact_mod_cast hsub))
  rw [← hk]
  exact div_mem (hmono S1 Finset.subset_union_left hS1)
    (hmono S2 Finset.subset_union_right hS2)

/-- Primitive element: a finite set of elements of `ℚ̄` is contained in `ℚ⟮γ⟯` for a single
`γ ∈ ℚ̄` (finite separable extension of `ℚ`). -/
theorem geomPrim (S : Finset (AlgebraicClosure ℚ)) :
    ∃ γ : AlgebraicClosure ℚ, ∀ s ∈ S,
      s ∈ IntermediateField.adjoin ℚ ({γ} : Set (AlgebraicClosure ℚ)) := by
  classical
  set M := IntermediateField.adjoin ℚ (↑S : Set (AlgebraicClosure ℚ)) with hM
  haveI : FiniteDimensional ℚ M := IntermediateField.finiteDimensional_adjoin
    (fun s _ => (Algebra.IsAlgebraic.isAlgebraic s).isIntegral)
  obtain ⟨γ', hγ'⟩ := Field.exists_primitive_element ℚ M
  refine ⟨(γ' : AlgebraicClosure ℚ), fun s hs => ?_⟩
  have hsM : s ∈ M := IntermediateField.subset_adjoin ℚ _ (by exact_mod_cast hs)
  have hmap : M =
      IntermediateField.adjoin ℚ ({(γ' : AlgebraicClosure ℚ)} : Set (AlgebraicClosure ℚ)) := by
    have hcong := congrArg (fun N => IntermediateField.map (M.val) N) hγ'
    simp only at hcong
    rw [IntermediateField.adjoin_map, Set.image_singleton] at hcong
    have h2 : IntermediateField.map M.val ⊤ = M := by
      rw [← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val]
    rw [h2] at hcong
    exact hcong.symm
  rw [hmap] at hsM
  exact hsM

/-- **Constant extraction.**  Every finite family of elements of `ℚ̄(T)` sits inside a single
constant-adjoin `ℚ(T)⟮γ⟯`, `γ ∈ ℚ̄`. -/
theorem extract (t : Finset (FractionRing (Polynomial (AlgebraicClosure ℚ)))) :
    ∃ γ : AlgebraicClosure ℚ, ∀ k ∈ t, k ∈ IntermediateField.adjoin (RatFunc ℚ)
      {algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ} := by
  classical
  choose Sf hSf using geomElt_mem
  let Stot : Finset (AlgebraicClosure ℚ) := t.biUnion Sf
  obtain ⟨γ, hγ⟩ := geomPrim Stot
  refine ⟨γ, fun k hk => ?_⟩
  have hkmem := hSf k
  set ι := algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))
    with hι
  let ιₐ : AlgebraicClosure ℚ →ₐ[ℚ] FractionRing (Polynomial (AlgebraicClosure ℚ)) :=
    IsScalarTower.toAlgHom ℚ (AlgebraicClosure ℚ)
      (FractionRing (Polynomial (AlgebraicClosure ℚ)))
  have hιₐ : ⇑ιₐ = ι := IsScalarTower.coe_toAlgHom' ℚ (AlgebraicClosure ℚ)
    (FractionRing (Polynomial (AlgebraicClosure ℚ)))
  have hcoeff_mem : ∀ s ∈ Stot, ι s ∈ IntermediateField.adjoin (RatFunc ℚ) {ι γ} := by
    intro s hs
    have hsγ : s ∈ IntermediateField.adjoin ℚ ({γ} : Set (AlgebraicClosure ℚ)) := hγ s hs
    have hmapped : ι s ∈ (IntermediateField.adjoin ℚ ({γ} : Set (AlgebraicClosure ℚ))).map ιₐ := by
      have himg : ιₐ s ∈ ((IntermediateField.adjoin ℚ ({γ} : Set (AlgebraicClosure ℚ))).map ιₐ :
          Set (FractionRing (Polynomial (AlgebraicClosure ℚ)))) := by
        rw [IntermediateField.coe_map]
        exact Set.mem_image_of_mem ιₐ hsγ
      rw [hιₐ] at himg
      exact himg
    rw [IntermediateField.adjoin_map, Set.image_singleton, hιₐ] at hmapped
    have hle : IntermediateField.adjoin ℚ ({ι γ} :
          Set (FractionRing (Polynomial (AlgebraicClosure ℚ))))
        ≤ (IntermediateField.adjoin (RatFunc ℚ) ({ι γ} :
            Set (FractionRing (Polynomial (AlgebraicClosure ℚ))))).restrictScalars ℚ := by
      rw [IntermediateField.adjoin_le_iff]
      intro y hy
      simp only [Set.mem_singleton_iff] at hy
      subst hy
      exact IntermediateField.subset_adjoin (RatFunc ℚ) {ι γ} (Set.mem_singleton _)
    exact hle hmapped
  have hsub : IntermediateField.adjoin (RatFunc ℚ)
        (ι '' (↑Stot : Set (AlgebraicClosure ℚ)))
      ≤ IntermediateField.adjoin (RatFunc ℚ) {ι γ} := by
    rw [IntermediateField.adjoin_le_iff]
    rintro _ ⟨s, hsStot, rfl⟩
    exact hcoeff_mem s hsStot
  have hsubk : IntermediateField.adjoin (RatFunc ℚ)
        (ι '' (↑(Sf k) : Set (AlgebraicClosure ℚ)))
      ≤ IntermediateField.adjoin (RatFunc ℚ) (ι '' (↑Stot : Set (AlgebraicClosure ℚ))) :=
    IntermediateField.adjoin.mono _ _ _
      (Set.image_mono (by
        intro x hx
        exact Finset.mem_biUnion.mpr ⟨k, hk, hx⟩))
  exact hsub (hsubk hkmem)

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 400000 in
/-- **The regularity core.**  For a finite extension `L / ℚ(T)` in which `ℚ` is relatively
algebraically closed (`algebraicClosure ℚ L = ⊥`, "regular"), the base change of `L` to the
geometric base field `ℚ̄(T) = FractionRing ℚ̄[T]` is a **field**.

The reduction: both `ℚ̄(T)` and `L` are algebraic over `ℚ(T)`, so they embed into an algebraic
closure `Ω = AlgebraicClosure ℚ(T)`; if their images are **linearly disjoint** over `ℚ(T)` then
`ℚ̄(T) ⊗ L` injects into the domain `Ω` (`Subalgebra.LinearDisjoint.isDomain_of_injective`), hence is
a domain, hence — being algebraic — a field (`Algebra.TensorProduct.isField_of_isAlgebraic`).

The linear disjointness is the geometric-integrality content of regularity.  It is proved by the
**colimit** route: `Subalgebra.LinearDisjoint.of_linearDisjoint_finite_left` reduces to every finite
subalgebra `A'` of the `ℚ̄(T)`-image; via `extract`, `A'` sits inside a single **constant**-adjoin
`C = ℚ(T)⟮c⟯` (`c = fa γ`, `γ ∈ ℚ̄`); the minimal polynomial of `c` over `ℚ(T)` equals
`(minpoly ℚ γ).map`, irreducible over `L` by the crux + `regular_ratFunc`, so the finite building
block gives `IsField (C ⊗ L)`, hence `C.LinearDisjoint fb.range`, transferred back to `A'`. -/
theorem isField_baseChange_of_regular
    {L : Type*} [Field L] [Algebra (RatFunc ℚ) L] [FiniteDimensional (RatFunc ℚ) L]
    [Algebra ℚ L] [IsScalarTower ℚ (RatFunc ℚ) L]
    (hreg : algebraicClosure ℚ L = ⊥) :
    IsField (FractionRing (Polynomial (AlgebraicClosure ℚ)) ⊗[RatFunc ℚ] L) := by
  classical
  haveI algL : Algebra.IsAlgebraic (RatFunc ℚ) L := Algebra.IsAlgebraic.of_finite _ _
  haveI algK : Algebra.IsAlgebraic (RatFunc ℚ)
      (FractionRing (Polynomial (AlgebraicClosure ℚ))) := isAlgebraic_ratFunc_geom
  let S := AlgebraicClosure (RatFunc ℚ)
  let fa : FractionRing (Polynomial (AlgebraicClosure ℚ)) →ₐ[RatFunc ℚ] S := IsAlgClosed.lift
  let fb : L →ₐ[RatFunc ℚ] S := IsAlgClosed.lift
  have hfa : Function.Injective fa := fa.toRingHom.injective
  have hfb : Function.Injective fb := fb.toRingHom.injective
  have hFreg : algebraicClosure ℚ (RatFunc ℚ) = ⊥ := regular_ratFunc
  haveI hSint : Algebra.IsIntegral (RatFunc ℚ) S := Algebra.IsAlgebraic.isIntegral
  haveI : Algebra.IsIntegral (RatFunc ℚ) ↥fa.range := ⟨fun y =>
    (isIntegral_algHom_iff fa.range.val Subtype.val_injective).mp
      (Algebra.IsIntegral.isIntegral (y : S))⟩
  have hLD : fa.range.LinearDisjoint fb.range := by
    refine Subalgebra.LinearDisjoint.of_linearDisjoint_finite_left fa.range fb.range ?_
    intro A' hA' hFin
    haveI := hFin
    obtain ⟨g, hgspan⟩ := Module.finite_def.mp hFin
    have hmemrange : ∀ a : ↥A', (a : S) ∈ fa.range := fun a => hA' a.2
    choose φ hφ using fun a : ↥A' => (fa.mem_range).mp (hmemrange a)
    obtain ⟨γ, hγ⟩ := extract (g.image φ)
    set c : S := fa (algebraMap (AlgebraicClosure ℚ)
      (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ) with hcdef
    set C : IntermediateField (RatFunc ℚ) S := IntermediateField.adjoin (RatFunc ℚ) {c} with hCdef
    have hgen : ∀ i ∈ g, (fa (φ i)) ∈ C := by
      intro i hi
      have hmem : φ i ∈ IntermediateField.adjoin (RatFunc ℚ)
          {algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ} :=
        hγ (φ i) (Finset.mem_image_of_mem φ hi)
      have h2 : fa (φ i) ∈ (IntermediateField.adjoin (RatFunc ℚ)
          {algebraMap (AlgebraicClosure ℚ)
            (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ}).map fa := by
        have himg : fa (φ i) ∈ (fa '' (IntermediateField.adjoin (RatFunc ℚ)
            {algebraMap (AlgebraicClosure ℚ)
              (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ} : Set _)) :=
          Set.mem_image_of_mem fa hmem
        rwa [← IntermediateField.coe_map] at himg
      rw [IntermediateField.adjoin_map, Set.image_singleton] at h2
      exact h2
    have hAC : A' ≤ C.toSubalgebra := by
      intro x hx
      rw [IntermediateField.mem_toSubalgebra]
      have h1 : (⟨x, hx⟩ : ↥A') ∈ Submodule.span (RatFunc ℚ) (g : Set ↥A') := by
        rw [hgspan]; exact Submodule.mem_top
      have h2 : x ∈ (Submodule.span (RatFunc ℚ) (g : Set ↥A')).map A'.val.toLinearMap :=
        Submodule.mem_map_of_mem h1
      rw [Submodule.map_span] at h2
      have hsub : (A'.val.toLinearMap '' (g : Set ↥A')) ⊆ (C.toSubmodule : Set S) := by
        rintro _ ⟨i, hi, rfl⟩
        show (i : S) ∈ C
        rw [← hφ i]
        exact hgen i hi
      exact (Submodule.span_le.mpr hsub) h2
    have hγint : IsIntegral ℚ γ := Algebra.IsIntegral.isIntegral γ
    have hcF : IsIntegral (RatFunc ℚ) c := Algebra.IsIntegral.isIntegral c
    haveI hCfin : FiniteDimensional (RatFunc ℚ) ↥C :=
      IntermediateField.adjoin.finiteDimensional hcF
    have hminF : minpoly (RatFunc ℚ) c
        = (minpoly ℚ γ).map (algebraMap ℚ (RatFunc ℚ)) := by
      have hcomp1 : (algebraMap (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))).comp
          (algebraMap ℚ (RatFunc ℚ))
          = algebraMap ℚ (FractionRing (Polynomial (AlgebraicClosure ℚ))) :=
        Subsingleton.elim _ _
      rw [hcdef, minpoly.algHom_eq fa hfa]
      set cK : FractionRing (Polynomial (AlgebraicClosure ℚ)) :=
        algebraMap (AlgebraicClosure ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ))) γ
        with hcKdef
      have hqmonic : ((minpoly ℚ γ).map (algebraMap ℚ (RatFunc ℚ))).Monic :=
        (minpoly.monic hγint).map _
      have hqirr : Irreducible ((minpoly ℚ γ).map (algebraMap ℚ (RatFunc ℚ))) :=
        irreducible_map_of_algClosure_eq_bot hFreg (minpoly.monic hγint) (minpoly.irreducible hγint)
      have hqeval : (Polynomial.aeval cK)
          ((minpoly ℚ γ).map (algebraMap ℚ (RatFunc ℚ))) = 0 := by
        rw [Polynomial.aeval_def, Polynomial.eval₂_map, hcomp1, ← Polynomial.aeval_def, hcKdef,
          Polynomial.aeval_algebraMap_apply, minpoly.aeval, map_zero]
      exact (minpoly.eq_of_irreducible_of_monic hqirr hqeval hqmonic).symm
    let γ' := IntermediateField.AdjoinSimple.gen (RatFunc ℚ) c
    have hγ'top : IntermediateField.adjoin (RatFunc ℚ) {γ'} = ⊤ := by
      apply IntermediateField.adjoin_eq_top_of_algebra
      exact (IntermediateField.adjoin.powerBasis hcF).adjoin_gen_eq_top
    have hirr : Irreducible ((minpoly (RatFunc ℚ) γ').map (algebraMap (RatFunc ℚ) L)) := by
      rw [IntermediateField.minpoly_gen, hminF, Polynomial.map_map,
        ← IsScalarTower.algebraMap_eq ℚ (RatFunc ℚ) L]
      exact irreducible_map_of_algClosure_eq_bot hreg (minpoly.monic hγint)
        (minpoly.irreducible hγint)
    have hfieldLC : IsField (L ⊗[RatFunc ℚ] ↥C) :=
      isField_tensor_of_primitive_irreducible (K := L) (↥C) γ' hγ'top hirr
    have hfieldCL : IsField (↥C ⊗[RatFunc ℚ] L) :=
      (Algebra.TensorProduct.comm (RatFunc ℚ) (↥C) L).toMulEquiv.isField hfieldLC
    have hLDC : C.toSubalgebra.LinearDisjoint fb.range := by
      have h := Subalgebra.LinearDisjoint.of_isField' hfieldCL C.val fb C.val.injective hfb
      rwa [IntermediateField.range_val] at h
    exact hLDC.of_le_left_of_flat hAC
  haveI : IsDomain (FractionRing (Polynomial (AlgebraicClosure ℚ)) ⊗[RatFunc ℚ] L) :=
    Subalgebra.LinearDisjoint.isDomain_of_injective hfa hfb hLD
  exact Algebra.TensorProduct.isField_of_isAlgebraic (RatFunc ℚ)
    (FractionRing (Polynomial (AlgebraicClosure ℚ))) L (Or.inr algL)

/-- **Absolute irreducibility from regularity** (the form consumed by the model translation).
If `L / ℚ(T)` is a finite extension, regular (`algebraicClosure ℚ L = ⊥`), generated by `β` whose
`ℚ(T)`-minimal polynomial is the base change of `F ∈ ℚ[T][X]`, then `F` stays irreducible after base
change to the geometric field `ℚ̄(T)` (along `toClosureFrac`). -/
theorem irreducible_map_toClosureFrac_of_regular
    {L : Type*} [Field L] [Algebra (RatFunc ℚ) L] [FiniteDimensional (RatFunc ℚ) L]
    [Algebra ℚ L] [IsScalarTower ℚ (RatFunc ℚ) L]
    (hreg : algebraicClosure ℚ L = ⊥)
    (β : L) (hβtop : IntermediateField.adjoin (RatFunc ℚ) {β} = ⊤)
    (F : ℚ[X][X]) (hFmap : minpoly (RatFunc ℚ) β = F.map (algebraMap ℚ[X] (RatFunc ℚ))) :
    Irreducible (F.map toClosureFrac) := by
  have hfield : IsField (FractionRing (Polynomial (AlgebraicClosure ℚ)) ⊗[RatFunc ℚ] L) :=
    isField_baseChange_of_regular hreg
  have htrans := irreducible_map_minpoly_of_isField_baseChange
    (K := RatFunc ℚ) (K' := FractionRing (Polynomial (AlgebraicClosure ℚ))) β hβtop hfield
  rw [hFmap, Polynomial.map_map] at htrans
  have hcomp : (algebraMap (RatFunc ℚ) (FractionRing (Polynomial (AlgebraicClosure ℚ)))).comp
      (algebraMap ℚ[X] (RatFunc ℚ)) = toClosureFrac :=
    RingHom.ext algebraMap_ratFunc_geom_comp
  rwa [hcomp] at htrans

end GeomBase

end Rigidity.RET
