/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.AbelianGeneration
import InverseGalois.Rigidity.RET.TranslateInfinity

/-!
# Inertia generates the deck group of an arbitrary cover of the line

A cover of the line unramified over the affine line is trivial, and so is one branched over a
single point of the sphere (`RET/NoUnbranchedCover.lean`, `RET/TranslateInfinity.lean`).  Both
statements hold for an arbitrary deck group, and both bound from below the group generated by the
inertia elements of a cover: the quotient of the deck group by a normal subgroup containing a
family of inertia elements is the deck group of a subcover in which those elements have died, so a
family large enough to make that subcover unramified generates the deck group as a normal subgroup.

Two families are large enough.  All the inertia elements at points of the *affine* line make the
subcover unramified over the affine line, so they normally generate the deck group of any cover
whatsoever — no hypothesis at infinity is needed, the affine line being simply connected however
the cover behaves at infinity.  And for a cover unramified at infinity, the inertia elements at the
points *other than any single chosen point* `t₀` leave a subcover branched over at most `t₀`, hence
trivial: one puncture may always be discarded.  That is the algebraic shadow of the sphere
relation, which expresses the loop around one puncture through the loops around the others.

Over two branch points, discarding one puncture leaves a single inertia group, which is cyclic; so
the deck group of a cover branched over two points is the normal closure of a cyclic subgroup.

## Main results

* `Rigidity.RET.normalClosure_isInertiaAt_eq_top` — the inertia elements of an arbitrary cover
  generate its deck group as a normal subgroup.
* `Rigidity.RET.closure_isInertiaAt_eq_top` — they generate it as a subgroup.
* `Rigidity.RET.normalClosure_isInertiaAt_ne_eq_top` — for a cover unramified at infinity the
  inertia elements away from any one chosen point already suffice.
* `Rigidity.RET.normalClosure_geomInertia_eq_top_of_pair` — the deck group of a cover branched
  over two points is the normal closure of one inertia group above one of them.
* `Rigidity.RET.exists_isCyclic_normalClosure_eq_top_of_pair` — hence the normal closure of a
  cyclic subgroup.
-/

open Polynomial IntermediateField
open scoped Pointwise

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

attribute [local instance] LineCover.sub_isGalois

/-! ### Inertia normally generates the deck group -/

/-- **The inertia elements of an arbitrary cover of the line generate its deck group as a normal
subgroup.**  The quotient by their normal closure is the deck group of a cover of the line
unramified over the whole affine line, and the affine line is simply connected. -/
theorem normalClosure_isInertiaAt_eq_top (L : LineCover) :
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} = ⊤ := by
  set N : Subgroup L.deck := Subgroup.normalClosure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ}
    with hNdef
  set f : L.deck →* L.deck ⧸ N := QuotientGroup.mk' N with hfdef
  have hfs : Function.Surjective f := QuotientGroup.mk'_surjective N
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  have hres : ∀ t : k, t ∉ (∅ : Set k) → ∀ σ : L.deck, L.IsInertiaAt t σ → L.subHom E σ = 1 := by
    intro t _ σ hσ
    refine (MulEquiv.map_eq_one_iff (descentEquiv f hfs)).mp ?_
    rw [descentEquiv_apply f hfs σ]
    exact (QuotientGroup.eq_one_iff σ).mpr (Subgroup.subset_normalClosure ⟨t, hσ⟩)
  haveI := LineCover.subsingleton_deck_of_unramifiedOutside_empty (L.sub E)
    (isUnramifiedOutside_sub E hres)
  haveI : Subsingleton (L.deck ⧸ N) := (descentEquiv f hfs).symm.injective.subsingleton
  exact eq_top_iff.mpr fun y _ => (QuotientGroup.eq_one_iff y).mp (Subsingleton.elim _ _)

/-- **One puncture may always be discarded.**  For a cover of the line unramified at infinity the
inertia elements at the points other than any single chosen point `t₀` already generate the deck
group as a normal subgroup: killing them leaves a cover branched over at most `t₀`, and the sphere
with one puncture is simply connected. -/
theorem normalClosure_isInertiaAt_ne_eq_top (L : LineCover) (hinf : L.IsUnramifiedAtInfinity)
    (t₀ : k) :
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, t ≠ t₀ ∧ L.IsInertiaAt t σ} = ⊤ := by
  set N : Subgroup L.deck :=
    Subgroup.normalClosure {σ : L.deck | ∃ t : k, t ≠ t₀ ∧ L.IsInertiaAt t σ} with hNdef
  set f : L.deck →* L.deck ⧸ N := QuotientGroup.mk' N with hfdef
  have hfs : Function.Surjective f := QuotientGroup.mk'_surjective N
  set E : IntermediateField (RatFunc k) L.M := fixedField f.ker with hE
  have hres : ∀ t : k, t ∉ ({t₀} : Set k) → ∀ σ : L.deck, L.IsInertiaAt t σ →
      L.subHom E σ = 1 := by
    intro t ht σ hσ
    refine (MulEquiv.map_eq_one_iff (descentEquiv f hfs)).mp ?_
    rw [descentEquiv_apply f hfs σ]
    exact (QuotientGroup.eq_one_iff σ).mpr
      (Subgroup.subset_normalClosure ⟨t, fun h => ht (by rw [h]; rfl), hσ⟩)
  haveI := LineCover.subsingleton_deck_of_unramifiedOutside_singleton (L.sub E) t₀
    (isUnramifiedOutside_sub E hres) (hinf.sub E)
  haveI : Subsingleton (L.deck ⧸ N) := (descentEquiv f hfs).symm.injective.subsingleton
  exact eq_top_iff.mpr fun y _ => (QuotientGroup.eq_one_iff y).mp (Subsingleton.elim _ _)

/-! ### Inertia generates the deck group as a subgroup -/

/-- The subgroup generated by a conjugation-stable set is normal. -/
theorem normal_closure_of_conj_mem {G : Type*} [Group G] {s : Set G}
    (hs : ∀ g x : G, x ∈ s → g * x * g⁻¹ ∈ s) : (Subgroup.closure s).Normal := by
  refine ⟨fun n hn g => ?_⟩
  induction hn using Subgroup.closure_induction with
  | mem x hx => exact Subgroup.subset_closure (hs g x hx)
  | one => simp
  | mul x y _ _ ihx ihy =>
      have hxy : g * (x * y) * g⁻¹ = g * x * g⁻¹ * (g * y * g⁻¹) := by group
      rw [hxy]
      exact mul_mem ihx ihy
  | inv x _ ihx =>
      have hx : g * x⁻¹ * g⁻¹ = (g * x * g⁻¹)⁻¹ := by group
      rw [hx]
      exact inv_mem ihx

/-- **Inertia elements are stable under conjugation**: conjugation moves the inertia group of a
place to the inertia group of the translated place, which lies over the same point of the line. -/
theorem LineCover.IsInertiaAt.conj {L : LineCover} {t : k} {σ : L.deck}
    (h : L.IsInertiaAt t σ) (g : L.deck) : L.IsInertiaAt t (g * σ * g⁻¹) := by
  obtain ⟨Q, hQmax, hQover, hσ⟩ := h
  haveI := hQmax
  haveI : Q.IsPrime := hQmax.isPrime
  haveI := hQover
  haveI hpr : (g • Q).IsPrime := inferInstance
  refine ⟨g • Q, hpr.isMaximal (Q_ne_bot L.M t (g • Q)), inferInstance, ?_⟩
  rw [geomInertia_smul]
  exact ⟨σ, hσ, rfl⟩

/-- **The inertia elements of an arbitrary cover of the line generate its deck group.**  They are
stable under conjugation, so the subgroup they generate is already normal. -/
theorem closure_isInertiaAt_eq_top (L : LineCover) :
    Subgroup.closure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ} = ⊤ := by
  haveI : (Subgroup.closure {σ : L.deck | ∃ t : k, L.IsInertiaAt t σ}).Normal :=
    normal_closure_of_conj_mem fun g x hx => by
      obtain ⟨t, hx⟩ := hx
      exact ⟨t, hx.conj g⟩
  refine eq_top_iff.mpr ?_
  rw [← normalClosure_isInertiaAt_eq_top L]
  exact Subgroup.normalClosure_le_normal Subgroup.subset_closure

/-! ### Covers branched over two points -/

/-- **The inertia elements at a point are the conjugates of a single inertia group.**  The deck
group permutes the places above a point transitively, so the normal closure of the inertia group
at one chosen place above `t₀` is the normal closure of all the inertia at `t₀`. -/
theorem normalClosure_geomInertia_eq_normalClosure (L : LineCover) (t₀ : k)
    (Q : Ideal (Bring L.M)) [hQmax : Q.IsMaximal] [Q.LiesOver (placeP t₀)] :
    Subgroup.normalClosure (geomInertia L.M Q : Set L.deck)
      = Subgroup.normalClosure {σ : L.deck | L.IsInertiaAt t₀ σ} := by
  haveI : Q.IsPrime := hQmax.isPrime
  refine le_antisymm (Subgroup.normalClosure_le_normal ?_) (Subgroup.normalClosure_le_normal ?_)
  · intro σ hσ
    exact Subgroup.subset_normalClosure
      (show L.IsInertiaAt t₀ σ from ⟨Q, hQmax, inferInstance, hσ⟩)
  · rintro σ ⟨Q', hQ'max, hQ'over, hQ'in⟩
    haveI := hQ'max
    haveI : Q'.IsPrime := hQ'max.isPrime
    haveI := hQ'over
    obtain ⟨g, hg⟩ := exists_smul_eq_of_liesOver (Ω := L.M) t₀ Q Q'
    rw [hg, geomInertia_smul] at hQ'in
    obtain ⟨y, hy, rfl⟩ := hQ'in
    exact (Subgroup.normalClosure_normal (s := (geomInertia L.M Q : Set L.deck))).conj_mem
      y (Subgroup.subset_normalClosure hy) g

/-- **A cover of the line branched over two points is normally generated by the inertia at either
one of them.**  Discarding the other puncture leaves the inertia at `t₀` alone, and nothing else
can ramify. -/
theorem normalClosure_isInertiaAt_eq_top_of_pair (L : LineCover) (t₀ t₁ : k)
    (hS : L.IsUnramifiedOutside {t₀, t₁}) (hinf : L.IsUnramifiedAtInfinity) :
    Subgroup.normalClosure {σ : L.deck | L.IsInertiaAt t₀ σ} = ⊤ := by
  refine eq_top_iff.mpr ?_
  rw [← normalClosure_isInertiaAt_ne_eq_top L hinf t₁]
  refine Subgroup.normalClosure_le_normal ?_
  rintro σ ⟨t, htne, hσ⟩
  by_cases h : t = t₀
  · subst h
    exact Subgroup.subset_normalClosure hσ
  · rw [hS t (by simp [h, htne]) σ hσ]
    exact one_mem _

/-- **A cover of the line branched over two points is the normal closure of one inertia group.** -/
theorem normalClosure_geomInertia_eq_top_of_pair (L : LineCover) (t₀ t₁ : k)
    (hS : L.IsUnramifiedOutside {t₀, t₁}) (hinf : L.IsUnramifiedAtInfinity)
    (Q : Ideal (Bring L.M)) [Q.IsMaximal] [Q.LiesOver (placeP t₀)] :
    Subgroup.normalClosure (geomInertia L.M Q : Set L.deck) = ⊤ := by
  rw [normalClosure_geomInertia_eq_normalClosure L t₀ Q]
  exact normalClosure_isInertiaAt_eq_top_of_pair L t₀ t₁ hS hinf

/-- **The deck group of a cover of the line branched over two points is the normal closure of a
cyclic subgroup**: geometric inertia groups are cyclic, and one of them already normally generates.
This is how much of `π₁(𝔾ₘ)` being procyclic is visible without the correspondence — the cyclic
group is there, but nothing yet forces its normal closure to be itself. -/
theorem exists_isCyclic_normalClosure_eq_top_of_pair (L : LineCover) (t₀ t₁ : k)
    (hS : L.IsUnramifiedOutside {t₀, t₁}) (hinf : L.IsUnramifiedAtInfinity) :
    ∃ C : Subgroup L.deck, IsCyclic C ∧ Subgroup.normalClosure (C : Set L.deck) = ⊤ := by
  obtain ⟨Q, hQmax, hQover⟩ := L.exists_place t₀
  haveI := hQmax
  haveI := hQover
  exact ⟨geomInertia L.M Q, isCyclic_geomInertia (Ω := L.M) t₀ Q,
    normalClosure_geomInertia_eq_top_of_pair L t₀ t₁ hS hinf Q⟩

end Rigidity.RET
