/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.ChartInertia
import InverseGalois.Rigidity.RET.LineParam
import InverseGalois.Rigidity.RET.InertiaSub
import InverseGalois.Rigidity.RET.KummerInertia

/-!
# A cover carrying a root of the coordinate is cyclic

Let `M` be a cover of the line whose branch locus is contained in the origin and the point at
infinity, and suppose that `M` contains an `m`-th root `u` of the coordinate, where `m` is a
multiple of the exponent of the deck group.  Then the deck group is cyclic.

The root `u` is a coordinate on a second line inside `M`, and over that line `M` is a cover
branched nowhere at all: away from `u = 0` a point of the new line lies over the point `uᵐ ≠ 0` of
the old one, where the cover is unramified by hypothesis; and over `u = 0` the inertia group is
cyclic, of order dividing the exponent `m`, and already maps onto the deck group of the Kummer line
`uᵐ = T`, which has order exactly `m` — so it maps onto it *injectively*, and a symmetry fixing the
new line pointwise is trivial there, hence trivial.  A cover of the affine line branched nowhere is
trivial, so `M` is the Kummer line itself, whose deck group is cyclic.

## Main results

* `Rigidity.RET.geomInertia_eq_top_of_pow_eq_X` — a cover carrying an `m`-th root of the coordinate
  is totally ramified over the origin.
* `Rigidity.RET.LineCover.isCyclic_deck_of_kummer_param` — a cover unramified away from the origin
  and carrying an `m`-th root of the coordinate, `m` killing the deck group, is cyclic.
-/

open Polynomial IsDedekindDomain

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-! ## Total ramification over the origin -/

section Ramification

variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [Algebra (Polynomial k) Ω]
  [IsScalarTower (Polynomial k) (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]

/-- The place of the origin is generated by the coordinate. -/
theorem placeP_zero : placeP (0 : k) = Ideal.span {(X : Polynomial k)} := by
  rw [placeP]
  simp

/-- **A root of the coordinate forces total ramification over the origin**: the `m`-th power of a
place above the origin divides the place extended to the cover. -/
theorem pow_dvd_map_placeP_zero {n : ℕ} (w : Bring Ω)
    (hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) X)
    (Q : Ideal (Bring Ω)) [hQm : Q.IsMaximal] [Q.LiesOver (placeP (0 : k))] :
    Q ^ n ∣ Ideal.map (algebraMap (Polynomial k) (Bring Ω)) (placeP (0 : k)) := by
  haveI := hQm.isPrime
  have haQ : algebraMap (Polynomial k) (Bring Ω) X ∈ Q := by
    have hover : placeP (0 : k) = Q.comap (algebraMap (Polynomial k) (Bring Ω)) :=
      Ideal.LiesOver.over
    have hmem : (X : Polynomial k) ∈ placeP (0 : k) := by
      rw [placeP_zero]
      exact Ideal.mem_span_singleton_self _
    rw [hover] at hmem
    exact hmem
  have hwQ : w ∈ Q := (‹Q.IsPrime›).mem_of_pow_mem n (by rw [hw]; exact haQ)
  have h1 : Q ∣ Ideal.span {w} :=
    Ideal.dvd_iff_le.mpr (by rwa [Ideal.span_le, Set.singleton_subset_iff])
  have h2 : Q ^ n ∣ Ideal.span {w ^ n} := by
    rw [← Ideal.span_singleton_pow]
    exact pow_dvd_pow_of_dvd h1 n
  rw [hw] at h2
  rwa [placeP_zero, Ideal.map_span, Set.image_singleton]

/-- **A cover carrying an `m`-th root of the coordinate has full inertia over the origin**, when
its degree is `m`: the place above the origin is totally ramified. -/
theorem geomInertia_eq_top_of_pow_eq_X {n : ℕ} (hfr : Module.finrank (RatFunc k) Ω = n)
    (w : Bring Ω) (hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) X)
    (Q : Ideal (Bring Ω)) [Q.IsMaximal] [Q.LiesOver (placeP (0 : k))] :
    geomInertia Ω Q = ⊤ := by
  refine geomInertia_eq_top_of_finrank_le 0 Q ?_
  rw [hfr]
  exact le_ramificationIdx_of_pow_dvd 0 Q (pow_dvd_map_placeP_zero w hw Q)

end Ramification

namespace LineCover

attribute [local instance] sub_isGalois

/-! ## The Kummer pullback -/

section Pullback

variable (P : LineCover) [Algebra k P.M] [IsScalarTower k (RatFunc k) P.M]
  {m : ℕ} [NeZero m] {u : P.M}
  (hpow : u ^ m = algebraMap (RatFunc k) P.M (RatFunc.X : RatFunc k))
  (hsplits : (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
    (algebraMap (RatFunc k) P.M)).Splits)

include hpow hsplits in
/-- **A cover unramified away from the origin and carrying an `m`-th root of the coordinate, with
`m` killing the deck group, has cyclic deck group.**

Over the line of the root the cover is unramified everywhere, hence trivial; so the cover is the
Kummer line `uᵐ = T`, whose deck group is cyclic. -/
theorem isCyclic_deck_of_kummer_param (hexp : ∀ τ : P.deck, τ ^ m = 1)
    (hM : P.IsUnramifiedOutside {(0 : k)}) : IsCyclic P.deck := by
  have hu : Transcendental k u := transcendental_of_pow hpow
  set ρ := paramHom u hu with hρdef
  have hρ := algebraMap_mem_paramHom_fieldRange hu hpow
  have hC : ∀ c : k, ρ (algebraMap k (RatFunc k) c)
      = algebraMap (RatFunc k) P.M (algebraMap k (RatFunc k) c) := by
    intro c
    rw [hρdef, paramHom_const, IsScalarTower.algebraMap_apply k (RatFunc k) P.M]
  have hpowρ : ρ (RatFunc.X : RatFunc k) ^ m = algebraMap (RatFunc k) P.M RatFunc.X := by
    rw [hρdef, paramHom_X]
    exact hpow
  -- the Kummer line inside the cover
  set K : IntermediateField (RatFunc k) P.M := kummerBase hu hpow with hKdef
  haveI : Normal (RatFunc k) K := normal_kummerBase hu hpow hsplits
  haveI := isScalarTower_poly_sub (K : Type) P.M
  have hfrK : Module.finrank (RatFunc k) (K : Type) = m := finrank_kummerBase hu hpow hsplits
  have hcardK : Nat.card (P.sub K).deck = m := by
    show Nat.card ((K : Type) ≃ₐ[RatFunc k] (K : Type)) = m
    rw [show Nat.card ((K : Type) ≃ₐ[RatFunc k] (K : Type))
      = Module.finrank (RatFunc k) (K : Type) by
        simpa using IsGalois.card_aut_eq_finrank (RatFunc k) (K : Type)]
    exact hfrK
  -- the root of the coordinate, inside the integral model of the Kummer line
  have huK : u ∈ K := param_mem_kummerBase hu hpow
  have hcoeK : ∀ y : (K : Type), ((y : P.M)) = algebraMap (K : Type) P.M y := fun _ => rfl
  have hXK : ((algebraMap (Polynomial k) (K : Type) X : (K : Type)) : P.M)
      = algebraMap (Polynomial k) P.M X := by
    rw [hcoeK, ← IsScalarTower.algebraMap_apply (Polynomial k) (K : Type) P.M]
  have hupow : (⟨u, huK⟩ : (K : Type)) ^ m = algebraMap (Polynomial k) (K : Type) X := by
    apply Subtype.ext
    rw [show (((⟨u, huK⟩ : (K : Type)) ^ m : (K : Type)) : P.M) = u ^ m from by push_cast; rfl,
      hXK, hpow, IsScalarTower.algebraMap_apply (Polynomial k) (RatFunc k) P.M,
      RatFunc.algebraMap_X]
  have hint : IsIntegral (Polynomial k) (⟨u, huK⟩ : (K : Type)) := by
    refine ⟨(X : (Polynomial k)[X]) ^ m - C X, monic_X_pow_sub_C _ (NeZero.ne m), ?_⟩
    rw [eval₂_sub, eval₂_pow, eval₂_X, eval₂_C, hupow, sub_self]
  have hwK : (⟨_, hint⟩ : Bring (K : Type)) ^ m
      = algebraMap (Polynomial k) (Bring (K : Type)) X := by
    apply Subtype.ext
    push_cast
    rw [hupow, IsScalarTower.algebraMap_apply (Polynomial k) (Bring (K : Type)) (K : Type)]
  -- the inertia group over the origin injects into the deck group of the Kummer line
  have hinj0 : ∀ Q : Ideal (Bring P.M), Q.IsMaximal → Q.LiesOver (placeP (0 : k)) →
      ∀ τ : P.deck, τ ∈ geomInertia P.M Q → P.subHom K τ = 1 → τ = 1 := by
    intro Q hQmax hQover τ hτ hτK
    haveI := hQmax
    haveI : Q.IsPrime := hQmax.isPrime
    haveI := hQover
    haveI hcm : (Q.comap (subInclusion (E := (K : Type)) (M := P.M))).IsMaximal :=
      isMaximal_comap_subInclusion (E := (K : Type)) 0 Q
    haveI := liesOver_comap_subInclusion (E := (K : Type)) (M := P.M) 0 Q
    -- the Kummer line is totally ramified over the origin
    have htop : geomInertia (K : Type) (Q.comap (subInclusion (E := (K : Type)) (M := P.M))) = ⊤ :=
      geomInertia_eq_top_of_pow_eq_X hfrK _ hwK _
    have hmap : (geomInertia P.M Q).map (P.subHom K) = ⊤ := by
      rw [← geomInertia_comap_eq_map (E := (K : Type)) (M := P.M) (P.subHom K)
        (P.subHom_commutes K) 0 Q (P.subHom_surjective K)]
      exact htop
    -- the inertia group is cyclic of order dividing `m`, and maps onto a group of order `m`
    haveI : IsCyclic (geomInertia P.M Q) := isCyclic_geomInertia (Ω := P.M) 0 Q
    have hdvd : Nat.card (geomInertia P.M Q) ∣ m := by
      rw [← IsCyclic.exponent_eq_card]
      exact Monoid.exponent_dvd_of_forall_pow_eq_one fun g => Subtype.ext (hexp (g : P.deck))
    set φ : (geomInertia P.M Q) →* (P.sub K).deck :=
      (P.subHom K).comp (geomInertia P.M Q).subtype with hφdef
    have hφsurj : Function.Surjective φ := by
      intro y
      have hy : y ∈ (geomInertia P.M Q).map (P.subHom K) := by rw [hmap]; trivial
      obtain ⟨x, hx, hxy⟩ := hy
      exact ⟨⟨x, hx⟩, hxy⟩
    have hle : m ≤ Nat.card (geomInertia P.M Q) := by
      rw [← hcardK]
      exact Nat.card_le_card_of_surjective φ hφsurj
    have hcardI : Nat.card (geomInertia P.M Q) = m :=
      le_antisymm (Nat.le_of_dvd (NeZero.pos m) hdvd) hle
    have hφbij : Function.Bijective φ :=
      (Nat.bijective_iff_surjective_and_card φ).mpr ⟨hφsurj, by rw [hcardI, hcardK]⟩
    have hone : (⟨τ, hτ⟩ : (geomInertia P.M Q)) = 1 := by
      refine hφbij.injective ?_
      rw [map_one]
      exact hτK
    exact congrArg Subtype.val hone
  -- the chart cut out by the root
  haveI hfd : FiniteDimensional (RatFunc k) (Chart P.M ρ) := Chart.finiteDimensional ρ hρ
  haveI hgal : IsGalois (RatFunc k) (Chart P.M ρ) := Chart.isGalois ρ hρ
  set N : LineCover := LineCover.of (Chart P.M ρ) with hNdef
  -- a symmetry of the chart fixes the Kummer line, which is the line of the chart
  have hfixK : ∀ σ : N.deck, P.subHom K (Chart.deckHom ρ hρ σ) = 1 := by
    intro σ
    ext y
    apply FaithfulSMul.algebraMap_injective (K : Type) P.M
    rw [P.subHom_commutes K]
    obtain ⟨f, hf⟩ := y.2
    rw [hcoeK] at hf
    show (Chart.deckHom ρ hρ σ) (algebraMap (K : Type) P.M y)
      = algebraMap (K : Type) P.M ((1 : (P.sub K).deck) y)
    rw [show algebraMap (K : Type) P.M ((1 : (P.sub K).deck) y)
      = algebraMap (K : Type) P.M y from rfl, ← hf]
    exact σ.commutes f
  -- over the line of the root the cover is unramified everywhere
  have hNun : N.IsUnramifiedOutside (∅ : Set k) := by
    intro a _ σ hσ
    have hτ := isInertiaAt_pow_of_chart P ρ hρ hC hpowρ hσ
    have hdeck : Chart.deckHom ρ hρ σ = 1 := by
      rcases eq_or_ne a 0 with rfl | ha
      · obtain ⟨Q, hQmax, hQover, hQin⟩ := hτ
        rw [zero_pow (NeZero.ne m)] at hQover
        exact hinj0 Q hQmax hQover _ hQin (hfixK σ)
      · exact hM (a ^ m) (by simpa using pow_ne_zero m ha) _ hτ
    exact Chart.deckHom_injective ρ hρ (by rw [hdeck, map_one])
  haveI : Subsingleton N.deck := subsingleton_deck_of_unramifiedOutside_empty N hNun
  -- hence the cover *is* the Kummer line
  have hinj : Function.Injective (P.subHom K) := by
    refine (injective_iff_map_eq_one _).mpr fun τ hτ => ?_
    have hfix : τ (ρ (RatFunc.X : RatFunc k)) = ρ (RatFunc.X : RatFunc k) := by
      have h := P.subHom_commutes K τ ⟨u, huK⟩
      rw [hτ] at h
      rw [hρdef, paramHom_X]
      exact h.symm
    obtain ⟨τ', hτ'⟩ := Chart.exists_deckHom_eq ρ hρ hC τ hfix
    rw [← hτ', Subsingleton.elim τ' 1, map_one]
  haveI : IsCyclic (P.sub K).deck := isCyclic_kummerBase hu hpow hsplits
  haveI : IsCyclic ((P.subHom K).range) := Subgroup.isCyclic _
  exact isCyclic_of_surjective (MonoidHom.ofInjective hinj).symm
    (MonoidHom.ofInjective hinj).symm.surjective

end Pullback

end LineCover

end Rigidity.RET
