/-
Adjoining a family of independent radicals.
-/
import Mathlib

/-!
# Adjoining several independent radicals

Let `E` be a field of characteristic zero containing a primitive `n`-th root of unity, and let
`g : ι → E` be a finite family of nonzero elements which is *independent modulo `n`-th powers*:
the only monomial `∏ i, g i ^ m i` (with integer exponents) that is an `n`-th power in `E` is one
whose exponents are all divisible by `n`.  Choose radicals `w i` with `w i ^ n = g i` inside an
extension `L` generated by them.

The data is packaged as `Rigidity.RET.Kummer.Setup`.  Its main results are:

* `Setup.isGalois` — `L / E` is a Galois extension;
* `Setup.psi` — the Kummer character `Gal(L/E) →* (ι → μₙ)`, `σ ↦ (σ (w i) / w i)ᵢ`;
* `Setup.psi_bijective` — it is an isomorphism;
* `Setup.finrank_eq` — hence `[L : E] = n ^ #ι`;
* `Setup.exists_aut` — for each index `i₀` there is an automorphism multiplying `w i₀` by `ζ`
  and fixing every other radical.

The surjectivity of `psi` is the only substantial point: if the image were a proper subgroup of
`ι → μₙ`, a character of the finite abelian quotient with values in `L` would exhibit a monomial
in the `g i` as an `n`-th power in `E` with exponents not all divisible by `n`.
-/

noncomputable section

namespace Rigidity.RET.Kummer

open Polynomial IntermediateField

variable {E L : Type*} [Field E] [Field L] [Algebra E L]
variable {ι : Type*} [Fintype ι] [DecidableEq ι] {n : ℕ}

/-- A family of `n`-th roots of independent elements of `E`, generating the extension `L`. -/
structure Setup (E L : Type*) [Field E] [Field L] [Algebra E L] (ι : Type*) [Fintype ι]
    (n : ℕ) where
  /-- A primitive `n`-th root of unity of the base field. -/
  zeta : E
  /-- The elements whose radicals are adjoined. -/
  g : ι → E
  /-- The radicals themselves. -/
  w : ι → L
  isPrimitiveRoot : IsPrimitiveRoot zeta n
  g_ne_zero : ∀ i, g i ≠ 0
  w_pow : ∀ i, w i ^ n = algebraMap E L (g i)
  adjoin_eq_top : IntermediateField.adjoin E (Set.range w) = ⊤
  indep : ∀ (m : ι → ℤ) (y : E), y ≠ 0 → y ^ n = ∏ i, g i ^ m i → ∀ i, (n : ℤ) ∣ m i

namespace Setup

variable [NeZero n] [CharZero E] (S : Setup E L ι n)

/-! ### The radicals and the roots of unity -/

omit [DecidableEq ι] [CharZero E] in
theorem w_ne_zero (i : ι) : S.w i ≠ 0 := by
  intro h
  refine S.g_ne_zero i ?_
  have := S.w_pow i
  rw [h, zero_pow (NeZero.ne n)] at this
  exact (map_eq_zero (algebraMap E L)).mp this.symm

omit [DecidableEq ι] in
theorem zeta_ne_zero : S.zeta ≠ 0 := by
  intro h
  have := S.isPrimitiveRoot.pow_eq_one
  rw [h, zero_pow (NeZero.ne n)] at this
  exact zero_ne_one this

/-- The chosen primitive root of unity, viewed in `L`. -/
def zetaL : L := algebraMap E L S.zeta

omit [DecidableEq ι] [NeZero n] [CharZero E] in
theorem zetaL_isPrimitiveRoot : IsPrimitiveRoot S.zetaL n :=
  S.isPrimitiveRoot.map_of_injective (algebraMap E L).injective

omit [DecidableEq ι] in
theorem zetaL_ne_zero : S.zetaL ≠ 0 := by
  simpa [zetaL] using S.zeta_ne_zero

/-- The chosen primitive root of unity, as a unit of `L`. -/
def zetaU : Lˣ := Units.mk0 S.zetaL S.zetaL_ne_zero

omit [DecidableEq ι] in
theorem zetaU_isPrimitiveRoot : IsPrimitiveRoot S.zetaU n :=
  IsPrimitiveRoot.coe_units_iff.mp S.zetaL_isPrimitiveRoot

omit [DecidableEq ι] in
theorem rootsOfUnity_eq_zpowers : rootsOfUnity n L = Subgroup.zpowers S.zetaU :=
  S.zetaU_isPrimitiveRoot.zpowers_eq.symm

/-- The chosen primitive root of unity, as an element of the group of `n`-th roots of unity. -/
def zetaR : rootsOfUnity n L :=
  ⟨S.zetaU, by rw [mem_rootsOfUnity]; exact S.zetaU_isPrimitiveRoot.pow_eq_one⟩

omit [DecidableEq ι] in
@[simp] theorem zetaR_coe : ((S.zetaR : Lˣ) : L) = S.zetaL := rfl

omit [DecidableEq ι] in
theorem exists_zpow_zetaR (x : rootsOfUnity n L) : ∃ j : ℤ, x = S.zetaR ^ j := by
  have hx : (x : Lˣ) ∈ Subgroup.zpowers S.zetaU := by
    rw [← S.rootsOfUnity_eq_zpowers]; exact x.2
  obtain ⟨j, hj⟩ := hx
  refine ⟨j, Subtype.ext ?_⟩
  rw [SubgroupClass.coe_zpow]
  exact hj.symm

omit [DecidableEq ι] [CharZero E] in
include S in
/-- Every `n`-th root of unity of `L` lies in the base field, hence is fixed by the Galois
action. -/
theorem map_eq_of_pow_eq_one (σ : L ≃ₐ[E] L) {x : L} (hx : x ^ n = 1) : σ x = x := by
  obtain ⟨j, -, rfl⟩ := S.zetaL_isPrimitiveRoot.eq_pow_of_pow_eq_one hx
  rw [map_pow]
  congr 1
  exact σ.commutes S.zeta

/-! ### `L` is Galois over `E` -/

/-- The polynomial of which `L` is a splitting field. -/
def poly : E[X] := ∏ i, (X ^ n - C (S.g i))

omit [DecidableEq ι] in
theorem w_isAlgebraic (i : ι) : IsAlgebraic E (S.w i) := by
  refine ⟨X ^ n - C (S.g i), ?_, ?_⟩
  · intro h
    have := congrArg (fun p => Polynomial.coeff p n) h
    simp [Polynomial.coeff_X_pow, Polynomial.coeff_C, NeZero.ne n] at this
  · simp [S.w_pow i]

omit [DecidableEq ι] in
theorem algebra_adjoin_eq_top : Algebra.adjoin E (Set.range S.w) = ⊤ := by
  have h := IntermediateField.adjoin_toSubalgebra_of_isAlgebraic (F := E) (E := L)
    (S := Set.range S.w) (by rintro _ ⟨i, rfl⟩; exact S.w_isAlgebraic i)
  rw [S.adjoin_eq_top] at h
  exact h.symm

omit [DecidableEq ι] in
theorem isSplittingField : IsSplittingField E L S.poly := by
  constructor
  · rw [poly, Polynomial.map_prod]
    refine Polynomial.Splits.prod fun i _ => ?_
    rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X, Polynomial.map_C]
    exact X_pow_sub_C_splits_of_isPrimitiveRoot S.zetaL_isPrimitiveRoot (S.w_pow i)
  · refine top_le_iff.mp ?_
    rw [← S.algebra_adjoin_eq_top]
    refine Algebra.adjoin_mono ?_
    rintro _ ⟨i, rfl⟩
    rw [Polynomial.mem_rootSet]
    refine ⟨?_, ?_⟩
    · refine Finset.prod_ne_zero_iff.mpr fun j _ => ?_
      exact (Polynomial.X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero (NeZero.ne n)) (S.g j))
    · rw [poly, map_prod]
      refine Finset.prod_eq_zero (Finset.mem_univ i) ?_
      simp [S.w_pow i]

omit [DecidableEq ι] in
include S in
theorem finiteDimensional : FiniteDimensional E L :=
  haveI := S.isSplittingField
  IsSplittingField.finiteDimensional (f := S.poly) L

omit [DecidableEq ι] in
include S in
theorem normal : Normal E L :=
  haveI := S.isSplittingField
  Normal.of_isSplittingField S.poly

omit [DecidableEq ι] in
include S in
theorem isGalois : IsGalois E L :=
  haveI := S.finiteDimensional
  haveI := S.normal
  ⟨⟩

/-! ### The Kummer character -/

omit [DecidableEq ι] [CharZero E] in
theorem psi_aux_pow (σ : L ≃ₐ[E] L) (i : ι) : (σ (S.w i) / S.w i) ^ n = 1 := by
  rw [div_pow, ← map_pow, S.w_pow, AlgEquiv.commutes, ← S.w_pow]
  exact div_self (pow_ne_zero _ (S.w_ne_zero i))

omit [DecidableEq ι] [CharZero E] in
theorem psi_aux_ne_zero (σ : L ≃ₐ[E] L) (i : ι) : σ (S.w i) / S.w i ≠ 0 :=
  div_ne_zero (by simpa using S.w_ne_zero i) (S.w_ne_zero i)

/-- The Kummer character `σ ↦ (σ (w i) / w i)ᵢ`. -/
def psi : (L ≃ₐ[E] L) →* (ι → rootsOfUnity n L) where
  toFun σ i := ⟨Units.mk0 _ (S.psi_aux_ne_zero σ i), by
    rw [mem_rootsOfUnity, ← Units.val_eq_one, Units.val_pow_eq_pow_val, Units.val_mk0]
    exact S.psi_aux_pow σ i⟩
  map_one' := by
    funext i
    refine Subtype.ext (Units.ext ?_)
    simp [S.w_ne_zero i]
  map_mul' := by
    intro σ τ
    funext i
    refine Subtype.ext (Units.ext ?_)
    have hfix : σ (τ (S.w i) / S.w i) = τ (S.w i) / S.w i :=
      S.map_eq_of_pow_eq_one σ (S.psi_aux_pow τ i)
    rw [map_div₀] at hfix
    have h1 : σ (S.w i) ≠ 0 := by simpa using S.w_ne_zero i
    have h2 : S.w i ≠ 0 := S.w_ne_zero i
    have h3 : σ (τ (S.w i)) = τ (S.w i) / S.w i * σ (S.w i) :=
      (div_eq_iff h1).mp hfix
    show σ (τ (S.w i)) / S.w i = (σ (S.w i) / S.w i) * (τ (S.w i) / S.w i)
    rw [h3]
    field_simp

omit [DecidableEq ι] [CharZero E] in
@[simp] theorem psi_coe (σ : L ≃ₐ[E] L) (i : ι) :
    ((S.psi σ i : Lˣ) : L) = σ (S.w i) / S.w i := rfl

omit [DecidableEq ι] in
theorem psi_injective : Function.Injective S.psi := by
  rw [injective_iff_map_eq_one]
  intro σ hσ
  have hfix : ∀ i, σ (S.w i) = S.w i := by
    intro i
    have := congrArg (fun f => ((f i : Lˣ) : L)) hσ
    simp only [psi_coe] at this
    have h1 : σ (S.w i) / S.w i = 1 := by simpa using this
    rw [div_eq_one_iff_eq (S.w_ne_zero i)] at h1
    exact h1
  have : σ.toAlgHom = AlgHom.id E L := by
    refine AlgHom.ext_of_adjoin_eq_top S.algebra_adjoin_eq_top ?_
    rintro _ ⟨i, rfl⟩
    exact hfix i
  ext x
  exact congrArg (fun φ => φ x) this

/-! ### Surjectivity of the Kummer character -/

section Surjective

omit [DecidableEq ι] [CharZero E] in
include S in
theorem hasEnoughRootsOfUnity : HasEnoughRootsOfUnity L n :=
  ⟨⟨S.zetaL, S.zetaL_isPrimitiveRoot⟩, rootsOfUnity.isCyclic L n⟩

include S in
/-- The components of a character of `ι → μₙ` are given by integer powers. -/
theorem exists_exponents (χ : (ι → rootsOfUnity n L) →* Lˣ) :
    ∃ m : ι → ℤ, ∀ (i : ι) (x : rootsOfUnity n L),
      χ (Pi.mulSingle i x) = (x : Lˣ) ^ m i := by
  have key : ∀ i : ι, ∃ k : ℤ, ∀ x : rootsOfUnity n L,
      χ (Pi.mulSingle i x) = (x : Lˣ) ^ k := by
    intro i
    set θ : (rootsOfUnity n L) →* Lˣ :=
      χ.comp (MonoidHom.mulSingle (fun _ : ι => (rootsOfUnity n L)) i) with hθ
    have hθapp : ∀ x, θ x = χ (Pi.mulSingle i x) := fun x => rfl
    have hzR : S.zetaR ^ n = 1 := by
      refine Subtype.ext ?_
      rw [SubgroupClass.coe_pow]
      exact S.zetaU_isPrimitiveRoot.pow_eq_one
    have hpow : (θ S.zetaR) ^ n = 1 := by rw [← map_pow, hzR, map_one]
    have hmem : θ S.zetaR ∈ Subgroup.zpowers S.zetaU := by
      rw [← S.rootsOfUnity_eq_zpowers, mem_rootsOfUnity]
      exact hpow
    obtain ⟨k, hk⟩ := hmem
    refine ⟨k, fun x => ?_⟩
    obtain ⟨j, rfl⟩ := S.exists_zpow_zetaR x
    have hcoe : ((S.zetaR ^ j : rootsOfUnity n L) : Lˣ) = S.zetaU ^ j := by
      rw [SubgroupClass.coe_zpow]
      rfl
    rw [← hθapp, map_zpow, ← hk, hcoe, ← zpow_mul, ← zpow_mul, mul_comm k j]
  choose m hm using key
  exact ⟨m, hm⟩

theorem psi_surjective : Function.Surjective S.psi := by
  haveI := S.isGalois
  haveI := S.finiteDimensional
  haveI := S.hasEnoughRootsOfUnity
  by_contra hns
  have hne : S.psi.range ≠ ⊤ := by
    rw [Ne, MonoidHom.range_eq_top]
    exact hns
  obtain ⟨a, ha⟩ : ∃ a : ι → rootsOfUnity n L, a ∉ S.psi.range := by
    by_contra hc
    push_neg at hc
    exact hne (eq_top_iff.mpr fun x _ => hc x)
  -- a nontrivial character of the quotient
  have hexp : Monoid.exponent ((ι → rootsOfUnity n L) ⧸ S.psi.range) ∣ n := by
    refine Monoid.exponent_dvd_of_forall_pow_eq_one fun q => ?_
    induction q using QuotientGroup.induction_on with
    | H x =>
      rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
      have : x ^ n = 1 := by
        funext i
        refine Subtype.ext (Units.ext ?_)
        have := (mem_rootsOfUnity _ _).mp (x i).2
        simpa using congrArg (fun u : Lˣ => (u : L)) this
      rw [this]
      exact Subgroup.one_mem _
  haveI : HasEnoughRootsOfUnity L (Monoid.exponent
      ((ι → rootsOfUnity n L) ⧸ S.psi.range)) := HasEnoughRootsOfUnity.of_dvd L hexp
  have hqa : (QuotientGroup.mk' S.psi.range) a ≠ 1 := by
    rw [Ne, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
    exact ha
  obtain ⟨φ, hφ⟩ := CommGroup.exists_apply_ne_one_of_hasEnoughRootsOfUnity _ L hqa
  set χ : (ι → rootsOfUnity n L) →* Lˣ := φ.comp (QuotientGroup.mk' S.psi.range) with hχdef
  have hχa : χ a ≠ 1 := hφ
  have hχtriv : ∀ σ : L ≃ₐ[E] L, χ (S.psi σ) = 1 := by
    intro σ
    have : (QuotientGroup.mk' S.psi.range) (S.psi σ) = 1 := by
      rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
      exact ⟨σ, rfl⟩
    rw [hχdef, MonoidHom.comp_apply, this, map_one]
  obtain ⟨m, hm⟩ := S.exists_exponents χ
  -- the monomial in the radicals attached to the exponent vector `m`
  set y : L := ∏ i, S.w i ^ m i with hy
  have hyne : y ≠ 0 := Finset.prod_ne_zero_iff.mpr fun i _ => zpow_ne_zero _ (S.w_ne_zero i)
  have hfix : ∀ σ : L ≃ₐ[E] L, σ y = y := by
    intro σ
    have h1 : ∏ i, ((S.psi σ i : Lˣ) : L) ^ m i = 1 := by
      have h2 := hχtriv σ
      rw [← Finset.univ_prod_mulSingle (S.psi σ), map_prod] at h2
      have h3 : ∏ i, ((S.psi σ i : Lˣ) ^ m i) = 1 := by
        rw [← h2]
        exact Finset.prod_congr rfl fun i _ => (hm i (S.psi σ i)).symm
      have := congrArg (fun u : Lˣ => (u : L)) h3
      simpa using this
    simp only [psi_coe, div_zpow] at h1
    rw [Finset.prod_div_distrib, div_eq_one_iff_eq] at h1
    · rw [hy, map_prod]
      simp only [map_zpow₀]
      exact h1
    · exact Finset.prod_ne_zero_iff.mpr fun i _ => zpow_ne_zero _ (S.w_ne_zero i)
  obtain ⟨y₀, hy₀0⟩ := (IsGalois.mem_bot_iff_fixed y).mpr hfix
  have hy₀ : algebraMap E L y₀ = y := hy₀0
  have hy₀ne : y₀ ≠ 0 := by
    intro h
    rw [h, map_zero] at hy₀
    exact hyne hy₀.symm
  have hkey : y₀ ^ n = ∏ i, S.g i ^ m i := by
    have h1 : (algebraMap E L) (y₀ ^ n) = (algebraMap E L) (∏ i, S.g i ^ m i) := by
      rw [map_pow, hy₀, hy, ← Finset.prod_pow]
      rw [map_prod]
      refine Finset.prod_congr rfl fun i _ => ?_
      rw [map_zpow₀, ← S.w_pow i, ← zpow_natCast (S.w i ^ m i) n, ← zpow_mul,
        ← zpow_natCast (S.w i) n, ← zpow_mul, mul_comm]
    exact (algebraMap E L).injective h1
  have hdvd := S.indep m y₀ hy₀ne hkey
  -- then every component of `χ` is trivial, contradicting `χ a ≠ 1`
  refine hχa ?_
  rw [← Finset.univ_prod_mulSingle a, map_prod]
  refine Finset.prod_eq_one fun i _ => ?_
  rw [hm i (a i)]
  obtain ⟨t, ht⟩ := hdvd i
  rw [ht, zpow_mul, zpow_natCast]
  have : ((a i : Lˣ)) ^ n = 1 := (mem_rootsOfUnity _ _).mp (a i).2
  rw [this, one_zpow]

theorem psi_bijective : Function.Bijective S.psi :=
  ⟨S.psi_injective, S.psi_surjective⟩

/-- The Kummer isomorphism `Gal(L/E) ≃ (ι → μₙ)`. -/
def galEquiv : (L ≃ₐ[E] L) ≃* (ι → rootsOfUnity n L) :=
  MulEquiv.ofBijective S.psi S.psi_bijective

include S in
theorem card_aut : Nat.card (L ≃ₐ[E] L) = n ^ Fintype.card ι := by
  haveI := S.hasEnoughRootsOfUnity
  rw [Nat.card_congr S.galEquiv.toEquiv, Nat.card_pi, Finset.prod_const,
    HasEnoughRootsOfUnity.natCard_rootsOfUnity L n, Finset.card_univ]

include S in
theorem finrank_eq : Module.finrank E L = n ^ Fintype.card ι := by
  haveI := S.isGalois
  haveI := S.finiteDimensional
  rw [← IsGalois.card_aut_eq_finrank E L, S.card_aut]

/-- For every index there is an automorphism multiplying that radical by `ζ` and fixing all the
others. -/
theorem exists_aut (i₀ : ι) : ∃ σ : L ≃ₐ[E] L,
    σ (S.w i₀) = algebraMap E L S.zeta * S.w i₀ ∧ ∀ i, i ≠ i₀ → σ (S.w i) = S.w i := by
  obtain ⟨σ, hσ⟩ := S.psi_surjective (Pi.mulSingle i₀ S.zetaR)
  refine ⟨σ, ?_, ?_⟩
  · have := congrArg (fun f => ((f i₀ : Lˣ) : L)) hσ
    simp only [psi_coe, Pi.mulSingle_eq_same, zetaR_coe] at this
    rw [div_eq_iff (S.w_ne_zero i₀)] at this
    rw [this]
    rfl
  · intro i hi
    have := congrArg (fun f => ((f i : Lˣ) : L)) hσ
    simp only [psi_coe, Pi.mulSingle_eq_of_ne hi] at this
    have h1 : σ (S.w i) / S.w i = 1 := by simpa using this
    rw [div_eq_one_iff_eq (S.w_ne_zero i)] at h1
    exact h1

omit [DecidableEq ι] in
/-- Every automorphism multiplies the radicals by powers of `ζ`. -/
theorem exists_zpow_of_aut (σ : L ≃ₐ[E] L) :
    ∃ m : ι → ℤ, ∀ i, σ (S.w i) = S.zetaL ^ m i * S.w i := by
  choose m hm using fun i => S.exists_zpow_zetaR (S.psi σ i)
  refine ⟨m, fun i => ?_⟩
  have h := congrArg (fun x : rootsOfUnity n L => ((x : Lˣ) : L)) (hm i)
  have hz : (((S.zetaR ^ m i : rootsOfUnity n L) : Lˣ) : L) = S.zetaL ^ m i := by
    rw [SubgroupClass.coe_zpow, Units.val_zpow_eq_zpow_val, zetaR_coe]
  simp only [psi_coe, hz] at h
  rw [div_eq_iff (S.w_ne_zero i)] at h
  exact h

/-- Every prescribed system of powers of `ζ` is realized by an automorphism. -/
theorem exists_aut_zpow (m : ι → ℤ) : ∃ σ : L ≃ₐ[E] L,
    ∀ i, σ (S.w i) = S.zetaL ^ m i * S.w i := by
  obtain ⟨σ, hσ⟩ := S.psi_surjective (fun i => S.zetaR ^ m i)
  refine ⟨σ, fun i => ?_⟩
  have h := congrArg (fun f => ((f i : Lˣ) : L)) hσ
  have hz : (((S.zetaR ^ m i : rootsOfUnity n L) : Lˣ) : L) = S.zetaL ^ m i := by
    rw [SubgroupClass.coe_zpow, Units.val_zpow_eq_zpow_val, zetaR_coe]
  simp only [psi_coe, hz] at h
  rw [div_eq_iff (S.w_ne_zero i)] at h
  exact h

end Surjective

end Setup

end Rigidity.RET.Kummer
