/-
Building multi-radical extensions, and their behaviour under a base change.
-/
import Mathlib
import InverseGalois.Rigidity.RET.KummerIndep

/-!
# Multi-radical extensions and base change

Two complements to `Rigidity.RET.Kummer.Setup`.

First, a *construction*: given a field `E` containing a primitive `n`-th root of unity and a
family `g : ι → E` of nonzero elements independent modulo `n`-th powers, the splitting field
`RadExt n g` of `∏ i, (X ^ n - g i)` carries a `Setup`, namely `setupOfIndep`.

Second, a *comparison*: if `E'` is an extension of `E` and the transported family is still
independent — witnessed by a second setup `S'` over `E'` — then the base change
`E' ⊗[E] L` of the first extension is again a field, isomorphic to the second one.  Both sides
have dimension `n ^ #ι` over `E'`, and a lift of the radicals gives a surjection of the first
onto the second; see `isField_tensor`.
-/

noncomputable section

namespace Rigidity.RET.Kummer

open Polynomial IntermediateField

/-! ### The extension generated by a family of radicals -/

section Construct

variable {E : Type*} [Field E] {ι : Type*} [Fintype ι] {n : ℕ}

/-- The polynomial whose roots are the `n`-th roots of the members of a family. -/
def radPoly (n : ℕ) (g : ι → E) : E[X] := ∏ i, (X ^ n - C (g i))

/-- The extension of `E` generated by `n`-th roots of the members of a family. -/
abbrev RadExt (n : ℕ) (g : ι → E) : Type _ := (radPoly n g).SplittingField

variable [NeZero n] {g : ι → E}

theorem radPoly_ne_zero : radPoly n g ≠ 0 :=
  Finset.prod_ne_zero_iff.mpr fun _ _ =>
    X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero (NeZero.ne n)) _

theorem splits_radFactor (i : ι) :
    (((X : E[X]) ^ n - C (g i)).map (algebraMap E (RadExt n g))).Splits :=
  Polynomial.Splits.of_dvd (Polynomial.SplittingField.splits (radPoly n g))
    (by rw [Ne, Polynomial.map_eq_zero]; exact radPoly_ne_zero)
    (Polynomial.map_dvd _ (Finset.dvd_prod_of_mem _ (Finset.mem_univ i)))

omit [NeZero n] in
theorem map_radFactor (i : ι) :
    ((X : E[X]) ^ n - C (g i)).map (algebraMap E (RadExt n g))
      = X ^ n - C (algebraMap E (RadExt n g) (g i)) := by
  rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X, Polynomial.map_C]

theorem exists_radRoot (i : ι) :
    ∃ x : RadExt n g, x ^ n = algebraMap E (RadExt n g) (g i) := by
  have hdeg : (((X : E[X]) ^ n - C (g i)).map (algebraMap E (RadExt n g))).degree ≠ 0 := by
    rw [map_radFactor, Polynomial.degree_X_pow_sub_C (Nat.pos_of_ne_zero (NeZero.ne n))]
    intro hc
    exact NeZero.ne n (by exact_mod_cast hc)
  obtain ⟨x, hx⟩ := (splits_radFactor i).exists_eval_eq_zero hdeg
  refine ⟨x, ?_⟩
  rw [map_radFactor, Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X,
    Polynomial.eval_C, sub_eq_zero] at hx
  exact hx

/-- A choice of `n`-th root of `g i` in the extension. -/
def radRoot (n : ℕ) [NeZero n] (g : ι → E) (i : ι) : RadExt n g := (exists_radRoot i).choose

theorem radRoot_pow (i : ι) : radRoot n g i ^ n = algebraMap E (RadExt n g) (g i) :=
  (exists_radRoot i).choose_spec

theorem radRoot_ne_zero (hg : ∀ i, g i ≠ 0) (i : ι) : radRoot n g i ≠ 0 := by
  intro h
  refine hg i ((algebraMap E (RadExt n g)).injective ?_)
  rw [map_zero, ← radRoot_pow (n := n) (g := g) i, h, zero_pow (NeZero.ne n)]

/-- The primitive root of unity, viewed in the extension. -/
def radZeta (n : ℕ) [NeZero n] (g : ι → E) (zeta : E) : RadExt n g :=
  algebraMap E (RadExt n g) zeta

theorem radZeta_isPrimitiveRoot {zeta : E} (hz : IsPrimitiveRoot zeta n) :
    IsPrimitiveRoot (radZeta n g zeta) n :=
  hz.map_of_injective (algebraMap E (RadExt n g)).injective

/-- The radicals generate the extension. -/
theorem adjoin_radRoot_eq_top {zeta : E} (hz : IsPrimitiveRoot zeta n) (hg : ∀ i, g i ≠ 0) :
    IntermediateField.adjoin E (Set.range (radRoot n g)) = ⊤ := by
  set S : IntermediateField E (RadExt n g) := IntermediateField.adjoin E (Set.range (radRoot n g))
    with hSdef
  have hsub : (radPoly n g).rootSet (RadExt n g) ⊆ (S : Set (RadExt n g)) := by
    intro x hx
    rw [Polynomial.mem_rootSet] at hx
    obtain ⟨-, hx0⟩ := hx
    have hx1 : ∏ i : ι, (Polynomial.aeval x) ((X : E[X]) ^ n - C (g i)) = 0 := by
      rw [← map_prod]; exact hx0
    rw [Finset.prod_eq_zero_iff] at hx1
    obtain ⟨i, -, hi⟩ := hx1
    rw [map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C, sub_eq_zero] at hi
    have hq : (x / radRoot n g i) ^ n = 1 := by
      rw [div_pow, hi, ← radRoot_pow (n := n) (g := g) i,
        div_self (pow_ne_zero _ (radRoot_ne_zero hg i))]
    obtain ⟨j, -, hj⟩ := (radZeta_isPrimitiveRoot (g := g) hz).eq_pow_of_pow_eq_one hq
    have hxeq : x = radZeta n g zeta ^ j * radRoot n g i := by
      rw [hj, div_mul_cancel₀ _ (radRoot_ne_zero hg i)]
    rw [hxeq]
    exact mul_mem (pow_mem (IntermediateField.algebraMap_mem _ _) _)
      (IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩)
  refine top_unique fun x _ => ?_
  have h1 : x ∈ Algebra.adjoin E ((radPoly n g).rootSet (RadExt n g)) := by
    rw [Polynomial.SplittingField.adjoin_rootSet]
    trivial
  exact Algebra.adjoin_le hsub h1

/-- **The Kummer setup attached to an independent family of radicands.** -/
def setupOfIndep (zeta : E) (hz : IsPrimitiveRoot zeta n) (g : ι → E) (hg : ∀ i, g i ≠ 0)
    (hind : ∀ (m : ι → ℤ) (y : E), y ≠ 0 → y ^ n = ∏ i, g i ^ m i → ∀ i, (n : ℤ) ∣ m i) :
    Setup E (RadExt n g) ι n where
  zeta := zeta
  g := g
  w := radRoot n g
  isPrimitiveRoot := hz
  g_ne_zero := hg
  w_pow := radRoot_pow
  adjoin_eq_top := adjoin_radRoot_eq_top hz hg
  indep := hind

@[simp]
theorem setupOfIndep_g (zeta : E) (hz : IsPrimitiveRoot zeta n) (g : ι → E) (hg : ∀ i, g i ≠ 0)
    (hind : ∀ (m : ι → ℤ) (y : E), y ≠ 0 → y ^ n = ∏ i, g i ^ m i → ∀ i, (n : ℤ) ∣ m i) :
    (setupOfIndep zeta hz g hg hind).g = g := rfl

end Construct

/-! ### Base change -/

section BaseChange

open scoped TensorProduct

variable {E L E' L' : Type*} [Field E] [Field L] [Field E'] [Field L']
  [Algebra E L] [Algebra E E'] [Algebra E' L'] [Algebra E L'] [IsScalarTower E E' L']
variable {ι : Type*} [Fintype ι] [DecidableEq ι] {n : ℕ} [NeZero n] [CharZero E] [CharZero E']

omit [DecidableEq ι] [CharZero E'] in
/-- The radicals of the base-changed family are roots of the transported minimal polynomials, so
the big extension embeds into the base-changed one. -/
theorem nonempty_algHom_of_setup (S : Setup E L ι n) (S' : Setup E' L' ι n)
    (hg : ∀ i, S'.g i = algebraMap E E' (S.g i)) : Nonempty (L →ₐ[E] L') := by
  haveI := S.finiteDimensional
  refine IntermediateField.nonempty_algHom_of_adjoin_splits (S := Set.range S.w) ?_ S.adjoin_eq_top
  rintro _ ⟨i, rfl⟩
  refine ⟨IsIntegral.of_finite _ _, ?_⟩
  have hdvd : minpoly E (S.w i) ∣ (X : E[X]) ^ n - C (S.g i) :=
    minpoly.dvd _ _ (by
      rw [map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C, S.w_pow, sub_self])
  have hmap : ((X : E[X]) ^ n - C (S.g i)).map (algebraMap E L') = X ^ n - C (S'.w i ^ n) := by
    rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X, Polynomial.map_C, S'.w_pow, hg,
      ← IsScalarTower.algebraMap_apply]
  refine Polynomial.Splits.of_dvd ?_ ?_ (Polynomial.map_dvd _ hdvd)
  · rw [hmap]
    exact X_pow_sub_C_splits_of_isPrimitiveRoot S'.zetaL_isPrimitiveRoot rfl
  · rw [hmap]
    exact X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero (NeZero.ne n)) _

/-- **The base change of a multi-radical extension along an extension of the base field is again
a field**, provided the radicands stay independent there. -/
theorem isField_tensor (S : Setup E L ι n) (S' : Setup E' L' ι n)
    (hg : ∀ i, S'.g i = algebraMap E E' (S.g i)) : IsField (E' ⊗[E] L) := by
  haveI := S.finiteDimensional
  haveI := S'.finiteDimensional
  obtain ⟨ψ⟩ := nonempty_algHom_of_setup S S' hg
  set Φ : (E' ⊗[E] L) →ₐ[E'] L' :=
    Algebra.TensorProduct.lift (Algebra.ofId E' L') ψ (fun _ _ => Commute.all _ _) with hΦ
  have hΦtmul : ∀ x : L, Φ ((1 : E') ⊗ₜ[E] x) = ψ x := by
    intro x
    rw [hΦ, Algebra.TensorProduct.lift_tmul, map_one, one_mul]
  have hpow : ∀ i, ψ (S.w i) ^ n = S'.w i ^ n := by
    intro i
    rw [← map_pow, S.w_pow, ψ.commutes, S'.w_pow, hg, ← IsScalarTower.algebraMap_apply]
  have hsurj : Function.Surjective Φ := by
    rw [← AlgHom.range_eq_top]
    refine top_le_iff.mp ?_
    rw [← S'.algebra_adjoin_eq_top]
    refine Algebra.adjoin_le ?_
    rintro _ ⟨i, rfl⟩
    have hq : (ψ (S.w i) / S'.w i) ^ n = 1 := by
      rw [div_pow, hpow, div_self (pow_ne_zero _ (S'.w_ne_zero i))]
    obtain ⟨j, -, hj⟩ := S'.zetaL_isPrimitiveRoot.eq_pow_of_pow_eq_one hq
    have h1 : ψ (S.w i) = S'.zetaL ^ j * S'.w i := by
      rw [hj, div_mul_cancel₀ _ (S'.w_ne_zero i)]
    have hwi : S'.w i = algebraMap E' L' (S'.zeta⁻¹ ^ j) * ψ (S.w i) := by
      rw [h1, map_pow, map_inv₀]
      show S'.w i = (S'.zetaL)⁻¹ ^ j * (S'.zetaL ^ j * S'.w i)
      rw [← mul_assoc, ← mul_pow, inv_mul_cancel₀ S'.zetaL_ne_zero, one_pow, one_mul]
    rw [hwi]
    exact mul_mem (Subalgebra.algebraMap_mem _ _) ⟨(1 : E') ⊗ₜ[E] S.w i, hΦtmul _⟩
  have hfin : Module.finrank E' (E' ⊗[E] L) = Module.finrank E' L' := by
    rw [Module.finrank_baseChange, S.finrank_eq, S'.finrank_eq]
  haveI : FiniteDimensional E' (E' ⊗[E] L) := inferInstance
  have hbij : Function.Bijective Φ :=
    ⟨(LinearMap.injective_iff_surjective_of_finrank_eq_finrank hfin
      (f := Φ.toLinearMap)).mpr hsurj, hsurj⟩
  exact (RingEquiv.ofBijective (Φ : (E' ⊗[E] L) →+* L') hbij).toMulEquiv.isField
    (Field.toIsField L')

end BaseChange

end Rigidity.RET.Kummer

end
