/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.BaseChart
import InverseGalois.Rigidity.RET.KummerCover
import InverseGalois.Rigidity.RET.KummerInertia

/-!
# A Kummer parameter as a second coordinate on the line

Let `M` be an extension of `ℚ̄(T)` containing an element `u` with `uᵐ = T`.  Then `u` is again a
coordinate on the line: it is transcendental over `ℚ̄`, so it determines an embedding
`ρ : ℚ̄(T) → M` sending the parameter to `u`, and the image of that embedding — the subfield
`ℚ̄(u)` — contains the original `ℚ̄(T)`, because `T` is the `m`-th power of `u`.  This is the
situation the chart of `RET/BaseChart.lean` was built for.

The image `ℚ̄(u)` is described here on both sides: it is the subfield generated by `u`, and it is
also the splitting field of `Xᵐ - T` inside `M`, because the other `m`-th roots of `T` are the
products `ζⁱu` with `ζ` a root of unity, and those constants are already in `ℚ̄`.  So the Kummer
line sitting inside `M` is a normal subextension of degree `m` with cyclic Galois group — the
degree-`m` self-map `x ↦ xᵐ` of the projective line, branched over `0` and `∞`.

## Main definitions

* `Rigidity.RET.paramHom` — the embedding of the line determined by a transcendental element.

## Main results

* `Rigidity.RET.transcendental_of_pow` — a root of a transcendental element is transcendental.
* `Rigidity.RET.algebraMap_mem_paramHom_fieldRange` — the Kummer parameter's line contains the
  original one.
* `Rigidity.RET.kummerBase_eq_adjoin_rootSet` — the Kummer parameter's line is the splitting field
  of `Xᵐ - T` inside `M`.
* `Rigidity.RET.finrank_kummerBase`, `Rigidity.RET.isCyclic_kummerBase` — it has degree `m` and
  cyclic Galois group.
-/

open Polynomial

noncomputable section


namespace Rigidity.RET

open GeomAKLB

variable {M : Type} [Field M] [Algebra (RatFunc k) M] [Algebra k M]
  [IsScalarTower k (RatFunc k) M]

/-! ## The line through a transcendental element -/

/-- **The embedding of the line determined by a transcendental element**: the unique morphism of
`ℚ̄`-algebras from the line to `M` carrying the parameter to `u`. -/
def paramHom (u : M) (hu : Transcendental k u) : RatFunc k →+* M :=
  IsFractionRing.lift (A := Polynomial k) (K := RatFunc k)
    (g := (Polynomial.aeval u : Polynomial k →ₐ[k] M).toRingHom)
    (transcendental_iff_injective.mp hu)

omit [Algebra (RatFunc k) M] [IsScalarTower k (RatFunc k) M] in
@[simp] theorem paramHom_algebraMap {u : M} (hu : Transcendental k u) (p : Polynomial k) :
    paramHom u hu (algebraMap (Polynomial k) (RatFunc k) p) = Polynomial.aeval u p :=
  IsFractionRing.lift_algebraMap _ p

omit [Algebra (RatFunc k) M] [IsScalarTower k (RatFunc k) M] in
@[simp] theorem paramHom_X {u : M} (hu : Transcendental k u) : paramHom u hu RatFunc.X = u := by
  have h : (RatFunc.X : RatFunc k) = algebraMap (Polynomial k) (RatFunc k) Polynomial.X := by
    simp
  rw [h, paramHom_algebraMap]
  simp

omit [Algebra (RatFunc k) M] in
@[simp] theorem paramHom_const {u : M} (hu : Transcendental k u) (c : k) :
    paramHom u hu (algebraMap k (RatFunc k) c) = algebraMap k M c := by
  rw [IsScalarTower.algebraMap_apply k (Polynomial k) (RatFunc k), paramHom_algebraMap]
  simp

/-- The parameter of the line is transcendental over the constants inside any extension. -/
theorem transcendental_algebraMap_X :
    Transcendental k (algebraMap (RatFunc k) M (RatFunc.X : RatFunc k)) := by
  intro halg
  refine RatFunc.transcendental_X (K := k) ?_
  refine (isAlgebraic_algHom_iff (IsScalarTower.toAlgHom k (RatFunc k) M) ?_).mp halg
  exact (algebraMap (RatFunc k) M).injective

/-- **A root of the parameter is again transcendental**, so it is again a coordinate on the
line. -/
theorem transcendental_of_pow {u : M} {m : ℕ} (hpow : u ^ m = algebraMap (RatFunc k) M (RatFunc.X : RatFunc k)) : Transcendental k u := by
  intro halg
  exact transcendental_algebraMap_X (M := M) (hpow ▸ halg.pow m)

/-- **The line through a Kummer parameter contains the original line**: the original parameter is
the `m`-th power of the new one. -/
theorem algebraMap_mem_paramHom_fieldRange {u : M} (hu : Transcendental k u) {m : ℕ}
    (hpow : u ^ m = algebraMap (RatFunc k) M (RatFunc.X : RatFunc k)) (f : RatFunc k) :
    algebraMap (RatFunc k) M f ∈ (paramHom u hu).fieldRange := by
  refine ratFunc_mem_subfield (algebraMap (RatFunc k) M) (paramHom u hu).fieldRange ?_ ?_ f
  · intro c
    exact ⟨algebraMap k (RatFunc k) c, by
      rw [paramHom_const, ← IsScalarTower.algebraMap_apply k (RatFunc k) M]⟩
  · exact ⟨RatFunc.X ^ m, by rw [map_pow, paramHom_X, hpow]⟩

/-! ## The Kummer line inside `M` -/

section KummerBase

variable {u : M} (hu : Transcendental k u) {m : ℕ} [NeZero m]
  (hpow : u ^ m = algebraMap (RatFunc k) M (RatFunc.X : RatFunc k))

/-- The line through a Kummer parameter, as an intermediate field of `M` over the original
line. -/
def kummerBase : IntermediateField (RatFunc k) M :=
  Chart.base (paramHom u hu) (algebraMap_mem_paramHom_fieldRange hu hpow)

omit [NeZero m] in
theorem param_mem_kummerBase : u ∈ kummerBase hu hpow :=
  ⟨RatFunc.X, paramHom_X hu⟩

omit [NeZero m] in
theorem paramHom_mem_kummerBase (f : RatFunc k) : paramHom u hu f ∈ kummerBase hu hpow := ⟨f, rfl⟩

omit [IsScalarTower k (RatFunc k) M] in
include hpow in
/-- The polynomial cut out by the Kummer parameter, read in `M`. -/
theorem map_X_pow_sub_C_eq_prod {ζ₀ : k} (hζ₀ : IsPrimitiveRoot ζ₀ m) :
    ((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map (algebraMap (RatFunc k) M)
      = ∏ i ∈ Finset.range m, (X - C ((algebraMap k M ζ₀) ^ i * u)) := by
  have hζ : IsPrimitiveRoot (algebraMap k M ζ₀) m :=
    hζ₀.map_of_injective (algebraMap k M).injective
  have hmap : ((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
      (algebraMap (RatFunc k) M)
      = (X : M[X]) ^ m - C (algebraMap (RatFunc k) M (RatFunc.X : RatFunc k)) := by
    simp
  rw [hmap]
  exact X_pow_sub_C_eq_prod hζ (NeZero.pos m) hpow

/-- **Every `m`-th root of the parameter lies on the Kummer line**: the roots differ by roots of
unity, which are constants. -/
theorem rootSet_subset_kummerBase :
    ((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).rootSet M
      ⊆ (kummerBase hu hpow : Set M) := by
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k m
  intro v hv
  rw [mem_rootSet'] at hv
  obtain ⟨-, hzero⟩ := hv
  have hprod := map_X_pow_sub_C_eq_prod (u := u) hpow hζ₀
  rw [aeval_def, eval₂_eq_eval_map, hprod, eval_prod] at hzero
  obtain ⟨i, _, hi⟩ := Finset.prod_eq_zero_iff.mp hzero
  rw [eval_sub, eval_X, eval_C, sub_eq_zero] at hi
  rw [hi]
  refine mul_mem (pow_mem ?_ i) (param_mem_kummerBase hu hpow)
  exact ⟨algebraMap k (RatFunc k) ζ₀, by rw [paramHom_const]⟩

include hpow in
/-- **The Kummer line is the splitting field of `Xᵐ - T` inside `M`.** -/
theorem kummerBase_eq_adjoin_rootSet :
    kummerBase hu hpow = IntermediateField.adjoin (RatFunc k)
      (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).rootSet M) := by
  refine le_antisymm ?_ (IntermediateField.adjoin_le_iff.mpr (rootSet_subset_kummerBase hu hpow))
  rintro x ⟨f, rfl⟩
  refine ratFunc_mem_subfield (paramHom u hu)
    (IntermediateField.adjoin (RatFunc k)
      (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).rootSet M)).toSubfield ?_ ?_ f
  · intro c
    rw [paramHom_const, IsScalarTower.algebraMap_apply k (RatFunc k) M]
    exact (IntermediateField.adjoin (RatFunc k) _).algebraMap_mem _
  · rw [paramHom_X]
    refine IntermediateField.subset_adjoin _ _ ?_
    rw [mem_rootSet']
    refine ⟨?_, ?_⟩
    · rw [Polynomial.map_sub, Polynomial.map_pow, map_X, map_C]
      exact fun hzero => X_pow_sub_C_ne_zero (NeZero.pos m) _ hzero
    · simp [hpow]

/-- The Kummer line is a splitting field of `Xᵐ - T`. -/
theorem isSplittingField_kummerBase
    (hsplits : (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
      (algebraMap (RatFunc k) M)).Splits) :
    IsSplittingField (RatFunc k) (kummerBase hu hpow)
      ((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)) := by
  rw [kummerBase_eq_adjoin_rootSet hu hpow]
  exact IntermediateField.adjoin_rootSet_isSplittingField hsplits

/-- The Kummer line is a normal extension of the original line. -/
theorem normal_kummerBase
    (hsplits : (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
      (algebraMap (RatFunc k) M)).Splits) :
    Normal (RatFunc k) (kummerBase hu hpow) :=
  haveI := isSplittingField_kummerBase hu hpow hsplits
  Normal.of_isSplittingField ((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k))

/-- A primitive `m`-th root of unity on the line. -/
private theorem primitiveRoots_ratFunc_nonempty : (primitiveRoots m (RatFunc k)).Nonempty := by
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k m
  exact ⟨_, (mem_primitiveRoots (NeZero.pos m)).mpr
    (hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective)⟩

/-- **The Kummer line has degree `m` over the original line.** -/
theorem finrank_kummerBase
    (hsplits : (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
      (algebraMap (RatFunc k) M)).Splits) :
    Module.finrank (RatFunc k) (kummerBase hu hpow) = m :=
  haveI := isSplittingField_kummerBase hu hpow hsplits
  finrank_of_isSplittingField_X_pow_sub_C (primitiveRoots_ratFunc_nonempty (m := m))
    (irreducible_X_pow_sub_C_X k (NeZero.ne m)) _

/-- **The Kummer line has cyclic Galois group over the original line.** -/
theorem isCyclic_kummerBase
    (hsplits : (((X : (RatFunc k)[X]) ^ m - C (RatFunc.X : RatFunc k)).map
      (algebraMap (RatFunc k) M)).Splits) :
    IsCyclic (kummerBase hu hpow ≃ₐ[RatFunc k] kummerBase hu hpow) :=
  haveI := isSplittingField_kummerBase hu hpow hsplits
  isCyclic_of_isSplittingField_X_pow_sub_C (primitiveRoots_ratFunc_nonempty (m := m))
    (irreducible_X_pow_sub_C_X k (NeZero.ne m)) _

end KummerBase

end Rigidity.RET
