/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.EquationCover
import InverseGalois.Rigidity.RET.InertiaGen
import InverseGalois.Hilbert.Analytic.SelmerMorse

/-!
# Transpositions as branch cycles of an equation cover

The cover of the line presented by a monic equation is generated by the roots of the equation, and
its integral model contains them: a root of a monic equation over the coordinate ring of the base is
integral over that ring.  The deck group therefore acts faithfully on a finite set of `deg f` roots
inside the integral model, and this is the permutation representation in which the local structure
of the cover can be computed, because an inertia element at a place fixes every element of the
integral model modulo that place — so it can only permute roots *sharing a residue*.

If the fibre of the equation over a point `t` of the line has only one degeneration — one double
point and simple points elsewhere — the residues of the roots collide only once, and an inertia
element at a place over `t` moves at most two roots.  This is the Morse condition of
`Mathlib.RingTheory.Polynomial.Morse`; the file plumbs it into the covers of the line, where it says
that the local monodromy at such a point is a **transposition**: the inertia group at every place
over `t` has order at most two, and at a branch point it has order exactly two and is generated by a
deck transformation acting on the roots as a transposition.

## Main results

* `Rigidity.RET.card_roots_le_ncard_rootSet_add_one` — a polynomial with a single double root and no
  worse degeneration has at least `deg - 1` distinct roots.
* `Rigidity.RET.splits_map_bring` — the equation splits already in the integral model of a cover
  splitting it.
* `Rigidity.RET.toPermHom_injective` — the deck group of a cover splitting the equation acts
  faithfully on the roots inside the integral model.
* `Rigidity.RET.ncard_rootSet_le_of_fibre` — the Morse condition at a place over `t`, read off the
  fibre of the equation over `t`.
* `Rigidity.RET.card_geomInertia_le_two_of_ncard_le` — under the Morse condition the inertia group
  at a place over `t` has order at most two.
* `Rigidity.RET.isInertiaGen_and_orderOf` — a nontrivial inertia element at such a place has order
  two and generates the inertia group, and `Rigidity.RET.isSwap_of_mem_geomInertia` — it acts on the
  roots as a transposition.
-/

open Polynomial

noncomputable section

namespace Rigidity.RET

open GeomAKLB

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

/-! ### Counting the distinct roots of a polynomial with one double root -/

/-- **A polynomial whose only degeneration is one double root has at least `deg - 1` distinct
roots.**

Every root other than the distinguished one is simple, because a multiple root is a common root of
the polynomial and of its derivative; the distinguished one has multiplicity at most two, because a
triple root is a root of the second derivative as well.  Summing the multiplicities over the
distinct roots then exceeds their number by at most one. -/
theorem card_roots_le_ncard_rootSet_add_one {F : Type*} [Field F] [CharZero F]
    {p : Polynomial F} (hp : p ≠ 0) (a : F)
    (hone : ∀ x, p.IsRoot x → (derivative p).IsRoot x → x = a)
    (htwo : ¬ (derivative (derivative p)).IsRoot a) :
    Multiset.card p.roots ≤ (p.rootSet F).ncard + 1 := by
  classical
  have hset : (p.rootSet F).ncard = p.roots.toFinset.card := by
    rw [Polynomial.rootSet_def, Polynomial.aroots_def, Algebra.algebraMap_self, Polynomial.map_id,
      Set.ncard_coe_finset]
  rw [hset]
  have hmulta : p.rootMultiplicity a ≤ 2 := by
    by_contra hcon
    push_neg at hcon
    exact htwo ((Polynomial.lt_rootMultiplicity_iff_isRoot_iterate_derivative (n := 2) hp).mp
      hcon 2 le_rfl)
  have hmult : ∀ x ∈ p.roots.toFinset,
      p.rootMultiplicity x ≤ 1 + (if x = a then 1 else 0) := by
    intro x _
    by_cases hxa : x = a
    · subst hxa; simpa using hmulta
    · simp only [hxa, if_false, add_zero]
      by_contra hcon
      push_neg at hcon
      have h := (Polynomial.one_lt_rootMultiplicity_iff_isRoot hp).mp hcon
      exact hxa (hone x h.1 h.2)
  have hcount : Multiset.card p.roots = ∑ x ∈ p.roots.toFinset, p.rootMultiplicity x := by
    rw [← Multiset.toFinset_sum_count_eq]
    exact Finset.sum_congr rfl fun x _ => Polynomial.count_roots p
  have hsum : ∑ x ∈ p.roots.toFinset, (1 + if x = a then 1 else 0)
      ≤ p.roots.toFinset.card + 1 := by
    have h : ∑ x ∈ p.roots.toFinset, (1 + if x = a then 1 else 0)
        = p.roots.toFinset.card + (if a ∈ p.roots.toFinset then 1 else 0) := by
      rw [Finset.sum_add_distrib, Finset.sum_const, smul_eq_mul, mul_one, Finset.sum_ite_eq']
    rw [h]
    split_ifs <;> simp
  exact hcount.trans_le ((Finset.sum_le_sum hmult).trans hsum)

/-! ### The equation splits in the integral model -/

variable (L : LineCover) (f : Polynomial (Polynomial k))

/-- The deck group commutes with the coordinate ring of the base on the integral model: it acts by
algebra automorphisms over the function field of the base. -/
local instance instSMulCommDeck : SMulCommClass L.deck (Polynomial k) (Bring L.M) :=
  IsGaloisGroup.commutes (G := L.deck) (A := Polynomial k) (B := Bring L.M)

/-- **A root of the generic fibre lies in the integral model**, where it is a root of the equation
itself: a root of a monic equation is integral over the ring the coefficients live in. -/
theorem mem_rootSet_bring (hf : f.Monic) {x : L.M} (hx : x ∈ (genericPoly f).rootSet L.M) :
    ∃ b : Bring L.M, (b : L.M) = x ∧ b ∈ f.rootSet (Bring L.M) := by
  have haeval : (Polynomial.aeval x) f = 0 := L.aeval_eq_zero_of_mem_rootSet f hx
  have hint : IsIntegral (Polynomial k) x := ⟨f, hf, by rwa [← Polynomial.aeval_def]⟩
  have key := Polynomial.aeval_algHom_apply
    (Subalgebra.val (integralClosure (Polynomial k) L.M)) (⟨x, hint⟩ : Bring L.M) f
  simp only [Subalgebra.coe_val] at key
  refine ⟨⟨x, hint⟩, rfl, ?_⟩
  rw [Polynomial.mem_rootSet']
  refine ⟨(hf.map (algebraMap (Polynomial k) (Bring L.M))).ne_zero, ?_⟩
  have hz : ((Polynomial.aeval (⟨x, hint⟩ : Bring L.M)) f : L.M) = 0 := by
    rw [← key, haeval]
  rw [Polynomial.aeval_def, ← Polynomial.eval_map] at hz ⊢
  exact Subtype.ext (by simpa using hz)

/-- **A cover splitting a monic equation splits it already in its integral model.**  The roots of a
monic equation over the coordinate ring of the base are integral over that ring, so the linear
factors of the equation have their coefficients in the integral model. -/
theorem splits_map_bring (hf : f.Monic)
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] :
    (f.map (algebraMap (Polynomial k) (Bring L.M))).Splits := by
  have hmap : (f.map (algebraMap (Polynomial k) (Bring L.M))).map
      (algebraMap (Bring L.M) L.M) = f.map (algebraMap (Polynomial k) L.M) := by
    rw [Polynomial.map_map, ← IsScalarTower.algebraMap_eq]
  have hgen : f.map (algebraMap (Polynomial k) L.M)
      = (genericPoly f).map (algebraMap (RatFunc k) L.M) := by
    rw [genericPoly, Polynomial.map_map, ← IsScalarTower.algebraMap_eq]
  refine Polynomial.Splits.of_splits_map_of_injective
    (IsIntegralClosure.algebraMap_injective (Bring L.M) (Polynomial k) L.M) ?_ ?_
  · rw [hmap, hgen]
    exact Polynomial.IsSplittingField.splits L.M (genericPoly f)
  · intro a ha
    rw [hmap] at ha
    have haroot : (Polynomial.aeval a) f = 0 := by
      have h := Polynomial.isRoot_of_mem_roots ha
      rwa [Polynomial.IsRoot, Polynomial.eval_map, ← Polynomial.aeval_def] at h
    exact ⟨⟨a, ⟨f, hf, by rwa [← Polynomial.aeval_def]⟩⟩, rfl⟩

/-! ### The permutation representation on the roots in the integral model -/

/-- **The deck group of a cover splitting the equation acts faithfully on the roots of the equation
in the integral model.**  Every root of the generic fibre is integral, hence lies in the integral
model, and the cover is generated by those roots. -/
theorem toPermHom_injective (hf : f.Monic)
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] :
    Function.Injective (MulAction.toPermHom L.deck (f.rootSet (Bring L.M))) := by
  rw [injective_iff_map_eq_one]
  intro σ hσ
  have hfix : ∀ x ∈ (genericPoly f).rootSet L.M, σ x = x := by
    intro x hx
    obtain ⟨b, hbx, hbmem⟩ := mem_rootSet_bring L f hf hx
    have h := congrArg (fun π : Equiv.Perm (f.rootSet (Bring L.M)) => π ⟨b, hbmem⟩) hσ
    simp only [MulAction.toPermHom_apply, MulAction.toPerm_apply, Equiv.Perm.coe_one,
      id_eq] at h
    have hb : σ • b = b := congrArg Subtype.val h
    rw [← hbx, ← coe_smul_geom (Ω := L.M) σ b, hb]
  have htop : (σ : L.M →ₐ[RatFunc k] L.M) = AlgHom.id (RatFunc k) L.M :=
    AlgHom.ext_of_adjoin_eq_top
      (Polynomial.IsSplittingField.adjoin_rootSet L.M (genericPoly f)) fun x hx => hfix x hx
  refine AlgEquiv.ext fun x => ?_
  simpa using AlgHom.congr_fun htop x

/-! ### The Morse condition from the fibre over a point -/

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- Reduction of the coordinate ring of the base at a place of the cover over `t` factors through
evaluation at `t`: the coordinate is congruent to `t` there. -/
theorem algebraMap_quotient_eq_comp (t : k) (Q : Ideal (Bring L.M)) [Q.LiesOver (placeP t)] :
    (algebraMap (Polynomial k) (Bring L.M ⧸ Q))
      = ((algebraMap (Polynomial k) (Bring L.M ⧸ Q)).comp Polynomial.C).comp (evalRingHom t) := by
  haveI : IsScalarTower (Polynomial k) (Bring L.M) (Bring L.M ⧸ Q) := inferInstance
  refine RingHom.ext fun p => ?_
  obtain ⟨q, hq⟩ : (X - C t : Polynomial k) ∣ p - C (p.eval t) :=
    Polynomial.X_sub_C_dvd_sub_C_eval
  have hmem : (X - C t : Polynomial k) ∈ placeP t := Ideal.mem_span_singleton_self _
  have hover : placeP t = Q.comap (algebraMap (Polynomial k) (Bring L.M)) := Ideal.LiesOver.over
  have hXQ : algebraMap (Polynomial k) (Bring L.M) (X - C t) ∈ Q := by
    rw [hover, Ideal.mem_comap] at hmem; exact hmem
  have hzero : algebraMap (Polynomial k) (Bring L.M ⧸ Q) (X - C t) = 0 := by
    rw [IsScalarTower.algebraMap_apply (Polynomial k) (Bring L.M) (Bring L.M ⧸ Q)]
    exact (Ideal.Quotient.eq_zero_iff_mem).mpr hXQ
  have hsub : algebraMap (Polynomial k) (Bring L.M ⧸ Q) (p - C (p.eval t)) = 0 := by
    rw [hq, map_mul, hzero, zero_mul]
  simp only [RingHom.coe_comp, Function.comp_apply, coe_evalRingHom]
  rw [map_sub, sub_eq_zero] at hsub
  exact hsub

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- **The Morse condition at a place over `t`, read off the fibre of the equation over `t`.**

If the fibre polynomial has a single degeneration — one double root, every other root simple — then
the roots of the equation in the integral model collide at most once modulo any place over `t`. -/
theorem ncard_rootSet_le_of_fibre (hf : f.Monic) (t : k) (Q : Ideal (Bring L.M)) [Q.IsMaximal]
    [Q.LiesOver (placeP t)] (a : k)
    (hone : ∀ x : k, (f.map (evalRingHom t)).IsRoot x →
      (derivative (f.map (evalRingHom t))).IsRoot x → x = a)
    (htwo : ¬ (derivative (derivative (f.map (evalRingHom t)))).IsRoot a) :
    (f.rootSet (Bring L.M)).ncard ≤ (f.rootSet (Bring L.M ⧸ Q)).ncard + 1 := by
  classical
  haveI : IsScalarTower (Polynomial k) (Bring L.M) (Bring L.M ⧸ Q) := inferInstance
  haveI : CharZero (Bring L.M ⧸ Q) := charZero_residue_top L.M t Q
  set D := Bring L.M ⧸ Q with hD
  set φ : k →+* D := (algebraMap (Polynomial k) D).comp Polynomial.C with hφ
  set fib : Polynomial k := f.map (evalRingHom t) with hfib
  have hfibmonic : fib.Monic := hf.map _
  have hmapD : f.map (algebraMap (Polynomial k) D) = fib.map φ := by
    rw [hfib, Polynomial.map_map, ← algebraMap_quotient_eq_comp L t Q]
  have hφinj : Function.Injective φ := φ.injective
  have hsplit : fib.Splits := IsAlgClosed.splits fib
  have hroots : (fib.map φ).roots = fib.roots.map φ := hsplit.roots_map_of_injective hφinj
  set P : Polynomial D := fib.map φ with hP
  have hPne : P ≠ 0 := (hfibmonic.map φ).ne_zero
  -- the equation has at most as many roots in the integral model as its reduction has, counted
  -- with multiplicity
  have h1 : (f.rootSet (Bring L.M)).ncard ≤ Multiset.card P.roots := by
    have := SelmerMorse.ncard_rootSet_le_roots_card (R := Polynomial k) (S := Bring L.M) (D := D)
      f (by rw [hmapD]; exact hPne)
    rwa [hmapD] at this
  refine h1.trans ?_
  -- the reduction has the same root set as the equation itself, and the degeneration data
  -- transfers along the (injective) inclusion of constants
  have hrootSet : f.rootSet D = P.rootSet D := by
    rw [Polynomial.rootSet_def, Polynomial.rootSet_def, Polynomial.aroots_def,
      Polynomial.aroots_def, hmapD, Algebra.algebraMap_self, Polynomial.map_id]
  rw [hrootSet]
  have hmem : ∀ x : D, P.IsRoot x → ∃ y : k, fib.IsRoot y ∧ φ y = x := by
    intro x hx
    have hxr : x ∈ P.roots := (Polynomial.mem_roots hPne).mpr hx
    rw [hroots] at hxr
    obtain ⟨y, hy, rfl⟩ := Multiset.mem_map.mp hxr
    exact ⟨y, (Polynomial.mem_roots hfibmonic.ne_zero).mp hy, rfl⟩
  have hderiv : ∀ (q : Polynomial k) (y : k), (q.map φ).eval (φ y) = φ (q.eval y) := by
    intro q y
    rw [Polynomial.eval_map, Polynomial.eval₂_at_apply]
  refine card_roots_le_ncard_rootSet_add_one hPne (φ a) ?_ ?_
  · intro x hx hx'
    obtain ⟨y, hy, rfl⟩ := hmem x hx
    refine congrArg φ (hone y hy ?_)
    have hd : derivative P = (derivative fib).map φ := by rw [hP, Polynomial.derivative_map]
    have hx2 : ((derivative fib).map φ).eval (φ y) = 0 := by rw [← hd]; exact hx'
    rw [hderiv] at hx2
    exact hφinj (hx2.trans (map_zero φ).symm)
  · intro hcon
    refine htwo ?_
    have hd : derivative (derivative P) = (derivative (derivative fib)).map φ := by
      rw [hP, Polynomial.derivative_map, Polynomial.derivative_map]
    have hc2 : ((derivative (derivative fib)).map φ).eval (φ a) = 0 := by rw [← hd]; exact hcon
    rw [hderiv] at hc2
    exact hφinj (hc2.trans (map_zero φ).symm)

/-! ### Inertia of order two, and transposition branch cycles -/

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- **Under the Morse condition every inertia element at the place is an involution.**  It permutes
the roots of the equation preserving their residues, so with at most one collision it either fixes
them all or exchanges two of them. -/
theorem sq_eq_one_of_mem_geomInertia (hf : f.Monic)
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] (t : k)
    (Q : Ideal (Bring L.M)) [Q.IsMaximal] [Q.LiesOver (placeP t)]
    (hmorse : (f.rootSet (Bring L.M)).ncard ≤ (f.rootSet (Bring L.M ⧸ Q)).ncard + 1)
    {σ : L.deck} (hσ : σ ∈ geomInertia L.M Q) : σ * σ = 1 := by
  classical
  haveI : Q.IsPrime := ‹Q.IsMaximal›.isPrime
  refine toPermHom_injective L f hf ?_
  rw [map_mul, map_one]
  rcases (splits_map_bring L f hf).toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia
    Q hmorse σ hσ with h | h
  · rw [h, one_mul]
  · obtain ⟨x, y, _, hxy⟩ := h
    rw [hxy, Equiv.swap_mul_self]

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- **Under the Morse condition the inertia group at a place has order at most two.**  The geometric
inertia groups are cyclic, and a cyclic group of exponent two has order at most two. -/
theorem card_geomInertia_le_two_of_ncard_le (hf : f.Monic)
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] (t : k)
    (Q : Ideal (Bring L.M)) [Q.IsMaximal] [Q.LiesOver (placeP t)]
    (hmorse : (f.rootSet (Bring L.M)).ncard ≤ (f.rootSet (Bring L.M ⧸ Q)).ncard + 1) :
    Nat.card (geomInertia L.M Q) ≤ 2 := by
  classical
  haveI : Q.IsPrime := ‹Q.IsMaximal›.isPrime
  have hsq : ∀ σ ∈ geomInertia L.M Q, σ * σ = 1 := fun σ hσ =>
    sq_eq_one_of_mem_geomInertia L f hf t Q hmorse hσ
  obtain ⟨g, hg⟩ := (isCyclic_geomInertia L.M t Q).exists_generator
  have htop : Subgroup.zpowers g = ⊤ := (Subgroup.eq_top_iff' _).mpr hg
  have hcard : Nat.card (geomInertia L.M Q) = orderOf g := by
    rw [← Nat.card_zpowers g, htop, Subgroup.card_top]
  rw [hcard]
  refine Nat.le_of_dvd two_pos (orderOf_dvd_of_pow_eq_one ?_)
  have h := hsq (g : L.deck) g.2
  rw [pow_two]
  exact Subtype.ext (by simpa using h)

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- **A nontrivial inertia element at a Morse place has order two and generates the inertia
group.** -/
theorem isInertiaGen_and_orderOf (hf : f.Monic)
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] (t : k)
    (Q : Ideal (Bring L.M)) [Q.IsMaximal] [Q.LiesOver (placeP t)]
    (hmorse : (f.rootSet (Bring L.M)).ncard ≤ (f.rootSet (Bring L.M ⧸ Q)).ncard + 1)
    {σ : L.deck} (hσ : σ ∈ geomInertia L.M Q) (hne : σ ≠ 1) :
    geomInertia L.M Q = Subgroup.zpowers σ ∧ orderOf σ = 2 := by
  have hord : orderOf σ = 2 := by
    have hdvd : orderOf σ ∣ 2 := orderOf_dvd_of_pow_eq_one
      (by rw [pow_two]; exact sq_eq_one_of_mem_geomInertia L f hf t Q hmorse hσ)
    rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
    · exact absurd (orderOf_eq_one_iff.mp h) hne
    · exact h
  refine ⟨(Subgroup.eq_of_le_of_card_le' (Subgroup.zpowers_le.mpr hσ) ?_).symm, hord⟩
  refine le_trans (card_geomInertia_le_two_of_ncard_le L f hf t Q hmorse) ?_
  exact le_of_eq (by rw [Nat.card_zpowers, hord])

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- **A nontrivial inertia element at a Morse place acts on the roots as a transposition.** -/
theorem isSwap_of_mem_geomInertia (hf : f.Monic) [DecidableEq (f.rootSet (Bring L.M))]
    [Polynomial.IsSplittingField (RatFunc k) L.M (genericPoly f)] (t : k)
    (Q : Ideal (Bring L.M)) [Q.IsMaximal] [Q.LiesOver (placeP t)]
    (hmorse : (f.rootSet (Bring L.M)).ncard ≤ (f.rootSet (Bring L.M ⧸ Q)).ncard + 1)
    {σ : L.deck} (hσ : σ ∈ geomInertia L.M Q) (hne : σ ≠ 1) :
    (MulAction.toPermHom L.deck (f.rootSet (Bring L.M)) σ).IsSwap := by
  classical
  haveI : Q.IsPrime := ‹Q.IsMaximal›.isPrime
  refine ((splits_map_bring L f hf).toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia
    Q hmorse σ hσ).resolve_left fun h => hne ?_
  exact toPermHom_injective L f hf (by rw [h, map_one])

end Rigidity.RET

end
