/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.DeckGroups
import InverseGalois.Rigidity.RET.TranslateInfinity

/-!
# Every cover is unramified at infinity in a suitable coordinate

Unramifiedness at the point at infinity has been a hypothesis throughout, and it is not one: the
branch locus of a cover is finite while the line has infinitely many points, so some point of the
affine line is not a branch point, and moving it to infinity — translate it to the origin, then
invert the coordinate — produces a cover with the same deck group which is unramified there.

The point of the coordinate move is that it costs nothing: the twisted cover is the same field with
the base acting through the coordinate change, so its deck group is the deck group of the original.
Every finite group that is a deck group at all is therefore a deck group over a finite set of
points in the sense of `Rigidity.RET.IsDeckGroupOver`.

The move costs at most one branch point — the origin of the new coordinate, where the old point at
infinity has gone — so the counting theorems survive it, one generator weaker: an abelian or
nilpotent deck group of an arbitrary cover is generated by as many elements as the cover has branch
points on the affine line, with no hypothesis at infinity at all.

## Main results

* `Rigidity.RET.LineCover.twistInvInv` — inverting the coordinate twice returns the cover.
* `Rigidity.RET.LineCover.exists_twist_isUnramifiedAtInfinity_ncard` — every cover is isomorphic,
  as a cover read in another coordinate, to one unramified at infinity with at most one more
  branch point.
* `Rigidity.RET.exists_finite_isDeckGroupOver` — every deck group occurs over a finite set of
  points.
* `Rigidity.RET.exists_generating_of_comm_ncard`,
  `Rigidity.RET.exists_generating_of_isNilpotent_ncard` — the deck group is generated by as many
  elements as the cover has branch points.
* `Rigidity.RET.IsAffineDeckGroup` — the class of finite groups occurring with a bounded number of
  branch points on the affine line, closed under quotients.
* `Rigidity.RET.isAffineDeckGroup_zero_iff`, `Rigidity.RET.isAffineDeckGroup_one_iff` — with no
  affine branch point only the trivial group occurs, and with one exactly the cyclic groups.
* `Rigidity.RET.isAffineDeckGroup_iff_exists_generating_of_comm` — a finite abelian group occurs
  with `n` affine branch points exactly when it is generated by `n` elements.
* `Rigidity.RET.IsAffineDeckGroup.exists_generating_abelianization` — for an arbitrary group, the
  abelianization is generated by as many elements as there are affine branch points.
* `Rigidity.RET.IsDeckGroupOver.isAffineDeckGroup` — a group occurring over a prescribed finite
  branch locus occurs with that many branch points on the affine line.
* `Rigidity.RET.not_isAffineDeckGroup_of_abelianization`,
  `Rigidity.RET.le_ncard_branchLocus_of_abelianization` — a group whose abelianization needs many
  generators needs as many branch points, with no hypothesis on the group.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] GeomAKLB.instMSA GeomAKLB.instIntegral GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instDedekindB GeomAKLB.instTorsionFree
  GeomAKLB.instFaithful

/-- Inverting the parameter twice returns it. -/
theorem invSubst_invSubst (f : RatFunc k) : invSubst (invSubst f) = f :=
  invSubst.symm_apply_apply f

/-! ### Counting points under the coordinate moves -/

/-- Translating a set of points is the same as taking a preimage under the opposite translation. -/
theorem sub_preimage_eq_image (a : k) (S : Set k) : (· - a) ⁻¹' S = (· + a) '' S := by
  ext t
  constructor
  · intro ht
    exact ⟨t - a, ht, by ring⟩
  · rintro ⟨s, hs, rfl⟩
    simpa using hs

/-- The nonzero points whose reciprocal lies in a finite set form a finite set. -/
theorem finite_inv_mem {S : Set k} (hS : S.Finite) : {t : k | t ≠ 0 ∧ t⁻¹ ∈ S}.Finite :=
  (hS.image (·⁻¹)).subset fun t ht => ⟨t⁻¹, ht.2, inv_inv t⟩

/-- Taking reciprocals does not increase the number of points. -/
theorem ncard_inv_mem_le {S : Set k} (hS : S.Finite) :
    {t : k | t ≠ 0 ∧ t⁻¹ ∈ S}.ncard ≤ S.ncard :=
  Set.ncard_le_ncard_of_injOn (·⁻¹) (fun _ ht => ht.2) (fun _ _ _ _ hab => inv_injective hab) hS

namespace LineCover

/-- **Inverting the coordinate twice returns the cover.**  The underlying field never changed, and
the base now acts through the inversion applied twice, which is the identity. -/
def twistInvInv (L : LineCover) :
    ((L.twist invSubst.toRingEquiv).twist invSubst.toRingEquiv).M ≃ₐ[RatFunc k] L.M where
  toFun x := x
  invFun x := x
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl
  map_add' _ _ := rfl
  commutes' f := by
    show algebraMap (RatFunc k) L.M (invSubst (invSubst f)) = algebraMap (RatFunc k) L.M f
    rw [invSubst_invSubst]

/-- **A cover with no ramification at a point becomes, in the coordinate inverted about that
point, a cover with no ramification at infinity.** -/
theorem isUnramifiedAtInfinity_twist_inv (L : LineCover)
    (h : L.IsUnramifiedOutside ({(0 : k)}ᶜ)) :
    (L.twist invSubst.toRingEquiv).IsUnramifiedAtInfinity := fun σ hσ =>
  IsUnramifiedOutside.transport L.twistInvInv.symm h 0 (by simp) σ hσ

/-- **Every cover of the line is, in a suitable coordinate, unramified at infinity, and the
coordinate move costs at most one branch point.**  A point which is not a branch point is
translated to the origin and the coordinate inverted; the deck group is unchanged, since the
twisted cover is the same field.  Translation permutes the branch points, and inversion carries
them to their reciprocals, with only the origin possibly becoming a new branch point — it is the
image of the old point at infinity. -/
theorem exists_twist_isUnramifiedAtInfinity_ncard (L : LineCover) :
    ∃ N : LineCover, Nonempty (N.deck ≃* L.deck) ∧ N.IsUnramifiedAtInfinity ∧
      N.branchLocus.ncard ≤ L.branchLocus.ncard + 1 := by
  obtain ⟨a, ha⟩ := (L.finite_branchLocus.infinite_compl).nonempty
  have hL : L.IsUnramifiedOutside ({a}ᶜ) :=
    (L.isUnramifiedOutside_iff_branchLocus_subset _).mpr fun u hu hu' => ha (hu' ▸ hu)
  have hT : (L.twist (translateSubst (-a))).IsUnramifiedOutside ({(0 : k)}ᶜ) := by
    have := IsUnramifiedOutside.twist_translate (-a) hL
    refine this.mono ?_
    intro u hu hu0
    exact hu (by rw [hu0]; simp)
  refine ⟨(L.twist (translateSubst (-a))).twist invSubst.toRingEquiv,
    ⟨((Twist.autEquiv (φ := translateSubst (-a)) (M := L.M)).trans
      (Twist.autEquiv (φ := invSubst.toRingEquiv)
        (M := (L.twist (translateSubst (-a))).M))).symm⟩,
    isUnramifiedAtInfinity_twist_inv _ hT, ?_⟩
  set P := L.twist (translateSubst (-a)) with hPdef
  have hPle : P.branchLocus.ncard ≤ L.branchLocus.ncard := by
    have hsub := (P.isUnramifiedOutside_iff_branchLocus_subset _).mp
      (IsUnramifiedOutside.twist_translate (-a) L.isUnramifiedOutside_branchLocus)
    have hfin : ((· - (-a)) ⁻¹' L.branchLocus).Finite := by
      rw [sub_preimage_eq_image]; exact L.finite_branchLocus.image _
    calc P.branchLocus.ncard ≤ ((· - (-a)) ⁻¹' L.branchLocus).ncard := Set.ncard_le_ncard hsub hfin
      _ = L.branchLocus.ncard := by
          rw [sub_preimage_eq_image, Set.ncard_image_of_injective _ (add_left_injective (-a))]
  have hinvfin : {t : k | t ≠ 0 ∧ t⁻¹ ∈ P.branchLocus}.Finite :=
    finite_inv_mem P.finite_branchLocus
  have hsubN := ((P.twist invSubst.toRingEquiv).isUnramifiedOutside_iff_branchLocus_subset _).mp
    (isUnramifiedOutside_twist_inv_ne_zero P P.isUnramifiedOutside_branchLocus)
  calc (P.twist invSubst.toRingEquiv).branchLocus.ncard
      ≤ ({(0 : k)} ∪ {t : k | t ≠ 0 ∧ t⁻¹ ∈ P.branchLocus}).ncard :=
        Set.ncard_le_ncard hsubN ((Set.finite_singleton _).union hinvfin)
    _ ≤ ({(0 : k)} : Set k).ncard + {t : k | t ≠ 0 ∧ t⁻¹ ∈ P.branchLocus}.ncard :=
        Set.ncard_union_le _ _
    _ ≤ 1 + L.branchLocus.ncard := by
        rw [Set.ncard_singleton]
        exact Nat.add_le_add_left ((ncard_inv_mem_le P.finite_branchLocus).trans hPle) 1
    _ = L.branchLocus.ncard + 1 := Nat.add_comm _ _

/-- **Every cover of the line is, in a suitable coordinate, unramified at infinity.** -/
theorem exists_twist_isUnramifiedAtInfinity (L : LineCover) :
    ∃ N : LineCover, Nonempty (N.deck ≃* L.deck) ∧ N.IsUnramifiedAtInfinity := by
  obtain ⟨N, e, hinf, -⟩ := L.exists_twist_isUnramifiedAtInfinity_ncard
  exact ⟨N, e, hinf⟩

end LineCover

/-- **Every deck group of a cover of the line occurs over a finite set of points.**  The branch
locus is finite, and unramifiedness at infinity can always be arranged by a coordinate move. -/
theorem exists_finite_isDeckGroupOver (L : LineCover) :
    ∃ S : Set k, S.Finite ∧ IsDeckGroupOver S L.deck := by
  obtain ⟨N, ⟨e⟩, hinf⟩ := L.exists_twist_isUnramifiedAtInfinity
  exact ⟨N.branchLocus, N.finite_branchLocus, N, ⟨e⟩, N.isUnramifiedOutside_branchLocus, hinf⟩

/-! ### Counting without a hypothesis at infinity -/

/-- **A cover of the line with abelian deck group has deck group generated by as many elements as
it has branch points.**  Nothing is assumed at infinity: the coordinate move which arranges
unramifiedness there adds at most one branch point, which is exactly the generator that the bound
over a prescribed branch locus saves. -/
theorem exists_generating_of_comm_ncard (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a) :
    ∃ s : Fin L.branchLocus.ncard → L.deck, Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨N, ⟨e⟩, hinf, hle⟩ := L.exists_twist_isUnramifiedAtInfinity_ncard
  have habN : ∀ a b : N.deck, a * b = b * a := fun a b =>
    e.injective (by rw [map_mul, map_mul, hab])
  have hcard : N.finite_branchLocus.toFinset.card ≤ L.branchLocus.ncard + 1 := by
    rwa [← Set.ncard_eq_toFinset_card _ N.finite_branchLocus]
  obtain ⟨s, hs⟩ := exists_generating_of_comm_of_card_le N habN hinf hcard
  exact ⟨fun i => e (s i), closure_range_mulEquiv_eq_top e hs⟩

/-- **A cover of the line with nilpotent deck group has deck group generated by as many elements as
it has branch points**, again with nothing assumed at infinity. -/
theorem exists_generating_of_isNilpotent_ncard (L : LineCover) [Group.IsNilpotent L.deck] :
    ∃ s : Fin L.branchLocus.ncard → L.deck, Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨N, ⟨e⟩, hinf, hle⟩ := L.exists_twist_isUnramifiedAtInfinity_ncard
  haveI : Group.IsNilpotent N.deck :=
    (Group.isNilpotent_congr e.symm).mp inferInstance
  have hcard : N.finite_branchLocus.toFinset.card ≤ L.branchLocus.ncard + 1 := by
    rwa [← Set.ncard_eq_toFinset_card _ N.finite_branchLocus]
  obtain ⟨s, hs⟩ := exists_generating_of_isNilpotent_of_card_le N hinf hcard
  exact ⟨fun i => e (s i), closure_range_mulEquiv_eq_top e hs⟩

/-- **A cover of the affine line branched over at most one point has cyclic deck group.**  No
hypothesis at infinity is needed, and none can be dropped further: the coordinate move turns the
one branch point and the point at infinity into two branch points of a cover unramified at
infinity, which is the two-point classification. -/
theorem isCyclic_deck_of_ncard_branchLocus_le_one (L : LineCover)
    (hcard : L.branchLocus.ncard ≤ 1) : IsCyclic L.deck := by
  obtain ⟨N, ⟨e⟩, hinf, hle⟩ := L.exists_twist_isUnramifiedAtInfinity_ncard
  have hcardN : N.finite_branchLocus.toFinset.card ≤ 2 := by
    rw [← Set.ncard_eq_toFinset_card _ N.finite_branchLocus]; omega
  obtain ⟨t, -, hsub⟩ := exists_range_superset_of_card_le N.finite_branchLocus hcardN
  haveI := LineCover.isCyclic_deck_of_unramifiedOutside_range_two N t
    (N.isUnramifiedOutside_branchLocus.mono hsub) hinf
  exact isCyclic_of_surjective (e : N.deck →* L.deck) e.surjective

/-! ### The groups occurring with a bounded number of affine branch points -/

/-- **A finite group occurs with `n` affine branch points** when it is the deck group of a cover of
the line whose branch locus on the affine line has at most `n` points.  Nothing is asked at
infinity, which is what distinguishes this from `Rigidity.RET.IsDeckGroupOver`: the points are
counted, not prescribed, and the point at infinity is not among them. -/
def IsAffineDeckGroup (n : ℕ) (G : Type) [Group G] [Finite G] : Prop :=
  ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.branchLocus.ncard ≤ n

/-- Allowing more branch points allows more groups. -/
theorem IsAffineDeckGroup.mono {m n : ℕ} (hmn : m ≤ n) {G : Type} [Group G] [Finite G]
    (h : IsAffineDeckGroup m G) : IsAffineDeckGroup n G := by
  obtain ⟨L, e, hle⟩ := h
  exact ⟨L, e, hle.trans hmn⟩

/-- Occurring with a bounded number of branch points depends only on the isomorphism type. -/
theorem IsAffineDeckGroup.congr {n : ℕ} {G H : Type} [Group G] [Finite G] [Group H] [Finite H]
    (h : IsAffineDeckGroup n G) (φ : G ≃* H) : IsAffineDeckGroup n H := by
  obtain ⟨L, ⟨e⟩, hle⟩ := h
  exact ⟨L, ⟨e.trans φ⟩, hle⟩

/-- Every cover exhibits its own deck group. -/
theorem isAffineDeckGroup_deck (L : LineCover) : IsAffineDeckGroup L.branchLocus.ncard L.deck :=
  ⟨L, ⟨MulEquiv.refl _⟩, le_rfl⟩

/-- **The groups occurring with at most `n` affine branch points are closed under quotients.**  The
subcover cutting out a normal subgroup branches only where the cover does. -/
theorem IsAffineDeckGroup.quotient {n : ℕ} {G : Type} [Group G] [Finite G]
    (h : IsAffineDeckGroup n G) (N : Subgroup G) [N.Normal] : IsAffineDeckGroup n (G ⧸ N) := by
  obtain ⟨L, ⟨e⟩, hle⟩ := h
  obtain ⟨E, hE, ⟨eq⟩⟩ := L.exists_sub_mulEquiv_quotient (N.comap (e : L.deck →* G))
  haveI := hE
  refine ⟨L.sub E, ⟨eq.trans (QuotientGroup.congr _ N e
    (Subgroup.map_comap_eq_self_of_surjective e.surjective N))⟩, le_trans ?_ hle⟩
  exact Set.ncard_le_ncard (L.branchLocus_sub_subset E) L.finite_branchLocus

/-- **Only the trivial group occurs with no affine branch point at all** — the affine line is
simply connected, and ramification at infinity alone cannot produce a cover. -/
theorem isAffineDeckGroup_zero_iff {G : Type} [Group G] [Finite G] :
    IsAffineDeckGroup 0 G ↔ Subsingleton G := by
  constructor
  · rintro ⟨L, ⟨e⟩, hle⟩
    haveI : Subsingleton L.deck :=
      L.branchLocus_eq_empty_iff.mp
        ((Set.ncard_eq_zero L.finite_branchLocus).mp (Nat.le_zero.mp hle))
    exact e.surjective.subsingleton
  · intro h
    refine ⟨trivialCover, ⟨mulEquivOfSubsingleton⟩, ?_⟩
    rw [trivialCover.branchLocus_eq_empty_iff.mpr inferInstance]
    simp

/-- **Every finite cyclic group is the deck group of a cover of the line with a single branch point
on the affine line.**  Take the two-point Kummer cover with branch cycles `g` and `g⁻¹` over `0`
and `1`, and invert the coordinate: the branch point at `0` goes to infinity, where nothing is
claimed, and the one at `1` stays. -/
theorem exists_cover_ncard_branchLocus_le_one_of_isCyclic {G : Type} [Group G] [Finite G]
    [hcyc : IsCyclic G] :
    ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.branchLocus.ncard ≤ 1 := by
  letI : CommGroup G := IsCyclic.commGroup
  obtain ⟨g, hg⟩ := hcyc.exists_generator
  set t : Fin 2 → k := ![0, 1] with htdef
  have htinj : Function.Injective t := by
    intro a b hab
    fin_cases a <;> fin_cases b <;> simp_all [t]
  set h : Fin 2 → G := ![g, g⁻¹] with hhdef
  have hprod : (List.ofFn h).prod = 1 := by simp [h, List.ofFn_succ]
  have htop : Subgroup.closure (Set.range h) = ⊤ := by
    refine eq_top_iff.mpr fun x _ => ?_
    have hgmem : g ∈ Subgroup.closure (Set.range h) := Subgroup.subset_closure ⟨0, by simp [h]⟩
    obtain ⟨n, rfl⟩ := hg x
    exact zpow_mem hgmem n
  obtain ⟨L, e, hout, hinf, -⟩ := exists_cover_of_commGroup t htinj h hprod htop
  refine ⟨L.twist invSubst.toRingEquiv,
    ⟨(Twist.autEquiv (φ := invSubst.toRingEquiv) (M := L.M)).symm.trans e⟩, ?_⟩
  have hss : {u : k | u ≠ 0 ∧ u⁻¹ ∈ Set.range t} ⊆ {(1 : k)} := by
    rintro u ⟨hu0, i, hi⟩
    fin_cases i
    · exact absurd (inv_eq_zero.mp (by simpa [t] using hi.symm)) hu0
    · exact inv_eq_one.mp (by simpa [t] using hi.symm)
  have hsub := ((L.twist invSubst.toRingEquiv).isUnramifiedOutside_iff_branchLocus_subset _).mp
    (LineCover.isUnramifiedOutside_twist_inv L hout hinf)
  calc (L.twist invSubst.toRingEquiv).branchLocus.ncard
      ≤ ({(1 : k)} : Set k).ncard :=
        Set.ncard_le_ncard (hsub.trans hss) (Set.finite_singleton _)
    _ = 1 := Set.ncard_singleton _

/-- **A finite group is the deck group of a cover of the line with at most one branch point on the
affine line exactly when it is cyclic.**  Ramification at infinity is free in both directions, and
it is what makes the statement nonvacuous: over a single point, with infinity unramified as well,
only the trivial group occurs. -/
theorem isCyclic_iff_exists_cover_ncard_branchLocus_le_one {G : Type} [Group G] [Finite G] :
    IsCyclic G ↔ ∃ L : LineCover, Nonempty (L.deck ≃* G) ∧ L.branchLocus.ncard ≤ 1 := by
  refine ⟨fun _ => exists_cover_ncard_branchLocus_le_one_of_isCyclic, ?_⟩
  rintro ⟨L, ⟨e⟩, hle⟩
  haveI := isCyclic_deck_of_ncard_branchLocus_le_one L hle
  exact isCyclic_of_surjective (e : L.deck →* G) e.surjective

/-- **Exactly the cyclic groups occur with one affine branch point.** -/
theorem isAffineDeckGroup_one_iff {G : Type} [Group G] [Finite G] :
    IsAffineDeckGroup 1 G ↔ IsCyclic G :=
  isCyclic_iff_exists_cover_ncard_branchLocus_le_one.symm

/-- **A group occurring over a prescribed finite branch locus occurs with that many affine branch
points.**  The converse fails, and must: the affine count does not see the point at infinity. -/
theorem IsDeckGroupOver.isAffineDeckGroup {S : Set k} (hS : S.Finite) {G : Type} [Group G]
    [Finite G] (h : IsDeckGroupOver S G) : IsAffineDeckGroup hS.toFinset.card G := by
  obtain ⟨L, e, hout, -⟩ := h
  refine ⟨L, e, ?_⟩
  rw [← Set.ncard_eq_toFinset_card _ hS]
  exact Set.ncard_le_ncard ((L.isUnramifiedOutside_iff_branchLocus_subset S).mp hout) hS

/-- Generation is carried along by a surjective homomorphism. -/
theorem closure_range_map_eq_top {G H : Type*} [Group G] [Group H] (f : G →* H)
    (hf : Function.Surjective f) {r : ℕ} {s : Fin r → G}
    (hs : Subgroup.closure (Set.range s) = ⊤) :
    Subgroup.closure (Set.range fun i => f (s i)) = ⊤ := by
  have hrange : (Set.range fun i => f (s i)) = f '' Set.range s := by
    rw [← Set.range_comp]; rfl
  rw [hrange, ← MonoidHom.map_closure, hs, Subgroup.map_top_of_surjective _ hf]

/-- A surjective homomorphism induces a surjection of abelianizations. -/
theorem abelianization_map_surjective {G H : Type*} [Group G] [Group H] {f : G →* H}
    (hf : Function.Surjective f) : Function.Surjective (Abelianization.map f) := by
  intro x
  obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (commutator H) x
  obtain ⟨z, rfl⟩ := hf y
  exact ⟨Abelianization.of z, rfl⟩

/-- **The abelianized deck group of a group occurring with `n` affine branch points is generated by
`n` elements**, with no hypothesis on the group at all. -/
theorem IsAffineDeckGroup.exists_generating_abelianization {n : ℕ} {G : Type} [Group G] [Finite G]
    (h : IsAffineDeckGroup n G) :
    ∃ s : Fin n → Abelianization G, Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨L, ⟨e⟩, hle⟩ := h
  obtain ⟨N, ⟨e'⟩, hinf, hlen⟩ := L.exists_twist_isUnramifiedAtInfinity_ncard
  have hcard : N.finite_branchLocus.toFinset.card ≤ n + 1 := by
    rw [← Set.ncard_eq_toFinset_card _ N.finite_branchLocus]
    omega
  obtain ⟨s, hs⟩ : ∃ s : Fin n → Abelianization N.deck, Subgroup.closure (Set.range s) = ⊤ := by
    rcases hc : N.finite_branchLocus.toFinset.card with _ | m
    · haveI : Subsingleton N.deck :=
        N.branchLocus_eq_empty_iff.mp
          (Set.Finite.toFinset_eq_empty.mp (Finset.card_eq_zero.mp hc))
      refine ⟨fun _ => 1, (Subgroup.eq_top_iff' _).mpr fun x => ?_⟩
      obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (commutator N.deck) x
      rw [Subsingleton.elim y 1, map_one]
      exact one_mem _
    · obtain ⟨s, hs⟩ := exists_generating_abelianization_of_card N hinf hc
      exact exists_generating_of_le (r := n) (by omega) hs
  refine ⟨fun i => Abelianization.map ((e'.trans e).toMonoidHom) (s i), ?_⟩
  exact closure_range_map_eq_top _
    (abelianization_map_surjective (e'.trans e).surjective) hs

/-- **A nilpotent group occurring with `n` affine branch points is generated by `n` elements.**
Only this direction is available beyond the abelian case: realizing a prescribed nilpotent group
needs the correspondence itself. -/
theorem IsAffineDeckGroup.exists_generating_of_isNilpotent {n : ℕ} {G : Type} [Group G] [Finite G]
    [Group.IsNilpotent G] (h : IsAffineDeckGroup n G) :
    ∃ s : Fin n → G, Subgroup.closure (Set.range s) = ⊤ := by
  obtain ⟨L, ⟨e⟩, hle⟩ := h
  haveI : Group.IsNilpotent L.deck := (Group.isNilpotent_congr e).mpr inferInstance
  obtain ⟨s, hs⟩ := exists_generating_of_isNilpotent_ncard L
  obtain ⟨s', hs'⟩ := exists_generating_of_le (r := n) hle hs
  exact ⟨fun i => e (s' i), closure_range_mulEquiv_eq_top e hs'⟩

/-- **A finite abelian group occurs with `n` branch points on the affine line exactly when it is
generated by `n` elements.**  One direction is the counting theorem for an arbitrary cover; the
other takes the Kummer cover over `0, 1, …, n` whose branch cycles are the generators together
with the inverse of their product, and inverts the coordinate, sending the branch point at `0` to
infinity.  This is the cyclic characterization at every rank, and it is sharp. -/
theorem isAffineDeckGroup_iff_exists_generating_of_comm {n : ℕ} {G : Type} [CommGroup G]
    [Finite G] :
    IsAffineDeckGroup n G ↔ ∃ s : Fin n → G, Subgroup.closure (Set.range s) = ⊤ := by
  constructor
  · rintro ⟨L, ⟨e⟩, hle⟩
    have hab : ∀ a b : L.deck, a * b = b * a := fun a b =>
      e.injective (by rw [map_mul, map_mul, mul_comm])
    obtain ⟨s, hs⟩ := exists_generating_of_comm_ncard L hab
    obtain ⟨s', hs'⟩ := exists_generating_of_le (r := n) hle hs
    exact ⟨fun i => e (s' i), closure_range_mulEquiv_eq_top e hs'⟩
  · rintro ⟨s, hs⟩
    set t : Fin (n + 1) → k := fun i => ((i : ℕ) : k) with htdef
    have htinj : Function.Injective t := fun a b hab =>
      Fin.ext (Nat.cast_injective (R := k) hab)
    set h : Fin (n + 1) → G := Fin.snoc s (∏ i, s i)⁻¹ with hhdef
    have hprod : (List.ofFn h).prod = 1 := by
      rw [List.prod_ofFn, Fin.prod_univ_castSucc]
      simp [h]
    have htop : Subgroup.closure (Set.range h) = ⊤ := by
      refine eq_top_iff.mpr ?_
      rw [← hs, Subgroup.closure_le]
      rintro _ ⟨i, rfl⟩
      exact Subgroup.subset_closure ⟨i.castSucc, by simp [h]⟩
    obtain ⟨L, e, hout, hinf, -⟩ := exists_cover_of_commGroup t htinj h hprod htop
    have hzero : (0 : k) ∈ Set.range t := ⟨0, by simp [t]⟩
    have hcard : (Set.range t \ {(0 : k)}).ncard = n := by
      rw [Set.ncard_diff_singleton_of_mem hzero, Set.ncard_range_of_injective htinj]
      simp
    have hS' : {u : k | u ≠ 0 ∧ u⁻¹ ∈ Set.range t}.ncard ≤ n := by
      refine le_of_le_of_eq ?_ hcard
      refine Set.ncard_le_ncard_of_injOn (·⁻¹) ?_ (fun _ _ _ _ hab => inv_injective hab)
        ((Set.finite_range t).diff)
      rintro u ⟨hu0, hu⟩
      exact ⟨hu, by simpa using inv_ne_zero hu0⟩
    refine ⟨L.twist invSubst.toRingEquiv,
      ⟨(Twist.autEquiv (φ := invSubst.toRingEquiv) (M := L.M)).symm.trans e⟩, ?_⟩
    have hsub := ((L.twist invSubst.toRingEquiv).isUnramifiedOutside_iff_branchLocus_subset _).mp
      (LineCover.isUnramifiedOutside_twist_inv L hout hinf)
    exact le_trans (Set.ncard_le_ncard hsub (finite_inv_mem (Set.finite_range t))) hS'

/-- **A cover with abelian deck group has at least as many branch points as its deck group has
generators**, with no hypothesis at infinity.  One branch point is lost relative to
`Rigidity.RET.two_add_le_card_branchLocus_of_comm`, and must be: ramification at infinity is
invisible to the branch locus on the affine line. -/
theorem succ_le_ncard_branchLocus_of_comm (L : LineCover) (hab : ∀ a b : L.deck, a * b = b * a)
    {r : ℕ} (hgen : ∀ s : Fin r → L.deck, Subgroup.closure (Set.range s) ≠ ⊤) :
    r + 1 ≤ L.branchLocus.ncard := by
  by_contra hlt
  push_neg at hlt
  obtain ⟨s, hs⟩ := exists_generating_of_comm_ncard L hab
  obtain ⟨s', hs'⟩ := exists_generating_of_le (r := r) (by omega) hs
  exact hgen s' hs'

/-- **An obstruction with no hypothesis on the group.**  A finite group whose abelianization needs
more than `n` generators does not occur with `n` branch points on the affine line. -/
theorem not_isAffineDeckGroup_of_abelianization {n : ℕ} {G : Type} [Group G] [Finite G]
    (h : ∀ s : Fin n → Abelianization G, Subgroup.closure (Set.range s) ≠ ⊤) :
    ¬ IsAffineDeckGroup n G := fun hG => by
  obtain ⟨s, hs⟩ := hG.exists_generating_abelianization
  exact h s hs

/-- **The same obstruction read on a cover**: a cover whose deck group has an abelianization needing
`r` generators has at least `r` branch points on the affine line. -/
theorem le_ncard_branchLocus_of_abelianization (L : LineCover) {r : ℕ}
    (hgen : ∀ s : Fin r → Abelianization L.deck, Subgroup.closure (Set.range s) ≠ ⊤) :
    r ≤ L.branchLocus.ncard := by
  by_contra hlt
  push_neg at hlt
  obtain ⟨s, hs⟩ := (isAffineDeckGroup_deck L).exists_generating_abelianization
  obtain ⟨s', hs'⟩ := exists_generating_of_le (r := r) (le_of_lt hlt) hs
  exact hgen s' hs'

end Rigidity.RET
