/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.LocalKummer

/-!
# Ramification of the multi-point Kummer cover

For distinct points `t₁, …, t_r` of `ℚ̄` and exponents `a₁, …, a_r`, the cover

`wⁿ = ∏ᵢ (T - tᵢ)^{aᵢ}`

is branched inside `{t₁, …, t_r, ∞}`.  This module computes the branching exactly: the inertia
group at a place above `tⱼ` is the cyclic group generated by the deck transformation
`w ↦ ζ^{aⱼ} w`, of order `n / gcd(n, aⱼ)`; and the cover is unramified at infinity as soon as `n`
divides `∑ᵢ aᵢ`.

The lower bound on inertia at `tⱼ` comes from an element of valuation one.  Write
`d = gcd(n, aⱼ)`, `m = n/d`, `A = aⱼ/d` and let `Y = w^m / (T - tⱼ)^A`; then `Y^d` is the datum
with the factor at `tⱼ` deleted, so `Y` is a unit at `tⱼ`, and Bézout `A·x = m·p + 1` turns
`z = w^x / (T - tⱼ)^p` into an element with `z^m = Y^x · (T - tⱼ)`, forcing the place above `tⱼ`
to occur to the power `m` in the extended place.  The upper bound is the tame-character
computation: an inertia element scales `Y` by a constant, which must be `1`.

## Main definitions

* `Rigidity.RET.multiU` — the multi-point datum with the factor at `tⱼ` deleted.
* `Rigidity.RET.revMultiA` — the multi-point datum read in the coordinate `S = T⁻¹` at infinity.
* `Rigidity.RET.twistRootS` — the Kummer root read in the coordinate at infinity.

## Main results

* `Rigidity.RET.geomInertia_eq_zpowers_multi` — the inertia group at `tⱼ` is generated by the
  deck transformation attached to `aⱼ`.
* `Rigidity.RET.isInertiaGenAt_multiCover` — that deck transformation is therefore a
  distinguished inertia element at `tⱼ`.
* `Rigidity.RET.isUnramifiedAtInfinity_multiCover` — the cover is unramified at infinity when
  `n ∣ ∑ᵢ aᵢ`.
-/

open Polynomial IntermediateField

noncomputable section


namespace Rigidity.RET

open GeomAKLB

/-! ### The auxiliary root at a branch point -/

section Aux

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

variable {r : ℕ}

/-- The multi-point datum with the factor at `t j` removed. -/
def multiU (t : Fin r → k) (a : Fin r → ℕ) (j : Fin r) : Polynomial k :=
  ∏ i ∈ Finset.univ.erase j, (X - C (t i)) ^ a i

theorem multiA_eq_mul (t : Fin r → k) (a : Fin r → ℕ) (j : Fin r) :
    multiA t a = (X - C (t j)) ^ a j * multiU t a j :=
  (Finset.mul_prod_erase _ _ (Finset.mem_univ j)).symm

theorem multiU_eval {t : Fin r → k} (ht : Function.Injective t) (a : Fin r → ℕ) (j : Fin r) :
    (multiU t a j).eval (t j) ≠ 0 := by
  simp only [multiU, eval_prod, eval_pow, eval_sub, eval_X, eval_C]
  exact Finset.prod_ne_zero_iff.mpr fun i hi =>
    pow_ne_zero _ (sub_ne_zero.mpr fun h => (Finset.mem_erase.mp hi).1 (ht h).symm)

variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]
  [Algebra (Polynomial k) Ω] [IsScalarTower (Polynomial k) (RatFunc k) Ω]

omit [FiniteDimensional (RatFunc k) Ω] [IsGalois (RatFunc k) Ω] in
/-- **The auxiliary root at a branch point.**  With `d = gcd(n, aⱼ)`, `m = n/d` and `A = aⱼ/d`,
the element `Y = w^m / (X - tⱼ)^A` is integral, satisfies `Y^d = ∏_{i ≠ j} (X - tᵢ)^{aᵢ}`, and is
therefore a unit at every place above `tⱼ`. -/
theorem exists_multiY {n : ℕ} [NeZero n] {t : Fin r → k} (a : Fin r → ℕ) (j : Fin r)
    (w : Bring Ω) (hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) (multiA t a)) :
    ∃ Y : Bring Ω, Y ^ (Nat.gcd n (a j)) = algebraMap (Polynomial k) (Bring Ω) (multiU t a j) ∧
      Y * (algebraMap (Polynomial k) (Bring Ω) (X - C (t j))) ^ (a j / Nat.gcd n (a j))
        = w ^ (n / Nat.gcd n (a j)) :=
  exists_localKummerY (multiA_eq_mul t a j) w hw

end Aux

/-! ### The upper bound on inertia at a branch point -/

section Upper

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

variable {r : ℕ}
variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]
  [Algebra (Polynomial k) Ω] [IsScalarTower (Polynomial k) (RatFunc k) Ω]

omit [FiniteDimensional (RatFunc k) Ω] in
/-- **The inertia bound at a branch point of the multi-point Kummer cover.**  An inertia element
at a place above `tⱼ` scales the root `w` by `ζ^c` with `gcd(n, aⱼ) ∣ c`. -/
theorem gcd_dvd_of_mem_inertia_multi {n : ℕ} [NeZero n] {t : Fin r → k} {a : Fin r → ℕ}
    (ht : Function.Injective t) (j : Fin r) (w : Bring Ω)
    (hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) (multiA t a))
    (Q : Ideal (Bring Ω)) [hQm : Q.IsMaximal] [Q.LiesOver (placeP (t j))]
    {σ : Ω ≃ₐ[RatFunc k] Ω} (hσ : σ ∈ geomInertia Ω Q)
    {ζ₀ : k} (hζ₀ : IsPrimitiveRoot ζ₀ n) {c : ℕ}
    (hc : σ (w : Ω) = algebraMap (RatFunc k) Ω ((algebraMap k (RatFunc k) ζ₀) ^ c) * (w : Ω)) :
    Nat.gcd n (a j) ∣ c := by
  haveI := hQm.isPrime
  set d : ℕ := Nat.gcd n (a j) with hddef
  have hd0 : 0 < d := Nat.gcd_pos_of_pos_left _ (NeZero.pos n)
  set m : ℕ := n / d with hmdef
  set A : ℕ := a j / d with hAdef
  have hmd : m * d = n := Nat.div_mul_cancel (Nat.gcd_dvd_left n (a j))
  have hm0 : 0 < m := Nat.pos_of_ne_zero fun h => (NeZero.ne n) (by rw [← hmd, h, zero_mul])
  obtain ⟨Y, hYd, hYmul⟩ := exists_multiY (Ω := Ω) a j w hw
  -- `Y` is a unit at the place
  have hYQ : Y ∉ Q := by
    intro hmem
    refine notMem_of_eval_ne_zero (Ω := Ω) (t := t j) (b := multiU t a j) (multiU_eval ht a j) Q ?_
    rw [← hYd]
    exact Ideal.pow_mem_of_mem Q hmem d hd0
  -- the inertia element scales `Y` by the constant `ζ₀^(c*m)`
  set P : Ω := algebraMap (Polynomial k) Ω (X - C (t j)) with hPdef
  have hP0 : P ≠ 0 := by
    rw [hPdef, Ne, map_eq_zero_iff _ algebraMap_poly_injective]
    exact X_sub_C_ne_zero (t j)
  have hfix : σ P = P := by
    rw [hPdef, IsScalarTower.algebraMap_apply (Polynomial k) (RatFunc k) Ω, σ.commutes]
  have hYmulΩ : (Y : Ω) * P ^ A = (w : Ω) ^ m := by
    have := congrArg (fun x : Bring Ω => (x : Ω)) hYmul
    simpa [hPdef] using this
  set z : Ω := algebraMap (RatFunc k) Ω ((algebraMap k (RatFunc k) ζ₀) ^ (c * m)) with hzdef
  have hstep : σ (Y : Ω) * P ^ A = (z * (Y : Ω)) * P ^ A := by
    calc σ (Y : Ω) * P ^ A = σ ((Y : Ω) * P ^ A) := by rw [map_mul, map_pow, hfix]
      _ = σ ((w : Ω) ^ m) := by rw [hYmulΩ]
      _ = (σ (w : Ω)) ^ m := by rw [map_pow]
      _ = z * ((w : Ω) ^ m) := by
          rw [hc, mul_pow, hzdef, ← map_pow, ← pow_mul]
      _ = (z * (Y : Ω)) * P ^ A := by rw [← hYmulΩ]; ring
  have hsmulΩ : σ (Y : Ω) = z * (Y : Ω) := mul_right_cancel₀ (pow_ne_zero _ hP0) hstep
  -- transported to the integral model, this is scaling by a constant
  have hsmul : σ • Y = algebraMap (Polynomial k) (Bring Ω) (C (ζ₀ ^ (c * m))) * Y := by
    apply Subtype.ext
    rw [coe_smul_geom, Submonoid.coe_mul, Subalgebra.coe_algebraMap]
    show σ (Y : Ω) = algebraMap (Polynomial k) Ω (C (ζ₀ ^ (c * m))) * (Y : Ω)
    rw [hsmulΩ]
    congr 1
    rw [hzdef, IsScalarTower.algebraMap_apply (Polynomial k) (RatFunc k) Ω, ← map_pow]
    congr 1
  have hone : ζ₀ ^ (c * m) = 1 := const_eq_one_of_mem_inertia (Ω := Ω) Q hσ hYQ hsmul
  have hdvd : n ∣ c * m := (hζ₀.pow_eq_one_iff_dvd _).mp hone
  rw [← hmd, mul_comm m d] at hdvd
  exact (Nat.mul_dvd_mul_iff_right hm0).mp (by rw [mul_comm c m] at hdvd ⊢; exact hdvd)

end Upper

/-! ### The lower bound on inertia at a branch point -/

section Lower

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

variable {r : ℕ}
variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]
  [Algebra (Polynomial k) Ω] [IsScalarTower (Polynomial k) (RatFunc k) Ω]

omit [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω] [IsGalois (RatFunc k) Ω]
  [IsScalarTower (Polynomial k) (RatFunc k) Ω] in
/-- The auxiliary root at `tⱼ` is a unit at every place above `tⱼ`. -/
theorem multiY_notMem {t : Fin r → k} (ht : Function.Injective t) (a : Fin r → ℕ) (j : Fin r)
    (Q : Ideal (Bring Ω)) [Q.IsMaximal] [Q.LiesOver (placeP (t j))]
    {Y : Bring Ω} {d : ℕ} (hd0 : 0 < d)
    (hYd : Y ^ d = algebraMap (Polynomial k) (Bring Ω) (multiU t a j)) : Y ∉ Q :=
  localKummerY_notMem (multiU_eval ht a j) Q hd0 hYd

/-- **The multi-point Kummer cover is ramified to order `n / gcd(n, aⱼ)` at `tⱼ`.** -/
theorem multi_pow_dvd_map_placeP {n : ℕ} [NeZero n] {t : Fin r → k} {a : Fin r → ℕ}
    (ht : Function.Injective t) (j : Fin r) (w : Bring Ω)
    (hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) (multiA t a))
    (Q : Ideal (Bring Ω)) [hQm : Q.IsMaximal] [Q.LiesOver (placeP (t j))] :
    Q ^ (n / Nat.gcd n (a j)) ∣
      Ideal.map (algebraMap (Polynomial k) (Bring Ω)) (placeP (t j)) :=
  local_pow_dvd_map_placeP (multiA_eq_mul t a j) (multiU_eval ht a j) w hw Q

set_option synthInstance.maxHeartbeats 200000 in
/-- A power of a place dividing the extended place bounds the inertia group below. -/
theorem le_card_geomInertia_of_pow_dvd (t : k) (Q : Ideal (Bring Ω)) [hQm : Q.IsMaximal]
    [Q.LiesOver (placeP t)] {m : ℕ}
    (hdvd : Q ^ m ∣ Ideal.map (algebraMap (Polynomial k) (Bring Ω)) (placeP t)) :
    m ≤ Nat.card (geomInertia Ω Q) := by
  haveI := residue_isSeparable Ω t Q
  have hcard := Ideal.card_inertia_eq_ramificationIdxIn (G := Ω ≃ₐ[RatFunc k] Ω)
    (placeP t) (placeP_ne_bot t) Q
  have hIn : Ideal.ramificationIdxIn (placeP t) (Bring Ω)
      = Ideal.ramificationIdx (algebraMap (Polynomial k) (Bring Ω)) (placeP t) Q :=
    Ideal.ramificationIdxIn_eq_ramificationIdx (placeP t) Q (Ω ≃ₐ[RatFunc k] Ω)
  rw [hcard, hIn]
  exact le_ramificationIdx_of_pow_dvd t Q hdvd

end Lower

/-! ### Group-theoretic and Kummer-theoretic glue -/

section Glue

/-- A subgroup of a subgroup of at most its cardinality is the whole of it. -/
theorem Subgroup.eq_of_le_of_card_le' {G : Type*} [Group G] {H K : Subgroup G} [Finite K]
    (hle : H ≤ K) (hcard : Nat.card K ≤ Nat.card H) : H = K := by
  refine SetLike.coe_injective (Set.eq_of_subset_of_ncard_le hle ?_ (Set.toFinite _))
  simpa using hcard

/-- **The exponent by which a deck transformation scales the Kummer root.** -/
theorem kummer_smul_root_val {K : Type*} [Field K] {n : ℕ} [NeZero n] {b : K}
    (H : Irreducible (X ^ n - C b)) (L : Type*) [Field L] [Algebra K L]
    [IsSplittingField K L (X ^ n - C b)] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (σ : L ≃ₐ[K] L) :
    σ (kummerRoot n b L)
      = algebraMap K L (ζ ^ (((autEquivZmod H L hζ) σ).toAdd.val)) * kummerRoot n b L := by
  set mm : ZMod n := ((autEquivZmod H L hζ) σ).toAdd with hmm
  have hcast : ((mm.val : ℕ) : ZMod n) = mm := by rw [ZMod.natCast_val, ZMod.cast_id]
  have hkey0 := autEquivZmod_symm_apply_natCast H L (kummerRoot_pow (n := n) (a := b) L) hζ mm.val
  rw [hcast] at hkey0
  have hσ : (autEquivZmod H L hζ).symm (Multiplicative.ofAdd mm) = σ := by rw [hmm]; simp
  rw [← hσ, hkey0, Algebra.smul_def, map_pow]

/-- A residue divisible by `gcd(n, b)` is an integer multiple of `b` in `ZMod n`. -/
theorem exists_zsmul_of_gcd_dvd {n b c : ℕ} (h : Nat.gcd n b ∣ c) :
    ∃ z : ℤ, (c : ZMod n) = z • (b : ZMod n) := by
  obtain ⟨e, he⟩ := h
  have hb : ((Nat.gcd n b : ℕ) : ZMod n) = (b : ZMod n) * ((Nat.gcdB n b : ℤ) : ZMod n) := by
    have h1 := Nat.gcd_eq_gcd_ab n b
    have h2 : ((Nat.gcd n b : ℤ) : ZMod n)
        = (((n : ℤ) * Nat.gcdA n b + (b : ℤ) * Nat.gcdB n b : ℤ) : ZMod n) := by rw [← h1]
    push_cast at h2 ⊢
    simpa [ZMod.natCast_self] using h2
  refine ⟨Nat.gcdB n b * e, ?_⟩
  rw [he, zsmul_eq_mul]
  push_cast
  rw [hb]
  ring

end Glue

/-! ### The inertia group at a branch point -/

section Inertia

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

variable {r : ℕ}
variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]
  [Algebra (Polynomial k) Ω] [IsScalarTower (Polynomial k) (RatFunc k) Ω]

/-- **The inertia group at a branch point of the multi-point Kummer cover, exactly.** -/
theorem geomInertia_eq_zpowers_multi {n : ℕ} [NeZero n] {t : Fin r → k} {a : Fin r → ℕ}
    (ht : Function.Injective t)
    (H : Irreducible ((X : (RatFunc k)[X]) ^ n -
      C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))))
    [IsSplittingField (RatFunc k) Ω
      (X ^ n - C (algebraMap (Polynomial k) (RatFunc k) (multiA t a)))]
    {ζ₀ : k} (hζ₀ : IsPrimitiveRoot ζ₀ n)
    (hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n)
    (j : Fin r) (Q : Ideal (Bring Ω)) [Q.IsMaximal] [Q.LiesOver (placeP (t j))] :
    geomInertia Ω Q = Subgroup.zpowers
      ((autEquivZmod H Ω hζ).symm (Multiplicative.ofAdd ((a j : ℕ) : ZMod n))) := by
  set E := autEquivZmod H Ω hζ with hEdef
  set σj := E.symm (Multiplicative.ofAdd ((a j : ℕ) : ZMod n)) with hσjdef
  set w : Bring Ω := kummerRootB Ω n (multiA t a) with hwdef
  have hw : w ^ n = algebraMap (Polynomial k) (Bring Ω) (multiA t a) := kummerRootB_pow
  -- the inertia group is contained in the cyclic group generated by `σⱼ`
  have hle : geomInertia Ω Q ≤ Subgroup.zpowers σj := by
    intro σ hσ
    have hcΩ : σ (w : Ω) = algebraMap (RatFunc k) Ω
        ((algebraMap k (RatFunc k) ζ₀) ^ (((E σ).toAdd).val)) * (w : Ω) :=
      kummer_smul_root_val H Ω hζ σ
    have hdvd : Nat.gcd n (a j) ∣ ((E σ).toAdd).val :=
      gcd_dvd_of_mem_inertia_multi ht j w hw Q hσ hζ₀ hcΩ
    obtain ⟨z, hz⟩ := exists_zsmul_of_gcd_dvd hdvd
    refine ⟨z, ?_⟩
    show σj ^ z = σ
    have h1 : σj ^ z = E.symm (Multiplicative.ofAdd (z • ((a j : ℕ) : ZMod n))) := by
      rw [hσjdef, ← map_zpow, ← ofAdd_zsmul]
    have h2 : (((E σ).toAdd).val : ZMod n) = (E σ).toAdd := by
      rw [ZMod.natCast_val, ZMod.cast_id]
    rw [h1, ← hz, h2]
    simp
  -- and has at least as many elements
  have hord : orderOf σj = n / Nat.gcd n (a j) := by
    have h1 : orderOf σj = orderOf (Multiplicative.ofAdd ((a j : ℕ) : ZMod n)) :=
      orderOf_injective E.symm.toMonoidHom E.symm.injective _
    rw [h1, orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_coe _ (NeZero.ne n)]
  have hcard : n / Nat.gcd n (a j) ≤ Nat.card (geomInertia Ω Q) :=
    le_card_geomInertia_of_pow_dvd (t j) Q (multi_pow_dvd_map_placeP ht j w hw Q)
  exact Subgroup.eq_of_le_of_card_le' hle (by rw [Nat.card_zpowers, hord]; exact hcard)

/-- **The deck transformation attached to `aⱼ` is a distinguished inertia element at `tⱼ`.** -/
theorem isInertiaGenAt_multiCover {n : ℕ} [NeZero n] {t : Fin r → k} {a : Fin r → ℕ}
    (ht : Function.Injective t)
    (H : Irreducible ((X : (RatFunc k)[X]) ^ n -
      C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))))
    (L : LineCover) [IsSplittingField (RatFunc k) L.M
      ((X : (RatFunc k)[X]) ^ n -
        C (algebraMap (Polynomial k) (RatFunc k) (multiA t a)))]
    {ζ₀ : k} (hζ₀ : IsPrimitiveRoot ζ₀ n)
    (hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n) (j : Fin r) :
    L.IsInertiaGenAt (t j)
      ((autEquivZmod H L.M hζ).symm (Multiplicative.ofAdd ((a j : ℕ) : ZMod n))) := by
  obtain ⟨Q, hQmax, hQover⟩ := exists_Q_over_placeP L.M (t j)
  haveI := hQmax
  haveI := hQover
  exact ⟨Q, hQmax, hQover, geomInertia_eq_zpowers_multi ht H hζ₀ hζ j Q⟩

end Inertia

/-! ### The datum at infinity -/

section AtInfinity

variable {r : ℕ}

/-- The multi-point datum, read in the coordinate `S = T⁻¹` at infinity: the polynomial
`∏ᵢ (1 - tᵢS)^{aᵢ}`, which takes the value `1` at `S = 0`. -/
def revMultiA (t : Fin r → k) (a : Fin r → ℕ) : Polynomial k := ∏ i, (1 - C (t i) * X) ^ (a i)

theorem revMultiA_eval_zero (t : Fin r → k) (a : Fin r → ℕ) : (revMultiA t a).eval 0 = 1 := by
  simp [revMultiA, eval_prod]

theorem revMultiA_ne_zero (t : Fin r → k) (a : Fin r → ℕ) : revMultiA t a ≠ 0 := by
  intro h
  have hev := revMultiA_eval_zero t a
  rw [h] at hev
  simp at hev

/-- **The inversion carries the datum at infinity to the multi-point datum**, up to the power
`T^{∑ aᵢ}`. -/
theorem invSubst_revMultiA (t : Fin r → k) (a : Fin r → ℕ) :
    invSubst (algebraMap (Polynomial k) (RatFunc k) (revMultiA t a)) * RatFunc.X ^ (∑ i, a i)
      = algebraMap (Polynomial k) (RatFunc k) (multiA t a) := by
  have hX : (RatFunc.X : RatFunc k) ≠ 0 := RatFunc.X_ne_zero
  have hcc : ∀ c : k, invSubst (RatFunc.C c) = RatFunc.C c := by
    intro c; simpa using invSubst.commutes c
  rw [revMultiA, multiA, map_prod, map_prod, map_prod, ← Finset.prod_pow_eq_pow_sum,
    ← Finset.prod_mul_distrib]
  refine Finset.prod_congr rfl fun i _ => ?_
  simp only [map_pow]
  rw [← mul_pow]
  congr 1
  simp only [map_sub, map_one, map_mul, map_sub, RatFunc.algebraMap_C, RatFunc.algebraMap_X,
    invSubst_X, hcc]
  field_simp

section Inf

variable {N : Type} [Field N] [Algebra (RatFunc k) N]

/-- The Kummer root of the multi-point datum, read in the coordinate at infinity: dividing by
`T^s` clears the pole of order `s` that the root has there. -/
def twistRootS (s : ℕ) (w : N) : Twist invSubst N :=
  (w * algebraMap (RatFunc k) N ((RatFunc.X)⁻¹ ^ s) : N)

/-- **In the coordinate at infinity the multi-point Kummer root satisfies the equation of the
datum `revMultiA`**, which is a unit at the point at infinity. -/
theorem twistRootS_pow {n s : ℕ} (t : Fin r → k) (a : Fin r → ℕ)
    (hsum : ∑ i, a i = n * s) (w : N)
    (hw : w ^ n =
      algebraMap (RatFunc k) N (algebraMap (Polynomial k) (RatFunc k) (multiA t a))) :
    (twistRootS s w) ^ n =
      algebraMap (RatFunc k) (Twist invSubst N)
        (algebraMap (Polynomial k) (RatFunc k) (revMultiA t a)) := by
  have hX : algebraMap (RatFunc k) N (RatFunc.X) ≠ 0 := by
    simpa using (map_ne_zero_iff _ (algebraMap (RatFunc k) N).injective).mpr
      (RatFunc.X_ne_zero (K := k))
  show (w * algebraMap (RatFunc k) N ((RatFunc.X)⁻¹ ^ s)) ^ n
      = algebraMap (RatFunc k) N
        (invSubst (algebraMap (Polynomial k) (RatFunc k) (revMultiA t a)))
  have key := congrArg (algebraMap (RatFunc k) N) (invSubst_revMultiA t a)
  rw [map_mul, map_pow, hsum] at key
  rw [mul_pow, hw, ← key, map_pow, map_inv₀, mul_assoc, ← pow_mul, mul_comm s n, ← mul_pow,
    mul_inv_cancel₀ hX, one_pow, mul_one]

end Inf

end AtInfinity

/-! ### Unramifiedness at infinity -/

section UnramInfinity

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

variable {r : ℕ}

/-- **The multi-point Kummer cover is unramified at the point at infinity** when `n` divides the
sum of the exponents. -/
theorem isUnramifiedAtInfinity_multiCover {n : ℕ} [NeZero n] {t : Fin r → k}
    {a : Fin r → ℕ} {s : ℕ} (hsum : ∑ i, a i = n * s)
    (H : Irreducible ((X : (RatFunc k)[X]) ^ n -
      C (algebraMap (Polynomial k) (RatFunc k) (multiA t a))))
    (L : LineCover) [IsSplittingField (RatFunc k) L.M
      ((X : (RatFunc k)[X]) ^ n -
        C (algebraMap (Polynomial k) (RatFunc k) (multiA t a)))] :
    L.IsUnramifiedAtInfinity := by
  obtain ⟨ζ₀, hζ₀⟩ := exists_primitiveRoot_k n
  have hζ : IsPrimitiveRoot (algebraMap k (RatFunc k) ζ₀) n :=
    hζ₀.map_of_injective (algebraMap k (RatFunc k)).injective
  set w : L.M :=
    kummerRoot n (algebraMap (Polynomial k) (RatFunc k) (multiA t a)) L.M with hwdef
  have hwpow : w ^ n = algebraMap (RatFunc k) L.M
      (algebraMap (Polynomial k) (RatFunc k) (multiA t a)) := kummerRoot_pow _
  have hpolyinj : Function.Injective
      ((algebraMap (RatFunc k) L.M).comp (algebraMap (Polynomial k) (RatFunc k))) :=
    (algebraMap (RatFunc k) L.M).injective.comp
      (IsFractionRing.injective (Polynomial k) (RatFunc k))
  have hw0 : w ≠ 0 := by
    intro h
    rw [h, zero_pow (NeZero.ne n)] at hwpow
    have hz : ((algebraMap (RatFunc k) L.M).comp
        (algebraMap (Polynomial k) (RatFunc k))) (multiA t a)
        = ((algebraMap (RatFunc k) L.M).comp (algebraMap (Polynomial k) (RatFunc k))) 0 := by
      rw [map_zero]; exact hwpow.symm
    exact multiA_ne_zero t a (hpolyinj hz)
  have hupow := twistRootS_pow t a hsum w hwpow
  have hpolyinj' : Function.Injective
      ((algebraMap (RatFunc k) (Twist (↑invSubst) L.M)).comp
        (algebraMap (Polynomial k) (RatFunc k))) :=
    (algebraMap (RatFunc k) (Twist (↑invSubst) L.M)).injective.comp
      (IsFractionRing.injective (Polynomial k) (RatFunc k))
  have hu0 : twistRootS s w ≠ 0 := by
    intro h
    rw [h, zero_pow (NeZero.ne n)] at hupow
    have hz : ((algebraMap (RatFunc k) (Twist (↑invSubst) L.M)).comp
        (algebraMap (Polynomial k) (RatFunc k))) (revMultiA t a)
        = ((algebraMap (RatFunc k) (Twist (↑invSubst) L.M)).comp
          (algebraMap (Polynomial k) (RatFunc k))) 0 := by
      rw [map_zero]; exact hupow.symm
    exact revMultiA_ne_zero t a (hpolyinj' hz)
  rintro τ ⟨Q, hQmax, hQover, hτ⟩
  haveI := hQmax
  haveI := hQover
  have hfix : τ (@twistRootS L.M L.field L.alg s w) = @twistRootS L.M L.field L.alg s w :=
    kummer_fix_of_mem_inertia_zero_unit n
      (by rw [revMultiA_eval_zero]; exact one_ne_zero) hu0 hupow Q hτ
  set σ : L.M ≃ₐ[RatFunc k] L.M := Twist.unaut τ with hσdef
  have hσu : σ (w * algebraMap (RatFunc k) L.M ((RatFunc.X)⁻¹ ^ s))
      = w * algebraMap (RatFunc k) L.M ((RatFunc.X)⁻¹ ^ s) := hfix
  have hXinv : algebraMap (RatFunc k) L.M ((RatFunc.X)⁻¹ ^ s) ≠ 0 := by
    refine (map_ne_zero_iff _ (algebraMap (RatFunc k) L.M).injective).mpr ?_
    exact pow_ne_zero _ (inv_ne_zero (RatFunc.X_ne_zero (K := k)))
  rw [map_mul, σ.commutes] at hσu
  have hσw : σ w = w := mul_right_cancel₀ hXinv hσu
  obtain ⟨m, hm, hone⟩ := kummer_smul_root H L.M hζ σ
  have hprod : algebraMap (RatFunc k) L.M ((algebraMap k (RatFunc k) ζ₀) ^ m) * w = 1 * w := by
    rw [one_mul, ← hm, hσw]
  have hz : (algebraMap k (RatFunc k) ζ₀) ^ m = 1 :=
    (map_eq_one_iff _ (algebraMap (RatFunc k) L.M).injective).mp (mul_right_cancel₀ hw0 hprod)
  have hσ1 : σ = 1 := hone hz
  have hτaut : τ = Twist.aut σ := AlgEquiv.ext fun _ => rfl
  rw [hτaut, hσ1]
  exact AlgEquiv.ext fun _ => rfl

end UnramInfinity

end Rigidity.RET
