/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.InertiaGen
import InverseGalois.Rigidity.RET.Unramified
import InverseGalois.Rigidity.RET.BranchSet

/-!
# Unramifiedness from a separable specialization

A cover of the line presented by a monic equation over the coordinate ring is unramified at every
point where the specialized equation stays separable: the branch points are found among the points
where the equation degenerates, with no further information about the cover.

The argument is local and elementary.  Write the monic equation as `f`, a root as `x`, and take a
place `Q` above the point `t`.  Dividing `f` by `X - x` writes `f = (X - x) g`, so the value of the
derivative of `f` at `x` is the value of `g` at `x`.  An inertia element moves `x` by an element of
`Q`, and if it moves it at all then, `x` and its image being two roots of `f`, the value of `g` at
the image vanishes.  Reducing at `Q`, the specialized equation and its derivative then share the
residue of `x` as a root, which a separable polynomial forbids.

## Main results

* `Rigidity.RET.eq_of_mem_inertia_of_separable` — an inertia element at a point where the
  specialized equation is separable fixes the root.
* `Rigidity.RET.LineCover.isUnramifiedAt_of_separable` — if the root generates the cover, the cover
  is unramified at every such point.
* `Rigidity.RET.LineCover.isUnramifiedAt_of_forall_separable` — the same for a cover generated by
  the roots of several equations.
* `Rigidity.RET.LineCover.branchLocus_subset_of_separable` — the branch locus lies inside the
  degeneracy locus of the equation.
-/

open Polynomial

noncomputable section


namespace Rigidity.RET

open GeomAKLB

attribute [local instance] Ideal.Quotient.field GeomAKLB.instMSA GeomAKLB.instIsFrac
  GeomAKLB.instIGG GeomAKLB.instFinite GeomAKLB.instIntegral GeomAKLB.instFaithful
  GeomAKLB.instDedekindB

section Geom

variable {Ω : Type} [Field Ω] [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω]
  [IsGalois (RatFunc k) Ω]
  [Algebra (Polynomial k) Ω] [IsScalarTower (Polynomial k) (RatFunc k) Ω]

/-- The residue map at a place of the integral model, read on the constants. -/
def residueConst (Q : Ideal (Bring Ω)) : k →+* (Bring Ω ⧸ Q) :=
  ((Ideal.Quotient.mk Q).comp (algebraMap (Polynomial k) (Bring Ω))).comp C

omit [Algebra (RatFunc k) Ω] [FiniteDimensional (RatFunc k) Ω] [IsGalois (RatFunc k) Ω]
  [IsScalarTower (Polynomial k) (RatFunc k) Ω] in
set_option synthInstance.maxHeartbeats 200000 in
/-- **Reduction at a place above `t` is evaluation at `t` on the coordinate ring**: the coordinate
and the constant `t` have the same residue there. -/
theorem comp_algebraMap_eq_residueConst (t : k) (Q : Ideal (Bring Ω)) [Q.IsMaximal]
    [hQ : Q.LiesOver (placeP t)] :
    (Ideal.Quotient.mk Q).comp (algebraMap (Polynomial k) (Bring Ω))
      = (residueConst Q).comp (evalRingHom t) := by
  have hmem : algebraMap (Polynomial k) (Bring Ω) (X - C t) ∈ Q := by
    have hP : (X - C t : Polynomial k) ∈ placeP t := Ideal.mem_span_singleton_self _
    rw [hQ.over] at hP
    exact hP
  have hX : (Ideal.Quotient.mk Q) (algebraMap (Polynomial k) (Bring Ω) X)
      = (Ideal.Quotient.mk Q) (algebraMap (Polynomial k) (Bring Ω) (C t)) := by
    refine Ideal.Quotient.eq.mpr ?_
    rw [← map_sub]
    exact hmem
  refine Polynomial.ringHom_ext (fun a => ?_) ?_
  · simp only [RingHom.comp_apply, residueConst, coe_evalRingHom, eval_C]
  · simpa only [RingHom.comp_apply, residueConst, coe_evalRingHom, eval_X] using hX

omit [FiniteDimensional (RatFunc k) Ω] in
set_option synthInstance.maxHeartbeats 400000 in
/-- **An inertia element at a point where the specialized equation is separable fixes the root.**
-/
theorem eq_of_mem_inertia_of_separable (t : k) (Q : Ideal (Bring Ω)) [Q.IsMaximal]
    [Q.LiesOver (placeP t)] {f : Polynomial (Polynomial k)} (hf : f.Monic) {x : Ω}
    (hroot : (Polynomial.aeval x) f = 0)
    (hsep : (f.map (evalRingHom t)).Separable) {σ : Ω ≃ₐ[RatFunc k] Ω}
    (hσ : σ ∈ geomInertia Ω Q) : σ x = x := by
  by_contra hne
  -- being a root of a monic equation, `x` lies in the integral model
  have hxint : IsIntegral (Polynomial k) x := ⟨f, hf, by rwa [← aeval_def]⟩
  have hinj : Function.Injective (algebraMap (Bring Ω) Ω) := fun _ _ h => Subtype.ext h
  set b : Bring Ω := ⟨x, hxint⟩ with hb
  set F : Polynomial (Bring Ω) := f.map (algebraMap (Polynomial k) (Bring Ω)) with hF
  -- evaluating the equation in the integral model is evaluating it in the cover
  have key : ∀ y : Bring Ω,
      (algebraMap (Bring Ω) Ω) (F.eval y) = Polynomial.aeval ((y : Ω)) f := by
    intro y
    rw [hF, Polynomial.eval_map, Polynomial.hom_eval₂, Polynomial.aeval_def,
      ← IsScalarTower.algebraMap_eq]
    rfl
  have hFb : F.eval b = 0 := by
    refine hinj ?_
    rw [key, map_zero]
    exact hroot
  have hσx : ((σ • b : Bring Ω) : Ω) = σ x := coe_smul_geom Ω σ b
  -- the image of the root is again a root
  have hFs : F.eval (σ • b) = 0 := by
    refine hinj ?_
    rw [key, map_zero, hσx]
    have h2 : (Polynomial.aeval (σ x)) f = σ ((Polynomial.aeval x) f) :=
      Polynomial.aeval_algHom_apply ((σ.restrictScalars (Polynomial k)).toAlgHom) x f
    rw [h2, hroot, map_zero]
  -- divide the root out of the equation
  obtain ⟨G, hG⟩ : (X - C b) ∣ F := Polynomial.dvd_iff_isRoot.mpr hFb
  have hbne : σ • b ≠ b := fun h => hne (by rw [← hσx, h])
  have hGs : G.eval (σ • b) = 0 := by
    have h := hFs
    rw [hG] at h
    simp only [Polynomial.eval_mul, Polynomial.eval_sub, Polynomial.eval_X,
      Polynomial.eval_C] at h
    rcases mul_eq_zero.mp h with h' | h'
    · exact absurd (sub_eq_zero.mp h') hbne
    · exact h'
  have hderiv : F.derivative.eval b = G.eval b := by
    rw [hG]
    simp [Polynomial.derivative_mul]
  -- reduce the equation at the place
  set π : Bring Ω →+* (Bring Ω ⧸ Q) := Ideal.Quotient.mk Q with hπ
  have hsub : σ • b - b ∈ Q := hσ b
  have hcong : π (σ • b) = π b := Ideal.Quotient.eq.mpr hsub
  set P : Polynomial (Bring Ω ⧸ Q) := F.map π with hP
  have hPsep : P.Separable := by
    have hPeq : P = (f.map (evalRingHom t)).map (residueConst Q) := by
      rw [hP, hF, Polynomial.map_map, Polynomial.map_map, hπ,
        comp_algebraMap_eq_residueConst t Q]
    rw [hPeq]
    exact hsep.map
  have hProot : P.eval (π b) = 0 := by
    rw [hP, Polynomial.eval_map, Polynomial.eval₂_at_apply, hFb, map_zero]
  have hPderiv : P.derivative.eval (π b) = 0 := by
    have h1 : P.derivative = F.derivative.map π := by rw [hP, Polynomial.derivative_map]
    rw [h1, Polynomial.eval_map, Polynomial.eval₂_at_apply, hderiv,
      ← Polynomial.eval₂_at_apply π b, ← hcong, Polynomial.eval₂_at_apply, hGs, map_zero]
  -- the specialized equation and its derivative cannot share a root
  obtain ⟨a, c, hac⟩ := hPsep
  have hev := congrArg (fun q : Polynomial (Bring Ω ⧸ Q) => q.eval (π b)) hac
  simp only [Polynomial.eval_add, Polynomial.eval_mul, hProot, hPderiv, mul_zero, add_zero,
    Polynomial.eval_one] at hev
  exact zero_ne_one hev

end Geom

namespace LineCover

/-- **A cover generated by roots of monic equations is unramified at every point where all the
specialized equations are separable.**  Each generator is fixed by an inertia element there, and an
automorphism fixing a generating family is the identity. -/
theorem isUnramifiedAt_of_forall_separable (L : LineCover) {ι : Type*} {x : ι → L.M}
    (hgen : Algebra.adjoin (RatFunc k) (Set.range x) = ⊤)
    {f : ι → Polynomial (Polynomial k)} (hf : ∀ i, (f i).Monic)
    (hroot : ∀ i, (Polynomial.aeval (x i)) (f i) = 0) {t : k}
    (hsep : ∀ i, ((f i).map (evalRingHom t)).Separable) {σ : L.deck} (hσ : L.IsInertiaAt t σ) :
    σ = 1 := by
  obtain ⟨Q, hQmax, hQover, hmem⟩ := hσ
  haveI := hQmax
  haveI := hQover
  have hid : σ.toAlgHom = (AlgHom.id (RatFunc k) L.M) := by
    refine AlgHom.ext_of_adjoin_eq_top hgen ?_
    rintro _ ⟨i, rfl⟩
    exact eq_of_mem_inertia_of_separable t Q (hf i) (hroot i) (hsep i) hmem
  refine AlgEquiv.ext fun y => ?_
  simpa using AlgHom.congr_fun hid y

/-- **A cover presented by a single monic equation is unramified wherever the specialized equation
is separable.** -/
theorem isUnramifiedAt_of_separable (L : LineCover) {x : L.M}
    (hgen : IntermediateField.adjoin (RatFunc k) {x} = ⊤)
    {f : Polynomial (Polynomial k)} (hf : f.Monic) (hroot : (Polynomial.aeval x) f = 0) {t : k}
    (hsep : (f.map (evalRingHom t)).Separable) {σ : L.deck} (hσ : L.IsInertiaAt t σ) : σ = 1 := by
  -- the generator is algebraic, so the subalgebra it generates is already the whole cover
  have hxalg : IsAlgebraic (RatFunc k) x := Algebra.IsAlgebraic.isAlgebraic x
  have hadj : Algebra.adjoin (RatFunc k) (Set.range (fun _ : Unit => x)) = ⊤ := by
    have hsub := IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hxalg
    have htop : (IntermediateField.adjoin (RatFunc k) {x}).toSubalgebra = ⊤ := by
      rw [hgen]; rfl
    rw [Set.range_const]
    rwa [hsub] at htop
  exact isUnramifiedAt_of_forall_separable L hadj (fun _ => hf) (fun _ => hroot)
    (fun _ => hsep) hσ

/-- **The branch points of a cover generated by roots of monic equations lie among the points where
one of the specialized equations degenerates.** -/
theorem isUnramifiedOutside_of_forall_separable (L : LineCover) {ι : Type*} {x : ι → L.M}
    (hgen : Algebra.adjoin (RatFunc k) (Set.range x) = ⊤)
    {f : ι → Polynomial (Polynomial k)} (hf : ∀ i, (f i).Monic)
    (hroot : ∀ i, (Polynomial.aeval (x i)) (f i) = 0) {S : Set k}
    (hsep : ∀ t ∉ S, ∀ i, ((f i).map (evalRingHom t)).Separable) :
    L.IsUnramifiedOutside S :=
  fun _ ht _ hσ => isUnramifiedAt_of_forall_separable L hgen hf hroot (hsep _ ht) hσ

/-- **The branch points of a cover presented by a monic equation lie among the points where the
specialized equation degenerates.** -/
theorem isUnramifiedOutside_of_separable (L : LineCover) {x : L.M}
    (hgen : IntermediateField.adjoin (RatFunc k) {x} = ⊤)
    {f : Polynomial (Polynomial k)} (hf : f.Monic) (hroot : (Polynomial.aeval x) f = 0)
    {S : Set k} (hsep : ∀ t ∉ S, (f.map (evalRingHom t)).Separable) :
    L.IsUnramifiedOutside S :=
  fun _ ht _ hσ => isUnramifiedAt_of_separable L hgen hf hroot (hsep _ ht) hσ

/-- **The branch locus is contained in the degeneracy locus of the equation.** -/
theorem branchLocus_subset_of_separable (L : LineCover) {x : L.M}
    (hgen : IntermediateField.adjoin (RatFunc k) {x} = ⊤)
    {f : Polynomial (Polynomial k)} (hf : f.Monic) (hroot : (Polynomial.aeval x) f = 0) :
    L.branchLocus ⊆ {t : k | ¬ (f.map (evalRingHom t)).Separable} :=
  (L.isUnramifiedOutside_iff_branchLocus_subset _).mp
    (isUnramifiedOutside_of_separable L hgen hf hroot fun _ ht => not_not.mp ht)

end LineCover

end Rigidity.RET
