/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.DeckGroups
import InverseGalois.Rigidity.RET.DeckGroupsExistence
import InverseGalois.Rigidity.RET.MonodromyQuotient
import InverseGalois.Rigidity.RET.Local.ProdOneGeneration

/-!
# The universal product-one tuple, and branch cycles for free

Realizing a finite group as the deck group of a cover with a prescribed branch locus is a coarser
demand than realizing a *prescribed* tuple as the branch cycles of such a cover: the first
statement forgets which elements of the group the loops around the punctures are sent to.  The two
demands are nevertheless equivalent, and this file proves it.  The mechanism is a universal group.

Fix `r` and a finite group `H`.  Let `J` be the (finite) set of product-one `r`-tuples of `H` and
let `Xᵢ : J → H` be the `i`-th coordinate function, so that `X₀ ⋯ X_{r-1} = 1` holds in the group
of functions `J → H` simply because it holds coordinatewise.  The subgroup `Ĝ` generated by the
`Xᵢ` therefore carries a generating product-one tuple, and it has the property that makes it
universal:

> every generating product-one `r`-tuple `ĝ` of `Ĝ` is the image of `X` under an automorphism
> of `Ĝ`.

Indeed `ĝ` defines a map `c : J → J`, `c a = (ĝ₀ a, …, ĝ_{r-1} a)`, and precomposition with `c` is
an endomorphism of `J → H` carrying `Xᵢ` to `ĝᵢ`; it preserves `Ĝ`, is onto because its image
contains a generating set, and an onto endomorphism of a finite group is an automorphism.

Universality is what buys the branch cycles.  A cover with deck group `Ĝ` and the prescribed branch
locus has *some* system of branch cycles (`Rigidity.RET.geomRETCompleteness_of_injective`); by
universality the identification of its deck group with `Ĝ` may be adjusted so that the branch
cycles become exactly `X`; and pushing forward along the evaluation `Ĝ →* H` at the tuple one
started from turns `X` into that tuple.  So no control over inertia is needed at the moment the
cover is built — only over its deck group and its branch locus.

## Main definitions

* `Rigidity.RET.univGroup` — the universal group, generated by the coordinate functions on the
  product-one tuples.
* `Rigidity.RET.univGen` — the universal generating product-one tuple.

## Main results

* `Rigidity.RET.exists_mulEquiv_univGen` — every generating product-one tuple of the universal
  group is the image of the universal tuple under an automorphism.
* `Rigidity.RET.geomRETExistence_of_isDeckGroupOver` — realizing every group over a branch locus
  realizes every tuple as a system of branch cycles.
* `Rigidity.RET.geomRETExistence_of_injective` — the existence direction of the Riemann Existence
  Theorem for the line, for any injective tuple of points.
* `Rigidity.RET.lineCover_exists_of_branchCycles` — the existence direction, packaged as a system
  of branch cycles.
-/

noncomputable section

namespace Rigidity.RET

open GeomAKLB

/-! ## Products in a group of functions -/

/-- The product of a tuple of functions is computed coordinatewise. -/
theorem list_prod_ofFn_apply {ι M : Type*} [Monoid M] {n : ℕ} (f : Fin n → ι → M) (a : ι) :
    (List.ofFn f).prod a = (List.ofFn fun i => f i a).prod := by
  have h := map_list_prod (Pi.evalMonoidHom (fun _ : ι => M) a) (List.ofFn f)
  simpa [Pi.evalMonoidHom, List.map_ofFn, Function.comp_def] using h

/-! ## The universal group -/

variable (H : Type*) [Group H] (r : ℕ)

/-- The product-one `r`-tuples of a group. -/
abbrev ProdOneTuple : Type _ := {a : Fin r → H // (List.ofFn a).prod = 1}

/-- The `i`-th coordinate function on the product-one `r`-tuples: the universal candidate for the
`i`-th member of such a tuple. -/
def univTuple (i : Fin r) : ProdOneTuple H r → H := fun a => a.1 i

/-- **The universal group**: the subgroup of the functions on the product-one `r`-tuples generated
by the `r` coordinate functions. -/
def univGroup : Subgroup (ProdOneTuple H r → H) := Subgroup.closure (Set.range (univTuple H r))

/-- **The universal product-one tuple**, read inside the group it generates. -/
def univGen (i : Fin r) : univGroup H r :=
  ⟨univTuple H r i, Subgroup.subset_closure ⟨i, rfl⟩⟩

theorem coe_univGen (i : Fin r) : ((univGen H r i : univGroup H r) : ProdOneTuple H r → H)
    = univTuple H r i := rfl

/-- The coordinate functions multiply to the identity, because a product-one tuple does. -/
theorem prod_univTuple : (List.ofFn (univTuple H r)).prod = 1 := by
  funext a
  rw [list_prod_ofFn_apply]
  simpa using a.2

/-- **The universal tuple has product one.** -/
theorem prod_univGen : (List.ofFn (univGen H r)).prod = 1 := by
  have h := map_list_prod (univGroup H r).subtype (List.ofFn (univGen H r))
  rw [List.map_ofFn] at h
  refine Subtype.ext ?_
  simp only [Subgroup.coe_one]
  rw [show ((List.ofFn (univGen H r)).prod : ProdOneTuple H r → H)
    = (univGroup H r).subtype ((List.ofFn (univGen H r)).prod) from rfl, h]
  simpa [Function.comp_def, coe_univGen] using prod_univTuple H r

/-- **The universal tuple generates the universal group.** -/
theorem closure_range_univGen : Subgroup.closure (Set.range (univGen H r)) = ⊤ := by
  have hpre : ((↑) : univGroup H r → (ProdOneTuple H r → H)) ⁻¹' Set.range (univTuple H r)
      = Set.range (univGen H r) := by
    ext x
    constructor
    · rintro ⟨i, hi⟩
      exact ⟨i, Subtype.ext hi⟩
    · rintro ⟨i, rfl⟩
      exact ⟨i, rfl⟩
  rw [← hpre]
  exact Subgroup.closure_closure_coe_preimage

/-- **The universal group is universal**: every generating product-one `r`-tuple of it is the image
of the universal tuple under an automorphism.

Precomposing the functions on the product-one tuples with the map `a ↦ (ĝ₀ a, …, ĝ_{r-1} a)` — a
map to product-one tuples precisely because the given tuple has product one — is an endomorphism
carrying the universal tuple to the given one.  It preserves the universal group, it is onto
because its image contains a generating set, and an onto endomorphism of a finite group is an
automorphism. -/
theorem exists_mulEquiv_univGen [Finite H] (ĝ : Fin r → univGroup H r)
    (hprod : (List.ofFn ĝ).prod = 1) (htop : Subgroup.closure (Set.range ĝ) = ⊤) :
    ∃ ψ : univGroup H r ≃* univGroup H r, ∀ i, ψ (univGen H r i) = ĝ i := by
  classical
  -- the tuple, evaluated at a product-one tuple, is again a product-one tuple
  have hc : ∀ a : ProdOneTuple H r,
      (List.ofFn fun i => ((ĝ i : ProdOneTuple H r → H)) a).prod = 1 := by
    intro a
    have h := map_list_prod
      ((Pi.evalMonoidHom (fun _ : ProdOneTuple H r => H) a).comp (univGroup H r).subtype)
      (List.ofFn ĝ)
    rw [hprod, map_one, List.map_ofFn] at h
    simpa [Pi.evalMonoidHom, Function.comp_def] using h.symm
  set c : ProdOneTuple H r → ProdOneTuple H r := fun a => ⟨fun i => ((ĝ i : _ → H)) a, hc a⟩
    with hcdef
  -- precomposition with `c`
  let F : (ProdOneTuple H r → H) →* (ProdOneTuple H r → H) :=
    { toFun := fun u => u ∘ c
      map_one' := rfl
      map_mul' := fun _ _ => rfl }
  have hFgen : ∀ i, F (univTuple H r i) = ((ĝ i : ProdOneTuple H r → H)) := fun i => funext
    fun _ => rfl
  have hmaps : ∀ x : univGroup H r, F x ∈ univGroup H r := by
    intro x
    have hle : Subgroup.closure (Set.range (univTuple H r)) ≤ (univGroup H r).comap F := by
      rw [Subgroup.closure_le]
      rintro _ ⟨i, rfl⟩
      refine Subgroup.mem_comap.2 ?_
      rw [hFgen i]
      exact (ĝ i).2
    exact hle x.2
  set ψ₀ : univGroup H r →* univGroup H r :=
    MonoidHom.codRestrict (F.comp (univGroup H r).subtype) (univGroup H r) hmaps with hψ₀def
  have hψ₀ : ∀ i, ψ₀ (univGen H r i) = ĝ i := fun i => Subtype.ext (hFgen i)
  have hsurj : Function.Surjective ψ₀ := by
    rw [← MonoidHom.range_eq_top, eq_top_iff, ← htop, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨univGen H r i, hψ₀ i⟩
  exact ⟨MulEquiv.ofBijective ψ₀ ⟨Finite.injective_iff_surjective.2 hsurj, hsurj⟩, hψ₀⟩

/-- **Evaluation at a product-one tuple** maps the universal group onto the group, carrying the
universal tuple to the given one; it is onto as soon as the given tuple generates. -/
theorem exists_monoidHom_univGen (h : Fin r → H)
    (hprod : (List.ofFn h).prod = 1) (htop : Subgroup.closure (Set.range h) = ⊤) :
    ∃ π : univGroup H r →* H, Function.Surjective π ∧ ∀ i, π (univGen H r i) = h i := by
  refine ⟨(Pi.evalMonoidHom (fun _ : ProdOneTuple H r => H) ⟨h, hprod⟩).comp
    (univGroup H r).subtype, ?_, fun i => rfl⟩
  rw [← MonoidHom.range_eq_top, eq_top_iff, ← htop, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  exact ⟨univGen H r i, rfl⟩

/-! ## Branch cycles for free -/

/-- **Realizing every finite group over a branch locus realizes every tuple as a system of branch
cycles there.**

Only the deck group and the branch locus of the cover need to be controlled: the inertia is
recovered afterwards, by building the cover for the universal group, reading off *some* system of
branch cycles, adjusting the identification of the deck group by the automorphism universality
provides, and pushing forward to the group one started from. -/
theorem geomRETExistence_of_isDeckGroupOver {r : ℕ} {t : Fin r → k} (ht : Function.Injective t)
    (hd : ∀ (G : Type) [Group G] [Finite G] (g : Fin r → G), (List.ofFn g).prod = 1 →
      Subgroup.closure (Set.range g) = ⊤ → IsDeckGroupOver (Set.range t) G) :
    GeomRETExistence t := by
  intro H _ _ h hprod htop
  obtain ⟨L, ⟨e⟩, hout, hinf⟩ :=
    hd (univGroup H r) (univGen H r) (prod_univGen H r) (closure_range_univGen H r)
  obtain ⟨g, hg⟩ := geomRETCompleteness_of_injective ht L hout hinf
  obtain ⟨ψ, hψ⟩ := exists_mulEquiv_univGen H r (fun i => e (g i))
    (by simpa using prod_ofFn_symm_eq_one e.symm hg.prod)
    (by simpa using closure_range_symm_eq_top e.symm hg.top)
  obtain ⟨π, hπ, hπgen⟩ := exists_monoidHom_univGen H r h hprod htop
  have hmono : IsMonodromyOver (univGen H r) t := by
    refine ⟨L, e.trans ψ.symm, hout, hinf, fun i => ?_⟩
    have hsymm : (e.trans ψ.symm).symm (univGen H r i) = g i := by
      simp [hψ i]
    rw [hsymm]
    exact hg.inertia i
  simpa [hπgen] using hmono.map π hπ

/-- Conversely, a cover realizing a tuple as its system of branch cycles realizes its group over
the branch locus. -/
theorem isDeckGroupOver_of_geomRETExistence {r : ℕ} {t : Fin r → k} (hgr : GeomRETExistence t)
    {G : Type} [Group G] [Finite G] (g : Fin r → G) (hprod : (List.ofFn g).prod = 1)
    (htop : Subgroup.closure (Set.range g) = ⊤) : IsDeckGroupOver (Set.range t) G := by
  obtain ⟨L, e, hout, hinf, -⟩ := hgr g hprod htop
  exact ⟨L, ⟨e⟩, hout, hinf⟩

/-- **The existence direction of the Riemann Existence Theorem for the line over `ℚ̄`.**

For `r` distinct points of the line, a generating product-one tuple in a finite group `H` — the
same thing as a surjection of the fundamental group of the `r`-punctured sphere, the sphere group
`Γ_r = ⟨x₀,…,x_{r-1} | x₀⋯x_{r-1} = 1⟩`, onto `H` — is the tuple of branch cycles of a cover of
the line with deck group `H`, unramified outside the given points and infinity.

The two hypotheses on the tuple are not decoration: they are exactly the two relations that hold
among the loops on the punctured sphere — the loops generate, because the cover is connected, and
their ordered product is contractible.  A tuple violating either is the branch-cycle system of no
cover. -/
theorem geomRETExistence_of_injective {r : ℕ} (t : Fin r → k) (ht : Function.Injective t) :
    GeomRETExistence t :=
  geomRETExistence_of_isDeckGroupOver ht fun _ _ _ g hprod htop =>
    isDeckGroupOver_of_prodOne ht g hprod htop

/-- **Prescribed branch cycles are realized by a cover of the line.**

Given `r` distinct points `t₀, …, t_{r-1}` of the line over `ℚ̄` and a tuple `h₀, …, h_{r-1}` of
elements of a finite group `H` which generate `H` and multiply to `1`, there is a finite Galois
cover of the line with deck group `H`, unramified outside the given points and infinity, in which
`hᵢ` is an inertia element at `tᵢ`. -/
theorem lineCover_exists_of_branchCycles {r : ℕ} (t : Fin r → k) (ht : Function.Injective t)
    {H : Type} [Group H] [Finite H] (h : Fin r → H)
    (hprod : (List.ofFn h).prod = 1) (htop : Subgroup.closure (Set.range h) = ⊤) :
    ∃ (L : LineCover) (e : L.deck ≃* H), ∀ i, L.IsInertiaAt (t i) (e.symm (h i)) := by
  obtain ⟨L, e, -, -, hin⟩ := geomRETExistence_of_injective t ht h hprod htop
  exact ⟨L, e, fun i => (hin i).isInertiaAt⟩

/-- The cover produced by the existence direction carries the prescribed tuple as a genuine system
of distinguished branch cycles: the tuple generates the deck group and has product one, and those
two properties travel along the identification of the deck group with `H`. -/
theorem exists_lineCover_isBranchCycleSystem {r : ℕ} (t : Fin r → k) (ht : Function.Injective t)
    {H : Type} [Group H] [Finite H] (h : Fin r → H)
    (hprod : (List.ofFn h).prod = 1) (htop : Subgroup.closure (Set.range h) = ⊤) :
    ∃ (L : LineCover) (e : L.deck ≃* H), L.IsBranchCycleGenSystem t (fun i => e.symm (h i)) := by
  obtain ⟨L, e, -, -, hin⟩ := geomRETExistence_of_injective t ht h hprod htop
  exact ⟨L, e, ⟨hin, closure_range_symm_eq_top e htop, prod_ofFn_symm_eq_one e hprod⟩⟩

end Rigidity.RET

end
