/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.SubCover

/-!
# Unramifiedness of a cover of the line outside a set of points

A cover of the line is **unramified outside `S`** if no point outside `S` carries a non-trivial
inertia element.  This is the property that delimits the branch locus of a cover, and the one that
has to be propagated through the descent: the cover produced by the Riemann Existence Theorem is
unramified outside the prescribed branch points, and the arithmetic Galois closure of that cover
must be shown to be unramified outside the *same* points before its branch cycles can be read off.

The main result here is the **compositum lemma**: a cover generated by normal subcovers each
unramified outside `S` is unramified outside `S`.  The proof is the inertia contraction of
`RET/SubCover.lean` plus one line of Galois theory — an automorphism fixing every member of a family
of intermediate fields whose supremum is everything is the identity.  This is the rung of the descent
ladder that makes the branch points of the Galois closure rational: the closure is generated by the
conjugates of the cover, and a conjugate of a cover unramified outside a set of *rational* points is
again unramified outside those points.

## Main definitions

* `Rigidity.RET.LineCover.IsUnramifiedOutside` — no non-trivial inertia outside `S`.

## Main results

* `Rigidity.RET.LineCover.IsUnramifiedOutside.of_iSup` — the compositum lemma.
* `Rigidity.RET.LineCover.IsUnramifiedOutside.transport` — the property only depends on the
  isomorphism class of the cover.
-/

open Polynomial

noncomputable section

set_option maxHeartbeats 1600000
set_option synthInstance.maxHeartbeats 1000000

namespace Rigidity.RET

open GeomAKLB

namespace LineCover

/-- A cover of the line is **unramified outside `S`** if every inertia element at a point outside
`S` is trivial. -/
def IsUnramifiedOutside (L : LineCover) (S : Set k) : Prop :=
  ∀ t ∉ S, ∀ σ : L.deck, L.IsInertiaAt t σ → σ = 1

theorem IsUnramifiedOutside.mono {L : LineCover} {S S' : Set k} (h : L.IsUnramifiedOutside S)
    (hS : S ⊆ S') : L.IsUnramifiedOutside S' :=
  fun _ ht σ hσ => h _ (fun hmem => ht (hS hmem)) σ hσ

/-- An automorphism which is the identity on every member of a family of intermediate fields whose
supremum is the whole field is the identity. -/
theorem eq_one_of_iSup {M : Type} [Field M] [Algebra (RatFunc k) M] {ι : Sort*}
    (E : ι → IntermediateField (RatFunc k) M) (hsup : ⨆ i, E i = ⊤)
    {σ : M ≃ₐ[RatFunc k] M} (h : ∀ i, ∀ x ∈ E i, σ x = x) : σ = 1 := by
  have hle : (⊤ : IntermediateField (RatFunc k) M)
      ≤ IntermediateField.fixedField (Subgroup.closure {σ}) := by
    rw [← hsup]
    refine iSup_le fun i => fun x hx => ?_
    rw [IntermediateField.mem_fixedField_iff]
    intro f hf
    refine Subgroup.closure_induction (p := fun f _ => f x = x) ?_ rfl ?_ ?_ hf
    · rintro g rfl
      exact h i x hx
    · intro g g' _ _ hg hg'
      show g (g' x) = x
      rw [hg', hg]
    · intro g _ hg
      have h2 : g⁻¹ (g x) = g⁻¹ x := by rw [hg]
      rw [← AlgEquiv.mul_apply, inv_mul_cancel, AlgEquiv.one_apply] at h2
      exact h2.symm
  ext x
  have hx : x ∈ IntermediateField.fixedField (Subgroup.closure {σ}) :=
    hle (IntermediateField.mem_top)
  rw [IntermediateField.mem_fixedField_iff] at hx
  exact hx σ (Subgroup.subset_closure rfl)

/-- **The compositum lemma.**  If a cover is generated, as a field, by normal subcovers each of
which is unramified outside `S`, then the cover itself is unramified outside `S`.

An inertia element of the big cover restricts to an inertia element of each subcover
(`IsInertiaAt.restrict`), hence to the identity on each subcover, hence is the identity. -/
theorem IsUnramifiedOutside.of_iSup {L : LineCover} {S : Set k} {ι : Sort*}
    (E : ι → IntermediateField (RatFunc k) L.M) [∀ i, Normal (RatFunc k) (E i)]
    (hsup : ⨆ i, E i = ⊤)
    (hE : ∀ i, (L.sub (E i)).IsUnramifiedOutside S) : L.IsUnramifiedOutside S := by
  intro t ht σ hσ
  refine eq_one_of_iSup E hsup fun i x hx => ?_
  have h1 : L.subHom (E i) σ = 1 := hE i t ht _ (IsInertiaAt.restrict L hσ)
  have h2 := AlgEquiv.restrictNormalHom_apply (E i) σ ⟨x, hx⟩
  rw [show AlgEquiv.restrictNormalHom (E i) σ = (1 : (L.sub (E i)).deck) from h1] at h2
  simpa using h2.symm

/-- Unramifiedness outside `S` only depends on the isomorphism class of the cover. -/
theorem IsUnramifiedOutside.transport {L L' : LineCover} (e : L.M ≃ₐ[RatFunc k] L'.M)
    {S : Set k} (h : L.IsUnramifiedOutside S) : L'.IsUnramifiedOutside S := by
  intro t ht σ hσ
  have h1 : AlgEquiv.autCongr e.symm σ = 1 := h t ht _ (IsInertiaAt.transport e.symm hσ)
  exact (AlgEquiv.autCongr e.symm).injective (by rw [h1, map_one])

end LineCover

end Rigidity.RET
