/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Pi1.FundamentalGroup

/-!
# The inertia generators of the tame fundamental group

The tame fundamental group `sphereCompletion r` of the `r`-punctured line is the profinite completion
of the sphere presentation group `Γ_r = ⟨x₀,…,x_{r-1} | x₀···x_{r-1} = 1⟩`.  Its distinguished
generators — the images of the presentation generators `x₀,…,x_{r-1}` — are the **tame inertia
generators**: one loop around each branch point.  This module records them and their two defining
features:

* the **product-one relation** `x₀···x_{r-1} = 1` (the boundary of a disc bounding all the
  punctures), and
* **topological generation**: the (abstract) subgroup they generate is dense, so its topological
  closure is the whole group.

These are the abstract π₁ shadow of the geometric inertia data (`InertiaRootData` in the descent
tower): the inertia generators of a geometric cover branched over the `r` points are the images of
these `sphereGen i` under the monodromy of the cover.

## Main definitions / results

* `sphereGen` — the inertia generators of `sphereCompletion r`.
* `sphereGen_prod` — the product-one relation.
* `sphereGen_dense` / `sphereGen_topologicalClosure_eq_top` — topological generation.
-/

namespace Rigidity.RET

open CategoryTheory ProfiniteGrp ProfiniteGrp.ProfiniteCompletion

variable {r : ℕ}

/-- The inertia generators of the tame π₁: the images in the profinite completion of the sphere
group's presentation generators, one per branch point. -/
noncomputable def sphereGen (r : ℕ) (i : Fin r) : sphereCompletion r :=
  sphereEta (PresentedGroup.of i)

/-- The inertia generators satisfy the product-one sphere relation. -/
theorem sphereGen_prod : (List.ofFn (sphereGen r)).prod = 1 := by
  have : (List.ofFn (sphereGen r))
      = (List.ofFn (fun i => PresentedGroup.of i : Fin r → SphereGroup r)).map sphereEta := by
    rw [List.map_ofFn]; rfl
  rw [this, ← map_list_prod, sphere_gens_prod_eq_one, map_one]

/-- The subgroup generated by the inertia generators equals the range of the completion unit. -/
theorem sphereEta_range_eq_closure_gen :
    sphereEta.range = Subgroup.closure (Set.range (sphereGen r)) := by
  rw [MonoidHom.range_eq_map, ← PresentedGroup.closure_range_of (sphereRel r),
    MonoidHom.map_closure]
  congr 1
  rw [← Set.range_comp]
  rfl

/-- **The inertia generators topologically generate the tame π₁.**  The subgroup they generate is
dense in `sphereCompletion r`. -/
theorem sphereGen_dense :
    Dense (Subgroup.closure (Set.range (sphereGen r)) : Set (sphereCompletion r)) := by
  have hd : Dense (Set.range (sphereEta : SphereGroup r → sphereCompletion r)) :=
    sphereEta_denseRange
  rw [← MonoidHom.coe_range, sphereEta_range_eq_closure_gen] at hd
  exact hd

/-- The topological closure of the subgroup generated by the inertia generators is the whole
completion. -/
theorem sphereGen_topologicalClosure_eq_top :
    (Subgroup.closure (Set.range (sphereGen r))).topologicalClosure = ⊤ := by
  apply SetLike.coe_injective
  rw [Subgroup.topologicalClosure_coe, Subgroup.coe_top]
  exact sphereGen_dense.closure_eq

/-! ### Monodromy of the inertia generators

A geometric Galois cover of the `r`-punctured line with deck group `H` is, on the abstract π₁ side, a
continuous surjection `f : sphereCompletion r ↠ H`.  Its **monodromy tuple** is the image of the
inertia generators, `i ↦ f (xᵢ)` — the local monodromy around each branch point.  This is exactly the
generating product-one tuple that a rigidity certificate records, so the abstract π₁ makes precise
that the certificate's `base` tuple *is* the branch monodromy of the inertia generators. -/

variable {H : Type} [Group H] [Finite H]

/-- The monodromy tuple of a continuous hom to a finite group: the image of the inertia generators,
i.e. the local monodromy around each branch point. -/
noncomputable def monodromyTuple
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H)) (i : Fin r) : H :=
  f (sphereGen r i)

/-- The monodromy tuple is the induced discrete homomorphism evaluated on the presentation
generators. -/
theorem monodromyTuple_eq
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H)) (i : Fin r) :
    monodromyTuple f i = sphereCompletionInduced f (PresentedGroup.of i) :=
  (sphereCompletionInduced_apply f (PresentedGroup.of i)).symm

theorem monodromyTuple_funext
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H)) :
    monodromyTuple f = fun i => sphereCompletionInduced f (PresentedGroup.of i) := by
  funext i; exact monodromyTuple_eq f i

/-- The monodromy tuple satisfies the product-one relation. -/
theorem monodromyTuple_prod
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H)) :
    (List.ofFn (monodromyTuple f)).prod = 1 := by
  obtain ⟨hb, _⟩ := eq_sphereHom (sphereCompletionInduced f)
  rw [monodromyTuple_funext]; exact hb

/-- If the cover is connected (the monodromy is surjective), the monodromy tuple generates `H`. -/
theorem monodromyTuple_generates
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H))
    (hf : Function.Surjective (f : sphereCompletion r → _)) :
    Subgroup.closure (Set.range (monodromyTuple f)) = ⊤ := by
  have hfi : Function.Surjective (sphereCompletionInduced f) :=
    (sphereCompletion_surjective_iff f).1 hf
  obtain ⟨hb, hsh⟩ := eq_sphereHom (sphereCompletionInduced f)
  have hgen := (sphereHom_surjective_iff _ hb).1 (by rw [hsh]; exact hfi)
  rw [monodromyTuple_funext]; exact hgen

/-- **The monodromy tuple of a connected cover is a generating product-one tuple.**  On the abstract
π₁ side, a connected geometric Galois cover with deck group `H` determines precisely the generating
product-one tuple that a rigidity certificate records — the branch monodromy of the tame inertia
generators. -/
theorem monodromyTuple_mem
    (f : sphereCompletion r ⟶ ProfiniteGrp.ofFiniteGrp (FiniteGrp.of H))
    (hf : Function.Surjective (f : sphereCompletion r → _)) :
    (List.ofFn (monodromyTuple f)).prod = 1
      ∧ Subgroup.closure (Set.range (monodromyTuple f)) = ⊤ :=
  ⟨monodromyTuple_prod f, monodromyTuple_generates f hf⟩

end Rigidity.RET
