/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.BaseChangeIndex
import InverseGalois.CFT.Kummer.CyclotomicDescent

/-!
# The norm index of a cyclic extension

For a cyclic extension of number fields the index of the principal ideles together with the norms
is exactly the degree.  The extension of prime degree is already known, and a general cyclic
extension is built from those by a tower: a cyclic group of composite order has a subgroup of
prime index, whose fixed field is a step of prime degree over the base field with the whole
extension again cyclic above it.

The count is multiplicative along a tower in the weak sense of a divisibility.  Passing to the
middle field shrinks the subgroup generated by the principal ideles and the norms, because a norm
from the top field is the norm of a norm, and the index of the smaller subgroup is the index of
the larger one times the relative index of the two.  That relative index is bounded by the count
for the upper step: the norm to the base field carries the ideles of the middle field onto the
larger subgroup modulo the smaller one, since a principal idele of the base field already lies in
the smaller one, and it carries the principal ideles and the norms of the middle field into the
smaller one.

Together with the first inequality, which bounds the count from below by the degree of a cyclic
extension, the divisibility along the tower gives equality at every stage of the induction.

## Main results

* `InverseGalois.CFT.index_dvd_mul_index_of_tower`: the norm index of a tower divides the product
  of the norm indices of its two steps.
* `InverseGalois.CFT.index_ideleDiag_sup_ideleNorm_eq_card`: **the index of the principal ideles
  together with the norms of a cyclic extension is the degree.**
* `InverseGalois.CFT.index_ideleDiag_sup_ideleNorm_eq_finrank`: the same count, phrased with the
  degree of the extension in place of the order of the Galois group.

## Tags

number field, idele, norm index, cyclic extension, second inequality
-/

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

/-! ### The norm index along a tower -/

section Tower

variable {k F K : Type*} [Field k] [NumberField k] [Field F] [NumberField F] [Field K]
  [NumberField K] [Algebra k F] [Algebra F K] [Algebra k K] [IsScalarTower k F K]
  [IsGalois k F] [IsGalois F K] [IsGalois k K]

set_option synthInstance.maxHeartbeats 400000 in
set_option maxHeartbeats 1000000 in
/-- **The norm index of a tower divides the product of the norm indices of its two steps.**  The
subgroup for the whole extension sits inside the subgroup for the lower step, and the norm to the
base field descends to a surjection of the ideles of the middle field modulo its own subgroup onto
the quotient of the two. -/
theorem index_dvd_mul_index_of_tower :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index ∣
      ((ideleDiag k).range ⊔ (ideleNorm k F).range).index *
        ((ideleDiag F).range ⊔ (ideleNorm F K).range).index := by
  set N1 : AddSubgroup ↥(idele k) := (ideleDiag k).range ⊔ (ideleNorm k F).range with hN1
  set N2 : AddSubgroup ↥(idele k) := (ideleDiag k).range ⊔ (ideleNorm k K).range with hN2
  set M : AddSubgroup ↥(idele F) := (ideleDiag F).range ⊔ (ideleNorm F K).range with hM
  have hle : N2 ≤ N1 := by
    refine sup_le_sup_left ?_ _
    rintro - ⟨x, rfl⟩
    exact ⟨ideleNorm F K x, ideleNorm_trans k F K x⟩
  set f : ↥(idele F) →+ ↥N1 :=
    (ideleNorm k F).codRestrict N1 fun x => AddSubgroup.mem_sup_right ⟨x, rfl⟩ with hf
  have hrel : N2.relIndex N1 ∣ M.index := by
    refine index_dvd_index_of_transfer f (fun b hb => ?_) fun a => ?_
    · obtain ⟨-, ⟨u, rfl⟩, -, ⟨d, rfl⟩, rfl⟩ := AddSubgroup.mem_sup.mp hb
      show (f _ : ↥(idele k)) ∈ N2
      show ideleNorm k F _ ∈ N2
      rw [map_add]
      refine AddSubgroup.add_mem _ (AddSubgroup.mem_sup_left (ideleNorm_ideleDiag_mem k F u)) ?_
      exact AddSubgroup.mem_sup_right ⟨d, (ideleNorm_trans k F K d).symm⟩
    · obtain ⟨-, ⟨u, rfl⟩, -, ⟨x, rfl⟩, ha⟩ := AddSubgroup.mem_sup.mp a.2
      refine ⟨x, ?_⟩
      show ((a : ↥(idele k)) - ideleNorm k F x) ∈ N2
      rw [← ha, add_sub_cancel_right]
      exact AddSubgroup.mem_sup_left ⟨u, rfl⟩
  rw [← AddSubgroup.relIndex_mul_index hle, mul_comm N1.index M.index]
  exact mul_dvd_mul hrel dvd_rfl

end Tower

/-! ### The norm index of a cyclic extension -/

section Cyclic

universe u

/-- The norm index of a trivial extension is one: every idele of the base field is the norm of
itself, read in the extension. -/
theorem index_eq_one_of_card_aut_eq_one {k K : Type*} [Field k] [NumberField k] [Field K]
    [NumberField K] [Algebra k K] [IsGalois k K] (hcard : Nat.card Gal(K/k) = 1) :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = 1 := by
  have htop : (ideleDiag k).range ⊔ (ideleNorm k K).range = ⊤ := by
    rw [eq_top_iff]
    intro a _
    refine AddSubgroup.mem_sup_right ⟨ideleComap k K a, ?_⟩
    rw [ideleNorm_ideleComap k K, hcard, one_nsmul]
  rw [htop, AddSubgroup.index_top]

set_option synthInstance.maxHeartbeats 800000 in
set_option maxHeartbeats 1000000 in
/-- The index of the principal ideles together with the norms of a cyclic extension is the degree,
for a base field and an extension in the same universe.  A prime dividing the degree gives a
subgroup of that index, whose fixed field is a step of prime degree over the base field; the count
for that step is known, the count for the remaining cyclic extension is smaller, and the tower
bounds the count for the whole extension by their product, which the first inequality matches. -/
private theorem index_aux (n : ℕ) : ∀ {k K : Type u} [Field k] [NumberField k] [Field K]
    [NumberField K] [Algebra k K] [IsGalois k K], IsCyclic Gal(K/k) →
    Nat.card Gal(K/k) = n → ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro k K _ _ _ _ _ _ hcyc hcard
    rcases eq_or_ne n 1 with rfl | hn1
    · exact index_eq_one_of_card_aut_eq_one hcard
    have hnpos : 0 < n := hcard ▸ Nat.card_pos
    obtain ⟨p, hp, hpd⟩ := Nat.exists_prime_and_dvd hn1
    obtain ⟨σ, hσ⟩ := hcyc.exists_generator
    -- the subgroup of index `p`, and its fixed field
    set H : Subgroup Gal(K/k) := Subgroup.zpowers (σ ^ p) with hH
    haveI : H.Normal :=
      ⟨fun x hx g => by
        rw [IsCyclic.commutative.comm g x, mul_assoc, mul_inv_cancel, mul_one]; exact hx⟩
    set E : IntermediateField k K := IntermediateField.fixedField H with hE
    haveI : NumberField ↥E := NumberField.of_module_finite k ↥E
    -- the degrees of the two steps
    have hord : orderOf σ = n := by
      rw [← Nat.card_zpowers, (Subgroup.eq_top_iff' _).mpr hσ, Subgroup.card_top, hcard]
    have hcardH : Nat.card ↥H = n / p := by
      rw [hH, Nat.card_zpowers, orderOf_pow, hord, Nat.gcd_eq_right hpd]
    have hEK : Module.finrank ↥E K = n / p := by
      rw [hE, IntermediateField.finrank_fixedField_eq_card, hcardH]
    have hkK : Module.finrank k K = n := by rw [← IsGalois.card_aut_eq_finrank, hcard]
    have hmul : Module.finrank k ↥E * Module.finrank ↥E K = n := by
      rw [Module.finrank_mul_finrank, hkK]
    have hpn : p * (n / p) = n := Nat.mul_div_cancel' hpd
    have hqpos : 0 < n / p := Nat.div_pos (Nat.le_of_dvd hnpos hpd) hp.pos
    have hkE : Module.finrank k ↥E = p := by
      refine Nat.eq_of_mul_eq_mul_right hqpos ?_
      rw [← hEK] at hpn ⊢
      rw [hmul, hpn]
    -- the upper step is again cyclic
    haveI : IsCyclic Gal(K/↥E) :=
      isCyclic_of_surjective (IntermediateField.subgroupEquivAlgEquiv H).toMonoidHom
        (MulEquiv.surjective _)
    have hcardE : Nat.card Gal(K/↥E) = n / p := by
      rw [IsGalois.card_aut_eq_finrank, hEK]
    -- the count in each step
    have hlow : ((ideleDiag ↥E).range ⊔ (ideleNorm ↥E K).range).index = n / p :=
      ih (n / p) (Nat.div_lt_self hnpos hp.one_lt) inferInstance hcardE
    have hupp : ((ideleDiag k).range ⊔ (ideleNorm k ↥E).range).index = p :=
      index_ideleDiag_sup_ideleNorm_eq_of_prime_degree hp hkE
    have hdvd := index_dvd_mul_index_of_tower (k := k) (F := ↥E) (K := K)
    rw [hlow, hupp, hpn] at hdvd
    haveI : NeZero n := ⟨hnpos.ne'⟩
    exact le_antisymm (Nat.le_of_dvd hnpos hdvd) (first_inequality_index hσ hcard)

set_option synthInstance.maxHeartbeats 800000 in
set_option maxHeartbeats 1000000 in
/-- **The index of the principal ideles together with the norms of a cyclic extension is the
degree.**  Interposing the fixed field of the whole Galois group, which is the base field, puts the
base field and the extension in a common universe. -/
theorem index_ideleDiag_sup_ideleNorm_eq_card {k K : Type*} [Field k] [NumberField k]
    [Field K] [NumberField K] [Algebra k K] [IsGalois k K] [IsCyclic Gal(K/k)] :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = Nat.card Gal(K/k) := by
  set n := Nat.card Gal(K/k) with hn
  set H : Subgroup Gal(K/k) := ⊤ with hH
  set E : IntermediateField k K := IntermediateField.fixedField H with hE
  haveI : NumberField ↥E := NumberField.of_module_finite k ↥E
  haveI : IsCyclic Gal(K/↥E) :=
    isCyclic_of_surjective (IntermediateField.subgroupEquivAlgEquiv H).toMonoidHom
      (MulEquiv.surjective _)
  have hEK : Module.finrank ↥E K = n := by
    rw [hE, IntermediateField.finrank_fixedField_eq_card, hH, Subgroup.card_top]
  have hcardE : Nat.card Gal(K/↥E) = n := by rw [IsGalois.card_aut_eq_finrank, hEK]
  have hkK : Module.finrank k K = n := (IsGalois.card_aut_eq_finrank k K).symm
  have hmul : Module.finrank k ↥E * Module.finrank ↥E K = n := by
    rw [Module.finrank_mul_finrank, hkK]
  rw [hEK] at hmul
  have hnpos : 0 < n := Nat.card_pos
  have hkE : Module.finrank k ↥E = 1 := Nat.eq_of_mul_eq_mul_right hnpos (by rw [hmul, one_mul])
  have hcardEk : Nat.card Gal(↥E/k) = 1 := by rw [IsGalois.card_aut_eq_finrank, hkE]
  have hupp : ((ideleDiag k).range ⊔ (ideleNorm k ↥E).range).index = 1 :=
    index_eq_one_of_card_aut_eq_one hcardEk
  have hlow : ((ideleDiag ↥E).range ⊔ (ideleNorm ↥E K).range).index = n :=
    index_aux n (k := ↥E) (K := K) inferInstance hcardE
  have hdvd := index_dvd_mul_index_of_tower (k := k) (F := ↥E) (K := K)
  rw [hupp, hlow, one_mul] at hdvd
  haveI : NeZero n := ⟨hnpos.ne'⟩
  obtain ⟨σ, hσ⟩ := IsCyclic.exists_generator (α := Gal(K/k))
  exact le_antisymm (Nat.le_of_dvd hnpos hdvd) (first_inequality_index hσ hn.symm)

/-- The index of the principal ideles together with the norms of a cyclic extension is the degree
of the extension. -/
theorem index_ideleDiag_sup_ideleNorm_eq_finrank {k K : Type*} [Field k] [NumberField k]
    [Field K] [NumberField K] [Algebra k K] [IsGalois k K] [IsCyclic Gal(K/k)] :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = Module.finrank k K := by
  rw [index_ideleDiag_sup_ideleNorm_eq_card, IsGalois.card_aut_eq_finrank]

end Cyclic

end InverseGalois.CFT
