/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Units.CompletionGalois

/-!
# Reading a local `p`-th power off the decomposition group

Let `M / K` be a Galois extension of number fields whose base contains a primitive `p`-th root of
unity, let `b` be an element of `M` whose `p`-th power `a` lies in `K`, and let `w` be a prime of
`M`.  Then `a` is a `p`-th power in the completion of `K` below `w` exactly when the decomposition
group at `w` fixes `b`.

Both directions run through the completion at `w`, of which the completion of `K` below is the
fixed field of the decomposition group.  If the decomposition group fixes `b` then `b` comes from
the completion below, and so does a `p`-th root of `a` there.  Conversely a `p`-th root of `a` in
the completion below differs from `b` by a `p`-th root of unity, and every `p`-th root of unity
already lies in the base field, so `b` too comes from the completion below and is fixed.

The criterion is what turns the statement that certain decomposition groups generate the Galois
group into the statement that an element which is locally a `p`-th power at the corresponding
places is globally one: an element fixed by every decomposition group in a generating family is
fixed by the whole group.

## Main results

* `InverseGalois.CFT.forall_stabilizer_smul_eq_iff_exists_pow`: **the decomposition group at a
  prime fixes a radical exactly when its `p`-th power is a local `p`-th power there.**
* `InverseGalois.CFT.smul_eq_self_of_mem_closure_stabilizer`: an automorphism in the subgroup
  generated by the decomposition groups at primes where the `p`-th power is a local `p`-th power
  fixes the radical.

## Tags

number field, completion, decomposition group, Kummer theory, local power
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

section Action

variable {K M : Type*} [Field K] [NumberField K] [Field M] [NumberField M] [Algebra K M]
  (w : HeightOneSpectrum (𝓞 M))

omit [NumberField K] in
/-- The decomposition group acts on the completion through its action on the field. -/
theorem stabilizer_smul_toAdicCompletion (σ : ↥(stabilizer Gal(M/K) w)) (x : M) :
    σ • toAdicCompletion w x = toAdicCompletion w ((σ : Gal(M/K)) x) := by
  rw [stabilizer_smul_adicCompletion_def, toAdicCompletion_apply, adicCompletionAut_coe]
  rfl

end Action

section LocalPower

variable {K M : Type*} [Field K] [NumberField K] [Field M] [NumberField M] [Algebra K M]
  [IsGalois K M] (w : HeightOneSpectrum (𝓞 M)) {p : ℕ}

/-- **The decomposition group at a prime fixes a radical exactly when the radicand is a `p`-th
power in the completion below**, the base field containing the `p`-th roots of unity.  An element
of the completion at the prime is fixed by the decomposition group exactly when it comes from the
completion below, and the radical is determined by the radicand up to a root of unity, which lies
in the base field. -/
theorem forall_stabilizer_smul_eq_iff_exists_pow {ζ : K} (hζ : IsPrimitiveRoot ζ p) (hp : p ≠ 0)
    {b : M} {a : K} (ha : algebraMap K M a = b ^ p) :
    (∀ σ : ↥(stabilizer Gal(M/K) w), (σ : Gal(M/K)) b = b) ↔
      ∃ c : (primeUnder (𝓞 K) w).adicCompletion K,
        c ^ p = algebraMap K ((primeUnder (𝓞 K) w).adicCompletion K) a := by
  haveI : NeZero p := ⟨hp⟩
  set Kv := (primeUnder (𝓞 K) w).adicCompletion K with hKv
  set Mw := w.adicCompletion M with hMw
  have htower : ∀ x : K, algebraMap Kv Mw (algebraMap K Kv x)
      = toAdicCompletion w (algebraMap K M x) := by
    intro x
    rw [← IsScalarTower.algebraMap_apply K Kv Mw, IsScalarTower.algebraMap_apply K M Mw]
    rfl
  have hinjKv : Function.Injective (algebraMap Kv Mw) := (algebraMap Kv Mw).injective
  have hinjM : Function.Injective (toAdicCompletion w (K := M)) :=
    (toAdicCompletion w (K := M)).injective
  constructor
  · intro h
    have hfix : ∀ σ : ↥(stabilizer Gal(M/K) w), σ • toAdicCompletion w b = toAdicCompletion w b :=
      fun σ => by rw [stabilizer_smul_toAdicCompletion, h σ]
    obtain ⟨c, hc⟩ :=
      (mem_range_algebraMap_iff_forall_stabilizer_smul_eq K w (toAdicCompletion w b)).mp hfix
    refine ⟨c, hinjKv ?_⟩
    rw [map_pow, hc, htower, ha, map_pow]
  · rintro ⟨c, hc⟩
    intro σ
    refine hinjM ?_
    rw [← stabilizer_smul_toAdicCompletion]
    revert σ
    rw [mem_range_algebraMap_iff_forall_stabilizer_smul_eq K w (toAdicCompletion w b)]
    have hd : (algebraMap Kv Mw c) ^ p = (toAdicCompletion w b) ^ p := by
      rw [← map_pow, hc, htower, ha, map_pow]
    rcases eq_or_ne b 0 with rfl | hb
    · exact ⟨0, by rw [map_zero, map_zero]⟩
    have hbne : toAdicCompletion w b ≠ 0 := fun h => hb (hinjM (by simpa using h))
    have hu : (algebraMap Kv Mw c / toAdicCompletion w b) ^ p = 1 := by
      rw [div_pow, hd, div_self (pow_ne_zero p hbne)]
    have hζM : IsPrimitiveRoot (algebraMap K Mw ζ) p :=
      hζ.map_of_injective (algebraMap K Mw).injective
    obtain ⟨j, -, hj⟩ := hζM.eq_pow_of_pow_eq_one hu
    have hζ0 : algebraMap K Mw ζ ≠ 0 := by
      intro h0
      have := hζM.pow_eq_one
      rw [h0, zero_pow hp] at this
      exact zero_ne_one this
    refine ⟨c * algebraMap K Kv (ζ ^ j)⁻¹, ?_⟩
    have hmap : algebraMap Kv Mw (algebraMap K Kv (ζ ^ j)⁻¹) = ((algebraMap K Mw ζ) ^ j)⁻¹ := by
      rw [← IsScalarTower.algebraMap_apply K Kv Mw, map_inv₀, map_pow]
    have hj' : algebraMap Kv Mw c = (algebraMap K Mw ζ) ^ j * toAdicCompletion w b :=
      ((eq_div_iff hbne).mp hj).symm
    rw [map_mul, hmap, hj', mul_right_comm, mul_inv_cancel₀ (pow_ne_zero j hζ0), one_mul]

variable {w}

/-- **An automorphism generated by the decomposition groups at primes where the radicand is a local
`p`-th power fixes the radical.**  Each such decomposition group fixes it, and the automorphisms
fixing an element form a subgroup. -/
theorem smul_eq_self_of_mem_closure_stabilizer {ζ : K} (hζ : IsPrimitiveRoot ζ p) (hp : p ≠ 0)
    {b : M} {a : K} (ha : algebraMap K M a = b ^ p)
    {W : Set (HeightOneSpectrum (𝓞 M))}
    (hW : ∀ w ∈ W, ∃ c : (primeUnder (𝓞 K) w).adicCompletion K,
      c ^ p = algebraMap K ((primeUnder (𝓞 K) w).adicCompletion K) a)
    {σ : Gal(M/K)}
    (hσ : σ ∈ Subgroup.closure (⋃ w ∈ W, (stabilizer Gal(M/K) w : Set Gal(M/K)))) :
    σ b = b := by
  have hle : Subgroup.closure (⋃ w ∈ W, (stabilizer Gal(M/K) w : Set Gal(M/K)))
      ≤ stabilizer Gal(M/K) b := by
    rw [Subgroup.closure_le]
    rintro τ hτ
    simp only [Set.mem_iUnion, SetLike.mem_coe, exists_prop] at hτ
    obtain ⟨w, hw, hτw⟩ := hτ
    exact (forall_stabilizer_smul_eq_iff_exists_pow w hζ hp ha).mpr (hW w hw) ⟨τ, hτw⟩
  exact hle hσ

end LocalPower

end InverseGalois.CFT
