/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.Pairing

/-!
# Prescribing an automorphism by a character of a subgroup

A saturated subgroup of the units of a field carries a family of radicands which is independent and
spanning modulo `p`-th powers, and an automorphism of the extension generated by their `p`-th roots
is described by the exponent vector recording the root of unity it introduces at each radicand.  A
radical of an element of the subgroup is then fixed exactly when the exponent vector of the
automorphism is orthogonal, modulo `p`, to the exponent vector of the element.

To prescribe an automorphism one is therefore given a character of a subgroup of the subgroup,
trivial on the `p`-th powers it contains, and must find an exponent vector computing it.  The
character factors through the classes modulo `p`-th powers, a finite group killed by `p`, so it is
a character of a subgroup of that finite group; and a character of a subgroup of a finite
commutative group extends to the whole group as soon as the values are taken in a field with enough
roots of unity.  Extending and evaluating at the radicands yields the exponent vector.

The resulting automorphism fixes the radical of an element of the smaller subgroup exactly when the
character is trivial there — and, two `p`-th roots of the same element differing by a root of unity
in the base, this does not depend on which radical is chosen.

## Main results

* `InverseGalois.CFT.finite_monoidHom_units_of_pow_eq_one`: a finite commutative group killed by
  `p` has finitely many characters with values in the units of a field.
* `InverseGalois.CFT.exists_monoidHom_extend_of_pow`: **a character of a subgroup, trivial on the
  `p`-th powers it contains, extends to a character of the larger subgroup trivial on every `p`-th
  power.**
* `InverseGalois.CFT.PowBasis.exists_expVector`: **such a character is computed by an exponent
  vector** read against the exponent vector of the element.
* `InverseGalois.CFT.PowBasis.exists_aut_fix_iff_of_character`: **there is an automorphism of the
  extension generated by the `p`-th roots of the radicands fixing the radical of an element of the
  smaller subgroup exactly when the character is trivial there.**

## Tags

Kummer theory, character, radical extension, saturated subgroup, root of unity, duality
-/

namespace InverseGalois.CFT

/-! ### Characters of a group killed by an exponent -/

section FiniteChar

variable {K : Type*} [Field K] {p : ℕ} [NeZero p]

omit [NeZero p] in
/-- A product of powers of a fixed element of a commutative group is the power at the sum of the
exponents. -/
theorem prod_zpow_eq_zpow_sum_group {G : Type*} [CommGroup G] {ι : Type*} (s : Finset ι) (x : G)
    (f : ι → ℤ) : ∏ i ∈ s, x ^ f i = x ^ ∑ i ∈ s, f i := by
  classical
  induction s using Finset.induction with
  | empty => simp
  | insert a s ha ih => rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, zpow_add]

/-- A character trivial on the kernel of a homomorphism descends to a character of its image. -/
theorem exists_monoidHom_of_ker_le {A G M : Type*} [Group A] [Group G] [Monoid M] (f : A →* G)
    (Φ : A →* M) (hker : ∀ x : A, x ∈ f.ker → Φ x = 1) :
    ∃ Ψ : ↥(f.range) →* M, ∀ x : A, Ψ (f.rangeRestrict x) = Φ x := by
  refine ⟨(QuotientGroup.lift f.ker Φ hker).comp
    (QuotientGroup.quotientKerEquivRange f).symm.toMonoidHom, fun x => ?_⟩
  have hex : (QuotientGroup.quotientKerEquivRange f) (QuotientGroup.mk x : A ⧸ f.ker)
      = f.rangeRestrict x := rfl
  rw [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, ← hex, MulEquiv.symm_apply_apply]
  rfl

/-- **A finite commutative group killed by `p` has only finitely many characters with values in the
units of a field**, every value being a `p`-th root of unity and a field having only finitely many
of those. -/
theorem finite_monoidHom_units_of_pow_eq_one {G : Type*} [CommGroup G] [Finite G]
    (hG : ∀ g : G, g ^ p = 1) : Finite (G →* Kˣ) := by
  have hmem : ∀ (f : G →* Kˣ) (g : G), f g ∈ rootsOfUnity p K := by
    intro f g
    rw [mem_rootsOfUnity, ← _root_.map_pow, hG g, _root_.map_one]
  refine Finite.of_injective
    (fun f : G →* Kˣ => fun g : G => (⟨f g, hmem f g⟩ : rootsOfUnity p K)) fun f₁ f₂ h => ?_
  refine DFunLike.ext _ _ fun g => ?_
  exact Subtype.ext_iff.mp (congrFun h g)

end FiniteChar

/-! ### Extending a character of a subgroup modulo `p`-th powers -/

section Extend

variable {K : Type*} [Field K] {p : ℕ} [NeZero p] [HasEnoughRootsOfUnity K p]

/-- **A character of a subgroup of a subgroup of the units of a field, trivial on the `p`-th powers
it contains, extends to a character of the larger subgroup trivial on every `p`-th power**, as soon
as the larger subgroup has finitely many classes modulo `p`-th powers.  The character factors
through those classes, and a character of a subgroup of a finite commutative group extends. -/
theorem exists_monoidHom_extend_of_pow {B : Subgroup Kˣ} (hfin : Finite (powQuotient B p))
    {U : Subgroup Kˣ} (hU : U ≤ B) (Φ : ↥U →* Kˣ)
    (hΦ : ∀ (u : Kˣ) (hu : u ∈ U) (y : Kˣ), u = y ^ p → Φ ⟨u, hu⟩ = 1) :
    ∃ Ψ : ↥B →* Kˣ, (∀ (u : Kˣ) (hu : u ∈ U), Ψ ⟨u, hU hu⟩ = Φ ⟨u, hu⟩) ∧
      ∀ y : ↥B, Ψ (y ^ p) = 1 := by
  haveI := hfin
  set q : ↥B →* powQuotient B p := QuotientGroup.mk' _ with hq
  set U' : Subgroup ↥B := U.comap B.subtype with hU'
  have hmemU : ∀ x : ↥U', ((x : ↥B) : Kˣ) ∈ U := fun x => Subgroup.mem_comap.mp x.2
  let ι : ↥U' →* ↥U :=
    { toFun := fun x => ⟨((x : ↥B) : Kˣ), hmemU x⟩
      map_one' := Subtype.ext rfl
      map_mul' := fun _ _ => Subtype.ext rfl }
  set Φ' : ↥U' →* Kˣ := Φ.comp ι with hΦ'
  set f : ↥U' →* powQuotient B p := q.comp U'.subtype with hf
  -- the character is trivial on the kernel of the class map
  have hker : ∀ x : ↥U', x ∈ f.ker → Φ' x = 1 := by
    intro x hx
    rw [MonoidHom.mem_ker, hf, MonoidHom.comp_apply, hq, QuotientGroup.mk'_apply,
      QuotientGroup.eq_one_iff] at hx
    obtain ⟨y, hy⟩ := hx
    have hxy : (x : ↥B) = y ^ p := by
      rw [← powMonoidHom_apply p y, hy]
      rfl
    have hxyK : ((x : ↥B) : Kˣ) = ((y : Kˣ)) ^ p := by
      rw [hxy]
      norm_cast
    exact hΦ _ (hmemU x) ((y : Kˣ)) hxyK
  -- descend it to the image of the smaller subgroup in the classes
  obtain ⟨Φbar, hΦbar⟩ := exists_monoidHom_of_ker_le f Φ' hker
  -- extend it to all of the classes
  haveI : HasEnoughRootsOfUnity K (Monoid.exponent (powQuotient B p)) :=
    HasEnoughRootsOfUnity.of_dvd K
      (Monoid.exponent_dvd_of_forall_pow_eq_one pow_eq_one_powQuotient)
  haveI : Finite (powQuotient B p →* Kˣ) :=
    finite_monoidHom_units_of_pow_eq_one (K := K) pow_eq_one_powQuotient
  haveI : Finite (↥(f.range) →* Kˣ) := by
    refine finite_monoidHom_units_of_pow_eq_one (K := K) (p := p) (G := ↥(f.range)) fun h => ?_
    ext
    simpa using pow_eq_one_powQuotient (h : powQuotient B p)
  obtain ⟨Ψbar, hΨ⟩ := MonoidHom.restrict_surjective (powQuotient B p) K f.range Φbar
  refine ⟨Ψbar.comp q, ?_, ?_⟩
  · intro u hu
    set x : ↥U' := ⟨⟨u, hU hu⟩, hu⟩ with hx
    have h1 := DFunLike.congr_fun hΨ (f.rangeRestrict x)
    rw [MonoidHom.restrictHom_apply, MonoidHom.restrict_apply] at h1
    have h2 : (Ψbar.comp q) ⟨u, hU hu⟩ = Ψbar ((f.rangeRestrict x : powQuotient B p)) := rfl
    rw [h2, h1, hΦbar x]
    rfl
  · intro y
    have hqy : q (y ^ p) = 1 := by
      rw [_root_.map_pow]
      exact pow_eq_one_powQuotient (q y)
    rw [MonoidHom.comp_apply, hqy, _root_.map_one]

end Extend

/-! ### Reading a character off a power basis -/

namespace PowBasis

section ExpVector

variable {K : Type*} [Field K] {p s : ℕ} {B : Subgroup Kˣ}

/-- **A character of a subgroup of a saturated subgroup with a power basis, trivial on the `p`-th
powers it contains, is computed by an exponent vector**: the character is trivial at an element of
the smaller subgroup exactly when the exponent vector is orthogonal, modulo `p`, to the exponent
vector of the element in the power basis. -/
theorem exists_expVector (P : PowBasis B p s) (hp : p.Prime) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hfin : Finite (powQuotient B p)) (hsat : ∀ y : Kˣ, y ^ p ∈ B → y ∈ B)
    {U : Subgroup Kˣ} (hU : U ≤ B) (Φ : ↥U →* Kˣ)
    (hΦ : ∀ (u : Kˣ) (hu : u ∈ U) (y : Kˣ), u = y ^ p → Φ ⟨u, hu⟩ = 1) :
    ∃ c : Fin s → ℤ, ∀ (u : Kˣ) (hu : u ∈ U) (m : Fin s → ℤ) (z : Kˣ),
      u = (∏ i, P.g i ^ m i) * z ^ p → (Φ ⟨u, hu⟩ = 1 ↔ (p : ℤ) ∣ ∑ i, c i * m i) := by
  haveI : NeZero p := ⟨hp.ne_zero⟩
  haveI : HasEnoughRootsOfUnity K p := ⟨⟨ζ, hζ⟩, inferInstance⟩
  set ζu : Kˣ := (hζ.isUnit hp.ne_zero).unit with hζudef
  have hζu : IsPrimitiveRoot ζu p := hζ.isUnit_unit hp.ne_zero
  obtain ⟨Ψ, hΨU, hΨp⟩ := exists_monoidHom_extend_of_pow hfin hU Φ hΦ
  -- the value at each radicand is a power of the root of unity
  have hval : ∀ i : Fin s, ∃ c : ℤ, Ψ ⟨P.g i, P.mem i⟩ = ζu ^ c := by
    intro i
    have h1 : (Ψ ⟨P.g i, P.mem i⟩) ^ p = 1 := by
      rw [← _root_.map_pow]
      exact hΨp _
    obtain ⟨j, -, hj⟩ := hζu.eq_pow_of_mem_rootsOfUnity ((mem_rootsOfUnity p _).mpr h1)
    exact ⟨(j : ℤ), by rw [zpow_natCast, hj]⟩
  choose c hc using hval
  refine ⟨c, fun u hu m z hm => ?_⟩
  -- the correction factor lies in the subgroup, by saturation
  have hprod : (∏ i, P.g i ^ m i) ∈ B := Subgroup.prod_mem _ fun i _ => zpow_mem (P.mem i) _
  have hzB : z ∈ B := by
    refine hsat z ?_
    have hz : z ^ p = (∏ i, P.g i ^ m i)⁻¹ * u := by rw [hm, inv_mul_cancel_left]
    rw [hz]
    exact Subgroup.mul_mem _ (Subgroup.inv_mem _ hprod) (hU hu)
  -- expand the element in the power basis and evaluate
  have hb : (⟨u, hU hu⟩ : ↥B) = (∏ i, (⟨P.g i, P.mem i⟩ : ↥B) ^ m i) * (⟨z, hzB⟩ : ↥B) ^ p := by
    refine Subtype.ext ?_
    push_cast
    exact hm
  have hstep : ∀ i : Fin s, Ψ ((⟨P.g i, P.mem i⟩ : ↥B) ^ m i) = ζu ^ (c i * m i) := by
    intro i
    rw [map_zpow, hc i, ← zpow_mul]
  have hΨu : Ψ ⟨u, hU hu⟩ = ζu ^ (∑ i, c i * m i) := by
    rw [hb, _root_.map_mul, hΨp, mul_one, _root_.map_prod,
      Finset.prod_congr rfl fun i _ => hstep i, prod_zpow_eq_zpow_sum_group]
  rw [← hΨU u hu, hΨu]
  exact hζu.zpow_eq_one_iff_dvd _

end ExpVector

/-! ### The automorphism prescribed by a character -/

section Prescribe

variable {K : Type*} [Field K] [CharZero K] {p s : ℕ} {B : Subgroup Kˣ}

/-- **A character of a subgroup of a saturated subgroup with a power basis, trivial on the `p`-th
powers it contains, is realised by an automorphism** of the extension generated by the `p`-th roots
of the radicands: the automorphism fixes a `p`-th root of an element of the smaller subgroup exactly
when the character is trivial there.  Two `p`-th roots of the same element differ by a root of unity
in the base, so the condition does not depend on the root chosen. -/
theorem exists_aut_fix_iff_of_character (P : PowBasis B p s) (hp : p.Prime) {ζ : K}
    (hζ : IsPrimitiveRoot ζ p) (hfin : Finite (powQuotient B p))
    (hsat : ∀ y : Kˣ, y ^ p ∈ B → y ∈ B) {U : Subgroup Kˣ} (hU : U ≤ B) (Φ : ↥U →* Kˣ)
    (hΦ : ∀ (u : Kˣ) (hu : u ∈ U) (y : Kˣ), u = y ^ p → Φ ⟨u, hu⟩ = 1) :
    ∃ σ : P.ext ≃ₐ[K] P.ext, ∀ (u : Kˣ) (hu : u ∈ U) (w : P.ext),
      w ^ p = algebraMap K P.ext (u : K) → (σ w = w ↔ Φ ⟨u, hu⟩ = 1) := by
  haveI : NeZero p := ⟨hp.ne_zero⟩
  obtain ⟨c, hc⟩ := P.exists_expVector hp hζ hfin hsat hU Φ hΦ
  obtain ⟨σ, hσ⟩ := P.exists_aut_radOf_iff hζ c
  refine ⟨σ, fun u hu w hw => ?_⟩
  obtain ⟨m, z, hm⟩ := P.span u (hU hu)
  have hwne : w ≠ 0 := by
    intro h
    rw [h, zero_pow hp.ne_zero] at hw
    exact Units.ne_zero u ((map_eq_zero _).mp hw.symm)
  have hpow : w ^ p = P.radOf m z ^ p := by rw [hw, P.radOf_pow_of_span hm]
  rw [aut_fix_iff_of_pow_eq hζ σ hwne (P.radOf_ne_zero m z) hpow, hσ m z]
  exact (hc u hu m z hm).symm

end Prescribe

end PowBasis

end InverseGalois.CFT
