/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.Unramified

/-!
# The quadratic character cut out by a square root

A square root `δ` of a rational number inside a number field `M` is moved by the Galois group of
`M` over the rationals through signs, and the resulting sign is a character of that Galois group.
Sending the nontrivial sign to a prescribed element of order dividing two of an arbitrary group
turns the sign into a character with values in that group, which is what the twisting step of an
embedding problem consumes.

The character is trivial on the inertia group at every place at which the radicand is a unit and
which does not lie over two: such a place is unramified in the extension generated by the square
root.  For the four radicands `1, -1, 2, -2` this means every place away from two.

## Main results

* `InverseGalois.CFT.sqrtChar`: **the character of the Galois group attached to a square root** and
  an element of order dividing two.
* `InverseGalois.CFT.sqrtChar_eq_one_of_mem_inertia`: **the character is trivial on the inertia
  group at a place away from two** at which the radicand is one of `1, -1, 2, -2`.

## Tags

number field, quadratic character, square root, inertia, ramification, Kummer theory
-/

namespace InverseGalois.CFT

open IsDedekindDomain NumberField

variable {M : Type*} [Field M] [NumberField M] {G : Type*} [Group G]

/-! ### The sign of a square root -/

/-- **An automorphism moves a square root of a rational number to plus or minus itself.** -/
theorem eq_or_eq_neg_of_sq_intCast {δ : M} {d : ℤ} (hδ : δ ^ 2 = (d : M)) (σ : Gal(M/ℚ)) :
    σ δ = δ ∨ σ δ = -δ := by
  have hsq : (σ δ) ^ 2 = δ ^ 2 := by rw [← map_pow, hδ, map_intCast]
  have hfac : (σ δ - δ) * (σ δ + δ) = 0 := by linear_combination hsq
  rcases mul_eq_zero.mp hfac with h | h
  · exact Or.inl (sub_eq_zero.mp h)
  · exact Or.inr (eq_neg_of_add_eq_zero_left h)

open scoped Classical in
/-- **The character of the Galois group attached to a square root** and an element of order
dividing two: an automorphism is sent to the identity when it fixes the square root and to the
prescribed element when it does not. -/
noncomputable def sqrtChar (δ : M) {z : G} (hz : z ^ 2 = 1)
    (hsq : ∀ σ : Gal(M/ℚ), σ δ = δ ∨ σ δ = -δ) (hδ : δ ≠ 0) : Gal(M/ℚ) →* G where
  toFun σ := if σ δ = δ then 1 else z
  map_one' := by simp
  map_mul' σ τ := by
    have hneg : -δ ≠ δ := by
      intro h
      refine hδ ?_
      have h2 : (2 : M) * δ = 0 := by linear_combination -h
      exact (mul_eq_zero.mp h2).resolve_left two_ne_zero
    have happ : (σ * τ) δ = σ (τ δ) := rfl
    rcases hsq σ with hσ | hσ <;> rcases hsq τ with hτ | hτ
    · have h1 : (σ * τ) δ = δ := by rw [happ, hτ, hσ]
      rw [if_pos h1, if_pos hσ, if_pos hτ, one_mul]
    · have hτ' : ¬ τ δ = δ := by rw [hτ]; exact hneg
      have h1 : ¬ (σ * τ) δ = δ := by rw [happ, hτ, map_neg, hσ]; exact hneg
      rw [if_neg h1, if_pos hσ, if_neg hτ', one_mul]
    · have hσ' : ¬ σ δ = δ := by rw [hσ]; exact hneg
      have h1 : ¬ (σ * τ) δ = δ := by rw [happ, hτ, hσ]; exact hneg
      rw [if_neg h1, if_neg hσ', if_pos hτ, mul_one]
    · have hσ' : ¬ σ δ = δ := by rw [hσ]; exact hneg
      have hτ' : ¬ τ δ = δ := by rw [hτ]; exact hneg
      have h1 : (σ * τ) δ = δ := by rw [happ, hτ, map_neg, hσ, neg_neg]
      rw [if_pos h1, if_neg hσ', if_neg hτ', ← sq, hz]

open scoped Classical in
theorem sqrtChar_apply {δ : M} {z : G} (hz : z ^ 2 = 1)
    (hsq : ∀ σ : Gal(M/ℚ), σ δ = δ ∨ σ δ = -δ) (hδ : δ ≠ 0) (σ : Gal(M/ℚ)) :
    sqrtChar δ hz hsq hδ σ = if σ δ = δ then 1 else z := rfl

theorem sqrtChar_eq_one {δ : M} {z : G} (hz : z ^ 2 = 1)
    (hsq : ∀ σ : Gal(M/ℚ), σ δ = δ ∨ σ δ = -δ) (hδ : δ ≠ 0) {σ : Gal(M/ℚ)} (h : σ δ = δ) :
    sqrtChar δ hz hsq hδ σ = 1 := by
  classical
  rw [sqrtChar_apply, if_pos h]

/-- **The character attached to a square root takes only two values.**  Its range therefore lies in
any subgroup containing the prescribed element. -/
theorem sqrtChar_range_le {δ : M} {z : G} (hz : z ^ 2 = 1)
    (hsq : ∀ σ : Gal(M/ℚ), σ δ = δ ∨ σ δ = -δ) (hδ : δ ≠ 0) {N : Subgroup G} (hzN : z ∈ N) :
    (sqrtChar δ hz hsq hδ).range ≤ N := by
  classical
  rintro _ ⟨σ, rfl⟩
  rw [sqrtChar_apply]
  split
  · exact N.one_mem
  · exact hzN

/-! ### Unramifiedness away from two -/

/-- **The four rational radicands are units at every place away from two.** -/
theorem valuation_intCast_eq_one_of_two_notMem {w : HeightOneSpectrum (𝓞 M)}
    (hw : (2 : 𝓞 M) ∉ w.asIdeal) {d : ℤ} (hd : d = 1 ∨ d = -1 ∨ d = 2 ∨ d = -2) :
    (primeUnder (𝓞 ℚ) w).valuation ℚ ((d : ℤ) : ℚ) = 1 := by
  set v : HeightOneSpectrum (𝓞 ℚ) := primeUnder (𝓞 ℚ) w with hv
  have h2 : v.valuation ℚ (2 : ℚ) = 1 := by
    have hmem : (2 : 𝓞 ℚ) ∉ v.asIdeal := by
      intro h
      rw [hv, primeUnder_asIdeal] at h
      exact hw (by simpa [map_ofNat] using Ideal.mem_comap.mp h)
    have hcast : (2 : ℚ) = algebraMap (𝓞 ℚ) ℚ (2 : 𝓞 ℚ) := by rw [map_ofNat]
    rw [hcast, HeightOneSpectrum.valuation_of_algebraMap]
    refine le_antisymm (v.intValuation_le_one _) ?_
    by_contra hlt
    push_neg at hlt
    exact hmem ((v.intValuation_lt_one_iff_mem _).mp hlt)
  rcases hd with rfl | rfl | rfl | rfl
  · simp
  · rw [show (((-1 : ℤ) : ℚ)) = -1 by norm_num, Valuation.map_neg]
    exact map_one (v.valuation ℚ)
  · rw [show (((2 : ℤ) : ℚ)) = 2 by norm_num]
    exact h2
  · rw [show (((-2 : ℤ) : ℚ)) = -2 by norm_num, Valuation.map_neg]
    exact h2

/-- **The character attached to a square root of one of `1, -1, 2, -2` is trivial on the inertia
group at every place away from two.**  The radicand is a unit at such a place, so the place does
not ramify in the extension generated by the square root. -/
theorem sqrtChar_eq_one_of_mem_inertia {δ : M} {z : G} (hz : z ^ 2 = 1)
    (hsq : ∀ σ : Gal(M/ℚ), σ δ = δ ∨ σ δ = -δ) (hδ : δ ≠ 0) {d : ℤ}
    (hd : d = 1 ∨ d = -1 ∨ d = 2 ∨ d = -2) (hδd : δ ^ 2 = (d : M))
    {w : HeightOneSpectrum (𝓞 M)} (hw : (2 : 𝓞 M) ∉ w.asIdeal)
    {σ : Gal(M/ℚ)} (hσ : σ ∈ Ideal.inertia Gal(M/ℚ) w.asIdeal) :
    sqrtChar δ hz hsq hδ σ = 1 := by
  have hpow : δ ^ 2 = algebraMap ℚ M ((d : ℤ) : ℚ) := by rw [hδd, map_intCast]
  have hζ : IsPrimitiveRoot (-1 : ℚ) 2 := IsPrimitiveRoot.neg_one 0 (by norm_num)
  refine sqrtChar_eq_one hz hsq hδ ?_
  exact eq_of_mem_inertia_of_radical Nat.prime_two hζ (by simpa using hw) hσ
    (valuation_intCast_eq_one_of_two_notMem hw hd) hpow

end InverseGalois.CFT
