/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.CyclotomicPlace
import InverseGalois.CFT.Units.PlaceComap

/-!
# The local data at a place of large ramification

The adic valuation of a rational prime at a place of a number field above it is read off the
ramification index: the prime below is generated by the rational prime, so its valuation is one
step below one, and the valuation upstairs raises that to the ramification index.

At a place above `ℓ` in a number field containing a primitive `ℓ`-th root of unity `ζ` the
ramification index is at least `ℓ - 1`, because `ζ - 1` divides `ℓ` to that depth.  So as soon as
the ramification index times the residue degree is at most `ℓ - 1` both are pinned: the ramification
index is exactly `ℓ - 1` and the residue degree is one.  That is exactly the situation in which
`ζ - 1` is a uniformiser and the residue field is the prime field, so the local data at a
cyclotomic place is available.

## Main results

* `InverseGalois.CFT.valuation_natCast_eq_exp_neg_ramificationIdx`: **the valuation of a rational
  prime at a place above it** is the exponential of minus the ramification index.
* `InverseGalois.CFT.ramificationIdx_eq_of_mul_le`: **the exact values of the two invariants** at a
  place above `ℓ` whose ramification index times residue degree is at most `ℓ - 1`, together with
  the valuation of `ζ - 1`.
* `InverseGalois.CFT.isCyclotomicPlace_of_mul_le`: **the local data at a place above `ℓ` whose
  ramification index times residue degree is at most `ℓ - 1`**.

## Tags

number field, ramification index, residue degree, adic valuation, cyclotomic place
-/

namespace InverseGalois.CFT

open scoped WithZero

open IsDedekindDomain NumberField WithZero

variable {K : Type*} [Field K] [NumberField K] {p : ℕ}

/-! ### The valuation of the residue characteristic -/

/-- The ramification index of a place over the rational prime it lies above. -/
theorem ramIdx_eq_ramificationIdx_span (v : HeightOneSpectrum (𝓞 K))
    [hover : v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] :
    ramIdx ℤ v =
      Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(p : ℤ)}) v.asIdeal := by
  rw [ramIdx, primeUnder_asIdeal, ← hover.over]

/-- The ramification index of a place over the rational prime it lies above is nonzero. -/
theorem ramificationIdx_span_ne_zero (v : HeightOneSpectrum (𝓞 K))
    [v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] :
    Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(p : ℤ)}) v.asIdeal ≠ 0 :=
  ramIdx_eq_ramificationIdx_span (p := p) v ▸ ramIdx_ne_zero (A := ℤ) v

/-- **The valuation of a rational prime at a place above it is the exponential of minus the
ramification index.**  The prime of `ℤ` below is generated by the rational prime, so its valuation
there is one step below one, and the comparison of the two adic valuations raises that to the
ramification index. -/
theorem valuation_natCast_eq_exp_neg_ramificationIdx (hp : p.Prime)
    (v : HeightOneSpectrum (𝓞 K)) [hover : v.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] :
    v.valuation K ((p : ℕ) : K) =
      exp (-(Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(p : ℤ)})
        v.asIdeal : ℤ)) := by
  have hunder : (primeUnder ℤ v).asIdeal = Ideal.span {(p : ℤ)} := by
    rw [primeUnder_asIdeal, ← hover.over]
  have hp0 : (p : ℤ) ≠ 0 := by exact_mod_cast hp.ne_zero
  have hbase : (primeUnder ℤ v).valuation ℚ ((p : ℕ) : ℚ) = exp (-1 : ℤ) := by
    rw [show ((p : ℕ) : ℚ) = algebraMap ℤ ℚ (p : ℤ) by push_cast; ring,
      HeightOneSpectrum.valuation_of_algebraMap]
    exact HeightOneSpectrum.intValuation_singleton _ hp0 hunder
  rw [show ((p : ℕ) : K) = algebraMap ℚ K ((p : ℕ) : ℚ) by push_cast; ring,
    valuation_algebraMap (A := ℤ) (B := 𝓞 K) v ((p : ℕ) : ℚ), hbase, ← exp_nsmul,
    ramIdx_eq_ramificationIdx_span (p := p) v]
  congr 1
  simp

/-! ### The local data at a place of large ramification -/

variable {ℓ g : ℕ}

/-- **A place above `ℓ` whose ramification index times residue degree is at most `ℓ - 1` is
totally and tamely pinned.**  Since `ζ - 1` divides `ℓ` to the depth `ℓ - 1`, the bound forces the
ramification index to be exactly `ℓ - 1` and the residue degree to be one, and `ζ - 1` is a
uniformiser. -/
theorem ramificationIdx_eq_of_mul_le (hℓ : ℓ.Prime) {ζ : K} (hζ : IsPrimitiveRoot ζ ℓ)
    (v : HeightOneSpectrum (𝓞 K)) [v.asIdeal.LiesOver (Ideal.span {(ℓ : ℤ)})]
    (hle : Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(ℓ : ℤ)}) v.asIdeal *
      (Ideal.span {(ℓ : ℤ)}).inertiaDeg v.asIdeal ≤ ℓ - 1) :
    Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(ℓ : ℤ)}) v.asIdeal = ℓ - 1 ∧
      (Ideal.span {(ℓ : ℤ)}).inertiaDeg v.asIdeal = 1 ∧
      v.valuation K (ζ - 1) = exp (-1 : ℤ) := by
  have hl2 : 2 ≤ ℓ := hℓ.two_le
  have he0 : Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(ℓ : ℤ)}) v.asIdeal ≠ 0 :=
    ramificationIdx_span_ne_zero (p := ℓ) v
  have hvl := valuation_natCast_eq_exp_neg_ramificationIdx hℓ v
  set e := Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(ℓ : ℤ)}) v.asIdeal with hedef
  set f := (Ideal.span {(ℓ : ℤ)}).inertiaDeg v.asIdeal with hfdef
  haveI := isMaximal_span_prime hℓ
  have hf0 : 0 < f := Ideal.inertiaDeg_pos _ _
  -- the bound on the product bounds the ramification index
  have hef : e ≤ ℓ - 1 := le_trans (Nat.le_mul_of_pos_right e hf0) hle
  have hlt1 : v.valuation K ((ℓ : ℕ) : K) < 1 := by
    rw [hvl, ← exp_zero (M := ℤ), exp_lt_exp]
    omega
  have hpow : v.valuation K ((ℓ : ℕ) : K) = v.valuation K (ζ - 1) ^ (ℓ - 1) :=
    valuation_natCast_eq_pow hℓ hζ v
  have hπ1 : v.valuation K (ζ - 1) < 1 := by
    by_contra hcon
    push_neg at hcon
    exact absurd (hpow ▸ one_le_pow₀ hcon) (not_le.mpr hlt1)
  have hle' : (exp (-((ℓ : ℤ) - 1)) : ℤᵐ⁰) ≤ v.valuation K ((ℓ : ℕ) : K) := by
    rw [hvl, exp_le_exp]
    omega
  have hunif : v.valuation K (ζ - 1) = exp (-1 : ℤ) :=
    valuation_sub_one_eq_exp_neg_one hℓ hζ v hπ1 hle'
  -- the ramification index is exactly `ℓ - 1`, and then the residue degree is one
  have hee : e = ℓ - 1 := by
    have h1 : (exp (-(e : ℤ)) : ℤᵐ⁰) = exp ((ℓ - 1) • (-1 : ℤ)) := by
      rw [← hvl, hpow, hunif, exp_nsmul]
    rw [exp_inj, nsmul_eq_mul, mul_neg, mul_one] at h1
    omega
  have hff : f = 1 := by
    rw [hee] at hle
    by_contra hne
    have h2 : 2 ≤ f := by omega
    have h3 : (ℓ - 1) * 2 ≤ (ℓ - 1) * f := Nat.mul_le_mul le_rfl h2
    have h4 : (ℓ - 1) * 2 ≤ ℓ - 1 := le_trans h3 hle
    omega
  exact ⟨hee, hff, hunif⟩

/-- **The local data at a place above `ℓ` whose ramification index times residue degree is at most
`ℓ - 1`.**  The bound pins the two invariants, so `ζ - 1` is a uniformiser and the residue field is
the prime field. -/
theorem isCyclotomicPlace_of_mul_le (hℓ : ℓ.Prime) {ζ : K} (hζ : IsPrimitiveRoot ζ ℓ)
    (v : HeightOneSpectrum (𝓞 K)) [v.asIdeal.LiesOver (Ideal.span {(ℓ : ℤ)})]
    (hle : Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(ℓ : ℤ)}) v.asIdeal *
      (Ideal.span {(ℓ : ℤ)}).inertiaDeg v.asIdeal ≤ ℓ - 1)
    (δ : K →+* K) (hδv : ∀ x : K, v.valuation K (δ x) = v.valuation K x) (hδζ : δ ζ = ζ ^ g)
    (hg : ∀ n : ℕ, 1 ≤ n → n + 1 ≤ ℓ → ((ℓ : ℤ) ∣ (g : ℤ) ^ n - g) → n = 1)
    (hg1 : ¬ ((ℓ : ℤ) ∣ (g : ℤ) - 1)) :
    IsCyclotomicPlace ℓ g (v.valuation K) (ζ - 1) δ (RingHom.id K) := by
  obtain ⟨-, hff, hunif⟩ := ramificationIdx_eq_of_mul_le hℓ hζ v hle
  exact isCyclotomicPlace_of_ringHom hℓ hζ v hff hunif δ hδv hδζ hg hg1

end InverseGalois.CFT
