/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.LocalPower
import InverseGalois.CFT.Kummer.LocalSurjective
import InverseGalois.CFT.Kummer.RootIndex
import InverseGalois.CFT.Kummer.SUnitUnramified
import InverseGalois.CFT.Kummer.Unramified
import InverseGalois.CFT.Units.ClassSet
import InverseGalois.CFT.Units.IdeleClassIndex
import InverseGalois.CFT.Units.PowSIdeleClass
import InverseGalois.CFT.Units.PowSIdeleNorm
import InverseGalois.CFT.Units.PrimeAbove

/-!
# The norm index of a cyclic radical extension of prime degree

Let `k` be a number field containing a primitive `p`-th root of unity, let `S` be a finite set of
finite places carrying the ideal classes and every prime above `p`, and let `K` be the extension of
degree `p` generated by a `p`-th root of an `S`-unit `a` which is not a `p`-th power.  The index of
the principal ideles together with the norms from `K` is exactly `p`.

The lower bound is the first inequality.  For the upper bound one counts.  Let `M` be the extension
of `k` generated by the `p`-th roots of all the `S`-units, of degree `p ^ s` where `s` is the number
of places of `S` counted with the infinite ones; the subgroup of its Galois group fixing a `p`-th
root of `a` has index `p`, and an auxiliary finite set `T` of places, disjoint from `S`, indexes a
family of decomposition groups generating it, so that its order is `p ^ #T` and `s = #T + 1`.

At the places of `T` the element `a` is a local `p`-th power, so `K` splits completely there; away
from `S` and `T` the extension `K` is unramified, its radicand being a unit.  The ideles which are
local `p`-th powers at the infinite places and on `S` and units outside `S ∪ T` are therefore norms
from `K`.  The relative index of that subgroup together with the principal ideles inside all the
ideles is `p ^ (2 * s) / p ^ (s + #T)`, which is `p` because `s = #T + 1`.

Every extension of prime degree of such a base is of this shape: it is cyclic, hence generated by a
root of a polynomial `X ^ p - a`, and the set of places may be enlarged to carry the ideal classes,
the primes above `p` and the places at which `a` is not a unit.

## Main results

* `InverseGalois.CFT.index_ideleDiag_sup_ideleNorm_of_radical`: **the index of the principal ideles
  together with the norms from a cyclic radical extension of prime degree is the degree.**
* `InverseGalois.CFT.index_ideleDiag_sup_ideleNorm_of_prime_degree`: **the same for an arbitrary
  extension of prime degree of a base carrying the roots of unity.**

## Tags

number field, idele, norm index, second inequality, Kummer theory, prime degree
-/

universe u

namespace InverseGalois.CFT

open IntermediateField IsDedekindDomain MulAction NumberField Rigidity.RET

/-! ### Transporting an index into the full product -/

section Transport

/-- The relative index of the image of a subgroup of a subgroup is the index upstairs. -/
theorem addRelIndex_map_subtype {G : Type*} [AddGroup G] {H : AddSubgroup G} (N : AddSubgroup H) :
    (N.map H.subtype).relIndex H = N.index := by
  show (AddSubgroup.comap H.subtype (N.map H.subtype)).index = N.index
  rw [AddSubgroup.comap_map_eq_self_of_injective H.subtype_injective]

end Transport

/-! ### The index -/

section SecondInequality

variable {k : Type u} [Field k] [NumberField k] {K : Type*} [Field K] [NumberField K]
  [Algebra k K] [IsGalois k K] {p : ℕ} {ζ : k} {Y : Type*} [Fintype Y]
  {ι : Y → HeightOneSpectrum (𝓞 k)}

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 2000000

/-- **The index of the principal ideles together with the norms from a cyclic radical extension of
prime degree is the degree.**  The lower bound is the first inequality; the upper bound compares the
subgroup of ideles which are local `p`-th powers on the distinguished set of places with the norms,
the extension splitting completely at the auxiliary places and being unramified outside. -/
theorem index_ideleDiag_sup_ideleNorm_of_radical (hp : p.Prime) (hζ : IsPrimitiveRoot ζ p)
    (hdeg : Module.finrank k K = p) (hinj : Function.Injective ι)
    (hpS : ∀ v : HeightOneSpectrum (𝓞 k), (p : 𝓞 k) ∈ v.asIdeal → v ∈ Set.range ι)
    (hrepr : ∀ m : HeightOneSpectrum (𝓞 k) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 k) in Filter.cofinite, m v = 0) →
      ∃ b : kˣ, ∀ v ∉ Set.range ι, ord k v (b : k) = m v)
    {a : kˣ} (ha : a ∈ sUnits k (Set.range ι)) (hnot : ∀ y : kˣ, a ≠ y ^ p)
    {β : K} (hβ : β ^ p = algebraMap k K (a : k))
    (hgenβ : IntermediateField.adjoin k ({β} : Set K) = ⊤) :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = p := by
  classical
  haveI : NeZero p := ⟨hp.ne_zero⟩
  haveI : Fact p.Prime := ⟨hp⟩
  haveI : HasEnoughRootsOfUnity k p := ⟨⟨ζ, hζ⟩, rootsOfUnity.isCyclic k p⟩
  -- the Kummer extension generated by the `p`-th roots of all the `S`-units
  obtain ⟨P⟩ := nonempty_powBasis_sUnits (ι := ι) hp hinj
  haveI : IsGalois k P.ext := P.isGalois_ext hζ
  obtain ⟨wa, hwa⟩ := P.exists_root ha
  have hpX : ∀ v : HeightOneSpectrum (𝓞 k),
      Valued.v ((p : ℕ) : v.adicCompletion k) ≠ 1 → v ∈ Set.range ι := fun v hv => by
    by_contra hc
    exact hv ((valued_natCast_eq_one_iff k v p).mpr fun h => hc (hpS v h))
  obtain ⟨T, hT1, -, hTcard, hTloc, hTsurj⟩ :=
    exists_finset_primes_sUnitSurj hp hζ hpX P (card_powQuotient_sUnits hinj) ha hnot hwa
      fun w hw => P.isUnramifiedAt_ext hp hζ hpS w hw
  -- the number of auxiliary places is one less than the number of distinguished ones
  have hcardGal : Nat.card Gal(P.ext/k)
      = p ^ (Fintype.card (InfinitePlace k) + Fintype.card Y) := by
    rw [IsGalois.card_aut_eq_finrank, P.finrank_ext hζ]
  have hsT : Fintype.card (InfinitePlace k) + Fintype.card Y = T.card + 1 := by
    have h := Subgroup.card_mul_index (stabilizer Gal(P.ext/k) wa)
    rw [index_stabilizer_eq hp hcardGal hwa hnot, hcardGal, hTcard, ← pow_succ] at h
    exact (Nat.pow_right_injective hp.two_le h).symm
  -- the extension of degree `p`
  have hcardK : Nat.card Gal(K/k) = p := by rw [IsGalois.card_aut_eq_finrank, hdeg]
  haveI : IsCyclic Gal(K/k) := isCyclic_of_prime_card hcardK
  obtain ⟨σ, hσgen⟩ := IsCyclic.exists_generator (α := Gal(K/k))
  have hone : ∀ g : Gal(K/k), g β = β → g = 1 := by
    intro g hg
    have hmem : g ∈ (k⟮β⟯ : IntermediateField k K).fixingSubgroup := by
      rw [fixingSubgroup_adjoin_simple_eq_stabilizer]
      exact hg
    rw [hgenβ] at hmem
    exact AlgEquiv.ext fun x => hmem ⟨x, IntermediateField.mem_top⟩
  have hsplitT : ∀ v : HeightOneSpectrum (𝓞 K), primeUnder (𝓞 k) v ∉ Set.range ι →
      primeUnder (𝓞 k) v ∈ (T : Set (HeightOneSpectrum (𝓞 k))) →
      stabilizer Gal(K/k) v = ⊥ := fun v _ hv =>
    (Subgroup.eq_bot_iff_forall _).mpr fun g hg => hone g
      ((forall_stabilizer_smul_eq_iff_exists_pow v hζ hp.ne_zero hβ.symm).mpr
        (hTloc _ (Finset.mem_coe.mp hv)) ⟨g, hg⟩)
  have hunram : ∀ v : HeightOneSpectrum (𝓞 K), primeUnder (𝓞 k) v ∉ Set.range ι →
      primeUnder (𝓞 k) v ∉ (T : Set (HeightOneSpectrum (𝓞 k))) →
      Algebra.IsUnramifiedAt (𝓞 k) v.asIdeal := by
    intro v hvS _
    refine isUnramifiedAt_of_radicals hp hζ (α := fun _ : Unit => β) (a := fun _ => (a : k))
      (fun _ => hβ) (by rwa [Set.range_const]) ?_
      fun _ => valuation_eq_one_of_mem_sUnits ha hvS
    intro hmem
    refine hvS (hpS _ ?_)
    rw [primeUnder_asIdeal, Ideal.under_def, Ideal.mem_comap, map_natCast]
    exact hmem
  -- the counting
  set F : Finset (HeightOneSpectrum (𝓞 k)) := Finset.univ.image ι with hFdef
  have hF : ∀ v, v ∈ F ↔ v ∈ Set.range ι := by
    intro v
    simp [hFdef, Set.mem_range, eq_comm]
  have hFcard : F.card = Fintype.card Y := by
    rw [hFdef, Finset.card_image_of_injective _ hinj, Finset.card_univ]
  have hdisj : Disjoint F T := Finset.disjoint_left.mpr fun v hv hvT => hT1 v hvT ((hF v).mp hv)
  have hG : ∀ v, v ∈ F ∪ T ↔ v ∈ Set.range ι ∪ (T : Set (HeightOneSpectrum (𝓞 k))) := by
    intro v
    rw [Finset.mem_union, Set.mem_union, hF, Finset.mem_coe]
  have hGcard : (F ∪ T).card = F.card + T.card := Finset.card_union_of_disjoint hdisj
  have hSfin : (Set.range ι).Finite := Set.finite_range ι
  have hTfin : (T : Set (HeightOneSpectrum (𝓞 k))).Finite := T.finite_toSet
  have hkey := relIndex_powSIdele_sup_range_fullDiag (K := k)
    (S := Set.range ι) (T := (T : Set (HeightOneSpectrum (𝓞 k)))) hp hζ F (F ∪ T) hF hG
    (fun v hv => (hF v).mpr (hpS v (by
      by_contra hc
      exact hv ((finitePlace_natCast_eq_one_iff v p).mpr hc))))
    (fun v hv => hT1 v (Finset.mem_coe.mp hv)) hpS hrepr hTsurj
  have hexp : 2 * (Fintype.card (InfinitePlace k) + F.card)
      = Fintype.card (InfinitePlace k) + (F ∪ T).card + 1 := by omega
  rw [hexp, pow_succ] at hkey
  have hrel := Nat.eq_of_mul_eq_mul_right
    (pow_pos hp.pos (Fintype.card (InfinitePlace k) + (F ∪ T).card))
    (hkey.trans (mul_comm _ _))
  -- the norms contain the local powers
  have hnorm : powSIdele (Set.range ι) (T : Set (HeightOneSpectrum (𝓞 k))) p ⊔ (fullDiag k).range
      ≤ AddSubgroup.map (idele k).subtype ((ideleDiag k).range ⊔ (ideleNorm k K).range) := by
    refine sup_le (fun x hx => ?_) ?_
    · refine ⟨⟨x, sIdele_le_idele _ _ hSfin hTfin (powSIdele_le_sIdele _ _ p hx)⟩,
        AddSubgroup.mem_sup_right ?_, rfl⟩
      exact powSIdele_le_range_ideleNorm hσgen hcardK hSfin hTfin hsplitT hunram hx
    · rintro _ ⟨u, rfl⟩
      exact ⟨ideleDiag k u, AddSubgroup.mem_sup_left ⟨u, rfl⟩, rfl⟩
  have hdvd : ((ideleDiag k).range ⊔ (ideleNorm k K).range).index ∣ p := by
    rw [← hrel, ← addRelIndex_map_subtype ((ideleDiag k).range ⊔ (ideleNorm k K).range)]
    exact AddSubgroup.relIndex_dvd_of_le_left _ hnorm
  exact le_antisymm (Nat.le_of_dvd hp.pos hdvd) (first_inequality_index hσgen hcardK)

end SecondInequality

/-! ### An arbitrary extension of prime degree -/

section PrimeDegree

variable {k : Type u} [Field k] [NumberField k] {K : Type*} [Field K] [NumberField K]
  [Algebra k K] [IsGalois k K] {p : ℕ} {ζ : k}

/-- **The index of the principal ideles together with the norms from an extension of prime degree
is the degree**, provided the base carries a primitive root of unity of that degree.  An extension
of prime degree is cyclic, so it is generated by a root of the polynomial `X ^ p - a`; enlarging the
set of distinguished places until it carries the ideal classes, the primes above `p` and the primes
at which `a` is not a unit puts the extension in the radical shape the count applies to. -/
theorem index_ideleDiag_sup_ideleNorm_of_prime_degree (hp : p.Prime) (hζ : IsPrimitiveRoot ζ p)
    (hdeg : Module.finrank k K = p) :
    ((ideleDiag k).range ⊔ (ideleNorm k K).range).index = p := by
  classical
  haveI : NeZero p := ⟨hp.ne_zero⟩
  haveI : Fact p.Prime := ⟨hp⟩
  have hcardK : Nat.card Gal(K/k) = p := by rw [IsGalois.card_aut_eq_finrank, hdeg]
  haveI : IsCyclic Gal(K/k) := isCyclic_of_prime_card hcardK
  -- a cyclic extension of a field carrying the roots of unity is radical
  have hprim : (primitiveRoots (Module.finrank k K) k).Nonempty := by
    rw [hdeg]
    exact ⟨ζ, (mem_primitiveRoots hp.pos).mpr hζ⟩
  obtain ⟨β, ⟨a₀, ha₀⟩, hgenβ⟩ := exists_root_adjoin_eq_top_of_isCyclic k K hprim
  have hirr : Irreducible ((Polynomial.X : Polynomial k) ^ p - Polynomial.C a₀) := by
    have h := irreducible_X_pow_sub_C_of_root_adjoin_eq_top ha₀.symm hgenβ
    rwa [hdeg] at h
  have hnotk : ∀ b : k, b ^ p ≠ a₀ := (X_pow_sub_C_irreducible_iff_of_prime hp).mp hirr
  have ha₀ne : a₀ ≠ 0 := fun h => hnotk 0 (by rw [zero_pow hp.ne_zero]; exact h.symm)
  obtain ⟨a, hval⟩ : ∃ a : kˣ, (a : k) = a₀ := ⟨Units.mk0 a₀ ha₀ne, rfl⟩
  have hnot : ∀ y : kˣ, a ≠ y ^ p := fun y hy =>
    hnotk (y : k) (by rw [← Units.val_pow_eq_pow_val, ← hy, hval])
  -- the distinguished places: the ideal classes, the primes above `p`, and the support of `a`
  have hpne : ((p : ℕ) : k) ≠ 0 := Nat.cast_ne_zero.mpr hp.ne_zero
  obtain ⟨T₀, hT₀fin, hT₀repr⟩ := exists_finite_ord_repr k
  set S : Set (HeightOneSpectrum (𝓞 k)) :=
    T₀ ∪ {v | ord k v (a : k) ≠ 0} ∪ {v | ord k v ((p : ℕ) : k) ≠ 0} with hSdef
  have hSfin : S.Finite :=
    (hT₀fin.union (Filter.eventually_cofinite.mp (ord_finite (K := k) (a : k)))).union
      (Filter.eventually_cofinite.mp (ord_finite (K := k) ((p : ℕ) : k)))
  haveI : Fintype ↥S := hSfin.fintype
  have hrange : Set.range (Subtype.val : ↥S → HeightOneSpectrum (𝓞 k)) = S := Subtype.range_coe
  refine index_ideleDiag_sup_ideleNorm_of_radical (ι := (Subtype.val : ↥S → _)) hp hζ hdeg
    Subtype.val_injective (fun v hv => ?_) (fun m hm => ?_) (a := a) (fun v hv => ?_) hnot
    (β := β) ?_ hgenβ
  · rw [hrange]
    exact Or.inr fun h0 => (valuation_natCast_eq_one_iff k v p).mp
      ((valuation_eq_one_iff_ord_eq_zero v hpne).mpr h0) hv
  · obtain ⟨b, hb⟩ := hT₀repr m hm
    exact ⟨b, fun v hv => hb v fun hvT => hv (by rw [hrange]; exact Or.inl (Or.inl hvT))⟩
  · rw [hrange] at hv
    by_contra h
    exact hv (Or.inl (Or.inr h))
  · rw [hval, ← hdeg]
    exact ha₀.symm

end PrimeDegree

end InverseGalois.CFT
