/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Counting the integral ideals of a given norm

Let `K` be a number field with ring of integers `𝓞 K`.  For a natural number `n` there are only
finitely many ideals of `𝓞 K` of absolute norm `n`, and the resulting counting function
`n ↦ #{I : Ideal (𝓞 K) // Ideal.absNorm I = n}` is exactly the coefficient sequence of the
Dedekind zeta function `NumberField.dedekindZeta`.

This file proves that the counting function is multiplicative and deduces the Euler product for
the Dedekind zeta function in the half plane of absolute convergence.

The multiplicativity is obtained from an explicit bijection.  If `m` and `n` are coprime then
multiplication of ideals identifies the pairs consisting of an ideal of norm `m` and an ideal of
norm `n` with the ideals of norm `m * n`; the inverse map sends an ideal `L` of norm `m * n` to the
pair `(L + (m), L + (n))`.  The two constructions are inverse to each other because the norm of an
ideal always belongs to that ideal, so that `(m)` and `(n)` already generate the unit ideal
together, and because an ideal of norm dividing `m * n` and containing `(m)` has norm dividing `m`.

Convergence is supplied by the classical count of ideals of bounded norm: the number of ideals of
norm at most `x` grows linearly in `x`, so the partial sums of the coefficients are `O(x)` and the
`L`-series converges absolutely to the right of `1`.

## Main results

* `IdealNormCount.card_absNorm_eq_one` — there is exactly one ideal of norm `1`, namely the unit
  ideal.
* `IdealNormCount.card_absNorm_mul` — for coprime `m` and `n` the number of ideals of norm `m * n`
  is the product of the number of ideals of norm `m` and the number of ideals of norm `n`.
* `IdealNormCount.normEquiv` — the bijection realising the previous statement.
* `IdealNormCount.isMultiplicative_idealCount` — the coefficient sequence of the Dedekind zeta
  function, viewed as an arithmetic function, is multiplicative.
* `IdealNormCount.lseriesSummable_card_absNorm` — the Dedekind zeta series converges absolutely
  for `1 < s.re`.
* `IdealNormCount.dedekindZeta_eulerProduct` — the Euler product for the Dedekind zeta function:
  for `1 < s.re` the value `dedekindZeta K s` is the product over the rational primes `p` of the
  local factor `∑' e, #{I : absNorm I = p ^ e} / (p ^ e) ^ s`.
-/

open NumberField Ideal Filter Asymptotics

namespace IdealNormCount

variable {K : Type*} [Field K] [NumberField K]

/-! ### The bijection behind multiplicativity -/

omit [NumberField K] in
/-- **Coprime integers generate the unit ideal of the ring of integers.**  A Bézout relation
`1 = a * m + b * n` in `ℤ` exhibits `1` as an element of the sum of the two principal ideals. -/
theorem sup_span_natCast_eq_top {m n : ℕ} (h : Nat.Coprime m n) :
    Ideal.span {((m : ℕ) : 𝓞 K)} ⊔ Ideal.span {((n : ℕ) : 𝓞 K)} = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  have hb : (1 : ℤ) = (m : ℤ) * Nat.gcdA m n + (n : ℤ) * Nat.gcdB m n := by
    have := Nat.gcd_eq_gcd_ab m n
    rw [Nat.Coprime] at h
    rw [h] at this
    exact_mod_cast this
  refine Submodule.mem_sup.2 ⟨((m : 𝓞 K)) * ((Nat.gcdA m n : ℤ) : 𝓞 K),
    Ideal.mul_mem_right _ _ (Ideal.subset_span rfl),
    ((n : 𝓞 K)) * ((Nat.gcdB m n : ℤ) : 𝓞 K),
    Ideal.mul_mem_right _ _ (Ideal.subset_span rfl), ?_⟩
  have := congrArg (fun z : ℤ => ((z : 𝓞 K))) hb.symm
  push_cast at this ⊢
  linear_combination this

/-- **The norm of an ideal generates a subideal of it.**  Indeed the absolute norm of an ideal is
one of its elements. -/
theorem span_absNorm_le (I : Ideal (𝓞 K)) :
    Ideal.span {((absNorm I : ℕ) : 𝓞 K)} ≤ I :=
  (Ideal.span_singleton_le_iff_mem _).2 (Ideal.absNorm_mem I)

/-- **An ideal is comaximal with any integer coprime to its norm.**  The norm of `I` lies in `I`,
and it generates the unit ideal together with `m`. -/
theorem sup_span_eq_top {I : Ideal (𝓞 K)} {m n : ℕ} (h : Nat.Coprime m n)
    (hI : absNorm I = n) : I ⊔ Ideal.span {((m : ℕ) : 𝓞 K)} = ⊤ := by
  refine top_le_iff.1 ?_
  rw [← sup_span_natCast_eq_top (K := K) h.symm]
  exact sup_le_sup_right (hI ▸ span_absNorm_le I) _

/-- **A factor of norm `m` is recovered from the product by adjoining `m`.**  If `I` has norm `m`
and `J` has norm `n` with `m` and `n` coprime, then `I` is the ideal generated by `I * J` and the
integer `m`. -/
theorem mul_sup_span_eq_left {I J : Ideal (𝓞 K)} {m n : ℕ} (h : Nat.Coprime m n)
    (hI : absNorm I = m) (hJ : absNorm J = n) :
    I * J ⊔ Ideal.span {((m : ℕ) : 𝓞 K)} = I := by
  refine le_antisymm (sup_le Ideal.mul_le_right (hI ▸ span_absNorm_le I)) ?_
  calc I = I * (J ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) := by rw [sup_span_eq_top h hJ, mul_top]
    _ = I * J ⊔ I * Ideal.span {((m : ℕ) : 𝓞 K)} := Ideal.mul_sup ..
    _ ≤ I * J ⊔ Ideal.span {((m : ℕ) : 𝓞 K)} := sup_le_sup_left Ideal.mul_le_left _

/-- **An ideal of norm `m * n` is the product of its `m`-part and its `n`-part.**  For coprime `m`
and `n` the two ideals obtained from `L` by adjoining `m`, respectively `n`, are comaximal, and
their product is `L` again. -/
theorem sup_span_mul_sup_span {L : Ideal (𝓞 K)} {m n : ℕ} (h : Nat.Coprime m n)
    (hL : absNorm L = m * n) :
    (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) * (L ⊔ Ideal.span {((n : ℕ) : 𝓞 K)}) = L := by
  have htop : (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) ⊔ (L ⊔ Ideal.span {((n : ℕ) : 𝓞 K)}) = ⊤ := by
    refine top_le_iff.1 ?_
    rw [← sup_span_natCast_eq_top (K := K) h]
    exact sup_le_sup le_sup_right le_sup_right
  refine le_antisymm ?_ ?_
  · rw [Ideal.sup_mul, Ideal.mul_sup, Ideal.mul_sup]
    refine sup_le (sup_le Ideal.mul_le_right Ideal.mul_le_right) (sup_le Ideal.mul_le_left ?_)
    rw [Ideal.span_singleton_mul_span_singleton]
    refine (Ideal.span_singleton_le_iff_mem _).2 ?_
    have := Ideal.absNorm_mem L
    rw [hL] at this
    push_cast at this ⊢
    exact this
  · rw [Ideal.mul_eq_inf_of_coprime htop]
    exact le_inf le_sup_left le_sup_left

/-- **The norm of the ideal generated by a rational integer is a power of that integer.**  The
exponent is the degree of the number field. -/
theorem absNorm_span_natCast (m : ℕ) :
    absNorm (Ideal.span {((m : ℕ) : 𝓞 K)}) = m ^ Module.finrank ℚ K := by
  rw [Ideal.absNorm_span_singleton,
    show ((m : ℕ) : 𝓞 K) = algebraMap ℤ (𝓞 K) (m : ℤ) by push_cast; ring,
    Algebra.norm_algebraMap_of_basis (RingOfIntegers.basis K),
    ← Module.finrank_eq_card_chooseBasisIndex, RingOfIntegers.rank]
  simp

/-- **Two divisors whose product is the product of their multiples are equal to them.**  If `a`
divides `m`, `b` divides `n` and `a * b = m * n` with `m` and `n` nonzero, then `a = m` and
`b = n`. -/
theorem eq_of_dvd_of_mul_eq {a b m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0)
    (ha : a ∣ m) (hb : b ∣ n) (hab : a * b = m * n) : a = m ∧ b = n := by
  have ham : a ≤ m := Nat.le_of_dvd (Nat.pos_of_ne_zero hm) ha
  have hbn : b ≤ n := Nat.le_of_dvd (Nat.pos_of_ne_zero hn) hb
  have ha0 : 0 < a := Nat.pos_of_ne_zero (by rintro rfl; simp at ha; omega)
  have hb0 : 0 < b := Nat.pos_of_ne_zero (by rintro rfl; simp at hb; omega)
  refine ⟨?_, ?_⟩
  · nlinarith
  · nlinarith

/-- **The `m`-part of an ideal of norm `m * n` has norm dividing `m`.**  Its norm divides `m * n`
because it contains the ideal, and it divides a power of `m` because it contains `m`. -/
theorem absNorm_sup_span_dvd {L : Ideal (𝓞 K)} {m n : ℕ} (h : Nat.Coprime m n)
    (hL : absNorm L = m * n) :
    absNorm (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) ∣ m := by
  have h1 : absNorm (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) ∣ m * n :=
    hL ▸ Ideal.absNorm_dvd_absNorm_of_le le_sup_left
  have h2 : absNorm (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) ∣ m ^ Module.finrank ℚ K :=
    absNorm_span_natCast (K := K) m ▸ Ideal.absNorm_dvd_absNorm_of_le le_sup_right
  exact (Nat.Coprime.coprime_dvd_left h2 (h.pow_left _)).dvd_of_dvd_mul_right h1

/-- **Splitting an ideal of norm `m * n` along coprime `m` and `n` gives ideals of norms `m` and
`n`.**  The two parts multiply back to the original ideal, so their norms multiply to `m * n`,
and each divides the intended value. -/
theorem absNorm_sup_span_eq {L : Ideal (𝓞 K)} {m n : ℕ} (h : Nat.Coprime m n) (hm : m ≠ 0)
    (hn : n ≠ 0) (hL : absNorm L = m * n) :
    absNorm (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) = m ∧
      absNorm (L ⊔ Ideal.span {((n : ℕ) : 𝓞 K)}) = n := by
  have hmul : absNorm (L ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}) *
      absNorm (L ⊔ Ideal.span {((n : ℕ) : 𝓞 K)}) = m * n := by
    rw [← map_mul, sup_span_mul_sup_span h hL, hL]
  exact eq_of_dvd_of_mul_eq hm hn (absNorm_sup_span_dvd h hL)
    (absNorm_sup_span_dvd h.symm (by rw [hL, mul_comm])) hmul

/-- **Multiplication of ideals is a bijection between pairs of ideals of coprime norms `m` and `n`
and the ideals of norm `m * n`.**  The inverse sends an ideal `L` to the pair obtained by adjoining
to `L` the integer `m`, respectively the integer `n`. -/
def normEquiv {m n : ℕ} (h : Nat.Coprime m n) (hm : m ≠ 0) (hn : n ≠ 0) :
    {I : Ideal (𝓞 K) // absNorm I = m} × {J : Ideal (𝓞 K) // absNorm J = n} ≃
      {L : Ideal (𝓞 K) // absNorm L = m * n} where
  toFun p := ⟨p.1.1 * p.2.1, by rw [map_mul, p.1.2, p.2.2]⟩
  invFun L := (⟨L.1 ⊔ Ideal.span {((m : ℕ) : 𝓞 K)}, (absNorm_sup_span_eq h hm hn L.2).1⟩,
    ⟨L.1 ⊔ Ideal.span {((n : ℕ) : 𝓞 K)}, (absNorm_sup_span_eq h hm hn L.2).2⟩)
  left_inv := by
    rintro ⟨⟨I, hI⟩, ⟨J, hJ⟩⟩
    refine Prod.ext (Subtype.ext ?_) (Subtype.ext ?_)
    · exact mul_sup_span_eq_left h hI hJ
    · show I * J ⊔ Ideal.span {((n : ℕ) : 𝓞 K)} = J
      rw [mul_comm I J]
      exact mul_sup_span_eq_left h.symm hJ hI
  right_inv := by
    rintro ⟨L, hL⟩
    exact Subtype.ext (sup_span_mul_sup_span h hL)

/-! ### Multiplicativity of the counting function -/

/-- **The unit ideal is the only ideal of norm one.** -/
theorem card_absNorm_eq_one : Nat.card {I : Ideal (𝓞 K) // absNorm I = 1} = 1 := by
  rw [Nat.card_eq_one_iff_unique]
  refine ⟨⟨fun a b => Subtype.ext ?_⟩, ⟨⟨⊤, absNorm_top⟩⟩⟩
  rw [absNorm_eq_one_iff.1 a.2, absNorm_eq_one_iff.1 b.2]

/-- **The number of integral ideals of a given norm is a multiplicative function of that norm.**
For coprime `m` and `n`, the ideals of norm `m * n` correspond bijectively to the pairs consisting
of an ideal of norm `m` and an ideal of norm `n`. -/
theorem card_absNorm_mul {m n : ℕ} (h : Nat.Coprime m n) :
    Nat.card {I : Ideal (𝓞 K) // absNorm I = m * n} =
      Nat.card {I : Ideal (𝓞 K) // absNorm I = m} *
        Nat.card {I : Ideal (𝓞 K) // absNorm I = n} := by
  rcases eq_or_ne m 0 with rfl | hm
  · rw [Nat.coprime_zero_left] at h
    subst h
    rw [card_absNorm_eq_one, mul_one, mul_one]
  rcases eq_or_ne n 0 with rfl | hn
  · rw [Nat.coprime_zero_right] at h
    subst h
    rw [card_absNorm_eq_one, one_mul, one_mul]
  rw [← Nat.card_prod, Nat.card_congr (normEquiv h hm hn)]

/-! ### Absolute convergence of the Dedekind zeta series -/

/-- **The partial sums of the counting function count the ideals of bounded norm.**  Adding the
zero ideal to the ideals of norm between `1` and `n` gives all ideals of norm at most `n`. -/
theorem sum_card_absNorm_Icc (n : ℕ) :
    (∑ k ∈ Finset.Icc 1 n, Nat.card {I : Ideal (𝓞 K) // absNorm I = k}) + 1
      = Nat.card {I : Ideal (𝓞 K) // absNorm I ≤ n} := by
  rw [show Finset.Icc 1 n = Finset.Ioc 0 n from Finset.Icc_succ_left_eq_Ioc _ _,
    show (1 : ℕ) = Nat.card {I : Ideal (𝓞 K) // absNorm I = 0} by
        simp [Ideal.absNorm_eq_zero_iff],
    Finset.sum_Ioc_add_eq_sum_Icc (n.zero_le),
    ← Finset.card_preimage_eq_sum_card_image_eq (fun k _ ↦ Ideal.finite_setOf_absNorm_eq k)]
  simp [Set.coe_eq_subtype]

/-- **The partial sums of the counting function, compared with a real bound on the norm.**  This
is the previous count phrased with the inequality read in `ℝ`. -/
theorem sum_card_absNorm_Icc' (n : ℕ) :
    (∑ k ∈ Finset.Icc 1 n, Nat.card {I : Ideal (𝓞 K) // absNorm I = k}) + 1
      = Nat.card {I : Ideal (𝓞 K) // (absNorm I : ℝ) ≤ (n : ℝ)} := by
  rw [sum_card_absNorm_Icc]
  exact Nat.card_congr (Equiv.subtypeEquivRight fun I ↦ by exact_mod_cast Iff.rfl)

/-- **The number of integral ideals of norm at most `x` grows at most linearly in `x`.**  This is
the boundedness contained in the asymptotic count of ideals of bounded norm. -/
theorem isBigO_card_absNorm_le :
    (fun x : ℝ ↦ (Nat.card {I : Ideal (𝓞 K) // (absNorm I : ℝ) ≤ x} : ℝ)) =O[atTop]
      (id : ℝ → ℝ) := by
  have h0 := (NumberField.Ideal.tendsto_norm_le_div_atTop K).isBigO_one ℝ
  refine (h0.mul (isBigO_refl (id : ℝ → ℝ) atTop)).congr' ?_ (.of_forall fun x ↦ (one_mul x))
  filter_upwards [eventually_ne_atTop (0 : ℝ)] with x hx
  simp [hx]

/-- **The partial sums of the ideal-counting function are `O(n)`.** -/
theorem isBigO_sum_card_absNorm :
    (fun n : ℕ ↦ ∑ k ∈ Finset.Icc 1 n, (Nat.card {I : Ideal (𝓞 K) // absNorm I = k} : ℝ))
      =O[atTop] fun n : ℕ ↦ (n : ℝ) ^ (1 : ℝ) := by
  have h2 := (isBigO_card_absNorm_le (K := K)).comp_tendsto
    (tendsto_natCast_atTop_atTop (R := ℝ))
  refine Asymptotics.IsBigO.trans ?_ (h2.congr (fun _ ↦ rfl) fun n ↦ by simp)
  refine Asymptotics.isBigO_of_le _ fun n ↦ ?_
  simp only [Function.comp_apply]
  have hle : (∑ k ∈ Finset.Icc 1 n, Nat.card {I : Ideal (𝓞 K) // absNorm I = k})
      ≤ Nat.card {I : Ideal (𝓞 K) // (absNorm I : ℝ) ≤ (n : ℝ)} := by
    rw [← sum_card_absNorm_Icc']
    omega
  rw [Real.norm_eq_abs, Real.norm_eq_abs, abs_of_nonneg (by positivity),
    abs_of_nonneg (by positivity), ← Nat.cast_sum]
  exact Nat.cast_le.2 hle

/-- **The Dedekind zeta series converges absolutely to the right of `1`.** -/
theorem lseriesSummable_card_absNorm {s : ℂ} (hs : 1 < s.re) :
    LSeriesSummable (fun n ↦ (Nat.card {I : Ideal (𝓞 K) // absNorm I = n} : ℂ)) s := by
  have := LSeriesSummable_of_sum_norm_bigO_and_nonneg (isBigO_sum_card_absNorm (K := K))
    (fun n ↦ Nat.cast_nonneg _) zero_le_one hs
  simpa using this

/-- **The terms of the Dedekind zeta series are norm-summable to the right of `1`.** -/
theorem summable_norm_term_card_absNorm {s : ℂ} (hs : 1 < s.re) :
    Summable fun n ↦
      ‖LSeries.term (fun n ↦ (Nat.card {I : Ideal (𝓞 K) // absNorm I = n} : ℂ)) s n‖ :=
  summable_norm_iff.2 (lseriesSummable_card_absNorm hs)

/-! ### The Dedekind zeta function as an `L`-series of a multiplicative arithmetic function -/

/-- **The ideal-counting function of a number field, as an arithmetic function.**  Away from `0`
its value at `n` is the number of integral ideals of norm `n`; at `0` it is set to zero, which does
not affect the associated `L`-series. -/
noncomputable def idealCount (K : Type*) [Field K] [NumberField K] : ArithmeticFunction ℂ where
  toFun n := if n = 0 then 0 else (Nat.card {I : Ideal (𝓞 K) // absNorm I = n} : ℂ)
  map_zero' := if_pos rfl

/-- **At a nonzero argument the ideal-counting arithmetic function counts ideals of that norm.** -/
theorem idealCount_apply {n : ℕ} (hn : n ≠ 0) :
    idealCount K n = (Nat.card {I : Ideal (𝓞 K) // absNorm I = n} : ℂ) := if_neg hn

/-- **The ideal-counting function of a number field is multiplicative.** -/
theorem isMultiplicative_idealCount : (idealCount K).IsMultiplicative := by
  refine ⟨by rw [idealCount_apply one_ne_zero, card_absNorm_eq_one, Nat.cast_one], ?_⟩
  intro m n h
  rcases eq_or_ne m 0 with rfl | hm
  · simp
  rcases eq_or_ne n 0 with rfl | hn
  · simp
  rw [idealCount_apply (mul_ne_zero hm hn), idealCount_apply hm, idealCount_apply hn,
    card_absNorm_mul h, Nat.cast_mul]

/-- **The Dedekind zeta function is the `L`-series of the ideal-counting arithmetic function.** -/
theorem dedekindZeta_eq_LSeries_idealCount (s : ℂ) :
    dedekindZeta K s = LSeries (idealCount K) s :=
  LSeries_congr (fun hn ↦ (idealCount_apply hn).symm) s

/-! ### The Euler product -/

/-- **The terms of the Dedekind zeta series are multiplicative in the index.** -/
theorem term_idealCount_mul {s : ℂ} {m n : ℕ} (h : Nat.Coprime m n) :
    LSeries.term (idealCount K) s (m * n)
      = LSeries.term (idealCount K) s m * LSeries.term (idealCount K) s n := by
  rcases eq_or_ne m 0 with rfl | hm
  · simp
  rcases eq_or_ne n 0 with rfl | hn
  · simp
  have hpow : ((m * n : ℕ) : ℂ) ^ s = (m : ℂ) ^ s * (n : ℂ) ^ s := by
    simpa only [Nat.cast_mul, Complex.ofReal_natCast]
      using Complex.mul_cpow_ofReal_nonneg (m.cast_nonneg (α := ℝ)) (n.cast_nonneg (α := ℝ)) s
  rw [LSeries.term_of_ne_zero (mul_ne_zero hm hn), LSeries.term_of_ne_zero hm,
    LSeries.term_of_ne_zero hn, div_mul_div_comm, hpow,
    (isMultiplicative_idealCount (K := K)).map_mul_of_coprime h]

/-- **The terms of the `L`-series of the ideal-counting arithmetic function are norm-summable to
the right of `1`.** -/
theorem summable_norm_term_idealCount {s : ℂ} (hs : 1 < s.re) :
    Summable fun n ↦ ‖LSeries.term (idealCount K) s n‖ := by
  refine (summable_norm_term_card_absNorm (K := K) hs).congr fun n ↦ ?_
  rw [LSeries.term_congr (fun hn ↦ (idealCount_apply hn).symm) s n]

/-- **The Euler product for the Dedekind zeta function, in terms of the `L`-series terms.**  For
`1 < s.re` the Dedekind zeta value is the product over the rational primes of the sum of the terms
indexed by the powers of that prime. -/
theorem dedekindZeta_eulerProduct_tprod {s : ℂ} (hs : 1 < s.re) :
    ∏' p : Nat.Primes, ∑' e : ℕ, LSeries.term (idealCount K) s ((p : ℕ) ^ e)
      = dedekindZeta K s := by
  rw [dedekindZeta_eq_LSeries_idealCount]
  refine EulerProduct.eulerProduct_tprod ?_ (fun h ↦ term_idealCount_mul h)
    (summable_norm_term_idealCount hs) (LSeries.term_zero _ _)
  rw [LSeries.term_of_ne_zero one_ne_zero, Nat.cast_one, Complex.one_cpow, div_one,
    (isMultiplicative_idealCount (K := K)).map_one]

/-- **The Euler product for the Dedekind zeta function.**  For `1 < s.re` the Dedekind zeta
function of `K` is the product over the rational primes `p` of the local factor obtained by summing
`#{I : absNorm I = p ^ e} / (p ^ e) ^ s` over all exponents `e`. -/
theorem dedekindZeta_eulerProduct {s : ℂ} (hs : 1 < s.re) :
    ∏' p : Nat.Primes, ∑' e : ℕ,
        (Nat.card {I : Ideal (𝓞 K) // absNorm I = (p : ℕ) ^ e} : ℂ) /
          (((p : ℕ) ^ e : ℕ) : ℂ) ^ s
      = dedekindZeta K s := by
  rw [← dedekindZeta_eulerProduct_tprod (K := K) hs]
  refine tprod_congr fun p ↦ tsum_congr fun e ↦ ?_
  rw [LSeries.term_of_ne_zero (pow_ne_zero e p.2.ne_zero),
    idealCount_apply (pow_ne_zero e p.2.ne_zero)]

end IdealNormCount
