/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Solutions of polynomial systems descend to the algebraically closed base

A finite system of polynomial equations with coefficients in an algebraically closed field `k` has
a solution in `k` as soon as it has a solution in *some* field extension `K`: a solution over `K`
certifies that the ideal generated by the system is proper, and a proper ideal of a polynomial ring
over an algebraically closed field has a zero, by the Nullstellensatz.  Inequations `q ≠ 0` are
allowed as well, by the Rabinowitsch trick of adjoining an inverse for each of them.

This is the transfer principle behind descending analytic constructions over `ℂ` to the
algebraically closed field `ℚ̄`: an object described by finitely many polynomial identities and
non-degeneracies in finitely many unknowns, and defined over `ℚ̄`, exists over `ℚ̄` as soon as it
exists over `ℂ`.

## Main results

* `Rigidity.RET.Transfer.nonempty_zeroLocus_of_nonempty` — the zero locus of an ideal over `k` is
  nonempty as soon as its zero locus over an extension field is.
* `Rigidity.RET.Transfer.exists_forall_aeval_eq_zero` — the same for a family of equations.
* `Rigidity.RET.Transfer.exists_solution` — equations together with inequations.
* `Rigidity.RET.Transfer.exists_specialization` — a point over an extension field specializes to a
  point over the algebraically closed field, keeping its identities and prescribed
  non-degeneracies.
* `Rigidity.RET.Transfer.exists_forall_map_eq_zero` — unknowns entering polynomial identities in
  one further indeterminate, and
* `Rigidity.RET.Transfer.exists_forall_map_map_eq_zero` — in two.
-/

open MvPolynomial

namespace Rigidity.RET.Transfer

variable {k K : Type*} [Field k] [IsAlgClosed k] [Field K] [Algebra k K]
variable {σ : Type*} [Finite σ]

/-- **A polynomial system over an algebraically closed field which is solvable over an extension
field is solvable over the field itself.**

A point of the zero locus over `K` witnesses that the ideal is proper; a maximal ideal above it is
the vanishing ideal of a point of `k ^ σ`, by the Nullstellensatz, and that point is a zero of the
original ideal. -/
theorem nonempty_zeroLocus_of_nonempty (I : Ideal (MvPolynomial σ k))
    (h : (zeroLocus K I).Nonempty) : (zeroLocus k I).Nonempty := by
  obtain ⟨x, hx⟩ := h
  have hne : I ≠ ⊤ := by
    intro htop
    have h1 : (1 : K) = 0 := by simpa using hx 1 (htop ▸ Submodule.mem_top)
    exact one_ne_zero h1
  obtain ⟨J, hJ, hIJ⟩ := Ideal.exists_le_maximal I hne
  obtain ⟨y, hy⟩ := eq_vanishingIdeal_singleton_of_isMaximal (k := k) k hJ
  exact ⟨y, fun p hp => (mem_vanishingIdeal_singleton_iff y p).1 (hy ▸ hIJ hp)⟩

/-- **A family of polynomial equations over an algebraically closed field which has a solution in
an extension field has a solution in the field itself.** -/
theorem exists_forall_aeval_eq_zero {ι : Type*} (p : ι → MvPolynomial σ k)
    (h : ∃ x : σ → K, ∀ i, aeval x (p i) = 0) :
    ∃ y : σ → k, ∀ i, aeval y (p i) = 0 := by
  obtain ⟨x, hx⟩ := h
  have hmem : x ∈ zeroLocus K (Ideal.span (Set.range p)) := by
    rw [zeroLocus_span]
    rintro _ ⟨i, rfl⟩
    exact hx i
  obtain ⟨y, hy⟩ := nonempty_zeroLocus_of_nonempty (K := K) _ ⟨x, hmem⟩
  rw [zeroLocus_span] at hy
  exact ⟨y, fun i => hy _ ⟨i, rfl⟩⟩

/-- **A polynomial system with inequations over an algebraically closed field which is solvable
over an extension field is solvable over the field itself.**

The inequations are turned into equations by the Rabinowitsch trick: one new unknown for each
inequation, constrained to be its inverse. -/
theorem exists_solution {ι κ : Type*} [Finite κ] (p : ι → MvPolynomial σ k)
    (q : κ → MvPolynomial σ k)
    (h : ∃ x : σ → K, (∀ i, aeval x (p i) = 0) ∧ ∀ j, aeval x (q j) ≠ 0) :
    ∃ y : σ → k, (∀ i, aeval y (p i) = 0) ∧ ∀ j, aeval y (q j) ≠ 0 := by
  classical
  obtain ⟨x, hp, hq⟩ := h
  -- the extended system: the original equations, and `q j * uⱼ = 1` for the new unknowns `uⱼ`
  set e : ι ⊕ κ → MvPolynomial (σ ⊕ κ) k :=
    Sum.elim (fun i => rename Sum.inl (p i))
      (fun j => rename Sum.inl (q j) * X (Sum.inr j) - 1) with he
  have hsol : ∃ x' : σ ⊕ κ → K, ∀ n, aeval x' (e n) = 0 := by
    refine ⟨Sum.elim x fun j => (aeval x (q j))⁻¹, ?_⟩
    rintro (i | j)
    · simpa [he, aeval_rename, Function.comp_def] using hp i
    · have : aeval (Sum.elim x fun j => (aeval x (q j))⁻¹) (rename Sum.inl (q j))
          = aeval x (q j) := by
        simp [aeval_rename, Function.comp_def]
      simp only [he, Sum.elim_inr, map_sub, map_mul, map_one, this, aeval_X, Sum.elim_inr]
      rw [mul_inv_cancel₀ (hq j), sub_self]
  obtain ⟨y', hy'⟩ := exists_forall_aeval_eq_zero (K := K) e hsol
  refine ⟨fun s => y' (Sum.inl s), fun i => ?_, fun j => ?_⟩
  · have := hy' (Sum.inl i)
    simpa [he, aeval_rename, Function.comp_def] using this
  · have h0 := hy' (Sum.inr j)
    have hrn : aeval y' (rename Sum.inl (q j)) = aeval (fun s => y' (Sum.inl s)) (q j) := by
      simp [aeval_rename, Function.comp_def]
    simp only [he, Sum.elim_inr, map_sub, map_mul, map_one, hrn, aeval_X, sub_eq_zero] at h0
    intro hzero
    rw [hzero, zero_mul] at h0
    exact zero_ne_one h0

/-- **A point with coordinates in an extension field specializes to a point over the algebraically
closed field**, keeping every polynomial identity it satisfies and any prescribed finite list of
non-degeneracies.

Read geometrically: the points of `k ^ σ` are dense in the closure of the point `x`, so a `K`-point
of an affine variety defined over `k` can be replaced by a `k`-point of the same variety lying in
any basic open set that contains it. -/
theorem exists_specialization {κ : Type*} [Finite κ] (x : σ → K) (q : κ → MvPolynomial σ k)
    (hq : ∀ j, aeval x (q j) ≠ 0) :
    ∃ y : σ → k, (∀ p : MvPolynomial σ k, aeval x p = 0 → aeval y p = 0) ∧
      ∀ j, aeval y (q j) ≠ 0 := by
  obtain ⟨y, hy, hyq⟩ :=
    exists_solution (K := K) (fun p : {p : MvPolynomial σ k // aeval x p = 0} => p.1) q
      ⟨x, fun p => p.2, hq⟩
  exact ⟨y, fun p hp => hy ⟨p, hp⟩, hyq⟩

/-! ## Unknowns inside polynomial identities

An unknown *polynomial* of bounded degree is a tuple of unknown coefficients, so identities between
polynomials whose coefficients are polynomial expressions in the unknowns are again a polynomial
system: the universal shape of such an identity is an element of `(MvPolynomial σ k)[X]`, and
substituting values for the unknowns is `Polynomial.map` along the evaluation. -/

omit [IsAlgClosed k] [Finite σ] in
private theorem map_eq_zero_iff {R : Type*} [CommRing R] [Algebra k R] (x : σ → R)
    (E : Polynomial (MvPolynomial σ k)) :
    E.map (aeval x : MvPolynomial σ k →ₐ[k] R).toRingHom = 0 ↔ ∀ n, aeval x (E.coeff n) = 0 := by
  rw [Polynomial.ext_iff]
  simp

omit [IsAlgClosed k] [Finite σ] in
private theorem map_map_eq_zero_iff {R : Type*} [CommRing R] [Algebra k R] (x : σ → R)
    (E : Polynomial (Polynomial (MvPolynomial σ k))) :
    E.map (Polynomial.mapRingHom (aeval x : MvPolynomial σ k →ₐ[k] R).toRingHom) = 0 ↔
      ∀ n, (E.coeff n).map (aeval x : MvPolynomial σ k →ₐ[k] R).toRingHom = 0 := by
  rw [Polynomial.ext_iff]
  simp

/-- **A family of polynomial identities in one indeterminate, whose coefficients are polynomial
expressions in the unknowns, descends from an extension field to the algebraically closed field.**

The identities hold after substituting values for the unknowns exactly when all of their
coefficients vanish there, so this is a polynomial system in the unknowns. -/
theorem exists_forall_map_eq_zero {ι : Type*} (E : ι → Polynomial (MvPolynomial σ k))
    (h : ∃ x : σ → K, ∀ i, (E i).map (aeval x : MvPolynomial σ k →ₐ[k] K).toRingHom = 0) :
    ∃ y : σ → k, ∀ i, (E i).map (aeval y : MvPolynomial σ k →ₐ[k] k).toRingHom = 0 := by
  obtain ⟨x, hx⟩ := h
  obtain ⟨y, hy⟩ := exists_forall_aeval_eq_zero (K := K)
    (fun p : ι × ℕ => (E p.1).coeff p.2)
    ⟨x, fun p => (map_eq_zero_iff x (E p.1)).1 (hx p.1) p.2⟩
  exact ⟨y, fun i => (map_eq_zero_iff y (E i)).2 fun n => hy (i, n)⟩

/-- **A family of polynomial identities in two indeterminates, whose coefficients are polynomial
expressions in the unknowns, descends from an extension field to the algebraically closed field.**

This is the shape taken by identities between covers of the line written as equations: one
indeterminate for the base, one for the fibre. -/
theorem exists_forall_map_map_eq_zero {ι : Type*}
    (E : ι → Polynomial (Polynomial (MvPolynomial σ k)))
    (h : ∃ x : σ → K, ∀ i, (E i).map
      (Polynomial.mapRingHom (aeval x : MvPolynomial σ k →ₐ[k] K).toRingHom) = 0) :
    ∃ y : σ → k, ∀ i, (E i).map
      (Polynomial.mapRingHom (aeval y : MvPolynomial σ k →ₐ[k] k).toRingHom) = 0 := by
  obtain ⟨x, hx⟩ := h
  obtain ⟨y, hy⟩ := exists_forall_map_eq_zero (K := K)
    (fun p : ι × ℕ => (E p.1).coeff p.2)
    ⟨x, fun p => (map_map_eq_zero_iff x (E p.1)).1 (hx p.1) p.2⟩
  exact ⟨y, fun i => (map_map_eq_zero_iff y (E i)).2 fun n => hy (i, n)⟩

end Rigidity.RET.Transfer
