/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# The order of a rational function at a height-one prime

For a Dedekind domain `R` with fraction field `K`, every height-one prime `v` of `R` measures an
element of `K` by the exponent with which `v` occurs in the factorization of the principal
fractional ideal it spans.  That exponent is `ord K v x`, an integer: positive when `x` vanishes at
`v`, negative when `x` has a pole there.

The construction is `FractionalIdeal.count` applied to `spanSingleton R⁰ x`, so all of its
arithmetic comes from the factorization of fractional ideals: the order is additive on products,
negates on inverses, vanishes on units of `R`, is non-negative on `R` itself, and — the finiteness
that makes divisors possible — vanishes at all but finitely many `v`.

## Main definitions

* `Rigidity.RET.ord` — the order of `x : K` at the height-one prime `v`.

## Main results

* `Rigidity.RET.ord_mul` — the order is additive on products of nonzero elements.
* `Rigidity.RET.ord_inv` — the order negates on inverses.
* `Rigidity.RET.ord_finite` — a nonzero element has nonzero order at only finitely many primes.
* `Rigidity.RET.ord_nonneg` — elements of `R` have non-negative order everywhere.
* `Rigidity.RET.mem_iff_ord_pos` — an element of `R` lies in `v` exactly when its order there is
  positive.
-/

open IsDedekindDomain FractionalIdeal
open scoped nonZeroDivisors

noncomputable section

namespace Rigidity.RET

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]

/-- **The order of a rational function at a height-one prime.**  It is the exponent of `v` in the
factorization of the fractional ideal generated by `x`: positive at a zero, negative at a pole. -/
def ord (v : HeightOneSpectrum R) (x : K) : ℤ :=
  FractionalIdeal.count K v (spanSingleton R⁰ x)

variable {K}
variable (v : HeightOneSpectrum R)

theorem ord_def (x : K) : ord K v x = FractionalIdeal.count K v (spanSingleton R⁰ x) := rfl

@[simp]
theorem ord_zero : ord K v (0 : K) = 0 := by
  rw [ord_def, spanSingleton_zero, FractionalIdeal.count_zero]

@[simp]
theorem ord_one : ord K v (1 : K) = 0 := by
  rw [ord_def, spanSingleton_one, FractionalIdeal.count_one]

omit [IsDedekindDomain R] in
/-- The fractional ideal spanned by a nonzero element is nonzero. -/
theorem spanSingleton_ne_zero {x : K} (hx : x ≠ 0) : spanSingleton R⁰ x ≠ 0 :=
  fun h => hx (spanSingleton_eq_zero_iff.mp h)

/-- **The order is additive on products.** -/
theorem ord_mul {x y : K} (hx : x ≠ 0) (hy : y ≠ 0) :
    ord K v (x * y) = ord K v x + ord K v y := by
  rw [ord_def, ord_def, ord_def, ← spanSingleton_mul_spanSingleton,
    FractionalIdeal.count_mul K v (spanSingleton_ne_zero hx) (spanSingleton_ne_zero hy)]

/-- **The order negates on inverses.** -/
@[simp]
theorem ord_inv (x : K) : ord K v x⁻¹ = -ord K v x := by
  rw [ord_def, ord_def, ← spanSingleton_inv, FractionalIdeal.count_inv]

/-- The order of a quotient is the difference of the orders. -/
theorem ord_div {x y : K} (hx : x ≠ 0) (hy : y ≠ 0) :
    ord K v (x / y) = ord K v x - ord K v y := by
  rw [div_eq_mul_inv, ord_mul v hx (inv_ne_zero hy), ord_inv, sub_eq_add_neg]

theorem ord_pow {x : K} (hx : x ≠ 0) (n : ℕ) : ord K v (x ^ n) = n * ord K v x := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ, ord_mul v (pow_ne_zero n hx) hx, ih]; push_cast; ring

theorem ord_zpow {x : K} (hx : x ≠ 0) (n : ℤ) : ord K v (x ^ n) = n * ord K v x := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast, ord_pow v hx]
  · rw [zpow_neg, zpow_natCast, ord_inv, ord_pow v hx]; ring

/-- **A nonzero rational function has nonzero order at only finitely many primes.**  This is the
finiteness that makes its divisor a genuine finitely supported function. -/
theorem ord_finite (x : K) : ∀ᶠ v : HeightOneSpectrum R in Filter.cofinite, ord K v x = 0 :=
  FractionalIdeal.finite_factors _

/-- The order of an element of `R` is the multiplicity of `v` in the factorization of the ideal it
generates. -/
theorem ord_algebraMap (r : R) :
    ord K v (algebraMap R K r) = FractionalIdeal.count K v (Ideal.span {r} : Ideal R) := by
  rw [ord_def, coeIdeal_span_singleton]

/-- **Elements of `R` have non-negative order.** -/
theorem ord_nonneg (r : R) : 0 ≤ ord K v (algebraMap R K r) := by
  rw [ord_algebraMap]
  exact FractionalIdeal.count_coe_nonneg K v _

/-- An element of `R` lies in the prime `v` exactly when it has positive order there. -/
theorem mem_iff_ord_pos {r : R} (hr : r ≠ 0) :
    r ∈ v.asIdeal ↔ 0 < ord K v (algebraMap R K r) := by
  classical
  have hspan : (Ideal.span {r} : Ideal R) ≠ 0 := by
    simpa [Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot] using hr
  rw [ord_algebraMap, FractionalIdeal.count_coe K v hspan, Int.natCast_pos, Nat.pos_iff_ne_zero,
    Associates.count_ne_zero_iff_dvd hspan v.irreducible, Ideal.dvd_span_singleton]

end Rigidity.RET
