/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Tate.Orbit

/-!
# The lattice of a transitive set for a cyclic group

A finite cyclic group acting transitively on a finite set permutes the basis of the free lattice on
that set, and the orbit–stabiliser theorem turns the computation for a single orbit into a
statement about the group: the Herbrand quotient of the lattice is the order of the stabiliser of a
point.

This is the form in which the computation is used in arithmetic.  The Galois group of an extension
of number fields acts transitively on the primes lying over a fixed prime of the base, and the
stabiliser of one of them is its decomposition group, of order the product of the ramification
index and the residue degree.

## Main results

* `InverseGalois.CFT.exists_pow_smul_eq`: a generator of a finite group reaches every point of a
  transitive set by a natural power.
* `InverseGalois.CFT.card_mul_card_stabilizer`: the orbit–stabiliser theorem for a transitive set.
* `InverseGalois.CFT.herbrand_permLatticeAut_toPerm`: **the Herbrand quotient of the free lattice
  on a transitive set is the order of the stabiliser of a point.**

## Tags

Tate cohomology, Herbrand quotient, orbit-stabiliser, decomposition group
-/

namespace InverseGalois.CFT

open MulAction

variable {G X : Type*} [Group G] [Finite G] [MulAction G X] [Fintype X]

/-! ### Reaching the whole set by natural powers -/

omit [Finite G] [Fintype X] in
/-- Powers of a permutation coming from a group element are the permutations of the powers. -/
theorem pow_toPerm_apply (σ : G) (k : ℕ) (x : X) :
    ((toPerm σ : Equiv.Perm X) ^ k) x = (σ ^ k) • x := by
  induction k generalizing x with
  | zero => simp
  | succ k ih => rw [pow_succ, Equiv.Perm.mul_apply, toPerm_apply, ih, pow_succ, mul_smul]

omit [Fintype X] in
/-- **A generator of a finite group reaches every point of a transitive set by a natural power.** -/
theorem exists_pow_smul_eq [IsPretransitive G X] {σ : G} (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ)
    (x₀ y : X) : ∃ k : ℕ, ((toPerm σ : Equiv.Perm X) ^ k) x₀ = y := by
  obtain ⟨g, hg⟩ := exists_smul_eq G x₀ y
  obtain ⟨k, hk⟩ := mem_powers_iff_mem_zpowers.2 (hσ g)
  have hk' : σ ^ k = g := hk
  exact ⟨k, by rw [pow_toPerm_apply, hk', hg]⟩

/-! ### The orbit-stabiliser theorem -/

omit [Finite G] in
/-- **The orbit–stabiliser theorem for a transitive set.** -/
theorem card_mul_card_stabilizer [IsPretransitive G X] (x₀ : X) :
    Fintype.card X * Nat.card (stabilizer G x₀) = Nat.card G := by
  have h1 : Nat.card (orbit G x₀) = Nat.card X := by
    rw [orbit_eq_univ]
    exact Nat.card_congr (Equiv.Set.univ X)
  have h2 : Nat.card (orbit G x₀) = (stabilizer G x₀).index :=
    Nat.card_congr (orbitEquivQuotientStabilizer G x₀)
  rw [← Nat.card_eq_fintype_card, ← h1, h2, Subgroup.index_mul_card]

/-! ### The Herbrand quotient -/

/-- **The Herbrand quotient of the free lattice on a transitive set is the order of the stabiliser
of a point.**  The group is cyclic of order `n`, generated by `σ`, and the lattice carries the
permutation action; the orbit is the whole set, so the lattice is induced from the trivial module
over the stabiliser. -/
theorem herbrand_permLatticeAut_toPerm [IsPretransitive G X] {σ : G}
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) (x₀ : X) {n : ℕ} (hn : Nat.card G = n) :
    herbrand (permLatticeAut (toPerm σ : Equiv.Perm X)) n = (Nat.card (stabilizer G x₀) : ℚ) := by
  have htrans : ∀ y : X, ∃ k : ℕ, ((toPerm σ : Equiv.Perm X) ^ k) x₀ = y :=
    exists_pow_smul_eq hσ x₀
  refine herbrand_permLatticeAut_of_transitive x₀ htrans ?_ Nat.card_pos.ne'
  rw [← card_eq_period _ x₀ htrans, card_mul_card_stabilizer, hn]

end InverseGalois.CFT
