/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Tate.Hexagon

/-!
# The Herbrand quotient

For a module over a cyclic group of order dividing `n`, presented by a single automorphism `σ`,
the *Herbrand quotient* is the ratio of the orders of the two Tate groups,

`h(M) = |Ĥ⁰(M)| / |Ĥ⁻¹(M)|`.

Its usefulness comes from two properties.  It is multiplicative in short exact sequences, an
immediate consequence of the hexagon: six groups in a cyclic exact sequence have equal products of
orders in odd and in even position, and rearranging that identity is exactly `h(B) = h(A) · h(C)`.
And it vanishes — that is, equals `1` — on finite modules, because for a finite module the two
Tate groups have the same order.  Together these say that the Herbrand quotient does not see
finite pieces: it can be computed after discarding any finite submodule or quotient, which is what
makes it computable in the arithmetic situations where the module itself is enormous but differs
from a manifestly understood one by something finite.

## Main definitions

* `InverseGalois.CFT.herbrand`: the Herbrand quotient, as a rational number.

## Main results

* `InverseGalois.CFT.TateSES.herbrand_mul`: **the Herbrand quotient is multiplicative** in short
  exact sequences.
* `InverseGalois.CFT.herbrand_eq_one_of_finite`: **the Herbrand quotient of a finite module
  is `1`**.
* `InverseGalois.CFT.TateSES.herbrand_eq_of_finite_sub`,
  `InverseGalois.CFT.TateSES.herbrand_eq_of_finite_quotient`: the Herbrand quotient is unchanged by
  passing to a quotient by a finite submodule, or to a submodule of finite index.

## Tags

Herbrand quotient, Tate cohomology, cyclic group
-/

namespace InverseGalois.CFT

variable {A B C : Type*} [AddCommGroup A] [AddCommGroup B] [AddCommGroup C]

/-- **The Herbrand quotient** of a module over the cyclic group generated by `σ`, an automorphism
whose `n`-th power is the identity: the order of `Ĥ⁰` divided by the order of `Ĥ⁻¹`.  The value is
only meaningful when both Tate groups are finite. -/
noncomputable def herbrand (σ : A ≃+ A) (n : ℕ) : ℚ :=
  (Nat.card (tateH0 σ n) : ℚ) / (Nat.card (tateHm1 σ n) : ℚ)

/-- The order of `Ĥ⁰`, as a positive rational. -/
theorem cast_card_tateH0_pos (σ : A ≃+ A) (n : ℕ) [Finite (tateH0 σ n)] :
    (0 : ℚ) < Nat.card (tateH0 σ n) := by
  exact_mod_cast Nat.card_pos (α := tateH0 σ n)

/-- The order of `Ĥ⁻¹`, as a positive rational. -/
theorem cast_card_tateHm1_pos (σ : A ≃+ A) (n : ℕ) [Finite (tateHm1 σ n)] :
    (0 : ℚ) < Nat.card (tateHm1 σ n) := by
  exact_mod_cast Nat.card_pos (α := tateHm1 σ n)

/-- The Herbrand quotient of a module with finite Tate groups is positive. -/
theorem herbrand_pos (σ : A ≃+ A) (n : ℕ) [Finite (tateH0 σ n)] [Finite (tateHm1 σ n)] :
    0 < herbrand σ n :=
  div_pos (cast_card_tateH0_pos σ n) (cast_card_tateHm1_pos σ n)

/-- **The Herbrand quotient of a finite module is `1`.**  For a finite module the two subquotients
`ker(σ - 1) / im N` and `ker N / im(σ - 1)` have the same order. -/
theorem herbrand_eq_one_of_finite (σ : A ≃+ A) {n : ℕ} (hσ : σ ^ n = 1) [Finite A] :
    herbrand σ n = 1 := by
  rw [herbrand, card_quotient_eq_card_quotient σ hσ]
  exact div_self (cast_card_tateHm1_pos σ n).ne'

namespace TateSES

variable {n : ℕ} (S : TateSES n A B C)

/-- **The Herbrand quotient is multiplicative in short exact sequences.**  This is the hexagon
identity, divided through by the orders of the three `Ĥ⁻¹` terms. -/
theorem herbrand_mul
    [Finite (tateH0 S.σA n)] [Finite (tateH0 S.σB n)] [Finite (tateH0 S.σC n)]
    [Finite (tateHm1 S.σA n)] [Finite (tateHm1 S.σB n)] [Finite (tateHm1 S.σC n)] :
    herbrand S.σA n * herbrand S.σC n = herbrand S.σB n := by
  have hA := cast_card_tateHm1_pos S.σA n
  have hB := cast_card_tateHm1_pos S.σB n
  have hC := cast_card_tateHm1_pos S.σC n
  have hcard : ((Nat.card (tateH0 S.σA n) * Nat.card (tateH0 S.σC n)
      * Nat.card (tateHm1 S.σB n) : ℕ) : ℚ)
      = ((Nat.card (tateH0 S.σB n) * Nat.card (tateHm1 S.σA n)
        * Nat.card (tateHm1 S.σC n) : ℕ) : ℚ) :=
    congrArg _ S.card_tateH0_mul_card_tateH0_mul_card_tateHm1
  push_cast at hcard
  rw [herbrand, herbrand, herbrand, div_mul_div_comm,
    div_eq_div_iff (by positivity) hB.ne']
  linear_combination hcard

/-- **A finite submodule does not change the Herbrand quotient.** -/
theorem herbrand_eq_of_finite_sub [Finite A]
    [Finite (tateH0 S.σB n)] [Finite (tateH0 S.σC n)]
    [Finite (tateHm1 S.σB n)] [Finite (tateHm1 S.σC n)] :
    herbrand S.σB n = herbrand S.σC n := by
  rw [← S.herbrand_mul, herbrand_eq_one_of_finite S.σA S.hσA, one_mul]

/-- **A finite quotient module does not change the Herbrand quotient.** -/
theorem herbrand_eq_of_finite_quotient [Finite C]
    [Finite (tateH0 S.σA n)] [Finite (tateH0 S.σB n)]
    [Finite (tateHm1 S.σA n)] [Finite (tateHm1 S.σB n)] :
    herbrand S.σB n = herbrand S.σA n := by
  rw [← S.herbrand_mul, herbrand_eq_one_of_finite S.σC S.hσC, mul_one]

end TateSES

end InverseGalois.CFT
