/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Tate.CyclicAction

/-!
# The lattice of the primes above a prime

The Galois group of an extension of Dedekind domains acts transitively on the primes lying over a
fixed prime of the base, and the stabiliser of one of them is its decomposition group, whose order
is the ramification index times the residue degree.  For a cyclic Galois group this determines the
Herbrand quotient of the free lattice on those primes: it is that same product.

The lattice in question is the group of divisors of the extension supported above the fixed prime,
which is the local factor of the group of ideles at that prime; the computation here is the local
contribution to the Herbrand quotient of the idele group.

## Main results

* `InverseGalois.CFT.stabilizer_primesOver_mk`: the stabiliser of a prime as a point of the set of
  primes over the base is its stabiliser as an ideal.
* `InverseGalois.CFT.herbrand_permLatticeAut_primesOver`: **the Herbrand quotient of the free
  lattice on the primes above a prime is the ramification index times the residue degree.**
* `InverseGalois.CFT.herbrand_piAut_permLatticeAut`: the Herbrand quotient of a finite product of
  permuted lattices is the product of their Herbrand quotients.
* `InverseGalois.CFT.herbrand_permLatticeAut_primesOver_pi`: the same computation for the primes
  above a finite family of primes of the base.

## Tags

Tate cohomology, Herbrand quotient, decomposition group, ramification
-/

namespace InverseGalois.CFT

open MulAction Ideal

open scoped Pointwise

variable {R S G : Type*} [CommRing R] [CommRing S] [Algebra R S]
  [Group G] [MulSemiringAction G S] [SMulCommClass G R S]

/-! ### The stabiliser of a prime -/

/-- **The stabiliser of a prime as a point of the set of primes over the base is its stabiliser as
an ideal.** -/
theorem stabilizer_primesOver_mk (p : Ideal R) (P : Ideal S) [P.IsPrime] [P.LiesOver p] :
    stabilizer G (primesOver.mk p P) = stabilizer G P := by
  ext σ
  rw [mem_stabilizer_iff, mem_stabilizer_iff, ← Subtype.val_inj, coe_smul_primesOver_mk]

/-! ### The Herbrand quotient -/

variable [IsDedekindDomain R] [IsDedekindDomain S] [Module.Finite R S]
  [Module.IsTorsionFree R S]
  [Finite G] [IsGaloisGroup G R S]

/-- **The Herbrand quotient of the free lattice on the primes above a prime is the ramification
index times the residue degree.**  The Galois group is cyclic of order `n`, generated by `σ`, and
it permutes the primes above the base prime transitively, so the lattice is induced from the
trivial module over the decomposition group of any one of them. -/
theorem herbrand_permLatticeAut_primesOver (p : Ideal R) (hp : p ≠ ⊥) [p.IsMaximal] (P : Ideal S)
    [P.LiesOver p] [P.IsMaximal] [Algebra.IsSeparable (R ⧸ p) (S ⧸ P)] {σ : G}
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) {n : ℕ} (hn : Nat.card G = n) :
    herbrand (permLatticeAut (toPerm σ : Equiv.Perm (p.primesOver S))) n
      = (p.ramificationIdxIn S : ℚ) * (p.inertiaDegIn S : ℚ) := by
  rw [herbrand_permLatticeAut_toPerm hσ (primesOver.mk p P) hn, stabilizer_primesOver_mk,
    Ideal.card_stabilizer_eq p hp P, Nat.cast_mul]

/-! ### Several primes at once -/

/-- **The Herbrand quotient of a finite product of permuted lattices is the product of their
Herbrand quotients.** -/
theorem herbrand_piAut_permLatticeAut {ι : Type*} [Fintype ι] {X : ι → Type*}
    {q : ∀ i, Equiv.Perm (X i)} {c : ι → ℚ} {n : ℕ}
    (h : ∀ i, herbrand (permLatticeAut (q i)) n = c i) :
    herbrand (piAut fun i => permLatticeAut (q i)) n = ∏ i, c i := by
  rw [herbrand_piAut]
  exact Finset.prod_congr rfl fun i _ => h i

/-- **The Herbrand quotient of the free lattice on the primes above a finite set of primes** is the
product of the ramification indices times the residue degrees. -/
theorem herbrand_permLatticeAut_primesOver_pi {ι : Type*} [Fintype ι] (p : ι → Ideal R)
    (hp : ∀ i, p i ≠ ⊥) (hmax : ∀ i, (p i).IsMaximal) (P : ι → Ideal S)
    (hPmax : ∀ i, (P i).IsMaximal) (hover : ∀ i, (P i).LiesOver (p i))
    (hsep : ∀ i, Algebra.IsSeparable (R ⧸ p i) (S ⧸ P i)) {σ : G}
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) {n : ℕ} (hn : Nat.card G = n) :
    herbrand (piAut fun i =>
        permLatticeAut (toPerm σ : Equiv.Perm ((p i).primesOver S))) n
      = ∏ i, ((p i).ramificationIdxIn S : ℚ) * ((p i).inertiaDegIn S : ℚ) := by
  refine herbrand_piAut_permLatticeAut fun i => ?_
  haveI := hmax i
  haveI := hPmax i
  haveI := hover i
  haveI := hsep i
  exact herbrand_permLatticeAut_primesOver (p i) (hp i) (P i) hσ hn

end InverseGalois.CFT
