/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Tate.Congr

/-!
# The restriction of an automorphism to an invariant subgroup

An automorphism of an abelian group that carries a subgroup into itself, and whose inverse does the
same, restricts to an automorphism of that subgroup.  This is the routine step that turns an
invariant lattice inside an ambient group into a module over the cyclic group generated by the
automorphism, so that its Herbrand quotient is defined and can be compared with that of the ambient
group.

## Main definitions

* `InverseGalois.CFT.subgroupAut`: the restriction of an automorphism to an invariant subgroup.

## Main results

* `InverseGalois.CFT.subgroupAut_pow_eq_one`: the restriction inherits the order of the
  automorphism.
* `InverseGalois.CFT.herbrand_topAut`: the restriction to the whole group has the Herbrand quotient
  of the group.
* `InverseGalois.CFT.module_finite_addSubgroup`: **a subgroup of a finitely generated abelian group
  is finitely generated.**
* `InverseGalois.CFT.module_free_addSubgroup`: a subgroup of a finitely generated torsion free
  abelian group is free.
* `InverseGalois.CFT.module_finite_of_range_eq_ker`: **an extension of a finitely generated abelian
  group by a finitely generated one is finitely generated.**

## Tags

Tate cohomology, Herbrand quotient, invariant subgroup, restriction
-/

namespace InverseGalois.CFT

variable {V : Type*} [AddCommGroup V] {τ : V ≃+ V} {L : AddSubgroup V} {n : ℕ}

/-! ### The restriction -/

/-- **The restriction of an automorphism to an invariant subgroup.** -/
def subgroupAut (τ : V ≃+ V) (L : AddSubgroup V) (h : ∀ x ∈ L, τ x ∈ L)
    (h' : ∀ x ∈ L, τ.symm x ∈ L) : L ≃+ L where
  toFun x := ⟨τ x, h x x.2⟩
  invFun x := ⟨τ.symm x, h' x x.2⟩
  left_inv x := Subtype.ext (τ.symm_apply_apply x)
  right_inv x := Subtype.ext (τ.apply_symm_apply x)
  map_add' _ _ := Subtype.ext (τ.map_add _ _)

@[simp]
theorem coe_subgroupAut_apply (h : ∀ x ∈ L, τ x ∈ L) (h' : ∀ x ∈ L, τ.symm x ∈ L) (x : L) :
    ((subgroupAut τ L h h' x : L) : V) = τ (x : V) := rfl

theorem coe_pow_subgroupAut_apply (h : ∀ x ∈ L, τ x ∈ L) (h' : ∀ x ∈ L, τ.symm x ∈ L) (k : ℕ)
    (x : L) : (((subgroupAut τ L h h') ^ k) x : V) = (τ ^ k) (x : V) := by
  induction k with
  | zero => rfl
  | succ k ih => rw [pow_succ_apply, coe_subgroupAut_apply, ih, ← pow_succ_apply]

/-- **The restriction inherits the order of the automorphism.** -/
theorem subgroupAut_pow_eq_one (h : ∀ x ∈ L, τ x ∈ L) (h' : ∀ x ∈ L, τ.symm x ∈ L)
    (hτ : τ ^ n = 1) : (subgroupAut τ L h h') ^ n = 1 :=
  AddEquiv.ext fun x => Subtype.ext (by rw [coe_pow_subgroupAut_apply, hτ]; rfl)

/-! ### The whole group -/

/-- **The restriction to the whole group has the Herbrand quotient of the group.** -/
theorem herbrand_topAut (h : ∀ x ∈ (⊤ : AddSubgroup V), τ x ∈ (⊤ : AddSubgroup V))
    (h' : ∀ x ∈ (⊤ : AddSubgroup V), τ.symm x ∈ (⊤ : AddSubgroup V)) (n : ℕ) :
    herbrand (subgroupAut τ ⊤ h h') n = herbrand τ n :=
  herbrand_congr (AddSubgroup.topEquiv (G := V)) (fun _ => rfl) n

/-! ### Finiteness of a subgroup -/

/-- **A subgroup of a finitely generated abelian group is finitely generated.**  The ring of
integers is Noetherian, so a submodule of a finitely generated module over it is again finitely
generated, and a subgroup is a submodule. -/
theorem module_finite_addSubgroup [AddGroup.FG V] (L : AddSubgroup V) : Module.Finite ℤ L := by
  haveI : Module.Finite ℤ V := Module.Finite.iff_addGroup_fg.mpr ‹_›
  haveI : IsNoetherian ℤ V := inferInstance
  rw [Module.Finite.iff_addGroup_fg, AddGroup.fg_iff_addSubgroup_fg,
    ← AddSubgroup.toIntSubmodule_toAddSubgroup L, ← Submodule.fg_iff_addSubgroup_fg]
  exact IsNoetherian.noetherian _

/-- A subgroup of a finitely generated torsion free abelian group is free. -/
theorem module_free_addSubgroup [AddGroup.FG V] [NoZeroSMulDivisors ℤ V] (L : AddSubgroup V) :
    Module.Free ℤ L := by
  haveI := module_finite_addSubgroup L
  haveI : NoZeroSMulDivisors ℤ L :=
    Function.Injective.noZeroSMulDivisors _ (AddSubgroup.subtype_injective L) rfl fun _ _ => rfl
  infer_instance

/-! ### Finiteness of an extension -/

/-- **An extension of a finitely generated abelian group by a finitely generated one is finitely
generated.**  A generating set of the image together with lifts of a generating set of the
subobject generate the middle term. -/
theorem module_finite_of_range_eq_ker {A B C : Type*} [AddCommGroup A] [AddCommGroup B]
    [AddCommGroup C] [Module.Finite ℤ A] (f : A →+ B) (g : B →+ C) [Module.Finite ℤ g.range]
    (h : f.range = g.ker) : Module.Finite ℤ B := by
  haveI : AddGroup.FG A := Module.Finite.iff_addGroup_fg.mp ‹_›
  have hrange : (LinearMap.range g.toIntLinearMap).FG := by
    rw [AddMonoidHom.coe_toIntLinearMap_range, Submodule.fg_iff_addSubgroup_fg,
      AddSubgroup.toIntSubmodule_toAddSubgroup, ← AddGroup.fg_iff_addSubgroup_fg]
    exact Module.Finite.iff_addGroup_fg.mp ‹_›
  have hker : (LinearMap.ker g.toIntLinearMap).FG := by
    rw [AddMonoidHom.coe_toIntLinearMap_ker, Submodule.fg_iff_addSubgroup_fg,
      AddSubgroup.toIntSubmodule_toAddSubgroup, ← h, ← AddGroup.fg_iff_addSubgroup_fg]
    infer_instance
  refine Module.Finite.of_fg_top (Submodule.fg_of_fg_map_of_fg_inf_ker g.toIntLinearMap ?_ ?_)
  · rwa [Submodule.map_top]
  · rwa [top_inf_eq]

end InverseGalois.CFT
