import InverseGalois.Rigidity.RET.Pi1.Etale.Category
import InverseGalois.Rigidity.RET.Pi1.Etale.Quotient
import InverseGalois.Rigidity.RET.Pi1.Etale.Connected
import Mathlib.CategoryTheory.Galois.IsFundamentalgroup
import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.FieldTheory.Galois.Profinite
import Mathlib.RingTheory.Etale.Field
import Mathlib.FieldTheory.Perfect
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.Topology.LocallyConstant.Basic
import Mathlib.LinearAlgebra.Dimension.Free

/-!
# The absolute Galois group as the fundamental group of the fibre functor

For a perfect field `K`, the automorphism group `Aut F` of the fibre functor
`F = fibreFunctor K (AlgebraicClosure K)` of the Galois category of finite étale `K`-algebras is the
étale fundamental group of `Spec K`.  This file identifies it with the **absolute Galois group**
`Gal(K̄/K) = AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K`.

The Grothendieck–Galois formalism (`CategoryTheory.PreGaloisCategory.IsFundamentalGroup`) provides a
canonical criterion for a compact topological group `G` acting naturally on the fibres to be the
fundamental group: transitivity on the fibres of Galois (connected) objects, continuity of the action
on each finite fibre, and faithfulness (only the identity acts trivially everywhere).  We verify
these three conditions for `Gal(K̄/K)` with its Krull topology:

* **Transitivity** is the statement that a finite separable field extension is a connected object of
  the category — any two `K`-embeddings of a field into `K̄` differ by an automorphism of `K̄`.
* **Continuity** holds because the action on a finite fibre is locally constant: `σ • h` depends only
  on the restriction of `σ` to the finite subextension generated by the image of `h`, and the
  stabilisers of elements are open in the Krull topology.
* **Faithfulness** holds because every element of `K̄` lies in a finite separable subextension, whose
  inclusion is a point of a fibre; an automorphism fixing every fibre fixes every such inclusion,
  hence every element of `K̄`.

The payoff is the group isomorphism `absoluteGaloisEquivAut`, `Gal(K̄/K) ≃* Aut F`, a homeomorphism
for the Krull topology on the source and the natural topology on `Aut F`.
-/

open CategoryTheory Limits Functor PreGaloisCategory
open scoped IntermediateField

universe u

namespace Rigidity.RET.Etale.FiniteEtaleAlgCat

variable {K : Type u} [Field K]

/-- A finite-dimensional separable field extension is étale. -/
theorem etale_of_separable_finiteDimensional (L : Type u) [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L] : Algebra.Etale K L where
  formallyEtale := Algebra.FormallyEtale.of_isSeparable K L
  finitePresentation := (Algebra.FinitePresentation.of_finiteType).mp inferInstance

variable (Ω : Type u) [Field Ω] [Algebra K Ω]

section Transitivity

variable [Normal K Ω]

/-- **Transitivity on the fibres of Galois objects.**  A Galois object `X` of the category of finite
étale `K`-algebras is connected, hence its coordinate ring is a field; the group `Ω ≃ₐ[K] Ω` acts
transitively on the fibre `X.unop.obj →ₐ[K] Ω` because any two `K`-embeddings of a field into the
normal extension `Ω` are conjugate under an automorphism of `Ω`. -/
theorem transitivity_lemma (X : (FiniteEtaleAlgCat.{u} K)ᵒᵖ) [IsGalois X] :
    MulAction.IsPretransitive (Ω ≃ₐ[K] Ω) ((fibreFunctor K Ω).obj X) := by
  haveI hconn : PreGaloisCategory.IsConnected (Opposite.op X.unop) := by
    rw [Opposite.op_unop]; infer_instance
  have hfield : IsField X.unop.obj := (isConnected_op_iff_isField X.unop).mp hconn
  letI : Field X.unop.obj := hfield.toField
  show MulAction.IsPretransitive (Ω ≃ₐ[K] Ω) (X.unop.obj →ₐ[K] Ω)
  exact fibre_isPretransitive

end Transitivity

section Continuity

variable [Algebra.IsIntegral K Ω]

/-- The orbit map `σ ↦ σ • h₀` of the monodromy action on the fibre of a finite `K`-algebra `E` is
locally constant: `σ • h₀` is determined by the values of `σ` on the finitely many images of a
`K`-basis of `E`, and the stabiliser of each such element is open in the Krull topology. -/
theorem fibre_orbitMap_isLocallyConstant {E : Type u} [CommRing E] [Algebra K E]
    [Module.Finite K E] (h₀ : E →ₐ[K] Ω) :
    IsLocallyConstant (fun σ : Ω ≃ₐ[K] Ω => σ • h₀) := by
  set b := Module.finBasis K E with hb
  rw [IsLocallyConstant.iff_isOpen_fiber]
  intro h'
  by_cases hne : ∃ σ₁ : Ω ≃ₐ[K] Ω, σ₁ • h₀ = h'
  · obtain ⟨σ₁, rfl⟩ := hne
    set V : Set (Ω ≃ₐ[K] Ω) :=
      ⋂ i, (MulAction.stabilizer (Ω ≃ₐ[K] Ω) (h₀ (b i)) : Set (Ω ≃ₐ[K] Ω)) with hV
    have hVopen : IsOpen V :=
      isOpen_iInter_of_finite (fun i => stabilizer_isOpen_of_isIntegral (h₀ (b i)))
    have hmemV : ∀ τ : Ω ≃ₐ[K] Ω, τ ∈ V ↔ ∀ i, τ (h₀ (b i)) = h₀ (b i) := by
      intro τ
      rw [hV]
      simp only [Set.mem_iInter, SetLike.mem_coe, MulAction.mem_stabilizer_iff, AlgEquiv.smul_def]
    have hbasis : ∀ τ : Ω ≃ₐ[K] Ω,
        (∀ i, τ (h₀ (b i)) = h₀ (b i)) → ∀ y : E, τ (h₀ y) = h₀ y := by
      intro τ hτ y
      have hlin : (τ.toLinearMap.comp h₀.toLinearMap) = h₀.toLinearMap := by
        apply b.ext
        intro i
        simp only [LinearMap.comp_apply, AlgEquiv.toLinearMap_apply, AlgHom.toLinearMap_apply]
        exact hτ i
      exact LinearMap.congr_fun hlin y
    have hpre : (fun σ : Ω ≃ₐ[K] Ω => σ • h₀) ⁻¹' {σ₁ • h₀} = (fun τ => σ₁ * τ) '' V := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_image]
      constructor
      · intro hσ
        refine ⟨σ₁⁻¹ * σ, ?_, by group⟩
        rw [hmemV]
        intro i
        have hσi : σ (h₀ (b i)) = σ₁ (h₀ (b i)) := by
          have h1 := AlgHom.congr_fun hσ (b i)
          rw [fibre_smul_apply, fibre_smul_apply] at h1
          exact h1
        show (σ₁⁻¹ * σ) (h₀ (b i)) = h₀ (b i)
        rw [AlgEquiv.mul_apply, hσi, ← AlgEquiv.mul_apply, inv_mul_cancel, AlgEquiv.one_apply]
      · rintro ⟨τ, hτV, rfl⟩
        rw [hmemV] at hτV
        apply AlgHom.ext
        intro y
        rw [fibre_smul_apply, fibre_smul_apply, AlgEquiv.mul_apply]
        exact congrArg σ₁ (hbasis τ hτV y)
    rw [hpre]
    exact isOpenMap_mul_left σ₁ V hVopen
  · push_neg at hne
    have hempty : (fun σ : Ω ≃ₐ[K] Ω => σ • h₀) ⁻¹' {h'} = ∅ := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_empty_iff_false, iff_false]
      exact hne σ
    rw [hempty]
    exact isOpen_empty

/-- **Continuity of the monodromy action on a finite fibre.**  For any object `X`, the action of
`Ω ≃ₐ[K] Ω` on the finite discrete fibre `X.unop.obj →ₐ[K] Ω` is continuous, since the orbit map
`σ ↦ σ • h` is locally constant. -/
theorem continuity_lemma (X : (FiniteEtaleAlgCat.{u} K)ᵒᵖ) :
    ContinuousSMul (Ω ≃ₐ[K] Ω) ((fibreFunctor K Ω).obj X) := by
  haveI : Module.Finite K X.unop.obj := etale_moduleFinite X.unop.obj
  constructor
  rw [continuous_iff_continuousAt]
  rintro ⟨σ₀, h₀⟩
  rw [continuousAt_prod_of_discrete_right]
  apply Continuous.continuousAt
  apply IsLocallyConstant.continuous
  exact fibre_orbitMap_isLocallyConstant Ω (E := X.unop.obj) h₀

end Continuity

section NonTrivial

variable [PerfectField K] [Algebra.IsAlgebraic K Ω]

/-- **Faithfulness of the monodromy action.**  An automorphism `σ` of `Ω` over `K` that fixes every
point of every fibre is the identity: every `a : Ω` generates a finite separable subextension
`K⟮a⟯`, an object of the category whose fibre contains the inclusion `K⟮a⟯ ↪ Ω`; fixing that point
forces `σ a = a`. -/
theorem nontrivial_lemma (σ : Ω ≃ₐ[K] Ω)
    (h : ∀ (X : (FiniteEtaleAlgCat.{u} K)ᵒᵖ) (x : (fibreFunctor K Ω).obj X), σ • x = x) :
    σ = 1 := by
  apply AlgEquiv.ext
  intro a
  haveI : Algebra.IsIntegral K Ω := inferInstance
  have ha : IsIntegral K a := Algebra.IsIntegral.isIntegral a
  haveI : FiniteDimensional K K⟮a⟯ := IntermediateField.adjoin.finiteDimensional ha
  haveI : Algebra.IsAlgebraic K K⟮a⟯ := IntermediateField.isAlgebraic_adjoin_simple ha
  haveI : Algebra.Etale K K⟮a⟯ := etale_of_separable_finiteDimensional K⟮a⟯
  let Aobj : FiniteEtaleAlgCat.{u} K :=
    ⟨CommAlgCat.of K K⟮a⟯, inferInstanceAs (Algebra.Etale K K⟮a⟯)⟩
  let ι : (K⟮a⟯ : IntermediateField K Ω) →ₐ[K] Ω := (K⟮a⟯).val
  have hpt : σ • ι = ι := h (Opposite.op Aobj) ι
  have hpt' : σ.toAlgHom.comp ι = ι := hpt
  have key : σ (ι (IntermediateField.AdjoinSimple.gen K a))
      = ι (IntermediateField.AdjoinSimple.gen K a) := AlgHom.congr_fun hpt' _
  have hιgen : ι (IntermediateField.AdjoinSimple.gen K a) = a :=
    IntermediateField.AdjoinSimple.algebraMap_gen K a
  rw [AlgEquiv.one_apply]
  rw [hιgen] at key
  exact key

end NonTrivial

section FundamentalGroup

variable [PerfectField K]

/-- The algebraic closure of a perfect field is a Galois extension. -/
instance isGalois_algebraicClosure : IsGalois K (AlgebraicClosure K) := ⟨⟩

/-- **The absolute Galois group is the fundamental group of the fibre functor.**  For a perfect field
`K`, the group `Gal(K̄/K) = AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K`, with its Krull topology and
natural action on the fibres, is the Grothendieck fundamental group of the fibre
functor of the Galois category of finite étale `K`-algebras. -/
instance isFundamentalGroup_absoluteGalois :
    IsFundamentalGroup (fibreFunctor K (AlgebraicClosure K))
      (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) where
  toIsNaturalSMul := inferInstance
  transitive_of_isGalois X := transitivity_lemma (AlgebraicClosure K) X
  continuous_smul X := continuity_lemma (AlgebraicClosure K) X
  non_trivial' σ h := nontrivial_lemma (AlgebraicClosure K) σ h

/-- **The absolute Galois group identified with the automorphism group of the fibre functor.**
For a perfect field `K`, `Gal(K̄/K) ≃* Aut F`, the group isomorphism induced by the natural action of
the Galois group on the fibres.  It is also a homeomorphism for the Krull topology on the source and
the natural (profinite) topology on `Aut F`. -/
noncomputable def absoluteGaloisEquivAut :
    (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) ≃*
      Aut (fibreFunctor K (AlgebraicClosure K)) :=
  PreGaloisCategory.toAutMulEquiv (fibreFunctor K (AlgebraicClosure K))
    (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K)

/-- The same identification, phrased with Mathlib's `Field.absoluteGaloisGroup`. -/
noncomputable def absoluteGaloisGroupEquivAut :
    Field.absoluteGaloisGroup K ≃* Aut (fibreFunctor K (AlgebraicClosure K)) :=
  absoluteGaloisEquivAut

end FundamentalGroup

end Rigidity.RET.Etale.FiniteEtaleAlgCat
