/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.RET.Pi1.Topological.Monodromy

/-!
# Lifting a map through a covering by a monodromy computation

The lifting criterion says that a map from a path-connected, locally path-connected space lifts
through a covering exactly when the image of its fundamental group lands inside the image of the
fundamental group of the total space.  That image condition is awkward to check directly, but it
has a purely combinatorial reformulation: a loop lies in the image precisely when its monodromy
fixes the chosen point of the fibre, because the lift of the loop starting there is then itself a
loop.  Reformulated this way the criterion becomes a statement about permutations of a fibre, which
is what a concrete computation actually produces.

A second, purely group-theoretic ingredient makes the check finite: when the fundamental group of
the target is generated by a single loop, it suffices to check that loop, since every other element
is one of its powers and powers of a permutation fixing a point fix that point.

## Main results

* `IsCoveringMap.mem_range_mapOfEq_of_monodromy_eq` — a loop whose monodromy fixes a fibre point
  lies in the image of the fundamental group of the total space.
* `IsCoveringMap.exists_lift_of_monodromy_fixed` — a map all of whose loops have monodromy fixing a
  fibre point lifts through the covering.
* `Rigidity.RET.pow_apply_eq_self_of_zpowers_eq_top` — for a cyclic group it is enough to check the
  generator.
-/

open Topology unitInterval

noncomputable section

namespace IsCoveringMap

variable {E X : Type*} [TopologicalSpace E] [TopologicalSpace X] {p : E → X}
  (cov : IsCoveringMap p)

/-- **A loop fixed by the monodromy is the image of a loop upstairs.**  Lifting the loop starting
at the fibre point produces a path whose endpoint is that same fibre point by hypothesis, hence a
genuine loop of the total space lying over the given one. -/
theorem mem_range_mapOfEq_of_monodromy_eq {x : X} {e₀ : E} (he : p e₀ = x)
    {γ : FundamentalGroup X x}
    (hfix : cov.monodromy (FundamentalGroup.toPath γ) ⟨e₀, he⟩ = ⟨e₀, he⟩) :
    γ ∈ (FundamentalGroup.mapOfEq ⟨p, cov.continuous⟩ he).range := by
  obtain ⟨q, rfl⟩ :=
    Path.Homotopic.Quotient.mk_surjective (show Path.Homotopic.Quotient x x from γ)
  have hone : cov.liftPath q e₀ (q.source.trans he.symm) 1 = e₀ :=
    (cov.monodromy_mk_val q ⟨e₀, he⟩).symm.trans (congrArg Subtype.val hfix)
  have hzero : cov.liftPath q e₀ (q.source.trans he.symm) 0 = e₀ :=
    cov.liftPath_zero q e₀ (q.source.trans he.symm)
  refine MonoidHom.mem_range.mpr
    ⟨FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk
      ⟨cov.liftPath q e₀ (q.source.trans he.symm), hzero, hone⟩), ?_⟩
  rw [FundamentalGroup.mapOfEq_apply]
  refine congrArg (fun r : Path x x => Path.Homotopic.Quotient.mk r) (Path.ext (funext fun t => ?_))
  exact congrFun (cov.liftPath_lifts q e₀ (q.source.trans he.symm)) t

/-- **A map whose loops have trivial monodromy at a fibre point lifts through the covering.**  This
is the lifting criterion, with the image condition on fundamental groups replaced by the equivalent
statement that the monodromy of every loop fixes the chosen point of the fibre. -/
theorem exists_lift_of_monodromy_fixed {A : Type*} [TopologicalSpace A] [PathConnectedSpace A]
    [LocPathConnectedSpace A] (f : C(A, X)) (a₀ : A) (e₀ : E) (he : p e₀ = f a₀)
    (hfix : ∀ γ : FundamentalGroup A a₀,
      cov.monodromyHom (f a₀) (FundamentalGroup.map f a₀ γ) ⟨e₀, he⟩ = ⟨e₀, he⟩) :
    ∃ F : C(A, E), F a₀ = e₀ ∧ p ∘ F = f := by
  have hle : (FundamentalGroup.map f a₀).range
      ≤ (FundamentalGroup.mapOfEq ⟨p, cov.continuous⟩ he).range := by
    rintro _ ⟨γ, rfl⟩
    exact cov.mem_range_mapOfEq_of_monodromy_eq he (hfix γ)
  obtain ⟨F, hF, -⟩ := cov.existsUnique_continuousMap_lifts_of_range_le he hle
  exact ⟨F, hF⟩

end IsCoveringMap

namespace Rigidity.RET

/-- **In a cyclic group it is enough to check the generator.**  If a power of the image of the
generator fixes a point, then the same power of the image of any element fixes it, because every
element is a power of the generator and powers commute. -/
theorem pow_apply_eq_self_of_zpowers_eq_top {H : Type*} [Group H] {g : H}
    (hgen : Subgroup.zpowers g = ⊤) {α : Type*} (ψ : H →* Equiv.Perm α) {n : ℕ} {a : α}
    (hn : (ψ g ^ n) a = a) (t : H) : (ψ t ^ n) a = a := by
  obtain ⟨m, rfl⟩ : t ∈ Subgroup.zpowers g := hgen ▸ Subgroup.mem_top t
  rw [map_zpow, ← zpow_natCast (ψ g ^ m) n, ← zpow_mul, mul_comm, zpow_mul, zpow_natCast]
  exact Equiv.Perm.zpow_apply_eq_self_of_apply_eq_self hn m

end Rigidity.RET

end
