/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Pi1.Topological.MonodromyPath
import InverseGalois.Rigidity.RET.Pi1.Topological.RegionVanKampen

/-!
# Loops of a region that live in a subregion

A subregion `U ⊆ X` containing the basepoint determines a subgroup of the fundamental group of
`X`: the image of the fundamental group of `U`.  This bookkeeping device turns the Seifert–van
Kampen theorem into a statement about subgroups — a loop of a region covered by two open pieces
lies in the subgroup generated by the two pieces — and it records what a piece contributes: a
convex piece contributes nothing, and a piece sitting inside a punctured disc contributes only
powers of the loop around the puncture.

## Main results

* `Rigidity.RET.pi1Image` — the subgroup of loops of `X` that live in the subregion `U`.
* `Rigidity.RET.pi1Image_mono` — it grows with the subregion.
* `Rigidity.RET.pi1Image_eq_top_of_eq` — every loop of a region lives in the region.
* `Rigidity.RET.pi1Image_transport` — moving the basepoint inside the subregion conjugates it.
* `Rigidity.RET.pi1Image_map_transport` — the same, phrased for a path of the ambient region that
  happens to stay inside the subregion.
* `Rigidity.RET.pi1Image_le_sup_of_cover` — Seifert–van Kampen in this form.
* `Rigidity.RET.pi1Image_eq_bot_of_convex` — a convex subregion contributes no loops.
* `Rigidity.RET.pi1Image_le_zpowers` — a subregion of a punctured disc contributes only powers of
  the loop around the puncture.
-/

open scoped unitInterval

noncomputable section

namespace Rigidity.RET

/-- The subgroup of loops of `X` that already live in the subregion `U`. -/
def pi1Image {X U : Set ℂ} (hU : U ⊆ X) {z₀ : ℂ} (hz₀ : z₀ ∈ U) :
    Subgroup (FundamentalGroup ↥X ⟨z₀, hU hz₀⟩) :=
  (FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀⟩ : ↥U)).range

/-- Including a subregion into an intermediate one and then into the ambient region is the
inclusion of the subregion. -/
theorem subsetIncl_comp {X U V : Set ℂ} (hUV : U ⊆ V) (hVX : V ⊆ X) :
    (subsetIncl hVX).comp (subsetIncl hUV) = subsetIncl (hUV.trans hVX) := rfl

/-- Loops that live in a smaller subregion live in a bigger one. -/
theorem pi1Image_mono {X U V : Set ℂ} (hUV : U ⊆ V) (hVX : V ⊆ X) {z₀ : ℂ} (hz₀ : z₀ ∈ U) :
    pi1Image (hUV.trans hVX) hz₀ ≤ pi1Image hVX (hUV hz₀) := by
  rintro x ⟨g, rfl⟩
  exact ⟨FundamentalGroup.map (subsetIncl hUV) (⟨z₀, hz₀⟩ : ↥U) g,
    (fundamentalGroup_map_comp (subsetIncl hVX) (subsetIncl hUV) _ g).symm⟩

/-- The inclusion of a region in itself induces the identity. -/
theorem fundamentalGroup_map_self {X : Set ℂ} (hU : X ⊆ X) {z₀ : ℂ} (hz₀ : z₀ ∈ X)
    (g : FundamentalGroup ↥X ⟨z₀, hz₀⟩) :
    FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀⟩ : ↥X) g = g := by
  obtain ⟨p, rfl⟩ :=
    Path.Homotopic.Quotient.mk_surjective
      (show Path.Homotopic.Quotient (⟨z₀, hz₀⟩ : ↥X) ⟨z₀, hz₀⟩ from g)
  rfl

/-- Every loop of a region lives in the region. -/
theorem pi1Image_eq_top_of_eq {X U : Set ℂ} (hUX : U ⊆ X) (hXU : X ⊆ U) {z₀ : ℂ}
    (hz₀ : z₀ ∈ U) : pi1Image hUX hz₀ = ⊤ := by
  obtain rfl : U = X := Set.Subset.antisymm hUX hXU
  refine (Subgroup.eq_top_iff' _).2 fun g => ?_
  exact ⟨g, fundamentalGroup_map_self hUX hz₀ g⟩

/-- Moving the basepoint along a path inside the subregion conjugates the subgroup of loops that
live in it. -/
theorem pi1Image_transport {X U : Set ℂ} (hU : U ⊆ X) {z₀ z₁ : ℂ} {hz₀ : z₀ ∈ U} {hz₁ : z₁ ∈ U}
    (ε : Path (⟨z₀, hz₀⟩ : ↥U) ⟨z₁, hz₁⟩) :
    pi1Image hU hz₁ = (pi1Image hU hz₀).map
      (FundamentalGroup.fundamentalGroupMulEquivOfPath
        (ε.map (subsetIncl hU).continuous)).toMonoidHom := by
  ext x
  constructor
  · rintro ⟨g, rfl⟩
    refine ⟨FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀⟩ : ↥U)
      ((FundamentalGroup.fundamentalGroupMulEquivOfPath ε).symm g), ⟨_, rfl⟩, ?_⟩
    simp only [MulEquiv.coe_toMonoidHom]
    rw [← map_fundamentalGroupMulEquivOfPath]
    simp
  · rintro ⟨-, ⟨g, rfl⟩, rfl⟩
    refine ⟨FundamentalGroup.fundamentalGroupMulEquivOfPath ε g, ?_⟩
    simp only [MulEquiv.coe_toMonoidHom]
    exact map_fundamentalGroupMulEquivOfPath (subsetIncl hU) ε g

/-- A path staying inside the subregion conjugates the loops living in it at one endpoint onto
those at the other. -/
theorem pi1Image_map_transport {X U : Set ℂ} (hU : U ⊆ X) {z₀ z₁ : ℂ} (hz₀ : z₀ ∈ U)
    (hz₁ : z₁ ∈ U) (ε : Path (⟨z₀, hU hz₀⟩ : ↥X) ⟨z₁, hU hz₁⟩)
    (hε : ∀ t, ((ε t : ↥X) : ℂ) ∈ U) :
    (pi1Image hU hz₀).map
        (FundamentalGroup.transport (Path.Homotopic.Quotient.mk ε)).toMonoidHom
      = pi1Image hU hz₁ := by
  let ε' : Path (⟨z₀, hz₀⟩ : ↥U) ⟨z₁, hz₁⟩ :=
    { toFun := fun t => ⟨((ε t : ↥X) : ℂ), hε t⟩
      continuous_toFun := (continuous_subtype_val.comp ε.continuous).subtype_mk _
      source' := by simp
      target' := by simp }
  have hmap : ε'.map (subsetIncl hU).continuous = ε := rfl
  have := pi1Image_transport hU ε'
  rw [hmap] at this
  exact this.symm

/-- **Seifert–van Kampen, in the form of loops that live in a subregion.**  A loop of a region
covered by two open pieces is a product of loops living in the pieces. -/
theorem pi1Image_le_sup_of_cover {X Ω U V : Set ℂ} (hΩX : Ω ⊆ X) (hU : U ⊆ Ω) (hV : V ⊆ Ω)
    (hcover : Ω ⊆ U ∪ V) (hUopen : IsOpen U) (hVopen : IsOpen V)
    [PathConnectedSpace ↥U] [PathConnectedSpace ↥V] [PathConnectedSpace ↥(U ∩ V)]
    {z₀ : ℂ} (hz₀U : z₀ ∈ U) (hz₀V : z₀ ∈ V) :
    pi1Image hΩX (hU hz₀U) ≤ pi1Image (hU.trans hΩX) hz₀U ⊔ pi1Image (hV.trans hΩX) hz₀V := by
  have htop := closure_range_subsetIncl_eq_top hU hV hcover hUopen hVopen hz₀U hz₀V
  rintro x ⟨g, rfl⟩
  have hg : g ∈ Subgroup.closure
      (Set.range (FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀U⟩ : ↥U)) ∪
        Set.range (FundamentalGroup.map (subsetIncl hV) (⟨z₀, hz₀V⟩ : ↥V))) := by
    rw [htop]; trivial
  induction hg using Subgroup.closure_induction with
  | mem y hy =>
    rcases hy with ⟨u, rfl⟩ | ⟨v, rfl⟩
    · exact Subgroup.mem_sup_left ⟨u,
        fundamentalGroup_map_comp (subsetIncl hΩX) (subsetIncl hU) _ u⟩
    · exact Subgroup.mem_sup_right ⟨v,
        fundamentalGroup_map_comp (subsetIncl hΩX) (subsetIncl hV) _ v⟩
  | one => simpa using one_mem _
  | mul a b _ _ ha hb => rw [map_mul]; exact mul_mem ha hb
  | inv a _ ha => rw [map_inv]; exact inv_mem ha

/-- A simply connected subregion contributes no loops. -/
theorem pi1Image_eq_bot {X U : Set ℂ} (hU : U ⊆ X) {z₀ : ℂ} (hz₀ : z₀ ∈ U)
    [Subsingleton (FundamentalGroup ↥U ⟨z₀, hz₀⟩)] : pi1Image hU hz₀ = ⊥ := by
  refine (Subgroup.eq_bot_iff_forall _).2 ?_
  rintro x ⟨g, rfl⟩
  rw [Subsingleton.elim g 1, map_one]

/-- A convex subregion contributes no loops. -/
theorem pi1Image_eq_bot_of_convex {X U : Set ℂ} (hU : U ⊆ X) (hconv : Convex ℝ U) {z₀ : ℂ}
    (hz₀ : z₀ ∈ U) : pi1Image hU hz₀ = ⊥ := by
  haveI := hconv.contractibleSpace ⟨z₀, hz₀⟩
  haveI : Subsingleton (FundamentalGroup ↥U ⟨z₀, hz₀⟩) :=
    inferInstanceAs (Subsingleton (Path.Homotopic.Quotient (⟨z₀, hz₀⟩ : ↥U) (⟨z₀, hz₀⟩ : ↥U)))
  exact pi1Image_eq_bot hU hz₀

/-- Loops living in a subregion whose fundamental group is generated by a single loop are powers
of that loop. -/
theorem pi1Image_le_zpowers {X D U : Set ℂ} (hDX : D ⊆ X) (hUD : U ⊆ D) {z₀ : ℂ} (hz₀ : z₀ ∈ U)
    {g : FundamentalGroup ↥D ⟨z₀, hUD hz₀⟩} (hg : Subgroup.zpowers g = ⊤) :
    pi1Image (hUD.trans hDX) hz₀ ≤
      Subgroup.zpowers (FundamentalGroup.map (subsetIncl hDX) (⟨z₀, hUD hz₀⟩ : ↥D) g) := by
  refine le_trans (pi1Image_mono hUD hDX hz₀) ?_
  rintro x ⟨y, rfl⟩
  have hy : y ∈ Subgroup.zpowers g := by rw [hg]; trivial
  obtain ⟨n, rfl⟩ := hy
  exact ⟨n, by rw [map_zpow]⟩

end Rigidity.RET

end
