/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Pi1.Topological.ExteriorLoop
import InverseGalois.Rigidity.RET.Pi1.Topological.PushLoop
import InverseGalois.Rigidity.RET.Pi1.Topological.RectInduction

/-!
# A generating product-one system of puncture loops

The fundamental group of the plane punctured along a finite set `S` is generated by loops winding
once around the punctures, one for each puncture, subject to the relation that their ordered
product, together with one extra generator, is trivial.  This file assembles that statement from
the rectangle induction: a rectangle containing every puncture has a boundary loop which is the
ordered product of one loop per puncture, and those loops generate; adjoining the inverse of the
boundary loop as a last factor turns the product into the identity without disturbing generation.

The basepoint is arbitrary, since the punctured plane is path connected and a product of puncture
loops survives transport along a path.

The extra generator is the boundary loop of the rectangle, read backwards.  Choosing the rectangle
large enough that its four sides run outside a disc containing every puncture exhibits that last
generator as a loop supported at the point at infinity, which is what identifies it, on a cover
unramified there, as the trivial deck transformation.

This is the shape in which the branch-cycle description of a covering consumes the fundamental
group: each generator is attached to a single puncture, the product of all of them is trivial, and
together they generate everything.

## Main results

* `Rigidity.RET.exists_punctureLoops_prodOne_compl` — the generating product-one system.
* `Rigidity.RET.exists_punctureLoops_prodOne_of_surjective` — its image in any quotient of the
  fundamental group.
-/

open scoped unitInterval

noncomputable section

namespace Rigidity.RET

/-- **The fundamental group of the punctured plane is generated by one loop around each puncture,
whose ordered product, extended by a single further generator, is trivial.** -/
theorem exists_punctureLoops_prodOne_compl {S : Set ℂ} (hS : S.Finite) {z₀ : ℂ}
    (hz₀ : z₀ ∈ Sᶜ) :
    ∃ (r : ℕ) (pt : Fin r → ℂ) (γ : Fin (r + 1) → FundamentalGroup ↥(Sᶜ) ⟨z₀, hz₀⟩),
      Function.Injective pt ∧ Set.range pt = S ∧
        (∀ i : Fin r, IsPunctureLoop Sᶜ (pt i) hz₀ (γ i.castSucc)) ∧
        (List.ofFn γ).prod = 1 ∧ Subgroup.closure (Set.range γ) = ⊤ ∧
        IsSupportedAtInfinity Sᶜ hz₀ (γ (Fin.last r)) := by
  haveI : PathConnectedSpace ↥(Sᶜ : Set ℂ) := pathConnectedSpace_punctured hS.countable
  obtain ⟨x₀, x₁, y₀, y₁, R, hab, hbc, hcd, hda, hR0, hext, eab, ebc, ecd, eda, hprod⟩ :=
    exists_rectSpider_compl hS
  set ε : Path (⟨cpt x₀ y₀, hab (left_mem_seg _ _)⟩ : ↥(Sᶜ : Set ℂ)) ⟨z₀, hz₀⟩ :=
    PathConnectedSpace.somePath _ _ with hε
  have hmap := hprod.transport ε
  have htop : (⊤ : Subgroup (FundamentalGroup ↥(Sᶜ : Set ℂ) ⟨cpt x₀ y₀, hab (left_mem_seg _ _)⟩)).map
      (FundamentalGroup.fundamentalGroupMulEquivOfPath ε).toMonoidHom = ⊤ :=
    Subgroup.map_top_of_surjective _
      (FundamentalGroup.fundamentalGroupMulEquivOfPath ε).surjective
  rw [htop] at hmap
  obtain ⟨r, pt, γ, hinj, hrange, hloop, hprodeq, hgen⟩ := hmap
  refine ⟨r, pt, Fin.snoc γ ((List.ofFn γ).prod)⁻¹, hinj, hrange, ?_, ?_, ?_, ?_⟩
  · intro i
    rw [Fin.snoc_castSucc]
    exact hloop i
  · rw [List.ofFn_succ']
    simp only [Fin.snoc_castSucc, Fin.snoc_last, List.prod_concat]
    exact mul_inv_cancel _
  · refine eq_top_iff.2 (hgen.trans (Subgroup.closure_mono ?_))
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc, Fin.snoc_castSucc _ _ _⟩
  · -- the extra generator is the boundary loop of the rectangle, read backwards; the rectangle
    -- was chosen with all four of its sides outside a disc containing every puncture
    rw [Fin.snoc_last, hprodeq]
    have hbx : FundamentalGroup.map (extIncl hext)
          (⟨cpt x₀ y₀, eab (left_mem_seg _ _)⟩ : ↥(extRegion R))
          (FundamentalGroup.fromPath (boxLoop eab ebc ecd eda))
        = FundamentalGroup.fromPath (boxLoop hab hbc hcd hda) := by
      show FundamentalGroup.fromPath ((boxLoop eab ebc ecd eda).map (subsetIncl hext))
        = FundamentalGroup.fromPath (boxLoop hab hbc hcd hda)
      rw [map_boxLoop]
    refine ⟨R, hext, ⟨cpt x₀ y₀, eab (left_mem_seg _ _)⟩,
      (FundamentalGroup.fromPath (boxLoop eab ebc ecd eda))⁻¹, ε, hR0, ?_⟩
    rw [map_inv, hbx, map_inv]
    rfl

/-- **A quotient of the fundamental group of the punctured plane is generated by the images of one
loop around each puncture, together with one further element, and those images multiply to the
identity in the given order.**

This is the shape of a system of branch cycles: each entry but the last is attached to a single
puncture, the ordered product of all of them is trivial, and together they generate. -/
theorem exists_punctureLoops_prodOne_of_surjective {S : Set ℂ} (hS : S.Finite) {z₀ : ℂ}
    (hz₀ : z₀ ∈ Sᶜ) {G : Type*} [Group G] {Φ : FundamentalGroup ↥(Sᶜ) ⟨z₀, hz₀⟩ →* G}
    (hΦ : Function.Surjective Φ) :
    ∃ (r : ℕ) (pt : Fin r → ℂ) (γ : Fin (r + 1) → FundamentalGroup ↥(Sᶜ) ⟨z₀, hz₀⟩),
      Function.Injective pt ∧ Set.range pt = S ∧
        (∀ i : Fin r, IsPunctureLoop Sᶜ (pt i) hz₀ (γ i.castSucc)) ∧
        (List.ofFn fun i => Φ (γ i)).prod = 1 ∧
          Subgroup.closure (Set.range fun i => Φ (γ i)) = ⊤ ∧
          IsSupportedAtInfinity Sᶜ hz₀ (γ (Fin.last r)) := by
  obtain ⟨r, pt, γ, hinj, hrange, hloop, hprod, hgen, hinf⟩ :=
    exists_punctureLoops_prodOne_compl hS hz₀
  refine ⟨r, pt, γ, hinj, hrange, hloop, ?_, ?_, hinf⟩
  · rw [show (List.ofFn fun i => Φ (γ i)) = (List.ofFn γ).map Φ by
      simp [List.map_ofFn, Function.comp_def]]
    rw [← map_list_prod, hprod, map_one]
  · rw [Set.range_comp' Φ γ, ← MonoidHom.map_closure, hgen, ← MonoidHom.range_eq_map,
      MonoidHom.range_eq_top]
    exact hΦ

end Rigidity.RET

end
