/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Pi1.Topological.VanKampen.GenerationGroup
import InverseGalois.Rigidity.RET.Pi1.Topological.PunctureLocal

/-!
# Seifert–van Kampen for regions of the plane

The generation form of Seifert–van Kampen is stated for two open subsets of an ambient topological
space covering the whole of it.  A region `Ω` of the plane covered by two subregions `U` and `V` is
an instance of that, with the ambient space taken to be the subtype `↥Ω`; but then the two pieces
appear as subsets of `↥Ω` rather than as regions of the plane in their own right, which is
inconvenient for an induction that keeps producing smaller regions.

This file performs the translation once and for all.  A subset of `Ω` viewed inside `↥Ω` is
homeomorphic to the subset viewed inside the plane (`regionSubHomeo`), and under that
homeomorphism the inclusion-induced map of Seifert–van Kampen becomes the map induced by the plain
inclusion `subsetIncl`.

## Main results

* `Rigidity.RET.closure_range_subsetIncl_eq_top` — for an open cover `Ω = U ∪ V` of a region of the
  plane by two regions with path connected pieces and path connected overlap, the fundamental group
  of `Ω` is generated by the images of those of `U` and `V`.
* `Rigidity.RET.eq_top_of_cover` — the same, phrased as a criterion for a subgroup containing both
  images to be everything.
-/

open Set

noncomputable section

namespace Rigidity.RET

/-! ### A subset of a region, inside the region or inside the plane -/

/-- **A subset of a region, viewed inside the region, is the subset itself.** -/
def regionSubHomeo {Ω U : Set ℂ} (h : U ⊆ Ω) :
    ↥((Subtype.val : ↥Ω → ℂ) ⁻¹' U) ≃ₜ ↥U where
  toFun w := ⟨((w : ↥Ω) : ℂ), w.2⟩
  invFun w := ⟨⟨(w : ℂ), h w.2⟩, w.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  continuous_toFun := (continuous_subtype_val.comp continuous_subtype_val).subtype_mk _
  continuous_invFun := (continuous_subtype_val.subtype_mk _).subtype_mk _

/-- The homeomorphism of `regionSubHomeo`, as a continuous map. -/
def regionSubMap {Ω U : Set ℂ} (h : U ⊆ Ω) :
    C(↥((Subtype.val : ↥Ω → ℂ) ⁻¹' U), ↥U) :=
  (regionSubHomeo h).toHomotopyEquiv.toFun

theorem subsetIncl_comp_regionSubMap {Ω U : Set ℂ} (h : U ⊆ Ω) :
    (subsetIncl h).comp (regionSubMap h) = VanKampen.inclUX _ := rfl

theorem fundamentalGroup_map_regionSubMap_surjective {Ω U : Set ℂ} (h : U ⊆ Ω)
    (b : ↥((Subtype.val : ↥Ω → ℂ) ⁻¹' U)) :
    Function.Surjective (FundamentalGroup.map (regionSubMap h) b) :=
  (fundamentalGroup_map_bijective (regionSubHomeo h).toHomotopyEquiv b).2

/-- Path connectivity transfers from a subset of the plane to the same subset viewed inside a
region containing it. -/
theorem pathConnectedSpace_preimage {Ω U : Set ℂ} (h : U ⊆ Ω) [PathConnectedSpace ↥U] :
    PathConnectedSpace ↥((Subtype.val : ↥Ω → ℂ) ⁻¹' U) :=
  (regionSubHomeo h).symm.surjective.pathConnectedSpace (regionSubHomeo h).symm.continuous

/-- The inclusion-induced map of Seifert–van Kampen, read as a map of fundamental groups of regions
of the plane. -/
theorem range_pi1U_eq_range_map {Ω U : Set ℂ} (h : U ⊆ Ω) {z₀ : ℂ} (hz₀ : z₀ ∈ U)
    (hx : (⟨z₀, h hz₀⟩ : ↥Ω) ∈ (Subtype.val : ↥Ω → ℂ) ⁻¹' U) :
    Set.range (VanKampen.pi1U ((Subtype.val : ↥Ω → ℂ) ⁻¹' U) hx)
      = Set.range (FundamentalGroup.map (subsetIncl h) (⟨z₀, hz₀⟩ : ↥U)) := by
  set b : ↥((Subtype.val : ↥Ω → ℂ) ⁻¹' U) := ⟨⟨z₀, h hz₀⟩, hx⟩ with hbdef
  have key : ∀ g, VanKampen.pi1U ((Subtype.val : ↥Ω → ℂ) ⁻¹' U) hx g
      = FundamentalGroup.map (subsetIncl h) (⟨z₀, hz₀⟩ : ↥U)
          (FundamentalGroup.map (regionSubMap h) b g) := fun g =>
    fundamentalGroup_map_comp (subsetIncl h) (regionSubMap h) b g
  have hsurj : Function.Surjective (FundamentalGroup.map (regionSubMap h) b) :=
    fundamentalGroup_map_regionSubMap_surjective h b
  ext γ
  simp only [Set.mem_range]
  constructor
  · rintro ⟨g, rfl⟩
    exact ⟨_, (key g).symm⟩
  · rintro ⟨c, rfl⟩
    obtain ⟨g, rfl⟩ := hsurj c
    exact ⟨g, key g⟩

/-- The second inclusion-induced map of Seifert–van Kampen, read as a map of fundamental groups of
regions of the plane. -/
theorem range_pi1V_eq_range_map {Ω V : Set ℂ} (h : V ⊆ Ω) {z₀ : ℂ} (hz₀ : z₀ ∈ V)
    (hx : (⟨z₀, h hz₀⟩ : ↥Ω) ∈ (Subtype.val : ↥Ω → ℂ) ⁻¹' V) :
    Set.range (VanKampen.pi1V ((Subtype.val : ↥Ω → ℂ) ⁻¹' V) hx)
      = Set.range (FundamentalGroup.map (subsetIncl h) (⟨z₀, hz₀⟩ : ↥V)) := by
  set b : ↥((Subtype.val : ↥Ω → ℂ) ⁻¹' V) := ⟨⟨z₀, h hz₀⟩, hx⟩ with hbdef
  have key : ∀ g, VanKampen.pi1V ((Subtype.val : ↥Ω → ℂ) ⁻¹' V) hx g
      = FundamentalGroup.map (subsetIncl h) (⟨z₀, hz₀⟩ : ↥V)
          (FundamentalGroup.map (regionSubMap h) b g) := fun g =>
    fundamentalGroup_map_comp (subsetIncl h) (regionSubMap h) b g
  have hsurj : Function.Surjective (FundamentalGroup.map (regionSubMap h) b) :=
    fundamentalGroup_map_regionSubMap_surjective h b
  ext γ
  simp only [Set.mem_range]
  constructor
  · rintro ⟨g, rfl⟩
    exact ⟨_, (key g).symm⟩
  · rintro ⟨c, rfl⟩
    obtain ⟨g, rfl⟩ := hsurj c
    exact ⟨g, key g⟩

/-! ### Seifert–van Kampen for a cover of a region -/

variable {Ω U V : Set ℂ}

/-- **Seifert–van Kampen for regions of the plane, generation form.**  A region covered by two open
subregions with path connected overlap has its fundamental group generated by the images of the
fundamental groups of the two pieces. -/
theorem closure_range_subsetIncl_eq_top (hU : U ⊆ Ω) (hV : V ⊆ Ω) (hcover : Ω ⊆ U ∪ V)
    (hUopen : IsOpen U) (hVopen : IsOpen V) [PathConnectedSpace ↥U] [PathConnectedSpace ↥V]
    [PathConnectedSpace ↥(U ∩ V)] {z₀ : ℂ} (hz₀U : z₀ ∈ U) (hz₀V : z₀ ∈ V) :
    Subgroup.closure
        (Set.range (FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀U⟩ : ↥U)) ∪
          Set.range (FundamentalGroup.map (subsetIncl hV) (⟨z₀, hz₀V⟩ : ↥V))) = ⊤ := by
  set U' : Set ↥Ω := (Subtype.val : ↥Ω → ℂ) ⁻¹' U with hU'def
  set V' : Set ↥Ω := (Subtype.val : ↥Ω → ℂ) ⁻¹' V with hV'def
  have hxU' : (⟨z₀, hU hz₀U⟩ : ↥Ω) ∈ U' := hz₀U
  have hxV' : (⟨z₀, hU hz₀U⟩ : ↥Ω) ∈ V' := hz₀V
  have hUV' : U' ∪ V' = Set.univ := by
    refine Set.eq_univ_iff_forall.2 fun w => ?_
    rcases hcover w.2 with hw | hw
    · exact Or.inl hw
    · exact Or.inr hw
  haveI : PathConnectedSpace ↥U' := pathConnectedSpace_preimage hU
  haveI : PathConnectedSpace ↥V' := pathConnectedSpace_preimage hV
  haveI : PathConnectedSpace ↥(U' ∩ V') :=
    pathConnectedSpace_preimage (Ω := Ω) (U := U ∩ V) (Set.inter_subset_left.trans hU)
  have hmain := VanKampen.closure_range_pi1_union_of_pathConnected U' V' hxU' hxV' hUV'
    (hUopen.preimage continuous_subtype_val) (hVopen.preimage continuous_subtype_val)
  rwa [range_pi1U_eq_range_map hU hz₀U hxU', range_pi1V_eq_range_map hV hz₀V hxV'] at hmain

/-- **Seifert–van Kampen for regions of the plane**, as a criterion for a subgroup to be
everything: a subgroup of the fundamental group of a region containing the image of the
fundamental group of each piece of an open cover is the whole group. -/
theorem eq_top_of_cover (hU : U ⊆ Ω) (hV : V ⊆ Ω) (hcover : Ω ⊆ U ∪ V) (hUopen : IsOpen U)
    (hVopen : IsOpen V) [PathConnectedSpace ↥U] [PathConnectedSpace ↥V]
    [PathConnectedSpace ↥(U ∩ V)] {z₀ : ℂ} (hz₀U : z₀ ∈ U) (hz₀V : z₀ ∈ V)
    {N : Subgroup (FundamentalGroup ↥Ω ⟨z₀, hU hz₀U⟩)}
    (hNU : ∀ g, FundamentalGroup.map (subsetIncl hU) (⟨z₀, hz₀U⟩ : ↥U) g ∈ N)
    (hNV : ∀ g, FundamentalGroup.map (subsetIncl hV) (⟨z₀, hz₀V⟩ : ↥V) g ∈ N) : N = ⊤ := by
  refine eq_top_iff.mpr ?_
  rw [← closure_range_subsetIncl_eq_top hU hV hcover hUopen hVopen hz₀U hz₀V]
  refine Subgroup.closure_le N |>.mpr ?_
  rintro γ (⟨g, rfl⟩ | ⟨g, rfl⟩)
  · exact hNU g
  · exact hNV g

end Rigidity.RET

end
