/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Pi1.Topological.BoxLoop
import InverseGalois.Rigidity.RET.Pi1.Topological.CircleLoop

/-!
# The square inscribed in a punctured disc

A punctured disc has an infinite cyclic fundamental group, generated by the circle running once
around the centre.  This file replaces that circle by the boundary of a square centred at the
puncture: the two loops are homotopic in the disc, so the square generates as well.

The comparison is the straight-line homotopy of `ConvexHomotopy.lean`.  Its hypothesis is that the
side and the quarter circle are never seen from the centre in opposite directions, which reduces
to the elementary inequality `(1 - u) cos (uπ/2) + u sin (uπ/2) > 0` on the unit interval.  The
same reduction works for all four quarters at once, since rotating by a right angle changes
nothing.

The point of the square is that its sides are straight, so the boundary loop is a `boxLoop` and
the cutting calculus of `BoxLoop.lean` applies to it.

## Main results

* `Rigidity.RET.sqArc` — a quarter of the circle inscribing the square.
* `Rigidity.RET.sqSide_subset` — a side of the square stays inside the punctured disc.
* `Rigidity.RET.boxLoop_eq_discLoop` — the boundary of the square is the circle loop.
* `Rigidity.RET.zpowers_boxLoop_eq_top` — the boundary of the square generates the fundamental
  group of the punctured disc.
-/

open scoped unitInterval

noncomputable section

namespace Rigidity.RET

/-! ### Norms compared through the square norm -/

/-- A bound on the square norm bounds the norm. -/
theorem norm_le_of_normSq_le {z : ℂ} {r : ℝ} (hr : 0 ≤ r) (h : Complex.normSq z ≤ r ^ 2) :
    ‖z‖ ≤ r := by
  have hz : Complex.normSq z = ‖z‖ ^ 2 := Complex.normSq_eq_norm_sq z
  nlinarith [norm_nonneg z]

/-- A strict bound on the square norm bounds the norm strictly. -/
theorem norm_lt_of_normSq_lt {z : ℂ} {r : ℝ} (hr : 0 ≤ r) (h : Complex.normSq z < r ^ 2) :
    ‖z‖ < r := by
  have hz : Complex.normSq z = ‖z‖ ^ 2 := Complex.normSq_eq_norm_sq z
  nlinarith [norm_nonneg z]

/-! ### The interpolation factor along a side -/

/-- The point of the segment from `1` to `i` at parameter `u`.  A side of the square is the centre
plus a rotation of `w` times this factor. -/
def segFactor (u : ℝ) : ℂ := ((1 - u : ℝ) : ℂ) + ((u : ℝ) : ℂ) * Complex.I

theorem normSq_segFactor (u : ℝ) : Complex.normSq (segFactor u) = (1 - u) ^ 2 + u ^ 2 := by
  simp [segFactor, Complex.normSq_apply]
  ring

/-- The side of the square is no further from the centre than its vertices are. -/
theorem norm_segFactor_le_one {u : ℝ} (h0 : 0 ≤ u) (h1 : u ≤ 1) : ‖segFactor u‖ ≤ 1 := by
  refine norm_le_of_normSq_le zero_le_one ?_
  rw [normSq_segFactor]
  nlinarith

/-- The side of the square misses the centre. -/
theorem segFactor_ne_zero {u : ℝ} (h1 : u ≤ 1) : segFactor u ≠ 0 := by
  intro hcon
  have h := normSq_segFactor u
  rw [hcon] at h
  simp only [map_zero] at h
  nlinarith

/-! ### The core positivity estimate -/

theorem exp_ofReal_mul_I (θ : ℝ) :
    Complex.exp ((θ : ℂ) * Complex.I)
      = ((Real.cos θ : ℝ) : ℂ) + ((Real.sin θ : ℝ) : ℂ) * Complex.I := by
  rw [Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin]

/-- The angle between a side of the square and the corresponding point of the quarter circle is
acute.  Away from the far vertex the cosine term is already positive; at the far vertex the two
points coincide and the sine term takes over. -/
theorem quarter_pos {u : ℝ} (h0 : 0 ≤ u) (h1 : u ≤ 1) :
    0 < (1 - u) * Real.cos (u * (Real.pi / 2)) + u * Real.sin (u * (Real.pi / 2)) := by
  have hpi : 0 < Real.pi := Real.pi_pos
  rcases eq_or_lt_of_le h1 with rfl | hu1
  · norm_num [Real.sin_pi_div_two]
  · have hθ0 : 0 ≤ u * (Real.pi / 2) := by positivity
    have hθlt : u * (Real.pi / 2) < Real.pi / 2 := by nlinarith
    have hcos : 0 < Real.cos (u * (Real.pi / 2)) :=
      Real.cos_pos_of_mem_Ioo ⟨by linarith, hθlt⟩
    have hsin : 0 ≤ Real.sin (u * (Real.pi / 2)) :=
      Real.sin_nonneg_of_nonneg_of_le_pi hθ0 (by linarith)
    nlinarith

/-- **A side of the square and the corresponding quarter circle are never seen from the centre in
opposite directions.**  The rotation `ζ` cancels against its conjugate, so the estimate does not
depend on which of the four quarters is meant. -/
theorem re_pos_core {w ζ : ℂ} (hζ : ζ ≠ 0) (hw : w ≠ 0) {u : ℝ} (h0 : 0 ≤ u) (h1 : u ≤ 1) :
    0 < (ζ * w * segFactor u * (starRingEnd ℂ)
      (ζ * Complex.exp (((u * (Real.pi / 2) : ℝ) : ℂ) * Complex.I) * w)).re := by
  have key : ∀ θ : ℝ, ζ * w * segFactor u * (starRingEnd ℂ)
      (ζ * Complex.exp ((θ : ℂ) * Complex.I) * w)
      = ((Complex.normSq ζ * Complex.normSq w : ℝ) : ℂ)
        * (segFactor u * (starRingEnd ℂ) (Complex.exp ((θ : ℂ) * Complex.I))) := by
    intro θ
    push_cast
    simp only [map_mul, ← Complex.mul_conj]
    ring
  have hconj : ∀ θ : ℝ, (starRingEnd ℂ) (Complex.exp ((θ : ℂ) * Complex.I))
      = ((Real.cos θ : ℝ) : ℂ) - ((Real.sin θ : ℝ) : ℂ) * Complex.I := by
    intro θ
    rw [exp_ofReal_mul_I, map_add, map_mul, Complex.conj_ofReal, Complex.conj_ofReal,
      Complex.conj_I]
    ring
  have hre : ∀ θ : ℝ, (((Complex.normSq ζ * Complex.normSq w : ℝ) : ℂ)
      * (segFactor u * (((Real.cos θ : ℝ) : ℂ) - ((Real.sin θ : ℝ) : ℂ) * Complex.I))).re
      = Complex.normSq ζ * Complex.normSq w
        * ((1 - u) * Real.cos θ + u * Real.sin θ) := by
    intro θ
    simp only [segFactor, Complex.mul_re, Complex.mul_im, Complex.sub_re, Complex.sub_im,
      Complex.add_re, Complex.add_im, Complex.ofReal_re, Complex.ofReal_im, Complex.I_re,
      Complex.I_im]
    ring
  rw [key, hconj, hre]
  exact mul_pos (mul_pos (Complex.normSq_pos.mpr hζ) (Complex.normSq_pos.mpr hw))
    (quarter_pos h0 h1)

/-! ### The square inscribed in a punctured disc -/

/-- The circle inscribing the square stays in the punctured disc. -/
theorem arc_mem_puncturedDisc {s w : ℂ} {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ) (x : ℝ) :
    s + Complex.exp ((x : ℂ) * Complex.I) * w ∈ puncturedDisc s ρ := by
  have hne : Complex.exp ((x : ℂ) * Complex.I) * w ≠ 0 :=
    mul_ne_zero (Complex.exp_ne_zero _) hw
  refine mem_puncturedDisc.mpr ⟨?_, ?_⟩
  · rw [add_sub_cancel_left, norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]
    exact hwρ
  · intro h
    exact hne (by simpa using congrArg (fun z => z - s) h)

/-- **A side of the square inscribed in a punctured disc stays in the disc.** -/
theorem sqSide_subset {s w : ℂ} {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ) (φ : ℝ) {p q : ℂ}
    (hp : p = s + Complex.exp ((φ : ℂ) * Complex.I) * w)
    (hq : q = s + Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w) :
    seg p q ⊆ puncturedDisc s ρ := by
  rintro z ⟨t, ⟨ht0, ht1⟩, rfl⟩
  have hexp : Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I)
      = Complex.exp ((φ : ℂ) * Complex.I) * Complex.I := by
    rw [show (((φ + Real.pi / 2 : ℝ) : ℂ)) * Complex.I
        = (φ : ℂ) * Complex.I + ((Real.pi : ℂ) / 2) * Complex.I by push_cast; ring,
      Complex.exp_add, Complex.exp_pi_div_two_mul_I]
  have hz : p + (t : ℂ) * (q - p)
      = s + Complex.exp ((φ : ℂ) * Complex.I) * w * segFactor t := by
    rw [hp, hq, hexp]
    simp only [segFactor]
    push_cast
    ring
  rw [hz]
  refine mem_puncturedDisc.mpr ⟨?_, ?_⟩
  · rw [add_sub_cancel_left, norm_mul, norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]
    calc ‖w‖ * ‖segFactor t‖ ≤ ‖w‖ * 1 :=
          mul_le_mul_of_nonneg_left (norm_segFactor_le_one ht0 ht1) (norm_nonneg w)
      _ = ‖w‖ := mul_one _
      _ < ρ := hwρ
  · intro h
    have : Complex.exp ((φ : ℂ) * Complex.I) * w * segFactor t = 0 := by
      simpa using congrArg (fun z => z - s) h
    exact mul_ne_zero (mul_ne_zero (Complex.exp_ne_zero _) hw) (segFactor_ne_zero ht1) this

/-- A quarter of the circle inscribing the square, from the vertex at angle `φ` to the next one. -/
def sqArc (s w : ℂ) {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ) (φ : ℝ)
    (p q : ↥(puncturedDisc s ρ))
    (hp : (p : ℂ) = s + Complex.exp ((φ : ℂ) * Complex.I) * w)
    (hq : (q : ℂ) = s + Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w) :
    Path p q where
  toFun u :=
    ⟨s + Complex.exp (((φ + (u : ℝ) * (Real.pi / 2) : ℝ) : ℂ) * Complex.I) * w,
      arc_mem_puncturedDisc hw hwρ _⟩
  continuous_toFun := by
    refine Continuous.subtype_mk ?_ _
    fun_prop
  source' := by
    refine Subtype.ext ?_
    rw [hp]
    norm_num
  target' := by
    refine Subtype.ext ?_
    rw [hq]
    norm_num

@[simp] theorem coe_sqArc (s w : ℂ) {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ) (φ : ℝ)
    (p q : ↥(puncturedDisc s ρ))
    (hp : (p : ℂ) = s + Complex.exp ((φ : ℂ) * Complex.I) * w)
    (hq : (q : ℂ) = s + Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w) (u : I) :
    ((sqArc s w hw hwρ φ p q hp hq u : ↥(puncturedDisc s ρ)) : ℂ)
      = s + Complex.exp (((φ + (u : ℝ) * (Real.pi / 2) : ℝ) : ℂ) * Complex.I) * w := rfl

/-! ### Comparing a side with its quarter circle -/

/-- Two concatenations use the same reparametrisation, so a pointwise comparison of the halves
gives a pointwise comparison of the wholes. -/
theorem re_pos_trans {X : Set ℂ} {s : ℂ} {x y z x' y' z' : ↥X}
    {P : Path x y} {Q : Path y z} {P' : Path x' y'} {Q' : Path y' z'}
    (hP : ∀ t, 0 < ((((P t : ↥X) : ℂ) - s) * (starRingEnd ℂ) (((P' t : ↥X) : ℂ) - s)).re)
    (hQ : ∀ t, 0 < ((((Q t : ↥X) : ℂ) - s) * (starRingEnd ℂ) (((Q' t : ↥X) : ℂ) - s)).re)
    (t : I) :
    0 < (((((P.trans Q) t : ↥X) : ℂ) - s) *
      (starRingEnd ℂ) (((((P'.trans Q') t : ↥X)) : ℂ) - s)).re := by
  rw [Path.trans_apply, Path.trans_apply]
  split_ifs with h
  · exact hP _
  · exact hQ _

/-- **A side of the square and its quarter circle are seen from the puncture at an acute angle**,
at every parameter. -/
theorem re_pos_quarter {s w : ℂ} {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ) (φ : ℝ)
    (p q : ↥(puncturedDisc s ρ))
    (hp : (p : ℂ) = s + Complex.exp ((φ : ℂ) * Complex.I) * w)
    (hq : (q : ℂ) = s + Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w)
    (hseg : seg (p : ℂ) (q : ℂ) ⊆ puncturedDisc s ρ) (u : I) :
    0 < ((((segPath p q hseg u : ↥(puncturedDisc s ρ)) : ℂ) - s) * (starRingEnd ℂ)
      (((sqArc s w hw hwρ φ p q hp hq u : ↥(puncturedDisc s ρ)) : ℂ) - s)).re := by
  have hexp : Complex.exp (((φ + Real.pi / 2 : ℝ) : ℂ) * Complex.I)
      = Complex.exp ((φ : ℂ) * Complex.I) * Complex.I := by
    rw [show (((φ + Real.pi / 2 : ℝ) : ℂ)) * Complex.I
        = (φ : ℂ) * Complex.I + ((Real.pi : ℂ) / 2) * Complex.I by push_cast; ring,
      Complex.exp_add, Complex.exp_pi_div_two_mul_I]
  have hval : ((segPath p q hseg u : ↥(puncturedDisc s ρ)) : ℂ) - s
      = Complex.exp ((φ : ℂ) * Complex.I) * w * segFactor (u : ℝ) := by
    rw [coe_segPath, hp, hq, hexp]
    simp only [segFactor]
    push_cast
    ring
  have hval2 : ((sqArc s w hw hwρ φ p q hp hq u : ↥(puncturedDisc s ρ)) : ℂ) - s
      = Complex.exp ((φ : ℂ) * Complex.I)
        * Complex.exp ((((u : ℝ) * (Real.pi / 2) : ℝ) : ℂ) * Complex.I) * w := by
    rw [coe_sqArc, show (((φ + (u : ℝ) * (Real.pi / 2) : ℝ) : ℂ)) * Complex.I
        = (φ : ℂ) * Complex.I + ((((u : ℝ) * (Real.pi / 2) : ℝ) : ℂ)) * Complex.I by
      push_cast; ring, Complex.exp_add]
    ring
  rw [hval, hval2]
  exact re_pos_core (Complex.exp_ne_zero _) hw u.2.1 u.2.2

/-! ### The boundary of the square -/

theorem mem_ball_of_mem_puncturedDisc {s : ℂ} {ρ : ℝ} (z : ↥(puncturedDisc s ρ)) :
    (z : ℂ) ∈ Metric.ball s ρ := z.2.1

theorem add_exp_mul_congr {s w A B : ℂ} (h : A = B) :
    s + Complex.exp A * w = s + Complex.exp B * w := by rw [h]

/-- **The boundary of the square centred at the puncture is the circle loop of the disc.**  The
circle is the concatenation of the four quarters joining consecutive vertices, and each quarter is
homotopic to the side joining the same two vertices by the straight-line homotopy. -/
theorem boxLoop_eq_discLoop {s w : ℂ} {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ)
    (hab : seg (s + w) (s + Complex.I * w) ⊆ puncturedDisc s ρ)
    (hbc : seg (s + Complex.I * w) (s - w) ⊆ puncturedDisc s ρ)
    (hcd : seg (s - w) (s - Complex.I * w) ⊆ puncturedDisc s ρ)
    (hda : seg (s - Complex.I * w) (s + w) ⊆ puncturedDisc s ρ) :
    boxLoop hab hbc hcd hda
      = Path.Homotopic.Quotient.mk (discLoop s ⟨s + w, hab (left_mem_seg _ _)⟩) := by
  have e0 : (s + w : ℂ) = s + Complex.exp (((0 : ℝ) : ℂ) * Complex.I) * w := by
    rw [show ((0 : ℝ) : ℂ) * Complex.I = 0 by push_cast; ring, Complex.exp_zero]
    ring
  have e1 : (s + Complex.I * w : ℂ)
      = s + Complex.exp (((0 + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w := by
    rw [show ((0 + Real.pi / 2 : ℝ) : ℂ) * Complex.I = (Real.pi : ℂ) / 2 * Complex.I by
      push_cast; ring, Complex.exp_pi_div_two_mul_I]
  have e2 : (s - w : ℂ)
      = s + Complex.exp (((0 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I) * w := by
    rw [show ((0 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I = (Real.pi : ℂ) * Complex.I by
      push_cast; ring, Complex.exp_pi_mul_I]
    ring
  have e3 : (s - Complex.I * w : ℂ)
      = s + Complex.exp (((0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I)
        * w := by
    rw [show ((0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I
        = (Real.pi : ℂ) * Complex.I + (Real.pi : ℂ) / 2 * Complex.I by push_cast; ring,
      Complex.exp_add, Complex.exp_pi_mul_I, Complex.exp_pi_div_two_mul_I]
    ring
  have e4 : (s + w : ℂ)
      = s + Complex.exp
        (((0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I)
        * w := by
    rw [show ((0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2 : ℝ) : ℂ) * Complex.I
        = 2 * (Real.pi : ℂ) * Complex.I by push_cast; ring, Complex.exp_two_pi_mul_I]
    ring
  have hdisc : discLoop s (⟨s + w, hab (left_mem_seg _ _)⟩ : ↥(puncturedDisc s ρ))
      = ((sqArc s w hw hwρ 0 ⟨s + w, hab (left_mem_seg _ _)⟩
              ⟨s + Complex.I * w, hab (right_mem_seg _ _)⟩ e0 e1).trans
          (sqArc s w hw hwρ (0 + Real.pi / 2) ⟨s + Complex.I * w, hbc (left_mem_seg _ _)⟩
              ⟨s - w, hbc (right_mem_seg _ _)⟩ e1 e2)).trans
        ((sqArc s w hw hwρ (0 + Real.pi / 2 + Real.pi / 2) ⟨s - w, hcd (left_mem_seg _ _)⟩
              ⟨s - Complex.I * w, hcd (right_mem_seg _ _)⟩ e2 e3).trans
          (sqArc s w hw hwρ (0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2)
              ⟨s - Complex.I * w, hda (left_mem_seg _ _)⟩ ⟨s + w, hda (right_mem_seg _ _)⟩
              e3 e4)) := by
    refine Path.ext (funext fun t => Subtype.ext ?_)
    simp only [coe_discLoop, Path.trans_apply]
    split_ifs with h1 h2 h3 <;>
      · rw [coe_sqArc, add_sub_cancel_left]
        refine add_exp_mul_congr ?_
        push_cast
        ring
  simp only [boxLoop, segArrow, ← Path.Homotopic.Quotient.mk_trans]
  rw [hdisc]
  refine Quotient.sound (homotopic_of_re_pos (K := Metric.ball s ρ)
    (isSegClosed_iff_convex.mpr (convex_ball s ρ)) (fun z hz => hz) _ _
    (fun t => mem_ball_of_mem_puncturedDisc _) (fun t => mem_ball_of_mem_puncturedDisc _) ?_)
  exact re_pos_trans
    (re_pos_trans (re_pos_quarter hw hwρ 0 _ _ e0 e1 hab)
      (re_pos_quarter hw hwρ (0 + Real.pi / 2) _ _ e1 e2 hbc))
    (re_pos_trans (re_pos_quarter hw hwρ (0 + Real.pi / 2 + Real.pi / 2) _ _ e2 e3 hcd)
      (re_pos_quarter hw hwρ (0 + Real.pi / 2 + Real.pi / 2 + Real.pi / 2) _ _ e3 e4 hda))

/-- **The boundary of a square around the puncture generates the fundamental group of a punctured
disc.** -/
theorem zpowers_boxLoop_eq_top {s w : ℂ} {ρ : ℝ} (hw : w ≠ 0) (hwρ : ‖w‖ < ρ)
    (hab : seg (s + w) (s + Complex.I * w) ⊆ puncturedDisc s ρ)
    (hbc : seg (s + Complex.I * w) (s - w) ⊆ puncturedDisc s ρ)
    (hcd : seg (s - w) (s - Complex.I * w) ⊆ puncturedDisc s ρ)
    (hda : seg (s - Complex.I * w) (s + w) ⊆ puncturedDisc s ρ) :
    Subgroup.zpowers (FundamentalGroup.fromPath (boxLoop hab hbc hcd hda)) = ⊤ := by
  have hρ : 0 < ρ := lt_of_le_of_lt (norm_nonneg w) hwρ
  rw [boxLoop_eq_discLoop hw hwρ hab hbc hcd hda]
  exact zpowers_discLoop_eq_top s hρ _

end Rigidity.RET

end
