/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.RET.Descent
import InverseGalois.Rigidity.RET.Descent.BaseTransfer
import InverseGalois.Rigidity.RET.Descent.RegularFixedField

/-!
# The index-two descent: from a three-point rigid group to a normal subgroup of index two

The rigidity method needs a *rationally rigid* class triple, and many groups have none while their
automorphism group does.  The classical remedy (Matzat; Malle–Matzat, *Inverse Galois Theory*
I.§5) applies rigidity to the overgroup `A` and then descends along an index-two normal subgroup
`H ⊴ A`.  This file states and assembles that descent.

## The mathematics

Let `A` carry a rigidity certificate with **three** branch points, and let `H ⊴ A` have index `2`.
The certificate produces a regular Galois extension `L / ℚ(T)` with group `A`, branched over three
rational points `t₀, t₁, t₂`, the inertia group over `tᵢ` being generated by the `i`-th branch
cycle `bᵢ`.

* **Parity.**  The branch cycles satisfy `b₀ b₁ b₂ = 1` and generate `A`, so — reading the relation
  in the two-element group `A / H` — *exactly two* of them lie outside `H`
  (`exists_two_notMem_of_index_two`).  Say `b₀, b₁ ∉ H` and `b₂ ∈ H`.
* **The quadratic subfield.**  `F = L^H` is a quadratic extension of `ℚ(T)`, regular over `ℚ`, so
  `F = ℚ(T)(√f)` with `f ∈ ℚ[T]` squarefree.  A finite place `p` of `ℚ(T)` ramifies in `F` exactly
  when the inertia group above `p` is not contained in `H`.  Away from the branch points the
  inertia is trivial; over `t₂` it is `⟨b₂⟩ ≤ H`; over `t₀` and `t₁` it is `⟨b₀⟩`, `⟨b₁⟩ ⊄ H`.
  Hence `f = c (T - t₀)(T - t₁)` up to squares.
* **Rationality.**  A conic with a rational point is rational: with `y² = c (T - t₀)(T - t₁)` and
  `u = y / (T - t₀)` one has `T = (t₀ u² - c t₁) / (u² - c)` and `y = u (T - t₀)`, so `F = ℚ(u)`.
* **Conclusion.**  `L / F` is Galois with group `H`, and `L` is regular over `ℚ`; transporting along
  `F ≃ₐ[ℚ] ℚ(u)` realizes `H` regularly over `ℚ(T)`.

## Main definitions

* `BranchedRegularCover` — a regular Galois cover of the `ℚ`-line together with its rational branch
  points, its branch cycles, and the two ramification statements that pin the branch locus: the
  inertia over a branch point is generated by the corresponding branch cycle, and the inertia
  elsewhere is trivial.
* `BranchedRegularCover.sub` — the intermediate field cut out by a subgroup of the deck group.
* `BranchedRegularCover.HasConicSubfield` — the statement that the cut-out field is generated over
  `ℚ(T)` by a square root of `d (T - tᵢ)(T - tⱼ)` for two of the three branch points.

## Main results

* `exists_two_notMem_of_index_two` — the parity count on a product-one generating triple.
* `nonempty_algEquiv_ratFunc_of_transcendental` — a field generated by one transcendental element
  is a rational function field.
* `nonempty_algEquiv_ratFunc_of_conic` — a conic with a rational point is a rational function
  field.
* `BranchedRegularCover.finrank_sub` — the degree of the cut-out field is the index of the
  subgroup.
* `BranchedRegularCover.sub_algEquiv_ratFunc` — a conic subfield of a three-point cover is a
  rational function field over `ℚ`.
* `isRegularInverseGalois_of_conicSubfield` — the descent: a subgroup cutting out a conic subfield
  of a three-point regular cover is a regular Galois group over `ℚ`.

## The geometric input

The parity count `exists_two_notMem_of_index_two` says which two branch points the quadratic
subfield of an index-two subgroup must be ramified over, and the ramification fields
`BranchedRegularCover.inertia_eq` and `BranchedRegularCover.inertia_bot` are exactly what is needed
to turn that count into a conic equation.  Carrying that step out, and producing a
`BranchedRegularCover` from a `RigidityCertificate` in the first place, are geometric arguments
about the integral model that this file takes as input rather than proving: they are the two
hypotheses `c : BranchedRegularCover A 3` and `c.HasConicSubfield H` of
`isRegularInverseGalois_of_conicSubfield`.  See `docs/Development/Shih.md`.
-/

open Polynomial

/-! ## Regularity passes to subfields -/

/-- **A subfield of a regular extension is regular.**  If `k` is relatively algebraically closed in
`B` and `A` embeds in `B` over `k`, then it is relatively algebraically closed in `A`. -/
theorem algebraicClosure_eq_bot_of_algHom {k A B : Type*} [Field k] [Field A] [Field B]
    [Algebra k A] [Algebra k B] (f : A →ₐ[k] B) (h : algebraicClosure k B = ⊥) :
    algebraicClosure k A = ⊥ := by
  refine bot_unique fun x hx => ?_
  have hfx : f x ∈ algebraicClosure k B := (map_mem_algebraicClosure_iff f).mpr hx
  obtain ⟨c, hc⟩ := IntermediateField.mem_bot.mp (h ▸ hfx)
  refine IntermediateField.mem_bot.mpr ⟨c, f.injective ?_⟩
  show f (algebraMap k A c) = f x
  rw [f.commutes, hc]

/-! ## A conic with a rational point is a rational function field -/

open scoped IntermediateField in
/-- **A field generated by one transcendental element is a rational function field.**

The evaluation `k[X] → F` at a transcendental `u` is injective, so it extends to the fraction
field; its image is an intermediate field containing `u`, hence everything. -/
theorem nonempty_algEquiv_ratFunc_of_transcendental {k F : Type*} [Field k] [Field F]
    [Algebra k F] {u : F} (hu : Transcendental k u)
    (htop : IntermediateField.adjoin k ({u} : Set F) = ⊤) :
    Nonempty (RatFunc k ≃ₐ[k] F) := by
  classical
  have hinj : Function.Injective (Polynomial.aeval u : k[X] →ₐ[k] F) :=
    transcendental_iff_injective.mp hu
  set φ : RatFunc k →ₐ[k] F :=
    RatFunc.liftAlgHom (Polynomial.aeval u : k[X] →ₐ[k] F)
      (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _ hinj) with hφ
  have hX : φ RatFunc.X = u := by
    have h1 : φ (algebraMap k[X] (RatFunc k) X) / φ (algebraMap k[X] (RatFunc k) 1) =
        (Polynomial.aeval u : k[X] →ₐ[k] F) X / (Polynomial.aeval u : k[X] →ₐ[k] F) 1 :=
      RatFunc.liftAlgHom_apply_div' _ _ _ _
    simpa [RatFunc.algebraMap_X] using h1
  have hsurj : Function.Surjective φ := by
    have hle : IntermediateField.adjoin k ({u} : Set F) ≤ φ.fieldRange := by
      rw [IntermediateField.adjoin_le_iff]
      rintro _ rfl
      exact ⟨RatFunc.X, hX⟩
    rw [htop, top_le_iff] at hle
    intro y
    have : y ∈ φ.fieldRange := hle ▸ IntermediateField.mem_top
    exact this
  exact ⟨AlgEquiv.ofBijective φ ⟨RatFunc.liftAlgHom_injective _ hinj, hsurj⟩⟩

/-- **A ring isomorphism of fields of characteristic zero is a `ℚ`-algebra isomorphism.**

Both structure maps out of `ℚ` are the rational cast, which every ring homomorphism respects. -/
theorem nonempty_algEquiv_rat_of_ringEquiv {A B : Type*} [Field A] [Field B]
    [Algebra ℚ A] [Algebra ℚ B] (e : A ≃+* B) : Nonempty (A ≃ₐ[ℚ] B) :=
  ⟨AlgEquiv.ofRingEquiv fun q => by
    rw [eq_ratCast (algebraMap ℚ A) q, eq_ratCast (algebraMap ℚ B) q]
    exact map_ratCast e q⟩

section Conic

variable {k F : Type*} [Field k] [Field F] [Algebra k F] [Algebra (RatFunc k) F]
  [IsScalarTower k (RatFunc k) F]

/-- The coordinate of the line stays transcendental over the constants in any extension. -/
theorem transcendental_algebraMap_X :
    Transcendental k (algebraMap (RatFunc k) F RatFunc.X) := by
  refine RatFunc.transcendental_X.ringHom_of_comp_eq (RingHom.id k)
    (algebraMap (RatFunc k) F) Function.surjective_id
    (algebraMap (RatFunc k) F).injective ?_
  ext q
  simp [IsScalarTower.algebraMap_apply k (RatFunc k) F]

/-- **A conic with a rational point is rational.**

If `F = k(T)(y)` with `y² = c (T - a)(T - b)` for distinct `a`, `b` and nonzero `c`, then
`u = y / (T - a)` satisfies `T = (a u² - c b) / (u² - c)` and `y = u (T - a)`, so `u` alone
generates `F` over `k`; being transcendental, it presents `F` as a rational function field. -/
theorem nonempty_algEquiv_ratFunc_of_conic {a b c : k} (hab : a ≠ b) (hc : c ≠ 0) {y : F}
    (hy : y ^ 2 = algebraMap (RatFunc k) F
      (RatFunc.C c * (RatFunc.X - RatFunc.C a) * (RatFunc.X - RatFunc.C b)))
    (htop : IntermediateField.adjoin (RatFunc k) ({y} : Set F) = ⊤) :
    Nonempty (RatFunc k ≃ₐ[k] F) := by
  classical
  set T : F := algebraMap (RatFunc k) F RatFunc.X with hT
  set A : F := algebraMap k F a with hA
  set B : F := algebraMap k F b with hB
  set C : F := algebraMap k F c with hC
  have hTtr : Transcendental k T := transcendental_algebraMap_X
  have hpush : ∀ z : k, algebraMap (RatFunc k) F (RatFunc.C z) = algebraMap k F z := by
    intro z
    rw [← RatFunc.algebraMap_eq_C, ← IsScalarTower.algebraMap_apply]
  have hy2 : y ^ 2 = C * (T - A) * (T - B) := by
    rw [hy]; simp only [map_mul, map_sub, hpush]; rfl
  have hTA : T - A ≠ 0 := by
    refine sub_ne_zero.mpr fun h => hTtr ?_
    rw [h, hA]
    exact isAlgebraic_algebraMap a
  have hCne : C ≠ 0 := by
    rw [hC, ne_eq, map_eq_zero]
    exact hc
  have hABne : A - B ≠ 0 := by
    rw [sub_ne_zero, hA, hB]
    exact fun h => hab ((algebraMap k F).injective h)
  set u : F := y / (T - A) with hu
  have hu2 : u ^ 2 * (T - A) = C * (T - B) := by
    rw [hu, div_pow, hy2]
    field_simp
  have hukey : (u ^ 2 - C) * (T - A) = C * (A - B) := by
    have h : (u ^ 2 - C) * (T - A) = u ^ 2 * (T - A) - C * (T - A) := by ring
    rw [h, hu2]; ring
  have hune : u ^ 2 - C ≠ 0 := by
    intro h
    rw [h, zero_mul] at hukey
    exact (mul_ne_zero hCne hABne) hukey.symm
  have hTeq : T * (u ^ 2 - C) = A * u ^ 2 - C * B := by linear_combination hu2
  set E : IntermediateField k F := IntermediateField.adjoin k ({u} : Set F) with hE
  have humem : u ∈ E := IntermediateField.subset_adjoin k _ rfl
  have hconst : ∀ z : k, algebraMap k F z ∈ E := fun z => E.algebraMap_mem z
  have hTmem : T ∈ E := by
    have h : T = (A * u ^ 2 - C * B) / (u ^ 2 - C) := by
      rw [eq_div_iff hune]
      linear_combination hTeq
    rw [h]
    exact div_mem (sub_mem (mul_mem (hconst a) (pow_mem humem 2))
      (mul_mem (hconst c) (hconst b))) (sub_mem (pow_mem humem 2) (hconst c))
  have hymem : y ∈ E := by
    have h : y = u * (T - A) := by rw [hu]; field_simp
    rw [h]
    exact mul_mem humem (sub_mem hTmem (hconst a))
  have hrange : Set.range (algebraMap (RatFunc k) F) ⊆ (E : Set F) := by
    rintro _ ⟨z, rfl⟩
    have hpoly : ∀ p : k[X], algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) p) ∈ E := by
      intro p
      have h1 : algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) p)
          = Polynomial.aeval T p := by
        rw [← RatFunc.aeval_X_left_eq_algebraMap p, hT]
        exact (Polynomial.aeval_algebraMap_apply F RatFunc.X p).symm
      rw [h1]
      have hsub : Algebra.adjoin k ({T} : Set F) ≤ E.toSubalgebra := by
        rw [Algebra.adjoin_le_iff]
        rintro _ rfl
        exact hTmem
      exact hsub (Polynomial.aeval_mem_adjoin_singleton k T)
    rw [← RatFunc.num_div_denom z, map_div₀]
    exact div_mem (hpoly _) (hpoly _)
  have hEtop : E = ⊤ := by
    have hle : (IntermediateField.adjoin (RatFunc k) ({y} : Set F)).toSubfield ≤ E.toSubfield :=
      IntermediateField.adjoin_le_subfield _ _ hrange (by simpa using hymem)
    rw [htop] at hle
    refine eq_top_iff.mpr fun x _ => ?_
    exact hle (by trivial)
  have hutr : Transcendental k u := by
    intro hualg
    haveI : FiniteDimensional k E := IntermediateField.adjoin.finiteDimensional hualg.isIntegral
    haveI : Algebra.IsAlgebraic k E := Algebra.IsAlgebraic.of_finite k E
    refine hTtr ?_
    have h := Algebra.IsAlgebraic.isAlgebraic (R := k) (⟨T, hTmem⟩ : E)
    simpa using h.algHom (IntermediateField.val E)
  exact nonempty_algEquiv_ratFunc_of_transcendental hutr hEtop

/-- `nonempty_algEquiv_ratFunc_of_conic` with the algebra structure forgotten, which is the form
in which the conclusion is transported across a different `ℚ`-algebra structure on `RatFunc ℚ`. -/
theorem nonempty_ringEquiv_ratFunc_of_conic {a b c : k} (hab : a ≠ b) (hc : c ≠ 0) {y : F}
    (hy : y ^ 2 = algebraMap (RatFunc k) F
      (RatFunc.C c * (RatFunc.X - RatFunc.C a) * (RatFunc.X - RatFunc.C b)))
    (htop : IntermediateField.adjoin (RatFunc k) ({y} : Set F) = ⊤) :
    Nonempty (RatFunc k ≃+* F) :=
  let ⟨e⟩ := nonempty_algEquiv_ratFunc_of_conic hab hc hy htop
  ⟨e.toRingEquiv⟩

end Conic

/-! ## The parity of a product-one triple modulo an index-two subgroup -/

/-- **Exactly two of three branch cycles are outside an index-two subgroup.**

The three entries multiply to `1` and generate the group, so in the two-element quotient their
images multiply to `1` and are not all trivial: an even, nonzero number of them is nontrivial. -/
theorem exists_two_notMem_of_index_two {A : Type*} [Group A] {H : Subgroup A} (hidx : H.index = 2)
    {b : Fin 3 → A} (hprod : (List.ofFn b).prod = 1)
    (hgen : Subgroup.closure (Set.range b) = ⊤) :
    ∃ i j : Fin 3, i ≠ j ∧ b i ∉ H ∧ b j ∉ H ∧ ∀ k, k ≠ i → k ≠ j → b k ∈ H := by
  -- `H` is a proper subgroup, so the three entries cannot all lie in it.
  have hne : ¬ (b 0 ∈ H ∧ b 1 ∈ H ∧ b 2 ∈ H) := by
    rintro ⟨h0, h1, h2⟩
    have hle : Subgroup.closure (Set.range b) ≤ H := by
      rw [Subgroup.closure_le]
      rintro _ ⟨k, rfl⟩
      fin_cases k <;> assumption
    rw [hgen, top_le_iff] at hle
    rw [hle, Subgroup.index_top] at hidx
    omega
  -- The product relation, read modulo `H`.
  have hmul : b 0 * (b 1 * b 2) ∈ H := by
    have : b 0 * (b 1 * b 2) = 1 := by
      simpa [List.ofFn_succ, mul_assoc] using hprod
    rw [this]
    exact one_mem H
  rw [Subgroup.mul_mem_iff_of_index_two hidx, Subgroup.mul_mem_iff_of_index_two hidx] at hmul
  -- Eight cases; five are excluded by the relation or by generation.
  by_cases h0 : b 0 ∈ H <;> by_cases h1 : b 1 ∈ H <;> by_cases h2 : b 2 ∈ H
  · exact absurd ⟨h0, h1, h2⟩ hne
  · exact absurd (hmul.mp h0) (by simp [h1, h2])
  · exact absurd (hmul.mp h0) (by simp [h1, h2])
  · exact ⟨1, 2, by decide, h1, h2, by intro k hk1 hk2; fin_cases k <;> simp_all⟩
  · exact absurd (hmul.mpr (by simp [h1, h2])) h0
  · exact ⟨0, 2, by decide, h0, h2, by intro k hk1 hk2; fin_cases k <;> simp_all⟩
  · exact ⟨0, 1, by decide, h0, h1, by intro k hk1 hk2; fin_cases k <;> simp_all⟩
  · exact absurd (hmul.mpr (by simp [h1, h2])) h0

/-! ## Branched regular covers of the `ℚ`-line -/

section BranchedCover

open scoped Pointwise

attribute [local instance 100] polyAlgebra

attribute [local instance] polyAlgebra_tower ArithAKLB.instMSA ArithAKLB.instIsFrac
  ArithAKLB.instIGG ArithAKLB.instFinite ArithAKLB.instIntegral ArithAKLB.instFaithfulBase
  ArithAKLB.instDedekind ArithAKLB.instFiniteGal ArithAKLB.instFaithfulGal ArithAKLB.instAlgRat

/-- **A regular Galois cover of the `ℚ`-line with its branch data.**

The output of the rigidity method, enriched with everything the index-two descent needs to see:

* the field `L`, a regular Galois extension of `ℚ(T)` with deck group `A` (`gal`, `regular`);
* the `r` branch points `branch i`, distinct `ℚ`-rational points of the line;
* the branch cycles `mono i`, a generating product-one tuple in `A`;
* `inertia_eq` — over the `i`-th branch point sits a place of the integral model whose inertia
  group is *generated by* the `i`-th branch cycle;
* `inertia_bot` — over every other finite place of the line the inertia is trivial.

The last two fields are what turn the branch cycles into a complete description of the
ramification, which is what identifies the quadratic subfields of the cover. -/
structure BranchedRegularCover (A : Type) [Group A] [Finite A] (r : ℕ) where
  /-- the cover, as a field. -/
  L : Type
  [fieldL : Field L]
  [algL : Algebra (RatFunc ℚ) L]
  [findimL : FiniteDimensional (RatFunc ℚ) L]
  [galL : IsGalois (RatFunc ℚ) L]
  [charZeroL : CharZero L]
  [towerL : IsScalarTower ℚ (RatFunc ℚ) L]
  /-- the deck group is `A`. -/
  gal : (L ≃ₐ[RatFunc ℚ] L) ≃* A
  /-- the cover is regular: it gains no constants over `ℚ`. -/
  regular : algebraicClosure ℚ L = ⊥
  /-- the `i`-th branch point, a `ℚ`-rational point of the line. -/
  branch : Fin r → ℚ
  /-- the branch points are distinct. -/
  branch_inj : Function.Injective branch
  /-- the `i`-th branch cycle. -/
  mono : Fin r → A
  /-- the branch cycles satisfy the product-one relation. -/
  mono_prod : (List.ofFn mono).prod = 1
  /-- the branch cycles generate the deck group (the cover is connected). -/
  mono_gen : Subgroup.closure (Set.range mono) = ⊤
  /-- over each branch point sits a place whose inertia group is generated by the branch cycle. -/
  inertia_eq : ∀ i, ∃ Q : Ideal (ArithAKLB.Aring L), Q.IsPrime ∧
    Q.LiesOver (Ideal.span {X - C (branch i)}) ∧
    ArithAKLB.arithInertia L Q = Subgroup.zpowers (gal.symm (mono i))
  /-- over every other finite place of the line the cover is unramified. -/
  inertia_bot : ∀ (P : Ideal (Polynomial ℚ)) (Q : Ideal (ArithAKLB.Aring L)), P.IsMaximal →
    Q.IsPrime → Q.LiesOver P → (∀ i, P ≠ Ideal.span {X - C (branch i)}) →
    ArithAKLB.arithInertia L Q = ⊥

attribute [instance] BranchedRegularCover.fieldL BranchedRegularCover.algL
  BranchedRegularCover.findimL BranchedRegularCover.galL BranchedRegularCover.charZeroL
  BranchedRegularCover.towerL

namespace BranchedRegularCover

variable {A : Type} [Group A] [Finite A] {r : ℕ}

/-- The intermediate field of the cover cut out by a subgroup of the deck group. -/
noncomputable def sub (c : BranchedRegularCover A r) (H : Subgroup A) :
    IntermediateField (RatFunc ℚ) c.L :=
  IntermediateField.fixedField (H.comap c.gal.toMonoidHom)

/-- **The subfield cut out by a subgroup has degree the index of that subgroup.**

The Galois correspondence: `[L : L^H] = |H|` and `[L : ℚ(T)] = |A|`. -/
theorem finrank_sub (c : BranchedRegularCover A r) (H : Subgroup A) :
    Module.finrank (RatFunc ℚ) ↥(c.sub H) = H.index := by
  classical
  haveI : Finite (c.L ≃ₐ[RatFunc ℚ] c.L) := Finite.of_equiv _ c.gal.symm.toEquiv
  set K : Subgroup (c.L ≃ₐ[RatFunc ℚ] c.L) := H.comap c.gal.toMonoidHom with hK
  have h1 : Module.finrank ↥(c.sub H) c.L = Nat.card K :=
    IntermediateField.finrank_fixedField_eq_card K
  have h2 : Module.finrank (RatFunc ℚ) ↥(c.sub H) * Module.finrank ↥(c.sub H) c.L
      = Module.finrank (RatFunc ℚ) c.L :=
    Module.finrank_mul_finrank (RatFunc ℚ) ↥(c.sub H) c.L
  have h3 : Module.finrank (RatFunc ℚ) c.L = Nat.card (c.L ≃ₐ[RatFunc ℚ] c.L) :=
    (IsGalois.card_aut_eq_finrank _ _).symm
  have h4 : K.index * Nat.card K = Nat.card (c.L ≃ₐ[RatFunc ℚ] c.L) := K.index_mul_card
  have h5 : K.index = H.index := by
    rw [hK]
    exact Subgroup.index_comap_of_surjective H c.gal.surjective
  have hpos : Nat.card K ≠ 0 := Nat.card_pos.ne'
  refine Nat.eq_of_mul_eq_mul_right (Nat.pos_of_ne_zero hpos) ?_
  rw [← h1, h2, h3, ← h4, h5, h1]

/-- **The subgroup cuts out a conic through two branch points.**

The intended source of this property is the ramification count.  Exactly two of the three branch
cycles lie outside an index-two subgroup (`exists_two_notMem_of_index_two`), and a finite place of
the line ramifies in the quadratic subfield exactly when the inertia above it escapes the
subgroup; so the quadratic subfield is ramified over `tᵢ` and `tⱼ` and nowhere else, which presents
it as `ℚ(T)(√(d (T - tᵢ)(T - tⱼ)))` for some nonzero rational `d`. -/
def HasConicSubfield (c : BranchedRegularCover A 3) (H : Subgroup A) : Prop :=
  ∃ (i j : Fin 3) (d : ℚ) (y : ↥(c.sub H)), i ≠ j ∧ d ≠ 0 ∧
    y ^ 2 = algebraMap (RatFunc ℚ) ↥(c.sub H) (RatFunc.C d *
      (RatFunc.X - RatFunc.C (c.branch i)) * (RatFunc.X - RatFunc.C (c.branch j))) ∧
    IntermediateField.adjoin (RatFunc ℚ) ({y} : Set ↥(c.sub H)) = ⊤

/-- **A conic subfield of a three-point cover is a rational function field.**

The subfield is a conic ramified over two rational points of the line, and a conic with a rational
point is rational. -/
theorem sub_algEquiv_ratFunc (c : BranchedRegularCover A 3) {H : Subgroup A}
    (hconic : c.HasConicSubfield H) : Nonempty (c.sub H ≃ₐ[ℚ] RatFunc ℚ) := by
  obtain ⟨i, j, d, y, hij, hd, hy, hgen⟩ := hconic
  obtain ⟨r⟩ := nonempty_ringEquiv_ratFunc_of_conic
    (F := ↥(c.sub H)) (fun h => hij (c.branch_inj h)) hd hy hgen
  -- The two `ℚ`-algebra structures on `RatFunc ℚ` agree, both being the rational cast.
  exact nonempty_algEquiv_rat_of_ringEquiv r.symm

/-- **The subfield cut out by a subgroup is a base for a regular realization of that subgroup.**

`L / (L^H)` is Galois with group `H`, and `L` is regular over `ℚ`, so no constants intervene. -/
theorem isRegularGaloisGroupOverBase_sub (c : BranchedRegularCover A r) (H : Subgroup A) :
    IsRegularGaloisGroupOverBase ℚ (c.sub H) H := by
  classical
  -- `K = gal⁻¹ H` is the subgroup of `Gal(L/ℚ(T))` cutting out `c.sub H`.
  set K : Subgroup (c.L ≃ₐ[RatFunc ℚ] c.L) := H.comap c.gal.toMonoidHom with hK
  have hmapK : K.map c.gal.toMonoidHom = H := by
    rw [hK]
    exact Subgroup.map_comap_eq_self_of_surjective c.gal.surjective H
  let eK : K ≃* H := (c.gal.subgroupMap K).trans (MulEquiv.subgroupCongr hmapK)
  -- `Gal(L / L^K) ≃* K ≃* H`.
  let ψ' : (c.L ≃ₐ[↥(c.sub H)] c.L) →* H :=
    ((IntermediateField.subgroupEquivAlgEquiv K).symm.trans eK : _ ≃* _).toMonoidHom
  have hψ'surj : Function.Surjective ψ' :=
    ((IntermediateField.subgroupEquivAlgEquiv K).symm.trans eK).surjective
  refine Rigidity.RET.isRegularGaloisGroupOverBase_fixedField (k := ℚ) (F := ↥(c.sub H)) ?_
    (⊥ : IntermediateField ↥(c.sub H) c.L) ?_ ψ' hψ'surj ?_
  · exact algebraicClosure_eq_bot_of_algHom ((c.sub H).val.restrictScalars ℚ) c.regular
  · rw [c.regular]; exact bot_le
  · intro g
    obtain ⟨n, hn⟩ := hψ'surj g
    exact ⟨n, by simp, hn⟩

end BranchedRegularCover

/-- **The descent along a conic subfield.**

If a subgroup of the deck group of a three-point regular cover of the `ℚ`-line cuts out a conic
through two of the branch points, then that subgroup is a regular Galois group over `ℚ`: the conic
is itself a rational function field, and the cover is a regular realization of the subgroup over
it. -/
theorem isRegularInverseGalois_of_conicSubfield {A : Type} [Group A] [Finite A]
    (c : BranchedRegularCover A 3) {H : Subgroup A} (hconic : c.HasConicSubfield H) :
    IsRegularInverseGalois H := by
  obtain ⟨e⟩ := c.sub_algEquiv_ratFunc hconic
  exact isRegularInverseGalois_of_overBase _
    ((c.isRegularGaloisGroupOverBase_sub H).of_algEquiv e)

end BranchedCover
