/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Rigidity.StructureConstant

/-!
# Matching the branch cycles of a cover against the certificate's tuple

The branch cycles of a cover are inertia elements of its geometric monodromy group `N`; the
certificate prescribes a tuple `base` in `G`.  A descent datum demands that the two agree *on the
nose*, `φ (gᵢ) = baseᵢ`.  What geometry delivers is weaker: the images `φ (gᵢ)` lie in the
prescribed conjugacy classes `Cᵢ`.  This module closes that gap, in the two steps in which it is
classically closed.

* **Rationality closes the choice of generator.**  A branch cycle is only determined up to replacing
  it by another generator of the same (cyclic, tame) inertia group, i.e. by a power `gᵢ ^ k` with
  `k` coprime to the order.  A *rational* class is closed under exactly those substitutions
  (`IsRationalClass.mk_eq_of_zpowers_eq`), so the class of `φ (gᵢ)` does not depend on which
  generator of the inertia group is picked.
* **Rigidity closes the conjugation.**  A tuple whose entries lie in the prescribed classes,
  generates, and has product one is a rigid tuple; rigidity says all such tuples are simultaneously
  conjugate, so a single `c ∈ G` carries `φ ∘ g` onto `base` (`Rigidity.exists_conj_comp_eq`).

Both statements are about the monodromy `φ : N ↠ G` alone, with no reference to the fields it comes
from; the geometric use is in `RET/Descent/Tower.lean`, where conjugating `φ` by `c` is again an
arithmetic model.

## Main results

* `IsRationalClass.mk_eq_of_zpowers_eq` — a rational class contains every generator of the cyclic
  group generated by any of its elements.
* `Rigidity.closure_range_map_eq_top`, `Rigidity.prod_ofFn_map_eq_one` — the two defining relations
  of a branch-cycle system travel along a surjection.
* `Rigidity.exists_conj_comp_eq` — rigidity conjugates the images of the branch cycles onto the
  certificate's tuple.
-/

namespace Rigidity

/-! ## Tuples along a group homomorphism -/

section GroupTuples

variable {G H : Type*} [Group G] [Group H]

/-- A generating tuple stays generating under a surjection. -/
theorem closure_range_map_eq_top {f : G →* H} (hf : Function.Surjective f) {r : ℕ}
    {g : Fin r → G} (htop : Subgroup.closure (Set.range g) = ⊤) :
    Subgroup.closure (Set.range fun i => f (g i)) = ⊤ := by
  have hrange : (Set.range fun i => f (g i)) = f '' Set.range g := Set.range_comp _ _
  rw [hrange, ← MonoidHom.map_closure, htop, ← MonoidHom.range_eq_map, MonoidHom.range_eq_top]
  exact hf

/-- A product-one tuple stays product-one under a homomorphism. -/
theorem prod_ofFn_map_eq_one (f : G →* H) {r : ℕ} {g : Fin r → G}
    (hprod : (List.ofFn g).prod = 1) : (List.ofFn fun i => f (g i)).prod = 1 := by
  rw [show List.ofFn (fun i => f (g i)) = (List.ofFn g).map f by rw [List.map_ofFn]; rfl,
    ← map_list_prod, hprod, map_one]

end GroupTuples

end Rigidity

/-! ## Rationality and the choice of a generator of the inertia group -/

/-- **A rational class contains every generator of the cyclic group it generates.**

If `g` lies in the rational class `c` and `g'` generates the same cyclic subgroup as `g`, then `g'`
lies in `c` as well: `g'` is a power `g ^ k` with `k` coprime to the order of `g`, and a rational
class is by definition closed under those powers.  This is what makes the class of a branch cycle
independent of which generator of the (cyclic) inertia group is chosen. -/
theorem IsRationalClass.mk_eq_of_zpowers_eq {G : Type*} [Group G] [Finite G] {c : ConjClasses G}
    (hc : IsRationalClass c) {g g' : G} (hg : ConjClasses.mk g = c)
    (h : Subgroup.zpowers g' = Subgroup.zpowers g) : ConjClasses.mk g' = c := by
  have hmem : g' ∈ Subgroup.zpowers g := h ▸ Subgroup.mem_zpowers g'
  obtain ⟨k, hk⟩ : ∃ k : ℕ, g ^ k = g' := by
    rw [← mem_powers_iff_mem_zpowers] at hmem
    obtain ⟨k, hk⟩ := hmem
    exact ⟨k, hk⟩
  have horder : orderOf g' = orderOf g := by
    rw [← Nat.card_zpowers, ← Nat.card_zpowers, h]
  have hpos : 0 < orderOf g := orderOf_pos g
  have hgcd : Nat.gcd (orderOf g) k = 1 := by
    have h1 : orderOf (g ^ k) = orderOf g / Nat.gcd (orderOf g) k := orderOf_pow g
    rw [hk, horder] at h1
    have h2 : orderOf g / Nat.gcd (orderOf g) k * Nat.gcd (orderOf g) k = orderOf g :=
      Nat.div_mul_cancel (Nat.gcd_dvd_left _ _)
    rw [← h1] at h2
    exact Nat.eq_of_mul_eq_mul_left hpos (by rw [h2, mul_one])
  have hcop : Nat.Coprime k (orderOf g) := by
    show Nat.gcd k (orderOf g) = 1
    rw [Nat.gcd_comm]
    exact hgcd
  rw [← hk]
  exact hc g hg k hcop

/-! ## Rigidity matches the images of the branch cycles with the prescribed tuple -/

namespace Rigidity

variable {G : Type} [Group G] [Finite G] {cert : RigidityCertificate G} {N : Type*} [Group N]

/-- The image of a system of branch cycles under the monodromy is a rigid tuple, as soon as its
entries lie in the prescribed classes: generation and the product-one relation travel along the
surjection `φ : N ↠ G`. -/
theorem comp_mem_rigidTuples {φ : N →* G} (hφ : Function.Surjective φ) {gen : Fin cert.r → N}
    (htop : Subgroup.closure (Set.range gen) = ⊤) (hprod : (List.ofFn gen).prod = 1)
    (hclass : ∀ i, ConjClasses.mk (φ (gen i)) = cert.C i) :
    (fun i => φ (gen i)) ∈ rigidTuples cert.C :=
  ⟨hclass, prod_ofFn_map_eq_one φ hprod, closure_range_map_eq_top hφ htop⟩

/-- **Rigidity conjugates the images of the branch cycles onto the certificate's tuple.**

The images `φ (gᵢ)` form a rigid tuple, and so does `base`; since `G` is centerless, rigidity — the
count of rigid tuples being `|G|` — says the two are related by a single simultaneous conjugation.
Only the classes of the `φ (gᵢ)` are needed, not the tuple itself. -/
theorem exists_conj_comp_eq {base : Fin cert.r → G} (hbase : base ∈ rigidTuples cert.C)
    {φ : N →* G} (hφ : Function.Surjective φ) {gen : Fin cert.r → N}
    (htop : Subgroup.closure (Set.range gen) = ⊤) (hprod : (List.ofFn gen).prod = 1)
    (hclass : ∀ i, ConjClasses.mk (φ (gen i)) = cert.C i) :
    ∃ c : G, ∀ i, c * φ (gen i) * c⁻¹ = base i := by
  have hmem := comp_mem_rigidTuples hφ htop hprod hclass
  have hZ : Subgroup.center G = ⊥ := center_triv_iff_center_eq_bot.mp cert.center_triv
  obtain ⟨x, hx⟩ := (rigid_card_iff_single_orbit hZ cert.gen).mp cert.rigid _ hmem base hbase
  refine ⟨ConjAct.ofConjAct x, fun i => ?_⟩
  have hi := congrFun hx i
  simpa [ConjAct.smul_def] using hi

end Rigidity
