/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.TateCohomology.Functorial
import InverseGalois.CFT.TateCohomology.Shifting

/-!
# The complete cohomology of a cyclic group repeats with period two

Dimension shifting replaces a representation by two auxiliary ones built from the functions on the
group: the shift, the functions modulo the record of the translates of a vector, and the coshift,
the functions whose values sum to zero.  The complete cohomology of the shift in a degree is that
of the representation one degree higher, and the complete cohomology of the coshift in a degree is
that of the representation one degree lower.  Composing the two identifications would relate a
degree to itself and say nothing, unless the shift and the coshift can be compared directly.

For a group generated by a single element they can.  Write the group multiplicatively and let the
generator be fixed.  Send a function on the group to the function whose value at a point is the
value of the original at the point translated by the generator, corrected by the inverse action of
the generator, minus the original value.  This twisted difference is equivariant, because every
element of the group commutes with the generator; it kills exactly the record of the translates of
a vector, because a function killed by it is determined by its value at the neutral element; and
its values are exactly the functions whose values sum to zero, because a telescoping sum inverts
the difference operator against the generator whenever the total vanishes.  So it identifies the
shift with the coshift, and the two dimension shifts compose into an identification of the complete
cohomology in a degree with the complete cohomology two degrees lower.

That is the periodicity which makes the arithmetic of a cyclic extension computable: a vanishing
statement in one degree propagates to every second degree above it.

## Main definitions

* `InverseGalois.CFT.Tate.cyclicDiff`: the twisted difference of a function on the group and its
  translate by a generator.
* `InverseGalois.CFT.Tate.cyclicShiftIso`: the resulting identification of the shift with the
  coshift.
* `InverseGalois.CFT.Tate.tateCyclicPeriod`: the identification of the complete cohomology of a
  representation of a finite cyclic group in a degree with the complete cohomology two degrees
  lower.

## Main results

* `InverseGalois.CFT.Tate.ker_cyclicDiff`: **the functions killed by the twisted difference are the
  records of the translates of a vector.**
* `InverseGalois.CFT.Tate.range_cyclicDiff`: **the twisted differences are the functions whose
  values sum to zero.**
* `InverseGalois.CFT.Tate.isZero_tateModule_add_two`: **a representation of a finite cyclic group
  without complete cohomology in a degree has none two degrees higher.**

## Tags

Tate cohomology, cyclic group, periodicity, dimension shifting
-/

namespace InverseGalois.CFT.Tate

open CategoryTheory Representation

universe u

noncomputable section

/-! ### Generators -/

section Generator

variable {G : Type*} [Group G] (σ : G)

/-- Every element of a group all of whose elements are powers of a fixed one commutes with that
one. -/
theorem commute_of_forall_pow (hσ : ∀ x : G, ∃ n : ℕ, σ ^ n = x) (x : G) : Commute x σ := by
  obtain ⟨n, rfl⟩ := hσ x
  exact (Commute.refl σ).pow_left n

end Generator

/-- **A finite cyclic group has a generator whose powers with natural exponent already exhaust
it.** -/
theorem exists_forall_pow (G : Type*) [Group G] [Finite G] [IsCyclic G] :
    ∃ σ : G, ∀ x : G, ∃ n : ℕ, σ ^ n = x := by
  obtain ⟨σ, hσ⟩ := IsCyclic.exists_generator (α := G)
  exact ⟨σ, fun x => (Submonoid.mem_powers_iff x σ).1 (mem_powers_iff_mem_zpowers.2 (hσ x))⟩

/-! ### The plain difference against a generator -/

section Translate

variable {k G V : Type*} [CommRing k] [Group G] [Finite G] [AddCommGroup V] [Module k V]

variable (k V) in
/-- The translate of a function on the group by an element, minus the function itself. -/
def transDiff (σ : G) : (G → V) →ₗ[k] (G → V) :=
  (inducedRep k G V σ : (G → V) →ₗ[k] (G → V)) - LinearMap.id

omit [Finite G] in
@[simp]
theorem transDiff_apply (σ : G) (f : G → V) (x : G) : transDiff k V σ f x = f (x * σ) - f x := rfl

omit [Finite G] in
/-- A translate by a power of an element, minus the function itself, is a difference against that
element. -/
theorem sub_mem_range_transDiff (σ : G) (n : ℕ) (u : G → V) :
    inducedRep k G V (σ ^ n) u - u ∈ LinearMap.range (transDiff k V σ) := by
  induction n with
  | zero => simp
  | succ n ih =>
    have key : inducedRep k G V (σ ^ (n + 1)) u - u
        = transDiff k V σ (inducedRep k G V (σ ^ n) u) + (inducedRep k G V (σ ^ n) u - u) := by
      refine funext fun x => ?_
      simp only [Pi.sub_apply, Pi.add_apply, transDiff_apply, inducedRep_apply, pow_succ',
        mul_assoc]
      abel
    rw [key]
    exact Submodule.add_mem _ (LinearMap.mem_range_self _ _) ih

omit [Finite G] in
/-- **The differences of a function on the group and its translates are already the differences
against a single generator.** -/
theorem coinvariantsKer_le_range_transDiff (σ : G) (hσ : ∀ x : G, ∃ n : ℕ, σ ^ n = x) :
    Coinvariants.ker (inducedRep k G V) ≤ LinearMap.range (transDiff k V σ) := by
  have hspan : Coinvariants.ker (inducedRep k G V)
      = Submodule.span k
        (Set.range fun gv : G × (G → V) => inducedRep k G V gv.1 gv.2 - gv.2) := rfl
  rw [hspan, Submodule.span_le]
  rintro _ ⟨⟨g, u⟩, rfl⟩
  obtain ⟨n, rfl⟩ := hσ g
  exact sub_mem_range_transDiff σ n u

end Translate

/-! ### The twisted difference against a generator -/

section Twisted

variable {k G V : Type*} [CommRing k] [Group G] [Finite G] [AddCommGroup V] [Module k V]
  (ρ : Representation k G V) (σ : G) (hσ : ∀ x : G, ∃ n : ℕ, σ ^ n = x)

/-- **The twisted difference against an element of the group**: the translate of a function by that
element, corrected by the inverse action of the element, minus the function itself. -/
def cyclicDiff : (G → V) →ₗ[k] (G → V) :=
  LinearMap.compLeft (ρ σ⁻¹ : V →ₗ[k] V) G ∘ₗ (inducedRep k G V σ : (G → V) →ₗ[k] (G → V))
    - LinearMap.id

omit [Finite G] in
@[simp]
theorem cyclicDiff_apply (f : G → V) (x : G) :
    cyclicDiff ρ σ f x = ρ σ⁻¹ (f (x * σ)) - f x := rfl

omit [Finite G] in
include hσ in
/-- The twisted difference kills the record of the translates of a vector. -/
theorem cyclicDiff_comp_coindEmb : cyclicDiff ρ σ ∘ₗ coindEmb ρ = 0 := by
  refine LinearMap.ext fun v => funext fun x => ?_
  show ρ σ⁻¹ (ρ (x * σ) v) - ρ x v = 0
  rw [← Module.End.mul_apply, ← map_mul, (commute_of_forall_pow σ hσ x).eq, ← mul_assoc,
    inv_mul_cancel, one_mul, sub_self]

omit [Finite G] in
include hσ in
/-- The twisted difference against a generator is equivariant. -/
theorem cyclicDiff_comp_inducedRep (g : G) :
    cyclicDiff ρ σ ∘ₗ (inducedRep k G V g : (G → V) →ₗ[k] (G → V))
      = (inducedRep k G V g : (G → V) →ₗ[k] (G → V)) ∘ₗ cyclicDiff ρ σ := by
  refine LinearMap.ext fun f => funext fun x => ?_
  show ρ σ⁻¹ (f (x * σ * g)) - f (x * g) = ρ σ⁻¹ (f (x * g * σ)) - f (x * g)
  simp only [mul_assoc, (commute_of_forall_pow σ hσ g).eq]

include hσ in
/-- The values of a twisted difference sum to zero. -/
theorem augMap_comp_cyclicDiff : augMap ρ ∘ₗ cyclicDiff ρ σ = 0 := by
  letI := Fintype.ofFinite G
  refine LinearMap.ext fun f => ?_
  rw [LinearMap.comp_apply, augMap_apply, LinearMap.zero_apply]
  have hsplit : ∀ x : G, ρ x⁻¹ (cyclicDiff ρ σ f x)
      = ρ (x * σ)⁻¹ (f (x * σ)) - ρ x⁻¹ (f x) := fun x => by
    rw [cyclicDiff_apply, map_sub, ← Module.End.mul_apply, ← map_mul,
      (commute_of_forall_pow σ hσ x).inv_inv.eq, ← mul_inv_rev]
  rw [Finset.sum_congr rfl fun x _ => hsplit x, Finset.sum_sub_distrib, sub_eq_zero]
  exact Fintype.sum_equiv (Equiv.mulRight σ) _ _ fun x => rfl

omit [Finite G] in
include hσ in
/-- **The functions killed by the twisted difference against a generator are the records of the
translates of a vector.** -/
theorem ker_cyclicDiff : LinearMap.ker (cyclicDiff ρ σ) = LinearMap.range (coindEmb ρ) := by
  refine le_antisymm (fun f hf => ?_)
    (LinearMap.range_le_ker_iff.2 (cyclicDiff_comp_coindEmb ρ σ hσ))
  have hstep : ∀ x : G, f (x * σ) = ρ σ (f x) := by
    intro x
    have h : ρ σ⁻¹ (f (x * σ)) = f x := by
      have h0 := congrFun (LinearMap.mem_ker.mp hf) x
      rwa [cyclicDiff_apply, Pi.zero_apply, sub_eq_zero] at h0
    rw [← h, ← Module.End.mul_apply, ← map_mul, mul_inv_cancel, map_one, Module.End.one_apply]
  have hpow : ∀ n : ℕ, f (σ ^ n) = ρ (σ ^ n) (f 1) := by
    intro n
    induction n with
    | zero => rw [pow_zero, map_one, Module.End.one_apply]
    | succ n ih =>
      have h1 : f (σ ^ (n + 1)) = ρ σ (f (σ ^ n)) := by
        rw [pow_succ]
        exact hstep (σ ^ n)
      rw [h1, ih, ← Module.End.mul_apply, ← map_mul, ← pow_succ']
  refine ⟨f 1, funext fun x => ?_⟩
  obtain ⟨n, rfl⟩ := hσ x
  rw [coindEmb_apply, hpow]

include hσ in
/-- **The twisted differences against a generator are exactly the functions whose values sum to
zero.** -/
theorem range_cyclicDiff : LinearMap.range (cyclicDiff ρ σ) = LinearMap.ker (augMap ρ) := by
  classical
  letI := Fintype.ofFinite G
  refine le_antisymm (LinearMap.range_le_ker_iff.2 (augMap_comp_cyclicDiff ρ σ hσ)) fun f hf => ?_
  have hsum : ∑ x : G, ρ x⁻¹ (f x) = 0 := by
    rw [← augMap_apply]
    exact LinearMap.mem_ker.mp hf
  have hmem : (fun x : G => ρ x⁻¹ (f x)) ∈ Coinvariants.ker (inducedRep k G V) := by
    rw [← Coinvariants.mk_eq_zero, mk_eq_mk_pi_single]
    simp only [hsum, Pi.single_zero, map_zero]
  obtain ⟨u, hu⟩ := coinvariantsKer_le_range_transDiff σ hσ hmem
  refine ⟨fun x => ρ x (u x), funext fun x => ?_⟩
  have hux : u (x * σ) - u x = ρ x⁻¹ (f x) := by
    simpa only [transDiff_apply] using congrFun hu x
  show ρ σ⁻¹ (ρ (x * σ) (u (x * σ))) - ρ x (u x) = f x
  have hfix : ρ σ⁻¹ (ρ (x * σ) (u (x * σ))) = ρ x (u (x * σ)) := by
    rw [← Module.End.mul_apply, ← map_mul, (commute_of_forall_pow σ hσ x).eq, ← mul_assoc,
      inv_mul_cancel, one_mul]
  rw [hfix, ← map_sub, hux, ← Module.End.mul_apply, ← map_mul, mul_inv_cancel, map_one,
    Module.End.one_apply]

end Twisted

/-! ### The shift and the coshift of a representation of a cyclic group -/

section Periodicity

variable {k G : Type u} [CommRing k] [Group G] [Finite G] (A : Rep k G) (σ : G)
  (hσ : ∀ x : G, ∃ n : ℕ, σ ^ n = x)

include hσ in
/-- The twisted difference against a generator, read from the shift to the coshift. -/
def cyclicShiftLinear : ↥(shiftObj A).V →ₗ[k] ↥(coshiftObj A).V :=
  Submodule.liftQ (LinearMap.range (coindEmb A.ρ))
    (LinearMap.codRestrict (LinearMap.ker (augMap A.ρ)) (cyclicDiff A.ρ σ)
      fun f => LinearMap.congr_fun (augMap_comp_cyclicDiff A.ρ σ hσ) f)
    (le_of_eq (by rw [LinearMap.ker_codRestrict, ker_cyclicDiff A.ρ σ hσ]))

theorem cyclicShiftLinear_mkQ (f : G → ↥A.V) :
    (cyclicShiftLinear A σ hσ ((LinearMap.range (coindEmb A.ρ)).mkQ f)).1
      = cyclicDiff A.ρ σ f := rfl

theorem cyclicShiftLinear_equivariant (g : G) :
    cyclicShiftLinear A σ hσ ∘ₗ (shiftObj A).ρ g
      = (coshiftObj A).ρ g ∘ₗ cyclicShiftLinear A σ hσ := by
  refine LinearMap.ext fun q => ?_
  obtain ⟨f, rfl⟩ := Submodule.mkQ_surjective (LinearMap.range (coindEmb A.ρ)) q
  exact Subtype.ext (LinearMap.congr_fun (cyclicDiff_comp_inducedRep A.ρ σ hσ g) f)

theorem cyclicShiftLinear_apply_rho (g : G) (q : ↥(shiftObj A).V) :
    cyclicShiftLinear A σ hσ ((shiftObj A).ρ g q)
      = (coshiftObj A).ρ g (cyclicShiftLinear A σ hσ q) :=
  LinearMap.congr_fun (cyclicShiftLinear_equivariant A σ hσ g) q

theorem cyclicShiftLinear_injective : Function.Injective (cyclicShiftLinear A σ hσ) := by
  intro q₁ q₂ hq
  obtain ⟨f₁, rfl⟩ := Submodule.mkQ_surjective (LinearMap.range (coindEmb A.ρ)) q₁
  obtain ⟨f₂, rfl⟩ := Submodule.mkQ_surjective (LinearMap.range (coindEmb A.ρ)) q₂
  have hd : cyclicDiff A.ρ σ (f₁ - f₂) = 0 := by
    rw [map_sub, sub_eq_zero]
    exact congrArg Subtype.val hq
  have hmem : f₁ - f₂ ∈ LinearMap.range (coindEmb A.ρ) := by
    rw [← ker_cyclicDiff A.ρ σ hσ]
    exact hd
  rw [Submodule.mkQ_apply, Submodule.mkQ_apply, Submodule.Quotient.eq]
  exact hmem

theorem cyclicShiftLinear_surjective : Function.Surjective (cyclicShiftLinear A σ hσ) := by
  intro y
  obtain ⟨z, hz⟩ := y
  rw [← range_cyclicDiff A.ρ σ hσ] at hz
  obtain ⟨f, hf⟩ := hz
  exact ⟨(LinearMap.range (coindEmb A.ρ)).mkQ f, Subtype.ext hf⟩

/-- The twisted difference against a generator, as a linear equivalence of the shift with the
coshift. -/
def cyclicShiftEquiv : ↥(shiftObj A).V ≃ₗ[k] ↥(coshiftObj A).V :=
  LinearEquiv.ofBijective (cyclicShiftLinear A σ hσ)
    ⟨cyclicShiftLinear_injective A σ hσ, cyclicShiftLinear_surjective A σ hσ⟩

theorem cyclicShiftEquiv_symm_equivariant (g : G) :
    (cyclicShiftEquiv A σ hσ).symm.toLinearMap ∘ₗ (coshiftObj A).ρ g
      = (shiftObj A).ρ g ∘ₗ (cyclicShiftEquiv A σ hσ).symm.toLinearMap := by
  refine LinearMap.ext fun z => (cyclicShiftEquiv A σ hσ).injective ?_
  have h1 : cyclicShiftEquiv A σ hσ
      (((cyclicShiftEquiv A σ hσ).symm.toLinearMap ∘ₗ (coshiftObj A).ρ g) z)
      = (coshiftObj A).ρ g z :=
    (cyclicShiftEquiv A σ hσ).apply_symm_apply _
  have h2 : cyclicShiftEquiv A σ hσ
      (((shiftObj A).ρ g ∘ₗ (cyclicShiftEquiv A σ hσ).symm.toLinearMap) z)
      = (coshiftObj A).ρ g
        (cyclicShiftEquiv A σ hσ ((cyclicShiftEquiv A σ hσ).symm z)) :=
    cyclicShiftLinear_apply_rho A σ hσ g _
  rw [h1, h2, LinearEquiv.apply_symm_apply]

/-- **The shift and the coshift of a representation of a group generated by one element are
isomorphic.** -/
def cyclicShiftIso : shiftObj A ≅ coshiftObj A where
  hom := mkHom (cyclicShiftLinear A σ hσ) (cyclicShiftLinear_equivariant A σ hσ)
  inv := mkHom (cyclicShiftEquiv A σ hσ).symm.toLinearMap
    (cyclicShiftEquiv_symm_equivariant A σ hσ)
  hom_inv_id := Action.hom_ext _ _ (ModuleCat.hom_ext (LinearMap.ext fun q =>
    (cyclicShiftEquiv A σ hσ).symm_apply_apply q))
  inv_hom_id := Action.hom_ext _ _ (ModuleCat.hom_ext (LinearMap.ext fun z =>
    (cyclicShiftEquiv A σ hσ).apply_symm_apply z))

/-- **The complete cohomology of a representation of a group generated by one element in a degree
is its complete cohomology two degrees lower.** -/
def tateCyclicEquiv (n : ℤ) : tateModule A (n + 1 + 1) ≃ₗ[k] tateModule A n :=
  ((tateShiftEquiv A (n + 1)).symm.trans
      (tateMapIso (cyclicShiftIso A σ hσ) (n + 1)).toLinearEquiv).trans
    (tateCoshiftEquiv A n).symm

end Periodicity

/-! ### The periodicity -/

section Cyclic

variable {k G : Type u} [CommRing k] [Group G] [Finite G] [IsCyclic G] (A : Rep k G)

/-- **The complete cohomology of a representation of a finite cyclic group has period two.** -/
def tateCyclicPeriod (n : ℤ) : tateModule A (n + 1 + 1) ≃ₗ[k] tateModule A n :=
  tateCyclicEquiv A (exists_forall_pow G).choose (exists_forall_pow G).choose_spec n

/-- **A representation of a finite cyclic group without complete cohomology in a degree has none
two degrees higher.** -/
theorem isZero_tateModule_add_two (n : ℤ) (h : Limits.IsZero (tateModule A n)) :
    Limits.IsZero (tateModule A (n + 1 + 1)) :=
  Limits.IsZero.of_iso h (tateCyclicPeriod A n).toModuleIso

end Cyclic

end

end InverseGalois.CFT.Tate
