/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.GroupCohomology.CyclicTateMap
import InverseGalois.CFT.GroupCohomology.InfResTwoInjective
import InverseGalois.CFT.Tate.Counting

/-!
# A class of large order transported across a pair of complementary normal subgroups

A finite group is generated by two normal subgroups meeting trivially, one of them cyclic and both
of the same order.  A module over the group then carries three interesting sets of invariants: the
invariants of each subgroup, and the invariants of the whole group.  The quotient by the first
subgroup is isomorphic to the second, hence cyclic, so the invariants of the first subgroup carry
a comparison map from the fixed points of a generator to second cohomology.

This file transports a class produced that way to the second cohomology of the quotient by the
*other* subgroup.  Inflating the class to the whole group and restricting it to the second
subgroup gives, by naturality of the comparison map along the isomorphism between the second
subgroup and the quotient by the first, the class of the same point computed on the second
subgroup.  That class vanishes exactly when the point is a norm from the second subgroup, and a
counting argument supplies precisely that: the norm of the first subgroup is a map of zeroth Tate
groups, and when it is surjective the order of the given class leaves no room for anything but a
bijection.  So the restriction vanishes, the inflation-restriction sequence produces a preimage on
the quotient by the second subgroup, and injectivity of inflation on orders carries the original
order down to it.

The upshot is a class in the second cohomology of the quotient by the second subgroup whose order
is divisible by the common order of the two subgroups.  In the arithmetic application the ambient
group is the Galois group of the compositum of a given extension with an auxiliary cyclic one, the
first subgroup is the group of the given extension and the second that of the auxiliary one, and
the class is the fundamental class of the given extension.

## Main definitions

* `InverseGalois.CFT.conjEquiv`: conjugation permutes a normal subgroup.
* `InverseGalois.CFT.subgroupNorm`: the sum of the translates of a point by a finite normal
  subgroup, landing in the invariants of that subgroup.

## Main results

* `InverseGalois.CFT.subgroupNorm_rho`: the norm of a normal subgroup is equivariant.
* `InverseGalois.CFT.subgroupNorm_coe`: the norm of a normal subgroup multiplies an invariant
  point by the order of the subgroup.
* `InverseGalois.CFT.bijective_mk'_comp_subtype`: a complement to a normal subgroup maps
  isomorphically onto the quotient.
* `InverseGalois.CFT.exists_zsmul_eq_zero_imp_dvd_H2_quotientToInvariants`: **a class of the
  largest possible order on the invariants of one of two complementary normal subgroups produces a
  class whose order is divisible by the same number on the quotient by the other.**

## Tags

group cohomology, Tate cohomology, fundamental class, inflation, restriction, norm
-/

namespace InverseGalois.CFT

open CategoryTheory groupCohomology

noncomputable section

variable {Γ : Type} [Group Γ]

/-! ### Conjugation -/

/-- Conjugation by a group element permutes a normal subgroup. -/
def conjEquiv (H : Subgroup Γ) [hH : H.Normal] (γ : Γ) : ↥H ≃ ↥H where
  toFun h := ⟨γ⁻¹ * (h : Γ) * γ, hH.conj_mem' _ h.2 γ⟩
  invFun h := ⟨γ * (h : Γ) * γ⁻¹, hH.conj_mem _ h.2 γ⟩
  left_inv h := Subtype.ext (by group)
  right_inv h := Subtype.ext (by group)

/-! ### The action of a group element -/

/-- The action of a group element on a representation over the integers, as an isomorphism of the
underlying additive group. -/
def rhoAddEquiv (A : Rep ℤ Γ) (γ : Γ) : ↥A.V ≃+ ↥A.V where
  toFun := A.ρ γ
  invFun := A.ρ γ⁻¹
  left_inv x := by
    rw [← Module.End.mul_apply, ← map_mul, inv_mul_cancel, map_one, Module.End.one_apply]
  right_inv x := by
    rw [← Module.End.mul_apply, ← map_mul, mul_inv_cancel, map_one, Module.End.one_apply]
  map_add' x y := map_add _ x y

@[simp]
theorem rhoAddEquiv_apply (A : Rep ℤ Γ) (γ : Γ) (x : ↥A.V) : rhoAddEquiv A γ x = A.ρ γ x := rfl

/-! ### The norm of a normal subgroup -/

variable (A : Rep ℤ Γ) (H : Subgroup Γ) [H.Normal] [Fintype ↥H]

/-- The sum of the translates of a point by a finite normal subgroup, as a point of the invariants
of that subgroup. -/
def subgroupNorm : ↥A.V →+ ↥(A.quotientToInvariants H).V where
  toFun x := ⟨Representation.norm (A.ρ.comp H.subtype) x,
    fun h => Representation.self_norm_apply _ h x⟩
  map_zero' := Subtype.ext (map_zero _)
  map_add' x y := Subtype.ext (map_add _ x y)

/-- The norm of a normal subgroup is the sum of the translates of the point. -/
theorem coe_subgroupNorm (x : ↥A.V) :
    ((subgroupNorm A H x : ↥(A.quotientToInvariants H).V) : ↥A.V)
      = ∑ h : ↥H, A.ρ (h : Γ) x := by
  show Representation.norm (A.ρ.comp H.subtype) x = _
  rw [Representation.norm, LinearMap.coe_sum, Finset.sum_apply]
  rfl

variable {A H}

/-- The norm of a normal subgroup is equivariant for the induced action on the invariants. -/
theorem subgroupNorm_rho (γ : Γ) (x : ↥A.V) :
    subgroupNorm A H (A.ρ γ x)
      = (A.quotientToInvariants H).ρ ((γ : Γ ⧸ H)) (subgroupNorm A H x) := by
  refine Subtype.ext ?_
  rw [coe_quotientToInvariants_rho, coe_subgroupNorm, coe_subgroupNorm, map_sum]
  refine Fintype.sum_equiv (conjEquiv H γ) _ _ fun h => ?_
  show A.ρ (h : Γ) (A.ρ γ x) = A.ρ γ (A.ρ (γ⁻¹ * (h : Γ) * γ) x)
  rw [← Module.End.mul_apply, ← map_mul, ← Module.End.mul_apply, ← map_mul,
    show γ * (γ⁻¹ * (h : Γ) * γ) = (h : Γ) * γ from by group]

/-- The norm of a normal subgroup multiplies an invariant point by the order of the subgroup. -/
theorem subgroupNorm_coe (v : ↥(A.quotientToInvariants H).V) :
    subgroupNorm A H (v : ↥A.V) = Nat.card ↥H • v := by
  refine Subtype.ext ?_
  rw [coe_subgroupNorm]
  have h1 : ∀ h : ↥H, A.ρ (h : Γ) (v : ↥A.V) = (v : ↥A.V) := fun h =>
    ((Representation.mem_invariants _ _).1 v.2) h
  rw [Finset.sum_congr rfl fun h _ => h1 h, Finset.sum_const, Finset.card_univ,
    ← Nat.card_eq_fintype_card]
  rfl

/-! ### A complement to a normal subgroup -/

/-- A subgroup meeting a normal subgroup trivially and generating the whole group with it maps
isomorphically onto the quotient by that normal subgroup. -/
theorem bijective_mk'_comp_subtype {H S : Subgroup Γ} [H.Normal] (hdisj : H ⊓ S = ⊥)
    (hsup : H ⊔ S = ⊤) : Function.Bijective ((QuotientGroup.mk' H).comp S.subtype) := by
  constructor
  · rw [injective_iff_map_eq_one]
    intro s hs
    have h1 : (s : Γ) ∈ H := by
      rwa [MonoidHom.comp_apply, Subgroup.coe_subtype, QuotientGroup.mk'_apply,
        QuotientGroup.eq_one_iff] at hs
    have h2 : (s : Γ) ∈ H ⊓ S := ⟨h1, s.2⟩
    rw [hdisj, Subgroup.mem_bot] at h2
    exact Subtype.ext h2
  · intro y
    induction y using QuotientGroup.induction_on with
    | H g =>
      have hg : g ∈ (↑(H ⊔ S) : Set Γ) := by rw [hsup]; trivial
      rw [Subgroup.normal_mul] at hg
      obtain ⟨h, hh, s, hs, rfl⟩ := hg
      refine ⟨⟨s, hs⟩, ?_⟩
      show ((s : Γ) : Γ ⧸ H) = ((h * s : Γ) : Γ ⧸ H)
      refine (QuotientGroup.eq.2 ?_).symm
      rw [mul_inv_rev]
      exact ‹H.Normal›.conj_mem' _ (H.inv_mem hh) s

/-! ### Transporting a class of large order -/

section Main

variable [Finite Γ] {S : Subgroup Γ} [S.Normal]

omit [Finite Γ] [S.Normal] in
/-- The norm of a normal subgroup intertwines the action of an element of a complement with the
action of its image on the invariants. -/
theorem subgroupNorm_comm {σS : ↥A.V ≃+ ↥A.V} {s₀ : ↥S} (hσS : ∀ x, σS x = A.ρ (s₀ : Γ) x)
    {σH : ↥(A.quotientToInvariants H).V ≃+ ↥(A.quotientToInvariants H).V}
    (hσH : ∀ x, σH x = (A.quotientToInvariants H).ρ (((s₀ : Γ) : Γ ⧸ H)) x) (x : ↥A.V) :
    subgroupNorm A H (σS x) = σH (subgroupNorm A H x) := by
  rw [hσS, hσH, subgroupNorm_rho]

/-- **A class of the largest possible order on the invariants of one of two complementary normal
subgroups produces a class whose order is divisible by the same number on the quotient by the
other.**  The class is inflated to the whole group and restricted to the complement, where
naturality of the comparison map of a cyclic group identifies it with the class of the same point;
that class vanishes because the point is a norm, which the counting argument supplies from the
surjectivity of the norm of the first subgroup.  The inflation-restriction sequence then produces
a preimage on the quotient by the complement, and inflation does not decrease orders. -/
theorem exists_zsmul_eq_zero_imp_dvd_H2_quotientToInvariants
    (hdisj : H ⊓ S = ⊥) (hsup : H ⊔ S = ⊤) {n : ℕ} (hnH : Nat.card ↥H = n)
    (hnS : Nat.card ↥S = n) {s₀ : ↥S} (hs₀ : ∀ x : ↥S, x ∈ Subgroup.zpowers s₀)
    {σS : ↥A.V ≃+ ↥A.V} (hσS : ∀ x, σS x = A.ρ (s₀ : Γ) x)
    {σH : ↥(A.quotientToInvariants H).V ≃+ ↥(A.quotientToInvariants H).V}
    (hσH : ∀ x, σH x = (A.quotientToInvariants H).ρ (((s₀ : Γ) : Γ ⧸ H)) x)
    (hH1H : ∀ z : ↥(groupCohomology ((Action.res _ H.subtype).obj A) 1), z = 0)
    (hH1S : ∀ z : ↥(groupCohomology ((Action.res _ S.subtype).obj A) 1), z = 0)
    [Finite (tateH0 σS n)] (hle : Nat.card (tateH0 σS n) ≤ n)
    (hnorm : Function.Surjective
      (tateH0.map n (subgroupNorm A H) (subgroupNorm_comm hσS hσH)))
    {aH : ↥(A.quotientToInvariants H).V} (haH : σH aH = aH)
    (hord : ∀ m : ℤ, m • tateH0.mk σH n aH haH = 0 → (n : ℤ) ∣ m) :
    ∃ γ : ↥(H2 (A.quotientToInvariants S)), ∀ m : ℤ, m • γ = 0 → (n : ℤ) ∣ m := by
  letI : Fintype ↥S := Fintype.ofFinite _
  letI : Fintype (Γ ⧸ H) := Fintype.ofFinite _
  have hbij := bijective_mk'_comp_subtype (S := S) hdisj hsup
  have hcardS : Nat.card ↥S = Nat.card (Γ ⧸ H) := Nat.card_congr (Equiv.ofBijective _ hbij)
  have hcardQ : Nat.card (Γ ⧸ H) = n := hcardS.symm.trans hnS
  have hgen₂ : ∀ z : Γ ⧸ H,
      z ∈ Subgroup.zpowers (((QuotientGroup.mk' H).comp S.subtype) s₀) := by
    intro z
    obtain ⟨w, rfl⟩ := hbij.2 z
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.1 (hs₀ w)
    exact Subgroup.mem_zpowers_iff.2 ⟨k, by rw [← map_zpow, hk]⟩
  have hyfix : σS (aH : ↥A.V) = (aH : ↥A.V) := by
    rw [hσS]
    exact congrArg Subtype.val ((hσH aH).symm.trans haH)
  set x : ↥(sigmaSubOne σH).ker := ⟨aH, (mem_ker_sigmaSubOne_iff σH aH).2 haH⟩ with hxdef
  set y : ↥(sigmaSubOne σS).ker :=
    ⟨(aH : ↥A.V), (mem_ker_sigmaSubOne_iff σS _).2 hyfix⟩ with hydef
  have hcomp := groupCohomology.map_comp (k := ℤ) (A := A.quotientToInvariants H) (B := A)
      (C := (Action.res (ModuleCat ℤ) S.subtype).obj A) (QuotientGroup.mk' H) S.subtype
      (Rep.subtype _ _ (Representation.le_comap_invariants A.ρ H))
      (𝟙 ((Action.res (ModuleCat ℤ) S.subtype).obj A)) 2
  have hres : resTwo A S (inflTwo A H (tateH0ToH2 hgen₂ hσH x)) = 0 := by
    have h1 : resTwo A S (inflTwo A H (tateH0ToH2 hgen₂ hσH x))
        = (groupCohomology.map ((QuotientGroup.mk' H).comp S.subtype)
            ((Action.res (ModuleCat ℤ) S.subtype).map
              (Rep.subtype _ _ (Representation.le_comap_invariants A.ρ H)) ≫ 𝟙 _) 2).hom
            (tateH0ToH2 hgen₂ hσH x) := by
      rw [hcomp]
      rfl
    rw [h1, map_tateH0ToH2 _ _ hcardS hs₀ hgen₂ hσH hσS x y rfl, tateH0ToH2_eq_zero_iff, hnS]
    exact tateH0.exists_normHom_of_map_surjective (subgroupNorm A H) (subgroupNorm_comm hσS hσH)
      hle hnorm hyfix haH ((subgroupNorm_coe aH).trans (by rw [hnH])) hord
  obtain ⟨γ, hγ⟩ := mem_range_inflTwo_of_resTwo_eq_zero hH1S _ hres
  refine ⟨γ, fun m hm => ?_⟩
  have h2 : m • inflTwo A H (tateH0ToH2 hgen₂ hσH x) = 0 := by
    rw [← hγ, ← map_zsmul, hm, map_zero]
  have h3 : m • tateH0ToH2 hgen₂ hσH x = 0 :=
    zsmul_eq_zero_of_zsmul_inflTwo_eq_zero hH1H _ h2
  rw [← map_zsmul, tateH0ToH2_eq_zero_iff, hcardQ] at h3
  refine hord m ?_
  have hmk : tateH0.mk σH n aH haH = QuotientAddGroup.mk' _ x := rfl
  rw [hmk, ← map_zsmul, QuotientAddGroup.mk'_apply, QuotientAddGroup.eq_zero_iff,
    AddSubgroup.mem_addSubgroupOf, AddMonoidHom.mem_range]
  exact h3

end Main

end

end InverseGalois.CFT
