/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.CentralDual

/-!
# A chain of characters adapted to an independent family

A central subgroup of exponent two is a vector space over the field with two elements, and a
family of its elements no one of which lies in the subgroup generated by the others is a linearly
independent family.  Such a family admits a *dual* family of characters: the `i`-th character
takes the value one at the `i`-th element and vanishes at the others.

Together with the characters vanishing at the whole family, the dual family separates the points
of the subgroup, while no element of the family is detected by two of the characters listed.  That
is exactly the arrangement an induction cutting the subgroup down one hyperplane at a time needs
when a distinguished element has to stay inside every subgroup considered before the one character
that sees it.

## Main results

* `InverseGalois.exists_charValue_ne_zero_of_notMem`: **a character separates an element of a
  central subgroup of exponent `p` from a subgroup it does not lie in.**
* `InverseGalois.exists_dualFamily`: **an independent family in a central subgroup of exponent two
  has a dual family of characters.**
* `InverseGalois.exists_charChain`: **an independent family in a finite central subgroup of
  exponent two is listed by a family of characters separating the points of the subgroup, each
  member of the family being detected by at most one character and each character detecting at
  most one member.**

## Tags

elementary abelian group, character, dual basis, centre, `p`-group
-/

namespace InverseGalois

variable {G : Type*} [Group G] {p : ℕ} {N : Subgroup G}

/-! ### Separating a point from a subgroup -/

/-- **A character separates an element of a central subgroup of exponent `p` from a subgroup it
does not lie in.**  The subgroup is a subspace of the vector space over the field with `p`
elements the central subgroup carries, and a functional on the quotient by that subspace not
killing the class of the element pulls back to the character sought. -/
theorem exists_charValue_ne_zero_of_notMem (hp : p.Prime) (h : N ≤ Subgroup.center G)
    (hexp : ∀ z ∈ N, z ^ p = 1) {M : Subgroup G} (hM : M ≤ N) {z : G} (hzN : z ∈ N)
    (hz : z ∉ M) :
    ∃ φ : Additive ↥N →+ ZMod p, charValue N φ z ≠ 0 ∧ M ≤ charKer N φ := by
  haveI : Fact p.Prime := ⟨hp⟩
  letI := commGroupOfLeCenter h
  letI := zmodModuleOfLeCenter (p := p) h hexp
  -- the subgroup, seen inside the vector space
  let S : AddSubgroup (Additive ↥N) :=
    { carrier := {x | ((Additive.toMul x : ↥N) : G) ∈ M}
      zero_mem' := M.one_mem
      add_mem' := fun ha hb => M.mul_mem ha hb
      neg_mem' := fun ha => M.inv_mem ha }
  have hmemS : ∀ x : Additive ↥N, x ∈ S ↔ ((Additive.toMul x : ↥N) : G) ∈ M := fun _ => Iff.rfl
  let T : Submodule (ZMod p) (Additive ↥N) := AddSubgroup.toZModSubmodule p S
  have hmemT : ∀ x : Additive ↥N, x ∈ T ↔ ((Additive.toMul x : ↥N) : G) ∈ M := fun x =>
    (AddSubgroup.mem_toZModSubmodule p).trans (hmemS x)
  have hzq : T.mkQ (Additive.ofMul (⟨z, hzN⟩ : ↥N)) ≠ 0 := by
    rw [Ne, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
    exact fun hc => hz ((hmemT _).mp hc)
  obtain ⟨f, hf⟩ := Module.Projective.exists_dual_ne_zero (ZMod p) hzq
  refine ⟨((f.comp T.mkQ) : Additive ↥N →ₗ[ZMod p] ZMod p).toAddMonoidHom, ?_,
    fun w hw => ⟨hM hw, ?_⟩⟩
  · rw [charValue_of_mem _ hzN]
    exact hf
  · rw [charValue_of_mem _ (hM hw)]
    show f (T.mkQ (Additive.ofMul (⟨w, hM hw⟩ : ↥N))) = 0
    rw [Submodule.mkQ_apply,
      (Submodule.Quotient.mk_eq_zero T).mpr
        ((hmemT (Additive.ofMul (⟨w, hM hw⟩ : ↥N))).mpr hw),
      map_zero]

/-! ### A dual family -/

variable {d : ℕ} {z : Fin d → G}

private theorem zmod_two_eq_one' {v : ZMod 2} (hv : v ≠ 0) : v = 1 := by revert hv; revert v; decide

/-- The subgroup generated by all members of a family but one. -/
def otherSpan (z : Fin d → G) (i : Fin d) : Subgroup G :=
  Subgroup.closure {g | ∃ j, j ≠ i ∧ z j = g}

theorem otherSpan_le (hzN : ∀ i, z i ∈ N) (i : Fin d) : otherSpan z i ≤ N :=
  Subgroup.closure_le _ |>.mpr (by rintro g ⟨j, -, rfl⟩; exact hzN j)

theorem mem_otherSpan {i j : Fin d} (hij : j ≠ i) : z j ∈ otherSpan z i :=
  Subgroup.subset_closure ⟨j, hij, rfl⟩

/-- **An independent family in a central subgroup of exponent two has a dual family of
characters**: the `i`-th one takes the value one at the `i`-th member and vanishes at the
others. -/
theorem exists_dualFamily (h : N ≤ Subgroup.center G) (hexp : ∀ w ∈ N, w ^ 2 = 1)
    (hzN : ∀ i, z i ∈ N) (hindep : ∀ i, z i ∉ otherSpan z i) :
    ∃ χ : Fin d → (Additive ↥N →+ ZMod 2), ∀ i j, charValue N (χ i) (z j) = if j = i then 1 else 0
      := by
  have hkey : ∀ i, ∃ φ : Additive ↥N →+ ZMod 2,
      ∀ j, charValue N φ (z j) = if j = i then 1 else 0 := by
    intro i
    obtain ⟨φ, hφ, hker⟩ := exists_charValue_ne_zero_of_notMem Nat.prime_two h hexp
      (otherSpan_le hzN i) (hzN i) (hindep i)
    refine ⟨φ, fun j => ?_⟩
    rcases eq_or_ne j i with rfl | hij
    · simpa using zmod_two_eq_one' hφ
    · rw [if_neg hij]
      exact (hker (mem_otherSpan hij)).2
  choose χ hχ using hkey
  exact ⟨χ, fun i j => hχ i j⟩

/-! ### The chain -/

open scoped Classical in
/-- **An independent family in a finite central subgroup of exponent two is listed by a family of
characters separating the points of the subgroup, each member of the family being detected by at
most one character and each character detecting at most one member.**  The list is the dual family
of the independent family followed by every character vanishing on the whole family: a character
not killed by an element of the subgroup differs from a character of the second kind by a
combination of the dual family, so the two kinds together separate the points, while a character
of the list detecting a member of the family is the member's own dual character. -/
theorem exists_charChain [Finite ↥N] (h : N ≤ Subgroup.center G) (hexp : ∀ w ∈ N, w ^ 2 = 1)
    (hzN : ∀ i, z i ∈ N) (hindep : ∀ i, z i ∉ otherSpan z i) :
    ∃ (t : ℕ) (chi : Fin t → (Additive ↥N →+ ZMod 2)),
      (∀ g ∈ N, (∀ k, charValue N (chi k) g = 0) → g = 1) ∧
        (∀ (i : Fin d) (k₁ k₂ : Fin t), charValue N (chi k₁) (z i) ≠ 0 →
          charValue N (chi k₂) (z i) ≠ 0 → k₁ = k₂) ∧
        ∀ (k : Fin t) (i₁ i₂ : Fin d), charValue N (chi k) (z i₁) ≠ 0 →
          charValue N (chi k) (z i₂) ≠ 0 → i₁ = i₂ := by
  obtain ⟨χ, hχ⟩ := exists_dualFamily h hexp hzN hindep
  haveI : Finite (Additive ↥N →+ ZMod 2) := finite_char (N := N) two_ne_zero
  -- the characters vanishing at every member of the family
  let V : Type _ := {φ : Additive ↥N →+ ZMod 2 // ∀ i, charValue N φ (z i) = 0}
  haveI : Finite V := Subtype.finite
  haveI : Fintype (Fin d ⊕ V) := Fintype.ofFinite _
  let chi₀ : Fin d ⊕ V → (Additive ↥N →+ ZMod 2) := Sum.elim χ Subtype.val
  -- reindex by an initial segment of the naturals
  let e := Fintype.equivFin (Fin d ⊕ V)
  have hval : ∀ (x : Fin d ⊕ V) (i : Fin d), charValue N (chi₀ x) (z i) ≠ 0 → x = Sum.inl i := by
    rintro (j | ⟨φ, hφ⟩) i hx
    · have := hχ j i
      by_cases hij : i = j
      · rw [hij]
      · exact absurd (by simpa [chi₀, hij] using this) hx
    · exact absurd (by simpa [chi₀] using hφ i) hx
  refine ⟨Fintype.card (Fin d ⊕ V), chi₀ ∘ e.symm, fun g hg hker => ?_,
    fun i k₁ k₂ h₁ h₂ => ?_, fun k i₁ i₂ h₁ h₂ => ?_⟩
  · -- every character kills `g`
    refine eq_one_of_forall_charValue_eq_zero Nat.prime_two h hexp hg fun φ => ?_
    set c : Fin d → ZMod 2 := fun i => charValue N φ (z i) with hc
    set φ' : Additive ↥N →+ ZMod 2 := φ - ∑ i, c i • χ i with hφ'
    have hφ'val : ∀ w ∈ N, charValue N φ' w = charValue N φ w - ∑ i, c i * charValue N (χ i) w := by
      intro w hw
      rw [charValue_of_mem _ hw, charValue_of_mem _ hw, hφ']
      simp only [AddMonoidHom.sub_apply, AddMonoidHom.finset_sum_apply, AddMonoidHom.smul_apply,
        smul_eq_mul]
      refine congrArg (fun x => φ (Additive.ofMul ⟨w, hw⟩) - x) (Finset.sum_congr rfl fun i _ => ?_)
      rw [charValue_of_mem (χ i) hw]
    have hφ'z : ∀ j, charValue N φ' (z j) = 0 := by
      intro j
      rw [hφ'val _ (hzN j)]
      have : ∀ i, c i * charValue N (χ i) (z j) = if i = j then c i else 0 := by
        intro i
        rw [hχ i j]
        rcases eq_or_ne i j with rfl | hij
        · simp
        · simp [Ne.symm hij, hij]
      rw [Finset.sum_congr rfl fun i _ => this i, Finset.sum_ite_eq' Finset.univ j c,
        if_pos (Finset.mem_univ j), hc]
      exact sub_self _
    have hmemV : φ' ∈ {φ : Additive ↥N →+ ZMod 2 | ∀ i, charValue N φ (z i) = 0} := hφ'z
    have hφ'g : charValue N φ' g = 0 := by
      have := hker (e (Sum.inr ⟨φ', hmemV⟩))
      simpa [chi₀] using this
    have hχg : ∀ i, charValue N (χ i) g = 0 := by
      intro i
      have := hker (e (Sum.inl i))
      simpa [chi₀] using this
    have := hφ'val g hg
    rw [hφ'g] at this
    have hzero : ∑ i, c i * charValue N (χ i) g = 0 := by
      refine Finset.sum_eq_zero fun i _ => ?_
      rw [hχg i, mul_zero]
    rw [hzero, sub_zero] at this
    exact this.symm
  · -- at most one character of the list detects the `i`-th member
    refine e.symm.injective ?_
    rw [hval (e.symm k₁) i h₁, hval (e.symm k₂) i h₂]
  · -- each character of the list detects at most one member of the family
    exact Sum.inl_injective ((hval (e.symm k) i₁ h₁).symm.trans (hval (e.symm k) i₂ h₂))
