/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Characters of a central subgroup of exponent `p`

A subgroup `N` of the centre of a group, all of whose elements satisfy `z ^ p = 1` for a prime
`p`, is an elementary abelian `p`-group, that is, a vector space over the field with `p`
elements.  Its characters — the additive maps from `Additive ↥N` to `ZMod p` — therefore separate
its elements, and there are only finitely many of them when `N` is finite.  This is the form in
which the linear algebra of such a subgroup enters an induction along the lower `p`-central
series: an element of `N` is trivial as soon as every character kills it, and the characters can
be enumerated.

A character is evaluated through `charValue`, which extends it by `0` to the whole ambient group,
so that no membership hypothesis has to be carried through the algebra.

## Main definitions

* `InverseGalois.charValue`: the value of a character of `N` at an element of the ambient group,
  taken to be `0` outside `N`.
* `InverseGalois.charKer`: the kernel of a character, as a subgroup of the ambient group.

## Main results

* `InverseGalois.exists_charValue_ne_zero`: **the characters separate the elements of a central
  subgroup of exponent `p`.**
* `InverseGalois.eq_one_iff_forall_charValue_eq_zero`: the same statement as a criterion for
  triviality.
* `InverseGalois.finite_char`: a finite subgroup has only finitely many characters.
* `InverseGalois.sup_charKer_zpowers`, `InverseGalois.inf_charKer_zpowers`: **at the prime two, a
  character not vanishing at an element of order two splits its subgroup** into the kernel of the
  character and the subgroup generated by that element.
* `InverseGalois.exists_sup_zpowers_eq_inf_charKer`: **a hyperplane of a subgroup and an element
  outside it generate a hyperplane**, cut out by a single character correcting the one the
  hyperplane came from.

## Tags

elementary abelian group, character, centre, `p`-group
-/

namespace InverseGalois

variable {G : Type*} [Group G] {p : ℕ} {N : Subgroup G}

/-- A subgroup of the centre of a group is commutative. -/
def commGroupOfLeCenter (h : N ≤ Subgroup.center G) : CommGroup ↥N :=
  { (inferInstance : Group ↥N) with
    mul_comm := fun a b => Subtype.ext (Subgroup.mem_center_iff.mp (h b.2) a) }

/-- The elements of a subgroup of the centre of exponent `p` form a vector space over the field
with `p` elements. -/
noncomputable def zmodModuleOfLeCenter (h : N ≤ Subgroup.center G)
    (hexp : ∀ z ∈ N, z ^ p = 1) :
    letI := commGroupOfLeCenter h
    Module (ZMod p) (Additive ↥N) :=
  letI := commGroupOfLeCenter h
  AddCommGroup.zmodModule fun x => by
    have h1 : (Additive.toMul x) ^ p = 1 := by
      apply Subtype.ext
      push_cast
      exact hexp _ (Additive.toMul x).2
    have h2 : Additive.ofMul ((Additive.toMul x) ^ p) = p • x := ofMul_pow p (Additive.toMul x)
    rw [h1] at h2
    simpa using h2.symm

/-- **The characters of a central subgroup of exponent `p` separate its elements.** -/
theorem exists_char_apply_ne_zero (hp : p.Prime) (h : N ≤ Subgroup.center G)
    (hexp : ∀ z ∈ N, z ^ p = 1) {z : ↥N} (hz : z ≠ 1) :
    ∃ φ : Additive ↥N →+ ZMod p, φ (Additive.ofMul z) ≠ 0 := by
  haveI : Fact p.Prime := ⟨hp⟩
  letI := commGroupOfLeCenter h
  letI := zmodModuleOfLeCenter h hexp
  have hz' : Additive.ofMul z ≠ 0 := fun hc => hz (Additive.ofMul.injective hc)
  obtain ⟨f, hf⟩ := Module.Projective.exists_dual_ne_zero (ZMod p) hz'
  exact ⟨f.toAddMonoidHom, hf⟩

theorem finite_char (hp : p ≠ 0) [Finite ↥N] : Finite (Additive ↥N →+ ZMod p) := by
  haveI : NeZero p := ⟨hp⟩
  exact Finite.of_injective (fun φ => (φ : Additive ↥N → ZMod p)) DFunLike.coe_injective

/-! ## Evaluation -/

/-- The value of a character of a subgroup `N` at an element of the ambient group, taken to be
`0` outside `N`. -/
noncomputable def charValue (N : Subgroup G) (φ : Additive ↥N →+ ZMod p) (z : G) : ZMod p :=
  haveI := Classical.dec (z ∈ N)
  if hz : z ∈ N then φ (Additive.ofMul ⟨z, hz⟩) else 0

variable (φ : Additive ↥N →+ ZMod p)

theorem charValue_of_mem {z : G} (hz : z ∈ N) :
    charValue N φ z = φ (Additive.ofMul ⟨z, hz⟩) :=
  dif_pos hz

theorem charValue_of_notMem {z : G} (hz : z ∉ N) : charValue N φ z = 0 :=
  dif_neg hz

@[simp] theorem charValue_one : charValue N φ 1 = 0 := by
  rw [charValue_of_mem φ N.one_mem]
  exact φ.map_zero

theorem charValue_mul {u v : G} (hu : u ∈ N) (hv : v ∈ N) :
    charValue N φ (u * v) = charValue N φ u + charValue N φ v := by
  rw [charValue_of_mem φ (N.mul_mem hu hv), charValue_of_mem φ hu, charValue_of_mem φ hv,
    ← map_add]
  rfl

theorem charValue_inv {u : G} (hu : u ∈ N) : charValue N φ u⁻¹ = -charValue N φ u := by
  have h := charValue_mul φ (N.inv_mem hu) hu
  rw [inv_mul_cancel, charValue_one] at h
  linear_combination (norm := abel) -h

theorem charValue_add (α β : Additive ↥N →+ ZMod p) (g : G) :
    charValue N (α + β) g = charValue N α g + charValue N β g := by
  by_cases hg : g ∈ N
  · rw [charValue_of_mem _ hg, charValue_of_mem _ hg, charValue_of_mem _ hg]
    rfl
  · rw [charValue_of_notMem _ hg, charValue_of_notMem _ hg, charValue_of_notMem _ hg, add_zero]

theorem charValue_list_prod {l : List G} (hl : ∀ z ∈ l, z ∈ N) :
    charValue N φ l.prod = (l.map (charValue N φ)).sum := by
  induction l with
  | nil => simp
  | cons z l ih =>
    have hz : z ∈ N := hl z (by simp)
    have hrest : ∀ w ∈ l, w ∈ N := fun w hw => hl w (by simp [hw])
    rw [List.prod_cons, charValue_mul φ hz (N.list_prod_mem hrest), ih hrest,
      List.map_cons, List.sum_cons]

/-! ## The kernel of a character -/

/-- The kernel of a character of a subgroup, as a subgroup of the ambient group. -/
noncomputable def charKer (N : Subgroup G) (φ : Additive ↥N →+ ZMod p) : Subgroup G where
  carrier := {g | g ∈ N ∧ charValue N φ g = 0}
  one_mem' := ⟨N.one_mem, charValue_one φ⟩
  mul_mem' := fun ha hb =>
    ⟨N.mul_mem ha.1 hb.1, by rw [charValue_mul φ ha.1 hb.1, ha.2, hb.2, add_zero]⟩
  inv_mem' := fun ha => ⟨N.inv_mem ha.1, by rw [charValue_inv φ ha.1, ha.2, neg_zero]⟩

theorem mem_charKer {g : G} : g ∈ charKer N φ ↔ g ∈ N ∧ charValue N φ g = 0 := Iff.rfl

theorem charKer_le : charKer N φ ≤ N := fun _ hg => hg.1

/-- **An element of a central subgroup of exponent `p` is trivial as soon as every character
kills it.** -/
theorem eq_one_of_forall_charValue_eq_zero (hp : p.Prime) (h : N ≤ Subgroup.center G)
    (hexp : ∀ z ∈ N, z ^ p = 1) {z : G} (hz : z ∈ N)
    (hchar : ∀ φ : Additive ↥N →+ ZMod p, charValue N φ z = 0) : z = 1 := by
  by_contra hne
  have hz1 : (⟨z, hz⟩ : ↥N) ≠ 1 := fun hc => hne (congrArg Subtype.val hc)
  obtain ⟨ψ, hψ⟩ := exists_char_apply_ne_zero hp h hexp hz1
  exact hψ ((charValue_of_mem ψ hz).symm.trans (hchar ψ))

/-! ## Splitting off a line -/

section Two

variable {ψ : Additive ↥N →+ ZMod 2} {z : G}

private theorem zmod_two_eq_one (v : ZMod 2) (hv : v ≠ 0) : v = 1 := by revert v; decide

private theorem zpow_eq_one_or_self (hz : z ^ 2 = 1) (k : ℤ) : z ^ k = 1 ∨ z ^ k = z := by
  have h2 : z ^ (2 : ℤ) = 1 := by rw [zpow_two, ← pow_two, hz]
  rcases Int.even_or_odd k with ⟨m, rfl⟩ | ⟨m, rfl⟩
  · left
    rw [← two_mul, zpow_mul, h2, one_zpow]
  · right
    rw [zpow_add, zpow_mul, h2, one_zpow, one_mul, zpow_one]

/-- An element squaring to the identity generates a subgroup with at most two elements. -/
theorem eq_one_or_eq_of_mem_zpowers (hz : z ^ 2 = 1) {w : G} (hw : w ∈ Subgroup.zpowers z) :
    w = 1 ∨ w = z := by
  obtain ⟨k, rfl⟩ := hw
  exact zpow_eq_one_or_self hz k

/-- **A character not vanishing at an element of order two splits its subgroup**: the kernel of the
character and the subgroup generated by that element generate it. -/
theorem sup_charKer_zpowers (hzN : z ∈ N) (hz : charValue N ψ z ≠ 0) :
    charKer N ψ ⊔ Subgroup.zpowers z = N := by
  refine le_antisymm (sup_le (charKer_le ψ) (Subgroup.zpowers_le.mpr hzN)) fun w hw => ?_
  rcases eq_or_ne (charValue N ψ w) 0 with h | h
  · exact Subgroup.mem_sup_left ⟨hw, h⟩
  · have hzw : w * z⁻¹ ∈ charKer N ψ := by
      refine ⟨N.mul_mem hw (N.inv_mem hzN), ?_⟩
      rw [charValue_mul ψ hw (N.inv_mem hzN), charValue_inv ψ hzN, zmod_two_eq_one _ h,
        zmod_two_eq_one _ hz]
      decide
    have hmem := Subgroup.mul_mem_sup hzw (Subgroup.mem_zpowers z)
    rwa [inv_mul_cancel_right] at hmem

/-- **A character not vanishing at an element of order two splits its subgroup**: the kernel of the
character meets the subgroup generated by that element trivially. -/
theorem inf_charKer_zpowers (hz2 : z ^ 2 = 1) (hz : charValue N ψ z ≠ 0) :
    charKer N ψ ⊓ Subgroup.zpowers z = ⊥ := by
  refine le_antisymm (fun w hw => ?_) bot_le
  rcases eq_one_or_eq_of_mem_zpowers hz2 hw.2 with rfl | rfl
  · exact Subgroup.mem_bot.mpr rfl
  · exact absurd hw.1.2 hz

end Two

/-! ## Correcting a character along a distinguished element -/

section Correct

/-- **Adding a character to another does not change its kernel inside the kernel of the character
added.** -/
theorem inf_charKer_add (α β : Additive ↥N →+ ZMod 2) :
    charKer N (α + β) ⊓ charKer N β = charKer N α ⊓ charKer N β := by
  ext g
  simp only [Subgroup.mem_inf, mem_charKer, charValue_add]
  constructor
  · rintro ⟨⟨hgN, h1⟩, -, h2⟩
    rw [h2, add_zero] at h1
    exact ⟨⟨hgN, h1⟩, hgN, h2⟩
  · rintro ⟨⟨hgN, h1⟩, -, h2⟩
    exact ⟨⟨hgN, by rw [h1, h2, add_zero]⟩, hgN, h2⟩

/-- **A character can be corrected so as to vanish at a distinguished element**, at the cost of
adding a character not vanishing there; inside the kernel of the character added, the kernel is
unchanged. -/
theorem exists_charValue_eq_zero_of_ne_zero (α β : Additive ↥N →+ ZMod 2) {w : G}
    (hβw : charValue N β w ≠ 0) :
    ∃ γ : Additive ↥N →+ ZMod 2, charValue N γ w = 0 ∧
      charKer N γ ⊓ charKer N β = charKer N α ⊓ charKer N β := by
  by_cases hαw : charValue N α w = 0
  · exact ⟨α, hαw, rfl⟩
  · refine ⟨α + β, ?_, inf_charKer_add α β⟩
    rw [charValue_add, zmod_two_eq_one _ hαw, zmod_two_eq_one _ hβw]
    decide

/-- **Putting a distinguished element back into a hyperplane of a subgroup.**  Cutting a subgroup
by the kernels of two characters and then adjoining an element seen by the first of them is again
the subgroup cut by the kernel of a single character, namely the second one corrected along the
element. -/
theorem sup_zpowers_eq_inf_charKer {Y : Subgroup G} {β α γ : Additive ↥N →+ ZMod 2} {w : G}
    (hwN : w ∈ N) (hwY : w ∈ Y) (hβw : charValue N β w ≠ 0) (hγw : charValue N γ w = 0)
    (hker : charKer N γ ⊓ charKer N β = charKer N α ⊓ charKer N β) :
    (Y ⊓ charKer N β) ⊓ charKer N α ⊔ Subgroup.zpowers w = Y ⊓ charKer N γ := by
  have hwmem : w ∈ Y ⊓ charKer N γ := Subgroup.mem_inf.mpr ⟨hwY, hwN, hγw⟩
  refine le_antisymm (sup_le (fun y hy => ?_) (Subgroup.zpowers_le.mpr hwmem)) fun y hy => ?_
  · obtain ⟨⟨hyY, hyβ⟩, hyα⟩ := hy
    exact Subgroup.mem_inf.mpr ⟨hyY, (hker ▸ Subgroup.mem_inf.mpr ⟨hyα, hyβ⟩ :
      y ∈ charKer N γ ⊓ charKer N β).1⟩
  · obtain ⟨hyY, hyγ⟩ := hy
    have hyN : y ∈ N := ((mem_charKer γ).mp hyγ).1
    have hyγ0 : charValue N γ y = 0 := ((mem_charKer γ).mp hyγ).2
    rcases eq_or_ne (charValue N β y) 0 with h | h
    · have : y ∈ charKer N α ⊓ charKer N β :=
        hker ▸ Subgroup.mem_inf.mpr ⟨hyγ, ⟨hyN, h⟩⟩
      exact Subgroup.mem_sup_left ⟨⟨hyY, hyN, h⟩, this.1⟩
    · have hwinv : w⁻¹ ∈ N := N.inv_mem hwN
      have huN : y * w⁻¹ ∈ N := N.mul_mem hyN hwinv
      have huβ : charValue N β (y * w⁻¹) = 0 := by
        rw [charValue_mul _ hyN hwinv, charValue_inv _ hwN, zmod_two_eq_one _ h,
          zmod_two_eq_one _ hβw]
        decide
      have huγ : charValue N γ (y * w⁻¹) = 0 := by
        rw [charValue_mul _ hyN hwinv, charValue_inv _ hwN, hyγ0, hγw, neg_zero, add_zero]
      have huα : y * w⁻¹ ∈ charKer N α ⊓ charKer N β :=
        hker ▸ Subgroup.mem_inf.mpr ⟨⟨huN, huγ⟩, ⟨huN, huβ⟩⟩
      have hu : y * w⁻¹ ∈ (Y ⊓ charKer N β) ⊓ charKer N α :=
        ⟨⟨Y.mul_mem hyY (Y.inv_mem hwY), huN, huβ⟩, huα.1⟩
      have := Subgroup.mul_mem_sup hu (Subgroup.mem_zpowers w)
      rwa [inv_mul_cancel_right] at this

/-- **A hyperplane of a subgroup and an element outside it generate a hyperplane.**  This is the
step of an induction cutting a subgroup down one character at a time: the element put back is the
one the induction has to keep inside every subgroup it considers. -/
theorem exists_sup_zpowers_eq_inf_charKer {Y : Subgroup G} (β α : Additive ↥N →+ ZMod 2) {w : G}
    (hwN : w ∈ N) (hwY : w ∈ Y) (hβw : charValue N β w ≠ 0) :
    ∃ γ : Additive ↥N →+ ZMod 2,
      (Y ⊓ charKer N β) ⊓ charKer N α ⊔ Subgroup.zpowers w = Y ⊓ charKer N γ := by
  obtain ⟨γ, hγw, hker⟩ := exists_charValue_eq_zero_of_ne_zero α β hβw
  exact ⟨γ, sup_zpowers_eq_inf_charKer hwN hwY hβw hγw hker⟩

end Correct

end InverseGalois
