/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.PCentral

/-!
# The first term of the lower `p`-central series and the Frattini subgroup

A maximal subgroup of a finite `p`-group is normal, and the quotient by it has no subgroup other
than the two trivial ones, so it is cyclic of order `p`.  Being abelian of exponent `p`, it kills
every commutator and every `p`-th power, which is to say that the first term of the lower
`p`-central series is contained in every maximal subgroup and hence in their intersection.

The reverse inclusion also holds, but is not needed: what the socle of a Scholz field requires is
that a character trivial on the commutators and the squares be trivial on the Frattini subgroup,
which is this direction.

## Main results

* `InverseGalois.lowerPCentralSeries_one_le_coatom`: the commutators and `p`-th powers of a finite
  `p`-group lie in every maximal subgroup.
* `InverseGalois.lowerPCentralSeries_one_le_frattini`: **the first term of the lower `p`-central
  series of a finite `p`-group lies in its Frattini subgroup.**

## Tags

`p`-group, Frattini subgroup, lower central series, maximal subgroup
-/

namespace InverseGalois

variable {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] [Finite G]

/-- The quotient of a finite `p`-group by a maximal subgroup has order `p`.  A nontrivial element
of the quotient generates a subgroup corresponding to a subgroup of the group strictly above the
maximal one, hence the whole quotient; so the quotient is generated by any element of order `p`,
which exists because the quotient is a nontrivial `p`-group. -/
theorem card_quotient_coatom (hG : IsPGroup p G) {M : Subgroup G} (hM : IsCoatom M) [M.Normal] :
    Nat.card (G ⧸ M) = p := by
  have hsurj : Function.Surjective (QuotientGroup.mk' M) := QuotientGroup.mk'_surjective M
  -- a subgroup of the quotient is trivial or everything
  have htop : ∀ K : Subgroup (G ⧸ M), K ≠ ⊥ → K = ⊤ := by
    intro K hK
    have hle : M ≤ Subgroup.comap (QuotientGroup.mk' M) K := by
      intro m hm
      simp [QuotientGroup.mk'_apply, (QuotientGroup.eq_one_iff m).mpr hm]
    have hne : Subgroup.comap (QuotientGroup.mk' M) K ≠ M := by
      intro h
      refine hK ?_
      rw [← Subgroup.map_comap_eq_self_of_surjective hsurj K, h]
      simp
    have heq : Subgroup.comap (QuotientGroup.mk' M) K = ⊤ :=
      hM.2 _ (lt_of_le_of_ne hle (Ne.symm hne))
    rw [← Subgroup.map_comap_eq_self_of_surjective hsurj K, heq]
    exact Subgroup.map_top_of_surjective _ hsurj
  -- the quotient is a nontrivial `p`-group, so it has an element of order `p`
  haveI : Nontrivial (G ⧸ M) := by
    refine ⟨1, QuotientGroup.mk (Classical.choose (SetLike.exists_of_lt (lt_top_iff_ne_top.mpr
      hM.1)) : G), ?_⟩
    have hx := Classical.choose_spec (SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hM.1))
    exact fun h => hx.2 ((QuotientGroup.eq_one_iff _).mp h.symm)
  have hq : IsPGroup p (G ⧸ M) := hG.to_quotient M
  obtain ⟨n, hn⟩ := IsPGroup.iff_card.mp hq
  have hnpos : n ≠ 0 := by
    rintro rfl
    rw [pow_zero] at hn
    exact absurd (Nat.card_eq_one_iff_unique.mp hn).1 (not_subsingleton _)
  obtain ⟨y, hy⟩ := exists_prime_orderOf_dvd_card' (G := G ⧸ M) p (hn ▸ dvd_pow_self p hnpos)
  have hy1 : (Subgroup.zpowers y) ≠ ⊥ := by
    intro h
    rw [Subgroup.zpowers_eq_bot.mp h, orderOf_one] at hy
    exact (Fact.out : p.Prime).one_lt.ne hy
  have hcard : Nat.card ↥(Subgroup.zpowers y) = p := by rw [Nat.card_zpowers, hy]
  rw [← Subgroup.card_top (G := G ⧸ M), ← htop _ hy1]
  exact hcard

/-- **The commutators and `p`-th powers of a finite `p`-group lie in every maximal subgroup.**
The quotient by a maximal subgroup has order `p`, so it is abelian of exponent `p`. -/
theorem lowerPCentralSeries_one_le_coatom (hG : IsPGroup p G) {M : Subgroup G}
    (hM : IsCoatom M) : lowerPCentralSeries p G 1 ≤ M := by
  haveI : M.Normal :=
    Subgroup.NormalizerCondition.normal_of_coatom M
      (normalizerCondition_of_isNilpotent (h := hG.isNilpotent)) hM
  have hcard := card_quotient_coatom hG hM
  haveI : IsCyclic (G ⧸ M) := isCyclic_of_prime_card (p := p) hcard
  have hcomm : ∀ a b : G ⧸ M, a * b = b * a := by
    letI := IsCyclic.commGroup (α := G ⧸ M)
    exact fun a b => mul_comm a b
  refine lowerPCentralSeries_succ_le_of (fun x _ y => ?_) (fun x _ => ?_)
  · rw [← QuotientGroup.eq_one_iff, commutatorElement_def, QuotientGroup.mk_mul,
      QuotientGroup.mk_mul, QuotientGroup.mk_mul, QuotientGroup.mk_inv, QuotientGroup.mk_inv,
      hcomm ((x : G ⧸ M)) ((y : G ⧸ M))]
    group
  · rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow, ← hcard]
    exact pow_card_eq_one'

/-- **The first term of the lower `p`-central series of a finite `p`-group lies in its Frattini
subgroup**, the Frattini subgroup being the intersection of the maximal subgroups. -/
theorem lowerPCentralSeries_one_le_frattini (hG : IsPGroup p G) :
    lowerPCentralSeries p G 1 ≤ frattini G := by
  rw [frattini, Order.radical]
  exact le_iInf₂ fun M hM => lowerPCentralSeries_one_le_coatom hG hM

/-- **Every term of the lower `p`-central series of a finite `p`-group past the first lies in its
Frattini subgroup**, the series being decreasing. -/
theorem lowerPCentralSeries_le_frattini (hG : IsPGroup p G) {n : ℕ} (hn : 1 ≤ n) :
    lowerPCentralSeries p G n ≤ frattini G :=
  (antitone_lowerPCentralSeries p G hn).trans (lowerPCentralSeries_one_le_frattini hG)

end InverseGalois
