/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.PCentralGenerators

/-!
# The free `p`-groups of bounded `p`-class

The groups of `p`-class at most `c` — those whose lower `p`-central series has reached the trivial
subgroup after `c` steps — form a variety, and the free object of rank `d` in it is the quotient
of the free group on `d` letters by the `c`-th term of its own lower `p`-central series.  Every
group of `p`-class at most `c` generated by `d` elements is a quotient of that object, by the
universal property of the free group; and the object is a *finite* `p`-group, because its lower
`p`-central series terminates and it is finitely generated.

These are the groups through which an induction on the `p`-class of the target passes.  Their
decisive feature is that reducing the class is the same as passing to a quotient: dividing the
free object of class `c` by the `c'`-th term of its lower `p`-central series returns the free
object of class `c'`, so a realization of the smaller free object is exactly a subfield of a
realization of the larger one, and the step from one to the next is a central embedding problem
with elementary abelian kernel.

## Main definitions

* `InverseGalois.FreePClass`: the free group of rank `d` and `p`-class at most `c`.
* `InverseGalois.FreePClass.gen`: its distinguished generators.
* `InverseGalois.FreePClass.lift`: the homomorphism induced by a family of elements of a group of
  `p`-class at most `c`.

## Main results

* `InverseGalois.FreePClass.instFinite`, `InverseGalois.FreePClass.isPGroup`: the free object is a
  finite `p`-group.
* `InverseGalois.FreePClass.exists_surjective`: **every group of `p`-class at most `c` generated by
  `d` elements is a quotient of the free object of rank `d` and class `c`.**
* `InverseGalois.FreePClass.quotientEquiv`: **dividing the free object of class `c` by the `c'`-th
  term of its lower `p`-central series returns the free object of class `c'`.**

## Tags

free group, `p`-group, lower central series, variety
-/

namespace InverseGalois

/-- The free group of rank `d` in the variety of groups of `p`-class at most `c`. -/
def FreePClass (p d c : ℕ) : Type :=
  FreeGroup (Fin d) ⧸ lowerPCentralSeries p (FreeGroup (Fin d)) c

namespace FreePClass

instance instGroup (p d c : ℕ) : Group (FreePClass p d c) :=
  inferInstanceAs (Group (FreeGroup (Fin d) ⧸ lowerPCentralSeries p (FreeGroup (Fin d)) c))

/-- The canonical projection of the free group onto the free object of `p`-class at most `c`. -/
def mk (p d c : ℕ) : FreeGroup (Fin d) →* FreePClass p d c :=
  QuotientGroup.mk' (lowerPCentralSeries p (FreeGroup (Fin d)) c)

theorem mk_surjective (p d c : ℕ) : Function.Surjective (mk p d c) :=
  QuotientGroup.mk'_surjective _

theorem ker_mk (p d c : ℕ) :
    (mk p d c).ker = lowerPCentralSeries p (FreeGroup (Fin d)) c :=
  QuotientGroup.ker_mk' _

/-- The distinguished generators of the free object of rank `d` and `p`-class at most `c`. -/
def gen (p d c : ℕ) (i : Fin d) : FreePClass p d c :=
  mk p d c (FreeGroup.of i)

theorem closure_range_gen (p d c : ℕ) : Subgroup.closure (Set.range (gen p d c)) = ⊤ := by
  have hrange : Set.range (gen p d c) = mk p d c '' Set.range (FreeGroup.of : Fin d → _) := by
    rw [← Set.range_comp]
    rfl
  rw [hrange, ← MonoidHom.map_closure, FreeGroup.closure_range_of]
  exact Subgroup.map_top_of_surjective _ (mk_surjective p d c)

@[simp] theorem lowerPCentralSeries_eq_bot (p d c : ℕ) :
    lowerPCentralSeries p (FreePClass p d c) c = ⊥ := by
  rw [← map_lowerPCentralSeries p (mk_surjective p d c) c, Subgroup.map_eq_bot_iff, ker_mk]

instance instFinite (p d c : ℕ) [hp : NeZero p] : Finite (FreePClass p d c) :=
  finite_of_lowerPCentralSeries_eq_bot hp.out c (FreePClass p d c) (Set.range (gen p d c))
    (Set.finite_range _) (closure_range_gen p d c) (lowerPCentralSeries_eq_bot p d c)

theorem isPGroup (p d c : ℕ) : IsPGroup p (FreePClass p d c) :=
  isPGroup_of_lowerPCentralSeries_eq_bot p c (FreePClass p d c) (lowerPCentralSeries_eq_bot p d c)

/-! ## The universal property -/

variable {p d c : ℕ} {G : Type*} [Group G]

/-- The homomorphism out of the free object of `p`-class at most `c` induced by a family of
elements of a group whose own lower `p`-central series has reached the trivial subgroup. -/
def lift (h : lowerPCentralSeries p G c = ⊥) (f : Fin d → G) : FreePClass p d c →* G :=
  QuotientGroup.lift _ (FreeGroup.lift f) fun x hx => by
    have hle := map_lowerPCentralSeries_le p (FreeGroup.lift f) c
    rw [h, le_bot_iff] at hle
    exact MonoidHom.mem_ker.mp ((Subgroup.map_eq_bot_iff _).mp hle hx)

@[simp] theorem lift_gen (h : lowerPCentralSeries p G c = ⊥) (f : Fin d → G) (i : Fin d) :
    lift h f (gen p d c i) = f i :=
  FreeGroup.lift_apply_of

theorem lift_surjective (h : lowerPCentralSeries p G c = ⊥) {f : Fin d → G}
    (hf : Subgroup.closure (Set.range f) = ⊤) : Function.Surjective (lift h f) := by
  have hcomp : (lift h f) ∘ (gen p d c) = f := funext fun i => lift_gen h f i
  rw [← MonoidHom.range_eq_top, MonoidHom.range_eq_map, ← closure_range_gen p d c,
    MonoidHom.map_closure, ← Set.range_comp, hcomp, hf]

/-- **Every group of `p`-class at most `c` generated by `d` elements is a quotient of the free
object of rank `d` and `p`-class at most `c`.** -/
theorem exists_surjective (h : lowerPCentralSeries p G c = ⊥) {f : Fin d → G}
    (hf : Subgroup.closure (Set.range f) = ⊤) :
    ∃ φ : FreePClass p d c →* G, Function.Surjective φ :=
  ⟨lift h f, lift_surjective h hf⟩

/-! ## Reducing the class -/

/-- **Dividing the free object of `p`-class at most `c` by the `c'`-th term of its lower
`p`-central series returns the free object of `p`-class at most `c'`.** -/
def quotientEquiv (p d : ℕ) {c c' : ℕ} (h : c' ≤ c) :
    FreePClass p d c ⧸ lowerPCentralSeries p (FreePClass p d c) c' ≃* FreePClass p d c' :=
  haveI : (Subgroup.map (mk p d c) (lowerPCentralSeries p (FreeGroup (Fin d)) c')).Normal :=
    Subgroup.Normal.map (lowerPCentralSeries_normal p _ c') _ (mk_surjective p d c)
  (QuotientGroup.quotientMulEquivOfEq
      (map_lowerPCentralSeries p (mk_surjective p d c) c').symm).trans
    (QuotientGroup.quotientQuotientEquivQuotient _ _
      (antitone_lowerPCentralSeries p (FreeGroup (Fin d)) h))

end FreePClass

end InverseGalois
