/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# The lower `p`-central series

The lower central series measures how far a group is from being abelian by repeatedly taking
commutators with the whole group.  For a `p`-group the relevant refinement also divides out
`p`-th powers at every stage: the resulting filtration

`λ₀ = G`,  `λₙ₊₁ = ⁅λₙ, G⁆ · λₙᵖ`

has *elementary abelian central* successive quotients, so it is the filtration that governs
presentations of `p`-groups by generators and relations.  The number of steps it takes to reach
the trivial subgroup is the `p`-class of the group, the invariant that, together with the number
of generators, cuts a finite `p`-group out of a single universal quotient of a free group.

This file introduces the series and establishes its basic calculus: it is a descending chain of
normal subgroups, a surjection carries it to the corresponding series of the image, and it
reaches the trivial subgroup in finitely many steps for a finite `p`-group.  The last statement is
proved by induction on the order: the series of the quotient by the centre reaches the trivial
subgroup, so the series of the group itself lands inside the centre, and from there every further
step raises central elements to the `p`-th power, which exhausts a finite `p`-group.

## Main definitions

* `InverseGalois.powSubgroup`: the subgroup generated by the `p`-th powers of a subgroup.
* `InverseGalois.lowerPCentralSeries`: the lower `p`-central series.

## Main results

* `InverseGalois.lowerPCentralSeries_succ_le` and `InverseGalois.antitone_lowerPCentralSeries`:
  the series descends.
* `InverseGalois.map_lowerPCentralSeries`: **a surjection carries the lower `p`-central series of
  the source onto that of the target.**
* `InverseGalois.exists_lowerPCentralSeries_eq_bot`: **the lower `p`-central series of a finite
  `p`-group reaches the trivial subgroup.**

## Tags

lower central series, `p`-group, `p`-class, Frattini quotient
-/

universe u

namespace InverseGalois

variable {G H : Type*} [Group G] [Group H]

/-! ## Subgroups generated by `p`-th powers -/

/-- The subgroup generated by the `p`-th powers of the elements of `K`. -/
def powSubgroup (p : ℕ) (K : Subgroup G) : Subgroup G :=
  Subgroup.closure ((· ^ p) '' (K : Set G))

theorem pow_mem_powSubgroup {p : ℕ} {K : Subgroup G} {x : G} (hx : x ∈ K) :
    x ^ p ∈ powSubgroup p K :=
  Subgroup.subset_closure ⟨x, hx, rfl⟩

/-- The `p`-th powers of `K` generate the smallest subgroup containing them. -/
theorem powSubgroup_le {p : ℕ} {K L : Subgroup G} (h : ∀ x ∈ K, x ^ p ∈ L) :
    powSubgroup p K ≤ L := by
  rw [powSubgroup, Subgroup.closure_le]
  rintro _ ⟨x, hx, rfl⟩
  exact h x hx

theorem powSubgroup_le_self {p : ℕ} {K : Subgroup G} : powSubgroup p K ≤ K :=
  powSubgroup_le fun _ hx => K.pow_mem hx _

theorem powSubgroup_mono {p : ℕ} {K L : Subgroup G} (h : K ≤ L) :
    powSubgroup p K ≤ powSubgroup p L :=
  powSubgroup_le fun _ hx => pow_mem_powSubgroup (h hx)

/-- A group homomorphism carries the subgroup generated by the `p`-th powers of `K` to the
subgroup generated by the `p`-th powers of the image of `K`. -/
theorem map_powSubgroup (p : ℕ) (K : Subgroup G) (f : G →* H) :
    (powSubgroup p K).map f = powSubgroup p (K.map f) := by
  rw [powSubgroup, powSubgroup, MonoidHom.map_closure]
  congr 1
  ext y
  simp only [Set.mem_image, Subgroup.coe_map, SetLike.mem_coe]
  constructor
  · rintro ⟨_, ⟨x, hx, rfl⟩, rfl⟩
    exact ⟨f x, ⟨x, hx, rfl⟩, (map_pow f x p).symm⟩
  · rintro ⟨_, ⟨x, hx, rfl⟩, rfl⟩
    exact ⟨x ^ p, ⟨x, hx, rfl⟩, map_pow f x p⟩

/-- The subgroup generated by a set closed under conjugation is normal. -/
theorem normal_closure_of_conj_mem {S : Set G} (h : ∀ g x, x ∈ S → g * x * g⁻¹ ∈ S) :
    (Subgroup.closure S).Normal := by
  refine ⟨fun x hx g => ?_⟩
  induction hx using Subgroup.closure_induction with
  | mem y hy => exact Subgroup.subset_closure (h g y hy)
  | one => simp
  | mul a b _ _ ha hb =>
    have hconj : g * (a * b) * g⁻¹ = g * a * g⁻¹ * (g * b * g⁻¹) := by group
    rw [hconj]
    exact mul_mem ha hb
  | inv a _ ha =>
    have hconj : g * a⁻¹ * g⁻¹ = (g * a * g⁻¹)⁻¹ := by group
    rw [hconj]
    exact inv_mem ha

instance powSubgroup_normal (p : ℕ) (K : Subgroup G) [hK : K.Normal] :
    (powSubgroup p K).Normal := by
  refine normal_closure_of_conj_mem ?_
  rintro g _ ⟨x, hx, rfl⟩
  exact ⟨g * x * g⁻¹, hK.conj_mem x hx g, conj_pow⟩

/-! ## The series -/

/-- The lower `p`-central series of `G`: it starts at `G` and passes from one term to the next by
taking commutators with the whole group and adjoining `p`-th powers.  Its successive quotients are
elementary abelian and central. -/
def lowerPCentralSeries (p : ℕ) (G : Type*) [Group G] : ℕ → Subgroup G
  | 0 => ⊤
  | n + 1 =>
    ⁅lowerPCentralSeries p G n, (⊤ : Subgroup G)⁆ ⊔ powSubgroup p (lowerPCentralSeries p G n)

@[simp]
theorem lowerPCentralSeries_zero (p : ℕ) (G : Type*) [Group G] :
    lowerPCentralSeries p G 0 = ⊤ :=
  rfl

theorem lowerPCentralSeries_succ (p : ℕ) (G : Type*) [Group G] (n : ℕ) :
    lowerPCentralSeries p G (n + 1) =
      ⁅lowerPCentralSeries p G n, (⊤ : Subgroup G)⁆ ⊔ powSubgroup p (lowerPCentralSeries p G n) :=
  rfl

instance lowerPCentralSeries_normal (p : ℕ) (G : Type*) [Group G] (n : ℕ) :
    (lowerPCentralSeries p G n).Normal := by
  induction n with
  | zero => rw [lowerPCentralSeries_zero]; infer_instance
  | succ n ih =>
    haveI := ih
    rw [lowerPCentralSeries_succ]
    infer_instance

theorem lowerPCentralSeries_succ_le (p : ℕ) (G : Type*) [Group G] (n : ℕ) :
    lowerPCentralSeries p G (n + 1) ≤ lowerPCentralSeries p G n := by
  rw [lowerPCentralSeries_succ]
  exact sup_le (Subgroup.commutator_le_left _ _) powSubgroup_le_self

theorem antitone_lowerPCentralSeries (p : ℕ) (G : Type*) [Group G] :
    Antitone (lowerPCentralSeries p G) :=
  antitone_nat_of_succ_le (lowerPCentralSeries_succ_le p G)

theorem commutator_mem_lowerPCentralSeries_succ {p : ℕ} {n : ℕ} {x y : G}
    (hx : x ∈ lowerPCentralSeries p G n) : ⁅x, y⁆ ∈ lowerPCentralSeries p G (n + 1) :=
  (le_sup_left : _ ≤ lowerPCentralSeries p G (n + 1))
    (Subgroup.commutator_mem_commutator hx (Subgroup.mem_top y))

theorem pow_mem_lowerPCentralSeries_succ {p : ℕ} {n : ℕ} {x : G}
    (hx : x ∈ lowerPCentralSeries p G n) : x ^ p ∈ lowerPCentralSeries p G (n + 1) :=
  (le_sup_right : _ ≤ lowerPCentralSeries p G (n + 1)) (pow_mem_powSubgroup hx)

/-- To bound one step of the lower `p`-central series it is enough to bound the commutators with
the whole group and the `p`-th powers. -/
theorem lowerPCentralSeries_succ_le_of {p : ℕ} {n : ℕ} {L : Subgroup G}
    (hcomm : ∀ x ∈ lowerPCentralSeries p G n, ∀ y : G, ⁅x, y⁆ ∈ L)
    (hpow : ∀ x ∈ lowerPCentralSeries p G n, x ^ p ∈ L) :
    lowerPCentralSeries p G (n + 1) ≤ L := by
  rw [lowerPCentralSeries_succ]
  exact sup_le (Subgroup.commutator_le.mpr fun x hx y _ => hcomm x hx y) (powSubgroup_le hpow)

/-! ## Functoriality -/

/-- Any homomorphism carries the lower `p`-central series into the lower `p`-central series. -/
theorem map_lowerPCentralSeries_le (p : ℕ) (f : G →* H) (n : ℕ) :
    (lowerPCentralSeries p G n).map f ≤ lowerPCentralSeries p H n := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [lowerPCentralSeries_succ, lowerPCentralSeries_succ, Subgroup.map_sup,
      Subgroup.map_commutator, map_powSubgroup]
    exact sup_le (le_sup_left.trans' (Subgroup.commutator_mono ih le_top))
      (le_sup_right.trans' (powSubgroup_mono ih))

/-- **A surjection carries the lower `p`-central series of the source onto that of the target.** -/
theorem map_lowerPCentralSeries (p : ℕ) {f : G →* H} (hf : Function.Surjective f) (n : ℕ) :
    (lowerPCentralSeries p G n).map f = lowerPCentralSeries p H n := by
  induction n with
  | zero => simpa using Subgroup.map_top_of_surjective f hf
  | succ n ih =>
    rw [lowerPCentralSeries_succ, lowerPCentralSeries_succ, Subgroup.map_sup,
      Subgroup.map_commutator, map_powSubgroup, ih, Subgroup.map_top_of_surjective f hf]

/-- If the lower `p`-central series of a quotient reaches the trivial subgroup at step `n`, then
the corresponding term for the group lies in the subgroup that was divided out. -/
theorem lowerPCentralSeries_le_of_quotient_eq_bot (p : ℕ) (N : Subgroup G) [N.Normal] {n : ℕ}
    (h : lowerPCentralSeries p (G ⧸ N) n = ⊥) : lowerPCentralSeries p G n ≤ N := by
  have hmap := map_lowerPCentralSeries p (QuotientGroup.mk'_surjective N) n
  rw [h, Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk'] at hmap
  exact hmap

/-- The lower `p`-central series of a quotient reaches the trivial subgroup as soon as the series
of the group does. -/
theorem lowerPCentralSeries_eq_bot_of_surjective (p : ℕ) {f : G →* H} (hf : Function.Surjective f)
    {n : ℕ} (h : lowerPCentralSeries p G n = ⊥) : lowerPCentralSeries p H n = ⊥ := by
  rw [← map_lowerPCentralSeries p hf n, h, Subgroup.map_bot]

theorem lowerPCentralSeries_eq_bot_of_le (p : ℕ) (G : Type*) [Group G] {c c' : ℕ} (hc : c ≤ c')
    (h : lowerPCentralSeries p G c = ⊥) : lowerPCentralSeries p G c' = ⊥ :=
  le_bot_iff.mp (h ▸ antitone_lowerPCentralSeries p G hc)

/-! ## Termination for a finite `p`-group -/

/-- Raising a central element to the `p ^ k`-th power. -/
def centerPowHom (p k : ℕ) (G : Type*) [Group G] : Subgroup.center G →* G where
  toFun z := (z : G) ^ p ^ k
  map_one' := one_pow _
  map_mul' z w := by
    have h : Commute (z : G) (w : G) := (Subgroup.mem_center_iff.mp z.2 (w : G)).symm
    simpa using h.mul_pow (p ^ k)

@[simp]
theorem centerPowHom_apply (p k : ℕ) (G : Type*) [Group G] (z : Subgroup.center G) :
    centerPowHom p k G z = (z : G) ^ p ^ k :=
  rfl

/-- Once the lower `p`-central series has entered the centre, every further step raises central
elements to the `p`-th power. -/
theorem lowerPCentralSeries_le_range_centerPowHom (p : ℕ) {G : Type*} [Group G] {m : ℕ}
    (hm : lowerPCentralSeries p G m ≤ Subgroup.center G) (k : ℕ) :
    lowerPCentralSeries p G (m + k) ≤ (centerPowHom p k G).range := by
  induction k with
  | zero =>
    intro x hx
    exact ⟨⟨x, hm hx⟩, by simp⟩
  | succ k ih =>
    have hcen : lowerPCentralSeries p G (m + k) ≤ Subgroup.center G := fun x hx => by
      obtain ⟨z, rfl⟩ := ih hx
      exact (Subgroup.center G).pow_mem z.2 _
    refine lowerPCentralSeries_succ_le_of (n := m + k) (fun x hx y => ?_) (fun x hx => ?_)
    · have hxy : x * y = y * x := (Subgroup.mem_center_iff.mp (hcen hx) y).symm
      have : ⁅x, y⁆ = 1 := by rw [commutatorElement_def, hxy]; group
      rw [this]
      exact one_mem _
    · obtain ⟨z, hz⟩ := ih hx
      refine ⟨z, ?_⟩
      rw [centerPowHom_apply, ← hz, centerPowHom_apply, ← pow_mul, ← pow_succ]

private theorem exists_lowerPCentralSeries_eq_bot_aux {p : ℕ} (hp : p.Prime) :
    ∀ (n : ℕ) (G : Type u) [Group G] [Finite G], IsPGroup p G → Nat.card G ≤ n →
      ∃ c, lowerPCentralSeries p G c = ⊥ := by
  haveI : Fact p.Prime := ⟨hp⟩
  intro n
  induction n with
  | zero =>
    intro G _ _ _ hcard
    have := Nat.card_pos (α := G)
    omega
  | succ n ih =>
    intro G _ _ hG hcard
    rcases subsingleton_or_nontrivial G with _ | _
    · refine ⟨0, ?_⟩
      rw [lowerPCentralSeries_zero, Subgroup.eq_bot_iff_forall]
      exact fun x _ => Subsingleton.elim x 1
    · haveI : Nontrivial (Subgroup.center G) := hG.center_nontrivial
      have hmul : Nat.card (Subgroup.center G) * (Subgroup.center G).index = Nat.card G :=
        Subgroup.card_mul_index _
      have hcardG : 0 < Nat.card G := Nat.card_pos
      have hidx : 0 < (Subgroup.center G).index := by
        rcases Nat.eq_zero_or_pos (Subgroup.center G).index with h | h
        · rw [h, Nat.mul_zero] at hmul
          omega
        · exact h
      have hZ : 1 < Nat.card (Subgroup.center G) := Finite.one_lt_card
      have hlt : Nat.card (G ⧸ Subgroup.center G) < Nat.card G := by
        rw [← Subgroup.index_eq_card, ← hmul]
        exact lt_mul_iff_one_lt_left hidx |>.mpr hZ
      obtain ⟨m, hm⟩ := ih (G ⧸ Subgroup.center G) (hG.to_quotient _) (by omega)
      have hle : lowerPCentralSeries p G m ≤ Subgroup.center G :=
        lowerPCentralSeries_le_of_quotient_eq_bot p _ hm
      obtain ⟨j, hj⟩ := (IsPGroup.iff_card (p := p) (G := Subgroup.center G)).mp
        (hG.to_subgroup (Subgroup.center G))
      refine ⟨m + j, le_bot_iff.mp ((lowerPCentralSeries_le_range_centerPowHom p hle j).trans ?_)⟩
      rintro _ ⟨z, rfl⟩
      rw [centerPowHom_apply, ← hj]
      have hcoe : (z : G) ^ Nat.card (Subgroup.center G) =
          ((z ^ Nat.card (Subgroup.center G) : Subgroup.center G) : G) := rfl
      rw [hcoe, pow_card_eq_one']
      exact Subgroup.mem_bot.mpr rfl

/-- **The lower `p`-central series of a finite `p`-group reaches the trivial subgroup**: every
finite `p`-group has a finite `p`-class. -/
theorem exists_lowerPCentralSeries_eq_bot {p : ℕ} (hp : p.Prime) (G : Type u) [Group G] [Finite G]
    (hG : IsPGroup p G) : ∃ c, lowerPCentralSeries p G c = ⊥ :=
  exists_lowerPCentralSeries_eq_bot_aux hp (Nat.card G) G hG le_rfl

end InverseGalois
