/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.Metacyclic

/-!
# A criterion for semiabelianness

Dentzer's class of semiabelian groups is generated from the trivial group by semidirect products
with a finite abelian group and by surjective images.  A group is therefore semiabelian as soon as
it is *covered* by such a semidirect product, and covering is a much weaker requirement than being
one: it is enough to have an abelian group `A` mapping into `G`, a semiabelian group `H` mapping
into `G` and normalising the image of `A`, and the two images together generating `G`.  The
semidirect product `A ⋊ H` formed from the conjugation action then surjects onto `G`.

The typical use is a normal abelian subgroup `N` of `G` together with any semiabelian subgroup
that supplements it.  When the quotient `G ⧸ N` is cyclic a single element supplements `N`, and the
cyclic group it generates is abelian, so **a finite group with a normal abelian subgroup of cyclic
quotient is semiabelian** — no splitting hypothesis, the covering does the work of a section.

## Main results

* `IsSemiabelian.of_conj_of_sup_eq_top`: **a group generated by the image of an abelian group and
  the image of a semiabelian group normalising it is semiabelian.**
* `IsSemiabelian.of_normal_of_sup_eq_top`: the same for a normal abelian subgroup supplemented by
  the image of a semiabelian group.
* `IsSemiabelian.of_normal_abelian_of_isCyclic_quotient`: **a finite group with a normal abelian
  subgroup of cyclic quotient is semiabelian.**
* `IsSemiabelian.of_normal_abelian_of_prime_index`: the same when the subgroup has prime index.
* `IsSemiabelian.of_mul_comm`: an abelian finite group is semiabelian, with commutativity supplied
  as a hypothesis rather than as an instance.
-/

namespace IsSemiabelian

/-- **A group covered by a semidirect product of an abelian group by a semiabelian one is
semiabelian.**  The compatibility hypothesis says that the action of `H` on `A` is the conjugation
action inside `G`, so that the two maps assemble into a homomorphism from `A ⋊[φ] H`, and the
generation hypothesis says that this homomorphism is surjective. -/
theorem of_conj_of_sup_eq_top {G A H : Type} [Group G] [Finite G] [CommGroup A] [Finite A]
    [Group H] [Finite H] (φ : H →* MulAut A) (α : A →* G) (ψ : H →* G)
    (hconj : ∀ (h : H) (a : A), α (φ h a) = ψ h * α a * (ψ h)⁻¹)
    (hsup : α.range ⊔ ψ.range = ⊤) (hH : IsSemiabelian H) : IsSemiabelian G := by
  have hcomp : ∀ h : H, α.comp (φ h).toMonoidHom = (MulAut.conj (ψ h)).toMonoidHom.comp α :=
    fun h => MonoidHom.ext fun a => hconj h a
  set f := SemidirectProduct.lift α ψ hcomp with hf
  have hrange : f.range = ⊤ := by
    refine top_le_iff.mp (hsup ▸ sup_le ?_ ?_)
    · rintro _ ⟨a, rfl⟩
      exact ⟨SemidirectProduct.inl a, by rw [hf, SemidirectProduct.lift_inl]⟩
    · rintro _ ⟨h, rfl⟩
      exact ⟨SemidirectProduct.inr h, by rw [hf, SemidirectProduct.lift_inr]⟩
  exact (IsSemiabelian.semidirect φ hH).of_surjective f (MonoidHom.range_eq_top.mp hrange)

/-- **A group generated by a normal abelian subgroup and the image of a semiabelian group is
semiabelian.**  The subgroup carries the conjugation action of the ambient group, which restricts
along the given homomorphism to an action of the semiabelian group. -/
theorem of_normal_of_sup_eq_top {G H : Type} [Group G] [Finite G] [Group H] [Finite H]
    (N : Subgroup G) [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x) (ψ : H →* G)
    (hsup : N ⊔ ψ.range = ⊤) (hH : IsSemiabelian H) : IsSemiabelian G := by
  letI : CommGroup ↥N := { (inferInstance : Group ↥N) with mul_comm := hcomm }
  refine of_conj_of_sup_eq_top (MulAut.conjNormal.comp ψ) N.subtype ψ (fun h a => ?_) ?_ hH
  · exact MulAut.conjNormal_apply (ψ h) a
  · rwa [N.range_subtype]

/-- **A finite group with a normal abelian subgroup of cyclic quotient is semiabelian.**  Any
element whose class generates the quotient supplements the subgroup, and the cyclic group of its
order maps onto the subgroup it generates. -/
theorem of_normal_abelian_of_isCyclic_quotient {G : Type} [Group G] [Finite G] (N : Subgroup G)
    [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x) [IsCyclic (G ⧸ N)] : IsSemiabelian G := by
  obtain ⟨q, hq⟩ := IsCyclic.exists_generator (α := G ⧸ N)
  obtain ⟨c, rfl⟩ := QuotientGroup.mk_surjective q
  haveI : NeZero (orderOf c) := ⟨(orderOf_pos c).ne'⟩
  set ψ := Semiabelian.zmodHomOfPowEqOne (orderOf c) c (pow_orderOf_eq_one c) with hψ
  refine of_normal_of_sup_eq_top N hcomm ψ ?_ (IsSemiabelian.of_commGroup _)
  have hzp : Subgroup.zpowers c ≤ ψ.range := by
    rw [hψ]
    exact Semiabelian.zpowers_le_range_zmodHomOfPowEqOne _ _ _
  refine top_le_iff.mp fun g _ => ?_
  obtain ⟨k, hk⟩ := hq (QuotientGroup.mk g)
  have hmk : (QuotientGroup.mk g : G ⧸ N) = QuotientGroup.mk (c ^ k) := by
    rw [← hk]
    simp
  have hmem : g * (c ^ k)⁻¹ ∈ N := by
    simpa [div_eq_mul_inv] using QuotientGroup.eq_iff_div_mem.mp hmk
  have h1 : g * (c ^ k)⁻¹ ∈ N ⊔ ψ.range := Subgroup.mem_sup_left hmem
  have h2 : c ^ k ∈ N ⊔ ψ.range :=
    Subgroup.mem_sup_right (hzp (Subgroup.zpow_mem_zpowers c k))
  simpa using mul_mem h1 h2

/-- **A finite group with a normal abelian subgroup of prime index is semiabelian.**  A group of
prime order is cyclic. -/
theorem of_normal_abelian_of_prime_index {G : Type} [Group G] [Finite G] (N : Subgroup G)
    [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x) {p : ℕ} [Fact p.Prime] (hp : N.index = p) :
    IsSemiabelian G := by
  haveI : IsCyclic (G ⧸ N) :=
    isCyclic_of_prime_card (p := p) (by rwa [← Subgroup.index_eq_card])
  exact of_normal_abelian_of_isCyclic_quotient N hcomm

/-- **An abelian finite group is semiabelian**, with commutativity supplied as a hypothesis rather
than as an instance.  The group is a normal abelian subgroup of itself, and the quotient by it is
trivial, hence cyclic. -/
theorem of_mul_comm {G : Type} [Group G] [Finite G] (hcomm : ∀ x y : G, x * y = y * x) :
    IsSemiabelian G := by
  haveI : Subsingleton (G ⧸ (⊤ : Subgroup G)) := QuotientGroup.subsingleton_quotient_top
  haveI : IsCyclic (G ⧸ (⊤ : Subgroup G)) := isCyclic_of_subsingleton
  exact of_normal_abelian_of_isCyclic_quotient ⊤ fun x y => Subtype.ext (hcomm (x : G) (y : G))

end IsSemiabelian
