/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.SemiabelianCriterion

/-!
# Small groups are semiabelian

Dentzer's class of semiabelian groups is closed under the covering criterion of
`InverseGalois.Solvable.SemiabelianCriterion`: a finite group with a normal abelian subgroup of
prime index belongs to the class.  This file feeds that criterion with the two classical sources of
normal subgroups of prime index in a small group.

The first is the *smallest prime factor* phenomenon: a subgroup whose index equals the smallest
prime dividing the order of the ambient group is automatically normal, because the ambient group
acts on the coset space and the resulting permutation representation has image of order dividing
`p !` while its kernel has index dividing the group order, leaving no room for a proper normal
core.  Mathlib records this as `Subgroup.normal_of_index_eq_minFac_card`.  Combining it with the
criterion gives the workhorse of the file: *an abelian subgroup whose index is the smallest prime
factor of the order makes the whole group semiabelian.*

The second is Sylow's first theorem, which supplies subgroups of every prime-power order dividing
the group order.  In a group of order `p ^ n` with `n ≤ 3` one takes a subgroup of order
`p ^ (n - 1)`; it has index `p`, which is the smallest prime factor, and it is abelian because
groups of order `1`, `p` and `p ^ 2` are commutative — the last by the standard argument that the
quotient by the centre cannot be cyclic and nontrivial.  In a group of order `p * q` with `p ≤ q`
one takes a subgroup of order `q`; it is cyclic of prime order and its index `p` is again the
smallest prime factor.  So every group of order `p`, `p ^ 2`, `p ^ 3` or `p * q` is semiabelian,
and in particular is realizable by the wreath-product machinery.

## Main results

* `IsSemiabelian.of_abelian_of_index_eq_minFac` — **a finite group with an abelian subgroup whose
  index is the smallest prime factor of its order is semiabelian**; no normality hypothesis is
  needed, as such a subgroup is normal automatically.
* `Semiabelian.mul_comm_of_card_eq_prime` — a group of prime order is commutative.
* `IsSemiabelian.of_card_eq_prime` — every group of prime order is semiabelian.
* `IsSemiabelian.of_card_eq_prime_sq` — every group of order `p ^ 2` is semiabelian.
* `IsSemiabelian.of_card_eq_prime_cube` — **every group of order `p ^ 3` is semiabelian**.
* `IsSemiabelian.of_card_eq_prime_mul_prime` — **every group of order `p * q`, for primes `p` and
  `q`, is semiabelian**.
-/

namespace Semiabelian

/-- **A group of prime order is commutative**: it is cyclic, being generated by any element other
than the identity, and cyclic groups are commutative. -/
theorem mul_comm_of_card_eq_prime {H : Type*} [Group H] {p : ℕ} (hp : p.Prime)
    (h : Nat.card H = p) : ∀ x y : H, x * y = y * x := by
  haveI : Fact p.Prime := ⟨hp⟩
  haveI : IsCyclic H := isCyclic_of_prime_card h
  exact fun x y => IsCyclic.commutative.comm x y

end Semiabelian

namespace IsSemiabelian

/-- **A finite group with an abelian subgroup whose index is the smallest prime factor of its
order is semiabelian.**  Normality is not an assumption: a subgroup of index equal to the smallest
prime factor of the order is always normal, since its normal core would otherwise have index a
proper multiple of that prime, yet dividing the factorial of the prime.  Once the subgroup is
normal it has prime index, so the quotient is cyclic and the covering criterion applies.  The
degenerate case of the trivial group, where the "smallest prime factor" of `1` is `1`, is handled
separately. -/
theorem of_abelian_of_index_eq_minFac {G : Type} [Group G] [Finite G] (N : Subgroup G)
    (hcomm : ∀ x y : ↥N, x * y = y * x) (hN : N.index = (Nat.card G).minFac) :
    IsSemiabelian G := by
  haveI : N.Normal := Subgroup.normal_of_index_eq_minFac_card hN
  by_cases h1 : Nat.card G = 1
  · haveI : Subsingleton G := (Nat.card_eq_one_iff_unique.mp h1).1
    exact .of_subsingleton G
  · haveI : Fact (Nat.card G).minFac.Prime := ⟨Nat.minFac_prime h1⟩
    exact of_normal_abelian_of_prime_index N hcomm hN

/-- **Every group of prime order is semiabelian**: it is cyclic, hence abelian, and the trivial
subgroup is an abelian subgroup whose index is the whole order, which is its own smallest prime
factor. -/
theorem of_card_eq_prime {G : Type} [Group G] [Finite G] {p : ℕ} (hp : p.Prime)
    (h : Nat.card G = p) : IsSemiabelian G := by
  refine of_abelian_of_index_eq_minFac ⊥ (fun x y => ?_) ?_
  · exact Subsingleton.elim _ _
  · rw [Subgroup.index_bot, h, hp.minFac_eq]

/-- **Every group of order `p ^ 2` is semiabelian.**  Sylow's first theorem produces a subgroup of
order `p`; it is cyclic, hence abelian, and its index is `p`, the smallest prime factor of
`p ^ 2`. -/
theorem of_card_eq_prime_sq {G : Type} [Group G] [Finite G] {p : ℕ} (hp : p.Prime)
    (h : Nat.card G = p ^ 2) : IsSemiabelian G := by
  haveI : Fact p.Prime := ⟨hp⟩
  obtain ⟨N, hNcard⟩ := Sylow.exists_subgroup_card_pow_prime (G := G) p (n := 1)
    (by rw [h, pow_one]; exact dvd_pow_self p two_ne_zero)
  rw [pow_one] at hNcard
  refine of_abelian_of_index_eq_minFac N (Semiabelian.mul_comm_of_card_eq_prime hp hNcard) ?_
  have hmul := N.card_mul_index
  rw [hNcard, h] at hmul
  have hindex : N.index = p := by
    refine Nat.eq_of_mul_eq_mul_left hp.pos ?_
    rw [hmul, sq]
  rw [hindex, h, hp.pow_minFac two_ne_zero]

/-- **Every group of order `p ^ 3` is semiabelian.**  Sylow's first theorem produces a subgroup of
order `p ^ 2`, which is commutative because the quotient of a group of order `p ^ 2` by its centre
is cyclic and a group with cyclic central quotient is abelian.  That subgroup has index `p`, the
smallest prime factor of `p ^ 3`, so it is normal and the criterion applies. -/
theorem of_card_eq_prime_cube {G : Type} [Group G] [Finite G] {p : ℕ} (hp : p.Prime)
    (h : Nat.card G = p ^ 3) : IsSemiabelian G := by
  haveI : Fact p.Prime := ⟨hp⟩
  obtain ⟨N, hNcard⟩ := Sylow.exists_subgroup_card_pow_prime (G := G) p (n := 2)
    (by rw [h]; exact pow_dvd_pow p (by norm_num))
  refine of_abelian_of_index_eq_minFac N (IsPGroup.commutative_of_card_eq_prime_sq hNcard) ?_
  have hmul := N.card_mul_index
  rw [hNcard, h] at hmul
  have hindex : N.index = p := by
    refine Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos 2) ?_
    rw [hmul]
    ring
  rw [hindex, h, hp.pow_minFac three_ne_zero]

/-- **A group of order `p * q` with `p ≤ q` prime is semiabelian.**  A Sylow `q`-subgroup has
order `q`, hence is cyclic and abelian, and its index is `p`; since `p ≤ q`, the smallest prime
factor of `p * q` is `p`, so the subgroup is normal of prime index. -/
theorem of_card_eq_prime_mul_prime_of_le {G : Type} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p ≤ q) (h : Nat.card G = p * q) :
    IsSemiabelian G := by
  haveI : Fact q.Prime := ⟨hq⟩
  have hone : 1 < p * q := lt_of_lt_of_le hp.one_lt (Nat.le_mul_of_pos_right p hq.pos)
  have hmin : (p * q).minFac = p := by
    have hle : (p * q).minFac ≤ p := Nat.minFac_le_of_dvd hp.two_le (Dvd.intro q rfl)
    have hpr := Nat.minFac_prime hone.ne'
    rcases (Nat.Prime.dvd_mul hpr).mp (Nat.minFac_dvd (p * q)) with hd | hd
    · exact (Nat.prime_dvd_prime_iff_eq hpr hp).mp hd
    · have hq' := (Nat.prime_dvd_prime_iff_eq hpr hq).mp hd
      omega
  obtain ⟨N, hNcard⟩ := Sylow.exists_subgroup_card_pow_prime (G := G) q (n := 1)
    (by rw [h, pow_one]; exact Dvd.intro_left p rfl)
  rw [pow_one] at hNcard
  refine of_abelian_of_index_eq_minFac N (Semiabelian.mul_comm_of_card_eq_prime hq hNcard) ?_
  have hmul := N.card_mul_index
  rw [hNcard, h] at hmul
  have hindex : N.index = p := by
    refine Nat.eq_of_mul_eq_mul_left hq.pos ?_
    rw [hmul, mul_comm p q]
  rw [hindex, h, hmin]

/-- **Every group of order `p * q`, for primes `p` and `q`, is semiabelian.**  Naming the two
primes so that the first is the smaller reduces to the ordered case; the case `p = q` is the
group of order `p ^ 2`, which the same argument covers. -/
theorem of_card_eq_prime_mul_prime {G : Type} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (h : Nat.card G = p * q) : IsSemiabelian G := by
  rcases le_total p q with hle | hle
  · exact of_card_eq_prime_mul_prime_of_le hp hq hle h
  · exact of_card_eq_prime_mul_prime_of_le hq hp hle (by rw [h, mul_comm])

end IsSemiabelian
