/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.SemiabelianCriterion

/-!
# Splitting criteria for semiabelianness

Dentzer's class of semiabelian groups is closed under building a semidirect product with a finite
abelian group, and more flexibly under being *covered* by such a semidirect product.  Concretely, a
finite group `G` with a normal abelian subgroup `N` is semiabelian as soon as some semiabelian
group maps into `G` so that its image together with `N` generates `G`.  The present file feeds that
criterion with the supplements produced by the classical splitting theorems.

The cleanest supplement is an honest subgroup `K ≤ G` with `N ⊔ K = ⊤`; there the covering map is
the inclusion `K.subtype`.  Such a `K` exists whenever the order of `N` is coprime to its index:
this is the **Schur–Zassenhaus** theorem, which even produces a complement, a subgroup meeting `N`
trivially and mapping isomorphically onto `G ⧸ N`.  Semiabelianness of the quotient therefore
transports to the complement and then, by the covering criterion, up to `G`.  Since a Sylow
`p`-subgroup always has order coprime to its index, a finite group with a normal abelian Sylow
subgroup of semiabelian quotient is semiabelian.

Independently of any coprimality, a group-theoretic section `s : G ⧸ N →* G` of the quotient map
supplements `N` directly: every `g` differs from `s (g mod N)` by an element of `N`.  So a split
extension of a semiabelian group by a finite abelian group is semiabelian, which recovers the
defining semidirect-product step without having to exhibit the action.

## Main results

* `IsSemiabelian.of_normal_abelian_of_sup_eq_top`: **a finite group generated by a normal abelian
  subgroup and a semiabelian subgroup is semiabelian.**
* `IsSemiabelian.of_normal_abelian_of_coprime_index`: the **Schur–Zassenhaus criterion** — a finite
  group with a normal abelian subgroup whose order is coprime to its index and whose quotient is
  semiabelian is semiabelian.
* `IsSemiabelian.of_normal_abelian_sylow`: a finite group with a normal abelian Sylow subgroup of
  semiabelian quotient is semiabelian.
* `IsSemiabelian.of_normal_abelian_of_section`: a finite group with a normal abelian subgroup whose
  quotient is semiabelian and whose quotient map admits a section is semiabelian.
-/

namespace IsSemiabelian

/-- **A finite group generated by a normal abelian subgroup and a semiabelian subgroup is
semiabelian.**  The inclusion of the supplementing subgroup is a homomorphism whose image, together
with the normal subgroup, exhausts the group, so the covering criterion applies with the
conjugation action of the subgroup on the normal one. -/
theorem of_normal_abelian_of_sup_eq_top {G : Type} [Group G] [Finite G] (N K : Subgroup G)
    [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x) (hsup : N ⊔ K = ⊤)
    (hK : IsSemiabelian ↥K) : IsSemiabelian G :=
  of_normal_of_sup_eq_top N hcomm K.subtype (by rwa [K.range_subtype]) hK

/-- **The Schur–Zassenhaus criterion for semiabelianness.**  If a normal abelian subgroup `N` of a
finite group has order coprime to its index, then it admits a complement `K`: a subgroup meeting
`N` trivially with `N ⊔ K = ⊤`, which the quotient map identifies with `G ⧸ N`.  Semiabelianness of
the quotient thus passes to `K`, and `N` together with `K` generates the whole group. -/
theorem of_normal_abelian_of_coprime_index {G : Type} [Group G] [Finite G] (N : Subgroup G)
    [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x)
    (hcop : Nat.Coprime (Nat.card ↥N) N.index) (hQ : IsSemiabelian (G ⧸ N)) :
    IsSemiabelian G := by
  obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime hcop
  exact of_normal_abelian_of_sup_eq_top N K hcomm hK.sup_eq_top
    (hQ.of_mulEquiv hK.symm.QuotientMulEquiv)

/-- **A finite group with a normal abelian Sylow subgroup of semiabelian quotient is
semiabelian.**  A Sylow `p`-subgroup is a Hall subgroup: its order is a power of `p` while `p` does
not divide its index, so the coprimality required by Schur–Zassenhaus is automatic. -/
theorem of_normal_abelian_sylow {G : Type} [Group G] [Finite G] {p : ℕ} [Fact p.Prime]
    (P : Sylow p G) [(P : Subgroup G).Normal]
    (hcomm : ∀ x y : ↥(P : Subgroup G), x * y = y * x)
    (hQ : IsSemiabelian (G ⧸ (P : Subgroup G))) : IsSemiabelian G :=
  of_normal_abelian_of_coprime_index _ hcomm P.card_coprime_index hQ

/-- **A split extension of a semiabelian group by a finite abelian normal subgroup is
semiabelian.**  A section `s` of the quotient map supplements the normal subgroup with no
coprimality assumption: each `g` and its lift `s (g mod N)` have the same class, hence differ by an
element of `N`, so the normal subgroup and the range of `s` generate the group. -/
theorem of_normal_abelian_of_section {G : Type} [Group G] [Finite G] (N : Subgroup G)
    [N.Normal] (hcomm : ∀ x y : ↥N, x * y = y * x) (s : G ⧸ N →* G)
    (hs : ∀ x : G ⧸ N, (QuotientGroup.mk (s x) : G ⧸ N) = x) (hQ : IsSemiabelian (G ⧸ N)) :
    IsSemiabelian G := by
  refine of_normal_of_sup_eq_top N hcomm s ?_ hQ
  refine top_le_iff.mp fun g _ => ?_
  have hmk : (QuotientGroup.mk g : G ⧸ N) = QuotientGroup.mk (s (QuotientGroup.mk g)) :=
    (hs (QuotientGroup.mk g)).symm
  have hmem : g * (s (QuotientGroup.mk g))⁻¹ ∈ N := by
    simpa [div_eq_mul_inv] using QuotientGroup.eq_iff_div_mem.mp hmk
  have h1 : g * (s (QuotientGroup.mk g))⁻¹ ∈ N ⊔ s.range := Subgroup.mem_sup_left hmem
  have h2 : s (QuotientGroup.mk g) ∈ N ⊔ s.range := Subgroup.mem_sup_right ⟨_, rfl⟩
  simpa using mul_mem h1 h2

end IsSemiabelian
