/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.Solvable.SemiabelianFrattini

/-!
# Groups of nilpotency class at most two are semiabelian

A finite group `G` whose commutator subgroup lies in its centre is very close to being abelian:
every subgroup containing the centre is normal, and adjoining a single element to the centre
produces an abelian normal subgroup.  That is exactly the input needed by the Frattini
supplementation criterion of `InverseGalois.Solvable.SemiabelianFrattini`, and it turns the whole
class into an induction on the order.

Concretely, let `G` be nontrivial with `⁅G, G⁆ ≤ Z(G)`.  The Frattini subgroup of a nontrivial
finite group is proper, so some `x : G` lies outside it, and the subgroup
`A = ⟨{x} ∪ Z(G)⟩` is generated by a set of pairwise commuting elements, hence abelian.  It
contains the centre, so it contains the commutator subgroup, which makes it normal: the conjugate
`g * a * g⁻¹` differs from `a` by the commutator `⁅a⁻¹, g⁆`.  Finally `x ∈ A` witnesses that `A`
escapes the Frattini subgroup, so `A` is supplemented by a proper subgroup.  The hypothesis
`⁅G, G⁆ ≤ Z(G)` is inherited by every subgroup — a commutator of elements of a subgroup is central
in the whole group, so a fortiori central in the subgroup — and the proper supplement is smaller,
which closes the induction.

## Main results

* `IsSemiabelian.of_commutator_le_center`: **a finite group whose commutator subgroup is contained
  in its centre is semiabelian.**
* `IsSemiabelian.of_nilpotencyClass_le_two`: **a finite nilpotent group of nilpotency class at most
  two is semiabelian.**
* `IsSemiabelian.of_isCyclic_quotient_center`: a finite group with cyclic central quotient is
  semiabelian.
-/

/-- The induction on the order behind `IsSemiabelian.of_commutator_le_center`, carried out over
all groups of order at most a given bound at once. -/
private theorem isSemiabelian_of_commutator_le_center_aux :
    ∀ (n : ℕ) (G : Type) [Group G] [Finite G], Nat.card G ≤ n →
      commutator G ≤ Subgroup.center G → IsSemiabelian G := by
  intro n
  induction n with
  | zero =>
    intro G _ _ hcard _
    exact absurd hcard (by simpa using Nat.card_pos.ne')
  | succ n ih =>
    intro G _ _ hcard h
    rcases subsingleton_or_nontrivial G with hs | hnt
    · exact .of_subsingleton G
    · have hfrne : frattini G ≠ ⊤ := by
        intro htop
        exact bot_ne_top
          (frattini_nongenerating (K := (⊥ : Subgroup G)) (by rw [htop, bot_sup_eq]))
      obtain ⟨x, hx⟩ := SetLike.exists_not_mem_of_ne_top (frattini G) hfrne
      set k : Set G := {x} ∪ (Subgroup.center G : Set G)
      have hcomm : ∀ a ∈ k, ∀ b ∈ k, a * b = b * a := by
        rintro a (rfl | ha) b (rfl | hb)
        · rfl
        · exact Subgroup.mem_center_iff.mp hb a
        · exact (Subgroup.mem_center_iff.mp ha b).symm
        · exact Subgroup.mem_center_iff.mp hb a
      set A : Subgroup G := Subgroup.closure k
      have hxA : x ∈ A := Subgroup.subset_closure (Or.inl rfl)
      have hzA : Subgroup.center G ≤ A := fun z hz => Subgroup.subset_closure (Or.inr hz)
      have habel : ∀ a b : ↥A, a * b = b * a := by
        letI := Subgroup.closureCommGroupOfComm hcomm
        intro a b
        exact mul_comm a b
      have hnorm : A.Normal := by
        constructor
        intro a ha g
        have hmem : ⁅a⁻¹, g⁆ ∈ A :=
          hzA (h (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)))
        have heq : g * a * g⁻¹ = a * ⁅a⁻¹, g⁆ := by
          rw [commutatorElement_def]; group
        rw [heq]
        exact A.mul_mem ha hmem
      haveI := hnorm
      refine IsSemiabelian.of_normal_abelian_not_le_frattini A habel
        (fun hle => hx (hle hxA)) fun U hU => ?_
      have hlt : Nat.card ↥U < Nat.card G := Subgroup.card_lt_card_of_ne_top hU
      refine ih ↥U (by omega) ?_
      rw [_root_.commutator_def, Subgroup.commutator_le]
      intro a _ b _
      rw [Subgroup.mem_center_iff]
      intro c
      have hz : (⁅(a : G), (b : G)⁆) ∈ Subgroup.center G :=
        h (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
      have hco : ((⁅a, b⁆ : ↥U) : G) = ⁅(a : G), (b : G)⁆ := by
        simp [commutatorElement_def]
      refine Subtype.ext ?_
      rw [Subgroup.coe_mul, Subgroup.coe_mul, hco]
      exact Subgroup.mem_center_iff.mp hz _

/-- **A finite group whose commutator subgroup is contained in its centre is semiabelian.**
Adjoining to the centre one element outside the Frattini subgroup produces an abelian normal
subgroup escaping the Frattini subgroup, and the hypothesis passes to subgroups, so the
supplementation criterion applies by induction on the order. -/
theorem IsSemiabelian.of_commutator_le_center {G : Type} [Group G] [Finite G]
    (h : commutator G ≤ Subgroup.center G) : IsSemiabelian G :=
  isSemiabelian_of_commutator_le_center_aux (Nat.card G) G le_rfl h

/-- **A finite nilpotent group of nilpotency class at most two is semiabelian.**  Class at most
two says that the second term of the upper central series is the whole group, which is precisely
the statement that all commutators are central. -/
theorem IsSemiabelian.of_nilpotencyClass_le_two {G : Type} [Group G] [Finite G]
    [Group.IsNilpotent G] (h : Group.nilpotencyClass G ≤ 2) : IsSemiabelian G := by
  refine IsSemiabelian.of_commutator_le_center ?_
  have htop : upperCentralSeries G 2 = ⊤ :=
    upperCentralSeries_eq_top_iff_nilpotencyClass_le.mpr h
  rw [_root_.commutator_def, Subgroup.commutator_le]
  intro a _ b _
  have ha : a ∈ upperCentralSeries G (1 + 1) := by rw [show 1 + 1 = 2 from rfl, htop]; trivial
  have hmem := mem_upperCentralSeries_succ_iff.mp ha b
  rwa [upperCentralSeries_one, ← commutatorElement_def] at hmem

/-- A finite group whose quotient by its centre is cyclic is semiabelian; such a group is in fact
abelian. -/
theorem IsSemiabelian.of_isCyclic_quotient_center {G : Type} [Group G] [Finite G]
    (h : IsCyclic (G ⧸ Subgroup.center G)) : IsSemiabelian G := by
  haveI := h
  exact IsSemiabelian.of_mul_comm (commutative_of_cyclic_center_quotient
    (QuotientGroup.mk' (Subgroup.center G)) (le_of_eq (QuotientGroup.ker_mk' _)))
