/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.CFT.Cyclotomic.DivisorSubfield
import InverseGalois.CFT.Cyclotomic.SquareRoots

/-!
# The quadratic subfield of a cyclotomic field of prime conductor

Let `q` be a prime congruent to `1` modulo `4`.  The quadratic Gauss sum attached to the quadratic
character of `ZMod q` and to a primitive `q`-th root of unity squares to `q` on the nose, because
the quadratic character takes the value `1` at `-1`; so `ℚ(ζ_q)` contains a square root `r` of `q`.
The Galois group of `ℚ(ζ_q)` over `ℚ` is cyclic, hence has a single subgroup of index two, so
`ℚ(r)` is *the* quadratic subfield of `ℚ(ζ_q)`.

Combining this with the splitting law of the subfield of prescribed degree identifies the primes
that split completely in `ℚ(r)`: they are the quadratic residues modulo `q`.  Quadratic reciprocity
turns the criterion around, so that for an odd prime `p` the field `ℚ(r)` splits `p` exactly when
`q` is a square modulo `p`.

## Main results

* `InverseGalois.CFT.isSquare_natCast_of_isPrimitiveRoot_one_mod_four`: a prime congruent to `1`
  modulo `4` is a square in any field of characteristic zero containing a primitive root of unity
  of that order.
* `InverseGalois.CFT.exists_sq_eq_natCast_of_one_mod_four`: such a prime is a square in every
  cyclotomic extension of `ℚ` of that conductor.
* `InverseGalois.CFT.finrank_adjoin_eq_two_of_sq_eq_natCast`: a square root of a prime generates a
  quadratic extension of `ℚ`.
* `InverseGalois.CFT.intermediateField_eq_of_finrank_eq_two`: two quadratic intermediate fields of
  a finite Galois extension with cyclic Galois group coincide.
* `InverseGalois.CFT.splitsCompletely_adjoin_sqrt_natCast`: the field generated by a square root of
  an odd prime `q` inside `ℚ(ζ_q)` is a Galois extension of `ℚ`, unramified away from `q`, in which
  a prime `p ≠ q` splits completely exactly when `p` is a square modulo `q`.
* `InverseGalois.CFT.splitsCompletely_adjoin_sqrt_natCast_iff_isSquare_symm`: for `q` congruent to
  `1` modulo `4` and `p` odd the criterion reads instead that `q` is a square modulo `p`.
-/

open NumberField IsCyclotomicExtension InverseGalois.NumberTheory IntermediateField
open AddChar MulChar

namespace InverseGalois.CFT

/-! ### A square root of a prime congruent to one modulo four -/

section GaussSum

variable {K : Type*} [Field K] [CharZero K]

/-- A prime `q` congruent to `1` modulo `4` is a square in a field of characteristic zero that
contains a primitive `q`-th root of unity: the quadratic Gauss sum has square `χ(-1) * q`, and the
quadratic character of `ZMod q` takes the value `1` at `-1` precisely under that congruence. -/
theorem isSquare_natCast_of_isPrimitiveRoot_one_mod_four {q : ℕ} (hq : q.Prime) (hq4 : q % 4 = 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ q) : IsSquare ((q : K)) := by
  classical
  haveI : Fact q.Prime := ⟨hq⟩
  haveI : NeZero q := ⟨hq.ne_zero⟩
  have hq2 : q ≠ 2 := by omega
  have hchar : ringChar (ZMod q) ≠ 2 := by rw [ZMod.ringChar_zmod_n]; exact hq2
  have hinj : Function.Injective (algebraMap ℤ K) := by
    intro a b h
    simpa [eq_intCast] using h
  set ψ : AddChar (ZMod q) K := zmodChar q hζ.pow_eq_one with hψdef
  have hψ : ψ.IsPrimitive := zmodChar_primitive_of_primitive_root q hζ
  set χ : MulChar (ZMod q) K := (quadraticChar (ZMod q)).ringHomComp (algebraMap ℤ K) with hχdef
  have hχ1 : χ ≠ 1 := (MulChar.ringHomComp_ne_one_iff hinj).mpr (quadraticChar_ne_one hchar)
  have hχ2 : χ.IsQuadratic := (quadraticChar_isQuadratic (ZMod q)).comp _
  have hsq := gaussSum_sq hχ1 hχ2 hψ
  rw [ZMod.card] at hsq
  have hneg : χ (-1) = 1 := by
    have h0 : quadraticChar (ZMod q) (-1) = 1 := by
      rw [quadraticChar_neg_one hchar, ZMod.card, ZMod.χ₄_nat_one_mod_four hq4]
    rw [hχdef, MulChar.ringHomComp_apply, h0, map_one]
  rw [hneg, one_mul] at hsq
  exact ⟨gaussSum χ ψ, by rw [← hsq]; ring⟩

end GaussSum

/-- A prime congruent to `1` modulo `4` is a square in every cyclotomic extension of `ℚ` whose
conductor is that prime. -/
theorem exists_sq_eq_natCast_of_one_mod_four {q : ℕ} (hq : q.Prime) (hq4 : q % 4 = 1)
    (E : Type*) [Field E] [NumberField E] [IsCyclotomicExtension {q} ℚ E] :
    ∃ r : E, r ^ 2 = (q : E) := by
  haveI : NeZero q := ⟨hq.ne_zero⟩
  obtain ⟨r, hr⟩ :=
    isSquare_natCast_of_isPrimitiveRoot_one_mod_four hq hq4 (zeta_spec q ℚ E)
  exact ⟨r, by rw [hr]; ring⟩

/-! ### The field generated by a square root of a prime -/

/-- A square root of a prime generates a quadratic extension of `ℚ`: it is a root of `X ^ 2 - q`,
and it is not rational because a prime is not a square. -/
theorem finrank_adjoin_eq_two_of_sq_eq_natCast {E : Type*} [Field E] [Algebra ℚ E] {q : ℕ}
    (hq : q.Prime) {r : E} (hr : r ^ 2 = (q : E)) :
    Module.finrank ℚ ℚ⟮r⟯ = 2 := by
  have hmonic : (Polynomial.X ^ 2 - Polynomial.C ((q : ℚ))).Monic :=
    Polynomial.monic_X_pow_sub_C _ (by norm_num)
  have hroot : (Polynomial.aeval r) (Polynomial.X ^ 2 - Polynomial.C ((q : ℚ))) = 0 := by
    simp [hr]
  have hint : IsIntegral ℚ r := ⟨_, hmonic, hroot⟩
  have hdeg : (Polynomial.X ^ 2 - Polynomial.C ((q : ℚ))).natDegree = 2 :=
    Polynomial.natDegree_X_pow_sub_C
  have hle : (minpoly ℚ r).natDegree ≤ 2 := by
    rw [← hdeg]
    exact Polynomial.natDegree_le_of_dvd (minpoly.dvd ℚ r hroot) hmonic.ne_zero
  have hpos : 0 < (minpoly ℚ r).natDegree := minpoly.natDegree_pos hint
  have hne : (minpoly ℚ r).natDegree ≠ 1 := by
    intro h1
    have hrank : Module.finrank ℚ ℚ⟮r⟯ = 1 := by
      rw [IntermediateField.adjoin.finrank hint, h1]
    have hbot : (ℚ⟮r⟯ : IntermediateField ℚ E) = ⊥ := IntermediateField.finrank_eq_one_iff.mp hrank
    obtain ⟨c, hc⟩ :=
      IntermediateField.mem_bot.mp (IntermediateField.adjoin_simple_eq_bot_iff.mp hbot)
    have hcq : c ^ 2 = (q : ℚ) := by
      have h : (algebraMap ℚ E) (c ^ 2) = (algebraMap ℚ E) ((q : ℚ)) := by
        rw [map_pow, hc, hr]
        simp
      exact (algebraMap ℚ E).injective h
    obtain ⟨k, hk⟩ := Rat.isSquare_natCast_iff.mp (⟨c, by rw [← hcq]; ring⟩ : IsSquare ((q : ℚ)))
    have h2 := hq.two_le
    rcases hq.eq_one_or_self_of_dvd k ⟨k, hk⟩ with rfl | rfl
    · omega
    · nlinarith
  rw [IntermediateField.adjoin.finrank hint]
  omega

/-- A finite cyclic group has at most one subgroup of index two: such a subgroup is normal, hence
contains every square, and the squares of a generator already form a subgroup of that index. -/
private theorem eq_of_index_eq_two {G : Type*} [Group G] [Finite G] [IsCyclic G]
    {H₁ H₂ : Subgroup G} (h₁ : H₁.index = 2) (h₂ : H₂.index = 2) : H₁ = H₂ := by
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := G)
  have hord : orderOf g = Nat.card G := orderOf_eq_card_of_forall_mem_zpowers hg
  have key : ∀ H : Subgroup G, H.index = 2 → H = Subgroup.zpowers (g ^ 2) := by
    intro H hH
    haveI : H.Normal := Subgroup.normal_of_index_eq_two hH
    have hmem : g ^ 2 ∈ H := by simpa [hH] using H.pow_index_mem g
    have hle : Subgroup.zpowers (g ^ 2) ≤ H := Subgroup.zpowers_le.mpr hmem
    have hcard : Nat.card ↥H * 2 = Nat.card G := by
      rw [← hH]
      exact H.card_mul_index
    have hdvd : (2 : ℕ) ∣ orderOf g := by
      rw [hord]
      exact ⟨Nat.card ↥H, by omega⟩
    have hz : Nat.card ↥(Subgroup.zpowers (g ^ 2)) = Nat.card G / 2 := by
      rw [Nat.card_zpowers, orderOf_pow_of_dvd (by norm_num) hdvd, hord]
    refine (Subgroup.eq_of_le_of_card_ge hle ?_).symm
    omega
  rw [key H₁ h₁, key H₂ h₂]

/-- Two intermediate fields of degree two in a finite Galois extension whose Galois group is
cyclic coincide: their fixing subgroups have index two, and a cyclic group has only one such
subgroup. -/
theorem intermediateField_eq_of_finrank_eq_two {k E : Type*} [Field k] [Field E] [Algebra k E]
    [FiniteDimensional k E] [IsGalois k E] [IsCyclic Gal(E/k)] {F₁ F₂ : IntermediateField k E}
    (h₁ : Module.finrank k F₁ = 2) (h₂ : Module.finrank k F₂ = 2) : F₁ = F₂ := by
  have hidx : ∀ F : IntermediateField k E, F.fixingSubgroup.index = Module.finrank k F := by
    intro F
    rw [← finrank_fixedField_eq_index F.fixingSubgroup, IsGalois.fixedField_fixingSubgroup F]
  have hfix : F₁.fixingSubgroup = F₂.fixingSubgroup :=
    eq_of_index_eq_two ((hidx F₁).trans h₁) ((hidx F₂).trans h₂)
  rw [← IsGalois.fixedField_fixingSubgroup F₁, ← IsGalois.fixedField_fixingSubgroup F₂, hfix]

/-! ### The splitting law of the quadratic subfield -/

/-- **The quadratic subfield of a cyclotomic field of prime conductor, and its splitting law.**
Let `q` be an odd prime and let `r` be a square root of `q` inside a cyclotomic field of conductor
`q`.  Then `ℚ(r)` is a Galois extension of `ℚ`, unramified at every prime not above `q`, and a
rational prime `p ≠ q` splits completely in it exactly when `p` is a square modulo `q`. -/
theorem splitsCompletely_adjoin_sqrt_natCast {q : ℕ} [hq : Fact q.Prime] (hq2 : q ≠ 2)
    {E : Type*} [Field E] [NumberField E] [IsCyclotomicExtension {q} ℚ E] {r : E}
    (hr : r ^ 2 = (q : E)) :
    IsGalois ℚ ↥ℚ⟮r⟯ ∧
      (∀ p : ℕ, p.Prime → p ≠ q → (SplitsCompletely ↥ℚ⟮r⟯ p ↔ IsSquare ((p : ZMod q)))) ∧
      (∀ (Q : Ideal (𝓞 ↥ℚ⟮r⟯)) [Q.IsPrime], Q ≠ ⊥ → (q : 𝓞 ↥ℚ⟮r⟯) ∉ Q →
        Algebra.IsUnramifiedAt ℤ Q) := by
  haveI : NeZero q := ⟨hq.out.ne_zero⟩
  haveI : IsGalois ℚ E := IsCyclotomicExtension.isGalois {q} ℚ E
  haveI : IsCyclic (ZMod q)ˣ := ZMod.isCyclic_units_prime hq.out
  haveI : IsCyclic Gal(E/ℚ) :=
    isCyclic_of_surjective (Rat.galEquivZMod q E).symm (Rat.galEquivZMod q E).symm.surjective
  have hodd : Odd q := hq.out.odd_of_ne_two hq2
  have hdvd : 2 ∣ q - 1 := by
    obtain ⟨j, hj⟩ := hodd
    omega
  obtain ⟨F, hrank, hgal, hsplit, hunr, -⟩ :=
    exists_intermediateField_finrank_eq_prime_and_splitsCompletely q Nat.prime_two hdvd E
  have heq : (ℚ⟮r⟯ : IntermediateField ℚ E) = F :=
    intermediateField_eq_of_finrank_eq_two (finrank_adjoin_eq_two_of_sq_eq_natCast hq.out hr) hrank
  subst heq
  refine ⟨hgal, fun p hp hpq => ?_, hunr⟩
  haveI : Fact p.Prime := ⟨hp⟩
  have hne : ((p : ℕ) : ZMod q) ≠ 0 := ZMod.prime_ne_zero q p (Ne.symm hpq)
  have hhalf : (q - 1) / 2 = q / 2 := by
    obtain ⟨j, hj⟩ := hodd
    omega
  rw [hsplit p hp hpq, ZMod.euler_criterion q hne, hhalf]

/-- The splitting law of the quadratic subfield in its reciprocal form.  For a prime `q` congruent
to `1` modulo `4` and an odd prime `p ≠ q`, the field generated by a square root of `q` inside a
cyclotomic field of conductor `q` splits `p` completely exactly when `q` is a square modulo `p`. -/
theorem splitsCompletely_adjoin_sqrt_natCast_iff_isSquare_symm {q : ℕ} [Fact q.Prime]
    (hq4 : q % 4 = 1) {E : Type*} [Field E] [NumberField E] [IsCyclotomicExtension {q} ℚ E]
    {r : E} (hr : r ^ 2 = (q : E)) {p : ℕ} (hp : p.Prime) (hp2 : p ≠ 2) (hpq : p ≠ q) :
    SplitsCompletely ↥ℚ⟮r⟯ p ↔ IsSquare ((q : ZMod p)) := by
  haveI : Fact p.Prime := ⟨hp⟩
  have hq2 : q ≠ 2 := by omega
  have hpz : ((p : ℕ) : ZMod q) ≠ 0 := ZMod.prime_ne_zero q p (Ne.symm hpq)
  have hqz : ((q : ℕ) : ZMod p) ≠ 0 := ZMod.prime_ne_zero p q hpq
  rw [(splitsCompletely_adjoin_sqrt_natCast hq2 hr).2.1 p hp hpq, ← legendreSym.eq_one_iff' q hpz,
    ← legendreSym.eq_one_iff' p hqz, legendreSym.quadratic_reciprocity_one_mod_four hq4 hp2]

end InverseGalois.CFT
