/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.PoitouTate.FrobeniusCharacter
import InverseGalois.CFT.RelativeFrobeniusBase
import InverseGalois.CFT.Units.FrobeniusPlace

/-!
# A finite place whose Frobenius character is prescribed by an automorphism

An automorphism of prime order of a Galois extension of number fields, generating a subgroup normal
in the automorphisms of an intermediate field, is the decomposition group over the base at
infinitely many primes.  Stated for the ideals of the ring of integers, that assertion is turned
here into one about the finite places, which is the form in which the norm residue symbol and the
value at a Frobenius automorphism are written.

The construction runs over a tower of four fields, because the prime is asked to split completely
in the intermediate field of the third floor while its Frobenius is prescribed over the second: an
automorphism of the top field fixing the third floor generates the decomposition group over the
first, and the decomposition group over the second is the preimage of that one, so it is generated
by the same automorphism read over the second floor.

Combined with the identification of the units whose value at the Frobenius automorphism of a place
is trivial, this produces, outside any prescribed finite set of places of the base, a place at
which that value is trivial exactly at the units one of whose radicals the given automorphism
fixes.  The places whose residue characteristic is the exponent are finite in number, so they too
can be avoided, and the identification applies at the place produced.

Reading the residue characteristic of a place off a completion of the number field is the small
piece of bookkeeping this needs: a rational prime is the residue characteristic of a completion
exactly when the place lies over it, because its valuation there is then less than one.

The trivial automorphism is left out by the construction above, which asks the prescribed
automorphism to have prime order, and it is reached separately.  Infinitely many primes of the base
split completely in a Galois extension, so one of them avoids any prescribed finite set; a prime
above such a one is unramified of residue degree one, which is to say that its decomposition group
is trivial, and then every unit with a radical in the extension is a power in the completion, so
its value at the Frobenius automorphism is trivial.

## Main results

* `InverseGalois.CFT.resChar_eq_of_hasResidueChar`: the residue characteristic of a completion is
  the residue characteristic of the place.
* `InverseGalois.CFT.resChar_primeUnder`: the residue characteristic is unchanged on passing to the
  prime below.
* `InverseGalois.CFT.stabilizer_eq_zpowers_restrictScalars_of_base`: **a decomposition group over
  the base generated by an automorphism of the top field is generated over an intermediate field by
  the same automorphism.**
* `InverseGalois.CFT.exists_relStabilizer_place_eq_zpowers_restrictScalars`: **an element of prime
  order generating a subgroup normal in the automorphisms of the third floor of a tower is the
  decomposition group at a finite place, over the first floor and over the second at once**,
  avoiding any prescribed finite set of places of the first floor.
* `InverseGalois.CFT.exists_place_placeFrobValue_eq_one_iff_smul_eq`: **the value at the Frobenius
  automorphism of that place is trivial exactly at the units whose radicals the given automorphism
  fixes.**
* `InverseGalois.CFT.exists_stabilizer_eq_bot`: **a Galois extension has, above a prime of the base
  avoiding any prescribed finite set, a prime with trivial decomposition group.**
* `InverseGalois.CFT.exists_place_placeFrobValue_eq_one_of_split`: **at such a place the value at
  the Frobenius automorphism is trivial at every unit with a radical in the extension.**

## Tags

Frobenius, decomposition group, Chebotarev, finite place, residue characteristic, Kummer theory
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField InverseGalois.NumberTheory

open scoped Pointwise

/-! ### The residue characteristic of a completion -/

section ResidueChar

variable {K : Type*} [Field K] [NumberField K]

/-- **A rational prime is the residue characteristic of a completion of a number field exactly when
the place lies over it.**  Its valuation in the completion is less than one, so it lies in the
place, hence is divisible by the residue characteristic; both are prime. -/
theorem resChar_eq_of_hasResidueChar {p e : ℕ} {v : HeightOneSpectrum (𝓞 K)}
    (h : HasResidueChar (v.adicCompletion K) p e) : resChar v = p := by
  have hval : Valued.v ((p : ℕ) : v.adicCompletion K)
      = v.valuation K (algebraMap (𝓞 K) K ((p : ℕ) : 𝓞 K)) := by
    rw [← map_natCast (algebraMap (𝓞 K) (v.adicCompletion K)) p,
      HeightOneSpectrum.valuedAdicCompletion_eq_valuation]
  have hmem : ((p : ℕ) : 𝓞 K) ∈ v.asIdeal :=
    (HeightOneSpectrum.valuation_lt_one_iff_mem v _).mp
      (hval ▸ valued_residueChar_lt_one h)
  have hunder : Ideal.span {((resChar v : ℕ) : ℤ)} = Ideal.under ℤ v.asIdeal :=
    (liesOver_resChar v).over
  have hpmem : ((p : ℕ) : ℤ) ∈ Ideal.span {((resChar v : ℕ) : ℤ)} := by
    rw [hunder]
    exact Ideal.mem_comap.mpr (by simpa using hmem)
  have hdvd : resChar v ∣ p := by
    have := Ideal.mem_span_singleton.mp hpmem
    exact_mod_cast this
  exact (Nat.prime_dvd_prime_iff_eq (resChar_prime v) h.prime).mp hdvd

end ResidueChar

/-! ### The residue characteristic of the prime below -/

section Below

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]

/-- **The residue characteristic is unchanged on passing to the prime below**: both primes lie over
the same rational prime. -/
theorem resChar_primeUnder (v : HeightOneSpectrum (𝓞 K)) :
    resChar (primeUnder (𝓞 k) v) = resChar v := by
  haveI : v.asIdeal.LiesOver (Ideal.span {((resChar v : ℕ) : ℤ)}) := liesOver_resChar v
  haveI : v.asIdeal.LiesOver (primeUnder (𝓞 k) v).asIdeal := ⟨rfl⟩
  haveI := Ideal.LiesOver.tower_bot v.asIdeal (primeUnder (𝓞 k) v).asIdeal
    (Ideal.span {((resChar v : ℕ) : ℤ)})
  exact resChar_eq_of_liesOver (resChar_prime v) _

end Below

/-! ### The decomposition group over an intermediate field -/

section Restrict

variable {k K F N : Type*} [Field k] [Field K] [Field F] [Field N]
  [Algebra k K] [Algebra k F] [Algebra k N] [Algebra K F] [Algebra K N] [Algebra F N]
  [IsScalarTower k K N] [IsScalarTower k F N] [IsScalarTower K F N]

/-- Restricting scalars twice along a tower is restricting scalars to the bottom. -/
theorem restrictScalars_restrictScalars (σ : Gal(N/F)) :
    (σ.restrictScalars K).restrictScalars k = σ.restrictScalars k :=
  AlgEquiv.ext fun _ => rfl

/-- The decomposition group over an intermediate field is the preimage of the decomposition group
over the base. -/
theorem comap_relRestrictScalarsHom_stabilizer (Q : Ideal (𝓞 N)) :
    Subgroup.comap (relRestrictScalarsHom (F := K) (N := N) k) (stabilizer Gal(N/k) Q)
      = stabilizer Gal(N/K) Q := by
  ext τ
  rw [Subgroup.mem_comap, mem_stabilizer_iff, mem_stabilizer_iff, relRestrictScalarsHom_apply,
    relRestrictScalars_smul_ideal]

/-- **A decomposition group over the base generated by an automorphism of the top field fixing an
intermediate field is generated, over any intermediate field of the tower, by that same
automorphism.**  Restriction of scalars is injective, so the preimage of the group it generates is
the group generated by its preimage. -/
theorem stabilizer_eq_zpowers_restrictScalars_of_base {Q : Ideal (𝓞 N)} {σ : Gal(N/F)}
    (h : stabilizer Gal(N/k) Q = Subgroup.zpowers (σ.restrictScalars k)) :
    stabilizer Gal(N/K) Q = Subgroup.zpowers (σ.restrictScalars K) := by
  have hσ : σ.restrictScalars k
      = relRestrictScalarsHom (F := K) (N := N) k (σ.restrictScalars K) :=
    (restrictScalars_restrictScalars σ).symm
  rw [← comap_relRestrictScalarsHom_stabilizer (k := k) (K := K) Q, h, hσ,
    ← MonoidHom.map_zpowers,
    Subgroup.comap_map_eq_self_of_injective relRestrictScalarsHom_injective]

end Restrict

/-! ### The decomposition group at a finite place -/

section Place

variable {k K F N : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Field F]
  [NumberField F] [Field N] [NumberField N] [Algebra k K] [Algebra k F] [Algebra k N]
  [Algebra K F] [Algebra K N] [Algebra F N] [IsScalarTower k K N] [IsScalarTower k F N]
  [IsScalarTower K F N] [IsGalois k N]

omit [NumberField K] in
/-- **An element of prime order generating a subgroup normal in the automorphisms of the third
floor of a tower of number fields is the decomposition group at a finite place of the top field,
over the first floor and over the second at once.**  The place produced lies over a prime of the
first floor avoiding a prescribed finite set and unramified at the top. -/
theorem exists_relStabilizer_place_eq_zpowers_restrictScalars {σ : Gal(N/F)}
    (hnorm : (Subgroup.zpowers σ).Normal) (hp : (orderOf σ).Prime)
    (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ W : HeightOneSpectrum (𝓞 N), primeUnder (𝓞 k) W ∉ T ∧
      primeUnder (𝓞 k) W ∉ relRamifiedSet k N ∧
      stabilizer Gal(N/k) W = Subgroup.zpowers (σ.restrictScalars k) ∧
      stabilizer Gal(N/K) W = Subgroup.zpowers (σ.restrictScalars K) := by
  obtain ⟨v, hvT, hvram, hvdeg, Q, hQprime, hQover, hQfin, hstab, hfrob⟩ :=
    exists_relStabilizer_eq_zpowers_restrictScalars (k := k) (F := F) (N := N) hnorm hp T
  haveI := hQprime
  haveI := hQover
  have hQ0 : Q ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot v.ne_bot Q
  have hunder : primeUnder (𝓞 k) (⟨Q, hQprime, hQ0⟩ : HeightOneSpectrum (𝓞 N)) = v :=
    HeightOneSpectrum.ext (Ideal.LiesOver.over (A := 𝓞 k) (P := Q) (p := v.asIdeal)).symm
  refine ⟨⟨Q, hQprime, hQ0⟩, ?_, ?_, ?_, ?_⟩
  · rw [hunder]; exact hvT
  · rw [hunder]; exact hvram
  · rw [stabilizer_eq_stabilizer_asIdeal]; exact hstab
  · rw [stabilizer_eq_stabilizer_asIdeal]
    exact stabilizer_eq_zpowers_restrictScalars_of_base (k := k) (K := K) (F := F) (N := N) hstab

end Place

/-! ### A place at which the Frobenius character is prescribed -/

section Prescribe

variable {k K F N : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Field F]
  [NumberField F] [Field N] [NumberField N] [Algebra k K] [Algebra k F] [Algebra k N]
  [Algebra K F] [Algebra K N] [Algebra F N] [IsScalarTower k K N] [IsScalarTower k F N]
  [IsScalarTower K F N] [IsGalois k N] {n : ℕ} [NeZero n]
  {P E : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **Above any prescribed finite set of finite places of the base there is a place of the top field
at which the value at the Frobenius automorphism is trivial exactly at the units one of whose
radicals a prescribed automorphism fixes.**  The automorphism is of prime order and generates a
subgroup normal in the automorphisms of the third floor, so it is the decomposition group there;
the places whose residue characteristic is the exponent are finite in number and can be avoided
along with the prescribed set, which puts the place in the range of the Kummer description of the
units that are powers in its completion. -/
theorem exists_place_placeFrobValue_eq_one_iff_smul_eq (hn : n.Prime)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (P v) (E v))
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) {σ : Gal(N/F)}
    (hnorm : (Subgroup.zpowers σ).Normal) (hp : (orderOf σ).Prime)
    (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ W : HeightOneSpectrum (𝓞 N), primeUnder (𝓞 k) W ∉ T ∧
      primeUnder (𝓞 k) W ∉ relRamifiedSet k N ∧
      stabilizer Gal(N/k) W = Subgroup.zpowers (σ.restrictScalars k) ∧
      ¬ P (primeUnder (𝓞 K) W) ∣ n ∧
      ∀ u : Kˣ, (n : ℤ) ∣ placeValue (primeUnder (𝓞 K) W) u →
        ∀ b : N, b ^ n = algebraMap K N (u : K) →
          (placeFrobValue hres hζ (primeUnder (𝓞 K) W) u = 1 ↔ (σ.restrictScalars K) b = b) := by
  classical
  haveI : IsGalois K N := IsGalois.tower_top_of_isGalois k K N
  have hfib : (resChar ⁻¹' {n} : Set (HeightOneSpectrum (𝓞 k))).Finite := Set.toFinite _
  obtain ⟨W, hWT, hWram, hWk, hWK⟩ :=
    exists_relStabilizer_place_eq_zpowers_restrictScalars (K := K) hnorm hp (T ∪ hfib.toFinset)
  rw [Finset.mem_union, not_or] at hWT
  obtain ⟨hWT, hWn⟩ := hWT
  have hPn : ¬ P (primeUnder (𝓞 K) W) ∣ n := by
    intro hdvd
    refine hWn (hfib.mem_toFinset.mpr ?_)
    have h1 : resChar (primeUnder (𝓞 K) W) = P (primeUnder (𝓞 K) W) :=
      resChar_eq_of_hasResidueChar (hres _)
    have h2 : P (primeUnder (𝓞 K) W) = n :=
      (Nat.prime_dvd_prime_iff_eq (hres _).prime hn).mp hdvd
    show resChar (primeUnder (𝓞 k) W) = n
    rw [resChar_primeUnder (k := k) W, ← resChar_primeUnder (k := K) W, h1, h2]
  exact ⟨W, hWT, hWram, hWk, hPn,
    fun u hu b hb => placeFrobValue_eq_one_iff_smul_eq hn hres hζ hPn hWK hu hb⟩

end Prescribe

/-! ### A place with trivial decomposition group -/

section Split

variable {k N : Type*} [Field k] [NumberField k] [Field N] [NumberField N] [Algebra k N]
  [IsGalois k N]

/-- **Above a prime of the base avoiding any prescribed finite set, a Galois extension of number
fields has a prime with trivial decomposition group.**  Infinitely many primes of the base split
completely in the extension, so one of them avoids the prescribed set; the primes above it are
unramified of residue degree one, which is exactly the triviality of their decomposition group. -/
theorem exists_stabilizer_eq_bot (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ W : HeightOneSpectrum (𝓞 N), primeUnder (𝓞 k) W ∉ T ∧
      MulAction.stabilizer Gal(N/k) W = ⊥ := by
  obtain ⟨v, hv, hvT⟩ := (infinite_relSplitSet (k := k) (L := N)).exists_notMem_finset T
  have hcard := card_relFiber_eq_of_splitsCompletelyIn (k := k) (L := N) hv
  have hnonempty : Nonempty ↥(primeBelow k ⁻¹' {v} : Set (HeightOneSpectrum (𝓞 N))) :=
    (Nat.card_ne_zero.mp (by
      rw [hcard]
      exact (Module.finrank_pos (R := k) (M := N)).ne')).1
  obtain ⟨⟨W, hWmem⟩⟩ := hnonempty
  have hW : primeBelow k W = v := hWmem
  have hunder : primeUnder (𝓞 k) W = v := HeightOneSpectrum.ext
    (congrArg HeightOneSpectrum.asIdeal hW)
  refine ⟨W, by rw [hunder]; exact hvT, ?_⟩
  haveI : W.asIdeal.IsPrime := W.isPrime
  haveI : W.asIdeal.LiesOver v.asIdeal := ⟨(congrArg HeightOneSpectrum.asIdeal hW).symm⟩
  obtain ⟨he, hf⟩ := hv W.asIdeal ⟨W.isPrime, inferInstance⟩
  rw [stabilizer_eq_stabilizer_asIdeal, relStabilizer_eq_bot_iff W.asIdeal W.ne_bot,
    show W.asIdeal.under (𝓞 k) = v.asIdeal from congrArg HeightOneSpectrum.asIdeal hW]
  exact ⟨he, hf⟩

end Split

/-! ### The Frobenius character of a completely split place -/

section SplitPrescribe

variable {k K N : Type} [Field k] [NumberField k] [Field K] [NumberField K] [Field N]
  [NumberField N] [Algebra k K] [Algebra k N] [Algebra K N] [IsScalarTower k K N] [IsGalois k N]
  {n : ℕ} [NeZero n] {P E : HeightOneSpectrum (𝓞 K) → ℕ}

omit [NumberField k] [NumberField K] [NumberField N] [IsGalois k N] in
/-- The decomposition group over an intermediate field of a prime with trivial decomposition group
over the base is trivial, because restriction of scalars is injective. -/
theorem stabilizer_eq_bot_of_base {W : HeightOneSpectrum (𝓞 N)}
    (hW : MulAction.stabilizer Gal(N/k) W = ⊥) : MulAction.stabilizer Gal(N/K) W = ⊥ := by
  rw [stabilizer_eq_stabilizer_asIdeal] at hW ⊢
  refine (Subgroup.eq_bot_iff_forall _).2 fun τ hτ => ?_
  have h1 : τ.restrictScalars k ∈ MulAction.stabilizer Gal(N/k) W.asIdeal := by
    rw [MulAction.mem_stabilizer_iff, relRestrictScalars_smul_ideal]
    exact hτ
  rw [hW, Subgroup.mem_bot] at h1
  exact AlgEquiv.restrictScalars_injective k (h1.trans (AlgEquiv.ext fun _ => rfl).symm)

/-- **Above any prescribed finite set of finite places of the base there is a place of the top
field, with trivial decomposition group, at which the value at the Frobenius automorphism is
trivial at every unit with a radical in the top field.**  The places whose residue characteristic
is the exponent are finite in number and can be avoided along with the prescribed set, which puts
the place in the range of the Kummer description of the units that are powers in its completion;
a trivial decomposition group fixes every radical. -/
theorem exists_place_placeFrobValue_eq_one_of_split (hn : n.Prime)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (P v) (E v))
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ W : HeightOneSpectrum (𝓞 N), primeUnder (𝓞 k) W ∉ T ∧
      MulAction.stabilizer Gal(N/k) W = ⊥ ∧ ¬ P (primeUnder (𝓞 K) W) ∣ n ∧
      ∀ u : Kˣ, (n : ℤ) ∣ placeValue (primeUnder (𝓞 K) W) u →
        ∀ b : N, b ^ n = algebraMap K N (u : K) →
          placeFrobValue hres hζ (primeUnder (𝓞 K) W) u = 1 := by
  classical
  haveI : IsGalois K N := IsGalois.tower_top_of_isGalois k K N
  have hfib : (resChar ⁻¹' {n} : Set (HeightOneSpectrum (𝓞 k))).Finite := Set.toFinite _
  obtain ⟨W, hWT, hWk⟩ := exists_stabilizer_eq_bot (N := N) (T ∪ hfib.toFinset)
  rw [Finset.mem_union, not_or] at hWT
  obtain ⟨hWT, hWn⟩ := hWT
  have hPn : ¬ P (primeUnder (𝓞 K) W) ∣ n := by
    intro hdvd
    refine hWn (hfib.mem_toFinset.mpr ?_)
    have h1 : resChar (primeUnder (𝓞 K) W) = P (primeUnder (𝓞 K) W) :=
      resChar_eq_of_hasResidueChar (hres _)
    have h2 : P (primeUnder (𝓞 K) W) = n :=
      (Nat.prime_dvd_prime_iff_eq (hres _).prime hn).mp hdvd
    show resChar (primeUnder (𝓞 k) W) = n
    rw [resChar_primeUnder (k := k) W, ← resChar_primeUnder (k := K) W, h1, h2]
  refine ⟨W, hWT, hWk, hPn, fun u hu b hb => ?_⟩
  rw [placeFrobValue_eq_one_iff_forall_stabilizer_smul_eq hn hres hζ W hPn hu hb]
  intro σ
  have hσ : (σ : Gal(N/K)) = 1 :=
    (Subgroup.eq_bot_iff_forall _).1 (stabilizer_eq_bot_of_base (k := k) hWk) _ σ.2
  rw [hσ]
  rfl

end SplitPrescribe

end InverseGalois.CFT
