/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.PrescribedValue
import InverseGalois.CFT.PoitouTate.SUnitReduce
import InverseGalois.CFT.Units.ClassSet

/-!
# Carrying the ideal classes away from a prescribed set of primes

A finite set of primes supports the ideal classes of a number field, in the sense that away from it
every finitely supported system of orders is realised by an element of the field.  The set is built
from one chosen fractional ideal in each class, so it depends on the choice, and nothing so far
prevents it from meeting a set of primes that some other part of a construction has already spoken
for.

The choice can be corrected.  Multiplying a representative by a principal ideal does not change its
class, and an element of the field can be prescribed arbitrary orders at finitely many places; so
each representative may be moved until it has no exponent at any prime of the forbidden set.  The
supporting set built from the corrected representatives is then disjoint from the forbidden one.
Taking the union of the translates of the result makes it stable under a finite group of
automorphisms, and disjointness survives as long as the forbidden set is stable too.

## Main results

* `InverseGalois.CFT.exists_finite_ord_repr_disjoint`: **the finite set of primes supporting the
  ideal classes can be chosen to avoid any prescribed finite set of primes.**
* `InverseGalois.CFT.exists_finite_stable_ord_repr_disjoint`: the same set can in addition be taken
  stable under a finite group of automorphisms, provided the prescribed set is.

## Tags

class group, fractional ideal, prescribed order, number field, place
-/

namespace InverseGalois.CFT

open FractionalIdeal IsDedekindDomain NumberField Rigidity.RET

open scoped nonZeroDivisors

/-! ### Moving the representatives off a finite set -/

section Avoid

variable (K : Type) [Field K] [NumberField K]

/-- **The finite set of primes supporting the ideal classes can be chosen to avoid any prescribed
finite set of primes.**  Each chosen representative of an ideal class is multiplied by the principal
ideal generated by an element whose orders on the prescribed set are the negatives of the exponents
of the representative there; the corrected representative lies in the same class and has no exponent
on the prescribed set. -/
theorem exists_finite_ord_repr_disjoint (E : Finset (HeightOneSpectrum (𝓞 K))) :
    ∃ X : Set (HeightOneSpectrum (𝓞 K)), X.Finite ∧ (∀ v ∈ X, v ∉ E) ∧
      ∀ n : HeightOneSpectrum (𝓞 K) → ℤ,
        (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) →
        ∃ a : Kˣ, ∀ v ∉ X, ord K v (a : K) = n v := by
  classical
  obtain ⟨rep0, hrep0⟩ := exists_rep_quotient K
  have hx : ∀ q, ∃ x : Kˣ, ∀ v ∈ E,
      ord K v (x : K) = -FractionalIdeal.count K v (rep0 q : FractionalIdeal (𝓞 K)⁰ K) := by
    intro q
    obtain ⟨x, hxv⟩ := exists_units_placeValue_eq E
      (fun v => FractionalIdeal.count K v (rep0 q : FractionalIdeal (𝓞 K)⁰ K))
    refine ⟨x, fun v hv => ?_⟩
    have h := hxv v hv
    rw [placeValue_eq_neg_ord] at h
    omega
  choose x hx using hx
  obtain ⟨rep, hrepapp⟩ : ∃ rep : _ → (FractionalIdeal (𝓞 K)⁰ K)ˣ,
      ∀ q, rep q = rep0 q * toPrincipalIdeal (𝓞 K) K (x q) :=
    ⟨fun q => rep0 q * toPrincipalIdeal (𝓞 K) K (x q), fun _ => rfl⟩
  have hrep : ∀ q, QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range (rep q) = q := by
    intro q
    have h1 : QuotientGroup.mk' (toPrincipalIdeal (𝓞 K) K).range
        (toPrincipalIdeal (𝓞 K) K (x q)) = 1 :=
      (QuotientGroup.eq_one_iff _).2 (MonoidHom.mem_range.2 ⟨x q, rfl⟩)
    rw [hrepapp, _root_.map_mul, hrep0, h1, mul_one]
  have hcount : ∀ q v, FractionalIdeal.count K v (rep q : FractionalIdeal (𝓞 K)⁰ K)
      = FractionalIdeal.count K v (rep0 q : FractionalIdeal (𝓞 K)⁰ K) + ord K v (x q : K) := by
    intro q v
    rw [hrepapp, Units.val_mul, coe_toPrincipalIdeal,
      FractionalIdeal.count_mul K v (Units.ne_zero (rep0 q))
        (spanSingleton_ne_zero_iff.mpr (Units.ne_zero (x q))), ord_def]
  refine ⟨⋃ q, {v | FractionalIdeal.count K v (rep q : FractionalIdeal (𝓞 K)⁰ K) ≠ 0}, ?_, ?_,
    fun n hn => ?_⟩
  · exact Set.finite_iUnion fun q =>
      Filter.eventually_cofinite.mp (FractionalIdeal.finite_factors _)
  · rintro v hv hvE
    obtain ⟨q, hq⟩ := Set.mem_iUnion.mp hv
    exact hq (by rw [hcount q v, hx q v hvE]; ring)
  · obtain ⟨a, ha⟩ := exists_ord_repr_of_forall_count K rep hrep n hn
    exact ⟨a, fun v hv => ha v fun q => not_not.1 fun hc => hv (Set.mem_iUnion.mpr ⟨q, hc⟩)⟩

end Avoid

/-! ### Making the disjoint set invariant -/

section Stable

variable {k : Type*} {K : Type} [Field k] [Field K] [NumberField K] [Algebra k K]
  [Finite Gal(K/k)]

/-- **A finite set of primes, stable under the Galois group and disjoint from a prescribed stable
set, away from which every finitely supported system of orders is realised by an element of the
field.**  The union of the translates of a set avoiding the prescribed one still avoids it, because
the prescribed set is carried into itself by every automorphism and by every inverse. -/
theorem exists_finite_stable_ord_repr_disjoint (E : Finset (HeightOneSpectrum (𝓞 K)))
    (hE : ∀ (g : Gal(K/k)) (v : HeightOneSpectrum (𝓞 K)), v ∈ E → g • v ∈ E) :
    ∃ X : Set (HeightOneSpectrum (𝓞 K)), X.Finite ∧
      (∀ (g : Gal(K/k)) (v : HeightOneSpectrum (𝓞 K)), g • v ∈ X ↔ v ∈ X) ∧
      (∀ v ∈ X, v ∉ E) ∧
      ∀ n : HeightOneSpectrum (𝓞 K) → ℤ,
        (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, n v = 0) →
        ∃ a : Kˣ, ∀ v ∉ X, ord K v (a : K) = n v := by
  obtain ⟨X, hXfin, hXE, hXrepr⟩ := exists_finite_ord_repr_disjoint K E
  refine ⟨⋃ g : Gal(K/k), (fun v => g • v) '' X, Set.finite_iUnion fun g => hXfin.image _,
    fun g v => ?_, ?_, fun n hn => ?_⟩
  · constructor
    · rintro hgv
      obtain ⟨s, w, hw, hwv⟩ := Set.mem_iUnion.mp hgv
      refine Set.mem_iUnion.mpr ⟨g⁻¹ * s, w, hw, ?_⟩
      show (g⁻¹ * s) • w = v
      rw [mul_smul, show s • w = g • v from hwv, inv_smul_smul]
    · rintro hv
      obtain ⟨s, w, hw, hwv⟩ := Set.mem_iUnion.mp hv
      refine Set.mem_iUnion.mpr ⟨g * s, w, hw, ?_⟩
      show (g * s) • w = g • v
      rw [mul_smul, show s • w = v from hwv]
  · rintro v hv hvE
    obtain ⟨g, w, hw, hwv⟩ := Set.mem_iUnion.mp hv
    refine hXE w hw ?_
    have hgv : g⁻¹ • v ∈ E := hE g⁻¹ v hvE
    rwa [← show g • w = v from hwv, inv_smul_smul] at hgv
  · obtain ⟨a, ha⟩ := hXrepr n hn
    exact ⟨a, fun v hv => ha v fun hvX =>
      hv (Set.mem_iUnion.mpr ⟨1, v, hvX, one_smul _ v⟩)⟩

end Stable

end InverseGalois.CFT
