/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Brauer.SymbolReciprocity
import InverseGalois.CFT.Kummer.DecompositionLocalPower
import InverseGalois.CFT.Kummer.LocalPower

/-!
# The Frobenius character of a finite place and the radicals it fixes

The value at the Frobenius automorphism of a finite place is multiplicative in the unit it is
taken of, so it is a character of the units of a number field, with values in the elements of the
rationals modulo the integers killed by the exponent.

Kummer theory identifies where that character is trivial.  A unit whose value at the place the
exponent divides is a power in the completion exactly when the decomposition group at a prime
above it, in an extension containing a radical of the unit, fixes that radical; and the value at
the Frobenius automorphism of such a unit is trivial exactly when the unit is a power in the
completion.  So the character is trivial at the unit exactly when the decomposition group fixes
the radical, and, when the decomposition group is generated by a single automorphism, exactly when
that automorphism fixes the radical.

## Main definitions

* `InverseGalois.CFT.placeFrobValueHom`: **the character of the units given by the value at the
  Frobenius automorphism** of a finite place.

## Main results

* `InverseGalois.CFT.placeFrobValue_eq_one_iff_forall_stabilizer_smul_eq`: **the value at the
  Frobenius automorphism is trivial exactly when the decomposition group above the place fixes a
  radical of the unit.**
* `InverseGalois.CFT.placeFrobValue_eq_one_iff_smul_eq`: **the same for a decomposition group
  generated by a single automorphism.**

## Tags

Frobenius, character, Kummer theory, decomposition group, radical, number field
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

/-! ### The Frobenius character -/

section Character

variable {K : Type} [Field K] [NumberField K] {n : ℕ} [NeZero n]
  {P E : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **The character of the units of a number field given by the value at the Frobenius
automorphism of a finite place.** -/
noncomputable def placeFrobValueHom (hres : ∀ v : HeightOneSpectrum (𝓞 K),
    HasResidueChar (v.adicCompletion K) (P v) (E v)) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (v : HeightOneSpectrum (𝓞 K)) : Kˣ →* Multiplicative QModZ :=
  (frobValue (hres v) (isUnitValGen_one (valued_adicCompletion_surjective v))
      (hζ.map_of_injective (algebraMap K (v.adicCompletion K)).injective)).comp
    (Units.map (algebraMap K (v.adicCompletion K)).toMonoidHom)

@[simp]
theorem placeFrobValueHom_apply (hres : ∀ v : HeightOneSpectrum (𝓞 K),
    HasResidueChar (v.adicCompletion K) (P v) (E v)) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (v : HeightOneSpectrum (𝓞 K)) (a : Kˣ) :
    placeFrobValueHom hres hζ v a = placeFrobValue hres hζ v a := rfl

/-- The Frobenius character is killed by the exponent. -/
theorem pow_placeFrobValueHom_eq_one (hres : ∀ v : HeightOneSpectrum (𝓞 K),
    HasResidueChar (v.adicCompletion K) (P v) (E v)) {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (v : HeightOneSpectrum (𝓞 K)) (a : Kˣ) : placeFrobValueHom hres hζ v a ^ n = 1 :=
  pow_placeFrobValue_eq_one hres hζ v a

end Character

/-! ### The radicals fixed by a decomposition group -/

section Radical

variable {K M : Type} [Field K] [NumberField K] [Field M] [NumberField M] [Algebra K M]
  [IsGalois K M] {n : ℕ} [NeZero n] {P E : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **The value at the Frobenius automorphism of a finite place, of a unit whose value there the
exponent divides, is trivial exactly when the decomposition group at a prime above the place, in
an extension containing a radical of the unit, fixes that radical.**  Both say that the unit is a
power in the completion at the place. -/
theorem placeFrobValue_eq_one_iff_forall_stabilizer_smul_eq (hn : n.Prime)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (P v) (E v))
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (w : HeightOneSpectrum (𝓞 M))
    (hw : ¬ P (primeUnder (𝓞 K) w) ∣ n) {u : Kˣ}
    (hu : (n : ℤ) ∣ placeValue (primeUnder (𝓞 K) w) u) {b : M}
    (hb : b ^ n = algebraMap K M (u : K)) :
    placeFrobValue hres hζ (primeUnder (𝓞 K) w) u = 1
      ↔ ∀ σ : ↥(stabilizer Gal(M/K) w), (σ : Gal(M/K)) b = b := by
  rw [placeFrobValue_eq_one_iff hn hres hζ hw hu,
    forall_stabilizer_smul_eq_iff_exists_pow w hζ hn.ne_zero hb.symm]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨(c : (primeUnder (𝓞 K) w).adicCompletion K), ?_⟩
    rw [← Units.val_pow_eq_pow_val, hc, Units.coe_map]
    rfl
  · rintro ⟨c, hc⟩
    refine exists_units_pow_eq_of_pow_eq_coe hn.ne_zero (c := c) ?_
    rw [Units.coe_map]
    exact hc

/-- **The value at the Frobenius automorphism of a finite place, of a unit whose value there the
exponent divides, is trivial exactly when a generator of the decomposition group at a prime above
the place fixes a radical of the unit.**  The automorphisms fixing the radical form a subgroup, so
it is enough that the generator fix it. -/
theorem placeFrobValue_eq_one_iff_smul_eq (hn : n.Prime)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (P v) (E v))
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) {w : HeightOneSpectrum (𝓞 M)}
    (hw : ¬ P (primeUnder (𝓞 K) w) ∣ n) {σ : Gal(M/K)}
    (hstab : stabilizer Gal(M/K) w = Subgroup.zpowers σ) {u : Kˣ}
    (hu : (n : ℤ) ∣ placeValue (primeUnder (𝓞 K) w) u) {b : M}
    (hb : b ^ n = algebraMap K M (u : K)) :
    placeFrobValue hres hζ (primeUnder (𝓞 K) w) u = 1 ↔ σ b = b := by
  rw [placeFrobValue_eq_one_iff_forall_stabilizer_smul_eq hn hres hζ w hw hu hb]
  constructor
  · intro h
    exact h ⟨σ, by rw [hstab]; exact Subgroup.mem_zpowers σ⟩
  · intro h τ
    have hle : stabilizer Gal(M/K) w ≤ stabilizer Gal(M/K) b := by
      rw [hstab, Subgroup.zpowers_le]
      exact h
    exact hle τ.2

end Radical

end InverseGalois.CFT
