/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.RadicalAut
import InverseGalois.CFT.Kummer.RadicalNormal
import InverseGalois.CFT.PoitouTate.ChebotarevPlace
import InverseGalois.CFT.Units.IdeleNormTower
import InverseGalois.CFT.Units.PlaceRestrict

/-!
# A finite place prescribed by a character of a group of units

A character of a group of units of a number field, trivial on the powers of exponent a prime that
the group contains, is realised by an automorphism of the extension generated by radicals of the
group; the extension is normal over any subfield over which the group is stable, and its
automorphisms over the field the radicals are taken from commute and are killed by the exponent.
So the automorphism has prime order and generates a normal subgroup, which is exactly the input of
the Chebotarev construction of a finite place with a prescribed decomposition group.

Feeding one into the other produces, outside any prescribed finite set of finite places of the
bottom field, a finite place at which the value at the Frobenius automorphism is trivial exactly at
the units the character kills.  The place is completely split in the field the radicals are taken
from: the automorphism fixes that field, so the decomposition group there is trivial, an assertion
about the bottom two floors of the tower which no longer mentions the radicals.

The last point is the only one needing an argument.  A decomposition group upstairs restricts into
the decomposition group downstairs, and the restriction is onto because every automorphism of the
middle field lifts to the top and the automorphisms over the middle field permute the places above
a given one transitively.

## Main results

* `InverseGalois.CFT.stabilizer_eq_bot_of_stabilizer_eq_zpowers`: **a place whose decomposition
  group over the bottom field is generated by an automorphism over the middle field is completely
  split in the middle field.**
* `InverseGalois.CFT.exists_aut_ambientRadField_of_character`: **a non-trivial character of a
  subgroup of units, trivial on the powers it contains, is realised by an automorphism of prime
  order generating a normal subgroup.**
* `InverseGalois.CFT.exists_place_placeFrobValue_eq_one_iff_character`: **outside any prescribed
  finite set of places of the bottom field there is a completely split place at which the value at
  the Frobenius automorphism is trivial exactly at the units the character kills.**

## Tags

Kummer theory, radical extension, Frobenius, decomposition group, Chebotarev, completely split
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### Complete splitting in the middle field of a tower -/

section Split

variable {k F N : Type*} [Field k] [NumberField k] [Field F] [NumberField F] [Field N]
  [NumberField N] [Algebra k F] [Algebra k N] [Algebra F N] [IsScalarTower k F N]
  [IsGalois k F] [IsGalois k N]

omit [NumberField k] in
/-- **A place whose decomposition group over the bottom field is generated by an automorphism over
the middle field is completely split in the middle field.**  An automorphism of the middle field
fixing the place below lifts to the top field, and there it can be corrected by an automorphism
over the middle field so as to fix the place itself; the corrected lift is then a power of the
generator, which restricts to the identity. -/
theorem stabilizer_eq_bot_of_stabilizer_eq_zpowers {σ : N ≃ₐ[F] N} {W : HeightOneSpectrum (𝓞 N)}
    (hW : stabilizer Gal(N/k) W = Subgroup.zpowers (σ.restrictScalars k)) :
    stabilizer Gal(F/k) (primeUnder (𝓞 F) W) = ⊥ := by
  haveI : IsGalois F N := IsGalois.tower_top_of_isGalois k F N
  haveI : IsGaloisGroup Gal(N/F) (𝓞 F) (𝓞 N) :=
    IsGaloisGroup.of_isFractionRing Gal(N/F) (𝓞 F) (𝓞 N) F N
  refine (Subgroup.eq_bot_iff_forall _).2 fun τ hτ => ?_
  obtain ⟨t, ht⟩ := AlgEquiv.restrictNormalHom_surjective (F := k) (K₁ := F) (E := N) τ
  have h1 : primeUnder (𝓞 F) (t • W) = primeUnder (𝓞 F) W := by
    rw [primeUnder_smul F t, ht]
    exact hτ
  obtain ⟨ρ, hρ⟩ := exists_smul_eq_of_primeUnder_eq (A := 𝓞 F) (G := Gal(N/F)) h1
  have hg : (ρ.restrictScalars k) * t ∈ stabilizer Gal(N/k) W := by
    show ((ρ.restrictScalars k) * t) • W = W
    rw [mul_smul]
    exact hρ
  rw [hW] at hg
  obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.1 hg
  have hrestr := congrArg (AlgEquiv.restrictNormalHom F) hm
  rw [map_zpow, map_mul, restrictNormalHom_restrictScalars k F σ, one_zpow,
    restrictNormalHom_restrictScalars k F ρ, one_mul, ht] at hrestr
  exact hrestr.symm

end Split

/-! ### The automorphism realising a character -/

section Aut

variable {k A : Type*} [Field k] [Field A] [Algebra k A] {Ω : IntermediateField k A}
  [CharZero ↥Ω] {p s : ℕ} {B : Subgroup (↥Ω)ˣ}

/-- **A non-trivial character of a subgroup of units, trivial on the powers of exponent a prime
that the subgroup contains, is realised by an automorphism of the radical field of prime order
generating a normal subgroup.**  The automorphisms of a field generated by radicals of prime
exponent commute and are killed by that exponent, so a non-identity one has order the exponent and
generates a normal subgroup. -/
theorem exists_aut_ambientRadField_of_character (P : PowBasis B p s) (hp : p.Prime) {ζ : ↥Ω}
    (hζ : IsPrimitiveRoot ζ p) (hfin : Finite (powQuotient B p))
    (hsat : ∀ y : (↥Ω)ˣ, y ^ p ∈ B → y ∈ B) (w : Fin s → A)
    (hw : ∀ i, w i ^ p = algebraMap ↥Ω A (P.rad i)) {U : Subgroup (↥Ω)ˣ} (hU : U ≤ B)
    (Φ : ↥U →* (↥Ω)ˣ)
    (hΦ : ∀ (u : (↥Ω)ˣ) (hu : u ∈ U) (y : (↥Ω)ˣ), u = y ^ p → Φ ⟨u, hu⟩ = 1)
    (hne : ∃ u : ↥U, Φ u ≠ 1) :
    ∃ σ : ↥(ambientRadField Ω w) ≃ₐ[↥Ω] ↥(ambientRadField Ω w),
      orderOf σ = p ∧ (Subgroup.zpowers σ).Normal ∧
      ∀ (u : (↥Ω)ˣ) (hu : u ∈ U) (v : ↥(ambientRadField Ω w)),
        v ^ p = algebraMap ↥Ω ↥(ambientRadField Ω w) (u : ↥Ω) →
          (σ v = v ↔ Φ ⟨u, hu⟩ = 1) := by
  haveI : NeZero p := ⟨hp.ne_zero⟩
  haveI : FiniteDimensional ↥Ω ↥(ambientRadField Ω w) :=
    finiteDimensional_ambientRadField P hζ w hw
  obtain ⟨σ, hσ⟩ := exists_aut_fix_iff_ambientRadField P hp hζ hfin hsat w hw hU Φ hΦ
  have htop : IntermediateField.adjoin ↥Ω
      (Set.range fun i => (⟨w i, mem_ambientRadField Ω w i⟩ : ↥(ambientRadField Ω w))) = ⊤ :=
    (P.setupOfRoots hζ w hw _ (mem_ambientRadField Ω w) rfl).adjoin_eq_top
  have hR : ∀ r ∈ (Set.range fun i => (⟨w i, mem_ambientRadField Ω w i⟩ :
      ↥(ambientRadField Ω w))), ∃ a : ↥Ω, r ^ p = algebraMap ↥Ω ↥(ambientRadField Ω w) a := by
    rintro _ ⟨i, rfl⟩
    exact ⟨P.rad i, Subtype.ext (hw i)⟩
  -- the automorphism is not the identity, because the character is not trivial
  have hσne : σ ≠ 1 := by
    obtain ⟨u, hu⟩ := hne
    obtain ⟨v, hvmem, hv⟩ := exists_mem_pow_eq_ambientRadField P hζ w hw (hU u.2)
    refine fun h => hu ?_
    refine (hσ (u : (↥Ω)ˣ) u.2 ⟨v, hvmem⟩ (Subtype.ext hv)).1 ?_
    rw [h, AlgEquiv.one_apply]
  exact ⟨σ, orderOf_eq_of_adjoin_radical hζ hR htop hp hσne,
    normal_zpowers_of_adjoin_radical hζ hR htop σ, hσ⟩

end Aut

/-! ### The place prescribed by the character -/

section Assemble

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Normal k A]
  [Field K] [NumberField K] [Algebra k K] [Algebra K A] {Ω : IntermediateField k A}
  [NumberField ↥Ω] [Normal k ↥Ω] [Algebra K ↥Ω] [IsScalarTower k K ↥Ω] [IsScalarTower K ↥Ω A]
  {p s : ℕ} [NeZero p] {B : Subgroup (↥Ω)ˣ} {Pc Ec : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **Outside any prescribed finite set of finite places of the bottom field there is a place,
completely split in the field the radicals are taken from, at which the value at the Frobenius
automorphism is trivial exactly at the units the character kills.**  The character is realised by
an automorphism of the radical field, of prime order and generating a normal subgroup; the place
whose decomposition group over the bottom field is that subgroup then reads the character off, and
is completely split because the automorphism fixes the field the radicals are taken from. -/
theorem exists_place_placeFrobValue_eq_one_iff_character (hp : p.Prime) (P : PowBasis B p s)
    (hstab : IsEmbeddingStable Ω B) (hsat : ∀ y : (↥Ω)ˣ, y ^ p ∈ B → y ∈ B)
    (hfin : Finite (powQuotient B p)) {ζ : K} (hζ : IsPrimitiveRoot ζ p) (w : Fin s → A)
    (hw : ∀ i, w i ^ p = algebraMap ↥Ω A (P.rad i))
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (Pc v) (Ec v))
    {U : Subgroup (↥Ω)ˣ} (hU : U ≤ B) (Φ : ↥U →* (↥Ω)ˣ)
    (hΦ : ∀ (u : (↥Ω)ˣ) (hu : u ∈ U) (y : (↥Ω)ˣ), u = y ^ p → Φ ⟨u, hu⟩ = 1)
    (hne : ∃ u : ↥U, Φ u ≠ 1) (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ V : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 k) V ∉ T ∧
      stabilizer Gal(↥Ω/k) V = ⊥ ∧ ¬ Pc (primeUnder (𝓞 K) V) ∣ p ∧
      ∀ (u : Kˣ) (hu : Units.map (algebraMap K ↥Ω : K →* ↥Ω) u ∈ U),
        (p : ℤ) ∣ placeValue (primeUnder (𝓞 K) V) u →
          (placeFrobValue hres hζ (primeUnder (𝓞 K) V) u = 1 ↔ Φ ⟨_, hu⟩ = 1) := by
  have hζΩ : IsPrimitiveRoot (algebraMap K ↥Ω ζ) p :=
    hζ.map_of_injective (algebraMap K ↥Ω).injective
  haveI : FiniteDimensional ↥Ω ↥(ambientRadField Ω w) :=
    finiteDimensional_ambientRadField P hζΩ w hw
  haveI : NumberField ↥(ambientRadField Ω w) :=
    NumberField.of_module_finite ↥Ω ↥(ambientRadField Ω w)
  haveI : Normal k ↥(ambientRadField Ω w) := normal_ambientRadField P hp hζΩ w hw hstab
  haveI : IsScalarTower k K ↥(ambientRadField Ω w) := IsScalarTower.of_algebraMap_eq fun x => by
    rw [IsScalarTower.algebraMap_apply k ↥Ω ↥(ambientRadField Ω w),
      IsScalarTower.algebraMap_apply k K ↥Ω,
      ← IsScalarTower.algebraMap_apply K ↥Ω ↥(ambientRadField Ω w)]
  haveI : IsGalois k ↥Ω := ⟨⟩
  haveI : IsGalois k ↥(ambientRadField Ω w) := ⟨⟩
  obtain ⟨σ, hord, hnormσ, hσ⟩ :=
    exists_aut_ambientRadField_of_character P hp hζΩ hfin hsat w hw hU Φ hΦ hne
  obtain ⟨W, hWT, -, hWk, hWP, hWfrob⟩ :=
    exists_place_placeFrobValue_eq_one_iff_smul_eq (k := k) (K := K) (F := ↥Ω)
      (N := ↥(ambientRadField Ω w)) hp hres hζ hnormσ (by rw [hord]; exact hp) T
  refine ⟨primeUnder (𝓞 ↥Ω) W, ?_, stabilizer_eq_bot_of_stabilizer_eq_zpowers hWk, ?_, ?_⟩
  · rwa [primeUnder_primeUnder k ↥Ω W]
  · rwa [primeUnder_primeUnder K ↥Ω W]
  · intro u hu hdvd
    rw [primeUnder_primeUnder K ↥Ω W] at hdvd ⊢
    obtain ⟨b, hbmem, hb⟩ := exists_mem_pow_eq_ambientRadField P hζΩ w hw (hU hu)
    have hbpow : (⟨b, hbmem⟩ : ↥(ambientRadField Ω w)) ^ p =
        algebraMap K ↥(ambientRadField Ω w) (u : K) := by
      rw [IsScalarTower.algebraMap_apply K ↥Ω ↥(ambientRadField Ω w)]
      exact Subtype.ext hb
    rw [hWfrob u hdvd _ hbpow]
    exact hσ _ hu ⟨b, hbmem⟩ (Subtype.ext hb)

end Assemble

end InverseGalois.CFT
