/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.PoitouTate.SplitFamily

/-!
# The coordinates of a family span a cyclic group of local classes

A class with values in a module of several coordinates is split by a cyclic extension of a
completion exactly when the local classes of its coordinates all lie in one cyclic subgroup of the
classes of that completion: the splitting field is generated by the radicals of the coordinates,
and it is cyclic exactly when those radicands generate a cyclic group modulo powers.

For the family of units built one coordinate at a time, that condition holds at every place
outside the part carrying the prescription, and for three separate reasons.  At a conjugate of one
of the exceptional places of a coordinate, all the other coordinates are local powers there, so
the group is generated by the one surviving coordinate.  At a place carrying no prescription but
lying in the finite set the prescription is defined on, every coordinate is trivial.  At every
remaining place no coordinate is ramified, and the unramified classes at a place not dividing the
exponent are cyclic of order the exponent, so they all lie in one cyclic group for that reason.

## Main results

* `InverseGalois.CFT.exists_forall_localClassHom_mem_zpowers`: **at every place outside the
  prescribed part the local classes of the units of a family all lie in the cyclic group generated
  by a single local class.**

## Tags

number field, place, local class, cyclic, unramified, prescription
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

section RankOne

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Field K] [NumberField K]
  [Algebra k K] {Ω : IntermediateField k A} [NumberField ↥Ω] [Algebra K ↥Ω] {p : ℕ} [NeZero p]

/-- **The coordinates of a family generate a cyclic group of local classes at every place outside
the prescribed part.**  A place is either a conjugate of one of the exceptional places of some
coordinate, in which case that coordinate's class generates and every other coordinate is trivial
there; or it carries a trivial prescription, in which case every coordinate is trivial there; or
no coordinate is ramified there and the place does not divide the exponent, in which case every
coordinate lies in the unramified classes, which are cyclic. -/
theorem exists_forall_localClassHom_mem_zpowers (hp : p.Prime) {ζ : K}
    (hζ : IsPrimitiveRoot ζ p) {Tr T Tn : Finset (HeightOneSpectrum (𝓞 K))} (hTr : Tr ⊆ T)
    (hpTn : ∀ v : HeightOneSpectrum (𝓞 K), FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → v ∈ Tn)
    {c : ℕ → (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    (hcT : ∀ (i : ℕ), ∀ v ∈ Tn, v ∉ T → c i v = 1)
    {d : ℕ} {S : Finset (HeightOneSpectrum (𝓞 K))} {Q R : ℕ → HeightOneSpectrum (𝓞 K)}
    {z : ℕ → Kˣ} (h : IsTwoPlaceFamily Ω p Tr Tn c d S Q R z)
    {v : HeightOneSpectrum (𝓞 K)} (hv : v ∉ T) :
    ∃ u : localClasses v p, ∀ i < d, localClassHom v p (z i) ∈ Subgroup.zpowers u := by
  classical
  by_cases hA : ∃ j < d, ∃ σ : Gal(K/k), σ • Q j = v ∨ σ • R j = v
  · obtain ⟨j, hj, σ, hσ⟩ := hA
    refine ⟨localClassHom v p (z j), fun i hi => ?_⟩
    rcases eq_or_ne i j with rfl | hij
    · exact Subgroup.mem_zpowers _
    · rcases hσ with hσ | hσ
      · rw [← hσ, h.crossQ i hi j hj hij σ]
        exact one_mem _
      · rw [← hσ, h.crossR i hi j hj hij σ]
        exact one_mem _
  · push_neg at hA
    have hne : ∀ i, i < d → v ≠ Q i ∧ v ≠ R i := by
      intro i hi
      have hone := hA i hi 1
      rw [one_smul, one_smul] at hone
      exact ⟨fun hcon => hone.1 hcon.symm, fun hcon => hone.2 hcon.symm⟩
    by_cases hvTn : v ∈ Tn
    · refine ⟨1, fun i hi => ?_⟩
      rw [h.prescribed i hi v hvTn, hcT i v hvTn hv]
      exact one_mem _
    · have hvp : FinitePlace.mk v ((p : ℕ) : K) = 1 := by
        by_contra hcon
        exact hvTn (hpTn v hcon)
      have hmem : ∀ i, i < d → localClassHom v p (z i) ∈ localUnramified v p := fun i hi =>
        (localClassHom_mem_localUnramified_iff v (z i)).2
          (h.unram i hi v (fun hcon => hv (hTr hcon)) (hne i hi).1 (hne i hi).2)
      obtain ⟨gU, hgU⟩ := (isCyclic_localUnramified hp hζ v hvp).exists_generator
      refine ⟨(gU : localClasses v p), fun i hi => ?_⟩
      obtain ⟨m, hm⟩ := hgU ⟨localClassHom v p (z i), hmem i hi⟩
      exact ⟨m, by simpa using congrArg Subtype.val hm⟩

end RankOne

end InverseGalois.CFT
