/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Kummer.RadicalAut
import InverseGalois.CFT.Kummer.RadicalRamIdx
import InverseGalois.CFT.Kummer.RadicandDescent
import InverseGalois.CFT.PoitouTate.RecursionSup
import InverseGalois.CFT.PoitouTate.SplitLocalPower

/-!
# One step of the recursion over a compositum with a radical second factor

The step of the recursion over a compositum asks of the second factor of the middle field that it
be abelian of exponent the exponent and unramified at the places carrying the prescribed global
unit.  When that factor is generated by `p`-th roots of units of the bottom field, all three
demands are met at once: the automorphisms of an extension generated by radicals of exponent `p`
commute and are killed by `p`, and a radical extension is unramified away from the exponent at
every place where the order of each radicand is a multiple of the exponent.

The place the step produces is completely split in the middle field, so the radicands themselves
become `p`-th powers in the completion there: the radicals lie in the completion of the middle
field, which is the completion of the bottom field.  So the new place kills the whole family of
radicands, which is exactly what makes it usable as an exceptional place of a later coordinate.

A prescription which is ramified where it is carried asks of the second factor not that it be
unramified there but that its radicands have, at such a place, a class on the line of the prescribed
class.  For a factor generated by radicals of the bottom field that is a condition on the radicands
alone: an element of the bottom field which becomes a `p`-th power in the factor is, up to a `p`-th
power of the bottom field, a monomial in the radicands, so its class at any place is a product of
powers of their classes.

## Main results

* `InverseGalois.CFT.localClassHom_eq_one_of_stabilizer_base_eq_bot`: a place of the middle field
  with trivial decomposition group over the bottom of the tower kills every radicand of the second
  factor.
* `InverseGalois.CFT.localClassHom_mem_zpowers_of_adjoin_radicals`: the class of an element of the
  bottom field which becomes a `p`-th power in a radical extension lies on any line carrying the
  classes of the radicands.
* `InverseGalois.CFT.exists_place_sUnit_prescribed_of_radical`: **one step of the recursion over a
  compositum whose second factor is generated by radicals** — a new place, outside the prescribed
  set, completely split in the compositum and killing every radicand, together with an `S`-unit
  meeting the prescription at the old places and ramified exactly at the new one.
* `InverseGalois.CFT.exists_place_sUnit_prescribed_of_radical_zpowers`: **the same for a
  prescription which may be ramified where it is carried**, granted that the classes of the
  radicands lie there on the line of the prescribed class; the `S`-unit produced is then ramified
  at the new place and, apart from where the prescription is carried, nowhere else.

## Tags

Chebotarev, compositum, radical extension, S-unit, prescription, recursion
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### A completely split place kills the radicands -/

section Kill

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Field K] [NumberField K]
  [Algebra k K] [Algebra K A] {Ω : IntermediateField k A} [NumberField ↥Ω] [Algebra K ↥Ω]
  [IsScalarTower k K ↥Ω] [IsGalois K ↥Ω] {M₂ : Type} [Field M₂] [Algebra K M₂] [Algebra M₂ ↥Ω]
  [IsScalarTower K M₂ ↥Ω] {p : ℕ} [NeZero p]

omit [NumberField k] [Algebra K A] in
/-- **A place of the middle field with trivial decomposition group over the bottom of the tower
kills every radicand of the second factor.**  Its completion is the completion of the bottom field,
so the radical, which lies in the middle field, is already there. -/
theorem localClassHom_eq_one_of_stabilizer_base_eq_bot {V : HeightOneSpectrum (𝓞 ↥Ω)}
    (hV : stabilizer Gal(↥Ω/k) V = ⊥) {b : Kˣ} {α : M₂}
    (hα : α ^ p = algebraMap K M₂ ((b : K))) :
    localClassHom (primeUnder (𝓞 K) V) p b = 1 := by
  refine localClassHom_eq_one_of_pow_eq (stabilizer_eq_bot_of_stabilizer_base_eq_bot hV)
    (α := algebraMap M₂ ↥Ω α) ?_
  rw [← _root_.map_pow, hα, ← IsScalarTower.algebraMap_apply]

end Kill

/-! ### The classes of a radical extension lie on the line of the radicands -/

section Descend

variable {K M : Type} [Field K] [NumberField K] [Field M] [NumberField M] [Algebra K M]
  [Normal K M] {p : ℕ} [NeZero p]

omit [NeZero p] in
/-- **The class of an element of the bottom field which becomes a `p`-th power in a radical
extension lies on any line carrying the classes of the radicands.**  Such an element is, up to a
`p`-th power of the bottom field, a monomial in the radicands, and a `p`-th power has trivial class
in the classes modulo `p`-th powers. -/
theorem localClassHom_mem_zpowers_of_adjoin_radicals (hp : p.Prime) {ζ : K}
    (hζ : IsPrimitiveRoot ζ p) {ι : Type*} [Finite ι] {b : ι → Kˣ} {α : ι → M}
    (hpow : ∀ i, α i ^ p = algebraMap K M ((b i : K)))
    (hgen : IntermediateField.adjoin K (Set.range α) = ⊤)
    {v : HeightOneSpectrum (𝓞 K)} {d : localClasses v p}
    (hd : ∀ i, localClassHom v p (b i) ∈ Subgroup.zpowers d)
    {x : Kˣ} (hx : ∃ y : M, algebraMap K M ((x : K)) = y ^ p) :
    localClassHom v p x ∈ Subgroup.zpowers d := by
  classical
  haveI : Fintype ι := Fintype.ofFinite ι
  haveI : IsGalois K M := ⟨⟩
  haveI : FiniteDimensional K M := FiniteDimensional.right ℚ K M
  obtain ⟨y, hy⟩ := hx
  obtain ⟨e, z, hz⟩ := exists_pow_prod_of_pow_eq_of_adjoin_eq_top hp hζ hpow hgen hy.symm
  rw [hz, _root_.map_mul]
  have hterm : ∀ i : ι, localClassHom v p (b i ^ e i) ∈ Subgroup.zpowers d := by
    intro i
    rw [_root_.map_pow]
    exact pow_mem (hd i) _
  refine mul_mem ?_ ?_
  · rw [_root_.map_prod]
    exact Subgroup.prod_mem (Subgroup.zpowers d) fun i _ => hterm i
  · rw [_root_.map_pow, pow_eq_one_of_quotient_range_powMonoidHom p]
    exact one_mem _

end Descend

/-! ### The step over a compositum with a radical second factor -/

section RadicalStep

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Normal k A]
  [IsAlgClosed A] [Field K] [NumberField K] [Algebra k K] [Algebra K A]
  {Ω : IntermediateField k A} [NumberField ↥Ω] [Normal k ↥Ω] [Algebra K ↥Ω]
  [IsScalarTower k K ↥Ω] [IsScalarTower K ↥Ω A] [IsGalois K ↥Ω]
  {M₁ M₂ : Type} [Field M₁] [NumberField M₁] [Algebra K M₁] [IsGalois K M₁]
  [Field M₂] [NumberField M₂] [Algebra K M₂] [Normal K M₂]
  [Algebra M₁ ↥Ω] [IsScalarTower K M₁ ↥Ω] [Algebra M₂ ↥Ω] [IsScalarTower K M₂ ↥Ω]
  {p : ℕ} [NeZero p] {Pc Ec : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **One step of the recursion prescribing local classes, over a middle field whose second factor
is generated by radicals of exponent `p`.**  The automorphisms of such a factor commute and are
killed by `p`, and it is unramified away from the exponent wherever the order of every radicand is
a multiple of the exponent, so the three demands the compositum step makes of the second factor are
all met.  The new place is completely split in the middle field, hence kills every radicand. -/
theorem exists_place_sUnit_prescribed_of_radical (hp : p.Prime) (hodd : 2 < p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (Pc v) (Ec v))
    (Tk : Finset (HeightOneSpectrum (𝓞 k))) {T Tn : Finset (HeightOneSpectrum (𝓞 K))}
    (hT : T ⊆ Tn) (hTk : ∀ v ∈ Tn, primeUnder (𝓞 k) v ∈ Tk)
    (hpTn : ∀ v : HeightOneSpectrum (𝓞 K), FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → v ∈ Tn)
    (hrepr : ∀ m : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, m v = 0) →
      ∃ a : Kˣ, ∀ v ∉ (Tn : Set (HeightOneSpectrum (𝓞 K))),
        Rigidity.RET.ord K v (a : K) = m v)
    {c : (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    (hcunr : ∀ v ∈ Tn, c v ∈ localUnramified v p)
    {g : Kˣ} (hg : g ∈ sUnits K (Tn : Set (HeightOneSpectrum (𝓞 K))))
    (hc : ∀ v ∈ T, c v = localClassHom v p g) (hcT : ∀ v ∈ Tn, v ∉ T → c v = 1)
    (hcn : ∀ v ∈ T, FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → c v = 1)
    (hsup : (IsScalarTower.toAlgHom K M₁ ↥Ω).fieldRange ⊔
      (IsScalarTower.toAlgHom K M₂ ↥Ω).fieldRange = ⊤)
    {ι : Type*} {b : ι → Kˣ} {α : ι → M₂}
    (hpow : ∀ i, α i ^ p = algebraMap K M₂ ((b i : K)))
    (hgen : IntermediateField.adjoin K (Set.range α) = ⊤)
    (hord : ∀ v ∈ T, FinitePlace.mk v ((p : ℕ) : K) = 1 →
      ∀ i, (p : ℤ) ∣ Rigidity.RET.ord K v ((b i : K)))
    (hsplit : ∀ v ∈ Tn, v ∉ T → ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ stabilizer Gal(M₁/K) w = ⊥)
    (hram₁ : ∀ v ∉ Tn, ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ ramIdx (𝓞 K) w = 1) :
    ∃ V : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 k) V ∉ Tk ∧
      stabilizer Gal(↥Ω/k) V = ⊥ ∧ ¬ Pc (primeUnder (𝓞 K) V) ∣ p ∧
      primeUnder (𝓞 K) V ∉ Tn ∧
      (∀ i, localClassHom (primeUnder (𝓞 K) V) p (b i) = 1) ∧
      ∃ z : Kˣ, z ∈ sUnits K (insert (primeUnder (𝓞 K) V)
          (Tn : Set (HeightOneSpectrum (𝓞 K)))) ∧
        (∀ v ∈ Tn, localClassHom v p z = c v) ∧
        (∀ v : HeightOneSpectrum (𝓞 K), v ≠ primeUnder (𝓞 K) V →
          (p : ℤ) ∣ placeValue v z) ∧
        ¬ (p : ℤ) ∣ placeValue (primeUnder (𝓞 K) V) z := by
  haveI : IsGalois K M₂ := ⟨⟩
  have hR : ∀ r ∈ Set.range α, ∃ a : K, r ^ p = algebraMap K M₂ a := by
    rintro _ ⟨i, rfl⟩
    exact ⟨(b i : K), hpow i⟩
  obtain ⟨V, hVk, hVstab, hVP, hVn, z, hz⟩ :=
    exists_place_sUnit_prescribed_of_sup (Ω := Ω) (M₁ := M₁) (M₂ := M₂) hp hodd hζ hres Tk hT hTk
      hpTn hrepr hcunr hg hc hcT hcn hsup (mul_comm_of_adjoin_radical hζ hR hgen)
      (pow_eq_one_of_adjoin_radical hζ hR hgen) hsplit hram₁
      fun v hv hvp => exists_primeUnder_ramIdx_eq_one_of_radicals hp hζ hpow hgen v hvp
        (hord v hv hvp)
  exact ⟨V, hVk, hVstab, hVP, hVn,
    fun i => localClassHom_eq_one_of_stabilizer_base_eq_bot hVstab (hpow i), z, hz⟩

/-- **One step of the recursion prescribing local classes over a compositum whose second factor is
generated by radicals, for a prescription which may be ramified where it is carried.**  What the
step asks of the second factor there is not unramifiedness but that its radicands have a class on
the line of the prescribed class, and that is a condition on the radicands alone: an element of the
bottom field which becomes a `p`-th power in the factor is a monomial in the radicands up to a
`p`-th power.  The new place is completely split in the middle field, hence kills every radicand,
and the `S`-unit produced is ramified there and, apart from where the prescription is carried,
nowhere else. -/
theorem exists_place_sUnit_prescribed_of_radical_zpowers (hp : p.Prime) (hodd : 2 < p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (Pc v) (Ec v))
    (Tk : Finset (HeightOneSpectrum (𝓞 k))) {T Tn : Finset (HeightOneSpectrum (𝓞 K))}
    (hT : T ⊆ Tn) (hTk : ∀ v ∈ Tn, primeUnder (𝓞 k) v ∈ Tk)
    (hpTn : ∀ v : HeightOneSpectrum (𝓞 K), FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → v ∈ Tn)
    (hrepr : ∀ m : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, m v = 0) →
      ∃ a : Kˣ, ∀ v ∉ (Tn : Set (HeightOneSpectrum (𝓞 K))),
        Rigidity.RET.ord K v (a : K) = m v)
    {c : (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    {g : Kˣ} (hg : g ∈ sUnits K (Tn : Set (HeightOneSpectrum (𝓞 K))))
    (hc : ∀ v ∈ T, c v = localClassHom v p g) (hcT : ∀ v ∈ Tn, v ∉ T → c v = 1)
    (hsup : (IsScalarTower.toAlgHom K M₁ ↥Ω).fieldRange ⊔
      (IsScalarTower.toAlgHom K M₂ ↥Ω).fieldRange = ⊤)
    {ι : Type*} [Finite ι] {b : ι → Kˣ} {α : ι → M₂}
    (hpow : ∀ i, α i ^ p = algebraMap K M₂ ((b i : K)))
    (hgen : IntermediateField.adjoin K (Set.range α) = ⊤)
    {D : (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    (hDc : ∀ v ∈ T, c v ∈ Subgroup.zpowers (D v))
    (hDb : ∀ v ∈ T, ∀ i, localClassHom v p (b i) ∈ Subgroup.zpowers (D v))
    (hsplit : ∀ v ∈ Tn, v ∉ T → ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ stabilizer Gal(M₁/K) w = ⊥)
    (hram₁ : ∀ v ∉ Tn, ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ ramIdx (𝓞 K) w = 1) :
    ∃ V : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 k) V ∉ Tk ∧
      stabilizer Gal(↥Ω/k) V = ⊥ ∧ ¬ Pc (primeUnder (𝓞 K) V) ∣ p ∧
      primeUnder (𝓞 K) V ∉ Tn ∧
      (∀ i, localClassHom (primeUnder (𝓞 K) V) p (b i) = 1) ∧
      ∃ z : Kˣ, z ∈ sUnits K (insert (primeUnder (𝓞 K) V)
          (Tn : Set (HeightOneSpectrum (𝓞 K)))) ∧
        (∀ v ∈ Tn, localClassHom v p z = c v) ∧
        (∀ v : HeightOneSpectrum (𝓞 K), v ∉ T → v ≠ primeUnder (𝓞 K) V →
          (p : ℤ) ∣ placeValue v z) ∧
        ¬ (p : ℤ) ∣ placeValue (primeUnder (𝓞 K) V) z := by
  have hR : ∀ r ∈ Set.range α, ∃ a : K, r ^ p = algebraMap K M₂ a := by
    rintro _ ⟨i, rfl⟩
    exact ⟨(b i : K), hpow i⟩
  obtain ⟨V, hVk, hVstab, hVP, hVn, z, hz⟩ :=
    exists_place_sUnit_prescribed_of_sup_zpowers (Ω := Ω) (M₁ := M₁) (M₂ := M₂) hp hodd hζ hres Tk
      hT hTk hpTn hrepr hg hc hcT hsup (mul_comm_of_adjoin_radical hζ hR hgen)
      (pow_eq_one_of_adjoin_radical hζ hR hgen) hsplit hram₁
      fun v hv => ⟨D v, hDc v hv, fun x hx =>
        localClassHom_mem_zpowers_of_adjoin_radicals hp hζ hpow hgen (hDb v hv) hx⟩
  exact ⟨V, hVk, hVstab, hVP, hVn,
    fun i => localClassHom_eq_one_of_stabilizer_base_eq_bot hVstab (hpow i), z, hz⟩

end RadicalStep

end InverseGalois.CFT
