/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Compositum
import InverseGalois.CFT.PoitouTate.RecursionStep
import InverseGalois.CFT.PoitouTate.SupRadicandChar

/-!
# One step of the recursion over a compositum of two auxiliary extensions

The step of the recursion prescribing local classes asks of the middle field only that the
character of the `S`-units cut out by the prescription be killed by every radicand of it.  When the
middle field is a compositum of two extensions of the bottom field, the second of which is abelian
of exponent the exponent, a radicand splits as a radicand of the first factor times a radicand of
the second, and the character kills each factor for its own reason: the first factor is a local
power where the prescription is not carried by a global unit and has value a multiple of the
exponent outside the prescribed set, while the second has value a multiple of the exponent on the
prescribed set.  So the step runs over the compositum as soon as the first factor splits completely
off the prescribed set and is unramified outside it, and the second is unramified on it.

The two copies of the factors inside the compositum have to generate it over the bottom field, and
that is a statement about sets of elements which does not see the field it is read over: it holds
for the compositum of two intermediate fields of any extension of the base.

## Main results

* `InverseGalois.CFT.exists_place_sUnit_prescribed_of_sup`: **one step of the recursion over a
  compositum** — a new place, outside the prescribed set and completely split in the compositum,
  together with an `S`-unit meeting the prescription at the old places and ramified exactly at the
  new one.

## Tags

Chebotarev, compositum, norm residue symbol, S-unit, prescription, recursion
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### The step over a compositum -/

section SupStep

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Normal k A]
  [IsAlgClosed A] [Field K] [NumberField K] [Algebra k K] [Algebra K A]
  {Ω : IntermediateField k A} [NumberField ↥Ω] [Normal k ↥Ω] [Algebra K ↥Ω]
  [IsScalarTower k K ↥Ω] [IsScalarTower K ↥Ω A] [IsGalois K ↥Ω]
  {M₁ M₂ : Type} [Field M₁] [NumberField M₁] [Algebra K M₁] [IsGalois K M₁]
  [Field M₂] [NumberField M₂] [Algebra K M₂] [Normal K M₂]
  [Algebra M₁ ↥Ω] [IsScalarTower K M₁ ↥Ω] [Algebra M₂ ↥Ω] [IsScalarTower K M₂ ↥Ω]
  {p : ℕ} [NeZero p] {Pc Ec : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **One step of the recursion prescribing local classes, over a middle field generated by two
extensions of the bottom field.**  The prescription is carried by a global `S`-unit on part of the
prescribed set and is trivial on the rest; the first extension splits completely on that rest and
is unramified outside the prescribed set, and the second extension is abelian of exponent the
exponent and unramified on the part carrying the global unit.  Then the character of the `S`-units
is killed by every radicand of the middle field, because a radicand factors along the two
extensions, and the step produces a new place, completely split in the middle field, together with
an `S`-unit meeting the prescription and ramified exactly there. -/
theorem exists_place_sUnit_prescribed_of_sup (hp : p.Prime) (hodd : 2 < p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (Pc v) (Ec v))
    (Tk : Finset (HeightOneSpectrum (𝓞 k))) {T Tn : Finset (HeightOneSpectrum (𝓞 K))}
    (hT : T ⊆ Tn) (hTk : ∀ v ∈ Tn, primeUnder (𝓞 k) v ∈ Tk)
    (hpTn : ∀ v : HeightOneSpectrum (𝓞 K), FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → v ∈ Tn)
    (hrepr : ∀ m : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, m v = 0) →
      ∃ a : Kˣ, ∀ v ∉ (Tn : Set (HeightOneSpectrum (𝓞 K))),
        Rigidity.RET.ord K v (a : K) = m v)
    {c : (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    (hcunr : ∀ v ∈ Tn, c v ∈ localUnramified v p)
    {g : Kˣ} (hg : g ∈ sUnits K (Tn : Set (HeightOneSpectrum (𝓞 K))))
    (hc : ∀ v ∈ T, c v = localClassHom v p g) (hcT : ∀ v ∈ Tn, v ∉ T → c v = 1)
    (hcn : ∀ v ∈ T, FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → c v = 1)
    (hsup : (IsScalarTower.toAlgHom K M₁ ↥Ω).fieldRange ⊔
      (IsScalarTower.toAlgHom K M₂ ↥Ω).fieldRange = ⊤)
    (hcomm : ∀ σ τ : M₂ ≃ₐ[K] M₂, σ * τ = τ * σ) (hexp : ∀ σ : M₂ ≃ₐ[K] M₂, σ ^ p = 1)
    (hsplit : ∀ v ∈ Tn, v ∉ T → ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ stabilizer Gal(M₁/K) w = ⊥)
    (hram₁ : ∀ v ∉ Tn, ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ ramIdx (𝓞 K) w = 1)
    (hram₂ : ∀ v ∈ T, ∃ w : HeightOneSpectrum (𝓞 M₂),
      primeUnder (𝓞 K) w = v ∧ ramIdx (𝓞 K) w = 1) :
    ∃ V : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 k) V ∉ Tk ∧
      stabilizer Gal(↥Ω/k) V = ⊥ ∧ ¬ Pc (primeUnder (𝓞 K) V) ∣ p ∧
      primeUnder (𝓞 K) V ∉ Tn ∧
      ∃ z : Kˣ, z ∈ sUnits K (insert (primeUnder (𝓞 K) V)
          (Tn : Set (HeightOneSpectrum (𝓞 K)))) ∧
        (∀ v ∈ Tn, localClassHom v p z = c v) ∧
        (∀ v : HeightOneSpectrum (𝓞 K), v ≠ primeUnder (𝓞 K) V →
          (p : ℤ) ∣ placeValue v z) ∧
        ¬ (p : ℤ) ∣ placeValue (primeUnder (𝓞 K) V) z := by
  have hp2 : p ≠ 2 := by omega
  refine exists_place_sUnit_prescribed_of_rad hp hodd hζ hres Tk hTk hpTn hrepr hcunr
    fun u hu y hy => ?_
  have hb : algebraMap K ↥Ω ((u : Kˣ) : K) = ((y : (↥Ω)ˣ) : ↥Ω) ^ p := by
    have hy' := congrArg Units.val hy
    rwa [Units.coe_map, MonoidHom.coe_coe, Units.val_pow_eq_pow_val] at hy'
  exact prescriptionChar_eq_one_of_pow_sup hp hp2 hres hζ hT hpTn hg hc hcT
    (fun v hv => hcunr v (hT hv)) hcn hsup hcomm hexp hsplit hram₁ hram₂ hb

end SupStep

end InverseGalois.CFT
