/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.PoitouTate.RecursionRadical
import InverseGalois.CFT.PoitouTate.TwoPlacesFree

/-!
# Two completely split places over a compositum with a radical second factor

The construction of two completely split places carrying a prescribed local behaviour is run
relative to an auxiliary field, and it asks that the places where the unit it starts from fails to
be a unit, and which are not among the places carrying the prescription, be completely split in
that field.  When the auxiliary field is a compositum whose second factor is generated by radicals,
the places already spoken for are split in the first factor only, so the construction cannot be
started from the unit one has: one first has to move to a unit whose failure to be a unit happens
at a single new place, completely split in the whole compositum.

That is exactly what one step of the recursion over the compositum provides.  Running it once
produces such a place and such a unit, realising the prescription where it matters; running the
two-place construction over the compositum from there produces the two places, and being completely
split in the compositum they kill every radicand of the second factor.

## Main results

* `InverseGalois.CFT.exists_two_places_sUnit_radical`: **two places completely split in a compositum
  whose second factor is generated by radicals, killing every radicand of that factor, and a unit
  ramified exactly at the two of them realising a prescribed local behaviour.**

## Tags

number field, place, completely split, compositum, radical extension, local class, prescription
-/

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### Starting the two-place construction over a compositum -/

section Radical

variable {k A K : Type} [Field k] [NumberField k] [Field A] [Algebra k A] [Normal k A]
  [IsAlgClosed A] [Field K] [NumberField K] [Algebra k K] [Algebra K A] [IsGalois k K]
  {Ω : IntermediateField k A} [NumberField ↥Ω] [Normal k ↥Ω] [Algebra K ↥Ω]
  [IsScalarTower k K ↥Ω] [IsScalarTower K ↥Ω A] [IsGalois K ↥Ω]
  {M₁ M₂ : Type} [Field M₁] [NumberField M₁] [Algebra K M₁] [IsGalois K M₁]
  [Field M₂] [NumberField M₂] [Algebra K M₂] [Normal K M₂]
  [Algebra M₁ ↥Ω] [IsScalarTower K M₁ ↥Ω] [Algebra M₂ ↥Ω] [IsScalarTower K M₂ ↥Ω]
  {p : ℕ} [NeZero p] {Pc Ec : HeightOneSpectrum (𝓞 K) → ℕ}

/-- **Two places completely split in a compositum with a radical second factor, and a unit ramified
exactly at them realising a prescribed local behaviour.**  A single step of the recursion over the
compositum moves the prescription onto a unit which fails to be a unit at one new place only, and
that place is completely split in the whole compositum; the two-place construction may then be run
over the compositum starting from it.  The two places it produces are completely split there, so
every radicand of the second factor is a power in their completions and has trivial class. -/
theorem exists_two_places_sUnit_radical (hp : p.Prime) (hodd : 2 < p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hres : ∀ v : HeightOneSpectrum (𝓞 K), HasResidueChar (v.adicCompletion K) (Pc v) (Ec v))
    {T Tn : Finset (HeightOneSpectrum (𝓞 K))} (hT : T ⊆ Tn)
    (hTstable : ∀ (σ : Gal(K/k)) (v : HeightOneSpectrum (𝓞 K)), v ∈ Tn → σ • v ∈ Tn)
    (hpTn : ∀ v : HeightOneSpectrum (𝓞 K), FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → v ∈ Tn)
    (hrepr : ∀ m : HeightOneSpectrum (𝓞 K) → ℤ,
      (∀ᶠ v : HeightOneSpectrum (𝓞 K) in Filter.cofinite, m v = 0) →
      ∃ a : Kˣ, ∀ v ∉ (Tn : Set (HeightOneSpectrum (𝓞 K))),
        Rigidity.RET.ord K v (a : K) = m v)
    {c : (v : HeightOneSpectrum (𝓞 K)) → localClasses v p}
    (hcunr : ∀ v ∈ Tn, c v ∈ localUnramified v p)
    {g : Kˣ} (hg : g ∈ sUnits K (Tn : Set (HeightOneSpectrum (𝓞 K))))
    (hc : ∀ v ∈ T, c v = localClassHom v p g) (hcT : ∀ v ∈ Tn, v ∉ T → c v = 1)
    (hcn : ∀ v ∈ T, FinitePlace.mk v ((p : ℕ) : K) ≠ 1 → c v = 1)
    (hsup : (IsScalarTower.toAlgHom K M₁ ↥Ω).fieldRange ⊔
      (IsScalarTower.toAlgHom K M₂ ↥Ω).fieldRange = ⊤)
    {ι : Type*} {b : ι → Kˣ} {α : ι → M₂}
    (hpow : ∀ i, α i ^ p = algebraMap K M₂ ((b i : K)))
    (hgen : IntermediateField.adjoin K (Set.range α) = ⊤)
    (hord : ∀ v ∈ T, FinitePlace.mk v ((p : ℕ) : K) = 1 →
      ∀ i, (p : ℤ) ∣ Rigidity.RET.ord K v ((b i : K)))
    (hsplit : ∀ v ∈ Tn, v ∉ T → ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ stabilizer Gal(M₁/K) w = ⊥)
    (hram₁ : ∀ v ∉ Tn, ∃ w : HeightOneSpectrum (𝓞 M₁),
      primeUnder (𝓞 K) w = v ∧ ramIdx (𝓞 K) w = 1) :
    ∃ Q R : HeightOneSpectrum (𝓞 K), Q ∉ Tn ∧ R ∉ Tn ∧
      (∃ w : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 K) w = Q ∧
        stabilizer Gal(↥Ω/k) w = ⊥) ∧
      (∃ w : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 K) w = R ∧
        stabilizer Gal(↥Ω/k) w = ⊥) ∧
      (∀ i, localClassHom Q p (b i) = 1) ∧ (∀ i, localClassHom R p (b i) = 1) ∧
      (∀ σ : Gal(K/k), Q ≠ σ • R) ∧
      stabilizer Gal(K/k) Q = ⊥ ∧ stabilizer Gal(K/k) R = ⊥ ∧
      ∃ z : Kˣ, (∀ v ∈ Tn, localClassHom v p z = c v) ∧
        (∀ v : HeightOneSpectrum (𝓞 K), v ≠ Q → v ≠ R → (p : ℤ) ∣ placeValue v z) ∧
        ¬ (p : ℤ) ∣ placeValue Q z ∧ ¬ (p : ℤ) ∣ placeValue R z ∧
        (∀ σ : Gal(K/k), σ ≠ 1 → localClassHom (σ • Q) p z = 1) ∧
        (∀ σ : Gal(K/k), σ ≠ 1 → localClassHom (σ • R) p z = 1) := by
  classical
  obtain ⟨V, -, hVstab, -, -, -, y, hyS, hyc, -, -⟩ :=
    exists_place_sUnit_prescribed_of_radical (Ω := Ω) (M₁ := M₁) (M₂ := M₂) hp hodd hζ hres
      (Tn.image (primeUnder (𝓞 k))) hT (fun v hv => Finset.mem_image_of_mem _ hv) hpTn hrepr
      hcunr hg hc hcT hcn hsup hpow hgen hord hsplit hram₁
  have hysplit : ∀ v : HeightOneSpectrum (𝓞 K), v ∉ Tn → Rigidity.RET.ord K v (y : K) ≠ 0 →
      ∃ w : HeightOneSpectrum (𝓞 ↥Ω), primeUnder (𝓞 K) w = v ∧
        stabilizer Gal(↥Ω/k) w = ⊥ := by
    intro v hv hord0
    have hmem : v ∈ insert (primeUnder (𝓞 K) V) (Tn : Set (HeightOneSpectrum (𝓞 K))) := by
      by_contra hcon
      exact hord0 (mem_sUnits.1 hyS v hcon)
    rcases hmem with rfl | hmem
    · exact ⟨V, rfl, hVstab⟩
    · exact absurd hmem hv
  have hyunr : ∀ v ∈ Tn, localClassHom v p y ∈ localUnramified v p := by
    intro v hv
    rw [hyc v hv]
    exact hcunr v hv
  have hyp : ∀ v ∈ Tn, Pc v ∣ p → localClassHom v p y = 1 := by
    intro v hv hdvd
    rw [hyc v hv]
    by_cases hvT : v ∈ T
    · exact hcn v hvT fun hone => not_dvd_of_finitePlace_natCast_eq_one (hres v) hone hdvd
    · exact hcT v hv hvT
  obtain ⟨Q, R, hQT, hRT, hQspl, hRspl, hQR, hQstab, hRstab, z, hzT, hzunr, hzQ, hzR, hzQc,
    hzRc⟩ := exists_two_places_sUnit_class_eq_of_split (Ω := Ω) hp hodd hζ hres hTstable hpTn
      hysplit hyunr hyp
  refine ⟨Q, R, hQT, hRT, hQspl, hRspl, ?_, ?_, hQR, hQstab, hRstab, z,
    fun v hv => (hzT v hv).trans (hyc v hv), hzunr, hzQ, hzR, hzQc, hzRc⟩
  · obtain ⟨w, hw1, hw2⟩ := hQspl
    intro i
    rw [← hw1]
    exact localClassHom_eq_one_of_stabilizer_base_eq_bot hw2 (hpow i)
  · obtain ⟨w, hw1, hw2⟩ := hRspl
    intro i
    rw [← hw1]
    exact localClassHom_eq_one_of_stabilizer_base_eq_bot hw2 (hpow i)

end Radical

end InverseGalois.CFT
