/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.SquareClasses
import InverseGalois.CFT.Global.HilbertMulPlaces
import InverseGalois.CFT.Global.OddGenerators
import InverseGalois.CFT.Global.Reciprocity

/-!
# The symbol of minus one against a rational number

The quadratic extension obtained by adjoining a square root of minus one is unramified outside
the dyadic place and the real place, and its local behaviour at an odd prime is governed by the
quartic character.  This file computes the Hilbert symbol `(-1, d)` place by place and reads the
product formula backwards: the symbol at the dyadic place is determined by the symbol at the real
place together with the symbols at the odd primes, and at an odd prime congruent to one modulo
four the symbol against minus one is trivial whatever the second argument.

The consequence is a rigid constraint on integers whose odd prime factors are all congruent to
one modulo four: for such an integer the dyadic symbol against minus one is exactly the sign, so
a positive one can never have nontrivial dyadic symbol.  An odd prime congruent to three modulo
four escapes the constraint, being positive with nontrivial dyadic symbol.

## Main results

* `InverseGalois.CFT.hilbertSymbolAt_neg_one_eq_one_of_one_mod_four`: **at a prime congruent to
  one modulo four the symbol against minus one is trivial.**
* `InverseGalois.CFT.hilbertSymbolAt_two_neg_one_of_odd_trivial`: the dyadic symbol against minus
  one is the sign, as soon as all the odd symbols against minus one are trivial.
* `InverseGalois.CFT.hilbertSymbolAt_two_neg_one_intCast`: **the dyadic symbol of an integer
  against minus one is its sign** when every odd prime factor is congruent to one modulo four.
* `InverseGalois.CFT.hilbertSymbolAt_two_neg_one_prime_of_three_mod_four`: a prime congruent to
  three modulo four is positive and has nontrivial dyadic symbol against minus one.

## Tags

Hilbert symbol, quartic character, product formula, quadratic reciprocity
-/

namespace InverseGalois.CFT

open Local

/-! ### The symbol at an odd prime -/

/-- A prime does not divide one. -/
theorem not_dvd_one_of_prime {p : Nat.Primes} : ¬ ((p : ℕ) : ℤ) ∣ (1 : ℤ) := by
  intro h
  rw [show (1 : ℤ) = ((1 : ℕ) : ℤ) by norm_num, Int.natCast_dvd_natCast] at h
  exact p.2.one_lt.ne' (Nat.dvd_one.mp h)

/-- **The symbol of minus one against an odd prime, at that prime, is the quartic character.** -/
theorem hilbertSymbolAt_neg_one_self {p : Nat.Primes} (hp2 : (p : ℕ) ≠ 2) :
    hilbertSymbolAt p (-1) (((p : ℕ) : ℚ)) = ZMod.χ₄ ((p : ℕ) : ZMod 4) := by
  rw [hilbertSymbolAt_comm]
  have h := hilbertSymbolAt_coe_intCast hp2 (not_dvd_neg_one p.2)
  rw [show (((-1 : ℤ) : ℚ)) = (-1 : ℚ) by norm_num] at h
  rw [h, legendreSym.at_neg_one hp2]

/-- At a prime congruent to one modulo four, minus one is a square, so the symbol of minus one
against that prime is trivial. -/
theorem hilbertSymbolAt_neg_one_self_of_one_mod_four {p : Nat.Primes} (hp : (p : ℕ) % 4 = 1) :
    hilbertSymbolAt p (-1) (((p : ℕ) : ℚ)) = 1 := by
  rw [hilbertSymbolAt_neg_one_self (by omega), ZMod.χ₄_nat_one_mod_four hp]

/-- At a prime congruent to three modulo four, minus one is a nonresidue, so the symbol of minus
one against that prime is nontrivial. -/
theorem hilbertSymbolAt_neg_one_self_of_three_mod_four {p : Nat.Primes} (hp : (p : ℕ) % 4 = 3) :
    hilbertSymbolAt p (-1) (((p : ℕ) : ℚ)) = -1 := by
  rw [hilbertSymbolAt_neg_one_self (by omega), ZMod.χ₄_nat_three_mod_four hp]

/-- **At a prime congruent to one modulo four the symbol against minus one is trivial**, whatever
the second argument: minus one is a square in the square-class group of that local field, and the
square classes of the rationals are generated by minus one and the primes. -/
theorem hilbertSymbolAt_neg_one_eq_one_of_one_mod_four {p : Nat.Primes} (hp : (p : ℕ) % 4 = 1)
    {d : ℚ} (hd : d ≠ 0) : hilbertSymbolAt p (-1) d = 1 := by
  have hp2 : (p : ℕ) ≠ 2 := by omega
  have hneg : (-1 : ℚ) ≠ 0 := by norm_num
  refine Rat.induction_on_prime_mul_sq
    (motive := fun x => hilbertSymbolAt p (-1) x = 1) ?_ ?_ ?_ ?_ hd
  · simpa using hilbertSymbolAt_intCast_eq_one (p := p) hp2 (m := -1) (n := 1)
      (not_dvd_neg_one p.2) not_dvd_one_of_prime
  · simpa using hilbertSymbolAt_intCast_eq_one (p := p) hp2 (m := -1) (n := -1)
      (not_dvd_neg_one p.2) (not_dvd_neg_one p.2)
  · intro r a hr ha ih
    have hr0 : ((r : ℚ)) ≠ 0 := Nat.cast_ne_zero.mpr hr.pos.ne'
    rw [hilbertSymbolAt_mul_right hp2 hneg hr0 ha, ih, mul_one]
    by_cases hrp : r = (p : ℕ)
    · rw [hrp]
      exact hilbertSymbolAt_neg_one_self_of_one_mod_four hp
    · simpa using hilbertSymbolAt_intCast_eq_one (p := p) hp2 (m := -1) (n := (r : ℤ))
        (not_dvd_neg_one p.2) (not_dvd_of_prime_ne p.2 hr fun h => hrp h.symm)
  · intro a c ha hc ih
    rw [hilbertSymbolAt_mul_sq_right p (-1) a c hc, ih]

/-! ### The symbol at the dyadic place -/

/-- **The dyadic symbol against minus one is the sign** of a rational all of whose symbols against
minus one at the odd primes are trivial: the product formula leaves exactly the dyadic place and
the real place, and at the real place the symbol against minus one is the sign. -/
theorem hilbertSymbolAt_two_neg_one_of_odd_trivial {d : ℚ} (hd : d ≠ 0)
    (h : ∀ p : Nat.Primes, (p : ℕ) ≠ 2 → hilbertSymbolAt p (-1) d = 1) :
    hilbertSymbolAt primeTwo (-1) d = if d < 0 then -1 else 1 := by
  have hneg : (-1 : ℚ) ≠ 0 := by norm_num
  have hdr : ((d : ℝ)) ≠ 0 := by exact_mod_cast hd
  have hside : ∀ p : Nat.Primes, p ∉ ({primeTwo} : Finset Nat.Primes) →
      hilbertSymbolAt p (-1) d = 1 := fun p hp =>
    h p fun hp2 => hp (Finset.mem_singleton.mpr (Subtype.ext hp2))
  have hprod : hilbertProduct (-1) d = 1 := hilbertProduct_eq_one hneg hd
  rw [hilbertProduct_eq_prod_of_subset (-1) d {primeTwo} hside, Finset.prod_singleton,
    show (((-1 : ℚ)) : ℝ) = (-1 : ℝ) by norm_num,
    hilbertSymbol_real (-1 : ℝ) ((d : ℝ)) (by norm_num) hdr] at hprod
  by_cases hlt : d < 0
  · rw [if_pos hlt]
    rw [if_pos ⟨by norm_num, by exact_mod_cast hlt⟩] at hprod
    omega
  · rw [if_neg hlt]
    rw [if_neg fun hc => hlt (by exact_mod_cast hc.2)] at hprod
    omega

/-- **The dyadic symbol of an integer against minus one is its sign** when every odd prime factor
of the integer is congruent to one modulo four. -/
theorem hilbertSymbolAt_two_neg_one_intCast {d : ℤ} (hd : d ≠ 0)
    (h : ∀ p : ℕ, p.Prime → p ≠ 2 → (p : ℤ) ∣ d → p % 4 = 1) :
    hilbertSymbolAt primeTwo (-1) ((d : ℚ)) = if d < 0 then -1 else 1 := by
  have hdq : ((d : ℚ)) ≠ 0 := Int.cast_ne_zero.mpr hd
  rw [hilbertSymbolAt_two_neg_one_of_odd_trivial hdq ?odd]
  case odd =>
    intro p hp2
    by_cases hdvd : ((p : ℕ) : ℤ) ∣ d
    · exact hilbertSymbolAt_neg_one_eq_one_of_one_mod_four (h _ p.2 hp2 hdvd) hdq
    · simpa using hilbertSymbolAt_intCast_eq_one (p := p) hp2 (m := -1) (n := d)
        (not_dvd_neg_one p.2) hdvd
  simp

/-- **A positive integer whose odd prime factors are all congruent to one modulo four has trivial
dyadic symbol against minus one.** -/
theorem hilbertSymbolAt_two_neg_one_eq_one_of_pos {d : ℤ} (hd : 0 < d)
    (h : ∀ p : ℕ, p.Prime → p ≠ 2 → (p : ℤ) ∣ d → p % 4 = 1) :
    hilbertSymbolAt primeTwo (-1) ((d : ℚ)) = 1 := by
  rw [hilbertSymbolAt_two_neg_one_intCast hd.ne' h, if_neg (by omega)]

/-- **A positive integer whose odd prime factors are all congruent to one modulo four can never
have nontrivial dyadic symbol against minus one.**  The pair consisting of a nontrivial symbol at
the dyadic place and a trivial symbol at the real place is out of reach of such integers. -/
theorem hilbertSymbolAt_two_neg_one_ne_neg_one_of_pos {d : ℤ} (hd : 0 < d)
    (h : ∀ p : ℕ, p.Prime → p ≠ 2 → (p : ℤ) ∣ d → p % 4 = 1) :
    hilbertSymbolAt primeTwo (-1) ((d : ℚ)) ≠ -1 := by
  rw [hilbertSymbolAt_two_neg_one_eq_one_of_pos hd h]
  omega

/-- **A prime congruent to three modulo four has nontrivial dyadic symbol against minus one**,
while being positive at the real place: it realizes the pair that is out of reach of the integers
whose odd prime factors are all congruent to one modulo four. -/
theorem hilbertSymbolAt_two_neg_one_prime_of_three_mod_four {q : ℕ} (hq : q.Prime)
    (hq4 : q % 4 = 3) : hilbertSymbolAt primeTwo (-1) ((q : ℚ)) = -1 := by
  have hq2 : q ≠ 2 := by omega
  set qq : Nat.Primes := ⟨q, hq⟩ with hqq
  have hne : primeTwo ≠ qq := fun h => hq2 (congrArg Subtype.val h).symm
  have hside : ∀ p : Nat.Primes, p ∉ ({primeTwo, qq} : Finset Nat.Primes) →
      hilbertSymbolAt p (-1) ((q : ℚ)) = 1 := by
    intro p hp
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hp
    have hp2 : (p : ℕ) ≠ 2 := fun h => hp.1 (Subtype.ext h)
    have hpq : (p : ℕ) ≠ q := fun h => hp.2 (Subtype.ext h)
    simpa using hilbertSymbolAt_intCast_eq_one (p := p) hp2 (m := -1) (n := (q : ℤ))
      (not_dvd_neg_one p.2) (not_dvd_of_prime_ne p.2 hq hpq)
  have hprod : hilbertProduct (-1) ((q : ℚ)) = 1 := hilbertProduct_neg_one_prime hq hq2
  rw [hilbertProduct_eq_prod_of_subset (-1) ((q : ℚ)) {primeTwo, qq} hside,
    Finset.prod_pair hne,
    hilbertSymbol_real_of_pos_right (a := (((-1 : ℚ)) : ℝ)) (by norm_num)
      (by exact_mod_cast hq.pos)] at hprod
  have hqval : hilbertSymbolAt qq (-1) ((q : ℚ)) = -1 :=
    hilbertSymbolAt_neg_one_self_of_three_mod_four (p := qq) hq4
  rw [hqval] at hprod
  omega

end InverseGalois.CFT
