import Mathlib
import InverseGalois.CFT.Global.HilbertProduct
import InverseGalois.CFT.Local.DyadicHilbertMul
import InverseGalois.CFT.Local.LegendreHilbert

/-!
# The product formula for the pairs involving the prime two

The product over all places of the Hilbert symbols of a pair of nonzero rationals is trivial.
This file proves that statement for the generating pairs in which one of the two arguments is the
prime `2`: the pair `(-1, 2)`, the pair `(2, q)` for an odd prime `q`, and the pair `(2, 2)`.

In each case only two places contribute.  For `(-1, 2)` the only nontrivial place could be the
dyadic one, and there the symbol is trivial because `-1` is congruent to `7` modulo `8`.  For
`(2, q)` the dyadic symbol is the second supplementary law read off modulo `8`, and the symbol at
`q` is the Legendre symbol of `2`; the two agree, so their product is a square and hence one.  The
pair `(2, 2)` is the pair `(2, -1)` in disguise.

## Main results

* `InverseGalois.CFT.hilbertProduct_neg_one_two`: the product formula for `(-1, 2)`.
* `InverseGalois.CFT.hilbertProduct_two_prime`: the product formula for `(2, q)`, `q` an odd
  prime.
* `InverseGalois.CFT.hilbertProduct_two_two`: the product formula for `(2, 2)`.
-/

namespace InverseGalois.CFT

open Local

/-- A prime other than `2` does not divide `-1`. -/
theorem not_dvd_neg_one_of_prime {p : Nat.Primes} : ¬ ((p : ℕ) : ℤ) ∣ (-1 : ℤ) := by
  intro hdvd
  have h1 : ((p : ℕ) : ℤ) ∣ (1 : ℤ) := (dvd_neg).1 hdvd
  have h2 : ((p : ℕ) : ℤ) ≤ 1 := Int.le_of_dvd (by norm_num) h1
  have h3 : 2 ≤ (p : ℕ) := p.2.two_le
  omega

/-- A prime other than `2` does not divide `2`. -/
theorem not_dvd_two_of_ne_two {p : Nat.Primes} (hp : (p : ℕ) ≠ 2) :
    ¬ ((p : ℕ) : ℤ) ∣ (2 : ℤ) := by
  intro hdvd
  have hnat : (p : ℕ) ∣ 2 := by exact_mod_cast hdvd
  exact hp ((Nat.prime_dvd_prime_iff_eq p.2 Nat.prime_two).1 hnat)

/-- A prime other than `q` does not divide `q`. -/
theorem not_dvd_prime_of_ne {p : Nat.Primes} {q : ℕ} (hq : q.Prime) (hne : (p : ℕ) ≠ q) :
    ¬ ((p : ℕ) : ℤ) ∣ (q : ℤ) := by
  intro hdvd
  have hnat : (p : ℕ) ∣ q := by exact_mod_cast hdvd
  exact hne ((Nat.prime_dvd_prime_iff_eq p.2 hq).1 hnat)

/-- Membership in a singleton set of primes is an equality of the underlying naturals. -/
theorem eq_of_notMem_singleton {p : Nat.Primes} {n : ℕ} {hn : n.Prime}
    (h : p ∉ ({⟨n, hn⟩} : Finset Nat.Primes)) : (p : ℕ) ≠ n := fun he =>
  h (Finset.mem_singleton.2 (Subtype.ext he))

/-- The sign attached to a unit residue modulo `8` is the value there of the quadratic character
cutting out the extension generated by a square root of two. -/
theorem dyadicOmegaSign_eq_chi8 : ∀ r : ZMod 8, IsUnit r → dyadicOmegaSign r = ZMod.χ₈ r := by
  decide

/-- The residue modulo `8` of an integer prime to `2` is a unit. -/
theorem isUnit_intCast_zmod_eight {m : ℤ} (hm : ¬ ((2 : ℕ) : ℤ) ∣ m) :
    IsUnit ((m : ZMod 8)) := by
  have hu : IsUnit ((m : ℤ_[2])) := isUnit_intCast_of_not_dvd hm
  have hmap := hu.map (PadicInt.toZModPow (p := 2) 3)
  rwa [map_intCast] at hmap

/-- **The dyadic Hilbert symbol of `2` against an odd integer is the Legendre symbol of `2`.** -/
theorem hilbertSymbol_two_intCast_dyadic {m : ℤ} (hm : ¬ ((2 : ℕ) : ℤ) ∣ m) :
    hilbertSymbol (2 : ℚ_[2]) ((m : ℚ_[2])) = ZMod.χ₈ ((m : ZMod 8)) := by
  have hu : IsUnit ((m : ℤ_[2])) := isUnit_intCast_of_not_dvd hm
  have h := hilbertSymbol_two_unit hu
  rw [PadicInt.coe_intCast, map_intCast] at h
  rw [h]
  exact dyadicOmegaSign_eq_chi8 _ (isUnit_intCast_zmod_eight hm)

/-- **The product formula for the pair `(-1, 2)`.** -/
theorem hilbertProduct_neg_one_two : hilbertProduct (-1) 2 = 1 := by
  have hS : ∀ p : Nat.Primes, p ∉ ({⟨2, Nat.prime_two⟩} : Finset Nat.Primes) →
      hilbertSymbolAt p (-1 : ℚ) (2 : ℚ) = 1 := by
    intro p hp
    have hp2 : (p : ℕ) ≠ 2 := eq_of_notMem_singleton hp
    have h1 : ((-1 : ℚ)) = (((-1 : ℤ)) : ℚ) := by norm_num
    have h2 : ((2 : ℚ)) = (((2 : ℤ)) : ℚ) := by norm_num
    rw [h1, h2]
    exact hilbertSymbolAt_intCast_eq_one hp2 not_dvd_neg_one_of_prime (not_dvd_two_of_ne_two hp2)
  rw [hilbertProduct_eq_prod_of_subset _ _ _ hS, Finset.prod_singleton]
  have hreal : hilbertSymbol (((-1 : ℚ)) : ℝ) (((2 : ℚ)) : ℝ) = 1 := by
    rw [show (((-1 : ℚ)) : ℝ) = -1 by norm_num, show (((2 : ℚ)) : ℝ) = 2 by norm_num,
      hilbertSymbol_real (-1 : ℝ) 2 (by norm_num) (by norm_num)]
    norm_num
  have hdyad : hilbertSymbolAt (⟨2, Nat.prime_two⟩ : Nat.Primes) (-1 : ℚ) (2 : ℚ) = 1 := by
    unfold hilbertSymbolAt
    rw [show (((-1 : ℚ)) : ℚ_[2]) = ((-1 : ℤ) : ℚ_[2]) by norm_num,
      show (((2 : ℚ)) : ℚ_[2]) = (2 : ℚ_[2]) by norm_num, hilbertSymbol_comm,
      hilbertSymbol_two_intCast_dyadic (m := -1) (by decide)]
    decide
  rw [hreal, hdyad, mul_one]

/-- **The product formula for the pair `(2, q)` with `q` an odd prime.** -/
theorem hilbertProduct_two_prime {q : ℕ} (hq : q.Prime) (hq2 : q ≠ 2) :
    hilbertProduct 2 ((q : ℚ)) = 1 := by
  haveI : Fact q.Prime := ⟨hq⟩
  have hqp : (⟨q, hq⟩ : Nat.Primes) ≠ (⟨2, Nat.prime_two⟩ : Nat.Primes) := by
    intro h
    exact hq2 (congrArg (fun r : Nat.Primes => (r : ℕ)) h)
  have hnd2 : ¬ ((q : ℕ) : ℤ) ∣ (2 : ℤ) := not_dvd_two_of_ne_two (p := ⟨q, hq⟩) hq2
  have hndq : ¬ ((2 : ℕ) : ℤ) ∣ (q : ℤ) := by
    intro hdvd
    have hnat : (2 : ℕ) ∣ q := by exact_mod_cast hdvd
    exact hq2 (((Nat.prime_dvd_prime_iff_eq Nat.prime_two hq).1 hnat).symm)
  have hS : ∀ p : Nat.Primes,
      p ∉ ({⟨q, hq⟩, ⟨2, Nat.prime_two⟩} : Finset Nat.Primes) →
      hilbertSymbolAt p (2 : ℚ) ((q : ℚ)) = 1 := by
    intro p hp
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hp
    have hp2 : (p : ℕ) ≠ 2 := fun he => hp.2 (Subtype.ext he)
    have hpq : (p : ℕ) ≠ q := fun he => hp.1 (Subtype.ext he)
    have h2 : ((2 : ℚ)) = (((2 : ℤ)) : ℚ) := by norm_num
    have hqc : ((q : ℚ)) = (((q : ℤ)) : ℚ) := by push_cast; ring
    rw [h2, hqc]
    exact hilbertSymbolAt_intCast_eq_one hp2 (not_dvd_two_of_ne_two hp2)
      (not_dvd_prime_of_ne hq hpq)
  have hpair : (∏ p ∈ ({⟨q, hq⟩, ⟨2, Nat.prime_two⟩} : Finset Nat.Primes),
      hilbertSymbolAt p (2 : ℚ) ((q : ℚ)))
      = hilbertSymbolAt (⟨q, hq⟩ : Nat.Primes) (2 : ℚ) ((q : ℚ))
        * hilbertSymbolAt (⟨2, Nat.prime_two⟩ : Nat.Primes) (2 : ℚ) ((q : ℚ)) :=
    Finset.prod_pair hqp
  rw [hilbertProduct_eq_prod_of_subset _ _ _ hS, hpair]
  have hreal : hilbertSymbol (((2 : ℚ)) : ℝ) (((q : ℚ)) : ℝ) = 1 := by
    have hqpos : (0 : ℝ) < (q : ℝ) := by exact_mod_cast hq.pos
    rw [show (((2 : ℚ)) : ℝ) = 2 by norm_num, show (((q : ℚ)) : ℝ) = (q : ℝ) by push_cast; ring,
      hilbertSymbol_real (2 : ℝ) (q : ℝ) (by norm_num) (ne_of_gt hqpos)]
    simp only [ite_eq_right_iff, and_imp]
    intro h
    exact absurd h (by norm_num)
  have hatq : hilbertSymbolAt (⟨q, hq⟩ : Nat.Primes) (2 : ℚ) ((q : ℚ)) = legendreSym q 2 := by
    unfold hilbertSymbolAt
    rw [show (((2 : ℚ)) : ℚ_[q]) = ((2 : ℤ) : ℚ_[q]) by norm_num,
      show (((q : ℚ)) : ℚ_[q]) = ((q : ℕ) : ℚ_[q]) by push_cast; ring]
    exact hilbertSymbol_intCast_p hq2 hnd2
  have hat2 : hilbertSymbolAt (⟨2, Nat.prime_two⟩ : Nat.Primes) (2 : ℚ) ((q : ℚ))
      = legendreSym q 2 := by
    unfold hilbertSymbolAt
    rw [show (((2 : ℚ)) : ℚ_[2]) = (2 : ℚ_[2]) by norm_num,
      show (((q : ℚ)) : ℚ_[2]) = ((q : ℤ) : ℚ_[2]) by push_cast; ring,
      hilbertSymbol_two_intCast_dyadic hndq, legendreSym.at_two hq2]
    congr 1
  rw [hreal, hatq, hat2, one_mul, ← sq]
  exact legendreSym_sq (p := q) hnd2

/-- **The product formula for the pair `(2, 2)`.** -/
theorem hilbertProduct_two_two : hilbertProduct 2 2 = 1 := by
  rw [hilbertProduct_self (a := (2 : ℚ)) (by norm_num), hilbertProduct_comm]
  exact hilbertProduct_neg_one_two

end InverseGalois.CFT
