/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.StructureCount
import InverseGalois.Rigidity.Rigidity
import InverseGalois.Rigidity.RET.Descent
import Mathieu.EnumM11

/-!
# A rationally rigid class triple in `Aut(M₂₂)`

The Mathieu group `M₂₂` has no rigid class triple at all, but its automorphism group
`Aut(M₂₂) = M₂₂ : 2` has one, and — unlike every triple available inside a Mathieu group
itself — all three of its classes are **rational**.  This file certifies that triple in the
Lean kernel, and therefore realises `Aut(M₂₂)` as a regular Galois group over `ℚ(T)`.

The triple is Matzat's `(2B, 4C, 11A)`: an outer involution of cycle type `2⁷1⁹`, an outer
element of cycle type `4⁴2³1¹` acting without fixed points on the `22` moving points, and the
inner class of order `11` (the fusion of the two `M₂₂`-classes `11A`, `11B`).

## The concrete model

`Aut(M₂₂)` is realised inside `Perm (Fin 23)` exactly where `M₂₂` itself sits, as a group of
permutations of `{0, …, 21}` fixing `22`.  It is generated by two elements:

* `sigma22 = (0 17)(2 6)(3 13)(4 19)(5 21)(8 15)(9 20)`, an outer involution of class `2B`;
* `zPerm = (0 7 19 8 14 12 20 10 9 15 5)(1 11 3 4 18 17 21 13 2 16 6)`, an element of order
  eleven — it is the Schreier generator `EnumM22.schB 7` of the vendored `M₂₂`.

Their product-one partner `y = x⁻¹ z⁻¹` has cycle type `4⁴2³1¹`, and the structure constant
`#{w ∈ 2B : w⁻¹ z⁻¹ ∈ 4C}` equals `11 = |C(z)|`, which by `Rigidity.rigid_of_card_prodOneFibre`
is rigidity.

## How the count is certified

Permutations are handled in a base-`23` integer encoding (`enc23`, `dec23`, `φ23`) with a
multiplication `mulC23` of encoded permutations, the exact analogue of the base-`11` encoding of
`Mathieu.EnumM11`.  The class `2B` is stored as a binary search-tree literal `TX` with `330`
keys, checked by `decide` to be closed under conjugation by the two generators and their
inverses; since `Btree.mem` is one-sidedly sound, that gives the containment *class ⊆ tree*,
which is all an upper bound on the fibre needs.  The second class is cut out by the pair of
conjugation-invariant tests `q⁴ = 1` and "`q` moves every one of the points `0, …, 21`";
filtering `TX` by that test applied to `w z⁻¹` leaves exactly `11` keys.

Nothing here uses `native_decide`.

## Main results

* `Rigidity.MathieuM22.center_eq_bot` — `Aut(M₂₂)` is centerless.
* `Rigidity.MathieuM22.gen_top` — the pair `x, z` generates.
* `Rigidity.MathieuM22.rigid_triple` — `Nat.card (rigidTuples classTriple) = Nat.card (Aut M₂₂)`.
* `Rigidity.MathieuM22.cert` — the resulting `RigidityCertificate`.
* `Rigidity.MathieuM22.isRegularInverseGalois` — `Aut(M₂₂)` is a regular Galois group over `ℚ(T)`.
-/

namespace Rigidity

namespace MathieuM22

open Equiv Mathieu Mathieu.EnumM11

set_option maxHeartbeats 4000000
set_option maxRecDepth 1000000

/-! ### The base-`23` encoding of permutations -/

/-- Encode an image vector `f : Fin 23 → Fin 23` as the base-`23` numeral
`∑ i, (f i) * 23 ^ i`. -/
def enc23 (f : Fin 23 → Fin 23) : ℕ := ∑ i : Fin 23, (f i).val * 23 ^ (i : ℕ)

/-- Decode a natural number back to an image vector (`i`-th base-`23` digit). -/
def dec23 (n : ℕ) : Fin 23 → Fin 23 :=
  fun i => ⟨(n / 23 ^ (i : ℕ)) % 23, Nat.mod_lt _ (by norm_num)⟩

/-- Apply a permutation `g` to an encoded permutation: decode, left-multiply, re-encode. -/
def applyGenF23 (g : Perm (Fin 23)) (n : ℕ) : ℕ := enc23 (fun i => g (dec23 n i))

/-- Encoding of the identity permutation. -/
def idCode23 : ℕ := enc23 id

/-- The encoding of a permutation by its image vector. -/
def φ23 (p : Perm (Fin 23)) : ℕ := enc23 (fun i => p i)

lemma enc23_eq (f : Fin 23 → Fin 23) : enc23 f = (finFunctionFinEquiv f).val := by
  rw [finFunctionFinEquiv_apply_val]; rfl

lemma dec23_enc23 (f : Fin 23 → Fin 23) : dec23 (enc23 f) = f := by
  funext j
  apply Fin.ext
  show (enc23 f / 23 ^ (j : ℕ)) % 23 = (f j).val
  have h := finFunctionFinEquiv_symm_apply_val (finFunctionFinEquiv f) j
  rw [Equiv.symm_apply_apply] at h
  rw [enc23_eq]; omega

lemma φ23_injective : Function.Injective φ23 := by
  intro p q h
  have h2 : dec23 (φ23 p) = dec23 (φ23 q) := by rw [h]
  rw [φ23, φ23, dec23_enc23, dec23_enc23] at h2
  exact Equiv.ext (fun i => congrFun h2 i)

lemma applyGenF23_φ23 (g p : Perm (Fin 23)) : applyGenF23 g (φ23 p) = φ23 (g * p) := by
  unfold applyGenF23 φ23
  rw [dec23_enc23]
  congr 1

lemma φ23_one : φ23 1 = idCode23 := by
  unfold φ23 idCode23
  congr 1

/-- Kernel-friendly digit-permutation apply (no `Finset.sum`): permutes the base-`23` digits of
`n` by the table `t`. -/
def stepImg23 (t : ℕ → ℕ) (n : ℕ) : ℕ :=
  t (n / 23^0 % 23) + 23*(t (n / 23^1 % 23) + 23*(t (n / 23^2 % 23) + 23*(t (n / 23^3 % 23)
  + 23*(t (n / 23^4 % 23) + 23*(t (n / 23^5 % 23) + 23*(t (n / 23^6 % 23) + 23*(t (n / 23^7 % 23)
  + 23*(t (n / 23^8 % 23) + 23*(t (n / 23^9 % 23) + 23*(t (n / 23^10 % 23)
  + 23*(t (n / 23^11 % 23) + 23*(t (n / 23^12 % 23) + 23*(t (n / 23^13 % 23)
  + 23*(t (n / 23^14 % 23) + 23*(t (n / 23^15 % 23) + 23*(t (n / 23^16 % 23)
  + 23*(t (n / 23^17 % 23) + 23*(t (n / 23^18 % 23) + 23*(t (n / 23^19 % 23)
  + 23*(t (n / 23^20 % 23) + 23*(t (n / 23^21 % 23)
  + 23*(t (n / 23^22 % 23)))))))))))))))))))))))

/-- Generic bridge: a permutation `g` whose value table on `0..22` is `t` acts on encoded codes
as `stepImg23 t`. -/
lemma stepImg23_bridge (g : Perm (Fin 23)) (t : ℕ → ℕ)
    (h : ∀ x : Fin 23, (g x).val = t x.val) (n : ℕ) : stepImg23 t n = applyGenF23 g n := by
  simp only [applyGenF23, enc23, stepImg23, Fin.sum_univ_succ, Fin.sum_univ_zero, h, dec23,
    Fin.val_succ, Fin.val_zero]
  ring

/-! ### Multiplication of encoded permutations -/

/-- The `j`-th base-`23` digit of a code. -/
def dg23 (a j : ℕ) : ℕ := a / 23 ^ j % 23

/-- Product of two encoded permutations: permute the digits of the right factor by the digit
table of the left factor. -/
def mulC23 (a b : ℕ) : ℕ := stepImg23 (dg23 a) b

lemma dg23_φ23 (g : Perm (Fin 23)) (i : Fin 23) : (g i).val = dg23 (φ23 g) i.val := by
  have h : dec23 (φ23 g) = fun i => g i := dec23_enc23 _
  exact (congrArg Fin.val (congrFun h i)).symm

lemma mulC23_φ23 (g p : Perm (Fin 23)) : mulC23 (φ23 g) (φ23 p) = φ23 (g * p) := by
  rw [mulC23, stepImg23_bridge g (dg23 (φ23 g)) (dg23_φ23 g), applyGenF23_φ23]

lemma mulC23_conj (g q : Perm (Fin 23)) :
    mulC23 (φ23 g) (mulC23 (φ23 q) (φ23 g⁻¹)) = φ23 (g * q * g⁻¹) := by
  rw [mulC23_φ23, mulC23_φ23, mul_assoc]

lemma mulC23_conj' (g q : Perm (Fin 23)) :
    mulC23 (φ23 g⁻¹) (mulC23 (φ23 q) (φ23 g)) = φ23 (g⁻¹ * q * g) := by
  rw [mulC23_φ23, mulC23_φ23, mul_assoc]

/-! ### The group `Aut(M₂₂)` and its two generators -/

/-- The outer involution of class `2B`, of cycle type `2⁷1⁹`. -/
def sigma22 : Perm (Fin 23) :=
  c[0, 17] * c[2, 6] * c[3, 13] * c[4, 19] * c[5, 21] * c[8, 15] * c[9, 20]

/-- The element of order eleven, of cycle type `11²1¹`.  It is the Schreier generator
`EnumM22.schB 7` of `M₂₂`. -/
def zPerm : Perm (Fin 23) :=
  c[0, 7, 19, 8, 14, 12, 20, 10, 9, 15, 5] * c[1, 11, 3, 4, 18, 17, 21, 13, 2, 16, 6]

/-- **`Aut(M₂₂) = M₂₂ : 2`**, as the subgroup of `Perm (Fin 23)` generated by `sigma22` and
`zPerm`. -/
def AutM22 : Subgroup (Perm (Fin 23)) := Subgroup.closure {sigma22, zPerm}

lemma sigma22_mem : sigma22 ∈ AutM22 := Subgroup.subset_closure (Set.mem_insert _ _)

lemma zPerm_mem : zPerm ∈ AutM22 := Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)

lemma zPerm_inv_mem : zPerm⁻¹ ∈ AutM22 := inv_mem zPerm_mem

lemma sigma22_sq : sigma22 * sigma22 = 1 := by decide

lemma sigma22_inv : sigma22⁻¹ = sigma22 := by decide

/-- Every element of `Aut(M₂₂)` fixes the point `22`. -/
theorem fix22 {g : Perm (Fin 23)} (hg : g ∈ AutM22) : g (22 : Fin 23) = 22 := by
  induction hg using Subgroup.closure_induction with
  | mem u hu =>
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hu
    rcases hu with rfl | rfl
    · decide
    · decide
  | one => rfl
  | mul a b _ _ ha hb => rw [Equiv.Perm.mul_apply, hb, ha]
  | inv a _ ha =>
    have h : a⁻¹ (22 : Fin 23) = a⁻¹ (a (22 : Fin 23)) := by rw [ha]
    rw [h]
    simp

/-! ### The three elements of the triple -/

/-- The involution of the triple, as an element of `Aut(M₂₂)`. -/
def xEl : ↥AutM22 := ⟨sigma22, sigma22_mem⟩

/-- The order-eleven element of the triple. -/
def zEl : ↥AutM22 := ⟨zPerm, zPerm_mem⟩

/-- The remaining entry of the triple, forced by the product-one relation. -/
def yEl : ↥AutM22 := xEl⁻¹ * zEl⁻¹

/-- The underlying permutation of the third entry. -/
def y0 : Perm (Fin 23) := sigma22⁻¹ * zPerm⁻¹

lemma yEl_coe : ((yEl : ↥AutM22) : Perm (Fin 23)) = y0 := rfl

/-- The triple of conjugacy classes `(2B, 4C, 11A)` of `Aut(M₂₂)`. -/
def classTriple : Fin 3 → ConjClasses ↥AutM22 :=
  ![ConjClasses.mk xEl, ConjClasses.mk yEl, ConjClasses.mk zEl]

lemma classTriple_zero : classTriple 0 = ConjClasses.mk xEl := rfl
lemma classTriple_one : classTriple 1 = ConjClasses.mk yEl := rfl
lemma classTriple_two : classTriple 2 = ConjClasses.mk zEl := rfl

lemma xEl_sq : xEl * xEl = 1 := Subtype.ext sigma22_sq

lemma xEl_inv : xEl⁻¹ = xEl := inv_eq_of_mul_eq_one_right xEl_sq

/-! ### Codes of the generators -/

/-- Code of `sigma22`. -/
def cX : ℕ := 20185781845176427302910320575947
/-- Code of `zPerm`. -/
def cZ : ℕ := 20503568791607425089700758443787
/-- Code of `zPerm⁻¹`. -/
def cZi : ℕ := 20664770203669172973369563573999

lemma cX_eq : φ23 sigma22 = cX := by decide
lemma cZ_eq : φ23 zPerm = cZ := by decide
lemma cZi_eq : φ23 zPerm⁻¹ = cZi := by decide

lemma idCode23_eq : idCode23 = 20837326537038308910317109288851 := by decide

/-- Conjugation by `sigma22` in codes, using that it is its own inverse. -/
lemma mulC23_conj_x (q : Perm (Fin 23)) :
    mulC23 cX (mulC23 (φ23 q) cX) = φ23 (sigma22 * q * sigma22) := by
  rw [← cX_eq, mulC23_φ23, mulC23_φ23, mul_assoc]

/-! ### Conjugation-closed sets of codes

A tree of codes closed under conjugation by the two generators and their inverses contains the
whole `Aut(M₂₂)`-conjugacy class of each of its keys.  Only the one-sided soundness of
`Btree.mem` is used, so no search-tree invariant is needed. -/

/-- The conjugation-closure test for a tree of codes. -/
abbrev ConjClosed (T : Btree) : Prop :=
  T.all (fun k => T.mem (mulC23 cX (mulC23 k cX)) && T.mem (mulC23 cZ (mulC23 k cZi)) &&
    T.mem (mulC23 cZi (mulC23 k cZ))) = true

lemma conj_gen_key {T : Btree} (hcl : ConjClosed T) {q : Perm (Fin 23)}
    (hq : T.mem (φ23 q) = true) :
    T.mem (φ23 (sigma22 * q * sigma22⁻¹)) = true ∧
      T.mem (φ23 (sigma22⁻¹ * q * sigma22)) = true ∧
      T.mem (φ23 (zPerm * q * zPerm⁻¹)) = true ∧ T.mem (φ23 (zPerm⁻¹ * q * zPerm)) = true := by
  have h := Btree.all_toList hcl _ (Btree.mem_toList hq)
  simp only [Bool.and_eq_true] at h
  obtain ⟨⟨h1, h2⟩, h3⟩ := h
  rw [mulC23_conj_x] at h1
  rw [← cZ_eq, ← cZi_eq, mulC23_conj] at h2
  rw [← cZi_eq, ← cZ_eq, mulC23_conj'] at h3
  exact ⟨by rw [sigma22_inv]; exact h1, by rw [sigma22_inv]; exact h1, h2, h3⟩

/-- Closure under conjugation by the generators propagates to all of `Aut(M₂₂)`. -/
theorem conj_key {T : Btree} (hcl : ConjClosed T) {c : Perm (Fin 23)} (hc : c ∈ AutM22)
    {p : Perm (Fin 23)} (hp : T.mem (φ23 p) = true) : T.mem (φ23 (c * p * c⁻¹)) = true := by
  have hc' : c ∈ Subgroup.closure ({sigma22, zPerm} : Set (Perm (Fin 23))) := hc
  refine Subgroup.closure_induction_left
    (p := fun c _ => ∀ q : Perm (Fin 23), T.mem (φ23 q) = true →
      T.mem (φ23 (c * q * c⁻¹)) = true) ?_ ?_ ?_ hc' p hp
  · intro q hq; simpa using hq
  · intro g hg u _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hstep : g * u * q * (g * u)⁻¹ = g * (u * q * u⁻¹) * g⁻¹ := by group
    rw [hstep]
    rcases hg with rfl | rfl
    · exact (conj_gen_key hcl (ih q hq)).1
    · exact (conj_gen_key hcl (ih q hq)).2.2.1
  · intro g hg u _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hstep : g⁻¹ * u * q * (g⁻¹ * u)⁻¹ = g⁻¹ * (u * q * u⁻¹) * g := by group
    rw [hstep]
    rcases hg with rfl | rfl
    · exact (conj_gen_key hcl (ih q hq)).2.1
    · exact (conj_gen_key hcl (ih q hq)).2.2.2

/-- Every member of the conjugacy class of a key is again a key. -/
theorem key_of_conjClass {T : Btree} (hcl : ConjClosed T) {p : Perm (Fin 23)}
    (hp : T.mem (φ23 p) = true) {u w : ↥AutM22} (hu : (u : Perm (Fin 23)) = p)
    (hw : ConjClasses.mk w = ConjClasses.mk u) : T.mem (φ23 (w : Perm (Fin 23))) = true := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have hval : (c : Perm (Fin 23)) * (w : Perm (Fin 23)) * ((c : Perm (Fin 23)))⁻¹ = p := by
    rw [← hu, ← hc]; rfl
  have hw' : (w : Perm (Fin 23)) = ((c : Perm (Fin 23)))⁻¹ * p * (((c : Perm (Fin 23)))⁻¹)⁻¹ := by
    rw [← hval]; group
  rw [hw']
  exact conj_key hcl (inv_mem c.2) hp

/-! ### `Aut(M₂₂)` is centerless

The element `q0` below has exactly two fixed points, `0` and `22`.  A central element commutes
with it, hence permutes its fixed points; since everything in `Aut(M₂₂)` fixes `22`, a central
element must fix `0` as well.  Commuting with `zPerm` then propagates the fixed point along the
`zPerm`-orbit of `0`, and commuting with `sigma22` jumps to `17`, whose `zPerm`-orbit is the
remaining half of the `22` moving points. -/

/-- A word in the two generators with exactly two fixed points, `0` and `22`. -/
def q0 : Perm (Fin 23) :=
  zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ * sigma22 * zPerm * sigma22

lemma q0_mem : q0 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hzi hzi) hzi) hs) hzi)
    hs) hz) hs)

lemma q0_fix : ∀ a : Fin 23, q0 a = a → a = 0 ∨ a = 22 := by decide

theorem center_eq_bot : Subgroup.center (↥AutM22) = ⊥ := by
  rw [eq_bot_iff]
  intro w hw
  rw [Subgroup.mem_bot]
  have hcomm : ∀ (g : Perm (Fin 23)) (hg : g ∈ AutM22),
      g * (w : Perm (Fin 23)) = (w : Perm (Fin 23)) * g := by
    intro g hg
    exact congrArg Subtype.val (Subgroup.mem_center_iff.mp hw ⟨g, hg⟩)
  have hstep : ∀ (g : Perm (Fin 23)) (_ : g ∈ AutM22) (a b : Fin 23), g a = b →
      (w : Perm (Fin 23)) a = a → (w : Perm (Fin 23)) b = b := by
    intro g hg a b hab ha
    have h := congrFun (congrArg (fun p : Perm (Fin 23) => (p : Fin 23 → Fin 23))
      (hcomm g hg)) a
    simp only [Equiv.Perm.coe_mul, Function.comp_apply] at h
    rw [ha, hab] at h
    exact h.symm
  have keyZ : ∀ a b : Fin 23, zPerm a = b → (w : Perm (Fin 23)) a = a →
      (w : Perm (Fin 23)) b = b := hstep zPerm zPerm_mem
  have f22 : (w : Perm (Fin 23)) (22 : Fin 23) = 22 := fix22 w.2
  have f0 : (w : Perm (Fin 23)) (0 : Fin 23) = 0 := by
    -- `q0` fixes `0`, so `w 0` is a fixed point of `q0`
    have hq := congrFun (congrArg (fun p : Perm (Fin 23) => (p : Fin 23 → Fin 23))
      (hcomm q0 q0_mem)) (0 : Fin 23)
    simp only [Equiv.Perm.coe_mul, Function.comp_apply] at hq
    rw [show q0 (0 : Fin 23) = 0 from by decide] at hq
    rcases q0_fix _ hq with h0 | h0
    · exact h0
    · exfalso
      have : (w : Perm (Fin 23)) (0 : Fin 23) = (w : Perm (Fin 23)) (22 : Fin 23) := by
        rw [h0, f22]
      exact absurd ((w : Perm (Fin 23)).injective this) (by decide)
  have f17 : (w : Perm (Fin 23)) (17 : Fin 23) = 17 :=
    hstep sigma22 sigma22_mem 0 17 (by decide) f0
  have f7 : (w : Perm (Fin 23)) (7 : Fin 23) = 7 := keyZ 0 7 (by decide) f0
  have f19 : (w : Perm (Fin 23)) (19 : Fin 23) = 19 := keyZ 7 19 (by decide) f7
  have f8 : (w : Perm (Fin 23)) (8 : Fin 23) = 8 := keyZ 19 8 (by decide) f19
  have f14 : (w : Perm (Fin 23)) (14 : Fin 23) = 14 := keyZ 8 14 (by decide) f8
  have f12 : (w : Perm (Fin 23)) (12 : Fin 23) = 12 := keyZ 14 12 (by decide) f14
  have f20 : (w : Perm (Fin 23)) (20 : Fin 23) = 20 := keyZ 12 20 (by decide) f12
  have f10 : (w : Perm (Fin 23)) (10 : Fin 23) = 10 := keyZ 20 10 (by decide) f20
  have f9 : (w : Perm (Fin 23)) (9 : Fin 23) = 9 := keyZ 10 9 (by decide) f10
  have f15 : (w : Perm (Fin 23)) (15 : Fin 23) = 15 := keyZ 9 15 (by decide) f9
  have f5 : (w : Perm (Fin 23)) (5 : Fin 23) = 5 := keyZ 15 5 (by decide) f15
  have f21 : (w : Perm (Fin 23)) (21 : Fin 23) = 21 := keyZ 17 21 (by decide) f17
  have f13 : (w : Perm (Fin 23)) (13 : Fin 23) = 13 := keyZ 21 13 (by decide) f21
  have f2 : (w : Perm (Fin 23)) (2 : Fin 23) = 2 := keyZ 13 2 (by decide) f13
  have f16 : (w : Perm (Fin 23)) (16 : Fin 23) = 16 := keyZ 2 16 (by decide) f2
  have f6 : (w : Perm (Fin 23)) (6 : Fin 23) = 6 := keyZ 16 6 (by decide) f16
  have f1 : (w : Perm (Fin 23)) (1 : Fin 23) = 1 := keyZ 6 1 (by decide) f6
  have f11 : (w : Perm (Fin 23)) (11 : Fin 23) = 11 := keyZ 1 11 (by decide) f1
  have f3 : (w : Perm (Fin 23)) (3 : Fin 23) = 3 := keyZ 11 3 (by decide) f11
  have f4 : (w : Perm (Fin 23)) (4 : Fin 23) = 4 := keyZ 3 4 (by decide) f3
  have f18 : (w : Perm (Fin 23)) (18 : Fin 23) = 18 := keyZ 4 18 (by decide) f4
  apply Subtype.ext
  refine Equiv.ext fun a => ?_
  show (w : Perm (Fin 23)) a = a
  fin_cases a
  exacts [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18,
    f19, f20, f21, f22]

/-! ### The pair generates -/

theorem gen_top : Subgroup.closure ({xEl, zEl} : Set ↥AutM22) = ⊤ := by
  have h : ({xEl, zEl} : Set ↥AutM22)
      = ((↑) : ↥AutM22 → Perm (Fin 23)) ⁻¹' ({sigma22, zPerm} : Set (Perm (Fin 23))) := by
    ext g
    simp only [Set.mem_preimage, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro (rfl | rfl)
      exacts [Or.inl rfl, Or.inr rfl]
    · rintro (hg | hg)
      exacts [Or.inl (Subtype.ext hg), Or.inr (Subtype.ext hg)]
  rw [h]
  exact Subgroup.closure_closure_coe_preimage

/-! ### The class tree -/

/-- The `330` codes of the class `2B` of `Aut(M₂₂)` (the outer involutions of cycle type
`2⁷1⁹`). -/
noncomputable def TX : Btree :=
  ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd (
  Btree.nd Btree.lf 19976411504044854662423982499643 Btree.lf ) 19977516243953036244941367270137
  Btree.lf ) 19992796477528687739045783960197 ( Btree.nd ( Btree.nd Btree.lf
  19992977821754450019686087435879 Btree.lf ) 19997079881608653544599001290871 Btree.lf ) )
  19998090588596611405741058496297 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20007266656976922202517633940769 Btree.lf ) 20007360556579900790747473947077 Btree.lf )
  20008274259535983487635933402467 ( Btree.nd Btree.lf 20008390788462827757782630904137 Btree.lf )
  ) ) 20030254222839865539608658591611 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20030285600288621851889066777637 Btree.lf ) 20035157188955522641761776621667 Btree.lf )
  20035210212328195570604403334685 ( Btree.nd Btree.lf 20046250211161607006745458450097 Btree.lf )
  ) 20046253254964925180528587758639 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20047841764511690365324595137521 Btree.lf ) 20047863537515884308193003768225 Btree.lf )
  20047891736081607885593136874415 ( Btree.nd Btree.lf 20047894786284691945118751677129 Btree.lf )
  ) ) ) 20052819491935505985536415801553 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd
  Btree.lf 20052987043112802247321660309711 Btree.lf ) 20071097138289364417941766431675 Btree.lf )
  20071921034763584007021832651193 ( Btree.nd ( Btree.nd Btree.lf 20076547146465882385484776775115
  Btree.lf ) 20077038046734823971432402815061 Btree.lf ) ) 20086545641096509099281214486501 (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20086787801088910960719962549853 Btree.lf )
  20087111156567201192658612290407 Btree.lf ) 20087363333507613942685340597341 ( Btree.nd Btree.lf
  20098626898814525832509728532147 Btree.lf ) ) ) 20099372626679341296018913078433 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20119032616307252364885209213515 Btree.lf )
  20119927018534793041557816720045 Btree.lf ) 20122813932649475462329400034989 ( Btree.nd Btree.lf
  20123412125108231431484038864719 Btree.lf ) ) 20125942214093772518150387672677 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20126090879936836849374663820257 Btree.lf )
  20126241095361692531017489256215 Btree.lf ) 20126836749365261055761931985477 ( Btree.nd Btree.lf
  20136081467348381940407994671757 Btree.lf ) ) ) ) ) 20137128480484017988466941136787 ( Btree.nd
  ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20157976957246759372305683509973
  Btree.lf ) 20159396345916776472175545317743 Btree.lf ) 20162734755059921945901312442825 (
  Btree.nd ( Btree.nd Btree.lf 20162883700376996384530771315159 Btree.lf )
  20164890220379935639826983708415 Btree.lf ) ) 20165262589076559135455312280363 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20166160656800379081499788232699 Btree.lf )
  20166309604828242595295460308393 Btree.lf ) 20185015661633172295405712009901 ( Btree.nd Btree.lf
  20185187307285791285700564629523 Btree.lf ) ) ) 20185781845176427302910320575947 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20186877429818448176607389438213 Btree.lf )
  20195780830341345254569097090735 Btree.lf ) 20197180948372811184897602325093 ( Btree.nd Btree.lf
  20204335710298214577080564341481 Btree.lf ) ) 20204640084045230790332607531533 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20205632150189554586581369341079 Btree.lf )
  20205758426701533815718380665489 Btree.lf ) 20222630508674234422203147757823 ( Btree.nd Btree.lf
  20222942044166399808292232951763 Btree.lf ) ) ) ) 20231139309121937490403898035819 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20231522075148696801832153967475 Btree.lf )
  20240033359308819019069114371869 Btree.lf ) 20240104694083179346508902676545 ( Btree.nd Btree.lf
  20244869929482709938775009124727 Btree.lf ) ) 20244941337848389073300711308679 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20245181360720510925088982570001 Btree.lf )
  20245252677100562673313593438157 Btree.lf ) 20259951316417340187190179628375 ( Btree.nd Btree.lf
  20260639065498866214351527670391 Btree.lf ) ) ) 20269799621519300451382346397681 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20270977336929347962249933962961 Btree.lf )
  20278946949721491004739448697399 Btree.lf ) 20279576244462146176927405362099 ( Btree.nd Btree.lf
  20283472114161842537149428598819 Btree.lf ) ) 20283961916277837856602976772881 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20284127419872865525620837405685 Btree.lf )
  20284691824406252951213194089863 Btree.lf ) 20297930222768754011315693648221 ( Btree.nd Btree.lf
  20298395209680028395388345168499 Btree.lf ) ) ) ) ) ) 20304049739122102235793882167665 (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20305280566244748460925041528795 Btree.lf ) 20315375116878570867415071364405 Btree.lf )
  20315614742530425606154740115055 ( Btree.nd ( Btree.nd Btree.lf 20322868638098401752873894285063
  Btree.lf ) 20323637863649815958217107607443 Btree.lf ) ) 20323970140707165224925178898231 (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20324178735239430938022324736977 Btree.lf )
  20336731340690974225185580603885 Btree.lf ) 20337867885141773783744425629087 ( Btree.nd Btree.lf
  20342473628079312273659375554879 Btree.lf ) ) ) 20343073593610227023433068665785 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20354191265993560819090989951187 Btree.lf )
  20355032586434864567093412494685 Btree.lf ) 20362419455513821973035857573971 ( Btree.nd Btree.lf
  20362714875611498644196557744613 Btree.lf ) ) 20363070566910477267553192967389 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20363664326339647779439559534905 Btree.lf )
  20370042241202638057439571031585 Btree.lf ) 20370084032044432791109510355663 ( Btree.nd Btree.lf
  20389763474046556876943032437435 Btree.lf ) ) ) ) 20389780906321933498814149339909 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20401473592709810345000869183703 Btree.lf )
  20401497471089355049286503378117 Btree.lf ) 20403094960845616670759864512229 ( Btree.nd (
  Btree.nd Btree.lf 20403116338395051258664111528303 Btree.lf ) 20403119125568218590941520952811
  Btree.lf ) ) 20403137795738250818210029621031 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20407391623350309440075711506041 Btree.lf ) 20408245405103685431851799789759 Btree.lf )
  20410973735995765427169835798221 ( Btree.nd Btree.lf 20411700290350021682763496530075 Btree.lf )
  ) ) 20431093960170639391522223863725 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20432313460949785290921213014519 Btree.lf ) 20441416712846830581076843684059 Btree.lf )
  20441695845274904389217421334579 ( Btree.nd Btree.lf 20441822067197087517456672057123 Btree.lf )
  ) 20442584172559814068627811103149 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20456786175735425777687830192943 Btree.lf ) 20458012510651714578373681394287 Btree.lf )
  20459546870579981921722549070509 ( Btree.nd Btree.lf 20459744749324676931939915777105 Btree.lf )
  ) ) ) ) 20476090670515249571217672643343 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd
  ( Btree.nd Btree.lf 20476934231757523893918632070247 Btree.lf ) 20480787810945416558116518386469
  Btree.lf ) 20481261420653374127015959000909 ( Btree.nd ( Btree.nd Btree.lf
  20481816277857521192293803622067 Btree.lf ) 20482059566885266623815302674595 Btree.lf ) )
  20488216969326694115498410871365 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20488275051697222163574012236591 Btree.lf ) 20503013541568586894227805671107 Btree.lf )
  20503049091302768956559396160589 ( Btree.nd Btree.lf 20519879030041064166584190996171 Btree.lf )
  ) ) 20519912323693228093237061044705 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20521495333353291071564083773525 Btree.lf ) 20521517866186912501040467178595 Btree.lf )
  20521521422451684260675341227067 ( Btree.nd Btree.lf 20521553011852430997166204857767 Btree.lf )
  ) 20526364885826308156171134303385 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20526700356945144674015279886211 Btree.lf ) 20529154910535192538967837389639 Btree.lf )
  20530133588501566120740064108781 ( Btree.nd Btree.lf 20545507402622496511691674204279 Btree.lf )
  ) ) ) 20545579953798829360630599300901 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd
  Btree.lf 20560043648809997537591329137975 Btree.lf ) 20560687070291623498641780967673 Btree.lf )
  20560954007093949520987735475711 ( Btree.nd Btree.lf 20561024123630258156288997020303 Btree.lf )
  ) 20574342689336138864385704625145 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20574754561525492967404724939871 Btree.lf ) 20579830927828621194266164467967 Btree.lf )
  20579903163937669141330745409669 ( Btree.nd Btree.lf 20580636342089939938385875737579 Btree.lf )
  ) ) 20581618724907836505156476236997 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20599513921315922205270081026559 Btree.lf ) 20600084431945165232735773020117 Btree.lf )
  20600425662500945629431501303723 ( Btree.nd Btree.lf 20600496169217199266814298810327 Btree.lf )
  ) 20610226271451781797966163387159 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20610748014587777648241668460773 Btree.lf ) 20611193028527024629142634828103 Btree.lf )
  20612461209814360059347484423421 ( Btree.nd Btree.lf 20635721206724117488573321145513 Btree.lf )
  ) ) ) ) ) ) 20636542823655884283222367144875 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20638699618746197776951191632681 Btree.lf )
  20639147876766753861945147042731 Btree.lf ) 20639446057233728969085320224449 ( Btree.nd (
  Btree.nd Btree.lf 20639967800161053567352333169097 Btree.lf ) 20654240200487509335028613286213
  Btree.lf ) ) 20655414563584477851477323761037 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20655713039133598528438887893375 Btree.lf ) 20657101541543643878252676060507 Btree.lf )
  20664666901384676283454690545999 ( Btree.nd Btree.lf 20665659580495315784725895525595 Btree.lf )
  ) ) 20677971164323945340074573130533 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20678321501450090456216751781543 Btree.lf ) 20678366931341653629872295283281 Btree.lf )
  20679385608195714348003776821287 ( Btree.nd Btree.lf 20689373714708393977535999511095 Btree.lf )
  ) 20689745665998070238723919626645 ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20690490685925929291469652013617 Btree.lf ) 20691462944100589671028428084303 Btree.lf )
  20711758457421623162730745616943 ( Btree.nd Btree.lf 20712054802583440862451562000401 Btree.lf )
  ) ) ) 20717951515745277418297705352793 ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd
  Btree.lf 20718546321678943604160478831251 Btree.lf ) 20718621927818674092671527461735 Btree.lf )
  20718919260325644659988458000515 ( Btree.nd ( Btree.nd Btree.lf 20725884875225428563905779904321
  Btree.lf ) 20725925614411548087914941975875 Btree.lf ) ) 20741358062462386253509635526925 (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20741369262962271028782353288051 Btree.lf )
  20746509728116289756245591626213 Btree.lf ) 20746517111072282543955414859287 ( Btree.nd Btree.lf
  20758493583816174678095440789117 Btree.lf ) ) ) 20758517198400761229123948513569 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20758521175392729820030545296405 Btree.lf )
  20758530717027148734205728949991 Btree.lf ) 20798180980883520715451255148437 ( Btree.nd Btree.lf
  20798228027442078752978339994159 Btree.lf ) ) 20798850833614802563432487471395 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20798898862654651998462803262421 Btree.lf )
  20799116938023360697800709731919 Btree.lf ) 20799122005286754700699283067473 ( Btree.nd Btree.lf
  20799520959727095143168489159985 Btree.lf ) ) ) ) ) 20799525609173338154427663832491 ( Btree.nd
  ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20799563927299952537610904987577
  Btree.lf ) 20799569555297180964925128596241 Btree.lf ) 20802052878328867295843292899013 (
  Btree.nd ( Btree.nd Btree.lf 20802703775995553440152625217321 Btree.lf )
  20802735441599185148928984814541 Btree.lf ) ) 20802963926402468425726362992147 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20804660730947889985965210102503 Btree.lf )
  20804677120598386117447016610499 Btree.lf ) 20804680615768919973589255183095 ( Btree.nd Btree.lf
  20804717699409101222994608192913 Btree.lf ) ) ) 20805297034572782207723027823493 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20805465596034798315713936585077 Btree.lf )
  20805672301004150002952351035655 Btree.lf ) 20806424271024843281011021934489 ( Btree.nd Btree.lf
  20807107270222955532740521010181 Btree.lf ) ) 20807628449764896005126549495851 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20807778246410651654206603586603 Btree.lf )
  20808149487653214241922065861063 Btree.lf ) 20808599153879923076821298446905 ( Btree.nd Btree.lf
  20808898042613627611686143887083 Btree.lf ) ) ) ) 20809121607310120370097158227617 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20809865786677155984512527251133 Btree.lf )
  20810331822376499229540208037829 Btree.lf ) 20811006740577954796664203009817 ( Btree.nd Btree.lf
  20811208969722132568332391753505 Btree.lf ) ) 20811544196546008779523677125175 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20811973496610940115359660026089 Btree.lf )
  20812181107891531751164765491883 Btree.lf ) 20812512008262644018761975865357 ( Btree.nd Btree.lf
  20813245154429000764845798005155 Btree.lf ) ) ) 20813572858152116880446777673527 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20814717952287481171515210927711 Btree.lf )
  20814763481807880049668755337665 Btree.lf ) 20815003534672684845008787431409 ( Btree.nd Btree.lf
  20816132627948183800052317373615 Btree.lf ) ) 20816560947826962261188744137925 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20816660449441868801279216664135 Btree.lf )
  20816732648573188300179980127387 Btree.lf ) 20817153842401288656251517734679 ( Btree.nd Btree.lf
  20817293874460046217187857879373 Btree.lf ) ) ) ) ) ) 20817476755075286282105852103801 (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf
  20818433423950283693179638401393 Btree.lf ) 20820127511350342303732091660821 Btree.lf )
  20820135780218999777077388595237 ( Btree.nd ( Btree.nd Btree.lf 20820151867250003101074083948875
  Btree.lf ) 20820162793115755419439340343301 Btree.lf ) ) 20821057258071073058436168949447 (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20821699650883033252849024300137 Btree.lf )
  20821808450853386218861089360967 Btree.lf ) 20821881107623210562568164345351 ( Btree.nd Btree.lf
  20822351535801809421523563815369 Btree.lf ) ) ) 20822536406520730286326140163263 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20823224182428086186688067196291 Btree.lf )
  20823587466740280937307599175037 Btree.lf ) 20825261477612431788446463592517 ( Btree.nd Btree.lf
  20825291567758201414723358091225 Btree.lf ) ) 20825301739868891399687155966847 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20825312268668546857270317617385 Btree.lf )
  20825833433522618657524392005597 Btree.lf ) 20825955769772166605232108374819 ( Btree.nd Btree.lf
  20826471326596701139887676374211 Btree.lf ) ) ) ) 20827001762464760411563019881227 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20827276103658648691581728322955 Btree.lf )
  20827830387415701959802870477023 Btree.lf ) 20828519674283298385575344195777 ( Btree.nd Btree.lf
  20828727704661334766227269604287 Btree.lf ) ) 20829044242089599872247059675837 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20829564432831070190021668671971 Btree.lf )
  20830162490075890905438251364015 Btree.lf ) 20830460245547431333402552871735 ( Btree.nd Btree.lf
  20831335010369122897095749645235 Btree.lf ) ) ) 20831549086773427873097263217027 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20832107053913672237474487683565 Btree.lf )
  20832178406576282923958796109985 Btree.lf ) 20833079097139060087167414664961 ( Btree.nd Btree.lf
  20833302516992950196883974081625 Btree.lf ) ) 20833751763949146353463830514509 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20833900713098606800490224167107 Btree.lf )
  20835651708764038551922044748275 Btree.lf ) 20835660958978160990282566984379 ( Btree.nd Btree.lf
  20835681793299038343920994089965 Btree.lf ) ) ) ) ) 20835684990684252119895036780119 ( Btree.nd
  ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20835860180675191397888157562723
  Btree.lf ) 20835938039312670006639575500249 Btree.lf ) 20835945734208409176816115549471 (
  Btree.nd ( Btree.nd Btree.lf 20835963858576555538524863097591 Btree.lf )
  20835981823763013755243969490335 Btree.lf ) ) 20836007998591044735948494873389 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20836105090885614250907929216331 Btree.lf )
  20836152115706892349939505284949 Btree.lf ) 20836275440673805588502668247287 ( Btree.nd Btree.lf
  20836354199391189129472169537807 Btree.lf ) ) ) 20836385168936941928447520597607 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20836505766163543085068894844543 Btree.lf )
  20836573199542837861719199184657 Btree.lf ) 20836595883991641391738178346367 ( Btree.nd Btree.lf
  20836603060606426964948329390149 Btree.lf ) ) 20836606053969438149006257596665 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20836653794973703894554874545865 Btree.lf )
  20836729536960163324251860682587 Btree.lf ) 20836757821675603872143289266067 ( Btree.nd Btree.lf
  20836835213486533580462765876443 Btree.lf ) ) ) ) 20836849576465734411557352104501 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20836871945063560705312650151429 Btree.lf )
  20836876726517556710514760876405 Btree.lf ) 20836951975644369230531982547585 ( Btree.nd Btree.lf
  20837027370968522462808408912189 Btree.lf ) ) 20837084936686117017197652517727 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20837177506730604043947272905247 Btree.lf )
  20837255147321862206602346010265 Btree.lf ) 20837276180000192119474310594573 ( Btree.nd Btree.lf
  20837279563269757263370077529179 Btree.lf ) ) ) 20837285718381664344185698570707 ( Btree.nd (
  Btree.nd ( Btree.nd ( Btree.nd Btree.lf 20837294089523988871115066861753 Btree.lf )
  20837303740392019455817583369545 Btree.lf ) 20837312757103129734477245146503 ( Btree.nd Btree.lf
  20837315345824195136796572076283 Btree.lf ) ) 20837317661261444744744683543049 ( Btree.nd (
  Btree.nd ( Btree.nd Btree.lf 20837323406576920523497945283655 Btree.lf )
  20837325191590708915395306135297 Btree.lf ) 20837325690645115046291377437605 ( Btree.nd Btree.lf
  20837326457057706678610421184973 Btree.lf ) ) ) ) ) ) ) )

lemma TX_closed : ConjClosed TX := by decide +kernel

lemma TX_mem_x0 : TX.mem (φ23 sigma22) = true := by rw [cX_eq, cX]; decide +kernel

/-! ### Order four without fixed points, in codes

The class `4C` is cut out among the relevant codes by two conjugation-invariant tests: the
fourth power is the identity, and no one of the `22` moving points is fixed.  Only the easy
implication is needed below, namely that a conjugate of `y` passes them. -/

/-- The fixed-point test on a code, over the `22` moving points: some base-`23` digit with index
below `22` equals its index. -/
def hasFix (n : ℕ) : Bool := (List.range 22).any (fun i => dg23 n i == i)

/-- The membership test for `4C` on a code: the fourth power is the identity and no moving point
is fixed. -/
def testY (q : ℕ) : Bool := (mulC23 (mulC23 q q) (mulC23 q q) == idCode23) && !hasFix q

/-- The keys of the involution tree whose product with `z⁻¹` passes the `4C` test: an
over-approximation of the structure-constant fibre. -/
noncomputable def fibreList : List ℕ := TX.toList.filter (fun k => testY (mulC23 k cZi))

lemma fibreList_length : fibreList.length = 11 := by decide +kernel

/-! ### The structure constant -/

/-- Every element of the class of `x` squares to one. -/
lemma sq_eq_one_of_conj {w : ↥AutM22} (hw : ConjClasses.mk w = ConjClasses.mk xEl) :
    w⁻¹ = w := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have h1 : c * (w * w) * c⁻¹ = 1 := by
    rw [show c * (w * w) * c⁻¹ = (c * w * c⁻¹) * (c * w * c⁻¹) by group, hc, xEl_sq]
  have h2 : w * w = c⁻¹ * (c * (w * w) * c⁻¹) * c := by group
  rw [h1] at h2
  simp only [mul_one, inv_mul_cancel] at h2
  exact inv_eq_of_mul_eq_one_right h2

/-- The fourth power of `y` is the identity. -/
lemma y0_pow_four : (y0 * y0) * (y0 * y0) = 1 := by decide

/-- `y` moves every one of the `22` points it is allowed to move. -/
lemma y0_nofix : ∀ a : Fin 23, y0 a = a → a = 22 := by decide

/-- Every element of the class of `y` passes the `4C` test on codes. -/
lemma testY_of_conj {u : ↥AutM22} (hu : ConjClasses.mk u = ConjClasses.mk yEl) :
    testY (φ23 ((u : Perm (Fin 23)))) = true := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hu)
  set p : Perm (Fin 23) := (u : Perm (Fin 23)) with hp
  set d : Perm (Fin 23) := (c : Perm (Fin 23)) with hd
  have hd22 : d (22 : Fin 23) = 22 := fix22 c.2
  have hcp : d * p * d⁻¹ = y0 := congrArg Subtype.val hc
  have hpd : p = d⁻¹ * y0 * d := by rw [← hcp]; group
  have hp4 : (p * p) * (p * p) = 1 := by
    rw [hpd]
    calc d⁻¹ * y0 * d * (d⁻¹ * y0 * d) * (d⁻¹ * y0 * d * (d⁻¹ * y0 * d))
        = d⁻¹ * ((y0 * y0) * (y0 * y0)) * d := by group
      _ = 1 := by rw [y0_pow_four]; group
  have hmul : mulC23 (φ23 p) (φ23 p) = φ23 (p * p) := mulC23_φ23 p p
  have hfour : mulC23 (mulC23 (φ23 p) (φ23 p)) (mulC23 (φ23 p) (φ23 p)) = idCode23 := by
    rw [hmul, mulC23_φ23, hp4, φ23_one]
  have hnf : hasFix (φ23 p) = false := by
    rw [Bool.eq_false_iff, ne_eq, hasFix, List.any_eq_true]
    rintro ⟨i, hi, hii⟩
    rw [List.mem_range] at hi
    simp only [beq_iff_eq] at hii
    have hlt : i < 23 := by omega
    have hval : (p ⟨i, hlt⟩).val = i := by rw [dg23_φ23 p ⟨i, hlt⟩]; exact hii
    have hfix : p ⟨i, hlt⟩ = ⟨i, hlt⟩ := Fin.ext hval
    have hy : y0 (d ⟨i, hlt⟩) = d ⟨i, hlt⟩ := by
      have h := congrArg (fun v : Fin 23 => d v) hfix
      simp only at h
      rw [hpd] at h
      simp only [Equiv.Perm.coe_mul, Function.comp_apply] at h
      calc y0 (d ⟨i, hlt⟩) = d (d⁻¹ (y0 (d ⟨i, hlt⟩))) := (d.apply_symm_apply _).symm
        _ = d ⟨i, hlt⟩ := h
    have h22 : d ⟨i, hlt⟩ = (22 : Fin 23) := y0_nofix _ hy
    have : (⟨i, hlt⟩ : Fin 23) = (22 : Fin 23) := d.injective (by rw [h22, hd22])
    omega
  unfold testY
  rw [hfour, hnf, beq_self_eq_true, Bool.not_false, Bool.and_true]

theorem card_prodOneFibre_le :
    Nat.card (prodOneFibre (classTriple 0) (classTriple 1) zEl) ≤ 11 := by
  classical
  have hmap : ∀ w ∈ prodOneFibre (classTriple 0) (classTriple 1) zEl,
      φ23 ((w : Perm (Fin 23))) ∈ fibreList := by
    rintro w ⟨hw0, hw1⟩
    rw [classTriple_zero] at hw0
    rw [classTriple_one] at hw1
    have hinv : w⁻¹ = w := sq_eq_one_of_conj hw0
    have hX : TX.mem (φ23 ((w : Perm (Fin 23)))) = true :=
      key_of_conjClass TX_closed TX_mem_x0 (u := xEl) rfl hw0
    have hY : testY (φ23 (((w⁻¹ * zEl⁻¹ : ↥AutM22) : Perm (Fin 23)))) = true := testY_of_conj hw1
    have hcoe : (((w⁻¹ * zEl⁻¹ : ↥AutM22) : Perm (Fin 23)))
        = ((w : Perm (Fin 23)))⁻¹ * zPerm⁻¹ := rfl
    rw [hcoe, show ((w : Perm (Fin 23)))⁻¹ = (w : Perm (Fin 23)) from congrArg Subtype.val hinv]
      at hY
    have hmul : mulC23 (φ23 ((w : Perm (Fin 23)))) cZi
        = φ23 ((w : Perm (Fin 23)) * zPerm⁻¹) := by
      rw [← cZi_eq, mulC23_φ23]
    refine List.mem_filter.mpr ⟨Btree.mem_toList hX, ?_⟩
    rw [hmul]
    exact hY
  have hinj : Set.InjOn (fun w : ↥AutM22 => φ23 ((w : Perm (Fin 23))))
      (prodOneFibre (classTriple 0) (classTriple 1) zEl) := by
    intro u _ v _ huv
    exact Subtype.ext (φ23_injective huv)
  have hcard : (prodOneFibre (classTriple 0) (classTriple 1) zEl).ncard
      ≤ ((fibreList.toFinset : Finset ℕ) : Set ℕ).ncard :=
    Set.ncard_le_ncard_of_injOn _
      (fun w hw => Finset.mem_coe.mpr (List.mem_toFinset.mpr (hmap w hw))) hinj
      (Finset.finite_toSet _)
  rw [Set.ncard_coe_finset] at hcard
  calc Nat.card ↥(prodOneFibre (classTriple 0) (classTriple 1) zEl)
      = (prodOneFibre (classTriple 0) (classTriple 1) zEl).ncard := Nat.card_coe_set_eq _
    _ ≤ fibreList.toFinset.card := hcard
    _ ≤ fibreList.length := List.toFinset_card_le _
    _ = 11 := fibreList_length

/-! ### The centralizer of the order-eleven element -/

lemma zPerm_pow_eleven : zPerm ^ 11 = 1 := by decide

lemma zPerm_ne_one : zPerm ≠ 1 := by decide

lemma zEl_pow_eleven : zEl ^ 11 = 1 := Subtype.ext zPerm_pow_eleven

lemma zEl_ne_one : zEl ≠ 1 := by
  intro h
  apply zPerm_ne_one
  have h' := Subtype.ext_iff.mp h
  rw [OneMemClass.coe_one] at h'
  exact h'

lemma orderOf_zEl : orderOf zEl = 11 := by
  haveI : Fact (Nat.Prime 11) := ⟨by norm_num⟩
  exact orderOf_eq_prime zEl_pow_eleven zEl_ne_one

theorem eleven_le_centralizer :
    11 ≤ Nat.card ↥(Subgroup.centralizer ({zEl} : Set ↥AutM22)) := by
  have hle : Subgroup.zpowers zEl ≤ Subgroup.centralizer ({zEl} : Set ↥AutM22) := by
    rw [Subgroup.zpowers_le]
    exact Subgroup.mem_centralizer_iff.mpr (by rintro m rfl; rfl)
  have hcard : Nat.card ↥(Subgroup.zpowers zEl)
      ≤ Nat.card ↥(Subgroup.centralizer ({zEl} : Set ↥AutM22)) :=
    Nat.card_le_card_of_injective _ (Subgroup.inclusion_injective hle)
  rwa [Nat.card_zpowers, orderOf_zEl] at hcard

/-! ### Rigidity -/

theorem xEl_mem_prodOneFibre :
    xEl ∈ prodOneFibre (classTriple 0) (classTriple 1) zEl := ⟨rfl, rfl⟩

/-- **The class triple `(2B, 4C, 11A)` is rigid in `Aut(M₂₂)`.**  The product-one triples with
entries in these three classes form a single orbit under simultaneous conjugation, of full size
`|Aut(M₂₂)| = 887040`, and every one of them generates. -/
theorem rigid_triple : Nat.card ↥(rigidTuples classTriple) = Nat.card ↥AutM22 :=
  rigid_of_card_prodOneFibre center_eq_bot gen_top xEl_mem_prodOneFibre classTriple_two
    (le_trans card_prodOneFibre_le eleven_le_centralizer)

/-! ### All three classes are rational -/

/-- An exponent may be reduced modulo any exponent of the element. -/
lemma pow_mod_of_pow_eq_one {g : ↥AutM22} {m : ℕ} (hm : g ^ m = 1) (u : ℕ) :
    g ^ u = g ^ (u % m) := by
  conv_lhs => rw [← Nat.div_add_mod u m]
  rw [pow_add, pow_mul, hm, one_pow, one_mul]

lemma xEl_pow_two : xEl ^ 2 = 1 := by rw [pow_two]; exact xEl_sq

lemma xEl_ne_one : xEl ≠ 1 := by
  intro h
  have h' : sigma22 = (1 : Perm (Fin 23)) := congrArg Subtype.val h
  exact absurd h' (by decide)

lemma orderOf_xEl : orderOf xEl = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact orderOf_eq_prime xEl_pow_two xEl_ne_one

/-- The class `2B` is rational: an involution is its own odd power. -/
theorem rational_x : IsRationalClass (ConjClasses.mk xEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_xEl] at hk
  have h2 : ¬ (2 ∣ k) := by
    intro h
    have : (2 : ℕ) ∣ Nat.gcd k 2 := Nat.dvd_gcd h dvd_rfl
    rw [hk] at this
    omega
  rw [pow_mod_of_pow_eq_one xEl_pow_two k, show k % 2 = 1 by omega, pow_one]

/-- A word in the two generators conjugating `y` to its inverse. -/
def gy0 : Perm (Fin 23) :=
  zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm *
    zPerm * zPerm * sigma22 * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ *
    sigma22 * zPerm

lemma gy0_mem : gy0 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    hzi hzi) hzi) hs) hzi) hzi) hzi) hs) hz) hz) hz) hs) hz) hs) hzi) hzi) hs) hzi) hs) hz)

/-- The conjugator inverting the order-four entry. -/
def gyEl : ↥AutM22 := ⟨gy0, gy0_mem⟩

lemma conj_yEl_inv : gyEl * yEl * gyEl⁻¹ = yEl⁻¹ := by
  apply Subtype.ext
  show gy0 * y0 * gy0⁻¹ = y0⁻¹
  decide

lemma yEl_pow_four : yEl ^ 4 = 1 := by
  have h : (yEl * yEl) * (yEl * yEl) = 1 := Subtype.ext y0_pow_four
  rw [show (4 : ℕ) = 2 + 2 from rfl, pow_add, pow_two]
  exact h

lemma yEl_sq_ne_one : yEl ^ 2 ≠ 1 := by
  intro h
  have h2 : y0 * y0 = 1 := by
    have h3 : ((yEl * yEl : ↥AutM22) : Perm (Fin 23)) = ((1 : ↥AutM22) : Perm (Fin 23)) :=
      congrArg Subtype.val (by rw [← pow_two]; exact h)
    exact h3
  exact absurd h2 (by decide)

lemma orderOf_yEl : orderOf yEl = 4 := by
  refine orderOf_eq_of_pow_and_pow_div_prime (by norm_num) yEl_pow_four ?_
  intro p hp hpd
  have hple : p ≤ 4 := Nat.le_of_dvd (by norm_num) hpd
  have hpge : 2 ≤ p := hp.two_le
  interval_cases p
  · exact yEl_sq_ne_one
  · exact absurd hpd (by norm_num)
  · exact absurd hp (by norm_num)

/-- The class `4C` is rational: `y` is conjugate to `y⁻¹ = y³`. -/
theorem rational_y : IsRationalClass (ConjClasses.mk yEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_yEl] at hk
  have h2 : ¬ (2 ∣ k) := by
    intro h
    have : (2 : ℕ) ∣ Nat.gcd k 4 := Nat.dvd_gcd h (by norm_num)
    rw [hk] at this
    omega
  have hinv : ConjClasses.mk yEl⁻¹ = ConjClasses.mk yEl :=
    (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gyEl, conj_yEl_inv⟩)).symm
  have hcube : yEl ^ 3 = yEl⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    calc yEl ^ 3 * yEl = yEl ^ 4 := by group
      _ = 1 := yEl_pow_four
  rw [pow_mod_of_pow_eq_one yEl_pow_four k]
  rcases (by omega : k % 4 = 1 ∨ k % 4 = 3) with h | h
  · rw [h, pow_one]
  · rw [h, hcube]; exact hinv

/-- A word in the two generators conjugating `z` to its square. -/
def gz0 : Perm (Fin 23) :=
  sigma22 * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ *
    zPerm⁻¹ * sigma22 * zPerm * zPerm * zPerm * zPerm * zPerm * sigma22 * zPerm * zPerm *
    zPerm * sigma22 * zPerm * zPerm * sigma22

lemma gz0_mem : gz0 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem hs hz) hs) hzi) hzi) hs) hzi) hzi) hzi) hzi) hs) hz)
    hz) hz) hz) hz) hs) hz) hz) hz) hs) hz) hz) hs)

/-- The conjugator squaring the order-eleven entry. -/
def gzEl : ↥AutM22 := ⟨gz0, gz0_mem⟩

lemma conj_zEl_sq : gzEl * zEl * gzEl⁻¹ = zEl ^ 2 := by
  apply Subtype.ext
  show gz0 * zPerm * gz0⁻¹ = zPerm ^ 2
  decide

/-- Conjugating by `gz` doubles the exponent of the order-eleven element. -/
lemma mk_zEl_conj (k : ℕ) : ConjClasses.mk (zEl ^ (2 * k)) = ConjClasses.mk (zEl ^ k) := by
  refine (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gzEl, ?_⟩)).symm
  have h : ∀ n : ℕ, gzEl * zEl ^ n * gzEl⁻¹ = (gzEl * zEl * gzEl⁻¹) ^ n := by
    intro n
    induction n with
    | zero => simp
    | succ m ih => rw [pow_succ, pow_succ, ← ih]; group
  rw [h k, conj_zEl_sq, ← pow_mul]

lemma zEl_pow_mod (u : ℕ) : zEl ^ u = zEl ^ (u % 11) := pow_mod_of_pow_eq_one zEl_pow_eleven u

/-- Doubling the exponent modulo eleven does not change the class of the power. -/
lemma mk_zEl_step {j k : ℕ} (h : j % 11 = (2 * k) % 11) :
    ConjClasses.mk (zEl ^ j) = ConjClasses.mk (zEl ^ k) := by
  rw [zEl_pow_mod j, h, ← zEl_pow_mod (2 * k)]
  exact mk_zEl_conj k

/-- The class `11A` is rational: `2` is a primitive root modulo `11`, so conjugation by `gz`
already reaches every power of `z` with exponent prime to eleven. -/
theorem rational_z : IsRationalClass (ConjClasses.mk zEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_zEl] at hk
  have h11 : ¬ (11 ∣ k) := by
    intro h
    have : (11 : ℕ) ∣ Nat.gcd k 11 := Nat.dvd_gcd h dvd_rfl
    rw [hk] at this
    omega
  have e1 : ConjClasses.mk (zEl ^ 1) = ConjClasses.mk zEl := by rw [pow_one]
  have e2 : ConjClasses.mk (zEl ^ 2) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 2) (k := 1) (by norm_num)).trans e1
  have e4 : ConjClasses.mk (zEl ^ 4) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 4) (k := 2) (by norm_num)).trans e2
  have e8 : ConjClasses.mk (zEl ^ 8) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 8) (k := 4) (by norm_num)).trans e4
  have e5 : ConjClasses.mk (zEl ^ 5) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 5) (k := 8) (by norm_num)).trans e8
  have e10 : ConjClasses.mk (zEl ^ 10) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 10) (k := 5) (by norm_num)).trans e5
  have e9 : ConjClasses.mk (zEl ^ 9) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 9) (k := 10) (by norm_num)).trans e10
  have e7 : ConjClasses.mk (zEl ^ 7) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 7) (k := 9) (by norm_num)).trans e9
  have e3 : ConjClasses.mk (zEl ^ 3) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 3) (k := 7) (by norm_num)).trans e7
  have e6 : ConjClasses.mk (zEl ^ 6) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 6) (k := 3) (by norm_num)).trans e3
  obtain ⟨j, hj1, hj2, hjk⟩ : ∃ j, 1 ≤ j ∧ j < 11 ∧ k % 11 = j :=
    ⟨k % 11, by omega, Nat.mod_lt _ (by norm_num), rfl⟩
  rw [zEl_pow_mod k, hjk]
  interval_cases j
  exacts [e1, e2, e3, e4, e5, e6, e7, e8, e9, e10]

theorem rational : ∀ i, IsRationalClass (classTriple i) := by
  intro i
  fin_cases i
  exacts [rational_x, rational_y, rational_z]

/-! ### The certificate -/

/-- **A rigidity certificate for `Aut(M₂₂) = M₂₂ : 2`.**  The triple `(2B, 4C, 11A)` is rigid,
generating, and rational, and the group is centerless. -/
noncomputable def cert : RigidityCertificate ↥AutM22 :=
  RigidityCertificate.ofStructureConstant classTriple center_eq_bot rational gen_top
    xEl_mem_prodOneFibre classTriple_two (le_trans card_prodOneFibre_le eleven_le_centralizer)

/-- **`Aut(M₂₂)` is a regular Galois group over `ℚ(T)`.** -/
theorem isRegularInverseGalois : IsRegularInverseGalois ↥AutM22 :=
  cert.isRegularInverseGalois

/-- **`Aut(M₂₂)` is a Galois group over `ℚ`.** -/
theorem isInverseGalois : IsInverseGalois ↥AutM22 :=
  Rigidity.rigidity_realizable cert

end MathieuM22

end Rigidity
