import InverseGalois.Rigidity.Examples.MathieuM22
import Mathieu.M22CardClean
import Mathieu.M22Transitive
import Mathieu.PSL34

/-!
# The Mathieu group `M₂₂` inside `Aut(M₂₂) = M₂₂ : 2`

`InverseGalois/Rigidity/Examples/MathieuM22.lean` builds the group

`AutM22 = ⟨σ, z⟩ ≤ Perm (Fin 23)`

and equips it with a rational rigidity certificate, hence realises it regularly over `ℚ`.  This
file identifies the group so realised: it contains the Mathieu group `M₂₂` of `Mathieu/DefM22.lean`
as a normal subgroup of index two, and has order `887040 = 2 · |M₂₂|`.

The chain of arguments is:

* the four Schreier generators `p1 = schB 1`, `p2 = schB 2`, `p7 = schB 7`, `p13 = schB 13` of
  `Mathieu/M22Transitive.lean` already generate all of `M₂₂` (`M22gen_eq`).  The lower bound on the
  order of the subgroup they generate is orbit-stabiliser: they move `21` onto each of the `22`
  points `≠ 22`, and the point stabiliser contains the image of `SL(3, F₄)` acting on the
  projective plane, which has order `20160`;
* each of the four is an explicit word in `σ` and `z`, so `M₂₂ ≤ AutM22` (`M22_le_AutM22`), and
  `z` itself is `p7`;
* conjugation by `σ` sends each of the four to a word in the four, so `M₂₂ ∪ M₂₂ σ` is a subgroup;
  it contains `σ` and `z` and is contained in `AutM22`, hence equals it (`AutM22_eq_ext`);
* the sign character of `Perm (Fin 23)` is trivial on `M₂₂` and is `-1` on `σ`, so its kernel in
  `AutM22` is exactly `M₂₂` (`ker_signAut`); `M₂₂` is therefore normal of index two
  (`index_M22`) and `|AutM22| = 887040` (`card_AutM22`).
-/

namespace Rigidity

namespace MathieuM22

open Equiv Mathieu
open Mathieu.M22Transitive (p1 p2 p7 p13 p1_mem p2_mem p7_mem p13_mem)

set_option maxHeartbeats 1000000
set_option maxRecDepth 100000

/-! ### The four Schreier generators generate `M₂₂` -/

/-- The four Schreier generators `schB 1, schB 2, schB 7, schB 13` of `M₂₂`. -/
def schGens : Set (Perm (Fin 23)) := {p1, p2, p7, p13}

/-- The subgroup of `Perm (Fin 23)` generated by the four Schreier generators. -/
def M22gen : Subgroup (Perm (Fin 23)) := Subgroup.closure schGens

lemma M22gen_def : M22gen = Subgroup.closure schGens := rfl

lemma p1_memGen : p1 ∈ M22gen :=
  Subgroup.subset_closure (show p1 ∈ schGens from Set.mem_insert _ _)

lemma p2_memGen : p2 ∈ M22gen :=
  Subgroup.subset_closure (show p2 ∈ schGens from Set.mem_insert_of_mem _ (Set.mem_insert _ _))

lemma p7_memGen : p7 ∈ M22gen :=
  Subgroup.subset_closure (show p7 ∈ schGens from
    Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ (Set.mem_insert _ _)))

lemma p13_memGen : p13 ∈ M22gen :=
  Subgroup.subset_closure (show p13 ∈ schGens from
    Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl)))

lemma mem_schGens_iff {g : Perm (Fin 23)} : g ∈ schGens ↔ g = p1 ∨ g = p2 ∨ g = p7 ∨ g = p13 :=
  Iff.rfl

lemma M22gen_le : M22gen ≤ M22 := by
  rw [M22gen_def, Subgroup.closure_le]
  intro g hg
  rcases mem_schGens_iff.mp hg with rfl | rfl | rfl | rfl
  exacts [p1_mem, p2_mem, p7_mem, p13_mem]

/-- The four generators already move `21` onto every point other than the fixed point `22`; the
witnesses are the words found by the breadth-first search of `Mathieu/M22Transitive.lean`. -/
theorem gen_reaches (x : Fin 23) (hx : x ≠ 22) :
    ∃ g : ↥M22gen, (g : Perm (Fin 23)) 21 = x := by
  fin_cases x
  · exact ⟨⟨p2 * p1 * p2, mul_mem (mul_mem p2_memGen p1_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p13 * p2, mul_mem p13_memGen p2_memGen⟩, by decide⟩
  · exact ⟨⟨p7 * p7, mul_mem p7_memGen p7_memGen⟩, by decide⟩
  · exact ⟨⟨p2 * p7 * p1 * p2,
      mul_mem (mul_mem (mul_mem p2_memGen p7_memGen) p1_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p1 * p2, mul_mem p1_memGen p2_memGen⟩, by decide⟩
  · exact ⟨⟨p7 * p2 * p7, mul_mem (mul_mem p7_memGen p2_memGen) p7_memGen⟩, by decide⟩
  · exact ⟨⟨p13 * p13, mul_mem p13_memGen p13_memGen⟩, by decide⟩
  · exact ⟨⟨p2, p2_memGen⟩, by decide⟩
  · exact ⟨⟨p13 * p1 * p2, mul_mem (mul_mem p13_memGen p1_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p2 * p13 * p2, mul_mem (mul_mem p2_memGen p13_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p1 * p13 * p2, mul_mem (mul_mem p1_memGen p13_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p7 * p13 * p2, mul_mem (mul_mem p7_memGen p13_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p1 * p7, mul_mem p1_memGen p7_memGen⟩, by decide⟩
  · exact ⟨⟨p7, p7_memGen⟩, by decide⟩
  · exact ⟨⟨p1 * p2 * p1 * p2,
      mul_mem (mul_mem (mul_mem p1_memGen p2_memGen) p1_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p2 * p7, mul_mem p2_memGen p7_memGen⟩, by decide⟩
  · exact ⟨⟨p13 * p1 * p7, mul_mem (mul_mem p13_memGen p1_memGen) p7_memGen⟩, by decide⟩
  · exact ⟨⟨p13, p13_memGen⟩, by decide⟩
  · exact ⟨⟨p7 * p1 * p2, mul_mem (mul_mem p7_memGen p1_memGen) p2_memGen⟩, by decide⟩
  · exact ⟨⟨p7 * p2, mul_mem p7_memGen p2_memGen⟩, by decide⟩
  · exact ⟨⟨p2 * p1 * p7, mul_mem (mul_mem p2_memGen p1_memGen) p7_memGen⟩, by decide⟩
  · exact ⟨1, by decide⟩
  · exact absurd rfl hx

lemma orbit_21 : MulAction.orbit ↥M22gen (21 : Fin 23) = {x : Fin 23 | x ≠ 22} := by
  ext x
  constructor
  · rintro ⟨g, rfl⟩ h
    have hfix : (g : Perm (Fin 23)) (22 : Fin 23) = 22 := M22_fixes_last (M22gen_le g.2)
    have h21 : (g : Perm (Fin 23)) (21 : Fin 23) = (g : Perm (Fin 23)) (22 : Fin 23) := by
      rw [hfix]; exact h
    exact absurd ((g : Perm (Fin 23)).injective h21) (by decide)
  · intro hx
    obtain ⟨g, hg⟩ := gen_reaches x hx
    exact ⟨g, hg⟩

lemma card_orbit_21 : Nat.card (MulAction.orbit ↥M22gen (21 : Fin 23)) = 22 := by
  have h : ({x : Fin 23 | x ≠ 22} : Set (Fin 23)) = ↑(({22}ᶜ : Finset (Fin 23))) := by
    ext x; simp
  rw [orbit_21, h, Nat.card_coe_set_eq, Set.ncard_coe_finset]
  decide

/-! ### The point stabiliser contains `PSL(3, 4)` -/

lemma schB1_eq_p1 : EnumM22.schB 1 = p1 := schB1_eq
lemma schB2_eq_p2 : EnumM22.schB 2 = p2 := schB2_eq
lemma schB7_eq_p7 : EnumM22.schB 7 = p7 := schB7_eq
lemma schB13_eq_p13 : EnumM22.schB 13 = p13 := schB13_eq

lemma w1_memGen : PSL34.w1 ∈ M22gen := by
  have hw : PSL34.w1 = p7⁻¹ * p1 * p1 * p7 * p2⁻¹ * p7⁻¹ * p1 := by
    unfold PSL34.w1
    rw [schB1_eq_p1, schB2_eq_p2, schB7_eq_p7]
  have h1 := p1_memGen
  have h2 := p2_memGen
  have h7 := p7_memGen
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (inv_mem h7) h1) h1) h7)
    (inv_mem h2)) (inv_mem h7)) h1

lemma w2_memGen : PSL34.w2 ∈ M22gen := by
  have hw : PSL34.w2 = p2 * p1 * p1 * p13 * p7⁻¹ * p13⁻¹ * p2 * p7⁻¹ := by
    unfold PSL34.w2
    rw [schB1_eq_p1, schB2_eq_p2, schB7_eq_p7, schB13_eq_p13]
  have h1 := p1_memGen
  have h2 := p2_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem h2 h1) h1) h13)
    (inv_mem h7)) (inv_mem h13)) h2) (inv_mem h7)

lemma w3_memGen : PSL34.w3 ∈ M22gen := by
  have hw : PSL34.w3 = p2 * p2 * p7⁻¹ * p1⁻¹ * p1⁻¹ * p13⁻¹ * p2 := by
    unfold PSL34.w3
    rw [schB1_eq_p1, schB2_eq_p2, schB7_eq_p7, schB13_eq_p13]
  have h1 := p1_memGen
  have h2 := p2_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem h2 h2) (inv_mem h7))
    (inv_mem h1)) (inv_mem h1)) (inv_mem h13)) h2

/-- The projective-plane representation of `SL(3, F₄)` is generated by `w1, w2, w3`. -/
lemma cpsiF4_range_eq :
    TransM21.cpsiF4.range =
      Subgroup.closure ({PSL34.w1, PSL34.w2, PSL34.w3} : Set (Perm (Fin 23))) := by
  rw [MonoidHom.range_eq_map, ← PSL34.closure_gens34_eq_top, MonoidHom.map_closure]
  congr 1
  rw [Set.image_insert_eq, Set.image_insert_eq, Set.image_singleton, TransM21.cpsiF4_apply,
    TransM21.cpsiF4_apply, TransM21.cpsiF4_apply, PSL34.conj_psi34_g1_eq_w1,
    PSL34.conj_psi34_g2_eq_w2, PSL34.conj_psi34_g3_eq_w3]

lemma cpsiF4_range_le : TransM21.cpsiF4.range ≤ M22gen := by
  rw [cpsiF4_range_eq, Subgroup.closure_le]
  intro g hg
  rcases (by exact hg : g = PSL34.w1 ∨ g = PSL34.w2 ∨ g = PSL34.w3) with rfl | rfl | rfl
  exacts [w1_memGen, w2_memGen, w3_memGen]

lemma cpsiF4_range_fix21 {g : Perm (Fin 23)} (hg : g ∈ TransM21.cpsiF4.range) :
    g (21 : Fin 23) = 21 := by
  obtain ⟨u, rfl⟩ := hg
  exact TransM21.M21_fix21 ⟨_, TransM21.cpsiF4_mem u⟩

lemma card_cpsiF4_range : Nat.card TransM21.cpsiF4.range = 20160 := by
  have hker : TransM21.cpsiF4.ker = TransM21.cpsi.ker := by
    ext u
    simp only [MonoidHom.mem_ker]
    constructor
    · intro h
      apply Subtype.ext
      rw [TransM21.cpsi_coe, OneMemClass.coe_one]
      exact h
    · intro h
      rw [← TransM21.cpsi_coe, h, OneMemClass.coe_one]
  have e1 := (Nat.card_congr (QuotientGroup.quotientKerEquivRange TransM21.cpsiF4).toEquiv).symm
  have e2 := (Nat.card_congr (QuotientGroup.quotientKerEquivRange TransM21.cpsi).toEquiv).symm
  rw [e1, hker, ← e2, M22CardClean.cpsi_range_card]

/-- The image of `SL(3, F₄)` inside the stabiliser of the point `21`. -/
noncomputable def stabEmb (w : ↥TransM21.cpsiF4.range) :
    ↥(MulAction.stabilizer ↥M22gen (21 : Fin 23)) :=
  ⟨⟨(w : Perm (Fin 23)), cpsiF4_range_le w.2⟩,
    MulAction.mem_stabilizer_iff.mpr (cpsiF4_range_fix21 w.2)⟩

lemma stabEmb_val (w : ↥TransM21.cpsiF4.range) :
    (((stabEmb w : ↥(MulAction.stabilizer ↥M22gen (21 : Fin 23))) : ↥M22gen) : Perm (Fin 23))
      = (w : Perm (Fin 23)) := rfl

lemma stabEmb_injective : Function.Injective stabEmb := by
  intro u v huv
  apply Subtype.ext
  rw [← stabEmb_val u, ← stabEmb_val v, huv]

lemma card_stabilizer_ge :
    20160 ≤ Nat.card (MulAction.stabilizer ↥M22gen (21 : Fin 23)) := by
  have h := Nat.card_le_card_of_injective stabEmb stabEmb_injective
  rwa [card_cpsiF4_range] at h

/-! ### The four generators generate `M₂₂` -/

lemma card_M22gen_ge : 443520 ≤ Nat.card ↥M22gen := by
  have hos : Nat.card (MulAction.orbit ↥M22gen (21 : Fin 23)) *
      Nat.card (MulAction.stabilizer ↥M22gen (21 : Fin 23)) = Nat.card ↥M22gen := by
    rw [Nat.card_congr (MulAction.orbitEquivQuotientStabilizer ↥M22gen (21 : Fin 23))]
    exact (Subgroup.card_eq_card_quotient_mul_card_subgroup _).symm
  rw [card_orbit_21] at hos
  have := card_stabilizer_ge
  omega

/-- **The four Schreier generators generate `M₂₂`.** -/
theorem M22gen_eq : M22gen = M22 :=
  Subgroup.eq_of_le_of_card_ge M22gen_le (by rw [M22_card_clean]; exact card_M22gen_ge)

/-! ### `M₂₂` lies inside `Aut(M₂₂)` -/

lemma zPerm_eq_p7 : zPerm = p7 := rfl

lemma p7_memAut : p7 ∈ AutM22 := zPerm_eq_p7 ▸ zPerm_mem

lemma p1_memAut : p1 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  have hw : p1 =
      sigma22 * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ *
        sigma22 * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm * zPerm * zPerm *
        sigma22 := by decide
  rw [hw]
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hs hzi) hzi) hs) hz)
    hz) hs) hzi) hzi) hs) hzi) hzi) hzi) hzi) hs) hz) hz) hz) hs)

lemma p2_memAut : p2 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  have hw : p2 =
      zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm⁻¹ * zPerm⁻¹ *
        sigma22 * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * sigma22 * zPerm * zPerm *
        zPerm * sigma22 * zPerm⁻¹ := by decide
  rw [hw]
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hzi
    hzi) hs) hzi) hzi) hzi) hs) hzi) hzi) hs) hz) hs) hzi) hzi) hzi) hs) hz) hz) hz) hs) hzi)

lemma p13_memAut : p13 ∈ AutM22 := by
  have hs := sigma22_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  have hw : p13 =
      zPerm⁻¹ * sigma22 * zPerm⁻¹ * sigma22 * zPerm * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ *
        sigma22 * zPerm⁻¹ * sigma22 * zPerm * zPerm * zPerm * sigma22 * zPerm⁻¹ * zPerm⁻¹ *
        sigma22 * zPerm * sigma22 := by decide
  rw [hw]
  exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem
    (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hzi
    hs) hzi) hs) hz) hz) hs) hzi) hzi) hs) hzi) hs) hz) hz) hz) hs) hzi) hzi) hs) hz) hs)

/-- **`M₂₂` is a subgroup of `Aut(M₂₂)`.** -/
theorem M22_le_AutM22 : M22 ≤ AutM22 := by
  rw [← M22gen_eq, M22gen_def, Subgroup.closure_le]
  intro g hg
  rcases mem_schGens_iff.mp hg with rfl | rfl | rfl | rfl
  exacts [p1_memAut, p2_memAut, p7_memAut, p13_memAut]

/-! ### Conjugation by `σ` preserves `M₂₂` -/

lemma conj_p1_memGen : sigma22 * p1 * sigma22 ∈ M22gen := by
  have h1 := p1_memGen
  have h2 := p2_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  have hw : sigma22 * p1 * sigma22 = p7⁻¹ * p13 * p7⁻¹ * p7⁻¹ * p7⁻¹ * p2⁻¹ := by decide
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (inv_mem h7) h13) (inv_mem h7))
    (inv_mem h7)) (inv_mem h7)) (inv_mem h2)

lemma conj_p2_memGen : sigma22 * p2 * sigma22 ∈ M22gen := by
  have h1 := p1_memGen
  have h2 := p2_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  have hw : sigma22 * p2 * sigma22 = p7 * p7 * p1 * p13 * p2⁻¹ * p13 := by decide
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem h7 h7) h1) h13) (inv_mem h2)) h13

lemma conj_p7_memGen : sigma22 * p7 * sigma22 ∈ M22gen := by
  have h1 := p1_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  have hw : sigma22 * p7 * sigma22 = p7⁻¹ * p13⁻¹ * p7 * p1 * p1 * p13 * p1 := by decide
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (inv_mem h7) (inv_mem h13)) h7)
    h1) h1) h13) h1

lemma conj_p13_memGen : sigma22 * p13 * sigma22 ∈ M22gen := by
  have h1 := p1_memGen
  have h7 := p7_memGen
  have h13 := p13_memGen
  have hw : sigma22 * p13 * sigma22 = p7 * p13 * p1⁻¹ * p13 * p1 * p1 := by decide
  rw [hw]
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem h7 h13) (inv_mem h1)) h13) h1) h1

/-- Conjugation by `σ` maps `M₂₂` into itself. -/
theorem sigma22_conj_mem : ∀ m ∈ M22, sigma22 * m * sigma22 ∈ M22 := by
  rw [← M22gen_eq]
  intro m hm
  rw [M22gen_def] at hm
  induction hm using Subgroup.closure_induction with
  | mem x hx =>
      rcases mem_schGens_iff.mp hx with rfl | rfl | rfl | rfl
      exacts [conj_p1_memGen, conj_p2_memGen, conj_p7_memGen, conj_p13_memGen]
  | one => rw [mul_one, sigma22_sq]; exact one_mem _
  | mul x y _ _ hx hy =>
      have h : sigma22 * (x * y) * sigma22 =
          (sigma22 * x * sigma22) * (sigma22 * y * sigma22) := by
        calc sigma22 * (x * y) * sigma22
            = sigma22 * x * (sigma22 * sigma22) * y * sigma22 := by rw [sigma22_sq]; group
          _ = (sigma22 * x * sigma22) * (sigma22 * y * sigma22) := by group
      rw [h]
      exact mul_mem hx hy
  | inv x _ hx =>
      have h : sigma22 * x⁻¹ * sigma22 = (sigma22 * x * sigma22)⁻¹ := by
        rw [mul_inv_rev, mul_inv_rev, sigma22_inv]
        group
      rw [h]
      exact inv_mem hx

/-! ### `Aut(M₂₂)` is `M₂₂ ∪ M₂₂ σ` -/

/-- The union of `M₂₂` and its coset `M₂₂ σ`, as a subgroup. -/
def M22Ext : Subgroup (Perm (Fin 23)) where
  carrier := {g | g ∈ M22 ∨ g * sigma22 ∈ M22}
  one_mem' := Or.inl (one_mem _)
  mul_mem' := by
    rintro a b (ha | ha) (hb | hb)
    · exact Or.inl (mul_mem ha hb)
    · refine Or.inr ?_
      rw [mul_assoc]
      exact mul_mem ha hb
    · refine Or.inr ?_
      have h : a * b * sigma22 = (a * sigma22) * (sigma22 * b * sigma22) := by
        calc a * b * sigma22 = a * (sigma22 * sigma22) * b * sigma22 := by rw [sigma22_sq]; group
          _ = (a * sigma22) * (sigma22 * b * sigma22) := by group
      rw [h]
      exact mul_mem ha (sigma22_conj_mem b hb)
    · refine Or.inl ?_
      have h : a * b = (a * sigma22) * (sigma22 * (b * sigma22) * sigma22) := by
        calc a * b = a * (sigma22 * sigma22) * b * (sigma22 * sigma22) := by
              rw [sigma22_sq]; group
          _ = (a * sigma22) * (sigma22 * (b * sigma22) * sigma22) := by group
      rw [h]
      exact mul_mem ha (sigma22_conj_mem _ hb)
  inv_mem' := by
    rintro a (ha | ha)
    · exact Or.inl (inv_mem ha)
    · refine Or.inr ?_
      have h : a⁻¹ * sigma22 = sigma22 * (a * sigma22)⁻¹ * sigma22 := by
        rw [mul_inv_rev]
        calc a⁻¹ * sigma22 = (sigma22 * sigma22) * a⁻¹ * sigma22 := by rw [sigma22_sq, one_mul]
          _ = sigma22 * (sigma22⁻¹ * a⁻¹) * sigma22 := by rw [sigma22_inv]; group
      rw [h]
      exact sigma22_conj_mem _ (inv_mem ha)

lemma mem_M22Ext_iff {g : Perm (Fin 23)} : g ∈ M22Ext ↔ g ∈ M22 ∨ g * sigma22 ∈ M22 := Iff.rfl

lemma AutM22_le_ext : AutM22 ≤ M22Ext := by
  rw [show AutM22 = Subgroup.closure ({sigma22, zPerm} : Set (Perm (Fin 23))) from rfl,
    Subgroup.closure_le]
  intro g hg
  rcases (by exact hg : g = sigma22 ∨ g = zPerm) with rfl | rfl
  · exact mem_M22Ext_iff.mpr (Or.inr (by rw [sigma22_sq]; exact one_mem _))
  · exact mem_M22Ext_iff.mpr (Or.inl (zPerm_eq_p7 ▸ p7_mem))

lemma ext_le_AutM22 : M22Ext ≤ AutM22 := by
  intro g hg
  rcases mem_M22Ext_iff.mp hg with h | h
  · exact M22_le_AutM22 h
  · have hg' : g = (g * sigma22) * sigma22 := by rw [mul_assoc, sigma22_sq, mul_one]
    rw [hg']
    exact mul_mem (M22_le_AutM22 h) sigma22_mem

/-- **`Aut(M₂₂)` is the union of `M₂₂` and the coset `M₂₂ σ`.** -/
theorem AutM22_eq_ext : AutM22 = M22Ext :=
  le_antisymm AutM22_le_ext ext_le_AutM22

/-! ### The sign character cuts out `M₂₂` -/

lemma sign_sigma22 : Equiv.Perm.sign sigma22 = -1 := by decide

lemma sign_eq_one_of_mem_M22 {g : Perm (Fin 23)} (hg : g ∈ M22) : Equiv.Perm.sign g = 1 := by
  rw [← M22gen_eq, M22gen_def] at hg
  have h : Subgroup.closure schGens ≤ (Equiv.Perm.sign : Perm (Fin 23) →* ℤˣ).ker := by
    rw [Subgroup.closure_le]
    intro x hx
    simp only [SetLike.mem_coe, MonoidHom.mem_ker]
    rcases mem_schGens_iff.mp hx with rfl | rfl | rfl | rfl
    · exact (by decide : Equiv.Perm.sign p1 = 1)
    · exact (by decide : Equiv.Perm.sign p2 = 1)
    · exact (by decide : Equiv.Perm.sign p7 = 1)
    · exact (by decide : Equiv.Perm.sign p13 = 1)
  exact MonoidHom.mem_ker.mp (h hg)

/-- The outer involution `σ` is not an element of `M₂₂`. -/
theorem sigma22_not_mem_M22 : sigma22 ∉ M22 := by
  intro h
  have h1 := sign_eq_one_of_mem_M22 h
  rw [sign_sigma22] at h1
  exact absurd h1 (by decide)

/-- The sign character of `Aut(M₂₂)`. -/
def signAut : ↥AutM22 →* ℤˣ := Equiv.Perm.sign.comp AutM22.subtype

lemma signAut_apply (g : ↥AutM22) : signAut g = Equiv.Perm.sign (g : Perm (Fin 23)) := by
  simp only [signAut, MonoidHom.comp_apply, Subgroup.coe_subtype]

lemma signAut_sigma22 : signAut ⟨sigma22, sigma22_mem⟩ = -1 := by
  rw [signAut_apply]
  exact sign_sigma22

/-- **The kernel of the sign character of `Aut(M₂₂)` is `M₂₂`.** -/
theorem ker_signAut : signAut.ker = M22.subgroupOf AutM22 := by
  ext g
  rw [MonoidHom.mem_ker, Subgroup.mem_subgroupOf, signAut_apply]
  constructor
  · intro h
    have hg : (g : Perm (Fin 23)) ∈ M22Ext := AutM22_eq_ext ▸ g.2
    rcases mem_M22Ext_iff.mp hg with hm | hm
    · exact hm
    · exfalso
      have h1 := sign_eq_one_of_mem_M22 hm
      rw [map_mul, h, one_mul, sign_sigma22] at h1
      exact absurd h1 (by decide)
  · exact fun h => sign_eq_one_of_mem_M22 h

instance normal_M22_subgroupOf : (M22.subgroupOf AutM22).Normal :=
  ker_signAut ▸ signAut.normal_ker

lemma range_signAut : signAut.range = ⊤ := by
  rw [eq_top_iff]
  rintro u -
  rcases Int.units_eq_one_or u with rfl | rfl
  · exact one_mem _
  · exact ⟨⟨sigma22, sigma22_mem⟩, signAut_sigma22⟩

/-- **`M₂₂` has index two in `Aut(M₂₂)`.** -/
theorem index_M22 : (M22.subgroupOf AutM22).index = 2 := by
  rw [← ker_signAut, Subgroup.index_ker, range_signAut, Subgroup.card_top,
    Nat.card_eq_fintype_card]
  decide

/-- **`|Aut(M₂₂)| = 887040 = 2 · |M₂₂|`.** -/
theorem card_AutM22 : Nat.card ↥AutM22 = 887040 := by
  have h := Subgroup.index_mul_card (M22.subgroupOf AutM22)
  rw [index_M22] at h
  have h2 : Nat.card ↥(M22.subgroupOf AutM22) = Nat.card ↥M22 :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe M22_le_AutM22).toEquiv
  rw [h2, M22_card_clean] at h
  omega

end MathieuM22

end Rigidity
