/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.StructureCount
import InverseGalois.Rigidity.Rigidity
import InverseGalois.Rigidity.RET.Descent

/-!
# Permutations as base-`n` numerals: a toolkit for rigidity certificates

A rigidity certificate for a concrete finite group is a finite computation: enumerate a conjugacy
class, count the product-one pairs above a fixed third entry, and exhibit conjugators realizing the
Galois action on each class.  Carrying that computation out on `Equiv.Perm (Fin n)` directly is
hopeless for the kernel, because deciding an equality of permutations unfolds a great deal of
`Fintype` machinery.  This file sets up the standard workaround once and for all: a permutation of
`Fin n` is encoded as the base-`n` numeral of its image vector, and the group law becomes an
operation on natural numbers that the kernel evaluates with its built-in arithmetic.

Everything is stated for an arbitrary `n`, so a certificate file only has to supply its two
generators, the list of codes of one conjugacy class, and the conjugators.

## Main definitions

* `Rigidity.PermCode.enc` / `Rigidity.PermCode.dec` — the base-`n` numeral of an image vector and
  its digits.
* `Rigidity.PermCode.φ` — the code of a permutation.
* `Rigidity.PermCode.mulC` — multiplication of codes, matching composition (`mulC_φ`).
* `Rigidity.PermCode.powC`, `Rigidity.PermCode.testOrd` — powers of codes and the order test.
* `Rigidity.PermCode.gen2` — the subgroup generated by two permutations, with its distinguished
  triple `xE`, `yE`, `zE`.

## Main results

* `Rigidity.PermCode.conj_key` — a list of codes closed under conjugation by the two generators and
  their inverses is closed under conjugation by the whole group.
* `Rigidity.PermCode.center_eq_bot_of` — a transitivity criterion making `gen2 x z` centerless.
* `Rigidity.PermCode.gen_top` — the two generators generate `gen2 x z`.
* `Rigidity.PermCode.card_prodOneFibre_le` — the structure constant is bounded by the length of the
  filtered list of class codes.
* `Rigidity.PermCode.isRationalClass_of_conj_inv`, `Rigidity.PermCode.isRationalClass_of_primRoot` —
  the two rationality criteria used by the certificates.
-/

namespace Rigidity

namespace PermCode

open Equiv

/-! ### The base-`n` encoding -/

/-- Encode an image vector `f : Fin n → Fin n` as the base-`n` numeral `∑ i, (f i) * n ^ i`. -/
def enc {n : ℕ} (f : Fin n → Fin n) : ℕ := ∑ i : Fin n, (f i).val * n ^ (i : ℕ)

/-- Decode a natural number back to an image vector (`i`-th base-`n` digit). -/
def dec (n : ℕ) [NeZero n] (a : ℕ) : Fin n → Fin n :=
  fun i => ⟨a / n ^ (i : ℕ) % n, Nat.mod_lt _ (Nat.pos_of_ne_zero (NeZero.ne n))⟩

/-- The code of a permutation: the numeral of its image vector. -/
def φ {n : ℕ} (p : Perm (Fin n)) : ℕ := enc fun i => p i

/-- The code of the identity permutation. -/
def idCode (n : ℕ) : ℕ := enc (id : Fin n → Fin n)

/-- The `j`-th base-`n` digit of a code. -/
def dg (n a j : ℕ) : ℕ := a / n ^ j % n

/-- Permute the low `k` base-`n` digits of `b` through the table `t`.  This is the kernel-friendly
shape of the encoded group law: it is a plain structural recursion on `k` using only the primitive
arithmetic of `ℕ`. -/
def step (n : ℕ) (t : ℕ → ℕ) : ℕ → ℕ → ℕ
  | _, 0 => 0
  | b, k + 1 => t (b % n) + n * step n t (b / n) k

/-- Product of two encoded permutations: permute the digits of the right factor by the digit table
of the left factor. -/
def mulC (n a b : ℕ) : ℕ := step n (dg n a) b n

/-- The `k`-th power of an encoded permutation. -/
def powC (n a : ℕ) : ℕ → ℕ
  | 0 => idCode n
  | k + 1 => mulC n a (powC n a k)

variable {n : ℕ}

lemma enc_eq (f : Fin n → Fin n) : enc f = (finFunctionFinEquiv f).val := by
  rw [finFunctionFinEquiv_apply]; rfl

lemma dec_enc [NeZero n] (f : Fin n → Fin n) : dec n (enc f) = f := by
  funext j
  apply Fin.ext
  show (enc f / n ^ (j : ℕ)) % n = (f j).val
  have h := finFunctionFinEquiv_symm_apply_val (finFunctionFinEquiv f) j
  rw [Equiv.symm_apply_apply] at h
  rw [enc_eq]
  omega

lemma dg_φ [NeZero n] (g : Perm (Fin n)) (i : Fin n) : (g i).val = dg n (φ g) i.val := by
  have h : dec n (φ g) = fun i => g i := dec_enc _
  exact (congrArg Fin.val (congrFun h i)).symm

lemma φ_injective [NeZero n] : Function.Injective (φ (n := n)) := by
  intro p q h
  have h2 : dec n (φ p) = dec n (φ q) := by rw [h]
  rw [φ, φ, dec_enc, dec_enc] at h2
  exact Equiv.ext fun i => congrFun h2 i

lemma φ_one : φ (1 : Perm (Fin n)) = idCode n := rfl

/-- `step` unrolled as a sum over the digits. -/
lemma step_eq_sum (t : ℕ → ℕ) (k : ℕ) : ∀ b : ℕ,
    step n t b k = ∑ i ∈ Finset.range k, t (b / n ^ i % n) * n ^ i := by
  induction k with
  | zero => intro b; simp [step]
  | succ k ih =>
      intro b
      rw [Finset.sum_range_succ',
        show step n t b (k + 1) = t (b % n) + n * step n t (b / n) k from rfl,
        ih (b / n), Finset.mul_sum, add_comm]
      congr 1
      · refine Finset.sum_congr rfl fun i _ => ?_
        rw [Nat.div_div_eq_div_mul, ← pow_succ']
        ring
      · simp

lemma mulC_φ [NeZero n] (g p : Perm (Fin n)) : mulC n (φ g) (φ p) = φ (g * p) := by
  have hstep : mulC n (φ g) (φ p)
      = ∑ i ∈ Finset.range n, dg n (φ g) (φ p / n ^ i % n) * n ^ i := step_eq_sum _ _ _
  rw [hstep, ← Fin.sum_univ_eq_sum_range
    (fun i => dg n (φ g) (φ p / n ^ i % n) * n ^ i) n]
  show _ = enc fun i => (g * p) i
  unfold enc
  refine Finset.sum_congr rfl fun i _ => ?_
  have hd : φ p / n ^ (i : ℕ) % n = (p i).val := (dg_φ p i).symm
  rw [hd]
  congr 1
  exact (dg_φ g (p i)).symm

lemma mulC_conj [NeZero n] (g q : Perm (Fin n)) :
    mulC n (φ g) (mulC n (φ q) (φ g⁻¹)) = φ (g * q * g⁻¹) := by
  rw [mulC_φ, mulC_φ, mul_assoc]

lemma mulC_conj' [NeZero n] (g q : Perm (Fin n)) :
    mulC n (φ g⁻¹) (mulC n (φ q) (φ g)) = φ (g⁻¹ * q * g) := by
  rw [mulC_φ, mulC_φ, mul_assoc]

lemma powC_φ [NeZero n] (g : Perm (Fin n)) (k : ℕ) : powC n (φ g) k = φ (g ^ k) := by
  induction k with
  | zero => simp [powC, φ_one]
  | succ k ih => rw [powC, ih, mulC_φ, pow_succ']

/-! ### The order test on codes -/

/-- The test "the encoded permutation has order exactly `m`", where `divs` lists the maximal proper
divisors of `m`. -/
def testOrd (n m : ℕ) (divs : List ℕ) (q : ℕ) : Bool :=
  (powC n q m == idCode n) && divs.all fun d => !(powC n q d == idCode n)

lemma testOrd_φ [NeZero n] {m : ℕ} {divs : List ℕ} {u : Perm (Fin n)}
    (h1 : u ^ m = 1) (h2 : ∀ d ∈ divs, u ^ d ≠ 1) : testOrd n m divs (φ u) = true := by
  have key : ∀ k : ℕ, (powC n (φ u) k == idCode n) = decide (u ^ k = 1) := by
    intro k
    rw [powC_φ, ← φ_one]
    by_cases h : u ^ k = 1
    · simp [h]
    · simpa [h] using fun hc => h (φ_injective hc)
  unfold testOrd
  rw [key m]
  simp only [h1, decide_true, Bool.true_and, List.all_eq_true]
  intro d hd
  rw [key d]
  simp [h2 d hd]

/-! ### Two-generator subgroups of `Perm (Fin n)` -/

variable (x z : Perm (Fin n))

/-- The subgroup of `Perm (Fin n)` generated by two permutations. -/
def gen2 : Subgroup (Perm (Fin n)) := Subgroup.closure {x, z}

lemma x_mem : x ∈ gen2 x z := Subgroup.subset_closure (Set.mem_insert _ _)

lemma z_mem : z ∈ gen2 x z := Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)

/-- The first entry of the distinguished triple. -/
def xE : ↥(gen2 x z) := ⟨x, x_mem x z⟩

/-- The third entry of the distinguished triple. -/
def zE : ↥(gen2 x z) := ⟨z, z_mem x z⟩

/-- The middle entry of the distinguished triple, forced by the product-one relation. -/
def yE : ↥(gen2 x z) := (xE x z)⁻¹ * (zE x z)⁻¹

lemma yE_coe : ((yE x z : ↥(gen2 x z)) : Perm (Fin n)) = x⁻¹ * z⁻¹ := rfl

/-- The distinguished triple of conjugacy classes. -/
def classTriple : Fin 3 → ConjClasses ↥(gen2 x z) :=
  ![ConjClasses.mk (xE x z), ConjClasses.mk (yE x z), ConjClasses.mk (zE x z)]

lemma classTriple_zero : classTriple x z 0 = ConjClasses.mk (xE x z) := rfl
lemma classTriple_one : classTriple x z 1 = ConjClasses.mk (yE x z) := rfl
lemma classTriple_two : classTriple x z 2 = ConjClasses.mk (zE x z) := rfl

lemma xE_mem_prodOneFibre :
    xE x z ∈ prodOneFibre (classTriple x z 0) (classTriple x z 1) (zE x z) := ⟨rfl, rfl⟩

/-- **The two generators generate.** -/
theorem gen_top : Subgroup.closure ({xE x z, zE x z} : Set ↥(gen2 x z)) = ⊤ := by
  have h : ({xE x z, zE x z} : Set ↥(gen2 x z))
      = ((↑) : ↥(gen2 x z) → Perm (Fin n)) ⁻¹' ({x, z} : Set (Perm (Fin n))) := by
    ext g
    simp only [Set.mem_preimage, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro (rfl | rfl)
      exacts [Or.inl rfl, Or.inr rfl]
    · rintro (hg | hg)
      exacts [Or.inl (Subtype.ext hg), Or.inr (Subtype.ext hg)]
  rw [h]
  exact Subgroup.closure_closure_coe_preimage

/-- **A subgroup containing the two generators is everything.** -/
theorem top_of_mem {H : Subgroup ↥(gen2 x z)} (hx : xE x z ∈ H) (hz : zE x z ∈ H) : H = ⊤ := by
  refine top_le_iff.mp ?_
  rw [← gen_top x z]
  refine (Subgroup.closure_le _).mpr ?_
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  exacts [hx, hz]

/-- **The first generator and the inverse of the second also generate.** -/
theorem gen_top_inv : Subgroup.closure ({xE x z, (zE x z)⁻¹} : Set ↥(gen2 x z)) = ⊤ := by
  have hx : xE x z ∈ Subgroup.closure ({xE x z, (zE x z)⁻¹} : Set ↥(gen2 x z)) :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hzi : (zE x z)⁻¹ ∈ Subgroup.closure ({xE x z, (zE x z)⁻¹} : Set ↥(gen2 x z)) :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  have hz : zE x z ∈ Subgroup.closure ({xE x z, (zE x z)⁻¹} : Set ↥(gen2 x z)) := by
    simpa using inv_mem hzi
  exact top_of_mem x z hx hz

/-! ### Closure of a list of codes under conjugation -/

/-- Conjugation-closure of a list of codes by the two generators and their inverses. -/
def ConjClosed (T : List ℕ) : Prop :=
  ∀ k ∈ T, mulC n (φ x) (mulC n k (φ x⁻¹)) ∈ T ∧ mulC n (φ x⁻¹) (mulC n k (φ x)) ∈ T ∧
    mulC n (φ z) (mulC n k (φ z⁻¹)) ∈ T ∧ mulC n (φ z⁻¹) (mulC n k (φ z)) ∈ T

instance (T : List ℕ) : Decidable (ConjClosed x z T) := by unfold ConjClosed; infer_instance

variable {x z}

/-- **Closure under the generators propagates to the whole group.** -/
theorem conj_key [NeZero n] {T : List ℕ} (hcl : ConjClosed x z T) {c : Perm (Fin n)}
    (hc : c ∈ gen2 x z) {p : Perm (Fin n)} (hp : φ p ∈ T) : φ (c * p * c⁻¹) ∈ T := by
  have hstep : ∀ q : Perm (Fin n), φ q ∈ T →
      φ (x * q * x⁻¹) ∈ T ∧ φ (x⁻¹ * q * x) ∈ T ∧ φ (z * q * z⁻¹) ∈ T ∧ φ (z⁻¹ * q * z) ∈ T := by
    intro q hq
    obtain ⟨h1, h2, h3, h4⟩ := hcl _ hq
    rw [mulC_conj] at h1 h3
    rw [mulC_conj'] at h2 h4
    exact ⟨h1, h2, h3, h4⟩
  have hc' : c ∈ Subgroup.closure ({x, z} : Set (Perm (Fin n))) := hc
  refine Subgroup.closure_induction_left
    (p := fun c _ => ∀ q : Perm (Fin n), φ q ∈ T → φ (c * q * c⁻¹) ∈ T) ?_ ?_ ?_ hc' p hp
  · intro q hq; simpa using hq
  · intro g hg y _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hmove : g * y * q * (g * y)⁻¹ = g * (y * q * y⁻¹) * g⁻¹ := by group
    rw [hmove]
    rcases hg with rfl | rfl
    · exact (hstep _ (ih q hq)).1
    · exact (hstep _ (ih q hq)).2.2.1
  · intro g hg y _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hmove : g⁻¹ * y * q * (g⁻¹ * y)⁻¹ = g⁻¹ * (y * q * y⁻¹) * g := by group
    rw [hmove]
    rcases hg with rfl | rfl
    · exact (hstep _ (ih q hq)).2.1
    · exact (hstep _ (ih q hq)).2.2.2

/-- Every member of the conjugacy class of a key is again a key. -/
theorem key_of_conjClass [NeZero n] {T : List ℕ} (hcl : ConjClosed x z T) {p : Perm (Fin n)}
    (hp : φ p ∈ T) {u w : ↥(gen2 x z)} (hu : (u : Perm (Fin n)) = p)
    (hw : ConjClasses.mk w = ConjClasses.mk u) : φ (w : Perm (Fin n)) ∈ T := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have hval : (c : Perm (Fin n)) * (w : Perm (Fin n)) * ((c : Perm (Fin n)))⁻¹ = p := by
    rw [← hu, ← hc]; rfl
  have hw' : (w : Perm (Fin n)) = ((c : Perm (Fin n)))⁻¹ * p * (((c : Perm (Fin n)))⁻¹)⁻¹ := by
    rw [← hval]; group
  rw [hw']
  exact conj_key hcl (inv_mem c.2) hp

/-! ### Centerlessness -/

/-- **A two-generator permutation group with a transitive orbit through the unique fixed point of
one generator is centerless.**

A central element commutes with `z`, so it permutes the fixed points of `z`; if `z` has just one,
that point is fixed.  Commuting then propagates the fixed point along any orbit. -/
theorem center_eq_bot_of (a₀ : Fin n) (hza₀ : z a₀ = a₀)
    (hzfix : ∀ a : Fin n, z a = a → a = a₀) (orb : List (Fin n))
    (hchain : List.IsChain (fun u v => z u = v) (x a₀ :: orb))
    (hcover : ∀ b : Fin n, b = a₀ ∨ b = x a₀ ∨ b ∈ orb) :
    Subgroup.center ↥(gen2 x z) = ⊥ := by
  rw [eq_bot_iff]
  intro w hw
  rw [Subgroup.mem_bot]
  have hcomm : ∀ g : Perm (Fin n), g ∈ gen2 x z →
      g * (w : Perm (Fin n)) = (w : Perm (Fin n)) * g := fun g hg =>
    congrArg Subtype.val (Subgroup.mem_center_iff.mp hw ⟨g, hg⟩)
  have hstep : ∀ g : Perm (Fin n), g ∈ gen2 x z → ∀ a b : Fin n, g a = b →
      (w : Perm (Fin n)) a = a → (w : Perm (Fin n)) b = b := by
    intro g hg a b hab ha
    have h := congrFun (congrArg (fun p : Perm (Fin n) => (p : Fin n → Fin n)) (hcomm g hg)) a
    simp only [Equiv.Perm.coe_mul, Function.comp_apply] at h
    rw [ha, hab] at h
    exact h.symm
  have hfix0 : (w : Perm (Fin n)) a₀ = a₀ := by
    have hq := congrFun (congrArg (fun p : Perm (Fin n) => (p : Fin n → Fin n))
      (hcomm z (z_mem x z))) a₀
    simp only [Equiv.Perm.coe_mul, Function.comp_apply, hza₀] at hq
    exact hzfix _ hq
  have hfixx : (w : Perm (Fin n)) (x a₀) = x a₀ := hstep x (x_mem x z) a₀ _ rfl hfix0
  have hall : ∀ (l : List (Fin n)) (a : Fin n), (w : Perm (Fin n)) a = a →
      List.IsChain (fun u v => z u = v) (a :: l) → ∀ b ∈ l, (w : Perm (Fin n)) b = b := by
    intro l
    induction l with
    | nil => intro a _ _ b hb; simp at hb
    | cons c t ih =>
        intro a ha hc b hb
        rw [List.isChain_cons_cons] at hc
        have hcfix : (w : Perm (Fin n)) c = c := hstep z (z_mem x z) a c hc.1 ha
        rcases List.mem_cons.mp hb with rfl | hb'
        · exact hcfix
        · exact ih c hcfix hc.2 b hb'
  apply Subtype.ext
  refine Equiv.ext fun b => ?_
  show (w : Perm (Fin n)) b = b
  rcases hcover b with rfl | rfl | hb
  · exact hfix0
  · exact hfixx
  · exact hall orb _ hfixx hchain b hb

/-! ### The structure-constant bound -/

variable (x z)

/-- The keys of the class list whose product with `z⁻¹` passes the middle-class test: an
over-approximation of the structure-constant fibre. -/
def fibreList (T : List ℕ) (test : ℕ → Bool) : List ℕ :=
  T.filter fun k => test (mulC n k (φ z⁻¹))

variable {x z}

/-- Every element of the class of an involution is an involution. -/
lemma inv_eq_self_of_conj {G : Type*} [Group G] {v w : G} (hv : v * v = 1)
    (hw : ConjClasses.mk w = ConjClasses.mk v) : w⁻¹ = w := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have h1 : c * (w * w) * c⁻¹ = 1 := by
    rw [show c * (w * w) * c⁻¹ = (c * w * c⁻¹) * (c * w * c⁻¹) by group, hc, hv]
  have h2 : w * w = c⁻¹ * (c * (w * w) * c⁻¹) * c := by group
  rw [h1] at h2
  simp only [mul_one, inv_mul_cancel] at h2
  exact inv_eq_of_mul_eq_one_right h2

/-- **The structure constant above an arbitrary third entry is bounded by the length of the
filtered class list.**

The first prescribed class is that of the involution `x`, the second is an arbitrary class `C₁`
recognized by a decidable test on codes, and the third entry is an arbitrary element `w` of the
group — not necessarily the generator `z`. -/
theorem card_prodOneFibre_le_of [NeZero n] {T : List ℕ} (hcl : ConjClosed x z T)
    (hxT : φ x ∈ T) (hxinv : x * x = 1) {test : ℕ → Bool} {C₁ : ConjClasses ↥(gen2 x z)}
    (htest : ∀ u : ↥(gen2 x z), ConjClasses.mk u = C₁ → test (φ (u : Perm (Fin n))) = true)
    (v : ↥(gen2 x z)) :
    Nat.card (prodOneFibre (ConjClasses.mk (xE x z)) C₁ v)
      ≤ (fibreList (v : Perm (Fin n)) T test).length := by
  classical
  have hxinv' : (xE x z) * (xE x z) = 1 := Subtype.ext hxinv
  have hmap : ∀ w ∈ prodOneFibre (ConjClasses.mk (xE x z)) C₁ v,
      φ (w : Perm (Fin n)) ∈ fibreList (v : Perm (Fin n)) T test := by
    rintro w ⟨hw0, hw1⟩
    have hinv : w⁻¹ = w := inv_eq_self_of_conj hxinv' hw0
    have hX : φ (w : Perm (Fin n)) ∈ T := key_of_conjClass hcl hxT (u := xE x z) rfl hw0
    have hY : test (φ (((w⁻¹ * v⁻¹ : ↥(gen2 x z)) : Perm (Fin n)))) = true := htest _ hw1
    have hcoe : (((w⁻¹ * v⁻¹ : ↥(gen2 x z)) : Perm (Fin n)))
        = ((w : Perm (Fin n)))⁻¹ * ((v : Perm (Fin n)))⁻¹ := rfl
    rw [hcoe, show ((w : Perm (Fin n)))⁻¹ = (w : Perm (Fin n)) from congrArg Subtype.val hinv]
      at hY
    refine List.mem_filter.mpr ⟨hX, ?_⟩
    rwa [mulC_φ]
  have hinj : Set.InjOn (fun w : ↥(gen2 x z) => φ (w : Perm (Fin n)))
      (prodOneFibre (ConjClasses.mk (xE x z)) C₁ v) :=
    fun u _ w _ huw => Subtype.ext (φ_injective huw)
  have hcard : (prodOneFibre (ConjClasses.mk (xE x z)) C₁ v).ncard
      ≤ (((fibreList (v : Perm (Fin n)) T test).toFinset : Finset ℕ) : Set ℕ).ncard :=
    Set.ncard_le_ncard_of_injOn _
      (fun w hw => Finset.mem_coe.mpr (List.mem_toFinset.mpr (hmap w hw))) hinj
      (Finset.finite_toSet _)
  rw [Set.ncard_coe_finset] at hcard
  calc Nat.card ↥(prodOneFibre (ConjClasses.mk (xE x z)) C₁ v)
      = (prodOneFibre (ConjClasses.mk (xE x z)) C₁ v).ncard := Nat.card_coe_set_eq _
    _ ≤ (fibreList (v : Perm (Fin n)) T test).toFinset.card := hcard
    _ ≤ (fibreList (v : Perm (Fin n)) T test).length := List.toFinset_card_le _

/-- **The structure constant is bounded by the length of the filtered class list.** -/
theorem card_prodOneFibre_le [NeZero n] {T : List ℕ} (hcl : ConjClosed x z T)
    (hxT : φ x ∈ T) (hxinv : x * x = 1) {test : ℕ → Bool}
    (htest : ∀ u : ↥(gen2 x z), ConjClasses.mk u = ConjClasses.mk (yE x z) →
      test (φ (u : Perm (Fin n))) = true) :
    Nat.card (prodOneFibre (classTriple x z 0) (classTriple x z 1) (zE x z))
      ≤ (fibreList z T test).length :=
  card_prodOneFibre_le_of hcl hxT hxinv htest (zE x z)

/-! ### Transporting conjugacy from the underlying permutations -/

/-- A conjugating permutation lying in the group witnesses conjugacy of subgroup elements. -/
lemma mk_eq_mk_of_perm {u v : ↥(gen2 x z)} {c : Perm (Fin n)} (hc : c ∈ gen2 x z)
    (h : c * (u : Perm (Fin n)) * c⁻¹ = (v : Perm (Fin n))) :
    ConjClasses.mk u = ConjClasses.mk v :=
  ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨⟨c, hc⟩, Subtype.ext h⟩)

/-- The same, for a power of a subgroup element. -/
lemma mk_pow_eq_mk_of_perm {u v : ↥(gen2 x z)} {k : ℕ} {c : Perm (Fin n)} (hc : c ∈ gen2 x z)
    (h : c * (u : Perm (Fin n)) ^ k * c⁻¹ = (v : Perm (Fin n))) :
    ConjClasses.mk (u ^ k) = ConjClasses.mk v := by
  refine mk_eq_mk_of_perm hc ?_
  rwa [show ((u ^ k : ↥(gen2 x z)) : Perm (Fin n)) = (u : Perm (Fin n)) ^ k by simp]

/-- The same, for the inverse of a subgroup element. -/
lemma mk_inv_eq_mk_of_perm {u v : ↥(gen2 x z)} {c : Perm (Fin n)} (hc : c ∈ gen2 x z)
    (h : c * ((u : Perm (Fin n)))⁻¹ * c⁻¹ = (v : Perm (Fin n))) :
    ConjClasses.mk u⁻¹ = ConjClasses.mk v := by
  refine mk_eq_mk_of_perm hc ?_
  rwa [show ((u⁻¹ : ↥(gen2 x z)) : Perm (Fin n)) = ((u : Perm (Fin n)))⁻¹ by simp]

/-! ### Orders -/

/-- Conjugate elements have the same order. -/
lemma orderOf_eq_of_conj {G : Type*} [Group G] {u v : G}
    (h : ConjClasses.mk u = ConjClasses.mk v) : orderOf u = orderOf v := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp h)
  have hinj := orderOf_injective (MulAut.conj c).toMonoidHom (MulAut.conj c).injective u
  rw [show (MulAut.conj c).toMonoidHom u = v from hc] at hinj
  exact hinj.symm

/-- Compute the order of a subgroup element from the underlying permutation. -/
lemma orderOf_eq_of_divs [NeZero n] {w : ↥(gen2 x z)} {m : ℕ} {divs : List ℕ} (hm : 0 < m)
    (hdivs : ∀ q ≤ m, q.Prime → q ∣ m → m / q ∈ divs)
    (hpow : (w : Perm (Fin n)) ^ m = 1)
    (hne : ∀ d ∈ divs, (w : Perm (Fin n)) ^ d ≠ 1) :
    orderOf w = m := by
  refine orderOf_eq_of_pow_and_pow_div_prime hm (Subtype.ext (by simpa using hpow)) ?_
  intro q hq hqd hc
  exact hne _ (hdivs q (Nat.le_of_dvd hm hqd) hq hqd) (by simpa using congrArg Subtype.val hc)

/-- The order test succeeds on every member of a class whose order is known. -/
theorem testOrd_of_class [NeZero n] {m : ℕ} {divs : List ℕ} {v : ↥(gen2 x z)}
    (hv : orderOf v = m) (hdvd : ∀ d ∈ divs, ¬ m ∣ d) :
    ∀ u : ↥(gen2 x z), ConjClasses.mk u = ConjClasses.mk v →
      testOrd n m divs (φ (u : Perm (Fin n))) = true := by
  intro u hu
  have hou : orderOf u = m := (orderOf_eq_of_conj hu).trans hv
  refine testOrd_φ ?_ ?_
  · have h1 : (u : ↥(gen2 x z)) ^ m = 1 := by rw [← hou]; exact pow_orderOf_eq_one u
    simpa using congrArg (fun w : ↥(gen2 x z) => (w : Perm (Fin n))) h1
  · intro d hd hcon
    refine hdvd d hd ?_
    rw [← hou]
    exact orderOf_dvd_of_pow_eq_one (Subtype.ext (by simpa using hcon))

/-- The cyclic group generated by an element bounds its centraliser from below. -/
theorem le_card_centralizer_of {H : Type*} [Group H] [Finite H] {w : H} {m : ℕ}
    (hw : orderOf w = m) :
    m ≤ Nat.card ↥(Subgroup.centralizer ({w} : Set H)) := by
  have hle : Subgroup.zpowers w ≤ Subgroup.centralizer ({w} : Set H) := by
    rw [Subgroup.zpowers_le]
    exact Subgroup.mem_centralizer_iff.mpr (by rintro m rfl; rfl)
  have hcard : Nat.card ↥(Subgroup.zpowers w)
      ≤ Nat.card ↥(Subgroup.centralizer ({w} : Set H)) :=
    Nat.card_le_card_of_injective _ (Subgroup.inclusion_injective hle)
  rwa [Nat.card_zpowers, hw] at hcard

/-- The cyclic group generated by the third entry bounds its centraliser from below. -/
theorem le_card_centralizer {m : ℕ} (hz : orderOf (zE x z) = m) :
    m ≤ Nat.card ↥(Subgroup.centralizer ({zE x z} : Set ↥(gen2 x z))) :=
  le_card_centralizer_of hz

/-! ### Rationality criteria -/

section Rational

variable {G : Type*} [Group G]

/-- An exponent may be reduced modulo any exponent of the element. -/
lemma pow_mod_of_pow_eq_one {g : G} {m : ℕ} (hm : g ^ m = 1) (u : ℕ) : g ^ u = g ^ (u % m) := by
  conv_lhs => rw [← Nat.div_add_mod u m]
  rw [pow_add, pow_mul, hm, one_pow, one_mul]

/-- **Rationality when every unit modulo the order is `±1`.**  For an element of order `m` with
`(ℤ/m)ˣ = {±1}` — that is `m ∈ {1, 2, 3, 4, 6}` — the class is rational as soon as the element is
conjugate to its inverse. -/
theorem isRationalClass_of_conj_inv {y : G} {m : ℕ} (hm : 0 < m) (hord : orderOf y = m)
    (hunits : ∀ r < m, Nat.gcd r m = 1 → r = 1 % m ∨ r = (m - 1) % m)
    (hconj : ConjClasses.mk y⁻¹ = ConjClasses.mk y) :
    IsRationalClass (ConjClasses.mk y) := by
  rcases Nat.lt_or_ge 1 m with h1 | h1
  case inr =>
    have hy : y = 1 := orderOf_eq_one_iff.mp (hord.trans (le_antisymm h1 hm))
    subst hy
    exact isRationalClass_mk_of_rep fun k _ => by simp
  refine isRationalClass_mk_of_rep fun k hk => ?_
  rw [hord] at hk
  have hpow : y ^ m = 1 := hord ▸ pow_orderOf_eq_one y
  have hgcd : Nat.gcd (k % m) m = 1 := by
    rw [← Nat.gcd_rec, Nat.gcd_comm]; exact hk
  have hlt : k % m < m := Nat.mod_lt _ hm
  rw [pow_mod_of_pow_eq_one hpow k]
  rcases hunits _ hlt hgcd with h | h
  · rw [h, Nat.mod_eq_of_lt h1, pow_one]
  · rw [h, Nat.mod_eq_of_lt (by omega)]
    have hinv : y ^ (m - 1) = y⁻¹ := by
      refine eq_inv_of_mul_eq_one_left ?_
      rw [← pow_succ, Nat.sub_add_cancel hm, hpow]
    rw [hinv, hconj]

/-- **Rationality of a prime-order class from one conjugator realizing a primitive root.**

If `z` has prime order `p` and is conjugate to `z ^ g` with `g` a primitive root modulo `p`, then
every power `z ^ k` with `p ∤ k` is conjugate to `z`. -/
theorem isRationalClass_of_primRoot {z : G} {p g : ℕ} (hp : 1 < p) (hord : orderOf z = p)
    (hconj : ConjClasses.mk (z ^ g) = ConjClasses.mk z)
    (hroot : ∀ r < p, Nat.gcd r p = 1 → ∃ e ∈ Finset.range p, r % p = g ^ e % p) :
    IsRationalClass (ConjClasses.mk z) := by
  refine isRationalClass_mk_of_rep fun k hk => ?_
  rw [hord] at hk
  have hpow : z ^ p = 1 := hord ▸ pow_orderOf_eq_one z
  have hmod : ∀ u : ℕ, z ^ u = z ^ (u % p) := pow_mod_of_pow_eq_one hpow
  have hconjPow : ∀ (c a : G) (v : ℕ), c * a ^ v * c⁻¹ = (c * a * c⁻¹) ^ v := by
    intro c a v
    induction v with
    | zero => simp
    | succ w ih => rw [pow_succ, pow_succ, ← ih]; group
  -- conjugating by a fixed element multiplies the exponent by `g`
  have hstepC : ∀ u : ℕ, ConjClasses.mk (z ^ (g * u)) = ConjClasses.mk (z ^ u) := by
    intro u
    obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hconj)
    refine ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨c, ?_⟩)
    rw [pow_mul, hconjPow c (z ^ g) u, hc]
  have hpowC : ∀ e : ℕ, ConjClasses.mk (z ^ (g ^ e)) = ConjClasses.mk z := by
    intro e
    induction e with
    | zero => simp
    | succ e ih =>
        rw [show g ^ (e + 1) = g * g ^ e by ring]
        exact (hstepC (g ^ e)).trans ih
  have hlt : k % p < p := Nat.mod_lt _ (by omega)
  have hgcd : Nat.gcd (k % p) p = 1 := by
    rw [← Nat.gcd_rec, Nat.gcd_comm]; exact hk
  obtain ⟨e, -, he⟩ := hroot _ hlt hgcd
  rw [Nat.mod_eq_of_lt hlt] at he
  rw [hmod k, he, ← hmod (g ^ e)]
  exact hpowC e

end Rational

/-! ### The packaged certificate -/

/-- **A rational rigidity certificate assembled from the encoded data.** -/
noncomputable def certOf
    (hcenter : Subgroup.center ↥(gen2 x z) = ⊥)
    (hrat : ∀ i, IsRationalClass (classTriple x z i))
    (hbound : Nat.card (prodOneFibre (classTriple x z 0) (classTriple x z 1) (zE x z))
        ≤ Nat.card ↥(Subgroup.centralizer ({zE x z} : Set ↥(gen2 x z)))) :
    RigidityCertificate ↥(gen2 x z) :=
  RigidityCertificate.ofStructureConstant (classTriple x z) hcenter hrat (gen_top x z)
    (xE_mem_prodOneFibre x z) (classTriple_two x z).symm hbound

end PermCode

end Rigidity
