/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.StructureCount
import InverseGalois.Rigidity.Rigidity
import InverseGalois.Rigidity.RET.Descent

/-!
# A rigidity certificate for `PGL₂(𝔽₇)`

`PGL₂(𝔽₇)` acts sharply `3`-transitively on the projective line `ℙ¹(𝔽₇)`, eight points, and is
realised here as the subgroup of `Equiv.Perm (Fin 8)` generated by the two Möbius maps

* `zPerm : t ↦ t + 1`, the seven-cycle `(0 1 2 3 4 5 6)` fixing the point `7 = ∞`;
* `xPerm : t ↦ 3 / t`, the involution `(2 3)(4 7)(5 6)`.

The triple of classes `(2B, 6A, 7A)` — an involution outside `PSL₂(𝔽₇)`, an element of order six,
and a unipotent element — is **rationally rigid**: every one of its three classes is fixed by the
whole cyclotomic action, and the product-one triples in the classes form a single orbit under
simultaneous conjugation.  A rational rigid triple is exactly a `RigidityCertificate`, so
`PGL₂(𝔽₇)` is a regular Galois group over `ℚ(T)` with no number-field descent.

Rationality is the delicate half.  In `PGL₂(𝔽₇)` the unipotent class is a *single* class of size
`48`, because the normaliser of a Sylow `7`-subgroup is the full Borel of order `42` and therefore
realises all of `(ℤ/7)ˣ`; inside `PSL₂(𝔽₇)` the two classes `7A`, `7B` are distinct and the method
would only give the field `ℚ(√-7)`.  This is why the *non-simple* group is the one the rigidity
method reaches over `ℚ`.

## The computation

Permutations of `Fin 8` are encoded as base-`8` numerals of their image vectors (`φ8`), so that
the kernel manipulates natural numbers rather than `Equiv`s.  The class `2B` is stored as the
explicit list `TX` of its `28` codes; `decide` checks that the list is closed under conjugation by
the two generators and their inverses, which by `closure_induction_left` makes it closed under
conjugation by the whole group, hence a superset of the class.  Filtering `TX` by "the product
with `z⁻¹` has order exactly six" leaves seven keys, and the structure-constant fibre injects into
that list.  Seven is also the order of the centraliser of `z`, so the fibre is exactly a
centraliser orbit and the triple is rigid.

Nothing here uses `native_decide`.

## Main results

* `Rigidity.PGL27.center_eq_bot` — `PGL₂(𝔽₇)` is centerless.
* `Rigidity.PGL27.card_prodOneFibre_le` — the structure constant is at most `7`.
* `Rigidity.PGL27.rigid_triple` — `Nat.card (rigidTuples classTriple) = Nat.card PGL₂(𝔽₇)`.
* `Rigidity.PGL27.cert` — the rational rigidity certificate.
* `Rigidity.PGL27.isRegularInverseGalois` — `PGL₂(𝔽₇)` is a regular Galois group over `ℚ(T)`.
-/

namespace Rigidity

namespace PGL27

open Equiv

set_option maxHeartbeats 1000000
set_option maxRecDepth 10000

/-! ### The base-`8` encoding of permutations -/

/-- Encode an image vector `f : Fin 8 → Fin 8` as the base-`8` numeral `∑ i, (f i) * 8 ^ i`. -/
def enc8 (f : Fin 8 → Fin 8) : ℕ := ∑ i : Fin 8, (f i).val * 8 ^ (i : ℕ)

/-- Decode a natural number back to an image vector (`i`-th base-`8` digit). -/
def dec8 (n : ℕ) : Fin 8 → Fin 8 :=
  fun i => ⟨(n / 8 ^ (i : ℕ)) % 8, Nat.mod_lt _ (by norm_num)⟩

/-- Apply a permutation `g` to an encoded permutation: decode, left-multiply, re-encode. -/
def applyGenF8 (g : Perm (Fin 8)) (n : ℕ) : ℕ := enc8 (fun i => g (dec8 n i))

/-- Encoding of the identity permutation. -/
def idCode8 : ℕ := enc8 id

/-- The encoding of a permutation by its image vector. -/
def φ8 (p : Perm (Fin 8)) : ℕ := enc8 (fun i => p i)

lemma enc8_eq (f : Fin 8 → Fin 8) : enc8 f = (finFunctionFinEquiv f).val := by
  rw [finFunctionFinEquiv_apply_val]; rfl

lemma dec8_enc8 (f : Fin 8 → Fin 8) : dec8 (enc8 f) = f := by
  funext j
  apply Fin.ext
  show (enc8 f / 8 ^ (j : ℕ)) % 8 = (f j).val
  have h := finFunctionFinEquiv_symm_apply_val (finFunctionFinEquiv f) j
  rw [Equiv.symm_apply_apply] at h
  rw [enc8_eq]; omega

lemma φ8_injective : Function.Injective φ8 := by
  intro p q h
  have h2 : dec8 (φ8 p) = dec8 (φ8 q) := by rw [h]
  rw [φ8, φ8, dec8_enc8, dec8_enc8] at h2
  exact Equiv.ext (fun i => congrFun h2 i)

lemma applyGenF8_φ8 (g p : Perm (Fin 8)) : applyGenF8 g (φ8 p) = φ8 (g * p) := by
  unfold applyGenF8 φ8
  rw [dec8_enc8]
  congr 1

lemma φ8_one : φ8 1 = idCode8 := by
  unfold φ8 idCode8
  congr 1

/-- Kernel-friendly digit-permutation apply (no `Finset.sum`): permutes the base-`8` digits of
`n` by the table `t`. -/
def stepImg8 (t : ℕ → ℕ) (n : ℕ) : ℕ :=
  t (n / 8^0 % 8) + 8*(t (n / 8^1 % 8) + 8*(t (n / 8^2 % 8) + 8*(t (n / 8^3 % 8)
  + 8*(t (n / 8^4 % 8) + 8*(t (n / 8^5 % 8) + 8*(t (n / 8^6 % 8) + 8*(t (n / 8^7 % 8))))))))

/-- Generic bridge: a permutation `g` whose value table on `0..7` is `t` acts on encoded codes as
`stepImg8 t`. -/
lemma stepImg8_bridge (g : Perm (Fin 8)) (t : ℕ → ℕ)
    (h : ∀ x : Fin 8, (g x).val = t x.val) (n : ℕ) : stepImg8 t n = applyGenF8 g n := by
  simp only [applyGenF8, enc8, stepImg8, Fin.sum_univ_succ, Fin.sum_univ_zero, h, dec8,
    Fin.val_succ, Fin.val_zero]
  ring

/-! ### Multiplication of encoded permutations -/

/-- The `j`-th base-`8` digit of a code. -/
def dg8 (a j : ℕ) : ℕ := a / 8 ^ j % 8

/-- Product of two encoded permutations: permute the digits of the right factor by the digit
table of the left factor. -/
def mulC8 (a b : ℕ) : ℕ := stepImg8 (dg8 a) b

lemma dg8_φ8 (g : Perm (Fin 8)) (i : Fin 8) : (g i).val = dg8 (φ8 g) i.val := by
  have h : dec8 (φ8 g) = fun i => g i := dec8_enc8 _
  exact (congrArg Fin.val (congrFun h i)).symm

lemma mulC8_φ8 (g p : Perm (Fin 8)) : mulC8 (φ8 g) (φ8 p) = φ8 (g * p) := by
  rw [mulC8, stepImg8_bridge g (dg8 (φ8 g)) (dg8_φ8 g), applyGenF8_φ8]

lemma mulC8_conj (g q : Perm (Fin 8)) :
    mulC8 (φ8 g) (mulC8 (φ8 q) (φ8 g⁻¹)) = φ8 (g * q * g⁻¹) := by
  rw [mulC8_φ8, mulC8_φ8, mul_assoc]

lemma mulC8_conj' (g q : Perm (Fin 8)) :
    mulC8 (φ8 g⁻¹) (mulC8 (φ8 q) (φ8 g)) = φ8 (g⁻¹ * q * g) := by
  rw [mulC8_φ8, mulC8_φ8, mul_assoc]

/-! ### The group and its two generators -/

/-- The Möbius involution `t ↦ 3 / t` of `ℙ¹(𝔽₇)`, of cycle type `2³1²`.  It is an odd
permutation, hence lies outside `PSL₂(𝔽₇)`: this is the class `2B`. -/
def xPerm : Perm (Fin 8) := c[2, 3] * c[4, 7] * c[5, 6]

/-- The Möbius translation `t ↦ t + 1` of `ℙ¹(𝔽₇)`, the seven-cycle fixing `∞ = 7`. -/
def zPerm : Perm (Fin 8) := c[0, 1, 2, 3, 4, 5, 6]

/-- **`PGL₂(𝔽₇)`**, as the subgroup of `Perm (Fin 8)` generated by the two Möbius maps. -/
def PGL2F7 : Subgroup (Perm (Fin 8)) := Subgroup.closure {xPerm, zPerm}

lemma xPerm_mem : xPerm ∈ PGL2F7 := Subgroup.subset_closure (Set.mem_insert _ _)

lemma zPerm_mem : zPerm ∈ PGL2F7 := Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)

lemma zPerm_inv_mem : zPerm⁻¹ ∈ PGL2F7 := inv_mem zPerm_mem

lemma xPerm_sq : xPerm * xPerm = 1 := by decide

lemma xPerm_inv : xPerm⁻¹ = xPerm := by decide

/-- The involution of the triple. -/
def xEl : ↥PGL2F7 := ⟨xPerm, xPerm_mem⟩

/-- The unipotent element of the triple. -/
def zEl : ↥PGL2F7 := ⟨zPerm, zPerm_mem⟩

/-- The remaining entry of the triple, forced by the product-one relation. -/
def yEl : ↥PGL2F7 := xEl⁻¹ * zEl⁻¹

/-- The underlying permutation of the middle entry. -/
def y0 : Perm (Fin 8) := xPerm⁻¹ * zPerm⁻¹

lemma yEl_coe : ((yEl : ↥PGL2F7) : Perm (Fin 8)) = y0 := rfl

/-- The triple of conjugacy classes `(2B, 6A, 7A)` of `PGL₂(𝔽₇)`. -/
def classTriple : Fin 3 → ConjClasses ↥PGL2F7 :=
  ![ConjClasses.mk xEl, ConjClasses.mk yEl, ConjClasses.mk zEl]

lemma classTriple_zero : classTriple 0 = ConjClasses.mk xEl := rfl
lemma classTriple_one : classTriple 1 = ConjClasses.mk yEl := rfl
lemma classTriple_two : classTriple 2 = ConjClasses.mk zEl := rfl

lemma xEl_sq : xEl * xEl = 1 := Subtype.ext xPerm_sq

lemma xEl_inv : xEl⁻¹ = xEl := inv_eq_of_mul_eq_one_right xEl_sq

/-! ### Codes of the generators -/

/-- Code of `xPerm`. -/
def cX : ℕ := 9925832
/-- Code of `zPerm`. -/
def cZ : ℕ := 14899409
/-- Code of `zPerm⁻¹`. -/
def cZi : ℕ := 16135238

lemma cX_eq : φ8 xPerm = cX := by decide
lemma cZ_eq : φ8 zPerm = cZ := by decide
lemma cZi_eq : φ8 zPerm⁻¹ = cZi := by decide

lemma idCode8_eq : idCode8 = 16434824 := by decide

/-! ### The class of the involution, as a list of codes -/

/-- The `28` codes of the class `2B` of `PGL₂(𝔽₇)` — the involutions of cycle type `2³1²`, that
is, the Möbius involutions with two fixed points on `ℙ¹(𝔽₇)`. -/
def TX : List ℕ :=
  [957607, 1525335, 1682191, 2278654, 3271352, 3737468, 5033448, 5269453, 5945793, 6573749,
   6983564, 8019536, 8844850, 9925832, 10023083, 10729614, 11245472, 12304922, 14500171,
   14571137, 14590744, 14722862, 15022448, 15321985, 15621130, 15917139, 16188060, 16258277]

/-- The conjugation-closure test for a list of codes: conjugating a key by either generator or
its inverse produces a key again. -/
def ConjClosed : Prop :=
  ∀ k ∈ TX, mulC8 cX (mulC8 k cX) ∈ TX ∧ mulC8 cZ (mulC8 k cZi) ∈ TX ∧
    mulC8 cZi (mulC8 k cZ) ∈ TX

instance : Decidable ConjClosed := by unfold ConjClosed; infer_instance

theorem TX_closed : ConjClosed := by decide +kernel

theorem TX_mem_x : φ8 xPerm ∈ TX := by rw [cX_eq, cX]; decide

lemma conj_x_key {q : Perm (Fin 8)} (hq : φ8 q ∈ TX) : φ8 (xPerm * q * xPerm) ∈ TX := by
  have h1 := (TX_closed _ hq).1
  rw [← cX_eq, mulC8_φ8, mulC8_φ8, ← mul_assoc] at h1
  exact h1

lemma conj_z_key {q : Perm (Fin 8)} (hq : φ8 q ∈ TX) : φ8 (zPerm * q * zPerm⁻¹) ∈ TX := by
  have h2 := (TX_closed _ hq).2.1
  rw [← cZ_eq, ← cZi_eq, mulC8_conj] at h2
  exact h2

lemma conj_zi_key {q : Perm (Fin 8)} (hq : φ8 q ∈ TX) : φ8 (zPerm⁻¹ * q * zPerm) ∈ TX := by
  have h3 := (TX_closed _ hq).2.2
  rw [← cZi_eq, ← cZ_eq, mulC8_conj'] at h3
  exact h3

/-- Conjugating a key by a generator or its inverse gives a key. -/
lemma conj_gen_key {q : Perm (Fin 8)} (hq : φ8 q ∈ TX) :
    φ8 (xPerm * q * xPerm⁻¹) ∈ TX ∧ φ8 (xPerm⁻¹ * q * xPerm) ∈ TX ∧
      φ8 (zPerm * q * zPerm⁻¹) ∈ TX ∧ φ8 (zPerm⁻¹ * q * zPerm) ∈ TX := by
  refine ⟨?_, ?_, conj_z_key hq, conj_zi_key hq⟩
  · rw [xPerm_inv]
    exact conj_x_key hq
  · rw [xPerm_inv]
    exact conj_x_key hq

/-- Closure under conjugation by the generators propagates to all of the group. -/
theorem conj_key {c : Perm (Fin 8)} (hc : c ∈ PGL2F7) {p : Perm (Fin 8)} (hp : φ8 p ∈ TX) :
    φ8 (c * p * c⁻¹) ∈ TX := by
  have hc' : c ∈ Subgroup.closure ({xPerm, zPerm} : Set (Perm (Fin 8))) := hc
  refine Subgroup.closure_induction_left
    (p := fun c _ => ∀ q : Perm (Fin 8), φ8 q ∈ TX → φ8 (c * q * c⁻¹) ∈ TX) ?_ ?_ ?_ hc' p hp
  · intro q hq; simpa using hq
  · intro g hg y _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hstep : g * y * q * (g * y)⁻¹ = g * (y * q * y⁻¹) * g⁻¹ := by group
    rw [hstep]
    rcases hg with rfl | rfl
    · exact (conj_gen_key (ih q hq)).1
    · exact (conj_gen_key (ih q hq)).2.2.1
  · intro g hg y _ ih q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    have hstep : g⁻¹ * y * q * (g⁻¹ * y)⁻¹ = g⁻¹ * (y * q * y⁻¹) * g := by group
    rw [hstep]
    rcases hg with rfl | rfl
    · exact (conj_gen_key (ih q hq)).2.1
    · exact (conj_gen_key (ih q hq)).2.2.2

/-- Every member of the conjugacy class of a key is again a key. -/
theorem key_of_conjClass {p : Perm (Fin 8)} (hp : φ8 p ∈ TX) {u w : ↥PGL2F7}
    (hu : (u : Perm (Fin 8)) = p) (hw : ConjClasses.mk w = ConjClasses.mk u) :
    φ8 (w : Perm (Fin 8)) ∈ TX := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have hval : (c : Perm (Fin 8)) * (w : Perm (Fin 8)) * ((c : Perm (Fin 8)))⁻¹ = p := by
    rw [← hu, ← hc]; rfl
  have hw' : (w : Perm (Fin 8)) = ((c : Perm (Fin 8)))⁻¹ * p * (((c : Perm (Fin 8)))⁻¹)⁻¹ := by
    rw [← hval]; group
  rw [hw']
  exact conj_key (inv_mem c.2) hp

/-! ### The group is centerless

The seven-cycle `zPerm` fixes only the point `7`, so a central element must fix `7`; the
generator `xPerm` carries `7` to `4`, and the `zPerm`-orbit of `4` is everything else. -/

lemma zPerm_fix : ∀ a : Fin 8, zPerm a = a → a = 7 := by decide

theorem center_eq_bot : Subgroup.center (↥PGL2F7) = ⊥ := by
  rw [eq_bot_iff]
  intro w hw
  rw [Subgroup.mem_bot]
  have hcomm : ∀ (g : Perm (Fin 8)), g ∈ PGL2F7 →
      g * (w : Perm (Fin 8)) = (w : Perm (Fin 8)) * g := by
    intro g hg
    exact congrArg Subtype.val (Subgroup.mem_center_iff.mp hw ⟨g, hg⟩)
  have hstep : ∀ (g : Perm (Fin 8)), g ∈ PGL2F7 → ∀ a b : Fin 8, g a = b →
      (w : Perm (Fin 8)) a = a → (w : Perm (Fin 8)) b = b := by
    intro g hg a b hab ha
    have h := congrFun (congrArg (fun p : Perm (Fin 8) => (p : Fin 8 → Fin 8))
      (hcomm g hg)) a
    simp only [Equiv.Perm.coe_mul, Function.comp_apply] at h
    rw [ha, hab] at h
    exact h.symm
  have keyZ : ∀ a b : Fin 8, zPerm a = b → (w : Perm (Fin 8)) a = a →
      (w : Perm (Fin 8)) b = b := hstep zPerm zPerm_mem
  have f7 : (w : Perm (Fin 8)) (7 : Fin 8) = 7 := by
    have hq := congrFun (congrArg (fun p : Perm (Fin 8) => (p : Fin 8 → Fin 8))
      (hcomm zPerm zPerm_mem)) (7 : Fin 8)
    simp only [Equiv.Perm.coe_mul, Function.comp_apply] at hq
    rw [show zPerm (7 : Fin 8) = 7 from by decide] at hq
    exact zPerm_fix _ hq
  have f4 : (w : Perm (Fin 8)) (4 : Fin 8) = 4 :=
    hstep xPerm xPerm_mem 7 4 (by decide) f7
  have f5 : (w : Perm (Fin 8)) (5 : Fin 8) = 5 := keyZ 4 5 (by decide) f4
  have f6 : (w : Perm (Fin 8)) (6 : Fin 8) = 6 := keyZ 5 6 (by decide) f5
  have f0 : (w : Perm (Fin 8)) (0 : Fin 8) = 0 := keyZ 6 0 (by decide) f6
  have f1 : (w : Perm (Fin 8)) (1 : Fin 8) = 1 := keyZ 0 1 (by decide) f0
  have f2 : (w : Perm (Fin 8)) (2 : Fin 8) = 2 := keyZ 1 2 (by decide) f1
  have f3 : (w : Perm (Fin 8)) (3 : Fin 8) = 3 := keyZ 2 3 (by decide) f2
  apply Subtype.ext
  refine Equiv.ext fun a => ?_
  show (w : Perm (Fin 8)) a = a
  fin_cases a
  exacts [f0, f1, f2, f3, f4, f5, f6, f7]

/-! ### The pair generates -/

theorem gen_top : Subgroup.closure ({xEl, zEl} : Set ↥PGL2F7) = ⊤ := by
  have h : ({xEl, zEl} : Set ↥PGL2F7)
      = ((↑) : ↥PGL2F7 → Perm (Fin 8)) ⁻¹' ({xPerm, zPerm} : Set (Perm (Fin 8))) := by
    ext g
    simp only [Set.mem_preimage, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro (rfl | rfl)
      exacts [Or.inl rfl, Or.inr rfl]
    · rintro (hg | hg)
      exacts [Or.inl (Subtype.ext hg), Or.inr (Subtype.ext hg)]
  rw [h]
  exact Subgroup.closure_closure_coe_preimage

/-! ### Order six, in codes

`PGL₂(𝔽₇)` has a single class of elements of order six, so membership in `6A` is the plain
order test: the sixth power is the identity while the second and third powers are not. -/

/-- The membership test for `6A` on a code. -/
def testY (q : ℕ) : Bool :=
  (mulC8 (mulC8 (mulC8 q q) q) (mulC8 (mulC8 q q) q) == idCode8) &&
    !(mulC8 (mulC8 q q) q == idCode8) && !(mulC8 q q == idCode8)

/-- The keys of the involution list whose product with `z⁻¹` has order six: an
over-approximation of the structure-constant fibre. -/
def fibreList : List ℕ := TX.filter (fun k => testY (mulC8 k cZi))

lemma fibreList_length : fibreList.length = 7 := by decide +kernel

/-! ### The structure constant -/

/-- Every element of the class of `x` squares to one. -/
lemma sq_eq_one_of_conj {w : ↥PGL2F7} (hw : ConjClasses.mk w = ConjClasses.mk xEl) :
    w⁻¹ = w := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hw)
  have h1 : c * (w * w) * c⁻¹ = 1 := by
    rw [show c * (w * w) * c⁻¹ = (c * w * c⁻¹) * (c * w * c⁻¹) by group, hc, xEl_sq]
  have h2 : w * w = c⁻¹ * (c * (w * w) * c⁻¹) * c := by group
  rw [h1] at h2
  simp only [mul_one, inv_mul_cancel] at h2
  exact inv_eq_of_mul_eq_one_right h2

lemma y0_pow_six : ((y0 * y0) * y0) * ((y0 * y0) * y0) = 1 := by decide
lemma y0_pow_three_ne : ((y0 * y0) * y0) ≠ 1 := by decide
lemma y0_pow_two_ne : (y0 * y0) ≠ 1 := by decide

/-- Every element of the class of `y` passes the order-six test on codes. -/
lemma testY_of_conj {u : ↥PGL2F7} (hu : ConjClasses.mk u = ConjClasses.mk yEl) :
    testY (φ8 ((u : Perm (Fin 8)))) = true := by
  obtain ⟨c, hc⟩ := isConj_iff.mp (ConjClasses.mk_eq_mk_iff_isConj.mp hu)
  set p : Perm (Fin 8) := (u : Perm (Fin 8)) with hp
  set d : Perm (Fin 8) := (c : Perm (Fin 8)) with hd
  have hcp : d * p * d⁻¹ = y0 := congrArg Subtype.val hc
  have hpd : p = d⁻¹ * y0 * d := by rw [← hcp]; group
  have hp2 : p * p = d⁻¹ * (y0 * y0) * d := by rw [hpd]; group
  have hp3 : (p * p) * p = d⁻¹ * ((y0 * y0) * y0) * d := by rw [hpd]; group
  have hp6 : ((p * p) * p) * ((p * p) * p) = 1 := by
    rw [hp3]
    calc d⁻¹ * ((y0 * y0) * y0) * d * (d⁻¹ * ((y0 * y0) * y0) * d)
        = d⁻¹ * (((y0 * y0) * y0) * (((y0 * y0) * y0))) * d := by group
      _ = 1 := by rw [y0_pow_six]; group
  have hcancel : ∀ t : Perm (Fin 8), d⁻¹ * t * d = 1 → t = 1 := by
    intro t ht
    have h2 : t = d * (d⁻¹ * t * d) * d⁻¹ := by group
    rw [ht] at h2
    simpa using h2
  have hp3ne : (p * p) * p ≠ 1 := by
    intro h
    rw [hp3] at h
    exact y0_pow_three_ne (hcancel _ h)
  have hp2ne : p * p ≠ 1 := by
    intro h
    rw [hp2] at h
    exact y0_pow_two_ne (hcancel _ h)
  have e2 : mulC8 (φ8 p) (φ8 p) = φ8 (p * p) := mulC8_φ8 p p
  have e3 : mulC8 (mulC8 (φ8 p) (φ8 p)) (φ8 p) = φ8 ((p * p) * p) := by rw [e2, mulC8_φ8]
  have h6 : mulC8 (mulC8 (mulC8 (φ8 p) (φ8 p)) (φ8 p))
      (mulC8 (mulC8 (φ8 p) (φ8 p)) (φ8 p)) = idCode8 := by
    rw [e3, mulC8_φ8, hp6, φ8_one]
  have h3 : ¬ (mulC8 (mulC8 (φ8 p) (φ8 p)) (φ8 p) = idCode8) := by
    rw [e3, ← φ8_one]
    exact fun h => hp3ne (φ8_injective h)
  have h2 : ¬ (mulC8 (φ8 p) (φ8 p) = idCode8) := by
    rw [e2, ← φ8_one]
    exact fun h => hp2ne (φ8_injective h)
  unfold testY
  rw [h6, beq_self_eq_true, beq_eq_false_iff_ne.mpr h3, beq_eq_false_iff_ne.mpr h2]
  rfl

theorem card_prodOneFibre_le :
    Nat.card (prodOneFibre (classTriple 0) (classTriple 1) zEl) ≤ 7 := by
  classical
  have hmap : ∀ w ∈ prodOneFibre (classTriple 0) (classTriple 1) zEl,
      φ8 ((w : Perm (Fin 8))) ∈ fibreList := by
    rintro w ⟨hw0, hw1⟩
    rw [classTriple_zero] at hw0
    rw [classTriple_one] at hw1
    have hinv : w⁻¹ = w := sq_eq_one_of_conj hw0
    have hX : φ8 ((w : Perm (Fin 8))) ∈ TX :=
      key_of_conjClass TX_mem_x (u := xEl) rfl hw0
    have hY : testY (φ8 (((w⁻¹ * zEl⁻¹ : ↥PGL2F7) : Perm (Fin 8)))) = true := testY_of_conj hw1
    have hcoe : (((w⁻¹ * zEl⁻¹ : ↥PGL2F7) : Perm (Fin 8)))
        = ((w : Perm (Fin 8)))⁻¹ * zPerm⁻¹ := rfl
    rw [hcoe, show ((w : Perm (Fin 8)))⁻¹ = (w : Perm (Fin 8)) from congrArg Subtype.val hinv]
      at hY
    have hmul : mulC8 (φ8 ((w : Perm (Fin 8)))) cZi = φ8 ((w : Perm (Fin 8)) * zPerm⁻¹) := by
      rw [← cZi_eq, mulC8_φ8]
    refine List.mem_filter.mpr ⟨hX, ?_⟩
    rw [hmul]
    exact hY
  have hinj : Set.InjOn (fun w : ↥PGL2F7 => φ8 ((w : Perm (Fin 8))))
      (prodOneFibre (classTriple 0) (classTriple 1) zEl) := by
    intro u _ v _ huv
    exact Subtype.ext (φ8_injective huv)
  have hcard : (prodOneFibre (classTriple 0) (classTriple 1) zEl).ncard
      ≤ ((fibreList.toFinset : Finset ℕ) : Set ℕ).ncard :=
    Set.ncard_le_ncard_of_injOn _
      (fun w hw => Finset.mem_coe.mpr (List.mem_toFinset.mpr (hmap w hw))) hinj
      (Finset.finite_toSet _)
  rw [Set.ncard_coe_finset] at hcard
  calc Nat.card ↥(prodOneFibre (classTriple 0) (classTriple 1) zEl)
      = (prodOneFibre (classTriple 0) (classTriple 1) zEl).ncard := Nat.card_coe_set_eq _
    _ ≤ fibreList.toFinset.card := hcard
    _ ≤ fibreList.length := List.toFinset_card_le _
    _ = 7 := fibreList_length

/-! ### The centraliser of the unipotent element -/

lemma zPerm_pow_seven : zPerm ^ 7 = 1 := by decide

lemma zPerm_ne_one : zPerm ≠ 1 := by decide

lemma zEl_pow_seven : zEl ^ 7 = 1 := Subtype.ext zPerm_pow_seven

lemma zEl_ne_one : zEl ≠ 1 := by
  intro h
  apply zPerm_ne_one
  have h' := Subtype.ext_iff.mp h
  rw [OneMemClass.coe_one] at h'
  exact h'

lemma orderOf_zEl : orderOf zEl = 7 := by
  haveI : Fact (Nat.Prime 7) := ⟨by norm_num⟩
  exact orderOf_eq_prime zEl_pow_seven zEl_ne_one

theorem seven_le_centralizer :
    7 ≤ Nat.card ↥(Subgroup.centralizer ({zEl} : Set ↥PGL2F7)) := by
  have hle : Subgroup.zpowers zEl ≤ Subgroup.centralizer ({zEl} : Set ↥PGL2F7) := by
    rw [Subgroup.zpowers_le]
    exact Subgroup.mem_centralizer_iff.mpr (by rintro m rfl; rfl)
  have hcard : Nat.card ↥(Subgroup.zpowers zEl)
      ≤ Nat.card ↥(Subgroup.centralizer ({zEl} : Set ↥PGL2F7)) :=
    Nat.card_le_card_of_injective _ (Subgroup.inclusion_injective hle)
  rwa [Nat.card_zpowers, orderOf_zEl] at hcard

/-! ### Rigidity -/

theorem xEl_mem_prodOneFibre :
    xEl ∈ prodOneFibre (classTriple 0) (classTriple 1) zEl := ⟨rfl, rfl⟩

/-- **The class triple `(2B, 6A, 7A)` is rigid in `PGL₂(𝔽₇)`.**  The product-one triples with
entries in these three classes form a single orbit under simultaneous conjugation, of full size
`|PGL₂(𝔽₇)|`. -/
theorem rigid_triple : Nat.card ↥(rigidTuples classTriple) = Nat.card ↥PGL2F7 :=
  rigid_of_card_prodOneFibre center_eq_bot gen_top xEl_mem_prodOneFibre classTriple_two
    (le_trans card_prodOneFibre_le seven_le_centralizer)

/-! ### All three classes are rational -/

/-- An exponent may be reduced modulo any exponent of the element. -/
lemma pow_mod_of_pow_eq_one {g : ↥PGL2F7} {m : ℕ} (hm : g ^ m = 1) (u : ℕ) :
    g ^ u = g ^ (u % m) := by
  conv_lhs => rw [← Nat.div_add_mod u m]
  rw [pow_add, pow_mul, hm, one_pow, one_mul]

lemma xEl_pow_two : xEl ^ 2 = 1 := by rw [pow_two]; exact xEl_sq

lemma xEl_ne_one : xEl ≠ 1 := by
  intro h
  have h' : xPerm = (1 : Perm (Fin 8)) := congrArg Subtype.val h
  exact absurd h' (by decide)

lemma orderOf_xEl : orderOf xEl = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact orderOf_eq_prime xEl_pow_two xEl_ne_one

/-- The class `2B` is rational: an involution is its own odd power. -/
theorem rational_x : IsRationalClass (ConjClasses.mk xEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_xEl] at hk
  have h2 : ¬ (2 ∣ k) := by
    intro h
    have : (2 : ℕ) ∣ Nat.gcd k 2 := Nat.dvd_gcd h dvd_rfl
    rw [hk] at this
    omega
  rw [pow_mod_of_pow_eq_one xEl_pow_two k, show k % 2 = 1 by omega, pow_one]

/-- A word in the two generators conjugating `y` to its inverse. -/
def gy0 : Perm (Fin 8) :=
  zPerm⁻¹ * xPerm * zPerm⁻¹ * xPerm * zPerm⁻¹ * xPerm

lemma gy0_mem : gy0 ∈ PGL2F7 := by
  have hx := xPerm_mem
  have hzi := zPerm_inv_mem
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hzi hx) hzi) hx) hzi) hx

/-- The conjugator inverting the order-six entry. -/
def gyEl : ↥PGL2F7 := ⟨gy0, gy0_mem⟩

lemma conj_yEl_inv : gyEl * yEl * gyEl⁻¹ = yEl⁻¹ := by
  apply Subtype.ext
  show gy0 * y0 * gy0⁻¹ = y0⁻¹
  decide

lemma yEl_cube : yEl ^ 3 = (yEl * yEl) * yEl := by rw [pow_succ, pow_succ, pow_one]

lemma yEl_pow_six : yEl ^ 6 = 1 := by
  have h : ((yEl * yEl) * yEl) * ((yEl * yEl) * yEl) = 1 := Subtype.ext y0_pow_six
  rw [show (6 : ℕ) = 3 + 3 from rfl, pow_add, yEl_cube]
  exact h

lemma yEl_pow_three_ne : yEl ^ 3 ≠ 1 := by
  intro h
  rw [yEl_cube] at h
  refine y0_pow_three_ne ?_
  have h3 : (((yEl * yEl) * yEl : ↥PGL2F7) : Perm (Fin 8)) = ((1 : ↥PGL2F7) : Perm (Fin 8)) :=
    congrArg Subtype.val h
  exact h3

lemma yEl_pow_two_ne : yEl ^ 2 ≠ 1 := by
  intro h
  refine y0_pow_two_ne ?_
  have h2 : ((yEl * yEl : ↥PGL2F7) : Perm (Fin 8)) = ((1 : ↥PGL2F7) : Perm (Fin 8)) :=
    congrArg Subtype.val (by rw [← pow_two]; exact h)
  exact h2

lemma orderOf_yEl : orderOf yEl = 6 := by
  refine orderOf_eq_of_pow_and_pow_div_prime (by norm_num) yEl_pow_six ?_
  intro p hp hpd
  have hple : p ≤ 6 := Nat.le_of_dvd (by norm_num) hpd
  have hpge : 2 ≤ p := hp.two_le
  interval_cases p
  · exact yEl_pow_three_ne
  · exact yEl_pow_two_ne
  · exact absurd hp (by norm_num)
  · exact absurd hpd (by norm_num)
  · exact absurd hp (by norm_num)

/-- The class `6A` is rational: `y` is conjugate to `y⁻¹ = y⁵`, and `1` and `5` are the only
residues prime to six. -/
theorem rational_y : IsRationalClass (ConjClasses.mk yEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_yEl] at hk
  have hinv : ConjClasses.mk yEl⁻¹ = ConjClasses.mk yEl :=
    (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gyEl, conj_yEl_inv⟩)).symm
  have hfive : yEl ^ 5 = yEl⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    calc yEl ^ 5 * yEl = yEl ^ 6 := by group
      _ = 1 := yEl_pow_six
  have hgcd : Nat.gcd (k % 6) 6 = 1 := by
    rw [← hk, Nat.gcd_comm k 6, Nat.gcd_rec 6 k, Nat.gcd_comm]
  have hlt : k % 6 < 6 := Nat.mod_lt _ (by norm_num)
  rw [pow_mod_of_pow_eq_one yEl_pow_six k]
  interval_cases h : (k % 6)
  · exact absurd hgcd (by decide)
  · rw [pow_one]
  · exact absurd hgcd (by decide)
  · exact absurd hgcd (by decide)
  · exact absurd hgcd (by decide)
  · rw [hfive]; exact hinv

/-- A word in the two generators conjugating `z` to its cube. -/
def gz0 : Perm (Fin 8) :=
  xPerm * zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * xPerm

lemma gz0_mem : gz0 ∈ PGL2F7 := by
  have hx := xPerm_mem
  have hz := zPerm_mem
  have hzi := zPerm_inv_mem
  exact mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hx hzi) hzi) hx) hz) hx

/-- The conjugator cubing the unipotent entry. -/
def gzEl : ↥PGL2F7 := ⟨gz0, gz0_mem⟩

lemma conj_zEl_cube : gzEl * zEl * gzEl⁻¹ = zEl ^ 3 := by
  apply Subtype.ext
  show gz0 * zPerm * gz0⁻¹ = zPerm ^ 3
  decide

/-- Conjugating by `gz` triples the exponent of the unipotent element. -/
lemma mk_zEl_conj (k : ℕ) : ConjClasses.mk (zEl ^ (3 * k)) = ConjClasses.mk (zEl ^ k) := by
  refine (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gzEl, ?_⟩)).symm
  have h : ∀ n : ℕ, gzEl * zEl ^ n * gzEl⁻¹ = (gzEl * zEl * gzEl⁻¹) ^ n := by
    intro n
    induction n with
    | zero => simp
    | succ m ih => rw [pow_succ, pow_succ, ← ih]; group
  rw [h k, conj_zEl_cube, ← pow_mul]

lemma zEl_pow_mod (u : ℕ) : zEl ^ u = zEl ^ (u % 7) := pow_mod_of_pow_eq_one zEl_pow_seven u

/-- Tripling the exponent modulo seven does not change the class of the power. -/
lemma mk_zEl_step {j k : ℕ} (h : j % 7 = (3 * k) % 7) :
    ConjClasses.mk (zEl ^ j) = ConjClasses.mk (zEl ^ k) := by
  rw [zEl_pow_mod j, h, ← zEl_pow_mod (3 * k)]
  exact mk_zEl_conj k

/-- The class `7A` is rational: in `PGL₂(𝔽₇)` — unlike in `PSL₂(𝔽₇)` — the Borel realises every
unit modulo seven, and `3` is a primitive root, so one conjugator already reaches every power. -/
theorem rational_z : IsRationalClass (ConjClasses.mk zEl) := by
  refine isRationalClass_mk_of_rep ?_
  intro k hk
  rw [orderOf_zEl] at hk
  have e1 : ConjClasses.mk (zEl ^ 1) = ConjClasses.mk zEl := by rw [pow_one]
  have e3 : ConjClasses.mk (zEl ^ 3) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 3) (k := 1) (by norm_num)).trans e1
  have e2 : ConjClasses.mk (zEl ^ 2) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 2) (k := 3) (by norm_num)).trans e3
  have e6 : ConjClasses.mk (zEl ^ 6) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 6) (k := 2) (by norm_num)).trans e2
  have e4 : ConjClasses.mk (zEl ^ 4) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 4) (k := 6) (by norm_num)).trans e6
  have e5 : ConjClasses.mk (zEl ^ 5) = ConjClasses.mk zEl :=
    (mk_zEl_step (j := 5) (k := 4) (by norm_num)).trans e4
  have h7 : ¬ (7 ∣ k) := by
    intro h
    have : (7 : ℕ) ∣ Nat.gcd k 7 := Nat.dvd_gcd h dvd_rfl
    rw [hk] at this
    omega
  obtain ⟨j, hj1, hj2, hjk⟩ : ∃ j, 1 ≤ j ∧ j < 7 ∧ k % 7 = j :=
    ⟨k % 7, by omega, Nat.mod_lt _ (by norm_num), rfl⟩
  rw [zEl_pow_mod k, hjk]
  interval_cases j
  exacts [e1, e2, e3, e4, e5, e6]

theorem rational : ∀ i, IsRationalClass (classTriple i) := by
  intro i
  fin_cases i
  exacts [rational_x, rational_y, rational_z]

/-! ### The certificate -/

/-- **A rational rigidity certificate for `PGL₂(𝔽₇)`.**  The triple `(2B, 6A, 7A)` is rigid,
generating and rational, and the group is centerless. -/
noncomputable def cert : RigidityCertificate ↥PGL2F7 :=
  RigidityCertificate.ofStructureConstant classTriple center_eq_bot rational gen_top
    xEl_mem_prodOneFibre classTriple_two (le_trans card_prodOneFibre_le seven_le_centralizer)

/-- **`PGL₂(𝔽₇)` is a regular Galois group over `ℚ(T)`.** -/
theorem isRegularInverseGalois : IsRegularInverseGalois ↥PGL2F7 :=
  cert.isRegularInverseGalois

/-- **`PGL₂(𝔽₇)` is a Galois group over `ℚ`.** -/
theorem isInverseGalois : IsInverseGalois ↥PGL2F7 :=
  Rigidity.rigidity_realizable cert

end PGL27

end Rigidity
