/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.Examples.PermCode

/-!
# `PSL₂(𝔽₁₁)` is a regular Galois group over a number field

The simple group `PSL₂(𝔽₁₁)` of order `660` acts faithfully on the projective line `ℙ¹(𝔽₁₁)`, a
set of `12` points, so it is realised here as the subgroup of `Equiv.Perm (Fin 12)` generated by
the two Möbius maps `z : t ↦ t + 1` and `x : t ↦ -1/t`. It is the index-two subgroup of the
`PGL₂(𝔽₁₁)` acting on the same points.

The triple of classes `(2A, 3A, 11A)` — the class of the involution `x`, the class of `y =
x⁻¹z⁻¹`, of order `3`, and the class of the translation `z` — is **rigid**: its product-one fibre
above `z` has exactly `11 = |C(z)|` elements.  It is however not **rational**: `PSL₂(𝔽₁₁)` has two
classes of elements of order `11`, distinguished by whether the exponent is a square modulo `11`,
and the exponents prime to `11` interchange them. The class triple is therefore stable only under
an index-two subgroup of the cyclotomic action, and the rigidity method descends the geometric
cover not to `ℚ(T)` but to `K(T)` for the number field `K` that subgroup cuts out.  Both members
of the cyclotomic orbit, `(2A, 3A, 11A)` and `(2A, 3A, 11B)`, are rigid, which is what the descent
needs.

All the finite computations are carried out on base-`12` numerals through
`InverseGalois.Rigidity.Examples.PermCode`, so the kernel verifies them with `decide`.

## Main results

* `Rigidity.PSL2F11.center_eq_bot` — `PSL₂(𝔽₁₁)` is centerless.
* `Rigidity.PSL2F11.rigid_triple` — the triple `(2A, 3A, 11A)` is rigid.
* `Rigidity.PSL2F11.rigid_triple'` — the mirror triple `(2A, 3A, 11B)` is rigid.
* `Rigidity.PSL2F11.orbit_rigid` — every cyclotomic twist of the triple is rigid.
* `Rigidity.PSL2F11.exists_regular_numberField` — `PSL₂(𝔽₁₁)` is a regular Galois group over
  `K(T)` for some number field `K`.
-/

namespace Rigidity

namespace PSL2F11

open Equiv Rigidity.PermCode

set_option maxHeartbeats 4000000
set_option maxRecDepth 40000

/-! ### The group and its two generators -/

/-- The Möbius involution `t ↦ -1/t` of `ℙ¹(𝔽₁₁)`. -/
def xPerm : Perm (Fin 12) := c[0, 11] * c[1, 10] * c[2, 5] * c[3, 7] * c[4, 8] * c[6, 9]

/-- The Möbius translation `t ↦ t + 1` of `ℙ¹(𝔽₁₁)`, the `11`-cycle fixing `∞ = 11`. -/
def zPerm : Perm (Fin 12) := c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

/-- **`PSL₂(𝔽₁₁)`**, as the subgroup of `Perm (Fin 12)` generated by the two Möbius maps. -/
abbrev PSL : Subgroup (Perm (Fin 12)) := gen2 xPerm zPerm

lemma xPerm_mem : xPerm ∈ PSL := x_mem xPerm zPerm

lemma zPerm_mem : zPerm ∈ PSL := z_mem xPerm zPerm

lemma zPerm_inv_mem : zPerm⁻¹ ∈ PSL := inv_mem zPerm_mem

lemma xE_coe : ((xE xPerm zPerm : ↥PSL) : Perm (Fin 12)) = xPerm := rfl

lemma zE_coe : ((zE xPerm zPerm : ↥PSL) : Perm (Fin 12)) = zPerm := rfl

lemma yE_coe : ((yE xPerm zPerm : ↥PSL) : Perm (Fin 12)) = xPerm⁻¹ * zPerm⁻¹ := rfl

lemma xPerm_sq : xPerm * xPerm = 1 := by decide

lemma xE_sq : xE xPerm zPerm * xE xPerm zPerm = 1 := Subtype.ext xPerm_sq

/-! ### The class of the involution, as a list of codes -/

/-- The `55` base-`12` codes of the class of the involution `x`. -/
def TX : List ℕ :=
  [94731018899, 222639505451, 260185925615, 354883849859, 610337009843, 766432361662,
   960749473673, 1204318440710, 1253203311448, 1354086085242, 1518329188750, 1675077696501,
   1834650848305, 1883495403548, 1937430852412, 2336277447196, 2507752264820, 2607870897907,
   2684320694209, 2765105909742, 3127284733639, 3297338269808, 3412269290705, 3471724700301,
   3583599326846, 3753211606606, 3778057881345, 3859629122096, 3971170565538, 4159586070387,
   4538777416250, 4627101778937, 4654335663560, 4774623917151, 4983630491521, 5352378595542,
   5394968911552, 5494286911718, 5574707637873, 5811170875851, 5964364229098, 6036527341999,
   6109081660000, 6341006447655, 6557886782249, 6747133229650, 6993028934353, 7054291183159,
   7115977917026, 7243621344927, 8113440113625, 8124099154171, 8127228022518, 8135119516205,
   8156407279537]

theorem TX_closed : ConjClosed xPerm zPerm TX := by decide +kernel

theorem TX_mem_x : φ xPerm ∈ TX := by decide

/-! ### The group is centerless -/

/-- The `zPerm`-orbit of the image of the fixed point under `xPerm`. -/
def orbList : List (Fin 12) := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

theorem center_eq_bot : Subgroup.center ↥PSL = ⊥ :=
  center_eq_bot_of (x := xPerm) (z := zPerm) 11 (by decide) (by decide) orbList
    (by decide) (by decide)

/-! ### Orders of the three entries -/

lemma orderOf_xE : orderOf (xE xPerm zPerm) = 2 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [xE_coe]; decide)
    (by rw [xE_coe]; decide)

lemma orderOf_yE : orderOf (yE xPerm zPerm) = 3 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [yE_coe]; decide)
    (by rw [yE_coe]; decide)

lemma orderOf_zE : orderOf (zE xPerm zPerm) = 11 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [zE_coe]; decide)
    (by rw [zE_coe]; decide)

lemma xE_pow_two : (xE xPerm zPerm) ^ 2 = 1 := by
  rw [← orderOf_xE]; exact pow_orderOf_eq_one _

lemma yE_pow_three : (yE xPerm zPerm) ^ 3 = 1 := by
  rw [← orderOf_yE]; exact pow_orderOf_eq_one _

lemma zE_pow_p : (zE xPerm zPerm) ^ 11 = 1 := by
  rw [← orderOf_zE]; exact pow_orderOf_eq_one _

/-! ### The structure constant of `(2A, 3A, 11A)` -/

/-- Every element of the middle class passes the order-three test on codes. -/
theorem testOrd_of_yE : ∀ u : ↥PSL, ConjClasses.mk u = ConjClasses.mk (yE xPerm zPerm) →
    testOrd 12 3 [1] (φ (u : Perm (Fin 12))) = true :=
  testOrd_of_class (divs := [1]) orderOf_yE (by decide)

theorem fibreList_length : (fibreList zPerm TX (testOrd 12 3 [1])).length = 11 := by
  decide +kernel

theorem card_prodOneFibre_le_centralizer :
    Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
        (zE xPerm zPerm))
      ≤ Nat.card ↥(Subgroup.centralizer ({zE xPerm zPerm} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
          (zE xPerm zPerm))
      ≤ (fibreList zPerm TX (testOrd 12 3 [1])).length :=
        card_prodOneFibre_le TX_closed TX_mem_x xPerm_sq testOrd_of_yE
    _ = 11 := fibreList_length
    _ ≤ _ := le_card_centralizer orderOf_zE

/-- **The triple `(2A, 3A, 11A)` is rigid in `PSL₂(𝔽₁₁)`.** -/
theorem rigid_triple : Nat.card ↥(rigidTuples (classTriple xPerm zPerm)) = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot (gen_top xPerm zPerm)
    (xE_mem_prodOneFibre xPerm zPerm) (classTriple_two xPerm zPerm).symm
    card_prodOneFibre_le_centralizer

/-! ### The mirror triple `(2A, 3A, 11B)`

The `11`-th roots of unity split into the squares modulo `11` and the non-squares, and the two
classes of elements of order `11` split with them: `z` and `z^2` are not conjugate.  Everything
above therefore has a mirror image, obtained by replacing `z` by `z^2`; both triples are needed
below, because the cyclotomic orbit of `(2A, 3A, 11A)` consists of exactly these two triples. -/

/-- The mirror third entry: the `2`-nd power of the translation, in the other class of
elements of order `11`. -/
def vEl : ↥PSL := (zE xPerm zPerm) ^ 2

lemma vEl_coe : ((vEl : ↥PSL) : Perm (Fin 12)) = zPerm ^ 2 := rfl

/-- The triple of classes `(2A, 3A, 11B)`. -/
def classTriple' : Fin 3 → ConjClasses ↥PSL :=
  ![ConjClasses.mk (xE xPerm zPerm), ConjClasses.mk (yE xPerm zPerm), ConjClasses.mk vEl]

lemma classTriple'_two : classTriple' 2 = ConjClasses.mk vEl := rfl

/-- A word in the two generators conjugating the involution to the mirror witness. -/
def cx0 : Perm (Fin 12) := zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹

lemma cx0_mem : cx0 ∈ PSL := mul_mem (mul_mem (mul_mem (zPerm_mem) xPerm_mem) zPerm_inv_mem) zPerm_inv_mem

/-- The conjugator, as an element of the group. -/
def cx0El : ↥PSL := ⟨cx0, cx0_mem⟩

/-- The witness of the mirror product-one fibre: a conjugate of the involution. -/
def x0El : ↥PSL := cx0El * xE xPerm zPerm * cx0El⁻¹

/-- The witness, as a permutation. -/
def x0Perm : Perm (Fin 12) := cx0 * xPerm * cx0⁻¹

lemma x0El_coe : ((x0El : ↥PSL) : Perm (Fin 12)) = x0Perm := rfl

/-- The witness lies in the class of the involution. -/
lemma mk_x0 : ConjClasses.mk x0El = ConjClasses.mk (xE xPerm zPerm) :=
  (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨cx0El, rfl⟩)).symm

/-- A word in the two generators conjugating the mirror middle entry to `y`. -/
def cy0 : Perm (Fin 12) := zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * xPerm * zPerm⁻¹ * xPerm * zPerm

lemma cy0_mem : cy0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (zPerm_inv_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem

/-- The mirror middle entry lies in the class of `y`. -/
lemma mk_mirror_mid : ConjClasses.mk (x0El⁻¹ * vEl⁻¹) = ConjClasses.mk (yE xPerm zPerm) :=
  mk_eq_mk_of_perm cy0_mem
    (by show cy0 * (x0Perm⁻¹ * (zPerm ^ 2)⁻¹) * cy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

theorem x0El_mem_prodOneFibre :
    x0El ∈ prodOneFibre (classTriple' 0) (classTriple' 1) vEl :=
  ⟨mk_x0, mk_mirror_mid⟩

/-- The mirror pair generates. -/
theorem gen_top' : Subgroup.closure ({x0El, vEl} : Set ↥PSL) = ⊤ := by
  have hx0 : x0El ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hv : vEl ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  have hz : zE xPerm zPerm ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) := by
    have hzv : zE xPerm zPerm = vEl ^ 6 := Subtype.ext (by decide)
    rw [hzv]; exact pow_mem hv 6
  have hx : xE xPerm zPerm ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) := by
    have hxw : xE xPerm zPerm = ((zE xPerm zPerm)⁻¹) * ((zE xPerm zPerm)⁻¹) * (x0El) * (zE xPerm zPerm) * (x0El) * (zE xPerm zPerm) * (x0El) * (zE xPerm zPerm) * (zE xPerm zPerm) * (zE xPerm zPerm) := Subtype.ext (by decide)
    rw [hxw]
    exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (inv_mem hz) (inv_mem hz)) hx0) hz) hx0) hz) hx0) hz) hz) hz)
  exact top_of_mem xPerm zPerm hx hz

lemma orderOf_vEl : orderOf vEl = 11 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [vEl_coe]; decide)
    (by rw [vEl_coe]; decide)

theorem fibreList_v_length :
    (fibreList ((vEl : ↥PSL) : Perm (Fin 12)) TX (testOrd 12 3 [1])).length = 11 := by
  rw [vEl_coe]
  decide +kernel

theorem card_prodOneFibre_le_centralizer' :
    Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) vEl)
      ≤ Nat.card ↥(Subgroup.centralizer ({vEl} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) vEl)
      ≤ (fibreList ((vEl : ↥PSL) : Perm (Fin 12)) TX (testOrd 12 3 [1])).length :=
        card_prodOneFibre_le_of TX_closed TX_mem_x xPerm_sq testOrd_of_yE vEl
    _ = 11 := fibreList_v_length
    _ ≤ _ := le_card_centralizer_of orderOf_vEl

/-- **The mirror triple `(2A, 3A, 11B)` is rigid in `PSL₂(𝔽₁₁)`.** -/
theorem rigid_triple' : Nat.card ↥(rigidTuples classTriple') = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot gen_top' x0El_mem_prodOneFibre
    classTriple'_two.symm card_prodOneFibre_le_centralizer'

/-! ### The cyclotomic orbit of the triple -/

/-- A word in the two generators inverting the middle entry. -/
def gy0 : Perm (Fin 12) := zPerm⁻¹ * xPerm * zPerm * zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm

lemma gy0_mem : gy0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem

/-- The square of the middle entry is its inverse, hence in its own class. -/
lemma mk_yE_sq : ConjClasses.mk ((yE xPerm zPerm) ^ 2) = ConjClasses.mk (yE xPerm zPerm) := by
  have h2 : (yE xPerm zPerm) ^ 2 = (yE xPerm zPerm)⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    calc (yE xPerm zPerm) ^ 2 * (yE xPerm zPerm) = (yE xPerm zPerm) ^ 3 := by group
      _ = 1 := yE_pow_three
  rw [h2]
  exact mk_inv_eq_mk_of_perm gy0_mem
    (by show gy0 * (xPerm⁻¹ * zPerm⁻¹)⁻¹ * gy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

/-- A word in the two generators raising the translation to the power `3`. -/
def gz0 : Perm (Fin 12) := xPerm * zPerm * zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * xPerm

lemma gz0_mem : gz0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (xPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) xPerm_mem

/-- The conjugator raising the translation, as an element of the group. -/
def gzEl : ↥PSL := ⟨gz0, gz0_mem⟩

lemma conj_zE_pow : gzEl * (zE xPerm zPerm) * gzEl⁻¹ = (zE xPerm zPerm) ^ 3 := by
  apply Subtype.ext
  show gz0 * zPerm * gz0⁻¹ = zPerm ^ 3
  decide

/-- Conjugating by `gz0` multiplies the exponent of the translation by `3`. -/
lemma mk_zE_conj (k : ℕ) :
    ConjClasses.mk ((zE xPerm zPerm) ^ (3 * k)) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  refine (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gzEl, ?_⟩)).symm
  have h : ∀ j : ℕ, gzEl * (zE xPerm zPerm) ^ j * gzEl⁻¹
      = (gzEl * (zE xPerm zPerm) * gzEl⁻¹) ^ j := by
    intro j
    induction j with
    | zero => simp
    | succ i ih => rw [pow_succ, pow_succ, ← ih]; group
  rw [h k, conj_zE_pow, ← pow_mul]

/-- The translation may be reduced modulo `11`. -/
lemma zE_pow_mod (u : ℕ) :
    (zE xPerm zPerm) ^ u = (zE xPerm zPerm) ^ (u % 11) :=
  pow_mod_of_pow_eq_one zE_pow_p u

/-- Multiplying the exponent by `3` modulo `11` does not change the class of the power. -/
lemma mk_zE_step {j k : ℕ} (h : j % 11 = (3 * k) % 11) :
    ConjClasses.mk ((zE xPerm zPerm) ^ j) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  rw [zE_pow_mod j, h, ← zE_pow_mod (3 * k)]
  exact mk_zE_conj k

/-- **Every power of the translation by an exponent prime to `11` lies in one of the two classes
`11A`, `11B`.**  The residues fall into the squares modulo `11` and the non-squares, and
conjugation by `gz0` cycles each of the two sets. -/
lemma mk_zE_pow_cases {k : ℕ} (hk : ¬ (11 ∣ k)) :
    ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk vEl := by
  have e1 : ConjClasses.mk ((zE xPerm zPerm) ^ 1) = ConjClasses.mk (zE xPerm zPerm) := by
    rw [pow_one]
  have e2 : ConjClasses.mk ((zE xPerm zPerm) ^ 2) = ConjClasses.mk vEl := rfl
  have e3 : ConjClasses.mk ((zE xPerm zPerm) ^ 3) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 3) (k := 1) (by norm_num)).trans e1
  have e9 : ConjClasses.mk ((zE xPerm zPerm) ^ 9) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 9) (k := 3) (by norm_num)).trans e3
  have e5 : ConjClasses.mk ((zE xPerm zPerm) ^ 5) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 5) (k := 9) (by norm_num)).trans e9
  have e4 : ConjClasses.mk ((zE xPerm zPerm) ^ 4) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 4) (k := 5) (by norm_num)).trans e5
  have e6 : ConjClasses.mk ((zE xPerm zPerm) ^ 6) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 6) (k := 2) (by norm_num)).trans e2
  have e7 : ConjClasses.mk ((zE xPerm zPerm) ^ 7) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 7) (k := 6) (by norm_num)).trans e6
  have e10 : ConjClasses.mk ((zE xPerm zPerm) ^ 10) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 10) (k := 7) (by norm_num)).trans e7
  have e8 : ConjClasses.mk ((zE xPerm zPerm) ^ 8) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 8) (k := 10) (by norm_num)).trans e10
  obtain ⟨j, hj1, hj2, hjk⟩ : ∃ j, 1 ≤ j ∧ j < 11 ∧ k % 11 = j :=
    ⟨k % 11, by omega, Nat.mod_lt _ (by norm_num), rfl⟩
  rw [zE_pow_mod k, hjk]
  interval_cases j
  exacts [Or.inl e1, Or.inr e2, Or.inl e3, Or.inl e4, Or.inl e5, Or.inr e6, Or.inr e7, Or.inr e8,
    Or.inl e9, Or.inr e10]

/-- No prime dividing `66` divides an exponent prime to `66`. -/
lemma not_dvd_of_coprime {u q : ℕ} (hq : q.Prime) (hqd : q ∣ 66)
    (h : Nat.Coprime u 66) : ¬ q ∣ u :=
  hq.coprime_iff_not_dvd.mp (Nat.Coprime.coprime_dvd_right hqd h).symm

/-- **Every cyclotomic twist of the triple `(2A, 3A, 11A)` is rigid.**  The twist by an
exponent prime to `66` is either the triple itself or its mirror image. -/
theorem orbit_rigid (u : Fin 3 → ℕ) (hu : ∀ i, Nat.Coprime (u i) 66) :
    Nat.card ↥(rigidTuples fun i =>
        ConjClasses.powClass (u i) (classTriple xPerm zPerm i)) = Nat.card ↥PSL := by
  have hx : ConjClasses.powClass (u 0) (classTriple xPerm zPerm 0)
      = ConjClasses.mk (xE xPerm zPerm) := by
    rw [classTriple_zero, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one xE_pow_two (u 0)]
    have h2 : ¬ (2 ∣ u 0) := not_dvd_of_coprime Nat.prime_two (by norm_num) (hu 0)
    rw [show u 0 % 2 = 1 by omega, pow_one]
  have hy : ConjClasses.powClass (u 1) (classTriple xPerm zPerm 1)
      = ConjClasses.mk (yE xPerm zPerm) := by
    rw [classTriple_one, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one yE_pow_three (u 1)]
    have h3 : ¬ (3 ∣ u 1) := not_dvd_of_coprime Nat.prime_three (by norm_num) (hu 1)
    rcases (by omega : u 1 % 3 = 1 ∨ u 1 % 3 = 2) with h | h
    · rw [h, pow_one]
    · rw [h]; exact mk_yE_sq
  have hz : ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2)
        = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2) = ConjClasses.mk vEl := by
    rw [classTriple_two, ConjClasses.powClass_mk]
    exact mk_zE_pow_cases (not_dvd_of_coprime (by norm_num) (by norm_num) (hu 2))
  rcases hz with hz | hz
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple xPerm zPerm from ?_]
    · exact rigid_triple
    · funext i; fin_cases i
      exacts [hx, hy, hz]
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple' from ?_]
    · exact rigid_triple'
    · funext i; fin_cases i
      exacts [hx, hy, hz]

/-! ### `PSL₂(𝔽₁₁)` is a regular Galois group over a number field -/

/-- The prescribed classes are made of elements of order dividing `66`. -/
theorem order_dvd (i : Fin 3) (g : ↥PSL)
    (hg : ConjClasses.mk g = classTriple xPerm zPerm i) : orderOf g ∣ 66 := by
  fin_cases i
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := xE xPerm zPerm) hg, orderOf_xE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := yE xPerm zPerm) hg, orderOf_yE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := zE xPerm zPerm) hg, orderOf_zE]; norm_num

/-- The prescribed classes carry a generating product-one triple. -/
theorem rigidTuples_nonempty : (rigidTuples (classTriple xPerm zPerm)).Nonempty := by
  rcases Set.eq_empty_or_nonempty (rigidTuples (classTriple xPerm zPerm)) with h | h
  · exfalso
    haveI : Nonempty ↥PSL := ⟨1⟩
    have hpos : 0 < Nat.card ↥PSL := Nat.card_pos
    have hcard := rigid_triple
    haveI : IsEmpty ↥(rigidTuples (classTriple xPerm zPerm)) := by rw [h]; infer_instance
    rw [Nat.card_of_isEmpty] at hcard
    omega
  · exact h

/-- **`PSL₂(𝔽₁₁)` is a regular Galois group over a number field.**

The triple `(2A, 3A, 11A)` is rigid and generating and the group is centerless, but the two
classes of elements of order `11` are irrational: the exponents prime to `11` interchange them.
The classes are therefore stable only under an index-two subgroup of the cyclotomic action, and
the rigidity method descends the geometric cover not to `ℚ(T)` but to `K(T)` for the number field
`K` that subgroup cuts out. -/
theorem exists_regular_numberField :
    ∃ (K : Type) (_ : Field K) (_ : NumberField K), IsRegularGaloisGroupOver K ↥PSL :=
  Rigidity.RET.Descent.exists_regular_numberField_of_orbitRigid (n := 66)
    (classTriple xPerm zPerm) (center_triv_iff_center_eq_bot.mpr center_eq_bot) order_dvd
    rigidTuples_nonempty orbit_rigid

end PSL2F11

end Rigidity
