/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.Examples.PermCode

/-!
# `PSL₂(𝔽₁₉)` is a regular Galois group over a number field

The simple group `PSL₂(𝔽₁₉)` of order `3420` acts faithfully on the projective line `ℙ¹(𝔽₁₉)`, a
set of `20` points, so it is realised here as the subgroup of `Equiv.Perm (Fin 20)` generated by
the two Möbius maps `z : t ↦ t + 1` and `x : t ↦ -1/t`. It is the index-two subgroup of the
`PGL₂(𝔽₁₉)` acting on the same points.

The triple of classes `(2A, 3A, 19A)` — the class of the involution `x`, the class of `y =
x⁻¹z⁻¹`, of order `3`, and the class of the translation `z` — is **rigid**: its product-one fibre
above `z` has exactly `19 = |C(z)|` elements.  It is however not **rational**: `PSL₂(𝔽₁₉)` has two
classes of elements of order `19`, distinguished by whether the exponent is a square modulo `19`,
and the exponents prime to `19` interchange them. The class triple is therefore stable only under
an index-two subgroup of the cyclotomic action, and the rigidity method descends the geometric
cover not to `ℚ(T)` but to `K(T)` for the number field `K` that subgroup cuts out.  Both members
of the cyclotomic orbit, `(2A, 3A, 19A)` and `(2A, 3A, 19B)`, are rigid, which is what the descent
needs.

All the finite computations are carried out on base-`20` numerals through
`InverseGalois.Rigidity.Examples.PermCode`, so the kernel verifies them with `decide`.

## Main results

* `Rigidity.PSL2F19.center_eq_bot` — `PSL₂(𝔽₁₉)` is centerless.
* `Rigidity.PSL2F19.rigid_triple` — the triple `(2A, 3A, 19A)` is rigid.
* `Rigidity.PSL2F19.rigid_triple'` — the mirror triple `(2A, 3A, 19B)` is rigid.
* `Rigidity.PSL2F19.orbit_rigid` — every cyclotomic twist of the triple is rigid.
* `Rigidity.PSL2F19.exists_regular_numberField` — `PSL₂(𝔽₁₉)` is a regular Galois group over
  `K(T)` for some number field `K`.
-/

namespace Rigidity

namespace PSL2F19

open Equiv Rigidity.PermCode

set_option maxHeartbeats 4000000
set_option maxRecDepth 40000

/-! ### The group and its two generators -/

/-- The Möbius involution `t ↦ -1/t` of `ℙ¹(𝔽₁₉)`. -/
def xPerm : Perm (Fin 20) := c[0, 19] * c[1, 18] * c[2, 9] * c[3, 6] * c[4, 14] * c[5, 15] * c[7, 8] * c[10, 17] * c[11, 12] * c[13, 16]

/-- The Möbius translation `t ↦ t + 1` of `ℙ¹(𝔽₁₉)`, the `19`-cycle fixing `∞ = 19`. -/
def zPerm : Perm (Fin 20) := c[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

/-- **`PSL₂(𝔽₁₉)`**, as the subgroup of `Perm (Fin 20)` generated by the two Möbius maps. -/
abbrev PSL : Subgroup (Perm (Fin 20)) := gen2 xPerm zPerm

lemma xPerm_mem : xPerm ∈ PSL := x_mem xPerm zPerm

lemma zPerm_mem : zPerm ∈ PSL := z_mem xPerm zPerm

lemma zPerm_inv_mem : zPerm⁻¹ ∈ PSL := inv_mem zPerm_mem

lemma xE_coe : ((xE xPerm zPerm : ↥PSL) : Perm (Fin 20)) = xPerm := rfl

lemma zE_coe : ((zE xPerm zPerm : ↥PSL) : Perm (Fin 20)) = zPerm := rfl

lemma yE_coe : ((yE xPerm zPerm : ↥PSL) : Perm (Fin 20)) = xPerm⁻¹ * zPerm⁻¹ := rfl

lemma xPerm_sq : xPerm * xPerm = 1 := by decide

lemma xE_sq : xE xPerm zPerm * xE xPerm zPerm = 1 := Subtype.ext xPerm_sq

/-! ### The class of the involution, as a list of codes -/

/-- The `171` base-`20` codes of the class of the involution `x`. -/
def TX : List ℕ :=
  [401907432008893682291979, 1084025022580983820527119, 1473447924424093179771099,
   1613865081933940398222679, 2015772432033072800514659, 2545021028986029320450219,
   3087312928523817897993779, 4311101379038149800812479, 4700555414371972699256459,
   5420233340071032932497598, 6227801504251255297110785, 6338842691310362591821987,
   7605731833394574963617997, 8314089692809452593200382, 8773379541113441326790386,
   9134109693292548557661588, 9233321632157605356372790, 9593399545283936907243992,
   10832817720328518219727970, 11709434878838830723007765, 11914881855783686074823836,
   13214220745300405483175754, 13636975158310317092247877, 14308767854052237597319601,
   14514214830996630811375672, 14731491137656684886543724, 15185352326482550100599795,
   15886731582282580959356338, 16114322662357920792317973, 16784087005765276678234917,
   17702855459201943341912222, 17918025832564195174873876, 18144995954748488610875511,
   18372618168305299227837146, 19063795541676330893752455, 19506558629408193346715725,
   21384881167937112451106765, 21698224414846363503951351, 22388660147406791164718650,
   23092137703905754444685949, 23404891048795445881522935, 23718234299789994793560282,
   24031610236669959385452868, 24409292698283198134334801, 25036010329678196822257533,
   26959655130736939837887409, 27088323888695541630864454, 27971842028345936574627130,
   28618744000767401022541426, 28995827044540274815374071, 29124495806195515389319096,
   29514684411373827966296122, 30020465708206766653225792, 30538669349558849023043443,
   32263457098717886669750352, 32634181067785039334196950, 33483058826542411497617504,
   34083491243808559344237297, 34453592624766911947884275, 34824347723628138209290873,
   34932961939545875190849851, 35424781619550286055911027, 36152563667370375640964603,
   36772078400039090486660498, 37071525924911564552114371, 37371003026989311059335464,
   37670481603637298785588976, 38332268713949081484365454, 39230673470145816625053932,
   39542602408332364290507425, 40791517583479321219718508, 41402893968714341853185893,
   42163964426918390411086298, 43403875331613158714677507, 43657349053413363080578001,
   44403419550862844389648242, 45150081592417774533925703, 45390480882217977741738596,
   45643330455353325848447070, 45896773125377529056107944, 46639029215387639157516931,
   47271949360383850097707058, 47880871720181648069527316, 48066727567697583916309835,
   48253207567390621782140354, 48688131344506557625882493, 49483532069693394740333270,
   50290762120898304238928447, 50464167684894240024918566, 51880349590998875169094001,
   52483636872598842329248458, 53078972400433774529375505, 54425328260298340901509201,
   54592252406573017270525124, 55355133194026139445739753, 56118015456254300337762743,
   56534567942752490249018286, 56713942446479505754033829, 57129903392763423725937372,
   57859992907695253466115878, 58330987585512785702623295, 58802604855125567862163492,
   59044358504403625532337201, 59273629183877396357870909, 59515353182016894028045017,
   60465309061102269534726523, 61178026258393110577552448, 61407328067476583927734156,
   63363804688872973108268768, 63772204726083481784786607, 64429671136608088378112446,
   64502519806067257502051555, 64837478151046936129838265, 65159955086797790498417394,
   65890892758791292999682323, 66634282266689769641898891, 66956759202440648269685601,
   68735297092056704668399527, 69426883712506971785346255, 69857635492381214640060564,
   70191583991649815144133728, 70288356068713438941014892, 70621713179524544341080456,
   71398242706657660915716309, 72175394748171041112736182, 72521203702873345293617346,
   74351540788490629767666269, 74747641255365672315206963, 75379702537652401202092076,
   75577751990904797261694613, 75775803004527905768977550, 76222889261855847428579707,
   76816416671698484819715357, 77658979247227395430042988, 78093613664371014593493525,
   78675285572051870817238938, 79083570589001275341675574, 79242848374995134326919430,
   79651133391945024035507686, 79957176429179487548228197, 80524708102717796181260689,
   81806599037679116589209948, 82214884054444174297653804, 82941693517857327518962571,
   84226494276221328695932366, 84514784889733910731567393, 84803077133668995292146801,
   85091367746987016172582208, 85668573192534265485605023, 85996119249778129326619857,
   87437575651915064900444514, 87725897472657085780872302, 88591393531532059654482144,
   89388368483272772037011318, 89649538848184437479765569, 90957199377058152866008142,
   91480131647309793578564283, 92003096526011484787264444, 92264235761332876956258714,
   92526028792371902338212585, 92787200713773294564814475, 93584377703316864339468887,
   99358874318968865736746177, 99392980198497470243657934, 99412451343589625711620133,
   99419472201465118072542712, 99439567568970074692657311, 99466029998817722518654089,
   99493144593794611947531267, 99554334016320328542672202, 99573806718087019687594401]

theorem TX_closed : ConjClosed xPerm zPerm TX := by decide +kernel

theorem TX_mem_x : φ xPerm ∈ TX := by decide

/-! ### The group is centerless -/

/-- The `zPerm`-orbit of the image of the fixed point under `xPerm`. -/
def orbList : List (Fin 20) := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

theorem center_eq_bot : Subgroup.center ↥PSL = ⊥ :=
  center_eq_bot_of (x := xPerm) (z := zPerm) 19 (by decide) (by decide) orbList
    (by decide) (by decide)

/-! ### Orders of the three entries -/

lemma orderOf_xE : orderOf (xE xPerm zPerm) = 2 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [xE_coe]; decide)
    (by rw [xE_coe]; decide)

lemma orderOf_yE : orderOf (yE xPerm zPerm) = 3 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [yE_coe]; decide)
    (by rw [yE_coe]; decide)

lemma orderOf_zE : orderOf (zE xPerm zPerm) = 19 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [zE_coe]; decide)
    (by rw [zE_coe]; decide)

lemma xE_pow_two : (xE xPerm zPerm) ^ 2 = 1 := by
  rw [← orderOf_xE]; exact pow_orderOf_eq_one _

lemma yE_pow_three : (yE xPerm zPerm) ^ 3 = 1 := by
  rw [← orderOf_yE]; exact pow_orderOf_eq_one _

lemma zE_pow_p : (zE xPerm zPerm) ^ 19 = 1 := by
  rw [← orderOf_zE]; exact pow_orderOf_eq_one _

/-! ### The structure constant of `(2A, 3A, 19A)` -/

/-- Every element of the middle class passes the order-three test on codes. -/
theorem testOrd_of_yE : ∀ u : ↥PSL, ConjClasses.mk u = ConjClasses.mk (yE xPerm zPerm) →
    testOrd 20 3 [1] (φ (u : Perm (Fin 20))) = true :=
  testOrd_of_class (divs := [1]) orderOf_yE (by decide)

theorem fibreList_length : (fibreList zPerm TX (testOrd 20 3 [1])).length = 19 := by
  decide +kernel

theorem card_prodOneFibre_le_centralizer :
    Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
        (zE xPerm zPerm))
      ≤ Nat.card ↥(Subgroup.centralizer ({zE xPerm zPerm} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
          (zE xPerm zPerm))
      ≤ (fibreList zPerm TX (testOrd 20 3 [1])).length :=
        card_prodOneFibre_le TX_closed TX_mem_x xPerm_sq testOrd_of_yE
    _ = 19 := fibreList_length
    _ ≤ _ := le_card_centralizer orderOf_zE

/-- **The triple `(2A, 3A, 19A)` is rigid in `PSL₂(𝔽₁₉)`.** -/
theorem rigid_triple : Nat.card ↥(rigidTuples (classTriple xPerm zPerm)) = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot (gen_top xPerm zPerm)
    (xE_mem_prodOneFibre xPerm zPerm) (classTriple_two xPerm zPerm).symm
    card_prodOneFibre_le_centralizer

/-! ### The mirror triple `(2A, 3A, 19B)`

The `19`-th roots of unity split into the squares modulo `19` and the non-squares, and the two
classes of elements of order `19` split with them: `z` and `z^2` are not conjugate.  Everything
above therefore has a mirror image, obtained by replacing `z` by `z^2`; both triples are needed
below, because the cyclotomic orbit of `(2A, 3A, 19A)` consists of exactly these two triples. -/

/-- The mirror third entry: the `2`-nd power of the translation, in the other class of
elements of order `19`. -/
def vEl : ↥PSL := (zE xPerm zPerm) ^ 2

lemma vEl_coe : ((vEl : ↥PSL) : Perm (Fin 20)) = zPerm ^ 2 := rfl

/-- The triple of classes `(2A, 3A, 19B)`. -/
def classTriple' : Fin 3 → ConjClasses ↥PSL :=
  ![ConjClasses.mk (xE xPerm zPerm), ConjClasses.mk (yE xPerm zPerm), ConjClasses.mk vEl]

lemma classTriple'_two : classTriple' 2 = ConjClasses.mk vEl := rfl

/-- A word in the two generators conjugating the involution to the mirror witness. -/
def cx0 : Perm (Fin 20) := zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * zPerm * zPerm

lemma cx0_mem : cx0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (zPerm_inv_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem

/-- The conjugator, as an element of the group. -/
def cx0El : ↥PSL := ⟨cx0, cx0_mem⟩

/-- The witness of the mirror product-one fibre: a conjugate of the involution. -/
def x0El : ↥PSL := cx0El * xE xPerm zPerm * cx0El⁻¹

/-- The witness, as a permutation. -/
def x0Perm : Perm (Fin 20) := cx0 * xPerm * cx0⁻¹

lemma x0El_coe : ((x0El : ↥PSL) : Perm (Fin 20)) = x0Perm := rfl

/-- The witness lies in the class of the involution. -/
lemma mk_x0 : ConjClasses.mk x0El = ConjClasses.mk (xE xPerm zPerm) :=
  (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨cx0El, rfl⟩)).symm

/-- A word in the two generators conjugating the mirror middle entry to `y`. -/
def cy0 : Perm (Fin 20) := xPerm * zPerm * xPerm * zPerm⁻¹ * xPerm * zPerm * zPerm * zPerm * zPerm * zPerm * zPerm * zPerm * xPerm

lemma cy0_mem : cy0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (xPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem

/-- The mirror middle entry lies in the class of `y`. -/
lemma mk_mirror_mid : ConjClasses.mk (x0El⁻¹ * vEl⁻¹) = ConjClasses.mk (yE xPerm zPerm) :=
  mk_eq_mk_of_perm cy0_mem
    (by show cy0 * (x0Perm⁻¹ * (zPerm ^ 2)⁻¹) * cy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

theorem x0El_mem_prodOneFibre :
    x0El ∈ prodOneFibre (classTriple' 0) (classTriple' 1) vEl :=
  ⟨mk_x0, mk_mirror_mid⟩

/-- The mirror pair generates. -/
theorem gen_top' : Subgroup.closure ({x0El, vEl} : Set ↥PSL) = ⊤ := by
  have hx0 : x0El ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hv : vEl ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  have hz : zE xPerm zPerm ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) := by
    have hzv : zE xPerm zPerm = vEl ^ 10 := Subtype.ext (by decide)
    rw [hzv]; exact pow_mem hv 10
  have hx : xE xPerm zPerm ∈ Subgroup.closure ({x0El, vEl} : Set ↥PSL) := by
    have hxw : xE xPerm zPerm = (zE xPerm zPerm) * (x0El) * (zE xPerm zPerm) * (x0El) * (zE xPerm zPerm) * (x0El) * ((zE xPerm zPerm)⁻¹) * (x0El) * ((zE xPerm zPerm)⁻¹) * (x0El) * ((zE xPerm zPerm)⁻¹) := Subtype.ext (by decide)
    rw [hxw]
    exact (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem hz hx0) hz) hx0) hz) hx0) (inv_mem hz)) hx0) (inv_mem hz)) hx0) (inv_mem hz))
  exact top_of_mem xPerm zPerm hx hz

lemma orderOf_vEl : orderOf vEl = 19 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [vEl_coe]; decide)
    (by rw [vEl_coe]; decide)

theorem fibreList_v_length :
    (fibreList ((vEl : ↥PSL) : Perm (Fin 20)) TX (testOrd 20 3 [1])).length = 19 := by
  rw [vEl_coe]
  decide +kernel

theorem card_prodOneFibre_le_centralizer' :
    Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) vEl)
      ≤ Nat.card ↥(Subgroup.centralizer ({vEl} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) vEl)
      ≤ (fibreList ((vEl : ↥PSL) : Perm (Fin 20)) TX (testOrd 20 3 [1])).length :=
        card_prodOneFibre_le_of TX_closed TX_mem_x xPerm_sq testOrd_of_yE vEl
    _ = 19 := fibreList_v_length
    _ ≤ _ := le_card_centralizer_of orderOf_vEl

/-- **The mirror triple `(2A, 3A, 19B)` is rigid in `PSL₂(𝔽₁₉)`.** -/
theorem rigid_triple' : Nat.card ↥(rigidTuples classTriple') = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot gen_top' x0El_mem_prodOneFibre
    classTriple'_two.symm card_prodOneFibre_le_centralizer'

/-! ### The cyclotomic orbit of the triple -/

/-- A word in the two generators inverting the middle entry. -/
def gy0 : Perm (Fin 20) := zPerm⁻¹ * xPerm * zPerm * zPerm * xPerm * zPerm⁻¹ * xPerm * zPerm * zPerm * zPerm * zPerm * zPerm * zPerm * zPerm

lemma gy0_mem : gy0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem

/-- The square of the middle entry is its inverse, hence in its own class. -/
lemma mk_yE_sq : ConjClasses.mk ((yE xPerm zPerm) ^ 2) = ConjClasses.mk (yE xPerm zPerm) := by
  have h2 : (yE xPerm zPerm) ^ 2 = (yE xPerm zPerm)⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    calc (yE xPerm zPerm) ^ 2 * (yE xPerm zPerm) = (yE xPerm zPerm) ^ 3 := by group
      _ = 1 := yE_pow_three
  rw [h2]
  exact mk_inv_eq_mk_of_perm gy0_mem
    (by show gy0 * (xPerm⁻¹ * zPerm⁻¹)⁻¹ * gy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

/-- A word in the two generators raising the translation to the power `4`. -/
def gz0 : Perm (Fin 20) := xPerm * zPerm * zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * zPerm * zPerm * zPerm * xPerm

lemma gz0_mem : gz0 ∈ PSL := mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (xPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem) xPerm_mem

/-- The conjugator raising the translation, as an element of the group. -/
def gzEl : ↥PSL := ⟨gz0, gz0_mem⟩

lemma conj_zE_pow : gzEl * (zE xPerm zPerm) * gzEl⁻¹ = (zE xPerm zPerm) ^ 4 := by
  apply Subtype.ext
  show gz0 * zPerm * gz0⁻¹ = zPerm ^ 4
  decide

/-- Conjugating by `gz0` multiplies the exponent of the translation by `4`. -/
lemma mk_zE_conj (k : ℕ) :
    ConjClasses.mk ((zE xPerm zPerm) ^ (4 * k)) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  refine (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gzEl, ?_⟩)).symm
  have h : ∀ j : ℕ, gzEl * (zE xPerm zPerm) ^ j * gzEl⁻¹
      = (gzEl * (zE xPerm zPerm) * gzEl⁻¹) ^ j := by
    intro j
    induction j with
    | zero => simp
    | succ i ih => rw [pow_succ, pow_succ, ← ih]; group
  rw [h k, conj_zE_pow, ← pow_mul]

/-- The translation may be reduced modulo `19`. -/
lemma zE_pow_mod (u : ℕ) :
    (zE xPerm zPerm) ^ u = (zE xPerm zPerm) ^ (u % 19) :=
  pow_mod_of_pow_eq_one zE_pow_p u

/-- Multiplying the exponent by `4` modulo `19` does not change the class of the power. -/
lemma mk_zE_step {j k : ℕ} (h : j % 19 = (4 * k) % 19) :
    ConjClasses.mk ((zE xPerm zPerm) ^ j) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  rw [zE_pow_mod j, h, ← zE_pow_mod (4 * k)]
  exact mk_zE_conj k

/-- **Every power of the translation by an exponent prime to `19` lies in one of the two classes
`19A`, `19B`.**  The residues fall into the squares modulo `19` and the non-squares, and
conjugation by `gz0` cycles each of the two sets. -/
lemma mk_zE_pow_cases {k : ℕ} (hk : ¬ (19 ∣ k)) :
    ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk vEl := by
  have e1 : ConjClasses.mk ((zE xPerm zPerm) ^ 1) = ConjClasses.mk (zE xPerm zPerm) := by
    rw [pow_one]
  have e2 : ConjClasses.mk ((zE xPerm zPerm) ^ 2) = ConjClasses.mk vEl := rfl
  have e4 : ConjClasses.mk ((zE xPerm zPerm) ^ 4) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 4) (k := 1) (by norm_num)).trans e1
  have e16 : ConjClasses.mk ((zE xPerm zPerm) ^ 16) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 16) (k := 4) (by norm_num)).trans e4
  have e7 : ConjClasses.mk ((zE xPerm zPerm) ^ 7) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 7) (k := 16) (by norm_num)).trans e16
  have e9 : ConjClasses.mk ((zE xPerm zPerm) ^ 9) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 9) (k := 7) (by norm_num)).trans e7
  have e17 : ConjClasses.mk ((zE xPerm zPerm) ^ 17) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 17) (k := 9) (by norm_num)).trans e9
  have e11 : ConjClasses.mk ((zE xPerm zPerm) ^ 11) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 11) (k := 17) (by norm_num)).trans e17
  have e6 : ConjClasses.mk ((zE xPerm zPerm) ^ 6) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 6) (k := 11) (by norm_num)).trans e11
  have e5 : ConjClasses.mk ((zE xPerm zPerm) ^ 5) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 5) (k := 6) (by norm_num)).trans e6
  have e8 : ConjClasses.mk ((zE xPerm zPerm) ^ 8) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 8) (k := 2) (by norm_num)).trans e2
  have e13 : ConjClasses.mk ((zE xPerm zPerm) ^ 13) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 13) (k := 8) (by norm_num)).trans e8
  have e14 : ConjClasses.mk ((zE xPerm zPerm) ^ 14) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 14) (k := 13) (by norm_num)).trans e13
  have e18 : ConjClasses.mk ((zE xPerm zPerm) ^ 18) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 18) (k := 14) (by norm_num)).trans e14
  have e15 : ConjClasses.mk ((zE xPerm zPerm) ^ 15) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 15) (k := 18) (by norm_num)).trans e18
  have e3 : ConjClasses.mk ((zE xPerm zPerm) ^ 3) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 3) (k := 15) (by norm_num)).trans e15
  have e12 : ConjClasses.mk ((zE xPerm zPerm) ^ 12) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 12) (k := 3) (by norm_num)).trans e3
  have e10 : ConjClasses.mk ((zE xPerm zPerm) ^ 10) = ConjClasses.mk vEl :=
    (mk_zE_step (j := 10) (k := 12) (by norm_num)).trans e12
  obtain ⟨j, hj1, hj2, hjk⟩ : ∃ j, 1 ≤ j ∧ j < 19 ∧ k % 19 = j :=
    ⟨k % 19, by omega, Nat.mod_lt _ (by norm_num), rfl⟩
  rw [zE_pow_mod k, hjk]
  interval_cases j
  exacts [Or.inl e1, Or.inr e2, Or.inr e3, Or.inl e4, Or.inl e5, Or.inl e6, Or.inl e7, Or.inr e8,
    Or.inl e9, Or.inr e10, Or.inl e11, Or.inr e12, Or.inr e13, Or.inr e14, Or.inr e15, Or.inl e16,
    Or.inl e17, Or.inr e18]

/-- No prime dividing `114` divides an exponent prime to `114`. -/
lemma not_dvd_of_coprime {u q : ℕ} (hq : q.Prime) (hqd : q ∣ 114)
    (h : Nat.Coprime u 114) : ¬ q ∣ u :=
  hq.coprime_iff_not_dvd.mp (Nat.Coprime.coprime_dvd_right hqd h).symm

/-- **Every cyclotomic twist of the triple `(2A, 3A, 19A)` is rigid.**  The twist by an
exponent prime to `114` is either the triple itself or its mirror image. -/
theorem orbit_rigid (u : Fin 3 → ℕ) (hu : ∀ i, Nat.Coprime (u i) 114) :
    Nat.card ↥(rigidTuples fun i =>
        ConjClasses.powClass (u i) (classTriple xPerm zPerm i)) = Nat.card ↥PSL := by
  have hx : ConjClasses.powClass (u 0) (classTriple xPerm zPerm 0)
      = ConjClasses.mk (xE xPerm zPerm) := by
    rw [classTriple_zero, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one xE_pow_two (u 0)]
    have h2 : ¬ (2 ∣ u 0) := not_dvd_of_coprime Nat.prime_two (by norm_num) (hu 0)
    rw [show u 0 % 2 = 1 by omega, pow_one]
  have hy : ConjClasses.powClass (u 1) (classTriple xPerm zPerm 1)
      = ConjClasses.mk (yE xPerm zPerm) := by
    rw [classTriple_one, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one yE_pow_three (u 1)]
    have h3 : ¬ (3 ∣ u 1) := not_dvd_of_coprime Nat.prime_three (by norm_num) (hu 1)
    rcases (by omega : u 1 % 3 = 1 ∨ u 1 % 3 = 2) with h | h
    · rw [h, pow_one]
    · rw [h]; exact mk_yE_sq
  have hz : ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2)
        = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2) = ConjClasses.mk vEl := by
    rw [classTriple_two, ConjClasses.powClass_mk]
    exact mk_zE_pow_cases (not_dvd_of_coprime (by norm_num) (by norm_num) (hu 2))
  rcases hz with hz | hz
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple xPerm zPerm from ?_]
    · exact rigid_triple
    · funext i; fin_cases i
      exacts [hx, hy, hz]
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple' from ?_]
    · exact rigid_triple'
    · funext i; fin_cases i
      exacts [hx, hy, hz]

/-! ### `PSL₂(𝔽₁₉)` is a regular Galois group over a number field -/

/-- The prescribed classes are made of elements of order dividing `114`. -/
theorem order_dvd (i : Fin 3) (g : ↥PSL)
    (hg : ConjClasses.mk g = classTriple xPerm zPerm i) : orderOf g ∣ 114 := by
  fin_cases i
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := xE xPerm zPerm) hg, orderOf_xE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := yE xPerm zPerm) hg, orderOf_yE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := zE xPerm zPerm) hg, orderOf_zE]; norm_num

/-- The prescribed classes carry a generating product-one triple. -/
theorem rigidTuples_nonempty : (rigidTuples (classTriple xPerm zPerm)).Nonempty := by
  rcases Set.eq_empty_or_nonempty (rigidTuples (classTriple xPerm zPerm)) with h | h
  · exfalso
    haveI : Nonempty ↥PSL := ⟨1⟩
    have hpos : 0 < Nat.card ↥PSL := Nat.card_pos
    have hcard := rigid_triple
    haveI : IsEmpty ↥(rigidTuples (classTriple xPerm zPerm)) := by rw [h]; infer_instance
    rw [Nat.card_of_isEmpty] at hcard
    omega
  · exact h

/-- **`PSL₂(𝔽₁₉)` is a regular Galois group over a number field.**

The triple `(2A, 3A, 19A)` is rigid and generating and the group is centerless, but the two
classes of elements of order `19` are irrational: the exponents prime to `19` interchange them.
The classes are therefore stable only under an index-two subgroup of the cyclotomic action, and
the rigidity method descends the geometric cover not to `ℚ(T)` but to `K(T)` for the number field
`K` that subgroup cuts out. -/
theorem exists_regular_numberField :
    ∃ (K : Type) (_ : Field K) (_ : NumberField K), IsRegularGaloisGroupOver K ↥PSL :=
  Rigidity.RET.Descent.exists_regular_numberField_of_orbitRigid (n := 114)
    (classTriple xPerm zPerm) (center_triv_iff_center_eq_bot.mpr center_eq_bot) order_dvd
    rigidTuples_nonempty orbit_rigid

end PSL2F19

end Rigidity
