/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import InverseGalois.Rigidity.Examples.PermCode

/-!
# `PSL₂(𝔽₇)` is a regular Galois group over a number field

The simple group `PSL₂(𝔽₇)` of order `168` acts faithfully on the projective line `ℙ¹(𝔽₇)`, a set
of `8` points, so it is realised here as the subgroup of `Equiv.Perm (Fin 8)` generated by the two
Möbius maps `z : t ↦ t + 1` and `x : t ↦ -1/t`.  Both are even permutations of the eight points —
`z` is a `7`-cycle and `x` a product of four transpositions — and the group they generate is the
index-two subgroup of the `PGL₂(𝔽₇)` of `Rigidity.PGL27`.

The triple of classes `(2A, 3A, 7A)` — the class of the involution `x`, the class of
`y = x⁻¹z⁻¹`, of order `3`, and the class of the translation `z` — is **rigid**: its product-one
fibre above `z` has exactly `7 = |C(z)|` elements.  It is however not **rational**: `PSL₂(𝔽₇)` has
two classes of elements of order `7`, distinguished by whether the exponent is a square modulo `7`,
and the exponents prime to `7` interchange them.  The class triple is therefore stable only under
an index-two subgroup of the cyclotomic action, and the rigidity method descends the geometric
cover not to `ℚ(T)` but to `K(T)` for the number field `K` that subgroup cuts out.  Both members of
the cyclotomic orbit, `(2A, 3A, 7A)` and `(2A, 3A, 7B)`, are rigid, which is what the descent needs.

All the finite computations are carried out on base-`8` numerals through
`InverseGalois.Rigidity.Examples.PermCode`, so the kernel verifies them with `decide`.

## Main results

* `Rigidity.PSL27.center_eq_bot` — `PSL₂(𝔽₇)` is centerless.
* `Rigidity.PSL27.rigid_triple` — the triple `(2A, 3A, 7A)` is rigid.
* `Rigidity.PSL27.rigid_triple'` — the mirror triple `(2A, 3A, 7B)` is rigid.
* `Rigidity.PSL27.orbit_rigid` — every cyclotomic twist of the triple is rigid.
* `Rigidity.PSL27.exists_regular_numberField` — `PSL₂(𝔽₇)` is a regular Galois group over `K(T)`
  for some number field `K`.
-/

namespace Rigidity

namespace PSL27

open Equiv Rigidity.PermCode

set_option maxHeartbeats 1000000
set_option maxRecDepth 40000

/-! ### The group and its two generators -/

/-- The Möbius involution `t ↦ -1/t` of `ℙ¹(𝔽₇)`, a product of four transpositions. -/
def xPerm : Perm (Fin 8) := c[0, 7] * c[1, 6] * c[2, 3] * c[4, 5]

/-- The Möbius translation `t ↦ t + 1` of `ℙ¹(𝔽₇)`, the `7`-cycle fixing `∞ = 7`. -/
def zPerm : Perm (Fin 8) := c[0, 1, 2, 3, 4, 5, 6]

/-- **`PSL₂(𝔽₇)`**, as the subgroup of `Perm (Fin 8)` generated by the two Möbius maps. -/
abbrev PSL : Subgroup (Perm (Fin 8)) := gen2 xPerm zPerm

lemma xPerm_mem : xPerm ∈ PSL := x_mem xPerm zPerm

lemma zPerm_mem : zPerm ∈ PSL := z_mem xPerm zPerm

lemma zPerm_inv_mem : zPerm⁻¹ ∈ PSL := inv_mem zPerm_mem

lemma xE_coe : ((xE xPerm zPerm : ↥PSL) : Perm (Fin 8)) = xPerm := rfl

lemma zE_coe : ((zE xPerm zPerm : ↥PSL) : Perm (Fin 8)) = zPerm := rfl

lemma yE_coe : ((yE xPerm zPerm : ↥PSL) : Perm (Fin 8)) = xPerm⁻¹ * zPerm⁻¹ := rfl

lemma xPerm_sq : xPerm * xPerm = 1 := by decide

lemma xE_sq : xE xPerm zPerm * xE xPerm zPerm = 1 := Subtype.ext xPerm_sq

/-! ### The class of the involution, as a list of codes -/

/-- The `21` base-`8` codes of the class of the involution `x`. -/
def TX : List ℕ :=
  [414967, 571823, 1139551, 2773435, 2895165, 3618874, 4346846, 4557812, 5706211, 6365030,
   7401002, 7810817, 8518230, 8942493, 9272641, 10985779, 11504724, 11789505, 14432341,
   14451948, 14522914]

theorem TX_closed : ConjClosed xPerm zPerm TX := by decide +kernel

theorem TX_mem_x : φ xPerm ∈ TX := by decide

/-! ### The group is centerless -/

/-- The `zPerm`-orbit of the image of the fixed point under `xPerm`. -/
def orbList : List (Fin 8) := [1, 2, 3, 4, 5, 6]

theorem center_eq_bot : Subgroup.center ↥PSL = ⊥ :=
  center_eq_bot_of (x := xPerm) (z := zPerm) 7 (by decide) (by decide) orbList
    (by decide) (by decide)

/-! ### Orders of the three entries -/

lemma orderOf_xE : orderOf (xE xPerm zPerm) = 2 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [xE_coe]; decide)
    (by rw [xE_coe]; decide)

lemma orderOf_yE : orderOf (yE xPerm zPerm) = 3 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [yE_coe]; decide)
    (by rw [yE_coe]; decide)

lemma orderOf_zE : orderOf (zE xPerm zPerm) = 7 :=
  orderOf_eq_of_divs (divs := [1]) (by norm_num) (by decide) (by rw [zE_coe]; decide)
    (by rw [zE_coe]; decide)

lemma xE_pow_two : (xE xPerm zPerm) ^ 2 = 1 := by
  rw [← orderOf_xE]; exact pow_orderOf_eq_one _

lemma yE_pow_three : (yE xPerm zPerm) ^ 3 = 1 := by
  rw [← orderOf_yE]; exact pow_orderOf_eq_one _

lemma zE_pow_seven : (zE xPerm zPerm) ^ 7 = 1 := by
  rw [← orderOf_zE]; exact pow_orderOf_eq_one _

/-! ### The structure constant of `(2A, 3A, 7A)` -/

/-- Every element of the middle class passes the order-three test on codes. -/
theorem testOrd_of_yE : ∀ u : ↥PSL, ConjClasses.mk u = ConjClasses.mk (yE xPerm zPerm) →
    testOrd 8 3 [1] (φ (u : Perm (Fin 8))) = true :=
  testOrd_of_class (divs := [1]) orderOf_yE (by decide)

theorem fibreList_length : (fibreList zPerm TX (testOrd 8 3 [1])).length = 7 := by decide +kernel

theorem card_prodOneFibre_le_centralizer :
    Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
        (zE xPerm zPerm))
      ≤ Nat.card ↥(Subgroup.centralizer ({zE xPerm zPerm} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple xPerm zPerm 0) (classTriple xPerm zPerm 1)
          (zE xPerm zPerm))
      ≤ (fibreList zPerm TX (testOrd 8 3 [1])).length :=
        card_prodOneFibre_le TX_closed TX_mem_x xPerm_sq testOrd_of_yE
    _ = 7 := fibreList_length
    _ ≤ _ := le_card_centralizer orderOf_zE

/-- **The triple `(2A, 3A, 7A)` is rigid in `PSL₂(𝔽₇)`.** -/
theorem rigid_triple : Nat.card ↥(rigidTuples (classTriple xPerm zPerm)) = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot (gen_top xPerm zPerm)
    (xE_mem_prodOneFibre xPerm zPerm) (classTriple_two xPerm zPerm).symm
    card_prodOneFibre_le_centralizer

/-! ### The mirror triple `(2A, 3A, 7B)`

Inversion does not preserve the class of the `7`-cycle: `z` and `z⁻¹` lie in the two distinct
classes of elements of order `7`, which the exponents prime to `7` interchange.  Everything above
therefore has a mirror image, obtained by replacing `z` by `z⁻¹`; both triples are needed below,
because the cyclotomic orbit of `(2A, 3A, 7A)` consists of exactly these two triples. -/

/-- The triple of classes `(2A, 3A, 7B)`.  Its middle entry is again the class of `y`: the two
possible middle entries `x⁻¹z⁻¹` and `x⁻¹z` are conjugate, `PSL₂(𝔽₇)` having a single class of
elements of order three. -/
def classTriple' : Fin 3 → ConjClasses ↥PSL :=
  ![ConjClasses.mk (xE xPerm zPerm), ConjClasses.mk (yE xPerm zPerm),
    ConjClasses.mk ((zE xPerm zPerm)⁻¹)]

lemma classTriple'_zero : classTriple' 0 = ConjClasses.mk (xE xPerm zPerm) := rfl
lemma classTriple'_one : classTriple' 1 = ConjClasses.mk (yE xPerm zPerm) := rfl
lemma classTriple'_two : classTriple' 2 = ConjClasses.mk ((zE xPerm zPerm)⁻¹) := rfl

/-- A word in the two generators conjugating the mirror middle entry to `y`. -/
def cy0 : Perm (Fin 8) :=
  zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹

lemma cy0_mem : cy0 ∈ PSL :=
  mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem zPerm_inv_mem zPerm_inv_mem) xPerm_mem)
    zPerm_mem) xPerm_mem) zPerm_inv_mem) zPerm_inv_mem

/-- The two possible middle entries are conjugate. -/
lemma mk_mirror_mid : ConjClasses.mk ((xE xPerm zPerm)⁻¹ * ((zE xPerm zPerm)⁻¹)⁻¹)
    = ConjClasses.mk (yE xPerm zPerm) :=
  mk_eq_mk_of_perm cy0_mem
    (by show cy0 * (xPerm⁻¹ * (zPerm⁻¹)⁻¹) * cy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

theorem xE_mem_prodOneFibre' :
    xE xPerm zPerm ∈ prodOneFibre (classTriple' 0) (classTriple' 1) ((zE xPerm zPerm)⁻¹) :=
  ⟨rfl, mk_mirror_mid⟩

theorem fibreList_inv_length :
    (fibreList (((zE xPerm zPerm)⁻¹ : ↥PSL) : Perm (Fin 8)) TX (testOrd 8 3 [1])).length = 7 := by
  show (fibreList zPerm⁻¹ TX (testOrd 8 3 [1])).length = 7
  decide +kernel

theorem card_prodOneFibre_le_centralizer' :
    Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) ((zE xPerm zPerm)⁻¹))
      ≤ Nat.card ↥(Subgroup.centralizer ({(zE xPerm zPerm)⁻¹} : Set ↥PSL)) :=
  calc Nat.card (prodOneFibre (classTriple' 0) (classTriple' 1) ((zE xPerm zPerm)⁻¹))
      ≤ (fibreList (((zE xPerm zPerm)⁻¹ : ↥PSL) : Perm (Fin 8)) TX (testOrd 8 3 [1])).length :=
        card_prodOneFibre_le_of TX_closed TX_mem_x xPerm_sq testOrd_of_yE _
    _ = 7 := fibreList_inv_length
    _ ≤ _ := le_card_centralizer_of (by rw [orderOf_inv]; exact orderOf_zE)

/-- **The mirror triple `(2A, 3A, 7B)` is rigid in `PSL₂(𝔽₇)`.** -/
theorem rigid_triple' : Nat.card ↥(rigidTuples classTriple') = Nat.card ↥PSL :=
  rigid_of_card_prodOneFibre center_eq_bot (gen_top_inv xPerm zPerm)
    xE_mem_prodOneFibre' classTriple'_two.symm card_prodOneFibre_le_centralizer'

/-! ### The cyclotomic orbit of the triple -/

/-- A word in the two generators inverting the middle entry. -/
def gy0 : Perm (Fin 8) := zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * xPerm * zPerm * zPerm * zPerm

lemma gy0_mem : gy0 ∈ PSL :=
  mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem zPerm_inv_mem zPerm_inv_mem)
    zPerm_inv_mem) xPerm_mem) zPerm_mem) zPerm_mem) zPerm_mem

/-- The square of the middle entry is its inverse, hence in its own class. -/
lemma mk_yE_sq : ConjClasses.mk ((yE xPerm zPerm) ^ 2) = ConjClasses.mk (yE xPerm zPerm) := by
  have h2 : (yE xPerm zPerm) ^ 2 = (yE xPerm zPerm)⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    calc (yE xPerm zPerm) ^ 2 * (yE xPerm zPerm) = (yE xPerm zPerm) ^ 3 := by group
      _ = 1 := yE_pow_three
  rw [h2]
  exact mk_inv_eq_mk_of_perm gy0_mem
    (by show gy0 * (xPerm⁻¹ * zPerm⁻¹)⁻¹ * gy0⁻¹ = xPerm⁻¹ * zPerm⁻¹; decide)

/-- A word in the two generators squaring the translation. -/
def gz0 : Perm (Fin 8) :=
  xPerm * zPerm * zPerm * xPerm * zPerm⁻¹ * zPerm⁻¹ * zPerm⁻¹ * xPerm

lemma gz0_mem : gz0 ∈ PSL :=
  mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem (mul_mem xPerm_mem zPerm_mem) zPerm_mem)
    xPerm_mem) zPerm_inv_mem) zPerm_inv_mem) zPerm_inv_mem) xPerm_mem

/-- The conjugator squaring the translation, as an element of the group. -/
def gzEl : ↥PSL := ⟨gz0, gz0_mem⟩

lemma conj_zE_sq : gzEl * (zE xPerm zPerm) * gzEl⁻¹ = (zE xPerm zPerm) ^ 2 := by
  apply Subtype.ext
  show gz0 * zPerm * gz0⁻¹ = zPerm ^ 2
  decide

/-- Conjugating by `gz0` doubles the exponent of the translation. -/
lemma mk_zE_conj (k : ℕ) :
    ConjClasses.mk ((zE xPerm zPerm) ^ (2 * k)) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  refine (ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨gzEl, ?_⟩)).symm
  have h : ∀ m : ℕ, gzEl * (zE xPerm zPerm) ^ m * gzEl⁻¹
      = (gzEl * (zE xPerm zPerm) * gzEl⁻¹) ^ m := by
    intro m
    induction m with
    | zero => simp
    | succ j ih => rw [pow_succ, pow_succ, ← ih]; group
  rw [h k, conj_zE_sq, ← pow_mul]

/-- The translation may be reduced modulo seven. -/
lemma zE_pow_mod (u : ℕ) : (zE xPerm zPerm) ^ u = (zE xPerm zPerm) ^ (u % 7) :=
  pow_mod_of_pow_eq_one zE_pow_seven u

/-- Doubling the exponent modulo seven does not change the class of the power. -/
lemma mk_zE_step {j k : ℕ} (h : j % 7 = (2 * k) % 7) :
    ConjClasses.mk ((zE xPerm zPerm) ^ j) = ConjClasses.mk ((zE xPerm zPerm) ^ k) := by
  rw [zE_pow_mod j, h, ← zE_pow_mod (2 * k)]
  exact mk_zE_conj k

/-- The sixth power of the translation is its inverse. -/
lemma zE_pow_six : (zE xPerm zPerm) ^ 6 = (zE xPerm zPerm)⁻¹ := by
  refine eq_inv_of_mul_eq_one_left ?_
  calc (zE xPerm zPerm) ^ 6 * (zE xPerm zPerm) = (zE xPerm zPerm) ^ 7 := by group
    _ = 1 := zE_pow_seven

/-- **Every power of the translation by an exponent prime to seven lies in one of the two classes
`7A`, `7B`.**  The residues fall into the three squares `1, 2, 4`, which conjugation by `gz0`
cycles, and the three non-squares `6, 5, 3`, which it cycles as well. -/
lemma mk_zE_pow_cases {k : ℕ} (hk : ¬ (7 ∣ k)) :
    ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.mk ((zE xPerm zPerm) ^ k) = ConjClasses.mk ((zE xPerm zPerm)⁻¹) := by
  have e1 : ConjClasses.mk ((zE xPerm zPerm) ^ 1) = ConjClasses.mk (zE xPerm zPerm) := by
    rw [pow_one]
  have e6 : ConjClasses.mk ((zE xPerm zPerm) ^ 6) = ConjClasses.mk ((zE xPerm zPerm)⁻¹) := by
    rw [zE_pow_six]
  have e2 : ConjClasses.mk ((zE xPerm zPerm) ^ 2) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 2) (k := 1) (by norm_num)).trans e1
  have e4 : ConjClasses.mk ((zE xPerm zPerm) ^ 4) = ConjClasses.mk (zE xPerm zPerm) :=
    (mk_zE_step (j := 4) (k := 2) (by norm_num)).trans e2
  have e5 : ConjClasses.mk ((zE xPerm zPerm) ^ 5) = ConjClasses.mk ((zE xPerm zPerm)⁻¹) :=
    (mk_zE_step (j := 5) (k := 6) (by norm_num)).trans e6
  have e3 : ConjClasses.mk ((zE xPerm zPerm) ^ 3) = ConjClasses.mk ((zE xPerm zPerm)⁻¹) :=
    (mk_zE_step (j := 3) (k := 5) (by norm_num)).trans e5
  obtain ⟨j, hj1, hj2, hjk⟩ : ∃ j, 1 ≤ j ∧ j < 7 ∧ k % 7 = j :=
    ⟨k % 7, by omega, Nat.mod_lt _ (by norm_num), rfl⟩
  rw [zE_pow_mod k, hjk]
  interval_cases j
  exacts [Or.inl e1, Or.inl e2, Or.inr e3, Or.inl e4, Or.inr e5, Or.inr e6]

/-- No prime dividing `42` divides an exponent prime to `42`. -/
lemma not_dvd_of_coprime {u q : ℕ} (hq : q.Prime) (hqd : q ∣ 42) (h : Nat.Coprime u 42) :
    ¬ q ∣ u :=
  hq.coprime_iff_not_dvd.mp (Nat.Coprime.coprime_dvd_right hqd h).symm

/-- **Every cyclotomic twist of the triple `(2A, 3A, 7A)` is rigid.**  The twist by an exponent
prime to `42` is either the triple itself or its mirror image. -/
theorem orbit_rigid (u : Fin 3 → ℕ) (hu : ∀ i, Nat.Coprime (u i) 42) :
    Nat.card ↥(rigidTuples fun i =>
        ConjClasses.powClass (u i) (classTriple xPerm zPerm i)) = Nat.card ↥PSL := by
  have hx : ConjClasses.powClass (u 0) (classTriple xPerm zPerm 0)
      = ConjClasses.mk (xE xPerm zPerm) := by
    rw [classTriple_zero, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one xE_pow_two (u 0)]
    have h2 : ¬ (2 ∣ u 0) := not_dvd_of_coprime Nat.prime_two (by norm_num) (hu 0)
    rw [show u 0 % 2 = 1 by omega, pow_one]
  have hy : ConjClasses.powClass (u 1) (classTriple xPerm zPerm 1)
      = ConjClasses.mk (yE xPerm zPerm) := by
    rw [classTriple_one, ConjClasses.powClass_mk, pow_mod_of_pow_eq_one yE_pow_three (u 1)]
    have h3 : ¬ (3 ∣ u 1) := not_dvd_of_coprime Nat.prime_three (by norm_num) (hu 1)
    rcases (by omega : u 1 % 3 = 1 ∨ u 1 % 3 = 2) with h | h
    · rw [h, pow_one]
    · rw [h]; exact mk_yE_sq
  have hz : ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2)
        = ConjClasses.mk (zE xPerm zPerm) ∨
      ConjClasses.powClass (u 2) (classTriple xPerm zPerm 2)
        = ConjClasses.mk ((zE xPerm zPerm)⁻¹) := by
    rw [classTriple_two, ConjClasses.powClass_mk]
    exact mk_zE_pow_cases (not_dvd_of_coprime (by norm_num) (by norm_num) (hu 2))
  rcases hz with hz | hz
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple xPerm zPerm from ?_]
    · exact rigid_triple
    · funext i; fin_cases i
      exacts [hx, hy, hz]
  · rw [show (fun i => ConjClasses.powClass (u i) (classTriple xPerm zPerm i))
        = classTriple' from ?_]
    · exact rigid_triple'
    · funext i; fin_cases i
      exacts [hx, hy, hz]

/-! ### `PSL₂(𝔽₇)` is a regular Galois group over a number field -/

/-- The prescribed classes are made of elements of order dividing `42`. -/
theorem order_dvd_fortyTwo (i : Fin 3) (g : ↥PSL)
    (hg : ConjClasses.mk g = classTriple xPerm zPerm i) : orderOf g ∣ 42 := by
  fin_cases i
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := xE xPerm zPerm) hg, orderOf_xE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := yE xPerm zPerm) hg, orderOf_yE]; norm_num
  · rw [ConjClasses.orderOf_eq_of_mk_eq (h := zE xPerm zPerm) hg, orderOf_zE]; norm_num

/-- The prescribed classes carry a generating product-one triple. -/
theorem rigidTuples_nonempty : (rigidTuples (classTriple xPerm zPerm)).Nonempty := by
  rcases Set.eq_empty_or_nonempty (rigidTuples (classTriple xPerm zPerm)) with h | h
  · exfalso
    haveI : Nonempty ↥PSL := ⟨1⟩
    have hpos : 0 < Nat.card ↥PSL := Nat.card_pos
    have hcard := rigid_triple
    haveI : IsEmpty ↥(rigidTuples (classTriple xPerm zPerm)) := by rw [h]; infer_instance
    rw [Nat.card_of_isEmpty] at hcard
    omega
  · exact h

/-- **`PSL₂(𝔽₇)` is a regular Galois group over a number field.**

The triple `(2A, 3A, 7A)` is rigid and generating and the group is centerless, but the two classes
of elements of order `7` are irrational: the exponents prime to `7` interchange them.  The classes
are therefore stable only under an index-two subgroup of the cyclotomic action, and the rigidity
method descends the geometric cover not to `ℚ(T)` but to `K(T)` for the number field `K` that
subgroup cuts out. -/
theorem exists_regular_numberField :
    ∃ (K : Type) (_ : Field K) (_ : NumberField K), IsRegularGaloisGroupOver K ↥PSL :=
  Rigidity.RET.Descent.exists_regular_numberField_of_orbitRigid (n := 42) (classTriple xPerm zPerm)
    (center_triv_iff_center_eq_bot.mpr center_eq_bot) order_dvd_fortyTwo rigidTuples_nonempty
    orbit_rigid

end PSL27

end Rigidity
