import InverseGalois.Solvable.ChiefSeries
import InverseGalois.Solvable.Nilpotent
import InverseGalois.Solvable.PCentral
import InverseGalois.Solvable.PCentralGenerators
import InverseGalois.Solvable.PCentralFree
import InverseGalois.Solvable.PCentralWord
import InverseGalois.Solvable.PCentralFrattini
import InverseGalois.Solvable.PCentralTower
import InverseGalois.Solvable.PCentralCoord
import InverseGalois.Solvable.PCentralCharacter
import InverseGalois.Solvable.PCentralPow
import InverseGalois.Solvable.ElementaryAbelian
import InverseGalois.Solvable.CentralDual
import InverseGalois.Solvable.CentralDualChain
import InverseGalois.Solvable.CentralLineQuotient
import InverseGalois.Solvable.PCentralShrink
import InverseGalois.Solvable.DispositionShrink
import InverseGalois.Solvable.DispositionCharacter
import InverseGalois.Solvable.Wreath
import InverseGalois.Solvable.WreathFunctor
import InverseGalois.Solvable.WreathRecognition
import InverseGalois.Solvable.Semiabelian
import InverseGalois.Solvable.SemiabelianProduct
import InverseGalois.Solvable.Metacyclic
import InverseGalois.Solvable.SemiabelianCriterion
import InverseGalois.Solvable.SemiabelianHall
import InverseGalois.Solvable.SemiabelianSmall
import InverseGalois.Solvable.SemiabelianZGroup
import InverseGalois.Solvable.SemiabelianP2Q
import InverseGalois.Solvable.SemiabelianP2Q2
import InverseGalois.Solvable.SemiabelianP4
import InverseGalois.Solvable.SemiabelianFrattini
import InverseGalois.Solvable.SemiabelianClassTwo
import InverseGalois.Solvable.SemiabelianSmallOrders
import InverseGalois.Solvable.SemiabelianLargePrime
import InverseGalois.Solvable.SemiabelianSylowCount
import InverseGalois.Solvable.SemiabelianAGroup
import InverseGalois.Solvable.SemiabelianFortyEight
import InverseGalois.Solvable.SemiabelianWreath
import InverseGalois.Solvable.WreathCyclic
import InverseGalois.Solvable.Shafarevich

/-!
# Solvable groups as Galois groups

Shafarevich's theorem states that every finite solvable group is a Galois group over `ℚ`.  Its
proof is arithmetic — it runs through embedding problems, class field theory and the
Grunwald–Wang theorem — and the *regular* analogue over `ℚ(T)` is not known even for `p`-groups.
This directory collects the group-theoretic reductions that organize the approach, each of them
free of arithmetic input and applicable to both realization predicates of the development.

* `InverseGalois.Solvable.ChiefSeries` peels a finite solvable group apart along elementary
  abelian normal subgroups, reducing the problem to embedding problems with elementary abelian
  kernel.
* `InverseGalois.Solvable.Nilpotent` assembles a finite nilpotent group from its Sylow subgroups,
  reducing the nilpotent case to `p`-groups.
* `InverseGalois.Solvable.PCentral` introduces the lower `p`-central series, the filtration with
  elementary abelian central quotients that measures how far a `p`-group is from being elementary
  abelian, and shows that it reaches the trivial subgroup in finitely many steps.
* `InverseGalois.Solvable.PCentralGenerators` exhibits each term of that series, modulo the next
  one, as generated by the iterated commutators and `p`-th powers of a set of generators of the
  group, and deduces that a finitely generated group whose series terminates is a finite
  `p`-group.
* `InverseGalois.Solvable.PCentralFree` constructs the free group of a given rank in the variety
  of groups of a given `p`-class, the finite `p`-group of which every group of that rank and class
  is a quotient, and identifies the reduction of its class with a quotient of it.
* `InverseGalois.Solvable.PCentralWord` records the iterated commutators and `p`-th powers that
  produce a basic element as a formal word, so that the generators it involves can be read off and
  substituting `1` for some of the generators can be evaluated.
* `InverseGalois.Solvable.PCentralFrattini` places the first term of the lower `p`-central series
  of a finite `p`-group inside every maximal subgroup, the quotient by a maximal subgroup being
  cyclic of order `p`, and hence inside the Frattini subgroup.
* `InverseGalois.Solvable.PCentralTower` identifies the kernel of the projection of the free object
  of `p`-class `c + 1` onto the free object of `p`-class `c` with a term of the lower `p`-central
  series, and so makes each rung of the tower a central Frattini extension with elementary abelian
  kernel: the shape of embedding problem the Scholz–Reichardt induction climbs.
* `InverseGalois.Solvable.PCentralCoord` identifies the bottom rung of that tower, the free object
  of `p`-class one and rank `d`, with the elementary abelian group of rank `d` and exponent `p`, by
  reading off the coordinates of an element along the generators.
* `InverseGalois.Solvable.PCentralCharacter` composes that identification with the reduction of the
  class to give the free object of positive `p`-class a canonical character onto the elementary
  abelian group of the same rank, characterized by its values on the distinguished generators, onto,
  and with kernel inside the Frattini subgroup.
* `InverseGalois.Solvable.PCentralPow` raises a congruence along the lower `p`-central series to
  the `p`-th power, one step further along at each turn, so that the `p ^ c`-th power map of the
  free object of `p`-class `c + 1` depends only on the coordinates of its argument; the powers of
  the distinguished generators it produces are the nontrivial elements of the kernel of the
  projection that a cyclic subgroup with the coordinates of a single generator already covers.
* `InverseGalois.Solvable.ElementaryAbelian` recognizes a finite abelian group of exponent dividing
  a prime and of order a power of it as that same elementary abelian group, and hence as the free
  object of `p`-class one, its exponent making it a vector space and its order the dimension.
* `InverseGalois.Solvable.CentralDual` presents a subgroup of the centre of exponent `p` as a
  vector space over the field with `p` elements, whose finitely many characters separate its
  elements and extend by `0` to the whole group; at the prime two the kernel of a character not
  vanishing at a given element of order two is a complement of the line that element generates.
* `InverseGalois.Solvable.CentralDualChain` lists the characters of such a subgroup at the prime two
  so that they separate its elements while an independent family inside it is detected only once
  apiece, which is the arrangement an induction cutting the subgroup down one hyperplane at a time
  needs when a distinguished element must survive every stage but one.
* `InverseGalois.Solvable.CentralLineQuotient` reads one stage of that cut as a central extension:
  the quotient by a hyperplane maps onto the quotient by the subgroup with kernel of order two,
  generated by the class of the element the hyperplane omits, and the cyclic group that element
  generates lifts the kernel homomorphically; putting the element back changes nothing about which
  members of the hyperplane a distinguished element reaches.
* `InverseGalois.Solvable.PCentralShrink` collapses a group generated by many copies of a
  generating system onto one copy chosen by a vector of bits, observes that the characters of the
  last term of the lower `2`-central series are polynomial functions of that vector, and applies
  the Chevalley–Warning theorem to annihilate a prescribed array of elements.
* `InverseGalois.Solvable.DispositionShrink` applies that collapse to the free objects themselves:
  the free object of rank `d * r` carries `r` copies of a system of `d` generators, and for large
  enough `r` an array of elements of the last term of its lower `2`-central series is annihilated
  row by row by the collapse onto the free object of rank `d` along a suitable selection of copies.
* `InverseGalois.Solvable.DispositionCharacter` reads that collapse through the coordinate
  characters of the two free objects, where it becomes the linear map summing the coordinates of
  each row over the selected copies, and records that it commutes with the projection of the tower
  and is onto as soon as one copy is selected.
* `InverseGalois.Solvable.Wreath` presents every semidirect product `A ⋊[φ] H` with `A` abelian as
  a quotient of the single regular wreath product `A ≀ᵣ H`, so that a realization of the wreath
  product realizes every split extension of `H` by `A` at once.
* `InverseGalois.Solvable.WreathFunctor` makes `A ≀ᵣ H` functorial in both arguments and exhibits
  `(A₁ × A₂) ≀ᵣ H` as a quotient of the iterated wreath product `A₁ ≀ᵣ (A₂ ≀ᵣ H)`, which lets a
  realization of wreath products propagate along quotients of either factor.
* `InverseGalois.Solvable.WreathRecognition` recognizes a group as a regular wreath product from a
  cocycle of coordinates together with a count, which is how a Galois group acting on conjugate
  layers of a field extension is identified.
* `InverseGalois.Solvable.Semiabelian` defines Dentzer's class of semiabelian groups — the class
  the wreath-product approach reaches — and derives a realization of every one of its members from
  a realization of the wreath products alone.
* `InverseGalois.Solvable.SemiabelianProduct` shows that the semiabelian class is closed under
  finite direct products, and deduces that a finite nilpotent group is semiabelian as soon as each
  of its Sylow subgroups is.
* `InverseGalois.Solvable.Metacyclic` shows that a finite group with a cyclic normal subgroup of
  cyclic quotient is semiabelian, and applies it to the generalized quaternion groups.
* `InverseGalois.Solvable.SemiabelianCriterion` shows that a group covered by a semidirect
  product of an abelian group by a semiabelian one is semiabelian, and deduces that a finite group
  with a normal abelian subgroup of cyclic quotient is semiabelian.
* `InverseGalois.Solvable.SemiabelianHall` supplements a normal abelian subgroup by a complement
  instead of by a cyclic group: a group with a normal abelian subgroup of coprime index, or with a
  normal abelian Sylow subgroup, is semiabelian as soon as the quotient is.
* `InverseGalois.Solvable.SemiabelianSmall` applies the criterion to the small orders: a group with
  an abelian subgroup whose index is the smallest prime factor of the order is semiabelian, and so
  is every group of order `p`, `p ^ 2`, `p ^ 3` or `p * q`.
* `InverseGalois.Solvable.SemiabelianZGroup` shows that a finite group all of whose Sylow subgroups
  are cyclic is metacyclic, hence semiabelian; in particular every group of squarefree order is.
* `InverseGalois.Solvable.SemiabelianP2Q` counts Sylow subgroups to produce a normal one in a group
  of order `p ^ 2 * q`, and concludes that every such group is semiabelian.
* `InverseGalois.Solvable.SemiabelianP2Q2` produces a normal Sylow subgroup in a group of order
  `p ^ 2 * q ^ 2`, the one order at which the counts leave a gap — `36`, with four Sylow
  `3`-subgroups — being settled through the kernel of the conjugation action on them.
* `InverseGalois.Solvable.SemiabelianP4` exhibits a maximal abelian normal subgroup of a group of
  order `p ^ 4` as one of index at most `p`, and concludes that every such group is semiabelian.
* `InverseGalois.Solvable.SemiabelianFrattini` supplements an abelian normal subgroup by a maximal
  subgroup whenever it escapes the Frattini subgroup, turning the covering criterion into an
  induction on the order.
* `InverseGalois.Solvable.SemiabelianClassTwo` runs that induction for a group whose commutator
  subgroup is central: adjoining a generator outside the Frattini subgroup to the centre produces
  the required abelian normal subgroup, so every finite group of nilpotency class at most two is
  semiabelian.
* `InverseGalois.Solvable.SemiabelianSmallOrders` puts the criteria for the individual shapes of
  order together and concludes that every finite group of order less than `24`, and indeed every
  one of order less than `32` other than `24`, is semiabelian.
* `InverseGalois.Solvable.SemiabelianLargePrime` makes the Sylow subgroup at a prime larger than
  the rest of the order unique, hence normal and abelian, so that such a group is semiabelian as
  soon as the quotient by it is.
* `InverseGalois.Solvable.SemiabelianSylowCount` replaces that size comparison by a divisor count:
  when no divisor of the complementary factor other than `1` is congruent to `1` modulo the prime,
  the Sylow subgroup is again unique, a condition that can be checked by evaluation at a concrete
  order.
* `InverseGalois.Solvable.SemiabelianAGroup` runs the Frattini induction for a finite solvable
  group all of whose Sylow subgroups are abelian: Frattini's argument makes a Sylow subgroup of the
  preimage of a minimal normal subgroup of the Frattini quotient normal in the whole group, and it
  escapes the Frattini subgroup, so Thompson's criterion holds and in particular every finite
  solvable group of cubefree order is semiabelian.
* `InverseGalois.Solvable.SemiabelianFortyEight` carries the enumeration of the orders from `32` to
  `48`, the two orders `24` and `32` excepted, and `48` is where it genuinely halts.
* `InverseGalois.Solvable.SemiabelianWreath` shows that the semiabelian class is closed under the
  regular wreath product, hence under its iterates, so that a Sylow `p`-subgroup of a symmetric
  group on `p ^ n` letters is semiabelian.
* `InverseGalois.Solvable.WreathCyclic` splits the bottom group of a wreath product into cyclic
  factors, so that the realization of wreath products only has to be established when the bottom
  group is finite cyclic.
* `InverseGalois.Solvable.Shafarevich` carries out Ore's reduction of the whole theorem to split
  embedding problems with kernel of prime power order, which is where the arithmetic input is
  concentrated.
-/
