/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Residue.AlgClosed
import InverseGalois.CFT.Residue.FrobeniusField
import InverseGalois.CFT.Units.InfiniteDecomposition
import InverseGalois.CFT.Profinite.EmbeddingObstruction

/-!
# The decomposition group at a prime of an algebraic closure

Fix a number field `k`, an algebraic closure `Ω` of it, and a nonzero prime `P` of the ring of
integers of `Ω`.  The stabilizer of `P` in the absolute Galois group acts on the residue field
`𝓞 Ω ⧸ P`, which is an algebraic closure of the finite residue field `𝓞 k ⧸ P ∩ 𝓞 k`, and that
action is surjective onto the automorphisms with kernel the inertia subgroup.  An arithmetic
Frobenius is any preimage of the residue Frobenius.

The two facts recorded here are the two halves of the statement that the decomposition group
modulo inertia is procyclic, generated by an arithmetic Frobenius.  The first is a generation
statement in the only form which is ever needed: an open subgroup of the stabilizer which contains
the inertia subgroup and an arithmetic Frobenius is the whole stabilizer.  The proof spends the
open subgroup on a finite subextension `E`, moves the given element by a power of the Frobenius
until the two agree on the (finite) image of the ring of integers of `E`, and then corrects the
difference by an element which is trivial on `E` — for which one needs surjectivity of the
stabilizer of `P` in `Gal(Ω/E)` onto the automorphisms of the residue field over the residue field
of `E`.  The second is a lifting statement: every element of a finite group is the value at an
arithmetic Frobenius of a smooth homomorphism killing inertia.

Together they give the local lifting theorem in the unramified case: a smooth homomorphism from
the decomposition group to a finite group which kills inertia lifts through any surjection of
finite groups, again smoothly.  Indeed the two homomorphisms one wants to compare agree on
inertia and at an arithmetic Frobenius, and their equalizer is an open subgroup, so the generation
statement forces them to agree everywhere.

## Main results

* `InverseGalois.CFT.exists_mem_fixingSubgroup_stabilizerHom_eq` — an automorphism of the residue
  field trivial on the residue field of a finite subextension comes from an element of the
  stabilizer which is trivial on that subextension.
* `InverseGalois.CFT.exists_arithFrobenius` — **an arithmetic Frobenius generates the stabilizer
  modulo inertia, and takes any prescribed value in a finite group.**
* `InverseGalois.CFT.exists_smoothHom_lift_of_inertia_le_ker` — **an unramified smooth
  homomorphism from a decomposition group to a finite group lifts through any surjection.**

## Tags

number field, algebraic closure, decomposition group, inertia, Frobenius, residue field
-/

namespace InverseGalois.CFT

open NumberField MulAction IntermediateField Pointwise

attribute [local instance] Ideal.Quotient.field
attribute [local instance] InverseGalois.CFT.smulCommClass_ringOfIntegers
attribute [local instance] InverseGalois.CFT.isInvariant_ringOfIntegers_of_isGalois

/-! ### Open subgroups of a subgroup of a Galois group -/

section Open

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- An open subgroup of a subgroup of a Galois group contains the trace on that subgroup of the
subgroup fixing a finite subextension. -/
theorem exists_fixingSubgroup_comap_le {A : Subgroup Gal(Ω/k)} {H : Subgroup ↥A}
    (hH : IsOpen (H : Set ↥A)) :
    ∃ E : IntermediateField k Ω, FiniteDimensional k ↥E ∧
      E.fixingSubgroup.comap A.subtype ≤ H := by
  have h1 : (H : Set ↥A) ∈ nhds (1 : ↥A) := hH.mem_nhds H.one_mem
  rw [nhds_subtype_eq_comap] at h1
  obtain ⟨V, hV, hVH⟩ := Filter.mem_comap.1 h1
  obtain ⟨F, hfin, hle⟩ := (krullTopology_mem_nhds_one_iff k Ω V).1 hV
  exact ⟨F, hfin, fun x hx => hVH (hle (Subgroup.mem_comap.1 hx))⟩

variable [IsGalois k Ω] in
/-- The trace on a subgroup of an open subgroup of a Galois group contains an open normal
subgroup, namely the trace of the subgroup fixing a finite Galois subextension. -/
theorem exists_isOpenNormal_comap_subtype_le (A : Subgroup Gal(Ω/k))
    {N : Subgroup Gal(Ω/k)} (hN : IsOpen (N : Set Gal(Ω/k))) :
    ∃ M : Subgroup ↥A, IsOpenNormal M ∧ M ≤ N.comap A.subtype := by
  have hmem : (N : Set Gal(Ω/k)) ∈ nhds (1 : Gal(Ω/k)) := hN.mem_nhds N.one_mem
  obtain ⟨E, hfin, hnorm, hle⟩ := (krullTopology_mem_nhds_one_iff_of_normal k Ω _).1 hmem
  haveI := hfin
  haveI := hnorm
  exact ⟨E.fixingSubgroup.comap A.subtype,
    isOpenNormal_comap_subtype A (isOpenNormal_fixingSubgroup E), fun _ hx => hle hx⟩

end Open

/-! ### Surjectivity relative to a finite subextension -/

section Residue

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  (P : Ideal (𝓞 Ω)) [P.IsPrime]

/-- **An automorphism of the residue field which is trivial on the residue field of a finite
subextension `E` comes from an element of the stabilizer which is trivial on `E`.**  This is the
surjectivity of the stabilizer of `P` in `Gal(Ω/E)` onto the automorphisms of the residue field
over the residue field of `E`, read in `Gal(Ω/k)`. -/
theorem exists_mem_fixingSubgroup_stabilizerHom_eq (E : IntermediateField k Ω)
    (α : (𝓞 Ω ⧸ P) ≃ₐ[𝓞 k ⧸ P.under (𝓞 k)] (𝓞 Ω ⧸ P))
    (hα : ∀ b : 𝓞 ↥E, α (Ideal.Quotient.mk P (algebraMap (𝓞 ↥E) (𝓞 Ω) b))
        = Ideal.Quotient.mk P (algebraMap (𝓞 ↥E) (𝓞 Ω) b)) :
    ∃ z : Gal(Ω/k), ∃ hz : z ∈ stabilizer Gal(Ω/k) P, z ∈ E.fixingSubgroup ∧
      Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k) ⟨z, hz⟩ = α := by
  haveI : IsGalois ↥E Ω := inferInstance
  haveI : P.LiesOver (P.under (𝓞 ↥E)) := inferInstance
  haveI : Algebra.IsInvariant (𝓞 ↥E) (𝓞 Ω) Gal(Ω/↥E) :=
    isInvariant_ringOfIntegers_of_isGalois ↥E Ω
  haveI : SMulCommClass Gal(Ω/↥E) (𝓞 ↥E) (𝓞 Ω) := smulCommClass_ringOfIntegers ↥E Ω
  letI : TopologicalSpace (𝓞 Ω) := ⊥
  haveI : DiscreteTopology (𝓞 Ω) := ⟨rfl⟩
  haveI : ContinuousSMul Gal(Ω/↥E) (𝓞 Ω) := continuousSMul_ringOfIntegers ↥E Ω
  have hcomm : ∀ r : 𝓞 ↥E ⧸ P.under (𝓞 ↥E),
      α.toRingEquiv (algebraMap (𝓞 ↥E ⧸ P.under (𝓞 ↥E)) (𝓞 Ω ⧸ P) r)
        = algebraMap (𝓞 ↥E ⧸ P.under (𝓞 ↥E)) (𝓞 Ω ⧸ P) r := by
    rintro ⟨b⟩
    exact hα b
  obtain ⟨τ, hτ⟩ := Ideal.Quotient.stabilizerHom_surjective_of_profinite
    (G := Gal(Ω/↥E)) (P.under (𝓞 ↥E)) P (AlgEquiv.ofRingEquiv hcomm)
  refine ⟨(τ : Gal(Ω/↥E)).restrictScalars k, τ.2, fun x => (τ : Gal(Ω/↥E)).commutes x, ?_⟩
  refine AlgEquiv.ext ?_
  rintro ⟨b⟩
  exact congrArg (fun (e : (𝓞 Ω ⧸ P) ≃ₐ[𝓞 ↥E ⧸ P.under (𝓞 ↥E)] (𝓞 Ω ⧸ P)) => e b) hτ

end Residue

/-! ### An arithmetic Frobenius -/

section Frobenius

variable {k Ω : Type*} [Field k] [NumberField k] [Field Ω] [Algebra k Ω] [IsGalois k Ω]
  [IsAlgClosed Ω] (P : Ideal (𝓞 Ω)) [P.IsPrime] (hP : P ≠ ⊥)

include hP in
/-- **An arithmetic Frobenius at a nonzero prime of the ring of integers of an algebraic closure
generates the stabilizer of the prime modulo inertia, and can be sent to any prescribed element of
any finite group by a smooth homomorphism killing inertia.**

Generation is stated in the form which is used: an open subgroup of the stabilizer containing the
inertia subgroup and the Frobenius is everything.  Given such a subgroup one produces a finite
subextension `E` whose fixator meets the stabilizer inside it; a power of the Frobenius matches
the given element on the finite image of the ring of integers of `E` in the residue field, and the
difference is corrected by an element trivial on `E`, up to inertia. -/
theorem exists_arithFrobenius :
    ∃ σ : ↥(stabilizer Gal(Ω/k) P),
      (∀ H : Subgroup ↥(stabilizer Gal(Ω/k) P), IsOpen (H : Set ↥(stabilizer Gal(Ω/k) P)) →
          (P.inertia Gal(Ω/k)).subgroupOf (stabilizer Gal(Ω/k) P) ≤ H → σ ∈ H →
          ∀ x, x ∈ H) ∧
      ∀ (C : Type*) [Group C] [Finite C] (c : C),
        ∃ ρ : ↥(stabilizer Gal(Ω/k) P) →* C,
          IsSmooth₁ (ρ : ↥(stabilizer Gal(Ω/k) P) → C) ∧
          (P.inertia Gal(Ω/k)).subgroupOf (stabilizer Gal(Ω/k) P) ≤ ρ.ker ∧ ρ σ = c := by
  haveI := isMaximal_prime_ringOfIntegers P hP
  haveI := isMaximal_under_ringOfIntegers k P hP
  haveI : Finite (𝓞 k ⧸ P.under (𝓞 k)) := finite_quotient_under_ringOfIntegers k P hP
  letI : Fintype (𝓞 k ⧸ P.under (𝓞 k)) := Fintype.ofFinite _
  haveI := isAlgClosed_quotient_ringOfIntegers P
  haveI : Algebra.IsAlgebraic (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 Ω ⧸ P) := inferInstance
  letI : TopologicalSpace (𝓞 Ω) := ⊥
  haveI : DiscreteTopology (𝓞 Ω) := ⟨rfl⟩
  haveI : ContinuousSMul Gal(Ω/k) (𝓞 Ω) := continuousSMul_ringOfIntegers k Ω
  obtain ⟨σ, hσ⟩ := Ideal.Quotient.stabilizerHom_surjective_of_profinite
    (G := Gal(Ω/k)) (P.under (𝓞 k)) P
    (FiniteField.frobeniusAlgEquivOfAlgebraic (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 Ω ⧸ P))
  refine ⟨σ, ?_, ?_⟩
  · intro H hHopen hIH hσH x
    obtain ⟨E, hEfin, hEle⟩ := exists_fixingSubgroup_comap_le hHopen
    haveI := hEfin
    haveI : NumberField ↥E := NumberField.of_module_finite k ↥E
    haveI : Finite (𝓞 ↥E ⧸ P.under (𝓞 ↥E)) := finite_quotient_under_ringOfIntegers ↥E P hP
    have hT : (Set.range (algebraMap (𝓞 ↥E ⧸ P.under (𝓞 ↥E)) (𝓞 Ω ⧸ P))).Finite :=
      Set.finite_range _
    obtain ⟨n, hn⟩ := exists_symm_pow_frobenius_apply (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 Ω ⧸ P)
      (Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k) x) hT
    have hα : ∀ b : 𝓞 ↥E,
        (Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k) ((σ ^ n)⁻¹ * x))
            (Ideal.Quotient.mk P (algebraMap (𝓞 ↥E) (𝓞 Ω) b))
          = Ideal.Quotient.mk P (algebraMap (𝓞 ↥E) (𝓞 Ω) b) := by
      intro b
      have hy : Ideal.Quotient.mk P (algebraMap (𝓞 ↥E) (𝓞 Ω) b)
          ∈ Set.range (algebraMap (𝓞 ↥E ⧸ P.under (𝓞 ↥E)) (𝓞 Ω ⧸ P)) :=
        ⟨Ideal.Quotient.mk _ b, rfl⟩
      rw [_root_.map_mul, _root_.map_inv, _root_.map_pow, hσ]
      exact hn _ hy
    obtain ⟨z, hz, hzE, hzα⟩ := exists_mem_fixingSubgroup_stabilizerHom_eq P E _ hα
    have hzH : (⟨z, hz⟩ : ↥(stabilizer Gal(Ω/k) P)) ∈ H := hEle hzE
    have hker : ((σ ^ n)⁻¹ * x) * (⟨z, hz⟩ : ↥(stabilizer Gal(Ω/k) P))⁻¹ ∈ H := by
      refine hIH ?_
      rw [← Ideal.Quotient.ker_stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k), MonoidHom.mem_ker,
        _root_.map_mul, _root_.map_inv, hzα, mul_inv_cancel]
    have hx : x = σ ^ n * ((((σ ^ n)⁻¹ * x) * (⟨z, hz⟩ : ↥(stabilizer Gal(Ω/k) P))⁻¹)
        * (⟨z, hz⟩ : ↥(stabilizer Gal(Ω/k) P))) := by group
    rw [hx]
    exact H.mul_mem (H.pow_mem hσH n) (H.mul_mem hker hzH)
  · intro C _ _ c
    obtain ⟨θ, ρ₀, hρc, hρfix⟩ := exists_monoidHom_aut_apply_frobenius
      (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 Ω ⧸ P) C c
    refine ⟨ρ₀.comp (Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k)), ?_, ?_, ?_⟩
    · obtain ⟨b, hb⟩ := Ideal.Quotient.mk_surjective (I := P) θ
      haveI : FiniteDimensional k ↥(IntermediateField.adjoin k {(b : Ω)}) :=
        IntermediateField.adjoin.finiteDimensional
          (Algebra.IsIntegral.isIntegral (R := k) (b : Ω))
      obtain ⟨M, hM, hMle⟩ := exists_isOpenNormal_comap_subtype_le (stabilizer Gal(Ω/k) P)
        (N := (IntermediateField.adjoin k {(b : Ω)}).fixingSubgroup)
        (IntermediateField.fixingSubgroup_isOpen _)
      refine ⟨M, hM, fun y m hm => ?_⟩
      have hmb : (m : Gal(Ω/k)) • b = b := by
        apply Subtype.ext
        exact (hMle hm) ⟨(b : Ω), IntermediateField.mem_adjoin_simple_self k (b : Ω)⟩
      have hfix : Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k) m θ = θ := by
        rw [← hb]
        show Ideal.Quotient.mk P ((m : Gal(Ω/k)) • b) = Ideal.Quotient.mk P b
        rw [hmb]
      simp only [MonoidHom.coe_comp, Function.comp_apply, _root_.map_mul]
      rw [hρfix _ hfix, mul_one]
    · intro y hy
      rw [← Ideal.Quotient.ker_stabilizerHom P (P.under (𝓞 k)) Gal(Ω/k)] at hy
      rw [MonoidHom.mem_ker, MonoidHom.comp_apply, MonoidHom.mem_ker.1 hy, _root_.map_one]
    · rw [MonoidHom.comp_apply, hσ, hρc]

include hP in
/-- **An unramified smooth homomorphism from a decomposition group to a finite group lifts through
any surjection of finite groups**, again smoothly.

Send an arithmetic Frobenius to a preimage of its value, which prescribes a smooth lift killing
inertia.  The lift and the given homomorphism then agree on inertia and at the Frobenius, and the
subgroup on which they agree is open because both have open kernels, so it is everything. -/
theorem exists_smoothHom_lift_of_inertia_le_ker {C C' : Type*} [Group C]
    [Group C'] [Finite C'] (q : C' →* C) (hq : Function.Surjective q)
    (ρ : ↥(stabilizer Gal(Ω/k) P) →* C) (hρ : IsSmooth₁ (ρ : ↥(stabilizer Gal(Ω/k) P) → C))
    (hI : (P.inertia Gal(Ω/k)).subgroupOf (stabilizer Gal(Ω/k) P) ≤ ρ.ker) :
    ∃ g : ↥(stabilizer Gal(Ω/k) P) →* C',
      IsSmooth₁ (g : ↥(stabilizer Gal(Ω/k) P) → C') ∧ ∀ x, q (g x) = ρ x := by
  obtain ⟨σ, hβ, hγ⟩ := exists_arithFrobenius (k := k) P hP
  obtain ⟨c', hc'⟩ := hq (ρ σ)
  obtain ⟨g, hgsm, hgI, hgσ⟩ := hγ C' c'
  refine ⟨g, hgsm, fun x => ?_⟩
  have hle : ρ.ker ⊓ g.ker ≤ (q.comp g).eqLocus ρ := by
    intro y hy
    have h1 : g y = 1 := hy.2
    have h2 : ρ y = 1 := hy.1
    show q (g y) = ρ y
    rw [h1, h2, _root_.map_one]
  have hopen : IsOpen (((q.comp g).eqLocus ρ : Subgroup ↥(stabilizer Gal(Ω/k) P)) :
      Set ↥(stabilizer Gal(Ω/k) P)) := by
    refine Subgroup.isOpen_mono hle ?_
    exact (isOpenNormal_ker_of_isSmooth₁ hρ).isOpen.inter
      (isOpenNormal_ker_of_isSmooth₁ hgsm).isOpen
  refine hβ ((q.comp g).eqLocus ρ) hopen (fun y hy => ?_) ?_ x
  · show q (g y) = ρ y
    rw [MonoidHom.mem_ker.1 (hgI hy), MonoidHom.mem_ker.1 (hI hy), _root_.map_one]
  · show q (g σ) = ρ σ
    rw [hgσ, hc']

end Frobenius

end InverseGalois.CFT
