/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Scholz.CentralCyclicLift

/-!
# The automorphisms of an algebraic closure of a finite field

Let `κ₀` be a finite field with `q` elements and let `κ` be an algebraic closure of it.  The
automorphism group of `κ` over `κ₀` is topologically generated by the Frobenius `x ↦ x ^ q`: every
automorphism agrees with a power of Frobenius on any prescribed finite set, and every element of
every finite group is the value at Frobenius of a homomorphism which is trivial on the
automorphisms fixing a suitable element.  These two statements are what turns the decomposition
group of a prime of an algebraic closure of a number field, modulo its inertia, into a free
procyclic group.

The subfield of degree `N + 1` is produced here as the equalizer of the `N + 1`-st power of
Frobenius with the identity, which is a subalgebra closed under inversion, hence an intermediate
field.  It is finite because its elements are roots of `X ^ (q ^ (N + 1)) - X`, and it has exactly
`q ^ (N + 1)` elements because that polynomial is separable and splits.  Indexing by `N + 1` rather
than by `N` keeps finiteness unconditional and makes the rank a hypothesis-free equation.

The last result packages the surjection onto the finite Galois group `Gal(κ_{q ^ (N + 1)} / κ₀)`:
choose `N` so that `N + 1` is the order of the prescribed element, send Frobenius to it using the
fact that a finite cyclic group is generated by Frobenius, and record a primitive element of the
subfield as the single element whose stabilizer is killed.

## Main results

* `InverseGalois.CFT.frobeniusSubfield` — the subfield of `κ` fixed by the `N + 1`-st power of
  Frobenius, with `mem_frobeniusSubfield`, `card_frobeniusSubfield` and
  `finrank_frobeniusSubfield`.
* `InverseGalois.CFT.exists_pow_of_algEquiv_of_finite` — **an automorphism of `κ` over `κ₀` agrees
  with a power of Frobenius on any finite set**, and `exists_symm_pow_frobenius_apply` for the
  form in which that is used.
* `InverseGalois.CFT.exists_monoidHom_aut_apply_frobenius` — **every element of every finite group
  is the value at Frobenius of a homomorphism out of `Aut_{κ₀}(κ)` which is trivial on the
  automorphisms fixing a single element.**

## Tags

finite field, algebraic closure, Frobenius, procyclic, decomposition group
-/

namespace InverseGalois.CFT

open Polynomial

section Frobenius

variable (κ₀ : Type*) [Field κ₀] [Fintype κ₀] (κ : Type*) [Field κ] [Algebra κ₀ κ]

/-- The degree of `X ^ m - X` is `m`, for `m` at least two. -/
theorem natDegree_X_pow_sub_X {m : ℕ} (hm : 2 ≤ m) : (X ^ m - X : κ[X]).natDegree = m := by
  have h : (X : κ[X]).natDegree < (X ^ m : κ[X]).natDegree := by
    rw [natDegree_X, natDegree_X_pow]; omega
  rw [natDegree_sub_eq_left_of_natDegree_lt h, natDegree_X_pow]

/-- The polynomial `X ^ m - X` is nonzero, for `m` at least two. -/
theorem X_pow_sub_X_ne_zero {m : ℕ} (hm : 2 ≤ m) : (X ^ m - X : κ[X]) ≠ 0 := fun h => by
  have := natDegree_X_pow_sub_X κ hm
  rw [h, natDegree_zero] at this
  omega

/-- A positive power of the cardinality of a finite field is at least two. -/
theorem two_le_card_pow (N : ℕ) : 2 ≤ Fintype.card κ₀ ^ (N + 1) := by
  calc (2 : ℕ) ≤ Fintype.card κ₀ := Fintype.one_lt_card
  _ = Fintype.card κ₀ ^ 1 := (pow_one _).symm
  _ ≤ Fintype.card κ₀ ^ (N + 1) := Nat.pow_le_pow_right Fintype.card_pos (by omega)

/-- The subfield of `κ` fixed by the `N + 1`-st power of the Frobenius of `κ₀`. -/
def frobeniusSubfield (N : ℕ) : IntermediateField κ₀ κ :=
  Subalgebra.toIntermediateField
    (AlgHom.equalizer (FiniteField.frobeniusAlgHom κ₀ κ ^ (N + 1)) (AlgHom.id κ₀ κ))
    fun x hx => by
      rw [AlgHom.mem_equalizer] at hx ⊢
      rw [map_inv₀, hx]
      simp

/-- Membership in `frobeniusSubfield` is the equation `x ^ (q ^ (N + 1)) = x`. -/
theorem mem_frobeniusSubfield {N : ℕ} {x : κ} :
    x ∈ frobeniusSubfield κ₀ κ N ↔ x ^ (Fintype.card κ₀ ^ (N + 1)) = x := by
  have h : x ∈ frobeniusSubfield κ₀ κ N ↔
      x ∈ AlgHom.equalizer (FiniteField.frobeniusAlgHom κ₀ κ ^ (N + 1)) (AlgHom.id κ₀ κ) := Iff.rfl
  rw [h, AlgHom.mem_equalizer]
  simp only [AlgHom.coe_pow, FiniteField.coe_frobeniusAlgHom, pow_iterate, AlgHom.coe_id, id_eq]

instance (N : ℕ) : Finite ↥(frobeniusSubfield κ₀ κ N) := by
  have hfin : {x : κ | x ^ (Fintype.card κ₀ ^ (N + 1)) = x}.Finite := by
    refine Set.Finite.subset (Polynomial.finite_setOf_isRoot
      (X_pow_sub_X_ne_zero κ (two_le_card_pow κ₀ N))) fun x hx => ?_
    simp only [Set.mem_setOf_eq, IsRoot.def, eval_sub, eval_pow, eval_X, sub_eq_zero]
    exact hx
  haveI := hfin.to_subtype
  exact Finite.of_equiv ↥{x : κ | x ^ (Fintype.card κ₀ ^ (N + 1)) = x}
    (Equiv.subtypeEquivRight fun x => (mem_frobeniusSubfield κ₀ κ (N := N) (x := x)).symm)

/-- **An automorphism of `κ` over `κ₀` acts on a finite intermediate field as a power of the
Frobenius**, because the automorphism group of a finite field is generated by its Frobenius and
restriction is compatible with it. -/
theorem exists_pow_of_algEquiv (α : κ ≃ₐ[κ₀] κ) (L : IntermediateField κ₀ κ) [Finite ↥L] :
    ∃ n : ℕ, ∀ y ∈ L, α y = y ^ (Fintype.card κ₀ ^ n) := by
  obtain ⟨n, hn⟩ := (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow κ₀ ↥L).2
    (α.restrictNormal ↥L)
  refine ⟨(n : ℕ), fun y hy => ?_⟩
  have h := congrArg (fun (e : ↥L ≃ₐ[κ₀] ↥L) => (algebraMap ↥L κ) (e ⟨y, hy⟩)) hn
  simp only at h
  rw [AlgEquiv.restrictNormal_commutes] at h
  have hpow : ((FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ ↥L ^ (n : ℕ)) ⟨y, hy⟩ : ↥L)
      = ⟨y, hy⟩ ^ (Fintype.card κ₀ ^ (n : ℕ)) := by
    rw [AlgEquiv.coe_pow, FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate]
  rw [show α y = α ((algebraMap ↥L κ) ⟨y, hy⟩) from rfl, ← h, hpow, _root_.map_pow]
  rfl

variable [IsAlgClosed κ]

/-- The subfield fixed by the `N + 1`-st power of Frobenius has `q ^ (N + 1)` elements: its
elements are exactly the roots of the separable polynomial `X ^ (q ^ (N + 1)) - X`, which splits. -/
theorem card_frobeniusSubfield (N : ℕ) :
    Nat.card ↥(frobeniusSubfield κ₀ κ N) = Fintype.card κ₀ ^ (N + 1) := by
  classical
  have h2 : 2 ≤ Fintype.card κ₀ ^ (N + 1) := two_le_card_pow κ₀ N
  have hne : (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]) ≠ 0 := X_pow_sub_X_ne_zero κ h2
  have hdeg : (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]).natDegree
      = Fintype.card κ₀ ^ (N + 1) := natDegree_X_pow_sub_X κ h2
  haveI hc0 : CharP κ₀ (ringChar κ₀) := ringChar.charP κ₀
  haveI : CharP κ (ringChar κ₀) :=
    charP_of_injective_algebraMap (R := κ₀) (A := κ) (algebraMap κ₀ κ).injective (ringChar κ₀)
  have hdvd : ringChar κ₀ ∣ Fintype.card κ₀ ^ (N + 1) := by
    obtain ⟨n, _, hcard⟩ := FiniteField.card κ₀ (ringChar κ₀)
    refine dvd_pow ?_ (Nat.succ_ne_zero N)
    rw [hcard]
    exact dvd_pow_self _ n.ne_zero
  have hsep : (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]).Separable :=
    galois_poly_separable (ringChar κ₀) _ hdvd
  have hroots : Multiset.card (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]).roots
      = Fintype.card κ₀ ^ (N + 1) := by
    have hs := splits_iff_card_roots.1
      (IsAlgClosed.splits (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]))
    rw [hdeg] at hs
    exact hs
  have hfc : (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]).roots.toFinset.card
      = Fintype.card κ₀ ^ (N + 1) := by
    rw [Multiset.toFinset_card_eq_card_iff_nodup.2 (nodup_roots hsep), hroots]
  have e : ↥(frobeniusSubfield κ₀ κ N) ≃
      {x : κ // x ∈ (X ^ (Fintype.card κ₀ ^ (N + 1)) - X : κ[X]).roots.toFinset} :=
    Equiv.subtypeEquivRight fun x => by
      rw [mem_frobeniusSubfield, Multiset.mem_toFinset, mem_roots hne]
      simp only [IsRoot.def, eval_sub, eval_pow, eval_X, sub_eq_zero]
  rw [Nat.card_congr e, Nat.card_eq_finsetCard, hfc]

/-- The subfield fixed by the `N + 1`-st power of Frobenius has degree `N + 1` over `κ₀`. -/
theorem finrank_frobeniusSubfield (N : ℕ) :
    Module.finrank κ₀ ↥(frobeniusSubfield κ₀ κ N) = N + 1 := by
  haveI : Fintype ↥(frobeniusSubfield κ₀ κ N) := Fintype.ofFinite _
  have h := Module.card_eq_pow_finrank (K := κ₀) (V := ↥(frobeniusSubfield κ₀ κ N))
  rw [← Nat.card_eq_fintype_card, card_frobeniusSubfield κ₀ κ N] at h
  exact (Nat.pow_right_injective Fintype.one_lt_card h).symm

variable [Algebra.IsAlgebraic κ₀ κ]

omit [IsAlgClosed κ] in
/-- **An automorphism of `κ` over `κ₀` agrees with a power of Frobenius on any finite set**, that
set being contained in a finite intermediate field. -/
theorem exists_pow_of_algEquiv_of_finite (α : κ ≃ₐ[κ₀] κ) {T : Set κ} (hT : T.Finite) :
    ∃ n : ℕ, ∀ y ∈ T, α y = y ^ (Fintype.card κ₀ ^ n) := by
  haveI := hT.to_subtype
  haveI : FiniteDimensional κ₀ ↥(IntermediateField.adjoin κ₀ T) :=
    IntermediateField.finiteDimensional_adjoin fun x _ =>
      (Algebra.IsAlgebraic.isAlgebraic x).isIntegral
  haveI : Finite ↥(IntermediateField.adjoin κ₀ T) := Module.finite_of_finite κ₀
  obtain ⟨n, hn⟩ := exists_pow_of_algEquiv κ₀ κ α (IntermediateField.adjoin κ₀ T)
  exact ⟨n, fun y hy => hn y (IntermediateField.subset_adjoin κ₀ T hy)⟩

omit [IsAlgClosed κ] in
/-- **Every automorphism agrees with a power of Frobenius on a finite set.**  Composing with the
inverse of that power therefore fixes the set pointwise. -/
theorem exists_symm_pow_frobenius_apply (α : κ ≃ₐ[κ₀] κ) {T : Set κ} (hT : T.Finite) :
    ∃ n : ℕ, ∀ y ∈ T, ((FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ) ^ n).symm (α y) = y := by
  obtain ⟨n, hn⟩ := exists_pow_of_algEquiv_of_finite κ₀ κ α hT
  refine ⟨n, fun y hy => ?_⟩
  have hφ : (FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ ^ n) y
      = y ^ (Fintype.card κ₀ ^ n) := by
    rw [AlgEquiv.coe_pow, FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate]
  rw [hn y hy, ← hφ, AlgEquiv.symm_apply_apply]

omit [IsAlgClosed κ] in
/-- Restriction carries the Frobenius of `κ` to the Frobenius of a subfield fixed by a power of
it. -/
theorem restrictNormalHom_frobeniusAlgEquiv (N : ℕ) :
    AlgEquiv.restrictNormalHom (F := κ₀) (K₁ := κ) ↥(frobeniusSubfield κ₀ κ N)
        (FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ)
      = FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ ↥(frobeniusSubfield κ₀ κ N) := by
  refine AlgEquiv.ext fun y => ?_
  apply (algebraMap ↥(frobeniusSubfield κ₀ κ N) κ).injective
  have h1 : (algebraMap ↥(frobeniusSubfield κ₀ κ N) κ)
      ((AlgEquiv.restrictNormalHom (F := κ₀) (K₁ := κ) ↥(frobeniusSubfield κ₀ κ N)
        (FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ)) y)
      = FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ
        ((algebraMap ↥(frobeniusSubfield κ₀ κ N) κ) y) :=
    AlgEquiv.restrictNormal_commutes _ _ y
  rw [h1]
  simp only [FiniteField.coe_frobeniusAlgEquivOfAlgebraic, _root_.map_pow]

/-- **A homomorphism from the automorphism group of an algebraic closure of a finite field takes a
prescribed value at Frobenius**, and can be taken to be trivial on the automorphisms fixing a
single element. -/
theorem exists_monoidHom_aut_apply_frobenius (C : Type*) [Group C] [Finite C] (c : C) :
    ∃ (θ : κ) (ρ : (κ ≃ₐ[κ₀] κ) →* C),
      ρ (FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ κ) = c ∧
        ∀ α : κ ≃ₐ[κ₀] κ, α θ = θ → ρ α = 1 := by
  obtain ⟨N, hN⟩ : ∃ N, orderOf c = N + 1 := ⟨orderOf c - 1, by have := orderOf_pos c; omega⟩
  have hgen : ∀ y : (↥(frobeniusSubfield κ₀ κ N) ≃ₐ[κ₀] ↥(frobeniusSubfield κ₀ κ N)),
      y ∈ Subgroup.zpowers
        (FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ ↥(frobeniusSubfield κ₀ κ N)) := by
    intro y
    obtain ⟨n, hn⟩ := (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow κ₀
      ↥(frobeniusSubfield κ₀ κ N)).2 y
    refine ⟨(n : ℕ), ?_⟩
    show FiniteField.frobeniusAlgEquivOfAlgebraic κ₀ ↥(frobeniusSubfield κ₀ κ N)
      ^ ((n : ℕ) : ℤ) = y
    rw [zpow_natCast]
    exact hn
  have hcardaut : Nat.card (↥(frobeniusSubfield κ₀ κ N) ≃ₐ[κ₀] ↥(frobeniusSubfield κ₀ κ N))
      = N + 1 := by
    rw [IsGalois.card_aut_eq_finrank, finrank_frobeniusSubfield]
  have hcpow : c ^ Nat.card (↥(frobeniusSubfield κ₀ κ N) ≃ₐ[κ₀]
      ↥(frobeniusSubfield κ₀ κ N)) = 1 := by
    rw [hcardaut, ← hN]
    exact pow_orderOf_eq_one c
  obtain ⟨h, hh⟩ := exists_monoidHom_apply_eq_of_forall_mem_zpowers hgen hcpow
  obtain ⟨a, ha⟩ := Field.exists_primitive_element κ₀ ↥(frobeniusSubfield κ₀ κ N)
  refine ⟨(a : κ), h.comp (AlgEquiv.restrictNormalHom ↥(frobeniusSubfield κ₀ κ N)), ?_, ?_⟩
  · rw [MonoidHom.comp_apply, restrictNormalHom_frobeniusAlgEquiv, hh]
  · intro α hα
    have hadj : Algebra.adjoin κ₀ ({a} : Set ↥(frobeniusSubfield κ₀ κ N)) = ⊤ := by
      rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
        (Algebra.IsAlgebraic.isAlgebraic a), ha, IntermediateField.top_toSubalgebra]
    have hres : AlgEquiv.restrictNormalHom (F := κ₀) (K₁ := κ)
        ↥(frobeniusSubfield κ₀ κ N) α = 1 := by
      have hfix : (α.restrictNormal ↥(frobeniusSubfield κ₀ κ N)) a = a := by
        apply (algebraMap ↥(frobeniusSubfield κ₀ κ N) κ).injective
        rw [AlgEquiv.restrictNormal_commutes]
        exact hα
      have heq : (α.restrictNormal ↥(frobeniusSubfield κ₀ κ N)).toAlgHom
          = AlgHom.id κ₀ ↥(frobeniusSubfield κ₀ κ N) := by
        refine AlgHom.ext_of_adjoin_eq_top hadj ?_
        intro x hx
        rw [Set.mem_singleton_iff] at hx
        subst hx
        exact hfix
      refine AlgEquiv.ext fun y => ?_
      simpa using DFunLike.congr_fun heq y
    rw [MonoidHom.comp_apply, hres, _root_.map_one]

end Frobenius

end InverseGalois.CFT
