/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Disjoint

/-!
# The compositum of a number field with a Galois extension of the rationals

Fix a number field `k` and a number field `F₀` that is Galois over the rationals.  Inside an
algebraic closure of `k` the image of a chosen embedding of `F₀` generates, together with `k`, a
field `baseCompositum ι` which is Galois over `k`, and restriction to the image of `F₀` compares
its Galois group with that of `F₀` over the rationals.

Restriction is injective as soon as the image of `F₀` generates the compositum over `k`, because an
automorphism fixing a generating set is the identity.  It is surjective as soon as no rational
prime ramifies in both `F₀` and `k`: the fixed field of the image of restriction is a subfield of
`F₀` whose image in the compositum is fixed by the whole Galois group over `k`, hence lands in `k`,
so no rational prime ramifies in it and Minkowski's bound forces it to be the rationals.  Both
hypotheses are available in the situation of interest, where `F₀` is a subfield of a cyclotomic
field of prime conductor unramified in `k`.

The compositum is built as the subfield generated over `k` by the image of a fixed embedding of
`F₀` into an algebraic closure of `k`.  A primitive element of `F₀` over the rationals identifies
that subfield with the splitting field over `k` of the minimal polynomial of the primitive element,
because normality of `F₀` over the rationals puts every root of the minimal polynomial in the image
of the embedding.  This yields at one stroke that the compositum is a finite Galois extension of
`k` and that the image of `F₀` generates it.

## Main definitions

* `InverseGalois.CFT.galRestrictSub`: restriction of the Galois group of an extension of `k` to a
  subfield coming from `F₀`.
* `InverseGalois.CFT.galEquivSub`: the resulting isomorphism of Galois groups.
* `InverseGalois.CFT.baseCompositum`: the subfield of an algebraic closure of `k` generated by `k`
  and the image of an embedding of `F₀`.

## Main results

* `InverseGalois.CFT.galRestrictSub_injective`: **restriction is injective when the subfield
  generates.**
* `InverseGalois.CFT.galRestrictSub_surjective`: **restriction is surjective when no rational prime
  ramifies in both fields.**
* `InverseGalois.CFT.finrank_eq_of_adjoin_eq_top`, `InverseGalois.CFT.isCyclic_of_adjoin_eq_top`:
  the degree and the cyclicity of the compositum over `k` are those of `F₀` over the rationals.
* `InverseGalois.CFT.adjoin_range_algebraMap_eq_top`: **the image of `F₀` generates the compositum
  over `k`.**

## Tags

number field, compositum, Galois group, restriction, ramification, splitting field, algebraic
closure
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

namespace InverseGalois.CFT

open Module NumberField Polynomial InverseGalois.NumberTheory

/-! ### Restriction to a subfield coming from the rationals -/

section Abstract

variable {k F₀ E : Type} [Field k] [NumberField k] [Field F₀] [NumberField F₀] [IsGalois ℚ F₀]
  [Field E] [NumberField E] [Algebra k E] [Algebra F₀ E] [IsScalarTower ℚ k E]
  [IsScalarTower ℚ F₀ E] [IsGalois k E]

variable (k F₀ E) in
/-- Restriction of an automorphism of `E` over `k` to the subfield of `E` coming from `F₀`. -/
noncomputable def galRestrictSub : Gal(E/k) →* Gal(F₀/ℚ) where
  toFun σ := AlgEquiv.restrictNormalHom F₀ (σ.restrictScalars ℚ)
  map_one' := by
    rw [show AlgEquiv.restrictScalars ℚ (1 : Gal(E/k)) = 1 from rfl, map_one]
  map_mul' σ τ := by
    show AlgEquiv.restrictNormalHom F₀ ((σ * τ).restrictScalars ℚ) = _
    have h : (σ * τ).restrictScalars ℚ = σ.restrictScalars ℚ * τ.restrictScalars ℚ := rfl
    rw [h, map_mul]

omit [IsGalois k E] in
/-- Restriction is compatible with the embedding of `F₀` into `E`. -/
theorem galRestrictSub_algebraMap (σ : Gal(E/k)) (y : F₀) :
    algebraMap F₀ E (galRestrictSub k F₀ E σ y) = σ (algebraMap F₀ E y) :=
  AlgEquiv.restrictNormal_commutes (σ.restrictScalars ℚ) F₀ y

omit [IsGalois k E] in
/-- **Restriction is injective when the subfield generates.**  An automorphism restricting to the
identity fixes a generating set, hence is the identity. -/
theorem galRestrictSub_injective
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ E)) = ⊤) :
    Function.Injective (galRestrictSub k F₀ E) := by
  rw [injective_iff_map_eq_one]
  intro σ hσ
  have h : σ.toAlgHom = AlgHom.id k E := by
    refine AlgHom.ext_of_adjoin_eq_top (s := Set.range (algebraMap F₀ E)) hgen ?_
    rintro _ ⟨y, rfl⟩
    show σ (algebraMap F₀ E y) = algebraMap F₀ E y
    rw [← galRestrictSub_algebraMap σ y, hσ]
    rfl
  refine AlgEquiv.ext fun x => ?_
  simpa using AlgHom.congr_fun h x

/-- **Restriction is surjective when no rational prime ramifies in both fields.**  The fixed field
of the image has image in `E` fixed by the whole Galois group over `k`, hence contained in `k`; no
rational prime then ramifies in it, so it is the rationals and the image is everything. -/
theorem galRestrictSub_surjective
    (hdisj : Disjoint (ramifiedSet F₀) (ramifiedSet k)) :
    Function.Surjective (galRestrictSub k F₀ E) := by
  set H := (galRestrictSub k F₀ E).range with hH
  set C := IntermediateField.fixedField H with hC
  haveI : FiniteDimensional ℚ ↥C := IntermediateField.finiteDimensional_left C
  haveI : NumberField ↥C := ⟨⟩
  have hmem : ∀ c : ↥C, algebraMap F₀ E (c : F₀) ∈ (⊥ : IntermediateField k E) := by
    intro c
    refine (IsGalois.mem_bot_iff_fixed _).mpr fun σ => ?_
    rw [← galRestrictSub_algebraMap σ (c : F₀)]
    congr 1
    exact (IntermediateField.mem_fixedField_iff H _).mp c.2 _ ⟨σ, rfl⟩
  letI : Algebra ↥C k :=
    ((IntermediateField.botEquiv k E).toRingHom.comp
      (RingHom.codRestrict ((algebraMap F₀ E).comp (algebraMap ↥C F₀))
        (⊥ : IntermediateField k E) hmem)).toAlgebra
  have hrank : Module.finrank ℚ ↥C = 1 :=
    finrank_eq_one_of_ramifiedSet_eq_empty ↥C
      (Set.eq_empty_iff_forall_notMem.mpr fun p hp =>
        Set.disjoint_left.mp hdisj (ramifiedSet_subset ↥C F₀ hp) (ramifiedSet_subset ↥C k hp))
  have hbot : C = ⊥ := IntermediateField.finrank_eq_one_iff.mp hrank
  have htop : H = ⊤ := by
    rw [← IntermediateField.fixingSubgroup_fixedField H, ← hC, hbot,
      IntermediateField.fixingSubgroup_bot]
  exact MonoidHom.range_eq_top.mp htop

variable (k F₀ E) in
/-- The isomorphism between the Galois group of `E` over `k` and that of `F₀` over the rationals,
under the two hypotheses making restriction bijective. -/
noncomputable def galEquivSub (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ E)) = ⊤)
    (hdisj : Disjoint (ramifiedSet F₀) (ramifiedSet k)) : Gal(E/k) ≃* Gal(F₀/ℚ) :=
  MulEquiv.ofBijective _ ⟨galRestrictSub_injective hgen, galRestrictSub_surjective hdisj⟩

/-- The degree of the compositum over `k` is the degree of `F₀` over the rationals. -/
theorem finrank_eq_of_adjoin_eq_top
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ E)) = ⊤)
    (hdisj : Disjoint (ramifiedSet F₀) (ramifiedSet k)) :
    Module.finrank k E = Module.finrank ℚ F₀ := by
  rw [← IsGalois.card_aut_eq_finrank k E, ← IsGalois.card_aut_eq_finrank ℚ F₀]
  exact Nat.card_congr (galEquivSub k F₀ E hgen hdisj).toEquiv

/-- The compositum is cyclic over `k` whenever `F₀` is cyclic over the rationals. -/
theorem isCyclic_of_adjoin_eq_top [IsCyclic Gal(F₀/ℚ)]
    (hgen : Algebra.adjoin k (Set.range (algebraMap F₀ E)) = ⊤)
    (hdisj : Disjoint (ramifiedSet F₀) (ramifiedSet k)) : IsCyclic Gal(E/k) :=
  isCyclic_of_surjective (galEquivSub k F₀ E hgen hdisj).symm
    (galEquivSub k F₀ E hgen hdisj).symm.surjective

end Abstract

/-! ### The compositum inside an algebraic closure -/

section Construction

variable {k : Type} [Field k] [NumberField k] {F₀ : Type} [Field F₀] [NumberField F₀]
  [IsGalois ℚ F₀]

variable (ι : F₀ →ₐ[ℚ] AlgebraicClosure k)

/-- The subfield of an algebraic closure of `k` generated by `k` and the image of `ι`. -/
noncomputable def baseCompositum : IntermediateField k (AlgebraicClosure k) :=
  IntermediateField.adjoin k (Set.range ι)

omit [IsGalois ℚ F₀] in
/-- The image of `ι` lies in the compositum. -/
theorem mem_baseCompositum (y : F₀) : ι y ∈ baseCompositum ι :=
  IntermediateField.subset_adjoin k _ ⟨y, rfl⟩

noncomputable instance algebraBaseCompositum : Algebra F₀ ↥(baseCompositum ι) :=
  (RingHom.codRestrict (ι : F₀ →+* AlgebraicClosure k) (baseCompositum ι)
    (mem_baseCompositum ι)).toAlgebra

omit [IsGalois ℚ F₀] in
/-- The structure map of `F₀` into the compositum is the chosen embedding. -/
theorem coe_algebraMap_baseCompositum (y : F₀) :
    ((algebraMap F₀ ↥(baseCompositum ι) y : ↥(baseCompositum ι)) : AlgebraicClosure k) = ι y :=
  rfl

/-- Every root of the minimal polynomial over the rationals of an element of `F₀` lies in the image
of `ι`, because `F₀` is normal over the rationals. -/
theorem rootSet_map_minpoly_subset_range (θ : F₀) :
    ((minpoly ℚ θ).map (algebraMap ℚ k)).rootSet (AlgebraicClosure k) ⊆ Set.range ι := by
  have hint : IsIntegral ℚ θ := Algebra.IsIntegral.isIntegral θ
  have hq0 : minpoly ℚ θ ≠ 0 := minpoly.ne_zero hint
  set q : ℚ[X] := minpoly ℚ θ with hqdef
  set p : k[X] := q.map (algebraMap ℚ k) with hpdef
  set P₀ : F₀[X] := q.map (algebraMap ℚ F₀) with hP₀def
  have hP₀0 : P₀ ≠ 0 := Polynomial.map_ne_zero hq0
  have hsplit : P₀.Splits := (IsGalois.to_normal (F := ℚ) (E := F₀)).splits θ
  have hmapι : P₀.map (ι : F₀ →+* AlgebraicClosure k)
      = q.map (algebraMap ℚ (AlgebraicClosure k)) := by
    rw [hP₀def, Polynomial.map_map, ι.comp_algebraMap]
  have hmapk : p.map (algebraMap k (AlgebraicClosure k))
      = q.map (algebraMap ℚ (AlgebraicClosure k)) := by
    rw [hpdef, Polynomial.map_map, ← IsScalarTower.algebraMap_eq]
  intro x hx
  have hroot : (P₀.map (ι : F₀ →+* AlgebraicClosure k)).IsRoot x := by
    rw [hmapι, ← hmapk, Polynomial.IsRoot, Polynomial.eval_map, ← Polynomial.aeval_def]
    exact (Polynomial.mem_rootSet.mp hx).2
  obtain ⟨y, hy⟩ := hsplit.mem_range_of_isRoot hP₀0 hroot
  exact ⟨y, hy⟩

/-- The compositum is generated over `k` by the roots of the minimal polynomial of a primitive
element of `F₀`. -/
theorem baseCompositum_eq_adjoin_rootSet {θ : F₀} (hθ : IntermediateField.adjoin ℚ {θ} = ⊤) :
    baseCompositum ι = IntermediateField.adjoin k
      (((minpoly ℚ θ).map (algebraMap ℚ k)).rootSet (AlgebraicClosure k)) := by
  have hint : IsIntegral ℚ θ := Algebra.IsIntegral.isIntegral θ
  have hq0 : minpoly ℚ θ ≠ 0 := minpoly.ne_zero hint
  set q : ℚ[X] := minpoly ℚ θ with hqdef
  set p : k[X] := q.map (algebraMap ℚ k) with hpdef
  have hp0 : p ≠ 0 := Polynomial.map_ne_zero hq0
  have hC : ι θ ∈ p.rootSet (AlgebraicClosure k) := by
    refine Polynomial.mem_rootSet.mpr ⟨hp0, ?_⟩
    rw [hpdef, Polynomial.aeval_map_algebraMap, Polynomial.aeval_algHom_apply, hqdef,
      minpoly.aeval, map_zero]
  have hA : p.rootSet (AlgebraicClosure k) ⊆ Set.range ι :=
    rootSet_map_minpoly_subset_range ι θ
  have hB : Set.range ι ⊆ (IntermediateField.adjoin k ({ι θ} : Set (AlgebraicClosure k)) :
      Set (AlgebraicClosure k)) := by
    rintro _ ⟨y, rfl⟩
    have hy : y ∈ Algebra.adjoin ℚ ({θ} : Set F₀) := by
      have hsub : (IntermediateField.adjoin ℚ ({θ} : Set F₀)).toSubalgebra
          = Algebra.adjoin ℚ ({θ} : Set F₀) :=
        IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic
      rw [← hsub, hθ]
      trivial
    rw [Algebra.adjoin_singleton_eq_range_aeval] at hy
    obtain ⟨f, rfl⟩ := hy
    have hrw : ι ((Polynomial.aeval θ).toRingHom f) = Polynomial.aeval (ι θ) f :=
      (Polynomial.aeval_algHom_apply ι θ f).symm
    rw [hrw]
    have hle : Algebra.adjoin ℚ ({ι θ} : Set (AlgebraicClosure k))
        ≤ Subalgebra.restrictScalars ℚ
          (IntermediateField.adjoin k ({ι θ} : Set (AlgebraicClosure k))).toSubalgebra :=
      Algebra.adjoin_le (by rintro _ rfl; exact IntermediateField.subset_adjoin k _ rfl)
    refine hle ?_
    rw [Algebra.adjoin_singleton_eq_range_aeval]
    exact ⟨f, rfl⟩
  refine le_antisymm ?_ ?_
  · refine le_trans (IntermediateField.adjoin_le_iff.mpr hB) ?_
    refine IntermediateField.adjoin_le_iff.mpr ?_
    rintro _ rfl
    exact IntermediateField.subset_adjoin k _ hC
  · exact IntermediateField.adjoin_le_iff.mpr fun x hx =>
      IntermediateField.subset_adjoin k _ (hA hx)

/-- The compositum is a splitting field over `k` of the minimal polynomial of a primitive element
of `F₀`. -/
theorem isSplittingField_baseCompositum {θ : F₀} (hθ : IntermediateField.adjoin ℚ {θ} = ⊤) :
    ((minpoly ℚ θ).map (algebraMap ℚ k)).IsSplittingField k ↥(baseCompositum ι) := by
  rw [baseCompositum_eq_adjoin_rootSet ι hθ]
  exact IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)

instance normalBaseCompositum : Normal k ↥(baseCompositum ι) := by
  obtain ⟨θ, hθ⟩ := Field.exists_primitive_element ℚ F₀
  haveI := isSplittingField_baseCompositum ι hθ
  exact Normal.of_isSplittingField ((minpoly ℚ θ).map (algebraMap ℚ k))

instance finiteDimensionalBaseCompositum : FiniteDimensional k ↥(baseCompositum ι) := by
  obtain ⟨θ, hθ⟩ := Field.exists_primitive_element ℚ F₀
  haveI := isSplittingField_baseCompositum ι hθ
  exact Polynomial.IsSplittingField.finiteDimensional _ ((minpoly ℚ θ).map (algebraMap ℚ k))

instance isGaloisBaseCompositum : IsGalois k ↥(baseCompositum ι) := ⟨⟩

instance numberFieldBaseCompositum : NumberField ↥(baseCompositum ι) where
  to_finiteDimensional := Module.Finite.trans k ↥(baseCompositum ι)

instance isScalarTowerBaseCompositum : IsScalarTower ℚ F₀ ↥(baseCompositum ι) :=
  IsScalarTower.of_algebraMap_eq' (Subsingleton.elim _ _)

/-- **The image of `F₀` generates the compositum over `k`.**  The compositum is a splitting field
of the minimal polynomial of a primitive element, and every root of that polynomial lies in the
image of `F₀`. -/
theorem adjoin_range_algebraMap_eq_top :
    Algebra.adjoin k (Set.range (algebraMap F₀ ↥(baseCompositum ι))) = ⊤ := by
  obtain ⟨θ, hθ⟩ := Field.exists_primitive_element ℚ F₀
  set p : k[X] := (minpoly ℚ θ).map (algebraMap ℚ k) with hpdef
  haveI hsf := isSplittingField_baseCompositum ι hθ
  have hsub : p.rootSet ↥(baseCompositum ι) ⊆ Set.range (algebraMap F₀ ↥(baseCompositum ι)) := by
    intro x hx
    have hx2 := Polynomial.mem_rootSet.mp hx
    have hx' : ((x : AlgebraicClosure k)) ∈ p.rootSet (AlgebraicClosure k) := by
      refine Polynomial.mem_rootSet.mpr ⟨hx2.1, ?_⟩
      have h2 : Polynomial.aeval ((baseCompositum ι).val x) p
          = (baseCompositum ι).val (Polynomial.aeval x p) :=
        Polynomial.aeval_algHom_apply _ _ _
      rw [show ((x : AlgebraicClosure k)) = (baseCompositum ι).val x from rfl, h2, hx2.2, map_zero]
    obtain ⟨y, hy⟩ := rootSet_map_minpoly_subset_range ι θ hx'
    exact ⟨y, Subtype.ext (by rw [coe_algebraMap_baseCompositum]; exact hy)⟩
  rw [← top_le_iff, ← Polynomial.IsSplittingField.adjoin_rootSet ↥(baseCompositum ι) p]
  exact Algebra.adjoin_mono hsub

/-- A primitive element of `F₀` over the rationals generates the compositum over `k`. -/
theorem adjoin_singleton_eq_top {θ : F₀} (hθ : IntermediateField.adjoin ℚ {θ} = ⊤) :
    Algebra.adjoin k ({algebraMap F₀ ↥(baseCompositum ι) θ} : Set ↥(baseCompositum ι)) = ⊤ := by
  have hint : IsIntegral ℚ θ := Algebra.IsIntegral.isIntegral θ
  rw [← top_le_iff, ← adjoin_range_algebraMap_eq_top ι]
  refine Algebra.adjoin_le ?_
  rintro _ ⟨y, rfl⟩
  have hy : y ∈ Algebra.adjoin ℚ ({θ} : Set F₀) := by
    have hsub : (IntermediateField.adjoin ℚ ({θ} : Set F₀)).toSubalgebra
        = Algebra.adjoin ℚ ({θ} : Set F₀) :=
      IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic
    rw [← hsub, hθ]
    trivial
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hy
  obtain ⟨f, rfl⟩ := hy
  have hrw : algebraMap F₀ ↥(baseCompositum ι) ((Polynomial.aeval θ).toRingHom f)
      = Polynomial.aeval (algebraMap F₀ ↥(baseCompositum ι) θ) f :=
    (Polynomial.aeval_algHom_apply (IsScalarTower.toAlgHom ℚ F₀ ↥(baseCompositum ι)) θ f).symm
  rw [hrw]
  have hle : Algebra.adjoin ℚ ({algebraMap F₀ ↥(baseCompositum ι) θ} : Set ↥(baseCompositum ι))
      ≤ Subalgebra.restrictScalars ℚ
        (Algebra.adjoin k ({algebraMap F₀ ↥(baseCompositum ι) θ} : Set ↥(baseCompositum ι))) :=
    Algebra.adjoin_le (by rintro _ rfl; exact Algebra.subset_adjoin rfl)
  refine hle ?_
  rw [Algebra.adjoin_singleton_eq_range_aeval]
  exact ⟨f, rfl⟩

omit [IsGalois ℚ F₀] in
/-- Enlarging the embedded field enlarges the compositum. -/
theorem baseCompositum_le_of_range_subset {L : Type} [Field L] [NumberField L]
    (ι' : L →ₐ[ℚ] AlgebraicClosure k) (h : Set.range ι ⊆ Set.range ι') :
    baseCompositum ι ≤ baseCompositum ι' :=
  IntermediateField.adjoin_le_iff.mpr (h.trans (IntermediateField.subset_adjoin k _))

end Construction

end InverseGalois.CFT
