/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.CentralCompositum

/-!
# Extending an automorphism of one factor of a compositum by the identity on the other

Let `A` and `B` be two finite Galois subextensions of `L / F`.  An automorphism `a` of `A` which
fixes `A ⊓ B` pointwise extends to an automorphism of the compositum `A ⊔ B` restricting to the
identity on `B`.  This is the classical theorem on natural irrationalities in the form in which it
is used: the Galois group of a compositum is the fibre product of the two Galois groups over the
group of the intersection, and here only the fibre over the identity of `B` is needed.

The proof is the Galois correspondence.  The fixing subgroups of the two factors are normal, their
intersection is trivial, and their join is the fixing subgroup of `A ⊓ B`.  An automorphism of the
compositum restricting to `a` on `A` fixes `A ⊓ B`, hence factors as a product of an element
trivial on `A` and an element trivial on `B`; the second factor is the required extension.

Over the rationals this combines with the Chebotarev step for a central involution: an involution
of an abelian factor `A` fixing `A ⊓ B` is realized as an arithmetic Frobenius of the compositum
which is trivial on `B`.

## Main results

* `InverseGalois.CFT.fixingSubgroup_inf`: under the Galois correspondence the intersection of two
  intermediate fields corresponds to the join of their fixing subgroups.
* `InverseGalois.CFT.exists_galRestrictProd_fst_eq`: restriction to the first factor of a
  compositum is surjective.
* `InverseGalois.CFT.exists_galRestrictProd_eq_prod_one`: an automorphism of `A` fixing `A ⊓ B`
  extends to the compositum by the identity on `B`.
* `InverseGalois.CFT.exists_prime_isArithFrobAt_eqOn_inf`: over the rationals such an extension of
  an involution is an arithmetic Frobenius at infinitely many primes.
-/

open NumberField InverseGalois.NumberTheory

namespace InverseGalois.CFT

/-- **The Galois correspondence turns intersections into joins.**  The fixing subgroup of the
intersection of two intermediate fields of a finite Galois extension is the subgroup generated by
their two fixing subgroups. -/
theorem fixingSubgroup_inf {F E : Type*} [Field F] [Field E] [Algebra F E]
    [FiniteDimensional F E] [IsGalois F E] (K M : IntermediateField F E) :
    (K ⊓ M).fixingSubgroup = K.fixingSubgroup ⊔ M.fixingSubgroup := by
  refine le_antisymm ?_ (sup_le (IntermediateField.fixingSubgroup_le inf_le_left)
    (IntermediateField.fixingSubgroup_le inf_le_right))
  rw [← IntermediateField.fixingSubgroup_fixedField (K.fixingSubgroup ⊔ M.fixingSubgroup)]
  refine IntermediateField.fixingSubgroup_le (le_inf ?_ ?_)
  · conv_rhs => rw [← IsGalois.fixedField_fixingSubgroup K]
    exact IntermediateField.fixedField_le le_sup_left
  · conv_rhs => rw [← IsGalois.fixedField_fixingSubgroup M]
    exact IntermediateField.fixedField_le le_sup_right

section Normal

variable {F L : Type*} [Field F] [Field L] [Algebra F L] (A B : IntermediateField F L)
  [Normal F A] [Normal F B]

/-- An automorphism of the compositum that fixes the copy of `A` inside it restricts to the
identity on `A`. -/
theorem galRestrictProd_fst_eq_one_of_mem_fixingSubgroup {σ : Gal(↥(A ⊔ B)/F)}
    (hσ : σ ∈ (IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B)).fixingSubgroup) :
    (galRestrictProd A B σ).1 = 1 := by
  ext x
  have hx : (⟨(x : L), (le_sup_left : A ≤ A ⊔ B) x.2⟩ : ↥(A ⊔ B)) ∈
      IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B) :=
    (IntermediateField.mem_restrict _ _).mpr x.2
  have hfix := (IntermediateField.mem_fixingSubgroup_iff _ σ).mp hσ _ hx
  have h := coe_galRestrictProd_fst A B σ x
  rw [hfix] at h
  simpa using h

/-- An automorphism of the compositum that fixes the copy of `B` inside it restricts to the
identity on `B`. -/
theorem galRestrictProd_snd_eq_one_of_mem_fixingSubgroup {σ : Gal(↥(A ⊔ B)/F)}
    (hσ : σ ∈ (IntermediateField.restrict (le_sup_right : B ≤ A ⊔ B)).fixingSubgroup) :
    (galRestrictProd A B σ).2 = 1 := by
  ext x
  have hx : (⟨(x : L), (le_sup_right : B ≤ A ⊔ B) x.2⟩ : ↥(A ⊔ B)) ∈
      IntermediateField.restrict (le_sup_right : B ≤ A ⊔ B) :=
    (IntermediateField.mem_restrict _ _).mpr x.2
  have hfix := (IntermediateField.mem_fixingSubgroup_iff _ σ).mp hσ _ hx
  have h := coe_galRestrictProd_snd A B σ x
  rw [hfix] at h
  simpa using h

end Normal

section Galois

variable {F L : Type*} [Field F] [Field L] [Algebra F L] (A B : IntermediateField F L)
  [IsGalois F A] [FiniteDimensional F A] [IsGalois F B] [FiniteDimensional F B]

omit [FiniteDimensional F A] [FiniteDimensional F B] in
/-- **Restriction to the first factor of a compositum is surjective.** -/
theorem exists_galRestrictProd_fst_eq (a : Gal(A/F)) :
    ∃ σ : Gal(↥(A ⊔ B)/F), (galRestrictProd A B σ).1 = a := by
  haveI : Normal F ↥(IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B)) :=
    Normal.of_algEquiv (IntermediateField.restrict_algEquiv _)
  obtain ⟨σ, hσ⟩ := AlgEquiv.restrictNormalHom_surjective
    (K₁ := IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B)) (E := ↥(A ⊔ B))
    (AlgEquiv.autCongr (IntermediateField.restrict_algEquiv (le_sup_left : A ≤ A ⊔ B)) a)
  refine ⟨σ, ?_⟩
  simp only [galRestrictProd, MonoidHom.prod_apply, MonoidHom.coe_comp, Function.comp_apply,
    MulEquiv.coe_toMonoidHom, hσ, MulEquiv.symm_apply_apply]

/-- **Natural irrationalities.**  An automorphism of `A` which fixes the intersection `A ⊓ B`
pointwise extends to an automorphism of the compositum `A ⊔ B` restricting to the identity
on `B`. -/
theorem exists_galRestrictProd_eq_prod_one {a : Gal(A/F)}
    (ha : ∀ x : A, (x : L) ∈ B → a x = x) :
    ∃ σ : Gal(↥(A ⊔ B)/F), galRestrictProd A B σ = (a, 1) := by
  haveI hA : Normal F ↥(IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B)) :=
    Normal.of_algEquiv (IntermediateField.restrict_algEquiv _)
  haveI hB : Normal F ↥(IntermediateField.restrict (le_sup_right : B ≤ A ⊔ B)) :=
    Normal.of_algEquiv (IntermediateField.restrict_algEquiv _)
  haveI hnormA :
      (IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B)).fixingSubgroup.Normal := by
    rw [← IntermediateField.restrictNormalHom_ker
      (IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B))]
    infer_instance
  obtain ⟨σ₀, hσ₀⟩ := exists_galRestrictProd_fst_eq A B a
  have hfix : σ₀ ∈ (IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B) ⊓
      IntermediateField.restrict (le_sup_right : B ≤ A ⊔ B)).fixingSubgroup := by
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    rw [IntermediateField.mem_inf, IntermediateField.mem_restrict,
      IntermediateField.mem_restrict] at hx
    have hval := coe_galRestrictProd_fst A B σ₀ ⟨(x : L), hx.1⟩
    rw [hσ₀, ha ⟨(x : L), hx.1⟩ hx.2] at hval
    exact Subtype.ext hval.symm
  rw [fixingSubgroup_inf, ← SetLike.mem_coe, Subgroup.normal_mul] at hfix
  obtain ⟨nA, hmemA, nB, hmemB, hmul⟩ := hfix
  have hmul' : nA * nB = σ₀ := hmul
  refine ⟨nB, Prod.ext ?_ (galRestrictProd_snd_eq_one_of_mem_fixingSubgroup A B hmemB)⟩
  have hprod : galRestrictProd A B σ₀ = galRestrictProd A B nA * galRestrictProd A B nB := by
    rw [← map_mul, hmul']
  have h1 := galRestrictProd_fst_eq_one_of_mem_fixingSubgroup A B hmemA
  have := congrArg Prod.fst hprod
  rw [hσ₀, Prod.fst_mul, h1, one_mul] at this
  exact this.symm

end Galois

section NumberField

variable {N : Type*} [Field N] [NumberField N] (A B : IntermediateField ℚ N) [IsGalois ℚ ↥A]
  [IsGalois ℚ ↥B]

set_option maxHeartbeats 1000000 in
/-- **Chebotarev for an involution prescribed on one factor of a compositum.**  Let `A` and `B` be
Galois subextensions of a number field with `A` abelian over `ℚ`, and let `a` be an involution of
the Galois group of `A` fixing `A ⊓ B` pointwise.  There are infinitely many primes carrying an
arithmetic Frobenius of the compositum which restricts to `a` on `A` and to the identity on `B`. -/
theorem exists_prime_isArithFrobAt_eqOn_inf (hcomm : ∀ x y : Gal(↥A/ℚ), x * y = y * x)
    {a : Gal(↥A/ℚ)} (ha2 : a ^ 2 = 1) (ha : ∀ x : ↥A, (x : N) ∈ B → a x = x) (T : Finset ℕ) :
    ∃ p : ℕ, p.Prime ∧ p ∉ T ∧ p ∉ ramifiedSet ↥(A ⊔ B) ∧ ∃ P : Ideal (𝓞 ↥(A ⊔ B)),
      P.IsPrime ∧ P.LiesOver (Ideal.span {(p : ℤ)}) ∧ ∃ σ : Gal(↥(A ⊔ B)/ℚ),
        galRestrictProd A B σ = (a, 1) ∧ IsArithFrobAt ℤ σ P := by
  obtain ⟨σ, hσ⟩ := exists_galRestrictProd_eq_prod_one A B ha
  have hσ2 : σ ^ 2 = 1 := by
    refine galRestrictProd_injective A B ?_
    rw [map_pow, map_one, hσ]
    simp [Prod.ext_iff, ha2]
  obtain ⟨p, hp, hpT, hpram, P, hP, hPover, hfrob⟩ :=
    exists_prime_isArithFrobAt_sup A B hcomm (by rw [hσ]) hσ2 T
  exact ⟨p, hp, hpT, hpram, P, hP, hPover, σ, hσ, hfrob⟩

end NumberField

end InverseGalois.CFT
