import Mathlib
import InverseGalois.CFT.Cyclotomic.Frobenius

/-!
# Decomposition, inertia and Frobenius for a Galois number field

Let `K` be a number field which is Galois over `ℚ` and let `P` be a nonzero prime of the ring of
integers `𝓞 K`.  Attached to `P` are three subgroups of `Gal(K/ℚ)`, namely the decomposition group
`MulAction.stabilizer Gal(K/ℚ) P`, the inertia group `Ideal.inertia Gal(K/ℚ) P`, and the cyclic
group generated by an arithmetic Frobenius `arithFrobAt ℤ Gal(K/ℚ) P`.  This file records the
dictionary relating them to the local invariants `e` and `f` of `P`.

## Main results

* `InverseGalois.CFT.inertia_eq_bot_iff_isUnramifiedAt`: the inertia group is trivial exactly when
  `P` is unramified over `ℤ`.
* `InverseGalois.CFT.orderOf_arithFrobAt_eq_inertiaDeg`: at an unramified prime the Frobenius has
  order the inertia degree.
* `InverseGalois.CFT.stabilizer_eq_zpowers_arithFrobAt`: at an unramified prime the decomposition
  group is generated by the Frobenius.
* `InverseGalois.CFT.stabilizer_eq_bot_iff` and `InverseGalois.CFT.arithFrobAt_eq_one_iff`: the
  decomposition group, respectively the Frobenius, is trivial exactly when `P` splits completely.
-/

open NumberField

open scoped Pointwise

namespace InverseGalois.CFT

attribute [local instance] Ideal.Quotient.field

variable {K : Type*} [Field K] [NumberField K] [IsGalois ℚ K]

section Basic

omit [IsGalois ℚ K] in
/-- A prime of `𝓞 K` lying over a rational prime is nonzero. -/
theorem ne_bot_of_liesOver (p : ℕ) [Fact p.Prime] (P : Ideal (𝓞 K))
    [P.LiesOver (Ideal.span {(p : ℤ)})] : P ≠ ⊥ := by
  refine Ideal.ne_bot_of_liesOver_of_ne_bot (p := Ideal.span {(p : ℤ)}) ?_ P
  simp [Ideal.span_singleton_eq_bot, (Fact.out : p.Prime).ne_zero]

omit [IsGalois ℚ K] in
/-- A nonzero prime of the ring of integers of a number field is maximal. -/
theorem isMaximal_of_ne_bot (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) : P.IsMaximal :=
  Ideal.IsPrime.isMaximal ‹_› hP

omit [IsGalois ℚ K] in
/-- The residue field at a nonzero prime of `𝓞 K` is finite. -/
theorem finite_quotient_of_ne_bot (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) :
    Finite (𝓞 K ⧸ P) :=
  haveI := isMaximal_of_ne_bot P hP
  inferInstance

omit [NumberField K] [IsGalois ℚ K] in
/-- The rational prime under a nonzero prime of `𝓞 K` is nonzero. -/
theorem under_ne_bot (P : Ideal (𝓞 K)) (hP : P ≠ ⊥) : P.under ℤ ≠ ⊥ :=
  Ideal.under_ne_bot ℤ hP

end Basic

section Inertia

omit [NumberField K] [IsGalois ℚ K] in
/-- The rational prime under a nonzero prime of `𝓞 K` is maximal. -/
theorem isMaximal_under_of_ne_bot (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) :
    (P.under ℤ).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance (under_ne_bot P hP)

omit [IsGalois ℚ K] in
/-- The residue field of the rational prime under a nonzero prime of `𝓞 K` is finite. -/
theorem finite_quotient_under_of_ne_bot (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) :
    Finite (ℤ ⧸ P.under ℤ) :=
  haveI := finite_quotient_of_ne_bot P hP
  .of_injective _ (Ideal.algebraMap_quotient_injective (R := ℤ) (A := 𝓞 K) (I := P))

omit [IsGalois ℚ K] in
/-- The residue extension at a nonzero prime of `𝓞 K` is separable. -/
theorem isSeparable_residue_of_ne_bot (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) :
    Algebra.IsSeparable (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P) := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  infer_instance

/-- The inertia group at a nonzero prime `P` of `𝓞 K` is trivial exactly when `P` is unramified
over `ℤ`. -/
theorem inertia_eq_bot_iff_isUnramifiedAt (P : Ideal (𝓞 K)) [P.IsPrime] (hP : P ≠ ⊥) :
    Ideal.inertia Gal(K/ℚ) P = ⊥ ↔ Algebra.IsUnramifiedAt ℤ P := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := finite_quotient_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  rw [Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hP, ← Subgroup.card_eq_one,
    Ideal.card_inertia_eq_ramificationIdxIn (G := Gal(K/ℚ)) (P.under ℤ) (under_ne_bot P hP) P,
    Ideal.ramificationIdxIn_eq_ramificationIdx (P.under ℤ) P Gal(K/ℚ)]

end Inertia

section Frobenius

variable (P : Ideal (𝓞 K)) [P.IsPrime] [Finite (𝓞 K ⧸ P)]

/-- The arithmetic Frobenius at a prime `P` fixes `P`, i.e. it lies in the decomposition group. -/
theorem arithFrobAt_mem_stabilizer :
    arithFrobAt ℤ Gal(K/ℚ) P ∈ MulAction.stabilizer Gal(K/ℚ) P := by
  have H := IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P
  have key : ∀ x : 𝓞 K, arithFrobAt ℤ Gal(K/ℚ) P • x ∈ P ↔ x ∈ P := by
    intro x
    conv_lhs => rw [show arithFrobAt ℤ Gal(K/ℚ) P • x =
      MulSemiringAction.toAlgHom ℤ (𝓞 K) (arithFrobAt ℤ Gal(K/ℚ) P) x from rfl,
      ← Ideal.mem_comap, H.comap_eq]
  rw [MulAction.mem_stabilizer_iff]
  ext y
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem,
    ← key ((arithFrobAt ℤ Gal(K/ℚ) P)⁻¹ • y), smul_inv_smul]

/-- At an unramified prime the arithmetic Frobenius has order the inertia degree. -/
theorem orderOf_arithFrobAt_eq_inertiaDeg (hP : P ≠ ⊥) (hunr : Algebra.IsUnramifiedAt ℤ P) :
    orderOf (arithFrobAt ℤ Gal(K/ℚ) P) = (P.under ℤ).inertiaDeg P := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  letI : Fintype (ℤ ⧸ P.under ℤ) := Fintype.ofFinite _
  have hmem := arithFrobAt_mem_stabilizer P
  have hker : (Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ)).ker = ⊥ := by
    rw [Ideal.Quotient.ker_stabilizerHom, (inertia_eq_bot_iff_isUnramifiedAt P hP).mpr hunr]
    simp
  have hinj := (MonoidHom.ker_eq_bot_iff _).mp hker
  have himg : Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ)
        ⟨arithFrobAt ℤ Gal(K/ℚ) P, hmem⟩ =
      FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P) := by
    ext x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective x
    have hb := (IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P).mk_apply b
    rw [Ideal.Quotient.stabilizerHom_apply, show
      (FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P))
        (Ideal.Quotient.mk P b) =
        Ideal.Quotient.mk P b ^ Fintype.card (ℤ ⧸ P.under ℤ) from rfl,
      ← Nat.card_eq_fintype_card]
    exact hb
  have h1 : orderOf (arithFrobAt ℤ Gal(K/ℚ) P) =
      orderOf (⟨arithFrobAt ℤ Gal(K/ℚ) P, hmem⟩ : MulAction.stabilizer Gal(K/ℚ) P) :=
    (Subgroup.orderOf_mk (H := MulAction.stabilizer Gal(K/ℚ) P) _ hmem).symm
  rw [h1, ← orderOf_injective _ hinj, himg,
    FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic, Ideal.inertiaDeg_algebraMap]

/-- At an unramified prime the decomposition group is the cyclic group generated by the
arithmetic Frobenius. -/
theorem stabilizer_eq_zpowers_arithFrobAt (hP : P ≠ ⊥) (hunr : Algebra.IsUnramifiedAt ℤ P) :
    MulAction.stabilizer Gal(K/ℚ) P = Subgroup.zpowers (arithFrobAt ℤ Gal(K/ℚ) P) := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  have hmem := arithFrobAt_mem_stabilizer P
  have hcard : Nat.card (MulAction.stabilizer Gal(K/ℚ) P) = (P.under ℤ).inertiaDeg P := by
    rw [Ideal.card_stabilizer_eq (G := Gal(K/ℚ)) (P.under ℤ) (under_ne_bot P hP) P,
      Ideal.ramificationIdxIn_eq_ramificationIdx (P.under ℤ) P Gal(K/ℚ),
      (Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hP).mp hunr, one_mul,
      Ideal.inertiaDegIn_eq_inertiaDeg (P.under ℤ) P Gal(K/ℚ)]
  refine (Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hmem) ?_).symm
  rw [hcard, Nat.card_zpowers, orderOf_arithFrobAt_eq_inertiaDeg P hP hunr]

omit [Finite (𝓞 K ⧸ P)] in
/-- A nonzero prime of `𝓞 K` splits completely exactly when its decomposition group is
trivial. -/
theorem stabilizer_eq_bot_iff (hP : P ≠ ⊥) :
    MulAction.stabilizer Gal(K/ℚ) P = ⊥ ↔
      Algebra.IsUnramifiedAt ℤ P ∧ (P.under ℤ).inertiaDeg P = 1 := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  rw [← Subgroup.card_eq_one,
    Ideal.card_stabilizer_eq (G := Gal(K/ℚ)) (P.under ℤ) (under_ne_bot P hP) P, mul_eq_one,
    Ideal.ramificationIdxIn_eq_ramificationIdx (P.under ℤ) P Gal(K/ℚ),
    ← Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hP,
    Ideal.inertiaDegIn_eq_inertiaDeg (P.under ℤ) P Gal(K/ℚ)]

/-- At an unramified prime, the Frobenius is trivial exactly when the decomposition group is
trivial. -/
theorem arithFrobAt_eq_one_iff_stabilizer_eq_bot (hP : P ≠ ⊥)
    (hunr : Algebra.IsUnramifiedAt ℤ P) :
    arithFrobAt ℤ Gal(K/ℚ) P = 1 ↔ MulAction.stabilizer Gal(K/ℚ) P = ⊥ := by
  rw [stabilizer_eq_zpowers_arithFrobAt P hP hunr, Subgroup.zpowers_eq_bot]

/-- At an unramified prime, the Frobenius is trivial exactly when the prime splits completely. -/
theorem arithFrobAt_eq_one_iff (hP : P ≠ ⊥) (hunr : Algebra.IsUnramifiedAt ℤ P) :
    arithFrobAt ℤ Gal(K/ℚ) P = 1 ↔ (P.under ℤ).inertiaDeg P = 1 := by
  rw [arithFrobAt_eq_one_iff_stabilizer_eq_bot P hP hunr, stabilizer_eq_bot_iff P hP,
    and_iff_right hunr]

end Frobenius

end InverseGalois.CFT
