/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Decomposition

/-!
# Generating the decomposition group at a ramified prime

At an unramified prime the decomposition group of a prime `P` of a Galois number field is the cyclic
group generated by an arithmetic Frobenius.  At a ramified prime that is no longer true, but the
Frobenius still generates the decomposition group *modulo inertia*: the quotient of the
decomposition group by the inertia group is the Galois group of the residue extension, which is
generated by the residue Frobenius, and an arithmetic Frobenius upstairs induces exactly that.
Consequently the decomposition group is contained in the subgroup generated by the inertia group
together with any arithmetic Frobenius.

The statement is used through the following consequence.  For a homomorphism out of the Galois
group, the image of the decomposition group is contained in the image of the inertia group as soon
as the image of a single arithmetic Frobenius is.  This turns a condition on a whole subgroup into a
condition on one element.

## Main results

* `InverseGalois.CFT.stabilizer_le_inertia_sup_zpowers`: **the decomposition group at a nonzero
  prime is generated by the inertia group together with an arithmetic Frobenius.**
* `InverseGalois.CFT.map_stabilizer_le_map_inertia`: the image of the decomposition group under a
  homomorphism lies in the image of the inertia group as soon as the image of an arithmetic
  Frobenius does.

## Tags

decomposition group, inertia group, Frobenius, residue field, ramification
-/

open NumberField

open scoped Pointwise

namespace InverseGalois.CFT

attribute [local instance] Ideal.Quotient.field

variable {K : Type*} [Field K] [NumberField K] [IsGalois ℚ K]
variable (P : Ideal (𝓞 K)) [P.IsPrime] [Finite (𝓞 K ⧸ P)]

omit [IsGalois ℚ K] [Finite (𝓞 K ⧸ P)] in
/-- An arithmetic Frobenius at a prime `P` fixes `P`, that is, it lies in the decomposition
group. -/
theorem mem_stabilizer_of_isArithFrobAt {σ : Gal(K/ℚ)} (hσ : IsArithFrobAt ℤ σ P) :
    σ ∈ MulAction.stabilizer Gal(K/ℚ) P := by
  have key : ∀ x : 𝓞 K, σ • x ∈ P ↔ x ∈ P := by
    intro x
    conv_lhs => rw [show σ • x = MulSemiringAction.toAlgHom ℤ (𝓞 K) σ x from rfl,
      ← Ideal.mem_comap, hσ.comap_eq]
  rw [MulAction.mem_stabilizer_iff]
  ext y
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, ← key (σ⁻¹ • y), smul_inv_smul]

/-- **The decomposition group is generated by the inertia group together with the canonical
arithmetic Frobenius.**  The residue extension is an extension of finite fields, so its Galois
group is generated by the residue Frobenius; the canonical arithmetic Frobenius induces the residue
Frobenius, and the map from the decomposition group to the Galois group of the residue extension is
surjective with kernel the inertia group. -/
theorem stabilizer_le_inertia_sup_zpowers_arithFrobAt (hP : P ≠ ⊥) :
    MulAction.stabilizer Gal(K/ℚ) P ≤
      Ideal.inertia Gal(K/ℚ) P ⊔ Subgroup.zpowers (arithFrobAt ℤ Gal(K/ℚ) P) := by
  haveI := isMaximal_of_ne_bot P hP
  haveI := isMaximal_under_of_ne_bot P hP
  haveI := finite_quotient_under_of_ne_bot P hP
  haveI := isSeparable_residue_of_ne_bot P hP
  letI : Fintype (ℤ ⧸ P.under ℤ) := Fintype.ofFinite _
  have hmem := arithFrobAt_mem_stabilizer P
  have himg : Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ)
        ⟨arithFrobAt ℤ Gal(K/ℚ) P, hmem⟩ =
      FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P) := by
    ext x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective x
    have hb := (IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P).mk_apply b
    rw [Ideal.Quotient.stabilizerHom_apply, show
      (FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P))
        (Ideal.Quotient.mk P b) =
        Ideal.Quotient.mk P b ^ Fintype.card (ℤ ⧸ P.under ℤ) from rfl,
      ← Nat.card_eq_fintype_card]
    exact hb
  intro d hd
  obtain ⟨n, hn⟩ := (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow
    (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P)).surjective
    (Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ) ⟨d, hd⟩)
  have hn' : FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ P.under ℤ) (𝓞 K ⧸ P) ^ (n : ℕ) =
      Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ) ⟨d, hd⟩ := hn
  set y : MulAction.stabilizer Gal(K/ℚ) P :=
    ⟨d, hd⟩ * (⟨arithFrobAt ℤ Gal(K/ℚ) P, hmem⟩ ^ (n : ℕ))⁻¹ with hy
  have hyker : (y : Gal(K/ℚ)) ∈ Ideal.inertia Gal(K/ℚ) P := by
    have : y ∈ (Ideal.Quotient.stabilizerHom P (P.under ℤ) Gal(K/ℚ)).ker := by
      rw [MonoidHom.mem_ker, hy, map_mul, map_inv, map_pow, himg, hn', mul_inv_cancel]
    rwa [Ideal.Quotient.ker_stabilizerHom, Subgroup.mem_subgroupOf] at this
  have hdeq : d = (y : Gal(K/ℚ)) * arithFrobAt ℤ Gal(K/ℚ) P ^ (n : ℕ) := by
    simp [hy]
  rw [hdeq]
  exact Subgroup.mul_mem_sup hyker (pow_mem (Subgroup.mem_zpowers _) _)

/-- **The decomposition group at a nonzero prime is generated by the inertia group together with an
arithmetic Frobenius.**  Any two arithmetic Frobenius elements at a prime differ by an element of
the inertia group, so the statement for the canonical one gives it for all of them. -/
theorem stabilizer_le_inertia_sup_zpowers (hP : P ≠ ⊥) {σ : Gal(K/ℚ)} (hσ : IsArithFrobAt ℤ σ P) :
    MulAction.stabilizer Gal(K/ℚ) P ≤ Ideal.inertia Gal(K/ℚ) P ⊔ Subgroup.zpowers σ := by
  refine (stabilizer_le_inertia_sup_zpowers_arithFrobAt P hP).trans (sup_le le_sup_left ?_)
  rw [Subgroup.zpowers_le]
  have hmem := (IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P).mul_inv_mem_inertia hσ
  have hrw : arithFrobAt ℤ Gal(K/ℚ) P = arithFrobAt ℤ Gal(K/ℚ) P * σ⁻¹ * σ := by group
  rw [hrw]
  exact Subgroup.mul_mem_sup hmem (Subgroup.mem_zpowers σ)

/-- **One element decides the whole decomposition group.**  The image of the decomposition group
under a homomorphism out of the Galois group is contained in the image of the inertia group as soon
as the image of an arithmetic Frobenius is. -/
theorem map_stabilizer_le_map_inertia {G : Type*} [Group G] (ψ : Gal(K/ℚ) →* G) (hP : P ≠ ⊥)
    {σ : Gal(K/ℚ)} (hσ : IsArithFrobAt ℤ σ P)
    (hψ : ψ σ ∈ (Ideal.inertia Gal(K/ℚ) P).map ψ) :
    (MulAction.stabilizer Gal(K/ℚ) P).map ψ ≤ (Ideal.inertia Gal(K/ℚ) P).map ψ := by
  rw [Subgroup.map_le_iff_le_comap]
  refine (stabilizer_le_inertia_sup_zpowers P hP hσ).trans (sup_le ?_ ?_)
  · exact Subgroup.le_comap_map ψ _
  · rw [Subgroup.zpowers_le]
    exact hψ

end InverseGalois.CFT
