/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Decomposition
import InverseGalois.CFT.InertiaSubgroup
import InverseGalois.CFT.SplitCompositum
import InverseGalois.NumberTheory.SplitDensity

/-!
# An involution of a Galois group as an arithmetic Frobenius

Chebotarev's density theorem realises every conjugacy class of the Galois group of a number field
as the class of an arithmetic Frobenius at infinitely many primes.  For an element of order two
generating a normal subgroup the statement follows from the only density input this development
has, namely that the primes splitting completely in a Galois number field have density the inverse
of its degree, and hence that infinitely many rational primes split completely in a smaller Galois
number field while failing to split completely in a larger one.

Take for the smaller field the fixed field of the subgroup generated by the element and for the
larger one the field itself.  Splitting completely below says that the decomposition group at a
prime above is contained in that subgroup; failing to split completely above says that it is
nontrivial.  A subgroup of order two leaves nothing in between, so the decomposition group is the
whole of it, and at an unramified prime the decomposition group is generated by the arithmetic
Frobenius.  The Frobenius is therefore the nontrivial element itself, since a group of order two
has only one of those.

## Main results

* `InverseGalois.CFT.exists_prime_stabilizer_eq_zpowers`: **an element of order two generating a
  normal subgroup is the arithmetic Frobenius at a prime avoiding any prescribed finite set**, and
  the decomposition group there is exactly the subgroup it generates.
* `InverseGalois.CFT.exists_prime_isArithFrobAt_of_sq_eq_one`: the same conclusion for an element
  whose square is one, the trivial element included.

## Tags

Frobenius, decomposition group, Chebotarev, Dirichlet density, involution
-/

open NumberField InverseGalois.NumberTheory

open scoped Pointwise

set_option synthInstance.maxHeartbeats 400000

namespace InverseGalois.CFT

/-- In a group of order two any two nontrivial elements agree. -/
private theorem eq_of_card_eq_two {G : Type*} [Group G] {K : Subgroup G} (hK : Nat.card ↥K = 2)
    {z w : G} (hz : z ∈ K) (hz1 : z ≠ 1) (hw : w ∈ K) (hw1 : w ≠ 1) : w = z := by
  obtain ⟨u, -, hu⟩ := (Nat.card_eq_two_iff' (1 : ↥K)).mp hK
  have h1 : ∀ x ∈ K, x ≠ 1 → x = (u : G) := fun x hx hx1 =>
    congrArg Subtype.val (hu ⟨x, hx⟩ fun h => hx1 (congrArg Subtype.val h))
  rw [h1 w hw hw1, ← h1 z hz hz1]

variable {K : Type*} [Field K] [NumberField K] [IsGalois ℚ K]

/-- **An element of order two generating a normal subgroup is an arithmetic Frobenius.**  The
primes splitting completely in the fixed field of the subgroup it generates but not in the whole
field are infinite in number, so one of them avoids both a prescribed finite set and the finitely
many ramified primes.  At a prime above it where the splitting fails, the decomposition group is
contained in the subgroup because the prime below splits completely, and is nontrivial because the
prime above does not; a subgroup of order two admits no other possibility, and the arithmetic
Frobenius generates the decomposition group at an unramified prime. -/
theorem exists_prime_stabilizer_eq_zpowers {σ : Gal(K/ℚ)} (hnorm : (Subgroup.zpowers σ).Normal)
    (hσ1 : σ ≠ 1) (hσ2 : σ ^ 2 = 1) (T : Finset ℕ) :
    ∃ p : ℕ, p.Prime ∧ p ∉ T ∧ p ∉ ramifiedSet K ∧ ∃ P : Ideal (𝓞 K), P.IsPrime ∧
      P.LiesOver (Ideal.span {(p : ℤ)}) ∧
      MulAction.stabilizer Gal(K/ℚ) P = Subgroup.zpowers σ ∧ IsArithFrobAt ℤ σ P := by
  classical
  haveI := hnorm
  have hcardH : Nat.card ↥(Subgroup.zpowers σ) = 2 := by
    rw [Nat.card_zpowers, orderOf_eq_prime hσ2 hσ1]
  set A : IntermediateField ℚ K := IntermediateField.fixedField (Subgroup.zpowers σ) with hA
  haveI : IsGalois ℚ ↥A := by rw [hA]; infer_instance
  haveI : NumberField ↥A := ⟨⟩
  clear_value A
  -- the fixed field is a proper subfield, of half the degree
  have hlt : Module.finrank ℚ ↥A < Module.finrank ℚ K := by
    have hmul := Module.finrank_mul_finrank ℚ ↥A K
    have hfr : Module.finrank ↥A K = 2 := by
      rw [hA, IntermediateField.finrank_fixedField_eq_card, hcardH]
    rw [hfr] at hmul
    have hpos : 0 < Module.finrank ℚ ↥A := Module.finrank_pos
    omega
  -- a prime splitting completely below but not above, unramified and outside the prescribed set
  obtain ⟨p, ⟨hp, hsplitA, hnsplit⟩, hpT⟩ :=
    (infinite_setOf_splitsCompletely_not_splitsCompletely ↥A K hlt).exists_notMem_finset
      (T ∪ (finite_ramifiedSet K).toFinset)
  simp only [Finset.mem_union, not_or] at hpT
  obtain ⟨hpT₁, hpram⟩ := hpT
  have hpram' : p ∉ ramifiedSet K := fun h =>
    hpram ((Set.Finite.mem_toFinset (finite_ramifiedSet K)).mpr h)
  haveI : Fact p.Prime := ⟨hp⟩
  -- a prime above it at which the splitting fails
  have hex : ∃ P ∈ (Ideal.span {(p : ℤ)}).primesOver (𝓞 K),
      ¬ (Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) (Ideal.span {(p : ℤ)}) P = 1 ∧
        (Ideal.span {(p : ℤ)}).inertiaDeg P = 1) := by
    by_contra hc
    refine hnsplit fun P hP => ?_
    by_contra hc2
    exact hc ⟨P, hP, hc2⟩
  obtain ⟨P, ⟨hPprime, hPover⟩, hPne⟩ := hex
  haveI := hPprime
  haveI := hPover
  have hP0 : P ≠ ⊥ := ne_bot_of_liesOver p P
  have hunr : Algebra.IsUnramifiedAt ℤ P :=
    (inertia_eq_bot_iff_isUnramifiedAt P hP0).mp (inertia_eq_bot_of_notMem_ramifiedSet hp P hpram')
  haveI : Finite (𝓞 K ⧸ P) := finite_quotient_of_ne_bot P hP0
  -- the decomposition group is nontrivial
  have hstabne : MulAction.stabilizer Gal(K/ℚ) P ≠ ⊥ := by
    intro hb
    refine hPne ?_
    have h1 : Nat.card ↥(MulAction.stabilizer Gal(K/ℚ) P) = 1 := Subgroup.card_eq_one.mpr hb
    rw [card_stabilizer_eq_mul K hp P] at h1
    exact ⟨Nat.eq_one_of_mul_eq_one_right h1, Nat.eq_one_of_mul_eq_one_left h1⟩
  -- and contained in the subgroup, because the prime below splits completely
  have hbotA : MulAction.stabilizer Gal(↥A/ℚ) (P.under (𝓞 ↥A)) = ⊥ := by
    haveI : (P.under (𝓞 ↥A)).LiesOver (Ideal.span {(p : ℤ)}) :=
      ⟨by rw [Ideal.under_under]; exact hPover.over⟩
    exact stabilizer_eq_bot_of_splitsCompletely ↥A hp _ hsplitA
  have hle : MulAction.stabilizer Gal(K/ℚ) P ≤ Subgroup.zpowers σ := by
    intro τ hτ
    have hmem := restrictNormal_mem_stabilizer A P hτ
    rw [hbotA, Subgroup.mem_bot] at hmem
    have hfix : τ ∈ A.fixingSubgroup := by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro x hx
      have hcom := AlgEquiv.restrictNormal_commutes τ ↥A ⟨x, hx⟩
      rw [hmem] at hcom
      simpa using hcom.symm
    rwa [hA, IntermediateField.fixingSubgroup_fixedField] at hfix
  have hstabeq : MulAction.stabilizer Gal(K/ℚ) P = Subgroup.zpowers σ := by
    refine Subgroup.eq_of_le_of_card_ge hle ?_
    have h1 : Nat.card ↥(MulAction.stabilizer Gal(K/ℚ) P) ≠ 1 := fun h =>
      hstabne (Subgroup.card_eq_one.mp h)
    have h2 : 0 < Nat.card ↥(MulAction.stabilizer Gal(K/ℚ) P) := Nat.card_pos
    rw [hcardH]
    omega
  -- the arithmetic Frobenius generates it, so it is the element itself
  have hfrob := stabilizer_eq_zpowers_arithFrobAt P hP0 hunr
  rw [hstabeq] at hfrob
  have hφmem : arithFrobAt ℤ Gal(K/ℚ) P ∈ Subgroup.zpowers σ := by
    rw [hfrob]
    exact Subgroup.mem_zpowers _
  have hφ1 : arithFrobAt ℤ Gal(K/ℚ) P ≠ 1 := by
    intro h
    have hb : Subgroup.zpowers σ = ⊥ := by rw [hfrob, h, Subgroup.zpowers_one_eq_bot]
    rw [Subgroup.card_eq_one.mpr hb] at hcardH
    omega
  have heq : arithFrobAt ℤ Gal(K/ℚ) P = σ :=
    eq_of_card_eq_two hcardH (Subgroup.mem_zpowers σ) hσ1 hφmem hφ1
  exact ⟨p, hp, hpT₁, hpram', P, hPprime, hPover, hstabeq,
    heq ▸ IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P⟩

/-- **An element whose square is one is an arithmetic Frobenius**, at a prime unramified in the
field and avoiding any prescribed finite set, as soon as the subgroup it generates is normal.  For
a nontrivial element this is the previous statement; for the trivial one it asks only for a prime
splitting completely, of which there are infinitely many. -/
theorem exists_prime_isArithFrobAt_of_sq_eq_one {σ : Gal(K/ℚ)}
    (hnorm : (Subgroup.zpowers σ).Normal) (hσ2 : σ ^ 2 = 1) (T : Finset ℕ) :
    ∃ p : ℕ, p.Prime ∧ p ∉ T ∧ p ∉ ramifiedSet K ∧ ∃ P : Ideal (𝓞 K), P.IsPrime ∧
      P.LiesOver (Ideal.span {(p : ℤ)}) ∧ IsArithFrobAt ℤ σ P := by
  classical
  by_cases hσ1 : σ = 1
  · subst hσ1
    obtain ⟨p, ⟨hp, hsplit⟩, hpT⟩ :=
      (infinite_splitSet K).exists_notMem_finset (T ∪ (finite_ramifiedSet K).toFinset)
    simp only [Finset.mem_union, not_or] at hpT
    obtain ⟨hpT₁, hpram⟩ := hpT
    have hpram' : p ∉ ramifiedSet K := fun h =>
      hpram ((Set.Finite.mem_toFinset (finite_ramifiedSet K)).mpr h)
    haveI : Fact p.Prime := ⟨hp⟩
    haveI := isMaximal_span_prime hp
    obtain ⟨P, hPmax, hPover⟩ :=
      Ideal.exists_maximal_ideal_liesOver_of_isIntegral (S := 𝓞 K) (Ideal.span {(p : ℤ)})
    haveI := hPmax
    haveI := hPover
    haveI : P.IsPrime := hPmax.isPrime
    have hP0 : P ≠ ⊥ := ne_bot_of_liesOver p P
    have hunr : Algebra.IsUnramifiedAt ℤ P :=
      (inertia_eq_bot_iff_isUnramifiedAt P hP0).mp
        (inertia_eq_bot_of_notMem_ramifiedSet hp P hpram')
    haveI : Finite (𝓞 K ⧸ P) := finite_quotient_of_ne_bot P hP0
    have hone : arithFrobAt ℤ Gal(K/ℚ) P = 1 :=
      (arithFrobAt_eq_one_iff_stabilizer_eq_bot P hP0 hunr).mpr
        (stabilizer_eq_bot_of_splitsCompletely K hp P hsplit)
    exact ⟨p, hp, hpT₁, hpram', P, inferInstance, hPover,
      hone ▸ IsArithFrobAt.arithFrobAt ℤ Gal(K/ℚ) P⟩
  · obtain ⟨p, hp, hpT, hpram, P, hPprime, hPover, -, hfrob⟩ :=
      exists_prime_stabilizer_eq_zpowers hnorm hσ1 hσ2 T
    exact ⟨p, hp, hpT, hpram, P, hPprime, hPover, hfrob⟩

end InverseGalois.CFT
