/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.InertiaGeneration
import InverseGalois.CFT.InertiaSubgroup

/-!
# The ramified primes of the fixed field of a subgroup

Let `N` be a Galois number field.  A rational prime ramifies in the fixed field of a subgroup `H` of
`Gal(N/ℚ)` exactly when some prime of `𝓞 N` above it has inertia subgroup not contained in `H`.
One direction is the statement that the inertia subgroup at a prime unramified in a subextension
fixes that subextension pointwise; the other is the ramification-index computation in the tower
`ℤ ⊆ 𝓞 E ⊆ 𝓞 N`, where `E` is the fixed field.

The residue degree is governed the same way, one step further up: a prime of the fixed field has
residue degree one over the rationals as soon as the decomposition subgroup of a prime above it is
already contained in the subgroup generated by the inertia subgroup and `H`.  Counting the two
decomposition groups against the two inertia subgroups reduces this to the observation that `H`
meets the decomposition group and the inertia subgroup in the same relative index.

This is the tool that reads off the ramification of a solution of an embedding problem: a surjection
`ψ : Gal(N/ℚ) →* G` cuts out the fixed field of its kernel, the primes ramifying there are exactly
those at which `ψ` is nontrivial on inertia, and the residue degrees are one exactly when `ψ` sees
no more of a decomposition group than of its inertia subgroup.

## Main results

* `InverseGalois.CFT.notMem_ramifiedSet_fixedField`: **a rational prime all of whose inertia
  subgroups lie in a subgroup is unramified in the fixed field of that subgroup.**
* `InverseGalois.CFT.mem_ramifiedSet_fixedField_iff`: **a rational prime ramifies in the fixed field
  of a normal subgroup exactly when the inertia subgroup of some prime above it is not contained in
  that subgroup.**
* `InverseGalois.CFT.notMem_ramifiedSet_fixedField_ker`: **a rational prime at which a homomorphism
  kills every inertia subgroup is unramified in the fixed field of its kernel.**
* `InverseGalois.CFT.forall_inertia_le_of_inertia_le` and
  `InverseGalois.CFT.notMem_ramifiedSet_fixedField_ker_of_inertia`: for a normal subgroup **one
  prime above `p` suffices**, since the Galois group permutes them transitively.
* `InverseGalois.CFT.inertiaDeg_under_fixedField_eq_one_of_stabilizer_le`: **a prime of the fixed
  field of a normal subgroup absorbing the decomposition group modulo inertia has residue degree
  one.**
* `InverseGalois.CFT.isSplitInertia_fixedField` and
  `InverseGalois.CFT.isSplitInertia_fixedField_ker`: **the fixed field has split inertia** as soon
  as every decomposition group is absorbed, respectively as soon as a homomorphism has the same
  image on every decomposition group as on the corresponding inertia subgroup.

## Tags

inertia subgroup, fixed field, ramified prime, residue degree, Galois number field
-/

open NumberField InverseGalois.NumberTheory

open scoped Pointwise

namespace InverseGalois.CFT

attribute [local instance] Ideal.Quotient.field

variable {N : Type*} [Field N] [NumberField N] [IsGalois ℚ N] {p : ℕ}

/-- **A rational prime all of whose inertia subgroups lie in a subgroup is unramified in the fixed
field of that subgroup.**  A prime of the fixed field above `p` is the prime below some prime `P` of
`𝓞 N`, and the ramification index of `P` over the fixed field already accounts for the whole inertia
subgroup of `P`, leaving nothing for the layer below. -/
theorem notMem_ramifiedSet_fixedField (H : Subgroup Gal(N/ℚ)) (hp : p.Prime)
    (h : ∀ P : Ideal (𝓞 N), P.IsPrime → P.LiesOver (Ideal.span {(p : ℤ)}) →
      Ideal.inertia Gal(N/ℚ) P ≤ H) :
    p ∉ ramifiedSet ↥(IntermediateField.fixedField H) := by
  haveI : Fact p.Prime := ⟨hp⟩
  set E : IntermediateField ℚ N := IntermediateField.fixedField H with hE
  haveI : NumberField ↥E := ⟨⟩
  rintro ⟨-, Q, ⟨hQprime, hQover⟩, hQe⟩
  haveI := hQprime
  haveI := hQover
  have hQbot : Q ≠ ⊥ := ne_bot_of_liesOver p Q
  obtain ⟨⟨P, hPp, hPo⟩⟩ := Q.nonempty_primesOver (S := 𝓞 N)
  haveI := hPp
  haveI := hPo
  have hQeq : Q = P.under (𝓞 ↥E) := hPo.over
  have hUbot : P.under (𝓞 ↥E) ≠ ⊥ := hQeq ▸ hQbot
  have hPbot : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hUbot P
  have hunder : (P.under (𝓞 ↥E)).under ℤ = Ideal.span {(p : ℤ)} := by
    rw [← hQeq]
    exact hQover.over.symm
  haveI : P.LiesOver (Ideal.span {(p : ℤ)}) := ⟨by rw [← hunder, Ideal.under_under]⟩
  have hunr := isUnramifiedAt_under_fixedField_of_inertia_le H P hPbot (h P hPp inferInstance)
  rw [Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := ℤ) hUbot, hunder, ← hQeq] at hunr
  exact hQe hunr

/-- **A rational prime ramifies in the fixed field of a normal subgroup exactly when the inertia
subgroup of some prime above it is not contained in that subgroup.**  The fixed field of a normal
subgroup is Galois over the rationals, so the inertia subgroup at an unramified prime restricts
trivially to it, which is to say that it fixes it pointwise. -/
theorem mem_ramifiedSet_fixedField_iff (H : Subgroup Gal(N/ℚ)) [H.Normal] (hp : p.Prime) :
    p ∈ ramifiedSet ↥(IntermediateField.fixedField H) ↔
      ∃ P : Ideal (𝓞 N), ∃ _ : P.IsPrime, ∃ _ : P.LiesOver (Ideal.span {(p : ℤ)}),
        ¬ Ideal.inertia Gal(N/ℚ) P ≤ H := by
  constructor
  · intro hmem
    by_contra hc
    push_neg at hc
    exact notMem_ramifiedSet_fixedField H hp (fun P h1 h2 => hc P h1 h2) hmem
  · rintro ⟨P, hPp, hPo, hle⟩
    haveI := hPp
    haveI := hPo
    by_contra hnot
    exact hle ((IntermediateField.fixingSubgroup_fixedField H) ▸
      inertia_le_fixingSubgroup (IntermediateField.fixedField H) hp P hnot)

/-- **A rational prime at which a homomorphism kills every inertia subgroup is unramified in the
fixed field of its kernel.** -/
theorem notMem_ramifiedSet_fixedField_ker {G : Type*} [Group G] (ψ : Gal(N/ℚ) →* G) (hp : p.Prime)
    (h : ∀ P : Ideal (𝓞 N), P.IsPrime → P.LiesOver (Ideal.span {(p : ℤ)}) →
      ∀ σ ∈ Ideal.inertia Gal(N/ℚ) P, ψ σ = 1) :
    p ∉ ramifiedSet ↥(IntermediateField.fixedField ψ.ker) :=
  notMem_ramifiedSet_fixedField ψ.ker hp fun P h1 h2 σ hσ => MonoidHom.mem_ker.mpr (h P h1 h2 σ hσ)

section Conjugate

/-- **A normal subgroup containing the inertia subgroup of one prime above `p` contains them all.**
The Galois group permutes the primes above `p` transitively, and conjugation carries the inertia
subgroup of a prime to that of its image. -/
theorem forall_inertia_le_of_inertia_le (H : Subgroup Gal(N/ℚ)) [hH : H.Normal]
    (P : Ideal (𝓞 N)) [P.IsPrime] (hP : P.LiesOver (Ideal.span {(p : ℤ)}))
    (hle : Ideal.inertia Gal(N/ℚ) P ≤ H) (Q : Ideal (𝓞 N)) [Q.IsPrime]
    (hQ : Q.LiesOver (Ideal.span {(p : ℤ)})) :
    Ideal.inertia Gal(N/ℚ) Q ≤ H := by
  haveI := hP
  haveI := hQ
  obtain ⟨σ, hσ⟩ := Ideal.exists_smul_eq_of_isGaloisGroup (Ideal.span {(p : ℤ)}) P Q Gal(N/ℚ)
  rw [← hσ, inertia_smul]
  rintro - ⟨ρ, hρ, rfl⟩
  exact hH.conj_mem ρ (hle hρ) σ

/-- **A rational prime one of whose inertia subgroups lies in a normal subgroup is unramified in the
fixed field of that subgroup.** -/
theorem notMem_ramifiedSet_fixedField_of_inertia_le (H : Subgroup Gal(N/ℚ)) [H.Normal]
    (hp : p.Prime) (P : Ideal (𝓞 N)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})]
    (hle : Ideal.inertia Gal(N/ℚ) P ≤ H) :
    p ∉ ramifiedSet ↥(IntermediateField.fixedField H) := by
  refine notMem_ramifiedSet_fixedField H hp fun Q h1 h2 => ?_
  haveI := h1
  exact forall_inertia_le_of_inertia_le H P inferInstance hle Q h2

/-- **A rational prime at which a homomorphism kills the inertia subgroup of one prime above it is
unramified in the fixed field of the kernel.** -/
theorem notMem_ramifiedSet_fixedField_ker_of_inertia {G : Type*} [Group G] (ψ : Gal(N/ℚ) →* G)
    (hp : p.Prime) (P : Ideal (𝓞 N)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})]
    (h : ∀ σ ∈ Ideal.inertia Gal(N/ℚ) P, ψ σ = 1) :
    p ∉ ramifiedSet ↥(IntermediateField.fixedField ψ.ker) :=
  notMem_ramifiedSet_fixedField_of_inertia_le ψ.ker hp P fun σ hσ => MonoidHom.mem_ker.mpr (h σ hσ)

end Conjugate

section GroupTheory

variable {G G' : Type*} [Group G] [Group G']

/-- **The two ways of cutting one subgroup down by another give subgroups of the same order.** -/
theorem card_subgroupOf_comm (H K : Subgroup G) :
    Nat.card ↥(H.subgroupOf K) = Nat.card ↥(K.subgroupOf H) := by
  rw [← Subgroup.inf_subgroupOf_right H K, ← Subgroup.inf_subgroupOf_right K H,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe (inf_le_right : H ⊓ K ≤ K)).toEquiv,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe (inf_le_right : K ⊓ H ≤ H)).toEquiv, inf_comm]

/-- **A subgroup whose image is contained in the image of another lies in that other one together
with the kernel.** -/
theorem le_sup_ker_of_map_le {ψ : G →* G'} {K I : Subgroup G} (h : K.map ψ ≤ I.map ψ) :
    K ≤ I ⊔ ψ.ker := by
  intro σ hσ
  obtain ⟨τ, hτ, hτσ⟩ := h (Subgroup.mem_map_of_mem ψ hσ)
  have hmem : τ⁻¹ * σ ∈ ψ.ker := by
    rw [MonoidHom.mem_ker, map_mul, map_inv, hτσ, inv_mul_cancel]
  have := Subgroup.mul_mem (I ⊔ ψ.ker) (Subgroup.mem_sup_left hτ) (Subgroup.mem_sup_right hmem)
  rwa [mul_inv_cancel_left] at this

end GroupTheory

section SplitInertia

omit [IsGalois ℚ N] in
/-- The decomposition subgroup of `P` computed inside a subgroup `H` of `Gal(N/ℚ)` is the
decomposition subgroup of `P` intersected with `H`. -/
theorem stabilizer_subgroupOf (H : Subgroup Gal(N/ℚ)) (P : Ideal (𝓞 N)) :
    MulAction.stabilizer H P = (MulAction.stabilizer Gal(N/ℚ) P).subgroupOf H :=
  rfl

omit [IsGalois ℚ N] in
/-- **Cross-multiplying the decomposition groups against the inertia subgroups**, upstairs and
inside a normal subgroup absorbing the decomposition group modulo inertia.  Both sides are the
common relative index of the subgroup, multiplied by the two intersections. -/
theorem card_stabilizer_mul_card_inertia_subgroup (H : Subgroup Gal(N/ℚ)) [H.Normal]
    (P : Ideal (𝓞 N))
    (hle : MulAction.stabilizer Gal(N/ℚ) P ≤ Ideal.inertia Gal(N/ℚ) P ⊔ H) :
    Nat.card (MulAction.stabilizer Gal(N/ℚ) P) * Nat.card (Ideal.inertia H P) =
      Nat.card (Ideal.inertia Gal(N/ℚ) P) * Nat.card (MulAction.stabilizer H P) := by
  set D := MulAction.stabilizer Gal(N/ℚ) P with hD
  set I := Ideal.inertia Gal(N/ℚ) P with hI
  have hne : ∀ X : Subgroup Gal(N/ℚ), H.relIndex X ≠ 0 := fun _ =>
    Subgroup.index_ne_zero_of_finite
  have hrel : H.relIndex D = H.relIndex I := by
    refine le_antisymm ?_
      (Subgroup.relIndex_le_of_le_right (Ideal.inertia_le_stabilizer (M := Gal(N/ℚ)) P) (hne D))
    calc H.relIndex D ≤ H.relIndex (I ⊔ H) := Subgroup.relIndex_le_of_le_right hle (hne _)
      _ = H.relIndex I := Subgroup.relIndex_sup_right I H
  have hcD : Nat.card ↥(H.subgroupOf D) * H.relIndex D = Nat.card D := Subgroup.card_mul_index _
  have hcI : Nat.card ↥(H.subgroupOf I) * H.relIndex I = Nat.card I := Subgroup.card_mul_index _
  rw [inertia_subgroupOf H P, stabilizer_subgroupOf H P, ← card_subgroupOf_comm H I,
    ← card_subgroupOf_comm H D, ← hcD, ← hcI, hrel]
  ring

set_option synthInstance.maxHeartbeats 400000 in
/-- **A prime of the fixed field of a normal subgroup absorbing the decomposition group modulo
inertia has residue degree one.**  The orders of the two decomposition groups are the orders of
the two inertia subgroups times the two residue degrees, the residue degree upstairs is the
product of the two in the tower, and cross-multiplying the four orders cancels everything but the
residue degree of the prime below. -/
theorem inertiaDeg_under_fixedPoints_eq_one_of_stabilizer_le (H : Subgroup Gal(N/ℚ)) [H.Normal]
    (hp : p.Prime) (P : Ideal (𝓞 N)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})]
    (hle : MulAction.stabilizer Gal(N/ℚ) P ≤ Ideal.inertia Gal(N/ℚ) P ⊔ H) :
    (Ideal.span {(p : ℤ)}).inertiaDeg
      (P.under (𝓞 ↥(FixedPoints.intermediateField (F := ℚ) (E := N) H))) = 1 := by
  haveI : Fact p.Prime := ⟨hp⟩
  set E : IntermediateField ℚ N := FixedPoints.intermediateField H with hE
  have hPbot : P ≠ ⊥ := ne_bot_of_liesOver p P
  haveI : P.IsMaximal := isMaximal_of_ne_bot P hPbot
  have hQbot : P.under (𝓞 E) ≠ ⊥ := Ideal.under_ne_bot (𝓞 E) hPbot
  haveI : (P.under (𝓞 E)).IsMaximal := Ideal.IsPrime.isMaximal inferInstance hQbot
  haveI : Finite (𝓞 N ⧸ P) := finite_quotient_of_ne_bot P hPbot
  haveI : Finite (𝓞 E ⧸ P.under (𝓞 E)) :=
    .of_injective _ (Ideal.algebraMap_quotient_injective (R := 𝓞 E) (A := 𝓞 N) (I := P))
  haveI : Algebra.IsSeparable (𝓞 E ⧸ P.under (𝓞 E)) (𝓞 N ⧸ P) := inferInstance
  haveI : (P.under (𝓞 E)).LiesOver (Ideal.span {(p : ℤ)}) :=
    ⟨by rw [Ideal.under_under]; exact Ideal.LiesOver.over⟩
  haveI := isMaximal_span_prime hp
  have hG : Nat.card (MulAction.stabilizer Gal(N/ℚ) P) =
      Nat.card (Ideal.inertia Gal(N/ℚ) P) * (Ideal.span {(p : ℤ)}).inertiaDeg P := by
    rw [card_stabilizer_eq_mul N hp P, card_inertia_eq_ramificationIdx_span hp P]
  have hH : Nat.card (MulAction.stabilizer H P) =
      Nat.card (Ideal.inertia H P) * (P.under (𝓞 E)).inertiaDeg P := by
    rw [Ideal.inertiaDeg_algebraMap]
    exact Ideal.card_stabilizer_eq_card_inertia_mul_finrank (G := H) (P.under (𝓞 E)) P
  have htower : (Ideal.span {(p : ℤ)}).inertiaDeg P =
      (Ideal.span {(p : ℤ)}).inertiaDeg (P.under (𝓞 E)) * (P.under (𝓞 E)).inertiaDeg P :=
    Ideal.inertiaDeg_algebra_tower (Ideal.span {(p : ℤ)}) (P.under (𝓞 E)) P
  have hkey := card_stabilizer_mul_card_inertia_subgroup H P hle
  rw [hG, hH, htower] at hkey
  have h3 : 0 < (P.under (𝓞 E)).inertiaDeg P := Ideal.inertiaDeg_pos _ _
  set a := Nat.card (Ideal.inertia Gal(N/ℚ) P) with ha
  set b := Nat.card (Ideal.inertia H P) with hb
  set f := (P.under (𝓞 E)).inertiaDeg P with hf
  set g := (Ideal.span {(p : ℤ)}).inertiaDeg (P.under (𝓞 E)) with hg
  have hX : 0 < a * b * f := Nat.mul_pos (Nat.mul_pos Nat.card_pos Nat.card_pos) h3
  refine Nat.eq_of_mul_eq_mul_left hX ?_
  calc a * b * f * g = a * (g * f) * b := by ring
    _ = a * (b * f) := hkey
    _ = a * b * f * 1 := by ring

/-- **A prime of the fixed field of a normal subgroup absorbing the decomposition group modulo
inertia has residue degree one**, stated for the fixed field in its `IntermediateField` spelling.
-/
theorem inertiaDeg_under_fixedField_eq_one_of_stabilizer_le (H : Subgroup Gal(N/ℚ)) [H.Normal]
    (hp : p.Prime) (P : Ideal (𝓞 N)) [P.IsPrime] [P.LiesOver (Ideal.span {(p : ℤ)})]
    (hle : MulAction.stabilizer Gal(N/ℚ) P ≤ Ideal.inertia Gal(N/ℚ) P ⊔ H) :
    (Ideal.span {(p : ℤ)}).inertiaDeg (P.under (𝓞 ↥(IntermediateField.fixedField H))) = 1 :=
  inertiaDeg_under_fixedPoints_eq_one_of_stabilizer_le H hp P hle

/-- **The fixed field of a normal subgroup absorbing every decomposition group modulo inertia has
split inertia.**  Every prime of the fixed field is the prime below a prime of `𝓞 N`, so the
residue-degree computation applies to all of them. -/
theorem isSplitInertia_fixedField (H : Subgroup Gal(N/ℚ)) [H.Normal]
    (h : ∀ q : ℕ, q.Prime → ∀ P : Ideal (𝓞 N), P.IsPrime → P.LiesOver (Ideal.span {(q : ℤ)}) →
      MulAction.stabilizer Gal(N/ℚ) P ≤ Ideal.inertia Gal(N/ℚ) P ⊔ H) :
    IsSplitInertia ↥(IntermediateField.fixedField H) := by
  set E : IntermediateField ℚ N := IntermediateField.fixedField H with hE
  haveI : NumberField ↥E := ⟨⟩
  intro q hq Q hQprime hQover
  haveI : Fact q.Prime := ⟨hq.1⟩
  haveI := hQprime
  haveI := hQover
  obtain ⟨⟨P, hPp, hPo⟩⟩ := Q.nonempty_primesOver (S := 𝓞 N)
  haveI := hPp
  haveI := hPo
  have hQeq : Q = P.under (𝓞 ↥E) := hPo.over
  have hunder : (P.under (𝓞 ↥E)).under ℤ = Ideal.span {(q : ℤ)} := by
    rw [← hQeq]; exact hQover.over.symm
  haveI : P.LiesOver (Ideal.span {(q : ℤ)}) := ⟨by rw [← hunder, Ideal.under_under]⟩
  rw [hQeq]
  exact inertiaDeg_under_fixedField_eq_one_of_stabilizer_le H hq.1 P
    (h q hq.1 P hPp inferInstance)

/-- **The fixed field of the kernel of a homomorphism which sees no more of any decomposition group
than of the corresponding inertia subgroup has split inertia.** -/
theorem isSplitInertia_fixedField_ker {G : Type*} [Group G] (ψ : Gal(N/ℚ) →* G)
    (h : ∀ q : ℕ, q.Prime → ∀ P : Ideal (𝓞 N), P.IsPrime → P.LiesOver (Ideal.span {(q : ℤ)}) →
      (MulAction.stabilizer Gal(N/ℚ) P).map ψ ≤ (Ideal.inertia Gal(N/ℚ) P).map ψ) :
    IsSplitInertia ↥(IntermediateField.fixedField ψ.ker) :=
  isSplitInertia_fixedField ψ.ker fun q hq P h1 h2 => le_sup_ker_of_map_le (h q hq P h1 h2)

end SplitInertia

end InverseGalois.CFT
