/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.InertiaRestrict
import InverseGalois.CFT.TameCharacter

/-!
# Inertia in an infinite extension is cyclic modulo an open subgroup and a wild part

The inertia subgroup at a prime of an infinite extension is not cyclic, and the characters it
carries are not the characters of a cyclic group; but they are once one remembers that a character
is trivial on an open subgroup.  Read at a finite level over the rationals large enough for the
open subgroup, inertia has a tame character with values in the units of a residue field, a cyclic
group, and the kernel of that character consists of elements of order a power of the residue
characteristic.

That is the shape of the statement here: at a prime away from an exponent `n`, there is one
element of inertia and one exponent `m` prime to `n` such that every element of inertia agrees
with a power of that element after being raised to the power `m` and read modulo the open
subgroup.  A character of inertia with values in the residues modulo `n`, trivial on the open
subgroup, is therefore determined by its value at that one element: the exponent `m` is invertible
modulo `n`.

## Main results

* `InverseGalois.CFT.exists_forall_mul_pow_inv_mem_ker`: a homomorphism to a finite cyclic group
  is accounted for by a single element.
* `InverseGalois.CFT.exists_rationalLevel_forall_smul_eq`: every open subgroup contains the
  automorphisms which fix a suitable finite Galois extension of the rationals pointwise.
* `InverseGalois.CFT.exists_mem_inertia_forall_pow_mem`: **the inertia subgroup at a prime away
  from an exponent is generated by one element, modulo an open subgroup and modulo raising to a
  power prime to the exponent.**

## Tags

inertia subgroup, tame character, Krull topology, cyclic group, number field
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

/-! ### A homomorphism to a finite cyclic group -/

section Cyclic

/-- **A homomorphism to a finite cyclic group is accounted for by a single element**: some element
of the source has powers hitting every value.  The image is a subgroup of a cyclic group, hence
cyclic, and a generator of the image is a value. -/
theorem exists_forall_mul_pow_inv_mem_ker {G C : Type*} [Group G] [Group C] [Finite C] [IsCyclic C]
    (T : G →* C) : ∃ g : G, ∀ x : G, ∃ j : ℕ, T (x * (g ^ j)⁻¹) = 1 := by
  obtain ⟨c, hc⟩ := IsCyclic.exists_generator (α := T.range)
  obtain ⟨g, hg⟩ := c.2
  refine ⟨g, fun x => ?_⟩
  have hx : (⟨T x, ⟨x, rfl⟩⟩ : T.range) ∈ Subgroup.zpowers c := hc _
  obtain ⟨j, hj⟩ := mem_powers_iff_mem_zpowers.2 hx
  refine ⟨j, ?_⟩
  have hval : (c : C) ^ j = T x := congrArg Subtype.val hj
  rw [map_mul, _root_.map_inv, map_pow, hg, hval, mul_inv_cancel]

end Cyclic

/-! ### A finite Galois level over the rationals inside an open subgroup -/

section Level

/-- An algebraically closed extension of a number field is an algebraic closure of the
rationals. -/
theorem isAlgClosure_rat_of_isAlgClosed (K Ω : Type) [Field K] [NumberField K] [Field Ω]
    [Algebra K Ω] [Algebra.IsAlgebraic K Ω] [IsAlgClosed Ω] [CharZero Ω] : IsAlgClosure ℚ Ω := by
  haveI : Algebra.IsAlgebraic ℚ Ω := Algebra.IsAlgebraic.trans ℚ K Ω
  exact ⟨inferInstance, inferInstance⟩

variable {K Ω : Type} [Field K] [NumberField K] [Field Ω] [Algebra K Ω] [IsGalois K Ω]
  [IsAlgClosed Ω] [CharZero Ω]

/-- **Every open subgroup contains the automorphisms which fix a suitable finite Galois extension
of the rationals pointwise.**  An open subgroup contains the automorphisms fixing a finite level
over the base field; that level is finite over the rationals as well, and its normal closure is a
finite Galois extension of the rationals containing it. -/
theorem exists_rationalLevel_forall_smul_eq {N : Subgroup Gal(Ω/K)}
    (hN : IsOpen (N : Set Gal(Ω/K))) :
    ∃ M : IntermediateField ℚ Ω, ∃ _ : FiniteDimensional ℚ ↥M, ∃ _ : IsGalois ℚ ↥M,
      ∀ σ : Gal(Ω/K), (∀ x : ↥M, σ (x : Ω) = (x : Ω)) → σ ∈ N := by
  haveI := isAlgClosure_rat_of_isAlgClosed K Ω
  haveI : Normal ℚ Ω := inferInstance
  obtain ⟨E, hE, hEN⟩ := (krullTopology_mem_nhds_one_iff K Ω (N : Set Gal(Ω/K))).1
    (hN.mem_nhds N.one_mem)
  haveI := hE
  haveI : FiniteDimensional ℚ ↥E := Module.Finite.trans (R := ℚ) K ↥E
  haveI : FiniteDimensional ℚ ↥(E.restrictScalars ℚ) := ‹_›
  refine ⟨IntermediateField.normalClosure ℚ ↥(E.restrictScalars ℚ) Ω, inferInstance, ⟨⟩,
    fun σ hσ => hEN ?_⟩
  refine (IntermediateField.mem_fixingSubgroup_iff _ _).2 fun x hx => ?_
  exact hσ ⟨x, IntermediateField.le_normalClosure (E.restrictScalars ℚ) hx⟩

end Level

/-! ### Inertia modulo an open subgroup -/

section Inertia

variable {K Ω : Type} [Field K] [NumberField K] [Field Ω] [Algebra K Ω] [IsGalois K Ω]
  [IsAlgClosed Ω]

set_option synthInstance.maxHeartbeats 800000 in
set_option maxHeartbeats 1600000 in
/-- **The inertia subgroup at a prime away from an exponent is generated by one element, modulo an
open subgroup and modulo raising to a power prime to the exponent.**

At a finite Galois level over the rationals inside the open subgroup, inertia at the place below
carries the tame character, whose values lie in the units of a finite residue field and so form a
cyclic group: one element of inertia accounts for every value.  What the tame character does not
see has order a power of the residue characteristic, which is prime to the exponent because the
prime is; raising to the power of the characteristic contained in the order of the inertia group
of the level therefore lands in the open subgroup. -/
theorem exists_mem_inertia_forall_pow_mem {n : ℕ} (P : Ideal (𝓞 Ω)) [P.IsPrime] (hP : P ≠ ⊥)
    (hn : (n : 𝓞 Ω) ∉ P) {N : Subgroup Gal(Ω/K)} (hN : IsOpen (N : Set Gal(Ω/K))) :
    ∃ (g : ↥(Ideal.inertia Gal(Ω/K) P)) (m : ℕ), Nat.Coprime m n ∧
      ∀ x : ↥(Ideal.inertia Gal(Ω/K) P), ∃ j : ℕ,
        ((((x * (g ^ j)⁻¹) ^ m : ↥(Ideal.inertia Gal(Ω/K) P)) : Gal(Ω/K)) ∈ N) := by
  haveI : CharZero Ω := charZero_of_injective_algebraMap (algebraMap K Ω).injective
  obtain ⟨M, hMfin, hMgal, hMN⟩ := exists_rationalLevel_forall_smul_eq (K := K) hN
  haveI := hMfin
  haveI := hMgal
  haveI : NumberField ↥M := NumberField.of_module_finite ℚ ↥M
  set w : Ideal (𝓞 ↥M) := Ideal.under (𝓞 ↥M) P with hwdef
  haveI : w.IsPrime := Ideal.IsPrime.under _ P
  have hwbot : w ≠ ⊥ := Ideal.under_ne_bot (𝓞 ↥M) hP
  haveI := isMaximal_of_ne_bot w hwbot
  haveI := finite_quotient_of_ne_bot w hwbot
  obtain ⟨π, hπ⟩ := exists_isUniformizer hwbot
  -- restriction to the level, as a homomorphism of Galois groups
  set rs : Gal(Ω/K) →* Gal(↥M/ℚ) :=
    (AlgEquiv.restrictNormalHom ↥M).comp
      ({ toFun := fun σ => σ.restrictScalars ℚ, map_one' := rfl,
         map_mul' := fun _ _ => rfl } : Gal(Ω/K) →* Gal(Ω/ℚ)) with hrsdef
  have hrsapp : ∀ σ : Gal(Ω/K), rs σ = (σ.restrictScalars ℚ).restrictNormal ↥M := fun _ => rfl
  have hrsI : ∀ x : ↥(Ideal.inertia Gal(Ω/K) P),
      rs ((Ideal.inertia Gal(Ω/K) P).subtype x) ∈ Ideal.inertia Gal(↥M/ℚ) w := by
    intro x
    rw [hrsapp]
    exact restrictNormal_mem_inertia M P fun y => x.2 y
  set ρ : ↥(Ideal.inertia Gal(Ω/K) P) →* ↥(Ideal.inertia Gal(↥M/ℚ) w) :=
    MonoidHom.codRestrict (rs.comp (Ideal.inertia Gal(Ω/K) P).subtype) _ hrsI with hρdef
  -- the residue characteristic and the order of inertia at the level
  set p := ringChar (𝓞 ↥M ⧸ w) with hpdef
  haveI : CharP (𝓞 ↥M ⧸ w) p := ringChar.charP _
  have hpprime : p.Prime := CharP.char_is_prime (𝓞 ↥M ⧸ w) p
  set c := Nat.card ↥(Ideal.inertia Gal(↥M/ℚ) w) with hcdef
  have hc0 : c ≠ 0 := Nat.card_pos.ne'
  have hpn : ¬ p ∣ n := by
    intro hdvd
    refine hn ?_
    have h0 : ((n : 𝓞 ↥M) : 𝓞 ↥M ⧸ w) = 0 := by
      rw [map_natCast]
      exact (CharP.cast_eq_zero_iff (𝓞 ↥M ⧸ w) p n).2 hdvd
    have hmem : (n : 𝓞 ↥M) ∈ w := Ideal.Quotient.eq_zero_iff_mem.1 h0
    have := Ideal.mem_comap.1 (hwdef ▸ hmem)
    rwa [map_natCast] at this
  obtain ⟨g, hg⟩ := exists_forall_mul_pow_inv_mem_ker ((tameChar hπ).comp ρ)
  refine ⟨g, p ^ c.factorization p,
    Nat.Coprime.pow_left _ ((Nat.Prime.coprime_iff_not_dvd hpprime).2 hpn), fun x => ?_⟩
  obtain ⟨j, hj⟩ := hg x
  refine ⟨j, ?_⟩
  set y := x * (g ^ j)⁻¹ with hydef
  obtain ⟨a, ha⟩ := exists_orderOf_eq_ringChar_pow hπ hj
  rw [Subgroup.orderOf_coe] at ha
  have hdvdc : p ^ a ∣ c := by
    rw [← ha]
    exact orderOf_dvd_natCard _
  have hdvdm : p ^ a ∣ p ^ c.factorization p :=
    (Nat.Prime.pow_dvd_iff_dvd_ordProj hpprime hc0).1 hdvdc
  have hρy : ρ (y ^ p ^ c.factorization p) = 1 := by
    rw [map_pow]
    refine orderOf_dvd_iff_pow_eq_one.1 ?_
    rw [ha]
    exact hdvdm
  refine hMN _ fun t => ?_
  have h1 : rs ((y ^ p ^ c.factorization p : ↥(Ideal.inertia Gal(Ω/K) P)) : Gal(Ω/K)) = 1 :=
    congrArg Subtype.val hρy
  have hcom := AlgEquiv.restrictNormal_commutes
    ((((y ^ p ^ c.factorization p : ↥(Ideal.inertia Gal(Ω/K) P)) :
      Gal(Ω/K)).restrictScalars ℚ)) (↥M) t
  rw [show (((y ^ p ^ c.factorization p : ↥(Ideal.inertia Gal(Ω/K) P)) :
    Gal(Ω/K)).restrictScalars ℚ).restrictNormal ↥M = 1 from h1, AlgEquiv.one_apply] at hcom
  exact hcom.symm

end Inertia

end InverseGalois.CFT
