import Mathlib
import InverseGalois.CFT.CyclotomicCompositum
import InverseGalois.CFT.InertiaAbelian
import InverseGalois.CFT.TameCharacter
import InverseGalois.CFT.TameRamification
import InverseGalois.CFT.UnramifiedCompositum

/-!
# Kronecker–Weber for tamely ramified abelian extensions

An abelian number field `L` which is tamely ramified embeds into a cyclotomic field, namely into
`ℚ(ζ_m)` for `m` the product of the primes that ramify in `L`.

The proof is the classical counting argument, carried out entirely with inertia subgroups of the
Galois group over `ℚ` rather than with completions.  Write `M` for the compositum of `L` with
`ℚ(ζ_m)` inside an algebraic closure of `ℚ`.  Then

* `M` is again abelian and tamely ramified, and no prime outside the prime factors of `m` ramifies
  in it;
* the Galois group of `M` is generated by its inertia subgroups, and a group generated by normal
  subgroups has order at most the product of their orders;
* at a ramified prime `p` the tame character embeds the inertia subgroup into the units of the
  residue field, so its order divides `p - 1`.

Multiplying these bounds gives `[M : ℚ] ≤ ∏ (p - 1) = φ m`, because `m` is squarefree.  Since `M`
contains `ℚ(ζ_m)`, whose degree is already `φ m`, the two fields coincide, and `L ⊆ M = ℚ(ζ_m)`.

The tameness hypothesis is what restricts this to the statement below rather than the full
Kronecker–Weber theorem: the wild part of the ramification is not controlled by the tame
character.

## Main definitions

* `InverseGalois.CFT.tameConductor`: the product of the primes ramifying in a number field.

## Main results

* `InverseGalois.CFT.squarefree_tameConductor`: the tame conductor is squarefree.
* `InverseGalois.CFT.ramifiedSet_cycCompositum`: the primes ramifying in the compositum are those
  ramifying in one of the two factors.
* `InverseGalois.CFT.isTamelyRamified_cycCompositum`: the compositum of a tamely ramified field
  with a squarefree cyclotomic field is tamely ramified.
* `InverseGalois.CFT.nonempty_algHom_cyclotomicField_of_inertia_le`: the general criterion, which
  reduces an embedding of `L` into `ℚ(ζₙ)` to a bound on inertia at each prime dividing `n`.
* `InverseGalois.CFT.finrank_cycCompositum_le_totient`: the degree bound `[M : ℚ] ≤ φ n` in the
  tame case.
* `InverseGalois.CFT.exists_algHom_cyclotomicField_of_tame`: **tame Kronecker–Weber**, a tamely
  ramified abelian number field embeds into a cyclotomic field.
-/

open NumberField InverseGalois.NumberTheory

namespace InverseGalois.CFT

section Conductor

/-- A product of distinct primes is squarefree. -/
theorem squarefree_prod_of_prime {s : Finset ℕ} (hs : ∀ p ∈ s, p.Prime) :
    Squarefree (∏ p ∈ s, p) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
      have hap : a.Prime := hs a (Finset.mem_insert_self a s)
      have hsub : ∀ p ∈ s, p.Prime := fun p hp => hs p (Finset.mem_insert_of_mem hp)
      rw [Finset.prod_insert ha]
      refine (Nat.squarefree_mul_iff).mpr ⟨?_, hap.squarefree, ih hsub⟩
      refine Nat.Coprime.prod_right fun q hq => ?_
      refine (Nat.coprime_primes hap (hsub q hq)).mpr ?_
      rintro rfl
      exact ha hq

variable (L : Type*) [Field L] [NumberField L]

/-- The **tame conductor** of a number field: the product of the rational primes that ramify in
it.  Only finitely many primes ramify, so this is a well-defined natural number. -/
noncomputable def tameConductor : ℕ := ∏ p ∈ (finite_ramifiedSet L).toFinset, p

/-- The tame conductor is squarefree, being a product of distinct primes. -/
theorem squarefree_tameConductor : Squarefree (tameConductor L) :=
  squarefree_prod_of_prime fun p hp => by
    simpa using ((Set.Finite.mem_toFinset _).mp hp).1

/-- The tame conductor is nonzero. -/
theorem tameConductor_ne_zero : tameConductor L ≠ 0 :=
  (squarefree_tameConductor L).ne_zero

/-- The prime factors of the tame conductor are exactly the ramified primes. -/
theorem primeFactors_tameConductor :
    (tameConductor L).primeFactors = (finite_ramifiedSet L).toFinset :=
  Nat.primeFactors_prod fun _p hp => ((Set.Finite.mem_toFinset _).mp hp).1

/-- Every ramified prime divides the tame conductor. -/
theorem ramifiedSet_subset_primeFactors_tameConductor :
    ramifiedSet L ⊆ ↑(tameConductor L).primeFactors := by
  rw [primeFactors_tameConductor]
  intro p hp
  simpa using hp

end Conductor

/-- For a squarefree `n`, Euler's totient is the product of `p - 1` over the primes dividing
`n`. -/
theorem prod_sub_one_eq_totient {n : ℕ} (hn : Squarefree n) :
    ∏ p ∈ n.primeFactors, (p - 1) = Nat.totient n := by
  rw [← prod_totient_pow_factorization hn.ne_zero]
  refine Finset.prod_congr rfl fun p hp => ?_
  have hpp : p.Prime := Nat.prime_of_mem_primeFactors hp
  have h1 : n.factorization p = 1 := by
    have hle := hn.natFactorization_le_one p
    have hpos : 0 < n.factorization p :=
      hpp.factorization_pos_of_dvd hn.ne_zero (Nat.dvd_of_mem_primeFactors hp)
    omega
  rw [h1, pow_one, Nat.totient_prime hpp]

section Group

/-- Commutativity is inherited by a subgroup, or more generally along any injective group
homomorphism. -/
theorem isMulCommutative_of_injective {G H : Type*} [Group G] [Group H] [IsMulCommutative H]
    (f : G →* H) (hf : Function.Injective f) : IsMulCommutative G :=
  ⟨⟨fun a b => hf (by rw [map_mul, map_mul, mul_comm])⟩⟩

/-- A product of two commutative groups is commutative. -/
theorem isMulCommutative_prod (G H : Type*) [Group G] [Group H] [IsMulCommutative G]
    [IsMulCommutative H] : IsMulCommutative (G × H) :=
  ⟨⟨fun a b => mul_comm a b⟩⟩

end Group

section Compositum

variable (L : Type*) [Field L] [NumberField L] (n : ℕ) [NeZero n]

/-- Only the primes dividing `n` ramify in an `n`-th cyclotomic field. -/
theorem ramifiedSet_subset_primeFactors (K : Type*) [Field K] [NumberField K]
    [IsCyclotomicExtension {n} ℚ K] : ramifiedSet K ⊆ ↑n.primeFactors := by
  rintro p ⟨hp, P, ⟨hPprime, hPover⟩, hPe⟩
  haveI : Fact p.Prime := ⟨hp⟩
  haveI := hPprime
  haveI := hPover
  haveI : IsGalois ℚ K := IsCyclotomicExtension.isGalois {n} ℚ K
  refine Finset.mem_coe.mpr (Nat.mem_primeFactors.mpr ⟨hp, ?_, NeZero.ne n⟩)
  by_contra hpn
  have hP0 := ne_bot_of_liesOver p P
  have h1 := card_inertia_eq_one_of_not_dvd n K p P hpn
  rw [card_inertia_eq_ramificationIdx P hP0, ← hPover.over] at h1
  exact hPe h1

/-- A prime ramifies in the compositum exactly when it ramifies in one of the two factors. -/
theorem ramifiedSet_cycCompositum :
    ramifiedSet ↥(cycCompositum L n) = ramifiedSet L ∪ ramifiedSet ↥(cycSubfield n) := by
  haveI : NumberField ↥(innerL L n) := ⟨⟩
  haveI : NumberField ↥(innerCyc L n) := ⟨⟩
  have htop : ramifiedSet ↥(⊤ : IntermediateField ℚ ↥(cycCompositum L n))
      = ramifiedSet ↥(cycCompositum L n) :=
    ramifiedSet_eq_of_ringEquiv (IntermediateField.topEquiv).toRingEquiv
  rw [← htop, ← innerL_sup_innerCyc L n, ramifiedSet_sup]
  congr 1
  · exact (ramifiedSet_eq_of_ringEquiv
      ((embEquiv L).trans (innerLEquiv L n).symm).toRingEquiv).symm
  · exact ramifiedSet_eq_of_ringEquiv (innerCycEquiv L n).toRingEquiv

/-- The compositum of a tamely ramified field with a cyclotomic field of squarefree conductor is
tamely ramified. -/
theorem isTamelyRamified_cycCompositum [IsGalois ℚ L] (hn : Squarefree n)
    (htame : IsTamelyRamified L) : IsTamelyRamified ↥(cycCompositum L n) := by
  haveI : NumberField ↥(innerL L n) := ⟨⟩
  haveI : NumberField ↥(innerCyc L n) := ⟨⟩
  refine isTamelyRamified_sup (innerL L n) (innerCyc L n) (innerL_sup_innerCyc L n) ?_ ?_
  · exact isTamelyRamified_of_ringEquiv
      ((embEquiv L).trans (innerLEquiv L n).symm).toRingEquiv htame
  · exact isTamelyRamified_of_ringEquiv (innerCycEquiv L n).symm.toRingEquiv
      (isTamelyRamified_cyclotomic n _ hn)

/-- The compositum of an abelian number field with a cyclotomic field is abelian, since its Galois
group embeds into the product of the two Galois groups. -/
theorem isMulCommutative_gal_cycCompositum [IsGalois ℚ L] [IsMulCommutative Gal(L/ℚ)] :
    IsMulCommutative Gal(↥(cycCompositum L n)/ℚ) := by
  haveI : IsMulCommutative Gal(↥(embSubfield L)/ℚ) :=
    isMulCommutative_of_injective (AlgEquiv.autCongr (embEquiv L)).symm.toMonoidHom
      (AlgEquiv.autCongr (embEquiv L)).symm.injective
  haveI : IsMulCommutative Gal(↥(cycSubfield n)/ℚ) :=
    IsCyclotomicExtension.isMulCommutative {n} ℚ _
  haveI := isMulCommutative_prod Gal(↥(embSubfield L)/ℚ) Gal(↥(cycSubfield n)/ℚ)
  exact isMulCommutative_of_injective (galRestrictProd (embSubfield L) (cycSubfield n))
    (galRestrictProd_injective _ _)

end Compositum

section KroneckerWeber

variable (L : Type*) [Field L] [NumberField L] [IsGalois ℚ L] [IsMulCommutative Gal(L/ℚ)]
variable (n : ℕ) [NeZero n]

/-- **The degree bound, in general form.**  Suppose every prime ramifying in the abelian field `L`
divides `n`, and suppose that at each prime `p` the compositum of `L` with `ℚ(ζₙ)` has inertia no
larger than `ℚ(ζₙ)` already has, namely of order at most `φ (p ^ k)` for `p ^ k` the exact power of
`p` dividing `n`.  Then the compositum has degree at most `φ n`.

The Galois group of the compositum is generated by its inertia subgroups, one for each prime
dividing `n`, and a group generated by normal subgroups has order at most the product of their
orders; the product of the local bounds is `φ n`. -/
theorem finrank_cycCompositum_le_totient_of_inertia_le
    (hram : ramifiedSet L ⊆ ↑n.primeFactors)
    (hloc : ∀ p ∈ n.primeFactors, ∀ P : Ideal (𝓞 ↥(cycCompositum L n)), P.IsPrime →
      P.under ℤ = Ideal.span {(p : ℤ)} →
      Nat.card (Ideal.inertia Gal(↥(cycCompositum L n)/ℚ) P) ≤
        Nat.totient (p ^ n.factorization p)) :
    Module.finrank ℚ ↥(cycCompositum L n) ≤ Nat.totient n := by
  haveI := isMulCommutative_gal_cycCompositum L n
  rw [← prod_totient_pow_factorization (NeZero.ne n),
    ← IsGalois.card_aut_eq_finrank ℚ ↥(cycCompositum L n)]
  refine card_le_prod_of_ramifiedSet n.primeFactors _ ?_ hloc ?_
  · intro p hp
    exact Nat.totient_pos.2 (pow_pos (Nat.prime_of_mem_primeFactors hp).pos _)
  · intro p hpmem
    rw [ramifiedSet_cycCompositum L n] at hpmem
    rcases hpmem with h | h
    · exact hram h
    · exact ramifiedSet_subset_primeFactors n _ h

/-- **The embedding criterion.**  Under the local inertia bounds of
`InverseGalois.CFT.finrank_cycCompositum_le_totient_of_inertia_le`, the abelian field `L` embeds
into `ℚ(ζₙ)`.  This reduces the Kronecker–Weber theorem to a statement about inertia at a single
prime. -/
theorem nonempty_algHom_cyclotomicField_of_inertia_le
    (hram : ramifiedSet L ⊆ ↑n.primeFactors)
    (hloc : ∀ p ∈ n.primeFactors, ∀ P : Ideal (𝓞 ↥(cycCompositum L n)), P.IsPrime →
      P.under ℤ = Ideal.span {(p : ℤ)} →
      Nat.card (Ideal.inertia Gal(↥(cycCompositum L n)/ℚ) P) ≤
        Nat.totient (p ^ n.factorization p)) :
    Nonempty (L →ₐ[ℚ] CyclotomicField n ℚ) :=
  nonempty_algHom_cyclotomicField_of_finrank_le L n
    (finrank_cycCompositum_le_totient_of_inertia_le L n hram hloc)

/-- **The degree bound, tame case.**  If `L` is abelian and tamely ramified and every prime
ramifying in `L` divides the squarefree number `n`, then the compositum of `L` with the `n`-th
cyclotomic field has degree at most `φ n`: tameness bounds the order of each inertia subgroup
by `p - 1`. -/
theorem finrank_cycCompositum_le_totient (hn : Squarefree n)
    (hram : ramifiedSet L ⊆ ↑n.primeFactors) (htame : IsTamelyRamified L) :
    Module.finrank ℚ ↥(cycCompositum L n) ≤ Nat.totient n := by
  haveI := isMulCommutative_gal_cycCompositum L n
  have hcomtame := isTamelyRamified_cycCompositum L n hn htame
  refine finrank_cycCompositum_le_totient_of_inertia_le L n hram ?_
  intro p hp P hPprime hPunder
  haveI := hPprime
  have hpp := Nat.prime_of_mem_primeFactors hp
  have h1 : n.factorization p = 1 := by
    have hle := hn.natFactorization_le_one p
    have hpos : 0 < n.factorization p :=
      hpp.factorization_pos_of_dvd hn.ne_zero (Nat.dvd_of_mem_primeFactors hp)
    omega
  haveI : P.LiesOver (Ideal.span {(p : ℤ)}) := ⟨hPunder.symm⟩
  have hnd := not_dvd_card_inertia_of_tame hcomtame p hpp P
  have hd := card_inertia_dvd_sub_one_of_liesOver p hpp P hnd
  have h2 := hpp.two_le
  rw [h1, pow_one, Nat.totient_prime hpp]
  exact Nat.le_of_dvd (by omega) hd

/-- **Kronecker–Weber, tame case.**  An abelian number field in which no residue characteristic
divides a ramification index embeds into a cyclotomic field; one may take the conductor to be the
product of the ramified primes. -/
theorem exists_algHom_cyclotomicField_of_tame (htame : IsTamelyRamified L) :
    ∃ m : ℕ, m ≠ 0 ∧ Nonempty (L →ₐ[ℚ] CyclotomicField m ℚ) := by
  haveI : NeZero (tameConductor L) := ⟨tameConductor_ne_zero L⟩
  refine ⟨tameConductor L, tameConductor_ne_zero L, ?_⟩
  exact nonempty_algHom_cyclotomicField_of_finrank_le L _
    (finrank_cycCompositum_le_totient L _ (squarefree_tameConductor L)
      (ramifiedSet_subset_primeFactors_tameConductor L) htame)

end KroneckerWeber

end InverseGalois.CFT
