/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.PiDual

/-!
# Prescribing the signs of a family of square roots

Let `M / F` be a finite Galois extension, `B` an intermediate field, and `r : ι → M` a finite
family of elements whose squares lie in `F`.  Every automorphism of `M / F` multiplies each `r i`
by a sign, so it determines a vector in `ι → ZMod 2`, and this assignment is a homomorphism from
the Galois group to the additive group of such vectors.  The question answered here is which sign
patterns are attained by automorphisms that fix `B` pointwise.

The answer is the obvious necessary condition: a pattern `t` is attained as soon as `∑ i ∈ S, t i`
vanishes for every subset `S` whose associated product `∏ i ∈ S, r i` already lies in `B`.  Indeed
the attained patterns form a subspace of the `ZMod 2`-vector space `ι → ZMod 2`, the linear
functionals on that space are exactly the subset sums, and the functionals annihilating the
subspace are exactly those coming from a subset with `∏ i ∈ S, r i` fixed by every automorphism
fixing `B`, that is, lying in `B`.  So the statement is the double annihilator theorem.

This replaces the classical route through multiquadratic Kummer theory: no degree count and no
explicit description of the field generated by the `r i` is needed, only the subsets whose product
lands in `B`.

The same sign calculus answers a second question: how a square root lying in a compositum of two
Galois extensions with trivial intersection is distributed between the two factors.  The Galois
group of the compositum is the product of the two Galois groups, so the sign character of the
square root splits into a summand vanishing on each factor's fixing subgroup, and realizing each
summand by a square root of its own exhibits the given one as a product of a square root from each
factor.

## Main results

* `InverseGalois.CFT.mem_of_forall_sum_eq_zero`: a vector lies in a subspace of `ι → ZMod 2` as
  soon as every subset sum annihilating the subspace annihilates the vector.
* `InverseGalois.CFT.exists_eq_of_forall_sum_eq_zero`: the same for the image of a homomorphism
  from a group to `ι → ZMod 2`.
* `InverseGalois.CFT.exists_fixingSubgroup_map_eq_signZMod_mul`: an automorphism fixing `B`
  pointwise and realizing a prescribed sign pattern on the square roots.
* `InverseGalois.CFT.exists_signChar_of_sq_mem`: the sign character attached to an element whose
  square lies in the base field.
* `InverseGalois.CFT.exists_sq_mem_forall_map_eq_signZMod`: every homomorphism from the Galois
  group to `ZMod 2` is the sign character of such an element.
* `InverseGalois.CFT.exists_mul_eq_of_sq_mem_sup`: **an element of a compositum of two Galois
  subextensions meeting in the base field whose square lies in the base field is the product of one
  such element from each factor.**
-/

namespace InverseGalois.CFT

/-! ### Signs -/

/-- The sign attached to an element of `ZMod 2`: `1` for `0` and `-1` for `1`. -/
def signZMod (R : Type*) [Ring R] (z : ZMod 2) : R := if z = 0 then 1 else -1

theorem eq_zero_or_one_zmod_two (z : ZMod 2) : z = 0 ∨ z = 1 := by revert z; decide

@[simp] theorem signZMod_zero (R : Type*) [Ring R] : signZMod R 0 = 1 := if_pos rfl

@[simp] theorem signZMod_one (R : Type*) [Ring R] : signZMod R 1 = -1 := if_neg (by decide)

/-- The sign is invertible, hence nonzero in a nontrivial ring. -/
theorem signZMod_ne_zero {R : Type*} [Ring R] [Nontrivial R] (z : ZMod 2) :
    signZMod R z ≠ 0 := by
  rcases eq_zero_or_one_zmod_two z with rfl | rfl <;> simp

/-- The sign is a homomorphism from the additive group `ZMod 2` to the units of a ring. -/
theorem signZMod_add (R : Type*) [Ring R] (x y : ZMod 2) :
    signZMod R (x + y) = signZMod R x * signZMod R y := by
  rcases eq_zero_or_one_zmod_two x with rfl | rfl <;>
      rcases eq_zero_or_one_zmod_two y with rfl | rfl <;>
    simp [show (1 : ZMod 2) + 1 = 0 from by decide]

/-- The sign takes distinct values on the two elements of `ZMod 2` whenever `2` is invertible. -/
theorem signZMod_injective (R : Type*) [CommRing R] [CharZero R] :
    Function.Injective (signZMod R) := by
  intro x y hxy
  have hne : (1 : R) ≠ -1 := by
    intro h
    have h2 : (2 : R) = 0 := by linear_combination h
    norm_num at h2
  rcases eq_zero_or_one_zmod_two x with rfl | rfl <;>
      rcases eq_zero_or_one_zmod_two y with rfl | rfl
  · rfl
  · exact absurd (by simpa using hxy) hne
  · exact absurd (by simpa using hxy.symm) hne
  · rfl

/-- A product of signs is the sign of the sum. -/
theorem prod_signZMod {R : Type*} [CommRing R] {ι : Type*} (S : Finset ι) (f : ι → ZMod 2) :
    ∏ i ∈ S, signZMod R (f i) = signZMod R (∑ i ∈ S, f i) := by
  classical
  refine Finset.induction_on S (by simp) ?_
  intro i S hi ih
  rw [Finset.prod_insert hi, Finset.sum_insert hi, ih, signZMod_add]

/-! ### Duality over the field with two elements -/

/-- **Subset sums detect membership in a subspace.**  A vector of `ZMod 2`-valued functions on a
finite index set lies in a subspace as soon as it is annihilated by every subset sum that
annihilates the subspace.  The linear functionals on `ι → ZMod 2` are exactly the subset sums, so
this is the double annihilator theorem. -/
theorem mem_of_forall_sum_eq_zero {ι : Type*} [Fintype ι] [DecidableEq ι]
    (W : Submodule (ZMod 2) (ι → ZMod 2)) (t : ι → ZMod 2)
    (h : ∀ S : Finset ι, (∀ w ∈ W, ∑ i ∈ S, w i = 0) → ∑ i ∈ S, t i = 0) : t ∈ W := by
  classical
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  refine mem_of_forall_dualCoeff W t fun a ha => ?_
  set S : Finset ι := Finset.univ.filter (fun i => a i = 1) with hSdef
  have key : ∀ v : ι → ZMod 2, ∑ i, v i * a i = ∑ i ∈ S, v i := by
    intro v
    rw [hSdef, Finset.sum_filter]
    refine Finset.sum_congr rfl fun i _ => ?_
    by_cases h' : a i = 1
    · rw [if_pos h', h', mul_one]
    · rw [if_neg h']
      rcases eq_zero_or_one_zmod_two (a i) with h'' | h''
      · rw [h'', mul_zero]
      · exact absurd h'' h'
  rw [key t]
  exact h S fun w hw => by rw [← key w]; exact ha w hw

/-- The image of a homomorphism from a group to the additive group of `ZMod 2`-valued functions,
as a subspace. -/
def rangeSubmodule {ι G : Type*} [Group G] (c : G → ι → ZMod 2)
    (hc : ∀ σ τ : G, c (σ * τ) = c σ + c τ) : Submodule (ZMod 2) (ι → ZMod 2) where
  carrier := Set.range c
  add_mem' := by
    intro a b ha hb
    obtain ⟨σ, rfl⟩ := ha
    obtain ⟨τ, rfl⟩ := hb
    exact ⟨σ * τ, hc σ τ⟩
  zero_mem' := by
    refine ⟨1, ?_⟩
    refine add_left_cancel (a := c 1) ?_
    rw [add_zero, ← hc 1 1, one_mul]
  smul_mem' := by
    intro a x hx
    obtain ⟨σ, rfl⟩ := hx
    rcases eq_zero_or_one_zmod_two a with rfl | rfl
    · refine ⟨1, ?_⟩
      have h1 : c 1 = 0 := by
        refine add_left_cancel (a := c 1) ?_
        rw [add_zero, ← hc 1 1, one_mul]
      rw [h1, zero_smul]
    · exact ⟨σ, (one_smul _ _).symm⟩

/-- **Subset sums detect the image of a cocycle.**  Let `c` be a homomorphism from a group to the
additive group of `ZMod 2`-valued functions on a finite index set.  A function `t` is a value of
`c` as soon as `∑ i ∈ S, t i` vanishes for every subset `S` on which all values of `c` sum to
zero. -/
theorem exists_eq_of_forall_sum_eq_zero {ι : Type*} [Fintype ι] [DecidableEq ι] {G : Type*}
    [Group G] (c : G → ι → ZMod 2) (hc : ∀ σ τ : G, c (σ * τ) = c σ + c τ) (t : ι → ZMod 2)
    (h : ∀ S : Finset ι, (∀ σ : G, ∑ i ∈ S, c σ i = 0) → ∑ i ∈ S, t i = 0) :
    ∃ σ : G, c σ = t :=
  mem_of_forall_sum_eq_zero (rangeSubmodule c hc) t
    fun S hS => h S fun σ => hS (c σ) ⟨σ, rfl⟩

/-! ### Prescribing the signs of square roots -/

section Galois

variable {F M : Type*} [Field F] [Field M] [Algebra F M] [FiniteDimensional F M] [IsGalois F M]
  [CharZero M] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **An automorphism with prescribed signs on a family of square roots.**  Let `r : ι → M` be a
family of nonzero elements whose squares lie in `F`, and let `B` be an intermediate field.  A sign
pattern `t : ι → ZMod 2` is realized by an automorphism of `M / F` fixing `B` pointwise as soon as
`∑ i ∈ S, t i = 0` for every subset `S` with `∏ i ∈ S, r i ∈ B`. -/
theorem exists_fixingSubgroup_map_eq_signZMod_mul (B : IntermediateField F M) {r : ι → M}
    {a : ι → F} (hr : ∀ i, r i ^ 2 = algebraMap F M (a i)) (hr0 : ∀ i, r i ≠ 0)
    (t : ι → ZMod 2) (ht : ∀ S : Finset ι, (∏ i ∈ S, r i) ∈ B → ∑ i ∈ S, t i = 0) :
    ∃ σ : Gal(M/F), (∀ x ∈ B, σ x = x) ∧ ∀ i, σ (r i) = signZMod M (t i) * r i := by
  classical
  -- every automorphism multiplies each `r i` by a sign
  have hpm : ∀ (σ : Gal(M/F)) (i : ι), σ (r i) = r i ∨ σ (r i) = -r i := by
    intro σ i
    have hsq : σ (r i) ^ 2 = r i ^ 2 := by
      rw [← map_pow, hr i, AlgEquiv.commutes, ← hr i]
    have hfac : (σ (r i) - r i) * (σ (r i) + r i) = 0 := by linear_combination hsq
    rcases mul_eq_zero.mp hfac with h | h
    · exact Or.inl (sub_eq_zero.mp h)
    · exact Or.inr (eq_neg_of_add_eq_zero_left h)
  obtain ⟨c, hcdef⟩ : ∃ c : Gal(M/F) → ι → ZMod 2,
      ∀ (σ : Gal(M/F)) (i : ι), c σ i = if σ (r i) = r i then 0 else 1 :=
    ⟨fun σ i => if σ (r i) = r i then 0 else 1, fun _ _ => rfl⟩
  have hcact : ∀ (σ : Gal(M/F)) (i : ι), σ (r i) = signZMod M (c σ i) * r i := by
    intro σ i
    by_cases h : σ (r i) = r i
    · rw [hcdef, if_pos h, signZMod_zero, one_mul, h]
    · rcases hpm σ i with h' | h'
      · exact absurd h' h
      · rw [hcdef, if_neg h, signZMod_one, neg_one_mul, h']
  have hcval : ∀ (σ : Gal(M/F)) (i : ι) (z : ZMod 2),
      σ (r i) = signZMod M z * r i → c σ i = z := by
    intro σ i z hz
    refine signZMod_injective M ?_
    exact mul_right_cancel₀ (hr0 i) ((hcact σ i).symm.trans hz)
  have hcadd : ∀ σ τ : Gal(M/F), c (σ * τ) = c σ + c τ := by
    intro σ τ
    funext i
    refine hcval (σ * τ) i (c σ i + c τ i) ?_
    rw [AlgEquiv.mul_apply, hcact τ i, signZMod_add]
    rcases eq_zero_or_one_zmod_two (c τ i) with h | h
    · rw [h, signZMod_zero, one_mul, mul_one, hcact σ i]
    · rw [h, signZMod_one, neg_one_mul, map_neg, hcact σ i]
      ring
  -- on a subset where all the signs of the `B`-fixing automorphisms cancel, the product of the
  -- square roots is fixed by every such automorphism, hence lies in `B`
  have hsum : ∀ S : Finset ι, (∀ g : B.fixingSubgroup, ∑ i ∈ S, c (g : Gal(M/F)) i = 0) →
      ∑ i ∈ S, t i = 0 := by
    intro S hS
    refine ht S ?_
    rw [← IsGalois.fixedField_fixingSubgroup B, IntermediateField.mem_fixedField_iff]
    intro g hg
    rw [map_prod, Finset.prod_congr rfl (fun i _ => hcact g i), Finset.prod_mul_distrib,
      prod_signZMod, hS ⟨g, hg⟩, signZMod_zero, one_mul]
  obtain ⟨σ, hσ⟩ := exists_eq_of_forall_sum_eq_zero (G := B.fixingSubgroup)
    (fun g => c (g : Gal(M/F))) (fun g g' => hcadd _ _) t hsum
  refine ⟨(σ : Gal(M/F)), fun x hx =>
    (IntermediateField.mem_fixingSubgroup_iff B (σ : Gal(M/F))).mp σ.2 x hx, fun i => ?_⟩
  rw [hcact (σ : Gal(M/F)) i, congrFun hσ i]

end Galois

/-! ### Splitting a square root over a compositum -/

section Compositum

variable {F M : Type*} [Field F] [Field M] [Algebra F M] [FiniteDimensional F M] [IsGalois F M]
  [CharZero M]

omit [FiniteDimensional F M] [IsGalois F M] in
/-- **The sign character of a square root.**  An automorphism of `M / F` multiplies an element
whose square lies in `F` by a sign, and the assignment of that sign is a homomorphism from the
Galois group to `ZMod 2`. -/
theorem exists_signChar_of_sq_mem {x : M} (hx0 : x ≠ 0) {b : F}
    (hb : x ^ 2 = algebraMap F M b) :
    ∃ χ : Gal(M/F) → ZMod 2, (∀ σ τ : Gal(M/F), χ (σ * τ) = χ σ + χ τ) ∧
      ∀ σ : Gal(M/F), σ x = signZMod M (χ σ) * x := by
  classical
  have hpm : ∀ σ : Gal(M/F), σ x = x ∨ σ x = -x := by
    intro σ
    have hsq : σ x ^ 2 = x ^ 2 := by rw [← map_pow, hb, AlgEquiv.commutes, ← hb]
    have hfac : (σ x - x) * (σ x + x) = 0 := by linear_combination hsq
    rcases mul_eq_zero.mp hfac with h | h
    · exact Or.inl (sub_eq_zero.mp h)
    · exact Or.inr (eq_neg_of_add_eq_zero_left h)
  obtain ⟨χ, hχdef⟩ : ∃ χ : Gal(M/F) → ZMod 2, ∀ σ, χ σ = if σ x = x then 0 else 1 :=
    ⟨fun σ => if σ x = x then 0 else 1, fun _ => rfl⟩
  have hact : ∀ σ : Gal(M/F), σ x = signZMod M (χ σ) * x := by
    intro σ
    by_cases h : σ x = x
    · rw [hχdef, if_pos h, signZMod_zero, one_mul, h]
    · rcases hpm σ with h' | h'
      · exact absurd h' h
      · rw [hχdef, if_neg h, signZMod_one, neg_one_mul, h']
  have hval : ∀ (σ : Gal(M/F)) (z : ZMod 2), σ x = signZMod M z * x → χ σ = z := fun σ z hz =>
    signZMod_injective M (mul_right_cancel₀ hx0 ((hact σ).symm.trans hz))
  refine ⟨χ, fun σ τ => hval (σ * τ) (χ σ + χ τ) ?_, hact⟩
  rw [AlgEquiv.mul_apply, hact τ, signZMod_add]
  rcases eq_zero_or_one_zmod_two (χ τ) with h | h
  · rw [h, signZMod_zero, one_mul, mul_one, hact σ]
  · rw [h, signZMod_one, neg_one_mul, map_neg, hact σ]
    ring

/-- **Every homomorphism from the Galois group to `ZMod 2` is the sign character of a square
root.**  The fixed field of the kernel is a quadratic extension of the base field, and the
difference of an element of it and its conjugate is a square root generating it. -/
theorem exists_sq_mem_forall_map_eq_signZMod (χ : Gal(M/F) → ZMod 2)
    (hχ : ∀ σ τ : Gal(M/F), χ (σ * τ) = χ σ + χ τ) :
    ∃ y : M, y ≠ 0 ∧ (∃ b : F, y ^ 2 = algebraMap F M b) ∧
      ∀ σ : Gal(M/F), σ y = signZMod M (χ σ) * y := by
  classical
  have hself : ∀ z : ZMod 2, z + z = 0 := by decide
  have hneg : ∀ z : ZMod 2, -z = z := by decide
  have hχ1 : χ 1 = 0 := by
    have h := hχ 1 1
    rw [one_mul] at h
    exact add_left_cancel (a := χ 1) (by rw [add_zero]; exact h.symm)
  have hinv : ∀ σ : Gal(M/F), χ σ⁻¹ = χ σ := by
    intro σ
    have h := hχ σ σ⁻¹
    rw [mul_inv_cancel, hχ1] at h
    rw [eq_neg_of_add_eq_zero_left h.symm, hneg]
  by_cases h0 : ∀ σ : Gal(M/F), χ σ = 0
  · exact ⟨1, one_ne_zero, ⟨1, by simp⟩, fun σ => by simp [h0 σ]⟩
  push_neg at h0
  obtain ⟨σ₀, hσ₀⟩ := h0
  have hσ₀1 : χ σ₀ = 1 := (eq_zero_or_one_zmod_two _).resolve_left hσ₀
  -- the kernel of the character
  let H : Subgroup Gal(M/F) :=
    { carrier := {σ | χ σ = 0}
      mul_mem' := by
        intro a c ha hc
        simp only [Set.mem_setOf_eq] at ha hc ⊢
        rw [hχ, ha, hc, add_zero]
      one_mem' := hχ1
      inv_mem' := by
        intro a ha
        simp only [Set.mem_setOf_eq] at ha ⊢
        rw [hinv, ha] }
  have hHmem : ∀ σ : Gal(M/F), σ ∈ H ↔ χ σ = 0 := fun _ => Iff.rfl
  haveI : H.Normal := by
    refine ⟨fun n hn g => ?_⟩
    rw [hHmem] at hn ⊢
    have hexp : χ (g * n * g⁻¹) = χ g + χ n + χ g⁻¹ := by rw [hχ, hχ]
    rw [hexp, hn, hinv, add_zero]
    exact hself _
  -- an element of the fixed field of the kernel moved by an automorphism outside it
  obtain ⟨u, huE, hune⟩ : ∃ u : M, u ∈ IntermediateField.fixedField H ∧ σ₀ u ≠ u := by
    by_contra hcon
    push_neg at hcon
    refine hσ₀ ?_
    have hmem : σ₀ ∈ H := by
      rw [← IntermediateField.fixingSubgroup_fixedField H]
      exact (IntermediateField.mem_fixingSubgroup_iff _ σ₀).mpr fun v hv => hcon v hv
    exact hmem
  have hfixH : ∀ σ ∈ H, σ u = u := fun σ hσ =>
    (IntermediateField.mem_fixedField_iff _ u).mp huE σ hσ
  have hsq0 : σ₀ * σ₀ ∈ H := by
    show χ (σ₀ * σ₀) = 0
    rw [hχ, hσ₀1]
    decide
  have hσ₀u : σ₀ (σ₀ u) = u := by
    rw [← AlgEquiv.mul_apply]
    exact hfixH _ hsq0
  have hH : ∀ σ ∈ H, σ (u - σ₀ u) = u - σ₀ u := by
    intro σ hσ
    have hone : χ σ = 0 := hσ
    have hc : σ₀⁻¹ * σ * σ₀ ∈ H := by
      show χ (σ₀⁻¹ * σ * σ₀) = 0
      rw [hχ, hχ, hinv, hσ₀1, hone]
      decide
    have h2 : σ (σ₀ u) = σ₀ u := by
      have hfx := hfixH _ hc
      calc σ (σ₀ u) = (σ * σ₀) u := (AlgEquiv.mul_apply σ σ₀ u).symm
        _ = (σ₀ * (σ₀⁻¹ * σ * σ₀)) u := by
            rw [show σ₀ * (σ₀⁻¹ * σ * σ₀) = σ * σ₀ from by group]
        _ = σ₀ ((σ₀⁻¹ * σ * σ₀) u) := AlgEquiv.mul_apply _ _ u
        _ = σ₀ u := by rw [hfx]
    rw [map_sub, hfixH σ hσ, h2]
  have hkey : ∀ σ : Gal(M/F), σ (u - σ₀ u) = signZMod M (χ σ) * (u - σ₀ u) := by
    intro σ
    rcases eq_zero_or_one_zmod_two (χ σ) with h | h
    · rw [h, signZMod_zero, one_mul]
      exact hH σ h
    · have hκ : σ₀⁻¹ * σ ∈ H := by
        show χ (σ₀⁻¹ * σ) = 0
        rw [hχ, hinv, hσ₀1, h]
        decide
      have hcomp : σ₀ ((σ₀⁻¹ * σ) (u - σ₀ u)) = σ (u - σ₀ u) := by
        rw [← AlgEquiv.mul_apply, show σ₀ * (σ₀⁻¹ * σ) = σ from by group]
      rw [h, signZMod_one, neg_one_mul, ← hcomp, hH _ hκ, map_sub, hσ₀u]
      ring
  refine ⟨u - σ₀ u, sub_ne_zero_of_ne (Ne.symm hune), ?_, hkey⟩
  have hfix2 : ∀ σ : Gal(M/F), σ ((u - σ₀ u) ^ 2) = (u - σ₀ u) ^ 2 := by
    intro σ
    rw [map_pow, hkey σ, mul_pow]
    rcases eq_zero_or_one_zmod_two (χ σ) with h | h <;> rw [h] <;> simp
  obtain ⟨c, hc⟩ := (IsGalois.mem_range_algebraMap_iff_fixed ((u - σ₀ u) ^ 2)).mpr hfix2
  exact ⟨c, hc.symm⟩

omit [FiniteDimensional F M] [IsGalois F M] [CharZero M] in
/-- An automorphism of a compositum of two intermediate fields whose fixing subgroups generate the
Galois group is a product of an automorphism fixing the first and one fixing the second. -/
theorem exists_mul_eq_of_fixingSubgroup_sup_eq_top (A B : IntermediateField F M) [IsGalois F ↥A]
    (hgen : A.fixingSubgroup ⊔ B.fixingSubgroup = ⊤) (σ : Gal(M/F)) :
    ∃ a ∈ A.fixingSubgroup, ∃ c ∈ B.fixingSubgroup, σ = a * c := by
  haveI : (A.fixingSubgroup).Normal := by
    rw [← A.restrictNormalHom_ker]
    infer_instance
  have hmem : σ ∈ (↑(A.fixingSubgroup ⊔ B.fixingSubgroup) : Set Gal(M/F)) := by
    rw [hgen]
    trivial
  rw [Subgroup.normal_mul] at hmem
  obtain ⟨a, ha, c, hc, hac⟩ := hmem
  exact ⟨a, ha, c, hc, hac.symm⟩

omit [FiniteDimensional F M] [CharZero M] in
/-- **The part of a quadratic character coming from one factor of a compositum.**  When the fixing
subgroups of two intermediate fields intersect trivially and generate the Galois group, every
homomorphism to `ZMod 2` is the sum of one vanishing on the first fixing subgroup and one vanishing
on the second; this produces the first summand, which agrees with the given homomorphism on the
second fixing subgroup. -/
theorem exists_char_eq_on_fixingSubgroup (A B : IntermediateField F M) [IsGalois F ↥A]
    (hdisj : A.fixingSubgroup ⊓ B.fixingSubgroup = ⊥)
    (hgen : A.fixingSubgroup ⊔ B.fixingSubgroup = ⊤) (χ : Gal(M/F) → ZMod 2)
    (hχ : ∀ σ τ : Gal(M/F), χ (σ * τ) = χ σ + χ τ) :
    ∃ ψ : Gal(M/F) → ZMod 2, (∀ σ τ : Gal(M/F), ψ (σ * τ) = ψ σ + ψ τ) ∧
      (∀ σ ∈ A.fixingSubgroup, ψ σ = 0) ∧ ∀ σ ∈ B.fixingSubgroup, ψ σ = χ σ := by
  have hχ1 : χ 1 = 0 := by
    have h := hχ 1 1
    rw [one_mul] at h
    exact add_left_cancel (a := χ 1) (by rw [add_zero]; exact h.symm)
  set res : Gal(M/F) →* Gal(↥A/F) := AlgEquiv.restrictNormalHom ↥A with hresdef
  have hbij : Function.Bijective (res.comp (B.fixingSubgroup).subtype) := by
    constructor
    · refine (injective_iff_map_eq_one _).mpr fun n hn => ?_
      have h1 : (n : Gal(M/F)) ∈ A.fixingSubgroup := by
        rw [← A.restrictNormalHom_ker, MonoidHom.mem_ker]
        exact hn
      have h2 : (n : Gal(M/F)) ∈ A.fixingSubgroup ⊓ B.fixingSubgroup := ⟨h1, n.2⟩
      rw [hdisj] at h2
      exact Subtype.ext (Subgroup.mem_bot.mp h2)
    · intro τ
      obtain ⟨σ, hσ⟩ := AlgEquiv.restrictNormalHom_surjective (F := F) (K₁ := ↥A) (E := M) τ
      obtain ⟨a, ha, c, hc, hac⟩ := exists_mul_eq_of_fixingSubgroup_sup_eq_top A B hgen σ
      have ha1 : res a = 1 := by
        rw [hresdef, ← MonoidHom.mem_ker, A.restrictNormalHom_ker]
        exact ha
      refine ⟨⟨c, hc⟩, ?_⟩
      show res c = τ
      rw [← hσ, hac, map_mul, ha1, one_mul]
  set e := MulEquiv.ofBijective _ hbij with hedef
  refine ⟨fun σ => χ ((e.symm (res σ) : ↥(B.fixingSubgroup)) : Gal(M/F)), fun σ τ => ?_,
    fun σ hσ => ?_, fun σ hσ => ?_⟩
  · simp only [map_mul, Subgroup.coe_mul]
    exact hχ _ _
  · have h1 : res σ = 1 := by
      rw [hresdef, ← MonoidHom.mem_ker, A.restrictNormalHom_ker]
      exact hσ
    simp only [h1, map_one, Subgroup.coe_one, hχ1]
  · have h1 : e ⟨σ, hσ⟩ = res σ := rfl
    show χ ((e.symm (res σ) : ↥(B.fixingSubgroup)) : Gal(M/F)) = χ σ
    rw [← h1, MulEquiv.symm_apply_apply]

/-- **A square root in a compositum of two Galois extensions meeting in the base field is the
product of a square root from each factor.**  The Galois group is the product of the two Galois
groups, so the sign character of the square root is the sum of a character vanishing on the first
factor's fixing subgroup and one vanishing on the second's; realizing each summand by a square root
of its own and comparing with the given one produces the factorization. -/
theorem exists_mul_eq_of_sq_mem_of_inf_eq_bot (A B : IntermediateField F M) [IsGalois F ↥A]
    [IsGalois F ↥B] (hinf : A ⊓ B = ⊥) (hsup : A ⊔ B = ⊤) {x : M} {b : F}
    (hb : x ^ 2 = algebraMap F M b) :
    ∃ y ∈ A, ∃ z ∈ B, x = y * z ∧ (∃ c : F, y ^ 2 = algebraMap F M c) ∧
      ∃ d : F, z ^ 2 = algebraMap F M d := by
  classical
  rcases eq_or_ne x 0 with rfl | hx0
  · exact ⟨0, zero_mem A, 1, one_mem B, by simp, ⟨0, by simp⟩, ⟨1, by simp⟩⟩
  obtain ⟨χ, hχ, hχact⟩ := exists_signChar_of_sq_mem hx0 hb
  have hdisj : A.fixingSubgroup ⊓ B.fixingSubgroup = ⊥ := by
    rw [← IntermediateField.fixingSubgroup_sup, hsup, IntermediateField.fixingSubgroup_top]
  have hgen : A.fixingSubgroup ⊔ B.fixingSubgroup = ⊤ := by
    have h1 : IntermediateField.fixedField (A.fixingSubgroup ⊔ B.fixingSubgroup) = ⊥ := by
      refine le_antisymm ?_ bot_le
      calc IntermediateField.fixedField (A.fixingSubgroup ⊔ B.fixingSubgroup)
          ≤ IntermediateField.fixedField A.fixingSubgroup ⊓
              IntermediateField.fixedField B.fixingSubgroup :=
            le_inf (IntermediateField.fixedField_le le_sup_left)
              (IntermediateField.fixedField_le le_sup_right)
        _ = A ⊓ B := by
            rw [IsGalois.fixedField_fixingSubgroup, IsGalois.fixedField_fixingSubgroup]
        _ = ⊥ := hinf
    calc A.fixingSubgroup ⊔ B.fixingSubgroup
        = IntermediateField.fixingSubgroup
            (IntermediateField.fixedField (A.fixingSubgroup ⊔ B.fixingSubgroup)) :=
          (IntermediateField.fixingSubgroup_fixedField _).symm
      _ = ⊤ := by rw [h1, IntermediateField.fixingSubgroup_bot]
  obtain ⟨χA, hχAadd, hχAzero, hχAeq⟩ := exists_char_eq_on_fixingSubgroup A B hdisj hgen χ hχ
  obtain ⟨χB, hχBadd, hχBzero, hχBeq⟩ :=
    exists_char_eq_on_fixingSubgroup B A (by rw [inf_comm]; exact hdisj)
      (by rw [sup_comm]; exact hgen) χ hχ
  have hsplit : ∀ σ : Gal(M/F), χ σ = χA σ + χB σ := by
    intro σ
    obtain ⟨a, ha, c, hc, rfl⟩ := exists_mul_eq_of_fixingSubgroup_sup_eq_top A B hgen σ
    rw [hχ, hχAadd, hχBadd, hχAzero a ha, hχBzero c hc, hχAeq c hc, hχBeq a ha, zero_add,
      add_zero, add_comm]
  obtain ⟨y, hy0, ⟨cy, hcy⟩, hyact⟩ := exists_sq_mem_forall_map_eq_signZMod χA hχAadd
  obtain ⟨z, hz0, ⟨cz, hcz⟩, hzact⟩ := exists_sq_mem_forall_map_eq_signZMod χB hχBadd
  have hyA : y ∈ A := by
    rw [← IsGalois.fixedField_fixingSubgroup A]
    refine (IntermediateField.mem_fixedField_iff _ y).mpr fun σ hσ => ?_
    rw [hyact σ, hχAzero σ hσ, signZMod_zero, one_mul]
  have hzB : z ∈ B := by
    rw [← IsGalois.fixedField_fixingSubgroup B]
    refine (IntermediateField.mem_fixedField_iff _ z).mpr fun σ hσ => ?_
    rw [hzact σ, hχBzero σ hσ, signZMod_zero, one_mul]
  have hyz : y * z ≠ 0 := mul_ne_zero hy0 hz0
  have hfixw : ∀ σ : Gal(M/F), σ (x / (y * z)) = x / (y * z) := by
    intro σ
    have hs : signZMod M (χA σ) ≠ 0 := signZMod_ne_zero _
    have ht : signZMod M (χB σ) ≠ 0 := signZMod_ne_zero _
    rw [map_div₀, map_mul, hχact σ, hyact σ, hzact σ, hsplit σ, signZMod_add]
    field_simp
  obtain ⟨w, hw⟩ := (IsGalois.mem_range_algebraMap_iff_fixed (x / (y * z))).mpr hfixw
  refine ⟨algebraMap F M w * y, mul_mem (A.algebraMap_mem w) hyA, z, hzB, ?_,
    ⟨w ^ 2 * cy, ?_⟩, ⟨cz, hcz⟩⟩
  · rw [hw]
    field_simp
  · rw [map_mul, map_pow, mul_pow, hcy]

/-- **A square root in a compositum of two Galois subextensions meeting in the base field is the
product of a square root from each factor.** -/
theorem exists_mul_eq_of_sq_mem_sup {K L : Type*} [Field K] [Field L] [Algebra K L] [CharZero L]
    (A B : IntermediateField K L) [FiniteDimensional K ↥(A ⊔ B)] [IsGalois K ↥(A ⊔ B)]
    [IsGalois K ↥A] [IsGalois K ↥B] (hinf : A ⊓ B = ⊥) {x : L} (hx : x ∈ A ⊔ B) {b : K}
    (hb : x ^ 2 = algebraMap K L b) :
    ∃ y ∈ A, ∃ z ∈ B, x = y * z ∧ (∃ c : K, y ^ 2 = algebraMap K L c) ∧
      ∃ d : K, z ^ 2 = algebraMap K L d := by
  classical
  set A' : IntermediateField K ↥(A ⊔ B) :=
    IntermediateField.restrict (le_sup_left : A ≤ A ⊔ B) with hA'
  set B' : IntermediateField K ↥(A ⊔ B) :=
    IntermediateField.restrict (le_sup_right : B ≤ A ⊔ B) with hB'
  haveI : IsGalois K ↥A' := IsGalois.of_algEquiv (IntermediateField.restrict_algEquiv _)
  haveI : IsGalois K ↥B' := IsGalois.of_algEquiv (IntermediateField.restrict_algEquiv _)
  have hliftA : IntermediateField.lift A' = A := IntermediateField.lift_restrict _
  have hliftB : IntermediateField.lift B' = B := IntermediateField.lift_restrict _
  have hinf' : A' ⊓ B' = ⊥ := by
    refine (IntermediateField.lift_inj _ _).mp ?_
    rw [IntermediateField.lift_inf, hliftA, hliftB, hinf, IntermediateField.lift_bot]
  have hsup' : A' ⊔ B' = ⊤ := by
    refine (IntermediateField.lift_inj _ _).mp ?_
    rw [IntermediateField.lift_sup, hliftA, hliftB, IntermediateField.lift_top]
  have hb' : (⟨x, hx⟩ : ↥(A ⊔ B)) ^ 2 = algebraMap K ↥(A ⊔ B) b := by
    apply Subtype.ext
    push_cast
    exact hb
  obtain ⟨y, hy, z, hz, hxyz, ⟨c, hc⟩, ⟨d, hd⟩⟩ :=
    exists_mul_eq_of_sq_mem_of_inf_eq_bot A' B' hinf' hsup' hb'
  refine ⟨(y : L), (IntermediateField.mem_restrict _ y).mp hy, (z : L),
    (IntermediateField.mem_restrict _ z).mp hz, ?_, ⟨c, ?_⟩, ⟨d, ?_⟩⟩
  · exact congrArg Subtype.val hxyz
  · have h := congrArg (Subtype.val : ↥(A ⊔ B) → L) hc
    push_cast at h
    exact h
  · have h := congrArg (Subtype.val : ↥(A ⊔ B) → L) hd
    push_cast at h
    exact h

end Compositum

end InverseGalois.CFT
