/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Prescribing the signs of a family of square roots

Let `M / F` be a finite Galois extension, `B` an intermediate field, and `r : ι → M` a finite
family of elements whose squares lie in `F`.  Every automorphism of `M / F` multiplies each `r i`
by a sign, so it determines a vector in `ι → ZMod 2`, and this assignment is a homomorphism from
the Galois group to the additive group of such vectors.  The question answered here is which sign
patterns are attained by automorphisms that fix `B` pointwise.

The answer is the obvious necessary condition: a pattern `t` is attained as soon as `∑ i ∈ S, t i`
vanishes for every subset `S` whose associated product `∏ i ∈ S, r i` already lies in `B`.  Indeed
the attained patterns form a subspace of the `ZMod 2`-vector space `ι → ZMod 2`, the linear
functionals on that space are exactly the subset sums, and the functionals annihilating the
subspace are exactly those coming from a subset with `∏ i ∈ S, r i` fixed by every automorphism
fixing `B`, that is, lying in `B`.  So the statement is the double annihilator theorem.

This replaces the classical route through multiquadratic Kummer theory: no degree count and no
explicit description of the field generated by the `r i` is needed, only the subsets whose product
lands in `B`.

## Main results

* `InverseGalois.CFT.mem_of_forall_sum_eq_zero`: a vector lies in a subspace of `ι → ZMod 2` as
  soon as every subset sum annihilating the subspace annihilates the vector.
* `InverseGalois.CFT.exists_eq_of_forall_sum_eq_zero`: the same for the image of a homomorphism
  from a group to `ι → ZMod 2`.
* `InverseGalois.CFT.exists_fixingSubgroup_map_eq_signZMod_mul`: an automorphism fixing `B`
  pointwise and realizing a prescribed sign pattern on the square roots.
-/

namespace InverseGalois.CFT

/-! ### Signs -/

/-- The sign attached to an element of `ZMod 2`: `1` for `0` and `-1` for `1`. -/
def signZMod (R : Type*) [Ring R] (z : ZMod 2) : R := if z = 0 then 1 else -1

theorem eq_zero_or_one_zmod_two (z : ZMod 2) : z = 0 ∨ z = 1 := by revert z; decide

@[simp] theorem signZMod_zero (R : Type*) [Ring R] : signZMod R 0 = 1 := if_pos rfl

@[simp] theorem signZMod_one (R : Type*) [Ring R] : signZMod R 1 = -1 := if_neg (by decide)

/-- The sign is a homomorphism from the additive group `ZMod 2` to the units of a ring. -/
theorem signZMod_add (R : Type*) [Ring R] (x y : ZMod 2) :
    signZMod R (x + y) = signZMod R x * signZMod R y := by
  rcases eq_zero_or_one_zmod_two x with rfl | rfl <;>
      rcases eq_zero_or_one_zmod_two y with rfl | rfl <;>
    simp [show (1 : ZMod 2) + 1 = 0 from by decide]

/-- The sign takes distinct values on the two elements of `ZMod 2` whenever `2` is invertible. -/
theorem signZMod_injective (R : Type*) [CommRing R] [CharZero R] :
    Function.Injective (signZMod R) := by
  intro x y hxy
  have hne : (1 : R) ≠ -1 := by
    intro h
    have h2 : (2 : R) = 0 := by linear_combination h
    norm_num at h2
  rcases eq_zero_or_one_zmod_two x with rfl | rfl <;>
      rcases eq_zero_or_one_zmod_two y with rfl | rfl
  · rfl
  · exact absurd (by simpa using hxy) hne
  · exact absurd (by simpa using hxy.symm) hne
  · rfl

/-- A product of signs is the sign of the sum. -/
theorem prod_signZMod {R : Type*} [CommRing R] {ι : Type*} (S : Finset ι) (f : ι → ZMod 2) :
    ∏ i ∈ S, signZMod R (f i) = signZMod R (∑ i ∈ S, f i) := by
  classical
  refine Finset.induction_on S (by simp) ?_
  intro i S hi ih
  rw [Finset.prod_insert hi, Finset.sum_insert hi, ih, signZMod_add]

/-! ### Duality over the field with two elements -/

/-- **Subset sums detect membership in a subspace.**  A vector of `ZMod 2`-valued functions on a
finite index set lies in a subspace as soon as it is annihilated by every subset sum that
annihilates the subspace.  The linear functionals on `ι → ZMod 2` are exactly the subset sums, so
this is the double annihilator theorem. -/
theorem mem_of_forall_sum_eq_zero {ι : Type*} [Fintype ι] [DecidableEq ι]
    (W : Submodule (ZMod 2) (ι → ZMod 2)) (t : ι → ZMod 2)
    (h : ∀ S : Finset ι, (∀ w ∈ W, ∑ i ∈ S, w i = 0) → ∑ i ∈ S, t i = 0) : t ∈ W := by
  classical
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  rw [← Subspace.forall_mem_dualAnnihilator_apply_eq_zero_iff W t]
  intro φ hφ
  set S : Finset ι := Finset.univ.filter (fun i => φ (Pi.single i (1 : ZMod 2)) = 1) with hSdef
  have key : ∀ v : ι → ZMod 2, φ v = ∑ i ∈ S, v i := by
    intro v
    have hv : φ v = φ (∑ i : ι, Pi.single i (v i)) := by rw [Finset.univ_sum_single]
    rw [hv, map_sum]
    have hterm : ∀ i ∈ (Finset.univ : Finset ι),
        φ (Pi.single i (v i)) = if i ∈ S then v i else 0 := by
      intro i _
      have hsm : (Pi.single i (v i) : ι → ZMod 2) = v i • (Pi.single i (1 : ZMod 2)) := by
        ext j
        rcases eq_or_ne j i with rfl | hj
        · simp
        · simp [hj]
      rw [hsm, map_smul, smul_eq_mul]
      by_cases hi : i ∈ S
      · rw [if_pos hi, (Finset.mem_filter.mp hi).2, mul_one]
      · rw [if_neg hi]
        have h0 : φ (Pi.single i (1 : ZMod 2)) = 0 := by
          simp only [hSdef, Finset.mem_filter, Finset.mem_univ, true_and] at hi
          rcases eq_zero_or_one_zmod_two (φ (Pi.single i (1 : ZMod 2))) with h' | h'
          · exact h'
          · exact absurd h' hi
        rw [h0, mul_zero]
    rw [Finset.sum_congr rfl hterm, Finset.sum_ite_mem, Finset.univ_inter]
  rw [key t]
  rw [Submodule.mem_dualAnnihilator] at hφ
  refine h S fun w hw => ?_
  rw [← key w]
  exact hφ w hw

/-- The image of a homomorphism from a group to the additive group of `ZMod 2`-valued functions,
as a subspace. -/
def rangeSubmodule {ι G : Type*} [Group G] (c : G → ι → ZMod 2)
    (hc : ∀ σ τ : G, c (σ * τ) = c σ + c τ) : Submodule (ZMod 2) (ι → ZMod 2) where
  carrier := Set.range c
  add_mem' := by
    intro a b ha hb
    obtain ⟨σ, rfl⟩ := ha
    obtain ⟨τ, rfl⟩ := hb
    exact ⟨σ * τ, hc σ τ⟩
  zero_mem' := by
    refine ⟨1, ?_⟩
    refine add_left_cancel (a := c 1) ?_
    rw [add_zero, ← hc 1 1, one_mul]
  smul_mem' := by
    intro a x hx
    obtain ⟨σ, rfl⟩ := hx
    rcases eq_zero_or_one_zmod_two a with rfl | rfl
    · refine ⟨1, ?_⟩
      have h1 : c 1 = 0 := by
        refine add_left_cancel (a := c 1) ?_
        rw [add_zero, ← hc 1 1, one_mul]
      rw [h1, zero_smul]
    · exact ⟨σ, (one_smul _ _).symm⟩

/-- **Subset sums detect the image of a cocycle.**  Let `c` be a homomorphism from a group to the
additive group of `ZMod 2`-valued functions on a finite index set.  A function `t` is a value of
`c` as soon as `∑ i ∈ S, t i` vanishes for every subset `S` on which all values of `c` sum to
zero. -/
theorem exists_eq_of_forall_sum_eq_zero {ι : Type*} [Fintype ι] [DecidableEq ι] {G : Type*}
    [Group G] (c : G → ι → ZMod 2) (hc : ∀ σ τ : G, c (σ * τ) = c σ + c τ) (t : ι → ZMod 2)
    (h : ∀ S : Finset ι, (∀ σ : G, ∑ i ∈ S, c σ i = 0) → ∑ i ∈ S, t i = 0) :
    ∃ σ : G, c σ = t :=
  mem_of_forall_sum_eq_zero (rangeSubmodule c hc) t
    fun S hS => h S fun σ => hS (c σ) ⟨σ, rfl⟩

/-! ### Prescribing the signs of square roots -/

section Galois

variable {F M : Type*} [Field F] [Field M] [Algebra F M] [FiniteDimensional F M] [IsGalois F M]
  [CharZero M] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **An automorphism with prescribed signs on a family of square roots.**  Let `r : ι → M` be a
family of nonzero elements whose squares lie in `F`, and let `B` be an intermediate field.  A sign
pattern `t : ι → ZMod 2` is realized by an automorphism of `M / F` fixing `B` pointwise as soon as
`∑ i ∈ S, t i = 0` for every subset `S` with `∏ i ∈ S, r i ∈ B`. -/
theorem exists_fixingSubgroup_map_eq_signZMod_mul (B : IntermediateField F M) {r : ι → M}
    {a : ι → F} (hr : ∀ i, r i ^ 2 = algebraMap F M (a i)) (hr0 : ∀ i, r i ≠ 0)
    (t : ι → ZMod 2) (ht : ∀ S : Finset ι, (∏ i ∈ S, r i) ∈ B → ∑ i ∈ S, t i = 0) :
    ∃ σ : Gal(M/F), (∀ x ∈ B, σ x = x) ∧ ∀ i, σ (r i) = signZMod M (t i) * r i := by
  classical
  -- every automorphism multiplies each `r i` by a sign
  have hpm : ∀ (σ : Gal(M/F)) (i : ι), σ (r i) = r i ∨ σ (r i) = -r i := by
    intro σ i
    have hsq : σ (r i) ^ 2 = r i ^ 2 := by
      rw [← map_pow, hr i, AlgEquiv.commutes, ← hr i]
    have hfac : (σ (r i) - r i) * (σ (r i) + r i) = 0 := by linear_combination hsq
    rcases mul_eq_zero.mp hfac with h | h
    · exact Or.inl (sub_eq_zero.mp h)
    · exact Or.inr (eq_neg_of_add_eq_zero_left h)
  obtain ⟨c, hcdef⟩ : ∃ c : Gal(M/F) → ι → ZMod 2,
      ∀ (σ : Gal(M/F)) (i : ι), c σ i = if σ (r i) = r i then 0 else 1 :=
    ⟨fun σ i => if σ (r i) = r i then 0 else 1, fun _ _ => rfl⟩
  have hcact : ∀ (σ : Gal(M/F)) (i : ι), σ (r i) = signZMod M (c σ i) * r i := by
    intro σ i
    by_cases h : σ (r i) = r i
    · rw [hcdef, if_pos h, signZMod_zero, one_mul, h]
    · rcases hpm σ i with h' | h'
      · exact absurd h' h
      · rw [hcdef, if_neg h, signZMod_one, neg_one_mul, h']
  have hcval : ∀ (σ : Gal(M/F)) (i : ι) (z : ZMod 2),
      σ (r i) = signZMod M z * r i → c σ i = z := by
    intro σ i z hz
    refine signZMod_injective M ?_
    exact mul_right_cancel₀ (hr0 i) ((hcact σ i).symm.trans hz)
  have hcadd : ∀ σ τ : Gal(M/F), c (σ * τ) = c σ + c τ := by
    intro σ τ
    funext i
    refine hcval (σ * τ) i (c σ i + c τ i) ?_
    rw [AlgEquiv.mul_apply, hcact τ i, signZMod_add]
    rcases eq_zero_or_one_zmod_two (c τ i) with h | h
    · rw [h, signZMod_zero, one_mul, mul_one, hcact σ i]
    · rw [h, signZMod_one, neg_one_mul, map_neg, hcact σ i]
      ring
  -- on a subset where all the signs of the `B`-fixing automorphisms cancel, the product of the
  -- square roots is fixed by every such automorphism, hence lies in `B`
  have hsum : ∀ S : Finset ι, (∀ g : B.fixingSubgroup, ∑ i ∈ S, c (g : Gal(M/F)) i = 0) →
      ∑ i ∈ S, t i = 0 := by
    intro S hS
    refine ht S ?_
    rw [← IsGalois.fixedField_fixingSubgroup B, IntermediateField.mem_fixedField_iff]
    intro g hg
    rw [map_prod, Finset.prod_congr rfl (fun i _ => hcact g i), Finset.prod_mul_distrib,
      prod_signZMod, hS ⟨g, hg⟩, signZMod_zero, one_mul]
  obtain ⟨σ, hσ⟩ := exists_eq_of_forall_sum_eq_zero (G := B.fixingSubgroup)
    (fun g => c (g : Gal(M/F))) (fun g g' => hcadd _ _) t hsum
  refine ⟨(σ : Gal(M/F)), fun x hx =>
    (IntermediateField.mem_fixingSubgroup_iff B (σ : Gal(M/F))).mp σ.2 x hx, fun i => ?_⟩
  rw [hcact (σ : Gal(M/F)) i, congrFun hσ i]

end Galois

end InverseGalois.CFT
