/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.NumberTheory.RelativeSplitDensity

/-!
# Decomposition groups and the Frobenius over a number-field base

Let `L` be a Galois extension of a number field `k` and let `P` be a nonzero prime of `𝓞 L`.
Attached to `P` are the decomposition group `MulAction.stabilizer Gal(L/k) P`, the inertia group,
and the cyclic group generated by an arithmetic Frobenius `arithFrobAt (𝓞 k) Gal(L/k) P`.  This
file records the dictionary relating them to the local invariants of `P` over the base, and uses
the density of the completely split primes of `k` to produce primes with a prescribed
decomposition group.

For an element `σ` of prime order generating a normal subgroup, the fixed field of that subgroup
has no proper intermediate field above it, so a prime of `k` splitting completely there but not in
`L` has decomposition group exactly the subgroup generated by `σ`.  The Frobenius at such a prime
therefore generates the same cyclic group as `σ`: it is one of the `σ ^ j` with `j` prime to the
order.

## Main results

* `InverseGalois.CFT.relStabilizer_eq_zpowers_arithFrobAt`: at an unramified prime the
  decomposition group over the base is generated by the arithmetic Frobenius.
* `InverseGalois.CFT.relStabilizer_eq_bot_iff`: the decomposition group over the base is trivial
  exactly when the prime is unramified of residue degree one.
* `InverseGalois.CFT.relStabilizer_le_of_splitsCompletelyIn`: a prime of the base splitting
  completely in the fixed field of a normal subgroup has all its decomposition groups inside that
  subgroup.
* `InverseGalois.CFT.exists_relStabilizer_eq_zpowers`: **an element of prime order generating a
  normal subgroup is the decomposition group at infinitely many primes of the base**, and the
  Frobenius there generates the group it generates.

## Tags

Frobenius, decomposition group, Chebotarev, Dirichlet density, number field
-/

open NumberField IsDedekindDomain InverseGalois.NumberTheory

open scoped Pointwise

set_option synthInstance.maxHeartbeats 800000

namespace InverseGalois.CFT

attribute [local instance] Ideal.Quotient.field

section Local

variable {k L : Type*} [Field k] [NumberField k] [Field L] [NumberField L] [Algebra k L]

/-- The residue field of a nonzero prime of `𝓞 L` is finite. -/
private theorem finite_res (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) : Finite (𝓞 L ⧸ P) :=
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  inferInstance

omit [NumberField L] in
/-- The prime of `𝓞 k` under a nonzero prime of `𝓞 L` is maximal. -/
private theorem isMaximal_relUnder (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    (P.under (𝓞 k)).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance (Ideal.under_ne_bot (𝓞 k) hP)

omit [NumberField k] in
/-- The residue field of the prime of `𝓞 k` under a nonzero prime of `𝓞 L` is finite. -/
private theorem finite_relUnder_res (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    Finite (𝓞 k ⧸ P.under (𝓞 k)) :=
  haveI := finite_res P hP
  .of_injective _ (Ideal.algebraMap_quotient_injective (R := 𝓞 k) (A := 𝓞 L) (I := P))

/-- The residue extension at a nonzero prime of `𝓞 L` is separable over the base. -/
private theorem isSeparable_relRes (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    Algebra.IsSeparable (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 L ⧸ P) := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  haveI := finite_res P hP
  haveI := isMaximal_relUnder (k := k) P hP
  haveI := finite_relUnder_res (k := k) P hP
  infer_instance

variable [IsGalois k L]

/-- **The order of the decomposition group over the base** is the ramification index times the
residue degree. -/
theorem card_relStabilizer (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    Nat.card (MulAction.stabilizer Gal(L/k) P) =
      Ideal.ramificationIdx (algebraMap (𝓞 k) (𝓞 L)) (P.under (𝓞 k)) P *
        (P.under (𝓞 k)).inertiaDeg P := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  haveI := finite_res P hP
  haveI := isMaximal_relUnder (k := k) P hP
  haveI := finite_relUnder_res (k := k) P hP
  haveI := isSeparable_relRes (k := k) P hP
  rw [Ideal.card_stabilizer_eq (G := Gal(L/k)) (P.under (𝓞 k)) (Ideal.under_ne_bot (𝓞 k) hP) P,
    Ideal.ramificationIdxIn_eq_ramificationIdx (P.under (𝓞 k)) P Gal(L/k),
    Ideal.inertiaDegIn_eq_inertiaDeg (P.under (𝓞 k)) P Gal(L/k)]

/-- The inertia group over the base is trivial exactly when the prime is unramified. -/
theorem relInertia_eq_bot_iff_isUnramifiedAt (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    Ideal.inertia Gal(L/k) P = ⊥ ↔ Algebra.IsUnramifiedAt (𝓞 k) P := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  haveI := finite_res P hP
  haveI := isMaximal_relUnder (k := k) P hP
  haveI := finite_relUnder_res (k := k) P hP
  haveI := isSeparable_relRes (k := k) P hP
  rw [Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := 𝓞 k) hP, ← Subgroup.card_eq_one,
    Ideal.card_inertia_eq_ramificationIdxIn (G := Gal(L/k)) (P.under (𝓞 k))
      (Ideal.under_ne_bot (𝓞 k) hP) P,
    Ideal.ramificationIdxIn_eq_ramificationIdx (P.under (𝓞 k)) P Gal(L/k)]

/-- The decomposition group over the base is trivial exactly when the prime is unramified of
residue degree one. -/
theorem relStabilizer_eq_bot_iff (P : Ideal (𝓞 L)) [P.IsPrime] (hP : P ≠ ⊥) :
    MulAction.stabilizer Gal(L/k) P = ⊥ ↔
      Ideal.ramificationIdx (algebraMap (𝓞 k) (𝓞 L)) (P.under (𝓞 k)) P = 1 ∧
        (P.under (𝓞 k)).inertiaDeg P = 1 := by
  rw [← Subgroup.card_eq_one, card_relStabilizer P hP, mul_eq_one]

/-! ### The Frobenius -/

variable (P : Ideal (𝓞 L)) [P.IsPrime] [Finite (𝓞 L ⧸ P)]

/-- The arithmetic Frobenius over the base lies in the decomposition group. -/
theorem relArithFrobAt_mem_stabilizer :
    arithFrobAt (𝓞 k) Gal(L/k) P ∈ MulAction.stabilizer Gal(L/k) P := by
  have H := IsArithFrobAt.arithFrobAt (𝓞 k) Gal(L/k) P
  have key : ∀ x : 𝓞 L, arithFrobAt (𝓞 k) Gal(L/k) P • x ∈ P ↔ x ∈ P := by
    intro x
    conv_lhs => rw [show arithFrobAt (𝓞 k) Gal(L/k) P • x =
      MulSemiringAction.toAlgHom (𝓞 k) (𝓞 L) (arithFrobAt (𝓞 k) Gal(L/k) P) x from rfl,
      ← Ideal.mem_comap, H.comap_eq]
  rw [MulAction.mem_stabilizer_iff]
  ext y
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem,
    ← key ((arithFrobAt (𝓞 k) Gal(L/k) P)⁻¹ • y), smul_inv_smul]

/-- At an unramified prime the arithmetic Frobenius over the base has order the residue degree. -/
theorem orderOf_relArithFrobAt_eq_inertiaDeg (hP : P ≠ ⊥)
    (hunr : Algebra.IsUnramifiedAt (𝓞 k) P) :
    orderOf (arithFrobAt (𝓞 k) Gal(L/k) P) = (P.under (𝓞 k)).inertiaDeg P := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  haveI := isMaximal_relUnder (k := k) P hP
  haveI := finite_relUnder_res (k := k) P hP
  haveI := isSeparable_relRes (k := k) P hP
  letI : Fintype (𝓞 k ⧸ P.under (𝓞 k)) := Fintype.ofFinite _
  have hmem := relArithFrobAt_mem_stabilizer (k := k) P
  have hker : (Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(L/k)).ker = ⊥ := by
    rw [Ideal.Quotient.ker_stabilizerHom,
      (relInertia_eq_bot_iff_isUnramifiedAt (k := k) P hP).mpr hunr]
    simp
  have hinj := (MonoidHom.ker_eq_bot_iff _).mp hker
  have himg : Ideal.Quotient.stabilizerHom P (P.under (𝓞 k)) Gal(L/k)
        ⟨arithFrobAt (𝓞 k) Gal(L/k) P, hmem⟩ =
      FiniteField.frobeniusAlgEquivOfAlgebraic (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 L ⧸ P) := by
    ext x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective x
    have hb := (IsArithFrobAt.arithFrobAt (𝓞 k) Gal(L/k) P).mk_apply b
    rw [Ideal.Quotient.stabilizerHom_apply, show
      (FiniteField.frobeniusAlgEquivOfAlgebraic (𝓞 k ⧸ P.under (𝓞 k)) (𝓞 L ⧸ P))
        (Ideal.Quotient.mk P b) =
        Ideal.Quotient.mk P b ^ Fintype.card (𝓞 k ⧸ P.under (𝓞 k)) from rfl,
      ← Nat.card_eq_fintype_card]
    exact hb
  have h1 : orderOf (arithFrobAt (𝓞 k) Gal(L/k) P) =
      orderOf (⟨arithFrobAt (𝓞 k) Gal(L/k) P, hmem⟩ : MulAction.stabilizer Gal(L/k) P) :=
    (Subgroup.orderOf_mk (H := MulAction.stabilizer Gal(L/k) P) _ hmem).symm
  rw [h1, ← orderOf_injective _ hinj, himg,
    FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic, Ideal.inertiaDeg_algebraMap]

/-- At an unramified prime the decomposition group over the base is the cyclic group generated by
the arithmetic Frobenius. -/
theorem relStabilizer_eq_zpowers_arithFrobAt (hP : P ≠ ⊥)
    (hunr : Algebra.IsUnramifiedAt (𝓞 k) P) :
    MulAction.stabilizer Gal(L/k) P = Subgroup.zpowers (arithFrobAt (𝓞 k) Gal(L/k) P) := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP
  haveI := isMaximal_relUnder (k := k) P hP
  haveI := finite_relUnder_res (k := k) P hP
  haveI := isSeparable_relRes (k := k) P hP
  have hmem := relArithFrobAt_mem_stabilizer (k := k) P
  have hcard : Nat.card (MulAction.stabilizer Gal(L/k) P) = (P.under (𝓞 k)).inertiaDeg P := by
    rw [card_relStabilizer P hP,
      (Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := 𝓞 k) hP).mp hunr, one_mul]
  refine (Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hmem) ?_).symm
  rw [hcard, Nat.card_zpowers, orderOf_relArithFrobAt_eq_inertiaDeg P hP hunr]

end Local

/-! ### Restriction to a normal subextension -/

section Restrict

variable {k L : Type*} [Field k] [Field L] [Algebra k L]
  (E : IntermediateField k L) [Normal k ↥E]

/-- Restricting an automorphism of `L` to a normal subextension is compatible with the inclusion
of the rings of integers. -/
theorem relAlgebraMap_smul_restrictNormal (σ : Gal(L/k)) (x : 𝓞 ↥E) :
    algebraMap (𝓞 ↥E) (𝓞 L) (σ.restrictNormal ↥E • x) = σ • algebraMap (𝓞 ↥E) (𝓞 L) x := by
  apply RingOfIntegers.ext
  show algebraMap (↥E) L ((σ.restrictNormal ↥E • x : 𝓞 ↥E) : ↥E) = σ (algebraMap (↥E) L (x : ↥E))
  rw [← AlgEquiv.restrictNormal_commutes σ ↥E (x : ↥E)]
  rfl

/-- **Restriction sends decomposition into decomposition** over a number-field base. -/
theorem relRestrictNormal_mem_stabilizer (P : Ideal (𝓞 L)) {σ : Gal(L/k)}
    (hσ : σ ∈ MulAction.stabilizer Gal(L/k) P) :
    σ.restrictNormal ↥E ∈ MulAction.stabilizer Gal(↥E/k) (P.under (𝓞 ↥E)) := by
  rw [MulAction.mem_stabilizer_iff] at hσ ⊢
  have hinv : (σ.restrictNormal ↥E)⁻¹ = (σ⁻¹).restrictNormal ↥E :=
    (map_inv (AlgEquiv.restrictNormalHom ↥E : Gal(L/k) →* Gal(↥E/k)) σ).symm
  refine SetLike.ext fun x => ?_
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, hinv]
  show algebraMap (𝓞 ↥E) (𝓞 L) ((σ⁻¹).restrictNormal ↥E • x) ∈ P ↔
    algebraMap (𝓞 ↥E) (𝓞 L) x ∈ P
  rw [relAlgebraMap_smul_restrictNormal E σ⁻¹ x, ← Ideal.mem_pointwise_smul_iff_inv_smul_mem, hσ]

end Restrict

/-! ### Splitting completely and the decomposition group -/

section Split

variable {k L : Type*} [Field k] [NumberField k] [Field L] [NumberField L] [Algebra k L]
  [IsGalois k L]

/-- A prime of `𝓞 L` above a prime of the base that splits completely has trivial decomposition
group. -/
theorem relStabilizer_eq_bot_of_splitsCompletelyIn {v : HeightOneSpectrum (𝓞 k)}
    (hv : SplitsCompletelyIn k L v) (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver v.asIdeal] :
    MulAction.stabilizer Gal(L/k) P = ⊥ := by
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot v.ne_bot P
  have hunder : P.under (𝓞 k) = v.asIdeal :=
    (Ideal.LiesOver.over (A := 𝓞 k) (P := P) (p := v.asIdeal)).symm
  obtain ⟨he, hf⟩ := hv P ⟨inferInstance, inferInstance⟩
  rw [relStabilizer_eq_bot_iff P hP0, hunder]
  exact ⟨he, hf⟩

/-- **A prime of the base splitting completely in the fixed field of a normal subgroup has its
decomposition groups inside that subgroup.** -/
theorem relStabilizer_le_of_splitsCompletelyIn {H : Subgroup Gal(L/k)} [H.Normal]
    [NumberField ↥(IntermediateField.fixedField H)] {v : HeightOneSpectrum (𝓞 k)}
    (hv : SplitsCompletelyIn k ↥(IntermediateField.fixedField H) v)
    (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver v.asIdeal] :
    MulAction.stabilizer Gal(L/k) P ≤ H := by
  set E : IntermediateField k L := IntermediateField.fixedField H with hE
  haveI : (P.under (𝓞 ↥E)).LiesOver v.asIdeal :=
    ⟨by rw [Ideal.under_under]
        exact Ideal.LiesOver.over (A := 𝓞 k) (P := P) (p := v.asIdeal)⟩
  have hbot : MulAction.stabilizer Gal(↥E/k) (P.under (𝓞 ↥E)) = ⊥ :=
    relStabilizer_eq_bot_of_splitsCompletelyIn hv (P.under (𝓞 ↥E))
  intro τ hτ
  have hmem := relRestrictNormal_mem_stabilizer E P hτ
  rw [hbot, Subgroup.mem_bot] at hmem
  have hfix : τ ∈ E.fixingSubgroup := by
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    have hcom := AlgEquiv.restrictNormal_commutes τ ↥E ⟨x, hx⟩
    rw [hmem] at hcom
    simpa using hcom.symm
  rwa [hE, IntermediateField.fixingSubgroup_fixedField] at hfix

/-! ### Realising a subgroup of prime order as a decomposition group -/

/-- **An element of prime order generating a normal subgroup is the decomposition group at
infinitely many primes of the base.**  The primes of `k` splitting completely in the fixed field of
the subgroup it generates but not in `L` are infinite in number, so one of them avoids both a
prescribed finite set and the finitely many primes ramifying in `L`.  At a prime above it where the
splitting fails the decomposition group is contained in the subgroup and nontrivial, and a group of
prime order leaves nothing in between; the arithmetic Frobenius generates the decomposition group
at an unramified prime, so it generates the same group as the element. -/
theorem exists_relStabilizer_eq_zpowers {σ : Gal(L/k)} (hnorm : (Subgroup.zpowers σ).Normal)
    (hp : (orderOf σ).Prime) (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ v : HeightOneSpectrum (𝓞 k), v ∉ T ∧ v ∉ relRamifiedSet k L ∧
      ∃ (P : Ideal (𝓞 L)) (_ : P.IsPrime) (_ : P.LiesOver v.asIdeal) (_ : Finite (𝓞 L ⧸ P)),
        MulAction.stabilizer Gal(L/k) P = Subgroup.zpowers σ ∧
        Subgroup.zpowers (arithFrobAt (𝓞 k) Gal(L/k) P) = Subgroup.zpowers σ := by
  classical
  haveI := hnorm
  have hcardH : Nat.card ↥(Subgroup.zpowers σ) = orderOf σ := Nat.card_zpowers σ
  set E : IntermediateField k L := IntermediateField.fixedField (Subgroup.zpowers σ) with hEdef
  haveI : IsGalois k ↥E := by rw [hEdef]; infer_instance
  haveI : NumberField ↥E := ⟨⟩
  -- the fixed field is a proper subfield
  have hlt : Module.finrank k ↥E < Module.finrank k L := by
    have hmul := Module.finrank_mul_finrank k ↥E L
    have hfr : Module.finrank ↥E L = orderOf σ := by
      rw [hEdef, IntermediateField.finrank_fixedField_eq_card, hcardH]
    rw [hfr] at hmul
    have hpos : 0 < Module.finrank k ↥E := Module.finrank_pos
    have h2 : 2 ≤ orderOf σ := hp.two_le
    nlinarith [hmul, hpos, h2]
  -- a prime splitting completely below but not above, unramified and outside the prescribed set
  obtain ⟨v, ⟨hsplitE, hnsplit⟩, hvT⟩ :=
    (infinite_setOf_splitsCompletelyIn_not_splitsCompletelyIn k ↥E L hlt).exists_notMem_finset
      (T ∪ (finite_relRamifiedSet (k := k) (L := L)).toFinset)
  simp only [Finset.mem_union, not_or] at hvT
  obtain ⟨hvT₁, hvram⟩ := hvT
  have hvram' : v ∉ relRamifiedSet k L := fun h =>
    hvram ((Set.Finite.mem_toFinset (finite_relRamifiedSet (k := k) (L := L))).mpr h)
  -- a prime above it at which the splitting fails
  have hex : ∃ P ∈ v.asIdeal.primesOver (𝓞 L),
      ¬ (Ideal.ramificationIdx (algebraMap (𝓞 k) (𝓞 L)) v.asIdeal P = 1 ∧
        v.asIdeal.inertiaDeg P = 1) := by
    by_contra hc
    refine hnsplit fun P hP => ?_
    by_contra hc2
    exact hc ⟨P, hP, hc2⟩
  obtain ⟨P, ⟨hPprime, hPover⟩, hPne⟩ := hex
  haveI := hPprime
  haveI := hPover
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot v.ne_bot P
  have hunder : P.under (𝓞 k) = v.asIdeal :=
    (Ideal.LiesOver.over (A := 𝓞 k) (P := P) (p := v.asIdeal)).symm
  haveI : Finite (𝓞 L ⧸ P) :=
    haveI : P.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hP0
    inferInstance
  -- the prime is unramified
  have hunr : Algebra.IsUnramifiedAt (𝓞 k) P := by
    refine (Algebra.isUnramifiedAt_iff_of_isDedekindDomain (R := 𝓞 k) hP0).mpr ?_
    rw [hunder]
    by_contra hc
    exact hvram' ⟨P, ⟨hPprime, hPover⟩, hc⟩
  -- the decomposition group is nontrivial
  have hstabne : MulAction.stabilizer Gal(L/k) P ≠ ⊥ := by
    intro hb
    refine hPne ?_
    have := (relStabilizer_eq_bot_iff P hP0).mp hb
    rwa [hunder] at this
  -- and contained in the subgroup
  have hle : MulAction.stabilizer Gal(L/k) P ≤ Subgroup.zpowers σ :=
    relStabilizer_le_of_splitsCompletelyIn (H := Subgroup.zpowers σ) hsplitE P
  have hstabeq : MulAction.stabilizer Gal(L/k) P = Subgroup.zpowers σ := by
    refine Subgroup.eq_of_le_of_card_ge hle ?_
    have hdvd : Nat.card ↥(MulAction.stabilizer Gal(L/k) P) ∣ Nat.card ↥(Subgroup.zpowers σ) :=
      Subgroup.card_dvd_of_le hle
    have h1 : Nat.card ↥(MulAction.stabilizer Gal(L/k) P) ≠ 1 := fun h =>
      hstabne (Subgroup.card_eq_one.mp h)
    rw [hcardH] at hdvd ⊢
    rcases (Nat.Prime.eq_one_or_self_of_dvd hp _ hdvd) with h | h
    · exact absurd h h1
    · omega
  exact ⟨v, hvT₁, hvram', P, hPprime, hPover, inferInstance, hstabeq,
    (relStabilizer_eq_zpowers_arithFrobAt P hP0 hunr).symm.trans hstabeq⟩

/-- **An element of prime order generating a normal subgroup is a power of an arithmetic Frobenius
over the base**, at a prime unramified in `L` and avoiding any prescribed finite set: the Frobenius
lies in the group generated by the element and is nontrivial. -/
theorem exists_relArithFrobAt_mem_zpowers {σ : Gal(L/k)} (hnorm : (Subgroup.zpowers σ).Normal)
    (hp : (orderOf σ).Prime) (T : Finset (HeightOneSpectrum (𝓞 k))) :
    ∃ v : HeightOneSpectrum (𝓞 k), v ∉ T ∧ v ∉ relRamifiedSet k L ∧
      ∃ (P : Ideal (𝓞 L)) (_ : P.IsPrime) (_ : P.LiesOver v.asIdeal) (_ : Finite (𝓞 L ⧸ P)),
        arithFrobAt (𝓞 k) Gal(L/k) P ∈ Subgroup.zpowers σ ∧
        arithFrobAt (𝓞 k) Gal(L/k) P ≠ 1 := by
  obtain ⟨v, hvT, hvram, P, hPprime, hPover, hPfin, -, hgen⟩ :=
    exists_relStabilizer_eq_zpowers hnorm hp T
  refine ⟨v, hvT, hvram, P, hPprime, hPover, hPfin, ?_, ?_⟩
  · rw [← hgen]
    exact Subgroup.mem_zpowers _
  · intro h
    rw [h, Subgroup.zpowers_one_eq_bot] at hgen
    have : Nat.card ↥(Subgroup.zpowers σ) = 1 := by
      rw [← hgen]
      exact Subgroup.card_bot
    rw [Nat.card_zpowers] at this
    exact hp.one_lt.ne' this

end Split

end InverseGalois.CFT
