/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.Cyclotomic.EighthRootSubfield
import InverseGalois.CFT.Cyclotomic.SquareRoots
import InverseGalois.CFT.KroneckerWeber
import InverseGalois.CFT.SqrtSign

/-!
# Where a square root is unramified

A square root of a natural number `n` generates a quadratic field, and the classical theory of
cyclotomic fields pins down exactly where such a field can ramify: only at `2` and at the prime
divisors of `n`.  This file records that bound in the form needed to certify that a prime stays
unramified in the subfield generated by one square root of a block of primes, namely as a subset
statement about `ramifiedSet`.

The bound comes from the cyclotomic square-root construction: inside the cyclotomic subfield of
conductor `8 * n` of an algebraic closure of the rationals every prime divisor of `n` is a square,
hence so is `n`; a square root of `n` in the algebraic closure differs from that one by a sign, so
the field it generates sits inside the cyclotomic subfield, where only the primes dividing
`8 * n` ramify.  Taking the conductor to be a multiple of eight costs nothing here because the
prime `2` is allowed to ramify in the conclusion anyway.

Alongside the ramification bound the file records that the subfield generated by a square root is
normal over the base, which is what lets the inertia subgroup of the ambient Galois group be
compared with the subgroup fixing it.

## Main results

* `InverseGalois.CFT.normal_adjoin_simple_of_sq_eq`: the subfield generated by an element whose
  square lies in the base field is normal over that base field.
* `InverseGalois.CFT.ramifiedSet_adjoin_sqrt_subset`: **a square root of a natural number `n`
  generates a field in which only `2` and the prime divisors of `n` ramify.**

## Tags

square root, quadratic field, ramification, cyclotomic field
-/

namespace InverseGalois.CFT

open IntermediateField NumberField InverseGalois.NumberTheory

/-! ### Normality of a quadratic subfield -/

/-- **The subfield generated by a square root of a base element is normal over the base.** -/
theorem normal_adjoin_simple_of_sq_eq {F L : Type*} [Field F] [Field L] [Algebra F L]
    [Normal F L] {m : F} {y : L} (hy : y ^ 2 = algebraMap F L m) : Normal F ↥F⟮y⟯ := by
  rw [IntermediateField.normal_iff_forall_map_le']
  intro σ
  have hmem : (σ : L →ₐ[F] L) y ∈ F⟮y⟯ := by
    show σ y ∈ F⟮y⟯
    rcases apply_eq_or_eq_neg hy σ with h | h
    · rw [h]; exact IntermediateField.mem_adjoin_simple_self F y
    · rw [h]; exact neg_mem (IntermediateField.mem_adjoin_simple_self F y)
  rw [IntermediateField.adjoin_map, Set.image_singleton]
  exact IntermediateField.adjoin_simple_le_iff.mpr hmem

/-! ### Ramification of a quadratic subfield -/

/-- The prime divisors of eight times a natural number are `2` together with the prime divisors of
that number. -/
theorem primeFactors_eight_mul_subset (n : ℕ) :
    ((8 * n).primeFactors : Set ℕ) ⊆ insert 2 (n.primeFactors : Set ℕ) := by
  intro q hq
  rw [Finset.mem_coe, Nat.mem_primeFactors] at hq
  obtain ⟨hqp, hqd, hne⟩ := hq
  have hn : n ≠ 0 := by rintro rfl; simp at hne
  rcases (Nat.Prime.dvd_mul hqp).mp hqd with h | h
  · left
    have : q ∣ 2 ^ 3 := by simpa using h
    have := (Nat.prime_dvd_prime_iff_eq hqp Nat.prime_two).mp (hqp.dvd_of_dvd_pow this)
    exact this
  · exact Or.inr (Finset.mem_coe.mpr (Nat.mem_primeFactors.mpr ⟨hqp, h, hn⟩))

/-- **Only `2` and the prime divisors of `n` ramify in the field generated by a square root
of `n`.** -/
theorem ramifiedSet_adjoin_sqrt_subset {n : ℕ} (hn : n ≠ 0) {y : AlgebraicClosure ℚ}
    (hy : y ^ 2 = (n : AlgebraicClosure ℚ)) :
    ramifiedSet ↥(ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ))
      ⊆ insert 2 (n.primeFactors : Set ℕ) := by
  haveI : NeZero (8 * n) := ⟨Nat.mul_ne_zero (by norm_num) hn⟩
  haveI : FiniteDimensional ℚ ↥(ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ)) :=
    IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral y)
  haveI : NumberField ↥(ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ)) := ⟨⟩
  -- a square root of `n` inside the cyclotomic subfield of conductor `8 * n`
  obtain ⟨ζ, hζ⟩ := exists_isPrimitiveRoot_of_cycSubfield_le (cycSubfield (8 * n)) le_rfl
  obtain ⟨x, hx⟩ := isSquare_natCast_of_isPrimitiveRoot (K := ↥(cycSubfield (8 * n)))
    (NeZero.ne (8 * n)) hζ ⟨n, rfl⟩ n fun q _ hq => hq.mul_left 8
  -- it differs from `y` by a sign, so `y` lies in that cyclotomic subfield
  have hX : ((x : AlgebraicClosure ℚ)) ^ 2 = (n : AlgebraicClosure ℚ) := by
    have := congrArg (fun z : ↥(cycSubfield (8 * n)) => (z : AlgebraicClosure ℚ)) hx
    push_cast at this
    rw [this]
    ring
  have hfac : (y - (x : AlgebraicClosure ℚ)) * (y + (x : AlgebraicClosure ℚ)) = 0 := by
    linear_combination hy - hX
  have hymem : y ∈ cycSubfield (8 * n) := by
    rcases mul_eq_zero.mp hfac with h | h
    · rw [sub_eq_zero.mp h]; exact x.2
    · rw [eq_neg_of_add_eq_zero_left h]; exact neg_mem x.2
  have hle : (ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ)) ≤ cycSubfield (8 * n) :=
    IntermediateField.adjoin_simple_le_iff.mpr hymem
  letI : Algebra ↥(ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ)) ↥(cycSubfield (8 * n)) :=
    (IntermediateField.inclusion hle).toRingHom.toAlgebra
  refine (ramifiedSet_subset ↥(ℚ⟮y⟯ : IntermediateField ℚ (AlgebraicClosure ℚ))
    ↥(cycSubfield (8 * n))).trans ?_
  exact (ramifiedSet_subset_primeFactors (8 * n) ↥(cycSubfield (8 * n))).trans
    (primeFactors_eight_mul_subset n)

end InverseGalois.CFT
