/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import InverseGalois.CFT.InertiaTameLevel

/-!
# A decomposition group in an infinite extension, read through an open subgroup

The decomposition group at a prime of an infinite extension is not generated by two elements, but
its image under a homomorphism with open kernel is, once the homomorphism kills nothing but
`ℓ`-power torsion there and the prime is away from `ℓ`.

Read at a finite level over the rationals inside the kernel, the decomposition group maps to the
Galois group of the residue field extension, a finite cyclic group; one element of the
decomposition group upstairs accounts for every value there, and that is one of the two generators.
What is left is the part of the decomposition group whose restriction to the level lies in inertia,
and there the tame character — again a character of a cyclic group — is accounted for by a single
element, the other generator; whatever the tame character does not see restricts to an element of
order a power of the residue characteristic, so it has both an `ℓ`-power order and a prime-to-`ℓ`
order downstairs, and is therefore killed.

The same argument bounds the image of the inertia subgroup on the nose: inertia restricts into
inertia, so the whole of it is carried by the second generator alone.

## Main results

* `InverseGalois.CFT.mem_stabilizer_iff_forall_smul_mem_iff`: an automorphism stabilises an ideal
  exactly when it preserves membership in it elementwise.
* `InverseGalois.CFT.restrictNormal_mem_stabilizer_of_forall`: restriction to a normal
  subextension maps the decomposition group of a prime into the decomposition group of the prime
  below it.
* `InverseGalois.CFT.exists_two_generators_map_stabilizer`: **the image of a decomposition group
  under a homomorphism with open kernel and `ℓ`-power torsion values is generated by two elements
  at a prime away from `ℓ`**, one of which already carries the image of inertia.

## Tags

decomposition group, inertia subgroup, tame character, residue field, Krull topology
-/

namespace InverseGalois.CFT

open IsDedekindDomain MulAction NumberField

open scoped Pointwise

set_option synthInstance.maxHeartbeats 400000

/-! ### Stabilising an ideal, elementwise -/

/-- **An automorphism stabilises an ideal exactly when it preserves membership in it
elementwise.** -/
theorem mem_stabilizer_iff_forall_smul_mem_iff {G R : Type*} [Group G] [CommRing R]
    [MulSemiringAction G R] {P : Ideal R} {σ : G} :
    σ ∈ MulAction.stabilizer G P ↔ ∀ x : R, σ • x ∈ P ↔ x ∈ P := by
  constructor
  · intro hσ x
    rw [MulAction.mem_stabilizer_iff] at hσ
    exact ⟨fun h => Ideal.smul_mem_pointwise_smul_iff.1 (hσ ▸ h),
      fun h => hσ ▸ Ideal.smul_mem_pointwise_smul _ _ _ h⟩
  · intro key
    rw [MulAction.mem_stabilizer_iff]
    ext y
    rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, ← key (σ⁻¹ • y), smul_inv_smul]

section Base

variable {k N : Type*} [Field k] [Field N] [Algebra k N]

/-- **Restriction sends decomposition into decomposition.**  If `σ` preserves membership in a prime
`P` of `𝓞 N` elementwise, then its restriction to a normal subextension `A` stabilises the prime of
`𝓞 A` lying under `P`. -/
theorem restrictNormal_mem_stabilizer_of_forall (A : IntermediateField k N) [Normal k ↥A]
    (P : Ideal (𝓞 N)) {σ : Gal(N/k)} (hσ : ∀ x : 𝓞 N, σ • x ∈ P ↔ x ∈ P) :
    σ.restrictNormal ↥A ∈ MulAction.stabilizer Gal(↥A/k) (P.under (𝓞 ↥A)) := by
  refine mem_stabilizer_iff_forall_smul_mem_iff.2 fun x => ?_
  show algebraMap (𝓞 ↥A) (𝓞 N) (σ.restrictNormal ↥A • x) ∈ P ↔ algebraMap (𝓞 ↥A) (𝓞 N) x ∈ P
  rw [algebraMap_smul_restrictNormal A σ x]
  exact hσ _

end Base

/-! ### Two generators for the image of a decomposition group -/

section Main

variable {K Ω : Type*} [Field K] [NumberField K] [Field Ω] [Algebra K Ω] [IsGalois K Ω]
  [IsAlgClosed Ω]

attribute [local instance] Ideal.Quotient.field

set_option synthInstance.maxHeartbeats 800000 in
set_option maxHeartbeats 1600000 in
/-- **The image of a decomposition group under a homomorphism with open kernel is generated by two
elements**, at a prime away from an exponent whose powers kill the image.

At a finite Galois level over the rationals inside the kernel, the decomposition group maps to the
Galois group of the residue extension, a finite cyclic group, and one element `σ` of the
decomposition group accounts for every value there.  What is left restricts into the inertia group
of the level, where the tame character is again accounted for by a single element `τ`; and what the
tame character does not see restricts to an element of order a power of the residue characteristic,
so its image has order prime to the exponent as well as a power of it, and is trivial.  Inertia
restricts into inertia, so its whole image is carried by `τ` alone. -/
theorem exists_two_generators_map_stabilizer {ℓ : ℕ} {G : Type*} [Group G]
    (P : Ideal (𝓞 Ω)) [P.IsPrime] (hP : P ≠ ⊥) (hℓP : (ℓ : 𝓞 Ω) ∉ P)
    {f : Gal(Ω/K) →* G} (hf : IsOpen ((f.ker : Subgroup Gal(Ω/K)) : Set Gal(Ω/K)))
    (hpg : ∀ x ∈ MulAction.stabilizer Gal(Ω/K) P, ∃ b : ℕ, f x ^ ℓ ^ b = 1) :
    ∃ τ ∈ MulAction.stabilizer Gal(Ω/K) P, ∃ σ ∈ MulAction.stabilizer Gal(Ω/K) P,
      (∀ x ∈ Ideal.inertia Gal(Ω/K) P, f x ∈ Subgroup.zpowers (f τ)) ∧
        ∀ x ∈ MulAction.stabilizer Gal(Ω/K) P, ∃ i q : ℤ, f x = f τ ^ i * f σ ^ q := by
  haveI : CharZero Ω := charZero_of_injective_algebraMap (algebraMap K Ω).injective
  obtain ⟨M, hMfin, hMgal, hMN⟩ := exists_rationalLevel_forall_smul_eq (K := K) hf
  haveI := hMfin
  haveI := hMgal
  haveI : NumberField ↥M := NumberField.of_module_finite ℚ ↥M
  set w : Ideal (𝓞 ↥M) := Ideal.under (𝓞 ↥M) P with hwdef
  haveI : w.IsPrime := Ideal.IsPrime.under _ P
  have hwbot : w ≠ ⊥ := Ideal.under_ne_bot (𝓞 ↥M) hP
  haveI := isMaximal_of_ne_bot w hwbot
  haveI := finite_quotient_of_ne_bot w hwbot
  haveI := isMaximal_under_of_ne_bot w hwbot
  haveI := finite_quotient_under_of_ne_bot w hwbot
  obtain ⟨π, hπ⟩ := exists_isUniformizer hwbot
  -- restriction to the level, as a homomorphism of Galois groups
  set rs : Gal(Ω/K) →* Gal(↥M/ℚ) :=
    (AlgEquiv.restrictNormalHom ↥M).comp
      ({ toFun := fun σ => σ.restrictScalars ℚ, map_one' := rfl,
         map_mul' := fun _ _ => rfl } : Gal(Ω/K) →* Gal(Ω/ℚ)) with hrsdef
  have hrsapp : ∀ σ : Gal(Ω/K), rs σ = (σ.restrictScalars ℚ).restrictNormal ↥M := fun _ => rfl
  have hfrs : ∀ x : Gal(Ω/K), rs x = 1 → f x = 1 := by
    intro x hx
    refine MonoidHom.mem_ker.1 (hMN x fun t => ?_)
    have hcom := AlgEquiv.restrictNormal_commutes (x.restrictScalars ℚ) (↥M) t
    rw [show (x.restrictScalars ℚ).restrictNormal ↥M = 1 from hx, AlgEquiv.one_apply] at hcom
    exact hcom.symm
  set D : Subgroup Gal(Ω/K) := MulAction.stabilizer Gal(Ω/K) P with hDdef
  have hrsD : ∀ x : ↥D, rs ((x : Gal(Ω/K))) ∈ MulAction.stabilizer Gal(↥M/ℚ) w := by
    intro x
    rw [hrsapp]
    exact restrictNormal_mem_stabilizer_of_forall M P
      (σ := ((x : Gal(Ω/K)).restrictScalars ℚ))
      (fun y => mem_stabilizer_iff_forall_smul_mem_iff.1 x.2 y)
  -- the Galois group of the residue extension at the level
  set p₀ : Ideal ℤ := Ideal.under ℤ w with hp₀def
  haveI : Finite ((𝓞 ↥M ⧸ w) ≃ₐ[ℤ ⧸ p₀] (𝓞 ↥M ⧸ w)) :=
    Finite.of_injective (fun e => (e : (𝓞 ↥M ⧸ w) → (𝓞 ↥M ⧸ w))) DFunLike.coe_injective
  set rsD : ↥D →* ↥(MulAction.stabilizer Gal(↥M/ℚ) w) :=
    MonoidHom.codRestrict (rs.comp D.subtype) _ hrsD with hrsDdef
  set T : ↥D →* ((𝓞 ↥M ⧸ w) ≃ₐ[ℤ ⧸ p₀] (𝓞 ↥M ⧸ w)) :=
    (Ideal.Quotient.stabilizerHom w p₀ Gal(↥M/ℚ)).comp rsD with hTdef
  have hkerT : ∀ x : ↥D, T x = 1 ↔ rs ((x : Gal(Ω/K))) ∈ Ideal.inertia Gal(↥M/ℚ) w := by
    intro x
    rw [hTdef]
    show (Ideal.Quotient.stabilizerHom w p₀ Gal(↥M/ℚ)) (rsD x) = 1 ↔ _
    rw [← MonoidHom.mem_ker, Ideal.Quotient.ker_stabilizerHom, Subgroup.mem_subgroupOf]
    rfl
  -- the residue characteristic is prime to the exponent
  set p := ringChar (𝓞 ↥M ⧸ w) with hpdef
  haveI : CharP (𝓞 ↥M ⧸ w) p := ringChar.charP _
  have hpprime : p.Prime := CharP.char_is_prime (𝓞 ↥M ⧸ w) p
  have hpn : ¬ p ∣ ℓ := by
    intro hdvd
    refine hℓP ?_
    have h0 : ((ℓ : 𝓞 ↥M) : 𝓞 ↥M ⧸ w) = 0 := by
      rw [map_natCast]
      exact (CharP.cast_eq_zero_iff (𝓞 ↥M ⧸ w) p ℓ).2 hdvd
    have hmem : (ℓ : 𝓞 ↥M) ∈ w := Ideal.Quotient.eq_zero_iff_mem.1 h0
    have := Ideal.mem_comap.1 (hwdef ▸ hmem)
    rwa [map_natCast] at this
  have hcop : Nat.Coprime p ℓ := (Nat.Prime.coprime_iff_not_dvd hpprime).2 hpn
  -- what restricts into inertia at the level
  have hJI : ∀ y : ↥(T.ker), rs (((y : ↥D) : Gal(Ω/K))) ∈ Ideal.inertia Gal(↥M/ℚ) w :=
    fun y => (hkerT _).1 y.2
  set ρJ : ↥(T.ker) →* ↥(Ideal.inertia Gal(↥M/ℚ) w) :=
    MonoidHom.codRestrict ((rs.comp D.subtype).comp (T.ker).subtype) _ hJI with hρJdef
  obtain ⟨g, hg⟩ := exists_forall_mul_pow_inv_mem_ker ((tameChar hπ).comp ρJ)
  obtain ⟨s, hs⟩ := exists_forall_mul_pow_inv_mem_ker T
  set τ : Gal(Ω/K) := ((g : ↥D) : Gal(Ω/K)) with hτdef
  set s' : Gal(Ω/K) := (s : Gal(Ω/K)) with hs'def
  have hkey : ∀ y : ↥(T.ker), f (((y : ↥D) : Gal(Ω/K))) ∈ Subgroup.zpowers (f τ) := by
    intro y
    obtain ⟨j, hj⟩ := hg y
    set z : ↥(T.ker) := y * (g ^ j)⁻¹ with hzdef
    obtain ⟨a, ha⟩ := exists_orderOf_eq_ringChar_pow hπ hj
    have hzz : rs (((z : ↥D) : Gal(Ω/K))) ^ p ^ a = 1 := by
      rw [← ha]
      exact pow_orderOf_eq_one _
    have hfz : f (((z : ↥D) : Gal(Ω/K))) ^ p ^ a = 1 := by
      rw [← map_pow]
      exact hfrs _ (by rw [map_pow]; exact hzz)
    obtain ⟨b, hb⟩ := hpg (((z : ↥D) : Gal(Ω/K))) (z : ↥D).2
    have h1 : orderOf (f (((z : ↥D) : Gal(Ω/K)))) ∣ p ^ a := orderOf_dvd_of_pow_eq_one hfz
    have h2 : orderOf (f (((z : ↥D) : Gal(Ω/K)))) ∣ ℓ ^ b := orderOf_dvd_of_pow_eq_one hb
    have hgcd : orderOf (f (((z : ↥D) : Gal(Ω/K)))) ∣ 1 := by
      have hd := Nat.dvd_gcd h1 h2
      rwa [Nat.Coprime.gcd_eq_one (Nat.Coprime.pow _ _ hcop)] at hd
    have hfz1 : f (((z : ↥D) : Gal(Ω/K))) = 1 :=
      orderOf_eq_one_iff.1 (Nat.dvd_one.1 hgcd)
    have hy : y = z * g ^ j := by
      rw [hzdef]
      group
    rw [hy]
    have hcoe : (((z * g ^ j : ↥(T.ker)) : ↥D) : Gal(Ω/K))
        = (((z : ↥D) : Gal(Ω/K))) * τ ^ j := by
      simp [hτdef]
    rw [hcoe, map_mul, map_pow, hfz1, one_mul]
    refine ⟨(j : ℤ), ?_⟩
    show (f τ) ^ (j : ℤ) = (f τ) ^ j
    exact zpow_natCast _ _
  refine ⟨τ, (g : ↥D).2, s', s.2, ?_, ?_⟩
  · intro x hx
    have hxD : x ∈ D := Ideal.inertia_le_stabilizer P hx
    have hxker : (⟨x, hxD⟩ : ↥D) ∈ T.ker := by
      rw [MonoidHom.mem_ker, hkerT ⟨x, hxD⟩, hrsapp]
      exact restrictNormal_mem_inertia M P (fun y => hx y)
    exact hkey ⟨⟨x, hxD⟩, hxker⟩
  · intro x hx
    obtain ⟨j, hj⟩ := hs ⟨x, hx⟩
    have hmem : ((⟨x, hx⟩ : ↥D) * (s ^ j)⁻¹) ∈ T.ker := MonoidHom.mem_ker.2 hj
    obtain ⟨i, hi⟩ := hkey ⟨_, hmem⟩
    refine ⟨i, (j : ℤ), ?_⟩
    simp only [Subgroup.coe_mul, Subgroup.coe_pow, InvMemClass.coe_inv, _root_.map_mul,
      _root_.map_inv, _root_.map_pow] at hi
    rw [hs'def, hi, zpow_natCast]
    group

end Main

end InverseGalois.CFT
